### ISSUE TITLE
Autoincrement in multithread action

### ISSUE THREAD

**Issue by ugendrang** [realm/realm-js#1001]
As there is no autoincrement in Realm, what is the best approach to follow for the following scenario,

Developing an app in ReactNative and Realm. App will receive bunch of data from third party api and also user can input set of data via UI which need to store in Realm DB with 'Batch' insert (assume api calls and UI inserts are performing at same interval of time). If the data need to be insert with Batch insert in 'multithread' or 'asyncronous' action, what approach should follow to autoincrement the reference_id, so that the refrerence_id will not be duplicate and will maintain the unique value.

**Comment by blagoev** [comment]
At the moment Realm does not support autoincremented ids.

**Comment by ugendrang** [comment]
@blagoev, i am aware that realm not supports autoincrement ids. Hence i am using V1 uuid ("uuid": "^3.0.1") to generate autoincrement id. Since my app runs in multi thread, i worried about duplicate key generation. Is there any plan to support autoincrement ids in Realm?

**Comment by blagoev** [comment]
There are no immediate plans on supporting auto incremented ids in the near term. This does not mean we wont provide such support in the future. Using uuid should be pretty safe and duplicates should be very rare
