### ISSUE TITLE
Can I use the data saved via realm-js in react in Android native?

### ISSUE THREAD

**Issue by HannanShaik** [realm/realm-js#1011]
Hi Guys,

I have saved some realm objects via `realm-js` in react native. Now I have a native android screen that wants to consume the data. Is it possible directly just by using the regular way of fetching data.

```
Realm realm = Realm.getDefaultInstance();
return realm.where(<<what to give here>>).findAll();
```

**Comment by kristiandupont** [comment]
You should be, yes. Be aware that you need to make sure the versions of Realm you use need to be compatible, the release schedule is not always 1:1.

You could either recreate your schema in Java and use the proper class name or you could use a [DynamicRealm](https://realm.io/docs/java/3.1.4/api/io/realm/DynamicRealm.html) and reference your model with a string.

**Comment by blagoev** [comment]
closing this as answered
