### ISSUE TITLE
React Native realm error when generating apk file

### ISSUE THREAD

**Issue by roman2710** [realm/realm-js#1012]
When I try to generate the apk file for react native android app I get the following error 

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/Users/roman/Documents/Coding/Quotes/default.realm.note'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by fealebenpae** [comment]
You can safely delete the `realm.note` file - it's a remnant of improper cleanup (likely the app force-closed while the realm was still open).

**Comment by roman2710** [comment]
Thanks that did it
