### ISSUE TITLE
Performance issues with ListView

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1013]
I am using a StackNavigator and clicking from a main menu screen into a screen with a Realm ListView. The data soure is a Realm found set resulting from a query of all objects. The result set has about 100 items. I am noticing two performance issues:

1. When I go to the screen containing the ListView and try to scroll right away there is a slight lag between clicking on the screen and being able to scroll. If a pause for one second and then click it is responsive. 

2. If I try to use the back button to return to the previous screen there is a several seconds lag before it becomes resposive. If I click on the button as soon as the ListView loads it accepts the mouse down but lags before it loads the previous screen. If I just wait a few seconds after the ListView screen loads and then click the back button it is instantly responsive. 

Both of these issues go away if I filter my data soruce to only have five entries insteed of 100.

Screen Recording: https://www.dropbox.com/s/xi2q6a4dlap8o21/Lag.mov?dl=0

**Comment by agersoncgps** [comment]
Retracted! Found an issue in my code. It is mostly a performance hit having to do with my generating of the section headers. Witht that removed I noticed only a slight version of this, perfectly within the range of acceptable. I will work on opotizeing my section header generation.

**Comment by blagoev** [comment]
Closing this. Glad you resolved it.
