### ISSUE TITLE
Realm react native updates don't work as expected

### ISSUE THREAD

**Issue by roman2710** [realm/realm-js#1014]
I am trying to update many realm objects at once using es6 for of loop. Here is my code.

```
let result = quotesRealm.objects('Quote').filtered('saved = true');
    let results = result.values();
    if (result.length !== undefined) {
        quotesRealm.write(() => {
            for (let quote of results) {
                quotesRealm.create('Quote', {
                    id: quote.id,
                    saved: false
                }, true);
            }
        });
    }
```

But the code only updates 3 objects if there are totally 6 objects in results. It updates 3 when there are 5 objects in results. When there are 2 objects it updates only one object. Is this a bug?

**Comment by kristiandupont** [comment]
You should invoke the [snapshot](https://realm.io/docs/javascript/1.2.0/api/Realm.Collection.html#snapshot) method on your `result` so it doesn't mutate while you are iterating over it.

**Comment by roman2710** [comment]
Yes it works alright now, thanks for the quick response

**Comment by sanjeevraolade** [comment]
Update does not work with **undefined**, so instead undefined, make use of **null**, it will work

**Comment by sexybells** [comment]
can you show me your code after fix?
