### ISSUE TITLE
Error: [object RealmObject]: Invalid predicate

### ISSUE THREAD

**Issue by ugendrang** [realm/realm-js#1022]
Kindly suggest how to filter query by RealmObject.
`class Person {}
Person.schema = {
  name: 'Person',
  properties: {
    name: {type:'string'},
    subCategories: {type: 'list', objectType: 'Parent', default: []},
  }
};

class Parent {}
Parent.schema = {
  name: 'Parent',
  properties: {
    name: {type:'string'},
    person: 'Person'  //backlink
  }
};	`

Arguments passed to the below function are 'name'(string) and 'person'(RealmObject). (Person name and Parent name can have duplicate values, so i thought to filter the query with RealmObject to fetch exact record)
export const findSubCategory = (person, name) => {
const categories = realm.objects('Parent').filtered('name = "'+name+'" AND person = '+person);
}

On executing the query, end up with following error  "name = 'xyx' and person = [object RealmObject]: Invalid predicate".

**Comment by blagoev** [comment]
You can not construct a filter with RealmObject directly. What you could do is filter using it's properties like
.filtered('name = "'+name+'" AND person.name = '+person.name);
