### ISSUE TITLE
Build error from undefined symbols

### ISSUE THREAD

**Issue by kevinnguy** [realm/realm-js#1024]
Not sure why I'm getting this error suddenly. Seems like the library isn't linking CocoaLumberjack but I'm not sure. Has anyone had this issue before? 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in libRealmReact.a(GCDWebServerMultiPartFormRequest.o)
      objc-class-ref in libRealmReact.a(GCDWebServerFileResponse.o)
      objc-class-ref in libRealmReact.a(GCDWebServerConnection.o)
      objc-class-ref in libRealmReact.a(GCDWebServerRequest.o)
      objc-class-ref in libRealmReact.a(GCDWebServer.o)
      objc-class-ref in libRealmReact.a(GCDWebServerFunctions.o)
ld: symbol(s) not found for architecture x86_64
```

I am on `realm: 1.3.0`

**Comment by kevinnguy** [comment]
Had to remove my `DerivedData` and `build` directories to fix this bug.

**Comment by haiifeng** [comment]
and i could not find out witch biuld directories, could you please tell me ?

**Comment by v-ken** [comment]
Few things that may help:

1. Remove project's DerivedData (File > Project Settings > Open DerivedData location)
2. Check that you are using a compatible React Native version with your Realm version - https://github.com/realm/realm-js/releases (Look for the last "Add support for React Native vX.XX")
3. `react-native unlink realm` and `react-native link realm`
