### ISSUE TITLE
Running Atom / Nuclide debugger causes "Unknown execution context" error

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1025]
![screenshot 2017-05-17 19 44 25](https://cloud.githubusercontent.com/assets/336441/26180754/40dc4c98-3b39-11e7-8601-2b9d580e4ae0.png)

It only happens when I am debugging with Nuclide debugger. Works fine with dubugging off and when dubugging routed through Chrome.

Do you have a handler for Atom / Nuclide debugging in:
https://github.com/realm/realm-js/blob/master/lib/index.js#L57-L60

I have aldreay run:
```
$ react-native link realm
Scanning 629 folders for symlinks in /Users/user/Desktop/CGPSApp/node_modules (8ms)
rnpm-install info Android module realm is already linked
rnpm-install info iOS module realm is already linked
```

**Comment by agersoncgps** [comment]
Duplicate of: https://github.com/realm/realm-js/issues/362

**Comment by chrise86** [comment]
I'm getting this issue when running on device, even with debugging turned off :(

**Comment by pbwei** [comment]
i have the same issue

**Comment by bmunkholm** [comment]
Nuclide is not a thing anymore, so closing.
