### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1026]
I posted this question to [StackOverflow](http://stackoverflow.com/questions/44013746/realm-how-to-get-the-properties-of-a-realted-object-inside-a-custom-row-compona), but the Realm tag does not appear to have a lot of answers on questions. I am really stuck on this and I am unable to proceed with my app until I can access related record data in my components. Any help is greatly appreciated. 

I have two Realm schemas defined. A student can have a list of parents.

```
const StudentSchema = {
      name: "Student",
      primaryKey: "id",
      properties: {
        id: "string", // primary key
        bb_first_name: "string",
        bb_last_name: "string",
        bb_current_grade: "string",
        bb_class_of: "string",
        DirectoryentryDisplay: "string",
        parents: {type: 'list', objectType: 'Parent'},
      }
    };

    const ParentsSchema = {
      name: "Parent",
      primaryKey: "id",
      properties: {
        id: "string", // primary key
        bb_first_name: "string",
        bb_last_name: "string",
        student_id: "string",
      }
    };
```

Inside of a custom componant for a Realm ListView row I am passing a Realm ListView DataSource which is a result set of a students, they end up in the row as a props:

```
<Text style={styles.text}>
            {`${this.props.bb_first_name} ${this.props.bb_last_name}`}
            {this.props.parents}
          </Text>
```

I am able to access properites of the student such as this.props.bb_first_name with no problems. However, I have tried everythig I can think of to access the parent data such as:

`{this.props.parents[0].bb_first_name} `

and it always comes back as undefined. However, this.props.parents.length returns a number and this.props.parents logs as "Object". So I know I have data in there. In fact when I create the Realm I check to make sure students have parent data:

```
this.realm.write(() => {
      //for (let i = 0; i < data.length - 1; ++i) {
      for (let i = 0; i < data.length; ++i) {
        let parents = this.realm.objects("Parent").filtered('student_id = "' + data[i].kp_ID + '"');
        this.realm.create(
          "Student",
          {
            id: data[i].kp_ID,
            bb_first_name: data[i].bb_first_name,
            bb_last_name: data[i].bb_last_name,
            bb_current_grade: data[i].bb_current_grade,
            bb_class_of: data[i].bb_class_of,
            DirectoryentryDisplay: data[i].DirectoryentryDisplay,
            parents: parents
          },
          true
        );
      }
    });
    let parents = this.realm.objects("Student")[0].parents
    console.log(parents[0].bb_first_name);
```

The final console.log does in fact print a prent's first name so I know the data is in there. This is what I tried next:

```
let parents = Array.from(this.props.parents);
let parentOne = parents[0]
let parentOneFirstName = parentOne.bb_first_name
console.log("name: " + parentOneFirstName);
```
parents is an array of RealmObjects. 

How can 

`let parentOneFirstName = parentOne.bb_first_name`

Produce the error:

`Cannot read property 'bb_first_name' of undefined`

when

`console.log("name: " + parentOneFirstName);`

prints out:

`name: Barry`

When I inspect parentOne in the console it clearly has a bb_first_name property.

**Comment by blagoev** [comment]
How this code gets to the console.log("name: " + parentOneFirstName); when the
```let parentOneFirstName = parentOne.bb_first_name```

throws an error.
Can you please describe what happens which statement is working and which not. Or is the one working when you evaluate it in the debugger console. The above sample code is little bit confusing.

cheers

**Comment by agersoncgps** [comment]
I bleive I figured it out. Thank you for looking into it. The List was looping over the data source wich was missing one "parent" and produced the error. Thanks for your help.

**Comment by blagoev** [comment]
glad its working. closing it
