### ISSUE TITLE
Looking for a smaller Realm library

### ISSUE THREAD

**Issue by yeswanth** [realm/realm-js#1029]
Hi, 
I am using Realm with React-Native and I see that librealmreact.so file occupies 2.3 mb (almost 33% of my apk size). I have abi splits & proguard enabled in my project. So, this is the size of the library in armeabi-v7a apk. 

I want to know how I can reduce the realm library's size in my apk. Are there others ways to do it, than what I already explored(proguard and abi splits)?

I only use Realm as a Object Database and don't use advance features like Sync. 
Is it possible to have a Realm library version with just the object database feature? 

Thanks in advance.

**Comment by blagoev** [comment]
Apart from what you are doing there is not much else you can do to reduce the apk size at the moment.

**Comment by blagoev** [comment]
closing this issue since no further information can be provided
