### ISSUE TITLE
Remote debugger connection always failed with VSCode when using realm-js

### ISSUE THREAD

**Issue by gen0083** [realm/realm-js#1035]
## Goals

Be able to debag using VSCode

## Expected results

There are no error when run debug with VSCode.

## Actual results

Got error below:

debug console in VSCode:

```console
[vscode-react-native] Debugger worker loaded runtime on port 3615
Unknown named module: './submit-analytics'
Module AppRegistry is not a registered callable module (calling runApplication)
```

Android device:

![tryvscode-mainactivity-05272017203803](https://cloud.githubusercontent.com/assets/7608725/26521676/4d0fcdda-4329-11e7-9eb4-61fc231a6ece.png)

it is same as #873 

## Steps to reproduce

1. create react native project `react-native init Test`
1. open project with VSCode
1. edit `.babelrc` and add dubug setting `launch.js` with React Native Tool
1. run debug(shotcut key `F5`) works expectedly at this point
1. install realm `npm install realm --save`
1. setup realm in react native project `react-native link realm`
1. add realm sample code from installation document of realm (see below sample)
1. run debug then get error: `Unknown named module: './submit-analytics'`

I can run debug this project with WebStorm, but cannot run debug with VSCode, always get above error.
Without debugger, `react-native run-android` was works correctly.
That means that data insertion was successful and count-up correctly every time of launching the app.

## Code sample that highlights the issue (full Xcode / Android Studio projects that we can compile ourselves are ideal)

index.android.js:

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Realm from 'realm';

export default class TryVsCode extends Component {
  render() {
    const realm = new Realm({
      schema: [{name: 'Dog', properties: {name: 'string'}}]
    });

    realm.write(() => {
      realm.create("Dog", {name: "a"});
    });

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          Dog length = {realm.objects("Dog").length}
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
          fugafuga
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TryVsCode', () => TryVsCode);
```

Sample project here <https://github.com/gen0083/TryVsCode>

## Version of Realm / Xcode/ Android Studio/ OSX/ WIN

OS: Mac
VSCode 1.12.2
React Native Tool(Extension in VSCode) 0.3.2
React Native 0.44.2
Node.js 7.10.0
npm 4.6.1

**Comment by blagoev** [comment]
we will be looking into this. 
as a workaround for now you may try using this one
https://github.com/realm/realm-js/commit/3764d4bf55ee604b2fdd3f02eb6a3e25dd0b07fd

**Comment by gen0083** [comment]
thanks @blagoev 
I'm trying the workaround and it works fine :)

**Comment by blagoev** [comment]
There is a PR for this now https://github.com/realm/realm-js/pull/1062
