### ISSUE TITLE
Installation fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by nnrealm** [realm/realm-js#1036]
On Ubuntu 16.04 LTS, NodeJS is installas /usr/bin/nodejs. This makes the installation command fail since node-pre-gyp as well as some commands in package.json expect to find the command "node" in PATH.

**Comment by blagoev** [comment]
Seems like missing node command is considered broken system in node-pre-gyp 
https://github.com/mapbox/node-pre-gyp/pull/45#issuecomment-39373305

the guidance is to use 
```apt-get install nodejs-legacy```

**Comment by nnrealm** [comment]
We should maybe update docs? Debian-based platforms make up a lot of Linux developer machines and the user facing docs just say to run "npm install --save realm", which fails.

https://realm.io/docs/javascript/latest/

**Comment by nnrealm** [comment]
Update: Adding the Nodesource repository to Ubuntu 16.04 and installing the 'nodejs' package from there results in an up-to-date Node and NPM installation whichs work correctly with Realm JS.

https://github.com/nodesource/distributions#deb

**Comment by blagoev** [comment]
Awesome. should I close this?
