### ISSUE TITLE
Is Realm Does not work for Node version 8.0.0

### ISSUE THREAD

**Issue by emrehayirci** [realm/realm-js#1042]
Hi,
I updated my Node version than started a new project. When i "npm install realm" i got that error: 
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/r
ealm-v1.3.1-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.3.1 and node@8.0.0 (n
ode-v57 ABI) (falling back to source compile with node-gyp)

```
How can i solve this?
Thanks

**Comment by emrehayirci** [comment]
How can i make this installation that npm install realm could use a working link like `https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v51-win32-x64.tar.gz`

**Comment by emrehayirci** [comment]
After reading through node-gyp docs i found out that --target parameter does what am i trying to do. so i ran npm install --save realm --target=7.10.0 and it installed flawlessly.

**Comment by tonylinyy** [comment]
it works 
thanks
