### ISSUE TITLE
Losing track of compiled binaries

### ISSUE THREAD

**Issue by Bogidon** [realm/realm-js#1044]
Frequently when I use realm-js in a node environment I get this error:

```
Error: Cannot find module '/__/node_modules/realm/compiled/node-v51_darwin_x64/realm.node'
```

Sometimes, the error refers to `node-v57_darwin_x64` instead.

Usually when this happens the `compiled` folder is missing entirely. Forcing Yarn to reinstall realm-js will recompile(?) the binary and fix the problem. 

I apologize for not having more details or a reproducible example at the moment. I'm not quite sure how to diagnose. In any case, the fault might be outside of realm-js, such as in yarn. I'll update this ticket if I find more information.

|||
|-|-|
| macOS |10.12.5 |
|node | 8.0.0 | 
|yarn | v0.24.6 |
|realm-js|^1.3.1, resolved to 1.3.1|

**Comment by blagoev** [comment]
Since its not clear this is from realm and we can't reproduce it I suggest to close this and reopen it maybe in the future.

**Comment by Bogidon** [comment]
Will do. If in the future someone else experiences this issue they'll at least now have a place to post to.

**Comment by Daopr** [comment]
I cannot figure how it happens, but it did
