### ISSUE TITLE
'Property' must be of type: string error thrown for Object properties

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1045]
I am trying to use an object as a property in a schema as explained in the [docs](https://realm.io/docs/javascript/latest/#object-properties). 

I would like to insert a reference to a Student into my DirectoryFavorites

```
const StudentSchema = {
      name: "Student",
      primaryKey: "id",
      properties: {
        id: "string", // primary key
        bb_first_name: "string",
        bb_last_name: "string",
        bb_current_grade: "string",
        bb_class_of: "string",
        DirectoryentryDisplay: "string",
        parents: { type: "list", objectType: "Parent" }
      }
    };

    const DirectoryFavoritesSchema = {
      name: "DirectoryFavorites",
      properties: {
        student: {type: 'Student'},
        user_id: "int"
      }
    };
```

I do that here:

```
let students = realm.objects('Student');
        let student = students.filtered('id == "'+this.props.id+'"');
        console.log(student);
        realm.create("DirectoryFavorites", { student: student, user_id: parseInt(global.user_id) });
```

The error I get is 'Property' must be of type: string which is confusing becuase I have said it should be a property of type Student. If I replace the single object property with a list property and add the student it works fine. 

```
const DirectoryFavoritesSchema = {
      name: "DirectoryFavorites",
      properties: {
        student_list: {type: 'list', objectType: 'Student'},
        user_id: "int"
      }
    };
```

**Comment by astigsen** [comment]
That seems like an error in the error message. It should probably have said: `'Property' must be of type: Student`.

The reason you get an error is that you are trying to add a list of students (which may only contain one, but it is still a list), where the property only takes a Student.

I would change your query to something like this:

(note I changed the query to not need string composition to make it less brittle):

```javascript
let student = students.filtered('id == $0', this.props.id)[0];
```

or since the `id` is a primary key, you could also do:

```javascript
let student = realm.objectForPrimaryKey("Student", this.props.id);
```

**Comment by blagoev** [comment]
also there will be more descriptive message with this fix https://github.com/realm/realm-js/pull/1046

**Comment by blagoev** [comment]
closing this one since nothing further can be added.
