### ISSUE TITLE
Open readOnly database from bundle (assets) path on Android

### ISSUE THREAD

**Issue by cwagner22** [realm/realm-js#1047]
Is it possible to open the realm database on Android without having to copy it to the Documents folder? On iOS I can use:
```
const realm = new Realm({
  path: RNFS.MainBundlePath + '/default.realm',
  readOnly: true
})
```

But `RNFS.MainBundlePath` is not available on Android. I copied my database to `src/main/assets/` but I don't know how to reference it.

**Comment by blagoev** [comment]
On Android assets files are not extracted on install. They remain zipped inside the application bundle.
You need use something for RN that will allow you to access the assets bundled database. At first glance https://github.com/itinance/react-native-fs/pull/83 this RN module seems to allow reading android assets.

You can also do it yourself by using the Android [AssetManager](https://developer.android.com/reference/android/content/res/AssetManager.html) access the bundled database. But that will require writing some plumping android native code for RN.  

In any case the realm file needs to be on the file system for realm to be able to use it.

**Comment by cwagner22** [comment]
The problem is that the Realm constructor needs the db path as parameter so I can't use any asset manager to read the file manually.

**Comment by blagoev** [comment]
I referred to using an AssetManager so you can extract the db file into your application files directory and then point to it when create the Realm instance. The path to the files directory for an app is well defined on android. I don't know what "Documents" folder you refer to. 

Is this helpful or I am missing something here?

**Comment by cwagner22** [comment]
Yeah I was hoping there was a way to use the realm database without copying it to another folder.
Here is how to do it with react-native-fs:
`RNFS.copyFileAssets('default.realm', RNFS.DocumentDirectoryPath + '/default.realm')`
You can also use Realm.copyBundledRealmFiles() butt that won't overwrite the destination file if it already exists.
