### ISSUE TITLE
RCTBridge.h file not found xCode error

### ISSUE THREAD

**Issue by natwales** [realm/realm-js#1048]
React Native 0.44.0 using realm 1.3.1 ios.

1) npm link realm 
2) open Xcode project. Fails to compile due to RCTBridge.h file not found in RealmReact.mm

**Comment by shauncodal** [comment]
same thing

**Comment by fealebenpae** [comment]
Are you by any chance using React Native as a CocoaPod, or did you create your project using the React Native CLI?

**Comment by shauncodal** [comment]
Not as a cocoaPod, using react native CLI

**Comment by fealebenpae** [comment]
What version of Xcode are you using?

**Comment by shauncodal** [comment]
Version 8.3.3 (8E3004b)

**Comment by miss-yadi** [comment]
I also met the same issue

**Comment by lnpquang** [comment]
Dear, 
I meet the same issue:

In file included from /node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:21:
../../../react-native/React/Base/RCTBridge+Private.h:12:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>

React-Native: 0.43.1
realm: 1.10.0

Thanks.
Best regards.

**Comment by jeffreyabarrios** [comment]
Has anyone found a solution for this error? I'm getting the exact same result.

**Comment by Jose4gg** [comment]
Same here!

**Comment by jasonmerino** [comment]
I too am seeing this error when trying to build my project with the realm source. It works fine with the NPM installed version, but does not work I include the source.

Working with:

react-native@0.43.3
realm@master (last release looks like 1.10.3 released yesterday)

**Comment by timwangdev** [comment]
@fealebenpae I'm using Pods to install react native and I got this error too.

**Comment by servatti** [comment]
Same here! Using Cocoapods and
"dependencies": {
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.48.3",
    "realm": "^1.12.0"
}

**Comment by servatti** [comment]
Based on @thevest [comment](https://github.com/airbnb/native-navigation/issues/85#issuecomment-298134777), in the add `RealmReact` Xcode project add

`$(SRCROOT)/../../../../ios/Pods/Headers/Public (recursive)`

**Comment by hackdie** [comment]
any work around for this?

my ...ios/Pods/Headers/Public  is also empty

**Comment by lllyyy** [comment]
同样的错误/usr/local/lib/node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:21:9: 'RCTBridge+Private.h' file not found

**Comment by mencomao** [comment]
Same here /usr/local/lib/node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:21:9: 'RCTBridge+Private.h' file not found

**Comment by kneth** [comment]
This was a common error in older versions of Realm JavaScript and React Native, we haven't observed it after moving to Cocoapods.
