### ISSUE TITLE
[React Native v0.45.0-rc.3] [iOS] Realm has no setter or ivar for its bridge

### ISSUE THREAD

**Issue by mehcode** [realm/realm-js#1049]
When trying to use Realm in the soon-to-be-stable v0.45 of React Native the `setBridge` function fails with the following (which causes the exception in the issue title to show in a red box) on https://github.com/realm/realm-js/blob/master/react-native/ios/RealmReact/RealmReact.mm#L275

```
[<RCTBridge 0x6100000a5e20> valueForUndefinedKey:]: this class is not key value coding-compliant for the key javaScriptExecutor.
```

I'm assuming this has to do with the newer C++ bridge. 

---

```
Realm: 1.3.1
React Native: v0.45.0-rc.3
Platform: iOS (Android seems to work great)
```

**Comment by ovr** [comment]
`0.45.0` Released, https://github.com/facebook/react-native/releases/tag/v0.45.0

ping @alazier, @appden, @tgoyne

**Comment by jbreuer95** [comment]
+1

**Comment by melsam** [comment]
+1. this is blocking us from updating to RN 0.45.

**Comment by yemarnevets** [comment]
Is there a recent version of ReactNative that still works with Realm? 

I am getting set up with Realm for the first time and I am happy to roll back RN temporarily to get experience with Realm.

**Comment by danielreuterwall** [comment]
It works fine in 0.44. Just the latest release that introduced this issue.

**Comment by Sophia-Gao** [comment]
+1

**Comment by SoundBlaster** [comment]
There is a same issue in RN repo but solutions from this tread can not help me
https://github.com/facebook/react-native/issues/13384

**Comment by billpatterson** [comment]
Also getting this error, also tried solutions in link @SoundBlaster mentioned, did not help me either. Project was working fine until I updated to RN 0.45 today.

**Comment by antonellil** [comment]
What is the solution for this?

**Comment by aparedes** [comment]
Right now, you should just use RN 0.44.3 or under. And wait for the next release of realm fixes it or a new update from RN.

**Comment by zphhhhh** [comment]
Hope can support RN 0.45 soon, THX

**Comment by fealebenpae** [comment]
Folks, https://github.com/realm/realm-js/pull/1065 fixes this issue. We'll try to make a new release as soon as possible, but in the mean time you can just apply the changes to `RealmReact.mm` in the PR to the same file in `node_modules/realm/react-native/ios/RealmReact` in your apps.

**Comment by aparedes** [comment]
@fealebenpae it works fine in debug mode but I get the same error for the release.

**Comment by fealebenpae** [comment]
@aparedes thanks, I'll check it out. What are your Xcode and React Native versions?

**Comment by aparedes** [comment]
@fealebenpae Xcode 8.3.3 and ReactNative 0.45.1

**Comment by fealebenpae** [comment]
I've reproduced it and fixed it, @aparedes, thanks. Check out the latest commit on #1065

**Comment by dzunglht** [comment]
Please do regression test on react-native (release-build mode)
Thanks

**Comment by frangeris** [comment]
@fealebenpae Installed and working :relieved: , any ETA for tag? in the mean time...

```bash
$ npm install realm/realm-js#237e1ba --save
```
