### ISSUE TITLE
Value not convertible to a Number with type: 'date' property - only when not connected to debugger on ios

### ISSUE THREAD

**Issue by pukeanddie** [realm/realm-js#1050]
react-native 0.44.0 & realm 1.2.0. 

I'm assigning the following timestamp to a realm 'date' property when creating an object

```
const loadedJsonTimestamp = '2017-06-06 21:23:53 UTC';
let props = {
    id,
    createdAt: new Date(loadedJsonTimestamp),
  };

try {
    realm.write(() => {
      realm.create(MyObject.schema.name, props);
    });
  } catch (e) {
    Alert.alert(e.toString());
  }
```
Now, if I run this in the simulator, or on a device with debug js remotely enabled it works fine. It's only when I disable debug js remotely or run an archive build that I get the **Value not convertible to a number** error

**Comment by pukeanddie** [comment]
closed issue. This issue has nothing to do with realm.js.

**Comment by raghuureddy** [comment]
@pukeanddie can you please tell us how you fixed this? I am facing the exact same issue.

**Comment by elad823** [comment]
Did you find any answer?

**Comment by gauravgrover95** [comment]
It is definitely a problem with RealmJS. 
[This StackOverflow Answer](https://stackoverflow.com/a/47855626/5254706) fixed the error for me.

**Comment by YvetteHo** [comment]
I ran into the same problem. Change 'YYYY-MM-DD HH:MM:SS UTC' to 'YYYY-MM-DDTHH:MM:SS' solved my problem.
