### ISSUE TITLE
unable to use rowHasChanged for Realm objects in ListView

### ISSUE THREAD

**Issue by EyalSi** [realm/realm-js#1051]
Seems like it is impossible to know if a record of ListView Realm objects really changed.
When using a real usecase and comparing to recordID and modification date as in this example:
```
  constructor(props) {
    super(props);
    const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => ((r1.recordID != r2.recordID) || (r1.modifiedDate.getTime() != r2.modifiedDate.getTime()))});
    let contacts = Realm.objects('Contact').snapshot()
    this.state = {
      contacts: contacts,
      dataSource: ds.cloneWithRows(contacts.sorted('modifiedDate',true)),
    };
  }

```
Any update done to the contact in Realm, which reflects in updating the modification date, is automatically changed in the datasource (though trying to get a snapshot). Hense the comparison of rowHasChanged, always returns false, as r1.modificationDate is the same as r2.modificationDate.

**Comment by kneth** [comment]
I am closing the issue. We need to consider a better ListView component.
