### ISSUE TITLE
error: terminate called after throwing an instance of 'realm::MultipleSyncAgents'

### ISSUE THREAD

**Issue by ianpward** [realm/realm-js#1053]
js-client1:

    const Realm = require('realm');
    const StoreProduct = {
    name: 'StoreProduct',
     properties: {
    productId: 'int'
     }
    };
    Realm.Sync.User.login('http://:9080', 'гыук', '12345678', (error, user) => {
    var realm = new Realm({
    sync: {
    user: user,
     url: 'realm://:9080/~/mainDB1'
     },
     schema: [StoreProduct]
    });
     realm.objects('StoreProduct').addListener((collection, changes) => {
         console.log(`${changes.insertions.length} insertions`);
         console.log(`${changes.modifications.length} modifications`);
         console.log(`${changes.deletions.length} deletions`);
         console.log(`new size of collection: ${collection.length}`);
         });
    });js-client 2:

```
const Realm = require('realm');
const StoreProduct = {
name: 'StoreProduct',
    properties: {
        productId: 'int'
    }
};
Realm.Sync.User.login('http://:9080', 'sameuser', '12345678', (error, user) => {
    var realm = new Realm({
        sync: {
            user: user,
            url: 'realm://:9080/~/mainDB1'
        },
        schema: [StoreProduct]
    });
     realm.write(()=> {
        realm.create('StoreProduct', {productId: 10});
        realm.create('StoreProduct', {productId: 11});
        realm.create('StoreProduct', {productId: 12});
        realm.create('StoreProduct', {productId: 13});
    })
    realm.close();
 // user.logout();
});
```

results in: `error: terminate called after throwing an instance of 'realm::MultipleSyncAgents'`

I believe this is related to using the same local path but we should definitely throw a more descriptive error
cc: @bigfish24

**Comment by bigfish24** [comment]
Agree we should make sure the error messages explain the problem.

**Comment by HariKiran9** [comment]
Hi Ian,

I am getting this type error, this is from Node.js to ROS.

terminate called after throwing an instance of 'realm::MultipleSyncAgents'
  what():  Multiple sync agents attempted to join the same session
Aborted (core dumped)

![image](https://user-images.githubusercontent.com/11388341/43765515-be82eeee-9a4d-11e8-84f3-652a114e2914.png)

**Comment by fealebenpae** [comment]
@HariKiran9 That usually happens if you have another instance of the Node.js script running. The actual reason for the crash is that a synced realm file cannot be open in more than one process at a time.
