### ISSUE TITLE
Asynchronously Opening Realms in JS

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1057]
Are there any plans to support "Asynchronously Opening Realms" in JavaScript. I see it documented in Objective-C but no mention of it in the JS docs.

**Comment by MrHubble** [comment]
@agersoncgps have you also tried `open`?
https://realm.io/docs/javascript/1.12.0/api/Realm.html#.open

From what I can tell, `open` could be used with `async / await` but `openAsync` could not.
