### ISSUE TITLE
Realm.create silently fails if properties are missing

### ISSUE THREAD

**Issue by astigsen** [realm/realm-js#1058]
If you give a dict as input to `Realm.create()` and it is missing some of the properties in the target model, the method silently fails.

The documentation does mention that you need to provide values for all properties with default values, but when you accidentally leave out a property, you can end up spending a lot of time debugging why it doesn't work, since it just fails silently (at least I did).

**Comment by blagoev** [comment]
@astigsen This should be resolved in the latest released version. Closing this as fixed.
