### ISSUE TITLE
Allow install without internet using yarn global cache or offline mirror

### ISSUE THREAD

**Issue by vikeri** [realm/realm-js#1067]
An advantage of yarn is that it allows [offline installs](https://yarnpkg.com/blog/2016/11/24/offline-mirror/). This does not work with Realm since it does an HTTP request while installing. It would be nice if this HTTP request could somehow be avoided.

```
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/realm-v1.3.1-node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@1.3.1 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http getaddrinfo ENOTFOUND static.realm.io static.realm.io:443 
```

**Comment by kristiandupont** [comment]
Sorry, but that would require us to put the binary builds for all platforms into the package which would make it very large. When a pregyp file is not available, it should try to build from source though that will not help either as that requires downloading the realm core.

**Comment by vikeri** [comment]
Ok, that's understandable
