### ISSUE TITLE
Realm ListView and fetchLimit

### ISSUE THREAD

**Issue by ugendrang** [realm/realm-js#1075]
I have more than 10,000 Category records and would like to display this records in RealmListView and keeping the RealmObjects wrapped in Results,

var category = realm.objects('Category');
const categoryDS = new ListView.DataSource({rowHasChanged: (r1, r2) => r1.name !== r2.name});
const mapStateToProps = (state) => {
  return {
    dataSource: recordDS.cloneWithRows(category),
  };
}

Since fetching all the 10,000 records and rendering all the records in ListView at single shot will not be the best practice. 

Do we have something like 'fetchLimit' in RealmListView, so that when i set fetchLimit={20}, the ListView will display the first 20 records and the next set will be loaded only the when onEndReached.

**Comment by ugendrang** [comment]
@kristiandupont , As I am new to React Native and Realm, I don't have idea to overcome the reported issue and struggling to fix it. Can you please help me out by providing some input, so that i can proceed from there.

**Comment by kneth** [comment]
`LIMIT` is part of the Realm Query Language.
