### ISSUE TITLE
Can you update `buildToolsVersion` in realm for react native ?

### ISSUE THREAD

**Issue by zphhhhh** [realm/realm-js#1081]
Now the default `buildToolsVersion` is "23.0.1", but if I update the gradle version to 3.3 in the main project, it would alert that  
```
Error:The SDK Build Tools revision (23.0.1) is too low for project ':realm'. Minimum required is 25.0.0
Update Build Tools version and sync project
```

Thanks!

**Comment by fealebenpae** [comment]
1.8.2 increases the `buildToolsVersion` to 25.0.2.
