### ISSUE TITLE
More descriptive auth error messages

### ISSUE THREAD

**Issue by ianpward** [realm/realm-js#1085]
When using Realm.Sync.User.login if you specify the server as an ip like `1.1.1.1` you get this error message:
➜  node users-client.js
(node:7431) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: only absolute urls are supported
(node:7431) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

If you specify an ip like: 1.1.1.1:9080 you get:
(node:7465) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: only http(s) protocols are supported
(node:7465) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

If you specify http://1.1.1.1 you get:
(node:7489) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://54.221.31.72/auth failed, reason: connect ECONNREFUSED 54.221.31.72:80
(node:7489) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fealebenpae** [comment]
We can clean up the errors (get rid of the `UnhandledPromiseRejectionWarning`) and leave only the inner error (`FetchError: request to http://54.221.31.72/auth failed, reason: connect ECONNREFUSED 54.221.31.72:80`) - would that be good enough?

**Comment by ianpward** [comment]
Should we be more descriptive ? like: `URLS must be in the format http://<IP_ADDRESS>:<PORT>`

**Comment by fealebenpae** [comment]
I've looked into this and the `UnhandledPromiseRejectionWarning` cruft is not generated by Realm - most likely the `login` API is called in a promise continuation in user code and the rejection is unhandled by the user.

The actual error messages are thrown by `fetch` itself when trying to perform a HTTP request. There might be a way to rethrow and improve them, but that needs more investigation.

**Comment by kneth** [comment]
@fealebenpae @ianpward Is this relevant for 2.3.0?

**Comment by ianpward** [comment]
@kneth I have no idea - you tell me
