### ISSUE TITLE
Support Chrome debugging with Sync

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1089]
I am using react native and I want to use the sync functionality on OSX. When I try to login I get the following error "Cannot read property 'User' of undefined" - if I log React.Sync to the console, sure enough it's undefined.

`Realm.Sync.User.login`

If I disable remote  debugging everything works as I expect it to but it's a nightmare to debug. 

Should I be able to use chrome debugger with realm sync?

**Comment by sambwest** [comment]
I got a response to this in the realm.io forums: https://forums.realm.io/t/react-sync-missing-when-debugging/379

Seems to suggest that for now you can't use Sync and chrome debug tools in react native. As the majority of react native development is done with chrome tools I have left this open as surely that is an issue?

**Comment by bmunkholm** [comment]
Thanks for that. It surely is.

**Comment by sambwest** [comment]
This is old seems to have been resolved ages ago. I'm going to close it.
