### ISSUE TITLE
Reject schema with nonoptional object property

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-js#1104]
Currently, all of the following properties (`alpha`, `beta`, and `gamma`) will be effectively optional:
~~~
const Foo = {
    name = 'Foo',
    properties: {
        alpha:  {type: 'Foo'},
        beta:   {type: 'Foo', optional: false},
        gamma:  {type: 'Foo', optional: true},
    }
};
let realm = new Realm({schema: [Foo]});
~~~

It seems to me that we should at least disallow `{type: 'Foo', optional: false}`, since it is ultimately not honored. I also think we should either disallow `{type: 'Foo'}`, or document that `optional` is true by default for object (link) properties.

**Comment by fealebenpae** [comment]
We validate the schema at the Object Store level. Please open an issue in realm-object-store instead.

**Comment by kspangsege** [comment]
Why did ya close this one? Please provide a comment and then reclose.

**Comment by kristiandupont** [comment]
Sorry, that was a mistake!
