### ISSUE TITLE
Array must contain values for all object properties

### ISSUE THREAD

**Issue by kennetpostigo** [realm/realm-js#1109]
Hey guys, i'm pretty new to realm but I'm not completely sure why I get the `Array must contain values for all object properties` error.

My code is as follows:
```js
createChecklistTemplate = () => {
  let { items } = this.state;  // An array of string values ['1', '2', '3']
  let group = this.props.group;
  let realm = this.props.realm;

  realm.write(() => {
    let checklistTemplate = realm.create('ChecklistTemplate', {
      uniqueidentifier: uuid.v4(),
      checklistInstances: [],
      group,
      itemTemplates: [],
    });

    items.map(name => {
      let checklistItemTemplate = realm.create('ChecklistItemTemplate', {
        name,
        uniqueidentifier: uuid.v4(),
        checklistTemplate,
        itemInstances: [],
      });

      checklistTemplate.itemTemplates.push(checklistItemTemplate);
    });

    group.checklistTemplate = checklistTemplate;

    [...group.members].map(student => {
      let checklist = realm.create('Checklist', {
        uniqueidentifier: uuid.v4(),
        items: [],
        student,
        template: checklistTemplate,
      });

      checklistTemplate.checklistInstances.push(checklist);

      checklistTemplate.itemTemplates.map(template => {
        let checklistItem = realm.create('ChecklistItem', {
          checked: false,
          uniqueidentifier: uuid.v4(),
          checklist,
          template,
        });

        checklist.items.push(checklistItem);
        template.itemInstances.push(checklistItem);
        return checklistItem;
      });
    });
  });
};
```

Can anyone explain to me why this error surfaces?

**Comment by fealebenpae** [comment]
Could you please create a small project that reproduces the error and attach it here?

**Comment by kennetpostigo** [comment]
@fealebenpae at the moment i'm not sure I can, project is react native and we have a time sensitive deadline this week. I didn't expect realm to be this difficult to debug, given that it gives this specific error, that may show up in x cases.

**Comment by kennetpostigo** [comment]
@fealebenpae what are the cases for when this specific error appear? It may help me narrow down the bug.

**Comment by fealebenpae** [comment]
This can happen if you're passing an array of values to `Realm.create` instead of an object literal. Also if you're trying to set an array to an object property instead of a list property. Without looking at your schema I can only guess, but maybe you have forgotten to specify `type: list` on a property that was meant to be a to-many relationship?

**Comment by kennetpostigo** [comment]
@fealebenpae Thank you! Those cases helped narrow it down for me :)
