### ISSUE TITLE
Float decimals changes after create/update

### ISSUE THREAD

**Issue by ashah888** [realm/realm-js#1110]
After inserting a float value of "90.99", the document stored is ... "90.9899978637695".

Is this a bug or on purpose?

**Comment by bdash** [comment]
90.99 cannot be represented exactly by a 32-bit floating point value, which is what a property of type float requests (it can't be represented exactly as a 64-bit double precision floating point value either, for that matter). [This article](http://www.exploringbinary.com/why-0-point-1-does-not-exist-in-floating-point/) provides a good overview as to why. If you'd like to preserve the value exactly as you inserted it, you should use a property of type double, which is the same representation JavaScript uses for numeric values. While it still won't store exactly the value 90.99, it will use exactly the same representation of that number that you have in your JavaScript code (which is really 90.9899999999999948840923025272786617279052734375).

**Comment by Sybio** [comment]
Model :
```javascript
Audit.schema = {
  name: 'Audit',
  primaryKey: 'id',
  properties: {
    rate: 'float?',
  }
};
```
Create/Update :
```javascript
this.write(() => {
  audit = this.create('Audit', {
    rate: 1.9,
  }, true);
});
```
WTF :
```javascript
console.log(audit.rate) // Output 1.899999976158142
```

Thanks to you @bdash, I solved my problem even if i find that very, very strange !

Working solution :
```javascript
Audit.schema = {
  name: 'Audit',
  primaryKey: 'id',
  properties: {
    rate: 'double?',
  }
};

// ...

console.log(audit.rate) // Output 1.9
```

**Comment by ammar-wizsoft** [comment]
yeah need to change the type to Double in realm model fix this issue
