### ISSUE TITLE
React-Native project directory messed up after installing realm

### ISSUE THREAD

**Issue by beyerss** [realm/realm-js#1112]
I'm creating a brand new project to use Realm with RN but I'm running into an issue that I haven't been able to get around. After installing realm, RN does not think my directory is an RN project directory anymore. My exact steps are:

`react-native init BibleBinderRN`
`cd BibleBinderRN/`
`react-native -v`

At this point I see: 

> react-native-cli: 2.0.1
react-native: 0.45.1

Next:

`npm install --save realm`
`react-native -v`

Result:

> react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

I don't understand why this is not an RN project directory at this point.

**Comment by blagoev** [comment]
Hi I have not been able to reproduce your issue. Tried the exact same steps with the exact same versions of the packages. 
Probably it relates to something in your environment. 
Can you post the full output of these commands so we can try understanding more about the problem

cheers

**Comment by rezals00** [comment]
some problem here ...

**Comment by mmartche** [comment]
Try run the 'npm' command with sudo or admin privileges
