### ISSUE TITLE
Connection has no connected handler

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1115]
v1.8.0

Everything appears to be working fine in my app, but the xcode console is showing "Connection has no connected handler" about once per second on going when I run my app on device. Just wondering what this error means, if it is anything to be concerned about, and do the errors represent any performance problem.

![screenshot 2017-07-03 18 19 49](https://user-images.githubusercontent.com/336441/27809289-4716a9de-601c-11e7-9574-de5c44d12466.png)

```
Realm.Sync.User.registerWithProvider(
      "http://localhost:9080",
      "custom/cgpsauth",
      accessToken,
      (error, user) => {
        console.log(error);
        if (!error) {
          Realm.openAsync(
            {
              schema: [
                StudentSchema,
                ParentPhonesSchema,
                ParentsSchema,
                ParentAdressSchema,
                DirectoryFavoritesSchema
              ],
              sync: {
                user: user,
                url: "realm://localhost:9080/cgps-app-v1"
              }
            },
            (error, realm) => {
              if (error) {
                return;
              }
              // Realm is now downloaded and ready for use
              this.realm = realm;
              console.log("sync done");
              console.log(user);
            }
          );
        }
      }
    );
```

**Comment by fealebenpae** [comment]
This isn't a message logged by Realm. Seems like it comes from a component internal to React Native itself: https://github.com/facebook/react-native/issues/10027.
