### ISSUE TITLE
List properties docs need some clarification

### ISSUE THREAD

**Issue by compojoom** [realm/realm-js#1123]
The list docs here https://realm.io/docs/javascript/latest/#list-properties a little hard to understand for someone who hasn't been working object dbs before. 

I have the following code:
```
db.write(() => {
  db.create('Field', field, true);
  company.fields.push(field);
});
```

This throws an exception "Attempting to create an object of type '%1' with an existing primary key "

I'm first creating the field, then trying to add the same field to the company.fields list, but this seems to be the wrong way to do this.
If I directly do company.fields.push without attempting to create the Field upfront everything works fine. 
So is the correct way to add list properties just to add the objects to the parent? Without creating the objects upfront?

And then how do you filter on those lists?

I have the following objects
Company -> fields -> crops
Company-> fields -> comments

How do I get all crops belonging to a company?
If I do this:
database.objects('Crop').filtered('company_id = $0', company_id);
 I get an exception: No property '%1' on object of type '%2'
Company.company_id, but I get the same result.

Are we able to get filtered result based on parent objects?

**Comment by compojoom** [comment]
Ok, so parent relationships seem to be implemented first in this pull request https://github.com/realm/realm-js/pull/1101 6 days ago. Which is great! I'm currently testing it, but still cannot understand how this is supposed to work?

This is my schema:
```
export default class Company extends Realm.Object {
}
Company.schema = {
	name: 'Company',
	primaryKey: 'company_id',
	properties: {
		company_id: 'string',
		name: 'string',
		country: {type: 'string', optional: true},
		email: {type: 'string', optional: true},
		position: {type: 'LatLng'},
		fields: {type: 'list', objectType: 'Field'}
	}
}

Field.schema = {
	name: 'Field',
	primaryKey: 'field_id',
	properties: {
		field_id: 'string',
		name: {type: 'string'},
		size: {type: 'int', optional: true},
		position: {type: 'LatLng'},
		active_crop_uuid: {type: 'string'},
		crops: {type: 'list', objectType: 'Crop'},
		linking_company: {type: 'linkingObjects', objectType: 'Company', property: 'fields'},
	}
};

```
I'm trying to get all the fields belonging to a particular company. So my query looks like this:

`realm.objects('Field').filtered('linking_company.company_id = $0', 'some_uuid_here');`

but this always throws an exception. "Property 'company_id is not a link in object of type 'Company'"

**Comment by fealebenpae** [comment]
> ```
> db.write(() => {
>    db.create('Field', field, true);
>    company.fields.push(field);
> });
> ```

You ought to save the result of `db.create` to a variable and pass that to `company.fields.push`. If you use the same plain object (`field`) `fields.push` is going to call `create` to get a realm object but it won't pass `true` for the `update` parameter and will try to create a brand new object.

> So is the correct way to add list properties just to add the objects to the parent? Without creating the objects upfront?

Adding an object to a list will call `create` if the object isn't already a realm object. You can call `push` with a plain object and it will create a realm object out of it and add it to the list and that's a perfectly fine way to use it. You can call `create` directly and push the returned object to the list and that's also fine. It's up to you which of the two approaches to choose based on your needs.

**Comment by compojoom** [comment]
Aaah, of course. I see now. That works. 

What about the reverse traversal? 
Can I find fields that belong to a company, or do I always have to go from company to fields?

**Comment by fealebenpae** [comment]
I don't think we support filtering by the contents of a list or linkingObjects property. @alazier do you know more?

I know it's a stupid workaround, but you could also express your query as `realm.objectForPrimaryKey('Company', 'some_uuid_here').fields` and that will give you the fields belonging to that company if you've only got the company primary key value.

**Comment by compojoom** [comment]
Yea, I was kind of hoping to solve the following situation. 
You have 20 companies. You know the ids of 10 of them and are supposed to show all the fields for those 10 companiesl
realm.objects('Field').filtered('company.company_id = $0 OR .... = $1') etc
now I would have to go through all the 10 companies and add their fields to an array etc.  

If we can't do this - what are linked objects for?

**Comment by fealebenpae** [comment]
I'm afraid that at the moment realm-js just doesn't have that functionality, even though we'd very much like to implement it in the future.

**Comment by compojoom** [comment]
Okay. 

But can someone explain the linked object feature? What is it supposed to do? Just give you the ability to access parent objects? If so - can we build a 1:1 relationship with it? Or is the linked object always a collection of links? I would love to update the docs - if I eventually manage to understand all this :D

**Comment by fealebenpae** [comment]
The Swift documentation explains linkingObjects properties (even though the Swift syntax for declaring them looks a little bit different than the JavaScript one they work the same): https://realm.io/docs/swift/latest/#inverse-relationships

**Comment by compojoom** [comment]
I see. Well, we should copy a lot from there :)

Is there a way to specify that a linked object is an object an not an array?

For example we have
company -> fields

1 company can have many fields.

But a field belongs only to a company. Right now I've specified a property like this:
`linking_company: {type: 'linkingObjects', objectType: 'Company', property: 'fields'}
`
but the linking_company is an array and I have to access it with linking_company[0]. Not a huge issue, but would prefer if I could do field.linking_company.name for example.

**Comment by fealebenpae** [comment]
No, I'm afraid not. linkingObjects properties are actually implemented partially using parts of the query system so they always have to be Results objects.

**Comment by compojoom** [comment]
Should we worry about performance if we go crazy with this? Or is this as performant as the normal parent to child relation?

**Comment by fealebenpae** [comment]
linkingObjects properties are as fast as list properties, you can use them however much you like.
