### ISSUE TITLE
Updating an Object that has a list property

### ISSUE THREAD

**Issue by compojoom** [realm/realm-js#1124]
I think that this is a bug, but not 100% sure. 

I have the following schema:
```
Company.schema = {
	name: 'Company',
	primaryKey: 'company_id',
	properties: {
		company_id: 'string',
		name: 'string',
		company_number: {type: 'string', optional: true},
		street: {type: 'string', optional: true},
		zip: {type: 'string', optional: true},
		city: {type: 'string', optional: true},
		country: {type: 'string', optional: true},
		tel: {type: 'string', optional: true},
		email: {type: 'string', optional: true},
		manager: {type: 'Manager', optional: true},
		notes: {type: 'string', optional: true},
		position: {type: 'LatLng'},
		fields: {type: 'list', objectType: 'Field'}
	}
}
```

I have a view where I'm creating a new company or updating a new company. When I update a new company with this code:
```
		database.write(() => {
			if (this.props.editMode) {
				let company =  {...this.props.company, ...value};
				// delete company.fields;

				database.create('Company', company, true);
			} else {
				database.create('Company', value, true);
            }

        });
```

I get an exception in js_object_accessor.hpp on line 68
```
        if (!Value::is_valid_for_property(m_ctx, value, prop)) {
            throw TypeErrorException(util::format("%1.%2", m_object_schema.name, prop.name),
                                     js_type_name_for_property_type(prop.type));
        }
```

it's complaining about the fields property, but I don't understand why. If I delete company.fields before updating, then I don't run into the Exception. A console log shows that it is a normal realm result property.

**Comment by compojoom** [comment]
It seems that this fixed the original issue:
https://github.com/realm/realm-js/commit/89149c0a7508c16c0da5c388bfa7903a5bbf875d
I can now update the object without deleting the list properties (and I get no exception thrown at me), but doing so actually removes all links in the list property. The original objects that are linked to are preserved, but the parent Object no longer links to them.

Here is a repository where I've reproduced the issue:
https://github.com/compojoom/realmBug

On launch of the app we automatically create a person that has 2 cars. Clicking the update button should update the person with the same information. Save works, but the person loses their cars...

**Comment by fealebenpae** [comment]
@bdash

**Comment by bdash** [comment]
My changes in #1069 / #1126 don't have any effect on the semantics of assignment once the property types are validated. I suspect that this behavior existed prior to #1069, and was simply masked until #1126 fixed assigning a list to a list property.

**Comment by bdash** [comment]
If I'm remembering the underlying cause of this issue correctly, this will be addressed when realm-js pulls in realm/realm-object-store#525.

**Comment by RoderickJDunn** [comment]
Any news on when this will will be fixed? I'm seeing the same behavior in RealmJS 1.11.0

**Comment by radiegtya** [comment]
+1, when updating Object that has list properties, the list properties removed

**Comment by RoderickJDunn** [comment]
FWIW I'm no longer seeing this issue in v2.15.3

**Comment by bmunkholm** [comment]
Thanks @RoderickJDunn !
