### ISSUE TITLE
How to implement a cache db with expired support ?

### ISSUE THREAD

**Issue by bang88** [realm/realm-js#1129]
Hi,
We use Realm as cache db in our App, load data from server then store them in the realm database and next time user fetch the data we load it from the cache db. we need an efficiency way to define a expired time. if realm support it nativity that would be cool, at this moment we use timespan as the   expires date, when fetch a new data compare the timespan and then decide load from server or cache.

If we have a auto expired feature built in realm that should solve this kinds of problems.

Thanks

**Comment by kristiandupont** [comment]
At the moment we don't have any sort of auto expire feature so you will have to make an implementation of this yourselves I'm afraid.
