### ISSUE TITLE
the token refresh timer does not get destroyed with the session

### ISSUE THREAD

**Issue by kvap** [realm/realm-js#1134]
## Expected Results

Node should exit once I close all synced realms and log the user out.

## Actual Results

Node does not exit. According to this `wtfnode` output, there are `2×N` timers scheduled, where `N=3` is the number of realms I opened:

```
- Timers:
  - (590444 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
  - (590414 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
  - (590251 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
  - (589671 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
  - (590488 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
  - (589726 ~ 9 min) (anonymous) @ /Users/kvap/realm/realm-object-server/examples/many-users/node_modules/realm/lib/user-methods.js:55
```

## Steps to Reproduce

1. Log the user in
2. Open a synced realm
3. Close it
4. Log the user out

## Version of Realm and Tooling

- Realm JS SDK Version: realm-js 1.8.1
- Node or React Nattive: Node 6.11.0
- Client OS & Version: macOS 10.12.5
- Which debugger for React Native: None

**Comment by Damnum** [comment]
Any news on this one?

**Comment by kneth** [comment]
The token refreshed has been reimplemented in object store in v10.0.0, and I believe its life-cycle is now tied with the sync client.
