### ISSUE TITLE
Listener is not being fired in the React-Native Code when doing insertion in Android - Java

### ISSUE THREAD

**Issue by noobiehacker** [realm/realm-js#1137]
Questions: Hello all!! I am trying to add a listener from the React Native code, insert a row from the Android Java Native code, and get the listener to trigger on the React Native side

## Goals

Add a listener in the React Native Code, trying to do an insertion in Android Code, getting the listener to fire.

## Expected Results

Listener getting fired

## Actual Results

Listener not getting fired

I have verified that we are writing to the same DB and the same table, any help would be appreciated

**Comment by shenjiayu** [comment]
@noobiehacker code snippet might be helpful..: )

**Comment by kristiandupont** [comment]
@noobiehacker this should work. Can you show or send us some code that reproduces this?
