### ISSUE TITLE
Cannot write URL to type:'string'

### ISSUE THREAD

**Issue by michaelspeed** [realm/realm-js#1142]
i have a realm with schema - 
`const Friends = {
  name:'Friends',
  primaryKey:'id',
  properties:{
    id:{type:'string', indexed: true},
    name:'string',
    email:'string',
    coverPic:{type:'string', default:'null'},
    profilepic:{type:'string', default:'null'},
    Private:{type:'Private', objectType:'Private'},
    Group:{type:'list', objectType:'Group'}
  }
}`

so now i have a write function like this using react native

`realm.write(() => {
                realm.create('Friends', {
                  id: item.id,
                  name: item.name,
                  email: item.email
                  profilePic: item.profilePic,
                  coverPic: item.coverPIc
                })
              })`

## Goals
in the above the item object is like this - 
  `item = {
         coverPic:null
         email:"King@gmail.com"
         id:"cj3ncb1q22xxxxxxxxxxx"
         name:"Austin Powers"
         profilePic:"https://files.graph.cool/xxxxxxxxx"
}`
profilePic/coverPic are optional. can return null or url

## Expected Results

Actual results is that the write should be successfull.

## Actual Results

email/id/name are written but profilePic/coverPic remains "null"
i tried using this method also - 
`realm.write(() => {
                  realm.create('Friends', {id: item.id , profilePic: item.profilePic}, true);
                })`
still it remains "null" 

## Steps to Reproduce

just copy the code and run from above.

## Code Sample

`this.props.friendQuery.user.friendsList.friendListContainer.users.forEach((item) => {
            let tempRealm = realm.objects('Friends').filtered('id == $0', item.id);
            if(tempRealm.length > 0){

            } else {
              realm.write(() => {
                realm.create('Friends', {
                  id: item.id,
                  name: item.name,
                  email: item.email
                })
              })
              if(item.profilePic !== null){
                realm.write(() => {
                  realm.create('Friends', {id: item.id , profilePic: item.profilePic}, true);
                })
              }
              if(item.coverPic !== null){
                realm.write(() => {
                  realm.create('Friends', {id: item.id , coverPic: item.coverPic}, true);
                })
              }
            }
          })`

## Version of Realm and Tooling

- Realm JS SDK Version:  1.10.0
- Node or React Nattive: 0.46.1
- Client OS & Version: iOS 11
- Which debugger for React Native: chrome

**Comment by kristiandupont** [comment]
We have been having issues with error messages from `Realm.create` but I thought we had it under control by now. It seems that your schema is lowercase `profilepic` whereas you write to `profilePic` so that might explain the problem, though not why you don't receive an error.

**Comment by michaelspeed** [comment]
that didnt fix! i ended doing this - 
`const Friends = {
  name:'Friends',
  primaryKey:'id',
  properties:{
    id:{type:'string', indexed: true},
    jsonObject:'string',
  }
}`

keeping the whole information as string and then parsing it to JSON object when needed
