### ISSUE TITLE
Crash when trying to start a sync realm

### ISSUE THREAD

**Issue by compojoom** [realm/realm-js#1144]
I have an app that users redux for parts of the state and realm for persisting data. 
When we start the app - depending if the user is logged in or not, I show a login screen. 
The user is authenticated against auth0 - if everything goes well with that I start a connection to realm mobile platform
```js
Realm.Sync.User.registerWithProvider(
 'http://localhost:9080',
  'custom/auth0',
  response.json.access_token,
  (error, ruser) => {
    // Realm.Sync.User.current = ruser;
    console.log(error, ruser, user)
    resolve({
       realm_user: ruser,
       user_id: user.sub,
       email: user.email,
       token: response.json.access_token,
       id_token: response.json.id_token,
       refresh: response.json.refresh_token
 });
 }
);
```

I have a database class:
```js
class Database {
	static realm;

	getInstance() {

		if(!this.realm) {
			this.realm = new Realm({
				sync: {
					user: store.getState().owner.user.realm_user,
					url: 'realm://localhost:9080/~/my-realm',
				},
				...schemas[schemas.length-1]
			});

		}
		return this.realm;
	}
}

export default new Database;
```

When the user logs in, we save the realm user in the redux state. And I use the saved realm user to init my realm db. Unfortunatly when I do this I get this Exception:
_LIBCPP_INLINE_VISIBILITY pointer get() const _NOEXCEPT {return __ptr_.first();} 
<img width="1439" alt="grafik" src="https://user-images.githubusercontent.com/693770/28263732-2b1281f0-6ae8-11e7-94da-2f164d24183f.png">

I've output the value of my realm user to the console and this is what I have:
`Object {identity: "e2389cc9f88c0b788b512b2bd85a13fd", isAdmin: false, server: "http://localhost:9080", token: "eyJhY2Nlc3MiOlsicmVmcmVzaCJdLCJhcHBfaWQiOiIiLCJleH…6MlLgxOWgBJSIK5flWSklgm+LbFLwtwy+CzdJms7MLGy/xA=="}`

I don't know if this is a real bug or I am just not using the API correctly. Any advises appreciated.

**Comment by compojoom** [comment]
I think I know why the crash happens. When we get the user Object from registerWithProvider this object actually is a User object. When I save it to redux it's transformed to a plain object that only contains the properties. And when I pass it to sync something in Realm complains about that. 

Since I have the user's token and identity shouldn't it be possible to start a sync realm that way?
I would really prefer that my getInstance function is synchronious instead of async. This would simplify things a lot and I won't have to go in callbacks all the time.

**Comment by kristiandupont** [comment]
The `User` class contains native code so serializing and deserializing will indeed cause problems. I guess we could add methods that do this. As for a workaround, maybe you have a map of `key`->`User` somewhere and only store such a key in your redux store? Obviously this won't survive through localstorage etc. if you are using that, but the session wouldn't anyway.
