### ISSUE TITLE
same query gives different results in seconds

### ISSUE THREAD

**Issue by emineKoc** [realm/realm-js#1147]
## Goals

I need to see the query results, delete and update. 

## Expected Results

deleted items should disappear from the table

## Actual Results

query gives different results for each get request which is happening every 5 sc.

## Code Sample
exports.show_activeleads = function(req, res, next) {
	let ongoing = realm.objects('table_name');
	res.rows = ongoing;
	next();
}

## Version of Realm and Tooling

- Realm JS SDK Version: ? 
     "realm": "^1.10.0",

- Node or React Nattive: ?
  Node 
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kristiandupont** [comment]
Hi @emineKoc, would it be possible for you to show or send us some code that repdocuces the problem that you are facing?
