### ISSUE TITLE
One-To-Many relationship still unclear

### ISSUE THREAD

**Issue by michaelspeed** [realm/realm-js#1148]
## Goals
I have two schemas - 
`const Message = {
  name: 'Message',
  primaryKey:'id',
  properties:{
    id: 'string',
    jsonObject:'string'
  }
}
const PrivateChannels = {
  name:'Private',
  primaryKey:'id',
  properties:{
    id:'string',
    jsonObject:'string',
    count:'int',
    messages:{type:'list', objectType:'Message'}
  }
}`

i am trying to link messages to a single private channel. i cannot get to read the messages.
may be a copy of #1123

implementation is like this - 

`let prsChannel = realm.objects('Private').filtered('id == $0', this.props.channel);
        let messageLists  = prsChannel[0].messages;
        console.log(messageLists.length); <----- [returns 0, messages are there] 
        if(messageLists.length != this.props.messageQuery.allMessageses.length){
          this.props.messageQuery.allMessageses.forEach((item) => {
            let messageJSON = JSON.stringify(item);
            realm.write(() => {
              messageLists.push({id: item.id, jsonObject: messageJSON});
            })
            console.log(messageLists.length); <----- [returns true length, messages are there] 
          })
        } else {
        }`

## Expected Results

i want to read all the messages that are linked to the private channel. any ideas?
DOCS ARE NOT ELABORATIVE

## Actual Results

before i write with `push` the length of the list remains 0, where as they were written before

## Steps to Reproduce

not a bug

## Code Sample

all given above

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node or React Nattive: 0.46.1
- Client OS & Version: iOS 11
- Which debugger for React Native: chreomedebugger

**Comment by michaelspeed** [comment]
i have fixed this. closing this issue, but it would be really better if the docs were a little bit more updated

**Comment by michaelspeed** [comment]
reopening issue still cannot access the pre-written data

**Comment by kneth** [comment]
@michaelspeed Can you provide an example of pre-written data?

**Comment by kneth** [comment]
@michaelspeed Any updates?

**Comment by kneth** [comment]
@michaelspeed I close for now. Don't hesitate to reopen when you have any updates.
