### ISSUE TITLE
Realm.Sync with Nodejs : Bad sync progress

### ISSUE THREAD

**Issue by nehadwivedi** [realm/realm-js#1153]
We have been using Realm.Sync with nodejs. We have started facing a problem of "Bad Sync progress" recently. However, if we delete the local realm files and sync again, the problem is corrected. Can you please suggest what is the way out here.

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Nattive: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kristiandupont** [comment]
Would it be possible for you to send us the client-side realm file next time you encounter this problem?

**Comment by nehadwivedi** [comment]
[realm-private.zip](https://github.com/realm/realm-js/files/1164473/realm-private.zip)
Please find the private realm file uploaded.
Thanks.

**Comment by kristiandupont** [comment]
Thank you, we will take a look at it.

**Comment by morten-krogh** [comment]
@nehadwivedi 
Thanks for sending the Realm. 

The Realm private.realm is the client side Realm, right?

Could you also send the corresponding server side Realm?

Could you also tell me what version of RMP you are using?

Thanks in advance.

**Comment by nehadwivedi** [comment]
The server side realm file is huge, it is around 700 MB. Please advise.

**Comment by morten-krogh** [comment]
Does it work to compress it and upload it here?

**Comment by nehadwivedi** [comment]
Even after compression. The size is 40GB..so can't be uploaded here.

**Comment by morten-krogh** [comment]
Can you upload it to Google drive and share it. Or Dropbox?
Otherwise, I will let you upload to my drive.

**Comment by morten-krogh** [comment]
Or you can use this form

https://script.google.com/a/macros/realm.io/s/AKfycbzoNbUuu2H9WwsupV8VKZrSgz8XBl-rD7zGD_o0MKZ7_Yrjoe8r/exec

**Comment by nehadwivedi** [comment]
Sorry..yes 400MB..

**Comment by morten-krogh** [comment]
I see the dropbox folder realm as empty. Have you uploaded the file?

**Comment by nehadwivedi** [comment]
Hi

Please check the file now.There was an error in upload last time.

Thanks
Neha

**Comment by morten-krogh** [comment]
I have the file.

Thank you.

I will look at it, but I won't be able to do it next week.

**Comment by kneth** [comment]
@nehadwivedi Do you still see issue? Have you tried to upgrade to Realm JS 2.0?

**Comment by kneth** [comment]
@nehadwivedi 

I am closing the issue. If upgrading to 2.0.x didn't help you, don't hesitate to reopen the issue.
