### ISSUE TITLE
User object is empty after registration or login

### ISSUE THREAD

**Issue by darkmantle** [realm/realm-js#1155]
## Goals
Trying to login to Realm Mobile Platform using both username/password and facebook. After that I am attempting to write to a realm and then fetch the objects again.

## Expected Results
A realm to be created (works)
Writing an object to a realm (no errors produced)
Read the objects again (error produced)

## Actual Results
I get the following error: 
> [TypeError: undefined is not a function (evaluating 'realm.object("Test")')]
line: 61756,
column: 43,
sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' 

It also says:

> Error: 'user' must be of type: object

If I console log the user returned on register/login it is an empty object. If I change the password it returns a correct error due to wrong password, adding to my belief that the authentication was successful.

## Code Sample
```javascript
import Realm from 'realm';

/* [ ... ] */

Realm.Sync.User.registerWithProvider('http://SERVER:9080', 'facebook', accessToken, (error, user) => {
	if (error) console.log(error);

	console.log(user);

	const TestSchema = {
		name: 'Test',
		properties: {
			name: 'string',
			email: 'string'
		}
	};
	const realm = new Realm({
		sync: {
			user: user,
			url: 'realm://SERVER:9080/~/REALM'
		},
		schema: [TestSchema]
	});
	realm.write(() => {
		let test = realm.create('Test', {
			"name": "test",
			"email": "test@test.com"
		})
	});
	const obj = realm.object("Test");
	console.log(obj);
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node & React Native: 6.11.0 & 0.46.1
- Client OS & Version: OS X El Capitan 10.11.6
- Which debugger for React Native: ?

**Comment by fealebenpae** [comment]
The method is `objects`, not `object`. `User` is a native object wrapped in a JavaScript proxy - it doesn't have any fields, but you can still access [its properties](https://realm.io/docs/javascript/latest/api/Realm.Sync.User.html). That's why logging it to the console prints an empty object. The same applies for all other Realm APIs.

**Comment by darkmantle** [comment]
Thank you. Was using the code sample in the docs, it must be wrong: https://realm.io/docs/javascript/latest/#opening-a-synchronized-realm

**Comment by kristiandupont** [comment]
You are right. We will correct that, thank you for pointing it out.
