### ISSUE TITLE
linkingObjects is empty

### ISSUE THREAD

**Issue by icfr** [realm/realm-js#1158]
## Goals
when i want to acces to parent properties parent is present but has no fileds
## Actual Results
task.project is an object but object.keys() of task.project return empty
 ## Steps to Reproduce
see repo
## Code Sample
[repo](https://github.com/artis-auxilium/test-realm)

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node or React Nattive: react native
- Client OS & Version: android(6.0/7.1)/ios 10.3.2
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
`task.project` is a [`Results`](https://realm.io/docs/javascript/1.10.0/api/Realm.Results.html), and [`keys()`](https://realm.io/docs/javascript/1.10.0/api/Realm.Results.html#keys) should return an iterator.

**Comment by kneth** [comment]
@icfr Did my comment above help you? Can we close the issue?

**Comment by icfr** [comment]
sorry for the late response, yes it can be closed
