### ISSUE TITLE
Is it possible to sort by a secondary criteria?

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-js#1159]
This works to sort by Last Name, but I would like to add a secondary sort by First Name (first_name). So it would sort by last name and then sub sort by first name. 

The docs sugjest it is possible, but I can find the right syntax to make it work.

const array = this.realm.objects("Student").sorted('last_name', false);

**Comment by thatjuan** [comment]
You can just concat multiple `.sorted()` calls.

e.g. 
```
const array = this.realm.objects("Student")
.sorted('last_name', false)
.sorted('first_name', false);
```

**Comment by blagoev** [comment]
You can do that by using multiple arguments for the sorted method

realm.objects("Person").sorted(["FirstName", "SecondName"])

cheers.

**Comment by blagoev** [comment]
closing this since it was answered in helpscout as well
