### ISSUE TITLE
Nested level filter queries fail

### ISSUE THREAD

**Issue by kennetpostigo** [realm/realm-js#1164]
I'm working on a filtering a some data and i'm a little confused by a query that is failing.

I have a `person` schema that has a `groups` field that is a list of `group` schema. This list has group schema that has a field called `name` that is a string. I'm trying to query for this field to match a specific string. In my code I am assembling a query that filters based on activeFilters that are set. The filters range from checking the `person` gender, age, etc. and when those filters are active filtering works however when activating a filter for the nested query I get empty results because the query failed. when generating the nested level query I do the following:
```js
if (this.hasActiveFilters('group')) {
  Object.keys(group).forEach(key => { // Here I am looping through each after group filter
     if (group[key]) { . // here checking if the key exists, key is a string ie. "group1"

       // Here i'm pushing into the larger query where groups is the groups
       //  field on student and group.name is  group objects in the groups field
       groupQuery.push(`group.name == "${key}" IN groups`) 
     }
   })
}
```

**Comment by kristiandupont** [comment]
I'm afraid we don't support the `IN` operator yet. You can concatenate a number of `==` queries to obtain a similar result.

More details here:
https://github.com/realm/realm-js/blob/master/docs/tutorials/query-language.md
