### ISSUE TITLE
openAsync fails with an error with no message or code

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-js#1165]
## Goals

Open synced realm and receive an error when operation fails

## Expected Results

When there's an issue receive an error with a message describing the issue.

## Actual Results

The error object provided to the callback doesn't have error code and the message doesn't describe the issue

## Steps to Reproduce

Provide undefined value as one of the schema objects for the realm's schema. This might be due to unsuccessful import of the object from external file or other.

## Code Sample

```swift
Realm.openAsync({
  schema: [undefined],
  schemaVersion: 1
}, (error, realm) => {
  if (error) {
    console.log(error.message);
    console.log(error.errorCode);
    return;
  }
  console.log(realm);
})
```

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node or React Nattive: Node.js
- Client OS & Version: mac 10.12.6

**Comment by kneth** [comment]
`Realm.asyncOpen()` has been removed in v10.0.0 - using `Realm.open()`.
