### ISSUE TITLE
[RN 0.47.1] Can not install Realm     Stop on `> node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by guoliang1206** [realm/realm-js#1169]
https://github.com/facebook/react-native/issues/15222

**Comment by kneth** [comment]
@guoliang1206 I have not been able to reproduce it.

**Comment by guoliang1206** [comment]
I guess the network quality caused this issue.

**Comment by guoliang1206** [comment]
hi, Today I find there has more error log appear, so I reopen this issue and attach some error informations.
![2017-08-07 1 28 39](https://user-images.githubusercontent.com/12846676/29013251-6a54fb12-7b74-11e7-9beb-a92476688d10.png)

**Comment by guoliang1206** [comment]
The log file
[p11571C13EA1500432740266-1500621443.zip](https://github.com/realm/realm-js/files/1203942/p11571C13EA1500432740266-1500621443.zip)

**Comment by kneth** [comment]
@guoliang1206 

Tried with node 7.9.0/npm 4.2.0, and I don't see it.

![screen shot 2017-08-10 at 11 11 31](https://user-images.githubusercontent.com/1225363/29163500-f97a9122-7dbc-11e7-98cc-a7c1d5df4e0d.png)

**Comment by guoliang1206** [comment]
@kneth I have  found same error on this place:
https://github.com/realm/realm-js/issues/674  
I am not clear that realm team fixed this issue, because I have a test with your suggestion, it is still make error.

**Comment by kneth** [comment]
@guoliang1206 I am running out of ideas. Maybe you can try to clear the cache (`npm cache clean`) and increase the log level (`--loglevel=verbose`) when installing.

**Comment by guoliang1206** [comment]
@kneth hi, finally I have find the reason ,China's firewall is jammed the operation.  I have switch another network provider.

**Comment by benhurott** [comment]
Guys, after reading the [npm docs](https://www.npmjs.com/package/realm) of the lib, I read an important thing: `pre-requisites: Node: 4.0 <= version < 7.0`.

I'm using the [n version manager package](https://www.npmjs.com/package/n) to switch easily between node versions installed on my machine.

I just use the command `n 6.14.3` (the latest stable version before 7.x) and ran `yarn install` again.

This is the result:
```
$ yarn install
yarn install v1.9.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > native-base@2.7.2" has incorrect peer dependency "react@>=16.4.1".
warning " > native-base@2.7.2" has incorrect peer dependency "react-native@>=0.56.0".
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > react-native-firebase@4.3.0" has unmet peer dependency "fbjs@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 57.64s.
```

I have installed the following packages globally:
* npm install -g node-gyp
* npm install -g node-pre-gyp
