### ISSUE TITLE
Prevent random access to ROS

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#1171]
Only allowed apps should be able to create and access realms on a ROS

**Comment by PvanHengel** [comment]
Could you use Oauth for this?  Perhaps the tokens could be used along with some regency or scope on the realm. If you could add the scopes or app Id from the token to the user object created.  It could be easily implemented in a custom Oauth provider with a few tweaks.

**Comment by michael-mckenna** [comment]
Any updates on this?
