### ISSUE TITLE
Support counters

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#1172]
Add support for the increment and decrement instructions on integer columns

**Comment by liborbus** [comment]
We need an additional API that can more clearly express intent and generate better conflict resolution steps when using [Synchronized Realms](https://realm.io/docs/javascript/latest/#working-with-a-synchronized-realm). Something like `io.realm.MutableRealmInteger` class from Realm Java SDK or `RealmInteger<T>` Realm .NET SDK.

**Comment by aureliopetrone** [comment]
No updates on this?
