### ISSUE TITLE
[RN 0.47.0]ReactPackage.java remove createJSModules function

### ISSUE THREAD

**Issue by laznrbfe** [realm/realm-js#1176]
Could I change [`RealmReactPackage.java`](https://github.com/realm/realm-js/blob/master/react-native/android/src/main/java/io/realm/react/RealmReactPackage.java#L18)
```
    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```
to
```
    // @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```
?

**Comment by kneth** [comment]
It is listed under Breaking Changes: https://github.com/facebook/react-native/releases/tag/v0.47.0

**Comment by kristiandupont** [comment]
It looks like we need to remove the method rather than just the `@override` annotation.

**Comment by ovr** [comment]
> It looks like we need to remove the method rather than just the @override annotation.
