### ISSUE TITLE
cryptic error when using Pro/EE features

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-js#1177]
I get this error: `Error: [undefined] Sync feature not available` - no error code, and this is the error message. I'm investigating what the issue is at the moment.

In general, this is an error that our Pro/EE customers will get (I take it this is an error happening when you try using Pro/EE features) so we can provide a clearer path to recovery.

**Comment by nirinchev** [comment]
This is the error message that we are throwing in .NET:
> The Sync feature is not available. If you are using Professional or Enterprise editions, make sure to call Realm.SetAccessToken before opening any synced Realms. Otherwise, contact sales@realm.io for more information.

**Comment by icanzilb** [comment]
More info: it's happening on trying to use `openAsync` on Linux. It would be nicer to provide a better error message and recovery instructions, e.g. `You're using Realm.openAsync on linux, please use setAccessToken` to enable paid features or if you haven't got a license, contact sales@realm.io"

**Comment by michael-mckenna** [comment]
Cryptic error to cryptic error...I also got the "Sync Feature not available error". For more info you can see the last half of the discussion here https://github.com/realm/realm-js/issues/1161#issuecomment-319737958.

His response was "Unfortunately, realm-js does not support classes at this time. That is your issue - strange error message though. We should fix that". I'm currently asking for clarification, but perhaps this can help.

I am using the access token given to me yet to no avail.

**Comment by kneth** [comment]
I have labeled it as an enhancement, and put it in our backlog so we don't forget to improve the error message.

**Comment by michael-mckenna** [comment]
For me there was an error with the token I received for my trial and Ian cleared it up.

**Comment by alazier** [comment]
We could improve the error message I think

**Comment by plandem** [comment]
will 'sync' work with electron-app?!

**Comment by michael-mckenna** [comment]
@plandem Yes, if you're running the macOS ROS distribution

**Comment by plandem** [comment]
@michael-mckenna so It's not possible to use ROS at cloud (e.g. AWS) and build electron app with sync?

**Comment by michael-mckenna** [comment]
@plandem For that you'll need at least the professional edition.

**Comment by plandem** [comment]
I see. In that case realm is not for me :( Sad, I really liked it in my IOS times, but now I need electron app and profession license is not case for prototype app without any income.

**Comment by bmunkholm** [comment]
@plandem Did you see our plans for Realm Cloud (https://realm.io/blog/realm-cloud-beta-waitlist/)?
That will work better for you as we won't be feature limiting, but usage based pricing.

**Comment by plandem** [comment]
@bmunkholm yep, I saw. But there is no any ETA and no information about prices. So it's too risky to stick with solution with so many unknown parts :( There are already some players on the market, so in case of cloud solution I would prefer to compare real numbers without any predictions.

connections capacity - ?
users capacity - ?
data storage capacity- ?
traffic capacity - ?

as you see - too many variables

**Comment by plandem** [comment]
@bmunkholm problem is not with ETA actually - I think you will be public this year :) More risky to choose solution without any idea about final prices and how it will scale.

**Comment by bmunkholm** [comment]
@plandem Sure, but you can expect to know at least pricing in Feb.

**Comment by bmunkholm** [comment]
But also just to be sure I fully understand your needs. The Electron app should also work on Linux?
Because you can build the Electron app for other Mac and Windows just fine and run ROS on AWS. It's only on Linux that the app would require a Pro edition (at the moment).

I would also be curious to understand your needs for the parameters you listed.

**Comment by plandem** [comment]
oh, I don’t need electron on linux. only mac and windows!

**Comment by plandem** [comment]
@bmunkholm so looks like I can stick with Realm, build for major platforms (iOS, Android, OSX, Windows) with sync via dedicated ROS at AWS with developer license. In that case that's ok. I'm looking forward for Realm Cloud, because as startup I would choose cloud solution with ability to move later at own server.
