### ISSUE TITLE
Throwing error when try to run any function under Realm

### ISSUE THREAD

**Issue by sanjeevmf** [realm/realm-js#1180]
console.log("Starting function");

// add your initialization code here

module.exports = function(changeEvent) {
    // event handler code goes here

    console.log("Changes in realm at:", changeEvent.path);

    var realm = changeEvent.realm;

    for (var className in changeEvent.changes) {
        var changes = changeEvent.changes[className];
        var objects = realm.objects(className);

        console.log("Changes in Model:", className);

        var i, pos;
        for (i = 0; i < changes.insertions.length; i++) {
            pos = changes.insertions[i];
            console.log("- object inserted at position", pos, ":", objects[pos]);
        }
        for (i = 0; i < changes.modifications.length; i++) {
            pos = changes.modifications[i];
            console.log("- object modified at position", pos, ":", objects[pos]);
        }
        for (i = 0; i < changes.deletions.length; i++) {
            pos = changes.deletions[i];
            console.log("- object deleted at position", pos);
        }
    }
    console.log("");
};

Following is the script which I try to run under Function but it throws error "We run into an issue trying to start My New Script".
Screenshot can be seen at https://ibb.co/c8kcLQ

**Comment by kneth** [comment]
@sanjeevmf Please try to restart server. If the issue persists, please send us the log.

**Comment by kneth** [comment]
@sanjeevmf Did restarting the server help?

**Comment by kneth** [comment]
@sanjeevmf I am closing the issue assuming that restarting the server helped.

**Comment by sanjeevmf** [comment]
@kneth Yes, we can close now. Restarting also works but I am using event hander now. Thanks
