### ISSUE TITLE
default.realm File size > 500M  wrong

### ISSUE THREAD

**Issue by nizhengzhou** [realm/realm-js#1185]
## Goals

I want to store more local data

 default.realm > 2G Or more

mmap() failed: Out of memory size: 1207959552 offset: 0

1    import Realm from 'realm';
2    class TestData {}
3   TestData.schema = {
4    name: 'TestData',
5     properties: {
6        id:  {type: 'int', optional: true},
7        base64Str:  {type: 'string', optional: true},
8    }
9   };
10 let realm = new Realm({schema: [TestData]});
11 for (let i=0; i<500;i++) {
12    realm.write(() => {
13            let testData = realm.create('TestData', {
14                base64Str:abc ,
15          });
16});

Using the android simulator  step :
1)The first run, the successful storage of 500M data 
2)Reopen the APP , Run to line 10 and throw an error, error msg:(mmap() failed: Out of memory size: 1207959552 offset: 0)

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.1
- Node or React Nattive: 0.46.4
- Client OS & Version: android

Please forgive me for my poor English 
I don't know what I should do next 
Should I switch to sqlite?

**Comment by nizhengzhou** [comment]
Correction, first run, successfully store 1G data

**Comment by kneth** [comment]
@nizhengzhou You could try to swap line 11 and 12. You can also try to add a call to [`close()`](https://realm.io/docs/javascript/1.10.0/api/Realm.html#close) at the end.

**Comment by nizhengzhou** [comment]
@kneth Thank you for your reply
try to swap line 11 and 12，try to add a call to close() at the end. run,Get the following error：
08-04 14:57:43.342 3896-3922/com.ohsadata.inspection E/ReactNativeJS: std::bad_alloc
08-04 14:57:43.398 3896-3922/com.ohsadata.inspection E/ReactNativeJS: undefined is not a function (evaluating 'this._lazyCallableModules[name]()')

**Comment by nizhengzhou** [comment]
I also found a very strange question.
The same code, such as:
------------------------------------
import Realm from 'realm';
class TestData {}
TestData.schema = {
    name: 'TestData',
    properties: {
        id:  {type: 'int', optional: true},
        base64Str:  {type: 'string', optional: true},
    }
};

let realm = new Realm({schema: [TestData]});

for (let i=0; i<500;i++) {
realm.write(() => {
	let testData = realm.create('TestData', {
		base64Str:abc ,
	});
});
}
realm.close();
------------------------------------
When run, report it directly：Out of memory size
But, I put the APP back in the background, and when I get back to the APP within a minute, everything is back to normal

**Comment by nizhengzhou** [comment]
On the mobile side, you should not use more than 1G of mobile db

**Comment by nizhengzhou** [comment]
@kneth 
After extensive testing, the default.realm size is stable and running around the 400M
Default. Realm size > = 500M, running new realm again ({schema: [TestData]}) will throw an exception: mmap () failed: Out of memory size
I estimate that it is likely to be related to the configuration of the vm heap, and if it is, when the actual user is using the vm heap, it is easy to throw Out the mmap () failed: Out of memory size
Can you help me, how to avoid the mmap () failed: Out of memory size?
My android simulator configuration:
Ram: 2000 MB
The vm heap: 456 MB
Internal stroage: 4000 MB
Sd card: studio - managed: 3000 MB

**Comment by nizhengzhou** [comment]
Different android devices, storage size may have certain difference, some can store some < > 500 m 500 m, and can run normally and use realm, I have a way to avoid the mmap () failed: Out of memory error of the size?
What I'm doing now is telling the user to store as much as 256M of data as much as possible, and storing more data will be abnormal.

**Comment by kneth** [comment]
Realm is using `mmap()` to load the objects from storage to memory. Both iOS and Android have some limitation on how much, you can `mmap()`. The exact value varies between models but I believe that you have been hit by it.

After restarting the app, do you have two instances of the app running? If you have, one instances will keep the old revision while the second one will keep adding revisions of the database without being able to reclaim the space. That will lead to large Realm files.

**Comment by nizhengzhou** [comment]
@kneth 
Thank you for your reply.
I seem to have a solution.
Use multiple scheminuses to store more data like this:
Const schemas = [
{schema: schema1, schema1:1},
{schema: schema2, schemo: 2},
...
]
...
While () {
Realm. Open (schemas [I])
Then (realm = > {
/ / execution logic, no realm. Close (), and make the next schemer
})
...
}
Each version stores a certain amount of data to avoid the mmap () failed: Out of memory size
Or specify multiple paths, execute the corresponding logic, fail to find the expectation, close, and try the next open
Realm. Open ({
Path: '*. Realm,
Schema: [schema]
}). Then (/ *... * /);

The difficulty is how to use which realm instance correctly

If the authorities provide the ability to automatically manage multiple realm functions and limit the size of each realm to a predetermined size, then a new realm is created, hoping to have such a function

**Comment by nizhengzhou** [comment]
Maybe I don't know, I'm sorry.
Basically, try multiple, each path stores a certain amount of data to avoid too large a single file, causing mmap () failed: Out of memory size,
Like this,
Realm. Open ({
Path: 'anotherRealm. Realm,
Schema: [CarSchema]
}). Then (/ *... * /);
If you implement multiple file automatic management and specify the size of each path, you want to have such a feature

**Comment by kneth** [comment]
@nizhengzhou Have you attached a debugger during your runs? If you have, you might end up with multiple instances of your app running. In that case, the staled instance (from first run) will keep an old version of the database, and the active instance will not be able to reclaim the memory used.

**Comment by nizhengzhou** [comment]
@kneth 
Local multiple versions, just a theory, no test.
After an internal discussion, the picture as a base64 storage is a kind of unwise choice, base64 performance.
I will change my logic, the picture changed to file storage, realm only l l path.
When the data is uploaded, the picture is converted to base64 for upload.
On mmap () failed: Out of memory size of the error, you can give me some suggestions? How to better use realm, to avoid the emergence of the problem?

**Comment by nizhengzhou** [comment]
@kneth 
English is not very good, thank you patiently answered my question

**Comment by kneth** [comment]
The limitations of `mmap()` is discussed in https://stackoverflow.com/questions/36669819/does-a-realm-table-have-a-size-limitation/. Realm JS does not yet have a compaction method (see #507 for details). For Android and iOS, you can typically `mmap()` 4-700 MB per process (see https://stackoverflow.com/questions/9184773/is-there-a-practical-limit-on-the-number-of-memory-mapped-files-in-ios/10004131).  

It is a good idea to store the picture on the file system and only store the path in Realm. Realm is not compressing data but does an efficient bit packaging.

**Comment by nizhengzhou** [comment]
@kneth Thanks again, I think I can close this question
