### ISSUE TITLE
Sorting list prop

### ISSUE THREAD

**Issue by jjdp** [realm/realm-js#1186]
Based on the js docs

```
let carList = person.cars;

// Add new cars to the list
realm.write(() => {
  carList.push({make: 'Honda', model: 'Accord', miles: 100});
  carList.push({make: 'Toyota', model: 'Prius', miles: 200});
});
```

Does this work `let sortedCarList = carList.sorted('miles')`? and also since you accessed the `cars` prop from `person`, does this still lazy load?

**Comment by kneth** [comment]
Yes, `sorted()` will also work and is updated in the same way as the unsorted list.
