### ISSUE TITLE
React.PropTypes deprecated warning

### ISSUE THREAD

**Issue by hellomaya** [realm/realm-js#1191]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
1.10.1

- Node or React Nattive: ?
React Native

- Client OS & Version: ?
iOS V10.2

- Which debugger for React Native: ?/None
None

The React.PropTypes is deprecated, and still appear in this file:

https://github.com/realm/realm-js/blob/master/react-native/listview.js

**Comment by kneth** [comment]
@hellomaya Thanks for reporting. The relevant documentation is https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes.
