### ISSUE TITLE
android build  fails on Node 8

### ISSUE THREAD

**Issue by blagoev** [realm/realm-js#1194]
investigate iOS build as well

**Comment by kneth** [comment]
Android builds seem to fail since local dependencies are created using symlinks. Prior node versions (at least 6.x) do it by copying.

**Comment by blagoev** [comment]
hm.. interesting. will see why would that matter if the symlinks are to the correct places.

**Comment by blagoev** [comment]
it seems it's not that prepublish thing only. Even with this fixed it still fails in  
bundleReleaseJsAndAssets with error:

Could not list contents of '/Users/username/realm/test-realm-local-tests/realm-js/tests/react-test-app/node_modules/realm/object-server-for-testing/object-server/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm.management/access_control.new_commit.cv'.

This is a locked file which RN tries to open and fails. On node 6.5.0 this does not fail. I will investigate more why that is.

**Comment by kneth** [comment]
Node 12 is required for building React Native apps.
