### ISSUE TITLE
RealmReactPackage.java:18: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by gsabatie** [realm/realm-js#1201]
## Goals
Run  application on an Android Device

## Actual Results
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':realm:compileReleaseJavaWithJavac'.

D:\GitHub\ProjectPushUP\node_modules\realm\android\src\main\java\io\realm\react\RealmReactPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^

## Steps to Reproduce

react-native run-android

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.1
- React Native: 0.47.1
- Client OS & Version: Windows 10 
- Which debugger for React Native: ?/None

**Comment by kristiandupont** [comment]
This was fixed with #1189 -- it will be included in the next release.
