### ISSUE TITLE
Hitting File Descriptor Limit even when Close is called

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-js#1202]
## Goals

I want to create several realms, insert data in them in a loop, and close them at the end of the close.

## Expected Results

I should not hit a file descriptor limit with opening several realms in a loop while calling close at the end of the loop.

## Actual Results

`Error: ENFILE: file table overflow`

## Steps to Reproduce

https://github.com/realm-demos/realm-js-playground/tree/max/loop

## Version of Realm and Tooling

- Realm JS SDK Version: See repo above
- Node or React Nattive: Node
- Client OS & Version:  MacOSX Sierra
- Which debugger for React Native: None

**Comment by nirinchev** [comment]
I'm not a js person, but looks like there's an error in the script - you shouldn't be declaring `const realm`, but rather `let realm`. After doing that and running the script, I was able to create 10k realms without an issue on my Mac and not hit a file descriptor problem.

**Comment by nirinchev** [comment]
My bad - it was the `"use strict"` that fixed the script, not changing the `const` to `let`.

**Comment by blagoev** [comment]
I did test it as well and seems working for me 
* with realm.close(); all 10k realms are created.

*without realm.close() ~ 1200 realms are created until an error of too many files opened is shown. An immediate run afterwards with realm.close() is successful  with 10k realms. 

@mbalex99 Did you try restarting your Mac and trying again?

**Comment by astigsen** [comment]
> without realm.close() ~ 1200 realms are created until an error of too many files opened is shown

Any idea why the garbage collector is not cleaning up the realms? I assume they a going out of scope after each iteration of the loop, so they should be closed automatically.

**Comment by fealebenpae** [comment]
Objects going our of scope are not going to cause collection. JavaScript is sadly not Swift.

The garbage collector kicks in very rarely. I expect that for a synthetic scenario like the repro here the GC wouldn't fire at all - unless the JavaScript heap is exhausted, Node.js will prefer to not GC to prevent the app from freezing while GC runs. And Realm objects have next to no weight in JavaScript so even if you open ten thousand realms, the GC will only see this as a few kilobytes on the JavaScript heap and go all "aw, no point in running".

**Comment by bdash** [comment]
We could conceivably use `AdjustAmountOfExternalAllocatedMemory` when allocating a `Realm` (or other wrappers around native types) to give V8's garbage collector an idea of the memory impact of such allocations. That would serve as something of a proxy for our use of other native resources, such as file handles.

**Comment by blagoev** [comment]
That is for v8 (android and nodejs only). It will help but it will not mitigate the issue, so a explicit close will be still required. Also isn't this specific scenario considered a bad practice and should be discouraged. (opening 10k realms in a loop). For the general scenario opening a bunch of realms not calling close should be fine for the majority of users.

**Comment by bdash** [comment]
> AdjustAmountOfExternalAllocatedMemory is for v8 (nodejs only)

Yes, that API is V8-only. JavaScriptCore's garbage collector supports a similar concept, but doesn't appear to expose it via its public API.

> It will help but it will not mitigate the issue, so a explicit close will be still required.

It doesn't remove the need to explicitly close a Realm, but it would make the impact of forgetting to do so less severe (the definition of mitigating the issue). It would also be beneficial for other expensive objects, such as `Results`, which are not explicitly finalized and could more plausibly accumulate in memory due to suboptimal user code.

**Comment by kristiandupont** [comment]
@mbalex99 I assume this is no longer P0? I'm removing the tag -- please restore it if I am mistaken.

**Comment by mbalex99** [comment]
Yeah I think we can decrease the severity but we should keep an eye out.
