### ISSUE TITLE
Build failing on Android

### ISSUE THREAD

**Issue by tusharv-bidchat** [realm/realm-js#1203]
## Goals

Build and Run project successfully

## Expected Results

Build Success

## Actual Results

RealmReactPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: RealmReactModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:realm:compileReleaseJavaWithJavac FAILED

## Steps to Reproduce

Create new react native project with latest version and add realm to it.
Try to build the project

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.1
- React Native: 0.47.1
- Android OS & Version: Marshmallow
- Which debugger for React Native: None

**Comment by kristiandupont** [comment]
This has been fixed in #1189 and will be included in the next release.

**Comment by tusharv-bidchat** [comment]
Thanks
