### ISSUE TITLE
Expose a generic authenticate method

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-js#1218]
## Goals

1. Expose the generic `authenticate` method that allows a user to hit ROS's custom authentication handler.
2. User should be able to post arbitrary JSON to receive back an auth token.
3. Keep existing `login` and `register` methods
4. Keep existing `loginWithProvider` and `registerWithProvider` methods but mark them as deprecated in favor of `authenticate`
5. Supply an optional callback method. If it is undefined, return a promise

This is in preparation for ROS 2.0

## Code Sample

```javascript
const json = {
     "myCompanyAppId": "somethingcool",
     "facebookId": "12345"
}
Realm.Sync.User.authenticate('http://localhost:9080', json)
   .then(user => console.log("good user")
   .catch(err => console.error(err))

// OR use the callback

Realm.Sync.User.authenticate('http://localhost:9080', json, (err, user) => {
    if(err) { console.error(err) }
    else { 
         console.log('welcome!')
    }
})
```

**Comment by nirinchev** [comment]
What is the reasoning behind this?

**Comment by mbalex99** [comment]
The New 2.0 has a generic json payload that it can accept. It doesn't make the distinction between logging in and registering.

Server side programmers can override a method in the AuthService called `authenticate` which nicely matches up with this API. 

In the new ROS 2.0, customers can do something like

```javascript
authenticate = (body: any) : Promise<{userId: string, isAdmin: boolean}> =>  {
      return new Promise((resolve, reject) => {
             MyCorporateSuperLegacyLogin(
                      body.app_id,
                      body.twoFactorAuth,
                      body.geoLocation,
                      body.corporateManifestoAgreement,
                      body.username,
                      body.ohYeahThePassword,
                      (err, myCorporateUser) => {
                             if (err) { reject(err) }
                             else { resolve({ myCorporateUser.userId, isAdmin: myCorporateUser.role === 'admin' }
                       }
                 )
         )
      })
}
```

**Comment by kneth** [comment]
@mbalex99 @nirinchev Does `Realm.Sync.User.authenticate` solves this issue?
