### ISSUE TITLE
Object is not a constructor on Typescript import * from "realm" 

### ISSUE THREAD

**Issue by CacaoRick** [realm/realm-js#1226]
Version:
- react-native: 0.47.1
- realm: 1.10.3

When use:

```javascript
import * as Realm from "realm"

new Realm({
	schema: [{ name: 'Dog', properties: { name: 'string' } }]
})

// or
Realm.open({
	schema: [{ name: 'Dog', properties: { name: 'string' } }]
})
.then((realm) => {...})
```

Will show error in red screen:

```text
Object is not a constructor (evaluating 'new Realm({
    schema: [{ name: 'Dog', properties: { name: 'string' } }]
})')

// or
Object is not a constructor (evaluating 'new _this(config)')
```
Change import to this type is no problem:
```javascript
import Realm from "realm"
```

But lose type intelligence and get ts error:

```text
Module ''realm'' has no default export.
```

Similar problems in stackoverflow
[Cannot open Realm using typescript 2.4.1 + react native 0.46.1 because Realm is not a constructor](https://stackoverflow.com/questions/45112877/cannot-open-realm-using-typescript-2-4-1-react-native-0-46-1-because-realm-is)

Thanks

**Comment by kneth** [comment]
@CacaoRick did you try any of the tricks in https://realm.io/docs/javascript/latest/#missing-realm-constructor

**Comment by CacaoRick** [comment]
Thanks @kneth
Bit I think this is not missing-realm-constructor problem, my react-native link work well.
And after I use `import Realm from "realm"`, my APP can be executed with no error.

Here is my realm.ts code to get realm instance with right type for typescript
```javascript
import Realm from "realm"
import * as RealmTypes from "realm"

const Meter: RealmTypes.ObjectSchema = {
    //...
}

const RecordData: RealmTypes.ObjectSchema = {
    //...
}

const Photo: RealmTypes.ObjectSchema = {
    //...
}

const realmConfiguration: RealmTypes.Configuration = { schema: [Meter, RecordData, Photo] }
const realm: RealmTypes = new Realm(realmConfiguration)
export default realm
```

Now it can be intelligence, but still show error `Module 'realm' has no default export.`

**Comment by kneth** [comment]
@CacaoRick Is your issue related to #884?

**Comment by CacaoRick** [comment]
I'm work in android.
But I test in iOS simulator will get same problem.
(Also just run react-native link, not configure podfile and run pod install)

**Comment by bang88** [comment]
@CacaoRick could you please add a config in `tsconfig.json`

```js
"allowSyntheticDefaultImports": true
```

**Comment by CacaoRick** [comment]
With `"allowSyntheticDefaultImports": true` in `tsconfig.json`

```javascript
import * as Realm from "realm"
```

App will show red screen and display error: `Object is not constructor`

Change import to:
```javascript
import Realm from "realm"
```

App work fine, but vscode will not intelligence and tslint show error 

```
Module "realm" has no default export.
```

Nothing change.

**Comment by bang88** [comment]
What version of your Realm types ?

```
"@types/realm": "^1.0.3",
```

Works fine for me.

**Comment by CacaoRick** [comment]
```
"realm": "^1.10.3",
"@types/realm": "^1.0.3",
```

**Comment by CacaoRick** [comment]
Maybe some problem in my tsconfig.json?

**Comment by CacaoRick** [comment]
Sorry my `allowSyntheticDefaultImports` not put in compilerOptions object.
`allowSyntheticDefaultImports` work fine with
```
import Realm from "realm"
```

**Comment by kneth** [comment]
@CacaoRick Not sure how to interpret you. Does it work for you?

**Comment by CacaoRick** [comment]
Yes allowSyntheticDefaultImports is work.
Thanks.
