### ISSUE TITLE
Yarn command failed

### ISSUE THREAD

**Issue by adyanced** [realm/realm-js#1231]
Yarn 'add', 'upgrade' command failed except 'remove'  

- React Nattive: 0.47.1
- Client OS & Version: Win10

I need upgrading other RN module running 'yarn upgrade xxx' and got this. Delete 'node_modules' , clear yarn cache has no effects. Unless remove realm can I upgrade other modules. 

[4/4] Building fresh packages...
████████████████████████████████████████████████████████████[1/2] ⠐ react-native-elements: ***
[2/2] ⠐ realm: not ok
[-/2] ⠐ waiting...
[-/2] ⠈ waiting...
error D:\new BLEHygrometer\node_modules\realm: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-pre-gyp install --fallback-to-build
Directory: D:\new BLEHygrometer\node_modules\realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@7.10.0 | win32 | x64
node-pre-gyp info check checked for "D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/1.10.3/realm-v1.10.3-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/1.10.3/realm-v1.10.3-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.10.3 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http socket hang up

D:\new BLEHygrometer\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.0 | win32 | x64
gyp info ok

D:\new BLEHygrometer\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node" --module_name=realm "--module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64" )  else (node "" configure --fallback-to-build "--module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node" --module_name=realm "--module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64" )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\new BLEHygrometer\\node_modules\\realm\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Richard\\.node-gyp\\7.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Richard\\.node-gyp\\7.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\new BLEHygrometer\\node_modules\\realm',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\new BLEHygrometer\\node_modules\\realm\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

D:\new BLEHygrometer\node_modules\realm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build "--module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node" --module_name=realm "--module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64" )  else (node "" build --fallback-to-build "--module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node" --module_name=realm "--module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64" )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.10.0 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã ��뽫��λ�����ӵ�ϵͳ·���С� [D:\new BLEHygrometer\node_modules\realm\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\new BLEHygrometer\\node_modules\\realm\\compiled\\node-v51_win32_x64\\realm.node" "--module_name=realm" "--module_path=D:\\new BLEHygrometer\\node_modules\\realm\\compiled\\node-v51_win32_x64"
gyp ERR! cwd D:\new BLEHygrometer\node_modules\realm
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm --module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\new BLEHygrometer\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\new BLEHygrometer\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\new BLEHygrometer\node_modules\realm
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64\realm.node --module_name=realm --module_path=D:\new BLEHygrometer\node_modules\realm\compiled\node-v51_win32_x64' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by nuocgansoi** [comment]
Same issue:
Windows 10, realm 1.10.3 (1.10.1 only have @Override error in RealmReactPackage.java)
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/1.10.3/realm-v1.10.3-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.10.3 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp)
...
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the
 .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to
 the system path if it is installed elsewhere.  [C:\NGS\Mobile\see\node_modules\realm\build\binding.sln]

**Comment by kneth** [comment]
@adyanced `static.realm.io` is hosted by AWS which is blocked in some countries. Does it an issue for you?

@nuocgansoi Did you install Visual C++ (the error message indicates that it is missing).

**Comment by adyanced** [comment]
@kneth But everything is okay till yesterday

**Comment by kneth** [comment]
@adyanced So it worked with earlier releases but not 1.10.3?

**Comment by adyanced** [comment]
No, before yesterday, 1.10.3 also works well. This issue comes no more than 3days .

**Comment by adyanced** [comment]
I tried to get file 'https://static.realm.io/node-pre-gyp/1.10.3/realm-v1.10.3-node-v51-win32-x64.tar.gz' manually and 404 error returned
![image](https://user-images.githubusercontent.com/6321512/29509204-0bfcae40-868a-11e7-96d6-b0457763356a.png)

**Comment by kneth** [comment]
@adyanced Thanks! I get the same error, and we need to investigate what is going on.

**Comment by fealebenpae** [comment]
Hey everyone, it turns out that during publishing 1.10.3 binaries on our CDN the Windows binaries were not uploaded so installing realm-js on Windows fell back to compiling from source. I just manually uploaded the binaries so you can try installing again.

**Comment by adyanced** [comment]
It works, thank you very much

**Comment by adyanced** [comment]
Hi, u upgrade to 1.11.0 today. But the same issue, file ‘https://static.realm.io/node-pre-gyp/1.11.0/realm-v1.11.0-node-v51-win32-x64.tar.gz' does not uploaded. Pls solve it, thanks

**Comment by kneth** [comment]
@adyanced We have a few issues with 1.11.0 so expect a new release later today.

**Comment by mirkoseifert** [comment]
I have a similar issue when running npm install for realm 2.6.0. I can't download:

https://static.realm.io/node-pre-gyp/2.6.0/realm-v2.6.0-node-v51-win32-x64.tar.gz

error message is:

404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: node-pre-gyp/2.6.0/realm-v2.6.0-node-v51-win32-x64.tar.gz
RequestId: 0CCE6FE0CFEBAE06
HostId: FB8/HtQgndB0EOPanujpZnVr6GPytdOuFWzKTspZIk39vj07G5BxuMGKxVc0McCSNwcfv9kVaK8=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: 404.html

What can I do about this?

**Comment by mirkoseifert** [comment]
Nevermind, I upgraded node to v8.11.2 and now it works.

**Comment by kneth** [comment]
@mirkoseifert Yes, we haven't got around node 10 yet 😢

**Comment by Vi-jay** [comment]
i got same issues , then i tried @mirkoseifert way change node version to fixed it

**Comment by mjstelly** [comment]
This is an issue once again. Please reopen it. I'm getting this
`node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwi
n-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.18.0 and node@10.11.0 (node-v64 ABI, unknown) (falling
back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-no
de-v64-darwin-x64.tar.gz`

**Comment by kneth** [comment]
@mjstelly We don't support node 10 but we are working on it.

**Comment by benhartouz** [comment]
Some issue with node version 11

**Comment by kneth** [comment]
@benhartouz We don't support node 11 yet. It is tracked by #2149.
