### ISSUE TITLE
 Predicate expressions must compare a keypath and another keypath or a constant value

### ISSUE THREAD

**Issue by cl1069573062** [realm/realm-js#1233]
class Message extends Realm.Object {}
Message.schema = {
  name: "Message",
  properties: {
    id: "string",
    messageId: "string",
    text: "string",
    time: "string",
    type: "string"
  }
};

  getMessage(id) {
    const messageId = id;
    return realm.objects("Message").filtered("id=" + messageId);
  }

if l use getMessage();
it will throw " Predicate expressions must compare a keypath and another keypath or a constant value" Exception

**Comment by kneth** [comment]
@cl1069573062 Any indication of what `messageID` is?

You are missing quotes around `messageId` i.e., `filtered('id = "' + messageID + '"');`

**Comment by bdash** [comment]
That'd probably be better written as `filtered('id = $0', messageID)` to avoid problems if the substituted value happens to contain double quote characters.

**Comment by cl1069573062** [comment]
@bdash  thanks that's work

**Comment by kneth** [comment]
Cool. I'll close the issue.
