### ISSUE TITLE
Unify admin token user as a normal user

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#1234]
Changes were made in [ROS](https://github.com/realm/realm-object-server/pull/773) to make the admin user be a normal user that is created on startup: `__auth`. As a result, the code path for the `User` should not be unique for admin users. Instead, an admin user should have the same ability to change permissions and other functionality.

**Comment by blagoev** [comment]
talked with @bigfish24 about moving this for later time

**Comment by alebsack** [comment]
@bigfish24 I think this is taken care of?

**Comment by bigfish24** [comment]
Yes
