### ISSUE TITLE
How to prevent creating realm-object-server folder?

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-js#1235]
When I launch my node app like `node app.js` everything is ok

When I'm trying to launch it like `node /nodes/someapp/app.js` it fails with error

    terminate called after throwing an instance of 'realm::util::File::PermissionDenied'
    what():  make_dir() failed: Permission denied

I guess that realm tries to create `realm-object-server` folder on every `require('realm')` right in `./` folder. So when I'm trying to launch my app from `/` realm tries to create that folder in `/`.

Looks like bug! Could you please fix it?

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.0
- Node or React Nattive: NodeJS 8
- Client OS & Version: Debian 9
- Which debugger for React Native: None

**Comment by kneth** [comment]
@MihaelIsaev Thanks for reporting.

**Comment by anysome** [comment]
Does this bug fixed?

**Comment by kneth** [comment]
@anysome We haven't been able to reproduce it.

**Comment by anysome** [comment]
Everything work fine in development. But the release version can't make dir for 'realm-object-server'.
#2236 Fixed the problem, maybe it should be documented.

**Comment by kneth** [comment]
Yeah, documenting the work-around would be a good idea.

**Comment by Eyesonly88** [comment]
I can reproduce this when using realm in a serverless function like from firebase cloud functions.
In firebase cloud functions, the functions use a read-only file system and only have a `/tmp` directory that can be used for writing to disk space. 

I've tried using process.chdir(/tmp) but still not overriding it.

This means I can't access a synced Realm from a firebase function 😢

**Comment by kneth** [comment]
@Eyesonly88 Do you get permission denied or a different error message?

**Comment by Eyesonly88** [comment]
@kneth I get permission denied.
Without being able to control where the `realm-object-server` folder is created, accessing a synced realm from a serverless function won't work (at least not in firebase cloud functions).

**Comment by Eyesonly88** [comment]
^ I tried that. It only set the local realm path. The `realm-object-server` folder was still created and not in the `defaultPath`.

**Comment by kneth** [comment]
In what order do you `process.chdir()` and `require('realm')`?

**Comment by Eyesonly88** [comment]
@kneth I did process.chdir() first and then require('realm')

**Comment by kneth** [comment]
@Eyesonly88 Please create a new issue with code to reproduce the issue.

**Comment by mithunph** [comment]
@Eyesonly88 Is the issue fixed now?

**Comment by TomGB** [comment]
@mithunph did you find an easy workaround?
I am trying to use `Realm.App({ id })` and `app.login(credentials)`  in an AWS Lambda.
And I am getting an error message for `make_dir()`

Is there a way to avoid creating the directory?
