### ISSUE TITLE
realm.syncSession always returns active

### ISSUE THREAD

**Issue by PvanHengel** [realm/realm-js#1239]
When calling realm.syncSession on a sync realm session, it always returns active.

To reproduce this issue setup a realm server and react native app.  

```
this.setState({ status:"Connected! " +JSON.stringify(user) });

        let realmConfig = {
            sync: {
                user: user,
                url: 'realm://localhost:9080/~/my-realm',
            },
            schema: [SyncTest]
        };

        let realm = new Realm(realmConfig);
        this.setState({ realm, status:"Open!" + user.identity });

        let testList = realm.objects('SyncTest');
        this.setState({ realm, dataSource: this.state.dataSource.cloneWithRows(testList) });

        testList.addListener(() => {
            let testList = realm.objects('SyncTest');
            this.setState({ realm, dataSource: this.state.dataSource.cloneWithRows(testList) });
            this.forceUpdate()
        });

        setInterval( function(){
            this.setState({ status:"Status: " + realm.syncSession.state + user.identity  });
        }.bind(this), 1000);
```

connect to the app for the first time, setup some records, then shut down the app, you will see the realm.syncSession.state always shows as active, it should flip to some sort of offline status.  Also somewhat related, is there a progress update callback that can be used to see if when offline if there are changes pending, and when online the progress of the sync?

**Comment by kneth** [comment]
About progress update: I guess that #794 is what you need. I hope we can wrap it up and release it soon.

What do you mean by "shut down the app"?  To narrow the search space, are you on Android or iOS?

**Comment by PvanHengel** [comment]
Thank you yes 794 looks like the progress.

By shut down the app I mean the realm server.  Basically I expect that it should show if it's connected or not.  Another option would be to go to airplane mode.  I could use the network API, however that doesn't cover cases where the server is down or network between other than cellular.  It's not clear to me what what it is actually reporting as active.  This is on iOS.

**Comment by kneth** [comment]
Currently we don't have an API which you can discover if you have lost connection with the server. However, it is on our wish list. From your description, it does sound like https://github.com/realm/realm-mobile-platform/issues/41.

**Comment by PvanHengel** [comment]
Yes sounds similar to that issue.   This and the progress update are critical to making sure users data is saved back to the server.   They sort of go hand in hand to make sure there is no loss of data, and also to help debug issues when users report they don't see their data elsewhere.  

The docs should be updated to reflect that the realm.syncSession.state doesn't do what one would think, and what exactly does it do?  Sometimes i see the status flash as "open" with the above code.

**Comment by kneth** [comment]
You will not have loss of data (if you do, it is a bug!). The local instance of objects will start sync'ing when the network connection is reestablished. For the time being, you might add some network connectivity check to your app if it is important to notify the user about it.

I agree, the documentation could be a bit more elaborate :smile:

**Comment by bmunkholm** [comment]
Perhaps create an issues for that @kneth ? ;-)

**Comment by kneth** [comment]
@PvanHengel May I close the issue?
