### ISSUE TITLE
document the sync error callback

### ISSUE THREAD

**Issue by blagoev** [realm/realm-js#1252]
The error callback is part of the sync configuration object

```JavaSciprt
const config = {
            sync: { user, url: `realm://localhost:9080/~/${realmName}`, 
              error: err => console.log(err) 
             },
            schema: [{ name: 'Dog', properties: { name: 'string' } }]
};

var realm = new Realm(config);
```

Still it is missing from the API documentation here:
https://realm.io/docs/javascript/1.10.0/api/Realm.html#~Configuration

[Update]
Also the website documentation should be updated to contain a sample for the sync configuration object and its properties.

**Comment by bigfish24** [comment]
@blagoev it is missing from the website documentation as well

**Comment by blagoev** [comment]
thanks I updated the issue comment.

**Comment by kneth** [comment]
Documentation: https://github.com/realm/realm.io/pull/3804

**Comment by kneth** [comment]
Where - and how - should we document the error codes and the categories?

**Comment by kneth** [comment]
I close the issue. There is a PR for the website too.
