### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by oximer** [realm/realm-js#1259]
```
 node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/1.10.1/realm-v1.10.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for realm@1.10.1 and node@6.9.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Linux 2.6.32-642.6.2.el6.x86_64
```

## Goals
 
Build my project

## Expected Results

Add realm dependency

## Actual Results

Network Timeout 

## Steps to Reproduce

Try to install it behind a proxy

## Code Sample

None

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.1
- Node or React Nattive: 4.5

I'm trying to build my project after adding Realm to it.
However, I have a problem with realm install script.
Different then the majority of npm dependencies, Realm download a binary from a external website while installing itself. However, my build server only allows connections to npm repository. I want you suggest you to change it.

I have more than 20 different dependencies no my project and Realm are the only one trying to do this kind of approach. 

>     "babel-eslint": "7.2.3",
>     "babel-jest": "20.0.0",
>     "babel-plugin-transform-remove-console": "6.8.4",
>     "babel-preset-react-native": "1.9.1",
>     "eslint-config-rallycoding": "3.2.0",
>     "eslint-plugin-react": "7.3.0",
>     "eslint-plugin-react-native": "3.0.1",
>     "git-guppy": "2.1.0",
>     "gulp": "3.9.1",
>     "gulp-eslint": "4.0.0",
>     "gulp-exec": "2.1.3",
>     "gulp-prettier-plugin": "1.0.0",
>     "guppy-pre-commit": "0.4.0",
>     "jest": "20.0.0",
>     "prettier": "1.5.3",
>     "react-test-renderer": "16.0.0-alpha.6",
>     "run-sequence": "2.1.0"
>    "base-64": "^0.1.0",
>     "gam-components": "0.0.11",
>     "gam-core-api": "0.0.16",
>     "gulp": "3.9.1",
>     "gulp-exec": "2.1.3",
>     "manuh": "0.1.2",
>     "node-forge": "0.7.0",
>     "react": "15.4.2",
>     "react-native": "0.41.2",
>     "react-native-camera": "0.9.4",
>     "react-native-device-info": "latest",
>     "react-native-drawer": "2.3.0",
>     "react-native-keyboard-spacer": "0.3.1",
>     "react-native-md-textinput": "2.0.4",
>     "react-native-progress": "3.2.0",
>     "react-native-swiper": "1.5.4",
>     "react-navigation": "1.0.0-beta.6",
>     "react-timer-mixin": "0.13.3",
>     "realm": "1.10.1",
>     "rhelena": "0.1.11",
>     "uuid": "3.1.0"

**Comment by blagoev** [comment]
Hi, 
The download of a binary on install is required because realm-js uses a node native addon. This addon has a binary build for every node version out there. If the binary can not be downloaded for a reason then this binary should be built locally on your machine from source. We are using node-pre-gyp [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) for that.

**Comment by fealebenpae** [comment]
I'm sorry, but because Realm has a C++ core we need to download precompiled binaries from our CDN `https://static.realm.io`. I'm afraid there's no way around that. Is it possible to add our CDN to your firewall's exceptions list?

**Comment by oximer** [comment]
I can add it to the exception list. A security team is responsible for it and the have restrict rules about downloading code on production build.
Any suggestion to work around it?

**Comment by fealebenpae** [comment]
We have a package of Realm for Node.js that includes all the precompiled binaries for macOS and Linux. We don't publish it on NPM because it's too big, but I suppose you can host it on a private npm registry server or even a plain HTTP server in your organization and reference it in your production `package.json`. The address is https://static.realm.io/node-pre-gyp/1.10.3/realm-1.10.3.tgz.

Do note that this is not an officially-supported distribution method, though, so use it at your own risk. I *strongly* urge you to contact your security team and whitelist the Realm CDN at https://static.realm.io.

**Comment by oximer** [comment]
@fealebenpae I think it will work. 
We have our own registry and I think I could submit it to them.
I will have to check with them, but it's seems a good alternative.

**Comment by oximer** [comment]
@fealebenpae if I add it to the my own registry, it will automatically stop trying to download it for static.realm.io?

**Comment by kneth** [comment]
@oximer You could give it another name?

**Comment by oximer** [comment]
Yes, I can give it another name.
Even that, it's not really clear how it will help me.

**Comment by kneth** [comment]
@oximer Maybe something like http://www.verdaccio.org/ could be useful for you. Disclaimer: I haven't tried it :smile:.

**Comment by kneth** [comment]
I am closing the issue since it is a out of the scope of a library like us.
