### ISSUE TITLE
Permission tests fail in Chrome debugging mode

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#1260]
The permission tests are currently disabled when running in the Chrome debugger.
For one reason or another, creating a permission object in the management realm and then monitoring for changes (the status code) never triggers a notification, causing the tests to hang.

I tried alleviating this with a poll via `setInterval`, but that didn't help as the `statusCode` field remains null even when the browser shows that it's been set. Whether this means that the opened realm is trapped in a transaction or not refreshed for some other reason, or because there is a bug in the property getter pipeline, I don't know. But it coincides with the listener not being triggered, which seems to rule out the latter.

**Comment by kneth** [comment]
The permission API has been removed in v10.0.0.
