### ISSUE TITLE
Compacting Realm in Node

### ISSUE THREAD

**Issue by eugenecp** [realm/realm-js#1261]
Hi, 

  Is there a way to compact realmdb on node? 
Unlike in java/ios there is no equivalent prototype for compactRealm in node.
Is there a script/linux binaries that can be called from node to do this instead for
the meantime?

thanks

**Comment by eugenecp** [comment]
Oh, I just see that there's a new uncompiled version (1.10.5) that have this enhancement.
I compiled it from source and its working now. 
Any date for the compiled release?

**Comment by kneth** [comment]
@eugenecp Happy to hear that you found it. I hope we can do a release this week.

**Comment by cliftonlabrum** [comment]
I know this is an old issue, but I don't see `compactRealm` anywhere in the Realm JS docs. Am I just not seeing it? Could someone show me how it is used?

**Comment by kneth** [comment]
@cliftonlabrum It's called [`compact`](https://realm.io/docs/javascript/latest/api/Realm.html#compact). You can also use the `shouldCompactOnLaunch` callback in the [configuration](https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration).

**Comment by cliftonlabrum** [comment]
Got it, thanks!
