### ISSUE TITLE
Encryption on Windows

### ISSUE THREAD

**Issue by eugenecp** [realm/realm-js#1262]
Hi,
  I am having this 
    Error: Encryption not enabled
 error on Node/Windows.

 Why is it not supported on Windows / Node?
 Will there be no problem using Linux / Node ?

Thanks

**Comment by kneth** [comment]
Encryption for node/Windows isn't supported yet, while node/Linux is supported (https://realm.io/docs/javascript/latest/#encryption).

Since Realm Core does support encryption on Windows, it shouldn't be too hard to enable it. We can't promise a release date for it.

**Comment by kneth** [comment]
I believe that we support encryption on Windows.
