### ISSUE TITLE
Realm is already in a write transaction

### ISSUE THREAD

**Issue by bleonard** [realm/realm-js#127]
<img width="1440" alt="screen shot 2015-11-09 at 10 48 15 pm" src="https://cloud.githubusercontent.com/assets/36106/11056228/70d9b8d2-8734-11e5-8f63-2df0bfed67ae.png">

debugging in chrome
hit command r a few times to refresh
it worked a few times, then crash above

**Comment by jayshah123** [comment]
One thing that tripped me up causing this error was using realm.write inside migration function, me not realizing that migration function is already running under write transaction by default,
thus causing to fail due to nesting of write transactions.

**Comment by huangtubiao** [comment]
I also get this same error, I try a lot of ways, but it is not work, is there a solution?

**Comment by evrimfeyyaz** [comment]
> One thing that tripped me up causing this error was using realm.write inside migration function, me not realizing that migration function is already running under write transaction by default,
> thus causing to fail due to nesting of write transactions.

This really tripped me up. It definitely should be documented.
