### ISSUE TITLE
creationAt must be of type: date

### ISSUE THREAD

**Issue by RiyasMeeran** [realm/realm-js#1270]
My api response JSON contains multiple date as string. Like this, `{
"creationAt" : "2012-04-21T18:25:43-05:00"
}`. When i try to create realm (`Realm.create()`) using this date string, it throws a error like `must be of type: date`.

Is there any default method in Realm to auto convert date string to Date? 

or any get;set; property like c#

**Comment by kneth** [comment]
Parsing JSON is not part of Realm, so you will need to deserialize the JSON to JavaScript objects using `JSON.parse()` and change the property `creationAt` to a `Date` object. Maybe something like

```
var obj = JSON.parse(your_json, function (key, value) {
    if (key == "creationAt") {
        return new Date(value);
    } else {
        return value;
    }
});
realm.create('YourObject', obj);
```

**Comment by RiyasMeeran** [comment]
Thanks,
  It works fine, More over if this function  implemented in your Realm, It could be more useful and avoid unwanted code.

**Comment by kneth** [comment]
@RiyasMeeran I fully understand that. Currently we are focused on getting up to the level of our other products (we lack a few functions).
