### ISSUE TITLE
Encryption makes it larger

### ISSUE THREAD

**Issue by eugenecp** [realm/realm-js#1272]
Hi,
   My node realm db , using the latest version when un-encrypted, compacted and zipped is about 3MB but if I add encryption this would grow to 14MB.  
Inspecting the unzip realm db, the un-encrypted would be about 14MB and the encrypted is about 140MB..

So.. why is this so?
Anything to shrink the encrypted realm db further?

Thanks

**Comment by kneth** [comment]
Typically a compression algorithm like the one used in zip, will try to find common data pattens. For example `AAAB` and `AAAC` both have `AAA` in common. An encrypted Realm file will not have such patterns, and zip will not be able to compress it. For an unencrypted Realm file, zip might be able to find strings with common substrings.

In general, we try to pack the data, and I doubt that you will see significant compression of Realm files.

**Comment by eugenecp** [comment]
HI,
  Lets forget the zipped file.

test 1.
new realm (with encryption)->for loop, add records ->200MB->compact->140MB

test 2.
new realm (no encryption)->for loop, add records ->30MB->compact->14MB

Now I download the test 2 realm file to my android app then call
the writeEncryptedCopyTo and produced an encrypted realm file with only 30MB size. 

So the missing piece is the nodejs writeEncryptedCopyTo enhancement that
may help in further reducing the realm size before sending it to the apps.

thanks..

**Comment by kneth** [comment]
@eugenecp And test 1 and 2 are using the same code (with and without encryption)?

@finnschiermer Can you explain why encryption will produce a much large Realm file?

**Comment by eugenecp** [comment]
I run a new test, and well sorry I think I messed up a little, so it's okay now.
The only thing left is with encryption being super slow. 
With no encryption: 2 second
With encryption: 2 minutes.

So maybe it's much slower in the for loop adding records with encryption enabled ?

And maybe if I started with no encryption and call writeEncryptedCopy at the end
will make it a little bit faster?

**Comment by kneth** [comment]
@eugenecp A factor of 60 sounds wrong. Our internal benchmarks have typically shown 10-30 % slower. Said that, it would be great if you create a new issue (with a little example).

If you start with no encryption and call `writeEncryptedCopy()`, you will have data unencrypted too. I would rather do something about the performance 😃

**Comment by kneth** [comment]
@eugenecp Do you still see a big slow-down when using encryption?

**Comment by kneth** [comment]
I am closing now. @eugenecp if you have any updates to share, don't hesitate to reopen.
