### ISSUE TITLE
Serializing and deserializing a User

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1276]
## Goals

In a multi process environment, like an electron app, it would be valuable to be able to pass users between processes in a serialized form.

## Expected Results

I would expect that when logging in to ROS and serializing the resulting user I would get an object as follows:

    Realm.Sync.User.register("http://localhost:9080", username, password, (err, user) => {
        const userString = JSON.stringify(user);
        // user === "{token: "...", identity: "some-username", server: "http://localhost:9080", isAdmin: false }"

This could be fixed by implementing a `toJSON` method on the `Realm.Sync.User` class: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

In addition to this, it would be valuable to create a `Realm.Sync.User` from a JSON representation. This could be implemented with a `fromJSON` method on the user.

## Actual Results

Serializing a Realm.Sync.User (`JSON.stringify(user)`) gives you the string representation of an empty object (`{}`) and the fields of a `User` are all implemented as getters that cannot be set.

## Steps to Reproduce

1. Login or register a user through the Realm Object Server.
2. Serialize the user using `JSON.stringify(user)`
3. Observe the disappointing result

## Code Sample

See "Expected Results"

## Version of Realm and Tooling

- Realm JS SDK Version: `2.0.0-rc5`

**Comment by ivanquirino** [comment]
a toJSON in realm objects and collections would be great. Useful for debugging and serialization support.
