### ISSUE TITLE
Sorting by sub objects with optional

### ISSUE THREAD

**Issue by RiyasMeeran** [realm/realm-js#1277]
Sorting by sub objects with optional property. 

```
//Example class
parent : [{
 firstChild : {
   secondChild:{
      startDate: 'new Date()'
  }
},
 firstChild:{
    secondChild: null
 },{
 firstChild: null
}]

realm.sorted('parent.firstChild.secondChild.startDate')
```

its return object not found error. how to solve this?

**Comment by kneth** [comment]
Currently you can only sort on a property - not on subobjects. See https://realm.io/docs/javascript/1.10.0/api/Realm.Collection.html#~SortDescriptor

**Comment by fukemy** [comment]
hi @RiyasMeeran , did u found any solution?
