### ISSUE TITLE
How to ccess realm-js realms from other native modules?

### ISSUE THREAD

**Issue by thatjuan** [realm/realm-js#1287]
Disclaimer: I tried StackOverflow but the question got [downvoted](https://stackoverflow.com/questions/45780501/how-to-use-realmswift-with-react-native) for not being "about programming" 🙄 

## Goals

I want to read/write to the same realm from both the JS context of React Native and from native modules. Specifically native modules written in Swift.

## Expected Results

I should be able to import RealmSwift from my React Native swift native module and be able to perform rw operations on the same realm I'm working with on the JS side of the app.

## Actual Results

The app crashes if RealmSwift is installed via CocoaPods. I also suspect I would have to use a RealmSwift distribution that matches the version of Realm Core that realm-js uses, and I'm unsure how to accomplish that.

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.3

**Comment by kneth** [comment]
We have an open issue on CocoaPods: #884.

**Comment by kneth** [comment]
I am closing as I believe #884 is tracking it.
