### ISSUE TITLE
relationship to many 

### ISSUE THREAD

**Issue by lossen** [realm/realm-js#1292]
Hello!
I have  two schemas: User and Client, and I try to do relationship to many between them.
Please tell me what am I doing wrong?
If I understand correctly, when I create a new client - clients field in User schema should update automatically?
Now clients field in User schema is empty although Client's are created.

```javascript 
class User {}
User.schema = {
    name: 'User',
    primaryKey: 'id',
    properties: {
        id: {type:'string',optional:true},
        firstName: {type:'string',optional:true},
        lastName: {type:'string',optional:true},
        email: {type:'string',optional:true},
        idToken: {type:'string',optional:true},
        accessToken: {type:'string',optional:true},
        refreshToken: {type:'string',optional:true},
        phone: {type:'int',optional:true},
        address: {type:'string',optional:true},
        lengthUnit: {type:'int',optional:true},
        weightUnit: {type:'int',optional:true},
        currency: {type:'string',optional:true},
        taxRate: {type:'int',optional:true},
        session: {type:'bool',optional:true},
        clients:{type: 'list', objectType: 'Client'}
    },
};
```

```javascript 
class Client {}
Client.schema = {
    name:'Client',
    primaryKey: 'id',
    properties: {
        medical_conditions:  {type:'string',optional:true},
        last_name:  {type:'string',optional:true},
        first_name:  {type:'string',optional:true},
        status:  {type:'string',optional:true},
        notes:  {type:'string',optional:true},
        DOB:  {type:'string',optional:true},
        phone_number:  {type:'int',optional:true},
        gender:  {type:'string',optional:true},
        trainer_id:{type:'string',optional:true},
        invite_code:{type:'string',optional:true},
        address:{type:'string',optional:true},
        id:  {type:'string',optional:true},
        email:{type:'string',optional:true},
        owners: {type: 'linkingObjects', objectType: 'User', property: 'clients'}
    },
}
```

**Comment by fealebenpae** [comment]
When you create a `Client` object you need to associate it with a user by calling `aUser.clients.push(client)`.

And no, it's the `Client.owners` field that will update automatically because it is the `linkingObjects` of the relationship described in `User.clients`.

Does this make sense?

**Comment by lossen** [comment]
Sorry, but I do not understand a few things.

In my reducer I do 
`import RealmModels from '../models/RealmModels';`

`export const createClient = (client) => (dispatch,getState) => {
  const state = getState(),
        token = state.user.idToken;
  if(token){
    RealmModels.write(() => {
      RealmModels.create('Client', {
        medical_conditions:  client.medical_conditions,
        last_name:  client.last_name,
        first_name:  client.first_name,
        status:  client.status,
        notes:  client.notes,
        DOB:  client.DOB,
        phone_number:  client.phone_number,
        gender:  client.gender,
        trainer_id:client.trainer_id,
        invite_code:client.invite_code,
        address:client.address,
        id:  uuid.v4(),
        email:client.email,
      });
    });
    return api.fetchCreateClient(token,client)
        .then((response) => response.json())
        .then((responseJson) => {
          dispatch(setClientInfo(responseJson.client))
        })
  }
}`

When I do User.clients.push(client) here, I get the error can't find variable User
How can I use User here? How should I connect User then to do push?

**Comment by kneth** [comment]
`User` is a class, and you will have to add the `client` object to an instance of `User`.
