### ISSUE TITLE
Typescript Binding Errors

### ISSUE THREAD

**Issue by nallick** [realm/realm-js#1296]
## Goals

Build a DataConnector, or even just a basic listener in node-js using TypeScript.

## Expected Results

Correct code should compile correctly.

## Actual Results

The TypeScript trans-compiler returns errors:
````
node_modules/realm/lib/index.d.ts(275,88): error TS2304: Cannot find name 'Permission'.
node_modules/realm/lib/index.d.ts(283,32): error TS2304: Cannot find name 'userId'.
node_modules/realm/lib/index.d.ts(284,32): error TS2304: Cannot find name 'metadataKey'.
node_modules/realm/lib/index.d.ts(284,45): error TS2374: Duplicate string index signature.
node_modules/realm/lib/index.d.ts(284,68): error TS2304: Cannot find name 'metadataValue'.
````

## Steps to Reproduce

Import realm into a typescript file and execute tsc on that file.

## Code Sample

Create a file _test.ts_ containing one line:
````
import * as Realm from "realm";
````

On the command line:
````
tsc test.ts
````

## Version of Realm and Tooling

- Realm JS SDK Version: 1.11.1
- Node or React Nattive: Node v8.4.0
- Client OS & Version: macOS 10.12.6
- Which debugger for React Native: None

**Comment by kneth** [comment]
@nallick We have merged a fix for it: https://github.com/realm/realm-js/pull/1285
And we hope to do a release later this week.
