### ISSUE TITLE
TypeScript bindings are missing the CHANGE_IDENTITY Instruction type

### ISSUE THREAD

**Issue by nallick** [realm/realm-js#1298]
## Goals

Build a DataConnector with TypeScript.

## Expected Results

Should be able to compile code that references all instructions.

## Actual Results

Can't compile code referencing the CHANGE_IDENTITY instruction type with error:
````
[ts] Type '"CHANGE_IDENTITY"' is not comparable to type '"INSERT" | "SET" | "DELETE" | "CLEAR" | "LIST_SET" | "LIST_INSERT" | "LIST_ERASE" | "LIST_CLEAR" ...'.
````

## Steps to Reproduce

https://realm.io/docs/javascript/latest/api/Realm.Sync.Adapter.html references an instruction called CHANGE_IDENTITY (at the bottom)

## Code Sample

````
import * as Realm from "realm";

class Test {}
    private processInstruction(instruction: Realm.Sync.Instruction) {
        if (instruction.type == "CHANGE_IDENTITY") {
            console.log("found CHANGE_IDENTITY");
        }
    }
}
````

## Version of Realm and Tooling

- Realm JS SDK Version: 1.11.1
- Node or React Nattive: Node v8.4.0
- Client OS & Version: macOS 10.12.6
- Which debugger for React Native: None

**Comment by kneth** [comment]
@nallick Thanks for reporting. Looks like an oversight from our side.

**Comment by kneth** [comment]
@nallick I have merged a fix, and I hope to do a release this week.
