### ISSUE TITLE
TypeScript binding errors

### ISSUE THREAD

**Issue by Bogidon** [realm/realm-js#1306]
This line throws the error:
`TS1016: A required parameter cannot follow an optional parameter.`
https://github.com/realm/realm-js/blob/eac393571dd3bcc1ba392ccff8c25f4a23a8e463/lib/index.d.ts#L454

You might want to move `progressCallback` to be the last argument, although it looks like it actually is the second argument in the js, which would be a breaking change: https://github.com/realm/realm-js/blob/7d25239fcc834503a5b6d4032b24e13f96eec1fc/lib/extensions.js#L79

In case the breaking change is intended, you'd probably want to make `progressCallback` nullable instead: 
```typescript
progressCallback: Realm.Sync.ProgressNotificationCallback | null
```

> **Sidenote**: it would be awesome if the typescript definitions were compiled during tests. I noticed a few similar issues.

**Comment by kneth** [comment]
@Bogidon Thanks for reporting.
