### ISSUE TITLE
Realm.Sync.User.adminUser() changed

### ISSUE THREAD

**Issue by alebsack** [realm/realm-js#1311]
In v2.0.0-rc7:
Instantiating an admin user now requires a server argument in `Realm.Sync.User.adminUser()`.  Providing even a blank value does not prevent the binding from connecting to ROS when calling `new Realm(...)`.  In ROS, this is a problem, since these services are not running yet.

When instantiating Realm, I get: `Error: Server for user must be specified`, `Error: Bad server URL` and other connection errors when providing dummy values to the `adminUser()` function.

**Comment by kneth** [comment]
@alebsack Current implementation:

`adminUser(token)` -> `createUser('', uuid, token, true)` (`uuid` is generated)

**Comment by fealebenpae** [comment]
It should call the new `Realm.Sync.User._adminUser` which created an Object Store admin user.

**Comment by kneth** [comment]
@fealebenpae Thanks.

**Comment by kneth** [comment]
The correct `adminUser()` is:

```
adminUser(token, server) {
  checkTypes(arguments, ['string', 'string']);
  return this._adminUser(server, token);
},
```

**Comment by kneth** [comment]
I believe that @alebsack can use the latest release candidate
