### ISSUE TITLE
debug issue

### ISSUE THREAD

**Issue by crazybits** [realm/realm-js#1324]
debug is stuck after trigger the following request,any hint?

> http://localhost:8082/create_session

**Comment by kneth** [comment]
Are you using RN 0.48? We have changed the port in https://github.com/realm/realm-js/pull/1326.

**Comment by crazybits** [comment]
@kneth  thanks for update, what do i need to change to use port 8083?

**Comment by crazybits** [comment]
btw, i am using react-native 0.44 and realmjs 1.10.0

**Comment by TGPSKI** [comment]
Greetings, I have a working implementation for Android.

Versions

OS: OSX 10.12.3 (16D32)
React Native: 0.48.4
Realm: 1.12.0 + Port update patch
Steps

Add a postinstall script to your package.json:
... 
"postinstall": "bash ./scripts/patch_realm_port.sh",
...
Add the project/scripts directory && touch patch_realm_port.sh
patch_realm_port.sh

#!/bin/bash

# android
perl -0777 -i -pe 's/(?mi-s)(private static final int DEFAULT_PORT = 8082;)/ private static final int DEFAULT_PORT = 8083;/g' "./node_modules/realm/android/src/main/java/io/realm/react/RealmReactModule.java"

# ios
perl -0777 -i -pe 's/(?mi-s)(#define WEB_SERVER_PORT 8082)/#define WEB_SERVER_PORT 8083/g' "./node_modules/realm/android/src/main/java/io/realm/react/RealmReactModule.java"
Run yarn install on your root dir

Build android release

IMPORTANT: run the following adb commands

adb reverse tcp:8081 tcp:8081
adb forward tcp:8082 tcp:8082
adb forward tcp:8083 tcp:8083
Start node server

Launch android debugger & run

**Comment by TGPSKI** [comment]
@kneth : any chance we could get a build from source guide for Realm android? 

I am struggling to see how one can reference both an outdated NDK and a current NDK in the compilation steps, and have not been able to link the .aar generated from the realm-js/react-native/android/ && ./gradlew assembleDebug or ./gradlew assembleRelease.

I tried a lot of different things, but ended up giving up and using this patch above while NPM remains out of date.

Here's one attempt I made. This script clones realm-js, clones submodules (not possible with yarn), builds the android aar, and then copies it into the react-native android project. From here, I am unclear as to how to use this precompiled version of Realm while compiling the react native app with an up-to-date NDK.

```bash
## PATCH REALM SUB-MODULES until NPM / YARN CAN BE UPDATED
## RE: android dev support for Realm

START_DIR=$(pwd)
if [ ! -d "latest_realm" ]; then
  echo ""
  echo "Realm-js #f8f6661fe21b0abf8c876f1cef0a45ece85d5145 not present. Cloning repo & submodules."
  echo ""
  git clone git://github.com/realm/realm-js.git latest_realm && cd latest_realm
  git checkout f8f6661fe21b0abf8c876f1cef0a45ece85d5145
  git submodule update --init --recursive
  cd ./react-native/android
  ANDROID_NDK=~/Library/Android/sdk/ndk-bundle-r10e ./gradlew assembleDebug
  ANDROID_NDK=~/Library/Android/sdk/ndk-bundle-r10e ./gradlew assembleRelease
  cd ./build/outputs/aar
  cp ./android-debug.aar "${START_DIR}/android/libs/realmDebug.aar"
  cp ./android-release.aar "${START_DIR}/android/libs/realmRelease.aar"
  cd ../../../../../../
else
  echo ""
  echo "Realm f8f6661fe21b0abf8c876f1cef0a45ece85d5145 present"
  echo ""
fi
```

**Comment by kneth** [comment]
Building for Android is `gradlew publishAndroid`. And yes, NDK r10e is required as Realm Core is built with NDK r10e.

**Comment by TGPSKI** [comment]
Yes, all good. However, my question is pre-building the aar (with r10e) whose output I could use with a modern NDK version for the rest of the build.

How do you integrate the output of `gradlew publishAndroid` into the existing react native project? The NDK used in the rest of the build is from 2017. 

Also, the generated files from `gradlew publishAndroid` do not match the directory structure thats is compiled when installing realm-js from NPM. Is this expected?

**Comment by kneth** [comment]
@TGPSKI We are currently working on upgrading NDK - Realm Java has the lead on that.

If you do `./gradlew installArchives`, you can find the `aar` file under `$HOME/.m2/repository/io/realm/react/realm-react-native`
