### ISSUE TITLE
Provide onUploadCompletion callback

### ISSUE THREAD

**Issue by blagoev** [realm/realm-js#1329]
The current progress api is not convenient enough when the user is interested only on a final callback on upload finished. We should provide such API which is already supported by the underlying sync implementation

**Comment by bmunkholm** [comment]
Align with what's done in other SDK's.

**Comment by bmunkholm** [comment]
@blagoev Only ONE "T:" label please :-)

**Comment by kneth** [comment]
* Realm Java: https://realm.io/docs/java/3.7.2/api/io/realm/SyncSession.html#uploadAllLocalChanges--
* Realm Cocoa: N/A
* Realm .NET: https://realm.io/docs/xamarin/1.6.0/api/reference/Realms.Sync.Session.html#Realms_Sync_Session_WaitForUploadAsync

**Comment by bmunkholm** [comment]
@kneth Was this completed?

**Comment by kneth** [comment]
@bmunkholm No, but you can still use the progress listener for it. I think it is trivial to write a wrapper. Realm Java provides a blocking method which I am not a huge fan of.

**Comment by bmunkholm** [comment]
Ok, So we should keep this issue then for a convenience wrapper.

**Comment by nirinchev** [comment]
Just a heads up - there are actually two different native methods - one gives you progress, the other just invokes a callback when upload/download completes. In .NET we expose both and I think it's a better approach than to write a wrapper around the progress one.

**Comment by kneth** [comment]
You can use `Realm.App.Sync.Session.uploadAllLocalChanges()` (https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.Sync.Session.html).
