### ISSUE TITLE
Invalid UTF-8 detected

### ISSUE THREAD

**Issue by rubengarciam** [realm/realm-js#1331]
Hi there, I'm trying to manually backup a realm database. It's a simple process:

1. Read the file with [react-native-fs (readFile)](https://github.com/itinance/react-native-fs#readfilefilepath-string-encoding-string-promisestring). Default encode is utf-8 (alternatives: ascii or base64)
2. Feed that output to an upload cloud service function.

Step 1 fails with the _invalid UTF-8 detected_ (or _invalid continuation byte_), even if the realm instance contains no data, just the data models / schema. 

Using realm 1.12.0.

Any thoughts? Many thanks

**Comment by kneth** [comment]
Are you on Android or iOS? Does the error message contain any info about the string, for example the bytes?

**Comment by rubengarciam** [comment]
Unfortunately nothing meaningful, happy to share the realm db if you'd like to do any specific tests. 

iOS 11
react native 0.48.1

**Comment by kneth** [comment]
You can send the Realm file to help@realm.io - please use "Realm JS issue 1331" as subject.

Sometimes custom keyboard and emoji collections mess up string.

**Comment by ashwinphatak** [comment]
@rubengarciam Realm database files have a binary format. Have you tried using 'base64' encoding? 

I was able to create a copy of a realm db file using `readFile` and `writeFile` with 'base64' encoding.

**Comment by kneth** [comment]
I close the issue for now. If you have updated to shared, don't hesitate to reopen the issue.

**Comment by rubengarciam** [comment]
Sorry for taking so long to reply (away due to personal issues).

I've tried @ashwinphatak suggestion but that doesn't seem to work on my end. I'll elaborate on what I'm doing (probably something wrong?):

1. Need to backup the realm.database in a Cloud Storage Provider (i.e. Dropbox) to restore it sometime in the future
2. Reading its contents using react-native-fs.readFile() fails (invalid UTF-8 detected)
3. Reading its contents with base64 encoding works file > file uploaded
...
4. Download the file and read its contents, again with base64 encoding
5. (over)Write the original file, using writeFile with no encoding value
6. The file restored still requires an encryption key (realm considers it is encoded)

**Comment by kneth** [comment]
Our underlying storage engine (Realm Core, https://github.com/realm/realm-core) is `mmap`ing Realm files. So if you don't close all instances before copying/restoring, I can easily image you will see corruptions.

It is better if you use `writeFile` to create the backup (no instances open). Maybe you can draw some inspiration from https://realm.io/docs/java/latest/#faq-backup-restore.

**Comment by rubengarciam** [comment]
Thanks @kneth I didn't manage to get it working, I always got the same issue.

Nevertheless, I've spin a realm object server, reconfigured the project to sync to it and got it properly syncing. I was trying to avoid having a backend object server but seems the only way to move forward.

Cheers
