### ISSUE TITLE
Freeze UI when getting list on navigate ComponentDidMount

### ISSUE THREAD

**Issue by Arunkumar-Precise** [realm/realm-js#1334]
When trying to get a list of objects on navigate ComponentDidMount **UI freeze (android and ios)**. Even in release build.

How to solve this? 
or 
How to show loading while getting list of object?

**Comment by kneth** [comment]
We need a like more context to have a chance to help. You deleted the issue template (https://github.com/realm/realm-js/blob/master/.github/ISSUE_TEMPLATE.md) which otherwise asks for the relevant items.
