### ISSUE TITLE
"require() must have a single string literal argument" (React Native 0.49)

### ISSUE THREAD

**Issue by rh389** [realm/realm-js#1342]
It seems the version of `metro-bundler` used for `react-native@0.49-rc.5` chokes during transformation on any instance of `require` called with a variable argument, specifically: https://github.com/realm/realm-js/blob/f8f6661fe21b0abf8c876f1cef0a45ece85d5145/lib/index.js#L23 and https://github.com/realm/realm-js/blob/f8f6661fe21b0abf8c876f1cef0a45ece85d5145/lib/user-methods.js#L25

I haven't found a cross-platform solution, but for anyone looking for a quick fix I've hacked around it for RN only at https://github.com/rh389/realm-js-flat / `yarn add realm@rh389/realm-js-flat` (I've had to flatten git submodules to allow npm/yarn to work directly from github).

## Version of Realm and Tooling

- Realm JS SDK Version: master
- Node or React Native: React native 0.49.0-rc.5
- Client OS & Version: N/A
- Which debugger for React Native: Chrome

**Comment by rh389** [comment]
I've just spotted that this is addressed by https://github.com/realm/realm-js/pull/1332

**Comment by ashwinphatak** [comment]
Fix merged into master.
