### ISSUE TITLE
Segmentation fault when passing unexpected user object to sync

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1348]
## Goals

Passing unexpected arguments to the `Realm.open`, specifically passing a promise as `user` on the `sync` config object.

## Expected Results

An error message describing the issue.

## Actual Results

     Segmentation fault: 11

## Steps to Reproduce

Create a new directory, initialize an npm package and install Realm JS

    npm init && npm install realm

And then run the code sample.

## Code Sample

    const Realm = require("realm");

    Realm.open({
      sync: {
        user: Promise.resolve()
      }
    });

## Version of Realm and Tooling

- Realm JS SDK Version: 2.15.3
- Node or React Native: Node v8.4.0
- Client OS & Version: Mac 
- Which debugger for React Native: None

**Comment by kneth** [comment]
I imagine that parameter validation in JavaScript can be hard, while TypeScript we are stricter (see for example https://github.com/realm/realm-js/blob/2.0.x/lib/index.d.ts#L347).

**Comment by roberhofer** [comment]
@kneth , @kraenhansen : is this still an outstanding issue? Should this be part of the Robustification effort?

**Comment by kraenhansen** [comment]
I just reproduced this crash with the latest Realm JS (v2.15.3) and updated the description to match this. As to @kneth's comment above, TypeScript parameter validation doesn't exist at runtime, so that won't help our users much.

**Comment by kneth** [comment]
We should go through [`populate_sync_config`](https://github.com/realm/realm-js/blob/master/src/js_sync.hpp#L905) to see if we can add more validation to avoid situation like this.

**Comment by kneth** [comment]
Released in v11.10.0
