### ISSUE TITLE
Lazily enable SyncManager

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#1351]
When Node evaluates `const Realm = require("realm");` it creates the `/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm`

According to @bdash this is because:
>`SyncManager::shared().configure_file_system(…)` is called within `SyncClass<T>::create_constructor`
>Cocoa uses a bottleneck function that all accesses to `SyncManager::shared()` go through which take care of ensuring that `configure_file_system` is called. This lets the initialization happen lazily, but ensures it always happens.

This has caused problems in tests where you want to clean the local state. However, if you delete `realm-object-server` directory after `const Realm = require("realm");` you will get `mkdir` errors since the code expects the `io.realm.object-server-utility` exists.

**Comment by kneth** [comment]
A fix has been merged
