### ISSUE TITLE
different Realm.Object add  Realm.List contain the same primaryKey object 

### ISSUE THREAD

**Issue by aliyoge** [realm/realm-js#1352]
```javascript
class IMUser extends Realm.Object {}
IMUser.schema = {
  name: 'IMUser',
  primaryKey:'id',
  properties: {
    id: {type: 'string'},
    msg:{type: 'string'},
  },
};

class UserData extends Realm.Object {}
UserData.schema = {
  name: 'UserData',
  primaryKey:'id',
  properties: {
    id: {type: 'int'},
    list:{type: 'list', objectType:'IMUser'},
  },
};

let imuser1 = realm.create('IMUser', {id: 1, msg: "examplea111111"});
UserData1.lists.push(imuser1);

let imuser2 = realm.create('IMUser', {id: 1, msg: "examplea22222"});
UserData2.lists.push(imuser2);
```

This give me:

```
Error: Attempting to create an object of type 'IMUser' with an existing primary key value 'not implemented
```

UserData1 and UserData2 are different user , them may have the same friend with id '1' and with defferent msg.

How can i make different UserData.list not use different IMUser schema?

**Comment by kneth** [comment]
When `IMUser` has a primary key, no objects can have the same value. Or said differently, for a given value of `id`, you can have zero or one `IMUser` object with that value. If two objects can have the same `id`, you cannot use `id` as a primary key.

Currently, Realm does only support single property primary keys.

For a deeper discussion of primary and unique keys, please take a look at https://en.wikipedia.org/wiki/Unique_key

**Comment by aliyoge** [comment]
@kneth 

Sorroy, I didn't make myself clear.

The problem is that I have different `UserData`, but `IMUser` in them's list saved in the same schema.

```javascript
let imuser1 = realm.create('IMUser', {id: 1, msg: "examplea111111"});
let imuser2 = realm.create('IMUser', {id: 1, msg: "examplea22222"});
```

I want to make `imuser1` and `imuser2` not in the same schema.

Is it possible that different  @`UserData.lists` are different schema.

**Comment by kneth** [comment]
If `imuser1` and `imuser2` have to be in to separate schemas, you will have to create two `IMUser` schema definitions (`IMUser1` and `IMUser2`). But that feels wrong, and I think you need to create a data model where either `id` is not a primary key or use another property as primary key.
