### ISSUE TITLE
App getting crash when debugging with realm

### ISSUE THREAD

**Issue by vishram2997** [realm/realm-js#1378]
Bugs: App is getting close when open debug in react native with realm

## Goals

I am trying to create a App in react native which use realm to store data locally and I need to use debug for some investigation and development

## Expected Results

It should run in debug mode without any issue.

## Actual Results

App get closed as soon I open debug.
Error message on emulator "app is closed"

## Steps to Reproduce

1. Create a react native project with 0.48 version and use realm 1.12.0 version then try to debug your app.
2.  Import Realm from 'realm';

## Code Sample

No code ,standard bug

## Version of Realm and Tooling

- Realm JS SDK Version: 1.12.0
- Node or React Native: React Native
- Client OS & Version: Android 6 marshmallow 23.0.1 google_api
- Which debugger for React Native: chrome debugger

**Comment by blagoev** [comment]
Hi thanks for reporting. This is already fixed and will be included in the next version of Realm JS that is about to be released soon.

Cheers
