### ISSUE TITLE
Support iOS7 if possible

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#138]
Right now we only support iOS8 as we use embedded dynamic libraries. If it's possible to support iOS7 we should as this is what ReactNative defaults to.

**Comment by ios122** [comment]
support iOS7,I can use Now; otherwise, I must find something instead!

**Comment by appden** [comment]
@alazier we should confirm, but it's possible we've been supporting iOS 7 since switching to use a static library. :smile:

**Comment by fealebenpae** [comment]
As of https://github.com/facebook/react-native/commit/07553d0f1c61173edad804c4e7a93c902719e05b React Native requires iOS 8.0.
