### ISSUE TITLE
#include <realm/sync/client.hpp> not found 

### ISSUE THREAD

**Issue by bang88** [realm/realm-js#1385]
## Expected Results
XCode build success

## Actual Results
Xcode build failed

## Version of Realm and Tooling

- Realm JS SDK Version: latest 
- Node or React Native: latest
- Client OS & Version: latest
- Which debugger for React Native: ?/None

I try to remove node_modules but no lucky. the error still there.

**Comment by kneth** [comment]
@bang88 The `README.md` is not so clear but you will have to run the script `scripts/download-realm.js` before you can build.

**Comment by bang88** [comment]
Hi @kneth when i run the command an error appear.

```sh
$ node download-realm.js
(node:98187) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: end of central directory record signature not found
(node:98187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kneth** [comment]
Are you able to access https://static.realm.io?

**Comment by bang88** [comment]
Yes, I have downloaded the realm-node files, but the error are the same the client file not found

**Comment by bang88** [comment]
I have try it in another empty project and the error are same as the old one. I have checked the downloaded files but can not found the file:

```sh
#include <realm/sync/client.hpp> // Not found .

```

**Comment by kneth** [comment]
You need to specify which platform, etc. you download for:

     node scripts/download-realm.js --platform mac --arch x64 --sync

**Comment by bang88** [comment]
Does not work. Where can i find `realm/sync/client.hpp` I can copy it manually.

**Comment by bang88** [comment]
@kneth Do you know how to fix this problem. I can do nothing unless this problem has gone. Thanks.

**Comment by kneth** [comment]
@bang88 Can you explain how the download script doesn't work? Any error message?

**Comment by bang88** [comment]
@kneth No errors. just can not compile it via XCode.

**Comment by pekq** [comment]
The script fails without errors. Can we do manually what it supposed to do?  
I'm realmjs `2.0.0-rc19` & node `v8.0.0`  
@bang88 Maybe you found a workaround?

**Comment by kneth** [comment]
node 8 might be a bad choice: https://github.com/realm/realm-js/blob/master/README.md#building-realm

As I recall, node 8 is symlinking instead of copying so you end up with cycle in your file system.

**Comment by bang88** [comment]
@pekq Before I switch to `rc19` I was using 1.x and the error still there and then I try to install the rc version and relink it it works. don't know why 😢 . this problem spending me hours and with no lucky.

My node version is `v8.6.0`, you can try to update and reinstall realm.  anyway I want use the `1.x` stable version but now I have to use the rc version until `realm` release the `2.0.0`.

**Comment by kneth** [comment]
@bang88 With 2.0 released, I would like to know if we can close the issue?

**Comment by bang88** [comment]
Yep.  No problem with this version
