### ISSUE TITLE
Documentation on query support

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#1389]
realm-cocoa offers an [NSPredicate cheatsheet](https://academy.realm.io/posts/nspredicate-cheatsheet/) and [much more detailed information](https://realm.io/docs/swift/latest/#queries) in the docs on how to use the query language. Given that realm-js' query language is based off NSPredicate, we should make clear what is and isn't supported.

**Comment by kneth** [comment]
The query language of JS is currently very limited and is [briefly documented](https://realm.io/docs/javascript/latest/#filtering).

**Comment by bigfish24** [comment]
My point in filing this is that the documentation needs to improve. Something similar to Realm-Cocoa is needed.

**Comment by kneth** [comment]
See https://github.com/realm/realm.io/pull/4272
