### ISSUE TITLE
Custom local file system path not respected

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-js#1392]
When using `Realm.open()`, a sync session is opened on behalf of the default Realm, i.e., the Realm at the default path. Apparently, this is true even when one specifies a custom file system path for the local Realm.

<details>
<pre>
Opening Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: WebSocket::Websocket()
Connection[1]: Reconnecting in 0 milliseconds
Connection[1]: Session[1]: Starting session for '/home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse'
Connection[1]: Session[1]: last_version_available  = 4
Connection[1]: Session[1]: progress_server_version = 0
Connection[1]: Session[1]: progress_client_version = 0
Using already open Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: Session[1]: Progress handler called, downloaded = 0, downloadable = 0, uploaded = 0, uploadable = 0, progress version = 0, snapshot version = 4
Connection[1]: Resolving 'localhost:9080'
Connection[1]: Connecting to endpoint '127.0.0.1:9080' (1/1)
Connection[1]: Connected to endpoint '127.0.0.1:9080' (from '127.0.0.1:45068')
Connection[1]: WebSocket::initiate_client_handshake()
Connection[1]: WebSocket::handle_http_response_received()
Connection[1]: Will emit a ping in 600000 milliseconds
Connection[1]: Session[1]: Sending: BIND(server_path='/4875a3b9bc07346ae7d5222b285a9708/lasse', signed_user_token_size=641, need_file_ident_pair=0)
Connection[1]: Session[1]: Sending: IDENT(server_file_ident=1, client_file_ident=2, client_file_ident_secret=5956816676923783173, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
Using already open Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: Session[1]: Sending: MARK(request_ident=1)
Download message compression: is_body_compressed = 0, compressed_body_size=0, uncompressed_body_size=47
Connection[1]: Session[1]: Received: DOWNLOAD(scan_server_version=1, scan_client_version=0, latest_server_version=1, latest_server_session_ident=9027494610096638549, latest_client_version=0, downloadable_bytes=23, number_of_changesets=1)
Using already open Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: Session[1]: 1 remote changeset integrated, producing client version 5
Using already open Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: Session[1]: Progress handler called, downloaded = 23, downloadable = 23, uploaded = 0, uploadable = 0, progress version = 1, snapshot version = 5
Connection[1]: Session[1]: Received: MARK(request_ident=1)
Closing Realm file: /home/kristian/js_test/realm-object-server/32da58ab-c3e2-4d08-bd70-35d6763a148d/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2Flasse
Connection[1]: Session[1]: Sending: UNBIND
Number of dogs: 0
Opening Realm file: /home/kristian/js_test/lasse_query.realm
Connection[2]: WebSocket::Websocket()
Connection[2]: Reconnecting in 737 milliseconds
Connection[2]: Session[2]: Starting session for '/home/kristian/js_test/lasse_query.realm'
Connection[2]: Session[2]: last_version_available  = 5
Connection[2]: Session[2]: progress_server_version = 1
Connection[2]: Session[2]: progress_client_version = 2
Using already open Realm file: /home/kristian/js_test/lasse_query.realm
Connection[2]: Session[2]: Progress handler called, downloaded = 0, downloadable = 0, uploaded = 23, uploadable = 23, progress version = 0, snapshot version = 5
Connection[2]: Resolving 'localhost:9080'
Connection[2]: Connecting to endpoint '127.0.0.1:9080' (1/1)
Connection[2]: Connected to endpoint '127.0.0.1:9080' (from '127.0.0.1:45076')
Connection[2]: WebSocket::initiate_client_handshake()
Connection[2]: WebSocket::handle_http_response_received()
Connection[2]: Will emit a ping in 600000 milliseconds
Connection[2]: Session[2]: Sending: BIND(server_path='/4875a3b9bc07346ae7d5222b285a9708/lasse', signed_user_token_size=641, need_file_ident_pair=0)
Connection[2]: Session[2]: Sending: IDENT(server_file_ident=1, client_file_ident=4, client_file_ident_secret=8898786207131975687, scan_server_version=1, scan_client_version=2, latest_server_version=1, latest_server_session_ident=9027494610096638549)
Using already open Realm file: /home/kristian/js_test/lasse_query.realm
Download message compression: is_body_compressed = 0, compressed_body_size=0, uncompressed_body_size=0
Connection[2]: Session[2]: Received: DOWNLOAD(scan_server_version=1, scan_client_version=2, latest_server_version=1, latest_server_session_ident=9027494610096638549, latest_client_version=2, downloadable_bytes=0, number_of_changesets=0)
Using already open Realm file: /home/kristian/js_test/lasse_query.realm
Using already open Realm file: /home/kristian/js_test/lasse_query.realm
Connection[2]: Session[2]: Progress handler called, downloaded = 0, downloadable = 0, uploaded = 23, uploadable = 23, progress version = 1, snapshot version = 6
</pre>
</details>
<br/>
 
According to @bdash , 
> https://github.com/realm/realm-js/blob/master/src/js_realm.hpp#L707-L710 — the config that it uses within `wait_for_download_completion` doesn’t have the path populated even if it’s set on the passed-in config

See also https://realmio.slack.com/messages/C04R271HS.

**Comment by bdash** [comment]
Fixed by #1402.
