### ISSUE TITLE
can I add/remove sync capabilities freely to a realm?

### ISSUE THREAD

**Issue by Talor-A** [realm/realm-js#1400]
## Goals

In my app, syncing to a server is a 'premium' feature. essentially, users can create a local realm database to store app data but backing up requires a subscription. because of this, whether a realm should be synced or not can change at any time. I've seen the docs on migrating a local realm to a synced one, but it seems like it will add a lot of complexity to go back and forth. is there a simple way to, for example, set up a synced realm but not give it a sync address? or would this involve connecting to a custom auth server of some sort and checking if the user has a subscription, then syncing manually?

- Realm JS SDK Version: 1.13.0
- Node or React Native: React Native
- Client OS & Version: n/a
- Which debugger for React Native: None

**Comment by Talor-A** [comment]
update on this: to solve this problem, could I just revoke the user's read/write permissions on the synced realm, and this would prevent their changes to the local DB from being persisted to the server? or will this prevent modification of the local realm as well?

and I've gone through the docs and API reference and it appears there's no way to start/stop syncing to the realm server. is this a feature that could be implemented?

**Comment by bmunkholm** [comment]
Hey @Talor-A 
Yeah I can this being a great use case for enable/disable of sync. Right now we don't have that feature, but it's something we have on the backlog. We are primarily focused on adding features that doesn't have a workaround at the moment, so for now you would unfortunately have to copy to the local/synced realm. You should not try any of the workarounds of not being connected or revoke write access. The reason being that all indivudual changes done to the Realm in "sync" mode accumulates in a list, so that it eventually can be synced to the server. That would just take up more space than if you use a local realm.

**Comment by Talor-A** [comment]
Thanks a lot @bmunkholm I'll go with that solution. Hope to see manual sync as a feature in a future version though 👍

**Comment by meetakshay99** [comment]
@Talor-A How did you finally solved this problem?

**Comment by chris-houston** [comment]
@Talor-A Do you know if this feature or something similar has been created since the time of this post? I am interested in the same thing.

**Comment by bmunkholm** [comment]
@chris-houston Sorry to say that this isn't a featured we have added yet. So you will have to go for the manual approach for now. But I'll reopen this issue.

**Comment by kneth** [comment]
I have fixed the URLs in the download script - see https://github.com/realm/realm-js/pull/2630. Building from source without sync should soon be possible :smile:.

**Comment by nguyen-tam** [comment]
@Talor-A can you please share what difficulty did you have when do manual sync?

**Comment by Talor-A** [comment]
@nguyen-tam  we never found a solution to this problem and I’m no longer on the team building that project. Sorry, best of luck

**Comment by fronck** [comment]
This issue will be addressed by #4331, which provides the ability to convert Realms to/from Sync in a consistent manner.
