### ISSUE TITLE
Linear migrations code in docs throws error on first run

### ISSUE THREAD

**Issue by ashwinphatak** [realm/realm-js#1410]
## Goals

Setting up linear migrations for a RN app as documented here: https://realm.io/docs/javascript/latest/#linear-migrations

## Expected Results

Migrations are run properly and the realm is ready to use.

## Actual Results

On the very first run, the app crashes with an error "Unable to open a realm at path '.management'. Please use a path where your app has read-write permissions."

![image](https://user-images.githubusercontent.com/14833/31529446-f838c790-aff6-11e7-9bb2-7f5d723995a4.png)

## Steps to Reproduce

First run of the example code at https://realm.io/docs/javascript/latest/#linear-migrations on a device.

## Code Sample

```
const schemas = [
  { schema: schema1, schemaVersion: 1, migration: migrationFunction1 },
  { schema: schema2, schemaVersion: 2, migration: migrationFunction2 },
  ...
]

// the first schema to update to is the current schema version
// since the first schema in our array is at
let nextSchemaIndex = Realm.schemaVersion(Realm.defaultPath);
while (nextSchemaIndex < schemas.length) {
  const migratedRealm = new Realm(schemas[nextSchemaIndex++]);
  migratedRealm.close();
}

// open the Realm with the latest schema
Realm.open(schemas[schemas.length-1]);
```

## Debugging / Suggested Fix

This error occurs because on first install, the Realm file doesn't exist and `Realm.schemaVersion(Realm.defaultPath)` returns -1, messing up the `while` loop. 

Suggested fix:

replace 

`let nextSchemaIndex = Realm.schemaVersion(Realm.defaultPath);` 

with 

`let nextSchemaIndex = Math.max(0, Realm.schemaVersion(Realm.defaultPath));`

## Version of Realm and Tooling

- Realm JS SDK Version: 1.13.0
- Node or React Native: RN
- Client OS & Version: Ubuntu 16.04 LTS
- Which debugger for React Native: None

**Comment by cbush** [comment]
Fixed by https://github.com/realm/realm.io/pull/4655 .
