### ISSUE TITLE
Jest tests: 'return' outside of function

### ISSUE THREAD

**Issue by bang88** [realm/realm-js#1422]
## Goals
When i run jest test component should not have errors.

## Expected Results
No errors

## Actual Results
```js
 28 | if ('REALM_DISABLE_ANALYTICS' in process.env) {
        29 |     module.exports = function(){};
      > 30 |     return;
           |     ^
        31 | }
        32 |
        33 | const os = require('os');
```

## Version of Realm and Tooling

- Realm JS SDK Version: latest
- Node or React Native: latest
- Client OS & Version: latest
- Which debugger for React Native: ?/None

**Comment by ashwinphatak** [comment]
@bang88 Could you fill in the steps to reproduce this issue?

**Comment by bang88** [comment]
I will test it later.

**Comment by bang88** [comment]
@ashwinphatak The problem are still there.

Just run `jest` test your js files if one of them imports `realm`. I have update `realm` to `2.0.1`.

**Comment by ashwinphatak** [comment]
@bang88 I can't reproduce the issue in a test project. Can you check if this code works for you?

Realm import in test file:
https://github.com/ashwinphatak/RealmIssue1422/blob/master/__tests__/App.js#L5

Test run:
![image](https://user-images.githubusercontent.com/14833/31926010-c94f9790-b8a9-11e7-8416-841828a056f3.png)

**Comment by bang88** [comment]
@ashwinphatak I tested like you said. here is my tests file 

`import Realm from 'realm';`

just one line code

errors:

```sh
$ yarn test -o
yarn run v1.2.1
$ jest -o
 FAIL  src/models/__tests__/index.js
  ● Test suite failed to run

    /Users/bang/dev/apps/myapp/node_modules/realm/lib/submit-analytics.js: 'return' outside of function (30:4)
        28 | if ('REALM_DISABLE_ANALYTICS' in process.env) {
        29 |     module.exports = function(){};
      > 30 |     return;
           |     ^
        31 | }
        32 |
        33 | const os = require('os');

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.08s
Ran all test suites related to changed files.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ashwinphatak** [comment]
Unfortunately, I can't reproduce it when running `yarn test` either. Could you upload a minimal RN project which reproduces the issue?

**Comment by bang88** [comment]
I can't reproduce it using your repo. Maybe something wrong with my code. I will check it later. 😢

**Comment by EJohnF** [comment]
@bang88 by the end, have you figured it out? I have the same problem

**Comment by bang88** [comment]
@EJohnF Not yet. 😢

**Comment by EJohnF** [comment]
@bang88 try to modify your package.json:
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(realm)/"
    ]
}

it helps me

**Comment by brascene** [comment]
@EJohnF wow and thank you very much, ignoring `"node_modules/(realm)/"`helped me resolve _return outside of function_ error!

**Comment by donni106** [comment]
Sadly I came across the same problem. Adding `realm` to the `transformIgnorePatterns` did not worked for me.

`FAIL  tests/App.test.js
  ● Test suite failed to run

    /Users/u/Development/project/app/node_modules/realm/lib/submit-analytics.js: 'return' outside of function (30:4)
        28 | if ('REALM_DISABLE_ANALYTICS' in process.env) {
        29 |     module.exports = function(){};
      > 30 |     return;
           |     ^
        31 | }
        32 | 
        33 | const os = require('os');`

**Comment by dkpalmer** [comment]
I also just ran into the _'return' outside of function_ error, ironically _after_ I added `realm` to `transformIgnorePatterns` while trying to resolve another error (`SyntaxError: Unexpected token import`).

```

**Comment by dkpalmer** [comment]
I was able to resolve the issue with the following in `.babelrc`:

```
"parserOpts": {
  "allowReturnOutsideFunction": true,
},
```
