### ISSUE TITLE
IMPORTANT: if you see this error, please send this log to help@realm.io.

### ISSUE THREAD

**Issue by xll503721** [realm/realm-js#1425]
[realm-core-2.8.6] Assertion failed: additive || (required_changes = ObjectStore::schema_from_group(read_group()).compare(schema)).empty()
0   jjyy                                0x000000010d94472f _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   jjyy                                0x000000010d944ad0 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 445
2   jjyy                                0x000000010d85661b _ZN5realm5Realm13update_schemaENS_6SchemaEyNSt3__18functionIFvNS2_10shared_ptrIS0_EES5_RS1_EEEb + 2331
3   jjyy                                0x000000010d86ea87 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 5623
4   jjyy                                0x000000010d854d46 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 198
5   jjyy                                0x000000010d71c1e0 _ZN5realm2js10RealmClassINS_3jsc5TypesEE19create_shared_realmEPK15OpaqueJSContextNS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedIPK13OpaqueJSValueEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_IPSJ_EESO_NSF_INSP_ISQ_SZ_EEEEEE + 192
6   jjyy                                0x000000010d71784a _ZN5realm2js10RealmClassINS_3jsc5TypesEE11constructorEPK15OpaqueJSContextP13OpaqueJSValuemPKPKS8_ + 10042
7   jjyy                                0x000000010d70bd62 _ZN5realm3jsc10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructEPK15OpaqueJSContextP13OpaqueJSValuemPKPKSA_PSD_ + 66
8   JavaScriptCore                      0x0000000112453c8d _ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE9constructEPNS_9ExecStateE + 445
9   JavaScriptCore                      0x000000011256148a vmEntryToNative + 310
10  JavaScriptCore                      0x00000001123b8c36 _ZN3JSC11Interpreter16executeConstructEPNS_9ExecStateEPNS_8JSObjectENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListENS_7JSValueE + 502
11  JavaScriptCore                      0x000000011210e7c2 _ZN3JSC17profiledConstructEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListES3_ + 178
12  JavaScriptCore                      0x00000001124b3656 JSObjectCallAsConstructor + 390
13  jjyy                                0x000000010d8e460c _ZN5realm2js8FunctionINS_3jsc5TypesEE9constructEPK15OpaqueJSContextRKP13OpaqueJSValuemPKPKS8_ + 60
14  jjyy                                0x000000010d8e408a _ZZN5realm3rpc9RPCServerC1EvENK3$_2clEN8nlohmann10basic_jsonINSt3__13mapENS5_6vectorENS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEbxdSB_EE + 666
15  jjyy                                0x000000010d8e3dae _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServerC1EvE3$_2SB_EEESB_DpOT_ + 126
16  jjyy                                0x000000010d8e3c70 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServerC1EvE3$_2NS_9allocatorIS5_EEFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS6_IcEEEEbxdS6_EESH_EEclEOSH_ + 64
17  jjyy                                0x000000010d8ff824 _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EESB_EEclESB_ + 180
18  jjyy                                0x000000010d8ff73a _ZZN5realm3rpc9RPCServer15perform_requestENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEERKN8nlohmann10basic_jsonINS2_3mapENS2_6vectorES8_bxdS6_EEENK4$_11clEv + 74
19  jjyy                                0x000000010d8ff6e4 _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServer15perform_requestESA_RKSB_E4$_11EEESB_DpOT_ + 52
20  jjyy                                0x000000010d8ff320 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServer15perform_requestENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKN8nlohmann10basic_jsonINS_3mapENS_6vectorESA_bxdS8_EEE4$_11NS8_ISI_EEFSF_vEEclEv + 48
21  jjyy                                0x000000010d8d393a _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 138
22  jjyy                                0x000000010d8d35d0 _ZNSt3__120__packaged_task_funcINS_8functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS9_EEvEEENS9_ISE_EESD_EclEv + 64
23  jjyy                                0x000000010d8b8052 _ZNSt3__113packaged_taskIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 914
24  jjyy                                0x000000010d8b755f _ZN5realm3rpc9RPCWorker12try_run_taskEv + 191
25  jjyy                                0x000000010d8cdf67 _ZZN5realm3rpc9RPCWorkerC1EvENK3$_0clEv + 55
26  jjyy                                0x000000010d8cdca5 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm3rpc9RPCWorkerC1EvE3$_0EEEEEPvSC_ + 517
27  libsystem_pthread.dylib             0x0000000115bbf93b _pthread_body + 180
28  libsystem_pthread.dylib             0x0000000115bbf887 _pthread_body + 0
29  libsystem_pthread.dylib             0x0000000115bbf08d thread_start + 13
IMPORTANT: if you see this error, please send this log to help@realm.io.
Thread name: 
/Users/it/Documents/newdemo/jjyy/node_modules/realm/src/object-store/src/shared_realm.cpp:448: [realm-core-2.8.6] Assertion failed: additive || (required_changes = ObjectStore::schema_from_group(read_group()).compare(schema)).empty()
0   jjyy                                0x000000010d94472f _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   jjyy                                0x000000010d944ad0 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 445
2   jjyy                                0x000000010d85661b _ZN5realm5Realm13update_schemaENS_6SchemaEyNSt3__18functionIFvNS2_10shared_ptrIS0_EES5_RS1_EEEb + 2331
3   jjyy                                0x000000010d86ea87 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 5623
4   jjyy                                0x000000010d854d46 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 198
5   jjyy                                0x000000010d71c1e0 _ZN5realm2js10RealmClassINS_3jsc5TypesEE19create_shared_realmEPK15OpaqueJSContextNS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedIPK13OpaqueJSValueEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_IPSJ_EESO_NSF_INSP_ISQ_SZ_EEEEEE + 192
6   jjyy                                0x000000010d71784a _ZN5realm2js10RealmClassINS_3jsc5TypesEE11constructorEPK15OpaqueJSContextP13OpaqueJSValuemPKPKS8_ + 10042
7   jjyy                                0x000000010d70bd62 _ZN5realm3jsc10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructEPK15OpaqueJSContextP13OpaqueJSValuemPKPKSA_PSD_ + 66
8   JavaScriptCore                      0x0000000112453c8d _ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE9constructEPNS_9ExecStateE + 445
9   JavaScriptCore                      0x000000011256148a vmEntryToNative + 310
10  JavaScriptCore                      0x00000001123b8c36 _ZN3JSC11Interpreter16executeConstructEPNS_9ExecStateEPNS_8JSObjectENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListENS_7JSValueE + 502
11  JavaScriptCore                      0x000000011210e7c2 _ZN3JSC17profiledConstructEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListES3_ + 178
12  JavaScriptCore                      0x00000001124b3656 JSObjectCallAsConstructor + 390
13  jjyy                                0x000000010d8e460c _ZN5realm2js8FunctionINS_3jsc5TypesEE9constructEPK15OpaqueJSContextRKP13OpaqueJSValuemPKPKS8_ + 60
14  jjyy                                0x000000010d8e408a _ZZN5realm3rpc9RPCServerC1EvENK3$_2clEN8nlohmann10basic_jsonINSt3__13mapENS5_6vectorENS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEbxdSB_EE + 666
15  jjyy                                0x000000010d8e3dae _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServerC1EvE3$_2SB_EEESB_DpOT_ + 126
16  jjyy                                0x000000010d8e3c70 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServerC1EvE3$_2NS_9allocatorIS5_EEFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS6_IcEEEEbxdS6_EESH_EEclEOSH_ + 64
17  jjyy                                0x000000010d8ff824 _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EESB_EEclESB_ + 180
18  jjyy                                0x000000010d8ff73a _ZZN5realm3rpc9RPCServer15perform_requestENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEERKN8nlohmann10basic_jsonINS2_3mapENS2_6vectorES8_bxdS6_EEENK4$_11clEv + 74
19  jjyy                                0x000000010d8ff6e4 _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServer15perform_requestESA_RKSB_E4$_11EEESB_DpOT_ + 52
20  jjyy                                0x000000010d8ff320 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServer15perform_requestENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKN8nlohmann10basic_jsonINS_3mapENS_6vectorESA_bxdS8_EEE4$_11NS8_ISI_EEFSF_vEEclEv + 48
21  jjyy                                0x000000010d8d393a _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 138
22  jjyy                                0x000000010d8d35d0 _ZNSt3__120__packaged_task_funcINS_8functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS9_EEvEEENS9_ISE_EESD_EclEv + 64
23  jjyy                                0x000000010d8b8052 _ZNSt3__113packaged_taskIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 914
24  jjyy                                0x000000010d8b755f _ZN5realm3rpc9RPCWorker12try_run_taskEv + 191
25  jjyy                                0x000000010d8cdf67 _ZZN5realm3rpc9RPCWorkerC1EvENK3$_0clEv + 55
26  jjyy                                0x000000010d8cdca5 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm3rpc9RPCWorkerC1EvE3$_0EEEEEPvSC_ + 517
27  libsystem_pthread.dylib             0x0000000115bbf93b _pthread_body + 180
28  libsystem_pthread.dylib             0x0000000115bbf887 _pthread_body + 0
29  libsystem_pthread.dylib             0x0000000115bbf08d thread_start + 13
IMPORTANT: if you see this error, please send this log to help@realm.io.2017-10-21 17:29:13.918205+0800 jjyy[1494:15968] /Users/it/Documents/newdemo/jjyy/node_modules/realm/src/object-store/src/shared_realm.cpp:448: [realm-core-2.8.6] Assertion failed: additive || (required_changes = ObjectStore::schema_from_group(read_group()).compare(schema)).empty()
0   jjyy                                0x000000010d94472f _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   jjyy                                0x000000010d944ad0 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 445
2   jjyy                                0x000000010d85661b _ZN5realm5Realm13update_schemaENS_6SchemaEyNSt3__18functionIFvNS2_10shared_ptrIS0_EES5_RS1_EEEb + 2331
3   jjyy                                0x000000010d86ea87 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 5623
4   jjyy                                0x000000010d854d46 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 198
5   jjyy                                0x000000010d71c1e0 _ZN5realm2js10RealmClassINS_3jsc5TypesEE19create_shared_realmEPK15OpaqueJSContextNS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedIPK13OpaqueJSValueEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_IPSJ_EESO_NSF_INSP_ISQ_SZ_EEEEEE + 192
6   jjyy                                0x000000010d71784a _ZN5realm2js10RealmClassINS_3jsc5TypesEE11constructorEPK15OpaqueJSContextP13OpaqueJSValuemPKPKS8_ + 10042
7   jjyy                                0x000000010d70bd62 _ZN5realm3jsc10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructEPK15OpaqueJSContextP13OpaqueJSValuemPKPKSA_PSD_ + 66
8   JavaScriptCore                      0x0000000112453c8d _ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE9constructEPNS_9ExecStateE + 445
9   JavaScriptCore                      0x000000011256148a vmEntryToNative + 310
10  JavaScriptCore                      0x00000001123b8c36 _ZN3JSC11Interpreter16executeConstructEPNS_9ExecStateEPNS_8JSObjectENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListENS_7JSValueE + 502
11  JavaScriptCore                      0x000000011210e7c2 _ZN3JSC17profiledConstructEPNS_9ExecStateENS_15ProfilingReasonENS_7JSValueENS_13ConstructTypeERKNS_13ConstructDataERKNS_7ArgListES3_ + 178
12  JavaScriptCore                      0x00000001124b3656 JSObjectCallAsConstructor + 390
13  jjyy                                0x000000010d8e460c _ZN5realm2js8FunctionINS_3jsc5TypesEE9constructEPK15OpaqueJSContextRKP13OpaqueJSValuemPKPKS8_ + 60
14  jjyy                                0x000000010d8e408a _ZZN5realm3rpc9RPCServerC1EvENK3$_2clEN8nlohmann10basic_jsonINSt3__13mapENS5_6vectorENS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEbxdSB_EE + 666
15  jjyy                                0x000000010d8e3dae _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServerC1EvE3$_2SB_EEESB_DpOT_ + 126
16  jjyy                                0x000000010d8e3c70 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServerC1EvE3$_2NS_9allocatorIS5_EEFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS6_IcEEEEbxdS6_EESH_EEclEOSH_ + 64
17  jjyy                                0x000000010d8ff824 _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EESB_EEclESB_ + 180
18  jjyy                                0x000000010d8ff73a _ZZN5realm3rpc9RPCServer15perform_requestENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEERKN8nlohmann10basic_jsonINS2_3mapENS2_6vectorES8_bxdS6_EEENK4$_11clEv + 74
19  jjyy                                0x000000010d8ff6e4 _ZNSt3__128__invoke_void_return_wrapperIN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEE6__callIJRZN5realm3rpc9RPCServer15perform_requestESA_RKSB_E4$_11EEESB_DpOT_ + 52
20  jjyy                                0x000000010d8ff320 _ZNSt3__110__function6__funcIZN5realm3rpc9RPCServer15perform_requestENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKN8nlohmann10basic_jsonINS_3mapENS_6vectorESA_bxdS8_EEE4$_11NS8_ISI_EEFSF_vEEclEv + 48
21  jjyy                                0x000000010d8d393a _ZNKSt3__18functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 138
22  jjyy                                0x000000010d8d35d0 _ZNSt3__120__packaged_task_funcINS_8functionIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS9_EEvEEENS9_ISE_EESD_EclEv + 64
23  jjyy                                0x000000010d8b8052 _ZNSt3__113packaged_taskIFN8nlohmann10basic_jsonINS_3mapENS_6vectorENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEbxdS8_EEvEEclEv + 914
24  jjyy                                0x000000010d8b755f _ZN5realm3rpc9RPCWorker12try_run_taskEv + 191
25  jjyy                                0x000000010d8cdf67 _ZZN5realm3rpc9RPCWorkerC1EvENK3$_0clEv + 55
26  jjyy                                0x000000010d8cdca5 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm3rpc9RPCWorkerC1EvE3$_0EEEEEPvSC_ + 517
27  libsystem_pthread.dylib             0x0000000115bbf93b _pthread_body + 180
28  libsystem_pthread.dylib             0x0000000115bbf887 _pthread_body + 0
29  libsystem_pthread.dylib             0x0000000115bbf08d thread_start + 13
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by baloran** [comment]
What append?

**Comment by kneth** [comment]
@xll503721 It is hard to say anything meaningful from a stack trace. But it looks like you try to open a Realm file in additive mode (sync?) and have destructive changes (for example removing a property) in you schema.

**Comment by kneth** [comment]
I am closing the issue.

@xll503721 Please fill out our issue template and reopen the issue.
