### ISSUE TITLE
'realm/util/optional.hpp' file not found

### ISSUE THREAD

**Issue by luisbar180492** [realm/realm-js#1427]
Hi everybody!, I have an error with realm-js. I have the next modules installed:
```
    "native-base": "^2.3.3",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.0",
    "react-native-navigation": "^1.1.250",
    "realm": "^2.0.1"
```
It works on Android but it does not work on iOS, I linked realm for both platform and I checked and realm has been linked correctly but on ios the build fails. Thank you! and sorry for my broken English.

**Comment by rh389** [comment]
If you see anything in your build logs about a failing `Download Core` step or a `download-realm` script you might have the same issue I had: https://github.com/realm/realm-js/issues/1424

TL;DR: Xcode runs node script when building, which relies on some gyp binaries. It's important that xcode is using the same node version as you used to `npm install` or `yarn add` realm.

**Comment by kneth** [comment]
Version 2.1.0 should have improved the situation.
