### ISSUE TITLE
using realm object with linking objects in the schema crashes react-navigation

### ISSUE THREAD

**Issue by Talor-A** [realm/realm-js#1432]
## Goals

pass a reference to a realm object as a param with react-navigation
## Expected Results

the item should appear as props for the next screen
## Actual Results

app crashes instantly

## Steps to Reproduce

1. set up react-navigation and realm
2. pass an item as a param to the next screen in a stackNavigator:
```js
              onPress={() => this.props.navigation.navigate('TodoView', { todo: TodoFromRealm })}
```
3. if the object has `linkingObjects` in its schema, the app will crash even if no items link to it. 

## Code Sample

sample schema: 
```js
const TaskSchema = {
  name: 'Task',
  primaryKey: 'id',
  properties: {
    title: { type: 'string' },
    id: { type: 'string', indexed: true },
    done: { type: 'bool', default: false },
    parent: { type: 'Task' },
    children: {
      type: 'linkingObjects',
      objectType: 'Task',
      property: 'parent'
    },
  },
}
```
removing the `parent` and `children` properties of the schema will fix the issue.

## Version of Realm and Tooling

- Realm JS SDK Version: 1.13.0
- Node or React Native: react-native 0.47.2
- Client OS & Version: Android 8 & iOS 11
- Which debugger for React Native: None

**Comment by ashwinphatak** [comment]
@Talor-A I'm able to successfully pass a realm object as a react-navigation param in a test project. Can you see if the example works for you too?

https://github.com/ashwinphatak/RealmIssue1432

![image](https://user-images.githubusercontent.com/14833/31995414-e4d69826-b9a1-11e7-99c4-ae0f4d65e479.png)

https://github.com/ashwinphatak/RealmIssue1432/blob/master/src/Screen1.js#L17

![image](https://user-images.githubusercontent.com/14833/31995420-ea4ba94a-b9a1-11e7-88d9-5a30e54b11a9.png)

**Comment by kneth** [comment]
I am closing the issue. I hope that the comment above help you to sort it out. If not, don't hesitate to reopen the issue.
