### ISSUE TITLE
Upgrade from realm 2.0.0 to 2.0.1 file not found /index_set.cpp:21:10: 'realm/util/assert.hpp' 

### ISSUE THREAD

**Issue by esutton** [realm/realm-js#1433]
/node_modules/realm/src/object-store/src/index_set.cpp:21:10: 'realm/util/assert.hpp' file not found

     iOS
    "react": "~15.4.1",
    "react-native": "0.42.3",
    "realm": "^2.0.1",

Installed using **yarn add realm**

A debug scheme build runs in simulator with no problems.  

## Work Around

`yarn add realm@2.0.0`

or

`yarn add realm@1.13.0
`

**Comment by kneth** [comment]
It might be related to #1427. Did you check out the submodules?

**Comment by iosfeng** [comment]
@kneth  what submodules? how to check out the submodules?

**Comment by kneth** [comment]
@iosfeng For a moment I thought you have cloned our repository. But you are building an app and installing Realm using npm, right?

**Comment by esutton** [comment]
@kneth I did not clone repo.

1. I cannot build my react native app after upgrading to **realm 2.0.1** using **yarn add realm**
2. Rolling back to **realm@2.0.0** or **realm@1.13.0** works fine

Something has broken between 2.0.0 and 2.0.1

**Comment by kneth** [comment]
@esutton Thanks for clarifying. 2.0.0->2.0.1 was an update of some dependencies only. And our CI system was able to build. Which version of Xcode do you use?

**Comment by esutton** [comment]
@kneth I switch back and forth between Xcode 9 and Xcode 9.1 beta.  

Perhaps it was Xcode 9.1 beta?  Not sure how that could affect a package's path?

`/node_modules/realm/src/object-store/src/index_set.cpp:21:10: 'realm/util/assert.hpp' file not found`

**Comment by rh389** [comment]
@esutton does that `assert.hpp` file exist? It should be in `node_modules/realm/vendor/realm-ios/util/assert.hpp`.

If not, it's probably the `downoad_realm.js` script that's failing to complete (pre-build step of RealmJS xcode project), could be a few reasons for that but I was caught out by a difference in node version between my shell and xcode's.

**Comment by kneth** [comment]
2.0.1 was released due to a bug fix in our sync library. We have seen some issues with Xcode 9 (our CI system hasn't been updated completely yet). @esutton Is it possible to build with Xcode 8?

**Comment by esutton** [comment]
@rh389 I issued a find command and yes the **assert.hpp** file did exist but it seemed the realm 2.0.1 project file could not find it.  I expect I could have tweaked the realm project path and solved it given time, however, it was less effort to roll-back to 2.0.0.

@kneth I no longer have Xcode 8 installed.  My focus is on iOS 11 and testing apps on iPhone X simulator using Xcode 9.0.1

**Comment by michelalbers** [comment]
Same issue here

**Comment by kneth** [comment]
I have asked my colleagues with more experience with Xcode than me to look at it. I hope they have time later this week.

**Comment by esutton** [comment]
After upgrading to 2.0.2 it seems to build fine on Xcode 9.2 Beta

` yarn add 2.0.2`

I do not know origin of the 2.0.1 issue.

All is good again!

**Comment by kneth** [comment]
@esutton Thanks for the feedback. Maybe the genre of Realm is [magic realism](https://en.wikipedia.org/wiki/Magic_realism) :smile:
