### ISSUE TITLE
Warning on react-native 0.49.3

### ISSUE THREAD

**Issue by phuongwd** [realm/realm-js#1437]
I get this warning:

> RCTLog.js:48 Module RealmReact requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

![image](https://user-images.githubusercontent.com/2460806/32033010-393281c2-ba34-11e7-88a4-30e6e9575be2.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.0-rc22
- Node or React Native: 0.49.3
- Client OS & Version: macOS Sierra
- Which debugger for React Native: Google Chrome

**Comment by kneth** [comment]
Thanks for reporting. I don't recall that we have tested with RN 0.49.3 yet.

**Comment by rh389** [comment]
The warning’s on 0.49.0 and above, PR at https://github.com/realm/realm-js/pull/1431

**Comment by byk04712** [comment]
same warning here

**Comment by kneth** [comment]
@byk04712 The fix in #1431 in version 2.0.3.
