### ISSUE TITLE
Error: basic_string::resize when updating object

### ISSUE THREAD

**Issue by huynhtansi** [realm/realm-js#1438]
I'm trying update an 'message' object in database with a 'string' property which is very long. Here is my code:

try {
   realm.write(() => {
      realm.create('Message',  message , true);
   });
} catch(e) {
   console.error(e);
}

I caught an error:  "Error: basic_string::resize".

Magically, if I enabled 'Debug JS Remotely' in Develop Menu, it worked fine.

Using React Native v0.49.0
Error occur on both Android & iOS 
RealmJS v2.0.0

**Comment by kneth** [comment]
"very long" - how long is that? It will help us to reproduce the error.

**Comment by kneth** [comment]
@huynhtansi I am closing the issue for now. If you have any updates, please reopen it.
