### ISSUE TITLE
RN App debugging Fails while importing Realm 

### ISSUE THREAD

**Issue by Hemsza** [realm/realm-js#1443]
While enabling the debug JS in react native app, its crash with error message **Fail to execute 'send'  on 'XmlHttpRequest'**.

with earlier Realm Version( 0.12.0) app was working fine while debugging but after upgrading latest version , its crashes while debugging.

## Actual Results
- Output on Chrome while debugging
![screenshot_2](https://user-images.githubusercontent.com/32870742/31666716-d9435428-b36a-11e7-9bcd-3267728cf954.png)

- Output on Device 
![screenshot1](https://user-images.githubusercontent.com/32870742/31666727-dfeac388-b36a-11e7-8987-63e43573ea82.png)

## Code Sample
import Realm from 'realm'; // debugging fails while including this line 

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.1
- Node or React Native: 0.49.3
- NodeJS version: 8.8.1
- React Native version: 0.49
- Client OS & Version: Ubuntu 16.04
- Which debugger for React Native: Yes

**Comment by kneth** [comment]
I believe it is due to a switch of port. Please take a look at https://github.com/realm/realm-js/pull/1326.

**Comment by Hemsza** [comment]
Thanks @kneth 
after Reinstalling realm its working fine.
