### ISSUE TITLE
Realm nested object support without separate entity/object definition

### ISSUE THREAD

**Issue by tunatoksoz** [realm/realm-js#1444]
## Goals
I am trying to store a nested object tied to an object. An example is:

class Product {}
Product.schema = {
  name: 'Product',
  primaryKey: 'id',
  properties: {
    id: {type: 'string'},
    price: {type: 'Price'}
  }
};
class Price {}
Price.schema = {
  name: 'Price',
  properties: {
    value: {type: 'int'},
    currency: {type: 'string'}
  }
}

This creates two objects. There's no need. Price does not make any sense out of the Product encapsulating it. Currently, trying upsert-like semantics:
        realm.create('Product', {
          id: '123',
          price: { value: 123, currency: 'usd' }
        }, true);
Would end up creating two Price objects

I am familiar with the objects concept from db4o.

**Comment by tunatoksoz** [comment]
https://github.com/realm/realm-java/issues/2396

This is related, but the concept of cascading updates is probably not the solution.

**Comment by kneth** [comment]
With 

    realm.create('Product', {
        id: '123',
        price: { value: 123, currency: 'usd' }
    }, true);

you are updating a product and you should have the properties you need to update. It might be better to update the `Price` object and not the `Product` object.

**Comment by tunatoksoz** [comment]
Yes and no, i think. 
To me, this sounds a bit more like value type vs reference type. Price on it's own doesn't have a meaning and is only meaningful in the context of containing product.

One very straight solution is adding priceValue and priceCurrency as different properties on the Product, but that sounds lame (and there is need to duplicate when there are multiple classes holding price as a property).

Also there are cases where you may want to do:
snapshot.productPrice = product.price

In this case, you really don't want snapshot and product refer to same object, so you'd want to clone and assign, but that'd leak a copy of a non-reference price object (old value), so you then go into doing snapshot.productPrice.value = product.price.value and do the same for currency.

**Comment by kneth** [comment]
I understand your use case, and I can see how it makes sense for you. It might feel natural for a JS developer but our storage engine is cross-platform, and there is no natural way for a Java developer to express your use case.

**Comment by CanRau** [comment]
Do I get your request right in that you're asking for a List containing "plain" objects rather than references to another model?
so having another supported type next to `string`, ìnt` etc would be one of `object`?
because that's what I'm looking for right now

or another workaround for me could be optional one-to-many relationships, because as I understand [the last line in the docs of to many relationships](https://realm.io/docs/javascript/latest/#to-many-relationships)
`Unlike other lists and to-one relationships, to-many relationships cannot be made optional.`
to many relationships always need at least one child right? that's a pity

**Comment by m-vdb** [comment]
Pointing out the fact that in MongoDB-like data stores that kind of thing is possible. MongoDB has drivers for a lot of programming languages. Can we keep this issue open? How hard can it be to implement it?

**Comment by astigsen** [comment]
Realm follows the language semantics. If you did the exact same thing with plain old JavaScript objects, what would you expect to happen? Something like this:

```javascript
var item1 = {
    id: "ITEM1",
    price: {
        value: 12,
        currency: "USD"
    }
};

// update price manually
var price = item1.price;
price.value = 13;
console.log(item1.price); // product price was updated

// Update ref to price object
item1.price = {value: 14, currency: "USD"};

// You now have two price objects
console.log(price);       // -> { value: 13, currency: 'USD' }
console.log(item1.price); // -> { value: 14, currency: 'USD' } 
```

That said, the ability to tag object as "embedded" so that you can tweak the semantics could be quite useful in a lot of cases.

**Comment by c-goettert** [comment]
For anyone stumbling across this issue, there is the concept of "embeded" objects now: https://docs.mongodb.com/realm/sdk/react-native/data-types/embedded-objects/#embedded-objects---react-native-sdk
