### ISSUE TITLE
Can't open file librealm-ios-dbg.a

### ISSUE THREAD

**Issue by OceanHorn** [realm/realm-js#1445]
## Steps to Reproduce

Meet error when integrate react-native with realm to an existed App.
'''
npm install --save realm
react-native link realm
'''
Then modify "Header Search Path" of target RealmJS, enable to find head files, add items like below:
'''
$(BUILT_PRODUCTS_DIR)
$(SRCROOT)/../vendor/realm-mac-x64/include/
'''
then, "react-native start" and "Commond+R"/"Commond + B" in Xcode.
and error occors.

‘’‘
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/other/ReactNative/folder/Native/node_modules/realm/src/../vendor/realm-ios/librealm-ios-dbg.a (No such file or directory)
’‘’

And there is no file exist in folder "./node_modules/realm/vendor/realm-ios/".

## Version of Realm and Tooling

- Realm JS SDK Version: ? "realm": "2.0.1"
- Node or React Native: ? "react-native": "0.49.3"
- Client OS & Version: ? 10.13
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
Which version of Xcode do you use? We are seeing some issues with Xcode 9.

**Comment by OceanHorn** [comment]
Xcode 9. The latest version.
But I Think this issue has nothing to do with Xcode version.

**Comment by kneth** [comment]
I have tried to build a small app with Realm JS 2.0.2. The file `librealm-ios-dbg.a` does exist. Why do you need to modify the header search path?

**Comment by OceanHorn** [comment]
@kneth Sorry for replying you so late. I have a pure react native app using realm, and now I need to migrate it to an iOS native app. 
I have fixed problems of other third party dependencies, except this. Do you have any idea? Thanks!

**Comment by OceanHorn** [comment]
Issue solved by extracting realm-sync-cocoa-2.1.0.tar.xz to folder "./node_modules/realm/vendor/realm-ios/" manually. 
But meet new problem "Error: Cannot find module './node_modules/lzma-native/binding-v3.0.1-node-v57-darwin-x64/lzma_native.node", and there is no folder named 'binding-v3.0.1-node-v57-darwin-x64' existed in 'lzma-native'.

**Comment by OceanHorn** [comment]
Maybe there is something wrong with 'lzma-native'.

**Comment by kneth** [comment]
Thanks for taking the time to investigate!

**Comment by OceanHorn** [comment]
This issue can be closed now.

**Comment by kneth** [comment]
@OceanHorn I'll leave it open until we have fixed the Xcode 9 issues, we are seeing.

**Comment by chephes** [comment]
I had the exact same issue. 
Here is how I solved it. Not sure if that will work for you.

1. Open the folder where the librealm-ios-dbg.a file should be in Finder.
2. Click download from icloud icon shown next to filename.
3. keep doing 1, 2 to all of those missing files.

**Comment by kneth** [comment]
My investigations show that calling node within Xcode can be problematic. Or more precisely, `/bin/sh` is a login shell and will not run `.bashrc` and your `nvm` environment will not be set up correctly. If `/bin/sh` wasn't executed as a login shell prior to Xcode 9, it can explain it bit I haven't been able to find something about it in the Xcode release notes.

I hope to be able to open a pull request solving it either later today or early next week.

**Comment by kneth** [comment]
Version 2.1.0 should have improved the situation.

**Comment by uranashel** [comment]
I got the same issue in xCode 10.2, does anyone help me out?

**Comment by ngoctan95** [comment]
@kneth  Same issue in xCode 10.1

**Comment by kneth** [comment]
@uranashel @ngoctan95 Which Realm version are you on? v2.26.1 has a fix for building using Xcode 10.2 so maybe you need to upgrade?

**Comment by ngoctan95** [comment]
I upgraded to 2.26.1, my xCode version is have been upgraded to 10.2. 
Still got that issue.

**Comment by kneth** [comment]
Please try to clean your workspace for old build files. If the issue still persist, please try to create a small app which can reproduce the error - and share the app with us.
