### ISSUE TITLE
RN doesn't updated after Deletion last element even Exception

### ISSUE THREAD

**Issue by kosiakMD** [realm/realm-js#1446]
## Goals

Try to update component with **Section List** after changes in Realm DB, by subscription to filtered Results.

## Expected Results

Updating (rerender) component with zero elements list.

## Actual Results

If Delete last element:
 - in JS DEBUG mode it doesn't update until 'ReMount' the 'Screen' (Component) - use React Navigation;
- in 'plain' mode App crashes with strange exception linked to some 'loop' in Xcode;

```
// run the run loop
    while (kCFRunLoopRunStopped != CFRunLoopRunInMode(kCFRunLoopDefaultMode, ((NSDate *)[NSDate distantFuture]).timeIntervalSinceReferenceDate, NO)) {
      RCTAssert(NO, @"not reached assertion"); // runloop spun. that's bad.
    }
```

## Steps to Reproduce

Subscribe to filtered Results. Add element 1 or more. Delete one by one until only one left. Delete last element.

## Code Sample

it's part of HOC that try update by notification callback:

```
...
               realmResults.addListener(() => {
                    if (this.ref) {
                        this.forceUpdate();
                        this.ref.forceUpdate();
                    } else if (this.mounted) {
                        this.forceUpdate();
                    }
                });
...
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.1
- React Native: 0.47
- Client OS & Version: iOS 11.0 / iOS 10.3
- Which debugger for React Native: Chrome Debugger / none

## Suppositions

According to this: https://realm.io/docs/javascript/latest/index.html#auto-updating-results
I think **Section List** (https://facebook.github.io/react-native/docs/sectionlist.html) do `for...in...`, and as result it doesn't update...
BUT why only if last element left???

**Comment by kneth** [comment]
Please notice that you are referring to the latest documentation (version 2.0) but are using Realm JS 1.10.3. In Realm JS 2.0 we changed the behaviour of `for ... in` (breaking change).

**Comment by kosiakMD** [comment]
@kneth, sorry for my confusing (copied from previous my issue), I'm using 2.0.1 (changed in the description).

**Comment by kneth** [comment]
Thanks for clarifying. Before `for ... in`,   [`Realm.Results.snapshot()`](https://realm.io/docs/javascript/2.0.0/api/Realm.Results.html#snapshot) is called. It implies it is possible to delete objects while iterating (the number of objects is constant ).  I have added a test in #1450 to illustrate it.

**Comment by kneth** [comment]
@kosiakMD I hope that my little test was illustrative. Don't hesitate to ask and/or open new issues.
