### ISSUE TITLE
Update RealmTasks sample app to work with ROS 2.0

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-js#1447]
https://github.com/realm-demos/realm-tasks/tree/master/RealmTasks%20React

**Comment by kneth** [comment]
Similar to #1434

**Comment by kneth** [comment]
Once #1483 has been solved, we can copy the solution.

**Comment by kneth** [comment]
I believe that https://github.com/realm/realm-server-side-samples/tree/master/20-EventHandler-TicTacToe-Game is a better example.
