### ISSUE TITLE
'realm/util/assert.hpp' file not found

### ISSUE THREAD

**Issue by newtonry** [realm/realm-js#1449]
This seems like a common issue. Building in XCode fails with ```'realm/util/assert.hpp' file not found```. Other people seem to be able to workaround it by using ```realm@2.0.0```. However, it fails for with ```2.0.0```, ```2.0.1```, and ```2.0.2``` for me. I've tried with ```XCode 9.0``` and ```XCode 9.1```. I've tried with multiple projects using ```react-native@0.48.4```.

There was also a thread about the possibility of a different version of node being used (https://github.com/realm/realm-js/issues/1424). I'm consistently on ```node v6.11.3```

## Goals
Setup realm in my react-native project.

## Expected Results
A successful iOS build.

## Actual Results
```'realm/util/assert.hpp' file not found```

## Steps to Reproduce
```yarn add realm@2.0.0```
```react-native link realm```
- Build the app.

## Version of Realm and Tooling
- Realm JS SDK Version: ```2.0.0```, ```2.0.1```, ```2.0.2```
- Node or React Native: ```react-native@0.48.4```
- XCode versions: ```XCode 9.0```, ```XCode 9.1```

**Comment by kneth** [comment]
Thanks for trying out so many versions. It is probably a similar to #1449.

**Comment by fealebenpae** [comment]
@newtonry could you attach the full Xcode build log?

**Comment by OceanHorn** [comment]
modify "Header Search Path" of target ‘RealmJS’, enable to find head files, add items like below:
'''
$(BUILT_PRODUCTS_DIR)
$(SRCROOT)/../vendor/realm-mac-x64/include/
'''

**Comment by kneth** [comment]
Thanks, that's a good hint :-)

**Comment by kneth** [comment]
Version 2.1.0 should improve the situation.
