### ISSUE TITLE
Sync SSL configuration don't feels JavaScript'ish

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1465]
## Goals

I want a more native feeling when configuring Realm JS.

## Expected Results

I would expect all parameters that configure sync use of SSL have parameters that are:

1. Short
2. camelCased
3. Grouped by their context:
    - Either they all start with "ssl": `sslValidate`, `sslCertificatePath`, `sslValidateCallback`,
    - Or (even better) they are all fields on a shared object named "ssl":
    ```
    {
      sync: {
        ssl: {
          validate: true,
          validateCallback: () => true,
          certificatePath: '../../'
        }
      }
    }
    ```

While we're modifying the interface I would highly recommend that the `open_ssl_verify_callback` gets called with a single object instead of 5 individual arguments. If this is already the case - the type definitions are wrong and should be updated.

Also - is there any reason for the difference in wording "validate" and "verify"? Could we pick one and stick with it?

## Actual Results

The configuration for sync SSL uses long underscore-cased names for:

- `validate_ssl`
- `ssl_trust_certificate_path`
- `open_ssl_verify_callback`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.2

**Comment by kneth** [comment]
Being a non-English speaker, I have no strong opinion if "verify" is better than "validate". But I can see the need to be consistent.

The changes you suggest are breaking changes, and we will have to treat them as such. We can add the API you suggest, and deprecate the existing one.

**Comment by kraenhansen** [comment]
Did ☝️  ever happen?

**Comment by kneth** [comment]
Never happened :cry:. Since it works, bug fixes and new features have had higher priority.
