### ISSUE TITLE
Make create method work with ES6 objects.

### ISSUE THREAD

**Issue by sinkaszab** [realm/realm-js#1468]
## Goals
I would like Realm to work with any kind of class declaration / constructor function. This type of object creation is too restrictive and not letting to use just any kind of class / constuctor function. Which is not preferred.

## Expected Results
current: `realm.create( myType, {object literal} );`
preferred: `realm.create( myType, new Type(any | anyobject) );`

**Comment by kneth** [comment]
Can you give a more concrete example? What is your use case? Answering will help us to understand what restrictions we put on our users.

**Comment by kneth** [comment]
I close the issue.

@sinkaszab If you have time to explain your use case, don't hesitate to reopen the issue.
