### ISSUE TITLE
Cannot change sync session config between calls to Realm.open

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1469]
## Goals

I want to be able to call `Realm.open({ ... })` with two different values for the `sync.validate_ssl` configuration.

Specifically I want to be able to
1. First call with `Realm.open({ sync: { validate_ssl: true }, ... })`
2. Ff the connection fails (I can detect that when the the sync's error callback is fired) I want to re-open the realm  with a different configuration `Realm.open({ sync: { validate_ssl: false }, ... })`.

## Expected Results

If opening a synchronized Realm on ROS that uses an untrusted certificate I would expect the first call to fail and the second call to succeed.

## Actual Results

The second call to `Realm.open` never resolves (and it actually never gets rejected either).

I suspect that the underlying implementation caches the configuration - probably because its used to open a sync session which is reused. But that is an unexpected and undocumented side-effect from calling Realm.open.

If this is the case - a couple of alternative ways of achieving the goal comes to mind:
1. The Session object used by Realm JS could be invalidated, forgotten (and perhaps closed) - so the next call to Realm.open would instantiate and open a new session. Perhaps by calling `Realm.closeSession()`, `Realm.invalidateSession()` or `Realm.forgetSession()`.
2. The call to Realm.open might take a session as an argument instead of the sync config parameters that gets passed to initialize the session.
3. Perhaps opening a Realm should be a function on a session rather than the global Realm object and `Realm.open` just be a shorthand to open with the default session.

## Steps to Reproduce & Code Sample

Start ROS with a self-signed certificate and run the following .js script using node:

```
async function run() {
  const user = await Realm.Sync.User.login('https://localhost:9443/', 'realm-admin', '');
  const url = 'realms://localhost:9443/__admin';
  // First attempt
  try {
    await Realm.open({
      sync: {
        url,
        user,
        validate_ssl: true,
      }
    });
  } catch (err) {
    console.log(`Expected failure: ${err.message}`);
  }
  // Second attempt
  await Realm.open({
    sync: {
      url,
      user,
      validate_ssl: false,
    }
  });
}

run();
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.2
- Node or React Native: Electron
- Client OS & Version: Mac

**Comment by kneth** [comment]
I think this will require that we expose object store's `SyncSession::close()` which might not close the session immediately. The alternative is to by-pass the caching mechanism.

**Comment by kneth** [comment]
Exposing `SyncSession::close()` isn't useful since you don't have an instance of `SyncSession`.

I think you are right about the caching, but the caching doesn't take the ssl options into account.

**Comment by kraenhansen** [comment]
I am given a reference to the sync session from the sync configs error callback: https://github.com/realm/realm-js/issues/1467 - but that would require that an error occurs to be able to close the session .. not ideal no

**Comment by fealebenpae** [comment]
There is a `syncSession` property on `Realm` instances: https://github.com/realm/realm-js/blob/837e8d90a320085e507cda11a864f9d10ac57664/src/js_realm.hpp#L258

**Comment by kneth** [comment]
Yes, but we are in a situation that creating a Realm instance failed 😢

**Comment by blagoev** [comment]
i believe this is related to https://github.com/realm/realm-object-store/issues/589
which is fixed in https://github.com/realm/realm-object-store/pull/596
still we need to validate this works and the Promise is rejected properly. The fix is for calling the error handler on the sync config object

**Comment by kraenhansen** [comment]
Isn't it wrong that this is labeled enhancement @kneth? As a consumer of Realm JS I have no idea of the underlying sync session and would expect my sync config to be respected between calls to Realm.open.

**Comment by kraenhansen** [comment]
This is still making Studio overly complicated when an untrusted certificate is discovered and Studio needs to reconnect, this time trusting the certificate.

**Comment by kneth** [comment]
It is unclear if this issue is still relevant after we introduced the new sync API in v10.0.0.

**Comment by kraenhansen** [comment]
I never "got around to it", so I'm removing my assignment to let anyone else take a stab at verifying this.
