### ISSUE TITLE
How to open a Realm without schema

### ISSUE THREAD

**Issue by kneth** [realm/realm-js#1470]

**Comment by deyanskiq** [comment]
Any updates on this?

**Comment by kneth** [comment]
The functionality is there but I don't think it is explained in the documentation. You can open an existing Realm using `new Realm()` - notice: no schema specified. The schema is derived from the file, and you can query, add objects, etc. 

Please take a look at https://github.com/realm/realm-js/blob/master/tests/js/realm-tests.js#L115

**Comment by kneth** [comment]
A short guide should be added to the documentation, and I have created an internal issue for it.
