### ISSUE TITLE
realm.subscribeToObjects is not a function error

### ISSUE THREAD

**Issue by zoranmarjanovic** [realm/realm-js#1476]
## Goals

Trying to call subscribeToObject method

## Expected Results

To call it successfully and get results

## Actual Results
Failed in Error
TypeError: realm.subscribeToObjects is not a function

## Code Sample

const config = {
    // path: 'synced.realm',
    sync: {
      user: user,
      url: 'realm/url',
      partial: true,
    },
    schema: [ CarSchema, PersonSchema ]
  }

  const realm = new Realm(config)

  const partialResults = realm.subscribeToObjects('Integer', 'age > 5').then((results, error) => {
    return results
  })

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.2
- Node or React Native: RN v0.46.4
- Client OS & Version: iOS
- Which debugger for React Native: default

**Comment by kneth** [comment]
Is `Integer` defined in your schema and exist in your Realm? Our best example is currently 
our test: https://github.com/realm/realm-js/blob/master/tests/js/session-tests.js#L700

**Comment by zoranmarjanovic** [comment]
It is about chrome debugger, getContext function return chromedebugger instead reactnative, when debugging react-native app
