### ISSUE TITLE
Realm.Sync.addListener is not defined in react-native

### ISSUE THREAD

**Issue by zoranmarjanovic** [realm/realm-js#1477]
## Goals

Trying to get what is changed in last sync

## Expected Results

To successfully get diff

## Actual Results

Fail in error
TypeError: _realm2.default.Sync.addListener is not a function

## Code Sample
  const config = {
    // path: 'synced.realm',
    sync: {
      user: user,
      url: 'realm/path'
    },
    schema: [ CarSchema, PersonSchema ]
  }
  const realm = new Realm(config)
  Realm.Sync.addListener(server_url, admin_user, regex, name, change_callback)
## Version of Realm and Tooling

 - Realm JS SDK Version: 2.0.2
 - Node or React Native: RN v0.46.4
 - Client OS & Version: iOS
 - Which debugger for React Native: default

**Comment by kneth** [comment]
Is it related to #1476? I mean, it looks a generic issue, you have.

**Comment by zoranmarjanovic** [comment]
Both functions are available in node app that I have made, but in ract-native code on ios it doesn't work, any chance that something in native are not linked well

**Comment by kneth** [comment]
Maybe one of the tricks in https://realm.io/docs/javascript/latest/#missing-realm-constructor is useful.

**Comment by zoranmarjanovic** [comment]
I found an issue, it is about chrome debugger, method getContext() return chromedebugger instead of reactnative. Is there any way to debug and use realm in common way? @kneth

**Comment by zoranmarjanovic** [comment]
Actually this resolve #1476, here is still an issue

**Comment by zoranmarjanovic** [comment]
First I have solved  #1476, but this one is still open, this method is available in nodejs app, but not in react native, I am digging into it still.

**Comment by zoranmarjanovic** [comment]
Here is problem 

in lib/index.js
const Sync = {
  User,
  Session,
}

there is no other properties, any chance to add addListener method here?

**Comment by kneth** [comment]
`Realm.Sync.addListener` is only available in the Professional and Enterprise editions (see https://realm.io/docs/realm-object-server/latest/#event-handling for details). Can you confirm that `addListener` is not found in these editions?

**Comment by kneth** [comment]
@zoranmarjanovic If you are interested, you are welcome to contact us for a trial version of PE/EE.

**Comment by mklb** [comment]
@kneth  I updated my ROS and the SDK (React Native) and used `addListener` till.. today. So the `addListener` was removed from the object server / sdk in V2 (developer edition)? How should we accomplish the "sync" part of realm without these callbacks? Or am I missing something ?
No Idea how I should login, load and subscribe to realms ..

**Comment by kneth** [comment]
@mklb You can use `Realm.addListener()` and `Realm.Results.addListener()` to subscribe to changes (including changes coming in from sync).
