### ISSUE TITLE
I there a way to disable realm-object-server?

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-js#1491]
## Goals

I want to prevent creating **realm-object-server** folder.

## Expected Results

Do not see **realm-object-server** folder inside my project folder.

## Actual Results

All the time when I start my project which uses realm I see that realm module creates **realm-object-server** folder, and even can't remove it because it restores it immediately.

## Steps to Reproduce

Just start any "Hello world" project with **require('realm')**

## Code Sample

```javascript
require('realm')
console.log('Hello world')
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.6
- Node or React Native: 6.11.2
- Client OS & Version: Debian 9
- Which debugger for React Native: None

**Comment by kneth** [comment]
Please use the issue template since it helps us to understand your use case and its context.

**Comment by bdash** [comment]
Of particular interest would be which versions of Realm JS you're using, and whether or not you're using Realm Platform's synchronization support.

**Comment by MihaelIsaev** [comment]
I've updated first post

**Comment by kneth** [comment]
I cannot reproduce it on macOS but I will try on a Linux machine tomorrow.

**Comment by kneth** [comment]
I have tried on a docker instance of Ubuntu Xenial using node 6.12.9 and Realm JS 2.0.6 - and I can't reproduce it.
