### ISSUE TITLE
realm report a crash when debug with iPhone device

### ISSUE THREAD

**Issue by RazerTang** [realm/realm-js#1492]
Hi Guys,
When I use xCode debug with my iPhone device, the realm-js throw a crash, as below image
![2017-11-15 9 19 16](https://user-images.githubusercontent.com/5905640/32813698-501c05cc-c9e6-11e7-8d57-8379cf0ad323.png)

To my surprised, There is no crash if I not connect xCode to debug with my iPhone device and it is also no crash on my colleague's computer no matter debug with xCode or not.

Anyone has an idea about this problem. Thanks.

## Version of Realm and Tooling

- Realm JS SDK Version: 1.8.3
- Node or React Native: v8.0.0
- Client OS & Version: iOS 10
- Which debugger for React Native: ?/None

**Comment by bdash** [comment]
This doesn't look like a crash, but rather that you're hitting a breakpoint when a C++ exception is thrown. I'd suggest looking in Xcode's breakpoint navigator to see if you have an exception breakpoint enabled, and consider disabling it if you're hitting it unexpectedly.

**Comment by RazerTang** [comment]
Wow, That's the  problem, I  have not awared of setting the C++ breakpoint.Thanks very much @bdash .
