### ISSUE TITLE
Inflated apk size by librealmreact.so in React Native apps

### ISSUE THREAD

**Issue by jayshah123** [realm/realm-js#1496]
## Goals

Reduce APK Size

## Expected Results

Lesser APK Size

## Actual Results

Large APK Size

## Steps to Reproduce

Use RealmJS in a react-native app. Use APK Analyzer in Android > Build > Analyze APK.

## Code Sample

See 3.1 MB for x86 and 2.5 MB for Armeabi-v7a

<img width="787" alt="screen shot 2017-11-16 at 7 48 35 pm" src="https://user-images.githubusercontent.com/659202/32895999-da46bf54-cb07-11e7-85d0-57211df16520.png">

## Version of Realm and Tooling

- Realm JS SDK Version: ^1.11.1
- Node or React Native: ^0.48.4
- Client OS & Version: Android
- Which debugger for React Native: None

**Comment by kneth** [comment]
It is going to be hard to reduce the size of our `.so` as we are already agressive with the compiler options. Maybe ABI split can help you: https://realm.io/docs/java/latest/#faq-library-size

**Comment by jayshah123** [comment]
Well I am looking about abi split, and react-native has sensible defaults regarding it, What I was wondering was wanting to only opt into realm object server and strip out unnecessary size for unwanted features if possible?

**Comment by kneth** [comment]
I am afraid that it is not possible to cherry-pick components. We hope to upgrade Android NDK soon, and maybe clang will be able to reduce the size a bit.

**Comment by jayshah123** [comment]
Ok I'll try again with newer/upcoming versions and open again if necessary.
