### ISSUE TITLE
Freezes in release

### ISSUE THREAD

**Issue by sywka** [realm/realm-js#1497]
## Expected Results

It continues to run

## Actual Results

Does not reach step2

## Steps to Reproduce

There is an error in the **release** (debug is ok)

## Code Sample

```js
class SessionModel {

  static FIELD_ID = '_id'
  static FIELD_TIME = '_time'
  static FIELD_OPERATOR = '_operator'
  static FIELD_OPERATION = '_operation'
  static FIELD_DISABLED = '_disabled'
  static FIELD_EXPORTED = '_exported'

  static FIELD_CODES = '_codes'
}

SessionModel.schema = {
  name: SessionModel.name,
  primaryKey: SessionModel.FIELD_ID,
  properties: {
    [SessionModel.FIELD_ID]: 'int',
    [SessionModel.FIELD_TIME]: 'date',
    [SessionModel.FIELD_OPERATOR]: OperatorModel.name,
    [SessionModel.FIELD_OPERATION]: OperationModel.name,
    [SessionModel.FIELD_DISABLED]: 'bool',
    [SessionModel.FIELD_EXPORTED]: 'bool',
    [SessionModel.FIELD_CODES]: `${CodeModel.name}[]`
  }
}

let realm = await Realm.open({
      schema: [SettingModel, SessionModel, OperatorModel, StoringPlaceModel, OperationModel, CodeModel],
      schemaVersion: 112,
      deleteRealmIfMigrationNeeded: true,
      shouldCompactOnLaunch: (totalBytes, usedBytes) => true
    })

console.log('step1')
let result = realm.objects(SessionModel.name)
console.log('step2')
```
Output: `step1`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.6
- Node or React Native: 0.50.3
- Client OS & Version: Android 4.2.2/8.0

**Comment by kneth** [comment]
Could you try to do `realm.empty` instead? It's a much simpler operation, and I am a bit curious to understand which operaions are blocking.

**Comment by sywka** [comment]
Sorry, my fault.
Update:
```js
const sessions = realm.objects(SessionModel.name)
console.log('step1')
sessions.sorted(SessionModel.FIELD_TIME)
console.log('step2')
```
Output: 
`step1`
`{ [Error: Cannot sort on key path '_time': property 'e._time' does not exist.] line: 631, column: 518, sourceURL: 'index.android.bundle' }`

It happens only in the release. What could be the problem?

**Comment by kneth** [comment]
Sorry for the late response. I think your schema should be

```
SessionModel.schema = {
  name: SessionModel.name,
  primaryKey: SessionModel.FIELD_ID,
  properties: {
    SessionModel.FIELD_ID: 'int',
    SessionModel.FIELD_TIME: 'date',
    SessionModel.FIELD_OPERATOR: `${OperatorModel.name}`,
    SessionModel.FIELD_OPERATION: ^${OperationModel.name}`,
    SessionModel.FIELD_DISABLED: 'bool',
    SessionModel.FIELD_EXPORTED: 'bool',
    SessionModel.FIELD_CODES: `${CodeModel.name}[]`
  }
}
```

**Comment by sywka** [comment]
`SessionModel.FIELD_ID` is link to string `_id`. I can't declare it like this `SessionModel.FIELD_ID: 'int',`.
If you mean to replace `OperatorModel.name` with `${OperatorModel.name}` then still can't sort by `_time`

**Comment by sywka** [comment]
It was in the use of `SessionModel.name`. changing this to `SessionModel.schema.name` fixed it.
