### ISSUE TITLE
Query sorting documentation is incorrect

### ISSUE THREAD

**Issue by billmalarky** [realm/realm-js#1501]
[From the docs: ](https://realm.io/docs/javascript/latest/#sorting)

> // Sort by price in descending order and then miles in ascending
> sortedHondas = hondas.sorted(['price', true], ['miles']);

This seems to be invalid, as in my test env sorting on multiple properties requires a single array to be passed in, not multiple array params. Furthermore, the 2nd value of each array param (the ASC/DESC value) seems to be necessary for realm to not throw an exception.

[and in the code comments:](https://github.com/realm/realm-js/blob/643c19ea75b45b8e1fbe0b5247aa08e9088db8d1/docs/collection.js#L101-L104)

`wines.sorted([['price', false], ['age'])`

Code comment syntax is broken (unclosed array literal) and the above also applies.

I was able to get sorting to work as expected with the following syntax 

`sortedHondas = hondas.sorted([['price', false], ['miles', false]]);`

Note it is one param passed to sorted() as a multidimensional array and the ASC/DESC value is REQUIRED, it doesn't default to false as you would expect.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.7
- Node or React Native: React native
- Client OS & Version: iphone 6 - ios 10.3 simulator
- Which debugger for React Native: chrome console

**Comment by kneth** [comment]
Thank you for reading our documentation and reporting bugs in it!!!

**Comment by billmalarky** [comment]
No problem!

On Fri, Nov 17, 2017 at 5:13 AM, Kenneth Geisshirt <notifications@github.com

**Comment by kneth** [comment]
See https://github.com/realm/realm.io/pull/4272
