### ISSUE TITLE
How to create native module android to retrieve realm data value in react native?

### ISSUE THREAD

**Issue by zxccvvv** [realm/realm-js#1502]
## Goals

show value of realm db in console.log

![image](https://user-images.githubusercontent.com/19633881/32925820-8b87fe86-cb76-11e7-9346-4ee8306b4beb.png)

## Actual Results

can't find any refer/tutorial to archieve it

## Version of Realm and Tooling

- React-native-cli : 2.0.1
- React-native: 0.47.1
- PC : Windows 10
- Which debugger for React Native: VSCode & Android Studio

**Comment by kneth** [comment]
I am not sure what you are asking. If you do `console.log('My object', myObject)`, the object will be converted to a string. And debugging using Chrome should give you the ability to inspect objects.
