### ISSUE TITLE
setTimeout hangs in react-native when it's in background.

### ISSUE THREAD

**Issue by tunatoksoz** [realm/realm-js#1507]
## Goals
Trying to realize a task in background that uses realm db as its data soure.

## Expected Results
Realm opens, and continues as it normally does.

## Actual Results
Realm hang while opening DB.

## Steps to Reproduce
Install react-native-background-job, and schedule a job. Kill the original app and wait for timer to wake background job up.

## Version of Realm and Tooling

- Realm JS SDK Version: 1.13
- Node or React Native: 0.50.3
- Client OS & Version: ?
- Which debugger for React Native: ?/None

I was able to track down the issue to a common problem: setTimeout is somewhat frozen until the app is reopened. This is currently in use here: 
https://github.com/realm/realm-js/blob/master/lib/extensions.js#L79

If i comment out setTimeout and just use the resolve/reject directly, the issue goes away.

**Comment by kneth** [comment]
Do you know if `react-native-background-job` execute the job in another process? If so, that might be the root cause.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.

**Comment by Louies89** [comment]
Hi @kneth & @bmunkholm 
How to write to Realm JS, when app is not active means not in foreground not in background.
In my case what I am trying to achieve is, I get FCM cloud notification and once I get it, if app is not running, I want to wake up the app in back ground and fetch some data from server and sleep again.

So whenever the app shall be activated, it shall start in a new process, so realm should be accessible, but, what i m finding is, 
`Realm.open(dbOptions).then(realm=>{console.log(realm)})`
prints => {}

So how to use realm when app is not running at all.

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag.

Thanks for your help!
