### ISSUE TITLE
Support relative paths for realm files

### ISSUE THREAD

**Issue by asamiller** [realm/realm-js#151]
The readme says:
> path – optional - defaults to Realm.defaultPath (which initially is 'Documents/default.realm')

but when I create a new database with a path specified:
```javascript
this.db = new Realm({
  schema: [Schemas.Queue],
  schemaVersion: 0,
  path: 'Documents/Queue.realm',
});
```
I get this error:
```
Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “Documents”.
```

**Comment by joshuapinter** [comment]
:+1: 

I ran into this as well. The docs use the following as an example: 

```js
// Open a realm at another path
let realmAtAnotherPath = new Realm({
  path: 'anotherRealm.realm',
  schema: [CarSchema]
});
```

But doing that produces an error like:

![screenshot 2016-03-01 17 19 25](https://cloud.githubusercontent.com/assets/180819/13446572/c5db6402-dfd1-11e5-964f-3cda4a9b7c31.png)

However, doing the following worked just fine: 

```js
var defaultPath = Realm.defaultPath;
var newPath     = defaultPath.substring(0, defaultPath.lastIndexOf('/')) + '/anotherRealm.realm';

// Open a realm at another path
let realmAtAnotherPath = new Realm({
  path: newPath,
  schema: [CarSchema]
});
```

**Comment by alazier** [comment]
I think what we should do is if the path doesn't begin with a `/`, assume that it is a relative path and prepend the path to the Documents dir. That way you can specify files outside of the Documents dir while still having this convenience.

**Comment by appden** [comment]
@joshuapinter we're really sorry about this oversight with the documentation! We'll get this fixed ASAP.

**Comment by appden** [comment]
@alazier: I agree, though I think we should expose absolute path prefixes for inside the app bundle as well as to the documents directory.

**Comment by alazier** [comment]
Don't think we need the prefixes as it isn't directly related to Realm, although maybe some other library should do this.
