### ISSUE TITLE
Thread 23: signal SIGABRT

### ISSUE THREAD

**Issue by RGump** [realm/realm-js#1510]
After updating the react-native and realm, I can not run the project. I get such compilation errors

Assertion failed: (m_value.object->find(key) != m_value.object->end()), function operator[], file node_modules/realm/vendor/json.hpp, line 4010.

- Realm JS SDK Version: 2.0.8
- React Native: 0.50.3
- Client OS: IOS Simulator 8?
- Which debugger for React Native: None

**Comment by edward-s** [comment]
+1
downgrade to 2.0.7 will solve this issue

**Comment by RGump** [comment]
edward-s, thanks, its work for me

**Comment by blagoev** [comment]
@RGump @edward-s we fixed this in 2.0.10. You can upgrade to it
