### ISSUE TITLE
react-native Debug JS Remotely?

### ISSUE THREAD

**Issue by zhuanglong** [realm/realm-js#1517]
rn 0.46.4
realm 2.0.8

error:
index.ios.bundle:7761Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.

POST http://localhost:8083/create_session net::ERR_EMPTY_RESPONSE

**Comment by colorfulberry** [comment]
Same bug,  How is goding?

**Comment by blagoev** [comment]
thanks we are preparing a fix for this and will be release it soon

**Comment by colorfulberry** [comment]
@blagoev Thanks. A good job for it.
@zhuanglong It worked with version 2.0.10. 2.0.8 not works with android. 2.0.9 not works with debugging. Please use 2.0.10

**Comment by Tamiyadd** [comment]
It worked with version 2.0.10 for me too.

**Comment by blagoev** [comment]
glad it's working for you guys.

I think we can close this issue.

**Comment by tranquan** [comment]
I have this bug again on version `2.14.2`
I am using react-native and when trying to `debug js remotely`

create_session net::ERR_EMPTY_RESPONSE on 8083

the debugger I used: https://github.com/jhen0409/react-native-debugger
