### ISSUE TITLE
After `Realm Studio` installation is complete, it can not start normally

### ISSUE THREAD

**Issue by Lizhooh** [realm/realm-js#1527]
![asdas](https://user-images.githubusercontent.com/19299088/33227566-1c15a3f8-d1e0-11e7-97af-b32f93afeceb.png)

- Realm Studio 1.8.0
- win7 x64 
- nodejs v8.5

**Comment by kraenhansen** [comment]
Hi @Lizhooh. This repository is for Realm JS related issues only.

However another user experienced this as well: https://stackoverflow.com/questions/47198349/realm-studio-for-windows-javascript-error

Realm JS (that Studio is dependent on) target Windows 8.1 and up, so Windows 7 is not supported. I've added that to the backlog that we should probably improve that error message.

**Comment by zhujiaming** [comment]
Does realm support Windows 7 now? If not, is there a plan to support it?
