### ISSUE TITLE
problem install realm react-native on windows

### ISSUE THREAD

**Issue by KiaSo** [realm/realm-js#1528]
after run npm install --save realm i got this error and warning : 

node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.2 and node@9.2.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)

## Goals

install on windows for using react-native realm

## Code Sample

npm install --save realm

## Version of Realm and Tooling
realm 2.0.4
Node : 9.2.0
react-native-cli: 2.0.1
react-native: 0.49.3
windows 10 x64 version

**Comment by kneth** [comment]
Node 9 was not supported in Realm JS 2.0.4. You will have to upgrade to 2.0.7.
