### ISSUE TITLE
Webstorm unable to debug react native using realm

### ISSUE THREAD

**Issue by krangiosdev** [realm/realm-js#1530]
## Goals

Debugger should work as expected

The else if part of the if condition clears the issue with Webstrom.
```
    if (typeof process === 'object' && process + '' === '[object process]') {
        // Visual Studio Code defines the global.__debug__ object.
        if (typeof global !== 'undefined' && global.__debug__) {
            return 'vscodedebugger';
        }
        
        return process.type === 'renderer' ? 'electron' : 'nodejs';
    }else if('env' in process && 'NODE_ENV' in process.env){
      return 'chromedebugger';
    }
```

## Actual Results
This will get the debugger to be recognized.
>

## Steps to Reproduce

Create a react native project in webstorm
Add realm to the project
Hit debug using the node option.
<!---
Please provide a code sample or test case that highlights the issue.
**Before:**
```
 if (typeof process === 'object' && process + '' === '[object process]') {
        // Visual Studio Code defines the global.__debug__ object.
        if (typeof global !== 'undefined' && global.__debug__) {
            return 'vscodedebugger';
        }
        
        return process.type === 'renderer' ? 'electron' : 'nodejs';
    }
```

**After:**
```
 if (typeof process === 'object' && process + '' === '[object process]') {
        // Visual Studio Code defines the global.__debug__ object.
        if (typeof global !== 'undefined' && global.__debug__) {
            return 'vscodedebugger';
        }
        
        return process.type === 'renderer' ? 'electron' : 'nodejs';
    }else if('env' in process && 'NODE_ENV' in process.env){
      return 'chromedebugger';
    }

```
## Version of Realm and Tooling

- Realm JS SDK Version: ^2.0.11
- Node or React Native: ^0.49.0
- Client OS & Version: OS 11.1
- Which debugger for React Native: ? Webstorm

**Comment by kneth** [comment]
Thanks. You are welcome to prepare your fix as a pull request. Please see `CONTRIBUTING.md` for details.

**Comment by durghe** [comment]
just tryed it out in IntelliJ and now it's working fine!
Thanks!

**Comment by kneth** [comment]
@durghe Thanks for the update.

Are you on Android on iOS?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
