### ISSUE TITLE
A typo on the docs

### ISSUE THREAD

**Issue by MilkBiscuit** [realm/realm-js#1531]
## Expected Results
https://realm.io/docs/javascript/latest/index.html#sorting
Missed a pair of square brackets.
Should be

// Sort by price in descending order and then miles in ascending
`sortedHondas = hondas.sorted([['price', true], ['miles']]);
`

## Actual Results
// Sort by price in descending order and then miles in ascending
`sortedHondas = hondas.sorted(['price', true], ['miles']);
`

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by MilkBiscuit** [comment]
This page missed closing square brackets
https://realm.io/docs/javascript/2.0.0/api/Realm.Results.html#sorted

// Sort wines by price in descending order, then sort ties by age in ascending order
wines.sorted([['price', false], ['age'])

Should be

wines.sorted([['price', false], ['age']])

**Comment by kneth** [comment]
Yes, I haven't had time to fix it yet (see also #1501).
