### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-js#1534]
## Goals

Install modules for node.js app with a single dependency of realm "latest"

## Expected Results

Success

## Actual Results

Fail

## Steps to Reproduce

macOS: 10.12.6
npm ver: 5.4.2

npm ERR! Failed at the lzma-native@3.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by fealebenpae** [comment]
What's your Node.js version?

**Comment by icanzilb** [comment]
@fealebenpae `8.8.1`

While npm is installing realm it spits out this:

```
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.4-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.4 and node@8.8.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
```

Then goes into compiling lzma-native and the make script fails 🙄

**Comment by fealebenpae** [comment]
I think it must have been a momentary fluke with the `lzma-native` dependency, because at first I got a 404 for the URL but now it works. Could you try again, please?

**Comment by icanzilb** [comment]
@fealebenpae I did try few times before opening an issue but what do you know ... now it's fine 👍🏼

**Comment by esutton** [comment]
I have been seeing the same issue on and off again with realm versions 2.0 and greater.  It seems to come and go with new realm releases.

I thought it *seemed* to be more frequent when using yarn as compared to **npm install**.  However I never figured out the root cause.

**Comment by icanzilb** [comment]
That's an interesting insight. It is the first time I see the error and I've been using realm a lot in the last months. Maybe it's something to look into @fealebenpae ?

**Comment by fealebenpae** [comment]
We hope to be able to drop `lzma-native` as a dependency soon.

**Comment by esutton** [comment]
@icanzilb I am not a node.js expert and do not understand what node-pre-gyp is.

There is a discussion about this issue from another realm user who also associated this issue with lzma-native realm:

[Error: Cannot find module 'binding-v3.0.1-node-v57-darwin-x64'](https://github.com/addaleax/lzma-native/issues/45)

**Comment by martsie** [comment]
I can echo having a similar issue. Realm is searching for lzma-native/binding-v3.0.4-node-v51-darwin-x64 however the latest lzma-native release doesn't appear to have a 3.0.4 binding folder (only up to v3.0.3)

**Comment by TheLastClown** [comment]
Having the same issue :(

**Comment by devendragarg** [comment]
same issue.
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/1.13.0/realm-v1.13.0-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.13.0 and node@10.1.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by cmbasnett** [comment]
For those still having this problem, I found that switching my `npm` to version `8.x` seemed to fix the compilation error, whereas it would fail if `npm` was using `10.0.0`.

**Comment by hpthao1090** [comment]
npm i react-native-realm

**Comment by joshuapinter** [comment]
@cmbasnett 
> For those still having this problem, I found that switching my `npm` to version `8.x` seemed to fix the compilation error, whereas it would fail if `npm` was using `10.0.0`.

Did you mean to say `node`? From what I can tell the latest version of `npm` is 6.x.

**Comment by aminosman** [comment]
Yeah, switching to `node` `8.x` worked for me
