### ISSUE TITLE
Error printed in the output upon successful opening file

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-js#1535]
## Goals

Open synced realm via `Realm.open()`

## Expected Results

No errors

## Actual Results

The promise returns a user object but an error message is printed in the console:

```
ERROR: Connection[1]: Failed to connect to endpoint '::1:9080': Connection refused
Connection[1]: Connected to endpoint '127.0.0.1:9080' (from '127.0.0.1:63925')
```

## Steps to Reproduce

Running a Node.js app on a macOS laptop, nothing special. The source is below:

## Code Sample

```JS
const HOST_PORT = 'localhost:9080';
const RW_USER = 'user1@realm';
const RW_PASS = 'password';
const FILE_NAME = 'test_259';

'use strict';

const Realm = require('realm');

const PersonSchema = {
  name: 'Person',
  properties: {
    id: {type: 'string'},
    name: {type: 'string'}
  }
};

Realm.Sync.User.login('http://'+HOST_PORT+'/', RW_USER, RW_PASS)
.then(user => {
  console.log("SUCCESS LOGIN: connected...");

  Realm.open({
    sync: {
      user: user,
      url: 'realm://'+HOST_PORT+'/~/'+FILE_NAME
    },
    schema: [PersonSchema],
    schemaVersion: 1
  })
  .then(realm => {
    console.log("SUCCESS OPEN: file created...");
  })
})
```

## Version of Realm and Tooling

- Realm JS SDK Version: `realm: latest` on npm
- Node or React Native: Node.js
- Client OS & Version: macOS 10.12.6

To clarify a bit more: The API works as expected, **except** for printing out an error message in the console. I'd recommend If there is no actual error avoid confusing the developers, and in case there is an actual error - the open file API shouldn't work.

**Comment by bdash** [comment]
I agree that this shouldn't be logged so severely. What's happening here is that "localhost" resolves to both an IPv4 and IPv6 address, and the attempt to connect to the IPv6 address is failing. It then falls back to trying the IPv4 address, which succeeds. I think it would be more appropriate for a failure to connect to a single address to be logged with a lower severity, with the error severity only used if _all_ addresses fail.

**Comment by bdash** [comment]
I wrote up an issue against the underlying sync component as I believe that's where this is determined.

**Comment by icanzilb** [comment]
Thanks for handling this

**Comment by kneth** [comment]
I put it on hold until a fix surfaces from the sync component.
