### ISSUE TITLE
Do you guys support LIKE queries in Realm-JS query language?

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-js#1546]
Do you have the `LIKE` from Realm-Java that does `*` for multi-char and `?` for single char?

**Comment by kneth** [comment]
No, the closest we have is `contains` (for substring matches). We do accept pull requests (you will need to add the functionality to https://github.com/realm/realm-object-store/blob/master/src/parser/query_builder.cpp#L178 and https://github.com/realm/realm-object-store/blob/master/src/parser/parser.hpp#L47).
