### ISSUE TITLE
xCode Build Fails

### ISSUE THREAD

**Issue by katima-g33k** [realm/realm-js#1547]
## Goals
Trying to build app with Realm using xCode, but keep getting error.

If anyone can help me debug this error it would be greatly appreciated. I have already tried multiple things including:
- Deleting the derived data;
- Cleaning the project;
- Setting script to run only when installing;

The build works when using `react-native run-ios` command, but still need to getting it working in xCode.

## Result
![image](https://user-images.githubusercontent.com/7608273/33509219-ab22c7be-d6cd-11e7-9233-f04cc86d3a6a.png)

## Steps to Reproduce

1.  Build the project
```bash
react-native init realmtest
cd realmtest
npm install
npm install realm --save
react-native link realm
npm start
```
2. Setup provisioning profile in xCode
3. Run project in xCode

## Version of Realm and Tooling
- Realm JS SDK Version: 2.0.11
- Node: 8.9.1
- React Native: 0.50.3
- xCode: 9.1

**Comment by kneth** [comment]
Please see #1483.

**Comment by kaushiksahoo2000** [comment]
I am having the same exact issue in trying to incorporate Realm JS into our React Native app. What is the current status of this issue?

**Comment by mtr1012** [comment]
please helppppppp

**Comment by katima-g33k** [comment]
For whatever reason, the problem at some point after my computer was restarted. But this week a colleague had the same problem and ended up finding the solution. It seems to be caused by a missing link. Try running `ln -s $(which node) /usr/local/bin/node`

**Comment by kneth** [comment]
@katima-g33k Just out of curiosity: did you upgrade to High Sierra as part of the reboot?

**Comment by katima-g33k** [comment]
No the reboot was due to a power outage.  The computer has been on high siearra even before i started using it. So the os version has nothing to do with the issue (in my case anyway)

**Comment by diablourbano** [comment]
If anyone arrive here with the same issue, I solved it thanks to @katima-g33k [last comment](https://github.com/realm/realm-js/issues/1547#issuecomment-364429140)

Conditions to consider this solution, I'm using `nvm` and before to apply this solution there was no `/usr/local/bin/node` so if you're using `nvm` first load the node version you're using for your project and the run `ln -s $(which node) /usr/local/bin/node`
