### ISSUE TITLE
Add support for JWT authentication

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1548]
We need to provide a built-in credentials type for JWT. It only accepts a token like:

```js
Realm.Sync.User.registerWithProvider('http://my.realm-auth-server.com:9080', 'JWT', 'my-token', (error, user) => { /* ... */ });
```

ROS issue: https://github.com/realm/realm-object-server-private/issues/701

Additionally, @mbalex99 wanted to deprecate `registerWithProvider` in favor of `authenticate`: https://docs.google.com/document/d/1fyOKB9tseBuNmWE4shxbSI3pRzeKVdOdXDKerartPCo/edit. Not sure if these should be handled together or separately.

**Comment by kneth** [comment]
We can deprecating `registerWithProvider` but we cannot remove it until next major version.
