### ISSUE TITLE
Fix node-pre-gyp not found

### ISSUE THREAD

**Issue by blagoev** [realm/realm-js#1549]
This is caused by the use of lzma module which installs node-pre-gyp in it's node_modules dir and in turn causes node-pre-gyp symlink in .bin to not be present in realm/node_modues/.bin which results in realm-js install script to fail with node-pre-gyp not found

The change that removes the tar.xz support can be tracked here realm/ci#247

Postponing this until the linked issue fixes the use of tar.xz for the sync library

**Comment by blagoev** [comment]
previous works for this are
https://github.com/realm/realm-js/pull/1511 and 
https://github.com/realm/realm-js/pull/1382

**Comment by bmunkholm** [comment]
Is this still an issue? @kneth

**Comment by kneth** [comment]
At least we haven't seen it for months. Let's close it and reopen if it resurfaces.
