### ISSUE TITLE
Tons of crashes: RCTFatalException: Unhandled JS Exception: Missing Realm constructor

### ISSUE THREAD

**Issue by danieldelouya** [realm/realm-js#1554]
Running: "realm": "^2.0.1"

Experiencing lots of crashes in release with the error message:
Fatal Exception: RCTFatalException: Unhandled JS Exception: Missing Realm constructor. Did you run "react-native link realm"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting

Everything is indeed linked. It's on iOS only these crashes are happening. 

What to do? Kinda urgent. Thanks. 

Fatal Exception: RCTFatalException: Unhandled JS Exception: Missing Realm constructor. Did you run "react-native link realm"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
0  CoreFoundation                 0x18de0efe0 __exceptionPreprocess
1  libobjc.A.dylib                0x18c870538 objc_exception_throw
2  CoreFoundation                 0x18de0ef28 -[NSException initWithCoder:]
3  Tangler                        0x1000b7270 RCTFatal (RCTAssert.m:138)
4  Tangler                        0x1000b4f34 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] (RCTExceptionsManager.m:60)
5  CoreFoundation                 0x18de14e80 __invoking___
6  CoreFoundation                 0x18dd0a2c4 -[NSInvocation invoke]
7  CoreFoundation                 0x18dd0ee9c -[NSInvocation invokeWithTarget:]
8  Tangler                        0x1000c8210 -[RCTModuleMethod invokeWithBridge:module:arguments:] (RCTModuleMethod.mm:522)
9  Tangler                        0x1001072f8 facebook::react::RCTNativeModule::invokeInner(unsigned int, folly::dynamic const&&) (RCTNativeModule.mm:96)
10 Tangler                        0x100107164 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke (Optional.h:299)
11 libdispatch.dylib              0x18ccc69e0 _dispatch_call_block_and_release
12 libdispatch.dylib              0x18ccc69a0 _dispatch_client_callout
13 libdispatch.dylib              0x18ccd4ad4 _dispatch_queue_serial_drain
14 libdispatch.dylib              0x18ccca2cc _dispatch_queue_invoke
15 libdispatch.dylib              0x18ccd4fa8 _dispatch_queue_override_invoke
16 libdispatch.dylib              0x18ccd6a50 _dispatch_root_queue_drain
17 libdispatch.dylib              0x18ccd67d0 _dispatch_worker_thread3
18 libsystem_pthread.dylib        0x18cecf100 _pthread_wqthread
19 libsystem_pthread.dylib        0x18cececac start_wqthread

**Comment by karthikpala** [comment]
Hi @kneth and @bmunkholm - We are also seeing crashes in firebase with similar error. Can you please let me know how this is resolved for you?

React-Native version: 0.59.10
Realm version: 2.28.0

**Comment by karthikpala** [comment]
Hi guys - can you please help?

**Comment by bmunkholm** [comment]
Hi @karthikpala,
We don't actively monitor closed issues. Please create a new issue (and refer to this one) with all relevant information in the template and we will take a look. Thanks!

**Comment by karthikpala** [comment]
Hi @bmunkholm  - Thanks I have already opened a new issue [here](https://github.com/realm/realm-js/issues/2814) #2814
