### ISSUE TITLE
Problems with API reference (realm.io/docs/javscript/latest/api)

### ISSUE THREAD

**Issue by MrHubble** [realm/realm-js#1558]
Page (realm.io/docs/javscript/latest/api) appears as below on both Safari and Chrome:

![screen shot 2017-12-07 at 11 41 49 am](https://user-images.githubusercontent.com/2251631/33692879-af0e0620-db43-11e7-8d07-321eafdbfb5b.png)

All links seem to give a 404:

![screen shot 2017-12-07 at 11 42 28 am](https://user-images.githubusercontent.com/2251631/33692891-c17fce88-db43-11e7-9c99-28c2e0c3bd40.png)

**Comment by kneth** [comment]
I can see the page just fine. Please try to reload.

**Comment by MrHubble** [comment]
I just tried in Firefox (so I've tried in 3 different browsers in total) and cleared the cache and still had the same result. The following errors were shown in the console:

<img width="1136" alt="screen shot 2017-12-10 at 7 04 52 pm" src="https://user-images.githubusercontent.com/2251631/33803169-3e8ccdd6-dddd-11e7-898e-c9bf85d26cb2.png">

**Comment by kneth** [comment]
@pixelchef Do you have a suggestion?

**Comment by kneth** [comment]
We have updated the website recently.

**Comment by MrHubble** [comment]
FYI, I'm still experiencing the same behaviour and it has not been fixed.

**Comment by bdash** [comment]
It looks like this happens if you load https://realm.io/docs/javascript/latest/api (with no trailing slash) rather than https://realm.io/docs/javascript/latest/api/.

**Comment by MrHubble** [comment]
Ahh, great find. You are right. Thanks.

**Comment by kneth** [comment]
It seems to be a "feature" for all of products' API pages, and I have created an issue for our web team.

**Comment by nlarew** [comment]
Closing - we'll soon be migrating the realm docs to the MongoDB docs platforms which will fix this issue.
