### ISSUE TITLE
Local realm not synced after losing connection and forcing re-login

### ISSUE THREAD

**Issue by rubengarciam** [realm/realm-js#1562]
**Goals**

Start app online, go offline, add item(s), force close the app, go back online, open the app and force a log in. Edits while offline are pushed back to ros.

**Expected Results**

As soon as the user is back and the app is online, resume syncing.

**Actual Results**

If I just go back online, sync happens fine
If I force Close the app, reopen it and force a login, the changes are not pushed. Instead, the local copy has the previous state before it went offline

**Steps to Reproduce**

Explained above

ROS 2.0
Realm-js: 2.0.12

**Comment by kneth** [comment]
@rubengarciam We did a bug fix in 2.1.1 related to reconnects so please upgrade and report back.

**Comment by rubengarciam** [comment]
Great to know! Will do after https://github.com/realm/realm-js/issues/1576 😋

**Comment by kneth** [comment]
Looking at https://github.com/addaleax/lzma-native/issues/45, it might actually not be LZMA but fsevent 😢

**Comment by rubengarciam** [comment]
@kneth I finally upgraded to 2.2.6 but the output is still the same

**Comment by kneth** [comment]
@rubengarciam Thanks for the update.

**Comment by kneth** [comment]
@rubengarciam Do you still experience the issue?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
