### ISSUE TITLE
Extract an auth package for use with js libraries

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1571]
We had to duplicate some of the auth logic for the realm-graphql client and likely for other upcoming js libraries. It'd be nice to extract a realm-auth (name TBD) package that contains the login and token refresh logic (including proactive refreshes) so that we don't duplicate code and effort.

**Comment by nirinchev** [comment]
This can probably help Studio as well. cc @kraenhansen

**Comment by kneth** [comment]
The upcoming `realm-web` will provide this.
