### ISSUE TITLE
Tests failing with unresolved dependencies

### ISSUE THREAD

**Issue by MaxRis** [realm/realm-js#1588]
## Goals

Build and run tests for node.js platform

## Expected Results

Tests passed fine

## Actual Results
Error: /XXX/realm-clone/realm-js/compiled/node-v51_linux_x64/realm.node: undefined symbol: _ZN5realm18SharedGroupOptions11sys_tmp_dirB5cxx11E
    at Object.Module._extensions..node (module.js:598:18)

## Steps to Reproduce

Run `npm test node`

## Version of Realm and Tooling

- Realm JS SDK Version: Latest clonned
- Node or React Native: Node
- Client OS & Version: Ubuntu, 16.04 LTS
- Which debugger for React Native: None

Similar failure occurs if I try to load "realm.node" from custom JS code.

**Comment by kneth** [comment]
Yes, I think I can reproduce it, and I hope to have a fix ready soon.

**Comment by kneth** [comment]
It was fixed in 2.2.0
