### ISSUE TITLE
Updating Objects With Primary Keys in tests gets stuck

### ISSUE THREAD

**Issue by jerdie** [realm/realm-js#1590]
## Goals

Test a functionality with upsert using jest tests

## Expected Results

model should be updated in tests

## Actual Results

Test does not stop

## Steps to Reproduce
1. create test with Update Objects With Primary Keys
2. npm run test
3. run test again

## Code Sample

**\_\_tests__/TestRealm.js**
```javascript
import Realm from 'realm';
import User from '../src/data/models/User';

describe("Testing realm upsert", () => {
    test("upsert", () => {
        const realm = new Realm({schema: [User]});
        let user = null;
        realm.write(() => {
            user = realm.create(User.schema.name, {username: "user1", firstName: "user"}, true);
        })
        expect(user.firstName).toBe("user")
        realm.write(() => {
            user = realm.create(User.schema.name, {username: "user1", firstName: "user2"}, true);
        })
        expect(user.firstName).toBe("user2")
    })
})

```
**src/data/models/User.js**
```
export default class User {
    static schema = {
        name: 'User',
        primaryKey: 'username',
        properties: {
            username: {type: 'string', optional: true},
            firstName: {type: 'string', optional: true},
            lastName: {type: 'string', optional: true},
            company: {type: 'string', optional: true},
            email: {type: 'string', optional: true},
            roles: 'string?[]',
        },
    }
}

```

![realmupserttest](https://user-images.githubusercontent.com/5143814/34385296-91ceadde-eb5c-11e7-9341-70d447a1833a.PNG)

There was a certain time i left it for 30 mins and its still running.

## Version of Realm and Tooling

```
{
  "name": "testRealm",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0"
  },
  "devDependencies": {
    "babel-jest": "22.0.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.0.4",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
- React Native
- Windows 10

**Comment by fealebenpae** [comment]
Hey @jerdie, I think I know why this is happening - a realm instance subscribes to the uv eventloop to watch the database file for changes and if it’s not closed Node.js will not exit. Try calling `close()` on the realm in the end of each test.

**Comment by jerdie** [comment]
@fealebenpae - thanks for the feedback. Not sure what happened on my first run, but when I restarted my machine, the tests ran fine. However, after trying to replicate again, I noticed that this happens when I am running multiple tests wich is accessing realm. I tried creating a duplicate tests of TestRealm, cleared jest cache and run jest test. Now all three of them are stuck in running. all of them have realm.close() at the end.

same thing happens with jest --no-cache

![realmupserttest](https://user-images.githubusercontent.com/5143814/34401998-db1cf82e-ebd9-11e7-81c2-f17d7dbcf324.PNG)

However, If I run with --runInBand, all tests run sequentially and pass. All tests will also pass when running test without --runInBand.

**Comment by fealebenpae** [comment]
Ah, of course - I hadn’t realized jest runs tests concurrently. Their implementation might cause issues with Realm’s shared state. You can try setting `cache: false` on the Realm constructor configuration object or, if that doesn’t work, disable running tests in parallel.

**Comment by fealebenpae** [comment]
Another option is to specify an explicit `path` in the constructor configuration so that no two tests try to run at the same time with the same file on disk which could cause deadlocks. Right now all tests try to use the default `default.realm` file - instead each test should use a unique file.

**Comment by jerdie** [comment]
Tried setting random path for each test and set inMemory to true. But realm dbs are still created on disk. Am i missing something on how to make inMemory work? Realms are filling my directory. I also don't want to create file for every test. Can you suggest other ways to set path?

**Comment by jerdie** [comment]
Hi, I tried to set path explicitly and I noticed it creates realm, .lock and management directory. I used inMemory but it only deletes realm file but not .lock and .management dir.

**Comment by bmunkholm** [comment]
@jerdie Sorry this was overlooked. You can delete them manually when the Realm has been closed.
