### ISSUE TITLE
EXC_BAD_ACCESS: Attempted to dereference garbage pointer (Async function in migration)

### ISSUE THREAD

**Issue by dotcom900825** [realm/realm-js#1598]
## Goals

We have a green field react-native app that heavily uses Realm.js and it has been really instrumental in our dev team. 

After we launched the app a few weeks ago, we've been consistently seeing two fatal native error that shows up on our Sentry service: 
```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x148.
Originated at or in a subcall of OpaqueJSValue const* realm::js::wrap<&(realm::js::RealmClass<realm::jsc::Types>::get_schema_version(OpaqueJSContext const*, OpaqueJSValue*, realm::js::ReturnValue<realm::jsc::Types>&))>(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)
```

```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x10.
Originated at or in a subcall of folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)
```
After looking through most of the exceptions on Sentry, most of them happened after we successfully fetched over some data and start to update the Realm.

We have about 2000 daily active users, and we are seeing about 100 occurrences per day for the first exceptions and about 15-30 occurrences for the second one.

We'd like to get some insight on what might cause those exceptions and what are some recommended way for us either fix the issue or better pin-point or trace back closer to the root cause.

We are using Microsoft's code-push service just FYI. And we noticed that in most of those exceptions, the mobile device's free memory usually looks small, eg:
- iPhone X: `Total: 2.7 GB / Free: 116.1 MB / Usable: 2.0 GB`
- iPhone 8 Plus: `Total: 2.9 GB / Free: 170.2 MB / Usable: 2.4 GB`
- iPhone 8: `Total: 1.9 GB / Free: 46.0 MB / Usable: 1.5 GB`
- iPhone 7 plus: `Total: 2.9 GB / Free: 139.5 MB / Usable: 2.5 GB`
- iPhone 7: `Total: 2.0 GB / Free: 70.0 MB / Usable: 1.4 GB`
- iPhone 6 Plus: `Total: 969.0 MB / Free: 23.1 MB / Usable: 673.5 MB`
- iPhone 6: `Total: 989.0 MB / Free: 28.0 MB / Usable: 773.4 MB`
- iPad Pro (10.5-inch): `Total: 3.9 GB / Free: 1.3 GB / Usable: 3.6 GB`
- iPad Pro (12.9-inch, 2nd generation): `Total: 3.9 GB / Free: 369.6 MB / Usable: 3.2 GB`
- iPad (5th generation): `Total: 1.9 GB / Free: 111.1 MB / Usable: 1.4 GB`
- iPad Air 2: `Total: 1.9 GB / Free: 70.5 MB / Usable: 1.4 GB`

## Expected Results
Be able to finish the Realm write/update flow without crashing the app.

## Actual Results
The app is crashing from time to time, which cause customer missing data and have to try do data reset on the mobile app.

First exception stack trace:
```
EXC_BAD_ACCESS
Attempted to dereference garbage pointer 0x10.
Originated at or in a subcall of folly::Expected<long long, folly::ConversionCode> folly::detail::str_to_integral<long long>(folly::Range<char const*>*)
```
![0x10](https://user-images.githubusercontent.com/1175408/34632196-f6e8765a-f228-11e7-9fae-9527eb6471b6.png)

Second exception stack trace:
```
EXC_BAD_ACCESS
Attempted to dereference garbage pointer 0x148.
Originated at or in a subcall of OpaqueJSValue const* realm::js::wrap<&(realm::js::RealmClass<realm::jsc::Types>::get_schema_version(OpaqueJSContext const*, OpaqueJSValue*, realm::js::ReturnValue<realm::jsc::Types>&))>(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)
```
![0x148](https://user-images.githubusercontent.com/1175408/34632263-4b72f6e6-f229-11e7-9bc8-7fda3a2158ca.png)

## Steps to Reproduce
We haven't able to get a solid reproduce locally in our dev environment

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.6
- Node or React Native: 0.50.3
- Client OS & Version: Different type of iOS devices ranging from iPhone 6 to the newlest iPhone X
- Which debugger for React Native: ?/None
- React-Native-Code-Push: 5.2.0-beta

**Comment by kneth** [comment]
`get_schema_version` is the C++ implementation of property `Realm.schemaVersion` and the method `Realm.schemaVersion(path)` so maybe you can inspect your code for these?

**Comment by dotcom900825** [comment]
@kneth Since we are seeing the a lot of this type of exceptions happens in scenarios such as: when the user used it in the morning for a while, switch to a different one and in the afternoon when they try to open it, the crash happens.

This makes us think if the original pointner gets garbage collected.

So the way we setup our Realm instance is pretty much the same as in https://github.com/realm/realm-js/blob/master/examples/ReactExample/components/realm.js, we export the instanaiated Realm object out and all the other modules will just import it and use it. 

```
import {
  AsyncStorage,
} from 'react-native';
import Realm from 'realm';
import ModelA from 'modelA';
import ModelB from 'modelB';

// Migrations
import version21Migration from './migrations/version21';

async function migration(oldRealm, newRealm) {
  if (oldRealm.schemaVersion < 21) {
    version21Migration(oldRealm, newRealm);
  }
  if (oldRealm.schemaVersion < 26) {
    await AsyncStorage.mergeItem('abc', JSON.stringify({
      foo: true,
      bar: true
    }));
  }
}

const realm = new Realm({
  schema: [
    modelA,
    modelB
  ],
  schemaVersion: 31,
  migration,
});

export default realm;
```

Do you think if this can actually be the issue, re-opening a app from the background or suspended state sometimes will cause the pointer to be G'Ced.

**Comment by dotcom900825** [comment]
@kneth We figured out the issue recently, the root cause is we have made the migration function as an async call. Seems like the new schemaVersion gets applied before the migration function returns, thus if our migration block has a few async await calls, there is a possibility that when we calling `oldRealm.schemaVersion` the `oldRealm` pointer becomes invalid because the schema changes has already been applied and the old Realm becomes unavailable.

**Comment by fealebenpae** [comment]
The migration callback is always synchronous - async functions are not supported.

**Comment by kneth** [comment]
@dotcom900825 Did your migration succeed when you changed it to a sync. call?

**Comment by dotcom900825** [comment]
@kneth Sorry for the late response, after we change it to synchronous call it works fine.

**Comment by kneth** [comment]
@dotcom900825 Happy to hear!
