### ISSUE TITLE
Save json with multiple objects and arrays

### ISSUE THREAD

**Issue by sureshsharma** [realm/realm-js#1604]
## Goals

I am new to realm, I achieved saving data with simple json but now i have a json with multiple objects and arrays and i have spend huge time trying achieve this. Any help will be appreciated.

## Code Sample
"status": 200,
    "message": "Success",
    "data": [
        {
            "containerStatus2": "Loaded",
            "stops": [
                {
                    "city": "ADDSTOPCITY",
                    "street": "ADDSTOPSTREET",
                    "company": "ADDSTOP",
                    "time1": "",
                    "time2": "",
                    "po": "PO",
                    "load_id": "769",
                    "date": "",
                    "id": "70"
                }
            ],
            "containerStatus": "Loaded",
            "instructions": "testing load",
            "dispatcher": {
                "status": 0,
                "device": "",
                "name": "admin",
                "created": 1491989234,
                "admin": 1,
                "locationUpdated": "",
                "longitude": "",
                "image_url": "https://lorempixel.com/200/200/technics/6",
                "os": ""
            },
            "docs": [
                {
                    "link": "https://alfred.urbantrucking.com/static/uploads/hhzgkplbqdec.jpg",
                    "type": "POD",
                    "name": "marijuana-map-large.jpg"
                },
                {
                    "type": "BOL",
                    "link": "https://alfred.urbantrucking.com/static/uploads/jttojntemolt.jpg",
                    "name": "lab-test.jpg"
                }
            ],
            "created": "Jan-01-2018, 09:36 PM",
            "pods": [],
            "container2": ""
        }],
    "success": 1
}

**Comment by kneth** [comment]
@sureshsharma I suggest that you ask the question at StackOverflow as we use Github issue primarily for bug reports and feature requests.

**Comment by sureshsharma** [comment]
All right, Thanks...
