### ISSUE TITLE
subscribeToObjects is not a function in Chrome Debugger

### ISSUE THREAD

**Issue by ozmaat** [realm/realm-js#1608]
I could debug react native app without any issues till now but chrome debugger raises an error with partial sync realm for subscribeToObjects function.

If debug js remotely is turned off, app works, but when it is turned on it causes the following error. 

Possible Unhandled Promise Rejection (id: 0):
TypeError: _this.partialRealm.subscribeToObjects is not a function

Realm login function

```
 Realm.Sync.User.login(
      `http://${REALM_SERVER}`,
      USER_NAME,
      USR_PASSWORD
    ).then(user => {
      let config = {
        sync: {
          user: user,
          url: `realm://${REALM_SERVER}/${realmName}`,
          partial: true
        },
        schema: schemas
      };

const realm = new Realm(config);
```

Realm open function

```
Realm.open({
      schema: schemas,
      sync: {
        user: Realm.Sync.User.current,
        url: `realm://${REALM_SERVER}/${realmName}`,
        partial: true
      }	  

```

Subscribing to objects

```
let posts = this.partialRealm
          .subscribeToObjects("Posts", "userid =='c8792c1'")
          .then((userPosts, error) => {});

```

I can see the subscribeToObjects as a defined function of Realm object at the console but debugger can't evaluate it.

The code seems ok as the app works without "debug js remotely".

- Realm JS SDK Version: 2.0.13
- React Native: 0.50.3
- Client OS & Version: ? Windows 10
- Which debugger for React Native: Chrome

**Comment by kneth** [comment]
It looks like `subscribeToObjects` has been added to properties instead of methods. We'll fix it in the next release but you can manually move https://github.com/realm/realm-js/blob/master/lib/browser/index.js#L64 to https://github.com/realm/realm-js/blob/master/lib/browser/index.js#L137 as a workaround.

Thanks for reporting.

**Comment by ozmaat** [comment]
Thanks kneth.

I have moved the function but now get the following error.

```
Cannot assign to read only property 'subscribeToObjects' of object '#<Realm>'
module.exports
    ...node_modules\realm\lib\extensions.js:151:8
```

**Comment by kneth** [comment]
Try to remove it. The method is implemented in JavaScript (in `extensions.js`) but calls a C++ method (`_subscribeToObjects`). In general, it can be difficult to debug apps with sync involved since the objects are modified outside the app (in the "invisible" sync thread).

**Comment by ozmaat** [comment]
I am not sure what you meant by "try to remove it". Do you mean not using the partial subscription at all. Could you please give some hint?

**Comment by kneth** [comment]
@ozmaat Sorry to be unclear. I meant that you should try to remove `subscribeToObjects` from `lib/browser/index.js`.

**Comment by ozmaat** [comment]
Thanks again. But it gives the original error when I remove the `subscribeToObjects` from lib/browser/index.js.

`TypeError: realm._subscribeToObjects is not a function`

Could we expect this to be resolved with the next release as it makes using debugging not possible.

**Comment by kneth** [comment]
@ozmaat Yeah, I hope to include a solution in the next release.

**Comment by ozmaat** [comment]
Thanks again. Look forward for the next release.
