### ISSUE TITLE
Release application build crashing

### ISSUE THREAD

**Issue by Alirun** [realm/realm-js#1609]
## Goals

Hi there!

I'm developing an application in react-native, which works properly in development mode.

## Expected Results

I wanted to test it's performance and build a release version.

## Actual Results

Release build crushed right after the launch.

````
01-09 20:16:13.644 23215 23251 E ReactNativeJS: Object type 't' not found in schema.
01-09 20:16:13.648 23215 23251 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
````

## Code Sample

`schemas/beer.js`
````
class Beer {}

Beer.schema = {
  name: 'Beer',
  primaryKey: 'id',
  properties: {
    id: 'int',
    title: 'string',
    type: {type: 'string', indexed: true}
  }
}

export { Beer }
````

`schemas/bar.js`
````
class Bar {}

Bar.schema = {
  name: 'Bar',
  primaryKey: 'id',
  properties: {
    id: 'int',
    title: 'string'
  }
}

export {Bar}
````

`schemas/index.js`
````
import { Bar } from './bar';
import { Beer } from './beer';

export const Schemas = {
    Bar: Bar,
    Beer: Beer
}
````

`baseRealm.js`
````
import Realm from 'realm'

import { Schemas } from './schemas'

export class BaseRealm {

  static get Schemas() { return Schemas; }

  constructor(modelName) {
    this.modelName = modelName;
    this.r = new Realm({ schema: Object.values(BaseRealm.Schemas), deleteRealmIfMigrationNeeded: true });
  }

  find(id) {
    return this.r.objectForPrimaryKey(this.modelName, id);
  }

  getAll() {
    return this.r.objects(this.modelName);
  }

  deleteById(id) {
    return this.delete(this.r.objectForPrimaryKey(this.modelName, id));
  }
}
````
And then I extend `barRealm.js` and `beerRealm.js` from `BaseRealm`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.1.1
- React Native: 0.49.5
- Client OS & Version: Android / Any Version

**Comment by kneth** [comment]
Out support for classes is somewhat limited: https://realm.io/docs/javascript/latest/#classes. 

Btw, should `this.delete` be `this.r.delete`?

**Comment by Alirun** [comment]
Sorry, problem was using class's name `Schemas.Beer.name` instead of schema's name `Schemas.Beer.schema.name`, which was changed by uglifier. It works properly now!
