### ISSUE TITLE
Expose per session connection state handler

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#1614]
This handler was added to sync: https://github.com/realm/realm-sync/issues/1890

We should expose for public use.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nirinchev** [comment]
This likely needs to be exposed at the OS level first.

**Comment by kraenhansen** [comment]
This issue that we're having in Studio would benefit greatly from an API like this:  https://github.com/realm/realm-studio/issues/650

**Comment by kraenhansen** [comment]
This is third from the bottom of the backlog - I would love to see this get prioritized higher as it would greatly increase the users experience of Studio when a disconnect happens.

**Comment by bmunkholm** [comment]
@kraenhansen The Backlog issues are not ordered. But I've moved it to the top as being at the bottom makes it likely to not being actively prioritized :-)

**Comment by kraenhansen** [comment]
Ehm ... OK? 😕  Are there good reasons we don't practice Scrum and keep those backlogs in prioritized order?

I think that would dramatically increase transparency of prioritization and make it easier to project when stuff will get done.

I want to create an issue tracking this - would https://github.com/realm/realm-wiki with a `T:Process` be a good place?

**Comment by bmunkholm** [comment]
Let's not hijack this issue for process discussion. I suggest to take it in #eng-process in Slack for a start.

**Comment by ianpward** [comment]
@roberhofer assigning to you for client-side product backlog prioritization

**Comment by roberhofer** [comment]
Reflected in AHA under: https://realmio.aha.io/features/SDK-17

**Comment by roberhofer** [comment]
According to @cmelchior this is addressed as per https://github.com/realm/realm-js/pull/1950
