### ISSUE TITLE
Prebuilds for node@9 and Electron on Linux

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1640]
## Goals

I want to use Realm JS for Electron from node@9.

## Expected Results

I would expect Realm JS being prebuilt for node module version 59 (for Electron on Linux)

## Actual Results

It installs from source when

## Steps to Reproduce

`nvm install 9 && npm install realm`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.4
- Node or React Native: Node
- Client OS & Version: Linux
- Which debugger for React Native: None

**Comment by fealebenpae** [comment]
We’ve had binaries for v59 on S3 for quite some time and I just confirmed that 2.2.4, 2.2.5, and 2.2.6 all have the v59 binary for Windows, macOS, and Linux.

Could you please paste your output from `npm install realm`?

**Comment by kraenhansen** [comment]
Okay - this is strange, then.

It seems that `realm-object-server` depends on `realm@1.12.0` - perhaps for migrations?:

```
> realm@2.1.1 install /project/node_modules/realm-object-server/node_modules/realm
> node-pre-gyp install --fallback-to-build

[realm] Success: "/project/node_modules/realm-object-server/node_modules/realm/compiled/node-v59_linux_x64/realm.node" is installed via remote

> realm@1.12.0 install /project/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/1.12.0/realm-v1.12.0-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@1.12.0 and node@9.3.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/project/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/build'
  ACTION binding_gyp_vendored_realm_target_download_realm /project/node_modules/realm-object-server/node_modules/realm-one/node_modules/realm/vendor/realm-node
Downloading dependency: realm-node 2.8.6
https://static.realm.io/downloads/core/realm-core-node-linux-2.8.6.tar.gz
Skipping the sync download because ENABLE_SYNC is false.
```

**Comment by fealebenpae** [comment]
@nirinchev ^

**Comment by kraenhansen** [comment]
Well - I won't expect Realm 1 to be pre-built for node@9 / 59, so I'm closing this for now and will fix it by ensuring the electron-builder don't install / build native modules for the realm-object-server.

**Comment by kraenhansen** [comment]
I've fixed this by temporarily downgrading to node 8 - and created https://github.com/realm/realm-object-server-private/issues/874 on the ROS repo as it seems this is where the fix needs to go.
