### ISSUE TITLE
The Javascript documentation menu in the website is not being renderend, instead I got a '*'

### ISSUE THREAD

**Issue by ivanquirino** [realm/realm-js#1641]
## Goals

Trying to browse the docs

## Expected Results

I expected to see the extensive menu which helps me read the docs faster

## Actual Results

I've got a '*' instead of the menu

## Steps to Reproduce

Browse to the docs, click 'Javascript'. No menu appears, a wild '*' appears.

![docsmenubug](https://user-images.githubusercontent.com/3946025/35460791-f007f99a-02c3-11e8-924f-42c047cb72a2.JPG)

## Version of Realm and Tooling
Current live website

**Comment by kneth** [comment]
Thanks for reporting. I'll fix it asap.

**Comment by nirinchev** [comment]
This has been fixed.

**Comment by ivanquirino** [comment]
That's nice, thank you!
