### ISSUE TITLE
Results.sorted documentation incorrect.

### ISSUE THREAD

**Issue by RobertBisson** [realm/realm-js#1644]
## Goals

Documentation for sorting with multiple properties is incorrect. API docs also omit that an array can be passed in the parameters block.

## Expected Results

Documentation correctly lists details on how to sort with multiple properties.

## Actual Results
Documentation for sorting with multiple properties is incorrect. See below.

## Steps to Reproduce

<img width="595" alt="screen shot 2018-01-30 at 12 23 22 pm" src="https://user-images.githubusercontent.com/7608385/35544905-625f3d4a-05b8-11e8-8398-b447a67bc03a.png">

<img width="645" alt="screen shot 2018-01-30 at 12 23 50 pm" src="https://user-images.githubusercontent.com/7608385/35544921-727a8d56-05b8-11e8-9f7d-e5f516a39d07.png">

**Comment by kneth** [comment]
I updated the documentation last week with this change. Maybe your browser's cache needs to be refreshed?

![screen shot 2018-01-30 at 12 03 43](https://user-images.githubusercontent.com/1225363/35563050-c00426a2-05b5-11e8-9c1a-b013b9518f74.png)

**Comment by RobertBisson** [comment]
The issue is still there. For multiple sorting the syntax is as follows:

sortedHondas = hondas.sorted( [ ["price", true], ["miles", false] ] );

Not:
sortedHondas = hondas.sorted(["price", true], ["miles", false]);

IE you pass in 1 array containing your descriptors, not multiple arrays.

**Comment by kneth** [comment]
https://github.com/realm/realm.io/pull/4314

**Comment by kneth** [comment]
@RobertBisson I have updated the docs.
