### ISSUE TITLE
react-native run-ios fails while downloading realm-sync-cocoa

### ISSUE THREAD

**Issue by prashantham** [realm/realm-js#1647]
## App to be displayed on simulator

/bin/sh -c /Users/prashanth/workspace/react-native/shree/ios/build/Build/Intermediates.noindex/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
SYNC_ARCHIVE: 'realm-sync-cocoa-2.2.9.tar.gz',
SYNC_ARCHIVE_ROOT: 'core' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-2.2.9.tar.gz
Extracting realm-sync-cocoa-2.2.9.tar.gz => /Users/prashanth/workspace/react-native/shree/node_modules/realm/vendor/realm-ios
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
Command /bin/sh failed with exit code 1

## Steps to Reproduce
react-native run-ios

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.6
- Node or React Native: 0.52.2
- Client OS & Version: mac os x High Sierra
- Which debugger for React Native: ?/None

**Comment by prashantham** [comment]
Seems like the cached version or corrupt/not fully downloaded. Deleting it and re-downloading worked.

**Comment by MujtabaFR** [comment]
How did you clean the cached version @prashantham ?!
Cleaning the project and the derived data doesn't seem to work

**Comment by prashantham** [comment]
Have not used realm for a while. But the downloads were cached in a folder. I think its displayed while compiling. Sometime due to network issues those would not be downloaded fully . Hence i cleared and re-ran it.
