### ISSUE TITLE
push method was not called on a Realm object! - when Chrome Debugger enabled

### ISSUE THREAD

**Issue by ozmaat** [realm/realm-js#1657]
Following push method is throwing the exception  `push method was not called on a Realm object!` when remote debugging enabled. 

```
this.partialRealm
          .subscribeToObjects(
            Constants.SCHEMAS.Favorites,
            "userid=='" + userId + "'"
          )
          .then((userPosts, error) => {
			this.userFavoritePosts = userPosts[0].posts;
		  })

this.userFavoritePosts.push(
            realm.create("Posts", { id: postId, post: postText }, true)
          );
```

	

This function work as expected when debugging is disabled. 

- Realm JS SDK Version: ?  Tested on both 2.2.6 and 2.2.7
- Node or React Native: ? React Native
- Client OS & Version: ? Windows 10
- Which debugger for React Native: ?/None -Chrome Debugger

**Comment by kneth** [comment]
We have reworked much in the support of the Chrome debugger. Please upgrade.

I close the issue, but if the problem persist after upgrading, don't hesitate to reopen or create a new issue.
