### ISSUE TITLE
Partial Realm - create with linked object - don't work with primary key

### ISSUE THREAD

**Issue by ozmaat** [realm/realm-js#1661]
Following create function works for a non-partial realm, where we provide the posts linked object for favorites model as  `posts: [{ id: postId }]`

But same code for a partial realm requires the other properties and throws the following error.

`Missing value for property 'Posts.post'`

```
PostModel.schema = {
  name: "Posts",
  primaryKey: "id",
  properties: {
    id: "int",
    post: "string"
  
  }
};

FavoritesModel.schema = {
  name: "Favorites",
  primaryKey: "userid",
  properties: {
    userid: "string",
    posts: "Posts[]"
  }
};


realm.create(
          "Favorites",
          {
            userid: userId,
            posts: [{ id: postId }]
          },
          true
        );
```

Realm JS SDK Version: ?  2.2.7
Node or React Native: ? React Native
Client OS & Version: ? Windows 10
Which debugger for React Native: ?/None -Chrome Debugger

**Comment by kneth** [comment]
@ozmaat Sorry for the delay. You mention that you are using partial sync. Can your provide the query?

Partial sync is currently in tech preview, so we are eager to learn how developers are using it :smile:

**Comment by ozmaat** [comment]
I use the partial realm for querying user's favorites records. 

```
this.partialRealm
          .subscribeToObjects(
            "Favorites",
            "userid=='" + userId + "'"
          )
          .then((userFavs, error) => {
            if (!error) {
              
              if (userFavs.length > 0) {
                this.userFavorites= userFavs[0].posts;
               } 
			else {
              console.log("error");
            }
          })
          .catch(e => {
             console.log("error");
          });
```

Btw, I have just checked if partial realm is working by downloading the realm db from emulator and opened in realm studio. But it seems , not only the userId given in the query but all records are downloaded to local device.

**Comment by kneth** [comment]
As support for query-based Realms was dropped in v10.0.0, I close the issue.
