### ISSUE TITLE
Can not start Realm server

### ISSUE THREAD

**Issue by NoaSironen** [realm/realm-js#1663]
Hello,
I am just starting to learn React Native and am now trying to solve the server side of the application I am building. After a bit of searching around it seemed like Realm was the way to go. I have now encountered the described problem and do not know how to proceed. Thank you for your time.
## Goals

Start a Realm server.
## Expected Results

Starting of a realm server.
## Actual Results

Error descriped below.

Error: Cannot find module '../compiled/win32-x64/node-v57/realm-sync-server.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\<localuser>\AppData\Roaming\npm\node_modules\realm-object-server\node_modules\realm-sync-server\lib\index.js:11:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
## Steps to Reproduce

npm install -g realm-object-server
react-native link
ros start
## Version of Realm and Tooling

- Realm JS SDK Version: 
- Node or React Native: 
node: 8.9.
react-native-cli: 2.0.
react-native: 0.52.0
- Client OS & Version:
Windows 10
- Which debugger for React Native: 
/None

**Comment by kneth** [comment]
@NoaSironen Which version of Realm JavaScript do you use?

**Comment by NoaSironen** [comment]
@kneth Since the project was on a deadline we did not have time to solve this and moved on to another database option. Thank you for your comment.

**Comment by fealebenpae** [comment]
Realm Object Server does not support Windows.

**Comment by NoaSironen** [comment]
@fealebenpae This issue is now closed as we moved on to another database option. Thank your time and help.

**Comment by marcus-sa** [comment]
Would be a great idea to actually STATE that the server isn't supported for Windows, lol

**Comment by ianpward** [comment]
Stated here:
https://docs.realm.io/platform/self-hosted/installation#supported-operating-systems

**Comment by ttous** [comment]
> 
> 
> Stated here:
> https://docs.realm.io/platform/self-hosted/installation#supported-operating-systems

_"Page not found"_
I know I'm late on this topic but today the documentation still contains dead links and looping links. I may have read it wrong, but I did not realized self-hosted servers were not supported for Windows users. I guess I have to use a cloud hosted one.
