### ISSUE TITLE
mmap() failed: Out of memory size error on Android

### ISSUE THREAD

**Issue by SemperChen** [realm/realm-js#1669]
Hello,

I'm seeing the error in our bug report on Bugsnags, when calling realm.write:
mmap() failed: Out of memory size: 11534336 offset: 0
Interestingly after this first crash there could be subsequent one indicating:
The Realm is already in a write transaction.
Have you guys heard of anything like this? Any ideas of how to debug this ( what to log, what to ask) ?

Thank you for the help!

**Comment by kneth** [comment]
Do you know which version of Android it is? How much memory does the device have?

React Native is 32 bit only, and you might see some memory limitation due to that.

Out-of-memory could indicate that you have a Realm instance which is not updated after another Realm's write transactions. As Realm is a [MVCC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control) database, holding on to an old version might prevent Realm to reuse memory.

**Comment by SemperChen** [comment]
global.realm = new Realm({schema: [ArticleSchema]});
...
export const ArticleSchema = {
    name: 'Article',
    primaryKey: 'id',
    properties: {
         @id:'string',
        currentChapterNum: 'int',
        tag:'string',
        content:'string',
        articleUrl:'string'
    }
};
...
for(let i=0;i<catalog.length;i++){
realm.write(() => {
                realm.create('Article', {
                    id: this.props.articleTag + this.startNum,
                    tag: this.props.articleTag,
                    currentChapterNum: this.startNum,
                    content: content,
                    articleUrl: articleUrl
                }, true);
            });
}
...
Android7.1
React Native 0.49.5

**Comment by kneth** [comment]
It might help to do one big transaction instead of many smalls transaction. What is the value of `catalog.length`? Do you insert big `content` strings? Do you have other Realm instances open?

**Comment by abhisharkjangir** [comment]
In Realm Javascript, i'm also getting `**mmap() failed : Out of memory size error in Android**` when i'm opening any new Realm instance.

Is anyone found the solution?

**Comment by kneth** [comment]
@abhisharkjangir Can you provide a stack trace (`adb logcat`)? Which device are you using? Does the Realm already exist, and if so, how large is it?

**Comment by abhisharkjangir** [comment]
@kneth  This is resolved. It was occurred due to opening multiple instances & not closing them in Android Native.

**Comment by kneth** [comment]
I close the issue as the solution by @abhisharkjangir  is often the case when `mmap` grows out of control :smile:
