### ISSUE TITLE
Supporting Filtering Based off array properties (ANY predicate)

### ISSUE THREAD

**Issue by andrew-wagner89** [realm/realm-js#1674]
## Goals
Is there a plan to support ANY predicates in the future?

## Expected Results

For example given a model like the following:
```
const PersonSchema = {
  name: 'Person',
  properties: {
    name:     'string',
    nicknames: 'string[]',
  }
};
```

Would it be possible using a query to filter out objects who's nicknames array contains a certain name like: 
`realm.objects('Person').filtered('ANY nicknames = "Chip"');
`

**Comment by bdash** [comment]
For queries with Realm JS, `ANY` is implicit for key paths that traverse arrays. The other sticking point with your query is that queries over arrays of primitives are not yet supported.

**Comment by andrew-wagner89** [comment]
Gotcha thanks. Is there a plan to support queries over arrays of primitives in the near future?

**Comment by bdash** [comment]
I don't have a timetable to share at this time.

**Comment by andrew-wagner89** [comment]
Okay I'll just implement it manually then. Thanks for the quick answers!

**Comment by bdash** [comment]
One way to work around this limitation is to add a type like `StringObject` with a single `value` property of type `String`. You could then filter using a predicate like `nicknames.value = "Chip"`.

**Comment by andrew-wagner89** [comment]
Oh that could work. I'll try that instead thanks! Just curious, whats the difficulty in querying primitive arrays compared to object arrays?

**Comment by bdash** [comment]
The underlying storage for arrays of objects and arrays of primitives are quite different, and so new code needs to be written to support queries involving arrays of primitives. It's not just a matter of tweaking the existing code for arrays of objects.

**Comment by anshumanworks** [comment]
> One way to work around this limitation is to add a type like `StringObject` with a single `value` property of type `String`. You could then filter using a predicate like `nicknames.value = "Chip"`.

Thanks for the reply, can you please help me on how can I query for the first `nicknames.value that is not Chip`?
