### ISSUE TITLE
Realm.open Modifies Realm.ObjectClass Elements of schema Array

### ISSUE THREAD

**Issue by 509dave16** [realm/realm-js#1675]
## Goals

- Open a realm with an array of ES6 classes in Typescript that satisfy the Realm.ObjectClass interface without any side affects to the ES6 classes in the array. This only happens in Typescript. No issues in Javascript.
## Expected Results
- I expected that upon opening a realm, no side affects to the array of ES6 classes would occur
![Before opening realm](https://s20.postimg.org/drpf0aysd/before_opening_realm.png)

## Actual Results
- The structure of the ES6 classes changed
[![After opening realm](https://s20.postimg.org/rldrpcjnx/after_opening_realm.png)](https://postimg.org/image/i0u52gubt/)
## Steps to Reproduce

* With provided code sample or one of your own do the following:
  * Declare at least one ES6 Class that satisfies the Realm.ObjectClass interface
  * Open a realm with that ES6 class passed in an array for the `schema` property of the Realm.Configuration object.
## Code Sample
- [Gist of Root Component to Register with React Native](https://gist.github.com/509dave16/b7800a3dad3c0e5fc3bfc5ffe53f3c0f)
- [Gist of tsconfig.json](https://gist.github.com/509dave16/7cddbe91016bf7a3ee4be36dc1539c61)
- [Gist of package.json](https://gist.github.com/509dave16/a97bb349a2d454cb3149f52c7ede7858)

## Solution
- The way to avoid this is to not use the same array passed to Realm.open. But instead create two separate arrays of the same model classes.
```
...
// Do not use with Realm.open
export RealmModels = [DogModel];
 // Only use with Realm.open
export RealmOpenModels = [DogModel];
```

## Version of Realm and Tooling
- Realm JS SDK Version: 2.2.6
- Node: 8.9.4
- React Native: 0.52.0
- Client OS & Version: 10.13.3
- Typescript: 2.6.2
- Which debugger for React Native: Chrome Remote Debugger

**Comment by kneth** [comment]
Thanks for reporting. We have been busy lately so we haven't had time to investigate.

**Comment by 509dave16** [comment]
@kneth I guess I should have been more clear. I am depending upon the static `schema` member of a Model class. And somehow the `schema` member goes missing from the Model class after a Realm has been opened using that Model class. But if I define a separate array of Model classes that is not used to open a Realm, the static `schema` won't get removed.

**Comment by 509dave16** [comment]
@kneth Ah. You're right. I would probably use the Realm instance `schema` property. Thanks for your help!
