### ISSUE TITLE
Partial Realm - all data downloaded to local

### ISSUE THREAD

**Issue by ozmaat** [realm/realm-js#1676]
I initialize two realms, one for non-partial and other for partial models.

```
this.realm = await initRealm(
        "realmdb",
        [
          PostModel,
          CategoryModel
        ],
        false // not partial
      );
	  
this.partialRealm = await initRealm(
        "realmdb",
        [
          PostModel,          
          FavoritesModel // has linked object to PostModel
		],
        true // partial
      );	 
``` 

Then subscribe to partial model as below.

```
this.partialRealm
          .subscribeToObjects(
            "Favorites",
            "userid=='" + userId + "'"
          )
          .then((userFavs, error) => {
            if (!error) {
              
              if (userFavs.length > 0) {
                this.userFavorites= userFavs[0].posts;
               } 
			else {
              console.log("error");
            }
          })
          .catch(e => {
             console.log("error");
          });

```
When you check the "userFavs" in console, only 1 row is filtered correctly. 

I downloaded both realm and partial realms from emulator. Realm contains all favorites not only the subscribed user. 

In Partial realm, userid seems to be undefined. 

```
matches property 	          query 	
Favorites_matches       userid=='undefined'

```
Is this a bug or am I missing something here?

- Realm JS SDK Version: 2.2.7
- Node or React Native: ? React Native - 0.52.0
- Client OS & Version: ? Windows 10
- Which debugger for React Native: Chrome Debugger

**Comment by kneth** [comment]
@ozmaat Is it possible for you to send us the files?
