### ISSUE TITLE
Feature request: provide API for `write_copy` 

### ISSUE THREAD

**Issue by vhbit** [realm/realm-js#1678]
## Goals

It would be great to have `write_copy` accessible from JS world. In our use case this might allow to create CLI apps to generate and/or preprocess realms for testing as it's much easier to do in JS than by using "native" version.

## Expected Results

Since `write` is already taken and looks more like transaction in Swift APIs, I expect to have API like `realm.saveCopy(path, encryptionKey)` or `realm.duplicateTo(path, encryptionKey)`. 
(but have to note that using of `encryptionKey` for us is definitely overkill, so that can be omitted).

## Actual Results

There is no way to create a copy.

**Comment by kneth** [comment]
I guess it is not too hard to implement. It is a matter of adding the method in `src/js_realm.hpp` which is calling [`write_copy`](https://github.com/realm/realm-object-store/blob/master/src/shared_realm.hpp#L295). We accept pull requests :-)

**Comment by vhbit** [comment]
@kneth any preference for the name?
