### ISSUE TITLE
Stringify on List type prints map of objects

### ISSUE THREAD

**Issue by vijayvbad** [realm/realm-js#1682]
## Goals

I am trying to print a realm object with a member of type list. My schema below:

MyUser.schema = {
    name: 'MyUser',
    primaryKey: 'id',
    properties: {
      id: 'string',
      name:  'Name',
      emails: {type: 'list', objectType: 'Email', default: []},
    }
}

## Expected Results

{
  "id": "5a993cc8d780c023550f060d",
  "name": {
    "firstName": "VB",
  },
  "emails": [{
      "type": "primary",
      "email": "vijayvb@gmail.cam",
      "isPrimary": true
    }
  ]
}

## Actual Results

{
  "id": "5a993cc8d780c023550f060d",
  "name": {
    "firstName": "VB",
  },
  "emails": {
    "0": {
      "type": "primary",
      "email": "vijayvb@gmail.cam",
      "isPrimary": true
    }
  }
}
## Steps to Reproduce

JSON.stringify(user);

**Comment by kneth** [comment]
[`Realm.Collection`](https://realm.io/docs/javascript/latest/api/Realm.Collection.html) isn't a JavaScript Array but an object. JavaScript Array is treated special even though it is an object.

**Comment by IgorHorta** [comment]
How should I serialize an object with nested lists ?

**Comment by kneth** [comment]
@IgorHorta If `JSON.stringify()` is not exactly what you need, you will have to traverse the object graph manually.
