### ISSUE TITLE
Partial Realm - subscribeToObjects does not work when offline

### ISSUE THREAD

**Issue by ozmaat** [realm/realm-js#1685]
GOALS
To be able to use the app in offline mode, once the first realm login is processed. (as mentioned [here](https://github.com/realm/realm-js/issues/857))

Actual Results

App does work on offline mode if no partial realm exists. It hangs on the subscribeToObjects if partial realm is used. No error is thrown.

it is not possible to use the app on offline mode if partial realm is used. 

Realm JS SDK Version: 2.2.7
Node or React Native: ? React Native - 0.52.0
Client OS & Version: ? Windows 10
Which debugger for React None

**Comment by kneth** [comment]
Partial sync will hang if you are offline.

By the way, we are currently enhancing partial sync. Version 2.3.0-beta.1 has a new API for it. You are welcome to try it but I have to warn you that 2.3.0 is use a new version of our object server and there is no way back. You can follow all the upcoming features in #1686.

**Comment by ozmaat** [comment]
Thanks @kneth. I will keep an eye on new version. 

Will the new version support offline connection for partial sync?

And if we start with non-partial for a data model and then turn that into partial, does realm automatically delete data from local device that is excluded by the partial subscribe query string.

**Comment by simonask** [comment]
Moving to use partial synchronization is equivalent to start synchronization with a different server-side endpoint. I don't think we plan to do any automatic migration there — so yes, in the simplest scenario it will look like a clean slate locally. :-)

It's not clear to me what you mean by "offline connection" — that seems like a contradiction in terms. ;-)

**Comment by ozmaat** [comment]
Thanks @simonask. I have some models that needs to be partial. Since partial sync is still not production ready, trying to understand if it is possible to migrate to partial sync in future easily, if we start with non-partial sync at first. 

Let's say, we have an X model that synced to user's local device initially, then we change the design and use partial sync for this model. User has 100 objects on his local synced realm but should have only 1 object after partial sync change. 

- Does realm create a new local copy of synced realm in this case where X model will have only 1 object. Is this what you meant by "look like a clean slate locally"

- Or still keep the original local copy , and removes the 99 objects from the local copy.


kneth mentioned that "Partial sync will hang if you are offline" for the current realmjs version. So if the device is offline, it is not possible to connect to ROS for partial sync.

**Comment by kneth** [comment]
@ozmaat We have released the new version so maybe you can try the new 2.3.x API?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
