### ISSUE TITLE
Lazy Count the number of results

### ISSUE THREAD

**Issue by Arukiap** [realm/realm-js#1687]
Is there any way of counting the number of filtered objects from a realm js query without using JS's .length property?

## Code Sample

I am doing this:

`const maleCount = realm.objects('Person').filtered('gender == "male"').length;`

And I wanted to know if there is a faster way of doing so, some Realm method as to not throw away the laziness Realm provides.

**Comment by kneth** [comment]
`.length` is implemented using functions in Realm Core (our storage/query engine), and it is a fairly cheap to compute.

If you have

```
let males = realm.objects('Person').filtered('gender == "male"');
let maleCount1 = males.length;
// do a lot but no changes to Person
let maleCount2 = males.length;
```

the second invocation of `.length` with not rerun the query.

The short answer is that we don't expose any other method to compute the length of a result set.

**Comment by Arukiap** [comment]
Thank you for the feedback @kneth!

**Comment by cristianoccazinsp** [comment]
Sorry for bringing this fossil up.

Is this still true as of 2021? Does calling `.length` on a query object return the actual length without fetching everything into memory and in a nicely and efficient way (similar to an SQL count query), or does it have to still go through all objects?

**Comment by tgoyne** [comment]
`.filtered("...").length` is the equivalent of a SQL count query, and has been since before the first public release of the JS SDK. It does not fetch everything into memory.

**Comment by cristianoccazinsp** [comment]
Our app stores old data for recovery purposes, and I'm wondering how big can a count query before it starts to be come slow.

Do you know any other implementation details about this? How many are "too many" objects before a count query starts to be be slow. Our filtering is indexed.

**Comment by tgoyne** [comment]
Getting the count of a query which is covered by an index (which is currently only an equality query on a single property) is approximately constant time (the index lookup is not actually constant time, but the overhead of things like parsing the query string will dominate it). Getting the count of any other query involves a table scan that takes time linearly proportional to the number of objects. Realm's low-level storage is designed specifically to make this sort of operation fast, but whether it's fast enough or how many object it takes for it to become too slow is going to depend on the very specific details of what you're doing and what your time budget is.
