### ISSUE TITLE
[2.3.x] API Docs issues for partial sync

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1700]
- The typings for `SubscriptionNotificationCallback` claim it's a function that is passed a number as argument: https://github.com/realm/realm-js/blob/2.3.x/lib/index.d.ts#L402 but in runtime, I get the subscription object.

- The docs in collection.js imply that the result of calling `.subscribe()` is a results object, whereas it's a `Subscription`, meaning that the `addListener` callback signature in the example is likely wrong: https://github.com/realm/realm-js/blob/2.3.x/docs/collection.js#L143

- The docs in sync.js claim that the `Subscription.addListener` callback is `function(state)`: https://github.com/realm/realm-js/blob/2.3.x/docs/sync.js#L503

- The docs in sync.js claim that the `Subscription.removeListener` callback is `function(collection, changes)` when it should be `function(subscription, changes)`: https://github.com/realm/realm-js/blob/2.3.x/docs/sync.js#L522

**Comment by kneth** [comment]
Done by #1707
