### ISSUE TITLE
use realm from js and from native side

### ISSUE THREAD

**Issue by sneerin** [realm/realm-js#1701]
can you suggest how can we use realm from both native and react side, I want to write to db in ios code, and read it from the react native.

**Comment by sneerin** [comment]
It would be great to have such universal storage, is it possible?

**Comment by kneth** [comment]
Mix native and react in the same app or separate apps?

**Comment by sneerin** [comment]
same application, the idea that I have native logic, and I have js logic, it would be great to save results in one DB, and use it without modules etc..

**Comment by kneth** [comment]
In that case, it is important that you ensure that Realm Cocoa and Realm JavaScript agree on the same version of Realm Core. You might wish to take a look at #1440.

**Comment by bmunkholm** [comment]
Closing as duplicate to the issue Kneth referred to.
