### ISSUE TITLE
Realm reporting wrong certificate information

### ISSUE THREAD

**Issue by tunatoksoz** [realm/realm-js#1702]
## Goals
openssl s_client -showcerts -connect <redacted>:443 </dev/null
depth=0 /O=Acme Co/CN=Kubernetes Ingress Controller Fake Certificate

openssl s_client -showcerts -servername <redacted> -connect <redacted>:443 </dev/null
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

  const realm = await Realm.open({
    sync: {
      user: user,
      url: REALM_HOST + '/~/db',
      error: console.log,
      validate_ssl: true,
      open_ssl_verify_callback: function(info) {
        console.log(info);
        return true;
      }
    }, ...
  }

info.pemCertificate points to the certificate in the first one (in my case, its' fake kubernete certificate).

## Expected Results

info.pemCertificate points to Let's Encrypt certs.

## Actual Results
It points to fake kubernetes certificate.

**Comment by kneth** [comment]
@morten-krogh Do you have a clue?

**Comment by morten-krogh** [comment]
I will look into it soon after finishing something else.

**Comment by morten-krogh** [comment]
I tested a connection to a server with a lets encrypt certificate.
The open_ssl_verify_callback function behaved as expected for me.

There are two certificates. They are reported in two consecutive calls to open_ssl_verify_callback with info.depth = 1 and info.depth = 0.

The depth 1 certificate is
 Subject: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

The depth 0 certificate is the server's own signed by the depth = 1 certificate.

Is this not what you get? @tunatoksoz 
Do you get two calls of the callback function?
You must return true. If you return false, there will be no more calls.

**Comment by kneth** [comment]
@tunatoksoz I am closing the issue. If the comment above doesn't help you, you are welcome to reopen it.
