### ISSUE TITLE
Expose BindingContext::schema_did_change callback

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1703]
It would be useful for the GraphQL service to invalidate its schema cache automatically. @tgoyne [mentioned](https://github.com/realm/realm-graphql-service/issues/37#issuecomment-371855117) OS exposes `BindingContext::schema_did_change` which, if surfaced via the js SDK would be exactly what we need.

Considering there's a way to manually invalidate the schema cache, I wouldn't consider this a super high priority, but would be nice to have, especially if it's not too time consuming to do.

**Comment by kneth** [comment]
@nirinchev Isn't this a duplicate of #1825?

**Comment by nirinchev** [comment]
It is, must have forgotten it existed when I filed #1825.
