### ISSUE TITLE
Realm-JS with Electron on Debian 9

### ISSUE THREAD

**Issue by MaxGierlachowski** [realm/realm-js#1710]
## Goals

Run realm js with electron on a Debian-linux machine
I know that realm js dose not officially support electron but I was curious if anybody already had this issue. 

## Expected Results

Build realm js against electron with electron-rebuild -f -w realm, launch it with electron .

## Actual Results

Error when executing electron .

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/cloxee/data/node_modules/realm/compiled/electron-v2.0_linux_x64/realm.node: undefined symbol: _ZN5realm18SharedGroupOptions11sys_tmp_dirB5cxx11E
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cloxee/data/node_modules/realm/lib/index.js:102:28)
    at Object.<anonymous> (/home/cloxee/data/node_modules/realm/lib/index.js:133:3)`

## Steps to Reproduce

Install Debian 9
Install latest realm js, electron and electron-rebuild version via npm
Run electron-rebuild -f -w realm
Launch App with electron .

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.0
- Node: 8.10.0
- Client OS & Version: Debian 9
- Electron: 2.0.0-beta.3

**Comment by kneth** [comment]
True that we don't support Electron yet. From the error, it looks like Realm Core hasn't been linked correctly with the rest. The order of libraries is important (in particular for gcc) so you might have to have a look in the linking phase.

**Comment by dubstylee** [comment]
I have definitely had some issues as well running Realm with Electron (on Windows), but after many hours of trial and error and struggling to keep my sanity, I finally got it to build with the 2.2.x branch. I have not been able to successfully compile any 2.3.x versions of Realm for use with Electron yet, but 2.2.x is good enough for my use case.

Perhaps I will try to spin up a VM and see if I can get it to compile in a Linux environment. That error is different than the issues I was having. Most of my problems were related to the Microsoft build tools, and OpenSSL.

**Comment by immanoj16** [comment]
Hey @MaxGierlachowski Did you solve this?

**Comment by kneth** [comment]
As mentioned earlier, we do not support Electron. [Realm Studio](https://github.com/realm/realm-studio) is an Electron app, and you are welcome to see how we are using Realm JS and Electron together.
