### ISSUE TITLE
Unable to open a realm at path default.realm on Android

### ISSUE THREAD

**Issue by MrHubble** [realm/realm-js#1714]
I am using Realm with React Native. Previously my Android build process kept getting stuck on 93%. The [fix](https://github.com/facebook/react-native/issues/10078#issuecomment-304084625) was `rm -r default.realm* && rm -r realm-*`, after which my build would complete successfully.
 
However, now the first time I go to use my app it will crash with errors similar to `unable to open a realm at path default.realm`, `not a realm`. After reloading, the app works fine and will no longer throw an error. So to replicate the bug I need to constantly delete the app from my Android device.

I can not replicate this bug when stepping through the code, it only occurs if I disable remote debugging.

## This I have tried:
- Opening the realm asynchronously rather than synchronously
- Manually specifying the path (ie `Realm.open({ path: 'myRealm.realm'`
- Closing the realm
- Unlinking and removing Realm from the project and then adding it back again

## Version of Realm and Tooling

- Realm JS SDK Version: 2.3.0
- Node or React Native: 0.48.4
- Client OS & Version: Mac OSX 10.13.3
- Which debugger for React Native: Chrome

**Comment by MrHubble** [comment]
I was able to re-add all of the realm files I deleted (`rm -r default.realm* && rm -r realm-*`) however the problem still exists. 

Often the app will just crash and reload and will not throw an error though sometimes it does when running a release version. After assembling a release and running on my Android device I was able to get this error:

![error](https://user-images.githubusercontent.com/2251631/37502825-25b33b1e-2929-11e8-97d6-7e788bc82d34.png)

**Comment by MrHubble** [comment]
### Further debugging

[This issue](https://github.com/realm/realm-java/issues/4176#issuecomment-288125117) suggests encryption _may_ be the culprit, so I thought removing the encryption option might change something:

![image](https://user-images.githubusercontent.com/16198924/37693353-36e6c0fc-2d13-11e8-8dd7-58c735440263.png)

Unfortunately not, now I am receiving a schema version difference. I thought 'somehow' the DB on the device was actually 31 and not the defined 47 so I changed the schema version to 31 to verify:

![image](https://user-images.githubusercontent.com/16198924/37693389-7ea7f21c-2d13-11e8-8987-89714af40ddc.png)

Okay... So somehow the schema version is correct? I assumed that removing the schema version and encryption option should be okay as I was planning to uninstall the application and reinstall to test the scenario, recreating the DB and not requiring migrations or a schema version at all: 

![image](https://user-images.githubusercontent.com/16198924/37693441-cb093832-2d13-11e8-843a-574263a3f455.png)

Only to reveal a new raised issue that must be library unrelated (I can't find its reference). 

Using android studio and a created emulator, I pulled the realm file once the application was started and running before the issue occurs, and have found nothing unusual with the file. The DB opens up using realm studio with the encryption turned off, and everything looks as though it has been successfully stored.

**Comment by kneth** [comment]
@MrHubble I can't give you a definite answer. The old bug, you are referring to was related to a race-condition when multiple threads were writing and reading an encrypted Realm. Since it has been fixed, I don't think what you see is related.

The last screen shot seems to be unrelated to Realm.

**Comment by bmunkholm** [comment]
Outdated. Feel free to reopen in case this is still relevant.
