### ISSUE TITLE
Subscription is not defined

### ISSUE THREAD

**Issue by artutra** [realm/realm-js#1716]
When running the debugger on a React Native application, it throws a "Subscription is not defined" error.
It occurs right at the `import Realm from 'realm'` line.

### Expected results
Run the react native debugger on a react native application with realm 
### Actual results
Got an error right after set debbuger on
![image](https://user-images.githubusercontent.com/15269475/37471160-df1f553e-2847-11e8-9809-d9dceb4b3dc8.png)

### Steps to reproduce
Create a react native application on android, import realm and activate the debbuger on Chrome

### Versions
Realm: 2.3.0
ReactNative: 0.52.2

I believe that this file is missing a `import Subscription from './subscription';`
https://github.com/realm/realm-js/blob/10480c1afe73b49dc0d6f2a2876f1bccf6d1b588/lib/browser/index.js#L150

**Comment by trungtin** [comment]
Why is this closed? Please re-release a fix, it happens on 2.3.1 too

**Comment by artutra** [comment]
Sorry, I did not explain that this is duplicated #1711

**Comment by artutra** [comment]
Downgrading from realm@2.3.0 to realm@2.2.15 solves this problem for me.

**Comment by rmn528** [comment]
I already downgraded to the version 2.2.15 and the same error persists

**Comment by LingboTang** [comment]
It still happens with 2.3.3
