### ISSUE TITLE
Cannot redefine property: logout

### ISSUE THREAD

**Issue by waltermvp** [realm/realm-js#1727]
## Goals

Run Realm

## Expected Results

App loads

## Actual Results

I get "Cannot redefine property: logout" red screen error

## Steps to Reproduce

First comment out subscription line as stated in https://github.com/realm/realm-js/issues/1711 . Import realm from anywhere and run app

## Code Sample

`import Realm from "realm";`

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
    "realm": "^2.2.18",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
- Client OS & Version: 
 Any

- Which debugger for React Native:
standard

**Comment by tomsjansons** [comment]
i'm facing the same issue, any news?

**Comment by macceth** [comment]
The code above by @tomsjansons worked for me, please consider to add it to the project module.

**Comment by sbayd** [comment]
+1, We are unable to debug our react-native application because of this bug using the latest(2.3.5) version. 
Remote debugging working fine on version 2.2.20

**Comment by kneth** [comment]
The API (and implementation) has changed a lot in v10.0.0. I am closing the issue.
