### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by iFreedive** [realm/realm-js#1733]
Hi I have the following set to listen for modifications on an Acknowledgement object

`						
realm.objects('Acknowledgement').addListener((acknowledgements, changes) => 
{											
        changes.modifications.forEach((index) => 
        {
	        ChangeEvent.acknowledgementModification(acknowledgements[index]);
        });					
});`

This Acknowledgement  object has a User object associated to it
Now the User object has a PermissionGroup object associated to it.
The PermissionGroup object has a list of Permission objects against.

If I modify a permission group by adding or deleting a permission it fires off the modification event.
Is this by design or a potential bug?

Is it designed that if you add a listener to an object and modifications to associated objects on that 
object fire the listener?

Thanks

Gary

**Comment by kneth** [comment]
It is by design as we see it as the result set is changed. That also include all objects which can reached by the result set.
