### ISSUE TITLE
cannot open debug mode of RN while using realm

### ISSUE THREAD

**Issue by brithbutter** [realm/realm-js#1739]
## Goals

start android app with debug mode to fix errors

## Expected Results

app start normally and see logs in Browser

## Actual Results

app comes up with exception and start failed
![358162813760770292](https://user-images.githubusercontent.com/16324673/38186850-9c8591fe-3687-11e8-918f-309dab737062.png)

## Steps to Reproduce

`npm start`
`react-native run android`
app start as  we expected to 
shake the device to open debug mode
The exception page come out
## Code Sample

`let Realm = require('realm');`
this is the line of the code exception pointing to

## Version of Realm and Tooling

- Realm JS SDK Version: 2.3.3
- Node or React Native: 54
- Client OS & Version: Ubuntu 16.04
- Which debugger for React Native: ? Chrome

**Comment by kneth** [comment]
@brithbutter Do you only experience this on Android?

**Comment by brithbutter** [comment]
@kneth Since I haven't try to develop a ios app yet, yes

**Comment by kneth** [comment]
@brithbutter No worries, I was trying to reduce the space where to look :smile:

**Comment by alax** [comment]
This is also an issue on iOS.

**Comment by Louies89** [comment]
@kneth  
I got the error also.... hope below screenshot will help you to fix the issue as it is pointing to the **rpc.js** file of realm....

![whatsapp image 2018-04-10 at 12 05 58 pm](https://user-images.githubusercontent.com/30086899/38539982-f08d93c4-3cb7-11e8-93eb-31cdd959f4bb.jpeg)

**Comment by kneth** [comment]
I believe we have a little bug, and it is being fixed in #1744.

**Comment by wangghon** [comment]
if the devices can not reached each other even in a same network, the issue still exist on 2.4.0.
I am wondering if we can disable the debug mode of realm when we debug the react native app.

**Comment by wangghon** [comment]
@kneth  yes, devices means phone + computer.  phone can not connect computer even they are in the same wifi.

**Comment by kneth** [comment]
@wangghon Have you tried to debug using a USB cable?

**Comment by wangghon** [comment]
yes, tried to debug react native app on android device  which was connected to a iMac

**Comment by dreamHeroK** [comment]
when i use  "realm": "^2.4.0",i have the same problem. android can't demote js.

**Comment by kneth** [comment]
@brithbutter @dreamHeroK @wangghon @Louies89 If you upgrade to latest Realm JS (2.8.2), do you still experience problem when debugging on Android?

**Comment by Louies89** [comment]
@kneth Yes, getting the error in 2.2.8.
Not tried with Realm JS (2.8.2). I am scared to upgrade version, if some problem will occur, I have to spend some time on it. As I have a lot of other work is pending.

Please let us know what improvements are there, if it will enhance our application, we will definitely give a try. 

Thank you :+1:  :)

**Comment by kneth** [comment]
Maybe #1779 is not relevant for you. Otherwise we have fixed bugs and added many features since v2.2.8.

**Comment by Louies89** [comment]
@kneth Can you please share the link, where we can find the added features and enhancements in new versions ?

**Comment by kneth** [comment]
@Louies89 See https://github.com/realm/realm-js/blob/master/CHANGELOG.md

**Comment by Louies89** [comment]
Thank you for the link :+1:

**Comment by Louies89** [comment]
@kneth Yes sure...

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
