### ISSUE TITLE
Sorting in request's order

### ISSUE THREAD

**Issue by PeteOyable** [realm/realm-js#1741]
## Goals

I have a filtered request with several conditions in it, I want the results to be filter in the same order.
Let say, I do this request : 
```javascript
const query = [4, 2, 3, 1].map(id => `id = ${id}`).join(' OR ');
const users = await realm.objects('Contact').filtered(query);
return users;
```
## Expected Results

I want the results to be ordered in that particular order => **Contact with id 4, Contact with id 2, Contact with id 3, Contact with id 1**.

## Actual Results

The results are filtered by id => **Contact with id 1, Contact with id 2, Contact with id 3, Contact with id 4**.

## Steps to Reproduce

Simply execute the request above, the schema is below.

### Schema : 
```javascript
const Contact = {
  name: 'Contact',
  primaryKey: 'id',
  properties: {
    id: 'int',
    lastname: 'string',
    firstname: 'string',
    address: 'string',
    phones: 'string',
    email: 'string',
    picture: 'string?',
    birthday: 'date?',
    birthplace: 'string?',
  }
};
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.7
- Node or React Native: React Native 0.53.0
- Client OS & Version: iOS and Android
- Which debugger for React Native: None

**Comment by kneth** [comment]
A `Realm` is unordered. You can sort a `Realm.Results` using [`sorted`](https://realm.io/docs/javascript/latest/#sorting) or use `SORT` as part of your query (see last item in https://realm.io/docs/javascript/latest/#filtering). The order will likely depend on the order to added the objects (no guarantee) and **not** the order in your query.

**Comment by PeteOyable** [comment]
I understand, si there's no way for me to get the results sorted as I want. I need to add some custom sorting in order to get my results ordered as I want.

Thank you @kneth for taking time to answer me.

**Comment by kneth** [comment]
True, we don't provide support for a custom comparison function as an argument to `Realm.Results.sorted()`. I think the performance penalty will be huge (the query engine will have to call a JS function for every comparison). 

If you use a list (a property of type `Contact[]`) in another class:

```
const ContactWrapper = {
  name: 'ContactWrapper',
  properties: {
    contacts: 'Contact[]'
  }
}
```

The list will be ordered. Then it is a matter of appending the objects in the right order :smile:.

**Comment by PeteOyable** [comment]
Ok, I've been able to have the result I want with a filter function :)
I think we can close this issue.

Thank you all.

**Comment by chelovekdrakon** [comment]
> A `Realm` is unordered. You can sort a `Realm.Results` using [`sorted`](https://realm.io/docs/javascript/latest/#sorting) or use `SORT` as part of your query (see last item in https://realm.io/docs/javascript/latest/#filtering). The order will likely depend on the order you added the objects (no guarantee) and **not** the order in your query.

Maybe it is out of the issue, but... :)
Am I able to sort "on one property or another"?
kind of sort("lastTimestamp || createdAt")
sort over "lastTimestamp", but if it is falsy --> use "createdAt"

**Comment by chelovekdrakon** [comment]
Also, @kneth, maybe you have "community chat" for such questions?)

**Comment by kneth** [comment]
@chelovekdrakon Sorry for the late reply. https://forums.realm.io/ is a good place.

**Comment by chelovekdrakon** [comment]
> @chelovekdrakon Sorry for the late reply. https://forums.realm.io/ is a good place.
Thank you :)

And how about `.sort(one || another)` syntax? is it possible?
How to achieve it?

**Comment by kneth** [comment]
I am not sure what you mean by "Am I able to sort "on one property or another". 

You can specify multiple properties. If you do `.sorted(['lastTimestamp', 'createdAt'])` you result set will be sorted by `lastTimestamp` and for objects with the same value for `lastTimestamp`, they will be sorted by `createdAt`. For example `[{lastTimestamp: 1, createdAt: 7}, {lastTimestamp: 2, createdAt: 1}, {lastTimestamp: 1, createdAt: 6}]` will be sorted as `[{lastTimestamp: 1, createdAt: 6}, {lastTimestamp: 1, createdAt: 7}, {lastTimestamp: 2, createdAt: 1}]`.

**Comment by chelovekdrakon** [comment]
@kneth yep, sorry for being unclear :) I will try to describe it better ;)
Here is my case: 
I have a `Channel` with last message (object) and date of creation (int).
Last message is nullable. Because some channels may not have any messages yet
So, I want to sort over `lastMessage.timestamp` or `createdTimestamp` when last message is null or undefined :) 
kind a `Result.sorted('lastMessage.timestamp || createdTimestamp');`

**Comment by kneth** [comment]
Sorry for the late reply.

I like the idea and the API you suggest but I am afraid it is not possible.  The only solution I can think of is to create a property (maybe `timestampToSort`) and manually update it. Initially it has the value `createdTimestamp` but once to add a message, you need to update the property.

**Comment by chelovekdrakon** [comment]
@kneth thank you :) 
This is exactly how I did it for now :) 
Works good 👍
