### ISSUE TITLE
Incompatibility with recent Gradle verisons

### ISSUE THREAD

**Issue by alexsmartens** [realm/realm-js#1742]
## Goals

To compile a project with updated SDK and Gradle versions 

## Expected Results

The project is compiled

## Actual Results

Build error
```
> Configure project :realm
Configuration 'compile' in project ':realm' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

## Steps to Reproduce

1) Update Android SDK versions
2) Update gradle versions

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.7 (2.3.3)
- Node or React Native: RN 0.52.0 (0.55.0)
- Client OS & Version: Android 27
- Which debugger for React Native: Chrome

**-- Additional version info:**

- compileSdkVersion 27
- buildToolsVersion "27.0.3"
- com.android.support:appcompat-v7:27.1.0

- gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

**Comment by kneth** [comment]
Thanks for reporting. It sounds trivial to fix ("All programmers are optimists", Frederick P. Brooks, jr.)

**Comment by saschak42** [comment]
When will this get fixed?

**Comment by cmelchior** [comment]
@alexsmartens @saschak42 You don't specify which version of Android Studio and Android Build tools you are using, but I suspect that you just need to update `build.gradle` with:

```
dependencies {
    implementation project(':realm')
}
```

instead of 
```
dependencies {
    compile project(':realm')
}
```
This was a change in Android, but our documentation does not describe this. I'll update the docs.

**Comment by kneth** [comment]
The issue has been closed since the documentation has been updated.

**Comment by saschak42** [comment]
We've tried Android Studio 3.1.4 and 3.2 Beta 5. With the Android Gradle plugin 3.0.0 and higher you don't need to specify a buildToolsVerson (see https://developer.android.com/studio/releases/build-tools). We also use implementation/api for a while. 

The problem is that the Realm build.gradle file uses compile instead of implementation: https://github.com/realm/realm-js/blob/master/react-native/android/build.gradle
