### ISSUE TITLE
[Bugs] [react-native] [android] Sync config error callback spam call with code 336134278

### ISSUE THREAD

**Issue by Winglonelion** [realm/realm-js#1743]
## Bugs: Sync config error callback spam call with code 336134278

**realm 2.2.15
react-native: 0.51.0
react-object-server: 2**

similar any sync config of realm js. We build a config object and pass it to constructor of Realm when our users login. 

```
function realmErrorHandle(obj, options) {
  console.log('=======> REALM ERR!', options);
}

  const syncConfig = {
      sync: {
        user,
        url: realmUrl(),
        error: realmErrorHandle,
      },
      path: dbLocation(userID),
      ...currentSchema,
    }

realmDB = new Realm(syncConfig)
```
**note: all parameter being ensure correct and work well on Ios version**

## Expected Results
  realmErrorHandle never being called and everything work expected.

## Actual Results
Realm still working but realmErrorHandle be call very spamly (maybe one times per second) and does not seem to will stop.

and describe following Error: 
```
{   
  name: 'Error',
  message: 'Unknown OpenSSL error: 336134278',
  isFatal: false,
  category: 'openssl',
  code: 336134278,
  userInfo: {} 
}
```
**the code of error 336134278 can not be find in any Realm documents or OpenSSL documents.**  

We use SSL for realm object server but realm-js client worked expected without any SSL config on Ios. But unlucky, we met this error on Android.

The lastest version which dont have this error is 2.0.13

## Steps to Reproduce
~~Happen when we register new realm user with ```Realm.Sync.User.registerWithProvider```. 
When use available user realmErrorHandle hasn't be call.~~

Update: This happen when first time launch application. In debug mode, If reload by double tap R, no log more!

  

## Update:
**We just upgrade realm js version to 2.2.15 but can not resolve this problem**

## Version of Realm and Tooling

- Realm JS SDK Version: **2.2.15**
- Node or React Native: **React Native 0.51.0**
- Client OS & Version: **Mac OS 10.12.6**
- Which debugger for React Native:  **None**

**Comment by kneth** [comment]
I think it is related to if the root certificate is found but we have to investigate a bit closer.

You can try to set `validate_ssl` in the configuration to false.

**Comment by Winglonelion** [comment]
@kneth Thank you for the quick support. I will try to make it more clean too

**Comment by kneth** [comment]
@Winglonelion Just curious, did you find the solution?

**Comment by Winglonelion** [comment]
@kneth, Sorry for my late.

But we don't hav many time to digging in Native code. 

Our trick is always return true for validateCallback. The log is stopped.

However, i still think it is  aBug and need to fix.

**Comment by Winglonelion** [comment]
It just a small issues. the true pain is on Android, with above config. Realm.open() never resolve promise. 

It is a reported problem but maybe not resolved in realmjs repo. Sorry, but i can't find it back. 

Frankly, the reason for we use ```new Realm()``` on Android because  ```Realm.open()```  promise can not be resolved.

**Comment by kneth** [comment]
@Winglonelion Once https://github.com/realm/realm-js/pull/1761 is merged and released, I think you can start using HTTPS again.

**Comment by Winglonelion** [comment]
Thanks team. We will try it now!
