### ISSUE TITLE
Cannot find entry file realm.js in any of the roots: ["My-project-path"]

### ISSUE THREAD

**Issue by vdthieu** [realm/realm-js#1750]
This happen when I build Release in Android
I 've tried to create an empty realm.js file as reqquired, the build successed but the app crashed right after it launch

![](https://i.imgur.com/zlrz8KO.png)

- Realm JS SDK Version: 2.2.15
- Node or React Native: 16.2.0
- Client OS & Version: Mac OS 10.12.6
- Which debugger for React Native: WebStorm

**Comment by kneth** [comment]
We haven't tested Realm JS much with WebStorm, and I think that asking at Stackoverflow is a better option. Said that, can you provide steps to reproduce the behaviour?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
