### ISSUE TITLE
Using Realm with external storage

### ISSUE THREAD

**Issue by ianzitow** [realm/realm-js#1760]
## Goals

I want to use sdcard on Android to save and load Realm data. 

## Expected Results

The file can be created and loaded without problems using app's folder on external storage.

## Actual Results

Unfortunately, when running Realm.open, it throws an exception of "Read-only file system", even after giving runtime permission to read and write external storage. I can see the file was created at the specified path. 

![screenshot_1524455457](https://user-images.githubusercontent.com/2258901/39106498-8833f4c8-4692-11e8-8fe0-4c94f8b3ae23.png)

## Steps to Reproduce

I used React Native Filesystem to determine the external storage path. Then, tried to open a Realm file, after explicitly given storage permission from React Native Permissions. 

## Code Sample

```let realmPath = RNFS.ExternalStorageDirectoryPath + '/Android/data/<BUNDLE_ID>/files/default.realm';
RNFS.exists(realmPath).then((result) => {
if (result) {
          console.warn('FOUND A FILE');
          Realm.open({path: realmPath, schema: [CarSchema, PersonSchema]})
                  .then(realm => {
                    console.warn('opened')
                  })
                  .catch(error => {
                    console.error(error);
                  });
        } else {
          setTimeout(() => {
            Permissions.request('storage').then(response => {
              if (response === 'authorized') {
                  Realm.open({path: realmPath, schema: [CarSchema, PersonSchema]})
                  .then(realm => {
                    console.warn('opened')
                  })
                  .catch(error => {
                    console.error(error);
                  });
              }
            }).catch(error => {
              console.error(error);
            })
          }, 0)
        }
      }).catch((error) => {
        // File does not exist
        // Define your models and their properties 
      });
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.13
- Node or React Native: 0.50.3
- Client OS & Version: Android API 25
- Which debugger for React Native: None

**Comment by kneth** [comment]
Maybe you can check if the directory is writable using [`stat`](https://github.com/itinance/react-native-fs#statfilepath-string-promisestatresult).

**Comment by ianzitow** [comment]
Using stat returns undefined for mode.

**Comment by kneth** [comment]
Please check if the SD card is mounted read-only (`mount` is your friend).

See also https://stackoverflow.com/questions/17858975/read-only-file-system?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by ianzitow** [comment]
The following code works pretty well in Android with Java:

```RealmConfiguration config = new RealmConfiguration.Builder().name("default.realm").directory(getExternalFilesDirs(null)[1]).build();
Realm.setDefaultConfiguration(config);```

However, the following triggers the "Read-only file system" error:

```RNFS.getAllExternalFilesDirs().then((dirs) => {
      console.warn(dirs);
      Realm.open({
        path: dirs[1] + '/' + 'default.realm',
      })
      .then((realm) => {
        console.warn('opened realm at: ' + realm.path);
      })
      .catch((err) => {
        console.error(err);
      })
    }).catch((error) => {
      console.error(error);
    })```

**Comment by kneth** [comment]
And you are certain that it is the second external directory to use (`dirs[1]`)? What does `console.warn(dirs)` print?

**Comment by ianzitow** [comment]
Absolutely, it shows two paths. The first one refers to actually a location in internal storage and the second is the location at sdcard.

**Comment by kneth** [comment]
@ianzitow Which Android device, do you use?

The first answer in https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android goes through many scenarios which can go wrong.

**Comment by ianzitow** [comment]
@kneth I've been using Moto G3 and a Samsung Galaxy. I ended up creating a bridge with Realm Java to solve this issue.

**Comment by mnlbox** [comment]
guys are you any idea about this?
I want to create my database on internal storage (somewhere rather than `/data/data/<package-name>/files`) because I want to have permission to copy my db to PC and open it with Realm Studio.
Are you any idea?

**/CC:** @ianzitow @kneth

**Comment by mnlbox** [comment]
@kneth thanks, Can you provide some example of how we can set path to SD card?
I think it's a little tricky.

**Comment by bmunkholm** [comment]
@mnlbox We try to use github only for bugs or feature requests. So please ask generic non realm questions on StackOverflow which also helps others to find the answers better later. Thanks!

**Comment by mnlbox** [comment]
@bmunkholm OK nut I think we need some example or docs about an important configuration like this. :thinking:

**Comment by mnlbox** [comment]
Some other information about app environment:

I open my database like this in react-native:
```
    componentWillMount() {
        Realm.open({
            schema: [ Constant.BookSchema ],
            path: '/storage/sdcard0/BookDB/db.realm'
        }).then(realm => {
            // some code here
        });
    }
```
I also add this two line to my `AndroidManifest.xml`:
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

It's create below files in this location `/storage/sdcard0/BookDB`:
```
db.realm.managment
    access_control.control.mx
    access_control.write.mx
db.realm
db.realm.lock
```
But It's return red error page with `Read-only file system` error. (something like first post in current issue)
My device just have internal storage with `/storage/sdcard0` location and it's not have any external SD card.

**Comment by mnlbox** [comment]
@bmunkholm please re-open this issue still fix completely.
Thanks :wink:

**Comment by bmunkholm** [comment]
@mnlbox Unless your issue is exactly the same as the original, it's always better to create a new separate issue and refer to this as related. Doing that together with a good repro case (ideally a complete test-case or full app that we can run) makes it much easier (and faster) to help. 🙏

**Comment by mnlbox** [comment]
@bmunkholm OK man I create new issue here: #2062

**Comment by ronastlelobo** [comment]
I am also facing the same issue. May i know if there is any valid fix?

**Comment by nirinchev** [comment]
If you're facing the same issue, then review the pointers given by @kneth - notably, specify the `path` option in the config to a valid directory where your app has write permissions. If that doesn't work, please open a new issue that describes what you're doing and what errors you're getting. Saying you have the same problem on a closed issue does not offer us much to go off of in order to help you.
