### ISSUE TITLE
Unable to access Realm on App Groups - iOS, react native 

### ISSUE THREAD

**Issue by vsridharan6** [realm/realm-js#1762]
## Goals

I am trying to use Realm on my iOS project, and React Native project. The realm is stored in our App Groups. When we try to access the Realm from the javascript side, we are not able to access the shared group. 

## Expected Results

// we get the realm db path from the native modules.
this.REALM_DB_PATH = NativeModules.RealmHelperModule.realmDBPath;

 const config = {schema: [SomeSchema], path: this.REALM_DB_PATH};
 const realm = new Realm(config);
 console.log(realm.path);

Expected result:

file:///Users/kira/Library/Developer/CoreSimulator/Devices/98C4E7E8-9E45-4A17-824C-3D80D9207A43/data/Containers/Shared/AppGroup/37915G54-BA5B-4E08-AE7E-DCE7668B5711/RealmDB.realm

## Actual Results

file:///Users/kira/Library/Developer/CoreSimulator/Devices/98C4E7E8-9E45-4A17-824C-3D80D9207A43/data/Containers/Data/Application/47896D45-4EC9-44EA-8069-442276621B35/Documents/file:///Users/kira/Library/Developer/CoreSimulator/Devices/98C4E7E8-9E45-4A17-824C-3D80D9207A43/data/Containers/Shared/AppGroup/37915G54-BA5B-4E08-AE7E-DCE7668B5711/RealmDB.realm

## Steps to Reproduce

1. Save Realm on App Groups on Native.
2. Access Realm on React Native. Get the path from a native module. 

## Version of Realm and Tooling

NodeJS-realm                        = 2.2.x;
NodeJS-react-native                 = 0.50.x;

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by kneth** [comment]
Realm is using memory-mapping (`mmap`) to access data on the storage device, and using I believe App Groups will not work nicely together with `mmap`. If you need to have the same Realm in multiple applications, I suggest that you take a look at [Realm Platform](https://realm.io/products/realm-platform).
