### ISSUE TITLE
Docs: how to build cross-platform npm package locally?

### ISSUE THREAD

**Issue by febeling** [realm/realm-js#1763]
## Goals

I need to build the npm package locally, so that I can run it on iOS and Android.

## Expected Results

Reading the README and perform the task.

## Actual Results

The docs say how to build for each platform, Android and iOS respectively. But they don't explain how to build one single package, which is valid for both platforms. 

## Steps to Reproduce

n/a

## Code Sample

n/a

## Version of Realm and Tooling

- Realm JS SDK Version: master
- Node or React Native: RN
- Client OS & Version: 0.55.3
- Which debugger for React Native: n/a

**Comment by febeling** [comment]
@kneth I'm not concerned with using a released package, but rather using a branch or fork intermittently. I tried just referencing a github reference to master in package.json, but the build fails, i.e. `react-native run-ios` etc. doesn't finish successfully. 

The docs about building mention initing sub-modules and such, so I assume there must be some build task somewhere that is performed before artifacts get uploaded to the public npm repository, which isn't readily present in the git repo normally.

**Comment by kneth** [comment]
You could try to create a local package using `npm pack` and `npm install` it in your app.

**Comment by febeling** [comment]
I've seen in the examples that just the path is specified. That probably also needs the a realm-js repo with submodules init'd. I'll confirm this an update here as soon as I get around doing it.

**Comment by kneth** [comment]
Yeah, we use Git submodules to pull in our binding abstraction layer (aka Realm Object Store).
