### ISSUE TITLE
Issue deleting a slice of data from the realm database.

### ISSUE THREAD

**Issue by jgreen01su** [realm/realm-js#1769]
Question: Is there a way to `delete` a `slice` from my realm database?

I just upgraded from 1.13.0 to 2.4.0.

Documentation for `slice` in both versions:
[2.3.0 Documentation for `slice`](https://realm.io/docs/javascript/2.3.0/api/Realm.Results.html#slice)
[1.12.0 Documentation for `slice`](https://realm.io/docs/javascript/1.12.0/api/Realm.Results.html#slice)

## Goals

I need a way to limit the amount of data I send in my _POST_ request, and to then remove the data I've sent.

## Expected Results

In 1.13.0, I would query my database, then `slice` a large chunk and send it to my remote server, once I get a valid response from the server I delete the chunk.

## Actual Results

In 2.4.0, when I try to delete the chunk I `slice`d from `Realm.Results` my application suddenly crashes without an error message.

It seems that in 2.4.0, `slice` doesn't return a `Realm.Object`, `[Realm.Object, ...]`, `Realm.Results` or `Realm.List` object required by `delete`, while in 1.13.0 it was. Or maybe there's a bug??

## Steps to Reproduce

Use `.slice` method on a `Realm.Results` object then use `realm.delete` on the result.

## Code Sample

Here's an example of how the code works.
```
Realm
  .then(realm => {
    const logs = realm.objects('log').filtered('id > 10').slice(0, 1000);  // get first 1000 logs

    const logsBody = JSON.stringify(logs.map(x => x));

    return fetch('${API_URL}/logs), {
      method: 'POST',
      body: logsBody,
    })
    .then(res => {
      if (!isValidResponse) { return; }
      return res.json();
    })
    .then(json => {
      if (!isJsonValid(json)) { return; }
      realm.write(() => realm.delete(logs)); // *CRASHES HERE* deletes first 1000 logs
    });
  });
```

In 1.13.0, the above example worked perfectly, but in 2.4.0 it crashes the application when I try to delete the logs.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- React Native: 0.55.3
- Client OS & Version: Android 7.0
- Which debugger for React Native: None

Is there another way I can do this in realm? Is this a bug with version 2.4.0? And would it be safer to switch to version 2.3.0??

Any help will be greatly appreciated!

**Comment by jgreen01** [comment]
While experimenting with different workarounds, I came across an interesting error that may shed light on what's happening.

I changed the delete code to this:
```
logs.forEach(
  log => {
    if (log.isValid()) {
      realm.delete(log);
    }
  }
);
```

![screenshot_20180427-173424](https://user-images.githubusercontent.com/25392304/39389856-9bab45ee-4a41-11e8-8700-4cb1fa0a400f.png)
