### ISSUE TITLE
Improve error reporting when giving wrong protocol type in URL

### ISSUE THREAD

**Issue by astigsen** [realm/realm-js#1770]
realm-js: v2.4.0

When connecting to Realm Cloud, it is easy to accidentally mix up `http://`/`https://` and `realm://`/`realms://`. Look at this small example:

```js
const Realm = require('realm'); 

const SERVER_URL = 'myinstance.cloud.realm.io';

async function main() {
    let user = await Realm.Sync.User.login(`https://${SERVER_URL}`, 'test', 'test')
    console.log("user logged in");

    const realm = await Realm.open({
        sync: {
            user: user,
            url: `realm://${SERVER_URL}/~/settings`,  // `realm://` does not match `https://` above!!
        }
    });

    console.log(realm.schema);
}

main()
```

And this is the output you get:

```
$ node client.js
user logged in
Connection[1]: Connected to endpoint '52.25.153.251:80' (from '192.168.1.140:49433')
ERROR: Connection[1]: Writing failed: Connection reset by peer
Connection[1]: Connection closed due to error
Connection[1]: Connected to endpoint '52.25.153.251:80' (from '192.168.1.140:49435')
ERROR: Connection[1]: Writing failed: End of input
Connection[1]: Connection closed due to error
Connection[1]: Connected to endpoint '52.25.153.251:80' (from '192.168.1.140:49436')
ERROR: Connection[1]: Writing failed: Connection reset by peer
```

No hint about why the connection was dropped by the server (and nothing useful in the server logs either)! Changing the prefix from `realm://` to `realms://` fixes it, but it can take a while to identify that as the culprit.

It should give you an explicit error that you are trying to connect to a secure endpoint using an unsecure protocol, and guidance on how to fix it.

**Comment by astigsen** [comment]
> The Cloud load balancer is simply not configured to allow http connections (port 80 isn't opened)

@alebsack mentioned that it was a possibility to open port 80 and just make it return an error, to catch people trying to connect to the wrong port. That would help both on being able to give sensible errors in the client, and also for logging on the server.

> I feel the automatic Realm solves this to some extent. Perhaps we should do more to guide people toward that?

We should definitely do that. There are also a few other things we could do as defensive programming:

1. We could verify that the realm protocol matches the protocol used to log in the user. That would at least catch the case where the developers made a simple mistake, mixing up the protocols.

2. We could allow for only specifying the path component when opening realms (the domain and protocol can be inferred from the `user` object). This would also match how URL's are used in HTML, where not specifying the first part of the URL means that it should be interpreted as relative to the current page (in our case, the server the user is currently logged in to).

**Comment by nirinchev** [comment]
I agree with 2 - it is already supported by the .NET SDK, so perhaps it's just a matter of aligning the other SDKs. 

My only concern with 1 is that there could be a rare use case where people are hosting auth over SSL but sync over plain http. Not sure if it's worth supporting though.

**Comment by kneth** [comment]
The default sync configuration can help you with this. A general remark is that we don't enough input validation.

**Comment by astigsen** [comment]
> My only concern with 1 is that there could be a rare use case where people are hosting auth over SSL but sync over plain http. Not sure if it's worth supporting though.

I think the default should be that we throw a `protocol mismatch` error. If someone happens to do an exotic setup (only possible with a customs stand-alone instance of ROS), then we could offer them a flag to disable this error, but it seems like a very rare use case.
