### ISSUE TITLE
Multiple types for a property?

### ISSUE THREAD

**Issue by donni106** [realm/realm-js#1771]
## Goals

I want to import my JSON data successfully.

## Expected Results

Complete import of a JSON with a schema containing:
```
"hint": {
  "type": ["boolean", "string"]
}
```

So I tried to adapt this to my realm schema:
```
hint: {
  type: ['boolean', 'string']
}
```

## Actual Results

> .hint must be of type 'string', got (boolean,string)

When changing to realm schema:
```
hint: {
  type:  'string'
}
```

> .hint must be of type 'string', got 'boolean' (false)

How can I achieve an import to realm with this JSON, where `hint` differs between boolean and string?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- Node or React Native: React Native 0.55.3
- Client OS & Version: macOS developing for iOS and Android
- Which debugger for React Native: React Native Debugger

**Comment by donni106** [comment]
Maybe I end up mapping the property to string before creating it in the realm.
So
```
hint: {
  type:  'string'
}
```
should be fine.

**Comment by nirinchev** [comment]
Yes - Realm has a strongly typed schema where properties may not have mixed types. Converting your boolean values to strings should work as long as you have an easy way to figure out if you should read the string as a boolean or a legitimate string.
