### ISSUE TITLE
React Native, iOS - Unable to open pre-bundled encrypted realm on actual iOS device

### ISSUE THREAD

**Issue by jjgp** [realm/realm-js#1772]
I am reporting here what I have experienced and has been reported by other developers in realm-cocoa here:
https://github.com/realm/realm-cocoa/issues/5488

I believe it is more suited here (...or maybe realm-core?) based on the stack trace.

## Goals

Would like to open a pre-bundled encrypted realm on an actual iOS device.

## Expected Results

Being able to open a pre-bundled encrypted realm on an actual iOS device.

## Actual Results

I created a pre-bundled realm with a node script. The realm was bundled in the resources in the Xcode project. When attempting to open the realm on the actual iOS device., RealmJS throws an error "Unable to open a realm path...".

NOTE: removing the encryption key from the realm will allow for it to work on the device.

The encrypted pre-bundled realm actually works on all simulators and devices Android & iOS except an actual iOS device.

## Steps to Reproduce

- Create an encrypted realm with the encryptionKey param in the schema.
- Bundle said realm in the Xcode project by including it as a bundled resource.
- Attempt to open said realm via the RealmJS interface.

<img width="713" alt="screen shot 2018-04-30 at 10 24 58 am" src="https://user-images.githubusercontent.com/3421544/39432212-db6c9662-4c60-11e8-8792-d7f5fc8aa1af.png">
(This is small can reproduce stack track...sorry)

<img width="489" alt="screen shot 2018-04-30 at 11 46 13 am" src="https://user-images.githubusercontent.com/3421544/39436513-25a1c0d0-4c6c-11e8-95c5-91972e792b02.png">

## Code Sample

The code is very similar to what is reported in:
https://github.com/realm/realm-cocoa/issues/5488

I am happy to provide more if requested.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- Node or React Native: React Native
- Client OS & Version: iOS 11
- Which debugger for React Native: None, used Xcode debugger in native code.

**Comment by jjgp** [comment]
After digging into this some more, it seems to be at the integration with realm-core. The only thing that I see so far is that the page_size() on iOS is different.

Upon understanding more I may open this issue in realm-core.

### Debugging Process

Modify group.hpp to include portions of SlabAlloc::attach_file as this is where the decryption error is thrown and I haven't figured a quicker way to include source. The modified portions I've used to debug is below.

### Findings

It seems `File::Map<char> map(m_file, File::access_ReadOnly, size);` actually throws. The only thing I can note different between that and the sim is the size.

### Modified group.hpp
```cpp
// Implementation

static void validate_buffer(const char* data, size_t size, const std::string& path)
{
    // Verify that size is sane and 8-byte aligned
    if (REALM_UNLIKELY(size < sizeof(24) || size % 8 != 0))
        throw InvalidDatabase("Realm file has bad size", path);
        
    const SlabAlloc::Header& header = *reinterpret_cast<const SlabAlloc::Header*>(data);

    // First four bytes of info block is file format id
    if (REALM_UNLIKELY(!(char(header.m_mnemonic[0]) == 'T' && char(header.m_mnemonic[1]) == '-' &&
                         char(header.m_mnemonic[2]) == 'D' && char(header.m_mnemonic[3]) == 'B')))
        throw InvalidDatabase("Not a Realm file", path);
    
    // Last bit in info block indicates which top_ref block is valid
    int slot_selector = ((header.m_flags & SlabAlloc::flags_SelectBit) != 0 ? 1 : 0);

    // Top-ref must always point within buffer
    uint_fast64_t top_ref = uint_fast64_t(header.m_top_ref[slot_selector]);
    if (slot_selector == 0 && top_ref == 0xFFFFFFFFFFFFFFFFULL) {
        if (REALM_UNLIKELY(size < sizeof(SlabAlloc::Header) + sizeof(SlabAlloc::StreamingFooter)))
            throw InvalidDatabase("Realm file in streaming form has bad size", path);
        const SlabAlloc::StreamingFooter& footer = *(reinterpret_cast<const SlabAlloc::StreamingFooter*>(data + size) - 1);
        top_ref = footer.m_top_ref;
        if (REALM_UNLIKELY(footer.m_magic_cookie != 0x3034125237E526C8ULL))
            throw InvalidDatabase("Bad Realm file header (#1)", path);
    }
    if (REALM_UNLIKELY(top_ref % 8 != 0))
        throw InvalidDatabase("Bad Realm file header (#2)", path);
    if (REALM_UNLIKELY(top_ref >= size))
        throw InvalidDatabase("Bad Realm file header (#3)", path);
}
    
inline Group::Group(const std::string& file, const char* key, OpenMode mode)
    : m_alloc() // Throws
    , m_top(m_alloc)
    , m_tables(m_alloc)
    , m_table_names(m_alloc)
    , m_is_shared(false)
    , m_total_rows(0)
{
    init_array_parents();

    if (is_attached() || m_is_shared)
        throw LogicError(LogicError::wrong_group_state);
    
    SlabAlloc::Config cfg;
    cfg.read_only = mode == mode_ReadOnly;
    cfg.no_create = mode == mode_ReadWriteNoCreate;
    cfg.encryption_key = key;
    
    const std::string path = file.c_str();
    
    util::File m_file;
    
    using namespace realm::util;
    File::AccessMode access = cfg.read_only ? File::access_ReadOnly : File::access_ReadWrite;
    File::CreateMode create = cfg.read_only || cfg.no_create ? File::create_Never : File::create_Auto;
    m_file.open(path.c_str(), access, create, 0);
    
    if (cfg.encryption_key) {
        m_file.set_encryption_key(cfg.encryption_key);
    }
    
    try {
        size_t size = page_size();
        m_file.prealloc(size);
        File::Map<char> map(m_file, File::access_ReadOnly, size); // Throws
        // we'll read header and (potentially) footer
        realm::util::encryption_read_barrier(map, 0, 24);
        realm::util::encryption_read_barrier(map, size - 24, 24);

        if (!cfg.skip_validate) {
            // Verify the data structures
            validate_buffer(map.get_addr(), size, path); // Throws
        }
    }
    catch (DecryptionFailed) {
        throw InvalidDatabase("Realm file decryption failed", path);
    }
    
    open(file, key, mode);
}
```

**Comment by ironage** [comment]
@jjgp thank you for that analysis! I agree that the page size difference looks suspect. If you wanted to test the theory further, you could create the initial file to be larger than 16384 bytes, and see if it can be opened on the iOS device. Most likely our validation check is too restrictive. Your use case should be supported since Realm files are designed for cross platform. I'll submit a fix to core, but we'll have to reproduce this and verify the fix to be sure before releasing.

**Comment by ironage** [comment]
@jjgp, unfortunately it's not such a quick fix as I expected. See Thomas' [comment](https://github.com/realm/realm-core/issues/3040#issuecomment-385550350) on the core issue.

**Comment by jjgp** [comment]
@ironage Appreciate the responses!
