### ISSUE TITLE
unable to resolve class javax.xml.bind.DatatypeConverter

### ISSUE THREAD

**Issue by puhfista** [realm/realm-js#1779]
## Goals

A successfully installed Android application using Realm

## Expected Results

When I compile my project, for it to work

## Actual Results

<img width="1224" alt="screen shot 2018-05-04 at 9 52 15 am" src="https://user-images.githubusercontent.com/9344431/39637635-d966df6c-4f80-11e8-811a-b26f7035a459.png">

## Steps to Reproduce

On newer versions of Java (confirmed here in Java 10), you are unable to install Realm to an Android application, due to it using a deprecated library: javax.xml.bind.DatatypeConverter

## Code Sample

N/A

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4.0
- Node or React Native: node v9, RN v0.54
- Client OS & Version: MacOS High Sierra
- Which debugger for React Native: ?/None

**Comment by puhfista** [comment]
A similar issue: https://github.com/checkstyle/checkstyle/issues/5027

**Comment by cmelchior** [comment]
This also fails when using Java `9.0.1`. I'm looking into it now.

**Comment by kneth** [comment]
@puhfista We will probably cut a release early next week.
