### ISSUE TITLE
TypeError: Class constructor XYZ cannot be invoked without 'new'

### ISSUE THREAD

**Issue by iclems** [realm/realm-js#1796]
When trying to create an object in the store using Node, the following error happens "TypeError: Class constructor Contact cannot be invoked without 'new'" which makes sense considering Node lack of support for ES6. 

## Steps to Reproduce

realm.create('Contact', data, true);

## Version of Realm and Tooling

- Realm JS SDK Version: 2.4
- Node or React Native: v8.9.1

**Comment by kneth** [comment]
@iclems Can you provide a little more context? For example, what is `data` and how do you open `realm`?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
