### ISSUE TITLE
TypeScript generated Node code is flawed

### ISSUE THREAD

**Issue by davidpasztor** [realm/realm-js#1803]
## Goals
Query Realm using the Node code generated by TypeScript.
Cause seems to be an issue in the type declaration file.

## Expected Results
Generated Node code runs without any errors.
Correct type declaration file

## Actual Results
Running the generated Node code results in a runtime JavaScript type error.
>Error: objectType must be of type 'string', got ([object Object])

## Steps to Reproduce
Call `realm.objects` with an input parameter of type `Realm.ObjectSchema`, then try running the generated Node code.

## Code Sample
The following line of code that compiles fine in TypeScript: `realm.objects<Video>(Video.schema)` generated the following Node code: `realm.objects(Video.schema)`, which causes a runtime JavaScript type error. Changing `Video.schema` to `Video.schema.name` fixes the issue.

The definition of `Video` (though only an example, all other Realm types cause the same issue):
```
class Video {
    public static schema: Realm.ObjectSchema = {
        name: 'Video',
        primaryKey: 'youtubeID',
        properties: {
            youtubeID:     'string',
            title:         'string',
            filePath:      'string?',
            thumbnailPath: 'string?',
            uploadDate:    'date'
        }
    }

    public youtubeID: string;
    public title: string;
    public filePath?: string | null;
    public thumbnailPath?: string | null;
    public uploadDate: Date;
}
```

The type declaration file contains the following declaration for the query functions `objects` and `objectForPrimaryKey`:

```TypeScript
/**
* @param  {string|Realm.ObjectSchema|Function} type
* @param  {number|string} key
* @returns {T | undefined}
*/
objectForPrimaryKey<T>(type: string | Realm.ObjectSchema | Function, key: number | string): T | undefined;

/**
* @param  {string|Realm.ObjectType|Function} type
* @returns Realm
*/
objects<T>(type: string | Realm.ObjectSchema | Function): Realm.Results<T>;
```

The comments for the type definition and the actual type definition don't match for `objects`. The comments show that the `type` input parameter should either be a `string`, `Realm.ObjectType` or `Function` while the actual type definition use `Realm.ObjectSchema` instead of `Realm.ObjectType`.

Due to the fact that the corresponding Node function expects a `string` input argument and not an `Object`, it seems to me that the TypeScript function signature should not contain the `Realm.ObjectSchema` type. However, when looking at the comments of the type definition, I suppose what should actually happen is changing `Realm.ObjectSchema` to `Realm.ObjectType`.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.5.0
- Node or React Native: Node v8.9.4
- Client OS & Version: macOS 10.13.4
- Which debugger for React Native: N/A

**Comment by kneth** [comment]
@davidpasztor Thanks for reporting. I have created #1816.
