### ISSUE TITLE
Sync hooks to modify data before sync (encryption at rest on ROS)

### ISSUE THREAD

**Issue by bkniffler** [realm/realm-js#1804]
## Goals

Being able to modify data objects before they are synced to ROS would allow for querying all data locally as if non-encrypted and still have it encrypted on the server via end-to-end encryption.

Currently, with e.g. ZeroKit, data needs to be encrypted locally, thus when I have a contact book with persons, I'd need to decrypt all data before I can search a contact by name.

**Comment by bkniffler** [comment]
As I said, its not about local encryption, but about encrypting before sending it to ROS. I want to query unencrypted data locally, but encrypt it as soon as it leaves the device.

ps. I don't get all the fuzz about ZeroKit and realm, is there any real integration, or is it more something like "hey, these to techs work really well together"?

**Comment by kneth** [comment]
If you use `realms://` in your server URL, the traffic is encrypted.

**Comment by bkniffler** [comment]
I'm not talking about basic secure transport. I'm talking about end-to-end encryption. So encrypting data on the client in a way that will not let anyone gaining control over the server to read the data. And I know I can do it already by encrypting data the moment I create/modify it in realm-js, but this means that every time I need to query for encrypted data (`name LIKE "*abc*"`), I need to unencrypt everything.

It would be much more efficient to encrypt data ONLY the moment before it is synced with a remote server. 

```
realm.open('realms://abc.com', {
  onSend: (obj) => {
     if (obj.type === 'Person') {
         obj.name = encrypt(obj.name)
     }
  },
  onReceive: (obj) => {
     if (obj.type === 'Person') {
         obj.name = decrypt(obj.name)
     }
  }
})
```

I hope this is clear now.

**Comment by kneth** [comment]
When you query an encrypted database, you don't have to decrypt everything. Internally, Realm is working on the encrypted data.

If you use `https` and `realms` when communicating with your server, it should not be possible to obtain any credentials which will make someone able to "gain control" over your server.

I suggest that you read the [white paper on secure apps](https://www2.realm.io/whitepaper/highly-secure-offline-first-apps-success).

**Comment by bkniffler** [comment]
Okay, I'll try to explain one more time. But I want to make it clear: This is not about SSL, this is not about fully AES encrypted local databases, this is not about trusting my own server or your realm servers. This is about zero knowledge, end-to-end encryption using something like Zerokit which you guys officially advertised (https://realm.io/blog/end-to-end-encryption-for-realm-by-tresorit-zerokit/ and https://tresorit.com/zerokit/realm), about securely encrypting some parts of the user data, in a way that will only allow this user to work with their data.

And I know that you guys support ZeroKit. I know how to implement ZeroKit. But If I have 1.000.000 objects in my local database, and I need to perform a search on the encrypted field (like a persons name), I will need to decrypt all data into memory and then I can filter the array of results. This is inefficient, this will take a lot of time and is basically not feasible.

Alternatively, you guys could allow for hooks before syncing with the remote database. This would allow to take advantage of ZeroKit without sacrificing local querying abilities.
```
realm.open('realms://abc.com', {
  onSend: (obj) => {
     if (obj.type === 'Person') {
         obj.name = encrypt(obj.name)
     }
  },
  onReceive: (obj) => {
     if (obj.type === 'Person') {
         obj.name = decrypt(obj.name)
     }
  }
})
```

**Comment by ianpward** [comment]
@bkniffler Thanks for your feature request. We don't have anything that would do this right now but it is something we have considered in our future roadmap. Today, with sync and ROS, we have encryption on the client and encryption in transit but we do not have encryption on the backend ROS. This is something we definitely plan to add. 

Zerokit has true end-to-end encryption - even when the application is running because the Realm process never sees the unencrypted data - but this has drawbacks with queries as you have uncovered as well as less granularity around conflict resolution and declaring types.
