### ISSUE TITLE
Command line for building from source in node

### ISSUE THREAD

**Issue by andytompkins** [realm/realm-js#1805]
The README states to run `npm install --build-from-source=realm`, however that command does not work as intended. I believe the command should be `npm install --build-from-source realm`.

## Goals

Build from source for node

## Expected Results

The package would attempt to build from source

## Actual Results

Nothing happened. This was in a newly created npm package dir (it had package.json and nothing else, no dependencies specified).

## Steps to Reproduce
npm init a new package
run the command from README

## Version of Realm and Tooling

- Realm JS SDK Version: latest/master
- Node or React Native: 8
- Client OS & Version: alpine 3.7
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
The command `npm install --build-from-source=realm` is intended to be used within the repository. 

If you are going to install Realm in a node.js app, `npm install realm --save` will install it and add it to your app's `package.json`.
