### ISSUE TITLE
Example query using BETWEEN (if supported)

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1807]
The [Docs](https://realm.io/docs/javascript/latest/#filtering) mention that we can use `BETWEEN` in a query but there's no example on how to do that. Also, there's some conflicting information on whether it is supported or not - if it isn't, let's remove it from the docs.

**Comment by kneth** [comment]
https://github.com/realm/realm.io/pull/4512

**Comment by kneth** [comment]
Update merged
