### ISSUE TITLE
When restart app, I got "0" with "realm.objects('model').length".

### ISSUE THREAD

**Issue by ghostrick** [realm/realm-js#1811]
I used `realm.create` to insert data. It works normally.
After that, when `realm.objects('model').length` is executed, I got "1". It works well !!

However, after restarting the application, if you execute `realm.objects('model').length` again, I got "0".
The data has disappeared. Or I can not get it well.

This behavior occurs on some android device. It does not occur on most devices.

Here is my code.

```javascript
// realm.js
import Realm from 'realm'

let realm = new Realm({
    schema: [
        { name: 'Card', properties: { card_number: 'string', jwt_token: 'string'} }   
    ]
})

export default realm

```

```javascript
    // component.js
    //...
    componentWillMount(){
        this.setState({
            isFirst: realm.objects('Card').length == 0 // true ...
        })
    }
    //....

```

**Comment by kneth** [comment]
Does it only happen on Android? Does it only happen when debugging?

**Comment by ghostrick** [comment]
@kneth 
No. We released our application.
Then, this bug has occurred on a few android devices.
During debugging this bug did not occur.

**Comment by kneth** [comment]
@ghostrick Do you know which devices?

**Comment by ghostrick** [comment]
@kneth 
There are three devices with problems as follows.
These three were reported by our customers.
- Xperia Z5 Compact SO-02H 
- Arrows NX F-02G
- Honor9

**Comment by kneth** [comment]
It is three very different devices so I doubt it is a device specific bug. Can you reproduce it in a simple test?

**Comment by ghostrick** [comment]
@kneth 
I will use AsyncStorage only for this project.
I appreciate your response and I will continue to use Realm in other projects. Thank you !!

**Comment by kneth** [comment]
@ghostrick Is it possible for you to share your source code and the Realm file? As you can see, I added the label `Reproduction Required` since I haven't observed it.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
