### ISSUE TITLE
Throws exception "dd is not defined" on sync error

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1814]
Hi,

Today realm cloud is having issues which means that it is unavailable and is provoking a sync error in my app. 

After my sync: {error: method}} is called the app crashes with an exception in xcode "dd is not defined" 

I don't think the app should crash if there is a sync error.

**Comment by kneth** [comment]
I agree that an app shouldn't crash due to a sync error (or any other error). `dd is not defined` does not ring a bell. Is it possible for you to post your error handler function? And also mention Realm JS version, etc. (the questions asked in the issue template)?

**Comment by sambwest** [comment]
Sorry for the delay in getting back to you. 

This error was only generated when the cloud sync server was down for a couple of hours. I cannot replicate it again now. 

I guess I'll close this for now as I haven't given you much to go on. Apologies.

**Comment by kneth** [comment]
@sambwest Thanks. If you see it again, please reopen the issue.
