### ISSUE TITLE
Document that Expo does not support Realm

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1826]
## Goals

As a developer I would like the Realm documentation to mention that Expo doesn't work with Realm if I encounter https://github.com/realm/realm-js/issues/1168.

As context I ran into this by using https://github.com/react-community/create-react-native-app, installing realm, running `npm start` and trying to bring up the app using the Expo app.

## Expected Results

The documentation could mention that (and why) Realm cannot be used with the Expo app.

Even better would be for Realm JS to recognize that it's running in the Expo app and throw an error with a link to https://expo.canny.io/feature-requests/p/support-for-realm

## Actual Results

Neither [the docs](https://realm.io/docs/javascript/latest/#missing-realm-constructor) nor the error mentions that the missing Realm constructor is a limitation of Expo when running Realm.

## Steps to Reproduce

N/A

## Code Sample

N/A

## Version of Realm and Tooling

- Realm JS SDK Version: N/A
- Node or React Native: React Native
- Client OS & Version: N/A
- Which debugger for React Native: None

**Comment by hasanal1995** [comment]
you can eject it

**Comment by kraenhansen** [comment]
@hasanal1995 thanks - I suppose I could.
Perhaps that solution should be a suggested work-around on Realms documentation, if it works.

**Comment by kneth** [comment]
Internal note: https://github.com/realm/realm.io/pull/4530

**Comment by kneth** [comment]
I have added a note to the documentation.
