### ISSUE TITLE
how to store an array of objects, best practice please !

### ISSUE THREAD

**Issue by hasanal1995** [realm/realm-js#1827]
i need to store huge amount of records from api in realm, what is best practice please !

i tried this way but i think that is not solution 
   new Promise((resolve, reject) => {
       try {
           realm.write(() => {
               newData.map((v, i) => {
                   realm.create(clientInfo, { name: v.toString(), age: v });
               })
               resolve(newData)
           })
       }
       catch (err) {
           reject(err)
       }
   })
}

**Comment by kneth** [comment]
Using a large transaction as you do in the snippet above, will give you better performance compare doing many small transactions.

As `Realm.write()` is catching any exceptions thrown and rollback the transaction, you don't need the `try`/`catch` block.
