### ISSUE TITLE
Unable to open encrypted realm in realm studio

### ISSUE THREAD

**Issue by karthikpala** [realm/realm-js#1829]
## Goals

I am trying to use a 64 bit hash string generated at [https://passwordsgenerator.net/sha256-hash-generator/](here) and use the following method to convert it into byte array.
```
function toByteArray(str) {
	var array = new Int8Array(str.length);
	for (i = 0; i < str.length; i++) {
		array[i] = str.charCodeAt(i);
	}
	return array;
}
```

Later we pull the realm db and use the 128 length hex string generated from the hash ([http://www.convertstring.com/EncodeDecode/HexEncode](url)) to decrypt. After doing this, the decryption is failing with error ->
 `Realm file decryption failed.`

A weird thing is this whole process is working for me when I use this key which I found randomly online.
lyNZHNHP7LDv17An6pOxADNLKYYqXYoQHxtmjjacTDR5RlkEbiJ2ELgJmRJ6/g==
The rest of the process was all same. Instead of using a 64 bit hash string, I was using the above key

## Version of Realm and Tooling

- Realm JS SDK Version: 2.2.0
- Node or React Native: React Native
- Client OS & Version: Android 7.1.1
- Which debugger for React Native: None

**Comment by kneth** [comment]
Can you provide us with a Realm file?

@kraenhansen Do you have any ideas or suggestions?

**Comment by kraenhansen** [comment]
I don't understand how / why the hex-decoder is used in this setup?

**Comment by kraenhansen** [comment]
I just tried this:
1. On https://passwordsgenerator.net/sha256-hash-generator/ I generated the hash `9B96A1FE1D548CBBC960CC6A0286668FD74A763667B06366FB2324269FCABAA4` which matches the passphrase `hi there`.
2. I used a script which used your function to generate a Realm (I've uploaded this to WeTransfer here https://we.tl/W6ScTQWrfR):
    ```
    const realm = new Realm({
      toByteArray("9B96A1FE1D548CBBC960CC6A0286668FD74A763667B06366FB2324269FCABAA4"),
      path: realmPath,
      schema: [SomeClass],
    });
    ```
3. I used http://www.convertstring.com/EncodeDecode/HexEncode to convert the phrase into a its hex representation: `39423936413146453144353438434242433936304343364130323836363638464437344137363336363742303633363646423233323432363946434142414134` and successfully opened the Realm using Studio.

**Comment by karthikpala** [comment]
Thanks for trying this out guys. 
FYI
I am using the following commands to pull the realm file from the emulator.
`adb exec-out run-as <package-name> cat files/localData.realm > realm/localData.realm`
(or)
```
adb root
adb pull /data/data/<package_name>/files/
```

@kraenhansen Thanks again for the whole steps.
I have just downloaded the file you've provided and tried to open with the hex string given by you.
Again same issue, It says **Unable to open a realm at path 'C:\Users\palakart\Desktop\encrypted-3 (1).realm': Realm file decryption failed.**
I'm using Realm Studio for Windows v2.0.0
Is there any problem with realm studio on windows?
Are you guys trying it out on a windows version?

**Comment by karthikpala** [comment]
@kneth Here is the realm file I've been using [https://we.tl/ueAHveTZTC](https://we.tl/ueAHveTZTC)

I've used following key to encrypt 

`D2C9090FAFFD4C5E66D36EE432975B8CD48854E4C50DD8E6FECF3100A76FE7D1`

and I've tried to decrypt it using the hex string as below
`44324339303930464146464434433545363644333645453433323937354238434434383835344534433530444438453646454346333130304137364645374431`

Then it is failing 😢 
PS:This is completely working fine with in the react native application.

**Comment by nirinchev** [comment]
I'd just like to point out I don't think encrypted Realm files are platform agnostic - generally you won't be able to open an encrypted Realm created on Android with Studio on Windows and vice versa. Could this be the reason for the behavior you're observing?

**Comment by fealebenpae** [comment]
> I don't think encrypted Realm files are platform agnostic

That's right - encrypted realm files rely on the platform-specific page size and are not portable across systems with different page sizes (e.g. armv7 and x86_64 processors, for example).

**Comment by karthikpala** [comment]
@nirinchev  @fealebenpae  But as I mentioned weirdly it worked for me one (or) two times. Now I am unable to replicate that. It is failing all the times.

If this is the limitation, do you know of any workaround for this?

**Comment by kraenhansen** [comment]
I was able to open your Realm on my Mac.

<img width="912" alt="skaermbillede 2018-05-31 kl 20 10 16" src="https://user-images.githubusercontent.com/1243959/40799724-a919817c-650e-11e8-93ee-67607254d7dd.png">

**Comment by karthikpala** [comment]
@kraenhansen  
😭 So it is platform specific then?
If so, Any idea why it worked one or two times like in a 50 trials I've made in these 3 days

Did any user with realm studio on a windows machine reported this issue earlier?

**Comment by kneth** [comment]
@karthikpala I suggest that you open an issue at https://github.com/realm/realm-studio/issues

**Comment by cryptoPickle** [comment]
I know it is old issue, it might help someone.

I had same issue as well, what i found out that you can't access the encrypted realm file with multiple process. So if you are trying to access your file while your simulator opened the realm file. You should close the realm file from your simulator and try to access with realm studio.
