### ISSUE TITLE
Bug: Should soft fail and continue on fallocate error on AWS Lambda

### ISSUE THREAD

**Issue by heri16** [realm/realm-js#1832]
## Goals
Trying to run realm-js on nodejs 8.10 AWS Lambda.

## Expected Results
Should be able to open a realm path on /tmp

## Actual Results
```
{
    "errorMessage": "posix_fallocate() failed: Operation not permitted",
    "errorType": "Error",
    "stackTrace": [
        "Function.open (/var/task/node_modules/realm/lib/extensions.js:72:47)",
        "exports.handler (/var/task/api/realm.js:45:25)"
    ]
}
```

## Steps to Reproduce
1. Create a serverless framework project.
1. npm install realm.
1. Deploy the function below: `sls deploy -f realm`
1. Try invoking the function below: `sls invoke -f realm --data "{'test': 'ok'}"`

## Code Sample
    'use strict'
    
    // See: https://realm.io/docs/javascript/latest/#getting-started
    
    const process = require('process')
    
    const debug = require('debug')('realm')
    const Realm = require('realm')
    
    const CarSchema = {
      name: 'Car',
      properties: {
        make: 'string',
        model: 'string',
        miles: { type: 'int', default: 0 },
      },
    }
    
    // Define new ES6 class
    class Person {
      get fullName() {
        return `${this.firstName} ${this.lastName}`
      }
    
      static get schema() {
        return {
          name: 'Person',
          properties: {
            name: 'string',
            birthday: 'date',
            cars: 'Car[]',
            picture: 'data?', // optional property
          },
        }
      }
    }
    
    exports.handler = async (event, context) => {
      console.log('Received event', JSON.stringify(event, 3)) // eslint-disable-line no-console
      console.log('Received context', JSON.stringify(context, 3)) // eslint-disable-line no-console
    
      let realm
      try {
        process.chdir('/tmp')
        realm = await Realm.open({
          path: '/tmp/cars.realm',
          inMemory: true,
          schema: [CarSchema, Person],
        })
      } catch (err) {
        console.error(err) // eslint-disable-line no-console
        throw err
      }
    
      // Create Realm objects and write to local storage
      realm.write(() => {
        const myCar = realm.create('Car', {
          make: 'Honda',
          model: 'Civic',
          miles: 1000,
        })
        myCar.miles += 20 // Update a property value
      })
    
      // Query Realm for all cars with a high mileage
      const cars = realm.objects('Car').filtered('miles > 1000')
    
      // Will return a Results object with our 1 car
      debug('cars.length:', cars.length) // => 1
    
      // Add another car
      realm.write(() => {
        realm.create('Car', {
          make: 'Ford',
          model: 'Focus',
          miles: 2000,
        })
      })
    
      // Query results are updated in realtime
      debug('cars.length:', cars.length) // => 2
      console.log('cars.length:', cars.length) // eslint-disable-line no-console
    
      return {
        statusCode: 200,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(cars),
      }
    }## Version of Realm and Tooling
* Realm JS SDK Version: ? Latest
* Node or React Native: ? Nodejs v8.10
* Client OS & Version: AWS Lambda Runtime
* Which debugger for React Native: None

**Comment by kneth** [comment]
Sorry for the late response.  The only thing I can suggest is that you check the permissions of `/tmp`.

**Comment by heri16** [comment]
I am sorry, this is not a user-help issue. There is no benefit from checking the permissions of /tmp when the PaaS provider is the one that controls it.

**Comment by kneth** [comment]
@heri16 Thanks for the hint on sparse files. 

@finnschiermer Can you enlighten us on sparse files and `mmap()`?

**Comment by kneth** [comment]
@heri16 Do you know which file system `/tmp` is? You can see it from the output of `mount`?

**Comment by jeddWebill** [comment]
Hi Is there any update on this?

**Comment by heri16** [comment]
@kneth it it the ephemeral filesystem provided on AWS Lambda.

**Comment by heri16** [comment]
Instead of doing of programming for every type of POSIX filesystem out there, should do defensive programming instead.

**Comment by kneth** [comment]
@heri16 @jeddWebill @emanuelez 

We have a fix coming up in #2178. I plan to release it as v2.22.0-alpha.1 but I will notify you when happens.

**Comment by kneth** [comment]
@heri16 @jaggs6 I have release a fix for AWS Lambda as v2.22.0-beta.1. I kindly ask you to try it out and tell me if it works out for you. If it does, I will release v2.22.0 Wednesday or Thursday next week.

**Comment by kneth** [comment]
v2.22.0-beta.1 doesn't fix it. But I don't think in it in our code. Running `fallocate -l 1M foo.img` give the same error.

**Comment by mithunph** [comment]
Hi everyone,
Is the issue fixed now?

**Comment by kneth** [comment]
@mithunph Unfortunately not. AWS support hasn't been able to explain why it doesn't work.

**Comment by mithunph** [comment]
Hi @kneth ,
Will it work atleast under EC2 instance instead of AWS Lambda(serverless)?

**Comment by bmunkholm** [comment]
@mithunph Absolutely. Our whole Cloud is running there :-)

**Comment by mithunph** [comment]
Thanks @bmunkholm @kneth
