### ISSUE TITLE
Query based sync docs

### ISSUE THREAD

**Issue by ironage** [realm/realm-js#1836]
https://realm.io/docs/javascript/latest/#partially-synced-realms (2.6.0) The sample code in this section is incorrect. 

`var results = realm.objects('Integer', 'age > 5');` 

It will give a runtime error, because only one argument is accepted in the `objects` method. It should change to:

`var results = realm.objects('Person').filtered('age > 5');`

**Comment by kneth** [comment]
Internal note: https://github.com/realm/realm.io/pull/4529
