### ISSUE TITLE
Incorrect docs for object-level permissions

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#1837]
The object level permissions docs look like a copy of the class-level docs: https://docs.realm.io/platform/using-synced-realms/access-control#object-level and don't actually show how to set permissions on a single object.

**Comment by kneth** [comment]
@nirinchev I have saved a draft on gitbook for you.

**Comment by kneth** [comment]
My draft has been lost so I have to recreate it.

**Comment by nirinchev** [comment]
I'd recommend editing the markdown files on https://github.com/realm/docs-platform and opening a PR - seems much easier to use than the UI.

**Comment by cmelchior** [comment]
We should have new, corret, docs for fine-grained permissions in: https://docs.realm.io/platform/using-synced-realms/access-control/fine-grained-permissions
