### ISSUE TITLE
Types returned by objects and objectForPrimaryKey should intersect `T` with `Realm.Object`

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1838]
## Goals

Even move precise types.

When calling the `objects` or `objectForPrimaryKey` either a collection of or a single live object is returned. Besides the fields defined on the schema these objects also has a couple of methods defined on them at runtime that the types does not know of.

## Expected Results

When calling `realm.objectForPrimaryKey<T>( ... )` (specifying a generic type `T`) I would expect the returned object to have type `T & Realm.Object`. See https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types.

When calling `realm.objects<T>('...')` (specifying a generic type `T`) I would expect the returned `Results<T>` (that is extending `Collection<T>`) to be ultimately extending `ReadonlyArray<T & Realm.Object>` so the object methods are available when iterating the individual objects using `forEach` and `map`.

## Actual Results

The two methods return objects with the generic type `T` and is only adding in the methods from `Realm.Object` at runtime.

## Steps to Reproduce + Code Sample

Let's say you have a Realm opened with a single class in the schema.

```
interface Person {
  id: string;
  name: string;
}
```

If you query for that object and supply the Person schema you cannot check if the object is valid.

```
const person = realm.objectForPrimaryKey<Person>( /* some id */ );
person.isValid() // <- TSC will complain, claiming that this method is missing
```

The same goes when iterating.

```
realm.objects<Person>('Person').forEach(person => {
    person.isValid() // <- TSC will complain, claiming that this method is missing
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.6
- Node or React Native: N/A
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by juanfer0002** [comment]
Hi. Any update on this enhacement?

**Comment by nirinchev** [comment]
No, but it's a fairly trivial change, so we'd be happy to accept a PR about it.
