### ISSUE TITLE
Jest test doesn't end when Realm is imported from another file.

### ISSUE THREAD

**Issue by jerdie** [realm/realm-js#1840]
## Goals
Make test finish

## Expected Results
Test end after run

## Actual Results
Test runs but does not end.
This becomes a problem when you have many tests that imports files that import realms. these tests are not eligible for garbage collection and causes Out of Memory error.
At first we were doing --forceExit but hit the error once we had many tests.

## Steps to Reproduce
1. Create js file that imports realm
2. Create test that imports file from step 1
3. Run test

## Code Sample
**\_\_tests__/test.js**
```
import test3 from '../testFile3'

describe('Test1', () => {
    test('simple test', () => {
        expect(1).toEqual(1)
    });
});
```
**testFile3.js**
```
import Realm from 'realm';

const testFn = () => {
};

export default testFn;


```

## Version of Realm and Tooling
**package.json**
```
{
  "name": "testRealm",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest --no-cache --detectOpenHandles"
  },
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "realm": "^2.7.1"
  },
  "devDependencies": {
    "@types/jest": "^22.2.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "^23.1.0",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
- Realm JS SDK Version: 2.7.1
- Node or React Native: Node
- Client OS & Version: Windows
- Which debugger for React Native: None

**Comment by kneth** [comment]
I think this issue is the same as #1387. In node you can simply terminate the script but in your scenario, it is not possible. 

Unfortunately I don't have a timeline for a fix-

**Comment by bmunkholm** [comment]
Closing as duplicate.
