### ISSUE TITLE
Segmentation Fault syncing in (postgres node adapter) from React Native -> ROS -> Postgres

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [realm/realm-js#1845]
Write data from react-native to Realm Object Server by

    Realm.Sync.User.login('https://xxxx-xxxx-xx.us1.cloud.realm.io/', 'xxxxx', 'xxxxxx')
          .then((user) => {
            const config = {
              sync: {
                user,
                url: 'realms://xxxx-xxxx-xx.us1.cloud.realm.io/xxxx',
                error: err => console.log(err),
                partial: true,
              },
              schema: [{
                name: 'one',
                primaryKey: 'id',
                properties: {
                  id: { type: 'int', indexed: true },
                  name: 'string',
                },
              }],
            };
            const realm = new Realm(config);
            console.log(realm.path);
            realm.write(() => {
              realm.create('one', { id: 11, name: 'string' });
            });
          });

and when I run my node postgres adapter to sync the data from ROS to postgres it fails saying Segmentation fault. unable to find any detailed logs. I can sync data from ROS to postgres when i write to ROS through **Realm studio** but doesn't work when I write through **react native**. I'm able to sync data from **postgres to react native through ROS** without issue. and also can see data getting written in ROS through realm studio.

**Comment by kneth** [comment]
@GaudamThiyagarajan Which Realm JS version are you using?

Last week we discovered two bugs which sound like you have hit. If you haven't upgraded, please go to version 2.7.2.

**Comment by GaudamThiyagarajan** [comment]
works fine after updating from 2.7.0 -> 2.7.2.
