### ISSUE TITLE
Record Installation Video

### ISSUE THREAD

**Issue by timanglade** [realm/realm-js#185]
Looking for something in the vein of https://www.youtube.com/watch?v=uwFemnYBzok (which we had to take down from the cocoa docs because the video became outdated, but it used to sit right at the top of “Getting Started”). Basically shows you how to create your first Realm project, from opening up your IDE for the first time, to adding Realm, to building a very simple app.

**Comment by timanglade** [comment]
@TimOliver Is this something you could help us with?

**Comment by TimOliver** [comment]
Yeah! I'd love to help out with that! :)

**Comment by appden** [comment]
I'm not sure this is worth the effort anymore considering our installation instructions boil down to running `rnpm link realm` :smile:

**Comment by timanglade** [comment]
Agreed, great job on that btw @appden!
