### ISSUE TITLE
Unable open encryption realm by realm studio

### ISSUE THREAD

**Issue by HsuWeiYu666** [realm/realm-js#1854]
JS code-----------------------------
        var key = new Int8Array(64);
        for (let i = 0; i < 64; i++) {
            key[i] = 8;
        }
        const realm = new Realm({ schema: [{name: 'Dog', properties: {name: 'string'}}], encryptionKey: key });
-------------------------------------
Then I use realm studio open the realm file
key: 38383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838
message: Unable to open a realm, Realm file decryption failed.

Can anyone tell me why?

**Comment by nirinchev** [comment]
Realm encryption depends on the platform's page size, so if the Realm was created on a platform with a different page size (e.g. some Android devices), you won't be able to open it with Studio.

**Comment by HsuWeiYu666** [comment]
@nirinchev I see.. How can I open it? Have any way to open?

**Comment by nirinchev** [comment]
You can open it on the platform that created the Realm. I don't think you can open it with Studio unless you run studio on an OS with the same page size as your original platform.

**Comment by evilrescuer** [comment]
@HsuWeiYu666 
If you use a Int8Array(64) (filled with 8), I think the **128-hex key**（for realm studio） is:
`080808.......`

I succeed when I write this code to transform(from Int8Array to hexString):
`arr.map(item => item.toString(16).padStart(2, '0')).join('')`
