### ISSUE TITLE
RN "Unexpected token < in JSON at position 0" when connecting to Unsubscribed Realm Cloud

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1862]
## Background

My realm cloud subscription trial expired yesterday (I'll subscribe today, promise!). It has caused the following issue.

## Goals

Open the local realm without any errors. My expired subscription shouldn't effect the opening of a synced realm.

## Expected Results

In react native, realm opens as normal but only causes a sync error.

## Actual Results

An uncatchable exception is thrown, the realm fails to open.

**React Native:** Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/6604613/41475463-7b55e6e6-7084-11e8-85a0-5577b1d360f1.png)

**Node:** Throws a catchable exception as per issue #1555 "Error: Could not authenticate: Realm Object Server didn't respond with valid JSON"

## Steps to Reproduce

Try and open a synced realm when your subscription has expired.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.8.3
- Node or React Native: 0.55.4
- Client OS & Version: osx 10.3
- Which debugger for React Native: chrome

**Comment by kneth** [comment]
`fetch` and `node-fetch` seem to behave differently (https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L44) so it looks like JSON in React Native (https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L248).

**Comment by bmunkholm** [comment]
This should be fixed now.
