### ISSUE TITLE
error when run npm i realm --save

### ISSUE THREAD

**Issue by DevSmoo** [realm/realm-js#1868]
node-pre-gyp ERR! Tried to download(403): https://static.realm.io/node-pre-gyp/2.8.4/realm-v2.8.4-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.8.4 and node@8.10.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--modu
le=D:\\React-Project\\realmTest\\node_modules\\realm\\compiled\\node-v57_win32_x64\\realm.node" "--module_name=realm" "--module_path=D:\\React-Project\\realmTest\\node_modules\\realm\\c
ompiled\\node-v57_win32_x64"
gyp ERR! cwd D:\React-Project\realmTest\node_modules\realm
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to
-build --module=D:\React-Project\realmTest\node_modules\realm\compiled\node-v57_win32_x64\realm.node --module_name=realm --module_path=D:\React-Project\realmTest\node_modules\realm\comp
iled\node-v57_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\React-Project\realmTest\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\React-Project\\realmTest\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\React-Project\realmTest\node_modules\realm
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\React-Projec
t\realmTest\node_modules\realm\compiled\node-v57_win32_x64\realm.node --module_name=realm --module_path=D:\React-Project\realmTest\node_modules\realm\compiled\node-v57_win32_x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.8.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.8.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Smo\AppData\Roaming\npm-cache\_logs\2018-06-17T12_07_35_570Z-debug.log

## Version of Realm and Tooling

    "react": "16.3.1",
    "react-native": "0.55.4"

**Comment by Clovin** [comment]
I have the same problem. But the HTTP status is 404.

node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.8.4/realm-v2.8.4-node-v64-darwin-x64.tar.gz

**Comment by Clovin** [comment]
When I change my node version to v9.11.2. The problem was solved.

**Comment by kneth** [comment]
@Clovin We don't support node 10 yet (node ABI v64 = node 10). See #1813.

@DevSmoo I can do `curl https://static.realm.io/node-pre-gyp/2.8.4/realm-v2.8.4-node-v57-win32-x64.tar.gz -O` so you are probably experience some transient network issue.

**Comment by DevSmoo** [comment]
@Clovin I use another module in my app, I afraid another module be crup

**Comment by DevSmoo** [comment]
@kneth i don't understand what do you want to say :(

**Comment by kneth** [comment]
@DevSmoo By law, we are not allowed to export to certain countries (see https://github.com/realm/realm-js#license) which I believe is the root of your issue. When I wrote my comment earlier, I didn't check your location.

**Comment by mammad2c** [comment]
@DevSmoo 
because of U.S.A fun laws:))  :
داداش کلا 
vpn 
بزن برای کار با 
npm
مشکلت حل میشه به جوز نود 10
