### ISSUE TITLE
Node Object-level Permissions - Schema validation fails

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1875]
## Question

Should the object level permissions be functioning in node / react native / realm cloud? I know this is one of the newer features. I tried for about 3 hours to get it running by following the documentation but I cannot get past this error. 

Are there any examples anywhere? 

## Goals

Open an object-level based permission realm .

## Expected Results

Open without issues. 

## Actual Results

Get a schema validation error.

Property 'Address.permissions' of type 'array' has unknown object type '__Permission'

## Code Sample

```
const AddressSchema = {
  name: 'Address',
  primaryKey: '_id',
  properties: {
    _id: 'string',
    permissions: '__Permission[]',
  },
}
```
## Version of Realm and Tooling

- Realm JS SDK Version: 2.8.3
- Node or React Native: 0.55.4
- Client OS & Version: osx 10.3
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
Yeah, I know we haven't documented it well enough - sorry.

You will have to include in the Realm's schema. Take a look at [this test](https://github.com/realm/realm-js/blob/master/tests/js/permission-tests.js#L173).

**Comment by sambwest** [comment]
Easy when you know how eh! Thanks so much for the pointer. 

For anyone else that stumbles across this thread. You need to add the three realm objects to your schema:

```
const AddressSchema = {
  name: 'Address',
  primaryKey: '_id',
  properties: {
    _id: 'string',
    permissions: '__Permission[]',
  },
}

let schema = [
  AddressSchema, 
  Realm.Permissions.Permission,
  Realm.Permissions.User,
  Realm.Permissions.Role,
]

Realm.open({
  schema: schema,
  sync: {
    user: user,
    url: url,
    fullSyncronization: false,
  }
})
```

**Question:** With the documentation a little difficult to follow at times. Where is the best place to seek help? Here as an issue or in the forums? 

**Question:**  What would be the preferred way to apply a role's permission's to an object? Querying the permissions then applying them one-by-one or is there a better way? I'm using a role as a team. So I'm saying 'this object is available to this team'

**Comment by apperside** [comment]
It's not needed anymore, [this](https://github.com/realm/realm-js/pull/1970) merged pull request fixes this issue
