### ISSUE TITLE
Can not download realm-sync-cocoa like #1645

### ISSUE THREAD

**Issue by jfan0888** [realm/realm-js#1876]
https://github.com/realm/realm-js/issues/1645

It seems like the pull request or any solution has not infected current version.
I can't download realm-sync-cocoa-3.5.5.tar.gz

realm: 2.8.5
react-native: 0.55.4

**Comment by kneth** [comment]
@jfan0888 Do you live in any of the countries mentioned in https://github.com/realm/realm-js/blob/master/README.md#license?

**Comment by jfan0888** [comment]
@kneth 
- Currently I am located in China. It has geo restrictions? If that is true, I was succeeded in downloading it once without any process. Then, I removed the app on simulator, it hasn't been played.
- Can you help me to find solution? By the way, I can't find location list in where you mentioned.

**Comment by kneth** [comment]
@jfan0888 We are allowed to export to China 🇨🇳 

Please post the error message so I can see how it goes wrong.

**Comment by jfan0888** [comment]
OK. You can notice that what I faced.
![capture](https://user-images.githubusercontent.com/23710692/41600515-fd0f4fb6-738a-11e8-8897-4f691dea871f.PNG)
![capture1](https://user-images.githubusercontent.com/23710692/41600525-01e6fb88-738b-11e8-9be3-596f9497dbfe.PNG)

**Comment by kneth** [comment]
@jfan0888 Do you connect to internet through a proxy?

**Comment by jfan0888** [comment]
yeah

**Comment by kneth** [comment]
I am not sure how well `node-fetch` is supporting proxies. At least our downloader doesn't take care of it: https://github.com/realm/realm-js/blob/master/scripts/download-realm.js#L66

**Comment by jfan0888** [comment]
@kneth it didn't solve the problem.

**Comment by jfan0888** [comment]
@kneth I verified that it works properly although the Internet speed is a bit slow.

**Comment by jfan0888** [comment]
@kneth what do you think of Internet speed? 
When i run the instruction you mentioned above, it is said that it will take more than 4 hours even though its size is only 135MB.

**Comment by kneth** [comment]
`static.realm.io` is hosted by Amazon S3 so I can't imagine that the bottleneck is at our end. 4 hours for 135 MB is less than 10 Kbit/sec so maybe you should check your internet connection.

**Comment by jfan0888** [comment]
I couldn't find solution on my end.

**Comment by kneth** [comment]
Let me suggest that you contact your internet provider to see if they can speed up the transfer.

**Comment by Arabrellaxy** [comment]
I happend to experienced this issue today.When I try to run my app from Xcode after installed realm.I got this error as below:

`Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-3.7.0.tar.gz',
  SYNC_ARCHIVE_ROOT: 'core' }
No lockfile found at the target, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-3.7.0.tar.gz
Extracting realm-sync-cocoa-3.7.0.tar.gz => /Users/xxx/Desktop/xxx/node_modules/realm/vendor/realm-ios
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:142:17) errno: -5, code: 'Z_BUF_ERROR' }
Command /bin/sh failed with exit code 1
`

I solved this issue manually based on @kneth 's answer,here are my steps:


**First step:**
 open cmd, locate to your project directory/node_modules/realm/vendor/realm-ios,you will find it is empty😊
**Second step**
 `vim download-realm.lock`,then write "SYNC_SERVER_FOLDER=sync
  SYNC_ARCHIVE=realm-sync-cocoa-3.7.0.tar.gz
  SYNC_ARCHIVE_ROOT=core" into this file.
Save and exit.
Remember to change the version number to what you need.
**Third step**
open another cmd,locate to your downloaded file "realm-sync-cocoa-3.7.0.tar.gz"
excute this command " tar -xzvf realm-sync-cocoa-3.7.0.tar.gz -C yourProjectDirectory/node_modules/realm/vendor/realm-ios"
**Fourth step**
open the first cmd,you will find the directory is not empty any more.copy all the files under directory "core" and paste them under directory "yourProjectDirectory/node_modules/realm/vendor/realm-ios"

Finally,build and run,you will make it.

**Comment by kneth** [comment]
@Arabrellaxy Thank you for the recipe. I think we should include it in our documentation. Downloading works in most cases, but it is always good to have a plan B.

**Comment by kneth** [comment]
I believe there is a bug in `download-realm.js` but it is only triggered in rare cases. I have documented (will be online soon).

**Comment by martsie** [comment]
I'm not sure this recipe works every time. When using it today I'm getting:

```
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',

  SYNC_ARCHIVE: 'realm-sync-cocoa-3.5.1.tar.gz',

  SYNC_ARCHIVE_ROOT: 'core' }

Target directory has a differing lockfile, overwriting.

Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-3.5.1.tar.gz

Extracting realm-sync-cocoa-3.5.1.tar.gz => ******

{ Error: unexpected end of file
```

My lock files looks like:

```
SYNC_SERVER_FOLDER=sync SYNC_ARCHIVE=realm-sync-cocoa-3.5.1.tar.gz SYNC_ARCHIVE_ROOT=core
```
and is placed in `/Users/marty/Documents/Work/01_clients/tupaia/meditrak/node_modules/realm/vendor/realm-ios` along with the contents of the core folder from that sync archive.

Does this fix work with realm versions under 3.7?

**Comment by kneth** [comment]
I have updated the documentation (as suggested above), and this issue seems to hit people with a buggy Mac.

**Comment by YaoHuiJi** [comment]
I tried @Arabrellaxy 's solution , but find that the script delete the file realm-sync-cocoa-xxx.tar.gz in tmpdir and still try to redownload it.so I check the script 'download-realm.js' and find this related code `if (stat.mtime.getTime() !== lastModified.getTime())` in the `download` method ,since the mtime of my own downloaded file is not the SAME as  the network request, so the script still run into the `saveFile` process, so I just comment out this code temporary to let the build pass. 
if someone meet this redownload problem, maybe this comment is useful.

**Comment by yuanyinchun** [comment]
realm-sync-cocoa downloading is very slow in China, I wrote a local file server to serve this file. Repo and usage is [here](https://github.com/yuanyinchun/realmFileServer).   
Hope it helps.

**Comment by alpamys-qanybet** [comment]
why don't we just download file manually and host it in localhost and make it download every time from localhost?!🤔

**Comment by WeijianXu** [comment]
> why don't we just download file manually and host it in localhost and make it download every time from localhost?!🤔

Can you show more detail of your way?

**Comment by alpamys-qanybet** [comment]
@WeijianXu,

in a file ```node_modules/realm/scripts/download-realm.js ```

 ```
function download(serverFolder, archive, destination) {
-    const url = `https://static.realm.io/downloads/${serverFolder}/${archive}`;
+    let url = `https://static.realm.io/downloads/${serverFolder}/${archive}`;
+
+    if (url === 'https://static.realm.io/downloads/sync/realm-sync-cocoa-3.15.0.tar.gz') {
+      url = 'http://localhost/dev/realm/realm-sync-cocoa-3.15.0.tar.gz';
+    }
```

if you don't understand what  - and + means it is git difference.

so, just download the original file and paste it in your localhost. in my case it is ```/var/www/dev/realm/```
