### ISSUE TITLE
Different behavior when debugging / not debugging

### ISSUE THREAD

**Issue by MujtabaFR** [realm/realm-js#1883]
Hello,
I noticed that Realm is behaving very differently according to wither debugging or not

This is just a summary of the idea :
I'm printing `object.constructor.name` to find the type of the object

When debugging (Remotely using Chrome or Safari) : 

```
let realm = new Realm(config);
realm.constructor.name --> will print (Realm)

let dogs = realm2.objects('Dog');
dogs.constructor.name --> will print (Results)

(inserting few dogs)

for (let oneDog of dogs) {
    oneDog.constructor.name --> will print (RealmObject)
} --> works perfectly
```

When not debugging:

```
let realm = new Realm(config);
realm.constructor.name --> will print (Object)

let dogs = realm2.objects('Dog');
dogs.constructor.name --> will print nothing

(inserting few dogs)

for (let oneDog of dogs) {
    oneDog.constructor.name --> not compiled
} --> will give the error below
```
![photo_2018-06-20_17-05-48](https://user-images.githubusercontent.com/7612635/41663610-804eeaae-74ac-11e8-9885-42359cd40667.jpg)

> TypeError: undefined is not a function (evaluating ‘_iterator[typeof Symbol === “function” ? Symbol.iterator : “@@iterator”]()’)

I noticed the problem because I can't get the results of query from Realm when not debugging,
I'm not sure if it's a bug or a problem with my codes

## Version of Realm and Tooling

- Realm JS SDK Version: 2.10.0
- React Native: 0.55.4
- Client OS & Version: Running on Android device 8.0
- Which debugger for React Native: Chrome

## Full code : 

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';

const Realm = require('realm');

export default class Page3Screen extends Component {
  state = { messege : 'no messege' }

  componentWillMount() {
    const config = {
      schema: [{ name: 'Dog', properties: { name: 'string' } }],
    };
    let realm = new Realm(config);
    console.log(realm.constructor.name);
    this.setState({ messege: realm.constructor.name });

    realm.write(() => {
      realm.create('Dog', { name: 'Zozo' });
    });

    let dogs = realm.objects('Dog');
    // console.log(dogs.constructor.name);
    // this.setState({ messege: dogs.constructor.name });

    // for (let oneDog of dogs) {
    //    console.log(oneDog.constructor.name);
    //    this.setState({ messege: oneDog.constructor.name });
    // }
  }

  render() {
    return (
      <View style={{ alignSelf: 'stretch', flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>{this.state.messege}</Text>
      </View>
    );
  }
}
```

**Comment by kneth** [comment]
The error message is related to https://github.com/facebook/react-native/issues/15902.

**Comment by MujtabaFR** [comment]
Thanks .. the suggested [updating the JSC version that ships with android](https://github.com/react-community/jsc-android-buildscripts) solved the issue

**Comment by kneth** [comment]
@MujtabaFR Great to hear!

**Comment by FibreFoX** [comment]
@MujtabaFR I might have found a comment reflecting the different behaviour:
https://github.com/facebook/react-native/issues/18426#issuecomment-375669836

Meanwhile using the newer JSC-version on android helps a lot, especially when using newer versions of RN like 0.57.2 and above.
