### ISSUE TITLE
Realm does not return exception on React native

### ISSUE THREAD

**Issue by alihesari** [realm/realm-js#1885]
I'm using Realm Database on React native. In my Model Schema id field is required. When id field is undefined Realm does return an exception and adding data is not done. Why Realm does not return an exception in try catch??

Model Schema:

    export default class ServicesModule {
        cache = {};
    }
    
    ServicesModule.schema = {
        name: "ServicesModule",
        primaryKey: "id",
        properties: {
            id: "int",
            title: "string?"
        }
    };

Insert data:

    try {
          return new Promise((resolve, reject) => {
             realm().write(() => {
                resolve(realm().create("ServicesModule", {title: 'Test exception'}, true));
             });
          });
    } catch(e) {
       console.error(e.message);
    }

**Comment by nirinchev** [comment]
As far as I can see, there are two issues with that code:
1. You're not awaiting the promise, so the catch clause will not handle a promise rejection.
2. You're not rejecting the promise when an exception occurs.

If you remove the promise stuff, you should be able to properly observe the exception:

```js
try {
    realm().write(() => {
        realm().create("ServicesModule", {title: 'Test exception'}, true);
    });
} catch(e) {
    console.error(e.message);
}
```

**Comment by alihesari** [comment]
@nirinchev Thank you. you are right.
