### ISSUE TITLE
React-Native Debug Error

### ISSUE THREAD

**Issue by duxiwei** [realm/realm-js#1889]
Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine
![test22](https://user-images.githubusercontent.com/15810382/41837511-46454a3c-7890-11e8-8938-97c36efeed63.png)
![screenshot_20180625-155627](https://user-images.githubusercontent.com/15810382/41837636-b1f2d376-7890-11e8-9ef1-f6c578c6c860.png)

**Comment by kneth** [comment]
Please provide more information, for example do you use a real device or emulator. Is it Android or iOS? Which version of Realm JS do you use?

**Comment by duxiwei** [comment]
My device is  Android  , the version of Realm JS I use is  2.21,thank you very much!!

**Comment by kneth** [comment]
@duxiwei Do you forward ports using `adb`?

**Comment by duxiwei** [comment]
yes

**Comment by kneth** [comment]
Does the debugger open in Chrome when you run `react-native run-android`? Do you enable remote debugging in your app on the device?

**Comment by duxiwei** [comment]
It's ok,but the debugger can't work , in other words  the same computer,the same android phone ,the debugger of my other program  is react-native  can work

**Comment by kneth** [comment]
Since your screenshot says 192.168.1.115 and not 127.0.0.1, please explain your set up. Just so I can replicate it.

**Comment by duxiwei** [comment]
System:Ubuntu18.04 , IDE:Webstorm2018.1.5 , node:v8.10.0 ; realm:2.2.1,react-native:0.52.0 , thanks

**Comment by V1sk** [comment]
same issues.

**Comment by kneth** [comment]
@duxiwei Realm JS 2.2.1 is fairly old, so could you try a recent version (2.12.0 or 2.13.0)?

**Comment by duxiwei** [comment]
I have tried it you said many times, but it never works.

**Comment by FokingGit** [comment]
same issue
Some infomation as follow via the Charles
![snipaste_2018-07-22_17-49-55](https://user-images.githubusercontent.com/23710155/43044404-be03ab98-8dd7-11e8-973b-cf89265d3add.png)

**Comment by kneth** [comment]
@FokingGit Can you try debugging over USB instead?

**Comment by Alex-DG** [comment]
I have a similar issue on an iPhone 6 real device when I try to Debug JS remotely:

```
"dependencies": {
"react": "16.4.1",
"react-native": "0.56.0",
"realm": "^2.14.1"
}
```
![image](https://user-images.githubusercontent.com/4311684/43831348-be89e948-9afb-11e8-9767-7a8feaeeb7be.png)

Console:

![image](https://user-images.githubusercontent.com/4311684/43831294-8e8117da-9afb-11e8-900c-c812b6914929.png)

I have no problem with Android though, I can debug and see my console logs.

**Comment by kneth** [comment]
@Alex-DG Thanks for the link to the RN issue. It indicates that using RN < 0.52 is a good idea - or wait for the fix to be released.

**Comment by adnkh** [comment]
For me, It was solved after connecting the device to the same network although it was connected by USB cable.

**Comment by palevoo** [comment]
hey, so is there any work around this issue ??
I have my device on same the network (iPhone), rn 0.57.8, realm 2.22.0
thanks

**Comment by cristianoccazinsp** [comment]
Same issue, can't debug a react native application and use realm at the same time. Same error as above.

**Comment by kneth** [comment]
@palevoo @cristianoccazinsp How do you connect the device? Does it work if you use a simulator?

**Comment by cristianoccazinsp** [comment]
@kneth Device connected through a USB cable.

As it turns out, I had two issues. First, my device had to be on the same LAN/WiFi. Secondly, my host OS (Mac in my case) and firewall had to enable inbound connections. Oddly enough, not all devices prompted me to allow these connections (reason I didn't notice initially).

After resolving the above two, the error is gone. However, I really don't like the fact that I need to be both connected and to also accept incoming network requests through the WiFi. Why can't Realm just use the cable connection like React?

**Comment by vinaytechindustan** [comment]
![realm](https://user-images.githubusercontent.com/41041666/56134414-2b7aea00-5fac-11e9-85b5-40ee3d07cdd2.png)

![image](https://user-images.githubusercontent.com/41041666/56135264-f8d1f100-5fad-11e9-8124-6a5c9ae88fca.png)


Facing the same issue when trying to debug using android device connected through usb cable.
Environment:
react-native:0.59.4
realm:^2.26.1
node:10.15.3

Here are some solutions which i tried but not even single solution worked
-> adb forward tcp:8083 tcp:8083
-> adb forward tcp:8082 tcp:8082
-> changing the file  rpc.js in node_modules/realm/lib/browser/
 The solution provided Selman555 at https://github.com/realm/realm-js/issues/578
-> changing the version of realm to 2.17
and many more but nothing really worked.

**Comment by madandrija** [comment]
> ![realm](https://user-images.githubusercontent.com/41041666/56134414-2b7aea00-5fac-11e9-85b5-40ee3d07cdd2.png)
> 
> ![image](https://user-images.githubusercontent.com/41041666/56135264-f8d1f100-5fad-11e9-8124-6a5c9ae88fca.png)
> 
> Facing the same issue when trying to debug using android device connected through usb cable.
> Environment:
> react-native:0.59.4
> realm:^2.26.1
> node:10.15.3
> 
> Here are some solutions which i tried but not even single solution worked
> -> adb forward tcp:8083 tcp:8083
> -> adb forward tcp:8082 tcp:8082
> -> changing the file rpc.js in node_modules/realm/lib/browser/
> The solution provided Selman555 at #578
> -> changing the version of realm to 2.17
> and many more but nothing really worked.

Same here, I get a few require lifecycle warnings, then there's a pause for about 10 seconds, then "Failed to execute..." message appears

**Comment by autotrof** [comment]
i install microsoft visual studio 2017 with realm ^2.28.1 and it's works
![image](https://user-images.githubusercontent.com/10995834/59970135-fe891b80-9588-11e9-8ca4-9e122800f613.png)

**Comment by bmunkholm** [comment]
@madandrija Is this still an issue for you?

**Comment by madandrija** [comment]
> @madandrija Is this still an issue for you?

With:

react-native:0.59.9
realm: 3.0.0-beta.1

doesn't seem so.

**Comment by ScripterSugar** [comment]
@adnkh Came here for the issue and your solution worked like a charm for me. Thanks!

**Comment by geocfu** [comment]
For future reference to anybody reading this. 
Try to disable your firewall.

**Comment by saurabhtourtech** [comment]
Getting same issue with  "realm": "^10.9.1" & "react-native": "0.66.1"

**Comment by catreedle** [comment]
Getting the same issue with realm 10.12.0 and react-native 0.63.4

I use a device connected to the same WiFi as my PC. couldn't do any workaround successfully @kneth 

https://github.com/realm/realm-js/issues/2551#issuecomment-1028697064

**Comment by catreedle** [comment]
did you find a solution to this @saurabhtourtech ?
