### ISSUE TITLE
command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by Daishygoyal** [realm/realm-js#1891]
**Goals**
Just build the code with realmJS for ios.

**Desired output**

Code should run like android build.

**Actial output**
Terminal stuck at 

![screenshot](https://user-images.githubusercontent.com/6419643/41847746-c0451f4e-7898-11e8-8883-876a0e2a43f5.png)

**Versions**
Node version  - 8.9.1
/usr/local/bin/node  - 8.9.1
sh command which realmJS use to build uses 7.10.0

I tried to fix the node versions usin NVM but no luck.

**Comment by kneth** [comment]
Is your issue similar to #1876? If not, please explain how you build.

**Comment by kneth** [comment]
I am not able to reproduce it. I am using node v8.11.3, xcode 9.4.1, RN 0.55.4 and Realm JS 2.10.0. The steps were:

```
nvm use lts/carbon
react-native init issue1891
cd issue1891
npm install realm --save
react-native link realm
react-native run-ios
```

**Comment by Daishygoyal** [comment]
I followed exact same steps. But exact same issue.
Node v8.9.1, xcode 9.3, RN 0.55.4, Realmjs 2.10.0.

**Comment by kneth** [comment]
Can you try to execute `node ./scripts/download-realm.js ios --sync` manually to get some information about where it goes wrong.

**Comment by Daishygoyal** [comment]
It was the node version issue, I switched to 8.11.3 and it worked.
