### ISSUE TITLE
When mixing JS and Java: java.lang.ClassNotFoundException: Didn't find class on path: DexPathList - io.realm.react.utils.SSLHelper

### ISSUE THREAD

**Issue by githubdoramon** [realm/realm-js#1896]
## Goals

Implement Realm js and Realm java together on an App with React Native integrated to Native Android

## Expected Results

Run the app without crashing

## Actual Results

After building with proguard enabled, the app crashes on open. Is complain that the class io.realm.react.utils.SSLHelper is not found by the React Native environment.

I lost the stack trace, but for future reference, I fixed this by adding this line to proguard:

- keep class io.realm.react.**

**Comment by kneth** [comment]
@githubdoramon To be honest, we haven't tested joining Realm JS and Realm Java in a single app. It sounds like you have figured out how to do it, and your tip is worth adding to our documentation.

**Comment by githubdoramon** [comment]
It took quite some time, but is working... another important tip is to make sure the js and java versions are reading the update data, it is necessary to always perform an empty write (or executeTransaction) before reading the data (when for example you write on js and then try to directly read on java)

**Comment by youngjuning** [comment]
+ 1

**Comment by XiaoJianPeng** [comment]
+1

**Comment by kneth** [comment]
@githubdoramon Thanks for the tips!
