### ISSUE TITLE
How to write data into a nested schema

### ISSUE THREAD

**Issue by paddy-krischa** [realm/realm-js#1909]
My schema is as follows, if i have to add data, how do i do that, any help is appreciated.

const examSchema = {
  name: 'Exams',
  properties: {
    Exams: { type: 'list', objectType: 'ExamList' },
  },
};

const examList = {
  name: 'ExamList',
  properties: {
    creationDateTime: 'date',
    SITE: 'string',
    examCodeList: { type: 'list', objectType: 'ExamCodeList' },
  },
};

const examCodeList = {
  name: 'ExamCodeList',
  properties: {
    EXAMCODE: 'string',
    DESCRIPTION: 'string',
    SUBEXAMS: { type: 'list', objectType: 'SubExamCodeList' },
  },
};

const subExamCodeList = {
  name: 'SubExamCodeList',
  properties: {
    DESCRIPTION: 'string',
    EXAMCODE: 'string',
    SUBSUBEXAM: { type: 'list', objectType: 'SubSubExamCodeList' },
  },
};

const subSubExamCodeList = {
  name: 'SubSubExamCodeList',
  properties: {
    DESCRIPTION: 'string',
    EXAMCODE: 'string',
  },
};

**Comment by kneth** [comment]
Maybe https://stackoverflow.com/questions/50504485/how-to-store-array-of-objects-in-realm-js is useful.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
