### ISSUE TITLE
Encrypting a data store using Javascript

### ISSUE THREAD

**Issue by gnaryak** [realm/realm-js#1910]
## Goals

I am trying to open a synced Realm Cloud data store with an encryption key.

I've tried to follow the documentation. I've looked for examples. I've looked at the source code. I suspect that I am making a mistake somewhere but it sure isn't easy to see where. Perhaps there is a bug in the Realm JS library.

## Expected Results

I would expect to open the encrypted data store, and to require the usage of that same encryption key for future access.

## Actual Results

Error: encryptionKey must be of type ‘binary’, got ([object Object])
at Promise (/myproject/node_modules/realm/lib/extensions.js:85:29)
at new Promise ()
at Function.open (/myproject/node_modules/realm/lib/extensions.js:84:27)
at minimal (/myproject/util/enc.js:7:16)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

The error occurs on the `Realm.open()` line from the code sample.

## Steps to Reproduce

See code sample.

## Code Sample

```
const Realm = require(‘realm’);
const minimal = async () => {
  const buffer = new ArrayBuffer(64);
  const view = new Int8Array(buffer);
  view.fill(7);
  const user = await Realm.Sync.User.login('https://myproject.us1.cloud.realm.io', myUsername, myPassword);
  const realmConfig = user.createConfiguration({ encryptionKey: buffer });
  // I've also tried:
  // const realmConfig = user.createConfiguration({ encryptionKey: view });
  // I've also tried using the base64-js library, sending the output from toByteArray() as the key
  return Realm.open(realmConfig);
}
minimal()
.then(realm => {
  console.log(‘done: %j’, realm);
  process.exit(0);
})
.catch(err => {
  console.log(err.stack);
  process.exit(1);
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.11.0
- Node or React Native: Node
- Client OS & Version: macOS 10.13.5
- Which debugger for React Native: None

**Comment by kneth** [comment]
Please take a look at https://github.com/realm/realm-js/blob/master/tests/js/encryption-tests.js#L73

**Comment by gnaryak** [comment]
@kneth Thanks for the tip to look at the tests. That definitely makes sense, and I should have thought of that. As one might have guessed, when I make my code match the test, it works.

This situation does indicate some discrepancies between the documentation and the codebase. It seems like the user.createConfiguration() and Realm.open() functions are potential causes of gaps between the documentation and the code.

Thanks again for your help!
