### ISSUE TITLE
Is there any function like onAuthStateChanged of firebase for listening user login status?

### ISSUE THREAD

**Issue by tsaohucn** [realm/realm-js#1911]
## Goals
I want to listen user login status to control my screen flow, but I only find  some kind of function like `Realm.Sync.User.login` `Realm.Sync.User.register`, no find any listening function like onAuthStateChanged of firebase, so how could I control screen flow by user login status?

## Expected Results

A function like onAuthStateChanged of firebase for listening user login status

## Actual Results
No find

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
Realm does not provide a callback mechanism as such. But `authenticate`, `login` and `register` return a promise which will be resolve (similar to `completed`) or rejected (similar to `error`).

You can update the screen saying "Logging in", and then call `login`. If the promise resolves, you can update the screen saying "Logged in" and if it is rejected, you can say "Log in failed".

See https://github.com/realm/realm-js/blob/master/tests/js/user-tests.js#L197 for a condensed version :smile:.
