### ISSUE TITLE
Unable Build Debug APK with Execution failed for task ':realm:processReleaseResources'

### ISSUE THREAD

**Issue by RenalPraba** [realm/realm-js#1914]
## Goals

Build unsigned debug react native APK with realm

## Expected Results

Successfully Building Process

## Actual Results

The building process stopped and failed

:realm:compileReleaseRenderscript UP-TO-DATE
:realm:generateReleaseBuildConfig UP-TO-DATE
:realm:generateReleaseResValues UP-TO-DATE
:realm:generateReleaseResources UP-TO-DATE
:realm:mergeReleaseResources UP-TO-DATE
:realm:processReleaseManifest UP-TO-DATE
:realm:processReleaseResources
/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/arbregame/Desktop/Memo/node_modules/realm/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

:realm:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':realm:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.798 secs

## Steps to Reproduce

Adding realm and link it

## Version of Realm and Tooling

- Realm JS SDK Version: 2.12.0
- React : 16.4.1
- React Native: 0.56.0

**Comment by kneth** [comment]
The error messages seems to be unrelated to Realm. Does your app build before you added Realm?

**Comment by RenalPraba** [comment]
I have only redux installed on my project, As I know I did make changes some of android gradle settings before. Previously before added realm it does build, is that changes affect realm?

**Comment by kneth** [comment]
Have you tried to take a look at https://github.com/lolatravel/realm-react-redux?

**Comment by RenalPraba** [comment]
is there any other way, currently i'm not ready yet for looking another library

**Comment by kneth** [comment]
@RenalPraba Can you create a small app which can reproduce this? If so, we can better investigate what is wrong.

**Comment by kraenhansen** [comment]
@kneth I am currently seeing this issue.

**Comment by RenalPraba** [comment]
@kneth i have created a new empty project, installing by npm install realm --save then try to build it and it was successful.
then when I link it using react-native link realm command and build it again the same error showing :realm:processReleaseResources FAILED

**Comment by kneth** [comment]
@RenalPraba My coworker @kraenhansen had the same issue with one of his demo apps, and he figured out what to do. #1918 is a fix, and I plan to get it released tomorrow.
