### ISSUE TITLE
testing react-native app with jest, undefined symbol: SSL_library_init

### ISSUE THREAD

**Issue by CastixGitHub** [realm/realm-js#1916]
## Goals
I wanted to test my react native application with jest
But i get this error
```$ npm test                     

> proj@0.0.1 test /home/castix/proj
> jest

 FAIL  __tests__/index.android.js
  ● Test suite failed to run

    /home/castix/proj/node_modules/realm/compiled/node-v57_linux_x64/realm.node: undefined symbol: SSL_library_init

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:372:31)
      at Object.<anonymous> (node_modules/realm/lib/index.js:102:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.796s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
^C
```

**undefined symbol: SSL_library_init**
Is there something I need to mock with jest or is it an issue with the linking of libssl
The application seems to work fine, but I can't set up unit tests

## Code Sample
jest config in `package.json`
```  "jest": {
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "preset": "react-native",
    "verbose": true,
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|@shoutem/theme|@shoutem/animation|@shoutem/ui|pouchdb-react-native|pouchdb-adapter-asyncstorage|react-native-fetch-blob|realm)"
    ],
    "setupFiles": [
      "./jest_setup.js"
    ]
  }
```
`jest_setup.js`
```
import { NativeModules } from "react-native";

NativeModules.BlobModule = {
  ...NativeModules.BlobModule,
  addNetworkingHandler: jest.fn()
};
```
and `__tests__/index.android.js`
```
import React from 'react';
// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

import Index from '../index.android.js';
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.12.0
- Jest: 23.3.0
- Node or React Native: react native 55
- Client OS & Version: ArchLinux 4.17.3-1-ARCH
- Which debugger for React Native: None

The most similar issue I found is https://forum.realm.io/t/realm-studio-linux-doesnt-open/896
Thanks

**Comment by kneth** [comment]
It is fixed by #1912 and we plan a release Wednesday or Thursday.

**Comment by CastixGitHub** [comment]
Thanks

I think I found a **temporary fix**:
```$ LD_PRELOAD=/usr/lib64/openssl-1.0/libcrypto.so:/usr/lib64/openssl-1.0/libssl.so npm test```

**Comment by ogtimothymiller** [comment]
I have this issue with the latest realm + node v8.10.0

**Comment by kneth** [comment]
@ogtimothymiller Do you still experience it with v2.16.0 (released yesterday)?

**Comment by ogtimothymiller** [comment]
I am unable to test until next Thursday 

Tim

**Comment by bmunkholm** [comment]
Closed due to no response.
