### ISSUE TITLE
registerWithProvider docs/api Inconsistency 

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1919]
The method registerWithProvider has two different signatures depending on which documents you look at. Also using a callback as the third argument is deprecated so perhaps should be indicated as so in the docs.  I think my second example is out of date and needs to be updated. 

https://realm.io/docs/javascript/latest/api/Realm.Sync.User.html
![image](https://user-images.githubusercontent.com/6604613/42529298-b6fdf6ac-8443-11e8-90bc-930263851b1e.png)

https://realm.io/docs/javascript/latest/

![image](https://user-images.githubusercontent.com/6604613/42529321-c4dc8310-8443-11e8-9ff5-509bf1cb5a03.png)

**Comment by kneth** [comment]
Thanks for reporting. The API is the correct one.

**Comment by kneth** [comment]
I have updated the documentation, and it will be online soon.
