### ISSUE TITLE
Realm Cloud - Realm.Sync.User.authenticate = Missing Parameter access token'

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#1920]
## Goals

Authenticate a user using JWT on the realm cloud

## Expected Results

The user authenticates without any issues

## Actual Results

It returns an error saying there are missing parameters, which as far as I can see there aren't. 

## Steps to Reproduce

1) Register a user using the JWT provider. 
2) Try to authenticate that user

## Code Sample

```
var Realm = require('realm')

let token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkZXYxMC0xZTI2MzM5Zi1hZjZjLTRlYWItYTEzYi0xZjg0ODM0NGM5NzQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTMxMjY0MzgxfQ.r9gf7DLNZH2qCyQj8Q4709h5j07aD1_l_WGzDJAq6QmnSrwzKAuT1vwmkupLYJohSz1LmhRgN7CGQBXY3myWOuwg6B96U6kDBO1aWhWrGQ-F-cgbvVdHrQicbZ02YquezdefM4zZzGreaDoe1-3NaIokwGmnKq3WB9-cwEdAmfrjDiKRWdKTzj-dotQz-u2giahv0JoEPAbKjq2UQJQPcwpOB9-nL91-GFxpiXYvBNCzNkMIwLwKixyFIMwfsjW6Jw9dtVhTdFhi5Iy3Amc8uhWiw1gr3Am7W_FpsFLwEno1i6FSvECk-cqxGmmHXoXpciW9inkHS4YJGvbFMN3NBo3nNwr_e9l32IfLP7-6w6MT6xWy5hJkGbXkzVpLXG-ErR5nJ0KQG_fpmaj35DiRDjvRMIGcTzbP-II15BAc71v3k_H9sEae7j0ccZplLnmQCWi9WphluafRGmNqsh6DAbwwya6fP8gCEG90ZJQ8Gjs6ex9XgZ75mRtvXIObJK2Xwk3sohhsZkqPq-A5a0M6hR8L-0PrBGR2HFiMo6Kopj8f_Sz_Q0h_iJy8hYhlVDMg1QAr3GUyPyMsVvGuVd3ntTQ3jhquTVa-5CMuIvQSb_DNPpPdEkAAeFQHb4Fkm39W1_N4A77ok-1lCGXFvkgxIfilWYoISojlqwPXufhoTc4'
Realm.Sync.User.authenticate(
  'https://ugodev.us1.cloud.realm.io',
  'jwt',
  {token: token},
).then(user => {
  console.log(user);
}).catch(err => {
  console.log('Error:',err)
})

```

Realm studio logs: 

`HTTP response: 2789e127-e254-4555-a757-a0c7d08c0f3f {"type":"https://realm.io/docs/object-server/problems/missing-parameters","title":"Your request did not validate because of missing parameters.","status":400,"code":602,"invalid_params":[{"name":"access token","reason":"Missing parameter 'access token'!"}]}`

JS Error
```
{
  name: 'AuthError',
  message: 'Your request did not validate because of missing parameters.',
  title: 'Your request did not validate because of missing parameters.',
  status: 400,
  code: 602,
  invalid_params:[ { name: 'access token', reason: 'Missing parameter \'access token\'!' } ] 
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.11.0
- Node or React Native: Node
- Client OS & Version: osx
- Which debugger for React Native: n/a

**Comment by nirinchev** [comment]
The [docs](https://docs.realm.io/platform/using-synced-realms/user-authentication/additional-providers#client-api) suggest using `registerWithProvider`:

```
Realm.Sync.User.registerWithProvider(
    'http://my.realm-auth-server.com:9080',
    'jwt',
    token,
    (error, user) => { /* ... */ });
```

**Comment by sambwest** [comment]
I don't want to register, I've already registered, I want to authenticate a user that is already registered. https://realm.io/docs/javascript/latest/api/Realm.Sync.User.html#authenticate

**Comment by nirinchev** [comment]
Despite the poor naming, `registerWithProvider` does just that - it creates the user if they didn't exist or logs them in if they did.

**Comment by sambwest** [comment]
Register with provider does seem to behave as you suggest but so should the authenticate method, no?

The testAuthenticateJWT() test here seems to pass:
https://github.com/realm/realm-js/blob/4cb9c77f46eac7f1e9320915ef9d89eb431af270/tests/js/user-tests.js

And the 2.2.0 release notes, seem to suggest that it should work. https://github.com/realm/realm-js/blob/d82c981386df0f397ffefca052f3a0a7972c834f/CHANGELOG.md
> [Sync] Added method Realm.Sync.User.authenticate to unify authentication of users.

But in my tests, on realm cloud it doesn't. I have updated my test to the registerWithProvider method you suggested and it does work in the same situation with the same parameters. Looks like a bug to me.

**Comment by nirinchev** [comment]
`authenticate` will work identically to `registerWithProvider` - it won't fail if the user didn't exist. But you're right that it should work, so there's certainly a bug - either in the test or the implementation of `authenticate`.

**Comment by sambwest** [comment]
ok, understood, thanks. I will use the registerWithProvier method for now.

**Comment by kneth** [comment]
I am closing the issue.

**Comment by sambwest** [comment]
@kneth Why did you close this? The issue remains. Even if it is just an alias for registerWithProvider it should still work according to the documentation. I'm trying to point these things out as I come across them to make it easier for the next guy who comes along.

I had a quick look at the code and the issue appears to be that the server expects the token to be in the json.data parameter not the json.token parameter. The change below brings it in line with the registerWithProvider method and fixes the issue in my tests. 

/node_modules/realm/lib/user-methods.js

```
authenticate(server, provider, options) {
            checkTypes(arguments, ['string', 'string', 'object'])
          

            var json = {}
            switch (provider.toLowerCase()) {
            case 'jwt':
                json.provider = 'jwt'
                // changing this fixes it
                //json.token = options.token;
                json.data = options.token;
                break
            case 'password':
                json.provider = 'password'
                json.user_info = { password: options.password }
                json.data = options.username
                break
            default:
                Object.assign(json, options)
                json.provider = provider
            }

            return _authenticate(this, server, json)
        },
```

**Comment by kneth** [comment]
@sambwest Sorry, I was too fast. But I would like to see us implementing #1579.

**Comment by sambwest** [comment]
2.16.0 eliminates this.
