### ISSUE TITLE
TypeError:undefined is not a function(evaluating'_realm2.default.open(databaseOptions)')

### ISSUE THREAD

**Issue by Adokiye** [realm/realm-js#1933]
I have a js file where I declared my schemas, the database options and functions that insert data, query data from the schema.

I am running the app on an android emulator, anytime I try to insert data it always comes back with this error `TypeError:undefined is not a function(evaluating'_realm2.default.open(databaseOptions)')` , can anyone please help, I've been stuck on it for days :(

**ALLSCHEMAS.JS**

    import Realm from 'realm';
    export const PERSON_SCHEMA = "Person";

    export const PersonSchema = {
    name: PERSON_SCHEMA,
    primaryKey: 'id',
    properties: {
        id: 'int',
        name: {type: 'string', indexed: true}
    }
    };
    const databaseOptions = {
    path: 'person.realm',
    schema: [PersonSchema],
    schemaVersion: 0
    };

    export const insertNewPerson = newPerson => new Promise((resolve, reject)=>{
    Realm.open(databaseOptions).then(realm => {
        realm.write(() => {
            realm.create(PERSON_SCHEMA, newPerson);
            resolve(newPerson);
        });
    }).catch((error) => reject(error));
    });
    export const queryAll = () => new Promise((resolve, reject) => {
    Realm.open(databaseOptions).then(realm => {
        let allPersons = realm.objects(PERSON_SCHEMA);
        resolve(allPersons);
    }).catch((error) => {
        reject(error);
    });
    });
    export default new Realm(databaseOptions);

**APP.JS**

    import React from 'react';
    import {StyleSheet, Text, View} from 'react-native';
    import {insertNewPerson, queryAll} from "./databases/allSchemas";
     export default class App extends React.Component {
      constructor(props) {
        super(props);
        this.state = {timePassed: false, value: '', realm: "books"};

      }

      render() {
        const newPerson = {
            id: Math.floor(Date.now() / 1000),
            name: this.state.realm
        };
        insertNewPerson(newPerson).then().catch((error) => {
            alert(error);
        });
        queryAll().then((value) => {
            this.setState({value});
        }).catch((error) => {
        })
        return (
            <View>
                <Text>
                    {this.state.value}
                </Text>
            </View>
        );
    }
    }

**Comment by nhachicha** [comment]
I managed to run your code, however, you'll encounter a Realm error since you'll be inserting the same object (with the same primary key) everytime you render (since on query completion you call set state which calls `render` which will insert the object again , which obviously fails.)

<img width="273" alt="screen shot 2018-07-23 at 17 29 25" src="https://user-images.githubusercontent.com/1793238/43090044-31e46234-8e9e-11e8-87da-1f0d74215a15.png">


<img width="872" alt="screen shot 2018-07-23 at 17 31 45" src="https://user-images.githubusercontent.com/1793238/43090084-50811a02-8e9e-11e8-8a69-89571c046ad4.png">

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
