### ISSUE TITLE
Failed to load 'http://<DEVICEIP>:8083/create_session',when i remote js debugging on android devices

### ISSUE THREAD

**Issue by kaikaifly** [realm/realm-js#1934]
- Realm JS SDK Version: ?
"realm": "^2.13.0"
- Node or React Native: ?
React Native
- Client OS & Version: ?
android
- Which debugger for React Native: ?/None
chrome

![_20180720191648](https://user-images.githubusercontent.com/14144514/42999929-368d8f70-8c52-11e8-8219-22570a77f1d2.png)
![_20180720191710](https://user-images.githubusercontent.com/14144514/42999936-3a97e700-8c52-11e8-9b15-5ffd2fefba8b.png)
![_20180720195108](https://user-images.githubusercontent.com/14144514/43001006-427cd9f4-8c56-11e8-8505-fd055682cfdb.png)

**Comment by nhachicha** [comment]
@kaikaifly looks similar to https://github.com/realm/realm-js/issues/1787#issuecomment-388573138 have you tried to open the Chrome debugger tool with `http://localhost:8081` instead of `http://127.0.0.1:8081`

**Comment by kaikaifly** [comment]
@nhachicha thank you
