### ISSUE TITLE
Provided schema version 1 is less than last set version 2

### ISSUE THREAD

**Issue by isaaclem** [realm/realm-js#1948]
## Goals

Trying to perform migration the right way

## Expected Results

Migration works seamlessly

## Actual Results

Provided schema version 1 is less than last set version 2

## Steps to Reproduce

**realm.js**

    'use strict';

    import Realm from 'realm';

    class Setting extends Realm.Object {}
    Setting.schema = {
      name: 'Setting',
      properties: {
        token: { type: 'string', default: '' },
        newlyAddedProperties: { type: 'string', default: '' },
      }
    };

    export default new Realm({
      schema: [ Setting ],
      schemaVersion: 2
    });

At first the `schemaVersion` was set to 1, and I added a new properties, so immediately I get `migration needed xxxx`. After some research, it seems that we need to bump `schemaVersion` by 1  whenever we change the properties, thats why I increase it to 2. And immediately the simulator that hitting this issue working fine.

However, some other simulator is hitting the issues as I mentioned above. How to really handle this migration?

## Version of Realm and Tooling

    "react": "^16.4.1",
    "react-native": "^0.56.0",
    "realm": "^2.14.0",
- Which debugger for React Native: None

**Comment by kneth** [comment]
It sounds like you have a place in your app where you open your Realm either without setting the schema version of setting it explicitly to 1.

**Comment by coderscode2** [comment]
I am facing the same issue and I don't have any place where I open with previous schema. 
I have open using schemas[schemas.length - 1]

Please help.

**Comment by coderscode2** [comment]
@kneth Can you please help with the above issue. Thanks
