### ISSUE TITLE
missing realm construct

### ISSUE THREAD

**Issue by shijinwu** [realm/realm-js#1954]
"react-native": "0.55.4",
"realm": "^2.14.2", or  "realm": "^2.2.20"
iOS simulator 
Missing Realm constructor. Did you run "react-native link realm"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting

**Comment by kneth** [comment]
Did you try all 6 suggestions for iOS?

**Comment by binbinla** [comment]
@kneth hello what is the latest version of realm?

**Comment by kneth** [comment]
It's 2.14.2.

**Comment by jonfelske** [comment]
@shijinwu any luck finding a fix/workaround?  I'm getting the same error.  
---
"react": "16.4.1",
 "react-native": "0.56.0",
"realm": "2.15.3",
---
iOS simulator
node: 9.10.0

**Comment by stefanwuest** [comment]
Experiencing the same error after updating to the latest React Native Version (0.57.1)
I have tried:
- Troubleshooting steps, as suggested in the documentation, (+ removing DerivedData, etc.)
- Removing and re-installing realm
- Tried different versions of realm (1.10.0, 2.16.0, 2.17.0)

iOS Simulator
node: 9.3.0

Any updates on this? I'd really appreciate any hints to find a solution.

**Comment by magnusburton** [comment]
With the new version of Realm (2.19.0) I tried installing Realm and got the `Missing Realm constructor` error.

**Comment by mingxin-yang** [comment]
+1
realm:2.29.1
react-native:0.59.10,
android is ok, the error appear on ios

**Comment by kneth** [comment]
@magnusburton @mingxin-yang Did you upgrade from a previous version? If so, try to clear the temp. build area first.

**Comment by mingxin-yang** [comment]
> @magnusburton @mingxin-yang Did you upgrade from a previous version? If so, try to clear the temp. build area first.

sorry,I had fixed it, I forget that import libs to my IOS project.
