### ISSUE TITLE
Support custom SSL for auth methods

### ISSUE THREAD

**Issue by ironage** [realm/realm-js#1971]
## Goals

I want to login and authenticate against a server which has a custom SSL certificate and verify it myself. But I don't see a way to set the [configuration](https://realm.io/docs/javascript/latest/api/Realm.Sync.html#~SSLConfiguration) for these parts of the API.
`Realm.Sync.User.login('https://localhost:9443', 'u', 'pw')`

The method works against `http://localhost:9080` but I don't want to send passwords over http.

## Actual Results

`FetchError: request to https://localhost:9443/auth failed, reason: unable to get local issuer certificate`

## Steps to Reproduce

Start a local ROS instance with a self signed certificate, and try to login with https.

## Version of Realm and Tooling

- Realm JS SDK Version: realm@2.14.0
- Node or React Native: both

**Comment by ianpward** [comment]
@roberhofer I need this prioritized for the next sprint per @fealebenpae work on this

**Comment by roberhofer** [comment]
@fealebenpae : Can you confirm whether this is done via the SSL work that you have done? E.g. can we close this? (another issue has a dependency on this, therefore checking)

**Comment by nirinchev** [comment]
No, this is client-side feature, unrelated to the SSL work done on the server.
