### ISSUE TITLE
Realm queries randomly returning null during unit tests.

### ISSUE THREAD

**Issue by abury** [realm/realm-js#1972]
We're running into some big issues trying to write tests for realm object serialisation. This pattern seems to work flawlessly in the simulator and on the device, but in tests it's not reliable. We've tried passing `inMemory: true` to the realm config and still no dice.

## Goals

Reliably test Realm serialisation using Jest

## Expected Results

A realm query consistently returns the same result.

## Actual Results

Realm randomly returns null for a query that should have data. (Happens more often on some machines than others).

We've written this code based on the example app. We've been trying for a day to crack this but we just cannot figure it out. It fails every second time on our CI and 1/10 times on our dev machines.

## Steps to Reproduce

N/a

## Code Sample

realm.js
```javascript
import Realm from 'realm';
import schema from './schema';

const realmConfig = {
  schema: schema,
  deleteRealmIfMigrationNeeded: true
}

export default new Realm(realmConfig);
```
accountManage.js
```javascript
import realm from '@/models/realm';

import Account from '@/models/schema/Account';

export function saveAccounts(accountsData) {
  return new Promise((success, failure) => {
    try {
      realm.write(() => {
        const accounts = accountsData.
          map(accountData => realm.create('Account', Account.mapping(accountData), true))
        success(accounts)
      })
    } catch (e) {
      failure(e)
    }
  })
}

```

Account.js
```javascript
import Realm from 'realm'
import realm from '@/models/realm'
import Currency from './Currency'
import Balance from './Balance'
import { currentUser } from '@/managers/model/userManager'

class Account {}

Account.schema = {
  name: 'Account',
  primaryKey: 'uuid',
  properties: {
    uuid: 'string?',
    currency: 'Currency',
    type: 'string?'
  }
}

Account.mapping = function(data) {
  const isoCode = data['currency'];
const query = `isoCode = "${isoCode}"`;
  const currency = realm.objects('Currency').filtered(query)[0]; <--- This randomly returns null ONLY during unit tests on some machines, specifically our CI
  return {
    'uuid': data['uuid'],
    'currency': currency,
    'type': data['type']
  }
}

export default Account
```

accountsManager.spec.js
```javascript
import realm from '@/models/realm'
import { deleteAllData } from '@/models/realmUtils'
import { saveAccounts } from '../accountManager'
import accountsStub from '@/stubs/Accounts/get-accounts-success'

afterAll(() => {
  deleteAllData()
});

describe('Save Accounts', () => {
  beforeAll(() => {
    realm.write(() => {
      realm.create('Currency', {
        name: 'Australian Dollar',
        isoCode: 'AUD',
      } , true)
    realm.create('Currency', {
      name: 'Great Britain Pound',
      isoCode: 'GBP',
    } , true)
    });
  });

  test('it creates the right amount of accounts', () => {
    expect.assertions(1);
    return saveAccounts(accountsStub.accounts).then(accounts => {
      expect(accounts.length).toBe(4);
    });
  });

  test('it seralizes the accounts correctly', () => {
    expect.assertions(2);
    return saveAccounts(accountsStub.accounts).then(accounts => {
      const account = accounts[0]
      expect(account.uuid).toBe('439fad52-3138-4fda-808f-36a880a67f20');
      expect(account.currency.name).toBe('Australian Dollar') <--- This assertion inconsistently fails
    });
  });
})

```

## Version of Realm and Tooling

- React 16.4.1
- React Native 0.56.0
- Realm: 2.13.0
- Node: 9.11.2
- Jest: 23.5.0
- Client OS & Version: Mac OSX: 10.13.6
- Which debugger for React Native: None

Any thoughts?

**Comment by ironage** [comment]
Hi @abury I suspect it is a scoping problem, can you try something along these lines

```

export function saveAccounts(accountsData) {
    return new Promise((success, failure) => {
        try {
            let accounts;
            realm.write(() => {
                accounts = accountsData.map(accountData => Account.createNew(accountData, realm))
            })
            success(accounts)
        } catch (e) {
            failure(e)
        }
    })
}

Account.createNew = function (data, writeableRealm) {
    const isoCode = data['currency'];
    const query = `isoCode = "${isoCode}"`;
    console.log('total currency objects: ' + writeableRealm.objects('Currency').length);
    const currency = writeableRealm.objects('Currency').filtered(query)[0];
    console.log('currency query returns: ' + JSON.stringify(currency));
    let createdAccount = writeableRealm.create('Account', {
        'uuid': data['uuid'],
        'currency': currency,
        'type': data['type']
    }, true);
    console.log('created account: ' + JSON.stringify(createdAccount));
}
```
I haven't actually run the code, so there may be syntax errors in that. But please try it out and see if it works for you. If not, please send the output of the console logs, and we will dig a bit deeper.

**Comment by abury** [comment]
Thanks for the reply @ironage, I also realized that our beforeAll block is not returning a promise or done, so I suspect that's causing the main issue, but I'll give that a go today 👍

**Comment by abury** [comment]
@ironage, Well, that's odd. I've made that change and, without the logs, the test passes on my machine, but when logging it out the test fails due to: `RangeError: Maximum call stack size exceeded`. Here's the log output:

```bash
  console.log project/models/schema/Account.js:31
      total currency objects: 2
    console.log project/models/schema/Account.js:33
      currency query returns: {"name":"Australian Dollar","isoCode":"AUD""accounts":{}}
    console.log project/models/schema/Account.js:31
      total currency objects: 2
    console.log project/models/schema/Account.js:33
      currency query returns: undefined
    console.log project/models/schema/Account.js:31
      total currency objects: 2
```

Why would logging out this data cause an infinite loop? And why is it undefined the 2nd time around?

**Comment by abury** [comment]
@ironage Looks like `JSON.stringify` was causing the recursion issue. I've removed it and it's acting as expected. On my machine. The CI is undergoing maintenance at the moment so I can't test to see if the updates have resolved the issue on CI, but I suspect they should be resolved now 🤞, just have to wait until tomorrow before I can test. I'll let you know how we go.

A question on the way we're using realm. We noticed that within the documentation, `open` and `close` is used extensively, however in the example code this doesn't seem to be used. The API for opening/closing realms makes things quite verbose and we're looking to keep the code clean if possible. What are the advantages of using open vs how we're doing it?

Thanks!

**Comment by ironage** [comment]
From the snippets that you've sent, it looks just fine the way you are using it. Normally you'd only need to close the realm if you want to open it again with different config or schema.

**Comment by abury** [comment]
Hi @ironage, doesn't look like that worked. The CI is still failing the test and after putting those logs in show 0 currency objects.

Do you know what would be causing this at all? I'm really keen to use realm but we can't confidently use it if it randomly fails like this on a CI. If you have any potential ideas on what could be causing this, it would be really, really helpful.

**Comment by ironage** [comment]
Can you send the updated code, and the console logs? Make sure that `success(accounts)` from `saveAccounts` is outside of the write block, otherwise it will return before committing the write transaction. Did you find out if you need to return something from `beforeAll`?
One other thing to check is if your CI is running the test at the same path or in an isolated environment. Since you don't specify a file name for the realm in the config, it is assigned a default name which will be shared if the test is run from the same location again; this could cause a race condition because of the `deleteAll` if testing is run concurrently.

**Comment by mxs** [comment]
Hi @ironage,

I work with @abury and you are spot on regarding the race condition, since Jest tests are ran in parallel. It was another test's `afterAll()` hook which was deleting from realm before the `realm.objects()` was called in the failing test

Thanks a whole bunch for pointing this out!

**Comment by ironage** [comment]
Great news - glad we could get this sorted out!

**Comment by abury** [comment]
Thanks @ironage! As @mxs we were able to just add `-- runInBand` to jest and it's now passing across the board, so it was more a jest issue than realm 👍
