### ISSUE TITLE
Realm.Sync.User.login fails

### ISSUE THREAD

**Issue by jigajames** [realm/realm-js#1977]
## Goals

Logging into realm fails

## Actual Results

On version 2.11.0 -> 2.14.2 the following code fails but returns correctly on 2.10.0

```
await Realm.Sync.User.login('https://rentro.***.realm.io', '***', '***')
```

```
ExceptionsManager.js:84 Unhandled promise rejection TypeError: Cannot set property identity of #<User> which has only a getter
    at assign (_object-assign.js:32)
    at _extends (user.js:24)
    at createUser (user.js:64)
    at deserialize (rpc.js:160)
    at createUser (rpc.js:71)
    at Function.createUser (user.js:28)
    at user-methods.js:264
    at run (es6.promise.js:66)
    at es6.promise.js:83
    at flush (_microtask.js:18)
```

And on the version 2.10.0 I get a segfault when subscribing for sync. 

## Version of Realm and Tooling

ream-js 2.11.0 - 2.14.2

**Comment by jigajames** [comment]
The segfault on 2.10.0 was caused by not providing schemas to user.createConfiguration

**Comment by kneth** [comment]
@jigajames It is actually the same as #1976. The plan is to add a check, and throw an exception when you try to open without a schema.
