### ISSUE TITLE
createConfiguration could use the path in the sync url

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1981]
## Goals

When using `createConfiguration` to create a configuration that syncs to something else than the `/default` Realm it would be nice if the user had a way to specify the path of the Realm on the server.

## Expected Results

Either the `config.path` could be appended to the server URL or perhaps a second string argument to the method.

## Actual Results

Calling `createConfiguration` on a user always returns a configuration object with the `/default` path.

## Steps to Reproduce

1. Authenticate a user
2. Call `user.createConfiguration({ path: "whatever" })`, log the result and observe that it has `/default` as the realm path of the `sync.url`.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.2
- Node or React Native: Node
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by nirinchev** [comment]
I believe `path` is the local Realm path. If you want to modify the url, you should do it by specifying `sync.url`:
```ts
user.createConfiguration({
  sync: {
    url: "realm://foobar.cloud.realm.io/whatever"
  }
});
```

I haven't tested if it works though :)

**Comment by kraenhansen** [comment]
Yeah - but as the main reason for the `createConfiguration` is to translate the server URL on the user into a `sync.url` an override like that is pretty pointless :) In that case, I would just create the configuration manually.

The `path` is for local realms as is, but one of my two suggestions is to change that to specify the path on the server if we're using `createConfiguration` - as the local path is ignored when opening a synced realm anyway.

**Comment by kraenhansen** [comment]
Ahh okay - it seems as it that was actually fixed: https://github.com/realm/realm-js/issues/1392 ... I just wasn't aware of that.

**Comment by kraenhansen** [comment]
Anyway - this issue is still relevant.

I suggest that `createConfiguration` takes a second optional string argument which is the virtual path of the Realm that will be synced against, which defaults to `"/default"`.

**Comment by nirinchev** [comment]
I think that would be very weird API as you'll have two ways of specifying the same thing. I would rather handle relative urls in the `sync` object:

```ts
user.createConfiguration({
  sync: {
    url: "/whatever"
  }
});
```

We can easily detect that and concatenate with the user url.

**Comment by kraenhansen** [comment]
@nirinchev that would be fine by me too.

**Comment by kraenhansen** [comment]
I just had a need for this again today :) Glad to see it's in active progress.
