### ISSUE TITLE
Realm and Proxy support

### ISSUE THREAD

**Issue by abury** [realm/realm-js#1982]
## Goals
Learn minimum supported versions for realm

Hey Realm team. 👋

We've noticed that RealmJS seems to use Proxy objects under the hood. As we understand it, Proxies are only supported on iOS 10.0 and up (and I assume Android support might be all over the place)

Does this mean that Realm is only supported on iOS 10 and up? I haven't seen any minimum version specified in Realms documentation, but we wanted to check with you.

Thanks!

Aron

**Comment by fealebenpae** [comment]
Realm only uses the Proxy API when running inside the Chrome debugger. When running on device the JavaScriptCore C API is used to expose the Realm API in JavaScript instead.

**Comment by kneth** [comment]
Realm is managing the objects, and this might look like a proxy. We try our best to get these managed object to behave like ordinary JavaScript objects 😎 . But a managed object is not a JavaScript `Proxy` object. As @fealebenpae points out, `Proxy` objects are only used when debugging.
