### ISSUE TITLE
realm: Failed to execute 'node-gyp.cmd build --fallback-to-build --module

### ISSUE THREAD

**Issue by abrarum** [realm/realm-js#1983]
I've installed Realm with ccxt api in react native app. "npm install" command is throwing exception:

`realm: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\react_native\project\cryp
error F:\react_native\project\cryptoapp\node_modules\realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: F:\react_native\project\cryptoapp\node_modules\realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.6.0 | win32 | x64
node-pre-gyp info check checked for "F:\react_native\project\cryptoapp\node_modules\realm\compiled\node-v64_win32_x64\realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.14.2/realm-v2.14.2-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.14.2/realm-v2.14.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/2.14.2/realm-v2.14.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.14.2 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.14.2/realm-v2.14.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/2.14.2/realm-v2.14.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@2.14.2 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\react_native\\project\\cryptoapp\\node_modules\\realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Abrar Ahmed\\.node-gyp\\10.6.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\react_native\\project\\cryptoapp\\node_modules\\realm',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\publish.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
F:\react_native\project\cryptoapp\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\test.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\set-version.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\changelog-header.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
Warning: Missing input files:
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\publish.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
F:\react_native\project\cryptoapp\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\test.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\set-version.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\scripts\changelog-header.sh
F:\react_native\project\cryptoapp\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.6.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\OpenSSL.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\OpenSSL.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\scripts.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\scripts.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\vendored-realm.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [F:\react_native\project\cryptoapp\node_modules\realm\build\vendored-realm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Abrar Ahmed\AppData\Local\Yarn\config\global\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Abrar Ahmed\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\compiled\\node-v64_win32_x64\\realm.node" "--module_name=realm" "--module_path=F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\compiled\\node-v64_win32_x64"
gyp ERR! cwd F:\react_native\project\cryptoapp\node_modules\realm
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Abrar Ahmed\AppData\Local\Yarn\config\global\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Abrar Ahmed\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "C:\\Users\\Abrar Ahmed\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\compiled\\node-v64_win32_x64\\realm.node" "--module_name=realm" "--module_path=F:\\react_native\\project\\cryptoapp\\node_modules\\realm\\compiled\\node-v64_win32_x64"
gyp ERR! cwd F:\react_native\project\cryptoapp\node_modules\realm
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\react_native\project\cryptoapp\node_modules\realm\compiled\node-v64_win32_x64\realm.node --module_name=realm --module_path=F:\react_native\project\cryptoapp\node_modules\realm\compiled\node-v64_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\react_native\project\cryptoapp\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Users\\Abrar Ahmed\\AppData\\Roaming\\npm\\node_modules\\node\\bin\\node.exe" "F:\\react_native\\project\\cryptoapp\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\react_native\project\cryptoapp\node_modules\realm
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok`

## Goals

I want to rebuild node_modules by "npm install"

## Expected Results

Expected that the modules will be re-installed in the node_modules folder.

## Actual Results

Instead it throws error mentioned above.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.13
- Node or React Native: 10.6.0 / 0.55.4
- Client OS & Version: Windows / 10
- Which debugger for React Native: Console cmd

**Comment by BINAIMENG** [comment]
You need to drop the node version 8.

**Comment by kneth** [comment]
Yes, we don't support node 10 yet. See also #1813.
