### ISSUE TITLE
Android: Warning after user authentication

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1986]
## Goals

Installing Realm JS into a React Native app should not yield warnings.

## Expected Results

No warnings after user authentication.

## Actual Results

After authenticating Realm JS registers a timer to refresh the token, but this will yield a warning:

> Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.

![screenshot_1535043782](https://user-images.githubusercontent.com/1243959/44540475-31fbdf00-a707-11e8-9652-14a5d7123419.png)

Note: This warning can be suppressed by users with

```
console.ignoredYellowBox = ['Setting a timer'];
```

See https://github.com/facebook/react-native/issues/12981#issuecomment-302059217

## Steps to Reproduce

1. Create a React Native app,
2. Add Realm JS,
3. Register or authenticate a user,
4. Observe the warning

## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.2
- Node or React Native: 0.56.0
- Client OS & Version: Android
- Which debugger for React Native: N/A

**Comment by kneth** [comment]
Will https://github.com/realm/realm-js/pull/2071 help in this situation?
