### ISSUE TITLE
Deprecation warning from ./gradlew: Task.leftShift(Closure) method has been deprecated

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1995]
## Goals

Running `./gradlew` in an app using Realm without deprecation warnings.

## Expected Results

No warnings when running `./gradlew`

## Actual Results

After following https://realm.io/docs/javascript/latest/ I get this warning as the first line when running any `./gradlew` command:

```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_d9y9ztx4qpkqkvbhyukdt2t0y.run(/Users/.../node_modules/realm/android/build.gradle:77)
```

## Steps to Reproduce

1. Follow the instructions on initializing a React Native app with Realm JS: https://realm.io/docs/javascript/latest/
2. Change directory into `android` and run any `./gradlew` command.

## Version of Realm and Tooling

- Gradle: 3.5.1
- Groovy: 2.4.10
- Ant: Apache Ant(TM) version 1.9.6 compiled on June 29 2015
- JVM: 1.8.0_144 (Oracle Corporation 25.144-b01)
- Realm JS SDK Version: 2.15.3
- Node or React Native: React Native 0.56.0
- Client OS & Version: Mac OS X 10.13.6 x86_64
- Which debugger for React Native: N/A

**Comment by jaggs6** [comment]
Any update on this issue now that Gradle 5.0 has been launched. Its a breaking the 5.0 gradle builds.

**Comment by naviet2308** [comment]
<img width="752" alt="screen shot 2018-11-30 at 23 46 42" src="https://user-images.githubusercontent.com/8268750/49302722-73680b80-f4fa-11e8-9983-7676f479b181.png">
Help me please.

**Comment by cmelchior** [comment]
A quick fix should be to replace

```
task buildReactNdkLib(dependsOn: [downloadJSCHeaders,prepareRealmCore,prepareOpenSSL_x86,prepareOpenSSL_arm], type: Exec) {
    inputs.file('src/main/jni')
    outputs.dir("$buildDir/realm-react-ndk/all")
```

with 

```
task buildReactNdkLib(dependsOn: [downloadJSCHeaders,prepareRealmCore,prepareOpenSSL_x86,prepareOpenSSL_arm], type: Exec) {
    inputs.files('src/main/jni')
    outputs.dir("$buildDir/realm-react-ndk/all")
```

in `node_modules/realm/react-native/android/build.gradle`

I'm working on a proper PR and fix.
