### ISSUE TITLE
Realm.Results.map is not a function?

### ISSUE THREAD

**Issue by pedrosimao** [realm/realm-js#2001]
## Goals
I did query a Realm collection

## Expected Results
I expect to be able to execute `.map()` or `.forEach()` methods on Realm results.

## Actual Results
When I console.log() the realm results I see well that the type of the object is a result.
But when I do try to execute `.map()` method on it I get the following error:
`TypeError: schedules.map is not a function`

## Code Sample
```
let selected = realm.objects('SchemaName');
selected.map(selection => .... )
```

## Version of Realm and Tooling
* Realm JS SDK Version: ?
2.15.3
* Node or React Native: ?
RN: 0.56.0
* Client OS & Version: ?
Mac OSx

**Comment by pedrosimao** [comment]
Given that I have found a solution I will close the issue.
But developers should really think about include some modern Javascript methods on Realm.objects and Realm.results.
RealmJS should follow the tendencies of modern javascript syntax... Also this kind of operations could be better documented.

**Comment by nirinchev** [comment]
@kneth is this a RN bug? I am fairly certain we've used `.map` with node apps.

**Comment by nirinchev** [comment]
Yes, let's check it out.

**Comment by pedrosimao** [comment]
Quick update, it seems on React Native it is possible to use .map or .forEach methods like this:
`Object.keys(object).forEach((key) => ... do something with key ) `
Chaining the method directly on the object like `object.forEach(key => ...)` will cause the error described.
I am not sure it is supposed to be like that. If it is the case it would be great to see that in the docs.

**Comment by kneth** [comment]
I think it is related to https://medium.com/@jordan_mohi/cant-find-variable-symbol-in-react-native-782489d86bd7

**Comment by Udbhav12** [comment]
I am facing this exact issue in RN 0.58.6 and above

**Comment by febeling** [comment]
Confirming this problem for react-native@0.55.3

**Comment by febeling** [comment]
Also see this with Realm.List, not just Realm.Results.

**Comment by Rob117** [comment]
Just to be clear, this is still an issue. When you search for realm node foreach, this comes up on the first page.

If you check all the methods that should be available on the object  using (taken from SO)
```Javascript
    const getMethods = obj => {
      let properties = new Set();
      let currentObj = obj;
      do {
        Object.getOwnPropertyNames(currentObj).map(item => properties.add(item));
      } while ((currentObj = Object.getPrototypeOf(currentObj)));
      return [...properties.keys()].filter(item => typeof obj[item] === 'function');
    };

  console.log(getMethods(resultsObject));
```

This will tell you that forEach _should_ be on that object, but trying to actually call it returns not a function

**Comment by davidleee** [comment]
We've spotted the same error on our Electron app.

I know Realm is not currently support Electron, but maybe this is not an RN-only issue?

**Comment by kneth** [comment]
It can be related to #1096.

**Comment by kneth** [comment]
We believe this is fixed by v12. Please reopen or create a new issue if it is still a problem.
