### ISSUE TITLE
Error only when debugger is not connected

### ISSUE THREAD

**Issue by pedrosimao** [realm/realm-js#2004]
## Goals

I am trying to delete Realm objects. It works perfectly when I am debugging JS remotely, but something goes wrong on release version or device version without remote debugger. I get this error message on Xcode:
`Error: Argument to 'delete' must be a Realm object or a collection of Realm objects.`

## Expected Results

Realm to delete the object normally, like it does when I have remote debugger connected.

## Actual Results

My app freezes or the deletion simply doesn't happen.
I think the problem actually happen when I try to select my device by id, because when I use await before calling the object my app freezes.

## Code Sample

```
let selected = realm.objectForPrimaryKey('SchemaName', id); // (where id equals an integer number)
realm.delete(selected);
```

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.15.3
- Node or React Native: ? 0.56.0
- Client OS & Version: ? Mac OSX
- Which debugger for React Native: ? react native debugger

**Comment by pedrosimao** [comment]
I have also tested the realm object via console.log(realmObject.property) and it displays the property content perfectly, which proves the `realm.objectForPrimaryKey('SchemaName', id)` is working without a problem. It is the delete function that fails to recognize a realm object.

**Comment by pedrosimao** [comment]
Ok, I found the culprit. 
I was using spread operator when returning the object.
For some reason iPad environment didn't like it.
I will close the issue.

**Comment by nirinchev** [comment]
I'm confused - in the snippet you posted, there's no spread operator.

**Comment by pedrosimao** [comment]
@nirinchev Yes, I know. I was using an external personal library full of realm methods, and I tried to simplify things for this post. I didn't include the spread operator here. But it was the problem. I have seen someone else here on github using spread operator to return Realm objects, so I did the same thinking it was a good practice. Well... it is not.

**Comment by nirinchev** [comment]
Gotcha. Maybe if you post the snippet with the spread operator I can try to shed some light on why it was not working. But in any case, I'm glad you were able to figure it out!
