### ISSUE TITLE
Wrong typescript definition for Realm.Permissions.User

### ISSUE THREAD

**Issue by apperside** [realm/realm-js#2012]
The type definition for the type `Realm.Permissions.User` is as follows:

```
class User {
        static schema: ObjectSchema;
        identity: string;
    }
```
The `identity` field I think is wrong because in realm studio the table contains an `id` field instead

## Version of Realm and Tooling

- Realm JS SDK Version: 2.15.3

**Comment by kneth** [comment]
Good catch. It is `Realm.User.identity` but `Realm.Permissions.User.id`.

**Comment by apperside** [comment]
@kneth  I made a pull request to fix it
