### ISSUE TITLE
Realm compaction can have a callback or promise resolution

### ISSUE THREAD

**Issue by Louies89** [realm/realm-js#2021]
Hi @kneth ,
As per the [documentation ](https://realm.io/docs/javascript/2.15.0/api/Realm.html#compact), the compact() method returns boolean result indicating  compaction success or failure.

1>> What I think is, if it shall able to callback or as it is an async process, it should return a promise, the application can show some "Please wait" message to user, during compaction.

In addition to this, if percentage of compaction done also can be send back, that can be even more better.

2>> I am trying to implement compaction in below way:
```
import Realm from 'realm';
const SchemaOptions = {
	path: 'Db1',
	schema: [ExamleSchema1],
	schemaVersion: 1,
	shouldCompactOnLaunch: (totalBytes,usedBytes)=>{
		compactDb('Db1', totalBytes, usedBytes);
		return false
	}
}

const SchemaOptions = {
	path: 'Db2',
	schema: [ExamleSchema1],
	schemaVersion: 1,
	shouldCompactOnLaunch: (totalBytes,usedBytes)=>{
		compactDb('Db2', totalBytes, usedBytes);
		return false
	}
}

function compactDb(db, totalBytes, usedBytes){
   if(totalBytes && usedBytes){
     let TwentyMB = 20 * 1024 * 1024
     if((totalBytes > TwentyMB ) && (Double(usedBytes) / Double(totalBytes)) < 0.5){

         Realm.compact();  <<--- Not sure about this line of code 
      }
  }
}
```
Will this code work and mainly Realm.compact() ?
Actually how to start compaction on different db schema I am not understanding.

**Comment by nirinchev** [comment]
You should not manually call `compact()` when using `shouldCompactOnLaunch` - instead you should return `true` if you want the database compacted and `false`, if you do not.

Regarding your other questions - `compact()` is not an asynchronous method, which is why it doesn't return a promise - it executes the work on the calling thread. Similarly, we don't currently offer a callback to report the compact progress. While I can see the value of such functionality, I'm not sure how easy it will be to add.

**Comment by Louies89** [comment]
OK will please let me know how to call compact() with config options, so that, suppose in shouldCompactOnLaunch , I will get the value of totalbytes and usedbytes, and keep it somewhere.

And will start comapction when the app is in background or not in use or use some alarm to start compaction.

**Comment by yuanyinchun** [comment]
@Louies89  here is an exapmle code to call compact(), make sure Realm Studio dose not open the same realm file when run compact, otherwise compact() will return false.

`const Realm = require('realm');

const YOUR_MODEL = {
    name: 'NAME',
    properties: {
        id: 'string',
        title:  'string'
    }
};

Realm.open({schema: [YOUR_MODEL], path: './realm.realm'})
    .then(realm => {
        let result = realm.compact();
        console.log(result); // result should be true
    })
    .catch(error => {
        console.log(error);
    });`

**Comment by Louies89** [comment]
Its so simple, I was thinking, no need of opening of realm and it will do it automatically.

Thank you for the reply.

Closing the issue, if required, this can be opened in future.
