### ISSUE TITLE
RealmStudio won't run

### ISSUE THREAD

**Issue by kwbskf** [realm/realm-js#2023]
## Goals

Install RealmStudio for Windows and run it on Windows 7.

## Expected Results

That it would run.

## Actual Results

Error dialog:
![image](https://user-images.githubusercontent.com/40439595/45577816-3d8c8280-b83b-11e8-8f42-2a2b393ba389.png)

## Steps to Reproduce

Download RealmStudio installer "Realm Studio Setup 2.8.0.exe", run it on Windows 7 (error occurs when installer tries to launch it and afterwards if it is launched from Start menu).

## Version of Realm and Tooling

- Client OS & Version: ? Windows 7 Enterprise SP 1 64-bit

**Comment by nirinchev** [comment]
Studio only supports windows 8.1 or higher.
