### ISSUE TITLE
Unable to find a matching configuration of project :realm: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by Amir-M7** [realm/realm-js#2041]
[##]([url](url
<img width="869" alt="screen shot 2018-09-24 at 4 07 03 pm" src="https://user-images.githubusercontent.com/17439071/45952440-e8f3bf00-c013-11e8-8fce-6490ee61495f.png">
)) Steps to Reproduce
when i want to run project with  react-native run-android shod this error in terminal : 
Unable to find a matching configuration of project :realm: None of the consumable configurations have attributes.
and then build failed

## Version of Realm and Tooling

- Realm JS SDK Version: ? 3.7
- Node or React Native: ? 0.55.4
- Client OS & Version: ? macOS
- Which debugger for React Native: ?/None

**Comment by rayjadore** [comment]
another possible probelm could be that realm was not install, so try installing it seperately if it doesnt install use nvm to change the version of node possibly v9 and try install it again

**Comment by Mohit-gwg** [comment]
Hello everyone, I am facing this same error which is listed above, I tried everyone suggested solutions but it didn't work in my case, 
error: 
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :realm.
     Required by:
         project :app
      > Unable to find a matching configuration of project :realm:
          - None of the consumable configurations have attributes.
