### ISSUE TITLE
Realm.Sync.setLogLevel is not a function in Debugger

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#2049]
## Goals

Set the log level. Seems to work fine without using Remove Debugging. 

## Expected Results

The log level is set

## Actual Results

Realm.Sync.setLogLevel is not a function

## Steps to Reproduce

`Realm.Sync.setLogLevel('trace')`

## Code Sample

`Realm.Sync.setLogLevel('trace')`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.16.3
- Node or React Native: RN
- Client OS & Version: ?
- Which debugger for React Native: Chrome

**Comment by kneth** [comment]
With v2.27.0 we open sourced many methods - including `Realm.Sync.setLogLevel()` - and I expect it to work now. Please reopen it is doesn't.
