### ISSUE TITLE
Subscription enhancements request

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2052]
To provide a nicer subscribe/unsubscribe API in the GraphQL service, we need the following enhancements to the subscription functionality in realm-js:

- [ ] Ability to unsubscribe by name. There should be no reason to subscribe to something only to later unsubscribe. 
- [ ] Ability to list all active subscriptions. We already have that information in the partial Realm, so there should be no reason not to expose it. I need just the name and the query and not a reference to the subscription instances or anything like that. 
- [ ] A nicer wrapper around waiting for subscription - something like:

```js
return new Promise((resolve, reject) => {
  const listener = (__, state) => {
    switch (state) {
      case Realm.Sync.SubscriptionState.Complete:
        subscription.removeListener(listener);
        resolve();
        break;
      case Realm.Sync.SubscriptionState.Error:
        subscription.removeListener(listener);
        reject(subscription.error);
        break;
    }
  };
  subscription.addListener(listener);
});
```

**Comment by cmelchior** [comment]
> Ability to list all active subscriptions. We already have that information in the partial Realm, so there should be no reason not to expose it. I need just the name and the query and not a reference to the subscription instances or anything like that.

IMO we should just expose the `__ResultSet` as a `Subscription`. I suspect that trying to do anything else is going to bite us later.

**Comment by nirinchev** [comment]
I'm not against that, but if we decide to do that, we should enhance the `Subscription` interface and add properties for the name and the serialized query. Otherwise it's fairly useless to get a list of these.

**Comment by cmelchior** [comment]
Yup. For bindings that support the text-based parser, they could also enable directly returning the `Results` object.

Java is currently a bit hampered in that regard, but just exposing a text-based description + name seems fine for a first iteration.
