### ISSUE TITLE
constructor must be of type 'function' on debugger mode

### ISSUE THREAD

**Issue by mistikk** [realm/realm-js#2053]
## Goals

It is working as well without debugger mode. But on debugger mode, we are getting error when try to create Realm object with schema parameters.

## Expected Results

It should work like without debugger

## Actual Results

![image](https://user-images.githubusercontent.com/8211075/46572411-43194c00-c953-11e8-8020-905983854a5c.png)

![image](https://user-images.githubusercontent.com/8211075/46572432-8d023200-c953-11e8-96a6-23a5b8da1fa9.png)

## Code Sample

![image](https://user-images.githubusercontent.com/8211075/46572461-deaabc80-c953-11e8-90e7-02c8e2e22ef8.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 2.17.0
- React Native: 0.57.1
- Client OS: Android
- Which debugger for React Native: Chrome

**Comment by sivagao** [comment]
always consume lots of time to debug realm related. think to abort this repo

**Comment by ithustle** [comment]
+1

**Comment by NaveenJayaram94** [comment]
+1 . How to fix this. Previously its working fine. I updated mu OS. startted getting this error. Please help

![screenshot_20181011-175639](https://user-images.githubusercontent.com/9761921/46804064-5a0ad480-cd7f-11e8-8a07-71bf08fb1973.png)

**Comment by ithustle** [comment]
Version 2.16.0 its working fine on RN 0.57.2

**Comment by bmunkholm** [comment]
@NaveenJayaram94 You upgraded from which OS to which OS?

**Comment by ithustle** [comment]
Actually, I've downgraded to 2.16.0. I did it yesterday. I was suffering about last 2 weeks because of this. I'm working on two differents machines. Win and MacOS. (10 and High Sierra)

**Comment by NaveenJayaram94** [comment]
I downgraded from Ubuntu 18.10 to 17.10.
Yesterday in 18.10 its working fine, today downgraded my is, in first compile only its throwing this error. I don't know what to do

**Comment by jgplane** [comment]
Happening to me too. I haven't updated my OS or realm version. Not sure this is related, but the error started popping up after I ran these commands:
```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by NaveenJayaram94** [comment]
but its work well without debugging, but without chrome debugging its very difficult develop RN App. Searching for other mobile NoSql DB.

**Comment by bmunkholm** [comment]
@NaveenJayaram94 Have you tried to use Safari on Mac? Others have great experience with that instead of Chrome.

**Comment by NaveenJayaram94** [comment]
@bmunkholm , I use Ubuntu 17.10. so only option left is the firefox browser. tomorrow .I'll test it tomorrow and I'll update. thanks

**Comment by figure-ai** [comment]
+1111

**Comment by NaveenJayaram94** [comment]
@bmunkholm even in firefox same error. searching for alternatives with NoSQL and real time database.

**Comment by mistikk** [comment]
It is related from last version of realm(v2.18.0). You should downgrade to 2.16.0.
And dont forgot to check version number on package.json. It should be "realm": "2.16.0" not "realm": "ˆ2.16.0". I lost 1 day for that :(

After that, run this code for reset all packages;
`watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache`

**Comment by NaveenJayaram94** [comment]
@mistikk Thanks budy. You saved me from disaster

**Comment by JackHull** [comment]
+1 on react-native for 2.18.0

**Comment by sinhpn92** [comment]
I have same issue in v2.18.0. Downgrade to v2.17.0 is solve.

**Comment by JackHull** [comment]
Got it fixed by upgrading to 2.19.0-rc.4.

**Comment by Jefferson-Henrique** [comment]
I've commented out the line 80 from "node_modules\realm\lib\browser\index.js".

```
[80] //config = this._constructor(config);
[81] let schemas = typeof config == 'object' && config.schema;
[82] let constructors = schemas ? {} : null;
```

It had a very slow start (when debug is on) but it worked fine for me on **v2.19.0**.

**Comment by alexmbp** [comment]
+1 for 2.19.0. Working ok on 2.17.0

**Comment by achilles-kosun** [comment]
still there on 2.19.1 :(

**Comment by radeno** [comment]
Get very similar error:
![image](https://user-images.githubusercontent.com/58521/49284825-03c03500-f496-11e8-9934-4f92f7bcd49e.png)

Version of Realm and Tooling

Realm JS SDK Version: 2.20.1
React Native: 0.57.7
Client OS: Android / iOS
Which debugger for React Native: React Native Debugger / Chrome

**Comment by alexmbp** [comment]
@radeno I've created a patch for myself

You can use it. It require patch-package installed and used. You will need to remove this .txt extension.

[realm+2.20.0.patch.txt](https://github.com/realm/realm-js/files/2633062/realm%2B2.20.0.patch.txt)

**Comment by radeno** [comment]
@alexmbp your patch adding something is already available in 2.20.1 and as i have written what i use that version :) https://github.com/realm/realm-js/blob/cfb54f07fc7530530fc7d4e285d531d157489c33/lib/browser/index.js#L136
So there must be another issue.

**Comment by alexmbp** [comment]
@radeno Than it should work already. I've hardcoded version to 2.20.0

**Comment by radeno** [comment]
@alexmbp trust me, it doesn't.
Anyway my issue is connected with https://github.com/realm/realm-js/issues/2128 and that will be fixed for real in this PR https://github.com/realm/realm-js/pull/2157

**Comment by cmelchior** [comment]
I tested with a completely new project using RealmJS 2.21.1 and debugging seems to work fine there. Closing.
