### ISSUE TITLE
Synced realm when using new Realm strange behaviour when Debugging

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#2058]
## Goals

I have previously asked in the forums how we should handle the situation where the user launches the app while offline, then later comes online. I have been informed that we are to use` new Realm ` instead of `Realm.open` and that you can continue to use the reference. 

> If you are offline and you want to open the realm first time (as in on app start) use new Realm API - if you go online that’s fine - just continue using the same reference

https://forums.realm.io/t/solved-retrieving-synced-data-offline/1925/8

## Expected Results - Once online again...

- The only difference between `Realm.open` and `new Realm` to be that Realm.open will asynchronously sync first. 
- When the user comes online the synchronization will connect and catch up. 
- Any change listeners registered whilst offline will get called if there are any updates. 

## Actual Results - Once online again...

- I am finding that often, but not always, the sync will never connect or catch up. 
- Connection listeners never get called to update the state to connected
- Session progress notifications dont get called. 

## Steps to Reproduce /  Sample

Before I spend the time trying to produce a repeatable example. Can someone confirm whether this is an issue or the intended behaviour? I'm not sure if...

- a) I'm misunderstanding and I need help on how it should work 
- b) I'm doing it wrong 
- c) It's a bug. 

It also appears to be more of an issue when debugging. The strange thing is. Sometimes, it does work for a bit. 

## Version of Realm and Tooling

- Realm JS SDK Version: 2.17.0
- Node or React Native: Both
- Client OS & Version: ?
- Which debugger for React Native: Chrome

## Edit ##

I'm almost positive this is just in the Chrome debugger

**Comment by kneth** [comment]
With v2.29.0 configuration options (`Realm.Sync.SyncConfiguration.newRealmFileBehavior` and `Realm.Sync.SyncConfiguration.existingRealmFileBehavior`) to help in your use case.
