### ISSUE TITLE
Debug JS Remotely - React Native

### ISSUE THREAD

**Issue by Melegy90** [realm/realm-js#2059]
Good day,

When I turn on the Debug JS Remotely feature on my Android device, I get this error:

"constructor must be of type 'function', got (undefined)

![image](https://user-images.githubusercontent.com/25931125/46672876-dc0cc900-cbd8-11e8-824c-4985b25217da.png)

When the Debug JS Remotely is Off, I get no errors

Android: Main SDK 16
React-native: 0.55.4
Realm: 2.18.0

**Comment by 424626154** [comment]
+1

**Comment by adrowicaksono** [comment]
i think on node_modules, you must fix constructor become _constructor

**Comment by wesleyguirra** [comment]
Same here
React Native 0.57.2
realm: 2.16.0

**Comment by csotiriou** [comment]
Same here, react native 0.57.2, realm 2.18

**Comment by JackHull** [comment]
Same here... Please fix!

**Comment by skinet2009** [comment]
Help for me:
- downgrade realm to version 2.14.0
- downgrade node to version 8.11.3
- react-native unlink realm
- react-native link

**Comment by epshtielsl** [comment]
Same here using iOS simulator.  Works fine if remote debugging turned off.
    "react-native": "0.56.0",
    "realm": "^2.18.0",

**Comment by JanedoeGVA** [comment]
Help me to : downgrade realm to version 2.14.0 

> Help for me:
> 
> * downgrade realm to version 2.14.0
> * downgrade node to version 8.11.3
> * react-native unlink realm
> * react-native link

Downgrade realm to version 2.14.0 worked for me, thanks.

**Comment by epshtielsl** [comment]
Update: I was able to resolve the issue by downgrading to realm version 2.17.0.

**Comment by benhartouz** [comment]
+1

**Comment by JackHull** [comment]
I got it fixed by upgrading manually to 2.19.0-rc.4, then again using `react-native link realm` and then rebuilding the app. Everything seems to work as expected now.

**Comment by benhartouz** [comment]
@epshtielsl thanks ;)

**Comment by crobinson42** [comment]
I can confirm that downgrading to `realm@2.17` fixes this remote debugging bug. I just tried `realm@2.19.1` on `react-native@0.57.4` and I receive the same error worded slightly different.

Anyhow, I hope the lib maintainers can help us help them get this issue resolved, please solicit for anything that will help resolve this! Thanks :-)

**Comment by bmunkholm** [comment]
We assume this is fixed in 2.20.0.

**Comment by vlatri** [comment]
"realm": "^2.20.0",
"react-native": "0.57.1",
Same issue.

**Comment by mjm918** [comment]
Having the same issue in 

"realm": "2.29.0"
"react": "16.8.6",
"react-native": "0.59.9"

**Comment by Desteel** [comment]
Having the same issue in

"realm": "3.2.0"
"react": "16.9.0",
"react-native": "0.61.5"
