### ISSUE TITLE
Chrome debug mode in android is slow

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#206]
I'm don't think this is our fault but we should confirm.

**Comment by dovfrank** [comment]
+1

**Comment by CodeTitanian** [comment]
+1
Also happens in iOS #491

**Comment by nulleof** [comment]
I use chrome dev tools only for showing `console.log()` output. I've found that Mac OS console logging tool is working with Realm much more faster. Use `$ react-native log-ios` or `$ react-native log-android` in your terminal. [https://facebook.github.io/react-native/docs/debugging.html#accessing-console-logs](url)

**Comment by kristiandupont** [comment]
Tracked with #491
