### ISSUE TITLE
Request - realm.open timeout

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#2061]
## Goals

Today there are appears to be issues with realm cloud and I've been getting 502 Gateway errors all morning (Not sure why yet, I've opened a ticket). When using `Realm.open` it hangs forever with no error, it's hard to handle it gracefully. The same thing happens when the app is launched offline. 

## Expected Results

I expect to be able to handle any issues with the open and be able to display an error or try and just open the local realm. 

## Actual Results

It hangs forever without anyway to handle it. 

## Steps to Reproduce

With the app offline or when the cloud is having issues, open a realm using `Realm.open` in RN. I think the assumption is that `_waitForDownload` on line 122 of /lib/extensions.js will error. It doesn't. 

Suggestion A) Add a timeout in case `_waitForDownload` doesn't respond. (below)
Suggestion B) Just return the local realm, as if it wasn't synced. (below)
Suggestion C) Make sure `_waitForDownload` responds. 

## Code Sample

```
 //Add static methods to the Realm object
    Object.defineProperties(realmConstructor, getOwnPropertyDescriptors({

        open(config) {
            // If no config is defined, we should just open the default realm
            if (config === undefined) { config = {}; }

            // For local Realms we open the Realm and return it in a resolved Promise.
            if (!("sync" in config)) {
                let promise = Promise.resolve(new realmConstructor(config));
                promise.progress = (callback) => { };
                return promise;
            }

            let syncSession;
            let promise = new Promise((resolve, reject) => {
                let realm = new realmConstructor(waitForDownloadConfig(config));
                realm._waitForDownload(
                    (session) => { syncSession = session; },
                    (error) => {
                        realm.close();
                        if (error) {
                            setTimeout(() => { reject(error); }, 1);
                        }
                        else {
                            try {
                                let syncedRealm = new realmConstructor(config);
                                setTimeout(() => { resolve(syncedRealm); }, 1);
                            } catch (e) {
                                reject(e);
                            }
                        }
                    });
                    // Suggestion A - error
                    setTimeout(() => {
                        realm.close();
                        reject('Timeout');
                    }, config.timeout || 10000)
              
                    // Suggestion B - return the local realm
                    setTimeout(() => {
                        realm.close();
                        // return local realm
                    }, config.timeout || 10000)
            });

            promise.progress = (callback) => {
                if (syncSession) {
                    syncSession.addProgressNotification('download', 'forCurrentlyOutstandingWork', callback);
                }

                return promise;
            };
            return promise;
        },
```
## Version of Realm and Tooling

- Realm JS SDK Version: 2.17.0
- Node or React Native: Both
- Client OS & Version: ?
- Which debugger for React Native: Chrome

**Comment by kneth** [comment]
It is possible to choose the behavior of opening Realms from v2.29.0. It includes a timeout option.

**Comment by sambwest** [comment]
Thank you. I have been away from realm for a little while but will shortly be coming back to it. Is the documentation up to date? Where, for example can I find the documentation on choosing open behaviour?

**Comment by kneth** [comment]
Actually, we had a little bug in how we use JSdoc but the API documentation will be online later today.
