### ISSUE TITLE
Assertion hit in react native tests

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2072]
We hit the following assertion on ci when running `testSetLink`:

```
src/realm/table.cpp:3480: [realm-core-5.10.1] Assertion failed: !is_link_type(m_spec->get_column_type(col_ndx))
```

https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-js/detail/master/633/pipeline/47

What's concerning is that this doesn't report the build as failed and has gone unnoticed.

**Comment by kneth** [comment]
I believe it has been fixed.
