### ISSUE TITLE
Change listener is not firing when adding new object from the native module

### ISSUE THREAD

**Issue by muraterd** [realm/realm-js#2080]
## Goals

I'm trying to use realm as a middleman in a react-native project to communicate between native module (Android-Java) and react-native. But the change listener is not firing in js side when i add new object from native module.

## Expected Results
the change listener in js should fire when i add a new object to the realm. And also the change listener in android (java) should fire when i add a new object to the realm from js side

## Actual Results
When i add an object from java the change listener in java is firing. And when i add an object from js the change listener in js is also firing. But when i try to add an object from js the change listener in java is not firing.

## Steps to Reproduce
Note: When i mean both side i mean javascript and java

1. Open a realm in both side
2. Write a query in both side. For example get all users.
3. Add change listener to that collection in both side.
4. Add new object from the javascript
5. The change listener in javascript will fire but the change listener in java will not.

## Code Sample
I shared an example code in the repo below
https://github.com/muraterd/Realm1/

## Version of Realm and Tooling

- Realm JS SDK Version: 2.18.0
- Node or React Native: React Native
- Client OS & Version: Android Oreo
- Which debugger for React Native: None

**Comment by kneth** [comment]
Sorry for the late reply. Depending on how you are implementing it, the following can explain what you see:

* If Java and JS run in separate processes/apps, you cannot share a Realm on mobile (similar to #1928)
* Mixing Java and JS in one app is currently not tested (see also #2409)

If you want to share data between two apps on the same mobile device, you can use [sync](https://docs.realm.io/sync/). Of course, the data needs a round-trip to a server.
