### ISSUE TITLE
error installing to react-native

### ISSUE THREAD

**Issue by henriqueweiand** [realm/realm-js#2081]
I can not perform the installation for a project in react native as it is available on the site.

The same error returns me:

I've tried with yarn but it will not either

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.18.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by henriqueweiand** [comment]
I believe it's for node 10 of the node then

![captura de tela 2018-10-22 as 09 26 36](https://user-images.githubusercontent.com/6539492/47292195-a3a7ba80-d5dc-11e8-8acf-31351b9f56c9.png)

**Comment by matthamil** [comment]
Ah, yeah, I was able to get this working with Node v <10. Perhaps this should be documented in the README?

**Comment by kneth** [comment]
We do support node 10 now.
