### ISSUE TITLE
Schema validation fail only on android release build with fine graded permissions

### ISSUE THREAD

**Issue by apperside** [realm/realm-js#2082]
I am running a react native project using realm platform.
I am using realm's fine graded permissions feature and I am experiencing an issue while running on Android in release mode.

When fine graded permissions was released, you had to include 3 Realm's classes in your app's schema in order to make them work: `Realm.Permissions.Permission` , `Realm.Permissions.User` , `Realm.Permissions.Role`.
This issue was fixed in pull request #1970 , and in fact the app works without adding them.
But there is no way to make it work on android release build, unless you explicitely add them. It works on debug build thought.
The problem is that adding them, will cause probelms on ios

## Goals

Use the same schema definition on Android and iOS when using fine graded permissions

## Expected Results

I can use the same schema definition on Android and iOS when using fine graded permissions

## Actual Results

Realm will throw a schema validation error on android release buid:

Property 'MyClass.permissions' of type 'array' has unknown object type '__Permission'

## Steps to Reproduce
Create a realm schema with object level permission like this

```
export default class MyClass {
    static schema = {
        name: "MyClass",
        properties: {
            id: "int",
            description: "string",
            permissions: '__Permission[]'
        }
    }

    id: number
    description:string
}
```

declare your realm schema like this
`schema:[MyClass.schema.name]`

run react native app on android in debug mode => IT WILL WORK

run react native app on android in RELEASE mode => IT WILL FAIL

declare your realm schema like this
`schema:[MyClass.schema.name,Realm.Permissions.Permission,Realm.Permissions.User,Realm.Permissions.Role,]`

run react native app on android in RELEASE mode => IT WILL WORK

## Version of Realm and Tooling

- Realm JS SDK Version: 2.18.0
- Node or React Native: react native 0.57.0
- Client OS & Version: Android Oreo

**Comment by kneth** [comment]
I recommend that you upgrade to a recent version. If the issue is still observed, please reopen the issue.
