### ISSUE TITLE
Error installing and running Realm iOS

### ISSUE THREAD

**Issue by taylor-pringle** [realm/realm-js#2085]
## Goals

Install Realm and be able to run the app

## Expected Results

Realm installs and able to be used in the app.

## Actual Results

Build fails and app comes with missing Realm constructor error.

Warning when realm installs

node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download.

Seems to install fine. React-native link realm produces no errors.

Have tried installing Realm in a brand new build and same issue. Funnily enough it runs fine on Android.

### The build fails when running react-native run-ios.

```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:59:9: error: no member named 'tm' in the global namespace
using ::tm;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:60:9: error: no member named 'clock' in the global namespace
using ::clock;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:61:9: error: no member named 'difftime' in the global namespace
using ::difftime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:62:9: error: no member named 'mktime' in the global namespace; did you mean 'mktemp'?
using ::mktime;
      ~~^
In file included from /Users/Developer/Documents/Projects/TeRakauTaumatuaApp/node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:19:
In file included from /Users/Developer/Documents/Projects/TeRakauTaumatuaApp/node_modules/realm/react-native/ios/RealmReact/RealmReact.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/assert.h:44:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:94:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/stdlib.h:216:7: note: 'mktemp' declared here
char    *mktemp(char *);
         ^
In file included from /Users/Developer/Documents/Projects/TeRakauTaumatuaApp/node_modules/realm/react-native/ios/RealmReact/RealmReact.mm:19:
In file included from /Users/Developer/Documents/Projects/TeRakauTaumatuaApp/node_modules/realm/react-native/ios/RealmReact/RealmReact.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:31:
In file included from ../../../../ios/Pods/Headers/Public/gRPC-C++/grpcpp/support/time.h:22:
In file included from ../../..
/../ios/Pods/Headers/Public/gRPC-C++/grpcpp/impl/codegen/time.h:22:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/chrono:303:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:63:9: error: no member named 'time' in the global namespace
using ::time;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:65:9: error: no member named 'asctime' in the global namespace
using ::asctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:66:9: error: no member named 'ctime' in the global namespace
using ::ctime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:67:9: error: no member named 'gmtime' in the global namespace
using ::gmtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:68:9: error: no member named 'localtime' in the global namespace
using ::localtime;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ctime:70:9: error: no member named 'strftime' in the global namespace
using ::strftime;
      ~~^


** BUILD FAILED **
```

## Version of Realm and Tooling

Realm JS SDK Version: v2.18.0
Node or React Native: Node v8.11.3 RN @0.57.1
Client OS & Version: OS Mojave 10.14

**Comment by renalpraba** [comment]
@taylor-pringle Are you using XCode 10?

**Comment by taylor-pringle** [comment]
@renalpraba Unfortunately downgrading did not help.

**Comment by renalpraba** [comment]
It's actually react-native issue as I know not realm, there is a workaround by changing build system to legacy instead new xcode 10 build system, but it's better waiting for 0.58 react-native version that will be support xcode 10 if you not to choose downgrading xcode

**Comment by taylor-pringle** [comment]
I downgraded to Xcode 9.4.1 however I still had issues trying to install realm.

**Comment by taylor-pringle** [comment]
Solution found here https://github.com/realm/realm-js/issues/1927!! 

Remove this Header Search Path from RealmReact.xcodeproj/project.pbxproj
"$(SRCROOT)/../../../../ios/Pods/Headers/Public/**"

Worked for me

**Comment by Hari70a** [comment]
@taylor-pringle 
After trying your solution, I could still got the same error in iOS which says "Missing Realm constructor. Did you run "react-native-realm"? "

Versions:
Xcode  : 10.1
realm   :  2.19.1
react-native: 0.56.0

May I lend your your help regarding this.

**Comment by taylor-pringle** [comment]
@Hari70a 

Yes I did run react-native-realm and linked it to the xcode libraries. After this I then edited the file as described in the comment above and it fixed my issue. I did also downgrade to xcode 9.4 which may or may not have helped with the situation.

Thanks

**Comment by kkusanagi** [comment]
for React Native 0.61 and Realm 3.1.0, this step doesn't help anymore. Any suggestion?

**Comment by Malikkhoja** [comment]
Facing same issue on RN 0.61 and Realm 3.2.0. Any suggestions?

**Comment by robertveloso** [comment]
Also facing this issue, firestone and realm results in this error

**Comment by sivaprasadkv** [comment]
> @Hari70a
> 
> Yes I did run react-native-realm and linked it to the xcode libraries. After this I then edited the file as described in the comment above and it fixed my issue. I did also downgrade to xcode 9.4 which may or may not have helped with the situation.
> 
> Thanks

I am getting a similar error with Xcode 13.4.1, Realm v12.6.2, React Native v0.73.5, and iOS SDK 14.0 as deployment target. While building the app with Xcode, gets this error and Xcode build logs as follows:

Undefined symbols for architecture arm64:
"_objc_msgSend$allBundles", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$countByEnumeratingWithState:objects:count:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringByAppendingPathComponent:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$enumeratorAtPath:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$copyItemAtPath:toPath:error:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$userInfo", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$pathExtension", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$isEqualToString:", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringWithUTF8String:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$code", referenced from:
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$createDirectoryAtPath:withIntermediateDirectories:attributes:error:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$objectForKeyedSubscript:", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$containsString:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$defaultManager", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringByDeletingLastPathComponent", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$fileExistsAtPath:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$removeItemAtPath:error:", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$localizedDescription", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$objectAtIndexedSubscript:", referenced from:
realm::JsPlatformHelpers::default_realm_file_directory() in librealm-js-ios.a(platform.o)
"_objc_msgSend$resourcePath", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$UTF8String", referenced from:
realm::JsPlatformHelpers::default_realm_file_directory() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Realm_React_Native_iOS_link_error
What is the solutions for this linking issue? Please suggest.

**Comment by sivaprasadkv** [comment]
I am getting a similar error with Xcode 13.4.1, Realm v12.6.2, React Native v0.73.5, and iOS SDK 14.0 as deployment target. While building the app with Xcode, gets this error and Xcode build logs as follows:

Undefined symbols for architecture arm64:
"_objc_msgSend$allBundles", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$countByEnumeratingWithState:objects:count:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringByAppendingPathComponent:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$enumeratorAtPath:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$copyItemAtPath:toPath:error:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$userInfo", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$pathExtension", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$isEqualToString:", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringWithUTF8String:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$code", referenced from:
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$createDirectoryAtPath:withIntermediateDirectories:attributes:error:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$objectForKeyedSubscript:", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$containsString:", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$defaultManager", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$stringByDeletingLastPathComponent", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$fileExistsAtPath:", referenced from:
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$removeItemAtPath:error:", referenced from:
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
"_objc_msgSend$localizedDescription", referenced from:
error_description(NSError*) in librealm-js-ios.a(platform.o)
"_objc_msgSend$objectAtIndexedSubscript:", referenced from:
realm::JsPlatformHelpers::default_realm_file_directory() in librealm-js-ios.a(platform.o)
"_objc_msgSend$resourcePath", referenced from:
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
"_objc_msgSend$UTF8String", referenced from:
realm::JsPlatformHelpers::default_realm_file_directory() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::ensure_directory_exists_for_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::copy_bundled_realm_files() in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_realm_files_from_directory(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
realm::JsPlatformHelpers::remove_file(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) in librealm-js-ios.a(platform.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="704" alt="Realm_React_Native_iOS_link_error" src="https://github.com/realm/realm-js/assets/3582975/74d30108-c9f0-4b90-9790-d5cc2f8f508a">

What is the solutions for this linking issue? Please suggest.
