### ISSUE TITLE
Support For Node JS 10

### ISSUE THREAD

**Issue by renalpraba** [realm/realm-js#2087]
As Node.js Foundation says in https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51 Node JS 10 will be a LTS version on October 30, from that a lot of people will using it as Node JS 10 is the current LTS version, so just curious is there any plan and the date for realm JS with node JS 10 support release?

**Comment by bmunkholm** [comment]
@renalpraba Thanks for the nudge :-)
We have it tracked here: #1813, so I'll close this for now and let you know that we will look into this again asap. I hope we can get it done before Oct 30, but I need to check with the team.
