### ISSUE TITLE
SectionList crashes when removing Object from Realm even when copied using Object.assign()

### ISSUE THREAD

**Issue by thomasarogers** [realm/realm-js#2091]
## Goals

Displaying a list of objects in SectionList passed as props, and upon removal from Realm the list updating

## Expected Results

SectionList updates minus the removed object(s)

## Actual Results

I have a component showing either a FlatList or SectionList showing a Date sectioned subset of objects the FlatList displays. Upon removing items from Realm only the SectionList crashes, the FlatList does not have any issues. 

SectionList crashes with below error
Error: Error: Accessing object of type ClientActivity which has been invalidated or deleted

![untitled](https://user-images.githubusercontent.com/42372294/47804776-93ef4b00-dd2d-11e8-9902-1e1e05fbefe0.png)

Code which removes all objects from realm: 

![screen shot 2018-10-31 at 17 08 49](https://user-images.githubusercontent.com/42372294/47805632-b3877300-dd2f-11e8-947e-649ca5fddcb3.png)

Code in component which gets objects from model and makes a copy which I thought would stop the SectionList having a reference to any objects and not crash:

![screen shot 2018-10-31 at 17 08 00](https://user-images.githubusercontent.com/42372294/47805643-ba15ea80-dd2f-11e8-979e-fd80abff8803.png)

Code which takes list of objects and sorts by Date then assigns to state for passing to component as prop:

![screen shot 2018-10-31 at 17 07 48](https://user-images.githubusercontent.com/42372294/47805655-c1d58f00-dd2f-11e8-9333-ddc80843033e.png)

Code which calls the SectionList or FlatList components and passes it the objects from state:

![screen shot 2018-10-31 at 17 10 07](https://user-images.githubusercontent.com/42372294/47805706-dca80380-dd2f-11e8-8d58-07f77c3d5c62.png)

SectionList render function which crashes the objects are removed from realm:

![screen shot 2018-10-31 at 17 08 10](https://user-images.githubusercontent.com/42372294/47805757-ff3a1c80-dd2f-11e8-9627-f408e7ce1442.png)

FlatList render function which does not crash at all on Object removal
![screen shot 2018-10-31 at 17 08 24](https://user-images.githubusercontent.com/42372294/47805773-0bbe7500-dd30-11e8-8a16-9b4c98c150be.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 2.18.0
- Node or React Native: 0.57.1
- Client OS & Version: OS X 10.13.6
- Which debugger for React Native: Xcode Console

**Comment by nirinchev** [comment]
Object.assign does a shallow copy of the objects, so in your case, it just materializes the collection in a new array, but the objects it contains are still the Realm objects in the original collection.
