### ISSUE TITLE
Realm js not syncing data after reconnection

### ISSUE THREAD

**Issue by aureliopetrone** [realm/realm-js#2093]
## Goals

I'm trying to access data offline and keep it synced, even if connection state changes in time.

## Expected Results

I expect realm to manage the network error automatically and sync the data when the connectivity returns.

## Actual Results

Sometime React Native gave me an error "Network request failed" (in the classic red box), but now it seems not appears anymore (even if I've not changed the code :\ ). However, the real problem is that when I reconnect to wifi/4g in the emulator it not syncing data anymore.

## Steps to Reproduce

I'm running the todoapp example in React Native.

## Code Sample

```
  // Get a result containing all projects
        const projects = realm
          .objects("Project")
          .filtered("owner == $0", this.props.user.identity)
          .sorted("timestamp", true);
          
        // When the list of projects change, React won't know about it because the Result object itself did not change.
        projects.addListener(() => {
          // Bump a data version counter that we'll pass to components that should update when the projects change.
          console.log("Dati aggiornati");
          this.setState({ dataVersion: this.state.dataVersion + 1 });
        });
        
        // Create a subscription and add a listener
        // Remember to remove the listener when component unmounts
        this.subscription = projects.subscribe();
        this.subscription.addListener(this.onSubscriptionChange);
        
        // Update the state with the projects
        this.setState({ projects });
```

## Version of Realm and Tooling

- Realm JS SDK Version: "^2.18.0"
- Node or React Native: RN
- Client OS & Version: Android 8.0 
- Which debugger for React Native: None

## UPDATE

This happens only on the emulator, on my p8 lite 2017 it seems to work also in dev mode.

**Comment by kneth** [comment]
I have observed a similar issue with v2.29.0 but only on iOS. On a real Android device, I haven't been able to reproduce it.

@aureliopetrone I know that it has been a long time since you created the issue but could you try to upgrade and see if you still have the issue?
