### ISSUE TITLE
Yarn install fails due to CDN 404 error

### ISSUE THREAD

**Issue by mjstelly** [realm/realm-js#2095]
Mac OSX High Sierra
Yarn installer
command `yarn add realm --save`

This is an issue once again. Please reopen it. I'm getting this

```node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-node-v64-darwi
n-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.18.0 and node@10.11.0 (node-v64 ABI, unknown) (falling
back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/2.18.0/realm-v2.18.0-no
de-v64-darwin-x64.tar.gz```

_Originally posted by @mjstelly in https://github.com/realm/realm-js/issue_comments#issuecomment-435476244_

**Comment by fealebenpae** [comment]
That's because you're trying to install on Node.js 10, which realm-js doesn't support yet. However, I'm happy to say that thanks to @kneth we'll be able to soon fix this: https://github.com/realm/realm-js/pull/2092.

**Comment by mjstelly** [comment]
Thanks @fealebenpae. I'm new to the project which uses realm. I just did a standard npm install without realizing the `node` requirement. I appreciate the help!

**Comment by liukaixin01** [comment]
I'm also have same issue in node@10.13.0，but fixed use node @9.8.0

**Comment by kneth** [comment]
@liukaixin01 v2.19.0 and v2.20.0 have node 10 support. Which version of Realm do you use?

**Comment by liukaixin01** [comment]
@kneth "realm": "2.2.14"
