### ISSUE TITLE
download realm-sync-cocoa-x.x.x.tar.gz after yarn every time

### ISSUE THREAD

**Issue by guopeng1994** [realm/realm-js#2096]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by SiSa68** [comment]
I need this too!!
Why it should download realm-sync-cocoa every time?!
There should be a way to prevent this
Or at least change its address to local file and every time it downloads file from local

Any suggestion?

**Comment by crazybits** [comment]
suffer from this as well, it is very time consuming to download realm-sync-cocoa every time run yarn, remember that older version can re-used the donwloaded file on local, do not need to download every time

**Comment by guopeng1994** [comment]
i build a local http server. and download sync and core file from realm.io, then i create a path just like the download url. after that i change the host realm.io from package.json to my local server address such as 192.168.1.1, then it should download from local server. and it it should be faster. but you need to change package.json every time after yarn new packages.
