### ISSUE TITLE
Code on github differs from published code

### ISSUE THREAD

**Issue by saschak42** [realm/realm-js#2103]
## Goals

We need the current version of the Android build.gradle file because of build errors. In the published version ([npmjs](https://www.npmjs.com/package/realm)) the build.gradle file for example has no google() repository. In github these changes were already made in version [2.4.2](https://github.com/realm/realm-js/commit/21d28f978064a656b4f1d32b300a65bc391972d3#diff-a472044ebdae65cdc7156fdcc043bc93).

## Expected Results

We would expect that the published files on npmjs and the code on github don't differ.

## Actual Results

For example the [build.gradle](https://github.com/realm/realm-js/blob/master/react-native/android/build.gradle) file differs completely from the one published on [npmjs](https://www.npmjs.com/package/realm).

Also the directory structure differs. The android folder on github is a subfolder of react-native. On npmjs the android folder is directly in the root (and the ios folder not).

## Steps to Reproduce

Compare the files.

## Version of Realm and Tooling

- Realm JS SDK Version: Compared different versions of Realm JS like 2.19.0, 2.18.0, 2.14.2, ...

**Comment by cmelchior** [comment]
The build file referenced here: https://github.com/realm/realm-js/blob/master/react-native/android/build.gradle is not the one we distribute. This is the one we use to build the android release itself. The `build` file we release is this one: https://github.com/realm/realm-js/blob/master/react-native/android/publish_android_template, it just gets renamed to  `build.gradle` during the release. I hope that clarifies it?

**Comment by saschak42** [comment]
@cmelchior Thank you for your answer. Yes, that clarifies it. But the problem still exists, because the published gradle file (https://github.com/realm/realm-js/blob/master/react-native/android/publish_android_template) is too old. For example the gradle plugin version is outdated and also the google repository is missing. Can you fix that?

**Comment by cmelchior** [comment]
Yes, we should upgrade those.
