### ISSUE TITLE
Expose setUpBasicPermissions API

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2112]
When ROS upgrades a full Realm to a reference Realm, no permissions are automatically created which means that we'll get a very locked-down Realm. We should expose a `setUpBasicPermissions` API that creates the permissions classes and tables, creates the everyone role, and calls `sync::set_up_basic_permissions_for_class` for all classes in the schema.

**Comment by kneth** [comment]
Not relevant anymore
