### ISSUE TITLE
Error: Cannot access realm that has been closed.

### ISSUE THREAD

**Issue by zabojad** [realm/realm-js#2117]
I'm using Realm to store my Redux state (with redux-persist). It worked like a charm until I've added the [react-native-threads](https://github.com/joltup/react-native-threads) lib and started another js thread in my RN app.

What happens:
1 - the app launches, fetch some data from the server and store it in Redux, which stores it in Realm.
2 - everything is fine until now
3 - the app starts a new js thread that only performs http request to a server, nothing else (no access to redux nor realm). As soon as this thread is started, I cannot use  realm anymore because of this error:
```
11-16 00:47:43.754 13012-16700/my.app E/ReactNativeJS: 'Error on setItem', { [Error: Cannot access realm that has been closed.]
      line: 13500,
      column: 31,
      sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }, 'persist:myapp-userSession', '{"user":"null","_persist":"{\\"version\\":-1,\\"rehydrated\\":true}"}'
11-16 00:47:43.766 13012-16700/my.app E/ReactNativeJS: 'Error storing data', { [Error: Cannot access realm that has been closed.]
      line: 13500,
      column: 31,
      sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }
```

Any idea why this is happening?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.15.3
- Node or React Native: 0.57.0
- Client OS & Version: Android 8.0.0
- Which debugger for React Native: none, (using logcat)

**Comment by zabojad** [comment]
@kneth Maybe you would have an idea about that.

I've looked into this issue https://github.com/realm/realm-js/issues/1589 but in my case, I never call `realm.close()` and it really happens from the moment I spawn a new js thread...

**Comment by kneth** [comment]
@zabojad The relevant issue is #1928. Even though the library's name is `react-native-threads` it is actually spawning a new *process* and not a thread (at least according to https://www.npmjs.com/package/react-native-threads). Realm doesn't support multi-process access on mobile yet.

**Comment by zabojad** [comment]
@kneth I do not think https://github.com/realm/realm-js/issues/1928 is the same issue.

First, I'm having this problem on Android, and https://github.com/realm/realm-js/issues/1928 is an iOS issue.

Then, I am not accessing the Realm DB nor making any call to the realm API in the new process.

So for my realm DB, there is still only one process accessing it...

**Comment by kneth** [comment]
At the moment, Realm does not support multi-process access on React Native.

**Comment by ZComwiz** [comment]
@kneth and how about now? How can one use Realm without it locking the whole UI for 20 seconds?
