### ISSUE TITLE
Unable to open a realm at path '.../default.realm.lock' open() failed: Operation not permitted.

### ISSUE THREAD

**Issue by duro** [realm/realm-js#2118]
## Goals

Simply trying to get consistent usage for all our users

## Expected Results

That realm opens for all users

## Actual Results

We are seeing in our Rollbar error reporter that some users when the following lines runs:

```
const realm = await Realm.open({
      schema: [SessionSchema]
    })
```

The full error is:

```
Error: Unable to open a realm at path '/var/mobile/Containers/Data/Application/D902B5A2-6492-4C34-AAB7-8B57AEAFDA4D/Documents/default.realm.lock': open() failed: Operation not permitted.
```

## Steps to Reproduce

In our case it's as soon as the user opens app, but is only happening sporadically with some users.

## Code Sample

We even tried adding a retry, in case it was some kind of temporary IO issue. Here is what our current code looks like:

https://gist.github.com/duro/12afc33755f58397d5f207084dc3baf3

## Version of Realm and Tooling

- Realm JS SDK Version: 2.19.0
- Node or React Native: 0.57.1
- Client OS & Version: Appears to only be iOS
- Which debugger for React Native: None, this is happening in live code

**Comment by deepeshwp** [comment]
Is there a solution to this universal problem since 2016 ? please can anyone share a link with all possible fixes made since this issue has started to occur. Please can someone from the realm team let us know what is going on as all the other issues are either just closed without any solutions.

**Comment by Yarkhan** [comment]
I'm still seeing this popping up in Appcenter. It seems to be getting worse over time.

**Comment by kneth** [comment]
@Yarkhan Do you see a pattern? For example, is it only iOS or Android? Any particular version? A specific device?

**Comment by Nahatakyan** [comment]
I'm getting this error too.
