### ISSUE TITLE
Realm client get confused by classes with names `ROLE` and `USER`

### ISSUE THREAD

**Issue by programaths** [realm/realm-js#2120]
## Goals

Using role and permissions

## Expected Results

Role and permissions are working, system introduce system classes in schema automatically.

## Actual Results

See [Test cases](https://gist.github.com/programaths/2fa2b0bfca94fadd5dfbbaecad7c0749)

```
- Type '__User' appears more than once in the schema.
- Property '__Permission.role' of type 'object' has unknown object type '__Role'
- Property '__User.role' of type 'object' has unknown object type '__Role'
- Property '__User.role' of type 'object' has unknown object type '__Role'
```

OR

```
  what():  Schema validation failed due to the following errors:
- Type '__User' appears more than once in the schema.
```

## Steps to Reproduce

Create a new pristine Realm-Object-Server
Create an admin account
Adapt the [test cases](https://gist.github.com/programaths/2fa2b0bfca94fadd5dfbbaecad7c0749) with appropriate account information

Run [test cases](https://gist.github.com/programaths/2fa2b0bfca94fadd5dfbbaecad7c0749)

## Code Sample

The [test cases](https://gist.github.com/programaths/2fa2b0bfca94fadd5dfbbaecad7c0749) are self contained

## Version of Realm and Tooling

- Realm JS SDK Version: 2.19.1
- Node or React Native: node v8.12.0
- Client OS & Version: (uname -a) Linux christian-Aspire-TC-605 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Which debugger for React Native: NA

**Comment by programaths** [comment]
So, I created a userland fix you can find [here](https://gist.github.com/programaths/26e24b663082ddec2bce6194768a8529).

Example of use:

```javascript
let fixedSchema = fixSchema([ROLE_CLASS, INVITATION_CLASS, SYS_USER_CLASS]);
```

**Comment by bmunkholm** [comment]
Thanks for the excellent repro case @programaths! It's now been fixed, awaiting review and will be out with the next release.
