### ISSUE TITLE
Expose `waitForUpload` and `waitForDownload`

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2122]
## Goals

We need the native `waitForUpload` and `waitForDownload` methods exposed either on the session or the Realm. Previously we had an internal `_waitForDownload` method on the `Realm` object but that is now gone and `_waitForUpload` is awkwardly placed on `Realm.Sync`. We should expose a consistent public API for these as using the byte-level progress notifications is overkill for the simple scenario where you want to ensure that everything has been uploaded/downloaded.

**Comment by nirinchev** [comment]
Ideally the API should look something like this:

```ts
    class Session {
        // Other session methods

        waitForUpload(): Promise<void>;
        waitForDownload(): Promise<void>;
    }
```

**Comment by nirinchev** [comment]
@roberhofer this is proving problematic for merging stage 1 of the service scalability effort. Please bring it up at the upcoming sdk meeting.

**Comment by bmunkholm** [comment]
Perhaps @cmelchior can take a stab at this?

**Comment by cmelchior** [comment]
Java already exposes this build on top of `Session::async_wait_fow_download_completion()`. They are called `SyncSession.downloadAllServerChanges()` or `SyncSession.uploadAllLocalChanges()`. We also have variants that accept a timeout. 

From what I recall using the blocking variant is dangerous in Sync as you are then effectively blocked behind a mutex with no way to cancel.

But I can take a look.

**Comment by cmelchior** [comment]
@nirinchev One question though. Would a JS user expect the thread to be fully up to date with notifications triggered once `Session.downloadAllServerChanges()` completes? 

In Java we don't do this as the SyncSession isn't coupled to any particular thread, but I'm a bit unsure about the JS semantics since there is only 1 thread? I suspect that people would expect it to be up to date?
