### ISSUE TITLE
[Bugs] Unable to open a realm at path | Invalid streaming format cookie.

### ISSUE THREAD

**Issue by Winglonelion** [realm/realm-js#2123]
## Goals
It is a randomly crash. Almost times, it worked nice. But some of this crash was collected by sentry and google crash report from realmjs 2.14.0.

## Expected Results
 Realm file open by a normal way.

## Actual Results
Realm database can not open and an Exception be throwed:
```
com.facebook.react.common.JavascriptException: Unable to open a realm at path '/data/data/my.app/files/local_v1.realm': Invalid streaming format cookie (3472328566010356275)., stack:
upgradeSchema@1257:159
<unknown>@967:468
v@2:1496
d@2:949
o@2:435
<unknown>@965:542
v@2:1496
d@2:949
o@2:435
<unknown>@619:368
v@2:1496
d@2:949
o@2:435
<unknown>@11:81
v@2:1496
d@2:879
o@2:435
global code@2870:4
at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException (ExceptionsManagerModule.java:38)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:160)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loop (Looper.java:164)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:192)
  at java.lang.Thread.run (Thread.java:764)
```

## Steps to Reproduce
Sorry, but when i tried with our devices and reproduce code. It worked fine in all times.
I think it happen in some special case.

## Code Sample

```
    const currentSchema = new studifySchema().current();
    const syncConfig = {
      sync: {
        user,
        url: realmUrl(),
        error: err => console.log('realm error', err),
      },
      path: realmDbLocation(userID),
      ...currentSchema,
    };

   studifyDB = await Realm.open(syncConfig).progress((transferred, transferable) => {
        // ... handler
    });
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.16.0-rc.2
- React Native: React Native 0.57.5
- Nodejs: 8.12
- Client OS & Version: Mac OS Sierra 10.12.6
- Which debugger for React Native: React Native Debugger

**Comment by bmunkholm** [comment]
We have nowhere in our code the error "Invalid streaming format cookie" - so I'm not sure what the problem is. We have never seen this before, so, unfortunately, we can't investigate this further without more information and ideally a repro case.

**Comment by Winglonelion** [comment]
@bmunkholm  Hi there, after few hours researched. I think it is a specify devices (or device serries) bugs and can not have a strangle reproduce scripts.

First: It relation to this issues in Realm cocoaPod: https://github.com/realm/realm-cocoa/issues/5974

Seconds: Follow our Google crash report. It only rise on Samsung devices which have android 8.0 and late

![screen shot 2018-11-23 at 10 07 23 am](https://user-images.githubusercontent.com/16574690/48927335-a6613c80-ef07-11e8-91e4-7f6e4ba6fbe0.png)

More info: Our realm file is compacted file by Realm browser newest version. And `shouldCompactOnLaunch` is not set.

**Comment by bmunkholm** [comment]
Thanks for the reference to realm/realm-cocoa#5974. It looks like github search across an org is quite working :-) 
Are you by any chance copying the realm file?

**Comment by Winglonelion** [comment]
https://drive.google.com/file/d/1QBOiXc7wGoWqxSjoVlw5RnkdtmrtvXc8/view 
`Please require permission and comment bellow.`

**Comment by nirinchev** [comment]
@bmunkholm that's an error from core: https://github.com/realm/realm-core/blob/8afd609420b149de044524e98328892084ccdaf4/src/realm/alloc_slab.cpp#L1181

**Comment by bmunkholm** [comment]
@Winglonelion Do you still experience this issue?

**Comment by thuan-nguyen-js** [comment]
@bmunkholm Hello, I'm Wing. I don't have last analytics data because I had left this Project for 6 month. But the last times tracked, it still persist.

**Comment by kneth** [comment]
I am closing the issue as we haven't heard back for a while. If the issue persist, notice us and we can reopen it.

**Comment by TomaterID** [comment]
I am using realm in electron, not on mobile, but recently two users faced the same issue basically same day. No one reported it before, but here we have two independent users same day.

I use realm 10.12.0 (don't update to latest due to lack of old Windows support, I still have some Windows 8 users). I use shouldCompactOnLaunch, but not always, only when some conditions are met.

Any recommendations how to avoid that in the future would be appreciated. Losing 1-2Gb of database is far from being fun.
