### ISSUE TITLE
Document Realm.Sync.setSyncLogger

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2125]
## Goals

To implement https://github.com/realm/realm-studio-private/issues/16 it would be great to get a way to intercept messages logged by the sync client.

## Expected Results

It would be great to be able to set a callback which would get called when the client wants to log a message, overriding the default behaviour of printing to the console:

```typescript
enum LogLevel {
    All = 'all'
    Trace = 'trace'
    Debug = 'debug'
    Detail = 'detail'
    Info = 'info'
    Warn = 'warn'
    Error = 'error'
    Fatal = 'fatal'
    Off = 'off'
};

Realm.Sync.setLogCallback((level: LogLevel, message: string) => {
    // Do whatever with the message ...
});

// Because `setLogCallback` was called no messages are logged to the console.
```

**Comment by nirinchev** [comment]
I don't know if this should be a separate request, but it would be great if we could reuse that to avoid realm-js logging to the console in general - e.g. in user-methods there's a `print_error` method that should use the log callback rather than the console.

**Comment by cmelchior** [comment]
In Java we have a `RealmLogger` interface for this kind of thing. The default behavior of logging to LogCat is just one implementation of this interface.

Note that having different log levels for different loggers is a bit tricky due to how the log-level is specified at the Sync level.

**Comment by kneth** [comment]
@kraenhansen Sorry but I think we have forgotten to document it. You can do:

```
Realm.Sync.setSyncLogger((level, message) => {
    console.log('test-client: %s', message);
});
```

**Comment by kraenhansen** [comment]
I'll try it out - thanks! I'll give it a spin when I get to the issue then 👍 It would be awesome to get it documented though.

**Comment by kraenhansen** [comment]
While we're documenting something which has not been considered a part of the official API, I would suggest renaming this function to `setLogger` or `setLogCallback` instead of the current name. There is no need to include `Sync` in the name of the method when it's already namespaced on `Realm.Sync`.

**Comment by kraenhansen** [comment]
I know I approved #2260, but as I am using the types I now realize that the callback is called with a number (representing the internal enum of sync) rather than a string for the log-level.

**Comment by kneth** [comment]
@kraenhansen So you are asking for a change to use strings in callback's signature?

**Comment by kraenhansen** [comment]
@kneth - that would be ideal but breaking. Alternatively updating the types to match the current reality.
