### ISSUE TITLE
Previous account data event if there aren't permission

### ISSUE THREAD

**Issue by aureliopetrone** [realm/realm-js#2150]
## Goals

I add an object and give object level permission for that user.
Then I log out and then log in with another account 

## Expected Results

I see only the data that i have permission to read. The previous data, even if stored in local realm is not shown.

## Actual Results

I can see the previous data on device (even the ones for those I don't have permissions, that I can only read but not edit, and i receive also the live updates ).

## Code Sample

This is the code I use for create the realm instance

```
const config = user.createConfiguration({
      schema: [MySchema],
      //sync: { url: "realms://dmd91.de1a.cloud.realm.io/db" }
      //fullSynchronization: true
    });
    // Open the Realm

    const realm = new Realm(config);
    

    realm.objects('MyObjects').subscribe()
       
    // Navigate to the main scene
    Actions.authenticated({ user, realm });
```

This is the one i use for the query

```
 const myobjects = realm
          .objects("MyObjects").sorted("name", false);


          
        // When the list of myobjects change, React won't know about it because the Result object itself did not change.
        myobjects.addListener(() => {
          this.forceUpdate(); // Force UI updates with new data
        });
        
        // Create a subscription and add a listener
        // Remember to remove the listener when component unmounts
        this.subscription = clienti.subscribe();


        this.subscription.addListener(this.onSubscriptionChange);
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.18.0
- Node or React Native: React Native
- Client OS & Version: Android 8.0
- Which debugger for React Native: None

**Comment by cmelchior** [comment]
How are you restricting the permissions for the objects you create? Also, keep in mind that all users are part of the "everyone" role which has very permissive privileges as a default: https://docs.realm.io/platform/using-synced-realms/access-control/fine-grained-permissions#roles

**Comment by aureliopetrone** [comment]
The Objects has a field that is a list of Permissions called permissions. There is only 1 permission for a Role a created (that have the user as a member), everything true except canModifySchema and canSetPermission.

As I understood, if I set up the permissions variable on an object, "everyone role" should not see that even if has the permission to read and query that class. Right?

Thanks @cmelchior

**Comment by kneth** [comment]
We are deprecating Realm Cloud and ask everybody to migrate to [MongoDB Realm](https://docs.mongodb.com/realm/). The permission model is one of the things which has changed.
