### ISSUE TITLE
Requesting tighter TypeScript definitions

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2163]
## Goals

Tighter TypeScript definitions which are closer to reality, making it easier to consume the library.

## Expected Results

When calling methods in Realm JS I expect the type definitions to be as close to the actual behaviour as possible.

## Actual Results

It is often the case that it takes partial configuration (for example the `sync` property is optional on the `Configuration`) or support different ways for users to enter configuration (such as the list of properties on the `ObjectSchema` which can be either `PropertyType` strings or `ObjectSchemaProperty` objects). This is great!

At the same time the library returns objects using the same "loose" types and it would make it easier for developers to use the library if these got more precise. For example:

- When calling `createConfiguration` on a `User` to get the default configuration related the that user, the `sync` property is always specified, but from the types it's optional.
- Accessing the schema after creation (via the `schema` property on the `Realm` object or `objectSchema()` method on a `Realm.Object`) the properties on an `ObjectSchema` are `ObjectSchemaProperty` objects, not strings. In addition to this - the `ObjectSchemaProperty` objects returned has a `name` property which is not obvious from the types.

## Steps to Reproduce

N/A

## Code Sample

N/A

## Version of Realm and Tooling

- Realm JS SDK Version: v2.21.0
- Node or React Native: N/A
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by kraenhansen** [comment]
Slightly related to this I just noticed that the `Realm#objectForPrimaryKey` and `Realm#objects` takes a generic type which doesn't default to `any`: https://github.com/realm/realm-js/blob/master/lib/index.d.ts#L761-L772, it would be easier to use the API if these defaulted to the `any` type.

**Comment by cmelchior** [comment]
Maybe I am misunderstanding something, but isn't it better to specific about the types? If you use `any` then you also accept a lot of invalid input arguments?

**Comment by kraenhansen** [comment]
It should still take a generic argument, but it's annoying that it defaults to the empty object. It's definitely better to be specific about the types, but when you're not supplying a type for the generic, I think it's annoying that the object supposingly does not have any properties. Maybe it's just because I've been writing quite a lot of tests today where I didn't bother to define the interface and had to write `realm.objects<any>('Whatever')` a lot of times.

**Comment by kneth** [comment]
Fixed in v2.19.1
