### ISSUE TITLE
Is there an API to query a local realm (instead of using Realm Studio)?

### ISSUE THREAD

**Issue by Eyesonly88** [realm/realm-js#2164]
## Goals

I want to query/monitor a local realm DB in an automated way without having to open Realm Studio. An example would be to integrate it with Reactotron.

## Expected Results

Having some sort of an API allows us to integrate querying and monitoring with other apps such as Reactotron to make debugging / development easier and faster.

**Comment by kneth** [comment]
@Eyesonly88 Not exactly sure what you mean. But you can open a Realm using `Realm.open()` and query it using `Realm.objects()` and `Realm.Results.filtered()`. Moreover, you can add [listeners](https://realm.io/docs/javascript/latest#notifications).

**Comment by kneth** [comment]
@Eyesonly88 On mobile platforms, we don't have good multiprocess support.

You can copy the Realm file from your mobile device to your computer and open it using a node.js app. Or you can sync your Realm with [Realm Cloud](https://cloud.realm.io/login) and sync it with your computer or any other device.

**Comment by Eyesonly88** [comment]
@kneth Ah I see. Cool, thanks for the reply. I'll try copying and use a node.js app.
Have a nice day 👍
