### ISSUE TITLE
AppCenter build failing for realm project

### ISSUE THREAD

**Issue by ivanpagac** [realm/realm-js#2166]
## Goals

AppCenter build with realm js

## Expected Results

build pass

## Actual Results

* What went wrong:
```
A problem occurred configuring project ':realm'.
> Could not resolve all files for configuration ':realm:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
     Required by:
         project :realm
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm@2.21.0
- Node or React Native: RN
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by yenda** [comment]
For some reason the artefact isn't in jcenter repo anymore, we have the same problem

**Comment by ivanpagac** [comment]
as a temporary solution in android build.gradle
`subprojects {project ->
    if (project.name.contains('realm')) {
            buildscript {
                repositories {
                google()
                jcenter()
                maven { url = "https://dl.bintray.com/android/android-tools/" }
            }    
        }
    }
}`

**Comment by yhrun** [comment]
> as a temporary solution in android build.gradle
> `subprojects {project -> if (project.name.contains('realm')) { buildscript { repositories { google() jcenter() maven { url = "https://dl.bintray.com/android/android-tools/" } } } } }`

it works for me

**Comment by kneth** [comment]
I am closing the issue but please reopen if the issue is observed in the future.
