### ISSUE TITLE
Prebuilt version causes errors on Debian

### ISSUE THREAD

**Issue by rajivshah3** [realm/realm-js#2180]
## Goals
We use `jest` to run our tests but one of them fails on our CI, which uses a docker image based on `node:8.12-stretch`. This is the error it gives:

```
FATAL ERROR: v8::FunctionTemplate::SetCallHandler FunctionTemplate already instantiated
 1: node::Abort() [/usr/bin/node]
 2: 0x8cce9c [/usr/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
 4: v8::FunctionTemplate::SetCallHandler(void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>) [/usr/bin/node]
 5: 0x7f029f624f68 [/trinity-wallet/src/shared/node_modules/realm/compiled/node-v57_linux_x64/realm.node]
 6: 0x8ce6d4 [/usr/bin/node]
 7: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/bin/node]
 8: 0xb0d64c [/usr/bin/node]
 9: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
10: 0xad4a43842fd
Aborted
```

I can reproduce this by pulling the `buildpack-deps:stretch` image, manually installing `yarn`, and running the tests again. I saw [this thread](https://forum.realm.io/t/cant-require-realm-on-linux-server/1107) but I don't think this issue is specific to ElasticBeanstalk as I'm able to reproduce it locally in a Docker container. I tried rebuilding `realm` from source as the thread suggested (`npm rebuild realm --build-from-source`) and the tests succeeded. It seems like the prebuilt binary is the one that causes this error. 

## Expected Results
Test should pass

## Actual Results
Fatal error thrown by `node` with the stacktrace shown above

## Steps to Reproduce

1. `git clone https://github.com/iotaledger/trinity-wallet && cd trinity-wallet`
2. `git checkout feature/realm`
3. `yarn && yarn deps:shared && yarn deps:mobile`
3. `cd src/mobile && yarn test`

I'll try to reproduce this with a smaller project, as cloning our entire codebase is probably not the easiest way to reproduce this

## Version of Realm and Tooling

- Realm JS SDK Version: `2.21.0`
- Node or React Native: Node
- Client OS & Version: `node:8.12-stretch` or [buildpack-deps:stretch](https://github.com/docker-library/buildpack-deps/blob/d7da72aaf3bb93fecf5fcb7c6ff154cb0c55d1d1/stretch/Dockerfile)
- Node version: 8.12.0, can also reproduce on 8.14.0

**Comment by kneth** [comment]
@rajivshah3 I have tried the four steps, and all tests (305 tests in 30 test suites) pass with some warnings.. My setup is Debian GNU/Linux v9.6 (x86-64) using node v8.12.0.

**Comment by rajivshah3** [comment]
Hi @kneth , sorry about that. I probably should have given instructions so you could reproduce on an inactive branch. We’ve been using `npm rebuild realm —build-from-source` to get around this issue because we needed our tests to pass on the CI. I’ll try to make a sample project that doesn’t include this workaround so that the bug is reproducible.

**Comment by rajivshah3** [comment]
@kneth the commit before we added the patch is `40f5091`, so if you try these steps it should reproduce:
```
git clone https://github.com/iotaledger/trinity-wallet && cd trinity-wallet
git checkout 40f5091
yarn && yarn deps:shared && yarn deps:mobile
cd src/mobile && yarn test
```

**Comment by rajivshah3** [comment]
Hey @kneth , were you able to reproduce this? If not I'll try creating a sample project

**Comment by kneth** [comment]
@rajivshah3 I see it but all tests pass. Maybe https://forum.realm.io/t/cant-require-realm-on-linux-server/1107/5 can offer an explanation.

**Comment by rajivshah3** [comment]
> I see it

You saw the error?

> all tests pass

That's odd 🤔 

> Maybe https://forum.realm.io/t/cant-require-realm-on-linux-server/1107/5 can offer an explanation.

As mentioned in https://github.com/realm/realm-js/issues/2180#issue-391435757, I don't believe this is an ElasticBeanstalk issue. I'm able to reproduce this by running the same Docker container on a Mac.

**Comment by kneth** [comment]
> You saw the error?

I see the error but all tests complete.

Do you only see it on Linux? Which C++ compiler do you use?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.

**Comment by rajivshah3** [comment]
Hi, sorry for not responding to this for a while. I think this is fixed as we're no longer seeing the issue
