### ISSUE TITLE
Unable to catch exception on realm error

### ISSUE THREAD

**Issue by programaths** [realm/realm-js#2181]
## Goals

Recovering a bad situation or log for forensic

## Expected Results

Any of the "catch" clause get executed upon error happening in realm library.

## Actual Results

None of the catch clause got executed.

## Steps to Reproduce

Execute the code found at https://gist.github.com/programaths/b1ade98a31c57378d75409819ce4be51
You can toggle `fullSynchronization` at true and false. In both case, the wrapping `try ... catch` should be triggered.

When `true`, the exception should be about invalid schema, it does `Process finished with exit code 134 (interrupted by signal 6: SIGABRT)` instead.
When `false`, the exception should be about invalid realm type, it does drop a stack trace and hang the process.

## Code Sample

https://gist.github.com/programaths/b1ade98a31c57378d75409819ce4be51

You can toggle `fullSynchronization` at true and false. In both case, the wrapping `try ... catch` should be triggered.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.19.1
- Node or React Native: Node
- Client OS & Version: (uname -a) Linux christian-Aspire-TC-605 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Which debugger for React Native: NA

**Comment by kneth** [comment]
@programaths Sorry for the late reply. The second case (setting to false, and the process hangs) is a known issue - you need to terminate the process manually.

Do you see the same behaviour if you use `new Realm()` instead of `Realm.open()`?

**Comment by programaths** [comment]
@kneth Seriously ? 8 months ago is not "late", it is severely late! Since then, I changed job!

And as usual, asking me to test. I am not using that product that is entirely supported by the user base and almost killed a company!

You can safely close that one.
