### ISSUE TITLE
ld: 4 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by cuibeihong** [realm/realm-js#2185]
i use Xcode10.1 run React native xcodeproj
error:

**duplicate symbol __ZN5realm5_impl12partial_sync9WorkQueue13create_threadEv in:
    /Users/div/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/libRealmReact.a(work_queue.o)
duplicate symbol __ZN5realm5_impl12partial_sync9WorkQueueD2Ev in:
    /Users/div/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/libRealmReact.a(work_queue.o)
duplicate symbol __ZN5realm5_impl12partial_sync9WorkQueueD1Ev in:
    /Users/div/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/libRealmReact.a(work_queue.o)
duplicate symbol __ZN5realm5_impl12partial_sync9WorkQueue7enqueueENSt3__18functionIFvvEEE in:
    /Users/div/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphoneos/libRealmReact.a(work_queue.o)
ld: 4 duplicate symbols for architecture arm64**

- Realm JS SDK Version: 2.21.1
- React Native: 0.57.4

i'm sure add & link realm success.
i need help!

**Comment by kneth** [comment]
@cuibeihong This is a bit odd as we don't support 64-bit ARM yet: https://github.com/realm/realm-js/blob/master/react-native/android/src/main/jni/Application.mk#L3

**Comment by kneth** [comment]
@cuibeihong Building with Xcode 10 might be causing trouble. Please use Xcode 9.

**Comment by dakkafex** [comment]
Same issue as of Xcode 11.1, also still with 10, is there a fix for this, or a confirmation that xcode 9 is still the only way?

**Comment by madeeha96** [comment]
Facing same issue!

**Comment by kneth** [comment]
@dakkafex @madeeha96 Which version of Realm JS do you use? Older versions will probably require older versions of Xcode to build. Moreover, if you upgrade from one Realm JS version to a newer version, clearing the build folder can be a good idea.
