### ISSUE TITLE
Realm prblem with "Always Embed Swift Standard Libraries" set to YES

### ISSUE THREAD

**Issue by saadqbal** [realm/realm-js#2191]
My requirement is to set "**Always Embed Swift Standard Libraries**" Flag to **YES** in the project. But when I set it to YES, Realm thows the following error:

`[462:39348] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.`

Realm works fine if the project is compiled with "**Always Embed Swift Standard Libraries**" set to **NO**.

Any possible work around would be greatly appreciated

**Comment by saadqbal** [comment]
I found out that when I integrated Jitsi-meet following [these instructions](https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md). 
I also set the "**Always Embed Swift Standard Libraries**" to **YES** as without it Jisti-meet does not work.

After this when I run the app, it shows the following realm error:
`2018-12-28 16:22:34.504 [error][tid:main][RCTModuleData.mm:179] Realm has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method.`

Jitsi-meet works fine if I remove realm with setting the  "**Always Embed Swift Standard Libraries**" to **YES**.

**Comment by kneth** [comment]
v2.29.2 as a fix for Jitsi-meet.
