### ISSUE TITLE
iOS - Missing Realm constructor even with Manually linking the library

### ISSUE THREAD

**Issue by githubdoramon** [realm/realm-js#2192]
## Goals

Use realm-js in iOS react native application

## Expected Results

Have realm available on the app

## Actual Results

Realm constructor is missing. I have used react-native link and also manually added the libRealmReact.a to link frameworks step. Have tried to require realm after initializing the app as well.

## Steps to Reproduce

Created the project and was never able to use realm on it.... It works fine on Android though. Have tried with different realm versions already. Are there any other ways to debug what can be happening?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.22.0-beta2
- Node or React Native: Node 8, react: 16.6.3, react-native 0.57.8
- Client OS & Version: iOS Device emulator
- Which debugger for React Native: None

**Comment by saadqbal** [comment]
hey @githubdoramon are you using some other library together with realm? e.g JitsiMeet or firebase etc.

I am facing the same issue but only when I add the JitsiMeet library.

**Comment by githubdoramon** [comment]
@saadqbal I am using a few libraries, but have no idea if they could be the problem:

    "react-native-cardview": "1.1.5",
    "react-native-fs": "^2.12.1",
    "react-native-i18n": "1.0.0",
    "react-native-vector-icons": "6.1.0",
    "realm": "2.22.0-beta.2"

Have you been able to track this somehow? Or was lucky to test removing the JitsiMeet?

**Comment by saadqbal** [comment]
@githubdoramon Yup. realm works fine if I remove JItsiMeet. But I need JitsiMeet so will have to find a solution.

**Comment by alihbk** [comment]
i have same problem . missing cosntructor realm . how to solve this ?

**Comment by byk04712** [comment]
+1

**Comment by haripermadi** [comment]
I have the same problem for ios, any solution?

**Comment by githubdoramon** [comment]
I found out that my project was really bad configured, and I was importing react twice (pod linking and manual linking). That created lots of errors, including this one. After organising the project properly things started working again

**Comment by mingxin-yang** [comment]
+1

**Comment by kneth** [comment]
v2.29.2 has a fix related to Jitsi-meet (and probably other libraries).
