### ISSUE TITLE
[iOS] EXC_BAD_ACCESS with developer console open

### ISSUE THREAD

**Issue by neurosnap** [realm/realm-js#2198]
## Goals

Trying to develop application with developer console open on iOS.

## Expected Results

The app periodically crashes with `EXC_BAD_ACCESS`.

## Actual Results

I don't receive any logs inside xcode indicating an error beyond the image linked.

<img width="978" alt="screen shot 2019-01-07 at 10 51 42 am" src="https://user-images.githubusercontent.com/1940365/50777829-9bb9f700-126a-11e9-8ff1-8adb5fc33eb8.png">

## Steps to Reproduce

It is seemingly random.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.1
- Node or React Native: 0.57.8
- Client OS & Version: xcode 10.1 simulator
- Which debugger for React Native: ?/None

**Comment by Andreyco** [comment]
I experience this issue as well, here are my observations

- crashes happens once Realm is open (both, `open` and `openAsync`). If I don't open Realm, app is stable
- crashes are random, even idling app crashes (once Realm is open)
- crashes are experienced **very** often, and **randomly**
- reading/writing works as expected

**Comment by neurosnap** [comment]
@Andreyco do you use `redux-logger`?  I recently removed it from my app and have not see any crashes.

**Comment by Andreyco** [comment]
@neurosnap No I don't but I bet React Native Debugger does. Giving it a shot...!

**Comment by kneth** [comment]
I wonder if v2.28.0 helped. I mean, the refactoring and optimization of the debugging experience might have a stabilizing side-effect too 😄. If it doesn't, please reopen the issue.
