### ISSUE TITLE
Realm.Sync.User.login(SERVER_URL, _credential) type error:network request failed

### ISSUE THREAD

**Issue by amittri** [realm/realm-js#2200]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by bmunkholm** [comment]
@amittri Did you intend to create an issue? Or was this in error?
If you want help, you will need to provide more details as the template outlines.
