### ISSUE TITLE
node- Running node 8.10.0 and realm 2.14.0

### ISSUE THREAD

**Issue by ayalrosenberg** [realm/realm-js#2203]
## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.0
- Node : 8.10.0
- Client OS & Version: MAC OS

Cannot find module '.../node_modules/realm/compiled/node-v57_darwin_x64/realm.node'

Tried with higher versions of 'realm' and getting same error. Used to work. Not working now.

**Comment by annelorraineuy** [comment]
I am getting this same error and its blocking me from building an android apk

**Comment by kneth** [comment]
@annelorraineuy 

Prior to version v2.19.0, we didn't rebuild for node 8 but for node 4, 5, 6, and 7. Please consider upgrading Realm to at least v2.19.0 or downgrade node.
