### ISSUE TITLE
Realm.open opens, closes and reopens connections

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2208]
## Goals

Opening synchronized Realms should be as fast as possible.

## Expected Results

When opening a synchronized Realm with `Realm.open` I expect a single connection to the server which lives until the Realm gets closed.

## Actual Results

When opening a synchronized Realm with `Realm.open` I see a connection being opened and closed before the promise resolves and a new connection being established after that.

I don't know if we would categorize this as a bug, but it's unexpected behaviour that makes opening a Realm, ensuring it's downloaded, updating a value and uploading that, take a little longer than it has to and its really confusing to see disconnects in the client logs when you have a stable connection.

Note: I don't see this behavior using `Realm` as a constructor.

### package.json

```json
{
  "name": "realm-js-connecting-twice",
  "version": "0.1.0",
  "description": "Reproducing a Realm JS issue",
  "main": "index.js",
  "scripts": {
    "start": "DEBUG=realm-js,test node index.js"
  },
  "author": "Kræn Hansen <kraen.hansen@realm.io>",
  "private": true,
  "dependencies": {
    "debug": "^4.1.1",
    "realm": "^2.22.0"
  }
}
```

### index.js

```javascript
const assert = require('assert');
const debug = require('debug');
const Realm = require('realm');

const log = debug('test');

const { SERVER_URL } = process.env;
assert(SERVER_URL, 'Missing a SERVER_URL environment variable');

const LOG_LEVELS = ['all', 'trace', 'debug', 'detail', 'info', 'warn', 'error', 'fatal'];

async function run() {
  // Set a sync logger
  let connectionCount = 0;
  const realmJsLogger = debug('realm-js');
  Realm.Sync.setSyncLogger((level, message) => {
    const levelName = LOG_LEVELS[level];
    realmJsLogger(`${levelName}: ${message}`);
    if (message.indexOf("Connected to endpoint") !== -1) {
      connectionCount++;
    }
  });

  log("Authenticating");
  const credentials = Realm.Sync.Credentials.nickname("tester");
  const user = await Realm.Sync.User.login(SERVER_URL, credentials);

  log("Opening synchronized Realm");
  const config = user.createConfiguration({
    sync: { url: '~/delete-me-again', fullSynchronization: true }
  });
  const realm = await Realm.open(config);
  // const realm = new Realm(config);

  log(`Opened Realm`);
  // Wait a sec for asynchronious behavior to settle
  await new Promise(resolve => setTimeout(resolve, 1000));
  // Close the Realm again
  log(`Closing the Realm`);
  realm.close();
  // Wait a sec for asynchronious behavior to settle
  await new Promise(resolve => setTimeout(resolve, 1000));
  // Assert something about the number of connections
  assert.equal(connectionCount, 1, "Expected a single connection");
}

run().then(() => {
  process.exit(0);
}, (err) => {
  console.error(err.stack);
  process.exit(1);
});
```

### Result of running ☝️ 

Install (`npm install`) and run the start script (`SERVER_URL="https://..." npm start`) to see the following output:

```
  test Authenticating +0ms
  test Opening synchronized Realm +321ms
  realm-js info: Connection[1]: Connected to endpoint '18.197.73.211:443' (from '192.168.2.208:62514') +0ms
  realm-js info: Connection[1]: Disconnected +264ms
  test Opened Realm +369ms
  realm-js info: Connection[2]: Connected to endpoint '18.197.73.211:443' (from '192.168.2.208:62516') +90ms
  test Closing the Realm +1s
  realm-js info: Connection[2]: Disconnected +916ms
AssertionError [ERR_ASSERTION]: Expected a single connection
    at run (/Users/kraenhansen/Repositories/realm-js-issues/index.js:44:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.22.0
- Node or React Native: Node 8.10
- Client OS & Version: MacOS 17.7.0
- Which debugger for React Native: N/A

**Comment by kneth** [comment]
I think it is expected as `Realm.open()` downloads the Realm before opening. We need to download the Realm without schema (otherwise a read-only Realm will break if there are schema changes), close it, and open it with schema after download.

**Comment by kraenhansen** [comment]
> otherwise a read-only Realm will break if there are schema changes

I don't understand this part. I recently learned that read-only Realms applies to the local realm being read-only and therefore make little sense in the context of synchronized Realms. Can you help me see where this closing + reopening happens in the code?

**Comment by kneth** [comment]
@kraenhansen

Yeah, read-only isn't the only reason. If you have schema changes before downloading, the server will have to merge these changes, which might put an extra burden on the server. So it is an optimization to download first and apply changes (if any) before letting the user have access.

The relevant code is `async_open_realm`: https://github.com/realm/realm-js/blob/master/src/js_realm.hpp#L899

**Comment by tgoyne** [comment]
It's not supposed to close and reopen the session. We close and reopen the Realm, but keep the session alive while doing that specifically to avoid having it disconnect and reconnect.

**Comment by kneth** [comment]
We have rewritten how we open Realms recently so I close the issue. If it keeps being an issue, please reopen.
