### ISSUE TITLE
Missing Realm Constructor Error

### ISSUE THREAD

**Issue by LanceMagnaye26** [realm/realm-js#2210]
I was following the **Get Started** guide on the [website](https://realm.io/docs/javascript/latest/#getting-started) I came across the error below and have tried other solutions to the problem but have not gotten any luck. I am running:
 
react-native-cli: 2.0.1
react-native: 0.57.8

<img width="501" alt="missing" src="https://user-images.githubusercontent.com/32000484/51065395-6cccb980-15b9-11e9-96ff-d3f1a415a1f2.png">

I get this error when using the sample code from the website.

**Comment by cmelchior** [comment]
@LanceMagnaye26 I was not able to reproduce this in a standalone React Native project using Realm 2.22.0, can you provide a project where this happens?

**Comment by LanceMagnaye26** [comment]
@cmelchior I just uploaded this to my repo 
https://github.com/LanceMagnaye26/RealmTesting

**Comment by Kyniska** [comment]
same error.
react-native-cli: 2.0.1
react-native: 0.58.6

**Comment by Kyniska** [comment]
What I find really interesting, the realm team provides incomplete code in their example: import { View, Text } from 'react-native' is not included, for example.
For beginners, this could be a source of interference easily remedied.

**Comment by uc-apa** [comment]
Facing this issue on react native v0.60. Realm did not have a podspec so I had to link it manually by dragging the RealmReact.xcodeproj file in project Libraries and adding libRealmJS.a in linked Frameworks and Libraries section. Still getting this error.

![image](https://user-images.githubusercontent.com/25792136/60960508-c3783d80-a327-11e9-9305-dff1a1af7c31.png)

Dependencies are as below:-
    "art": "^0.10.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "buffer": "^5.2.1",
    "crypto-js": "^3.1.9-1",
    "events": "^3.0.0",
    "firebase": "^6.2.4",
    "moment": "^2.24.0",
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-autoheight-webview": "^1.1.4",
    "react-native-color-picker": "^0.4.0",
    "react-native-device-info": "^2.2.2",
    "react-native-fbsdk": "^0.10.0",
    "react-native-fs": "^2.13.3",
    "react-native-google-signin": "2.0.0",
    "react-native-iap": "2.4.8",
    "react-native-orientation-locker": "^1.1.6",
    "react-native-pdf": "^5.0.12",
    "react-native-push-notification": "^3.1.3",
    "react-native-router-flux": "^4.0.6",
    "react-native-svg": "^9.4.0",
    "react-native-tts": "^3.0.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.2",
    "react-native-webview": "^6.3.1",
    "react-native-zip-archive": "^4.1.1",
    "realm": "^2.29.0",
    "rn-fetch-blob": "^0.10.15",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "xml2js": "^0.4.19"

**Comment by dimitarnestorov** [comment]
I get this only when I use "Debug JS Remotely" from the ⌘ + D menu

**Comment by dimitarnestorov** [comment]
Works when debugging in Chrome. Fails when debugging in VS Code.
VS Code: 1.38.1. React Native Tools 0.11.1.

**Comment by HusseinElGanzory** [comment]
> I get this only when I use "Debug JS Remotely" from the ⌘ + D menu. Using Realm 3.1.0 and RN 0.60.5 on iOS and Android.

I downgrad react native tool extension now it works fine

**Comment by kevinnguy** [comment]
> Works when debugging in Chrome. Fails when debugging in VS Code.
> VS Code: 1.38.1. React Native Tools 0.11.1.

I'm also running into this problem as well. Is there a fix for this?

**Comment by dimitarnestorov** [comment]
@kevinadi It's merged, should be in the next release
