### ISSUE TITLE
Convert Realm Cloud Anonymous User into an authenticated User

### ISSUE THREAD

**Issue by apperside** [realm/realm-js#2211]
## Goals

Being able to transform an anonymous user to a regular user.

## Expected Results

I cannot find anywhere in your docs how to do this

The api would look like

```
let currentUser=Realm.Sync.User.current
if(currentUser.isAnonymous()){
    currentUser.authenticate(provider)
}
```

## Actual Results

It appears there is no way to do that

## Version of Realm and Tooling

- Realm JS SDK Version: 2.22.0
- Node or React Native: react-native 0.57.0

**Comment by cmelchior** [comment]
Yes, currently there is no way to convert a user like that. It is, however, something that makes sense to do, but I do not have a timeline.

**Comment by kneth** [comment]
With v10, it is possible to link credentials.
