### ISSUE TITLE
Imperative API for schema manipulation

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2216]
## Goals

To manipulate a Realms schema, Realm Studio currently edits the schema, closes and reopens the Realm with the mutated schema. It would be great if it could create, update and delete properties and classes with an imperative API on a Realm instance.

## Expected Results

I would like the following methods available on an instance of `Realm`:

### Methods for class manipulation
```typescript
function createClass(name: string, properties: Realm.PropertiesTypes, primaryKey?: string): void;
function updateClass(name: string, properties: Realm.PropertiesTypes): void; // ⚠ Might delete or modify existing properties
function deleteClass(name: string): void;
function renameClass(oldName: string, newName: string): void;
```

### Methods for property manipulation
```typescript
function createProperty(className: string, name: string, schema: Realm.ObjectSchemaProperty): void;
function updateProperty(className: string, name: string, schema: Realm.ObjectSchemaProperty): void;
function deleteProperty(className: string, name: string): void;
function renameProperty(className: string, oldName: string, newName: string): void;
```

**Comment by bmunkholm** [comment]
@kraenhansen Is this done now?

**Comment by kraenhansen** [comment]
I believe this can be considered done with #2251 - but we still need tests on what happens when the user calls `_updateSchema` with destructive schema changes and at some point we should consider making this API properly documented and public.
