### ISSUE TITLE
Requiring realm should be lightweight

### ISSUE THREAD

**Issue by ironage** [realm/realm-js#2218]
A user [reports](https://github.com/realm/realm-js/issues/2217) that in realm@2.20.1 `const Realm = require('realm');` will try to open a file on disk by way of `realmConstructor.Sync._initializeSyncManager`. Simply requiring Realm as a dependency should not cause a write to disk and as far as I know, there should be no reason to initialise the sync manager for projects that are only using realm locally. We should initialise on the fly, when a sync session is requested the first time.

This behaviour seems to have been added by https://github.com/realm/realm-js/pull/2114
@cmelchior I'll assign this to you in case there is a reason I do not see that this was changed.

**Comment by roberhofer** [comment]
@cmelchior : would you mind commenting on this? If initialization is not required for local realm, then let's remove.

**Comment by bmunkholm** [comment]
@roberhofer There is already a PR for this #2222.
