### ISSUE TITLE
Realm not defined error on opening realm file on windows realm studio

### ISSUE THREAD

**Issue by bhavin1701** [realm/realm-js#2224]

**Comment by bhavin1701** [comment]
![untitled](https://user-images.githubusercontent.com/29137795/51344575-f3c0dc80-1a66-11e9-8d8a-b6380797e91e.png)

**Comment by bhavin1701** [comment]
working fine on mac OS on realm browser

**Comment by ironage** [comment]
Issue moved to [realm/realm-studio #1086](https://github.com/realm/realm-studio/issues/1086) via [**ZenHub**](https://www.zenhub.com/)
