### ISSUE TITLE
realm crashes App when creating object with missing parameter when debugging

### ISSUE THREAD

**Issue by AlexBueckig** [realm/realm-js#2232]
## Goals

Insert a new object with missing a required parameter while having a debugger running

## Expected Results

realm throws exception or any kind of error as without debugger.

## Actual Results

App straight up crashes...

## Steps to Reproduce

Run App [from this repository](https://github.com/AlexBueckig/RealmTest) with debugger active

## Code Sample
Schema-definition:
```
const CarSchema = {
  name: 'Car',
  primaryKey: 'id',
  properties: {
    id:    'int',
    make:  'string',
    model: 'string',
    miles: {type: 'int', default: 0},
  }
};
```

Insert-Code:
```      
realm.open({schema: [CarSchema], schemaVersion: 1}).then(realm => {
    realm.write(() => {
          console.log('Creating first car...');
          const myCar = realm.create('Car', {
            id: 1,
            make: 'Honda',
            //model: 'Civic', // Omitting required parameter -> Crashes... With parameter -> no crash
            miles: 1000
          });
          console.log('Updating mileage...');
          myCar.miles += 20; // Update a property value

          /* Should show a car object if successful */
          console.log(JSON.parse(JSON.stringify(myCar)));
    });
}).catch((error) => console.log(error));
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.22.0
- Node or React Native: RN 0.57.8 with Node 10.13 created with react-native-cli
- Client OS & Version: Win 10
- Which debugger for React Native: React-Native-Debugger [v0.8.2](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.8.2)

**Comment by kneth** [comment]
@AlexBueckig We have worked a bit on the debugging component recently so please try to upgrade.
