### ISSUE TITLE
iOS device crash at JSGlobalContextRelease

### ISSUE THREAD

**Issue by cesargdm** [realm/realm-js#2233]
## Goals
Use realm in device **while remote debugging**

## Actual Results
While not making any read or write, (actually happens moments after writing data and being queried), the app suddenly crashes at physical iOS device at line 41 in file `RealmJS.xcodeproj/RealmJS/JSC/jsc_protected.hpp`.

```obj
~Protected() {
        if (m_context) {
            JSGlobalContextRelease(m_context);
        }
    }
```

NOTE: Only happens while remote debbuging

## Steps to Reproduce
Run on device, debbuging mode.
After crash some data happens to be missing.

## Code Sample
```javascript
// TabNavigation.js

export let realm

class TabNavigationScreen extends PureComponent {
  async connectRealm() {
    try {
      realm = await openRealm()
    } catch (error) {
      console.warn('Realm error', error)
    }
  }
}
```

```javascript
// realm/index.js
export const openRealm = () => {
  return Realm.open({
    schema: [
      OfflineServiceSchema,
      OfflineUnitServiceSchema,
      OfflineUnitServiceStatusSchema,
      PlagueCountSchema,
    ],
  })
}
```

## Version of Realm and Tooling
* Realm JS SDK Version: 2.21.1
* React Native: 0.57.8
* Client OS & Version: iOS 12
* Which debugger for React Native: Chrome

**Comment by cesargdm** [comment]
<img width="1215" alt="screen shot 2019-01-29 at 5 05 39 pm" src="https://user-images.githubusercontent.com/10179494/51946748-20221480-23e8-11e9-8081-e96a076a2038.png">

**Comment by AKACC** [comment]
@cesargdm any solution?

**Comment by cesargdm** [comment]
@AKACC Didn't find any, migrated to WatermelonDB

**Comment by Mscynol** [comment]
It's a serious problems,
I often meet it and make me feel confused

**Comment by ameenmattar** [comment]
Still facing the problem, realm version: "^2.29.2",

**Comment by webforuse** [comment]
Still facing this problem !!!

-realm version: "^3.3.0",
-react-native: "0.60.4",
<img width="1463" alt="изображение" src="https://user-images.githubusercontent.com/37406224/68235608-98230800-0014-11ea-9a2f-188967e6f157.png">

impossible debuging process !!!

**Comment by Finneah** [comment]
realm is still not usable! 
I'm not ready to waste my time and constantly restart the app just because it's constantly crashing because of realm!

Either debugging OR realm .. I choose to debug. 
A pity. I've been watching this for a year now, desperately waiting for you to fix that. I really wanted to use relam. But my patience is finished.

**Comment by mrarronz** [comment]
Same issue happened to my app! This crash happens not very often, but really annoying!

**Comment by bmunkholm** [comment]
Closing this as it will be resolved with the support for Hermes and the Flipper debugger. Please see [here ](https://github.com/realm/realm-js/issues/3940) to try it out and provide feedback. Thanks for your patience!
