### ISSUE TITLE
Can't get Realm to work on iOS for React Native 0.58.0

### ISSUE THREAD

**Issue by ferrannp** [realm/realm-js#2239]
Can't get Realm to work with iOS with the new React Native 0.58.0. I tried to update from 0.57.x and the iOS project was not compiling. I tried a new project and:

## Steps to Reproduce

```
react-native init YourProject
yarn add realm
react-native link realm
```

![simulator screen shot - iphone x - 2019-01-25 at 16 42 15](https://user-images.githubusercontent.com/774577/51756329-05d2f880-20c1-11e9-84b1-e742efc098af.png)

## Code Sample

https://github.com/ferrannp/realm-react-native-test

## Version of Realm and Tooling

- Realm JS SDK Version: 2.22.0
- React Native: 0.58.0

**Comment by cesargdm** [comment]
x2

**Comment by nvuhung** [comment]
Same issue on iOS :(

**Comment by abanobboles** [comment]
Same issue on iOS, how can I use realm with an old react native version?

**Comment by felixus95** [comment]
iOS

**Comment by dsemenov** [comment]
Same story with React Native 0.58.1, 0.58.2 and 0.58.3

**Comment by jtweaver** [comment]
Same. Is realm ready for react-native 0.58.* or do we need to downgrade?

**Comment by sorinns** [comment]
+1
react-native 0.58.3, realm 2.22.0
unfortunately I had to rollback to react-native 0.57.1

**Comment by bmunkholm** [comment]
It appears react-native 0.58 broke something. Until this is fixed it's recommended to downgrade to 0.57.1

**Comment by plouh** [comment]
RN 0.58 updated JavaScriptCore and it is now needed as a framework dependency, so it was a major change in that respect and I suspect it has everything to do with realm breaking.  

In addition android should now have support for 64 bit binaries so it is another possible cause for android problems.

**Comment by bmichotte** [comment]
Same here, realm is unusable with RN 0.58+.
Any news / ETA realm team ?

**Comment by cmelchior** [comment]
We are working on fixing it here: https://github.com/realm/realm-js/pull/2242
No ETA yet.

**Comment by vinpro24** [comment]
> ETA

@cmelchior How to fix it? Im also getting the same error. react-native 0.58.3, realm 2.23.0

**Comment by ferrannp** [comment]
@vinpro24 you need to wait till #2242 is completed and released.

**Comment by cesargdm** [comment]
In the meanwhile I've migrated my project to https://github.com/Nozbe/WatermelonDB .If it's help for anyone

**Comment by pieter888** [comment]
Is there a workaround in the meantime except for downgrading react-native to 0.57?

**Comment by renalpraba** [comment]
react-native 0.59 is nearly here, I think it's good to make sure the fix is runable on 0.59 if that breaks something new too

**Comment by renalpraba** [comment]
#2242 says all checks have passed, waiting for more info 👍

**Comment by Joyreece** [comment]
same issue on iOS (React Native 0.58.5 & Realm 2.21.0).

**Comment by vdlindenmark** [comment]
#2242 is merged, so it should be fixed?

**Comment by bmunkholm** [comment]
@vdlindenmark and others - it should now work in realm-js 2.24.0 - please try it out and let us know if it works for you.

**Comment by pieter888** [comment]
Can confirm this issue is resolved for me in react 0.58.5.

I did encounter issue https://github.com/realm/realm-js/issues/2259 after installing Realm 2.24.0.
But it works after adding the latest "decompress" and "https-proxy-agent" to my package.json as a workaround.

**Comment by sorinns** [comment]
confirmed for me too
react-native 0.58.6 + realm 2.24.0 works

**Comment by ferrannp** [comment]
Thanks for fixing this @tgoyne !

**Comment by Noly1990** [comment]
Thank you, I had got the same problem, and now, update the realm from 2.23.0 to 2.24.0, works no bugs with react-native 0.58.5.
