### ISSUE TITLE
when debugging realm collection listeners behave unexpectedly.

### ISSUE THREAD

**Issue by xcxooxl** [realm/realm-js#2240]
Building a chat application, My data flow that new messages/conversations are being saved directly to realm, Then I have a listener on the collection of conversations and that is updating my state (react-redux).

When I have debugger attached (react-native) something very strange happens
## Goals

```
    handleChanges: (entities, changes) => {
        let entitiesCopy = entities.map((item) => {
            return item
        });

        if (changes.insertions.length && !entitiesCopy.length)
            debugger; // This condition returns true! Only when debugger attached.

        this.store.dispatch({type: "UPDATE_CONVERSATIONS", data: entitiesCopy});
    },
```

Only change state when a conversation is deleted or added.

I expected that if there was an insertion it would also appear in the entities array.

## Actual Results
The entity didn't appear in the entities array.

I updated my state with wrong data.

No crash, Just wasting resources, rerendering my FlatList many times. (This happens even when no insertion should happen
## Steps to Reproduce

I guess just listen to a collection with debugger attached, Also I am adding new messages with setInterval that happens every second or so (for testing purposes).

## Code Sample

Code that saves new messages, 
```
        databaseService.db.write(() => {
            // Build conversation
            let conversationId = `${author.id}-${adItem.id}`;
            let conversation = new Conversation();
            conversation.adItem = adItem;
            conversation.id = conversationId;

            // Update Or Create.
            databaseService.db.create('Conversation', conversation, true);

            // Build message
            let msg = new Message();
            msg.author = author;
            msg.conversation = conversation;
            msg.body = body;
            msg.unread = true;
            msg.conversationId = conversationId; // Because sometimes conversation property is null ???
            msg = databaseService.db.create('Message', msg, true);

            let messages = conversation.messages || [];
            messages.push(msg);
            conversation.messages = messages;

            // Only create new message array if not exists already and add message.
            if (!conversation.participants || !conversation.participants.length)
                conversation.participants = [author];
        })
```
## Version of Realm and Tooling

- Realm JS SDK Version:  2.22.0
- Node or React Native: ? 0.57.8
- Client OS & Version: Android API 28
- Which debugger for React Native: Chrome devtools

**Comment by reyalpsirc** [comment]
I'm also having the same problem with the listeners I have. Some are invoked but other aren't when debugging (but works well when in production).
However in my case, it fails mostly when using the relations (and updating the linked object)

**Comment by kneth** [comment]
Both v2.24.0 and v2.28.0 touched debugging. If you still experience the issue, please reopen it.
