### ISSUE TITLE
Expose a hasActiveSessions property

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2248]
In ROS tests, we call `clearTestState` after almost all tests, but that's subject to timing-related issues as there might be some sessions that have not yet been inactivated. Currently, we work around it by waiting arbitrarily (100 ms) before calling the method. Instead, realm-js should expose a `hasActiveSessions` property which we can periodically poll to ensure we don't hit assertion failures.

Also, it would be useful to be able to specify the session stop policy - in tests, I would rather sessions are terminated immediately after the Realm is closed.

**Comment by nirinchev** [comment]
@roberhofer can we prioritize that - it's supposedly a low effort issue, but it's a major source of pain for fixing the reliability of the ROS tests.

**Comment by roberhofer** [comment]
Can you check with whomever you need help with? If this is low effort and blocking reliable ROS tests then just agree within engineering to get this done. If in doubt ask @geragray .

**Comment by cmelchior** [comment]
I can take a look at this today. I believe ObjectStore has a function for this so shouldn't take long.

**Comment by nirinchev** [comment]
I couldn't find one, but it'd be fairly trivial to expose it - we just need to extract the condition that's throwing the assertion into a different function.

**Comment by cmelchior** [comment]
Yes, I discovered that as well. I'm updating ObjectStore right now.

**Comment by cmelchior** [comment]
`Realm._hasExistingSessions()` and `Realm.Sync.SyncConfiguration._sessionStopPolicy` has been added and merged.
