### ISSUE TITLE
unfortunately app has stopped react native ( after installing realm )

### ISSUE THREAD

**Issue by acaliht** [realm/realm-js#2249]
Hello
after react-native init myapp
i install the realm
but when react-native run-android
app is not running

 "unfortunately app has stopped react native"
react native : 0.58.4
realm : latest version of realm

**Comment by mimoune** [comment]
hi,you can resolve this issue with adding this instruction :
`ndk {
        abiFilters 'armeabi-v7a', 'x86'
        }`
in "defaultConfig" section in  "android/app/build.gradle" file
Demo:
[https://drive.google.com/file/d/1xAA6uhSlqtmOx13f5omlVnv_AiUdxPvb/view](url)

**Comment by acaliht** [comment]
Worked !!
Thank You  :) <3

**Comment by hsnMoghadasi** [comment]
Thank you

**Comment by monstruSSG** [comment]
Worked for me !! Thanks

**Comment by madeeha96** [comment]
Error still exists. Attaching screenshit 
<img width="1131" alt="Screenshot 2019-10-20 at 11 22 55 AM" src="https://user-images.githubusercontent.com/33419910/67155610-0c2e9200-f32c-11e9-96dc-468b39913460.png">

**Comment by hsnMoghadasi** [comment]
> Error still exists. Attaching screenshit
> <img alt="Screenshot 2019-10-20 at 11 22 55 AM" width="1131" src="https://user-images.githubusercontent.com/33419910/67155610-0c2e9200-f32c-11e9-96dc-468b39913460.png">

update realm  to 2.28.0 version
it's gonna be fixed.

**Comment by trungnguyencmu** [comment]
+1, I still got app has stopped when I build to apk file and install in real phone. It's still run good in simulator :(

**Comment by Temirtator** [comment]
@trungnguyencmu did u solve this problem?

**Comment by brunofunnie** [comment]
> ndk { abiFilters 'armeabi-v7a', 'x86' }

After installing/using Realm in the app it started to crash, but only in the first execution, after it created the default.realm file it opens normally. Adding the ndk line fixed this issue.

React Native 0.63.2
Realm 6.0.4

**Comment by gustavo-dev** [comment]
I added 

> ndk { abiFilters 'armeabi-v7a', 'x86' }

but now I get an error build
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Conflicting configuration : 'armeabi-v7a,x86' in ndk abiFilters cannot be present when splits abi filters are set : x86_64,x86,armeabi-v7a,arm64-v8a
```

**Comment by workpebojot** [comment]
Android Studio: https://developer.android.com/ndk/guides/abis#gc (They Updated it)
`android {
    defaultConfig {
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }
}`

**Comment by fronck** [comment]
@workpebojot  Thanks for reporting that.

**Comment by 3gcodes** [comment]
I'm still having this issue.

```
splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
```

I've tried setting the abiFilters to either of those, and the app just crashes when trying to launch. React-Native 0.63.x.

**Comment by rianonehub** [comment]
Turn off Hermes feature on `android/app/build.gradle`
`
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]
`
worked for me on RN 0.63

**Comment by mrezaslk** [comment]
@rianonehub you save my time.thanks
