### ISSUE TITLE
Support IN queries for list properties

### ISSUE THREAD

**Issue by appden** [realm/realm-js#225]
I created a branch (`sk-list-queries`) that contains a failing test that should pass, so please use that (and expand the test) when we implement this feature.

**Comment by Kureev** [comment]
Any updates?

**Comment by alazier** [comment]
@Kureev not yet. In the meantime you can generate the equivalent query string by OR ing together individual comparisons.

**Comment by ashwinphatak** [comment]
I don't see the `sk-list-queries` branch anymore. How should the API for this look like?

**Comment by kneth** [comment]
We rely on core's query language, and once that supports it, we will automatically support it.
