### ISSUE TITLE
Realm Get Wrong Context on React-Native

### ISSUE THREAD

**Issue by nowarzz** [realm/realm-js#2256]
## Goals
Install on React-Native

## Expected Results
Working fine

## Actual Results
Could not find variable 'Symbol'.

Problems is:
on realm/index.js line 56:
`  if (typeof atob !== 'undefined') {
            return 'chromedebugger';
        }`
and
realm/index.js line 111:
`    case 'chromedebugger':
    case 'vscodedebugger':
        realmConstructor = require('./browser').default; // (exported as ES6 module)
        break;`

that Realm detect React-Native as chromedebugger because of atob is not undefined.

## Steps to Reproduce
1. Create RN Project
2. Add react-native-queue (which has dependency to realm).
3. Import react-native-queue to components.
4. Run it.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.23.0
- Node or React Native: Node: 8.12.0 React Native: 0.58.5
- Client OS & Version: Android 8.1.0 Build number sdk_gphone_x86-userdebug 8.1.0 (emulator) and 9 PKQ1.180729.001 (Xiaomi Pocophone F1)
- Which debugger for React Native: None

**Comment by radeno** [comment]
@nowarzz same as https://github.com/realm/realm-js/issues/2239
