### ISSUE TITLE
Support RNPM

### ISSUE THREAD

**Issue by appden** [realm/realm-js#226]
It's becoming the de facto way for clients to link in React Native plugins. Supporting it shouldn't be too difficult: https://github.com/rnpm/rnpm

**Comment by appden** [comment]
I think we should really add support for this, but I think it would require landing a PR to support embedded frameworks rather than static libraries. It's not too difficult given I already did something very similar in the Cordova branch.

**Comment by alazier** [comment]
I think we should support this at some point but it is lower priority than supporting our current users or building user requested features.

**Comment by jwhitley** [comment]
Until that time, I'll suggest that a prominent warning that rnpm doesn't work (yet) should be added to the getting started docs.  rnpm has gotten so good, that I often assume that projects which don't list it just haven't found out about it yet (which is exactly what has happened on several occasions so far).

Conversely, it's surprising when it fails, and that led me on a merry chase with essentially zero useful messaging that my project setup was borked.

**Comment by appden** [comment]
@jwhitley good idea!

@alazier React Native is merging in `rnpm` to officially become part of the project, so its importance will suddenly rise and we may instead need to send the PR to RN instead.
