### ISSUE TITLE
Cannot read property then of undefined

### ISSUE THREAD

**Issue by denchp** [realm/realm-js#2270]
I'm working on updating our project to RN .58 - from .47, and updating Realm alongside.

I've updated packages, pods, linked project, but I am getting missing dependencies, which I've worked-around by adding to our package.json:

    "https-proxy-agent": "2.2.1",
    "decompress": "4.2.0",
    "command-line-args": "5.0.2"

However, I'm now hitting a new error:

> Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
>   SYNC_ARCHIVE: 'realm-sync-cocoa-3.15.0.tar.gz',
>   SYNC_ARCHIVE_ROOT: 'core' }
> No lockfile found at the target, proceeding.
> /.../node_modules/realm/scripts/download-realm.js:134
>         .then(() => corePath && download(desired.CORE_SERVER_FOLDER, desired.CORE_ARCHIVE, corePath))
>         ^
>
> TypeError: Cannot read property 'then' of undefined
>     at acquire (/.../node_modules/realm/scripts/download-realm.js:134:9)
>     at Object.<anonymous> (/.../node_modules/realm/scripts/download-realm.js:261:5)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
> Command PhaseScriptExecution failed with a nonzero exit code
> 

- Realm JS SDK Version: 2.24.0
- Node or React Native: Node 10.x, RN .58
- Client OS & Version: OSX

**Comment by denchp** [comment]
Clean and build fixed the latest problem...

**Comment by aidan2129** [comment]
Having the same issue tried removing node_modules and re-installing but still the same.

**Comment by denchp** [comment]
What version are you updating to?  We've attempted to go to 59 - but Realm reportedly has issues with it - specifically 64-bit compatibility.

**Comment by M1K3Yio** [comment]
@aidan2129 I encountered this issue myself with upgrading to RN 0.59.  0.59 now supports 64bit, which Realm currently does not.  

In your app/build.gradle if you add the following to remove 64bit, until realm support this should work for you.
```
android {
...
    packagingOptions {
        // exclude everything 64bit related
        exclude '/lib/mips64/**'
        exclude '/lib/arm64-v8a/**'
        exclude '/lib/x86_64/**'
    }
}

**Comment by aidan2129** [comment]
@M1K3Yio My issue is on mac when running npm install.

**Comment by aidan2129** [comment]
@M1K3Yio @denchp Im on 0.59.0 its working fine on android.
