### ISSUE TITLE
Unable to open a realm at path: Unsupported Realm file format version.

### ISSUE THREAD

**Issue by joshuapinter** [realm/realm-js#2276]
Hey Guys,

I have a `.realm` file that will not open up on my React Native app but it opens up just fine on the latest Realm Studio. I can't seem to find any additional information about the version or anything of the `.realm` file itself. 

I'm attaching it here. Are you able to see what version of `realm` package we need or whatever in order to open this on my React Native app. This is preventing all of our users from opening up the app at all. 

Really appreciate your insight here. 

Thanks!

Joshua

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.0
- Node or React Native: v10.11.0 and 0.39.2
- Client OS & Version: macOS 10.14.3
- Which debugger for React Native: XCode

[realm files.zip](https://github.com/realm/realm-js/files/2943826/realm.files.zip)

**Comment by joshuapinter** [comment]
Nevermind. I fixed it by updating to `realm` version 2.23.0. I also cleared out any existing build products and relinked the `realm` package. Now we're back up and running. Likely having to do with an older realm core library or something.

**Comment by guandaxia** [comment]
![image](https://user-images.githubusercontent.com/9638813/72702954-460f6e80-3b8f-11ea-952f-9d1727a511fc.png)
have you see this tips? I guess the latest Realm Studio upgrade realm db file version , then the client can not open the db file.

I use Realm Studio version is Version 3.9.0-beta.0
