### ISSUE TITLE
Creating child object without parent object

### ISSUE THREAD

**Issue by zek** [realm/realm-js#2284]
## Goals

I am trying to create a new chat message without accessing chat object. (Without using chat.push)

## Actual Results

Created ChatMessage object has no relation with Chat object. So chatmessage.chat is just empty.

## Code Sample

~~~
class ChatMessage extends Realm.Object {
  static schema = {
    name: 'ChatMessage',
    primaryKey: '_id',
    properties: {
      _id: 'string',
      message: 'string',
      createdAt: 'date',
      user_id: 'int',
      chat: { type: 'linkingObjects', objectType: 'Chat', property: 'messages' },
    },
  }
}

class Chat extends Realm.Object {
  static schema = {
    name: 'Chat',
    primaryKey: 'id',
    properties: {
      id: 'int',
      private: { type: 'bool', default: true },
      messages: 'ChatMessage[]',
      participants: 'int[]',
    },
  };
}
realm.create(Chat, {
    id: 12,
    participants: [56, 1],
  })

realm.create(ChatMessage, {
    _id: "12",
    message: 'test',
    createdAt: new Date(),
    user_id: 5,
    chat: 12,
  });
~~~

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.24.0
- Node or React Native: ? React Native
- Client OS & Version: ? 
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
It is the expected behaviour. You don't link the `ChatMessage` to any `Chat`, and your single `Chat` object (with `id` = 12) will have an empty `messages`.

The `chat` property in `ChatMessage` is not used to populate the `message` list. It is actually a read-only property, and I guess we should throw an error in this case.
