### ISSUE TITLE
Crash: Cannot create asynchronous query while in a write transaction

### ISSUE THREAD

**Issue by yanjie311** [realm/realm-js#2287]

**Comment by yanjie311** [comment]
![0A706162-1D89-4E7A-8B2D-ED3A73886897 jpg](https://user-images.githubusercontent.com/20129277/54502918-f1480980-4967-11e9-988d-a4cc0bf28a41.png)

**Comment by ianakiara** [comment]
This can happen if you are doing findAllAsync inside a change listener
https://github.com/realm/realm-java/issues/5771#issuecomment-442004078

This solved my issue ☝️

**Comment by Zhuinden** [comment]
a trick I've seen people do is that they run the `findAllAsync` inside a `handler.post {` so that they would be on the next event loop, and not when the transaction is updating the RealmResults.
