### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 69

### ISSUE THREAD

**Issue by roytan883** [realm/realm-js#2291]
```
electron-v4.0_win32_x64\realm.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)
```

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.25
- Node or React Native: ? Node
- Client OS & Version: ? Windows
- Which debugger for React Native: ?/None

can you re-compile realm for windows electron node with version 69. I try to re-compile it by myself, but failed.

**Comment by roytan883** [comment]
from electron 4.0.4, it use NODE_MODULE_VERSION 69
so, current this 
> https://static.realm.io/node-pre-gyp/2.25.0/realm-v2.25.0-electron-v4.0-win32-x64.tar.gz 
compiled version is wrong, which use NODE_MODULE_VERSION 64

**Comment by budescode** [comment]
hi, where should I keep the file in my project folder?

**Comment by roytan883** [comment]
current server URL is:

> https://static.realm.io/node-pre-gyp/2.25.0/realm-v2.25.0-electron-v4.0-win32-x64.tar.gz

> https://static.realm.io/node-pre-gyp/2.25.0/realm-v2.25.0-node-v64-win32-x64.tar.gz

current local path is: 
> node_modules\realm\compiled\electron-v4.0_win32_x64\realm.node

> node_modules\realm\compiled\node-v64_win32_x64\realm.node

maybe need provide new : 
> https://static.realm.io/node-pre-gyp/2.25.0/realm-v2.25.0-node-v69-win32-x64.tar.gz

> https://static.realm.io/node-pre-gyp/2.25.0/realm-v2.25.0-electron-v4.0-win32-x64.tar.gz (compiled by NODE_MODULE_VERSION 69)

**Comment by kneth** [comment]
We current build and release for Electron 2.0, 3.0, 3.1, 4.0, 4.1, and 4.2.
