### ISSUE TITLE
[Android] undefined is not an object (evaluating '_NativeModules$Realm.debugHosts')

### ISSUE THREAD

**Issue by matheusgrieger** [realm/realm-js#2294]
## Goals

Simply trying to launch the app. After installing Realm Database it has worked and I could successfully write data to it. Since then, it just doesn't launch anymore. Tried to rebuild, clear caches, and really, tried everything I know of. Followed all steps from the docs and troubleshooting, and tried many solutions from the other related issues (#1150, #527, #762), but nothing seems to work.

## Expected Results

Launch the app normally (not using Realm on startup or anything like that, it only gets called upon touching a button).

## Actual Results

![image](https://user-images.githubusercontent.com/6992464/54630785-621b1e80-4a59-11e9-992e-469d0696df9f.png)

Above image is from an emulator.

Also tried to get a stacktrace from the Android Device Monitor, however, I am being unsuccessful.

## Steps to Reproduce

Install Realm normally, check all changes from `react-native link` are OK, write some data, and restart the app.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.25.0
- React Native: 0.57.4
- Which debugger for React Native: None

**Comment by matheusgrieger** [comment]
It has stopped and started working when I enabled remote JS debugging. However, that's likely a bug, since every time the app is being tested, it is obligatory to have remote debug enabled.

**Comment by epshtielsl** [comment]
I am getting this error even though remote debugging is disabled...

**Comment by matheusgrieger** [comment]
@epshtielsl it worked for me when I enabled remote debugging only...

**Comment by kneth** [comment]
@matheusgrieger Do you debug under VSCode and its react-native plugin?

We did a bit of refactoring of the RN debugging code in v2.28.0, so it might be worth upgrading.

**Comment by matheusgrieger** [comment]
We gave up on React Native and went back to hybrid solutions using Cordova. RN was running too slow for our project...

**Comment by borysstach** [comment]
I have very similar issue on upgrade from 1.13.0 to 2.29.2
"null is not an object (evaluating '_NativeModules$Realm.debugHosts')" only without debugger
Fixed it by removing this check: https://github.com/borysstach/realm-js/commit/5518dd3c700d90cf9c1b2deadfdcc29425c9d814
