### ISSUE TITLE
Ability to get the Realm that manages the object

### ISSUE THREAD

**Issue by v-ken** [realm/realm-js#2295]
## Goals

Ability to get the `Realm` instance that manages the current `Object`.
iOS has the ability:
https://realm.io/docs/swift/3.13.1/api/Classes/Object.html#/s:10RealmSwift6ObjectC5realmAA0A0CSgvp

## Expected Results

`myRealmObject.realm` should return the Realm instance that manages the current object

**Comment by cmelchior** [comment]
There is actually an undocumented `_realm` property that returns the Realm. We could consider making it public since it is already public in the Java and Swift API's

**Comment by bentron2000** [comment]
Any chance you can put this in the 'easy win' pile? inc TypeScript :) Would love to get rid of all these 
`// @ts-expect-error // unTyped API` comments :P
