### ISSUE TITLE
Performance impact with huge data insertions

### ISSUE THREAD

**Issue by kmvkrish** [realm/realm-js#2300]
We have an API paginated over 5000 records with 500 per page. Each page's response is of 550KB in size. As soon as a page's response is obtained, we write the data to the realm DB using **`realm.create()`** method.
What we have observed is, when the Realm table has 2000 records inserted, the insertions from 2001-5000 are taking **2seconds per insertion**. This is again causing an issue to the UI in our react native app.

Also, we have another API with 50000 records paginated with 500 records per page. Each page's response is of 50KB size. The insertions of **50000 records took nearly 2 minutes 50 seconds.** But for **5000 records, it took 24 minutes**, surprisingly.

Our app's UI was unresponsive for almost 24 minutes due to such slow insertions. Is there a way, we can optimise the insertions of such a huge data?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.1
- Node or React Native: node-8.12.0, RN-0.57
- Client OS & Version: Android Oreo (8.0)
- Which debugger for React Native: Samsung Galaxy Tab S3 device, running Android Oreo.

**Comment by bmunkholm** [comment]
Please make a small self contained repro that illustrates the problem with Realm alone. I'm very certain something else is the issue. Inserting 5000 records should not take 24 minutes. Even though I obviously don't know how big a record is.

Are you inserting each record as a separate transaction or making one transaction with 500 records per transaction?
How big is each record?

**Comment by aureliopetrone** [comment]
> when the Realm table has 2000 records inserted, the insertions from 2001-5000 are taking 2seconds per insertion. This is again causing an issue to the UI in our react native app.

@kmvkrish @bmunkholm same issue here

**Comment by kmvkrish** [comment]
> Please make a small self contained repro that illustrates the problem with Realm alone. I'm very certain something else is the issue. Inserting 5000 records should not take 24 minutes. It's not clear to me how the two insertions of 50000 records in 2:50 and 5000 in 24:00 differs?
> 
> Are you inserting each record as a separate transaction or making one transaction with 500 records per transaction?

@bmunkholm Our API's response contains 500 records per page and **each record is of size nearly 1.5KB**. Total API response of 5000 records is approximately **7MB**

Yes, each record is inserted in a **separate transaction**. **We also tried to insert 500 records in a single transaction. But the insertion time reduced to a few MilliSeconds only**

**Comment by bmunkholm** [comment]
@kmvkrish and @aureliopetrone 
How exactly are you testing this and measuring performance? 
If you are doing this in a debugger, that's the issue.
Here I provided a simple sample that demonstrates performance: https://github.com/realm/realm-js/issues/2154#issuecomment-453068402. Please take that and modify to match your model and validate your performance for your example.
Thanks!

**Comment by kmvkrish** [comment]
> @kmvkrish and @aureliopetrone
> How exactly are you testing this and measuring performance?
> If you are doing this in a debugger, that's the issue.
> Here I provided a simple sample that demonstrates performance: [#2154 (comment)](https://github.com/realm/realm-js/issues/2154#issuecomment-453068402). Please take that and modify to match your model and validate your performance for your example.
> Thanks!

@bmunkholm We are using real device - **Samsung Galaxy Tab S3** with the below configuration.
1. OS: Android Oreo (8.0)
2. RAM: 4GB
3. Storage: 32GB built-in memory.

We installed our app in the device, and made the API calls. For each API call response, we are initiating DB insertions by iterating over 500 records in the response.
For every insertion, the app logs the start and end time. We are monitoring them for the app performance.

**Comment by bmunkholm** [comment]
@kmvkrish Ok then it's not the debugger that tricks you. I'm sure something else is though.
Please make a synthetic test where you take a sample of your data and model and replicate the issue in a standalone sample app. I can't guess what wrong with your code or if it's indeed Realm that is slow. The code sample I shared in above comment doesn't indicate that it is Realm that is slow.

**Comment by kmvkrish** [comment]
> @kmvkrish Ok then it's not the debugger that tricks you. I'm sure something else is though.
> Please make a synthetic test where you take a sample of your data and model and replicate the issue in a standalone sample app. I can't guess what wrong with your code or if it's indeed Realm that is slow. The code sample I shared in above comment doesn't indicate that it is Realm that is slow.
> Can you time just the Realm insertions and show the code?

@bmunkholm Sure, I will share you the code where the db insertions start, along with the logs.

> But, for a simple NodeJS app, the realm-js insertions would be fast, as the server uses the system's configuration. But for a limited memory devices like Phones/tablets, the environment is a bit different. Testing on the real physical device is the best thing to know the issue

**Comment by kmvkrish** [comment]
> @kmvkrish Ok then it's not the debugger that tricks you. I'm sure something else is though.
> Please make a synthetic test where you take a sample of your data and model and replicate the issue in a standalone sample app. I can't guess what wrong with your code or if it's indeed Realm that is slow. The code sample I shared in above comment doesn't indicate that it is Realm that is slow.
> Can you time just the Realm insertions and show the code?

@bmunkholm Here is the sample app we developed using React Native. You can also find the logs in the repository for 2 different scenarios.

- DB schemas without back-linking 
- DB Schemas with back-linking

Both scenarios took same time.

Surprisingly, this demo app took only 20 seconds of time to save all the records. But, when we implement the same in our actual app, it took more than 25minutes, even though we used the same DB insert call.

`realmInstance.write(() => {
    realmInstance.create(
        <SchemaName>,
        {<Schema record data in JSON structure>},
        <toUpdateIfExists>
    );
});`

You can find this in the App.js file.

**Comment by bmunkholm** [comment]
@kmvkrish Well, you are obviously doing something else that takes the time - this test shows that Realm doesn't appear to be what's taking the time? Agree?

For this test I would even suggest to skip all the logging and just do one write transaction for all or for every 1000 records. That should speed it up. But this is not your issue.

Obviously, I can't tell you what else is taking the time, you would have to measure that yourself.

**Comment by kmvkrish** [comment]
@bmunkholm, this is our demo app. Our actual app has a logic that checks for unique items from realm db and iterates over the records and fetches data for them. This operation for fetching unique records is taking more time. And this operation must be done for every record obtained from the API.

**Comment by bmunkholm** [comment]
Sure, so You will have to analyze how much time is spend on what.

tor. 28. mar. 2019 kl. 03.48 skrev Krishna Manoj Varanasi <
notifications@github.com>:

**Comment by kmvkrish** [comment]
> Sure, so You will have to analyze how much time is spend on what. 

Yes. We debugged our code and found the code block that is eating the download time. We have optimized it.

But, I have a question on finding DISTINCT records from realm. I used:
> Sorting and find distinct values are possible with functions SORT and DISTINCT, e.g. age > 20 SORT(name ASC, age DESC) DISTINCT(name).
For 10000 records, this operation took nearly 1.2seconds to finish. This same operation must be executed for each of the 5000 records in our app. This is the costliest operation of our whole app.

Can you suggest how to achieve this in a minimum time?

**Comment by bmunkholm** [comment]
You should ensure you have a primary key for the properties you sort on.

But also find a way where you don't have to sort 10000 records 5000 times. Can't you do that after you have inserted all records?

**Comment by kmvkrish** [comment]
@bmunkholm  We have updated out business logic to handle the sorting and finding uniques rows after the insertions are finished. This gave us a huge performance improvement.
Thanks.

**Comment by sej1228** [comment]
> same issue

same issue
