### ISSUE TITLE
Realm Database on ReactNative, How to rename key of object after get datas? 

### ISSUE THREAD

**Issue by JJLife** [realm/realm-js#2309]
I have acct_id, acct_number, acct_name, ... table in my realm schema. Then after I got datas from realm and want to rename key of object.

acct_id rename to Identifier
acct_number rename to Number
acct_name rename to Name
I try to rename with loops after got datas from realm but slowly. ( use .map() )

## Goals
  Can you advise me how to rename after get datas with tools of realm database.
## Expected Results
 How to rename with tools of realm database.
## Code Sample

    Realm.open({
        path: 'datav8.realm',
        schema: [datav8.Account],
        schemaVersion: 1
      })
    .then(realm => {
        let dataAccount = realm.objects("Account");
        let datas = dataAccount.map( res => 
          ({ 
              Identifier : res.acct_id, 
              Number     : res.acct_number,
              Name       : res.acct_name
          }));
        console.log(datas)
    })

## Version of Realm and Tooling

- Realm JS SDK Version: 2.25.0
- React Native: 0.59.2
- Client OS & Version: 10.14.3
- Which debugger for React Native: None

**Comment by kramer9x** [comment]
@JJLife, from what I see, you need to update your table schema and create a migration for this update.

https://realm.io/docs/javascript/latest/#migrations

**Comment by JJLife** [comment]
@kramer9x  Hi, I don't update properties of my table schema ( acct_id, acct_number, acct_name). After I get the data and want rename object (Identifier, Number, Name) while properties of my table schema don't change( acct_id, acct_number, acct_name).

before that, I get the data from SQLite ( select acct_id as Identifier, acct_number as Number, ..... from tables ) to define key of object.

Thank you.

**Comment by kneth** [comment]
You can use `mapTo` in the schema: https://realm.io/docs/javascript/2.29.2/api/Realm.html#~ObjectSchemaProperty

**Comment by JJLife** [comment]
Dear All

   Thank you for closed to this.
