### ISSUE TITLE
realm.removeAllListeners() not clearing listeners already registered

### ISSUE THREAD

**Issue by kmvkrish** [realm/realm-js#2312]
We have 2 components in our React Native app. HomeScreen and Settings screens which have listeners registered on Realm.Collection to update the UI.

From the settings screen, the user can clean the RealmDB. Before cleaning the DB, we are trying to remove the listeners on the collections.

HomeScreen has listener on Users table.
Settings screen has listener on the AppConfig table.

## Expected Results

All listeners on the collections must be removed when we use `realm.removeAllListeners()`

## Actual Results

We are able to unregister only the listener in the Settings screen, as we have reference to it. For listener on the HomeScreen, we don't have the reference, as the user is navigated to settings screen.

If we use `realm.removeAllListeners()`, they are not being removed.

## Code Sample

**User table listener**

`this.users = realm.objects('Users');
  this.users.addListener(this.usersDataListener);
`

**AppConfig table listener**

`this.appConfig = realm.objects('AppConfig');
  this.appConfig.addListener(this.appConfigListener);
`

In the settings screen, the reference of `this.appConfig` collection is available. And hence, we can use `this.appConfig.removeListener(this.appConfigListener)` method. This is working as expected.

We are not able to remove the listener on the User table as we don't have reference to it in the settings screen. Hence we are using `realm.removeAllListeners()` to remove all the listeners. But, this is not removing all the listeners and the listeners are being triggered while cleaning the realm db which is causing a crash in the app.

Can you please help how to unregister the listeners in the **SettingsScreen**?

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.0
- Node or React Native: React Native - 0.57
- Client OS & Version: Android 8 (Oreo)
- Which debugger for React Native: None.

**Comment by kneth** [comment]
@kmvkrish Thanks for reporting. We need to investigate a bit but it sounds like a bug at our end.

**Comment by jembach** [comment]
Hi,
I have the same problem. over my app are much listener. When the user should be logged out, all listener has to be removed at once. But it doesn't work.

Please try to fix this bug

**Comment by aureliopetrone** [comment]
It seems I have this problem too.

**Comment by kneth** [comment]
@jembach Please tell us the Realm version, RN version, iOS or Android.

**Comment by jembach** [comment]
I have the following Versions:
- Realm JS SDK Version: 2.28.0
- React Native - 0.59

But after spending some time, we have blowd up our code to solve the problem. we are now not using realm.removeAllListeners any more.

Nevertheless it would be nice, to fix it

**Comment by kneth** [comment]
@jembach Thank you for the update. I'll keep the issue open in order to remember to get back to it soon.

**Comment by kneth** [comment]
It might be our documentation is badly written but `Realm.removeAllListeners()` will only remove listeners registered by `Realm.addListener()` i.e., only listeners of changes to the Realm. Collection listeners - registered by `Realm.Results.addListener()` - can be removed by `Realm.Results.removeAllListeners()`.

I am closing the issue as `Realm.removeAllListeners()` will never be able to remove collection listeners. When you call `Realm.close()` on the last instance, all listeners will be removed.
