### ISSUE TITLE
TypeError: _realm.default.objects(...).isEmpty is not a function

### ISSUE THREAD

**Issue by sumyfly** [realm/realm-js#2315]
## Goals
I want to use isEmpty method to check whether the results are empty, but I hit on this error.

## Expected Results
isEmpty function of Realm.Results should exist.

## Actual Results
When I debug my app, I can see this error on the console.

## Steps to Reproduce
Call isEmpty on a Realm.Results object.

## Code Sample
    try {
      return !realm.objects<ProductType>('Product').isEmpty();
    } catch (error) {
      console.log(error);
      return false;
    }

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.0
- React Native: 0.57.5
- Client OS & Version: macOS 10.14.3
- Which debugger for React Native: React Native Debugger

## document url
https://realm.io/docs/javascript/latest/api/Realm.Results.html#isEmpty

Thanks in advance!

**Comment by kneth** [comment]
@sumyfly Do you only observe it when you are debugging? Is it both on Android and iOS?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
