### ISSUE TITLE
Large space inflation when overwriting same data

### ISSUE THREAD

**Issue by zpalmtree** [realm/realm-js#2318]
## Goals

Overwrite old object without file size inflation.

## Expected Results

File size remains relatively constant when overwriting old objects.

## Actual Results

File size rapidly increases, for example, writing the same data 1000 times resulted in a file size increase of 10x.

## Steps to Reproduce

Worth noting my DB is encrypted. Not sure if this matters or not.
Amount of objects stays constant in DB (1), so overwrite is working correctly, just inflating space used.

* Open DB
* Write data with constant private key
* Close DB
* Repeat above steps quite a few times, say, 100
* Inspect file size before and after
* File size should have increased
* Sometimes takes a couple repeats of this process to size file size increase, I assume because file size is increased in chunks.

## Code Sample

```js
import Realm from 'realm';
const fs = require('react-native-fs');
import { sha512 } from 'js-sha512';

export async function saveToDatabase(wallet, pinCode) {
    /* Get encryption key from pin code */
    var key = sha512.arrayBuffer(pinCode.toString());

    const realm = await Realm.open({
        schema: [
            WalletSchema, WalletSynchronizerSchema, SubWalletSchema,
            TransactionSchema, SubWalletsSchema, TxPrivateKeysSchema,
            TransfersSchema, TransactionInputSchema, UnconfirmedInputSchema,
            SynchronizationStatusSchema
        ],
        encryptionKey: key,
    });

    try {
        /* Write the wallet to the DB, overwriting old wallet */
        await realm.write(() => {
            walletToRealm(wallet, realm)
        })
    } finally {
        realm.close();
    }
}

async function increaseDBSize() {
    for (let i = 0; i < 100; i++) {
        await saveToDatabase(Globals.wallet, Globals.pinCode);
    }

    const dbSize = await fs.stat(Realm.defaultPath);
    console.log('DB size: ' + dbSize.size);
}
```
`walletToRealm` just converts from JSON to a realm object using `realm.create`. Let me know if you need the source of that, or the schemas.

I also tried keeping one version of the realm open, instead of opening and closing on every save, but I saw the same behaviour. Perhaps this wouldn't occur if I live updated the objects? I have to convert to/from JSON each time however, so this isn't an option.

I see some similar issues to this, but I don't think I'm making the mistakes there - since I'm closing my DB after every open.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.21.1
- Node or React Native: React Native
- Client OS & Version: Android 9, Nexus 6, Api 28
- Which debugger for React Native: None

**Comment by kneth** [comment]
You can try to compact the Realm file when you open it (see https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration). As a start, you can let the `shouldCompactOnLaunch` callback always return true.

**Comment by kneth** [comment]
@zpalmtree I believe you are facing the same situation as in #1751 and I hope that the suggestions there can help you.

**Comment by zpalmtree** [comment]
Was the advice in that post not to open/close the DB on every access, which I'm doing already?
I am using compaction, which works fine, but on larger file sizes takes quite a long time -- I didn't consider compacting on every open, I only did it when I initially launched the app, I'll look into this.

Is compaction faster if the database is already mostly compacted?

Thank you for the assistance.

**Comment by kneth** [comment]
It is hard to tell from your snippet. Do you have any other instance open? If so, you might have memory which cannot be reused. When that happens, the file size will grow for every commit.

Compacting will take longer for a larger database so compacting it everything will probably save you time.

**Comment by zpalmtree** [comment]
I should only have one instance open, I usually open, perform an operation, and close right after. In this small test case at least, there was certainly only ever one instance open.

Unfortunately compacting every open was not achievable - I was already having issues with running out of memory opening the DB, and so for some users this resulted in the compaction never completing, and the app not opening.

Ended up swapping to sqlite :/

Thank you for the assistance regardless.
