### ISSUE TITLE
Cyrillic in file path for Windows

### ISSUE THREAD

**Issue by brightsider** [realm/realm-js#2319]
If using cyrillic in path then can't open database.
Error text:
Unable to open a realm at path 'D:\тест\default.realm.managment': make_dir() failed: No such file or directory Path:.
Same error get through Realm Studio for Windows.

**Comment by kneth** [comment]
I believe we have seen it recently, and it is unrelated to Cyrillic. See #2097. Can you confirm that you also see it if you are on Latin-1?

**Comment by nirinchev** [comment]
@kneth I believe #2097 is due to exceeding the windows path length - the path posted in that issue contains 297 characters, whereas this one seems to be well within bounds.

**Comment by brightsider** [comment]
@kneth I think this bug not related to #2097 because test it on short path.
How to test Latin-1? I think It happens on Windows-1251

**Comment by kneth** [comment]
@brightsider Is it possible for you to share a minimal example which can reproduce the error?

By Latin-1 I mean Windows-1252 (too much of an old Linux user in me).

**Comment by brightsider** [comment]
@kneth create any database on Windows, move to folder with Cyrillic in path like this - D:\тест\default.realm.managment.
And try to open in Realm Studio

**Comment by chetak-nis** [comment]
@kneth 
Getting this issue in a folder having a Japanese character in windows 10.

**Comment by kneth** [comment]
The proper fix is in Realm Core (see https://github.com/realm/realm-core/issues/3230).

**Comment by kneth** [comment]
We have merged the bug not it is not released yet.

**Comment by ironage** [comment]
Released in js version v2.29.0.
