### ISSUE TITLE
[iOs] [remote debugging] Unable to find module for EventDispatcher React Native

### ISSUE THREAD

**Issue by raphaelbadia** [realm/realm-js#2324]
## Goals

I'm trying to code normally. I just installed realm, it works great. But on iOs, after enabling remote debugging and hit reload, this error message pops up.
It happens with both chrome debugger and React Native Debugger.
It happens only on iOs.

## Expected Results

I should see my app.

## Actual Results
![image](https://user-images.githubusercontent.com/1901628/55635106-3372a700-57c0-11e9-93dc-8918a42b332a.png)
```
Unable to find module for EventDispatcher

-[RCTCxxBridge moduleForName:lazilyLoadIfNecessary:]
    RCTCxxBridge.mm:478
-[RCTCxxBridge moduleForClass:]
-[RCTBridge(RCTEventDispatcher) eventDispatcher]
-[RCTSettingsManager userDefaultsDidChange:]
__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
_CFXRegistrationPost
___CFXNotificationPost_block_invoke
-[_CFXNotificationRegistrar find:object:observer:enumerator:]
_CFXNotificationPost
-[NSNotificationCenter postNotificationName:object:userInfo:]
-[RCTDevSettingsUserDefaultsDataSource _reloadWithDefaults:]
-[RCTDevSettingsUserDefaultsDataSource initWithDefaultValues:]
-[RCTDevSettings init]
__44-[RCTModuleData initWithModuleClass:bridge:]_block_invoke
-[RCTModuleData setUpInstanceAndBridge]
__25-[RCTModuleData instance]_block_invoke
RCTUnsafeExecuteOnMainQueueSync
-[RCTModuleData instance]
__49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

## Steps to Reproduce

* Add realm to a new project
* enable remote js debugging
* reload
* the message appears

## Version of Realm and Tooling

- Realm JS SDK Version: ^2.26.0
- Node or React Native: 0.59.3
- Client OS & Version: iphone X
- Which debugger for React Native: React Native Debugger / Chrome debugger

**Comment by zek** [comment]
This is a secret of realmjs and they maintainers dont care about it

**Comment by zgavin** [comment]
I was also having this issue and solved it by downgrading to 0.57.8.  This obviously isn't an ideal solution, but there really are no ideal solutions when it comes to using realm with a chrome based debugger (ie, see #491).  You'll either need to accept limited debugging capabilities or switch to an alternative database.

**Comment by Alekseyideas** [comment]
I have the same error((( 
Will be work with react-native-sqlite-storage. 
About realm see [comment](https://github.com/Microsoft/vscode-react-native/issues/955#issuecomment-477096156)

**Comment by kneth** [comment]
It seems to be a more general problem: https://stackoverflow.com/questions/54883304/unable-to-find-module-for-eventdispatcher-react-native
