### ISSUE TITLE
APP crash when system try to memcpy or when i kill my app

### ISSUE THREAD

**Issue by jramalho** [realm/realm-js#2326]
## Goals

Sometimes the app crash. when the apk is killed on when a memcpy is araised by tem system.

## Expected Results

Memory errors shouldn't appear on my play store log.

## Actual Results

```
> Motorola Moto Z (2) Play (albus), Android 8.0
> Relatório 1 de 1
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> pid: 0, tid: 0 >>> br.com.appgeolife <<<
> 
> backtrace:
>   #00  pc 000000000004aab0  /system/lib/libc.so (tgkill+12)
>   #01  pc 000000000001a443  /system/lib/libc.so (abort+54)
>   #02  pc 00000000004ea773  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #03  pc 00000000004ea7b7  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #04  pc 00000000004ea85b  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #05  pc 00000000004264a7  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #06  pc 00000000000e0c1c  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #07  pc 000000000042908f  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #08  pc 00000000004292d9  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #09  pc 00000000000e1354  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #10  pc 00000000001dab18  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #11  pc 00000000001d9d00  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #12  pc 00000000001d8738  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #13  pc 00000000004862a5  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #14  pc 00000000001d88d0  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #15  pc 00000000004f4135  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #16  pc 00000000004d6043  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #17  pc 00000000004d6153  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #18  pc 00000000000e2ea0  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #19  pc 0000000000140594  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #20  pc 00000000001434b0  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/librealmreact.so
>   #21  pc 00000000000638c7  /data/app/myapp-0EepNZz4KkzNCMunb_VeVA==/lib/arm/libjsc.so (_ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE+222)
>   #22  pc 0000000000000021  <anonymous>
```

## Steps to Reproduce

Use Realm and react-native 0.58 >
install the armeabi-v7a arch apk

## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.0
- Node or React Native: React native
- Client OS & Version: Android 8.0
- Which debugger for React Native: play store log

**Comment by kneth** [comment]
Please tell us a bit more of the context. For example, do you see it if you use v2.25.0? Does it happen when the app is just launched or does it happen when the app is running? Do you use encryption?

Moreover, do you have a minimal app which can reproduce the crash?

**Comment by jramalho** [comment]
@kneth using the last version of Ream-js V:2.26.0. Happen when the app is in background and you relaunch it. Dont use encryption at all and is just a local-database.

We are using in an production app, but i can't share it.
We dont know how to reproduce yet.
Thanks in advance.

**Comment by kneth** [comment]
@jramalho I haven't been able to reproduce it using Realm JS v2.26.0 and RN 0.59.4. Do you see it on Motorola Moto Z only or do you see it on other devices too?

**Comment by jramalho** [comment]
Moto z series, occur on moto z (griffin) and moto z2 (albus).

**Comment by jramalho** [comment]
Actually, it is a bug on react-native-maps. The memory consumption and don't even give me a log. But thanks. 
Closing the issue.
Thanks for your time.

**Comment by jramalho** [comment]
Now i have an sentry log to show up here.

https://sentry.io/share/issue/97b9fb29eeaf4e71a078bbc9020ab0e3/

https://sentry.io/share/issue/b2be966308d449ee81e3da3f71ec2eac/

https://sentry.io/share/issue/007a5fdc493c41f786c77eca8e610d9c/

**Comment by jramalho** [comment]
We find the problem. A background fetch call was being called two times, and excluding objects that already was excluded from the realm.
