### ISSUE TITLE
Update docs for collection.subscribe()

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2334]
The docs and typescript definitions are not very clear:

- The typescript definitions claim that `timeToLive` is required where it should be optional.
- The unit for `timeToLive` is unclear and undocumented.

**Comment by ironage** [comment]
For reference, ttl units are milliseconds (https://github.com/realm/realm-object-store/blob/jas/subscription-inclusions/src/sync/partial_sync.hpp#L74). In https://github.com/realm/realm-js/pull/2296 I've updated the typescript definition of ttl to be optional.

For updating the docs, are you thinking of adding comments along with the typescript? Or are you referring to the js API docs on Results.subscribe()?

**Comment by ironage** [comment]
Updated js API docs for ttl via https://github.com/realm/realm-js/pull/2296 as well. I think that covers everything, if not let me know.

**Comment by nirinchev** [comment]
Yeah, I was thinking of just mentioning it in the JS api docs.

**Comment by ironage** [comment]
Fixed in https://github.com/realm/realm-js/pull/2296
