### ISSUE TITLE
Realm.UpdateMode is undefined

### ISSUE THREAD

**Issue by hlus** [realm/realm-js#2341]
## Expected Results

Now I have solution like code below. But create method have different signature, and my ts lint is signaling me about this problem.

## Code Sample

const savedThread = realm.create<HydratedConversation>(
          HydratedConversation.schema.name,
          createdConv,
          "all",
);

## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.1
- React Native: 0.57.8
- Which debugger for React Native: Reactotron

**Comment by mecp** [comment]
I am facing the same issue

**Comment by JohnWebb4** [comment]
Having the same issue. Opened PR to fix.
