### ISSUE TITLE
Electron+angular realm

### ISSUE THREAD

**Issue by Bahtiyorov** [realm/realm-js#2342]
Can I use realm inside angular with electron ? Now electron and realm working cool,  but when I try use angular  with electron not working. thanks in advance

**Comment by kneth** [comment]
@Bahtiyorov We don't have official Electron support so we only test with what we need (to get https://github.com/realm/realm-studio/ working).

Your question is broad - can you be more specific?

**Comment by Bahtiyorov** [comment]
can I use with angular ???? it is not working when I try to include angular to electron

**Comment by kneth** [comment]
I think that Realm and Angular should be able to co-exist. It is more likely your packager which is your troublemaker.
