### ISSUE TITLE
Accessing object of type WalletSchema which has been invalidated or deleted

### ISSUE THREAD

**Issue by bachlongkocanh** [realm/realm-js#2344]
I get data from schema to list. After i delete record by:
`realm.delete(record)` then get an error
`Accessing object of type WalletSchema which has been invalidated or deleted`.
Who can explain to me: 'why I have this error and how do I resolve it?'

**Comment by kneth** [comment]
You don't give us much context but if you delete an object, and you try to access it later, you see this error. Actually, you might have an object of the same object in another part of your app. Each Realm object has a method called `isValid()` to help you avoid these errors.

**Comment by 0oTMNo0** [comment]
i have same issue.
