### ISSUE TITLE
Reference to loadLibrary is ambiguous  SoLoader.loadLibrary("realmreact")

### ISSUE THREAD

**Issue by SantosDavid** [realm/realm-js#2346]
## Goals

Create an app with expo and after removing expo I will try to use Realm and React native.

## Expected Results

Run app an Emulator e build apk.

## Actual Results

![image](https://user-images.githubusercontent.com/26348312/56527358-ea428700-6523-11e9-94d0-0262f449bc56.png)

## Steps to Reproduce

1 - Run: expo init new-project

2 - Run: Expo eject

3 - [Follow this tutorial](https://docs.expo.io/versions/v32.0.0/expokit/eject/#__next)

4 - Run: npm install --save realm

5 - Run: react-native link realm

6 - Run: expo start and react-native run-android --variant devKernelDebug.

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.25.0
- Node or React Native: ? React Native
- Client OS & Version: ? Ubuntu 18.10 and Ubuntu 18.04

**Comment by kneth** [comment]
@SantosDavid Expo doesn't support Realm: https://expo.canny.io/feature-requests/p/support-for-realm

Said that, it looks like `SoLoader` is included twice?

**Comment by SantosDavid** [comment]
I removed expo from my project. 

I ran `expo eject` and chose to keep expo kit. Does Realm work with expoKit ?

I think the `SoLoader.loadLibrary` can't be resolved.

**Comment by SantosDavid** [comment]
The app was running in the `emulator with Realm` for about 2 weeks.

I don't know what happened, but now doesn't work anymore.

I try make a new app with the same "**Steps to Reproduce**" in different computers, but too doesn't work.

**Comment by kneth** [comment]
@SantosDavid I think you are running into the same issue as described in https://github.com/expo/expo/issues/1743

**Comment by mayaflor** [comment]
Hi @kneth, thanks for helping us!  
I'm working on this project along with @SantosDavid and we figured out what was wrong. The `build.gradle` file on the `android/app` folder was generated using the deprecated term `compile` instead of `implementation`
So Realm really does work with ExpoKit.

**Comment by kneth** [comment]
@SantosDavid @mayaflor Thanks for the update. It is great to hear that you have succes with the ExpoKit/Realm combo.
