### ISSUE TITLE
[iOS] - Saving data on realm when the APP receives a background fetch event and the phone is blocked.

### ISSUE THREAD

**Issue by jramalho** [realm/realm-js#2349]
## Goals

Save Data in Realm when i do a background fetch Event and the app is in background on iOS but the cellphone is blocked.
In the realm objective c lib has some stuff about using a background fetch event, searched on the js lib and it doesn't have it.

## Expected Results

Save actual information on Realm-js in iOS.
## Actual Results
Failed() Operation not permited.

```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: br.com.myapp exhausted real (wall clock) time allowance of 27.12 seconds |  | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 20.790 (user 20.790, system 0.000), 35% CPU", | "Elapsed application CPU time (seconds): 1.778, 3% CPU" | )
Triggered by Thread:  0

```
## Steps to Reproduce

1. Realm App when the phone is blocked
2. Receive a Background Fetch

## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.1
- Node or React Native: React-native
- Client OS & Version: iOS 11.4
- Which debugger for React Native: Sentry

**Comment by jramalho** [comment]
So, changing the function in Objective-C code let me save all the content.

##   realm/src/ios/platform.mm
```
void ensure_directory_exists_for_file(const std::string &fileName)
{
    @autoreleasepool {
        NSString *docsDir = [@(fileName.c_str()) stringByDeletingLastPathComponent];
        NSFileManager *manager = [NSFileManager defaultManager];
        [manager setAttributes:@{NSFileProtectionKey: NSFileProtectionNone}
                  ofItemAtPath:docsDir error:nil];

        if ([manager fileExistsAtPath:docsDir]) {
            return;
        }

        NSError *error = nil;
        if ([manager createDirectoryAtPath:docsDir withIntermediateDirectories:YES attributes:nil error:&error]) {
            throw std::runtime_error(util::format("Failed to create directory \"%1\": %2", docsDir.UTF8String, error_description(error).UTF8String));
        }
    }
}
```

**Comment by kneth** [comment]
@tgoyne Do you know of any security concerns when setting the attribute to `NSFileProtectionNone`?

**Comment by tgoyne** [comment]
File protection makes it so that if a device is stolen or seized while the device is locked or powered off it's impossible to read any of the data from the device. This naturally also means that apps can't read or write the data while the device is locked.

Developers which want to disable file protection for their Realm files should simply do so themselves via the normal system APIs just as they would for any other file.

**Comment by bmunkholm** [comment]
@jramalho I hope this answer from tgoyne is what you need and I will close this.

**Comment by gboyegadada** [comment]
I think it would be very helpful if a suitable workaround is also added in the JS section of the docs by the Realm team. I do not have any prior `Swift / Objective-C` experience so applying the workaround in the `Swift / Objective-C` section of the Realms docs in my RN project was not immediately apparent (and quite honestly still isn't). 

I have been trying to find a way to disable iOS file protection for the realm directory and then use Realm’s built-in encryption as directed in the `Swift / Objective-C` section of the docs but I cannot find any materials showing me how to do this in a React Native project. 

The OP's solution here also means having to modify files in the `node_modules` folder (or forking the repo?)
