### ISSUE TITLE
Andriod Create model with 'modified'

### ISSUE THREAD

**Issue by wf08314110101** [realm/realm-js#2350]
## Goals
ModelA.scheme = {
  name: string,
  age: {type: 'int', optional: true, default: 0}
}

realm.create('ModelA', {name: 'a'}, 'modified')
let aModel = realm.objects('ModelA').filtered('name == $0', 'a')

## Expected Results
console.log(aModel.age) /// 0

## Actual Results
console.log(aModel.age) /// undefined

## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.1
- Node or React Native: 0.59.5
- Client OS & Version: Andriod 8.0
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@wf08314110101 I haven't been able to reproduce it. Please take a look at #2486 and see if my test  differs what you try to do.
