### ISSUE TITLE
Realm.Sync.User.logout yields a 400 error

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2352]
## Goals

Logging out a user should revoke the users access token.

## Expected Results

I expect the revocation request to just succeed with a 200 OK status code.

## Actual Results

The server complains with a 400 error.

```
error: [http] HTTP response: 505450cd-ab87-4deb-8b4a-6dc7685c2092
{"type":"https://docs.realm.io/server/troubleshoot/errors#missing-parameters","title":"Your request did not validate because of missing parameters.","status":400,"code":602,"invalid_params":[{"name":"token","reason":"Missing parameter 'token'!"}]}
```

## Steps to Reproduce & Code Sample

```javascript
const Realm = require('realm');

async function run() {
    const credentials = Realm.Sync.Credentials.nickname('delete-me');
    const user = await Realm.Sync.User.login('http://localhost:9080', credentials);
    console.log(`Authenticated as ${user.identity}`);
    // Deauthenticate
    await user.logout();
}

run().then(() => {
    console.log('Done ...');
    process.exit(0);
}, err => {
    console.error(err);
    process.exit(1);
});
```

This is where the logout is defined: https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L599-L621.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.1
- Node or React Native: Node
- Client OS & Version: MacOS
- Which debugger for React Native: N/A

**Comment by nirinchev** [comment]
This has been fixed by: https://github.com/realm/realm-js/pull/2348

**Comment by kraenhansen** [comment]
My oh my - I wish I had looked at the changelog before spending time formulating and debugging this 😅
