### ISSUE TITLE
App crash on start in debug mode

### ISSUE THREAD

**Issue by virtyos** [realm/realm-js#2354]
![Screenshot_2019-04-28-14-13-44-178_com zubza_mobile_rn2](https://user-images.githubusercontent.com/210544/56863542-1e082b80-69c0-11e9-9ee8-54c1376fdeb1.png)

The image above I see after install and start a debug app on my device. 

React native version: 0.59.5
Device: Xiaomi Redmi 3S
Android : 6.0.1

Previous app built with 0.57.4 version of react native worked fine.  I tried to disable all additional libs such as firebase,  google maps but no success ((

**Comment by virtyos** [comment]
App code I use (It's the simpliest just to test starting):

```
import { Text, TouchableOpacity, View } from "react-native";

export default class App extends React.PureComponent {


    render() {
        return (
            <View><Text>sss</Text></View>
        );
    }
}
```

**Comment by bmunkholm** [comment]
@virtyos I don't see how this has anything to do with Realm so I'm closing this.
