### ISSUE TITLE
Stop supporting node 6 in the next release

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-js#2356]
We need to update the doc to remove the need to use node 6 to run tests, as there's a refactor that helps alleviate this issue. 
We also introduced the usage of `async` in https://github.com/realm/realm-js/pull/2302 which requires node > 6 to run (at least for CI)

**Comment by kneth** [comment]
Internal note: https://github.com/realm/realm.io/pull/4635

**Comment by nirinchev** [comment]
Shouldn't that be a major version bump then? It would be a breaking change for someone running node 6.

**Comment by kneth** [comment]
v6 had end-of-life by the end of April 2019 (https://nodejs.org/en/about/releases/).

**Comment by bmunkholm** [comment]
But that doesn't change that it's a breaking change?

**Comment by kneth** [comment]
Let's move to Slack to discuss it further.

**Comment by kneth** [comment]
https://realm.io/docs/javascript/latest/ has been updated.
