### ISSUE TITLE
Error doing yarn: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by lichen19853** [realm/realm-js#2367]
## Version of Realm and Tooling
- Realm 2.26.1
- Node v11.6.0
- macOS 10.14.4
- XCode 10.2.1
- yarn 1.13.0

Trying to do a yarn, getting error

> Traceback (most recent call last):
>   File "./gyp-mac-tool", line 611, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "./gyp-mac-tool", line 28, in main
>     exit_code = executor.Dispatch(args)
>   File "./gyp-mac-tool", line 43, in Dispatch
>     return getattr(self, method)(*args[1:])
>   File "./gyp-mac-tool", line 246, in ExecFilterLibtool
>     if not libtool_re.match(line) and not libtool_re5.match(line):
> TypeError: cannot use a string pattern on a bytes-like object
> make: *** [Release/object-store.a] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Darwin 18.5.0
> gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/Cellar/node/11.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/chen/Documents/kamino-v2/node_modules/realm/compiled/node-v67_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/chen/Documents/kamino-v2/node_modules/realm/compiled/node-v67_darwin_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
> gyp ERR! cwd /Users/chen/Documents/kamino-v2/node_modules/realm
> gyp ERR! node -v v11.6.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok

**Comment by nirinchev** [comment]
We don't support node 11 yet. Can you try downgrading to 10 and trying again?

**Comment by lichen19853** [comment]
Thanks @nirinchev ! Confirmed that downgrading to node 10 resolves this issue.
