### ISSUE TITLE
error: 'kSCNetworkReachabilityFlagsIsWWAN' is unavailable: not available on macOS

### ISSUE THREAD

**Issue by MaheshNandam** [realm/realm-js#2375]
Got this error while installing v2.26.1

../src/object-store/src/sync/impl/apple/network_reachability_observer.cpp:42:17: error: 'kSCNetworkReachabilityFlagsIsWWAN' is unavailable: not available on macOS
    if (flags & kSCNetworkReachabilityFlagsIsWWAN)
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCNetworkReachability.h:174:2: note: 
      'kSCNetworkReachabilityFlagsIsWWAN' has been explicitly marked unavailable here
        kSCNetworkReachabilityFlagsIsWWAN
        ^
1 error generated.
make: *** [Release/obj.target/object-store/src/object-store/src/sync/impl/apple/network_reachability_observer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node --module_name=realm --module_path=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm
node-pre-gyp ERR! node -v v12.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node --module_name=realm --module_path=/Users/mahesh/Documents/develop/connect-mobile-redux/connect-mobile-app/node_modules/realm/compiled/node-v72_darwin_x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN react-native-gesture-handler@1.2.1 requires a peer of react-native@>= 0.58.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.1 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.1 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.26.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the realm@2.26.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rajivshah3** [comment]
Have you updated Xcode recently? Sometimes that will screw up command line builds. A restart normally fixes the issue for me

**Comment by nirinchev** [comment]
If I'm reading the output correctly, you're using node 12. This is not supported, so you'll need to downgrade to 10.

**Comment by MaheshNandam** [comment]
Yes, I have upgraded my Xcode (10.2), till now it's working with realm v2.26.0 for Xcode 10.2 along with node v12, but last week I got this issue.

**Comment by MaheshNandam** [comment]
Downgraded node v10.15.3, works fine.
