### ISSUE TITLE
React Native Realm insertion causing memory leaks.

### ISSUE THREAD

**Issue by surbhit** [realm/realm-js#2379]
We are fetching around 1000 records from server with pagination. Each page is fetched with 100 records. Although the insertion is fast the memory consumption of the app goes to 175MB after all data is being inserted. Because of which app is responding slow and UI is not smooth in devices like iPhone 5, iPhone 6 and iPhone 6 Plus. Although it looks good in iPhone 7 onwards. That may be because they have 2GB RAM as compared to 1 GB lower versions of the devices

Expected Behaviour: While data is being inserted memory consumption should not go that high which was around 175 MB. I am not sure if this is the ideal behaviour.

## Version of Realm and Tooling

- Realm JS SDK Version: ^2.2.7
- Node or React Native: 0.55.4
- Client OS & Version: iOS 12
- Which debugger for React Native: ?/None

**Comment by bmunkholm** [comment]
@surbhit We are using github for bug tracking only. For general questions please ask on StackOverflow or our Forum. If you believe there is a bug or memory performance issue, please provide the smallest possible app that clearly demonstrates the issue.
Thanks!
I would also suggest to use the latest version of realm-js.
