### ISSUE TITLE
[iOS] Unable to find module for EventDispatcher React Native

### ISSUE THREAD

**Issue by mmosayed** [realm/realm-js#2382]
I am getting the following in my developer console after installing Realm on React Native: 

```
Invalidating <RCTCxxBridge: 0x7fbdb5758b50> (parent: <RCTBridge: 0x600000eb16c0>, executor: (null))
```

Then when I activate remote JS debug I get the following: 

```
Unable to find module for EventDispatcher
```

## Expected Results

I'm not supposed to be getting these warnings or errors.

## Steps to Reproduce

1. Installed realmjs for React Native. `yarn add realm`
2. Linked `react-native link realm`
3. Ran `react-native run-ios`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.28.0
- React Native: 0.59.8
- Client OS & Version: OSX 10.14.4 
- Which debugger for React Native: Chrome Remote debugger

**Comment by kneth** [comment]
In v2.29.2 we have a fix to help Jitsi users - I wonder if it can help here too.

Moreover, it seems to be not only related to Realm usage:
https://stackoverflow.com/questions/54883304/unable-to-find-module-for-eventdispatcher-react-native/56160671#56160671
