### ISSUE TITLE
npm install --save realm Not Error

### ISSUE THREAD

**Issue by umangshu** [realm/realm-js#2383]
## Goals

Trying to add realm to project

## Expected Results

npm added successfully

## Actual Results

Getting error from both 
yarn add realm
npm install --save realm

npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.5: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! path /Users/umangshu/Desktop/Umang/MTX/haydenhall/node_modules/@react-navigation/native/node_modules/react-native-safe-area-view
npm ERR! code EISGIT
npm ERR! git /Users/umangshu/Desktop/Umang/MTX/haydenhall/node_modules/@react-navigation/native/node_modules/react-native-safe-area-view: Appears to be a git re
po or submodule.
npm ERR! git     /Users/umangshu/Desktop/Umang/MTX/haydenhall/node_modules/@react-navigation/native/node_modules/react-native-safe-area-view
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/umangshu/.npm/_logs/2019-05-24T06_36_37_473Z-debug.log

## Steps to Reproduce

npm install --save realm

## Version of Realm and Tooling

- Realm JS SDK Version: Latest
- Node or React Native: react-native-cli: 2.0.1, react-native: 0.59.5
- Client OS & Version: OSX 10.14.3
- Which debugger for React Native: Chrome Remote debugger

**Comment by pritasam** [comment]
Any update on this issue :(

**Comment by nirinchev** [comment]
Why do you think this is a Realm issue? The log appears to mention errors related to `react-native-safe-area-view`. Do you experience the issue in a brand new empty project?

**Comment by baudev** [comment]
Remove the directory `node_modules/react-native-safe-area-view/` then run again `npm install --save realm`.

**Comment by mingxin-yang** [comment]
> rm -rf node_modules/*/.git/

**Comment by kneth** [comment]
Also discussed in #1838.
