### ISSUE TITLE
Realm list "push" is undefined.

### ISSUE THREAD

**Issue by igormuba** [realm/realm-js#2385]
## Goals

Trying to push a new int into an int realm list. But this bug also happens when I try to use anything from the List, none of [this functions](https://realm.io/docs/javascript/latest/api/Realm.List.html) work

## Expected Results

When I call the object.listOfTheObject.push(int) for a new int to be inserted into the list.

## Actual Results

Get an error "(node:73249) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined"
Also, if I try to print the list is shows as undefined on the console.

## Steps to Reproduce

An schema like
```
let mySchema={
    name:'MySchema',
    properties:{
        my_schema_id: 'string',
        numbers: 'int[]'
    }
```

Create a new object like
```
Realm.open({schema: [mySchema]})
  .then(realm => {
    realm.write(() => {

        realm.create('MySchema', {my_schema_id: `${my_schema_id}`, numbers: [parseInt(number, 10)]});
      });
```

Add a number like:
```
Realm.open({schema: [mySchema]})
    .then((realm) => {
    let fetchedSchema = realm.objects('MySchema').filtered(`my_schema_id ="${my_schema_id}"`);

console.log(fetchedSchema);
    realm.write(()=>{
        fetchedSchema.numbers.push(parseInt(number, 10));
    });
```

It gives an error
```
(node:73249) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
```

I can create the object, if I open the database with Realm Studio the first number, when the object was created is there.
On the `console.log(fetchedSchema);`I can print the object, it contains the `numbers` list, it even prints the initial number on the list. I can add numbers inside it not eh studio, and again, the print will show the list and all the numbers correctly, but I can't call any functions from the list! Can't get it's length, can't push anything to it... It is driving me mad....

## Version of Realm and Tooling

- Realm JS SDK Version: "realm": "^2.28.0",
- Node or React Native: Node v10.15.1
- Client OS & Version: Mac 10.14.5

**Comment by nirinchev** [comment]
`fetchedSchema` is a collection of objects, not a single object. You can use indexing to access a single object and then access its `numbers` property: `fetchedSchema[0].numbers.push(...)`. Note that it there are no matches to your query, `fetchedSchema` will be empty and you'll get an error so make sure to guard against that.
