### ISSUE TITLE
Running tests in Visual Studio Code is broken

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-js#2386]
It seems that running tests in Visual Studio Code no longer works.

This script has been removed (when running the task "Download and start Server")
```
running command$ /Users/cm/Realm/realm-js/scripts/download_and_start_server.sh 
Failed to launch external program "${workspaceRoot}/scripts/download_and_start_server.sh" .
spawn /Users/cm/Realm/realm-js/scripts/download_and_start_server.sh ENOENT
```

And it isn't clear from https://github.com/realm/realm-js/pull/2343/files#diff-6a3371457528722a734f3c51d9238c13R135 how to exactly accomplish running and debugging tests from Visual Studio Code

**Comment by kneth** [comment]
@blagoev has been working on getting debugging back in shape.

**Comment by kneth** [comment]
I believe we are in a much better position now.
