### ISSUE TITLE
Hi @Lizhooh. This repository is for Realm JS related issues only.

### ISSUE THREAD

**Issue by zhujiaming** [realm/realm-js#2390]
Hi @Lizhooh. This repository is for Realm JS related issues only.

However another user experienced this as well: https://stackoverflow.com/questions/47198349/realm-studio-for-windows-javascript-error

Realm JS (that Studio is dependent on) target Windows 8.1 and up, so Windows 7 is not supported. I've added that to the backlog that we should probably improve that error message.

_Originally posted by @kraenhansen in https://github.com/realm/realm-js/issues/1527#issuecomment-347115165_

Does realm support Windows 7 now? If not, is there a plan to support it?

**Comment by nirinchev** [comment]
We don't support it and we don't plan to support it for now.
