### ISSUE TITLE
Dynamic default

### ISSUE THREAD

**Issue by DrummerSi** [realm/realm-js#2393]
I'd like to be able to specify a function for default values within a schema

The following schema use currently causes an error, due to the default timestamp field expecting a number, not a function:
```
export const TestSchema = {
    name: "TestItem",
    properties: {
        videoId:        "string",
        published:       "int",
        timestamp:      {
            type: "int",
            default: () => Math.round((new Date()).getTime() / 1000) 
        }
    }
}
```

The default function returns what is expected (a number). Could support be added to calculate default value functions? Or would that add to much overhead? I think it'd be perfect for use cases like this where you wish to store the current timestamp

**Comment by kneth** [comment]
@DrummerSi Sorry for the late reply. Yeah, we could as it but it will be costly to make a such callback. It is not so hard to implement. I like the idea and I'll add to the list of future improvements.

**Comment by lilingxi01** [comment]
Any update on this right now?

**Comment by kneth** [comment]
@lilingxi01 Unfortunately not.
