### ISSUE TITLE
Android app crashing when in release mode

### ISSUE THREAD

**Issue by nates-dennis** [realm/realm-js#2395]
## Goals

Trying to login to realm when android app is in release mode.
## Expected Results

the app to launch and successfully login to realm sync
## Actual Results

The app crashes when trying to login to realm. 
[error.log](https://github.com/realm/realm-js/files/3236840/error.log)

## Steps to Reproduce

i have added the following to the proguard-rules
`
-keep class io.realm.react.**
`
but the error suggests that it cannot find a static method in SSL helper class that this line covers.
i was able to get a release build working by overriding the ssl validation callback in the realm sync configuration but that created this issue #2394 . this only affects android so i suspect it is a proguard rule issue. 
## Version of Realm and Tooling

- Realm JS SDK Version: 2.26.1
- Node or React Native: 0.57.8
- Client OS & Version: Android
- Which debugger for React Native: ?/None

**Comment by nates-dennis** [comment]
i solved the issue by changing 
`
-keep class io.realm.react.**
`
to 
`
-keep class io.realm.react.** { *; }
`

**Comment by aashishshrestha5532** [comment]
I have fixed the issue by 
`def enableProguardInReleaseBuilds = false` on app->build.gradle
I hope this one might be useful to somebody
