### ISSUE TITLE
Accessing Multiple table in realm would break the DB Operation...

### ISSUE THREAD

**Issue by ashokadichill** [realm/realm-js#2396]
## Goals
Fetching data in multiple tables in the realm and access it in an asynchronous manner
Would break the DB operation

If the realm supports asynchronous table access with the different realm it should not break the DB operation it should allow us to do multiple tables without any failures.

If I am waiting for the first table operation completes and starts the another table operation it will lead to waiting time

```
RealmDataStore.getPaintData().then( (paint_res) => {
     RealmDataStore.getPartsData().then( (parts_res) => {
          //start UI operation
     }).catch( (err) => {  } )
}).catch( (err) => {  } )

or

let paint_res = await RealmDataStore.getPaintData()
let parts_res = await RealmDataStore.getPartsData()
```

Please give me a valid explanation why the below doesn't work

```
let paint_res = RealmDataStore.getPaintData()
let parts_res = RealmDataStore.getPartsData()
```

I can't use the below

```
Realm.open({
    schema: [Paint, Parts]
}).then(realm => {
```

For migration would happen for the table at any time 

## Expected Results
Both will return The Data from the DB once it's finished

## Actual Results

[Error: Realm at path '/data/data/com.testos/files/default.realm' already opened on current thread with different schema.]

## Steps to Reproduce
Create two Table in the realm and insert data into it
Try to get both tables data in an asynchronous manner

## Code Sample

`HelperClass`

`const Realm = require('realm');`

```
class RealmDataStore {
     getPaintData() {
        const Paint = {
            name: 'PaintSchema',
            properties: {
                paint_color : 'string?',
                paint_price : 'string?'
            }
        }

        let PaintData = []

        Realm.open({
            schema: [Paint],schemaVersion : 1
        }).then(realm => {
            realm.objects('PaintSchema').map( (data) => {
                PaintData.push({
                    paint_color : data.paint_color,
                    paint_price : data.paint_price,
                })
                
            });
            realm.close()
            console.log("Paint data",PaintData)
        }).catch(  error => {
            // catch catched here and sent back as error
            console.log("err",error)
        });
      
    }

    getPartsData() {
        const Parts = {
            name: 'PartsSchema',
            properties: {
                part_name   : 'string?',
                part_make   : 'string?'
            }
        }

        let partsData = []

        Realm.open({
            schema: [Parts],schemaVersion : 1
        }).then(realm => {
            realm.objects('PartsSchema').map( (data) => {
                partsData.push({
                    part_name   : data.part_name,
                    part_make   : data.part_make,
                })
                
            });
            realm.close()
            console.log("parts data",partsData)
        }).catch(  error => {
            // catch catched here and sent back as error
            console.log("err",error)
        });
      
    }
}
```

`React-native-class`

```
class App extends Component {

   componentDidMount() {
      RealmDataStore.getPaintData()
      RealmDataStore.getPartsData()
    }

}
```

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.26.1
- Node or React Native: ? 0.59.4
- Client OS & Version: ? mac os high sierra 10.13.6
- Which debugger for React Native: None

**Comment by kneth** [comment]
You are opening two instances of the same Realm file but with different schemas. That's the reason you get the error message. You will either have to have the two tables in separate Realm files or open the Realm as: `Realm.open({schema: [Parts, Paint]})`.
