### ISSUE TITLE
Realm is not created on the first launch

### ISSUE THREAD

**Issue by max-zu** [realm/realm-js#2400]
App crashes on the first launch after update from `2.2.10` to `2.28.0`.
On the second launch app works fine.

```
react-native: 0.55.4
macOS: 10.14.5
```

`POST http://192.168.42.36:8083/create_realm net::ERR_EMPTY_RESPONSE`.

![image](https://user-images.githubusercontent.com/22217379/58952859-899e9f00-879d-11e9-9bd1-3b05cf02a25e.png)

![image](https://user-images.githubusercontent.com/22217379/58953513-64129500-879f-11e9-853b-f53427351524.png)

**Comment by max-zu** [comment]
It seems that condition on [this line](https://github.com/realm/realm-js/blob/9262fca03841dee91e6cda07ab66ccc5977029a3/src/ios/platform.mm#L78) is incorrect.

**Comment by ValeriiKov** [comment]
some additional notes related this issue: 
https://github.com/realm/realm-js/issues/578#issuecomment-499123822

**Comment by esutton** [comment]
I am seeing iOS crashes on this that adding the missing not sign "!" fixes.
````
    "react": "^16.8.6",
    "react-native": "0.59.9",
    "realm": "^2.28.1",
````
