### ISSUE TITLE
Unexpected behavior when calling results.subscribe(undefined)

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-js#2403]
The docs for [`results.subscribe(options)`](https://github.com/realm/realm-js/blob/master/lib/index.d.ts#L220) indicate, that `options` is optional and can be provided or not provided. It is surprising then that providing `undefined` as an argument to `subscribe` results in the exception `JS value must be of type 'object', got (undefined)`. Since this method is implemented in C++, it seems like it is too strict in checking the argument type and doesn't fallback to the no-argument case, like one would expect from a regular js function. Namely, I expect `results.subscribe()` to be equivalent to `results.subscribe(undefined)`.

**Comment by kneth** [comment]
@nirinchev 

If you use `undefined` it will count as an argument. Consider the following JS code:

```
function f(a) {
  console.log(arguments.length, a);
}

f('hello');
f(undefined);
f();
```

Using node v8.11.3, you will get:

```
1 'hello'
1 undefined
0 undefined
```

Adding `Value::is_undefined()`  to https://github.com/realm/realm-js/blob/master/src/js_results.hpp#L324 is an option.

**Comment by nirinchev** [comment]
I think that the behavior of 2 and 3 should be the same - i.e. calling `f(undefined)` or `f()` should result in the same thing - at least in most js libraries it does, so it was surprising that this is not the case here.
