### ISSUE TITLE
My app crashesh on release due to migration required

### ISSUE THREAD

**Issue by uendar** [realm/realm-js#2407]
I generate an apk release mode in react native and when i try to open it crashes. It says :

 Unhandled promise rejection, { [Error: Error: Migration is required due to the following errors:
- Property 'X.Y' has been added.

Any idea how to solve this. I am stacked with this issue. 
I have installed the last realm 2.28.1

**Comment by JGdesign** [comment]
You will need to include/update the "schemaVersion". Check out the docs, but for example: 
// schemaVersion defaults to 0
Realm.open({schema: [PersonSchema]});

Need to update to:
Realm.open({schema: [UpdatedPersonSchema], schemaVersion: 1}); 

Keep increasing the schemaVersion each time you modify/add your schemas.

**Comment by sreeragkiyyath** [comment]
If existing app exists it can show issues regarding migration.

Solution is to Incrementally update the schema version number before a release.

**Comment by mjm918** [comment]
Run a linear migration. refer to doc
