### ISSUE TITLE
Require cycles  node_modules/realm/lib/browser/collections.js -> node_modules/realm/lib/browser/util.js

### ISSUE THREAD

**Issue by star-heng** [realm/realm-js#2408]
## Version of Realm and Tooling

- Realm JS SDK Version: 2.27.0-rc.3
- Node: 10.6.0
-React Native: 0.57.4
- android: 8.1

⚠️
YellowBox.js:67 Require cycle: node_modules/realm/lib/browser/collections.js -> node_modules/realm/lib/browser/util.js -> node_modules/realm/lib/browser/collections.js

![652B3572-A29D-4A8C-B2EE-C10BD45C51FF](https://user-images.githubusercontent.com/8955903/59238982-96eeda00-8c32-11e9-8015-e6e964039639.png)

**Comment by kneth** [comment]
@star-heng Please update to a recent version.

**Comment by Winandvdb** [comment]
I upgraded to Realm v2.29.1 but I still get this require cycle warning.
I use Node v10.15.3 and React Native v 0.59.8

**Comment by star-heng** [comment]
@kneth  ok, I will have a try.
