### ISSUE TITLE
realm@2.27.0 install: `Failed to execute 'node-gyp.cmd build --fallback-to-build `

### ISSUE THREAD

**Issue by kourosh-ir** [realm/realm-js#2413]
## Goals

npm install --save realm

## Expected Results

npm install --save realm success

## Actual Results

> realm@3.0.0-beta.1 install C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/3.0.0-beta.1/realm-v3.0.0-beta.1-node-v67-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@3.0.0-beta.1 and node@11.5.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
Warning: Missing input files:
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\index.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\ava\package.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\jest\test.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\object-id-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\scripts\set-version.sh
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\spec\helpers\mock_realm.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\.eslintrc.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\user-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\spec\helpers\reporters.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\schemas.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\encryption-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\worker-tests-script.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\ava\test.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\realm-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\query-tests.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\adapter-tests.ts
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\mocha\package.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\package.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\asserts.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\session-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\garbage-collection.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\linkingobjects-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\download-api-helper.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\scripts\publish.sh
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\spec\helpers\setup-module-path.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\results-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\worker.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\list-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\permission-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\spec\support\jasmine.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\migration-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\object-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\package.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\scripts\test.sh
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\scripts\changelog-header.sh
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\admin-user-helper.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\query-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\spec\unit_tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\mocha\test.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\notifier-tests.ts
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\test-runners\jest\package.json
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\js\async-tests.js
C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\..\tests\index.js
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  download-realm
  Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
    SYNC_ARCHIVE: 'realm-sync-Release-v4.4.2-Windows-x64-devel.tar.gz',
    CORE_SERVER_FOLDER: 'core/v5.19.1/windows/x64/nouwp/Release',
    CORE_ARCHIVE: 'realm-core-Release-v5.19.1-Windows-x64-devel.tar.gz' }
  No lockfile found at the target, proceeding.
  Download url: https://static.realm.io/downloads/core/v5.19.1/windows/x64/nouwp/Release/realm-core-Release-v5.19.1-Windows-x64-devel.tar.gz
  Downloading realm-core-Release-v5.19.1-Windows-x64-devel.tar.gz
  Extracting realm-core-Release-v5.19.1-Windows-x64-devel.tar.gz => C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\vendor\realm-win-x64
  Download url: https://static.realm.io/downloads/sync/realm-sync-Release-v4.4.2-Windows-x64-devel.tar.gz
  Downloading realm-sync-Release-v4.4.2-Windows-x64-devel.tar.gz
  Extracting realm-sync-Release-v4.4.2-Windows-x64-devel.tar.gz => C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\vendor\realm-win-x64
  Success
  binding_callback_thread_observer.cpp
  collection_notifications.cpp
  index_set.cpp
  list.cpp
  object.cpp
  object_schema.cpp
  object_store.cpp
  placeholder.cpp
  results.cpp
  schema.cpp
  shared_realm.cpp
  thread_safe_reference.cpp
  collection_change_builder.cpp
  collection_notifier.cpp
  list_notifier.cpp
  object_notifier.cpp
  primitive_list_notifier.cpp
  realm_coordinator.cpp
  results_notifier.cpp
  transact_log_handler.cpp
  weak_realm_notifier.cpp
  uuid.cpp
  external_commit_helper.cpp
  adapter.cpp
  admin_realm.cpp
  global_notifier.cpp
  sync_file.cpp
  sync_metadata.cpp
  work_queue.cpp
  partial_sync.cpp
  sync_config.cpp
  sync_manager.cpp
  sync_session.cpp
  sync_user.cpp
  win_delay_load_hook.cc
  object-store.vcxproj -> C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\Release\\object-store.lib
  js_realm.cpp
  node_init.cpp
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(52): error C2039: 'NamedPropertyGetterCallback': is not a member of 'v8' (compiling sour
ce file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\.node-gyp\11.5.0\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(52): error C2061: syntax error: identifier 'NamedPropertyGetterCallback' (compiling sour
ce file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(53): error C2039: 'NamedPropertySetterCallback': is not a member of 'v8' (compiling sour
ce file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\.node-gyp\11.5.0\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(53): error C2061: syntax error: identifier 'NamedPropertySetterCallback' (compiling sour
ce file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(54): error C2039: 'NamedPropertyEnumeratorCallback': is not a member of 'v8' (compiling
source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\.node-gyp\11.5.0\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(54): error C2061: syntax error: identifier 'NamedPropertyEnumeratorCallback' (compiling
source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_function.hpp(41): error C2039: 'GetCallingContext': is not a member of 'v8::Isolate' (compiling so
urce file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\.node-gyp\11.5.0\include\node\v8-platform.h(18): note: see declaration of 'v8::Isolate' (compiling source file ..\src\node\node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(92): error C2039: 'StringPropertyGetterCallback': is not a member of 'realm::node::Types' (comp
iling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\
  node_init.cpp)
  c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_class.hpp(368): note: see reference to class template instantiation 'realm::js::StringPropertyTy
  pe<realm::node::Types>' being compiled (compiling source file ..\src\node\node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(92): error C3646: 'getter': unknown override specifier (compiling source file ..\src\node\node_
init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(compiling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(93): error C2039: 'StringPropertySetterCallback': is not a member of 'realm::node::Types' (comp
iling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\
  node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(93): error C3646: 'setter': unknown override specifier (compiling source file ..\src\node\node_
init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(93): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(compiling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(94): error C2039: 'StringPropertyEnumeratorCallback': is not a member of 'realm::node::Types' (
compiling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\
  node_init.cpp)
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(94): error C3646: 'enumerator': unknown override specifier (compiling source file ..\src\node\n
ode_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
c:\users\kourosh\desktop\projects\fitness\node_modules\realm\src\js_class.hpp(94): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(compiling source file ..\src\node\node_init.cpp) [C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\build\realm.vcxproj]
  platform.cpp
  sync_logger.cpp
  win_delay_load_hook.cc
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Kourosh\\Desktop\\Projects\\fitness\\node_modules\\realm\\compiled\\node-v67_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Users\\Kourosh\\Desktop\\Projects\\fitness\\node_modules\\realm\\compiled\\node-v67_win32_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm
gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\compiled\node-v67_win32_x64\realm.node --module_name=realm --module_path=C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\compiled\node-v67_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kourosh\\Desktop\\Projects\\fitness\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm
node-pre-gyp ERR! node -v v11.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\compiled\node-v67_win32_x64\realm.node --module_name=realm --module_path=C:\Users\Kourosh\Desktop\Projects\fitness\node_modules\realm\compiled\node-v67_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@3.0.0-beta.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@3.0.0-beta.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kourosh\AppData\Roaming\npm-cache\_logs\2019-06-16T06_13_00_195Z-debug.log

## Version of Realm and Tooling

- Realm JS SDK Version: ? 2.27.0
- Node or React Native: ? 11.5.0
- Client OS & Version: ? Windows 10
- Which debugger for React Native: ?/None

**Comment by lironsher** [comment]
+1

**Comment by digvijayLogistic** [comment]
+1

**Comment by lironsher** [comment]
Downgrade to 10.x 
That's what solve for me

**Comment by WesleyJesus99** [comment]
thanks @lironsher i install the nvm and changed my version of node for 10.0.0 then executed command with success.

**Comment by httplups** [comment]
npm install --save realm@0.14.3

**Comment by digvijayLogistic** [comment]
> npm install --save realm@0.14.3

please , try using this command :

sudo npm install realm@0.14.3 --unsafe-perm

**Comment by sree127** [comment]
Downgrading to V 10.X worked. Thanks @WesleyJesus99

**Comment by xmedeko** [comment]
See also Node 12 support request #2418
