### ISSUE TITLE
[Help] Multiple database and switching between databases

### ISSUE THREAD

**Issue by mjm918** [realm/realm-js#2417]
Hi, is it possible to create multiple realm databases dynamically in an app and switch between them anytime?

I searched online but could not find anything related to this. 

Please let me know. Thanks

**Comment by kneth** [comment]
@mjm918 Yes, you can open as many Realm databases as you wish. Only thing to keep in mind is that they could have different names (see https://realm.io/docs/javascript/latest/#other-realms for details).
