### ISSUE TITLE
node 12

### ISSUE THREAD

**Issue by email2019** [realm/realm-js#2418]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@email2019 We hope to be able to allocate time in late summer to work on Node 12 support.

**Comment by MIREX** [comment]
Is node 10 already supported?

**Comment by arashmilani** [comment]
Yes node >= 8.15.0 and 10.15.1 are supported

**Comment by kneth** [comment]
@wellmonge Before we get to support node 12, you need to either use node 8 or node 10.

**Comment by bmunkholm** [comment]
Thanks for the offer @wellmonge - that's highly appreciated! There is already a PR with some outstanding work in the last comment here: https://github.com/realm/realm-js/pull/2425. Let us know if you feel that's up your alley as it may be a bit involved.

There is a lot of work to do to support each new node version, and all that work can be avoided by moving to n-api instead and we would never be behind on support for new node versions. That is however a larger effort of perhaps 1 month or so. That's what we would really like to do.

**Comment by reynaldpn** [comment]
Node js v12 is the latest LTS version now

**Comment by kneth** [comment]
And we are working hard migrate to N-API in order to support it :-)

**Comment by xmedeko** [comment]
@bmunkholm @kneth is this duplicate of @2516 ?

**Comment by bmunkholm** [comment]
@xmedeko Thanks again - yes this is a dupe.
