### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by AwanesowArtem** [realm/realm-js#2421]
Hi guys.

I create chat app and in my app I have the following schemas/entities:
1) Dialog;
2) Message.
   My question is: what will be better from a performance point of view when getting messages:
1. Store messages for all dialogs in one message list and then to get messages by dialog identifier
2. Store in each dialog its message list (It requires to get dialog and only then from this dialog to get message list)

Thanks in advance.

**Comment by kneth** [comment]
@AwanesowArtem It is hard to get a precise answer but I would go with option 2 for a number of reasons:

* The dialog identifier is likely to be your primary key, so a lookup of a dialog is fast ([`Realm.objectForPrimaryKey()`](https://realm.io/docs/javascript/latest/api/Realm.html#objectForPrimaryKey) is your friend).
* With a dialog object, you have immediately access to all the messages, and lists are generally fast.
* The advantage of lists is that they are ordered so if you insert A before B, A will have a lower index - always.

If you need to go from a message to a dialog, consider adding a [linking object](https://realm.io/docs/javascript/latest/#inverse-relationships).

**Comment by AwanesowArtem** [comment]
> @AwanesowArtem It is hard to get a precise answer but I would go with option 2 for a number of reasons:
> 
> * The dialog identifier is likely to be your primary key, so a lookup of a dialog is fast ([`Realm.objectForPrimaryKey()`](https://realm.io/docs/javascript/latest/api/Realm.html#objectForPrimaryKey) is your friend).
> * With a dialog object, you have immediately access to all the messages, and lists are generally fast.
> * The advantage of lists is that they are ordered so if you insert A before B, A will have a lower index - always.
> 
> If you need to go from a message to a dialog, consider adding a [linking object](https://realm.io/docs/javascript/latest/#inverse-relationships).

Thank you for your answer. But I'm wondering how realm would store messages list inside dialog(In case 2) internally? If each message has Dialog identifier
1) In a separate table. To get message list for dialog realm joins message table with dialog table?
2) Somehow in a dialog itself?

**Comment by kneth** [comment]
The messages will be stored in a separate table but internally the lists are just references. That means that Realm doesn't have to join the two tables but just resolves a reference. It also means that a message can be associated with multiple dialogs with a very low access cost.

**Comment by AwanesowArtem** [comment]
> The messages will be stored in a separate table but internally the lists are just references. That means that Realm doesn't have to join the two tables but just resolves a reference. It also means that a message can be associated with multiple dialogs with a very low access cost.

Each dialog will store list of its message identifiers?

**Comment by kneth** [comment]
The dialogs will have lists with references to messages.

**Comment by AwanesowArtem** [comment]
> The dialogs will have lists with references to messages.

Can I find somewhere the source code of these queries?

**Comment by kneth** [comment]
> Can I find somewhere the source code of these queries?

It is a bit evolved as it consists of three components:

* http://github.com/realm/realm-js is mostly a wrapper for JavaScript and TypeScript
* http://github.com/realm/realm-object-store is a lot of the bookkeeping
* http://github.com/realm/realm-core is the actual storage and query engine
