### ISSUE TITLE
Create a Pods File

### ISSUE THREAD

**Issue by zek** [realm/realm-js#2431]
## Goals

Every time when I compile my RN project, it downloads realm and it really takes too much time. I wonder if you can add pods support so we can use https://cocoapods.org/pods/Realm.

**Comment by kneth** [comment]
@zek It sounds like a good idea but I don't what it takes and when we have the time to do it.

**Comment by igor-nm** [comment]
The same here!
@zek Are you using the 0.60 react-native version ? 
I'm but I can't use realm on ios, also I don't found any solution for this.
If you using 0.60 react-native version , could you help me ?

**Comment by xiongcaichang** [comment]
need help too

**Comment by uc-apa** [comment]
I am also facing issues. Kindly suggest me what should I do to build my project.

![image](https://user-images.githubusercontent.com/25792136/60883524-07a40900-a268-11e9-93f4-05c3a9cca43a.png)

**Comment by uc-apa** [comment]
My project is also dependent upon realm. And now upgrading it to react native 0.60 in which realm is not working on iOS. Please provide a fix for it as soon as possible. Thank you.

**Comment by zek** [comment]
#884

**Comment by uc-apa** [comment]
I got this issue fixed. Earlier I linked only libRealmJS.a in my project. Now I have added both and the error is gone.
![image](https://user-images.githubusercontent.com/25792136/61102977-db69d180-a48d-11e9-8ab9-b95d3a6ab25a.png)

**Comment by bmunkholm** [comment]
Closing this as a duplicate of #884
