### ISSUE TITLE
Unable to rebuild realm with electron

### ISSUE THREAD

**Issue by jindalrohit** [realm/realm-js#2433]
I installed realm using this command :
**npm install realm@v2.28.1 --save**

But I am getting following error while rebuilding it.
---------------------------------------------------------------------------------------------------------
C:\projects\angular-electron>npm install

> invoice-generataion@6.0.1 postinstall C:\projects\angular-electron
> npm run postinstall:electron && electron-builder install-app-deps

> invoice-generataion@6.0.1 postinstall:electron C:\projects\angular-electron
> node postinstall
  • electron-builder version=20.41.0
  • loaded configuration file=C:\projects\angular-electron\electron-builder.json
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> realm@2.28.1 install C:\projects\angular-electron\node_modules\realm
> node-pre-gyp install --fallback-to-build

Warning: Missing input files:
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\migration-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\object-id-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\mocha\package.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\spec\helpers\mock_realm.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\spec\helpers\setup-module-path.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\spec\helpers\reporters.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\object-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\package.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\results-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\worker-tests-script.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\garbage-collection.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\query-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\jest\package.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\mocha\test.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\download-api-helper.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\list-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\async-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\ava\package.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\jest\test.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\session-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\linkingobjects-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\scripts\changelog-header.sh
C:\projects\angular-electron\node_modules\realm\build\..\tests\test-runners\ava\test.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\package.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\realm-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\worker.js
C:\projects\angular-electron\node_modules\realm\build\..\scripts\test.sh
C:\projects\angular-electron\node_modules\realm\build\..\tests\spec\unit_tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\asserts.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\encryption-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\schemas.js
C:\projects\angular-electron\node_modules\realm\build\..\scripts\set-version.sh
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\query-tests.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\user-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\admin-user-helper.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\permission-tests.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\spec\support\jasmine.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\.eslintrc.json
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\index.js
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\notifier-tests.ts
C:\projects\angular-electron\node_modules\realm\build\..\scripts\publish.sh
C:\projects\angular-electron\node_modules\realm\build\..\tests\js\adapter-tests.ts
C:\projects\angular-electron\node_modules\realm\build\..\tests\index.js
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  download-realm
  Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
    SYNC_ARCHIVE: 'realm-sync-Release-v4.4.2-Windows-x64-devel.tar.gz',
    CORE_SERVER_FOLDER: 'core/v5.19.1/windows/x64/nouwp/Release',
    CORE_ARCHIVE: 'realm-core-Release-v5.19.1-Windows-x64-devel.tar.gz' }
  Matching lockfile already exists at target - nothing to do (use --force to override)
  binding_callback_thread_observer.cpp
  collection_notifications.cpp
  index_set.cpp
  list.cpp
  object.cpp
  object_schema.cpp
  object_store.cpp
  placeholder.cpp
  results.cpp
  schema.cpp
  shared_realm.cpp
  thread_safe_reference.cpp
  collection_change_builder.cpp
  collection_notifier.cpp
  list_notifier.cpp
  object_notifier.cpp
  primitive_list_notifier.cpp
  realm_coordinator.cpp
  results_notifier.cpp
  transact_log_handler.cpp
  weak_realm_notifier.cpp
  uuid.cpp
  external_commit_helper.cpp
  adapter.cpp
  admin_realm.cpp
  global_notifier.cpp
  sync_file.cpp
  sync_metadata.cpp
  work_queue.cpp
c:\projects\angular-electron\node_modules\realm\src\object-store\src\server\adapter.hpp(63): warning C4715: 'realm::Adapter::instruction_type_string': not all control paths return a value [C:\projects\angular-electron\node_modules\realm\build\object-store.vcxproj]
  partial_sync.cpp
  sync_config.cpp
  sync_manager.cpp
  sync_session.cpp
  sync_user.cpp
  win_delay_load_hook.cc
  object-store.vcxproj -> C:\projects\angular-electron\node_modules\realm\build\Release\\object-store.lib
  js_realm.cpp
  node_init.cpp
  platform.cpp
  sync_logger.cpp
  win_delay_load_hook.cc
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(52): error C2039: 'NamedPropertyGetterCallback': is not a member of 'v8' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\users\testuser01\.electron-gyp\5.0.2\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(52): error C2061: syntax error: identifier 'NamedPropertyGetterCallback' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(53): error C2039: 'NamedPropertySetterCallback': is not a member of 'v8' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\users\testuser01\.electron-gyp\5.0.2\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(53): error C2061: syntax error: identifier 'NamedPropertySetterCallback' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(54): error C2039: 'NamedPropertyEnumeratorCallback': is not a member of 'v8' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\users\testuser01\.electron-gyp\5.0.2\include\node\v8-platform.h(16): note: see declaration of 'v8' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(54): error C2061: syntax error: identifier 'NamedPropertyEnumeratorCallback' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\node\node_function.hpp(41): error C2039: 'GetCallingContext': is not a member of 'v8::Isolate' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\users\testuser01\.electron-gyp\5.0.2\include\node\v8-platform.h(18): note: see declaration of 'v8::Isolate' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(92): error C2039: 'StringPropertyGetterCallback': is not a member of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp)
  c:\projects\angular-electron\node_modules\realm\src\node\node_class.hpp(368): note: see reference to class template instantiation 'realm::js::StringPropertyType<realm::node::Types>' being compiled (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(92): error C3646: 'getter': unknown override specifier (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(93): error C2039: 'StringPropertySetterCallback': is not a member of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(93): error C3646: 'setter': unknown override specifier (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(93): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(94): error C2039: 'StringPropertyEnumeratorCallback': is not a member of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
  c:\projects\angular-electron\node_modules\realm\src\node\node_types.hpp(38): note: see declaration of 'realm::node::Types' (compiling source file ..\src\node\node_init.cpp)
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(94): error C3646: 'enumerator': unknown override specifier (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
c:\projects\angular-electron\node_modules\realm\src\js_class.hpp(94): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\node\node_init.cpp) [C:\projects\angular-electron\node_modules\realm\build\realm.vcxproj]
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\angular-electron\node_modules\realm\compiled\electron-v5.0_win32_x64\realm.node --module_name=realm --module_path=C:\projects\angular-electron\node_modules\realm\compiled\electron-v5.0_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.28.1/realm-v2.28.1-electron-v5.0-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.28.1 and electron@5.0.2 (electron-v5.0 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\angular-electron\\node_modules\\realm\\compiled\\electron-v5.0_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\projects\\angular-electron\\node_modules\\realm\\compiled\\electron-v5.0_win32_x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v5.0"
gyp ERR! cwd C:\projects\angular-electron\node_modules\realm
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects\angular-electron\node_modules\realm\compiled\electron-v5.0_win32_x64\realm.node --module_name=realm --module_path=C:\projects\angular-electron\node_modules\realm\compiled\electron-v5.0_win32_x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects\angular-electron\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\angular-electron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects\angular-electron\node_modules\realm
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.28.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.28.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\testuser01\AppData\Roaming\npm-cache\_logs\2019-07-03T14_32_05_328Z-debug.log

    at ChildProcess.childProcess.once.code (C:\projects\angular-electron\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at _rebuild (C:\projects\angular-electron\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\projects\angular-electron\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\projects\angular-electron\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (C:\projects\angular-electron\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\projects\angular-electron\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\projects\angular-electron\node_modules\electron-builder\src\cli\install-app-deps.ts:59:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at _installAppDeps (C:\projects\angular-electron\node_modules\electron-builder\out\cli\install-app-deps.js:178:26)
    at installAppDeps (C:\projects\angular-electron\node_modules\electron-builder\out\cli\install-app-deps.js:146:26)
    at then (C:\projects\angular-electron\node_modules\electron-builder\src\cli\cli.ts:49:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! invoice-generataion@6.0.1 postinstall: `npm run postinstall:electron && electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the invoice-generataion@6.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\testuser01\AppData\Roaming\npm-cache\_logs\2019-07-03T14_32_05_411Z-debug.log
---------------------------------------------------------------------------------------------------------
Node : v10.15.1
NPM : v6.4.1

**Comment by kneth** [comment]
@jindalrohit You are building against Electron 5 which at the same ABI level as node 12. Currently we don't support node 12 but we are working on it - see #2425. Either downgrade to Electron 4 or have a little patience :smile:

**Comment by jindalrohit** [comment]
It worked after downgrading the version.
