### ISSUE TITLE
"Realm accessed from incorrect thread exception" when tryin to run on IOs

### ISSUE THREAD

**Issue by justDanielMata** [realm/realm-js#2435]
## Expected Results

When trying to run my application, i get a crash on Open with the exception of the title, this only happens after upgrading my app to RN 0.59

The app opens Correctly

## Actual Results
An exception
![Simulator Screen Shot - iPhone X - 2019-07-05 at 15 52 21](https://user-images.githubusercontent.com/20018305/60740669-022f8180-9f3d-11e9-92d9-a15cec5fff24.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.0
- Node or React Native: node v9.4.0 and react native 0.59.9
- Client OS & Version: IOS 12.2
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@justDanielMata From the stack trace, it looks like you are using Realm Cocoa and Realm JavaScript in the same app. We don't support it as such, and you have to be careful to select versions ofRealm Cocoa and Realm JavaScript which are using the same version of Realm Core.

Moreover, Realm is in general thread-confined. You can read more about it [here](https://realm.io/docs/objc/latest/#passing-instances-across-threads) and [here](https://realm.io/docs/objc/latest/#using-a-realm-across-threads).
