### ISSUE TITLE
Prebuilt binaries for Electron 4.2.x

### ISSUE THREAD

**Issue by rajivshah3** [realm/realm-js#2452]
## Goals

Is it possible to provide prebuilt binaries for Electron 4.2.x? It seems like they're provided for 4.0.x and 4.1.x: https://github.com/realm/realm-js/blob/46bf1160b86e37a78cb810ed3c9b317021af12ad/Jenkinsfile#L8

However, according to the Electron [release notes](https://electronjs.org/releases/stable?version=4&page=2#4.2.0):

>The 4.2.x series is now only release line in the 4.x.y major release line that will receive bug fixes and security fixes. 

It would be super helpful to us (and likely others) since it wouldn't require us to install the Windows 8.1 SDK (required by https://github.com/realm/realm-js/blob/master/realm.gypi#L212) alongside the Windows 10 SDK (which we already have)

**Comment by kneth** [comment]
We could add v4.2 to the list of unsupported versions of Electron :smile:

**Comment by kneth** [comment]
@rajivshah3 I have released it in v3.0.0-beta.2. I understand if you can't use it in production. The schedule of a regular release is not carved in stone yet so don't expect it soon.

**Comment by rajivshah3** [comment]
Thanks!
