### ISSUE TITLE
addListener and ping timeout after restart node.js server

### ISSUE THREAD

**Issue by waqasghouri89** [realm/realm-js#2461]
Hi, 

I'm realm-js with node.js server and express.io. The problem I'm facing and stuck with **addListener** & **ping timeout**. FYI: 200+ user can be use the application at the same time.

- When I start node.js server, I logging admin user and save its instance in variable for later user in overall project. and bind the event to detect any change at any path and do further functionality like send push notification and socket fire. 

![image](https://user-images.githubusercontent.com/6640637/61515648-207f8d80-a9d1-11e9-9144-3402135940d6.png)

- Just after the server started, user's from mobile app iOS (Realm SDK) & Android ( Realm SDK), adding message which sync to Realm Database and event listener also fire. but now user come after 5 minutes or later and send message, it syned to Realm Studio but event not fired. (It fired but taking time to fire) and admin not aware with the user's message on time. 

is any one facing the same scenario or have any resolution? the problem I detect is that if user cann't continuously ping to realm its connection doesn't keep live or break. which come live after few minutes and then event fire.

**Comment by kneth** [comment]
I believe it is similar to #2074. Moreover, I have seen it reported in a private communication, but I haven't been able to reproduce it.
