### ISSUE TITLE
Undefined is not a constructor (evaluating 'new XMLHttpRequest()')

### ISSUE THREAD

**Issue by bachlongkocanh** [realm/realm-js#2465]
Import realm app IOS crash and return error

## Actual Results

Turn off debugger:
`Undefined is not a constructor (evaluating 'new XMLHttpRequest')`
Turn on debugger work.

## Steps to Reproduce

`Import REALM from 'realm'`

## Version of Realm and Tooling

- Realm JS SDK Version: `v2.29.1 (latest)`
- Node or React Native: `node: v8, react-native: 0.59, react: 16.8.3`
- Client OS & Version: `MAC OSX 10.13.6`
- Which debugger for React Native: `Xcode 10.1`

### P/S: I don't want downgrade version react native.

**Comment by kneth** [comment]
I have tried to reproduce it with a little app today with luck.

Is `XMLHttpRequest` defined if you don't import Realm and just call the constructor on your app?
