### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by AwanesowArtem** [realm/realm-js#2466]
Hi everyone.
Want to make pagination with the following code: 
```
public static getNewsList(page: Page): NewsItem[] {
    const news = realm
      .objects<NewsItem>(NewsItemSchema.schema.name)
      .slice(page.offset, page.limit)

    return Array.from(news)
  }
```
When the code is executed for the first time it works correctly: offset is 0 and limit is 20 - 20 records are returned.
But when this code is executed for the second time with offset: 20 and limit: 20 - 0 records are returned.
What am I doing wrong?
Note: There are records 40 in "news" table: the code should have been worked correctly.
Thanks in advance.

**Comment by kneth** [comment]
`slice()`'s second argument is end and not length:

* https://realm.io/docs/javascript/latest/api/Realm.Collection.html#slice
* https://www.w3schools.com/jsref/jsref_slice_array.asp

**Comment by kneth** [comment]
As my test hasn't been able to reproduce it, I close the issue. If you still experience issues with `slice()`, please reopen.
