### ISSUE TITLE
Error: Missing right-hand side of OR

### ISSUE THREAD

**Issue by dimlksin2** [realm/realm-js#2467]
Hello, after updating the realm version to 2.29.1, we get an error
Is there a solution?

realm.objects('Services').filtered('Type = 0 || Type = 1')

{ [Error: Missing right-hand side of OR] line: 211801, column: 36 }

swears at | |

**Comment by mjm918** [comment]
I am facing the same issue. As a workaround, you can use like following:
```
let service = realm.objects('Services');
service = service.filter((key,idx)=>{
         return key.Type == 0 || key.Type == 1;
});
```

**Comment by ironage** [comment]
Are you using this query to subscribe to query based sync, or is this only operating on a local Realm?
Are you calling anything else after `filtered(...)` such as `.sorted()`?
Can you confirm that the `Type` property is an indexed integer (or primary key)?

**Comment by mjm918** [comment]
In my case, I was using local realm.

I was not calling anything after `filtered`

The property I was comparing, was not indexed int. It was `double`.

**Comment by ironage** [comment]
@mjm918  are you able to share the exact query that was failing? If possible please share your schema for the class which you are running the query on. I'm not able to reproduce this error yet.

**Comment by mjm918** [comment]
Hi @ironage , thanks for your concern. I am sharing my code below:

```
ProductList.schema = {
    name: TBL_PRODUCT,
    primaryKey: 'product_id',
    properties: {
        product_id: {
            type: 'int',
            indexed: true
        },
        product_code: 'string',
        product_name: 'string?',
        product_desc: 'string?',
        product_remark: 'string?',
        sequence_no: 'int?',
        product_status: 'int?',
        QR_code: 'string?',
        product_current_quantity: 'double?',
        product_available_quantity: 'double?',
        product_cost_price: 'double?',
        category_id: 'int?',
        product_group_id: 'int?',
        search_price: 'double?',
        search_uom: 'string?',
        search_min_price: 'double?',
        search_def_image: 'string?',
        updated_at: 'date'
    }
}
```

`let product = realm.objects(TBL_PRODUCT).filtered('product_available_quantity >= $0 AND product_available_quantity <= $1', parseFloat(from_qty), parseFloat(to_qty));`

I noticed one thing that if `from_qty ` and `to_qty` is same I get the error most of the time. On the other hand, for example if `from_qty` is `12` and `to_qty` is `4000`, I get the error too.

**Comment by kneth** [comment]
I haven't been able to reproduce. If the issue persists, I would appreciate an example which can reproduce it.
