### ISSUE TITLE
Fix applyPermissions() 

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-js#2472]
`applyPermissions({ userId }, path, 'read')` gives read permission to one user.
But `applyPermissions(userid, path, 'read')` gives read permission for public.

**Comment by nirinchev** [comment]
Does this happen with 3.x?

**Comment by raudabaugh** [comment]
@nirinchev In 3.0.0-node12.1, `applyPermissions(userId, path, 'read')` raises this error:
`Error: Your request parameters did not validate. 'condition': Invalid parameter 'condition'!`

`applyPermissions({ userId }, path, 'read')` sets the permissions as expected.

**Comment by blagoev** [comment]
This one is working as expected in realmjs 3.0. Will close this issue. Please reopen if it is not for you.
