### ISSUE TITLE
Getting issue in linking in react native 0.59.0

### ISSUE THREAD

**Issue by navneetgarggate6** [realm/realm-js#2474]
yarn add realm@2.24.0

debug Package to link: realm
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at /node_modules/@react-native-community/cli/build/cliEntry.js:152:22

**Comment by kneth** [comment]
@navneetgarggate6 Do you get the same error if you install a recent version of Realm?

**Comment by navneetgarggate6** [comment]
Yes i tested with latest version as well and getting same issue

**Comment by kneth** [comment]
Does it work if you are using `npm` instead of `yarn`?

**Comment by navneetgarggate6** [comment]
Yes same issue with npm as well.

**Comment by kneth** [comment]
https://github.com/react-native-community/cli/issues/273#issuecomment-482584211 indicates that it might be an issue the our Podfile. Can you try to add the comment to the Podfile manually and see if it helps?

**Comment by navneetgarggate6** [comment]
I am using it on Linux machine and I just want to use in for android only.

**Comment by kneth** [comment]
Please run `realm-native link realm --verbose` and post the output.

**Comment by navneetgarggate6** [comment]
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: realm
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/home/owner/projects/mytest/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/home/owner/projects/mytest/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at /home/owner/projects/mytest/node_modules/@react-native-community/cli/build/cliEntry.js:152:22

**Comment by navneetgarggate6** [comment]
any update on this ?

**Comment by kneth** [comment]
Unfortunately I am not able to reproduce it. Starting a new app:

```
react-native init LinkApp --version 0.59.0
cd LinkApp/
npm install realm@2.24.0 --save
react-native link realm
```

Output from the last command is:

```
info Linking "realm" iOS dependency
info iOS module "realm" has been successfully linked
info Linking "realm" Android dependency
info Android module "realm" has been successfully linked
```

I get the same result on MacOS and Debian GNU/Linux 9.

Three quick additional questions:

* Did you add Realm to an existing app?
* Which other dependencies to you have?
* If yes to the first question, did you remove the temporary build directory?

**Comment by navneetgarggate6** [comment]
I am using node 12 on Ubuntu 16

Did you add Realm to an existing app?

Yes I am using react native ignite cli (https://github.com/infinitered/ignite)

**Comment by kneth** [comment]
Which parameters do you use?

**Comment by navneetgarggate6** [comment]
parameters for ignite ?

ignite new TestProject -b ignite-bowser@4.5.0

**Comment by kneth** [comment]
I have no experience with Ignite, so please open (and mention me) an issue at https://github.com/infinitered/ignite

**Comment by navneetgarggate6** [comment]
Ok let me check it again. I am closing this issue for now.
