### ISSUE TITLE
iOS app is going to crash or stuck when remote debugging is enabled.

### ISSUE THREAD

**Issue by sahilpandya** [realm/realm-js#2477]
When remote debug mode is enabled that time app is going to crash, stuck **incrementPendingJSCalls** place inside React native code.
Realm is working fine when the app remote mode disabled.

### Version of Realm and Tooling
 Realm JS SDK Version: 2.29.1
 React Native: 0.52

**Comment by kneth** [comment]
@sahilpandya Do you use ExpoKit? If you do, other users have had the same problem (https://github.com/realm/realm-js/issues/1783#issuecomment-415339204). If don't, it might be a duplicate of https://github.com/realm/realm-js/issues/1538.
