### ISSUE TITLE
Realm React Native LIKE doesn't seem to work!

### ISSUE THREAD

**Issue by Yieron** [realm/realm-js#2481]
Realm.objects('Stores').filtered('cStoreFullName LIKE \"' + this.state.searchContent + '\" OR cStoreCode LIKE \"' + this.state.searchContent + '\"')

Realm like doesn't seem to work.

I replaced it with

Realm.objects('Stores').filtered('cStoreFullName CONTAINS \"' + this.state.searchContent + '\" OR cStoreCode CONTAINS \"' + this.state.searchContent + '\"');
 
It is OK。

**Comment by kneth** [comment]
@Yieron 

`LIKE` requires you to have wildcards (`*` and `?`). Your query should be something like:

```
Realm.objects('Stores').filtered('cStoreFullName LIKE "*' + this.state.searchContent + '" OR cStoreCode LIKE "*' + this.state.searchContent + '"')
```

Please take a look at [the documentation](https://realm.io/docs/javascript/latest/#filtering).
