### ISSUE TITLE
BUG - Fields being reset and cleared on migration when changed to required

### ISSUE THREAD

**Issue by levipro** [realm/realm-js#2484]
Changing a field from optional to required in schema clears the value even if it is already set

## Goals

Change a field in the database from optional to required

## Expected Results

Fields that are set should stay intact

## Actual Results

As soon as I change the field to `optional: false` and then increment the schema number I reload the app.

My data does not stay intact....
Date fields get reset to Dec 31, 1969 at 4:00:00 PM
Ints get set to 0
Strings get set to ""

## Steps to Reproduce

I am running react native 0.60.4 and realm 2.29.2 on iOS 12.2

And this happens in both debug and release modes.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- Node or React Native: 0.60.4
- Client OS & Version: iOS 12.2
- Which debugger for React Native: ?/None0

**Comment by kneth** [comment]
@levipro How do your [migration function](https://realm.io/docs/javascript/latest/#performing-a-migration) look like? The migration function must copy the values from the old to the new Realm (unfortunately the doc isn't clear on that).

Doing from optional to required (or the opposite) will add a new column and remove the old column in the underlying table (see https://github.com/realm/realm-object-store/blob/master/src/object_store.cpp#L226). That's the reason, you need a migration function.

**Comment by levipro** [comment]
@kneth thank you for the clarification
