### ISSUE TITLE
autolink problems react-native 0.60.5

### ISSUE THREAD

**Issue by joaodematejr** [realm/realm-js#2492]
Are you scheduled to release a new version of 'Realm' shared with react-native 0.60.5 autolink ??

Thankful.

## Version of Realm and Tooling

- Realm JS SDK Version: "realm": "^ 2.29.2",
- Node or React Native:? node -v 10.16.2 / "react-native": "0.60.5",
- Client OS & Version:? MacOS Mojave 10.14.6
- Which debugger for React Native:? / None

**Comment by mattijsf** [comment]
I think this is a duplicate of #2476

**Comment by joaodematejr** [comment]
OK thank you !!!

**Comment by mattmogford** [comment]
Looks like we have 2 closed, self-referencing issues here.
Is anyone working on this?? 
rnpm will be removed in the next version

**Comment by mattmogford** [comment]
> Looks like we have 2 closed, self-referencing issues here.
> Is anyone working on this??
> rnpm will be removed in the next version
Ignore me, I misunderstood the wording of the reference tag on the other issue.
