### ISSUE TITLE
Cannot call addListener when using a ES2015 class as schema

### ISSUE THREAD

**Issue by mattijsf** [realm/realm-js#2494]
## Goals

Use a class as schema (as shown per https://realm.io/docs/javascript/latest/#classes) and be able to use objects the same manner as if the schema was defined as an object.

## Expected Results

Be able to call `.addListener` on an object that is a result of `realm.create` or `realm.objects` when the schema was defined using a ES2015 class.

## Actual Results

```
ExceptionsManager.js:86 person.addListener is not a function
handleException @ ExceptionsManager.js:86
handleError @ setUpErrorHandling.js:23
reportFatalError @ error-guard.js:42
guardedLoadModule @ require.js:197
metroRequire @ require.js:122
(anonymous) @ RealmTest2.js:33
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:72
RCTLog.js:47 Running application Tripps ({
    initialProps =     {
    };
    rootTag = 11;
})
```

## Code Sample

```jsx
import Realm from "realm"

class Person {
  get fullName() {
    return this.firstName + " " + this.lastName
  }
}

Person.schema = {
  name: "Person",
  properties: {
    firstName: "string",
    lastName: "string",
  },
}

const realm = new Realm({
  path: "realm-test.realm",
  schema: [Person],
})

realm.write(() => {
  realm.create(Person.schema.name, {
    firstName: "John",
    lastName: "Smith",
  })
})

const persons = realm.objects(Person.schema.name)
const person = persons[persons.length - 1]
console.log(person.fullName)

person.addListener(obj => { // Error: person.addListener is not a function
  if (obj) {
    console.log("Changes Found! " + obj.fullName)
  }
})

```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- Node / React Native: 10.16.3 / 0.60.4
- Client OS & Version: iPhone SE / iOS 12.1 simulator
- Which debugger for React Native: Chrome

**Comment by mattijsf** [comment]
It works when I simply replace:

```jsx
  schema: [Person],
```

with

```jsx
  schema: [Person.schema],
```

But then we can't use calculated properties such as `person.fullName`

**Comment by kneth** [comment]
@mattijsf You need to do `class Person extends Realm.Object`.

**Comment by mattijsf** [comment]
Thanks. That made it work at runtime, however I'm using TypeScript and adding the `extends Realm.Object` causes the following error when defining `class Person extends Realm.Object`:

```js
Type '{ readonly prototype: Object; }' is not a constructor function type.ts(2507)
``` 

<img width="821" alt="Screenshot 2019-08-27 09 51 21" src="https://user-images.githubusercontent.com/706368/63751766-45a8cb00-c8b0-11e9-9542-268dcb4bc086.png">

**Comment by kneth** [comment]
@mattijsf Yeah, the Typescript support could be better. Please create an issue about your Typescript observations.

**Comment by djMax** [comment]
Could be better??? It doesn't work at all.
