### ISSUE TITLE
Support mirroring of binary

### ISSUE THREAD

**Issue by malice00** [realm/realm-js#2501]
## Goals

We would like to be able to host/cache the Realm Binaries on a server inside the company. This should be possible according to the documentation of 'node-pre-gyp', unfortunately because of the way Realm is configured, only the host-part of the mirror is used. Because of company rules, we also need to add a context-root to the mirror URL.

Currently when setting the mirror-property 'realm_binary_host_mirror' to any URL with a path will be cut to just the protocol and host because Realm's configuration for 'remote_path' is an absolute path ("/node-pre-gyp/{version}/"). Changing it to "./node-pre-gyp/{version}/" will make node-pre-gyp accept the configured property.

FYI: The cutting of the path for absolute remote-path values is documented behavior in node-pre-gyp, so this is not a bug on their part!

## Expected Results

I expect my Realm-Binary to be downloaded from my mirror-host.

## Actual Results

Node aborts with an exception because it is trying to connect to the wrong host and the fall-back of rebuilding from source will not work because of proxy-constraints.

**Comment by kneth** [comment]
We understand your company's requirement. Your suggestion is the same as in the example: https://github.com/springmeyer/node-addon-example/blob/master/package.json#L14.

**Comment by malice00** [comment]
Indeed it is. Shouldn't be too difficult, right? Or would you like me to create a PR?

**Comment by kneth** [comment]
@malice00 You are welcome to do so. I can make a test release so we can see if it is working.
