### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load

### ISSUE THREAD

**Issue by kishansbs** [realm/realm-js#2502]
getting this issue after build successfully, and run apk in real device.

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: Didn't find class "io.realm.react.util.SSLHelper" on path: DexPathList[[zip file "/data/app/**Package name**-_6WtNMftSBIYmN0hqHsLvw==/base.apk"],nativeLibraryDirectories=[/data/app/com.adavers.mauritiusexplored-_6WtNMftSBIYmN0hqHsLvw==/lib/arm, /data/app/com.adavers.mauritiusexplored-_6WtNMftSBIYmN0hqHsLvw==/base.apk!/lib/armeabi-v7a, /system/lib]]
at com.facebook.soloader.SoLoader.b(Unknown Source:383)
at com.facebook.soloader.SoLoader.a(Unknown Source:106)
at com.facebook.soloader.SoLoader.a(Unknown Source:96)
at com.facebook.soloader.SoLoader.a(Unknown Source:1)
at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
at io.realm.react.b.b(Unknown Source:0)
at d.b.n.P.a(Unknown Source:41)
at d.b.n.l.a(Unknown Source:30)
at d.b.n.I.a(Unknown Source:34)
at d.b.n.I.a(Unknown Source:54)
at d.b.n.I.a(Unknown Source:36)
at d.b.n.I.a(Unknown Source:0)
at d.b.n.D.run(Unknown Source:68)
at java.lang.Thread.run(Thread.java:764)

 "react": "16.8.6",
    "react-native": "0.60.4",
 "realm": "^2.29.2",

**Comment by kneth** [comment]
@kishansbs Can you try two things:

* Downgrade to v2.29.1 to see if you get the same error
* Apply the ProGuard tips at https://github.com/realm/realm-js/issues/2391#issuecomment-506573272

Moreover, do you by any chance mix 32 bit and 64 bit libraries?

**Comment by kishansbs** [comment]
here is the code --- 

android/app/build.gradle-

def enableProguardInReleaseBuilds = true

 abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"//, "arm64-v8a", "x86_64"
        }

 applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]//, "arm64-v8a": 3, "x86_64": 4
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

 packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        //pickFirst '**/arm64-v8a/libc++_shared.so'
       // pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }

 "realm": "^2.29.1",
 "react": "16.8.6",
  "react-native": "0.60.4",


getting same issues -- not time of debug, after generating apk.

![Screenshot_2019-08-30-16-00-31-075_com miui bugreport](https://user-images.githubusercontent.com/49237019/64014792-a3534680-cb40-11e9-8478-931770ba32d7.png)

**Comment by kishansbs** [comment]
running this apk --- app-armeabi-v7a-release.apk

**Comment by kishansbs** [comment]
@kneth any solution?

**Comment by paschaldev** [comment]
@kishansbs You have to disable hermes for it to work, I have experienced this issue before. Once you disable hermes, it would work fine. We are all waiting for hermes support.

**Comment by thekevinbrown** [comment]
Realm does not yet support Hermes: https://github.com/realm/realm-js/issues/2455

**Comment by kishansbs** [comment]
Hermes is already disable.

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

**Comment by kishansbs** [comment]
is library need to be link?

**Comment by kneth** [comment]
@kishansbs Did you run `react-native link realm`?

Moreover, can you inspect the `.apk` file to see if you have any Realm related `.so`?

**Comment by kishansbs** [comment]
no

**Comment by kneth** [comment]
Can it be that you are hit by #2640?

**Comment by prashantsingh0205** [comment]
@kishansbs You closed the issue. Can you please share how you resolved it. Facing same issue.

**Comment by kneth** [comment]
@prashantsingh0205 Did you by any change enable Hermes? We have seen an error similar to this when Hermes is enabled (and we do not yet support Hermes).

**Comment by ShridharCodewave** [comment]
Hello, I am using react native 0.59.9 and realm 2.29.1 and facing the same issue any solution for this?

**Comment by kneth** [comment]
@ShridharCodewave Please create a new issue where you fill out the issue template so we can see what can be the issue.

**Comment by shrivastavaanurag** [comment]
[this link](https://github.com/realm/realm-js/issues/2015#issuecomment-437559270) reslove the issue.

**Comment by gboyegadada** [comment]
> @kishansbs You have to disable hermes for it to work, I have experienced this issue before. Once you disable hermes, it would work fine. We are all waiting for hermes support.

This worked for me after 2 days of debugging ! Thanks 🍻

**Comment by faisolp** [comment]
> Hermes is already disable.
> 
> project.ext.react = [ entryFile: "index.js", enableHermes: false, // clean and rebuild if changing ]

I tried .,that ok
