### ISSUE TITLE
Debugging the application after installing realm-js

### ISSUE THREAD

**Issue by Anytram** [realm/realm-js#2510]
Hello,
After installing realm-js, the program works fine, however after trying to enable Debug JS Remotly on the android emulator I'm getting an error:
![image](https://user-images.githubusercontent.com/37418524/64323301-85fcfd00-cfc4-11e9-9cb0-e656c4bc13e5.png)

The only working solution that I found is:
"Easy fix is to goto node_modules/realm/lib/browser/rpc.js and replace line 216 with let url = 'http://127.0.0.1:8083/' + command;" (https://stackoverflow.com/a/46658650)

Unfortunately, this solution requires changing the code in node_modules. 
That is why I am asking you, is there a better solution to this problem?

- Realm JS SDK Version: 2.29.2
- React Native: 0.60
- Which debugger for React Native:  Remote debugging on chrome

**Comment by paschaldev** [comment]
No don't edit the node file, shake your device to open the react native menu and look for Dev server settings, update with the IP and PORT and then reload.

**Comment by bmunkholm** [comment]
Closing as this seems resolved.

**Comment by BravenxX** [comment]
Your solution doesn't work for me... I've been searching for like 2 hours
