### ISSUE TITLE
How to create .realm file and upload it to S3 bucket using serverless framework?

### ISSUE THREAD

**Issue by mithunph** [realm/realm-js#2511]
Below is my code:
    Realm.open({schema: [schemaName], path: 'filepath', schemaVersion: 1})
    .then(realm => {
        realm.write(() => {
            console.log('completed file==');
        });
        realm.close();
    })
    .catch(error => {
    console.log(error);
    });

**Comment by bmunkholm** [comment]
Hey @mithunph 
As mentioned in the issue template, we only use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Forum](https://forums.realm.io/).

Also when you do post issues, please fill out the entire template we provide.

Thanks for your help!
