### ISSUE TITLE
TypeError: Cannot assign to read only property 'getListenerDirectory' 

### ISSUE THREAD

**Issue by StevenMasini** [realm/realm-js#2514]
## Goals

Trying to run my test suite using Jest.

## Expected Results

The test suite should pass without error.

## Actual Results

Since I updated to the latest realm version 2.29.2 I am getting this error in my test suite.

`TypeError: Cannot assign to read only property 'getListenerDirectory' of function 'function Sync() { [native code] }'`

## Steps to Reproduce

Nothing special. But if I downgrade to realm 2.26.1 the issue is gone.

## Code Sample

Just using `import Realm from 'realm'` cause this issue, nothing else than this.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- Node or React Native: v10.16.0
- Client OS & Version: RN 0.60.5
- Which debugger for React Native: None

**Comment by StevenMasini** [comment]
I also would like to specify that I got this issue after implement **linear migration** in my project. 

Base on my research, the error come from `notifier.js` and more specifically this [line](https://github.com/realm/realm-js/blob/0acb954b24614795a3ddf88be3ec45dae20b0865/lib/notifier.js#L339).

In [2.26.1](https://github.com/realm/realm-js/blob/v2.26.1/lib/notifier.js) this line doesn't exist and since I downgrade I don't have the issue.

**Comment by kneth** [comment]
@StevenMasini Thank you for reporting. Is it possible for you to create a very small sample app which can reproduce the behaviour?

**Comment by kneth** [comment]
@StevenMasini I am closing the issue for now. If you observe it, you are welcome to reopen it.
