### ISSUE TITLE
"rnpm" config that will stop working from next release in react-native 0.60

### ISSUE THREAD

**Issue by rayjadore** [realm/realm-js#2515]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by marcodafonseca** [comment]
+1

**Comment by nirinchev** [comment]
Please don't open duplicate issues. Also, next time you need to open issue, be sure to fill the template to make it easier to get help. In any case, https://github.com/realm/realm-js/issues/2476 already tracks the rnpm deprecation.
