### ISSUE TITLE
Unique Push

### ISSUE THREAD

**Issue by zek** [realm/realm-js#2522]
I would like to push a list if item does not exists already.
I tried below but it does not work when we hit this function multiple times at same time.
~~~
  addMessage(message, userId, seen = false) {
    if (ChatMessage.findById(message._id)) {
      return message._id;
    }
    this.lastUpdate = new Date();
    const m = ChatMessage.create({
      ...message,
      user_id: userId || Store.auth.user.id,
      seen: seen,
    });
    this.messages.push(m);
    return m._id;
  }
~~~

![image](https://user-images.githubusercontent.com/3463291/65076228-43162e80-d9a1-11e9-9f4c-253da741404a.png)

As you can see there are 7 ChatMessage but 8 messages in Chat.

**Comment by kneth** [comment]
From your description it sounds like you have multiple invocations of `addMessage()` within the same transaction. Is it possible to break it down into smaller transactions? I mean, so `addMessage()` is one small transaction?

**Comment by zek** [comment]
2 different device tries to invocate addMessage within the same time actually. I use full sync feature btw.

**Comment by kneth** [comment]
@zek Sorry, I missed that you are using multiple devices. In this case, it is expected that you will see the same object twice in the list due to how the merge algorithm works. You can use a filter to emulate uniqueness (`chatMessages.filtered('DISTINCT('_id'))`).
