### ISSUE TITLE
Realm created 17 gb of files on server root

### ISSUE THREAD

**Issue by ahsankhan1911** [realm/realm-js#2526]
Hi,
We are using Realm Cloud for real time chat and other different purposes in our app. But after some time Realm created heavy files 17 GB on the server root.

I want to know If I will delete those files will will it effect my data or anything else on the server. ? I want to delete it because I think its too much of storage. As we are using Realm cloud why its using system 17 GB storage?

Second thing is that. Is there any solution or feature of realm to use it without the generation of those heavy cache files or in simple word what is the best way to manage to those files ? 

## Version of Realm and Tooling

- Realm JS SDK Version: 2.20.0 (NPM module realm)
- Node or React Native: Node
- Client OS & Version: Ubuntu 16.04.1 LTS
- Which debugger for React Native: None

**Comment by bmunkholm** [comment]
Hey @ahsankhan1911,
As mentioned in the issue template, we only use this repo for bug reports and feature requests. For questions about how to use realm best, we defer to our [Forum](https://forums.realm.io/).
That said, please add details as we have no clue what you are doing server side, and which files are becoming big.

**Comment by ahsankhan1911** [comment]
okay thank you
