### ISSUE TITLE
Installing realm 3.1.0 fails during node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by braudabaugh** [realm/realm-js#2532]
I've tried installing this on Windows, Ubuntu and MacOS.  All fail with the same error.
```
$ npm install

> realm@3.1.0 install C:\Workspaces\ThreadLearning\thread-rest\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Workspaces\\ThreadLearning\\thread-rest\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Workspaces\ThreadLearning\thread-rest\node_modules\realm
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
```

**Comment by MobileAppVault** [comment]
Which version of node you are using?

In previouse realmjs version `node 12` didn't worked for me. Downgrade to `node 10` fixed the issue for me.

**Comment by nirinchev** [comment]
According to [this node-pre-gyp issue](https://github.com/mapbox/node-pre-gyp/issues/367), it seems to be mostly network related - can you try installing on a different network?

**Comment by fansilva1991** [comment]
I having a similar issue here while building my application.

It started to fail without any change on my package.json file.

```
38757 verbose stack Error: realm@2.29.2 install: `node-pre-gyp install --fallback-to-build`
38757 verbose stack Exit status 6
38757 verbose stack     at EventEmitter.<anonymous> (/Users/vsts/hostedtoolcache/node/10.15.3/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
38757 verbose stack     at EventEmitter.emit (events.js:189:13)
38757 verbose stack     at ChildProcess.<anonymous> (/Users/vsts/hostedtoolcache/node/10.15.3/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
38757 verbose stack     at ChildProcess.emit (events.js:189:13)
38757 verbose stack     at maybeClose (internal/child_process.js:970:16)
38757 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by braudabaugh** [comment]
Looks like there was some dependency change that broke node-pre-gyp https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by bmamone** [comment]
I'm facing the same issue right now trying to install Realm on my project.

> Which version of node you are using?
> 
> In previouse realmjs version `node 12` didn't worked for me. Downgrade to `node 10` fixed the issue for me.

I guess the common `node v12` error not related. There are different outputs when using Node 10 or 12.

When running on `v12.6.0` I get:

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/3.1.0/realm-v3.1.0-node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for realm@3.1.0 and node@12.6.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
(...)
```

And after that it errors on the source compile.

When running on `v10.11.0`:

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Linux 5.1.11-arch1-1-ARCH
node-pre-gyp ERR! command "/home/*******/.nvm/versions/node/v10.11.0/bin/node" "/home/*******/projects/*******/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/*******/projects/*******/node_modules/realm
node-pre-gyp ERR! node -v v10.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

**Comment by janet-rivas** [comment]
I'm having the same issue 

node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/vsts/.nvm/versions/node/v8.16.1/bin/node" /work/1/s/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vsts/agent/2.155.1/work/1/s/node_modules/realm
node-pre-gyp ERR! node -v v8.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! realm@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the realm@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I tried  Node version 12.x and 10.x  this did not work

**Comment by janet-rivas** [comment]
> Which version of node you are using?
> 
> In previouse realmjs version `node 12` didn't worked for me. Downgrade to `node 10` fixed the issue for me.

Could you please share the node version ?

**Comment by vaibsshukla** [comment]
Facing same issue !!!!


> realm@3.1.0 install /Users/vaibhav/Desktop/test/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/vaibhav/Desktop/test/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vaibhav/Desktop/test/node_modules/realm
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! realm@3.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the realm@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vaibhav/.npm/_logs/2019-09-24T07_08_59_578Z-debug.log

**Comment by dionisio28** [comment]
Yesterday I had this same error, I have node in version 10.16.3, so today I tried to install with the command _npm install realm --save_ and it worked **(Windows 10)**

**Comment by bmamone** [comment]
Installing with `npm install realm --save` using Node.js v10.11.0 on Linux is now working again

**Comment by springmeyer** [comment]
This should be fixed now as long as your package-lock.json does not try to install `minipass@2.8.4`: see https://github.com/mapbox/node-pre-gyp/issues/477#issuecomment-534630617

**Comment by bmunkholm** [comment]
Seems resolved now. Otherwise please provide a repro case. Thanks!

**Comment by Janjiran** [comment]
Remove minipass lines from your `yarn.lock/package.lock` file and it should work.

![image](https://user-images.githubusercontent.com/50450387/67041023-09ae1b80-f125-11e9-8ea4-a7dbf9842f55.png)

**Comment by thebigredgeek** [comment]
This happens with latest yarn with nodejs v12.6.0 and realm version 2.29.2 (according to the installed package.json)

**Comment by andrekovac** [comment]
Get the same errors as @thebigredgeek with node v12.18.3 --> The latest LTS release.

**Comment by andrekovac** [comment]
Node v12 is not supported by Realm v3.x as mentioned here: https://github.com/realm/realm-js/issues/2880#issuecomment-628665377

**Comment by ivanhoe-dev** [comment]
for those who are still suffering from this, I solved this by downgrade my Node.js version to v10.18.0. As suggested by @andrekovac , Realm v3.x doesn't support node12
