### ISSUE TITLE
fifo.cannot find fifo.cpp 

### ISSUE THREAD

**Issue by eladgel** [realm/realm-js#2541]
## Goals

Run on simulator

## Expected Results

Build and deploy to simulator

## Actual Results

Build fails

Showing All Errors Only
Build input file cannot be found: '/APP_PATH/node_modules/realm/src/object-store/src/util/fifo.cpp'

## Steps to Reproduce

Upgraded to "realm": "3.1.0" and I can't build the project anymore when downgrading back to 2.29.2, all goes back to normal and build succeeds. 
I use cocoapods in my project but realm is not a part of it

## Version of Realm and Tooling

- Realm JS SDK Version: 3.1.0
- Node or React Native: 59.9
- Client OS & Version: IOS 13.0
- Which debugger for React Native: None

**Comment by eladgel** [comment]
** update
 tried removing referenes from fifo.cpp in the pbxproj file.. now I see this
![image](https://user-images.githubusercontent.com/412137/65761358-4a6ad400-e127-11e9-9348-2ff8529a57e3.png)

**Comment by kneth** [comment]
Please try to clean the build folder and rebuild. The files `fifo.hpp` and `fido.cpp` were moved from Realm Object Store to Realm Core in v3.0.0.

**Comment by eladgel** [comment]
removed folder clean build and the first problem was solves, opening a different issue for the second
