### ISSUE TITLE
management-schemea is missing

### ISSUE THREAD

**Issue by eladgel** [realm/realm-js#2543]
## Goals

Run on simulator

## Expected Results

Build and deploy to simulator

## Actual Results

Build succeeds then when running I get an exception saying that a module is missing, the module's name is management-scheme

## Steps to Reproduce

Upgraded to "realm": "3.1.0" and I can't run the project anymore, getting red screen. When downgrading back to 2.29.2, all goes back to normal and the app loads.
## Code Sample

![65761358-4a6ad400-e127-11e9-9348-2ff8529a57e3](https://user-images.githubusercontent.com/412137/65776193-49976980-e14a-11e9-99e0-dbb8691c87fe.png)

## Version of Realm and Tooling

Version of Realm and Tooling
Realm JS SDK Version: 3.1.0
Node or React Native: v10.16.3 / 59.9
Client OS & Version: IOS 13.0
Which debugger for React Native: None

**Comment by Imran-cse** [comment]
I'm using realm@3.0.0 and facing the same issue.

**Comment by bmunkholm** [comment]
@eladgel @Imran-cse Could you please update a reference to a gihub repo with a sample app that demonstrates the issue? Thanks!

**Comment by eladgel** [comment]
@bmunkholm sure it will take me some time as my project is very heavy

**Comment by eladgel** [comment]
@Imran-cse not happening anymore do you have react-native-webview installed?

**Comment by kneth** [comment]
Please try to remove `node_modules` and run `npm install` again.
