### ISSUE TITLE
Support Core logging

### ISSUE THREAD

**Issue by thekevinbrown** [realm/realm-js#2546]
## Goals

Things don't always go as expected. Developers should have a way to enable a sort of trace logging with Realm so they can see what it's doing in a production application. Without logging we have to go through a lot of extra work to narrow down performance issues.

## Expected Results

There should be a way to enable logging, either by configuring Realm, or for performance reasons packaging up the logging version as a different NPM dependency.

## Actual Results

The only way to debug what Realm is doing is to guess at what might be causing a problem and remove it. 

## Steps to Reproduce

Have someone that is not familiar with Realm trying to make a repro to demo a bug. It takes a lot longer than it should.

## Code Sample

Not relevant

## Version of Realm and Tooling

- Realm JS SDK Version: Any
- Node or React Native: Any
- Client OS & Version: Any
- Which debugger for React Native: None

## Note

This issue was originally raised as #2499, I'm splitting it out because multiple separate and unconnected issues were discovered in exploring there.

**Comment by DDeathlonger** [comment]
Bump, agreed. (in all releases, dotnet loves some love too.)
