### ISSUE TITLE
How does realm lazy loading work? 

### ISSUE THREAD

**Issue by alnorris** [realm/realm-js#2565]
Hi,
I'm trying to figure out how to implement infinite scrolling since there is no limit. I've been testing the library and console.log or debugger lists all items in cars with their data, even if there are 500,000+

My understanding with realm being lazy is that I shouldn't be able to do this, and only when I directly access the object I should see it.?

>     const cars = realm.objects('Car')
>     console.log(cars)

**Comment by kraenhansen** [comment]
Realm Studio uses [react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/List) to load only the objects the user is scrolling to. The more lightweight [react-window](https://react-window.now.sh/#/examples/list/fixed-size) which was based on the react-virtualized codebase, might also be relevant here.
