### ISSUE TITLE
Error building iOS:  The file “Info.plist” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by dakkafex** [realm/realm-js#2573]
## Goals

Trying to build iOS with realm but the the error 
``` could not read data from '/Users/---/Documents/Softwaremancy/MyApp/node_modules/realm/tests/ios/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file```  keeps popping up.

I have tried a host of different solutions, from downgrading to 2.28, which produces different errors like "No member named 'clock' in the global namespace; did you mean 'flock'?", removing RealmJSTests from the RealmJS project targets, which does produce a succesfull build but results in the app error "Missing realm constructor"
## Expected Results

A successful build.
## Actual Results

Build failure with the above mentioned error
## Steps to Reproduce

1.yarn add realm
2. react-native link realm
3. build with xcode

## Version of Realm and Tooling

- Realm JS SDK Version: 3.2.0 (also tried 3.3.0)
- Node or React Native:  RN 0.59.8
- Client OS & Version: Xcode 10.1

**Comment by dakkafex** [comment]
I removed the tests target from the realm lib and now i am met with 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is it perhaps an issue that im using cocoa pods along with realm?

**Comment by sej1228** [comment]
Is it solved now? I have the same problem

**Comment by dakkafex** [comment]
still cannot get past ```` duplicate symbol '_OBJC_IVAR_$_GCDWebServerURLEncodedFormRequest._arguments' in:
    /Users/henk/Library/Developer/Xcode/DerivedData/WhosThat_app-axxkmftwrprdsnaxtynfzrtgsvca/Build/Products/Debug-iphonesimulator/libGCDWebServers.a(GCDWebServerURLEncodedFormRequest.o)
    /Users/henk/Library/Developer/Xcode/DerivedData/WhosThat_app-axxkmftwrprdsnaxtynfzrtgsvca/Build/Products/Debug-iphonesimulator/libRealmReact.a(GCDWebServerURLEncodedFormRequest.o)
ld: 177 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by martin9908** [comment]
I'm also experiencing the same issue. What could have been the cause of this issue?

**Comment by dakkafex** [comment]
so what i figured out is that realm does not completely remove itself with simply ```yarn remove realm``` if someone knows how to completely scrub realm from my project, appreciated.

**Comment by kneth** [comment]
> so what i figured out is that realm does not completely remove itself

Did you run `react-native unlink realm` before removing Realm? Did you clear the build folder so no transient files exist?

**Comment by JediahDizon** [comment]
I cloned this repository, copied the `tests` folder and past it in the place XCode is complaining about and it compiled. Now, I'm having the error `Missing realm Constructor, did you run react-native link realm?`

**Comment by bmunkholm** [comment]
@JediahDizon @dakkafex  Is this still a problem with 6.0?

**Comment by kneth** [comment]
I am closing the issue due to lack of activity. Please reopen or create new issue if you still experience it.
