### ISSUE TITLE
Will realm support react native 60 above for android.

### ISSUE THREAD

**Issue by ankitjpk** [realm/realm-js#2581]
Apk crashes after building the app.

I get
`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: library "libjsc.so" not found`

**Comment by BravenxX** [comment]
I'm using 0.61.2 and it's working for me. I don't know about your error but isn't because Rn version.

**Comment by shubhang93** [comment]
> Apk crashes after building the app.
> 
> I get
> `java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: library "libjsc.so" not found`

I believe you are trying to use hermes engine, Realm is not compatible with the hermes js engine yet. Please make sure the enableHermes in your build.gradle is set to false.

**Comment by kneth** [comment]
I am closing the issue. If it persists when `enableHermes` is set to false, please reopen the issue.

**Comment by saibharani** [comment]
if you are keen on using hermes or react native v8 engines you can have a look at [https://github.com/vasern/vasern](vasern) it supports both of them
