### ISSUE TITLE
Cannot install realm for React Native project on windows 10 using npm 

### ISSUE THREAD

**Issue by shivam-yadav-au1** [realm/realm-js#2582]
## Expected Results

 Want to install realm database in react-native project by using npm install command  

## Actual Results

 realm@2.23.0-hotfix.1 install C:\Digiprex\RakshaCardAgentApp\node_modules\realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.23.0-hotfix.1/realm-v2.23.0-hotfix.1-node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for realm@2.23.0-hotfix.1 and node@12.10.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Warning: Missing input files:
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\scripts\test.sh
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\scripts\set-version.sh
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\scripts\publish.sh
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\src\object-store\src\util\compiler.hpp
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\scripts\changelog-header.sh
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\src\object-store\src\descriptor_ordering.hpp
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\lib\browser\util.jsscripts\build-node-pre-gyp.ps1
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\..\src\object-store\src\util\time.hpp
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\OpenSSL.vcxproj(21,3): error MSB4019: The imported project "C:\
Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\scripts.vcxproj(21,3): error MSB4019: The imported project "C:\
Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Digiprex\RakshaCardAgentApp\node_modules\realm\build\vendored-realm.vcxproj(21,3): error MSB4019: The imported proje
ct "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Shivam\AppData\Roaming\nvm\v12.10.0\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Digiprex\\RakshaCardAgentApp\\node_modules\\realm\\compiled\\node-v72_win32_x64\\realm.node" "--module_name=realm" "--module_path=C:\\Digiprex\\RakshaCardAgentApp\\node_modules\\realm\\compiled\\node-v72_win32_x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Digiprex\RakshaCardAgentApp\node_modules\realm
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Digiprex\RakshaCardAgentApp\node_modules\realm\compiled\node-v72_win32_x64\realm.node --module_name=realm --module_path=C:\Digiprex\RakshaCardAgentApp\node_modules\realm\compiled\node-v72_win32_x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Digiprex\RakshaCardAgentApp\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Digiprex\\RakshaCardAgentApp\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Digiprex\RakshaCardAgentApp\node_modules\realm
node-pre-gyp ERR! node -v v12.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Digiprex\RakshaCardAgentApp\node_modules\realm\compiled\node-v72_win32_x64\realm.node --module_name=realm --module_path=C:\Digiprex\RakshaCardAgentApp\node_modules\realm\compiled\node-v72_win32_x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN rollback Rolling back yallist@3.1.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Digiprex\RakshaCardAgentApp\node_modules\tar\node_modules'
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN mongodb-stitch-react-native-core@4.5.0 requires a peer of react-native@^0.57.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-qrcode-scanner@1.2.3 requires a peer of react-native-camera@^1.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-drawer@2.2.2 requires a peer of react-navigation@^4.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-stack@1.5.5 requires a peer of react-navigation@^4.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@2.23.0-hotfix.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@2.23.0-hotfix.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivam\AppData\Roaming\npm-cache\_logs\2019-10-26T12_19_24_757Z-debug.log

## Version of Realm and Tooling

- Realm JS SDK Version: latest
- Node or React Native: React-Native
- Client OS & Version: Windows 10 
- Which debugger for React Native: ?/None

**Comment by Janjiran** [comment]
Same here

- mac os 10.15
- node 11.15.0
- react-native 0.61.2

**Comment by polash62** [comment]
I am also facing the same error. 

- Windows 10
- Node V12.8.1

**Comment by Janjiran** [comment]
Downgrade to node v10 resolved the issue, i’v also installed pre-gyp as dev dependency and removed minipass block from yarn.lock

**Comment by polash62** [comment]
yeah solved that issue by downgrading node version into 10.

**Comment by kneth** [comment]
I am closing the issue. We are working on support node v12 but currently only v8 and v10 are supported.

**Comment by dionisio28** [comment]
@kneth  v10.14.1 is supported ?
