### ISSUE TITLE
Unable to Archive on Xcode 11.

### ISSUE THREAD

**Issue by hussainimp** [realm/realm-js#2584]
**Unable to Archive using Xcode 11.1**
Able to build an archive on Xcode 10.3 but archive not generating on Xcode 11

**Steps**:-
1.) Install latest or old 'realm'
2.) Link the realm using - react-native link realm
3.) Start generating and archive.
4.) Fails to generate archive 

**Error** :- 
GCDWebServers target :- 
1./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/System/Library/Frameworks/Security.framework/Headers/SecProtocolTypes.h:187:18: Unknown type name 'SecTrustRef'
2. /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:9: Could not build module 'Security'
3. /Users/impadmin/Documents/Projects/ReactNativeProjects/MainBoilerPlate/node_modules/realm/vendor/GCDWebServer/GCDWebServer/Core/GCDWebServerHTTPStatusCodes.h:31:9: Could not build module 'Foundation'

**Version**:-
react-native: "0.61.1"
realm: "3.3.0",
xcode:11.1
ios:13

![Screenshot 2019-11-01 at 1 36 33 PM](https://user-images.githubusercontent.com/57175325/68011190-a4bdfe00-fcac-11e9-8060-a6dae94df971.png)

**Comment by kneth** [comment]
Thank you for reporting. It looks like one of our dependencies (`GCDWebServers`) will require an update to support Xcode 11.

**Comment by Eyesonly88** [comment]
Any update on this please?

**Comment by psk200** [comment]
Hi, Help needed for this issue, Apple will be restricting the apps after June 30 2020 if the apps are not with iOS 13.

https://developer.apple.com/news/?id=03262020b

**Comment by blagoev** [comment]
Hi, 
Which version of realm are you using. I suggest you try the latest version and see if it works for your scenario.
