### ISSUE TITLE
addProgressNotification not return like expected

### ISSUE THREAD

**Issue by khanhduytran** [realm/realm-js#2594]
## Goals

Hi,
I want to display realm download progress bar. I use `syncSession.addProgressNotification` to get the `transferred bytes` and `transferable bytes`. Return data not like i expected, it won't return the notification when downloading. It just return in the beginning and when it finished download data

## Expected Results

Returns notification about `transferred bytes` and `transferable bytes` every second or something like that
Ex:
First time i login and start download data
+ transferred: 0 KB
+ transferable: 5.6 MB

And every second or something like that it will return
+ transferred: 89 KB
+ transferable: 5.6 MB
-----------------------------
+ transferred: 1.2 MB
+ transferable: 5.6 MB
-----------------------------
+ transferred: 3.4 MB
+ transferable: 5.6 MB

And when finish download
+ transferred: 5.6 MB
+ transferable: 5.6 MB

## Actual Results

It only return the `transferred bytes` and `transferable bytes` in the beginning and when it finished download data

- Here is some picture about this issue
![Screen Shot 2019-11-06 at 15 19 33](https://user-images.githubusercontent.com/40479912/68280869-02858800-00a9-11ea-81a4-79ebde754be9.png)

## Steps to Reproduce

Just start download the data and console.log `transferred bytes` and `transferable bytes` 

## Code Sample

```
run = () => {
    this._realm.syncSession.addProgressNotification(
      'download',
      'reportIndefinitely',
      (transferred: number, transferable: number) => {
        this.test(transferred, transferable)
      }
    )
  }

test = (transferred: number, transferable: number) => {
    console.log('transferred', bytes(transferred, { unitSeparator: ' ' }))
    console.log('transferable', bytes(transferable, { unitSeparator: ' ' }))
    console.log('---------------------------')
  }
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2
- Node or React Native: ( react native - 0.59.5 ) ( node-12.6.0 )
- OS: MacOS 10.14.6
- Which debugger for React Native: Safari debugger

**Comment by nirinchev** [comment]
By default, the data is sent in chunks of 16 mb. That means that if your Realm is smaller than that, you'll get just two notifications - once when the download starts, and once when it completes.

**Comment by khanhduytran** [comment]
> By default, the data is sent in chunks of 16 mb. That means that if your Realm is smaller than that, you'll get just two notifications - once when the download starts, and once when it completes.

@nirinchev You can see in the image above. The total data is 48.69 MB, according to your answer that mean i'll get at least three notifications right ? once when the download starts, once when it reach 16 MB and once when it completes. But i'm only getting two notifications.

**Comment by nirinchev** [comment]
Ah, I was going off of the example you posted which was 5.6 mb so got confused. In that case, another factor determining download sizes is the size of the transaction. If you inserted all objects in a single transaction, that will be transferred as a single chunk to the device. Do you think that may have been the case?

**Comment by khanhduytran** [comment]
> Ah, I was going off of the example you posted which was 5.6 mb so got confused. In that case, another factor determining download sizes is the size of the transaction. If you inserted all objects in a single transaction, that will be transferred as a single chunk to the device. Do you think that may have been the case?

@nirinchev I call download request like this.
Ex: 
```
sync = ( ) => {
  const results = this._realm
            .objects<T>(this._className)
            .filtered('deleted = false')
            .sorted(descriptor, reverse)

results.subscribe(this.__className).addListener( {some call back} )
}
```

And in outside i call
```
product.sync() // download product
supplier.sync() // download supplier
category.sync() // download category
...etc
// and so on
```

**Comment by kneth** [comment]
With query-based sync I don't think the progress notifications make much sense. The subscription listener can only monitor the state changes.

**Comment by LukeStorry** [comment]
I'm still getting the same issue I think. 

```js
  realm.syncSession?.addProgressNotification('download', 'forCurrentlyOutstandingWork',
      (transferred, transferrable) => console.log({transferred, transferrable}),
    );
```
returns:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/5787482/204029088-18563093-3590-4a47-b245-2531c4e62466.png">


Although this is only 14MB, so will be transferred in the first payload, I would expect `transferrable` argument to show the total expected in the first log, to be able to calculate progress %?

ie expected for the above:
```
"transferrable": 14218575, "transferred": 1195}
"transferrable": 14218575, "transferred": 14218575}
"transferrable": 14218575, "transferred": 14218575}
```
