### ISSUE TITLE
script.js:17 Uncaught TypeError: Failed to execute 'open' on 'XMLHttpRequest': 2 arguments required, but only 0 present.     at HTMLButtonElement.loadEmployee

### ISSUE THREAD

**Issue by bozkurt30** [realm/realm-js#2606]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@bozkurt30 Please fill out the template. Otherwise, we have very little to work with.

`HTMLButtonElement.loadEmployee` is in somewhere in your code. How does it use `XMLHttpRequest`?

**Comment by bozkurt30** [comment]
@kneth thank you. I solved the problem.
