### ISSUE TITLE
Cannot find protocol declaration for 'GCDWebServerBodyWriter'; did you mean 'GCDWebServerBodyReader'?

### ISSUE THREAD

**Issue by 3degreeszw** [realm/realm-js#2614]
removed ios/build folder
Installed realm using npm install --save realm
cd ios && pod install & cd ..
react-native run-ios

## Version of Realm and Tooling

- Realm JS SDK Version: 3.4.2
- Node or React Native: 0.61.2
- Client OS & Version: IOS All Versions
- Which debugger for React Native: ?/None

**Comment by bmunkholm** [comment]
Those repro steps required some app installed. Please post a link to a minimal but full reprocase.
Thanks!

**Comment by EphraimTMadondo** [comment]
https://github.com/EphraimTMadondo/ShonaStudyBible.git

**Comment by EphraimTMadondo** [comment]
> Those repro steps required some app installed. Please post a link to a minimal but full reprocase.
> Thanks!

https://github.com/EphraimTMadondo/ShonaStudyBible.git

**Comment by kraenhansen** [comment]
I see your repository has `realm` installed as v4.0.0-beta.0 - is that intentional?

**Comment by EphraimTMadondo** [comment]
> I see your repository has `realm` installed as v4.0.0-beta.0 - is that intentional?
YES
Previously had Realm JS SDK Version: 3.4.2 but
 The problem persists

**Comment by bmunkholm** [comment]
@EphraimTMadondo Did you get this working with the 6.0 version?

**Comment by kneth** [comment]
I am closing the issue due to lack of activity. Please reopen or create new issue if you still experience it.
