### ISSUE TITLE
Error: Unable to resolve module `dns` when I want to use sorted function

### ISSUE THREAD

**Issue by enzzoperez** [realm/realm-js#2625]
## Goals
I want to return all result sorted from a table

## Expected Results
I get the error shown following

## Actual Results
Error: Unable to resolve module `dns` from `
/proyectos/app/src/storage/querys.js`: Module `dns` does not exist in the Haste module map

## Steps to Reproduce
I just add the the `sorted` function to query, but when I delete the sorted function the project work correctly. I'm doing something wrong? :thinking: 

## Code Sample
```
      if (!filter) {
            const a = realm.objects(Test.schema.name)
            const result = a.sorted('finishedDate', true)
            return result
        }
        const results = realm
            .objects(Test.schema.name)
            .filtered('id == $0', filter);
        return results;
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.28
- Node or React Native: RN 0.60.5
- Client OS & Version: Ubuntu 18.04
- Which debugger for React Native: reactotron

**Comment by kneth** [comment]
It is indeed a mystery. Realm does not include `dns` anywhere. Since `querys.js` is your file, please check if your are using `dns` somewhere.

**Comment by enzzoperez** [comment]
I did try put Sorted function again but now it's all ok :thinking: , maybe was my server, thank u
