### ISSUE TITLE
realm@3.1.0 install: `node-pre-gyp install --fallback-to-build` npm ERR! Exit status

### ISSUE THREAD

**Issue by Bhivinrk** [realm/realm-js#2644]
i got the following error while installing realm

Error:
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/fsc/Desktop/Deepr/Serenity/node_modules/realm/compiled/node-v72_linux_x64/realm.node --module_name=realm --module_path=/home/fsc/Desktop/Deepr/Serenity/node_modules/realm/compiled/node-v72_linux_x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN react-native-fast-image@7.0.2 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN Serenity@0.0.1 No repository field.
npm WARN Serenity@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! realm@3.1.0 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the realm@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/fsc/.npm/_logs/2019-12-10T07_49_31_350Z-debug.log

Development environment:
node v12.13.1
react-native-cli: 2.0.1
react-native: 0.61.2
OS:ubuntu

**Comment by kneth** [comment]
We don't support node 12 yet, please downgrade to node 8 or 10. We are working on node 12 support - see #2516.
