### ISSUE TITLE
Method to subscribe and wait for completion

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2651]
## Goals

A more intuitive API, requiring less boilerplate code from developers.

## Expected Results

In addition to https://github.com/realm/realm-js/issues/2650 we could introduce a method on `Results` to create a QBS subscription, wait for its completion and resolve to the `Results` object, enabling more one-liners.

### Option 1: `whenCompleted(name?: string, timeout?: number)`

Add a method named `whenCompleted` on the `Results` class.

This method takes:
- An optional subscription `name`
- A `timeout` (as milliseconds - ensuring that the promise either resolves or eventually gets rejected) as parameters.

Calling the method would:
- Register a (optionally named) `Subscription` on the `Result` object
- Register a listener on the `Subscription`
- Return a promise which resolves (to the original `Result` object) when the subscription transitions to the completed state or rejects if it transitions to the error state or the timeout occurs.

Note: We should also not forget to remove any subscription state change listener that we register, before resolving or rejecting the promise.

#### Example 1: Called on `Result` returned from `filtered(...)`

This would register a subscription on the filtered query and would therefore not download every `Person`.

```javascript
const persons = await realm.objects('Person').filtered('name = $0', name).whenCompleted();
```

#### Example 2: Support additional filtering

The `Result` resolved from calling `whenCompleted` would support additional filtering. In this case the subscription would download every `Person` and the filtering for teens would happen locally.

```javascript
const persons = await realm.objects('Person').whenCompleted();
const teens = persons.filtered('age > 12');
```

### Option 2: Make `subscribe(name?: string)` return something extending `Promise`

We could further improve option 1, making it less confusing that we have both `whenCompleted` and `subscribe` by making a `Subscription` inherit from `Promise`. And have that promise resolve to the `Result` which the subscription was created on.

The pattern of extending the Promise interface is [a pattern that we're already using](https://github.com/realm/realm-js/blob/master/lib/extensions.js#L216-L229).

To avoid "unhandled promise rejection" we could call a `.catch(null)` on the `Subscription` before returning it.

#### Example 3: `Subscription` resolving to the `Results` object

```javascript
// Create a subscription on persons older than 12 and await its `Result`
const teens = await realm.objects('Person').filtered('age > 12').subscribe('everyone');
// Perform an additional local filtering on the gender
const teenBoys = teens.filtered('gender = "male"');
```

- Realm JS SDK Version: 2.5.0
- Node or React Native: N/A
- Client OS & Version: N/A
- Which debugger for React Native: None

**Comment by cmelchior** [comment]
Personally I like `const persons = await realm.objects('Person').subscribe('everyone');`

This is also kinda what Java exposes with:
````
Subscription sub = realm.where(Person.class).subscribe('everyone');
sub.addChangeListener(...)
```

But we can do that because the Subscription object in Java is a normal Realm Object.

**Comment by kraenhansen** [comment]
That's not the same? You can already do this with the latest version of Realm JS:

```
const subscription  = realm.objects('Person').subscribe('everyone')
subscription.addListener((results, state) => { /* ... */ });
```

**Comment by kraenhansen** [comment]
I'll close this for now, until we get clarity on the future of a replacement of query-based sync.
