### ISSUE TITLE
Realm addListener methods called for zero modifications

### ISSUE THREAD

**Issue by karthikpala** [realm/realm-js#2652]
## Goals
I am trying to add listener on the realm result objects in the constructor method of the component using the below code to identify any modifications/deletions and insertions if made on the realm dB Object.
[https://realm.io/docs/javascript/2.29.0/api/Realm.Results.html#addListener](url)

Eg: `this.PositionDB.addListener(this.listenToPositionChanges);`
and
`listenToPositionChanges = (collection, changes) => {
  console.log(changes.insertions.length + "insertions");
  console.log(changes.modifications.length + "modifications");
  console.log(changes.newModifications.length + "newModifications");
  console.log(changes.oldModifications.length + "oldModifications");
  console.log(changes.deletions.length + "deletions");
  console.log("new size of collection:"+ collection.length);
}`

## Expected Results

The registered listener method should be called only when any changes are made to the specified Realm result object in realm dB

## Actual Results

The method is called immediately after rendering the component - i.e, opening the page for the first time. The logs printed were as below which shows zero modifications to the realm object.

`0insertions`
`0modifications`
`0newModifications`
`0oldModifications`
`0deletions`
`new size of collection:119`

## Steps to Reproduce

Add a listener on the realm result object and it is fired immediately after component mounts even if changes are not there

## Code Sample

`listenToPositionChanges = (collection, changes) => {
  console.log(changes.insertions.length + "insertions");
  console.log(changes.modifications.length + "modifications");
  console.log(changes.newModifications.length + "newModifications");
  console.log(changes.oldModifications.length + "oldModifications");
  console.log(changes.deletions.length + "deletions");
  console.log("new size of collection:"+ collection.length);
}`

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.0
- Node or React Native: 0.59.10
- Client OS & Version: Android - 7.1
- Which debugger for React Native: None

**Comment by kneth** [comment]
@karthikpala Two quick follow-up questions:

1. Do you use sync?
1. Do you observe the same behaviour on iOS?

**Comment by karthikpala** [comment]
No we are not using sync - This is just an offline realm residing on user's device.
iOS - We haven't tested yet, will let you know soon

This just popped up when we were upgrading realm from 2.28.0 to 2.29.0. This is leading to unnecessary render and re-calculation of the data on the screen

**Comment by kneth** [comment]
I think it is similar to #927. Does it happen every time? I am asking in order to understand if it is easy to reproduce.

**Comment by karthikpala** [comment]
Yes it is happening every time. In the issue #927 , they are reporting that an empty list is returned first and then data is returned. We are not getting empty realm list in our case

**Comment by karthikpala** [comment]
We are using node - v8.11.3. Do you for-see any impact using this version?

**Comment by kneth** [comment]
You should be aware that node v8.x has EOL this month. Once we get node v12.x supported, we might stop building for node v8.x.

**Comment by karthikpala** [comment]
Sure we will update node asap.

Do you have any other thoughts on this issue?

**Comment by kneth** [comment]
@karthikpala Realm JS should align with the other Realm SDKs. For example, Realm Cocoa will set the initial change set to `nil` in order for app developers to skip refreshing the UI the first time.

**Comment by miwialex** [comment]
has there been any update on this? I am seeing this as well. I have a listener that just keeps firing over and over, with 0 changes.

**Comment by kneth** [comment]
@miwialex Can it be that you have empty write transactions?

**Comment by miwialex** [comment]
@kneth I actually ended up finding the culprit. My code was actually recreating the listener and re initializing the query, so it only seemed like it kept firing.
