### ISSUE TITLE
After update app in store then not create database realm

### ISSUE THREAD

**Issue by nghiant96** [realm/realm-js#2656]
After update app in store then not create database realm

## Version of Realm and Tooling

- Realm JS SDK Version: 2.29.2 
- React Native: 0.60

**Comment by bmunkholm** [comment]
@nghiant96 You have to explain in more details which bug you think you have found and fill out all of the issue template. Thanks!

**Comment by nghiant96** [comment]
@bmunkholm I update app in store then realm not save and load data, realm not working.  But I run with debug or uninstall and reinstall it working. i think error schema but incorrect.

**Comment by bmunkholm** [comment]
@nghiant96 You have to describe it detail what your issue is, how you have tried to debug it and how someone else can replicate your issue. Please fill in all details in the issue template.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
