### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: Didn't find class "io.realm.react.util.SSLHelper" on path: DexPathList

### ISSUE THREAD

**Issue by ShridharCodewave** [realm/realm-js#2658]
## Version of Realm and Tooling

- Realm JS SDK Version:  2.29.1
- React Native: 0.59.9

android/app/build.gradle

 splits {
            enable false
            reset()
           include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            universalApk false
        }
    }

**Comment by kneth** [comment]
We fixed a bug related to Android builds in [v2.29.2](https://github.com/realm/realm-js/blob/master/CHANGELOG.md#2292-release-notes-2019-8-14). Please try to upgrade.

**Comment by ShridharCodewave** [comment]
@kneth I updated the ream to 2.29.2 but the apk is crashing same as before

**Comment by kneth** [comment]
Please create and share a small project which can reproduce the error.

**Comment by bmunkholm** [comment]
.

**Comment by obrunsmann** [comment]
I had the same issue; disabling Hermes worked for me.

On the long run I would love to see Hermes Support on this library

**Comment by blagoev** [comment]
We have Hermes in our radar but its currently not supported. Closing this issue for now

**Comment by ZComwiz** [comment]
@blagoev- is Hermes supported now?

**Comment by kneth** [comment]
@ZComwiz No, we don't support Hermes yet. See #2455
