### ISSUE TITLE
Document Realm.write() behaviour on error

### ISSUE THREAD

**Issue by xmedeko** [realm/realm-js#2665]
Following the #2646 and #2660, please document the `Realm.write(callback)` behaviour on error inside the `callback` - is the transaction committed or cancelled?
Thanks.

**Comment by kraenhansen** [comment]
If the callback throws an exception the transaction will be cancelled, we should probably add that to https://realm.io/docs/javascript/latest/api/Realm.html#write, but I think that's expected, isn't it?

**Comment by xmedeko** [comment]
Yes, it's usual behaviour. Many different databases and plenty database framework exists. I've seen already project where such behaviour has not been implemented. So I rather see it explicitly written or I have to check it.

Also, Java API doc `Realm.executeTransaction()` states it: _Executes a given transaction on the Realm. beginTransaction() and commitTransaction() will be called automatically. If any exception is thrown during the transaction cancelTransaction() will be called instead of commitTransaction()._

And the Realm Java doc https://realm.io/docs/java/latest/ states it too: _If an exception happens inside a transaction, you’ll lose the changes in that transaction, but the Realm itself won’t be affected (or corrupted). If you catch the exception and the app continues, you’ll need to cancel the transaction. If you use executeTransaction, this happens automatically._

(I would expect the Realm docs to be similar for different languages.)

BTW. Just came to my mind it would be nice to document behaviour of `write()` inside `write()`. Just a sentence like `Nested write() is not possible.`
