### ISSUE TITLE
duplicate  symbol '_OBJC_CLASS_$_GCDWebServerURLEncodedFormRequest

### ISSUE THREAD

**Issue by congpeijun** [realm/realm-js#2668]
- Realm JS SDK Version: ? 3.6.0
- Node or React Native: ? RN
- Client OS & Version: ?
- Which debugger for React Native: ?/None

duplicate symbol '_OBJC_CLASS_$_GCDWebServerURLEncodedFormRequest' in:
    ios/build/xxx/Build/Products/Debug-iphonesimulator/GCDWebServer/libGCDWebServer.a(GCDWebServerURLEncodedFormRequest.o)
   ios/build/xxx/Build/Products/Debug-iphonesimulator/libRealmReact.a(GCDWebServerURLEncodedFormRequest.o)

**Comment by kraenhansen** [comment]
Have you tried deleting the `ios/build` folder and/or opened the XCode workspace and clicked "Clean Build Folder" in the "Product" top menu?

**Comment by congpeijun** [comment]
@kraenhansen Yes, but it does't work.
but when I add `use_frameworks!` in the Podfile, it works.

**Comment by edritech93** [comment]
same for me

**Comment by kneth** [comment]
@congpeijun @edritech93 Do you have any other dependencies in your Podfile? Do you have any react native library in your `package.json` which contains C++ code?

**Comment by kraenhansen** [comment]
Also - is this a fresh installation of Realm JS or did you upgrade from a previous version? If yes - do you remember if you followed the standard instructions on installing Realm JS or if you added any files to your XCode project, manually?

**Comment by congpeijun** [comment]
I use the dynamic framework of the realm, and it works.

**Comment by kneth** [comment]
Great to hear.
