### ISSUE TITLE
Use current nodejs version in tests.sh

### ISSUE THREAD

**Issue by blagoev** [realm/realm-js#2670]
Currently our test script install node 8 and runs tests against it. I would prefer this to be left for the user of tests.sh to decide which version to run it against.

**Comment by kneth** [comment]
You can specify the node version as a command-line parameter: `./scripts/test.sh node Release v10.17.0`

**Comment by kneth** [comment]
I suggest that we upgrade `test.sh` to use node v10 as default.

**Comment by blagoev** [comment]
I suggest we change test.sh to use current user version and remove the default. On CI we pass the argument anyway but locally it's very annoying when it switches the node version under you. 
It's pretty bad when debugging on Windows Subsystem for Linux (WSL) when it does that since all open VS Code instances  start complaining and need a reload to work again.

So the proposed logic change is: If there is an parameter passed use that or use the current node version

**Comment by kneth** [comment]
We now default to v10.19.0.
