### ISSUE TITLE
To get subsegment data inform of array

### ISSUE THREAD

**Issue by suriyagp** [realm/realm-js#2671]
## Goals
I am storing the some set of information, like users and their logs. Need to get the information as the single object "users" and "logs" as the sub-segment inform of array. 

> The realm implementation is by using JavaScript

I had created like the following 
```
var logs = {
  name: 'logs',
  property:{
    id: 'int',
    status: 'string',
    syncTS: 'string'
  }
}
```

```
var users = {
  name: 'users',
  property:{
    id: 'int',
    name: 'string',
    email: 'string',
    logs: 'logs[]'
  }
}
```

## Expected Results
The following is the expected result

```
{
  "users": {
    "id": 1,
    "name": "abcd",
    "email": "abcd@efg.com",
    "logs": [
      {
        "id": 1,
        "status": "Active",
        "syncTS": null
      },
      {
        "id": 2,
        "status": "Inactive",
        "syncTS": null
      }
    ]
  }
}
```

## Actual Results
The problem is with the sub-segment
```
{
  "users": {
    "id": 1,
    "name": "abcd",
    "email": "abcd@efg.com",
    "logs": {
      "0": {
        "id": 1,
        "status": "Active",
        "syncTS": null
      },
      "1": {
        "id": 2,
        "status": "Inactive",
        "syncTS": null
      }
    }
  }
}
```

## Steps to Reproduce
Just create the schema using the above snippet 

## Code Sample
 ```
Realm.open({ schema: ['logs','users'] })
    .then(realm => {
       var data = realm.objects('users');
        console.log(JSON.stringify(data['0']));
        realm.close();
    })
    .catch(error => {
        console.log(error);
    });
```

## Version of Realm and Tooling

- Realm JS SDK Version:  3.6.0
- Node : v10.11.0
- Client OS & Version: Ubuntu 18.04.3 LTS
- Which debugger for React Native: None

**Comment by kneth** [comment]
@suriyagp It's a "feature" of Realm JS - see my explanation in https://github.com/realm/realm-js/issues/2518#issuecomment-532684777.

**Comment by suriyagp** [comment]
@kneth But this solution only works for the header segment, not for the sub-segment. As i mentioned in the above scenario

**Comment by kneth** [comment]
Your `logs` is a [Realm list](https://realm.io/docs/javascript/latest/api/Realm.List.html) which is closer to be an object than an array. We try to emulate an array as close as possible, for example by implementing `[]`.

**Comment by suriyagp** [comment]
@kneth thanks for the update
