### ISSUE TITLE
Sync Realm to SQL Server

### ISSUE THREAD

**Issue by viniciusvelasco** [realm/realm-js#2672]
Hello, I am currently sending the data recorded in the device realm to my SQL Server database manually using a rest API, but this has generated a lot of problems, mainly because Realm doesn't give me a json object but a realm object and When I make the post I have several errors and could not find a solution that solved this problem. I am thinking of using realm sync, would it be possible using sync to send the data to my SQL Server? Both from realm to SQL Server and from SQL Server to Realm. If that's possible, how would you do it?

**Comment by kneth** [comment]
We have just announced of [MongoDB Realm](https://www.mongodb.com/realm). I don't if you can migrate from SQL Server to MongoDB, but it is what we will recommend at the moment.
