### ISSUE TITLE
Malformed calls from JS corrupting the whole DB

### ISSUE THREAD

**Issue by Epick362** [realm/realm-js#2685]
## Goals

I'm trying to insert a lof of (>300k) objects into Realm. 

## Expected Results

Objects get batched into Realm successfully.

## Actual Results

After about 150k of objects, Realm crashes with a cryptic message that doesn't reference Realm directly but it is most likely the culprit. 

```
2020-01-14 15:13:05.214 5863-13164/com.my.app E/unknown:ReactNative: Exception in native call
    com.facebook.jni.CppException: Malformed calls from JS: field sizes are different.
    
    [[33],[3],[],1331]
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:216)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:784)
```

After opening up the app again, I get an mmap() out of memory error right on initialization of realm and have to remove everything (only thing that works is `Realm.clearTestState()`)

## Steps to Reproduce

It happens to me when i batch insert a lot of data into multiple Realm instances. Is there anything I'm doing wrong?

## Code Sample

```
const FeatureSchema = {
  name: "Feature",
  primaryKey: "identifierHash",
  properties: {
    geohash: {
      type: "string",
      indexed: true
    },
    layerName: "string",
    identifierHash: { type: "string", indexed: true },
    data: "string"
  }
}

for (let batchIdx = 1; batchIdx <= batches; batchIdx++) {
      .... loading data

      let realm = await Realm.open({ schema: [FeatureSchema] })

      realm.beginTransaction()

      features.map(feature => {
        realm.create(
          FeatureSchema.name,
          {
            geohash,
            layerName: feature.layerName,
            identifierHash: feature.properties.identifierHash,
            data: JSON.stringify(feature)
          },
          true
        )
      })

      realm.commitTransaction()
      console.tron.log("Total features after batch", realm.objects(FeatureSchema.name).length)

      realm.close()
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 4.0.0-beta.0
- Node or React Native: React Native 0.59 
- Client OS & Version: Android 9.1.0
- Which debugger for React Native: Logcat

**Comment by kneth** [comment]
I can see that you are using v4.0.0-beta.0. Do you observe the same issue if you use v3.6.0? v4.0.0 will bring a new file format of Realm files, so I am trying to figure out if this breaking change has a bug - or if the bug is somewhere else.

Moreover, is your Android device 32 or 64 bit? Here I am speculating about out-of-virtual-memory if you're on 32 bit.

**Comment by Epick362** [comment]
I'm using 64-bit build. I'll try version 3.6.0 and report back. Thank you for the quick reply.

**Comment by Epick362** [comment]
On version 3.6.0 I get mmap out of memory error way sooner (with the same code) so I can't confirm if the same thing occurs there. I have noticed that the number of objects I can import varies (sometimes its 200k other times less). 

Is there a better way to import a large number of objects than mine?

**Comment by kneth** [comment]
Do you have the debugger running (in Chrome) when you see the crash?

If so, the explanation is that the communication link between the device and the debugger or just the debugger cannot handle so many objects. A Realm object is tightly coupled to the data in the Realm, so we have to send over any update to the debugger. Creating 350k objects will result in a lot of traffic.

Unfortunately I can't offer a simple fix. I know that other users have had better experience using iOS and Safari for debugging.

**Comment by Epick362** [comment]
No I didn't. I also suspect it's something to do with the debugger updates but seeing as it works in production I will just have to work around it in dev. Thank you for your time, closing.
