### ISSUE TITLE
Use realm database in a native module

### ISSUE THREAD

**Issue by techday84** [realm/realm-js#2689]
I have a realm database in my react native app. I need to access at the same database by a native module. Is not posible to write some data in the same realm database by a native module (java)?
I need to know it because if it is not possible, I have to change realm for sql or another.

Thanks. 

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
We don't have a recipe or a guide explaining how to do it. In theory it should be possible.

Mixing Realm JavaScript and Realm Cocoa is possible after we got Cocoapod support implemented.

Two things to keep in mind:

1. Realm Java and Realm JavaScript must support the file Realm file format
1. Realm does not support multiprocess access

**Comment by bimusiek** [comment]
@kneth About second point, if one was to run RealmJS in react-native and run second JS process using `react-native-threads`, would it work? 

We are doing some heavy-lifting in the app and trying to move it to background thread and it is using Realm as communication layer. 

I remember from using Realm with Apple Watch app, that if encryption is disabled it works across multi processes (main app + apple watch app with one Realm)

**Comment by kneth** [comment]
@bimusiek Realm JavaScript hasn't support for multi-process access.

**Comment by bimusiek** [comment]
Thanks for confirming.

We were able to make it work by separating databases paths and having communication over Realm Sync between processes 👍
