### ISSUE TITLE
Cannot read property 'Discard' of undefined when using the Realm.Sync.ClientResyncMode.Discard enum

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2690]
## Goals

I want to use `Realm.Sync.ClientResyncMode.Discard` as suggested is possible from the TypeScript definition.

## Expected Results

If config has `clientResyncMode: Realm.Sync.ClientResyncMode.Discard` the Realm is opened with the "discard" resync mode.

## Actual Results

An error is thrown:

    Cannot read property 'Discard' of undefined

## Steps to Reproduce & Code Sample

    const Realm = require("realm")
    console.log(Realm.Sync.ClientResyncMode.Discard)

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.2
- Node or React Native: Both
- Client OS & Version: N/A
- Which debugger for React Native: None

**Comment by kneth** [comment]
I am not able to reproduce it using the following code snippets:

```
import * as Realm from 'realm'
console.log(Realm.Sync.ClientResyncMode.Discard)
```

and 

```
import Realm = require('realm')
console.log(Realm.Sync.ClientResyncMode.Discard)
```

But I am able to reproduce it using your code snippet :smile:.

**Comment by douglasjunior** [comment]
If I use:

```ts
import * as Realm from 'realm';

const realmApp = new Realm.App({
  id: '<my app id>',
});
```

Causes error:

```
ERROR TypeError: undefined is not a constructor (evaluating 'new Realm.App({
    id: '<my app id>'
  })')
```

And with:

```ts
import * as Realm from 'realm';

const realmApp = new Realm.App({
  id: '<my app id>',
});

Realm.open({
    schema: [RegistroInteresse.schema, Cliente.schema],
    schemaVersion: 2,
    sync: {
      user,
      partitionValue: 'usuarioId=1',
      existingRealmFileBehavior: {
        type: Realm.OpenRealmBehaviorType.OpenImmediately,
        timeOut: 15000,
        timeOutBehavior: Realm.OpenRealmTimeOutBehavior.OpenLocalRealm,
      },
      newRealmFileBehavior: {
        type: Realm.OpenRealmBehaviorType.OpenImmediately,
        timeOut: 15000,
        timeOutBehavior: Realm.OpenRealmTimeOutBehavior.OpenLocalRealm,
      },
      error: (session, error) => {
        console.warn(error);
      },
      clientReset: {
        mode: Realm.ClientResetMode.DiscardLocal,
      },
    },
  });
```

The `Realm.App` works, but throws another error:

```
 WARN  [ReferenceError: Can't find variable: OpenRealmBehaviorType]
```
