### ISSUE TITLE
Can't resolve 'react-native' when adding Realm to a non-native project created using create-react-app

### ISSUE THREAD

**Issue by scolobey** [realm/realm-js#2693]
## Goals

I'd like to add Realm to a project that was created using create-react-app.

## Expected Results

Installing Realm via npm, I expect to be able to import the Realm package in my project.

## Actual Results

When I require Realm in my project, I receive the following error message:

```
./node_modules/realm/lib/browser/index.js
Module not found: Can't resolve 'react-native' in '/Users/scolobey/Desktop/Projects/realm-blog/node_modules/realm/lib/browser'
```
And inspecting in the console reveals this message:

```
./node_modules/realm/lib/browser/index.js
Module not found: Can't resolve 'react-native' in '/Users/scolobey/Desktop/Projects/javascript/my-app/node_modules/realm/lib/browser'
console.<computed> @ index.js:1
r @ backend.js:6
handleErrors @ webpackHotDevClient.js:173
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:212
```

## Steps to Reproduce

```
npx create-react-app my-app
cd my-app
npm i
npm i --save realm
npm start
```
Then attempt to require or import realm in App.js or Index.js via:
`Realm = require('realm');`
or
`import Realm from 'realm';`

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.3
- Node: v10.16.3
- Client OS & Version: Mojave 10.14.6
- Which debugger for React Native: None

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0",
    "realm": "^3.6.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by kneth** [comment]
Realm doesn't support running in the browser. If you want to use Realm for a React application, you can only use it on the backend part and not the frontend part.

React Native apps are a bit different as they don't have this division within them.

It is possible to use Realm in a React app. Unfortunately we don't have an example. You can swap out Postgres and use Realm instead in tutorials like https://www.freecodecamp.org/news/fullstack-react-blog-app-with-express-and-psql/

**Comment by scolobey** [comment]
Awesome, thank you for the reply. I was starting to grasp this:
> Realm doesn't support running in the browser.

But I was a little misled by [this tutorial](https://academy.realm.io/posts/realm-node-js-express-blog-tutorial/) on building a simple blog with Realm, Node and Express .

Maybe a silly question, but what is the main limitation on running in the browser? I would guess either space, permissions, or code compatibility?

Given that I have both an Android app and an IOS that are currently synching to Realm Cloud, the best way to synch web would appear to be via [GraphQl](https://docs.realm.io/sync/graphql-web-access_)?

**Comment by bimusiek** [comment]
@scolobey If you are interested, we were able to run RealmJS on react-native & Electron within one source-code. 

On Web your only option is GraphQL.

**Comment by kneth** [comment]
@scolobey writes:

> Maybe a silly question, but what is the main limitation on running in the browser?

Not a silly question. Most of Realm JS (as well as Realm Core - our storage engine) is written in C++. It could be cool to support browsers directly in the future but no plans.

**Comment by saulpalv** [comment]
electron realm for create react app guide from official docs

https://docs.mongodb.com/realm/sdk/node/integrations/electron-cra/

**Comment by jbeckton** [comment]
it seems like the Realm SDK's are a half-ass port from days gone by. The realm-web and realm (node) sdk's don't work with Angular, especially if you need to build an SSR app with Angular Universal. I was hoping to save myself time by not building an API and using Realm App services but but it does not appear that MongoDB corp has spent much effort on modernizing their services stack. My choices are to learn React or switch to another JAMStack option like FaunaDB. It's too bad that Mongo's SDK's are so far behind the rest of the world in this area.
