### ISSUE TITLE
Realm.Sync.ChangeEvent produces non-existing indices for insertions & deletions

### ISSUE THREAD

**Issue by bimusiek** [realm/realm-js#2696]
## Goals
Get primary keys of deleted objects using RealmJS in NodeJS and listening to all realms of users.

## Expected Results
When I get changeEvent with deletions, I expect it to have proper indexes. 
In my actual tries, I have 1 object in the database. 
When removing it, I would expect to get `deletions: [0]` 

## Actual Results
When getting a change event, the index of the deleted object is `1420636099337594400`.

Example event data when adding new `ImporterAuthenticationModel` to empty table: 
```
{"ImporterAuthenticationModel":{"deletions":[],"insertions":[1420636099337594400],"newModifications":[],"modifications":[],"oldModifications":[]}}
```

## Steps to Reproduce
1. Create an example model in Realm Studio.
2. Use `Realm.Sync.addListener` with admin user to listen to all realms
3. Insertions, modifications, and deletions will consist of weird indexes.

## Code Sample
```typescript
const onChange = async (event: Realm.Sync.ChangeEvent): Promise<void> => {
    console.log(`onChange: ${event.path}\n${JSON.stringify(event.changes)}`);
    const { realm, oldRealm } = event;
    const authModels = realm.objects(ImporterAuthenticationModel.schema.name);
    const oldAuthModels = oldRealm.objects(
      ImporterAuthenticationModel.schema.name
    );

    const authModelChanges =
      event.changes[ImporterAuthenticationModel.schema.name];
    if (!authModelChanges) {
      return;
    }
    const insertedAuthModelsIndices = authModelChanges.insertions;
    const deletedAuthModelsIndices = authModelChanges.deletions;

    const insertionPromises = insertedAuthModelsIndices.map(async index => {
      const authModel = authModels[index];
      if (!authModel) {
        throw new Error(`Got [${index}] that cannot be found on ${authModels}`);
      }
      return reauthenticateAuthModel(authModel);
    });

    const deletionPromises = deletedAuthModelsIndices.map(async index => {
      const authModel = oldAuthModels[index];
      if (!authModel) {
        throw new Error(
          `Got [${index}] that cannot be found on ${oldAuthModels}`
        );
      }
      return clearAuthModel(authModel);
    });

    return Promise.all([
      Promise.all(insertionPromises),
      Promise.all(deletionPromises)
    ]).then();
  }
```

## Version of Realm and Tooling

- Realm JS SDK Version: 4.0.0-beta.0
- Node or React Native: node v10.16.3
- Client OS & Version: n/a
- Which debugger for React Native: n/a

**Comment by tgoyne** [comment]
In 4.0.0-beta.0 the values reported are object keys and not indexes. This isn't very useful, as we haven't actually exposed a way to look up objects by key yet. In the next beta release it'll instead just give you the objects directly.

**Comment by bimusiek** [comment]
@tgoyne I just checked `beta.1` and it is the same case, so I guess you mean newer than `beta.1`. 

Is there any timeline for new version with properly working change events?

**Comment by bimusiek** [comment]
@tgoyne There is some undocumented private function to get object by id, however it returns an error.

<img width="1508" alt="Screenshot 2020-01-23 01 26 58" src="https://user-images.githubusercontent.com/1025588/72946537-859cad00-3d7f-11ea-8c6c-a65d87cbedc7.png">

I will wait for new version of realm then, thanks!
