### ISSUE TITLE
Realm in Debug Mode kills React Native on iOS and Android

### ISSUE THREAD

**Issue by sallar** [realm/realm-js#2702]
Installing Realm kills React Native app if debugger is enabled. Without the debugger, everything works fine.

## Goals

Using Realm in React Native.

## Expected Results

App would continue to work when debugger enabled.

## Actual Results

If debugger is enabled, the app crashes and exits when run using `npx react-native run-ios`. If the app is run from XCode, XCode pauses and shows the error: `TypeError: snapshot method was not called on a Realm object!`. Note that even without any listeners or Realm code running, this happens (only by installing Realm).

Safari debugger works fine.

## Steps to Reproduce

- Install Realm (latest beta or latest stable version)
- Open React Native app
- Enabled debugger
- App crashes

## Version of Realm and Tooling

- Realm JS SDK Version: 4 beta or 3 stable
- Node or React Native: 0.61
- Client OS & Version: iOS / Android both simulator and real devices
- Which debugger for React Native: Chrome

**Comment by kneth** [comment]
Do you call `snapshot`? If not, my best guess is that you are iterating over a result set (where we call `snapshot`).

Is it possible to share a code snippet where you see the error?  It would help us to reproduce the issue.

**Comment by sallar** [comment]
@kneth The whole application dies just by installing `realm` and enabling debug mode. I wasn't running any queries at all.

**Comment by andreypaul** [comment]
I have the same problem...

**Comment by brmk** [comment]
Is there any solution? I have no `snapshot` method calls in my app at all, but enabling the remote debugging simply kills the app

**Comment by zidniryi** [comment]
I have some problem too bro.

**Comment by Shumuu** [comment]
So I recreated the bug in a very simple Project.

https://github.com/Shumuu/RealmSnapshot

I add a listener to Todos and if I use filtered  or sorted on the collection object, the app crashes with the mentioned error information.

If I had known about this bug before, I wouldn't have chosen realm. This makes the dev experience really, really awful. Hope this gets fixed soon

**Comment by kneth** [comment]
Please upgrade to a recent version. If you still experience the issue after upgrading, please either reopen the issue or create a new one.

**Comment by Shumuu** [comment]
Seems to be working with realm 6.1.0. 

Just made a small Test Project and it didn't crash. Will report back in case it does crash

**Comment by NgocLe1001RP** [comment]
same issue, crash when open debuging

**Comment by alejandromolero** [comment]
> same issue, crash when open debuging
same here since two days ago

**Comment by shanu95** [comment]
can't debug after adding realm

**Comment by Hassan-Riaz** [comment]
> can't debug after adding realm

yes I am facing same issue.

**Comment by Hassan-Riaz** [comment]
as soon the app launches it crashes and I am not using filtered or sorted just fetching data from db via collection listener

**Comment by Hassan-Riaz** [comment]
@sallar any workaround or fix?
"realm": "^10.10.1",

**Comment by sallar** [comment]
@Hassan-Riaz I decided not to use Realm.

**Comment by takameyer** [comment]
Our method for getting the Chrome Debugger to run with Realm has become a giant technical burden that we have chosen no longer to chase.  When React Native fully moves to JSI (hermes enabled by default), the Chrome Debugger will be no longer be supported (see https://reactnative.dev/blog/2021/10/26/toward-hermes-being-the-default#pioneering-at-vertical-integrations).  What will be supported is [Flipper](https://fbflipper.com/)

**Comment by Hassan-Riaz** [comment]
@sallar  what are you using instead of the realm?
Because I need the same features.
Specially the listener part

**Comment by Hassan-Riaz** [comment]
@takameyer so what should be done?
I want to use debugging?

**Comment by takameyer** [comment]
@Hassan-Riaz There are alternatives to the chrome-debugger.  One alternative, with a bit of configuration, is to [debug in Safari](https://reactnative.dev/docs/debugging#safari-developer-tools). Also I mentioned Flipper in a previous comment, which has a rich log viewer and network monitor.  Also with our upcoming Hermes release (available in Alpha) one can use the Hermes debugger within Flipper to set breakpoints in JavaScript.
It is also wise to migrate to these alternatives, since when the new React Native architecture is released (sometime in 2022) it will come with a new bridge which will break the current Chrome debugger paradigm.  
Hope this is helpful!

**Comment by WenLonG12345** [comment]
Want to ask in Flipper, what are the plugin to inspect realm db value?

**Comment by kneth** [comment]
@WenLonG12345 Currently we don't have a plugin to inspect Realms directly.
