### ISSUE TITLE
Realm.Sync.addListener() is not consistent

### ISSUE THREAD

**Issue by RosenTomov** [realm/realm-js#2705]
## Goals
The goal is to make Realm.Sync.addListener() always "attach/listen" the matched realms.

## Expected Results
Realm.Sync.addListener() to be consistent.

## Actual Results
Sometimes Realm.Sync.addListener() fails to match realms (or attach change event?). You have to restart your server, so it can try again or rely on "retry logic" (see sample).

## Steps to Reproduce
Use Realm.Sync.addListener() and make a change to your DB (edit, add entry), it won't register.

## Code Sample
package.json
```
{
  "name": "testproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.js",
    "start-babel": "babel-node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "realm": "^3.6.3"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "nodemon": "^2.0.2"
  }
}
```

index.js
```
const Realm = require('realm');

const realmUsername = 'Username';
const realmPassword = 'Password';
const realmServerURL = 'Realm url without https:// or realms://';

Realm.Sync.setLogLevel('error');

const CarSchema = {
    name: 'Car',
    properties: {
        Id: 'string',
        make: 'string',
        model: 'string',
        miles: { type: 'int', default: 0 },
    }
};

let retryCount = 0;
let areListenersAttached = false;

const handleChange = changeEvent => {
    console.log('attached', changeEvent);
    areListenersAttached = true;
};

const AttachAndCheckListeners = async (realm, realmConfig) => {
    try {
        if (retryCount < 5) {
            // clear old listeners, just in case
            await Realm.Sync.removeAllListeners();
            // attach listener
            await Realm.Sync.addListener(realmConfig, 'change', handleChange);

            // perform db change
            realm.write(() => {
                let [vehicle] = realm.objects('Car').filtered('Id = "Test"');
                if (!vehicle) {
                    vehicle = realm.create(
                        'Car',
                        { Id: 'Test', make: 'Honda', model: 'Civic', miles: 0 },
                        true
                    );
                }

                vehicle.miles = retryCount;
            });

            // check if handleChange was called
            setTimeout(async () => {
                if (!areListenersAttached) {
                    retryCount += 1;
                    console.log(`Failed - retry #${retryCount}`);
                    await AttachAndCheckListeners(realm, realmConfig);
                }
            }, 5000);
        }
    } catch (error) {
        console.log(error)
    }
};

(async () => {
    const currentCredentials = Realm.Sync.Credentials.usernamePassword(
        realmUsername,
        realmPassword
    );

    const user = await Realm.Sync.User.login(
        `https://${realmServerURL}`,
        currentCredentials
    );

    const databaseOptions = {
        schema: [CarSchema],
        sync: {
            url: `realms://${realmServerURL}/test`,
            user
        }
    };

    const realm = await Realm.open(databaseOptions);

    const realmPath = /.*/; // assume you have to listen to more than 1 realm

    const realmConfig = {
        serverUrl: `realms://${realmServerURL}`,
        adminUser: user,
        filterRegex: realmPath
    };

    await AttachAndCheckListeners(realm, realmConfig);
})();
```

## Version of Realm and Tooling

- Realm JS SDK Version:  3.6.3
- Node or React Native: Node v8.17.0 (can't use higher on Windows https://github.com/realm/realm-js/issues/2560)
- Client OS & Version: Windows 10 Pro 64 bit
- Which debugger for React Native: None

**Comment by kneth** [comment]
I think this is the same as #2461 which we couldn't reproduce. Does it only happen on Windows or can you reproduce it on other operating systems?

**Comment by RosenTomov** [comment]
![Screenshot 2020-02-03 at 11 51 23](https://user-images.githubusercontent.com/32323783/73643389-11fe7800-467c-11ea-91b4-fb65aab99988.png)

The sample above, tested with:
MacOS 10.15.2
Node v10.18.1

Failed 3 times, "hooked" on the 4th.

**Comment by kneth** [comment]
I haven't been able to reproduce it.
MacOS 10.15.2
Node 10.17.0 and 10.18.1
ROS: 3.23.1 on localhost (no SSL)

**Comment by RosenTomov** [comment]
Could it be something with our Realm cloud instances? 
As you can see in the screenshot, we're also getting a lot of:
ERROR: Connection[X]: Reading failed: End of input

ROS: v3.28.2

**Comment by kneth** [comment]
@RosenTomov Sorry for the late reply. Do you still observe it with a recent version of Realm JS?

**Comment by RosenTomov** [comment]
I'm still getting some failures, just tested it again with the example from above, with updated dependencies.

```
{
  "name": "testproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.js",
    "start-babel": "babel-node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "realm": "^6.0.2"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "nodemon": "^2.0.4"
  }
}
```

After that it gets into the callback, it crashes.
![image](https://user-images.githubusercontent.com/32323783/85833635-b784c600-b79a-11ea-85ae-b1b7c582605a.png)

And here's using babel-node
![image](https://user-images.githubusercontent.com/32323783/85833792-f7e44400-b79a-11ea-869d-c7671dbc747d.png)

**Comment by kneth** [comment]
@RosenTomov Thanks for the quick update. We will have to investigate what is causing it.
