### ISSUE TITLE
iOS library files are zero bytes

### ISSUE THREAD

**Issue by simonmitchell** [realm/realm-js#2708]
## Goals

Trying to install realm-js in a React Native app (iOS). This was working fine all day yesterday, but has stopped working as of this morning (31/01/2020 9:00am UTC)

## Expected Results

For realm to be easily installable

## Actual Results

Xcode gives compiler warning about realm library files being zero bytes:
`file too small (length=0) file '/node_modules/realm/vendor/realm-ios/librealm-ios.a' for architecture x86_64`

All of the library files within the realm-ios folder are zero bytes in length when viewed in finder too.

## Steps to Reproduce

Setup a new RN project, install realm-js using auto-linking and run project.

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.0
- Node or React Native: Node: v10.15.0, RN: 0.61.5
- Client OS & Version: iOS 13.3.1
- Which debugger for React Native: None

**Comment by kneth** [comment]
Does it still happen if you remove the build folder and rebuild? Can you verify that `librealm-ios.a` is an empty (size = 0) file?

**Comment by simonmitchell** [comment]
If I run `rm -rf node_modules` (which also clears the build folder) and run `yarn install` again, I can confirm `libream-ios.a` as well as all the other files in that folder are empty files.
<img width="1095" alt="Screenshot 2020-02-04 at 09 50 29" src="https://user-images.githubusercontent.com/9033831/73733394-c909fa80-4733-11ea-8835-e665420d3a87.png">

**Comment by kneth** [comment]
I have created a new app from scratch, and I am still not able to reproduce it. But `yarn install` will remove all temporary files (like `.a` files). 

Please notice that yarn might cause the issue (see https://github.com/realm/realm-js/issues/2617#issuecomment-559446483).
