### ISSUE TITLE
Can't update realm object

### ISSUE THREAD

**Issue by barak109** [realm/realm-js#2718]
## Goals

I want to edit object property in realm 

## Expected Results

The propety will change

## Actual Results

The propety didn't change

## Steps to Reproduce

1.  Create a new object and add it to realm - work
2.Find the object with filter - work
3.Try to update object property - doesn't work

## Code Sample

```
export const lastMessage = message => {
  Realm.open({
    schema: SchemasArray
  }).then(realm => {
    let conv: any = realm
      .objects("Conversation")
      .filtered(`_id = "${message.convId}"  LIMIT(1)`);
    realm.write(() => {
      conv.lastMessage = message;
    });
  });
};

```
## Version of Realm and Tooling

- Realm JS SDK Version: i'v tried -3.0.0, 3.6.0,3.6.3
- Node or React Native: 0.59.8
- Client OS & Version: tested devices-  ios 13.3 ,  android 8.0.0
- Which debugger for React Native: chrome

**Comment by kraenhansen** [comment]
Filtered returns a Result object, although you're limiting to a single result, you still have to pick the first item of the result to update it:

```javascript
conv[0].lastMessage = message;
```

Depending on your schema, consider using the (objectForPrimaryKey)[https://realm.io/docs/javascript/latest/api/Realm.html#objectForPrimaryKey] method instead. This just requires that `_id` is primary key of `Conversation`.

Please reopen this issue if you're still experiencing the issue after adapting my suggestion.
