### ISSUE TITLE
Duplicate symbols in react native build (3.6.4)

### ISSUE THREAD

**Issue by stevenmathers** [realm/realm-js#2727]
## Goals
trying to build the app using realm js 3.6.4

## Expected Results
build without error

## Actual Results
duplicate symbol '_OBJC_CLASS_$_RealmReact' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
duplicate symbol '_OBJC_METACLASS_$_RealmReact' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
duplicate symbol '_OBJC_IVAR_$_RealmReact._eventHandlers' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
duplicate symbol '_RealmReactGetJSGlobalContextForExecutor' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
duplicate symbol '_OBJC_IVAR_$_RealmReact._bridge' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
duplicate symbol '_initializeOnJSThread(OpaqueJSContext* () block_pointer)' in:
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmJS.a(RealmReact.o)
    /Users/runner/Library/Developer/Xcode/DerivedData/Geo-cspvlxxapoefvvelbwbinzucczbj/Build/Intermediates.noindex/ArchiveIntermediates/GeoX/BuildProductsPath/Release-iphoneos/libRealmReact.a(RealmReact.o)
ld: 6 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Version of Realm and Tooling
node 10, react native 61.4 
android fine, ios not

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kraenhansen** [comment]
Please provide steps to reproduce - ideally a git repository with the least amount of code required to reproduce the error.

**Comment by stevenmathers** [comment]
Hi, this occurs using AppCenter which is always a clean slate every build.  Legacy build system, FWIW

I am upgrading from  realm 2.29.x

Is there a specific version of xcode required or...?

**Comment by kraenhansen** [comment]
You say that you're upgrading from 2.29.x, do you remember if you did anything special to your Xcode project files when you installed Realm into your project? (like adding a `librealm.a` file into the project).

Our readme states Xcode 9.4+, but to be honest I havn't tried earlier versions of Xcode lately. In general, try using the latest available if possible.

**Comment by stevenmathers** [comment]
Hi.  Good question.   I dont think so, but I cant be absolutely certain.

I can experiment with removing realm and looking for anything realmy that remains in xcode files.

using the latest version of xcode didnt change the situation.

**Comment by dbarner1** [comment]
Same error here.

**Comment by kraenhansen** [comment]
@dbarner1 please create your own issue with steps to reproduce and preferably a link to a git repository with the minimal amount of code needed to reproduce the issue. That - would be greatly appreciated! 🙂
