### ISSUE TITLE
Milliseconds or Nanoseconds?

### ISSUE THREAD

**Issue by cmcnicholas** [realm/realm-js#2734]
## Goals

I noticed the documentation for querying may be incomplete: https://github.com/realm/realm-js/blob/master/docs/tutorials/query-language.md#timestamps

It mentions date formats including nanoseconds but every example i have seen is in milliseconds, most platforms don't have the precision for nanoseconds is this correct? Should i be formatting dates with nanoseconds or milliseconds?

## Expected Results

Formatting a date value, need to understand is it milliseconds or nanoseconds realm wants?

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by blagoev** [comment]
Unless you needed nanoseconds precision you don't need to specify it in the query.

**Comment by cmcnicholas** [comment]
> Unless you needed nanoseconds precision you don't need to specify it in the query.

My point being I believe the documentation to be wrong. I do need milliseconds precision, is the documentation correct and it's nanoseconds? If I start using milliseconds it won't compare correctly but I haven't seen any queries specifying nanoseconds ie. 1 billionth of a second precision

**Comment by blagoev** [comment]
you are right, that should be milliseconds in the doc

**Comment by blagoev** [comment]
@cmcnicholas The docs are correct its nanoseconds as its stated in the docs. Sorry about the previous misinformation on that

**Comment by cmcnicholas** [comment]
crikey, where can I go to find the underlying realm implementation for this sort of stuff? I currently have to look at it via one of the sdk's but I imagine there is a spec somewhere?

**Comment by ironage** [comment]
@cmcnicholas here's [some comments](https://github.com/realm/realm-core/blob/master/src/realm/timestamp.hpp#L32-L65) in the core implementation that might interest you.

You're right in pointing out that not all SDK native types support nanosecond precision, but given that a Realm file is cross platform we decided to implement Realm Timestamps to support the most precise implementation (a cocoa NSDate supports nanoseconds). Those SDKs which only support up to millisecond resolution (as with js Dates) will set the Realm nanosecond part to 0. However, in an effort to maintain complete flexibility, the query language allows you to specify the nanosecond part in a query if desired. While this creates a bit of an inconsistency in the API, it also allows you to completely specify the timestamp in case you were reading a Realm file generated by the cocoa SDK. In practice this means converting milliseconds into nanoseconds for these types of queries. Hope that helps clarify things a bit.

**Comment by blagoev** [comment]
closing this issue for it seems it has been answered. If needed please reopen.
