### ISSUE TITLE
must be of type 'number', got 'null' (null)

### ISSUE THREAD

**Issue by harryharihar** [realm/realm-js#2735]
I want to store data and with null values.

const OutletSchema = {
        name: outlet,
        properties: {
          ID: 'int',
          PIN_CODE: 'int',
          PHONE: 'string',
          MOBILE: 'string',
          EMAIL: 'string',
          ALT_PER_CONTACT: 'string',
          STATE_CODE: 'string',
          FOOD_LICENSE_NO: 'string',
        }
      };

      const database = {
        path: 'outlet.realm',
        schema: [OutletSchema],
        schemaVersion: 0
      };
   
Realm.open(database).then(realm => {
        realm.write(() => {
          allOuletsList.forEach(obj => {
            realm.create(OUTLET_SCHEMA, obj);
          });
        });
      });

Sample Json
{
  "ID": 415,
  "PIN_CODE": null,
  "PHONE": null,
  "MOBILE": null,
  "EMAIL": null,
  "ALT_PER_CONTACT": null,
  "STATE_CODE": "27",
  "FOOD_LICENSE_NO": "11512011001578"
}

I am still getting *Error: outlet.PIN_CODE must be of type 'number', got 'null' (null)*

Realm JS SDK Version: 3.6.4
Node or React Native: 0.58.5
Client OS & Version: windows 10

**Comment by Shumuu** [comment]
All fields that can have null values, must be optional.

You should have a look at the [documentation](https://realm.io/docs/javascript/latest/#models) again.

The important bit is

```
properties: {
  ID: 'int',
  PIN_CODE: 'int**?**',
  PHONE: 'string**?**',
}
```

**Comment by kneth** [comment]
Answered by @Shumuu

**Comment by anshumanworks** [comment]
> For basic types only optional fields can store null and undefined values.
> 
> You should have a look at the [documentation](https://realm.io/docs/javascript/latest/#models) again.
> 
> The important bit is
> 
> ```
> properties: {
>   ID: 'int',
>   PIN_CODE: 'int?',
>   PHONE: 'string?',
> }
> ```
> 
> The **?** makes the property optional.

can `number?[]` hold null?

**Comment by Shumuu** [comment]
Yes @anshumanworks  `number?[]` can hold null values.

[List Properties](https://realm.io/docs/javascript/latest/#list-properties)


`const PersonSchema = {
  name: 'Person',
  properties: {
    name: 'string',
    testScores: 'double?[]'
  }
};

let realm = new Realm({schema: [PersonSchema, CarSchema]});

realm.write(() => {
  let charlie = realm.create('Person', {
    name: 'Charlie',
    testScores: [100.0]
  });

  // Charlie had an excused absense for the second test and was allowed to skip it
  charlie.testScores.push(null);

  // And then he didn't do so well on the third test
  charlie.testScores.push(70.0);
});`

**Comment by anshumanworks** [comment]
> Yes @anshumanworks `number?[]` can hold null values. The list itself is not optional but can be an empty array, the list can hold null values though.
> 
> [List Properties](https://realm.io/docs/javascript/latest/#list-properties)
> 
> ```
> const PersonSchema = {
>   name: 'Person',
>   properties: {
>     name: 'string',
>     testScores: 'double?[]'
>   }
> };
> 
> let realm = new Realm({schema: [PersonSchema, CarSchema]});
> 
> realm.write(() => {
>   let charlie = realm.create('Person', {
>     name: 'Charlie',
>     testScores: [100.0]
>   });
> 
>   // Charlie had an excused absense for the second test and was allowed to skip it
>   charlie.testScores.push(null);
> 
>   // And then he didn't do so well on the third test
>   charlie.testScores.push(70.0);
> });
> ```

Thanks for answering. 
So you mean I can't store `null` to a key if it is `array`. Cool.
Also, can I have UnionTypes in Realm? Like not defining the data type before hand?

**Comment by Shumuu** [comment]
> So you mean I can't store null to a key if it is array. Cool.

No, you can store null values in `number?[]`.

> Also, can I have UnionTypes in Realm? Like not defining the data type before hand?

Not 100% sure, but I highly doubt it.

**Comment by anshumanworks** [comment]
> > So you mean I can't store null to a key if it is array. Cool.
> 
> No, you can store null values in `number?[]`.
> 
> > Also, can I have UnionTypes in Realm? Like not defining the data type before hand?
> 
> Not 100% sure, but I highly doubt it.

Yeah, I understand that Array Items can be **null** but my use case is that there is a field `users: number?[]` and the API returns `null` for users. In this case, it is throwing the error.

**Comment by Shumuu** [comment]
What API ?.

number?[] is an Array which contains either numbers or null values. Are you
expecting users ?

Could you explain your use case maybe a little bit more ?

>

**Comment by anshumanworks** [comment]
> What API ?. number?[] is an Array which contains either numbers or null values. Are you expecting users ? Could you explain your use case maybe a little bit more ?
> […](#)

Sorry, so what I mean is.
Say if I have a users array which is `number?[]` but my backend API returns null for this array, which is not accepted by realm as it is throwing error.

**Comment by Shumuu** [comment]
If your API returns null for this array, just do a null check and if it is
null, initialize it as an empty array instead

Am Mo., 31. Aug. 2020 um 14:29 Uhr schrieb Anshuman Bhardwaj <
notifications@github.com>:

**Comment by anshumanworks** [comment]
@Shumuu thanks

**Comment by anshumanworks** [comment]
I am getting this error 
DB ERROR [Error: Task.recurringDaysOfMonth must be of type 'number?[]', got 'null' (null)]

My API returns this data
```
{"__typename": "Task", "checklist": null, "createdAt": "2020-08-27T08:40:30.824Z", "createdBy": "aut138360db", "description": "Issue", "expiresAt": "2020-09-01T12:43:00.039Z", "files": [], "id": "Krj1g", "isRepeating": true, "recurringDay": ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"], "recurringDaysOfMonth": null, "recurringPeriod": "DAILY", "target": {"__typename": "Target", "users": [Array]}, "title": "Task Repeat issue", "updatedAt": "2020-09-01T08:43:00.036Z"}
```

@Shumuu like you said I assigned `[]` to the properties with value as `null`.

This is what is passed to the realm.create() call
```
{"__typename": "Task", "checklist": null, "createdAt": "2020-08-27T08:40:30.824Z", "createdBy": "auth0|5f030b230f9b7b00138360db", "description": "Issue", "expiresAt": "2020-09-01T12:43:00.039Z", "files": [], "id": "Krmam3l2zDi3nrdjZj1g", "isRepeating": true, "recurringDay": ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"], "recurringDaysOfMonth": [], "recurringPeriod": "DAILY", "target": {"__typename": "Target", "users": [Array]}, "title": "Task Repeat issue", "updatedAt": "2020-09-01T08:43:00.036Z"}
```
