### ISSUE TITLE
Not work case insensitive with cyrillic

### ISSUE THREAD

**Issue by jdorj** [realm/realm-js#2744]
- Realm JS SDK Version: 3.6.4

**Comment by kraenhansen** [comment]
For us to better understand and resolve your issue, would you please fill out the [issue template](https://raw.githubusercontent.com/realm/realm-js/master/.github/ISSUE_TEMPLATE.md)?

**Comment by ironage** [comment]
This is likely related to https://github.com/realm/realm-js/issues/820 and is due to a core limitation https://github.com/realm/realm-core/issues/777
> sorting and case insensitive string matches in queries are only supported for character sets in ‘Latin Basic’, ‘Latin Supplement’, ‘Latin Extended A’, ‘Latin Extended B’ (UTF-8 range 0-591).

**Comment by steffenagger** [comment]
As @ironage wrote this is a known (non trivial) issue. Please upvote https://github.com/realm/realm-core/issues/777, if you're in need of this feature. Will close this issue.
