### ISSUE TITLE
Proguard error on ExpoKit ejected apps

### ISSUE THREAD

**Issue by stochris** [realm/realm-js#2749]
I encountered an error with really recent version of the react-native, realm and expo, and used a fix provided by #2015 ( a 2018 issue ).

The fix is quite simple, just need to add `-keep class io.realm.react.**` in the proguard rules.

I propose that this should be added to a troubleshooting section inside th readme 😄, given that I'm not the only one encountering this problem as of lately

For replication, I created an expo project, ejected it to "ExpoKit" managed project, and then added realm ( which I also linked by running `react-native link realm`, even though react-native autolink should handle it, expo managed projects seems to have a bit of a problem with this )
## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.5
- Node or React Native: 0.60 ( expo fork for sdk 36 )
- Client OS & Version: macOS Mojave 10.14.6
- Which debugger for React Native: None

**Comment by kneth** [comment]
Expo does unfortunately not support Realm.
