### ISSUE TITLE
Improve error message when Chrome debugging does not work

### ISSUE THREAD

**Issue by DHidee66** [realm/realm-js#276]
Hi,

I keep getting this error when I try to debug the app in Chrome. 

![screen shot 2016-02-23 at 10 56 29 pm](https://cloud.githubusercontent.com/assets/6751025/13268081/b9ab4d1a-da80-11e5-97af-e71b86afe67a.png)

The first time I debug the app on a clean device it runs ok but then after I restart the app or the device it crashes.

Thank You!

**Comment by nhachicha** [comment]
Hi @DHidee66 
can you try to reverse & forward the port manually from the shell?
```
adb reverse tcp:8081 tcp:8081
adb forward tcp:8082 tcp:8082
```

**Comment by DHidee66** [comment]
Hey @nhachicha .. It works. Thank you. :)
What is causing this to happen?

**Comment by DHidee66** [comment]
I called a non existing function and this came up in the Chrome debugger but not on the device.
![screen shot 2016-02-24 at 12 09 10 pm](https://cloud.githubusercontent.com/assets/6751025/13283792/4337312e-daf0-11e5-957e-be33a489c1b6.png)
Is it realm that needs to create a session in 8082?

**Comment by nhachicha** [comment]
We do have an Http server running on device (port 8082) to process Chrome debug commands.
this is why you need to forward & reverse the aforementioned port. This is done for you when you compile https://github.com/realm/realm-js/blob/master/react-native/android/publish_android_template#L19, but you may have this problem when having more than one device attached

**Comment by DHidee66** [comment]
It seems like the task it's not executed at the right time, cause ``adb forward tcp:8082 tcp:8082`` definitely  fixes the problem.

**Comment by appden** [comment]
Reopening this so we can be sure to improve the error message along with improving documentation.

**Comment by appden** [comment]
The documentation issue for this is #249

**Comment by funkyeah** [comment]
Also can confirm `adb forward tcp:8082 tcp:8082` fixed the issue for me. 

If it helps anyone in the future my particular situation was:
1) I was using chrome debugger
2) had issues connecting to standalone React-Dev-Tools which suggests doing 'adb reverse tcp:8097 tcp:8097'. 
3) re-enabled the chrome debugging and it no longer worked with the same error message as this issue
4) had to do both the `adb reverse tcp:8081 tcp:8081` and forward command above to get it to work again
