### ISSUE TITLE
Accessing object of type * which has been invalidated or deleted.

### ISSUE THREAD

**Issue by angelo558** [realm/realm-js#2765]
Hello everyone!

## Goals

I am trying to get values from my realm and print them in a flatlist in react native 

## Expected Results

I would expect it to print my flatlist without any issues.

## Actual Results

The error :
Accessing object of type ListIncomes which has been invalidated or deleted.
But when I check if my object is valid, (isValid()), I get true, I can even make a console.log with it.

## Steps to Reproduce

First, I created a first Realm that I modified just to add an id. I also changed the name of ListIncomeSchemaOk and ListIncomes but it doesn't change anything. Weirdest thing is that the text "TEST" is written on my app and is printed on my screen just before the error comes. It seems logical since I can make a console.log(Array.from(realm.objects('ListIncomes'))) and the right thing is printed.

## Code Sample
The definition of my realm:
`const ListIncomeSchemaOk = {
  name: 'ListIncomes',
  properties: {
    id: 'string',
    charterer:  'string',
    type:  'string',
    tonage:  'float',
    price:  'float',
    from:  'string',
    to:  'string',
    fromyear:  'int',
    frommonth:  'int',
    fromday:  'int',
    toyear:  'int',
    tomonth:  'int',
    today:  'int'
  }
};`

When I try to get my values:

`
    componentDidMount(){
        Realm.open({schema: [ListIncomeSchemaOk], schemaVersion: currentVersion})
        .then(realm => {
           this.setState({listItems: Array.from(realm.objects('ListIncomes'))})
          realm.close();
        })
        .catch(error => {
          console.log(error);
        })
    }`

And in the render:

`  <FlatList
  data={this.state.listItems}
  keyExtractor={(item) => item.id}
  renderItem={({item}) => <Text>TEST</Text>}
  />`

## Version of Realm and Tooling

- Realm JS SDK Version: 4.0.0-beta.0
- Node or React Native: react-native-cli: 2.0.1 and react-native: 0.61.5
- Client OS & Version:  Windows 10 PRO 1909
- Which debugger for React Native: ?/None

I am pretty sure it is a stupid error but I checked others similar issues on github and stack but all add an issue with navigation (but I don't have any navigation on my file) or with the validity but my object is valid... I really don't understand and it's making me crazy! Sorry if it is a stupid error
Thanks in advance and have a nice evenning :)

**Comment by ebrahimhassan121** [comment]
@angelo558 did you find a solution

**Comment by angelo558** [comment]
Yes, as I said in the edit I was closing realm too soon. now I only close it on componentWillUnmount



Sent from my MI 5s
On ebrahimhassan121 <notifications@github.com>, 27 Jun 2020 8:07 pm wrote:

@angelo558<https://github.com/angelo558> did you find a solution

**Comment by lilingxi01** [comment]
Just a memo: this issue can also be triggered by the "hot refresh" of react native dev. If you are facing this issue and have no idea on that, check if it only happens after a hot refresh.

**Comment by Joshfindit** [comment]
Surprisingly enough, the example TODO app led me in to this error.

https://github.com/mongodb-university/realm-tutorial-react-native/blob/4f873f2fe271be8030704aebbac65c7149533770/providers/TasksProvider.js#L48

That line is called in the following scenario:
- Navigate to a screen that uses a `FlatList` to list tasks
- Show a Modal that's part of the TaskView screen
- Success, Fail, or Dismiss the modal
- *Line is run here and the realm connection is closed, causing the error*

**Comment by takameyer** [comment]
@Joshfindit That tutorial is out of date.  We now have a package called `@realm/react` that handles this better.  Try it out and let us know what you think!
https://github.com/realm/realm-js/tree/master/packages/realm-react
