### ISSUE TITLE
Is there a way to get only specific fields from table?

### ISSUE THREAD

**Issue by AwanesowArtem** [realm/realm-js#2772]
Hi guys.
Is there a way to get only specific fields from a table?
For example, I have a table which has 20 fields, in some cases, I don't need all fields, is there a way to specify what exact fields I want to get?

I hope getting only part of the fields will improve performance.

Thanks in advance.

**Comment by tgoyne** [comment]
There is no need to do that with Realm. Realm objects are a live view into the database rather than a copy of the data, and any fields which you do not access will not be read from disk at all.
