### ISSUE TITLE
Vulnerable dependency (decompress)

### ISSUE THREAD

**Issue by rajivshah3** [realm/realm-js#2773]
## Goals

`realm-js` depends on [`decompress`](https://github.com/kevva/decompress), which is vulnerable to arbitrary file write (kevva/decompress#71). It does not seem like that project is actively maintained anymore, as the most recent commit is from 2017. Even though `decompress` only seems to be used in order to [unzip `realm-core` and `realm-sync`](https://github.com/realm/realm-js/blob/e76ef7b276af3e38728ed21ca3eb1cbcf7d89f8f/scripts/download-realm.js#L114-L118) when building from source and not anywhere else, tools such as [Snyk](https://app.snyk.io/vuln/SNYK-JS-DECOMPRESS-557358) and `npm audit` are now alerting users that `realm-js` has introduced a vulnerable dependency. Would it be possible to switch to something like [node-tar](https://github.com/npm/node-tar) to avoid this alert? I'm happy to make a PR for this change.

**Comment by blagoev** [comment]
Hey @rajivshah3 thanks for reporting this. It would be great if you submit a PR for this. We should be definitely removing such dependencies
