### ISSUE TITLE
Installation with NPM fails

### ISSUE THREAD

**Issue by guoyw** [realm/realm-js#2774]
Node version ：v12.16.1
npm  version  ：v6.14.3
![CB4CE76C-E43D-4785-B9E6-9E35113023C7](https://user-images.githubusercontent.com/25916259/77874828-d5688a80-7280-11ea-888b-48dba4bb58e1.png)

**Comment by blagoev** [comment]
You should upgrade the Realm JS version to version 5. It adds support for node 12. Closing this issue. Reopen it if you still have problems
