### ISSUE TITLE
[v5] Can't use realmObject.keys() with TypeScript

### ISSUE THREAD

**Issue by sintylapse** [realm/realm-js#2778]
## Goals
Using `realmObject.keys()` causes TypeScript error `Property 'keys' does not exist on type 'Object'.`. It might be related to https://eslint.org/docs/rules/no-prototype-builtins so we could use keys like this 
```js
Realm.Object.prototype.keys.call(realmObject)
```
but the same error appears in ts `Property 'keys' does not exist on type 'Object'.`

It seems new methods should be added to prototype definition

## Expected Results
No ts errors

## Actual Results
`Property 'keys' does not exist on type 'Object'.`

## Version of Realm and Tooling
- Realm JS SDK Version: 5.0.2
- Node or React Native: 61.5

**Comment by blagoev** [comment]
@sintylapse It should be fixed in Realm JS 5.0.3. We added TypeScript definitions for these methods

**Comment by sintylapse** [comment]
@blagoev yes it works now, thanks
