### ISSUE TITLE
Have app await migration on synchronous realm?

### ISSUE THREAD

**Issue by AkalUstat** [realm/realm-js#2779]
Orignally in my app, I used asynchronous realm using `Realm.open`. But i moved to the synchronous implementation using `new Realm`. Due to some recent major changes to schema, I have had to specify a migration function to realm, but it is an async function (and potentially time consuming due to the amount of items the user may have to stored).Due to this, the app is showing a white screen during the migration (for long periods of time). Is there anyway avoid this or get informed of a migration starting/ending without changing my codebase to `Realm.open`.

My current function: 
```js

const localRealmConfig: Configuration = {
  schema: [ EntrySchema, ModificationSchema, LineSchema ],
  schemaVersion: 2,
  migration: async ( oldRealm, newRealm ) => {
    if ( oldRealm.schemaVersion < 2 ) {
      const newItems = newRealm.objects<entryObj>( 'Entry' );
      for await ( const item of newItems ) {
        if ( !item.lines ) item.lines = item.type === 'Bani' ? await loadBani( item.shabadId, 'long' ) : await loadShabad( item.shabadId );
      }
    }
  },
  // deleteRealmIfMigrationNeeded: true,
};

export default new Realm( localRealmConfig );

```

**Comment by sintylapse** [comment]
Maybe use https://github.com/crazycodeboy/react-native-splash-screen ? Just call `SplashScreen.hide()`inside js when migration is over

**Comment by AkalUstat** [comment]
Is there a function/variable provided by realm to know when its done?

**Comment by sintylapse** [comment]
@AkalUstat you can have full control over migrations by using linear migrations https://realm.io/docs/javascript/latest/#linear-migrations

**Comment by kneth** [comment]
We don't have progress notification for schema migration as we have for downloading a synced Realm. In general, we recommend that you use `Realm.open()` to avoid blocking.

**Comment by JDrizzy** [comment]
> we recommend that you use Realm.open() to avoid blocking

What would be the recommended way to write a test for a migration that uses `Realm.open()`? I'm having issues trying to confirm expected changes after a migration has been completed, but can't find a way to wait for the migration to finish before testing the data.

```JS
test('wait for migration to finish - bad example', async () => {
  let realm = await Realm.open({
    schema: [
      {
        name: 'Table',
        primaryKey: '_id',
        properties: {
          _id: 'int',
          field1: 'int'
        }
      }
    ],
    path: 'test.realm',
    schemaVersion: 1
  })
  realm.close()

  realm = await Realm.open({
    schema: [
      {
        name: 'Table',
        primaryKey: '_id',
        properties: {
          _id: 'int',
          field1: 'int',
          field2: 'int'
        }
      }
    ],
    schemaVersion: 2,
    path: 'test.realm',
    migration: (oldRealm, newRealm) => {
      setTimeout(() => {
        console.log('Migration finished')
      }, 100)
    }
  })

  // Does not wait for migration to finish before the database is closed
  console.log('closing...')
  realm.close()
  Realm.deleteFile({ path: 'test.realm' })
})
```

I'm running realm-js version 11.0.0 if that helps. Checking out more recent versions released, I can't see any changes to the migration logic, besides from changing the configuration name to `onMigration` instead.

Please let me know if anyone has bumped into something similar and if there is any workarounds. Thank you greatly ❤️

**Comment by kneth** [comment]
@JDrizzy You probably don't see the migration code running since Realm can automatically migrate the schema. If you instead change the type of `field1` to `string`, manual migration will be needed.
