### ISSUE TITLE
Error: @size and @count can only operate on types list, binary, or string. Not working on int[], float[], etc?

### ISSUE THREAD

**Issue by hkwdaniel** [realm/realm-js#2807]
## Goals

Filter based on array size

## Expected Results

Persons with scores > 0

## Actual Results

Error: Invalid query: @size and @count can only operate on types list, binary, or string

## Steps to Reproduce

```
const PersonSchema = {
  name: 'Person',
  properties: {
    name: 'string',
    testScores: int[]
  }
};

realm.objects('Person').filtered('testScores.@count > 0');
```

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native: >60
- Client OS & Version: Android device
- Which debugger for React Native: None

**Comment by ironage** [comment]
We don't have support for querying list of primitives yet, but we are currently working on it and the query you are trying to run will be available soon.

**Comment by kneth** [comment]
Blocked by: https://github.com/realm/realm-core/pull/3693

**Comment by ironage** [comment]
This feature has been released in the v10 release series since realm-js 10.0.0-beta.1. Please upgrade to try it out.
