### ISSUE TITLE
failed to compile RealmAnalytics.mm

### ISSUE THREAD

**Issue by YaoHuiJi** [realm/realm-js#2812]
## Goals

Update realm from 2.29.2 to 5.0.3 in my react-native project.

edit: It seems to have nothing to do with realm upgrade, because I upgrade react-native from 0.60.5 to 0.62.2 before upgrading realm,  when I downgrade realm to 2.29.2, this build failure still exists.

## Expected Results

Successfully build RealmReact  with react native 0.62.2 (Flipper).

## Actual Results

Failed to compile RealmAnalytics.mm. Failed to build RealmReact. 

Here are the Xcode build messages and the snapshot of it.

<img width="1001" alt="截屏2020-04-15 21 19 30" src="https://user-images.githubusercontent.com/741543/79348259-5bfeb680-7f67-11ea-8dd0-d2c76803e2f4.png">

`
CompileC /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/Objects-normal/arm64/RealmAnalytics.o /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RealmReact' from project 'RealmReact')
    cd /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios
    export LANG=en_US.US-ASCII
    /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/../../scripts/ccache-clang.sh -x objective-c++ -target arm64-apple-ios8.0 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++14 -stdlib=libc++ -fobjc-arc -fmodules -fmodules-cache-path=/Users/jackyao/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/jackyao/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -fembed-bitcode-marker -index-store-path /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Index/DataStore -iquote /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/RealmReact-generated-files.hmap -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/RealmReact-own-target-headers.hmap -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/RealmReact-all-target-headers.hmap -iquote /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/RealmReact-project-headers.hmap -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Products/Debug-iphoneos/include -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/src -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/src/object-store/src -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/src/object-store/external/json -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/vendor -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/vendor/realm-ios/include -I../../vendor/GCDWebServer/GCDWebServer -I../../vendor/GCDWebServer/GCDWebServer/Core -I../../vendor/GCDWebServer/GCDWebServer/Requests -I../../vendor/GCDWebServer/GCDWebServer/Responses -I../../../react-native/React -I../../../react-native/React/Base -I../../../react-native/React/CoreModules -I../../../react-native/React/CxxBridge -I../../../react-native/React/CxxModule -I../../../react-native/React/CxxUtils -I../../../react-native/React/DevSupport -I../../../react-native/React/Fabric -I../../../react-native/React/Inspector -I../../../react-native/React/Modules -I../../../react-native/React/Profiler -I../../../react-native/React/UIUtils -I../../../react-native/React/Views -I../../../react-native/React/Base/Surface -I../../../react-native/React/Fabric/Mounting -I../../../react-native/React/Fabric/Surface -I../../../react-native/React/Fabric/Utils -I../../../react-native/React/Views/RefreshControl -I../../../react-native/React/Views/SafeAreaView -I../../../react-native/React/Views/ScrollView -I../../../react-native/React/Base/Surface/SurfaceHostingView -I../../../react-native/React/Fabric/Mounting/ComponentViews -I../../../react-native/React/Fabric/Mounting/ComponentViews/ART -I../../../react-native/React/Fabric/Mounting/ComponentViews/ActivityIndicator -I../../../react-native/React/Fabric/Mounting/ComponentViews/Image -I../../../react-native/React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop -I../../../react-native/React/Fabric/Mounting/ComponentViews/Modal -I../../../react-native/React/Fabric/Mounting/ComponentViews/Root -I../../../react-native/React/Fabric/Mounting/ComponentViews/SafeAreaView -I../../../react-native/React/Fabric/Mounting/ComponentViews/ScrollView -I../../../react-native/React/Fabric/Mounting/ComponentViews/Slider -I../../../react-native/React/Fabric/Mounting/ComponentViews/Switch -I../../../react-native/React/Fabric/Mounting/ComponentViews/Text -I../../../react-native/React/Fabric/Mounting/ComponentViews/UnimplementedComponent -I../../../react-native/React/Fabric/Mounting/ComponentViews/UnimplementedView -I../../../react-native/React/Fabric/Mounting/ComponentViews/View -I../../../../ios/Pods/Headers/Public -I../../../../ios/Pods/Headers/Public/CocoaAsyncSocket -I../../../../ios/Pods/Headers/Public/CocoaLibEvent -I../../../../ios/Pods/Headers/Public/DoubleConversion -I../../../../ios/Pods/Headers/Public/FBLazyVector -I../../../../ios/Pods/Headers/Public/FBReactNativeSpec -I../../../../ios/Pods/Headers/Public/Flipper -I../../../../ios/Pods/Headers/Public/Flipper-DoubleConversion -I../../../../ios/Pods/Headers/Public/Flipper-Folly -I../../../../ios/Pods/Headers/Public/Flipper-Glog -I../../../../ios/Pods/Headers/Public/Flipper-PeerTalk -I../../../../ios/Pods/Headers/Public/Flipper-RSocket -I../../../../ios/Pods/Headers/Public/FlipperKit -I../../../../ios/Pods/Headers/Public/GCDWebServer -I../../../../ios/Pods/Headers/Public/Interactable -I../../../../ios/Pods/Headers/Public/OpenSSL-Universal -I../../../../ios/Pods/Headers/Public/RCTRequired -I../../../../ios/Pods/Headers/Public/RCTTypeSafety -I../../../../ios/Pods/Headers/Public/RNCPushNotificationIOS -I../../../../ios/Pods/Headers/Public/RNDateTimePicker -I../../../../ios/Pods/Headers/Public/RNDeviceInfo -I../../../../ios/Pods/Headers/Public/RNGestureHandler -I../../../../ios/Pods/Headers/Public/RNLocalize -I../../../../ios/Pods/Headers/Public/RNOpenAppSettings -I../../../../ios/Pods/Headers/Public/RNReanimated -I../../../../ios/Pods/Headers/Public/RNSVG -I../../../../ios/Pods/Headers/Public/RNScreens -I../../../../ios/Pods/Headers/Public/RNSound -I../../../../ios/Pods/Headers/Public/RNVectorIcons -I../../../../ios/Pods/Headers/Public/React-Core -I../../../../ios/Pods/Headers/Public/React-RCTText -I../../../../ios/Pods/Headers/Public/React-cxxreact -I../../../../ios/Pods/Headers/Public/React-jsi -I../../../../ios/Pods/Headers/Public/React-jsiexecutor -I../../../../ios/Pods/Headers/Public/React-jsinspector -I../../../../ios/Pods/Headers/Public/ReactCommon -I../../../../ios/Pods/Headers/Public/ReactNativeART -I../../../../ios/Pods/Headers/Public/Yoga -I../../../../ios/Pods/Headers/Public/YogaKit -I../../../../ios/Pods/Headers/Public/glog -I../../../../ios/Pods/Headers/Public/react-native-background-timer -I../../../../ios/Pods/Headers/Public/react-native-blur -I../../../../ios/Pods/Headers/Public/react-native-keep-awake -I../../../../ios/Pods/Headers/Public/CocoaLibEvent/event2 -I../../../../ios/Pods/Headers/Public/DoubleConversion/double-conversion -I../../../../ios/Pods/Headers/Public/FBLazyVector/FBLazyVector -I../../../../ios/Pods/Headers/Public/FBReactNativeSpec/FBReactNativeSpec -I../../../../ios/Pods/Headers/Public/Flipper-DoubleConversion/double-conversion -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly -I../../../../ios/Pods/Headers/Public/Flipper-Glog/glog -I../../../../ios/Pods/Headers/Public/Flipper-PeerTalk/peertalk -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/yarpl -I../../../../ios/Pods/Headers/Public/FlipperKit/FBDefines -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitHighlightOverlay -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitLayoutPlugin -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitLayoutTextSearchable -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitNetworkPlugin -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitReactPlugin -I../../../../ios/Pods/Headers/Public/FlipperKit/FlipperKitUserDefaultsPlugin -I../../../../ios/Pods/Headers/Public/FlipperKit/SKIOSNetworkPlugin -I../../../../ios/Pods/Headers/Public/OpenSSL-Universal/openssl -I../../../../ios/Pods/Headers/Public/RCTRequired/RCTRequired -I../../../../ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety -I../../../../ios/Pods/Headers/Public/React-Core/React -I../../../../ios/Pods/Headers/Public/React-RCTText/RCTText -I../../../../ios/Pods/Headers/Public/React-cxxreact/cxxreact -I../../../../ios/Pods/Headers/Public/React-jsi/jsi -I../../../../ios/Pods/Headers/Public/React-jsiexecutor/jsireact -I../../../../ios/Pods/Headers/Public/React-jsinspector/jsinspector -I../../../../ios/Pods/Headers/Public/ReactCommon/ReactCommon -I../../../../ios/Pods/Headers/Public/Yoga/yoga -I../../../../ios/Pods/Headers/Public/glog/glog -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/chrono -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/concurrency -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/container -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/executors -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/experimental -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/functional -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/futures -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/gen -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/hash -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/init -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/io -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/lang -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/memory -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/net -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/portability -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/ssl -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/synchronization -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/system -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/tracing -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/benchmarks -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/framing -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/internal -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/statemachine -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/transports -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/yarpl/flowable -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/yarpl/observable -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/container/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/executors/task_queue -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/executors/thread_factory -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/futures/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/hash/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/io/async -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/memory/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/net/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/ssl/detail -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/synchronization/detail -I../../../../ios/Pods/Headers/Public/Flipper-RSocket/rsocket/transports/tcp -I../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/io/async/ssl -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/tests/react-test-app/ios/Pods/Headers/Public/React -I/Users/jackyao/ReactNative/individualmanagement/node_modules/realm/examples/ReactExample/node_modules/react-native/React -I/Users/jackyao/ReactNative/individualmanagement/ios/Pods/Headers/Public/React-Core -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/DerivedSources-normal/arm64 -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/DerivedSources/arm64 -I/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/DerivedSources -F/Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Products/Debug-iphoneos -isystem ../../core/include -MMD -MT dependencies -MF /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/Objects-normal/arm64/RealmAnalytics.d --serialize-diagnostics /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/Objects-normal/arm64/RealmAnalytics.dia -c /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm -o /Users/jackyao/Library/Developer/Xcode/DerivedData/IndividualManagement-bydmeqfaqklessatftyybnsyykds/Build/Intermediates.noindex/RealmReact.build/Debug-iphoneos/RealmReact.build/Objects-normal/arm64/RealmAnalytics.o

In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm:57:
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/assert.h:44:
In file included from ../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/portability/stdlib.h:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:101:9: error: no member named 'div_t' in the global namespace; did you mean 'dev_t'?
using ::div_t;
      ~~^
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm:57:
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/types.h:103:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/_types/_dev_t.h:31:31: note: 'dev_t' declared here
typedef __darwin_dev_t        dev_t;    /* device number */
                              ^
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm:57:
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/assert.h:44:
In file included from ../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/portability/stdlib.h:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:102:9: error: no member named 'ldiv_t' in the global namespace; did you mean 'dev_t'?
using ::ldiv_t;
      ~~^
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm:57:
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/types.h:103:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/_types/_dev_t.h:31:31: note: 'dev_t' declared here
typedef __darwin_dev_t        dev_t;    /* device number */
                              ^
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.mm:57:
In file included from /Users/jackyao/ReactNative/individualmanagement/node_modules/realm/react-native/ios/RealmReact/RealmAnalytics.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/assert.h:44:
In file included from ../../../../ios/Pods/Headers/Public/Flipper-Folly/folly/portability/stdlib.h:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:104:9: error: no member named 'lldiv_t' in the global namespace
using ::lldiv_t;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:106:9: error: no member named 'atof' in the global namespace
using ::atof;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:107:9: error: no member named 'atoi' in the global namespace
using ::atoi;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:108:9: error: no member named 'atol' in the global namespace
using ::atol;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:110:9: error: no member named 'atoll' in the global namespace
using ::atoll;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:112:9: error: no member named 'strtod' in the global namespace
using ::strtod;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:113:9: error: no member named 'strtof' in the global namespace
using ::strtof;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:114:9: error: no member named 'strtold' in the global namespace
using ::strtold;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:115:9: error: no member named 'strtol' in the global namespace
using ::strtol;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:117:9: error: no member named 'strtoll' in the global namespace
using ::strtoll;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:119:9: error: no member named 'strtoul' in the global namespace
using ::strtoul;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:121:9: error: no member named 'strtoull' in the global namespace
using ::strtoull;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:126:9: error: no member named 'rand' in the global namespace
using ::rand;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:127:9: error: no member named 'srand' in the global namespace
using ::srand;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:128:9: error: no member named 'calloc' in the global namespace
using ::calloc;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:129:9: error: no member named 'free' in the global namespace
using ::free;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:130:9: error: no member named 'malloc' in the global namespace
using ::malloc;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

`
and this is the Xcode screenshot  when I click one of the errors above

<img width="854" alt="截屏2020-04-15 21 56 25" src="https://user-images.githubusercontent.com/741543/79348878-2908f280-7f68-11ea-950b-4f147a94c845.png">

 I am not familiar with Xcode and c++, but these errors seem to be related to c++ headers? or some search header path conflict?  
I am not sure if I am right, I found that  the file path of the header file 'stdlib.h' included by cstdlib is '/ios/Pods/Flipper-Folly/folly/portability/Stdlib.h' ,should it be 'Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h' ?
If this is the problem, how to fix it?

here are the 'Header Search Path' of RealmReact project:

<img width="754" alt="截屏2020-04-15 22 34 26" src="https://user-images.githubusercontent.com/741543/79350142-a97c2300-7f69-11ea-9f4f-0cb8bca26878.png">

`
$(inherited) 
$(SRCROOT)/../../src 
$(SRCROOT)/../../src/object-store/src 
$(SRCROOT)/../../src/object-store/external/json 
$(SRCROOT)/../../vendor 
$(SRCROOT)/../../vendor/realm-ios/include 
$(SRCROOT)/../../vendor/GCDWebServer/GCDWebServer/** 
$(SRCROOT)/../../../react-native/React/** 
$(SRCROOT)/../../../../ios/Pods/Headers/Public/** 
$(SRCROOT)/../../tests/react-test-app/ios/Pods/Headers/Public/React $(SRCROOT)/../../examples/ReactExample/node_modules/react-native/React/**
`
I tried to change some of the paths aimlessly but have not luck😫

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native:  node 10.20.1 & react native 0.62.2
- Client OS & Version: macOS 10.15.4
- Which debugger for React Native: None

**Comment by YaoHuiJi** [comment]
it's not an issue about realm,  but about [react native upgrade](https://github.com/react-native-community/upgrade-support/issues/49#issuecomment-614699153). so I will close it.

**Comment by IM-CrazyDeveloper** [comment]
> it's not an issue about realm, but about [react native upgrade](https://github.com/react-native-community/upgrade-support/issues/49#issuecomment-614699153). so I will close it.

This os actual Realm issue

**Comment by kneth** [comment]
@IM-CrazyDeveloper Do you experience the issue with latest version (10.4.1)?

**Comment by flikQ** [comment]
This is still an issue.

**Comment by IM-CrazyDeveloper** [comment]
> @IM-CrazyDeveloper Do you experience the issue with latest version (10.4.1)?
no i didnt tried with this version, i downgraded realm to fix issue.

**Comment by kneth** [comment]
Since we did a major upgrade of build systems in v10.3.0, upgrading might cause you trouble. Please try to clear your build folders and mostly like your Cocoapod folders.

**Comment by rogel123** [comment]
@IM-CrazyDeveloper Hi still experiencing this issue. how did you resolve it?

**Comment by kneth** [comment]
@rogel123 Do you experience it when upgrading from pre-10.3.0 to latest? If so, please clear your build folders.

**Comment by rogel123** [comment]
Hi @kneth I made a huge upgrade from 3.2.0 to latest.

**Comment by ticketsadvantage** [comment]
@kneth @rogel123 Any word on solutions to this? I've been trying to fix this for a few days now...

I tried deleting all my extra header paths, tried recursive/non-recursive, tried cleaning out my podfile, but no luck.

**Comment by nicknjpconsultingllc** [comment]
@kneth @rogel123 Any word on solutions to this? I've been trying to fix this for a few days now...

I tried deleting all my extra header paths, tried recursive/non-recursive, tried cleaning out my podfile, but no luck.

**Comment by xploSEoF** [comment]
I'm also getting this issue. I am trying to upgrade a project from v3.2.0 to v10.8.0 but it won't build in XCode even following the usual:

- Clear cache
- Clear derived data
- Clear pods and re-install
- Clear node_modules folder and re-install
- Clear all of the above, re-install, and try again

I'm left with the rather painful decision to go backwards and install an older version, probably pre-v10 given the number of others experiencing this and the seemingly complete dismissal of the issue.

**Comment by nicknjpconsultingllc** [comment]
@xploSEoF I had to start a new RN project, then copy basically the whole iOS folder into my existing iOS folder. Then make all the changes to appdelegate, info.plist, etc. that my app needed. That seems to have worked.
