### ISSUE TITLE
Missing Realm constructor issue in production devices

### ISSUE THREAD

**Issue by karthikpala** [realm/realm-js#2814]
## Goals

Implement Realm JS with react-native for iOS 

## Expected Results

Realm JS should not crash in production for iOS

## Actual Results

Lots of crashes observed in firebase console.
It is weird that the crash is never observed in our testing devices.

```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
0  CoreFoundation                 0x184a88a48 __exceptionPreprocess
1  libobjc.A.dylib                0x1847affa4 objc_exception_throw
2  React                          0x10346c350 RCTGetFatalHandler + 159 (RCTAssert.m:159)
3  CoreModules                    0x102ef297c -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 65 (RCTExceptionsManager.mm:65)
4  CoreFoundation                 0x184a8ec20 __invoking___
5  CoreFoundation                 0x18495ed30 -[NSInvocation invoke]
6  CoreFoundation                 0x18495f908 -[NSInvocation invokeWithTarget:]
7  React                          0x10349feb8 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 572 (RCTModuleMethod.mm:572)
8  React                          0x1034a1fd4 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
9  React                          0x1034a1d38 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
10 libdispatch.dylib              0x184754610 _dispatch_call_block_and_release
11 libdispatch.dylib              0x184755184 _dispatch_client_callout
12 libdispatch.dylib              0x184701404 _dispatch_lane_serial_drain$VARIANT$mp
13 libdispatch.dylib              0x184701df8 _dispatch_lane_invoke$VARIANT$mp
14 libdispatch.dylib              0x18470b314 _dispatch_workloop_worker_thread
15 libsystem_pthread.dylib        0x1847a4b88 _pthread_wqthread
16 libsystem_pthread.dylib        0x1847a7760 start_wqthread
```

## Steps to Reproduce

I'm unable to find which user action is causing this crash. I only have the above stack-trace from firebase

We have tested many number of times in our test devices and unable to see this crash

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.4
- Node: 10.18.0
- React Native: 0.61.2
- Client OS & Version: iOS - issue is happening in multiple OS versions as per firebase (13.2.0, 13.3.1 etc)
- Which debugger for React Native: ?/None

**Comment by karthikpala** [comment]
Hi @kneth - Can you please provide any insight for this issue. It keeps on popping up in our firebase crashlytics console.

**Comment by karthikpala** [comment]
Hey, can anyone help me here? Is this something related to build process?

**Comment by kneth** [comment]
@karthikpala Sorry for the late reply. I suggest that you upgrade to a newer version as we have had a few fixes to our support of the auto-linking.

**Comment by karthikpala** [comment]
Thanks @kneth  - I will update the version and check. 
We are at realm v3.6.5 and unable to replicate this issue in our local builds. Since we are seeing this only in firebase crashlytics - do you have any idea why it might be happening?

**Comment by srinadh-k** [comment]
Is this issue fixed or still open?

**Comment by kneth** [comment]
@karthikpala @srinadh-k Do you still experience it if you upgrade to latest version?

**Comment by kneth** [comment]
I am closing the issue due to inactivity. If you experience the issue, please create a new issue.

**Comment by JaioSkura** [comment]
Hi! I am having the same issue, only in producction and after killing the app. I mean, when first install everything works ok, when opening again from background too, but when opening after been killed I had this error. 
Working with version: 10.20.0-beta.2

Would apreciate too much you help. Thanks

**Comment by hassanbazzi** [comment]
Same here. Happening to our users with 10.20.0-beta.2
