### ISSUE TITLE
[5.0.3]realm.delete can NOT delete the object returned by realm.objectForPrimaryKey

### ISSUE THREAD

**Issue by YaoHuiJi** [realm/realm-js#2816]
## Goals

delete an object from realm by id like this
`
realm.write(()=>{
   realm.delete(realm.objectForPrimaryKey(modelName, id));
})
`
It works fine all the time until I upgrade realm from 2.29.2 to 5.0.3.

## Expected Results

successfully delete realm object by id

## Actual Results

failed to delete, an error occurred:

> Argument to 'delete' must be a Realm object or a collection of Realm objects. 

I think realm.delete has failed to recognize the object returned by objectForPrimaryKey  as an realm object, but I don't know why.

## Code Sample

`
realm.write(()=>{
   realm.delete(realm.objectForPrimaryKey(modelName, id));
})
`

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.3
- Node or React Native:  react-native 0.60.5
- Client OS & Version: macOS 10.15.4
- Which debugger for React Native: ?/None

**Comment by blagoev** [comment]
thanks for reporting. we will investigate this further.

**Comment by blagoev** [comment]
@YaoHuiJi did you had the RN app with debugger enabled or this happens regardless?

**Comment by YaoHuiJi** [comment]
hi @blagoev,
I tried just now and found out it works well when debugger is enabled ,both on simulator and real device. 
and I have log the output of realm.objectForPrimaryKey, it's not null or undefined, and obj.isValid() is true. 
I also tried getting an object via realm.objects and delete it, failed too, same error.
if you need more information, please tell me.

**Comment by Gazzini** [comment]
I'm getting this error as well.

I'm not sure if it's related, but there might be something fundamentally wrong with my realm config. All of the objects in any sort of `Realm.Results` or `Realm.Collection` objects appear to be empty when I print them (literally `{}`), but the properties correctly resolve when accessed.

For instance:
```
const pool = realm.objectForPrimaryKey('Pool', pool.objectId);
console.log(pool);
console.log(pool.name);
```
This will print:
```
{}
examplePoolName
```

**Comment by Gazzini** [comment]
All of my issues disappear if I pass the schemas directly, instead of the classes, when calling Realm.open():

https://github.com/realm/realm-js/issues/2848#issuecomment-631485221

**Comment by YaoHuiJi** [comment]
still no luck after upgrade to 6.0.3
