### ISSUE TITLE
Updating from 3.3.0 to 5.03 broke Realm.copyBundledRealmFiles()

### ISSUE THREAD

**Issue by wesvance** [realm/realm-js#2824]
## Goals
I'd like to copy a realm bundled with my app, with Realm.copyBundledRealmFiles, and consume it with react-realm-context.

## Expected Results
For the bundled realm, available at the MainBundlePath, to get copied into the DocumentDirectoryPath and be consumed with react-realm-context by using copyBundledRealmFiles

## Actual Results
The realm didn't get bundled with the app and the realm initialization created a default, empty, realm. When inspecting the MainBundlePath, the pre-populated realm is present, however the realm created at the document directory is empty.

## Steps to Reproduce
Create a RN app, try and copy the bundled files in.

## Version of Realm and Tooling

Works on Realm JS 3.3.0 but broke on 5.0.3, node version 10.16.0
- Realm JS SDK Version: 5.0.3
- Node or React Native: 10.16.0

**Comment by kraenhansen** [comment]
Thanks for taking the time to report this!

> Node or React Native: 10.16.0
What is this referring to? It looks like a Node.js version to me, what version of React Native are you on and is this something you're experiencing on both iOS and Android?

Is this something you're experiencing only with release builds of the app or also when you're running it locally in development mode?

> Steps to Reproduce: Create a RN app, try and copy the bundled files in.

Concrete commands to help us easily reproduce this, would be great here.

**Comment by wesvance** [comment]
Sure!

I'm using RN: "0.61.5", and the app was only designed to be built for iOS - so thats where I see the error. 

I've experienced this on both development and release builds - but for local builds, it seems like theres a potential race condition? The realm file I'm trying to copy over is ~300mb, so I'm assuming it takes a second to do the copy. Similarly copyBundledRealmFiles wont copy the file if an existing file already exists - when I first build and launch the app, I get an empty realm file in the realm name.

### Steps to reproduce: 
1. Get a large-ish realm file, mine is 300 mb & place in the resources folder of the iOS app, and ensure its being added to the bundled resources with the build.
2. Add: Realm.copyBundledRealmFiles(); at the top of the index.js file, or BEFORE the first consumption of the Realm file. I'm using react-realm-context (v0.3.0) and react-realm-context initializes the realms whenever I import and create a new 'createRealmContext'. So I run Realm.copyBuildRealmFiles() before calling createRealmContext from 'react-realm-context'.
3. Build the app (must be a new build with no existing data, as copyBundledRealmFiles wont overwrite existing files).
4. Check the Realm Path - is the realm empty, or copied over? In my case - in all instances since upgrading from Realm v3.3.0, the realm is empty. I've tried to move the copyBundledRealmFiles to other places in the app (top of index.js, top of App.js, useEffect in app.js, etc), with no success.

### Question
How does copyBundledRealmFiles work? Is it guaranteed to finish before realm can initialize and create an empty realm?

I hope that helps!

**Comment by kraenhansen** [comment]
First off, sorry for the long wait on our part.
We've tried, but failed to reproduce the issue with realm@10.0.1:

## Generating a large Realm file

We're generating a large (400 mb) Realm with the following script:

```javascript
const Realm = require('realm');

const realm = new Realm({
  path: 'large.realm',
  schema: [{name: 'MyClass', properties: {data: 'data'}}],
});

if (realm.empty) {
  realm.write(() => {
    for (let i = 0; i < 40000; i++) {
      realm.create('MyClass', {
        data: new ArrayBuffer(10000),
      });
    }
  });
}

realm.close();
```

## Importing and calling the `copyBundledRealmFiles` method

```javascript
// Import the Realm file
import Realm from 'realm';

// Copy the bundled files (blocks until the files are completely copied)
Realm.copyBundledRealmFiles();

// Open Realm and print the number of objects
const config = { path: 'large.realm' };
const realm = new Realm(config);
console.log(`We have ${realm.objects('MyClass').length} objects`);
realm.close();

// Delete the file from the "Documents" directory, to force the next run to copy it.
// Comment this out to verify that the file is indeed copied to the "Documents" directory of the device.
Realm.deleteFile(config);
```

## Answering your questions

> I've experienced this on both development and release builds - but for local builds, it seems like theres a potential race condition?
> How does copyBundledRealmFiles work? Is it guaranteed to finish before realm can initialize and create an empty realm?

The `Realm.copyBundledRealmFiles` has a blocking synchronous implementation, which ensures that the file is completely copied from the bundle before it returns.
