### ISSUE TITLE
React Native Realm Db Backup

### ISSUE THREAD

**Issue by MehdiRaza1998** [realm/realm-js#2837]
-->

## Goals
To be able to successfully create a backup mechanism of realm DB with google drive.

## Expected Results
To access realm file and import/export easily 

## Actual Results
I want to backup my realm db file to google drive. I have searched everywhere there isn't any proper way to do that. Should I go for JSON conversion of my data and then importing/exporting. I mean Realm is just amazing, isn't there a proper way of making backups of my data.

**Comment by bmunkholm** [comment]
Why don't you just use the builtin sync to cloud.realm.io? That will provide realtime backup of any changes.
Alternatively if the realm file is not open, it's just a file you can copy to anywhere.

**Comment by bmunkholm** [comment]
That said we aim to keep github for bug reports and feature requests. So I'll be closing this issue and you are very welcome to ask others in our Forum for other advice if needed.

**Comment by MehdiRaza1998** [comment]
I am using Realm for local offline storage.  I am preferring the free storage providers like Google drive. I want to backup my data there. Isn't there a proper way to get the realm file, upload, download, and replace it back with the previous file.

**Comment by bmunkholm** [comment]
The short answer is that we don't have any features as such to support that. But as I mentioned it only requires you to not have the file open (!), and then you can copy/send/replace the realm file to your hearts content :-). Just ensure you don't copy an open file!

**Comment by panda0603** [comment]
@bmunkholm 
where is the db file located in android and ios? 
I would also allow users to save this db file on google drive or email or other storage, then allow them to import this file back if the app is reinstalled. 
I would need to know the location, the name and  extension of the db file. 
Thanks alot!

**Comment by kneth** [comment]
For an open Realm instance, you should be able to get the path using the `path` property.

**Comment by aftabaminzoobiapps** [comment]
> @bmunkholm
> where is the db file located in android and ios?
> I would also allow users to save this db file on google drive or email or other storage, then allow them to import this file back if the app is reinstalled.
> I would need to know the location, the name and extension of the db file.
> Thanks alot!

any help. I have copied the .realm file to some other folder
now I want to import that file back if the app is reinstalled.

**Comment by kneth** [comment]
@aftabaminzoobiapps 

When copying Realm files, you have to be 100 % certain that all instances are closed. As you know where you copied the files from, you can you that path to copy them back.

You can also [bundle Realm files](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#.copyBundledRealmFiles) with your app.

**Comment by AftabUfaq** [comment]
> @aftabaminzoobiapps
> 
> When copying Realm files, you have to be 100 % certain that all instances are closed. As you know where you copied the files from, you can you that path to copy them back.
> 
> You can also [bundle Realm files](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#.copyBundledRealmFiles) with your app.

after I have copied the `.realm` file and send that file to another device. now I was to restore data from the. realm file. how can I do this? any hint or suggestion. I am stuck on this for more than a month.

**Comment by kneth** [comment]
@AftabUfaq You can copy the file to the app's sandbox (how and where depend on platform) and then simply open the file in the app.

**Comment by AftabUfaq** [comment]
> @AftabUfaq You can copy the file to the app's sandbox (how and where depend on platform) and then simply open the file in the app.

thank you. can open that file as a normal like we open database.
