### ISSUE TITLE
Realm + Electron - works in local envt but throws an error after signing

### ISSUE THREAD

**Issue by arpwal** [realm/realm-js#2855]
I am trying to add Realm to the [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) project. I am able to do the basic CRUD operations in the dev environment, however after notarizing the app I am getting the following error while doing a `realm.open(config)`: 

```bash
Error: illegal operation on a directory
    at openLocalRealm (/Applications/.../Resources/app.asar/node_modules/realm/lib/extensions.js:99)
    at Function.open (/Applications/.../Resources/app.asar/node_modules/realm/lib/extensions.js:157)
    at Function.realm (/Applications/.../Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at new Jg (/Applications/.../Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at vK.onFinish (/Applications/.../Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at onFinish (/Applications/.../Contents/Resources/app.asar/dist/renderer.prod.js:2)
    at /Applications/.../Contents/Resources/app.asar/dist/renderer.prod.js:2
```

## Goals

I'm trying to get Realm work w/ an electron app. 

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.4
- Node or React Native: Node v12.16.3
- Client OS & Version: Fairly reproducible on MacOS - Catalina, High Sierra, and Mojave ..

**Comment by arpwal** [comment]
The plist file for signing the app is -- 

```bash
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.files.downloads.read-write</key>
    <true/>
    <key>com.apple.security.files.all</key>
    <true/>
  </dict>
</plist>

```

**Comment by kraenhansen** [comment]
While Realm JS doesn't officially support Electron, Realm Studio is [planning to add notarization as well](https://github.com/realm/realm-studio/issues/1139), that issue might be worth subscribing to.
Are you setting a specific `path` in the config object you're passing to `Realm.open`?

You might be hit by a variant of https://github.com/realm/realm-js/issues/818, where Realm JS might be trying to write a default Realm to a current working directory that it's not allowed to write to.
[Realm Studio changes working directory](https://github.com/realm/realm-studio/blob/master/src/utils/process-directories.ts) before opening Realm files (as far as I can remember, we do that to mitigate that issue).

**Comment by arpwal** [comment]
Good point, I think #818 and this are related issues. Thank you for the tip! :)

**Comment by kneth** [comment]
I close the issue, and let us use #818 to track it instead.

**Comment by cameroncruz** [comment]
@arpwal Hey I'm also trying to get Realm working with electron-react-boilerplate, but running into several errors installing. How did you do it successfully?
