### ISSUE TITLE
Missing realm constructor did you run pod install?

### ISSUE THREAD

**Issue by eladgel** [realm/realm-js#2856]
## Goals

Run the app on android

## Expected Results

App will run

## Actual Results

App crash on start asking if I ran pod install?

## Steps to Reproduce

-clone
-run yarn
-run react-native run-android
https://github.com/honeybook/realmtest

## Code Sample
In repo

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.4
- Node or React Native: 0.62.2
- Client OS & Version: Android version 9- Xiaomi mi 2
- Which debugger for React Native: ?/None

**Comment by eladgel** [comment]
I see the realm library being loaded on debug mode.

**Comment by eladgel** [comment]
Just saw this https://github.com/realm/realm-js/issues/2455
:/

**Comment by tfkci** [comment]
I have the same issue and didn't find anything in #2455 related to this. Can you please share how did you solve it @eladgel
