### ISSUE TITLE
Encryption Support

### ISSUE THREAD

**Issue by wzpo** [realm/realm-js#286]

**Comment by alazier** [comment]
This has already bee added and will be in the next release. You can start using this now by checking out the repo and building the npm module locally. To do this you need to do is set the version of the `realm` module to the repo path as is done in the examples: https://github.com/realm/realm-js/blob/master/examples/ReactExample/package.json#L10

There is an example of how to use encryption here: https://github.com/realm/realm-js/blob/master/tests/lib/encryption-tests.js#L40

**Comment by alazier** [comment]
This was just released in v0.11.0
