### ISSUE TITLE
error while updating property autocorrect on a view managed by: android text input

### ISSUE THREAD

**Issue by yfsx** [realm/realm-js#287]
when i add realm for android, this error displayed on my emulator : 

    error while updating property autocorrect on a view managed by: android text input

how to fix this? thanks

**Comment by alazier** [comment]
Haven't seen this before so not sure how to fix. What steps did you take to add Realm to your project? If you remove Realm does the issue go away?

**Comment by yfsx** [comment]
i did exactly from https://realm.io/docs/react-native/latest/

of course it's gone, but i can't remove it since my ios version using the same code, it was impossible to remove it

**Comment by alazier** [comment]
Can you share your project or reproduce the issue in a new project?

**Comment by yfsx** [comment]
its really strange that when i do "debug in chrome", it work flawlessly

**Comment by alazier** [comment]
That is strange. Sounds like a packager error or stale build artifacts. Might be worth killing/restarting the packager, restarting the emulator, and building clean to see if that makes a difference.

**Comment by alazier** [comment]
Any luck getting this working?

**Comment by jialiu54321** [comment]
got the same error without using realm.......all i did was adding the 'autoCorrect' to a textInput view and I got this error
