### ISSUE TITLE
'React/RCTBridge+Private.h' file not found. with iOS archive build.

### ISSUE THREAD

**Issue by yuehue** [realm/realm-js#2872]
## Goals

I'm trying to archive iOS release build with react native. 

Because of the banning of UIWebView usage. I'm forced to upgrade from RN 0.59.x to RN 0.6+ that comes with Pod auto linking.
 -  I followed the diff from : https://react-native-community.github.io/upgrade-helper/?from=0.59.9&to=0.61.5 
 - rm -rf node_modules
 - clear Pods directory
 - yarn install whole new dependencies.
 - pod install 

Everything seem good. 

- Run on iOS simulator ... checked , 
- Android simulator ... checked.
- Android build with release variant ... checked.   

But when I tried to build release and archive to app store. I got this error

'React/RCTBridge+Private.h' file not found.

## Expected Results
Build with no error.

## Actual Results
Fail with error message :'React/RCTBridge+Private.h' file not found.  in file **RealmReact.mm** target RealmReact.
It works fine on Android and also run on iOS simulator with Debug build. But failed with release build (archive)

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.4
- Node 10.15.3, React Native: 0.61.5
- Client OS & Version: ? XCode 11.4.1, CocoaPods 1.9.1
- Which debugger for React Native: ?/None

**Comment by yuehue** [comment]
Here is my current Podfile

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!
	
target 'MyTarget' do
    pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
    pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
    pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
    pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
    pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
    pod 'RealmJS', :path => '../node_modules/realm'
    use_native_modules!
  
end

```

**Comment by yuehue** [comment]
I tried remove use_frameworks! from pod file and it compiled with no error. But got error "Missing realm constructor. Did you run "pod install" "  instead

**Comment by steffenagger** [comment]
[Issue 2872](https://github.com/realm/realm-js/issues/2872)

Upgrading RN is quite the manual task, and tons of things can go wrong (especially from < 0.60 to >= 0.60) - so just checking:

1. When archiving, are you using the `.xcodeproj` file? If so, use the `.xcworkspace` instead.
2. Is `'MyTarget'` your project target in xcode? (I'm curious as I think most boilerplates uses the project name, but then again you should be seeing errors during pod install if it didn't exist..)
3. When clearing `node_modules` & `ios/Pods` directories, did you also remove `package-lock.json`/`yarn.lock` & `Podfile.lock` to ensure new versions?
4. If you can build, but still get the latest error, it sounds like you still have native modules (manually) linked, while the codebase is now referencing newer versions. If it's at all a solution, the easiest way could be to create a whole new RN project, and then migrate your code (use the same name to keep bundle identifier etc.)

**Comment by kneth** [comment]
@yuehue Did https://github.com/realm/realm-js/issues/2872#issuecomment-629144788 solve your issue?

**Comment by yuehue** [comment]
@kneth I ended up with create new react native project and move my source there and everything just works. It took some time but I found that it actually faster and much less frustrating than finding the cause of this error.

**Comment by kneth** [comment]
@yuehue I am happy to hear that you got it to work. Updating RN projects can unfortunately be diffucult.
