### ISSUE TITLE
Can the old version still be used?

### ISSUE THREAD

**Issue by fadeli1** [realm/realm-js#2876]
npm install relam@2.21.1
npm ERR! code E404
npm ERR! 404 Not Found: relam@2.21.1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lzz\AppData\Roaming\npm-cache\_logs\2020-05-13T10_45_03_508Z-debug.log

**Comment by kneth** [comment]
@fadeli1 

First, v2.21.1 is more than 1.5 years old, and in general we don't provide support for older version.

Second, I have tried to create a simple node.js project, and I can instal v2.21.1. 

I close the issue, and if you are still experience it, please either reopen or create a new issue.

**Comment by fadeli1** [comment]
@kneth 
Thanks, solved
