### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by SalmanGhumsani** [realm/realm-js#2878]
I am trying to run the application with realmjs but this error I am facing, I am searching this from the last 2days but no luck please help.

```
Using Node.js v14.2.0
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '/Users/salman/Documents/Bitbucket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

![Screenshot 2020-05-14 at 4 31 38 PM](https://user-images.githubusercontent.com/25687810/81927306-0ddde100-9601-11ea-9116-a51a70ef9442.png)
![Screenshot 2020-05-14 at 4 35 18 PM](https://user-images.githubusercontent.com/25687810/81927314-1209fe80-9601-11ea-8684-73e75252ae9a.png)

**Comment by Niraljain9** [comment]
Going through same issue

**Comment by kneth** [comment]
@SalmanGhumsani Please fill out the issue template (Realm JS version, etc.). 

Does your folder has a space in the name (or is `Users/salman/Documents/Bitbucket` only partially the path)?

**Comment by kneth** [comment]
> Please fill out the issue template (Realm JS version, etc.).
> Does your folder has a space in the name (or is Users/salman/Documents/Bitbucket only partially the path)?

@SalmanGhumsani Have you been able to resolve the issue?

**Comment by SalmanGhumsani** [comment]
@kneth I have resolved by changing the directory(folder)

**Comment by kneth** [comment]
Great to hear. I believe a general fix is relatively easy and I will try to get to it after my vacation.

**Comment by kneth** [comment]
Fixed by https://github.com/realm/realm-js/pull/3188
