### ISSUE TITLE
Upgrading from 4.0.0-beta.0

### ISSUE THREAD

**Issue by sadikyalcin** [realm/realm-js#2879]
I'm trying to upgrade the package from 4.0.0-beta.0 to 5.0.5 but running into "Realm at path '.../Documents.default.realm' already opened on current thread with different schema" error on iOS and white screen of death on Android.

<img width="432" alt="Screenshot 2020-05-14 at 12 45 34" src="https://user-images.githubusercontent.com/8109619/81930685-d5c6a600-95e0-11ea-8f6c-8df34b848af5.png">

Is there upgrading steps I need to take that I'm not aware of?

## Expected Results

The app should run normally.

## Actual Results

Crash on launch.

## Steps to Reproduce

- Update realm from v4 to v5
- Run the application

## Code Sample

Example Schema:

    export const HomeSchema = {
        name: 'Home',
        primaryKey: 'nid',
        properties: {
            nid: {
            type: 'int',
            indexed: true,
        },
        title: 'string',
        body: 'string',
        },
    };

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.5
- Node or React Native: 0.61.5
- Client OS & Version: iOS v11+ onwards, Android 9+
- Which debugger for React Native: None

**Comment by kneth** [comment]
@sadikyalcin What should have been v4.0.0 was delayed for different reasons and shifting priorities, and we have decided to skip the 4.x series. Instead it will become v6.0.0, and v6.0.0-beta.1 is already available. I suggest that you upgrade to that version, and we plan to release v6.0.0 soon.

v5.0.5 (and the 3.x series) is using Realm file format v9, while v4.0.0-beta.0 and upcoming 6.x series are using Realm file format v10. While it is possible to upgrade from file format v9 to v10, it is not possible to downgrade. The error you observe is a consequence of that.

I am sorry that we haven't communicated skipping v4.x more clearly.
