### ISSUE TITLE
Cannot install realm v3.6.5 npm package

### ISSUE THREAD

**Issue by samparhizkar** [realm/realm-js#2880]
## Goals
Trying to install Realm v3.6.5 via NPM or Yarn in a react native project

## Actual Results
I was not able to finish npm install or yarn install command. However the latest 5.0.3 realm installs without any issues. Here's the stacktrace

> yarn install v1.22.4
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> [4/4] 🔨  Building fresh packages...
> [7/8] ⠠ realm
> [2/8] ⠠ fsevents
> [-/8] ⠠ waiting...
> [-/8] ⠠ waiting...
> error /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm: Command failed.
> Exit code: 1
> Command: node-pre-gyp install --fallback-to-build
> Arguments: 
> Directory: /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm
> Output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.13.0
> node-pre-gyp info using node@12.16.2 | darwin | x64
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> node-pre-gyp info check checked for "/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node" (not found)
> node-pre-gyp http GET https://static.realm.io/node-pre-gyp/3.6.5/realm-v3.6.5-node-v72-darwin-x64.tar.gz
> node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/3.6.5/realm-v3.6.5-node-v72-darwin-x64.tar.gz
> node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/3.6.5/realm-v3.6.5-node-v72-darwin-x64.tar.gz 
> node-pre-gyp WARN Pre-built binaries not found for realm@3.6.5 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/3.6.5/realm-v3.6.5-node-v72-darwin-x64.tar.gz 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@5.1.0
> gyp info using node@12.16.2 | darwin | x64
> gyp info ok 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@5.1.0
> gyp info using node@12.16.2 | darwin | x64
> gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
> gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> gyp info spawn args [
> gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> gyp info ok 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@5.1.0
> gyp info using node@12.16.2 | darwin | x64
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   TOUCH Release/obj.target/OpenSSL.stamp
>   ACTION binding_gyp_vendored_realm_target_download_realm /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/vendor/realm-mac-x64
> Resolved requirements: {
>   SYNC_SERVER_FOLDER: 'sync',
>   SYNC_ARCHIVE: 'realm-sync-node-cocoa-4.9.5.tar.gz',
>   SYNC_ARCHIVE_ROOT: 'realm-sync-node-cocoa-4.9.5'
> }
> Resolved options: { platform: 'mac', sync: true, arch: 'x64' }
> No lockfile found at the target, proceeding.
> Download url: https://static.realm.io/downloads/sync/realm-sync-node-cocoa-4.9.5.tar.gz
> Downloading realm-sync-node-cocoa-4.9.5.tar.gz
> Extracting realm-sync-node-cocoa-4.9.5.tar.gz => /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/vendor/realm-mac-x64
> Success
>   TOUCH Release/obj.target/vendored-realm.stamp
>   TOUCH Release/obj.target/realm-core.stamp
>   TOUCH Release/obj.target/realm-sync.stamp
>   CXX(target) Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/collection_notifications.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/index_set.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/list.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/object.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/object_schema.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/object_store.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/placeholder.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/results.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/schema.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/shared_realm.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/thread_safe_reference.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_change_builder.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/collection_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/list_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/object_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/primitive_list_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/realm_coordinator.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/results_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/transact_log_handler.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/weak_realm_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/util/uuid.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/apple/external_commit_helper.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/impl/apple/keychain_helper.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/apple/network_reachability_observer.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/apple/system_configuration.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/server/adapter.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/server/admin_realm.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/server/global_notifier.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/sync_file.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/sync_metadata.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/impl/work_queue.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/partial_sync.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/async_open_task.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_config.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_manager.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_session.o
>   CXX(target) Release/obj.target/object-store/src/object-store/src/sync/sync_user.o
>   LIBTOOL-STATIC Release/object-store.a
>   CXX(target) Release/obj.target/realm/src/js_realm.o
>   CXX(target) Release/obj.target/realm/src/node/node_init.o
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:21:
> In file included from ../src/node/node_string.hpp:21:
> ../src/node/node_types.hpp:52:42: error: no type named 'NamedPropertyGetterCallback' in namespace 'v8'; did you mean 'IndexPropertyGetterCallback'?
>     using StringPropertyGetterCallback = v8::NamedPropertyGetterCallback;
>                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                          IndexPropertyGetterCallback
> ../src/node/node_types.hpp:50:11: note: 'IndexPropertyGetterCallback' declared here
>     using IndexPropertyGetterCallback = Nan::IndexGetterCallback;
>           ^
> ../src/node/node_types.hpp:53:42: error: no type named 'NamedPropertySetterCallback' in namespace 'v8'; did you mean 'IndexPropertySetterCallback'?
>     using StringPropertySetterCallback = v8::NamedPropertySetterCallback;
>                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                          IndexPropertySetterCallback
> ../src/node/node_types.hpp:51:11: note: 'IndexPropertySetterCallback' declared here
>     using IndexPropertySetterCallback = Nan::IndexSetterCallback;
>           ^
> ../src/node/node_types.hpp:54:50: error: no type named 'NamedPropertyEnumeratorCallback' in namespace 'v8'; did you mean 'IndexedPropertyEnumeratorCallback'?
>     using StringPropertyEnumeratorCallback = v8::NamedPropertyEnumeratorCallback;
>                                              ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                  IndexedPropertyEnumeratorCallback
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:5966:16: note: 'IndexedPropertyEnumeratorCallback' declared here
> typedef void (*IndexedPropertyEnumeratorCallback)(
>                ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:21:
> ../src/node/node_string.hpp:51:32: error: too few arguments to function call, single argument 'isolate' was not specified
>     m_str.resize(s->Utf8Length());
>                  ~~~~~~~~~~~~~ ^
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2818:3: note: 'Utf8Length' declared here
>   int Utf8Length(Isolate* isolate) const;
>   ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:21:
> ../src/node/node_string.hpp:53:18: error: cannot initialize a parameter of type 'v8::Isolate *' with an rvalue of type 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'char *')
>     s->WriteUtf8(&m_str[0], m_str.size(), 0, flags);
>                  ^~~~~~~~~
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2878:26: note: passing argument to parameter 'isolate' here
>   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
>                          ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:24:
> ../src/node/node_object.hpp:33:57: error: no type named 'ExternalOneByteStringResourceImpl' in namespace 'v8'; did you mean 'Nan::ExternalOneByteStringResource'?
>         node_key = v8::String::NewExternal(isolate, new v8::ExternalOneByteStringResourceImpl(key.data(), key.size()));
>                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                         Nan::ExternalOneByteStringResource
> ../../nan/nan.h:193:5: note: 'Nan::ExternalOneByteStringResource' declared here
>     ExternalOneByteStringResource;
>     ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:24:
> ../src/node/node_object.hpp:33:61: error: allocating an object of abstract class type 'Nan::ExternalOneByteStringResource' (aka 'v8::String::ExternalOneByteStringResource')
>         node_key = v8::String::NewExternal(isolate, new v8::ExternalOneByteStringResourceImpl(key.data(), key.size()));
>                                                             ^
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2994:25: note: unimplemented pure virtual method 'data' in 'ExternalOneByteStringResource'
>     virtual const char* data() const = 0;
>                         ^
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2996:20: note: unimplemented pure virtual method 'length' in 'ExternalOneByteStringResource'
>     virtual size_t length() const = 0;
>                    ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:24:
> ../src/node/node_object.hpp:108:40: error: no matching member function for call to 'ToString'
>         names.push_back(array->Get(i)->ToString());
>                         ~~~~~~~~~~~~~~~^~~~~~~~
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2668:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
>   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
>                                            ^
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2684:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
>                 Local<String> ToString(Isolate* isolate) const);
>                               ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:25:
> ../src/node/node_function.hpp:41:19: error: no member named 'GetCallingContext' in 'v8::Isolate'; did you mean 'GetCurrentContext'?
>     if (!isolate->GetCallingContext().IsEmpty()) {
>                   ^~~~~~~~~~~~~~~~~
>                   GetCurrentContext
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:8273:18: note: 'GetCurrentContext' declared here
>   Local<Context> GetCurrentContext();
>                  ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:26:
> ../src/node/node_value.hpp:152:19: error: no matching member function for call to 'ToString'
>     return value->ToString();
>            ~~~~~~~^~~~~~~~
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2668:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
>   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
>                                            ^
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2684:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
>                 Local<String> ToString(Isolate* isolate) const);
>                               ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:29:
> ../src/node/node_class.hpp:191:23: error: no member named 'SetNamedPropertyHandler' in 'v8::ObjectTemplate'; did you mean 'SetIndexedPropertyHandler'?
>         instance_tpl->SetNamedPropertyHandler(string_accessor.getter ? string_accessor.getter : get_nonexistent_property, set_property, 0, 0, string_accessor.enumerator);
>                       ^~~~~~~~~~~~~~~~~~~~~~~
>                       SetIndexedPropertyHandler
> /Users/ronniechatterjee/Library/Caches/node-gyp/12.16.2/include/node/v8.h:6501:8: note: 'SetIndexedPropertyHandler' declared here
>   void SetIndexedPropertyHandler(
>        ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:29:
> In file included from ../src/node/node_class.hpp:23:
> ../src/js_class.hpp:92:17: error: no type named 'StringPropertyGetterCallback' in 'realm::node::Types'
>     typename T::StringPropertyGetterCallback getter;
>     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/node/node_class.hpp:368:16: note: in instantiation of template class 'realm::js::StringPropertyType<realm::node::Types>' requested here
> template<node::StringPropertyType::GetterType F>
>                ^
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:29:
> In file included from ../src/node/node_class.hpp:23:
> ../src/js_class.hpp:93:17: error: no type named 'StringPropertySetterCallback' in 'realm::node::Types'
>     typename T::StringPropertySetterCallback setter;
>     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ../src/node/node_init.cpp:19:
> In file included from ../src/node/node_init.hpp:29:
> ../src/node/node_class.hpp:373:10: error: called object type 'int' is not a function or function pointer
>         F(isolate, info.This(), property, return_value);
>         ~^
> 14 errors generated.
> make: *** [Release/obj.target/realm/src/node/node_init.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Darwin 19.4.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node" "--module_name=realm" "--module_path=/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/compiled/node-v72_darwin_x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm
> gyp ERR! node -v v12.16.2
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node --module_name=realm --module_path=/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/compiled/node-v72_darwin_x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Darwin 19.4.0
> node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /Users/ronniechatterjee/Developer/chinook/chinook-app/node_modules/realm
> node-pre-gyp ERR! node -v v12.16.2
> node-pre-gyp ERR! node-pre-gyp -v v0.13.0
> node-pre-gyp ERR! not ok 
> 

## Steps to Reproduce
Add realm v.3.6.5 to package.json file of a react native project and try to run npm install or yarn install command.

## Version of Realm and Tooling

- Realm JS SDK Version: 3.6.5
- Node or React Native: Node v12.16.2 - React native v61.5
- Client OS & Version: macOS Catalina 10.15.4
- Which debugger for React Native: none

**Comment by bmunkholm** [comment]
Node.12 is not supported by realm-js 3.6.5. So you will have to either downgrade node or use the new realm-js 5 or 6.
