### ISSUE TITLE
Realm v6.0.0 - old entires lost their order and new entries being added at random

### ISSUE THREAD

**Issue by RosenTomov** [realm/realm-js#2885]
I've recently update to Realm studio 3.11.0 and Realm 6.0.0, it seems that the order of the items in my DB got all mixed up. Adding new items seems to be at random (places them randomly, instead of as last item).

Edit:
Just to add, when I updated to 6.0.0, I got "badchangeset" (or similar can't remember the exact wording) inside realm studio, for the opened realm.

## Goals
Be able to keep the order the items, that are being added.

## Actual Results
Items seem to be added at random.

## Steps to Reproduce
Connect to a realm and add a few entries.

## Code Sample

**I can't reproduce it on a new test realm, but it happens on our development one.**

package.json
```
{
  "name": "testproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "realm": "^6.0.0"
  }
}

```

index.js
```
const Realm = require('realm');

const realmUsername = 'Username';
const realmPassword = 'Password';
const realmServerURL = 'Realm url without https:// or realms://';

const testSchema = {
    name: 'Test',
    properties: {
        id: 'string',
        test: 'string?',
    }
};

const generateGuid = () => {
    const s4 = () => {
        return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
    }

    return `${s4() + s4()}-${s4()}-${s4()}-${s4()}-${s4()}${s4()}${s4()}`;
};


(async () => {
    const currentCredentials = Realm.Sync.Credentials.usernamePassword(
        realmUsername,
        realmPassword
    );

    const user = await Realm.Sync.User.login(
        `https://${realmServerURL}`,
        currentCredentials
    );

    const databaseOptions = {
        schema: [testSchema],
        sync: {
            url: `realms://${realmServerURL}/test`,
            user
        }
    };

    const realm = await Realm.open(databaseOptions);

    realm.write(() => {
        realm.create('Test', {
            id: generateGuid(),
            test: '1',
        });

        realm.create('Test', {
            id: generateGuid(),
            test: '2',
        });

        realm.create('Test', {
            id: generateGuid(),
            test: '3',
        });
    });

    realm.objects('Test').forEach(f => {
        console.log(f.test);
    })

    console.log('End');
})();

```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.0
- Node or React Native: Node 12.16.3
- Client OS & Version: Windows 10 Pro 64bit
- Which debugger for React Native: None

**Comment by RosenTomov** [comment]
Running a `forEach(f => realm.write(() => create))` just for testing, also doesn't keep the order.

And adding manually:

![realm-problem](https://user-images.githubusercontent.com/32323783/82323313-8d442980-99e0-11ea-998d-730040a4aace.gif)

**Comment by ianpward** [comment]
@RosenTomov there is no guarantee of order in tables. If you want to maintain order you need to use a RealmList

**Comment by kraenhansen** [comment]
Either `RealmList` or sorting on a property, like a `createdAt` date.

**Comment by RosenTomov** [comment]
Ok, I just never had that issue before 6.0.0, that's why I was wondering.
