### ISSUE TITLE
Error: illegal operation on a directory at openLocalRealm

### ISSUE THREAD

**Issue by trickyc0d3r** [realm/realm-js#2887]
## Goals

Trying to get set data to realm-db in main process of electron and then forward data from db to render process

## Expected Results

Data recieved in render process on production build

## Actual Results
No data recieved in render process on production build. No access to realm in at all.

## Steps to Reproduce

define models in main process of electron app -> call getter function from render process via ipcRenderer to ipcMain -> call back data from db to ipcRenderer.

another one try -> define realm schema in render process -> try to get access to it.

## Code Sample

`const Account_Schema_Name = 'Account'

const AccountDatabaseOpt = {
    path: 'account.realm',
    schema: [AccountSchema],
    schemaVersion: 0
};

export const GetAccountData = () =>
    new Promise((resolve, reject) => {
        const realm = new Realm(AccountDatabaseOpt);
        resolve(realm.objects(Account_Schema_Name)[0]);
        return realm.close();
    });

export const SetAccountData = (data: any) =>
    new Promise((resolve, reject) => {
        const realm = new Realm(AccountDatabaseOpt);
        let accData: any = realm.objects(Account_Schema_Name)[0];
        realm.write((): any =>
            !accData
                ? realm.create(Account_Schema_Name, data)
                : Object.keys(data).map((i): any => (accData[i] = data[i]))
        );
        resolve(true);
        return realm.close();
    });`
`import { GetAccountData, SetAccountData } from "../../models/qrLinkModel";

console.log('*************', GetAccountData())`

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.5
- Node or React Native: 
- Client OS & Version: ElectronJS v.9.0.0-beta18 & MacOS Cathalina
- Which debugger for React Native: react-debugger

**Comment by rashvaz** [comment]
@trickyc0d3r  did you solve this?

**Comment by trickyc0d3r** [comment]
Yeap. Just deleted this shit and thats it

**Comment by vazra** [comment]
@trickyc0d3r  😄 😄 

@rashvaz  it may be the issue with permission, please refer my comment at https://github.com/realm/realm-js/issues/818#issuecomment-645537228 , it may be the same issue.

**Comment by KidsBen7** [comment]
Did you solve this, everything work fine until i run it on production ...
