### ISSUE TITLE
realm.node is not a win32 application

### ISSUE THREAD

**Issue by trickyc0d3r** [realm/realm-js#2888]
after bundle electron app to mproduction build for windows I've get error listed in topic.

env:
MacOS Cathalina,
Windows 10 Pro,
ElectronJS 9.0.0
realm-js 5.0.5

**Comment by trickyc0d3r** [comment]
up!

**Comment by kneth** [comment]
We currently don't prebuild from Electron 9 (see https://github.com/realm/realm-js/blob/master/Jenkinsfile#L13). Is it possible for you to use Electron 8?

**Comment by trickyc0d3r** [comment]
Yes I guess. But will it help to reach the goal?

**Comment by kneth** [comment]
[Realm Studio](https://github.com/realm/realm-studio) is an example of an Electron app using Realm JavaScript. It works on MacOS, Linux and Windows.
