### ISSUE TITLE
not working on real device while working in emulator

### ISSUE THREAD

**Issue by mertbuldur** [realm/realm-js#2892]
hello I am using realm database in my react native project.
I can't get any response when I compile and throw it to the real device when everything works smoothly in the emulator and the devices I connect with adb.

**Comment by bmunkholm** [comment]
@mertbuldur Could you please fill out the issue template and be more specific as to what's working and what's not? In particular how we can reproduce your issue?

**Comment by mertbuldur** [comment]
I apologize for my bad English.
While my app is running on the emulator, it doesn't even pull data on the real device.

**Comment by bmunkholm** [comment]
There is nothing wrong with your english. It's just that you have to describe your problem and how we can reproduce the problem in much greater details if we should have a chance to help you.
When you create a new issue, there is a [template](https://github.com/realm/realm-js/issues/new) you must fill out.

**Comment by bmunkholm** [comment]
Closing due to no response. Please reopen if you get more information.
