### ISSUE TITLE
RealmJS PhaseScriptExecution cannot escape the folder/file path

### ISSUE THREAD

**Issue by csdal** [realm/realm-js#2910]
## Goals
`npx react-native run-ios` must successfully run without this error: `PhaseScriptExecution failed with a nonzero exit code`

## Actual Results

```
Using Node.js v12.16.1
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/Users/username/Documents/React'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Command PhaseScriptExecution failed with a nonzero exit code
```

## Steps to Reproduce

On Mac, create folders that contain space, for example:
```
/Users/username/Document/React Native Projects/RealmJS Test/
```
I also have another folder:
```
/Users/username/Document/React/
```
In the `RealmJS Test` folder, I created a React Native project and installed realm.
```
npx react-native init TestRealm
cd TestReal
npm install --save realm
cd ios && pod install && cd ..
npx react-native run-ios
```
## Version of Realm and Tooling

- Realm JS SDK Version:  6.0.0
- Node or React Native: 13.13.0 
- Client OS & Version: iOS

## Solution
I rename the folders as the followings:
```
/Users/username/Document/ReactNativeProjects/RealmJSTest/
```
It solved.

**Comment by kraenhansen** [comment]
Thanks for reporting this!

**Comment by kneth** [comment]
From v10.3.0 we distribute binary files within the `npm` package, and no download is done during building.
