### ISSUE TITLE
Pre-built binary for Android.

### ISSUE THREAD

**Issue by jmartindivmedianet** [realm/realm-js#2913]
I'm new to realm... and to coding for Android.  I'm generating androidjs apk's on my Windows machine and installing them on an Android tablet.  
I've at least learned that I probably need something in addition to **node_modules/realm/compiled/node-v64_win32_x64/realm.node** in my project to support Android when I push to the tablet.  I need help understanding how to get a pre-built binary for realm-js Android.  Thanks a lot.

**Comment by bmunkholm** [comment]
Hi @jmartindivmedianet 
Welcome to Realm .. and Android!
Allow me to initially redirect you to the right place. This repo is actually only for bug reports or feature requests. So I would have to ask you to post the question on StackOverflow instead as that's a better place for general questions.
Thanks!

**Comment by jmartindivmedianet** [comment]
Thanks so much for your polite reply.  I see newbies get beat up a lot for asking stupid questions, so I appreciate your kindness!

**Comment by bmunkholm** [comment]
Yeah, so many unknown conventions and expectations. No questions are stupid, and StackOverflow may be a bit harsh at first, but you will learn to ask really good questions :-) Do read their guide on how to do that - it's quite good!
