### ISSUE TITLE
pending on running custom scripts

### ISSUE THREAD

**Issue by magicismight** [realm/realm-js#293]
Installed Realm on `react-native@0.20.0`.
But i can\`t get it running on a simulator, It always pendding on `running custom scripts` stage.

**Comment by appden** [comment]
Please try selecting the "Report Navigator" in Xcode (see screenshot below) then selecting the build task while it's stuck and pasting in the script output.

<img width="260" alt="screen shot 2016-03-01 at 8 09 39 am" src="https://cloud.githubusercontent.com/assets/70904/13433063/18f4f6fa-df85-11e5-8c19-44c51b839f91.png">

React Native sometimes takes a _really_ long time running the `react-native-xcode.sh` script during the "Bundle React Native code and images" build phase.

**Comment by magicismight** [comment]
Solved.
It`s pending on downloading dependency.
![qq 20160302091025](https://cloud.githubusercontent.com/assets/7693239/13447463/a1c41f7a-e056-11e5-975e-2c0de38c122d.png)
It takes about an hour to download this.
The network in China is really shit!

**Comment by appden** [comment]
Oh right, I forgot about that possibility. Sorry about that!

**Comment by StefanWallin** [comment]
Is there a way to download and install/place the core package with some other tool to avoid internet crippling the install of realm?

**Comment by alazier** [comment]
@StefanWallin right now it seems we unpack the core tarball from the tmpdir every time we build. If the tarball is in the temp directory it shouldn't try to redownload it. 

I just made a pr to just reuse the unpacked core directory if it is the correct version. With this change once unpacked it shouldn't ever download a new version unless we bump the version or you delete the core symlink or directory. You can start using this now by replacing the `scripts/download-core.sh` file with this version https://github.com/realm/realm-js/blob/al-download-core/scripts/download-core.sh
