### ISSUE TITLE
query is not async

### ISSUE THREAD

**Issue by narychen** [realm/realm-js#294]
let hondas = realm.objects('Car').filtered('make = "Honda"');
It would be blocked when the dataset is large or the query perform a complicated search because javascript is single-threaded.

**Comment by timanglade** [comment]
Hey thanks @narychen. This is something we’ve been working on, and that consider very urgent. We are tracking it in #165

**Comment by Starscream27** [comment]
What's the status of this ? We're seriously considering realm as our main client database on an electron app but the fact that all the sdk methods return objects directly and not promises make me doubt the integration with a non blocking environment such as node.js. 

Although `open` returns a promise, almost no other method does. I can't find any documentation on realm "asynchronounsness". Any ressource to help me out here ?
