### ISSUE TITLE
Support case insensitive queries

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#295]
Requested by a user. We should probably come up with a syntax better than the [c] used in predicates. Thoughts @bdash @kristiandupont @jpsim @cmelchior ?

**Comment by alazier** [comment]
http://stackoverflow.com/questions/35724572/realm-for-react-native-case-insensitive-search/35727721#35727721

**Comment by edmofro** [comment]
Love your work - will love it even more with this issue cleaned up :-)

**Comment by alazier** [comment]
This was just shipped in v0.11.0.

**Comment by edmofro** [comment]
Could you please add to the docs?

**Comment by alazier** [comment]
@edmofro will do. Heres is what will be added:

> At the moment only a subset of the NSPredicate syntax is supported in the query language. Basic comparison operators `==`, `!=`, `>`, `>=`, `<`, and `<=` are supported for numeric properties. `==`, `BEGINSWITH`, `ENDSWITH`, and `CONTAINS` are supported for string properties. String comparisons can be made case insensitive by appending `[c]` to the operator: `==[c]`, `BEGINSWITH[c]` etc.
