### ISSUE TITLE
Can't perform install of Realm 5.0.5 via yarn

### ISSUE THREAD

**Issue by isnifer** [realm/realm-js#2961]
Hello, I'm using Microsoft AppCenter to Build my app.
Last hour I can't install deps of my app which includes Realm 5.0.5.

It tries to install package "node-pre-gyp" which is watching to:
```
"node-pre-gyp": "git+https://github.com/kneth/node-pre-gyp.git#add-node-14.0.0",
```

See — https://github.com/realm/realm-js/blob/v5.0.5/package.json#L93.

First of all, I can't believe that this is possible for package like Realm to watch on some fork instead of npm package.

## Goals

Install Realm 5.0.5

## Expected Results

Successful Install

## Actual Results

```
error Couldn't find match for "09b0c262cf9ba2cb28c8a29f6bb5882c8c160cdf" in "refs/heads/binding-fixes,refs/heads/master,refs/heads/simplify-appveyor,refs/heads/support-symlinks,refs/heads/tokenize-module-name,refs/heads/v0.7.x,refs/tags/v0.1.0,refs/tags/v0.1.1,refs/tags/v0.1.2,refs/tags/v0.1.3,refs/tags/v0.1.4,refs/tags/v0.1.5,refs/tags/v0.1.6,refs/tags/v0.1.7,refs/tags/v0.1.8,refs/tags/v0.1.9,refs/tags/v0.10.0,refs/tags/v0.10.1,refs/tags/v0.10.1-dev.1,refs/tags/v0.10.2,refs/tags/v0.11.0,refs/tags/v0.12.0,refs/tags/v0.2.0,refs/tags/v0.2.1,refs/tags/v0.2.2,refs/tags/v0.2.3,refs/tags/v0.2.4,refs/tags/v0.2.5,refs/tags/v0.2.6,refs/tags/v0.3.0,refs/tags/v0.3.1,refs/tags/v0.4.0,refs/tags/v0.4.1,refs/tags/v0.4.2,refs/tags/v0.5.0,refs/tags/v0.5.0-alpha,refs/tags/v0.5.1,refs/tags/v0.5.10,refs/tags/v0.5.11,refs/tags/v0.5.12,refs/tags/v0.5.13,refs/tags/v0.5.14,refs/tags/v0.5.15,refs/tags/v0.5.16,refs/tags/v0.5.17,refs/tags/v0.5.18,refs/tags/v0.5.19,refs/tags/v0.5.2,refs/tags/v0.5.20,refs/tags/v0.5.21,refs/tags/v0.5.22,r...
```

## Steps to Reproduce

I think MS AppCenter is installing node_modules without any cache.
So you need to clean yarn/npm cache and then perform install.

## Version of Realm and Tooling

- Realm JS SDK Version: **5.0.5**
- Node or React Native: **React-Native**
- Client OS & Version: MacOS
- Which debugger for React Native: None

**Comment by kyleamazza** [comment]
Seeing the same issue, but for npm as well, both for installation on a personal machine, as well as on GitLab CI. Running into the error:
```bash
npm ERR! code 1
npm ERR! Command failed: git checkout add-node-14.0.0
npm ERR! error: pathspec 'add-node-14.0.0' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2020-06-11T21_28_01_676Z-debug.log
```
when running `npm install realm@<version>` (tested with versions 3.6.5, 5.0.5, 10.0.0-beta.6)

**Comment by kneth** [comment]
> It looks like realm@6.0.2 and above have node-pre-gyp@^0.15.0, but realm@6.0.1, 6.0.0, and 5.0.5 point to git+https://github.com/kneth/node-pre-gyp.git#add-node-14.0.0, which is a branch that seems to no longer exist on that repository.

I have restored the branch. Cleaning up is dangerous 😄

**Comment by lucasluca** [comment]
Same problem happening in the same day and same month, one year later. Could u restore the branch again @kneth

**Comment by kneth** [comment]
@lucasluca The branch is still active, and I am not able to reproduce the issue using node 12 and 14. Please note that Realm JavaScript v5.0.5 is not expected to work with node 15 and later.
