### ISSUE TITLE
Realm Web: Implement missing credentials (Facebook, Google, JWT, Apple, Functions)

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#2963]
Implement more credentials for authentication providers:
  * [ ] Facebook
  * [ ] Google
  * [ ] Custom JWT
  * [ ] Apple Sign In
  * [ ] Functions

**Comment by djodjo02130** [comment]
HI ! @kraenhansen Do you know when this features, will be done ? Or do you have any calendar for phase 2 ? Thanks
