### ISSUE TITLE
applyPermissions gives public access to everyone if userId does not exist

### ISSUE THREAD

**Issue by and-dutra** [realm/realm-js#2978]
## Goals

Giver permission to a user

## Expected Results

Throw an error if user does not exist

## Actual Results
The desired folder has public permission applied

## Steps to Reproduce
1. Create admin user
2. Create a folder
3. Try to give access to the folder using a non-existent userId

## Code Sample

```js
  const adminUser = await Realm.Sync.User.login(
    `https://${server_address}`,
    "admin",
    "admin"
  );

  const path = `realms://${server_address}/chat`;

  adminUser
    .applyPermissions({ userId: "NONEXISTENTUSER" }, "/chat", "read")
    .then((permissionChange) => {
      console.log(permissionChange);
    })
    .catch((error) => {
      console.log(error);
      // ...
    });

```
## Results of above code:
![Screen Shot 2020-06-15 at 15 57 31](https://user-images.githubusercontent.com/5191320/84695322-0ae85000-af21-11ea-8b66-0df3f30d64c1.png)
](url)

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: Node
- Client OS & Version: 12.16.1[

**Comment by kneth** [comment]
Thank you for the suggestion. Until we get it done, I suggest that you - in your app - check if the user exists.
