### ISSUE TITLE
Realm works only in debug mode

### ISSUE THREAD

**Issue by Berezhnov** [realm/realm-js#2984]
## Goals

Updated react native from 0.58 to 0.62.2. Realm : "v2.28.1" -> the latest realm (6.0.2)

## Expected Results

Apps works and all libraries updated.

## Actual Results
All libraries was updated. The app fully works in debug mode (using Chrome).

This is result of Realm.open() (or new Realm(), what is similar):
![image](https://user-images.githubusercontent.com/21060845/84884180-d1dbe700-b0aa-11ea-8daa-c6f32e6651b6.png)

But without debug mode / in release build Realm.open() or new Realm() return {} as a result:
![image](https://user-images.githubusercontent.com/21060845/84884269-f1730f80-b0aa-11ea-98c1-7faf5a005866.png)

Problems appears both on Android and iOS.

I think something wrong with Javascript engine  cause app works in debug mode with v8 engine and doesn't without debug mode. I have jsc-android package, but it affects only Android, so it is not cause of the problem. 

## Reproduce

react-native init project
npm install realm

then add in index.js:
`Realm.open({}).then(res => alert(JSON.stringify(res)));`
## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: 0.62.2, 12.16.3
- Client OS & Version: macOs catalina 10.15.3
- Which debugger for React Native: None, only standard chrome

**Comment by Berezhnov** [comment]
Found fix:
When using `Realm.open({schema : ...})`

**Comment by thuytony** [comment]
@Berezhnov I am also facing with this problem. Can you tell me more about how to fix it?

**Comment by ProfessionalAmateur** [comment]
Im also having this same issue

**Comment by ilyabreev** [comment]
Same issue here.
