### ISSUE TITLE
Prebuild for latest stable Electron is N/A, increased file size while building from source.

### ISSUE THREAD

**Issue by vazra** [realm/realm-js#2991]
I am working on an electron app which uses realm database. I've both windows and mac versions of the product. For the previous version (before using realm) I was using the latest stable release of electron in 8.x.x (it's 8.3.2 now, current stable version of electron is 9.0.4 ). But I found it difficult to rebuild realm for these versions of electron with windows as target, using `electron-builder` or `electron-rebuild`. As I was not able to find any prebuild binaries available for the latest stable version, I tried to build from source using the above tools, which didn't work well for Windows, 32 bit target. 

One thing that worked for me was to downgrade the electron version to 8.1.1. 

Is there any way for me to get realm prebuild binaries for electron9.0.4 (Win 64 &32 bit)? 

when I tried to build it myself the size of the final electron build is larger, when compared with the prebuild that is available for  electron version 8.1.1.  

Is there any place where I can look into to see which are version have prebuild binaries and for which all platforms. 

(I tried using `electron-builder install-app-deps` to rebuild for electron, which didn't work for me)

## Goals

Use realm with my electron desktop app, with latest stable version (9.0.4 or 8.3.2) for windows 32bit target. 

## Expected Results

should be able to use realm my using `npm install && electron-builder install-app-deps`

## Actual Results

prebuild was not available (or I was not able to find 🤔 ) for latest stable electron versions. 

## Steps to Reproduce

clone the repo at https://github.com/vazra/electron-react-ts-rxdb, upgrade electron version to latest stable, try rebuilding native modules for windows 32bit.

## Code Sample

a demo is available at https://github.com/vazra/electron-react-ts-rxdb

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: Electron
- Client OS & Version: 8.3.2
- Which debugger for React Native: None

**Comment by kneth** [comment]
@vazra We need to add the version to the list in https://github.com/realm/realm-js/blob/master/Jenkinsfile#L13 and verify that tests pass.

**Comment by vazra** [comment]
@kneth  thanks for the response. As of now, I see that the only version supported are `['8.1.1', '7.2.3']`. Is there any considerations while selecting these releases to build for? how and when this line will get updated? What is the process of updating the list? 

> Note: 8.1.1 was released 4 months ago, and there was 16 stable releases with security as other patches. and the latest major version is 9.x
