### ISSUE TITLE
Failed to execute 'fetch' on 'Window': member signal is not of type AbortSignal.

### ISSUE THREAD

**Issue by cameroncruz** [realm/realm-js#3005]
Hi, I'm running into issues integrating basic authentication using Realm with Electron. I believe this issue is related to https://github.com/Azure/azure-sdk-for-js/issues/5143. I noticed that in realm-js, lib/NetworkTransport.js line 46 is where global fetch is being retrieved. While avoiding global fetch is the solution azure-sdk-for-js decided to pursue, is there a short-term solution I can apply to get unblocked? Thanks.

## Goals

I want to enable email/password Login based on https://docs.mongodb.com/realm/tutorial/react-native/ for my Electron app.

## Expected Results

Calling app.logIn(creds) on a Realm.App to return a valid user.

## Actual Results

I receive the following error:
Failed to execute 'fetch' on 'Window': member signal is not of type AbortSignal.

## Steps to Reproduce

Following this tutorial https://docs.mongodb.com/realm/tutorial/react-native/ with Electron.

## Code Sample

```
app = new Realm.App(appConfig);
const creds = Realm.Credentials.emailPassword(email, password);
const newUser = await app.logIn(creds);
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm@v10.0.0-beta.6
- Node or React Native: Node
- Client OS & Version: MacOS 10.15.5
- Which debugger for React Native: None

**Comment by cameroncruz** [comment]
I built realm@v10.0.0-beta.6 from source with the following change to NetworkTransport.js lines 43-47:

```
if (!DefaultNetworkTransport.fetch) {
            // Try to get it from the global
            if (false) {
                DefaultNetworkTransport.fetch = fetch.bind(window);
            }
```

which seems to do the trick. Is there any motivation to continue trying to get global fetch?

**Comment by kraenhansen** [comment]
Are you running this code from the main or a renderer process?
If you are available, it would be great to get a repository with a minimal app reproducing this error.

**Comment by kraenhansen** [comment]
The PR has been merged, you can expect a fix for this in the upcoming v10 beta release.
