### ISSUE TITLE
Realm object constructor must not return another value

### ISSUE THREAD

**Issue by Schabaani** [realm/realm-js#3007]
## Goals
Create a simple Realm App and saving some data.

## Expected Results
After adding realm to project and config it, Saves data

## Actual Results
Realm object constructor must not return another value

## Steps to Reproduce
1. Create a new React Native project
1. add realm and lodash as dependencies
1. add below codes

## Code Sample
**SaleTX.js**

```
import _ from 'lodash'

class RealmBase {}
RealmBase.prototype.refAsArray = function(ref) {
    return _.keys(this[ref]).map(key => this[ref][key])
}
class SaleTX extends RealmBase {
	get json() {
		let result = {
			id: this.id,
			merchantId: this.merchantId,
		};

		return result;
	}
}

SaleTX.schema = {
	name: 'SaleTX',
	primaryKey: 'id',
	properties: {
		id: { type: 'string', indexed: true },
		merchantId: { type: 'string', optional: true },
	}
};

export { SaleTX };

```

**App.js**

```
import React from 'react';
import {
  View
}
import Realm from 'realm';
import { SaleTX } from './SaleTX';

class App extends React.Component {
  constructor(props) {
    super(props);
  }

componentDidMount (){
  const realm = new Realm({
    schema: [
      SaleTX,
    ],
  });

  let sale = realm.write(() => {
    realm.create('SaleTX', {
      merchantId: '54',
      id: '1'
    });
    
  });

}

  render () {
    return(
      <View />
    )
}
}

```

## Version of Realm and Tooling
* Realm JS SDK Version: 6.0.2
*  React Native: 0.62.2
* Client OS & Version: Win 10 or Mac High Sierra

**Comment by kneth** [comment]
Please see https://github.com/realm/realm-js/issues/2790

**Comment by Schabaani** [comment]
Thanks @kneth .
But [blagoev](https://github.com/realm/realm-js/issues/2790#issuecomment-609881274) said in Realm v5 we can use Inheritance. And another thing, we have an old project that uses Realm 2.25.0 then upgraded to 3.6.5, in that project all of our classes use inheritance. It is too strange.

**Comment by kneth** [comment]
@Schabaani It is indeed strange. We need to investigate a bit more.
