### ISSUE TITLE
realm v6.0.2 报错，在浏览器里debug时没问题

### ISSUE THREAD

**Issue by maruihi** [realm/realm-js#3014]
![WechatIMG158](https://user-images.githubusercontent.com/19216762/86109903-7886a580-baf7-11ea-93f9-b9fd140e2328.jpeg)
undefined is not a function(evaluating object.setPrototypeOf(Permission.prototype, realmConstructor.Object.prototype)')))

**Comment by kneth** [comment]
From the screenshot, I assume you are using React Native. But which version of RN are you using? Do you observe it on Android or iOS? Only when debugging?

**Comment by maruihi** [comment]
> From the screenshot, I assume you are using React Native. But which version of RN are you using? Do you observe it on Android or iOS? Only when debugging?
RN 0.55.4。
platform：android。
Both debug and release modes have problems。
Now I'm sure that's why the method Object.setProtoTypeOf() is not supported, Maybe because I use RN 0.55.4。

**Comment by kneth** [comment]
We have released v6.0.3. Please upgrade and tell us if you still experience the issue.

**Comment by steffenagger** [comment]
@maruihi any update on this?

**Comment by maruihi** [comment]
> We have released v6.0.3. Please upgrade and tell us if you still experience the issue.

Thanks! I replaced it for the time being Object.setProtoTypeOf (), in other ways, I'll try to upgrade to released v6.0.3 and tell you the result
