### ISSUE TITLE
Why do I have to be online for app.logIn() - how to achieve offline support

### ISSUE THREAD

**Issue by Twisterking** [realm/realm-js#3018]
So, I am new to Realms and I am trying to get a very basic ReactNative App to run, sync some data with MongoDB Realms / Atlas while being offline capable.

What completely boggles my mind is that it is nowhere mentioned on how to make the app offline capable. Do I have to handle the  `app.logIn()` completely myself while offline? How would I do that?

The mongoDB docs talk a lot about offline first, but seem to completely miss the point on how to achieve that.

## Expected Results

Make my barebones React Native app (or nodeJS dev app) offline capable.

## Actual Results

Well, I immediately get a network error.

## Steps to Reproduce

```js
async function run() {
  let user;
  const app = new Realm.App(appConfig);
  const credentials = Realm.Credentials.anonymous();

  try {
    user = await app.logIn(credentials); // completely breaks while offline
    console.log(`Logged in with the user: ${user.identity}`);
  } finally {
    console.log('END');
  }
}

run().catch(console.dir);
```

## Version of Realm and Tooling

- Realm JS SDK Version: `"realm": "^10.0.0-beta.7"`
- Node or React Native: both
- Client OS & Version: macOS 10.14.6

**Comment by kneth** [comment]
If you are offline, `app.logIn()` will fail. You need to validate the credentials, and it can only be done against MongoDB Realm Cloud (and therefore you need to be online). Once logged in, you can open your Realm. If you loose connectivity, you can continue use your Realm seamlessly. When connectivity, changes (locally and/or remotely) will flow between the mobile device and MongoDB Realm Cloud.
