### ISSUE TITLE
Cannot use 'in' operator to search for 'node' in undefined

### ISSUE THREAD

**Issue by moander** [realm/realm-js#3021]
## Goals

```js
import * as RealmWeb from 'realm-web';
```

## Actual Results

```
Uncaught TypeError: Cannot use 'in' operator to search for 'node' in undefined
    at Module.eval (bundle.es.js?06c1:274)
    at eval (bundle.es.js:1895)
    at Module../node_modules/realm-web/dist/bundle.es.js (vendor.js:4130)
    at __webpack_require__ (app.js:854)
```

 It fails because `process` exists without a `versions` child key.
```js
const isNodeProcess = typeof process === "object" && "node" in process.versions;
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm-web 0.5.0
- Node or React Native: node 12.16.1
- Client OS & Version: macos 10.15

**Comment by kraenhansen** [comment]
I just published Realm Web v0.6.0 with a fix for this.
Please upgrade and re-open if the issue persists.
