### ISSUE TITLE
writeCopyTo promise

### ISSUE THREAD

**Issue by chittasec** [realm/realm-js#3029]
Hi ,

I am trying to use writeCopyTo to create a copy and backup  to iCloud .

Questions are 
 - Is the copy created a consistent copy even if the source database is open and in use in the application?
- Is there a promise call back for the copy . So that I can copy to icloud after the local copy is completed ?

Thanks,
Chitta

**Comment by kneth** [comment]
@chittasec In principle you can call `writeCopyTo` when the database is open but in many applications, it might be better to close all instances first in order not to call `writeCopyTo` while a write transaction is in progress. 

The method `writeCopyTo` is synchronous and it will return when the write is done - no promises or callbacks.

It might be better to write a local copy first and then copy it to iCloud. If the iCloud account is full, I imagine the call to `writeCopyTo` will be failing with non-intuitive error messages (haven't tried, just guessing).

**Comment by steffenagger** [comment]
@chittasec did the above answer your questions?

**Comment by kneth** [comment]
I am closing the issue. If you have further questions, please create a new issue.
