### ISSUE TITLE
v10.0.0-beta.8: TypeError: process.versions is not an Object. (evaluating '"node" in process.versions')

### ISSUE THREAD

**Issue by ioveracker** [realm/realm-js#3045]
## Goals

Updated existing React Native app from `realm@10.0.0-beta.7` to `realm@10.0.0-beta.8` and now the app throws a TypeError on launch.

## Expected Results

TypeError should not be thrown and Realm should function normally in a React Native app.

## Actual Results

```
TypeError: process.versions is not an Object. (evaluating '"node" in process.versions')
```
Appears to be caused by the following code from `realm-network-transport`:
```
const isNodeProcess = typeof process === "object" && "node" in process.versions;
```

## Steps to Reproduce

1. Run a React Native app on Realm 10.0.0-beta.8.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.8
- Node or React Native: React Native 0.62.2 running on Node 10.15.3 (also tried 12.17.0)
- Client OS & Version: iOS 13.4.1 but probably Android too
- Which debugger for React Native: None

**Comment by Nosekim** [comment]
same here, app dont launch
Realm JS SDK Version: 10.0.0-beta.8
Node or React Native: React Native 0.62.2  and 0.63 running on Node 10.21.0

**Comment by kraenhansen** [comment]
Thanks for reporting this.

A fix for this is contained in https://github.com/realm/realm-js/pull/3001.
