### ISSUE TITLE
Unable to resolve module `./NetworkTransport` from `node_modules\realm\lib\extensions.js`

### ISSUE THREAD

**Issue by MadeByRaymond** [realm/realm-js#3070]
#
![Screenshot_20200717-004150_Lysts](https://user-images.githubusercontent.com/29353783/87733496-eb667080-c7c7-11ea-9baf-6457858003fd.jpg)

## Steps to Reproduce
Installed "realm": "^10.0.0-beta.8", Run react native with npm run android (react-native run-android). 
Loading bundle stops with this error 
`error: Error: Unable to resolve module `./NetworkTransport` from `node_modules\realm\lib\extensions.js`:

None of these files exist:
  * node_modules\realm\lib\NetworkTransport(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\realm\lib\NetworkTransport\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.8
- Node or React Native: React Native - 0.62.2
- Client OS & Version: Windows 10

**Comment by mr-raymond** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/29353783/87733567-18b31e80-c7c8-11ea-8d30-4000fdb5eb66.png)

**Comment by kneth** [comment]
@MadeByRaymond Did you upgrade from a previous version? If you did, please reset your cache and/or metro and maybe uninstall the app on the device. We removed the file `NetworkTransport.js` in v10.0.0-beta.8 and now depend on the `realm-network-transport` instead. The cache/metro might be using the previous version of `lib/extension.js`.

**Comment by MadeByRaymond** [comment]
Thanks, that helped. But now my App keeps crashing when I try to lunch

**Comment by kneth** [comment]
@MadeByRaymond Does it crash with the same error message? Can you verify that `node_modules/realm/lib/extensions.js` has line `const { DefaultNetworkTransport } = require('realm-network-transport');` and not `require('./NetworkTransport')`? Can you verify if you have `node_modules/realm-network-transport`? If you can confirm that, then it is metro, watchman or something in the RN build cache which is the issue. In my experience, RN is not expiring caches, and changes to dependencies are not always visible in the installed app.

**Comment by MadeByRaymond** [comment]
None of those are the issue. I can confirm that 
`node_modules/realm/lib/extensions.js` has line `const { DefaultNetworkTransport } = require('realm-network-transport');` and not `require('./NetworkTransport')`
And that the RN, Metro cache has been reset. 
I think it may have to do with #3069 .

**Comment by aw12051996** [comment]
application force close when in release mode even though in debug mode the application runs smoothly ?
RN 0.63
Realm ^ 6.0.4

**Comment by kneth** [comment]
We suggest that you upgrade as it has been fixed in recent versions.
