### ISSUE TITLE
Cannot access realm that has been closed

### ISSUE THREAD

**Issue by Yarkhan** [realm/realm-js#3077]
I'm not sure if this goes here or in the Jitsi repo, so I'm opening this issue in both repositories. If you guys could point me to the right direction, I'il gladly make the necessary changes and open a pull request

Realm closes when a Jitsi call starts, triggering errors where listeners have been set.

## Goals

I'm trying to integrate Jitsi alongside Realm in my app

## Expected Results

Realm shouldn't crash

## Actual Results
No useful stack

## Steps to Reproduce

Start a meeting then update a realm object. Realm closes and crashes if you try to update an object.

## Code Sample
I've isolated a reproduction case for the bug.
https://github.com/Yarkhan/android-realm-jitsi-bug

## Version of Realm and Tooling

- Realm JS SDK Version: Realm 6.0.3 (and below)
- Node or React Native: Node 14 RN 0.61.5
- Client OS & Version: Android (all)
- Which debugger for React Native: None

**Comment by Yarkhan** [comment]
Writing about the problem certainly helps, eh?
Found a workaroud. Just reopen Realm after joining a Jitsi call.

I'il leave this open, though. I really want to know why Realm closes.

**Comment by kneth** [comment]
@Yarkhan Can you reproduce it if you change the name of the Realm file to something else than `default.realm`?

**Comment by Yarkhan** [comment]
Thank you so much! I can't reproduce the case anymore setting another name to the realm file. Everything seems to be working.

**Comment by kneth** [comment]
@Yarkhan It sounds like Jitsi is using `default.realm` for some internal data store.

**Comment by jmagdada** [comment]
hi @Yarkhan how do you rename the realm file? :)

**Comment by kneth** [comment]
@jmagdada You can set `path` in the Realm configuration.

**Comment by Yarkhan** [comment]
@jmagdada, if you are also trying to integrate Jitsi, it doesn't play along with Realm even after renaming the realm file. Both libraries messes with React Native directly in some way and are incompatible with each other.

**Comment by jmagdada** [comment]
@Yarkhan yeah I still get the error even after renaming it.. may I know what workaround you have done to fix this ?

**Comment by Yarkhan** [comment]
@jmagdada No workarounds that I know of. I've been using the web version of Jitsi and will migrate to WatermelonDB eventually, since it supports both Jitsi and Web.

**Comment by jmagdada** [comment]
@Yarkhan maybe we can reopen realm once its closed. but Im not sure how to do so. Im using..

`new Realm({schema: schemas});`

do you have any idea?
