### ISSUE TITLE
Realm Sync - undefined values in new columns

### ISSUE THREAD

**Issue by RosenTomov** [realm/realm-js#3078]
## Goals & Expected Results
Be able to create and use new columns from realm cloud.

## Actual Results
![undefined](https://user-images.githubusercontent.com/32323783/87974594-f88aa480-cad2-11ea-957c-6028bfe570c1.PNG)

## Steps to Reproduce
Update schema with a new columns.

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.3
- Node or React Native:  Node 12.18.1
- Client OS & Version: Windows 10 pro 64 bit
- Which debugger for React Native: None

**Comment by kraenhansen** [comment]
I would love to help get this resolved. Your instructions on "Steps to Reproduce" are however insufficient for me to make progress. 

- What individual steps are you taking to get to this state?
- What exactly did you experience and where? (I see a screenshot from Realm Studio, but thats not mentioned in your description).
- You mention updating the schema, from where are you performing that update? (in-code via an app or via the Studio UI?).

**Comment by RosenTomov** [comment]
Sorry, I was in a hurry.

1. Adding new entries in the DB through code or manually, after updating the schema and opening the realm. This happened only to the newly added columns. 
2. Yes, the screenshot is from Realm Studio, whenever I create an entry, it always says "undefined" for the new columns and I couldn't change it, even manually from the studio. 
3. I've updated the schema through code -> updated my model -> opened sync realm.

Coming back the next day, after restarting, it seems to be working fine, so I think it might have been from the studio.
![fine](https://user-images.githubusercontent.com/32323783/88047676-a9885200-cb5a-11ea-9915-24b682b56bdf.PNG)

Feel free to close it, unless you wish to investigate this further.

**Comment by kneth** [comment]
@RosenTomov Thank you for the update. I'll close the issue, but if you experience anything like it again, don't hesitate to open a new issue.
