### ISSUE TITLE
Realm 10 Beta 9: callResetPasswordFunction() & resetPassword() functions missing promisify callbacks.

### ISSUE THREAD

**Issue by timesync** [realm/realm-js#3080]
## Goals

I'm trying to execute a password reset using a custom password reset function in Realm.

## Expected Results

I expected to have the password reset function called using the `callResetPasswordFunction()`.

## Actual Results

When executing `callResetPasswordFunction()`, the documentation dictates it be called with two arguments _and_ TypeScript dictates that the function be called with three arguments. I've tried it both ways:

`callResetPasswordFunction(email, password, [])`
`callResetPasswordFunction(email, password)`

The resulting stack trace is:

```
Error: Invalid arguments: 4 expected, but 3 supplied.
    at /home/runner/PreciousPunyTechnicians/node_modules/realm/lib/em
ail-password-auth-methods.js:44:37
    at /home/runner/PreciousPunyTechnicians/node_modules/realm/lib/ut
ils.js:33:13
    at new Promise (<anonymous>)
    at promisify (/home/runner/PreciousPunyTechnicians/node_modules/r
ealm/lib/utils.js:32:16)
    at EmailPasswordAuth.callResetPasswordFunction (/home/runner/Prec
iousPunyTechnicians/node_modules/realm/lib/email-password-auth-method
s.js:44:16)
    at /home/runner/PreciousPunyTechnicians/index.js:17:40
    at Script.runInContext (vm.js:131:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:
1153:10)
```

Even if I go in and add the callbacks, more errors arise. 

## Steps to Reproduce

1. Import Realm.
2. Create a Realm App.
3. Call `callResetPasswordFunction()`.

## Code Sample

https://repl.it/@timesync/PreciousPunyTechnicians

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node or React Native: Node

**Comment by kraenhansen** [comment]
Thanks for reporting this. It should be fixed with https://github.com/realm/realm-js/pull/3079.
