### ISSUE TITLE
How to filter by a value in a list?

### ISSUE THREAD

**Issue by BravenxX** [realm/realm-js#3087]
If I have in a schema like this:

```
FormularioSchema = {
  name: user,
  properties: {
    names: 'string?[]',
};
```

How can I get all user that have a "Jim" name in names array ?? 

Its there a query for that? I cant find a way to do it.

**Comment by kraenhansen** [comment]
You can use [the `ANY` operator](https://realm.io/docs/javascript/latest/api/tutorial-query-language.html) for this:

```
realm.objects('User').filtered('ANY name = $0', 'Jim');
```
