### ISSUE TITLE
Reflect.consturctor requires first argument be a contstructor

### ISSUE THREAD

**Issue by uendar** [realm/realm-js#3089]
I tried to update realm from 2.19.2 to last 6.0.2 and when i run and open my project i get 

_Reflect.consturctor requires first argument be a contstructor_

in differents files. What has changed and how can we fix this?

**Comment by kraenhansen** [comment]
@uendar would you please fill out the issue template? Specifically we would need to know if you're running Nose.js or React Native and if RN, if you're running with the debugger enabled.
Any source code and stack trace would also be highly appreciated.

**Comment by kneth** [comment]
I am close the issue. If you experience it again, please create a new issue with the template filled out.
