### ISSUE TITLE
NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://inspektify-home-inspection.us1a.cloud.realm.io/auth, NSErrorFailingURLKey=https://inspektify-home-inspection.us1a.cloud.realm.io/auth, _kCFStreamErro

### ISSUE THREAD

**Issue by FawadMahmood** [realm/realm-js#3094]
## Expected Results

Offline persistance go away after force close app and reopen again.

## Version of Realm and Tooling

- Realm JS SDK Version: ^6.0.3
- Node or React Native: 0.62.2
- Client OS & Version: Mac OS/Iphone
- Which debugger for React Native: Chrome/Release

**Comment by steffenagger** [comment]
@FawadMahmood could you elaborate a bit more on _Steps to Reproduce_?
Also as this is on a physical device, is this encountered when connected via Cellular data or WiFi?

**Comment by FawadMahmood** [comment]
Hello @steffenagger  Thank you so much for you response, Actually it only happen when I close app forcefully from stack and my internet is not connected,

Example : I open app with internet then even internet stop working everything works well offline, however when I close the app forcefully (Internet not connected), then I reopen without internet try to write into database, I start getting this error and loader stays.

My Code : 

When ever I open my app : 

export const startInitialConfiguration = (setUser) => async (dispatch, getState) => {
  const user = Realm.Sync.User.current;
  if(user){
    const config = user.createConfiguration({
      sync: { 
              url:`realms://${realmString}/${user.identity}/userRealm`,
              error: err => alert(JSON.stringify(err)),
              fullSynchronization: true,
            },
      newRealmFileBehavior: {
          type: "openImmediately"
      },
      existingRealmFileBehavior: {
          type: "openImmediately"
      },
      schema:[userSchema,addressSchema,agentSchema,clientSchema,inspectionScheema] // ...
    });
  

    Realm.open(config).progress((transferred, transferable) => {
      // update UI
      console.log("DATA TRANSFERED" , transferred);
      console.log("DATA TRANSFERABLE" , transferable);
      dispatch({
        type:auth.TRANSFERINFO,
        payload:{transferred:transferred,transferable:transferable}
      })
    })
    .then(realm => {
      alert("Realm Instance Loaded");
        console.log("Realm Instance Loaded");
        realmInstance = realm;
        dispatch(getInspectionDueIn24())
        if(setUser){
          console.log("WRITING USER INFORMATION" ,  {...setUser,identity:user.identity});
          dispatch({
            type:auth.AUTHENTICATED,
            payload:{...setUser,identity:user.identity}
          })
          realm.write(() => {
            realm.create(USER_SCHEEMA, {...setUser,identity:user.identity});
          });
          console.log("WRITING USER INFORMATION SUCCESS");
        }else{
          console.log("Reading User Information");
          realm.objects(USER_SCHEEMA).filtered("identity = \'" + user.identity + "\' LIMIT(1)").map((user,index)=>{
            console.log("Reading User Information",user);
            let _user={
              company:user.company ,
              email: user.email,
              hearaboutus: user.hearaboutus,
              identity: user.identity,
              name: user.name,
              phone: user.phone,
            }

            dispatch({
              type:auth.AUTHENTICATED,
              payload:{..._user,identity:user.identity}
            })
          });
        }
    })
    .catch((e) =>console.log("ERROR ON INITIAL LOAD" , e));
  }

  
  console.disableYellowBox = true;
}

Try fetch data : 

       type:inspection.LOADING24HOURS,
            payload:true
        })
        if(realmInstance){
            console.log("FETCHING 24/7 RECORD")
            let inspections = []
            realmInstance.objects(INSPECTION).filtered('datetime >= $0', startOfDay(new Date()), endOfDay(new Date())).map((a)=>{
                console.log("FETCHING 24/7 RECORD" , a);
                
                let inspection={
                    address:{
                        state:a.address.state,
                        street:a.address.street,
                        zip:a.address.zip,
                    },
                    agent:{
                        name: a.agent.name,
                        checked: a.agent.checked,
                        email:a.agent.email,
                        phone:a.agent.phone,
                        type:a.agent.type,
                    },
                    client: {
                        name:a.client.name,
                        email:a.client.email,
                        checked:a.client.checked,
                        phone:a.client.phone,
   
                    },
                    fee: a.fee,
                    paid: a.paid,
                    template: a.template,
                    uid: a.uid,
                    datetime:a.datetime,
                  }
          
                  inspections.push(inspection);
            });

            console.log("FETCHING 24/7 RECORD" , inspections);

            dispatch({
                type:inspection.INSPECTION24HOURS,
                payload:inspections
              })
 
              dispatch({
                  type:inspection.LOADING24HOURS,
                  payload:false
              })


            // let inspections = []
            // realm.objects(INSPECTION).filtered('datetime >= $0', startOfDay(new Date()), endOfDay(new Date())).map((a)=>{
            
            //  });

           
             
        }

**Comment by FawadMahmood** [comment]
https://www.loom.com/share/f37e22190d814868986a2b2f0aa2674d here's video reference of issue I am having.

**Comment by FawadMahmood** [comment]
Actually I tried Debug, Realm Open not working while application is offline. Please guide me how it should be.

**Comment by FawadMahmood** [comment]
let synchedRealm = new Realm({
      sync: {
        user: user,
        url: `realms://${realmString}/~/userRealm`,
        fullSynchronization: true,
      },
      schema:[userSchema,addressSchema,agentSchema,clientSchema,inspectionScheema] 
    });

    synchedRealm.syncSession.resume();
    realmInstance = synchedRealm;
    dispatch(getInspectionDueIn24())

This code worked for me, now it works offline and online, however when I try use open, that don't work for me.

Who ever having same issue can use this example, it's working code offline/online. 

@steffenagger  Thanks for the support. 👍
