### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code, while trying to build react-native project in iOS

### ISSUE THREAD

**Issue by ashish76** [realm/realm-js#3101]
Hi,

I am getting the error while trying to build a react-native project in Xcode.

Error is: Command PhaseScriptExecution failed with a nonzero exit code
I tried to uninstall the Realm and reinstall with a different version of Node (10.16.1, 12.18.2, 14.5.0)
I have spent almost 2 days to resolve this error but did not get any success. 
I appreciate for any help

Attached the full stack trace of the error 

## Version of Realm and Tooling
[Build target RealmJS_2020-07-29T22-17-55.txt](https://github.com/realm/realm-js/files/4996332/Build.target.RealmJS_2020-07-29T22-17-55.txt)

- Realm JS SDK Version: 6.0.3
- Node or React Native: 0.61.1
- Client OS & Version: Mac Cataline
- Node version: 10.16.1, 12.18.2, 14.5.0 (Node installed using NVM)

**Comment by steffenagger** [comment]
A solution can be found here: https://github.com/realm/realm-js/issues/1448#issuecomment-340757479
