### ISSUE TITLE
Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8083/call_method'

### ISSUE THREAD

**Issue by livelybone** [realm/realm-js#3105]
## Steps to Reproduce
1. run command: react-native run-ios
2. app runs well in iPhone x simulator, then open the debugger mode via `command + D`, and the bug appears

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: 0.62.2
- Client OS & Version: macOS Mojave | 10.14.6
- Which debugger for React Native:  chrome debugger

**Comment by livelybone** [comment]
I solved this by run command `cd ios && pod cache clean --all && rm -rf ./Pods && pod install`. But I don't know how this bug come out

**Comment by livelybone** [comment]
> I solved this by run command `cd ios && pod cache clean --all && rm -rf ./Pods && pod install`. But I don't know how this bug come out

It appears again. T_T!
![image](https://user-images.githubusercontent.com/13741638/89094251-80867d80-d3f4-11ea-80c9-9d9377c49529.png)

**Comment by ensargunesdogdu** [comment]
Hello There, 

I also have same problem. When i hit command+R i got same error.

My Versions :
    "react": "16.13.1",
    "react-native": "0.63.2",
    "realm": "6.1.2",

**Comment by praveen-wal** [comment]
@ensargunesdogdu Did you solve this issue?

**Comment by kneth** [comment]
We are migrating to Flipper for debugging, and this will go away once https://github.com/realm/realm-js/pull/3792 is merged
