### ISSUE TITLE
invalid user link request when trying to linkCredentails v10

### ISSUE THREAD

**Issue by kevin-lii** [realm/realm-js#3113]
## Goals
Trying to link an userAPIKey credential to email credential

## Expected Results
Successfully linked the userAPIKey Credential

## Actual Results

I got an error with the message `invalid user link request`

## Steps to Reproduce
  const apiCredentials = Realm.Credentials.userApiKey(key);
await userInstance.linkCredentials(apiCredentials);

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node or React Native: 0.62.2

**Comment by kneth** [comment]
@kevin-lii Thanks for reporting. We need to investigate a bit further.

**Comment by kneth** [comment]
@kevin-lii Please upgrade to v10.0.0-beta.13. If the issue is still observed, please reopen ticket.
