### ISSUE TITLE
6.0.3 iOS - The Realm is already in a write transaction

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#3114]
## Goals
Regular offline use (no syncing).  I will be updating this issue if the same error is reported on Android, but for now this is iOS only.

## Expected Results
No `already in a transaction` errors.

## Actual Results
We have been starting to receive `The Realm is already in a write transaction` reports during normal use (I believe) and without any code change.  This error started to happen after the 5.0.3 to 6.0.3 upgrade, and I believe there's nothing in the code that may be triggering concurrent transactions (especially since JavaScript is single-threaded!)

Please review the following code snipet. Perhaps we have been using Realm incorrectly and the issue started to show just now with recent updates.

Note that once the first error triggers, most database operations will fail with the same error until the app is fully restarted.

## Steps to Reproduce
Regular realm usage without any sync/online features.

## Code Sample
Regular offline use, no special code required.

The following is a code snippet of how the 'data layer' is implemented (code that will be regularly called and awaited from various components)

```
export async function updateStatus(id, uploading, error, errorInfo){

  let updated = await asyncWrite(global.realm, (realm) => {

    let exists = realm.objectForPrimaryKey('QueueItem', id);
    if(exists){

      exists.uploading = uploading;
      exists.error = error;
      if(errorInfo !== undefined){
        exists.errorInfo = errorInfo;
      }
      exists.lastUpdate = new Date().getTime();

      return true;
    }
    return false;
  });

  return updated;
}
```

Where `asyncWrite` is just a helper to convert realm sync calls into "fake" async calls:
```
export function asyncWrite(realm, cb){

  return new Promise((resolve, reject) => {
    setTimeout(() =>{
      try{
        realm.write(() => {
          resolve(cb(realm));
        });
      }
      catch(err){
        reject(err);
      }
    });
  });
}
```

And lastly, `global.realm` is instantiated once on app start (root component mount), as follows:

```
export default async function initDatabase(){
  let res = await Realm.open({schema: [...schema objects...], schemaVersion: 1});

  // exclude realm file from backups, most likely already ignored if in documents folder.
  fs.excludeFromBackupKey(Realm.defaultPath).catch((err) => console.error("Failed to exclude realm dir from backup", err.message || err));
  return res;
}

global.realm = await initDatabase();

```
Would having an event listener running permanently (until unmount) that in turn runs a query when fired cause an issue? E.g.,

```
this.objListener = await getQueueCollection();
this.objListener.addListener(this.handleRealmUpdate);

// handleRealmUpdate will in turn run another realm query

```

Additionally, after some error spam with this message (for about 2 minutes), the app fully crashed with the following:
```
EXC_BAD_ACCESS Attempted to dereference null pointer. 
    /usr/lib/system/libsystem_platform.dylib __platform_memmove
    Frameworks/CoreFoundation.framework/CoreFoundation _dataCopyProperty
    Frameworks/CoreFoundation.framework/CoreFoundation _CFWriteStreamCopyProperty
    Frameworks/ImageIO.framework/ImageIO _JPEGWriter::createData()
    Frameworks/ImageIO.framework/ImageIO _CGImageCreateEXIFJPEGData
    Frameworks/AVFoundation.framework/AVFoundation +[AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:]
    Tenant Move-In realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>::FunctionRef<realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&>(realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&)::{lambda(void*, realm::BPlusTreeNode*, unsigned long)#1}::__invoke(realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&, realm::BPlusTreeNode*, unsigned long)
    Frameworks/AVFoundation.framework/AVFoundation -[AVCaptureStillImageOutput handleNotification:payload:]
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopDoBlocks
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    PrivateFrameworks/UIKitCore.framework/UIKitCore _UIApplicationMain
    Tenant Move-In _mh_execute_header
    /usr/lib/system/libdyld.dylib _start
```

Lastly, before all this happened (about 1 hour and a half before), the following crash was also reported for the same user/device:
```
NSMallocException Failed to grow buffer 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/CoreFoundation.framework/CoreFoundation __CFRaiseMemoryException
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFReallocationFailed
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFSafelyReallocate
    Frameworks/Foundation.framework/Foundation __NSMutableDataGrowBytes
    Frameworks/Foundation.framework/Foundation -[NSConcreteMutableData appendBytes:length:]
    Frameworks/ImageIO.framework/ImageIO IIOImageWriteSession::putBytes(void const*, unsigned long)
    Frameworks/ImageIO.framework/ImageIO iioWriteCallback(void*, int, void*)
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _aj_ostream_write
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _aj_block_encode_ac
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _aj_encode_buffers_baseline
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _aj_encode_row
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _applejpeg_encode_image_row
    PrivateFrameworks/AppleJPEG.framework/AppleJPEG _recode_all
    Frameworks/ImageIO.framework/ImageIO IIOImageDestination::finalize()
    Frameworks/ImageIO.framework/ImageIO _CGImageDestinationFinalize
    Tenant Move-In realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>::FunctionRef<realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&>(realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&)::{lambda(void*, realm::BPlusTreeNode*, unsigned long)#1}::__invoke(realm::BPlusTree<realm::Timestamp>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&, realm::BPlusTreeNode*, unsigned long)
    Frameworks/AVFoundation.framework/AVFoundation -[AVCaptureStillImageOutput handleNotification:payload:]
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopDoBlocks
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    PrivateFrameworks/UIKitCore.framework/UIKitCore _UIApplicationMain
    Tenant Move-In _mh_execute_header
    /usr/lib/system/libdyld.dylib _start
```

As replied on and closed by https://github.com/realm/realm-js/issues/3111
However, Realm might be involved in this after all... 

## Version of Realm and Tooling

- Realm JS SDK Version: ? 6.0.3
- Node or React Native: ? React Native 0.61.5
- Client OS & Version: ? iOS 13.5.1 / iPhone 8
- Which debugger for React Native: None - production build

**Comment by kneth** [comment]
@cristianoccazinsp Do you have a chance to see how large the Realm file is after the crash? My guess is that it is far too large for iOS to handle, and the `NSMallocException Failed to grow buffer` error comes from that.

The error `The Realm is already in a write transaction` can come from a listener doing a write transaction. It might be better to use manual transactions (`beginTransaction`, etc.) and check if you already in a transaction (nested transactions are not supported).

**Comment by cristianoccazinsp** [comment]
@kneth I don't really have access to the file since this happened in production devices, but I can certainly to replicate it and see how big it ends up. Although we store some json values, I don't see the database having to store more than 10mb in a very rare case.

From the code samples above, do you think the transaction error can really happen in that code?  Although there's an event listener, it only fires another method that will in turn open a new `.write(..)` call in a timeout with the async helper above. Moreover, this error never happened before, and now it happened in a way that the whole app was blocked and unable to do any write to the database until it actually crashed.

**Comment by cristianoccazinsp** [comment]
I've also checked the realm file, it is just about 4Mb big, shouldn't be causing issues.

**Comment by kneth** [comment]
> Although there's an event listener, it only fires another method that will in turn open a new `.write(..)`

Due to how we interact with the event loop, you might end up with nested transactions. If possible, try to check `Realm.isInTransaction` before you begin a transaction `Realm.beginTransaction()`. Moreover, be aware of exceptions in your listener. If you don't have a `try`/`catch` in your listener, you might experience crashing with "random" stack traces.

> realm file, it is just about 4Mb big

Indeed, it is small!

> Again, this only happens with iOS, Android doesn't seem to suffer from this issue.

We need to investigate this as a bug.

**Comment by cristianoccazinsp** [comment]
I wish I could reproduce the issue locally myself, but I had no luck so far.  I've tried everything, intensive read/writes, massive objects (~10mb), and it never breaks on my device, not even memory leaks! On the other hand, the production iOS builds seem to be firing these errors very often.  

Would it be possible to have `write` calls enqueue the transaction or something? 

Can `Realm.isInTransaction` be called right before `realm.write(..)` to prevent the crash/error?  Perhaps I could update the write wrapper to re-try a few times with `Realm.isInTransaction` checks, but I don't really know if that would solve the problem since it really looks like the realm ends up stuck in a transaction until fully restarted, so this would only delay the crashes.

Would the fact that there's ever only one ingle realm instance (assigned to `global.realm`) be a problem now with 6.x?

Thanks!

**Comment by kneth** [comment]
Sorry for not being clear. My suggestion is to write the listener something like:

```
let listener = (r, c) => {
  try {
    if (!r.isInTransaction) {
      r.beginTransaction();
    }
    // ... create, delete, modify objects
  }
  catch (e) {
    console.log(`Error: ${e}`);
  }
};
```

**Comment by enigmablue** [comment]
I hit this error as well when i put a listener. 

For some reason, when there is an [1] existing isInTransaction and [2] i try to update the state that uses that same data, and then [3] theres another transaction - the error is hit.  Something along that line.

Background: I use the listener to track activities and then update the view (using state). The problem hits when the user logs in, and a bulk number of insertions hit the database. So the state is unable to update as quickly as the realm transactions.

My code now is then like this, not very efficient.. but dosen't hit all cases...

I update a state object to set that there is a new activity.
  ```
changes.insertions.forEach((index) => {
       insertBlock.push(shares[index])
          setInsertionProcessing(insertBlock);
        }
   });
```

I use an interval to wait a few seconds as the records are inserted into realm.

I use a setInterval originally because i wanted to load 'in processing' objects in a queue. Oh but man that was a bit messy so i just increased the interval instead (2000). I prefered interval then timeout because i think timeout somewhat uses the current timeshot.

```
useEffect(()=>{

      if (insertionProcessing == null) return
      var myVar = setInterval(function loadShares() {
        if (realm.isInTransaction == true){
          return
         }
        else {
          console.log("updating view")
          let newAllShares = ShareSchema.getAllShares();
            setAllShares(newAllShares)
          clearInterval(myVar);
          setInsertionProcessing(null);
        }
      }, 2000);

  }, [insertionProcessing])
```

**Comment by cristianoccazinsp** [comment]
Update: I have received this error on Android now as well (Galaxy A10e, Android 9).  We will be releasing a new version with an updated RealmJS version and an attempt to prevent the issue by using `isInTransaction` and a timed-out retry, although we think this is an ugly workaround that wasn't needed before.

**Comment by kneth** [comment]
@cristianoccazinsp Do you have any updates to share? I mean, does `isInTransaction` have any impact on the crash rate?

**Comment by cristianoccazinsp** [comment]
@kneth I'm still monitoring the logs as new users update to this version. No issues so far, but the work around to check `isInTransaction` is still ideal for me and I'm sure it was a "new bug" after one of the updates. Perhaps the work around is hiding an actual bug, but users take a few weeks to update so we will see soon.

**Comment by kneth** [comment]
@cristianoccazinsp I agree that it's a workaround. Please ping me if you observe any crash.

**Comment by enigmablue** [comment]
I had crashes on this weeks ago (in production even) and had to put some emergency fix. 

For my use case, It happens when I insert multiple objects into the database. For me, it happens when a user is logged in. Here I also update the GUI based on that listener setup on that object. Besides the crash, I also had a severe rendering issue, if I inserted 300 records into the database, it would cause 300 renders because of the way the listener is setup. And there is no way for the listener to know when the last row is inserted.

So instead of listening on the individual object, I created a table of 'user actions'. Whenever user logs in, i retrieve objects from database and store in Realm.  After that I insert a record into that new table. When the new table listener picks up the event, then i refresh the view. 

So I solved the problem by doing a better database design instead. 

Hope this helps anyone who may hit this issue!

**Comment by kneth** [comment]
@enigmablue Thanks for the update.

**Comment by kneth** [comment]
@cristianoccazinsp Does https://github.com/realm/realm-js/issues/3114#issuecomment-687694002 help you?

**Comment by kneth** [comment]
>  I haven't seen this anymore after upgrading

If you see it again, please either reopen this issue or create a new one.

**Comment by cristianoccazinsp** [comment]
Looks like this is still happening, rarely, but still does.  This time this happened in background (most likely from an Android headlessJS call). RealmJS  10.6.1
