### ISSUE TITLE
realm logIn() function not working when restarting the App

### ISSUE THREAD

**Issue by Sascha195** [realm/realm-js#3118]
## Goals

Successful implementation of the login() function for the realm App

## Expected Results

After restarting the app the login should work properly

## Actual Results

When starting the app for the first time, the login works without problems. As soon as the app is closed or restarted, the login does not work anymore. Error message "The user aborted a request". This behavior occurs only on Windows 10. The app has already been tested on macOS and worked fine. Once the Windows computer has been completely restarted, the first login will work again. I assume that after closing the app some ports on Windows are not released again and will block the following logins.

## Code Sample

```
const logIn = async (credentials) => {
    try {
      // Authenticate the user
      const _user = await realmApp.logIn(credentials); //will fail after first login

      setUser(_user);

      openRealm(_user);

      return {
        success: true,
        user: _user,
      };
    } catch (err) { //err.message = "The user aborted a request", err.code = -1
      return {
        success: false,
        user: null,
        message: err.message,
      };
    }
  };


//realmApp defined as
new window.Realm.App({
        id: config.syncServerAppId,
        location: 'us-east-1',
        timeout: 10000,
      })
```

## Version of Realm and Tooling

- "realm": "^10.0.0-beta.9"
- "react": "^16.13.1"
- "react-native-web": "^0.12.3"
- "node-gyp": "^7.0.0"
- "node-pre-gyp": "^0.15.0"
- "node": "14.7.0"
- Windows 10

**Comment by johnsaigle** [comment]
@Sascha195 I believe I ran into a similar problem and was able to solve it by changing the permissions on `realm-object-server`. If in doubt delete it and try again to see if it fixes your problem.

I am developing with the Node SDK on Linux so it may not work, but worth a shot if you're stuck.

**Comment by kneth** [comment]
@Sascha195 Did the above suggestion help?

**Comment by Sascha195** [comment]
@kneth @johnsaigle I tried your suggestion, but unfortunately neither changing the permissions nor setting up the realm server again was of any help. Any other solution suggestions?

**Comment by matt2legit** [comment]
I'm seeing the same behavior with React Native on iOS.  Noticed it in beta.9, but I'm still seeing it after upgrading to beta.11

**Comment by matt2legit** [comment]
Just to follow up on this with some more details.  The first time we fire the app up and login, it works just fine.  If we reload the app bundle and try to login again, the login call just hangs.  I checked the realm logs in atlas and it doesn't even appear to be making the request.  I tried to debug this some, but I'm not sure what `this._login` references in `lib/app.js`.  It's making it that far, but there aren't any errors, so I'm flying blind.

We are using React Native 0.62.2 and running in the Xcode simulator and also on a device.  I'm not sure if this is the exact same issue reference above, but it appears to be similar.

**Comment by matt2legit** [comment]
I'm using Function Auth / Credentials here.  I also noticed that when I turned on the Chrome Debugger that Credentials.function is not defined.  I tried to add method for it in `rpc.js`, but no matter what credential type I try I get `Must first create RPC session with a valid host`.  It looks like `sessionHost` isn't set or passed when `sendRequest` is called.

Still my biggest issue is that I can't refresh the app and login again.  @kneth any idea on this or should I create a new issue for it.  It's a pretty big blocker at the moment, so any help would be appreciated.

**Comment by kneth** [comment]
@matt2legit Do you only observe it when you are debugging? #3236 is reporting a similar issue.

**Comment by izakfilmalter** [comment]
Any updates on this? I'm on the RC and it's unusable. Been looking into Realm to switch off of Firebase, and this is putting me off.

**Comment by blagoev** [comment]
this is fixed by https://github.com/realm/realm-js/pull/3340
