### ISSUE TITLE
resetPassword and callResetPasswordFunction are impossible to execute due to incorrect number of arguments

### ISSUE THREAD

**Issue by johnsaigle** [realm/realm-js#3120]
## Goals

Calling `emailPasswordAuth.resetPassword()` to reset a user's password.

## Expected Results

The password should be reset.

## Actual Results

![realmbad](https://user-images.githubusercontent.com/4022790/89815363-a4437500-db12-11ea-997b-c8928ca8e2a2.PNG)

I believe the error is in the following code from `node_modules/realm/lib/email-password-auth-methods.js`
![you](https://user-images.githubusercontent.com/4022790/89815436-cccb6f00-db12-11ea-80db-620864b74460.PNG)

The stack trace indicates that a parameter is missing and these two functions do not have `cb` in the argument list, unlike the other functions. Adding `cb` as the fourth argument to both functions fixed my issue.

## Steps to Reproduce

Try to use the function.

## Code Sample

![realmbad2](https://user-images.githubusercontent.com/4022790/89815532-f5536900-db12-11ea-9a48-9ffeed5f0854.PNG)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node or React Native: Node
- Client OS & Version: Ubuntu 18.04 LTS

**Comment by kneth** [comment]
I believe it has been fixed by #3079 but not yet released.

**Comment by johnsaigle** [comment]
Any idea when the next release will be?

**Comment by kneth** [comment]
As a principle we never promise releases at specific dates but let's say next week 😄
