### ISSUE TITLE
iOS fails continuously after the the first time

### ISSUE THREAD

**Issue by cherimo** [realm/realm-js#3128]
Hey there,

I have googled/stackoverflow and searched in the issues box for straight 2 days now..
I found multiple scenarios where the problem is almost identical but didnt reslove my issue.
The environment that I use is React Native.
On Android btw everything works fine, its iOS that gives me the most headache.

The first time I installed the plugin everything works fine in the simulator build, no errors, nothing. 
When I run it again without making changes it gives me the following error:
The following build commands failed:
	Ld /Users/name/Library/Developer/Xcode/DerivedData/ProjectName-bjelovsgossmgxdhanthpkyraxtu/Build/Products/Debug-iphonesimulator/RealmJS/RealmJS.framework/RealmJS normal x86_64

When I tried to build it in XCode I get a lot(101) of errors which mainly exist in the following messages:
 - Undefined symbols for architecture armv7
 - Undefined symbol: realm::ConstLstIf<realm::Timestamp>::max(unsigned long*) const
 - Undefined symbol: virtual thunk to realm::ConstLstIf<realm::StringData>::sort(std::__1::vector<unsigned long...

I am using the following dependencies at the moment:
    "@eva-design/eva": "^2.0.0",
    "@expo/react-native-action-sheet": "^3.8.0",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.4.0",
    "@react-navigation/bottom-tabs": "^5.7.2",
    "@react-navigation/drawer": "^5.8.6",
    "@react-navigation/material-top-tabs": "^5.2.14",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "@ui-kitten/components": "^5.0.0",
    "@ui-kitten/eva-icons": "^5.0.0",
    "i18n-js": "^3.7.1",
    "react": "16.13.1",
    "react-native": "0.63.1",
    "react-native-flash-message": "^0.1.15",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-localize": "^1.4.0",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-secure-storage": "^0.1.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-list-view": "^3.2.3",
    "react-native-tab-view": "^2.15.0",
    "react-redux": "^7.2.1",
    "realm": "^6.0.4",
    "redux": "^4.0.5"

I followed the installation page and tried a lot workarounds here and in stackoverflow but still no success.

Does somebody know what I am doing wrong?

**Comment by kneth** [comment]
@cherimo Thank you for reporting. Just one simple question: which version of MacOS and Xcode do you use?

You say

> The following build commands failed:
> Ld /Users/name/Library/Developer/Xcode/DerivedData/ProjectName-bjelovsgossmgxdhanthpkyraxtu/Build/Products/Debug-iphonesimulator/RealmJS/RealmJS.framework/RealmJS normal x86_64

but also 

> Undefined symbols for architecture armv7

It looks like a mix up of x86_64 and armv7. Can you confirm that you observe this mixture?

**Comment by cherimo** [comment]
@kneth Thank you for your fast response.
I made a new project and installed realm as the only dependency..
And everything works fine, this issue has to do something with one the 3 plugins which requires to make some changes in ios core files. I am gonna troubleshoot my way out of this. As soon as i have more information I will let you know.

Thank you
