### ISSUE TITLE
Bug | args.map is not a function

### ISSUE THREAD

**Issue by omerts** [realm/realm-js#3141]
Hey, 
Realm version: v10.0.0-beta9

Seems like there is a serious bug around the lib/browser/rpc.js file, many of the auth methods are expecting an args array param, while they are receiving scalar values, which cause an `args.map is not a function` error.
For example (lib/browser/rpc.js line 103: 
```javascript
export function _emailPasswordRPC (args) {
  args = args.map(arg => serialize(null, arg))
  const result = sendRequest('_emailPassword', { arguments: args })
  return deserialize(undefined, result)
}
```

Calling function is lib/browser/credentials.js line 37:

``` javascript
static emailPassword(email, password) {
  return _emailPasswordRPC(email, password);
}
```
so rpc function should either be updated to `...args` or calling function should pass an array.

**Comment by kraenhansen** [comment]
Thanks for reporting this @omerts - this is surely seems like an oversight on our part.

**Comment by blagoev** [comment]
Thanks for reporting. This is fixed by https://github.com/realm/realm-js/pull/3149 and will be part of our next release
