### ISSUE TITLE
Filter aggregate operators don't work with list of dates or booleans

### ISSUE THREAD

**Issue by sintylapse** [realm/realm-js#3152]
## Goals
Trying to use filter with aggregate operators like `.@count` or `.@size` on properties that are lists of dates or booleans throws an error `Invalid query: @size and @count can only operate on types list, binary, or string`

<img width="627" alt="Screen Shot 2020-08-20 at 00 05 54" src="https://user-images.githubusercontent.com/12295016/90690457-682eb380-e27a-11ea-9e9d-e19f66c4505b.png">

## Expected Results
Filter should work normally

## Actual Results
`Invalid query: @size and @count can only operate on types list, binary, or string `

## Steps to Reproduce
1. Create schema with property as list of dates
2. Try to filter objects of this schema using aggregate operators like `.@count` or `.@size` on this property

## Version of Realm and Tooling
- Realm JS SDK Version: 6.0.3
- React Native: 0.61.5
- Which debugger for React Native: Realm Studio Version 3.11.0

**Comment by ironage** [comment]
Hi @sintylapse we have added support for queries on primitive lists only recently. In realm studio it looks like this feature is only available in the latest beta version (realm studio 10.0.0-beta.2). Note that using this version will upgrade your Realm files to a new format, so make sure you are ok with that before trying it out. Related to https://github.com/realm/realm-js/issues/1812
