### ISSUE TITLE
MongoDB realm - realm.syncSession.config does not return entire config

### ISSUE THREAD

**Issue by bentron2000** [realm/realm-js#3155]
## Goals

Trying to retrieve the current partitionValue from a sync session configuration on a realm instance.

## Expected Results

`realm.syncSession.config.partitionValue` to return the value of the partition key. 

## Actual Results

returns `undefined`

## Steps to Reproduce

run `realm.syncSession.config.partitionValue` on a synced realm.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node: v12.13.0
- Client OS & Version: osx 10.13.6

**Comment by ianpward** [comment]
@bentron2000 I think you want to access this off the SyncConfiguration - 
https://docs.mongodb.com/realm-sdks/js/10.0.0-beta.11/Realm.Sync.html#~SyncConfiguration

**Comment by bentron2000** [comment]
> @bentron2000 I think you want to access this off the SyncConfiguration -
> https://docs.mongodb.com/realm-sdks/js/10.0.0-beta.11/Realm.Sync.html#~SyncConfiguration

Hi @ianpward 

So you can't get it directly from an instance of a realm or the `_realm` property of a realm object?

I have quite a lot of different realms and corresponding objects across my project and it would be very useful to be able to determine the `partitionValue`of any of them on the fly.

If I inspect an instance of a `Realm`, I can see `syncSession.config` but it does not contain this information.

![Screen Shot 2020-09-18 at 6 25 07 pm](https://user-images.githubusercontent.com/5344375/93574974-66245580-f9dc-11ea-9d3f-c7647280b59a.png)

**Comment by ianpward** [comment]
Agree it would be useful - I just wanted to give you another option for now. I have this to our "quick-wins" backlog

**Comment by steffenagger** [comment]
A fix will be in the next/upcoming v10.0.0 release.
