### ISSUE TITLE
Realm Web: Persist and retrieve anonymous users

### ISSUE THREAD

**Issue by dalmo3** [realm/realm-js#3164]
Related to https://github.com/realm/realm-js/issues/2964#issuecomment-673222982. 

Just started playing with realm-web on React and if I log in with anonymous credentials, at each page refresh a new set of profile/accessToken/refreshToken is created, absolutely cluttering localStorage.

Sample code [here](https://codesandbox.io/s/great-cookies-6pzzz) (open the app in new window).

For some reason the fix provided by https://github.com/realm/realm-js/pull/2990 doesn't seem to work for anonymous credentials.

This problem is nonexistent with Stitch Browser SDK, since its [AnonymousCredential](https://github.com/mongodb/stitch-android-sdk/blob/87c47223231aa4e390524a8cde4773a41d95faf3/core/sdk/src/main/java/com/mongodb/stitch/core/auth/providers/anonymous/AnonymousCredential.java) makes use of [ProviderCapabilities](https://github.com/mongodb/stitch-android-sdk/blob/master/core/sdk/src/main/java/com/mongodb/stitch/core/auth/ProviderCapabilities.java) with `reusesExistingSession = true`. Therefore `initializeDefaultAppClient` uses existing anon user from localStorage

Is that possible with realm-web?

**Comment by kraenhansen** [comment]
Would it be possible for you to post some of the code you're using?

When calling `logIn` with anonymous credentials, you're effectively creating a new user on the server. If you want to avoid that, you'll need to check if another user is already authenticated (`app.currentUser !== null`) before calling `logIn`.

**Comment by dalmo3** [comment]
Yep, sample code [here](https://codesandbox.io/s/great-cookies-6pzzz) (open the app in new window).

> When calling `logIn` with anonymous credentials, you're effectively creating a new user on the server. If you want to avoid that, you'll need to check if another user is already authenticated (`app.currentUser !== null`) before calling `logIn`.

Great, but I couldn't make that work. Fell into this https://github.com/realm/realm-js/issues/2946. It's commented out in the sandbox.

**Comment by kraenhansen** [comment]
@dalmo3 the `function not found: 'hasOwnProperty'` error is thrown as a side-effect of calling `console.log()` on a `User` object: Which we need to get fixed, but it's unrelated to your original issue.

I adjusted your sandbox to show how the anonymous user can be reused https://codesandbox.io/s/black-snow-k861x - does this help / make sense?

**Comment by dalmo3** [comment]
So simple, makes a lot of sense, thank you!

**Comment by kraenhansen** [comment]
Great! I'll close this for now - please keep an eye out for an update fixing the other issue though.
