### ISSUE TITLE
Pod install error on v10.0.0-beta.10: Cannot find module download-realm.js

### ISSUE THREAD

**Issue by ioveracker** [realm/realm-js#3168]
## Goals

Install Realm v10.0.0-beta.10 in a React Native app.

## Expected Results

Installing the iOS pods should download Realm and install successfully.

## Actual Results

```
Installing RealmJS (10.0.0-beta.10)
[!] /bin/bash -c 
set -e
./scripts/xcode-download-realm.sh ./scripts

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/Users/ioveracker/Source/my-app/node_modules/realm/scripts/scripts/download-realm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

error Command failed with exit code 1.
```

## Steps to Reproduce

1. Use yarn or npm to install `realm@10.0.0-beta.10` in a React Native project.
2. In the `ios` directory, run `pod install` to install CocoaPods.
3. Observe that the above error is thrown.

## Code Sample

Basic React Native project that I used to reproduce this is available at [ioveracker/realm-v10.0.0-beta.10-pods-error](https://github.com/ioveracker/realm-v10.0.0-beta.10-pods-error).

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.10
- Node or React Native: React Native 0.63.2
- Client OS & Version: macOS 10.15.5
- Which debugger for React Native: N/A

**Comment by blagoev** [comment]
Thanks for reporting and more so providing a fix.
