### ISSUE TITLE
Cannot modify managed objects outside of a write transaction.

### ISSUE THREAD

**Issue by sadikyalcin** [realm/realm-js#3173]
## Goals

I have a list of news articles with a favourite boolean. I update the realm when it's the favourite/unfavourite button is tapped. The write is successful, I can see the change being reflected straight away but `Cannot modify managed objects outside of a write transaction.` is thrown. I'm struggling to see what the issue is here...

## Expected Results

No error thrown.

## Actual Results

`Cannot modify managed objects outside of a write transaction.` error is thrown even though the write is successful.

## Code Sample

    favorite = _nid => {
      try {
        realm.write(() => {
          realm.create(
            'News',
            {
              nid: parseInt(_nid, 10),
              favorite: true,
            },
            'modified',
          );
        });

        const data = {
          rows: this.state.allData,
          pager: {
            total_items: this.state.routes[0].totalItems,
          },
        };

        this.dataHandler(data);
      } catch (error) {
        console.log('error: ', error); // error is trigged here, caused by `dataHandler`
        Alert.alert(alertMessages.dbError.title, alertMessages.dbError.message);
      }
    };

    dataHandler = _data => {
      let updatedData = [];

      const newsData = realm.objects('News');

      _data.rows.map(item => {
        const newData = newsData.filtered('nid = "' + item.nid + '"');

        if (newData && newData.length > 0 && newData[0].favorite) {
          item.favorite = newData[0].favorite;
        } else {
          item.favorite = false;
        }
        updatedData.push(item);
      });

      updatedData.map(async item => {
        realm.write(() => {
          realm.create(
            'News',
            {
              nid: parseInt(item.nid, 10),
              title: item.title,
              body: item.body,
              filename: item.filename,
              uri: item.uri,
              extension: item.extension,
              filesize: item.filesize,
              filemime: item.filemime,
              categoryID: item.field_category ? item.field_category : '0',
              categoryLabel: item.field_category_1 ? item.field_category_1 : 'All News',
              created: item.created,
              favorite: item.favorite,
              sticky: item.sticky === 'true' ? true : false,
            },
            'modified',
          );
        });
      });

      _data.rows = updatedData;

      this.setData(_data);
    };

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.0
- Node or React Native: 0.61.5
- Client OS & Version: not os related
- Which debugger for React Native: None

**Comment by steffenagger** [comment]
`_data.rows` is containing `Realm.Object`s and will already be updated. So in other terms, there's no need to run the `dataHandler`.

The error arises when setting `item.favorite` outside of a write transaction.

**Comment by sadikyalcin** [comment]
> `_data.rows` is containing `Realm.Object`s and will already be updated. So in other terms, there's no need to run the `dataHandler`.
> 
> The error arises when setting `item.favorite` outside of a write transaction.

I need the data handler as per my app logic. But I see the issue now. If I include the `item.favorite` inside a write, it overrides all realm objects. What I needed to do was, convert the `newData` to a plain JS object. I don't think realm has a method for that. Regardless, I'll handle it here from now on.

**Comment by steffenagger** [comment]
> What I needed to do was, convert the `newData` to a plain JS object. I don't think realm has a method for that.

If you update to realm@6.1.0 you can use `newData.toJSON()` to get a plain JS object.
