### ISSUE TITLE
v10.0.0-beta.11: Syntax error, unexpected token on launch of React Native app

### ISSUE THREAD

**Issue by ioveracker** [realm/realm-js#3178]
## Goals

Run a React Native app on v10.0.0-beta.11.

## Expected Results

The app should run without errors.

## Actual Results

An error is thrown due to a syntax error in `lib/browser/index.js`.

<img width="488" alt="Screen Shot 2020-08-28 at 10 37 54 AM" src="https://user-images.githubusercontent.com/1653961/91619705-b01c9d00-e942-11ea-9349-21f61db7053e.png">

## Steps to Reproduce

Run a React Native app with Realm@10.0.0-beta.11 and observe a crash on launch.

## Code Sample

https://github.com/ioveracker/mongodb-realm-react-native-playground/tree/beta.11-syntax-error

## Version of Realm and Tooling

- Realm JS SDK Version: v10.0.0-beta.11
- Node or React Native: React Native 0.63.2
- Client OS & Version: macOS 10.15.5
- Which debugger for React Native: N/A

**Comment by kneth** [comment]
PR: https://github.com/realm/realm-js/pull/3179
