### ISSUE TITLE
Unable to write to realm in app group version 6.1.0 only

### ISSUE THREAD

**Issue by EricWiener** [realm/realm-js#3180]
## Goals
Create a new realm object in a realm stored in an app group. It worked for RealmJS 6.0.3, but it no longer works for Realm JS 6.1.0. I believe this may be caused by the following update in 6.1.0: 

> Holding a shared lock while being suspended on iOS would cause the app to be terminated. ([#6671])(realm/realm-cocoa#6671)

## Expected Results
The object should be added no issue.

## Actual Results
I get the error: `Continuous transaction through SharedGroup object without history information`.
[Full error log](https://github.com/realm/realm-js/files/5147684/realmjs_error.txt)

## Steps to Reproduce
1. Create a Realm in a shared app group. 
2. Try to create a new object:

## Code Sample
Can't provide the source of the code, but any creation in a shared app group should have similar results.
```
realm.write(() => {
      realm.create('MyItem', item, UpdateMode.All);
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.0
- Node or React Native: 0.63.3
- Client OS & Version: iOS 13.4 iPhone 11 Pro Simulator
- Which debugger for React Native: None

**Comment by kneth** [comment]
@EricWiener Thank you for reporting. Can you explain your set up a bit? I mean, what constitutes your app group? An iOS app and a MacOS app?

@finnschiermer Is this something you can take a look at?

**Comment by finnschiermer** [comment]
@EricWiener 
1. Can you provoke this with a single app or does it take multiple apps? 
2. If the latter: are both/all apps updated to same version? 
3. Is the error triggered on a clean start (no legacy realm file, lock file, management dir) or is it opening an already existing file?

**Comment by EricWiener** [comment]
Thanks so much for the reply @kneth and @finnschiermer! My app group consists of an iOS app and a share extension within the same project, so everything is on the same version (and within the same XCode project). It is triggered for sure with an existing realm, but I will try right now on a new realm and report back

**Comment by EricWiener** [comment]
After deleting the existing app and trying to re-install the app crashes when it first tries to setup Realm: `[javascript] 'Unhandled promise rejection', [Error: Continuous transaction through SharedGroup object without history information`
[full log.txt](https://github.com/realm/realm-js/files/5150158/new_realm_log.txt)

**Comment by finnschiermer** [comment]
Handing over to an iOS expert. What do you think, @tgoyne ?

**Comment by tgoyne** [comment]
I took the starter app created by expo, added Realm, made it create and write to a Realm in a shared container on startup, and it appears to work correctly on all of the iOS 13 simulator running on 10.15, iOS 14 beta and iOS 11.3.1. The full project is attached, but the only relevant bits of code are:

```
@interface AppGroup : NSObject <RCTBridgeModule>
@end
@implementation AppGroup
RCT_EXPORT_MODULE();

- (NSDictionary *)constantsToExport {
  return @{@"path": [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:@"group.io.realm.test"].path};
}
+ (BOOL)requiresMainQueueSetup { return NO; }
@end
```
```
export default function App() {
  const realm = new Realm({
    path: NativeModules.AppGroup
[shared-group.zip](https://github.com/realm/realm-js/files/5153494/shared-group.zip)
.path + "/default.realm",
    schema: [{name: 'Dog', properties: {name: 'string'}}]
  });
  realm.write(() => {
    realm.create('Dog', {name: 'Rex'});
  });
  realm.close();
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

Presumably your real app is doing something quite a bit more complicated than this, and it's something else causing the problem. Are you using `shouldCompactOnLaunch` (or manually calling compact())? Incorrect locking related to that could  potentially explain the error.

**Comment by EricWiener** [comment]
@tgoyne thanks for the reply! I'm not using `shouldCompactOnLaunch` or `compact`. However, I am using both RealmSwift and RealmJS in the app so I can make use of IceCream sync. I will work on taking the sample app you made and adding RealmSwift to it to see if I can reproduce the issue there, although I will need to move it to a non-expo app since I need to install pods.

**Comment by tgoyne** [comment]
Oh, mixing access between RealmSwift and RealmJS currently won't work because we haven't released a version of RealmSwift yet that uses the new locking scheme. That should happen very soon.

**Comment by EricWiener** [comment]
@tgoyne oh wow that would explain it. Sorry for not mentioning that before you created the example app. I really appreciate your help with this!
