### ISSUE TITLE
Invalid createSession import

### ISSUE THREAD

**Issue by euZebe** [realm/realm-js#3181]
After I upgraded realm from 10.0.0-beta.9 to 10.0.0-beta.11, my app gets an error on startup 

```
error: SyntaxError: /Users/euzebe/dev/myApp/node_modules/realm/lib/browser/index.js: Unexpected token (34:25)

  32 | import * as util from './util';
  33 | import { static as staticUserMethods } from '../user';
> 34 | import { createSession } './session';
     |                          ^
  35 | 
  36 | const {debugHosts, debugPort} = NativeModules.Realm;
  37 | 
```

`from` keyword is missing.
The problem comes from commit https://github.com/realm/realm-js/commit/2a1877afabdbad9d70960dd62f59a4e26783dc72
  
## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.11
- React Native: 0.62.2
- Client OS & Version: macOS Catalina 10.15.6
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@euZebe Thanks for your fix.
