### ISSUE TITLE
DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8083/create_session'.

### ISSUE THREAD

**Issue by yrjwcharm** [realm/realm-js#3184]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by bmunkholm** [comment]
@yrjwcharm Sorry but we can't help you with that limited information.  Please fill in the entire template.

**Comment by cristianoccazinsp** [comment]
This happens to me often when trying to debug locally.  When chrome's debugger starts, you will get this often if the device has no WiFi (I guess realm connects to the device through WiFi or something).

Turning on wifi and reloading will most of the time fix the problem.  But yes, remote debugging with realm can sometimes raise very cryptic error messages.
