### ISSUE TITLE
Cannot create new after delete ...

### ISSUE THREAD

**Issue by Jugging** [realm/realm-js#3195]
1. Cannot create  a new  topic  after delete topic,when use `realm.create`,it will return **key not found**
2. `realm.delete(topic);`   cause the program to crash

## Code Sample
```
     var topic = realm.objectForPrimaryKey('XXXX','XXid')
      if(topic.isValid()){
          try{
              realm.delete(topic);   // ---> cause the program to crash
          }
           catch(e){
                console.log(e);
             }
    }
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.0
- Node or React Native: Node
- Client OS & Version: window 10
- electron 8.1.1

**Comment by kneth** [comment]
@Jugging 

Can you post the stack trace?

The object you are trying to delete, was it created with an earlier (pre v6) version of Realm? Moreover, can you reproduce it with node.js?

Finally, it is possible for you to share the Realm file (in a private communication channel)?
