### ISSUE TITLE
Accessing data from a Realm: security issue ?

### ISSUE THREAD

**Issue by euZebe** [realm/realm-js#3198]
## Goals

Prevent anyone to access my own realm.

Let's consider a realm app with a single document type: User. 
User documents have a partitionKey `username`.

## Expected Results

When logged in, I should not be able to see data whose partition key is not related to me.

## Actual Results

It seems like knowing a valid partition key, I can read (and write ?) any data from a realm I do not own.

## Code Sample

```javascript
const Realm = require("realm");

 class RealmUser  {
   username // my partition key
   _id
  name

  constructor({ name, username }){
    this.username = username
    this._id = randomUuid()
    this.lastname = lastname
    this.name = name
  }

  static schema = {
    name: "User",
    properties: {
      username: "string",
      _id: "string",
      name: "string",
    },
    primaryKey: "_id",
  }
}


const realmApp = new Realm.App({ id: "my-realm-app-id" });

// My app uses a JWT authentication. Tokens contain a field called "username", with which I set the partition key.
const credentials = Realm.Credentials.custom("aValidJWToken");

realmApp.logIn(credentials).then((user) => {
  const config = {
    schema: [
      RealmUser.schema,
    ],
    sync: {
      user,
      partitionValue: "26ec022e-0aac-4e40-8804-a5aabc251889", // <== here,  I should set partitionValue as the username I get from the JWT
    },
  };

  Realm.open(config)
    .then((openedRealm) => {
      console.log(
        "Realm open with schemas: ",
        config.schema.map((s) => s.name)
      );

      console.log("user", JSON.stringify(openedRealm.objects("User")))
    })
    .catch(console.error);
});
```

By only changing the partitionValue to another valid partition key, I can read any data from any other realm.

Did I miss something, in my realm server configuration or in the understanding of Realm? Or isn't it a real security issue, considering I just need my own valid credentials and an existing partitionKey to access the related data (even if the partitionKey does not match my own one)?

I imagine cases where partitionKey is an email, way more predictable than a random string...

(I guess I missed or misunderstood something)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.12
- Node or React Native: Node
- Client OS & Version: macOS 10.15.6

**Comment by nirinchev** [comment]
You can see how to define data access rules here: https://docs.mongodb.com/realm/sync/rules/. When opening a Realm with a particular user (represented by an access token), the server will reject attempts to read data from a partition the user doesn't have access to.
