### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code RealmJS Using in React Native

### ISSUE THREAD

**Issue by pandiyanmadhan94** [realm/realm-js#3202]
I am trying to run the application within react-native using realmjs but I am facing this error, I am searching this from the last 2 days but no luck please help.

Using mac OS Catalina
Using Node.js v14.9.0
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/Users/sys-user/Desktop/Vel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by kneth** [comment]
It looks like you have a space in your path. It has been fixed by https://github.com/realm/realm-js/pull/3188 and we will release it soon.

As a workaround, try to use a path without spaces.
