### ISSUE TITLE
Error "Invalid session ID" when using react-native-debugger

### ISSUE THREAD

**Issue by colaskirschoff** [realm/realm-js#3213]
## Goals

Use react-native-debugger together with realm (or chrome debugger)

## Expected Results

No crash

## Actual Results

Error message "Invalid session ID"
Stack trace:
sendRequest
    rpc.js:336:18
getProperty
    rpc.js:143:17
getProperty
    util.js:89:19

## Steps to Reproduce

- Open debug menu
- Click on Debug

## Version of Realm and Tooling

react-native: 0.61.1
realm: 6.1.1
simulator: iOS 13.7 (same bug on Android)

**Comment by kraenhansen** [comment]
Are you referring to the https://www.npmjs.com/package/react-native-debugger package?

The version of React Native that you're using got released over a year ago, could I ask you to upgrade and confirm that you can reproduce the bug with the latest version of Realm and React Native?

**Comment by colaskirschoff** [comment]
Hi, I'm referring to this one, which is widely used: https://github.com/jhen0409/react-native-debugger. But the bug also happens while debugging directly on chrome and actually was already mentioned here: https://github.com/realm/realm-js/issues/408.

If you have any clue on how I could debug this I'm happy to listen, otherwise I'll come back to you when I update react native :)

**Comment by colaskirschoff** [comment]
Hi again, just kept debugging and it's actually due to another library that depends on an older version of realm. Thank you !
