### ISSUE TITLE
Realm casts array of string to an object

### ISSUE THREAD

**Issue by Youhy** [realm/realm-js#3217]
## Goals

I have a schema 

```
export const User = {
    name: 'Profile',
    primaryKey: 'id',
    properties: {
        id: 'string',
        citizen: 'string?',
        imageUrl: 'string?',
        position: 'string?',
        firstName: 'Localized?',
        middleNames: 'Localized?',
        lastName: 'Localized?',
        emails: 'string[]',
        phones: 'string[]',
        location: 'Location?',
        dob: 'Dob?',
        address: 'Address?',
        identityNumber: 'IdentityNumber?'
    }
};

```
where `emails` and `phones` are arrays of strings;

When getting data from realm  `emails` and `phones` are casted to an object

## Expected Results

"emails": ["adam.smith@example.com"]

## Actual Results

"emails": {"0": "adam.smith@example.com"}

## Steps to Reproduce

Just copy my collection and add an array of strings

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: v14 / 0.62.2
- Client OS & Version: iOS 14

**Comment by kraenhansen** [comment]
I'd suggest you try upgrading to [Realm JS v6.1.0](https://github.com/realm/realm-js/blob/master/CHANGELOG.md#610-release-notes-2020-08-27) where we released a fix to make `Collections` and `Results` serialize in a nicer way. Specifically we added an enhancement:
> toJSON() implemented for Realm.Collection, to return a nicer serializable Array. (#3013)

Please reopen this issue (or create a new) if it persists after updating Realm JS to the latest version.
In that case, it would be great if you could share the piece of code producing this object (I suppose you're calling `console.log` on an object, but I'm not sure).
