### ISSUE TITLE
[6.1.0] Bad state message (STATE) when trying to open sync realm, [6.1.1, 6.1.2] crash on Windows

### ISSUE THREAD

**Issue by RosenTomov** [realm/realm-js#3219]
## Goals
Be able to open all sync realms. I've noticed this only during development on our local machines.

## Actual Results
Most of our instances are returning
```[{\"message\":\"1\",\"errorCode\":1},\"Bad state message (STATE)\"]```

Realm 6.1.1 crashes instead. (Process finished with exit code -1073741819 (0xC0000005) - file system error?)

## Steps to Reproduce

Just open a synced realm locally:
```
const realm = await Realm.open(databaseOptions);
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.0 & 6.1.1 (crashes)
- Node or React Native: 12.18.3
- Client OS & Version: Windows 10 64 bit pro
- Which debugger for React Native: None

**Comment by kraenhansen** [comment]
@RosenTomov would it be possible for you to share (parts of) your `databaseOptions` object? This would help determine what schema you're using and what kind of server you're connecting to.

> Most of our instances are returning
> [{\"message\":\"1\",\"errorCode\":1},\"Bad state message (STATE)\"]

What are you referring to here? Where are you reading this message?

**Comment by RosenTomov** [comment]
```
  sync: {
    user: User {},
    fullSynchronization: true,
    url: realmURL
  },
  schema: [
    { name: 'someName', primaryKey: 'Id', properties: [Object] },
    ...
  ]
}

```

I'm getting `Bad state message (STATE)` in my console/logger, right when `await Realm.open()` is called.

**Comment by RosenTomov** [comment]
6.1.2 also crashes on windows, might not be related Bad state message (STATE).

**Comment by RosenTomov** [comment]
Just tested it on macOS Catalina 10.15.6, doesn't seem to crash, I believe some issue with was introduced with 6.1.1 on Windows.

**Comment by RosenTomov** [comment]
After multiple clean restarts (deleting realm-object-server), 6.1.2 fired up without crashing.
