### ISSUE TITLE
Realm return empty object in release apk and when debug mode off

### ISSUE THREAD

**Issue by waohwaohwaoh** [realm/realm-js#3225]
## Goals

Create app on rn-0.63, react-16.13.1 and install realm v6.0.4

## Expected Results

Apps works and all libraries updated.

## Actual Results
I have 2 models and I import their in index.ts file 
![Снимок экрана 2020-09-16 в 11 57 28](https://user-images.githubusercontent.com/30194400/93315662-f8c5c880-f813-11ea-856b-0899e5534c92.png)
I use their in next code under the name **schemaV1** 
import schemaV1 from './schemas/v1';
export default [
    {schema: schemaV1, schemaVersion: 1}
]
and next i open Realm connection
Realm.open(schemas[schemas.length - 1]).then((realm: Realm) => {
        Alert.alert(JSON.stringify(realm))
});
in debug mode all works fine, but if debug mode is disabled(Android and iOS) or I launch release apk in Android (iOS not tested) 
Realm.open(schemas[schemas.length - 1]).then((realm: Realm) => {
        Alert.alert(JSON.stringify(realm))
}); 
return in console empty object.
![image](https://user-images.githubusercontent.com/30194400/93327212-b061d700-f822-11ea-8247-0b127948b663.png)
![image](https://user-images.githubusercontent.com/30194400/93327309-cf606900-f822-11ea-993a-a581479ac463.png)
![image](https://user-images.githubusercontent.com/30194400/93327288-c66f9780-f822-11ea-869a-ab7c2786e378.png)

 I saw past problem https://github.com/realm/realm-js/issues/2984 and tried what is written there, but it is not decided my problem

## Steps to Reproduce
react-native init project
npm install realm

then add in index.js:
Realm.open({}).then(res => alert(JSON.stringify(res)));

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.4
- Node or React Native: 12.8.0 and 0.63
- Client OS & Version: Windows 10 and macOs catalina 10.15.2
- Which debugger for React Native: None, only standard chrome

**Comment by kraenhansen** [comment]
Since you're not using a synchronized Realm, I don't see a reason to use the `Realm.open` static method.
Can you verify that this issue persists if you use the Realm constructor directly?

```javascript
const config = schemas[schemas.length - 1]; // I believe this is your "latest" configuration (with a "schema" property), right?
const realm = new Realm(config);
```

What other steps do I need to complete to reproduce the bug?
How specifically are you building / running the app with debug mode off and the release APK? I.e. are you using Android Studio or the react-native-cli for this?

**Comment by ASakkeer** [comment]
I too facing the same issue after updating realm. I degrated the version, it's working fine. But, I need the solution for latest version issue. If anyone have an idea, let us know.

**Comment by ProfessionalAmateur** [comment]
@ASakkeer What version did you downgrade to?
