### ISSUE TITLE
React Native Android: Fatal signal 11 - fault addr

### ISSUE THREAD

**Issue by djinely** [realm/realm-js#3226]
## Goals

Write to realm db

## Expected Results

Successful write

## Actual Results

<img width="833" alt="Screen Shot 2020-09-10 at 10 50 00" src="https://user-images.githubusercontent.com/11662157/93337792-4cdfa580-f832-11ea-9e6f-4089f0685d5f.png">

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.2
- Node or React Native: 0.62.2
- Client OS & Version: Android 10
- Which debugger for React Native: Android Studio Logcat

**Comment by kneth** [comment]
@djinely Do you expect it to be the same as #3224?

**Comment by djinely** [comment]
@kneth the error for android is less clear to us.
Is it also related to accessing objects in a query result?

**Comment by kraenhansen** [comment]
@djinely I'm afraid we need more information to reproduce this.
A small repository reproducing this would be great, a piece if code and an explanation what leads up to this crash would also be help.
