### ISSUE TITLE
window cannot detect the change of realm file

### ISSUE THREAD

**Issue by Jugging** [realm/realm-js#3230]
when add or delete a data , macOS can detect  the change of realm file but window 10  or git cannot

**Version of Realm and Tooling**
Realm JS SDK Version: 6.1.0
Node or React Native: Electron 8.1.1

**Comment by kraenhansen** [comment]
We need more information to reproduce this.

Specifically what steps do I need to perform to reproduce this?
Can you share a repository with code that reproduce this issue?
