### ISSUE TITLE
Can't fetch data from MongoDB Atlas cluster (linked from Realm) in React Native

### ISSUE THREAD

**Issue by HuseyinSaidKoca** [realm/realm-js#3237]
I want to use fetched data from Realm in my React Native application. I linked my Atlas cluster to Realm. I did anonymous authentication ([with this document][1]) and there is no problem while connecting to Realm.

As you can see:
 - [These are my logs][2]
 - [These are connected users to my database][3]
 - [Details of connected user][4]
 - [Details of log][5]

But the problem begins after that. I can't fetch any data from my database because of this error:

    [TypeError: user.remoteMongoClient is not a function. (In 'user.remoteMongoClient("mongodb-atlas")', 'user.remoteMongoClient' is undefined)]

I'm using this code to test the connection to my database:

```js
const appId = "[appId]"; 
const appConfig = { id: appId, timeout: 10000};

async function run() {
  let user;
  try {
    const app = new Realm.App(appConfig);
    user = await app.logIn(Realm.Credentials.anonymous());
    const mongoClient = await user.remoteMongoClient("mongodb-atlas");
    const mongoCollection = await mongoClient
      .db("okul")
      .collection("ogrenciler");

    const number_of_documents = await mongoCollection.count;
    console.log(number_of_documents);

  } 
  catch(err) {
    user.logOut();
    console.log(err);
  }
}
run().catch(console.dir);
```

So, I think that the problem is with `remoteMongoClient`function (`mongodb-atlas` is my service name). What would I use instead of this function?

I searched for it but I didn't find any solutions.

  [1]: https://docs.mongodb.com/realm/authentication/anonymous/
  [2]: https://i.stack.imgur.com/K96aH.png
  [3]: https://i.stack.imgur.com/dfnts.png
  [4]: https://i.stack.imgur.com/bujWR.png
  [5]: https://i.stack.imgur.com/OwSaw.png
  [6]: https://i.stack.imgur.com/VE6Uw.png

**Comment by neopit** [comment]
Same for. Each time I try to get data the app is crashing.

**Comment by steffenagger** [comment]
Could you try updating to `realm@10.0.0-beta.13` & use `mongoClient` instead of `remoteMongoClient`, e.g.:
```ts
const mongoClient = await user.mongoClient("mongodb-atlas");
```

**Comment by kneth** [comment]
I am close the issue. If you experience the issue after follow [this comment](https://github.com/realm/realm-js/issues/3237#issuecomment-695969375), please create a new issue.
