### ISSUE TITLE
Memory issues using Realm JS

### ISSUE THREAD

**Issue by DanielYapiko** [realm/realm-js#3246]
Hello everyone,

We are facing some performance issues recently on our application and we have the feeling it's all related with realm. 

It's a game that works with slots, so each time a new slot is created we do a massive creation of data in the tables. What we have found is that the creating of each slot increases the memory in use 20mb (the second increases 50mb, the third 100mb...), but after close and open the app the space allocated by realm is just 500-800kb. 

I think all those mb are references to all objects we have created, and I am wondering how we could clean those mb. The problem we have is that users that creates several slots without closing the app could get +300mb in memory consumption, which is a problem on some devices.

We have been investigating about compacting the data using realm.compact() but does not work for us, it only works each time we reopen the app (using shouldCompact method).

Is there any way we can reduce that cache memory or clean the memory usage?

Thanks a lot.

## Version of Realm and Tooling

- Realm JS SDK Version: 6.0.1
- Node or React Native: 0.62.6
- Client OS & Version: iOS 13 (simulator) + Android 10
- Which debugger for React Native: React Native debugger

**Comment by steffenagger** [comment]
Hello @DanielYapiko, could you supply some information on how/when you open & close the Realm in your app?

**Comment by kneth** [comment]
I am closing the issue since we have any new information.
