### ISSUE TITLE
Uncaught Error: Unable to serialize value from another Realm

### ISSUE THREAD

**Issue by JamesWatling** [realm/realm-js#326]
Hi, on attempting to delete a collection using realm I am getting 

```
rpc.js:126 Uncaught Error: Unable to serialize value from another Realm
```

The code I am running looks like the following:

```
  const allOfModel = realm.objects(model);
    if (allOfModel.length) {
     realm.write(() => {
       realm.delete(allOfModel);
      });
```

**Comment by appden** [comment]
@JamesWatling your `realm` variable seems to represent a different Realm than `this.realm()`. If you changed `this.realm()` to be `realm` it would probably work, but you should probably make sure you aren't accidentally creating two different Realms when you really only want one.

**Comment by JamesWatling** [comment]
Thanks @appden, that was a typo in the code (refactored for the issue without testing :( ) 

But it ends up I was returning a new instance, and adopting a Singleton pattern solved my problem.

Thanks
