### ISSUE TITLE
Realm sync - Error: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by RosenTomov** [realm/realm-js#3263]
## Goals & Expected Results
Have realm sync work.

## Actual Results
I started getting the following error:
```
Error: getaddrinfo EAI_AGAIN {url_to_our_sync_realm}
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:120:14)
```
Ream is inaccessible, a server restart fixes it. We haven't had any issues until the start of this week.

## Steps to Reproduce
Not sure how exactly.

## Code Sample
```
  sync: {
    user: User {},
    fullSynchronization: true,
    url: realmURL
  },
  schema: [
    { name: 'someName', primaryKey: 'Id', properties: [Object] },
    ...
  ]
}
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.2
- Node or React Native: Node 12.8.3
- Client OS & Version: Amazon Linux AMI 4.15.2 64bit
- Which debugger for React Native: None

**Comment by geragray** [comment]
@RosenTomov could you please if you are using the self-hosted version of Realm Object Server against which sync does not work? If yes, it would be better to ask this question in our support portal https://support.realm.io/support/home.

**Comment by RosenTomov** [comment]
@geragray We're using legacy Realm, not MongoDB Realm and not self hosted. I've created a support ticket anyway.

**Comment by geragray** [comment]
@RosenTomov I spoke with our support team, it seems that they are got the same issue via our support portal. I will close this ticket for now, but please reopen it if you will not get it resolved through the next few days.
