### ISSUE TITLE
Pod Install hung on Installing RealmJS (6.0.4)

### ISSUE THREAD

**Issue by joconnor-dev** [realm/realm-js#3274]
```traceroute: Warning: static.realm.io has multiple addresses; using 104.17.151.91
traceroute to static.realm.io (104.17.151.91), 64 hops max, 52 byte packets
1  testwifi.here (192.168.86.1)  7.389 ms  5.574 ms  6.235 ms
2  142.254.217.21 (142.254.217.21)  19.296 ms  17.717 ms  19.249 ms
3  agg63.sodsny0302h.northeast.rr.com (24.58.233.69)  34.152 ms  34.143 ms  33.858 ms
4  agg59.rochnyei02r.northeast.rr.com (24.58.52.16)  24.500 ms  24.771 ms  17.543 ms
5  be28.rochnyei01r.northeast.rr.com (24.58.32.74)  25.353 ms  24.368 ms  28.152 ms
6  bu-ether15.chcgildt87w-bcr00.tbone.rr.com (66.109.6.72)  36.644 ms
    bu-ether13.tustca4200w-bcr00.tbone.rr.com (66.109.6.2)  36.767 ms
    bu-ether15.chcgildt87w-bcr00.tbone.rr.com (66.109.6.72)  32.684 ms
7  bu-ether11.nycmny837aw-bcr00.tbone.rr.com (66.109.6.24)  45.975 ms  46.903 ms
    bu-ether17.atlngamq47w-bcr01.tbone.rr.com (66.109.6.94)  44.697 ms
8  66.109.5.119 (66.109.5.119)  41.270 ms  38.037 ms  43.577 ms
9  * * *
10  * 104.17.151.91 (104.17.151.91)  41.663 ms *
```
I have 455Mbps download speeds and it's been hung on `Installing RealmJS (6.0.4`) more specifically -- `Downloading realm-sync-cocoa05.0.14.tar.gz` (when using --verbose) for almost 2 hours. 

Normally I have no issues when running pod install. All of the other engineers I work with are having the same issue. I tried to download it in Chrome and it's estimated time to complete was 2 hours. I did multiple tests on my network and I'm getting my normal download speeds and so did the engineers I'm working with. All of us have no network issues.

**Comment by fronck** [comment]
@joconnor-dev I've just tested the download, and I get ~10MB/sec download speed.  Can you please test again?
Also, I'm assuming that the filename (`realm-sync-cocoa05.0.14.tar.gz`) is a typo?  It should be `realm-sync-cocoa-5.0.14.tar.gz` (`-` as opposed to `0`).

**Comment by yazmnh87** [comment]
I thought mine was stuck too, just took a while to finish

**Comment by joconnor-dev** [comment]
@fronck sorry for the delay — I’m still having to wait an hour for Realm to finish. Not sure where the bottleneck is but it’s happening to my entire team, and we’re all located in different cities across the US.

**Comment by fronck** [comment]
@joconnor-dev @yazmnh87 We haven't been able to reproduce this issue ourselves.  Can you confirm whether you're still seeing it?

**Comment by mirkodrummer** [comment]
I'm facing the same issue when running pod install --verbose
```
-> Installing RealmJS (10.0.1)
 > Running prepare command
   $ /bin/bash -c  set -e ./scripts/xcode-download-realm.sh ./scripts
   Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
     SYNC_ARCHIVE: 'realm-sync-cocoa-10.0.0.tar.gz',
     SYNC_ARCHIVE_ROOT: 'core' }
   Resolved options: { platform: 'ios', sync: true }
   No lockfile found at the target /Users/mirkomariani/Projects/digitalcataloguern/node_modules/realm/vendor/realm-ios, proceeding.
   Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-10.0.0.tar.gz
   Downloading realm-sync-cocoa-10.0.0.tar.gz
```

It stays there forever, the download seems really slow. I'm located in EU.
