### ISSUE TITLE
NodeJS SDK $project syntax? (mongo query projections)

### ISSUE THREAD

**Issue by johnsaigle** [realm/realm-js#3275]
## Goals

(copied from SO post https://stackoverflow.com/questions/63942993/mongodb-realm-nodejs-sdk-project-syntax)

I'm trying to do a simple query where some collection data is returned. I want to filter out the `_id` field in the results.

From my understanding (based on the [documentation](https://docs.mongodb.com/realm/node/mongodb/#project-document-fields)) the syntax to do so should look like this:

```
myCollection.findOne(
        { name: hostName },
        { $project: { _id: 0 } }
)
```

However when I do this the filter has not been applied, e.g.:

```
{
  _id: XXXXXXXXXXXXXXXXXXXX,
  name: 'the name',
  ...
}
```

Can anybody point me in the right direction?

## Expected Results

Receiving a filtered query result
## Actual Results

The entire query was returned.

## Steps to Reproduce

Use the sample code above in your own database. Try to use a projection to filter a query.

## Version of Realm and Tooling

- Realm JS SDK Version: `10.0.0-beta.12`
- Node or React Native: Node

**Comment by steffenagger** [comment]
Hello @johnsaigle, I completely understand your confusion - it seems the docs & SDK are not currently aligned.
I believe it's `projection` instead of `$project`, as:

```js
myCollection.findOne(
  { name: 'find me' },
  { projection: { _id: 0 } }
)
```

**Comment by johnsaigle** [comment]
Thanks for the reply. I'll test this when I'm able and follow up here.

Is there a repository for the MongoDB documentation? If so I'm happy to cross-post this issue there.

**Comment by kneth** [comment]
@johnsaigle If you go to https://docs.mongodb.com/realm/node/mongodb/, you can leave a comment by clicking "No" to "Was this page useful?". The docs team will then be notified.

**Comment by johnsaigle** [comment]
@kneth @steffenagger The syntax is still not filtering my result. Here's an example from another query.

```javascript
const result = await accounts.findOne(
      { username: username },
      {
        projection: {
          _id: 0,
          password: 0,
        },
      }
    );
if (!result) {
      res
        .status(404)
        .send({ err: `No user profile found with the username ${username}` });
      return;
    }
    res.status(200).send({ result });
```

I would expect this query to remove the `_id` and `password` fields from my results. However, I get this result:

```
{ result:
   { _id: '5f6108db4edc244a4844cbcd',
     email: 'john@example.com',
     password:
      'XXXXXXXXXXXXXXXXXX',
     username: 'johns',
}
```

**Comment by johnsaigle** [comment]
Ah I have a correction and found a curious nuance.

In my above example, changing the return line from

```javascript
    res.status(200).send({ result });
```

to

```javascript
    res.status(200).send(result);
```
fixed my problem. (The difference is the curly braces)

Any idea why including curly braces `{}` would change the result of the information returned? 
I assumed the projection would exclude the results at the database layer and that by the time it was back in the Express environment that there would be no way to access these fields.

**Comment by steffenagger** [comment]
> Any idea why including curly braces `{}` would change the result of the information returned?
> I assumed the projection would exclude the results at the database layer and that by the time it was back in the Express environment that there would be no way to access these fields.

@johnsaigle first, sorry for the late reply.
I've just tested this, and `result._id` is `undefined` with `{ projection: { _id: 0 } }`... could it be some caching in express, or the rest-client, giving you these results?
