### ISSUE TITLE
Cannot make Google credentials while debugging: "_realm.default.Credentials.google is not a function"

### ISSUE THREAD

**Issue by Mattadore** [realm/realm-js#3279]
## Goals

I wanted to authenticate with google while using VSCode debugger.
## Expected Results

Authentication with google
## Actual Results
It crashed :(

I got:
`TypeError: _realm.default.Credentials.google is not a function`

## Steps to Reproduce

Construct a google credentials object with `
Realm.Credentials.google(serverAuthCode)
` in the beta branch and run it with the VSCode debugger. The _realm.default.Credentials object instance does not have a "google" property at all. It works fine when doing a normal development build, but it breaks specifically in the vscode debugger. It HAS "facebook" and "apple" properties just not a "google" one as confirmed by said debugger.

## Code Sample

Realm.Credentials.google("googlecode")

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.13
- Node or React Native: React Native
- Client OS & Version: Ubuntu 18.03
- Which debugger for React Native: VSCode

**Comment by kneth** [comment]
Solved by https://github.com/realm/realm-js/pull/3265 and we hope to get it merged and release soon.

**Comment by Mattadore** [comment]
Thank you, I missed that PR. 🙏
