### ISSUE TITLE
Add method Realm.objectForPrimaryKey(objectType, primaryKey)

### ISSUE THREAD

**Issue by esutton** [realm/realm-js#328]
I would like to see a simple method to retrieve an object by primary key.

Ideally something similar to this would be simple to use.

`let myObject = results[ 'keyName' ];`

Or maybe what Swift developers have:

`public func objectForPrimaryKey<T: Object>(type: T.Type, key: AnyObject) -> T?`
https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm19objectForPrimaryKeyuRdq_CS_6Object_FS0_FTMq_3keyPSs9AnyObject__GSqq__

Thank you for making realm easy to get going with on react-native!

**Comment by alazier** [comment]
I agree we should add this to have parity across our apis for different languages. Until we add this you can do something like `var object = realm.objects(ObjectType).filtered('id = ' + key)[0]`
