### ISSUE TITLE
JWT connection impossible when react-native-debugger is open

### ISSUE THREAD

**Issue by euZebe** [realm/realm-js#3285]
## Goals

Use [react-native-debugger](https://github.com/jhen0409/react-native-debugger) a app which uses Realm.

## Expected Results

The app should connect successfully to Realm when RN debugger is open and debug is enabled.

(considering the application is able to connect to Realm when RN debugger is closed)

## Actual Results

> TypeError: _realm.default.Credentials.jwt is not a function

Please note that this warning does not occur when the debugger is closed.

## Code Sample
```javascript
  const credentials = Realm.Credentials.jwt(jwt)
  const user: Realm.User = await realmApp.logIn(credentials)
```
## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-rc.1
- Node or React Native: RN
- Client OS & Version: macOS 10.15.7
- Which debugger for React Native: https://github.com/jhen0409/react-native-debugger

**Comment by kneth** [comment]
@euZebe Thank you for reporting. It is an oversight, and we will add it.
