### ISSUE TITLE
App crashes sliently when adding Realm as a react-native dependency

### ISSUE THREAD

**Issue by gustavo-dev** [realm/realm-js#3288]
The title says it.

## Goals

I'm trying to implement Realm in my React Native App

## Expected Results

App loads successfully

## Actual Results

The app crashes silently, without any errors, it just closes

## Steps to Reproduce
EDIT: I'm just installing realm, idk what's happening because there aren't any logs 

## Code Sample

I don't think I have something to put here 

## Version of Realm and Tooling

- Realm JS SDK Version: latest
- Node or React Native: 4.12.0
- Client OS & Version: Windows 10
- Which debugger for React Native: None

**Comment by gustavo-dev** [comment]
UPDATE: I created a new project from scratch and added `realm` and it works fine. I have no idea what's happening because there aren't any logs when my app crashes

**Comment by kneth** [comment]
@gustavo-dev I will close the issue. If you experience it again, please create a new one. Our experience is that RN is caching a lot to provide a hot reloading, and it is often required to clear the caches when installing a new package or upgrading existing ones.

**Comment by gustavo-dev** [comment]
@kneth I just tried `watchman watch-del-all`, then removing `node_modules` and reinstalling it and resetting metro cache with `yarn start --reset-cache`, but the crash stills happens
