### ISSUE TITLE
Backup and restore from iCloud React-native

### ISSUE THREAD

**Issue by chittasec** [realm/realm-js#3289]
What should be the approach for back-up / restore RealmDB to iCloud in react-native ?
I tried below .

* Close the DB .
* Backup Realm DB file ( just one file ) to iCloud.
Restore
* Copy back the realm file from iCloud and replace main file with it .

The file gets copied back and DB can open . But somehow I keep seeing old data .
What can be the issue ?

Thanks,
Chitta

**Comment by kneth** [comment]
@chittasec It is important that all Realm instances are closed (but you say "Close the DB" so I guess you know that).

It might be a good idea to use [`Realm.writeCopyTo()`](https://realm.io/docs/javascript/6.0.0/api/Realm.html#writeCopyTo) to create the backup. As part of your restore, it might be good to delete all files associated with a Realm. You can use [`Realm.deleteFile()`](https://realm.io/docs/javascript/6.0.0/api/Realm.html#.deleteFile).

> But somehow I keep seeing old data

I am a bit curious what you are saying here. Did you write/modify/delete objects between doing the backup and the restore?

**Comment by chittasec** [comment]
Thank you Kenneth .
For closing the DB : I am opening the Realm and doing realm.close () .
Realm.writeCopyTo()  is good suggestion . This creates one file ?
How do I restore from this backed up file ? Is there another API to do this ?

**Comment by kneth** [comment]
> For closing the DB : I am opening the Realm and doing realm.close () .

:+1:

> Realm.writeCopyTo() is good suggestion . This creates one file ?

Yes, it will create a new (compacted) file.

> How do I restore from this backed up file ? Is there another API to do this ?

We don't have an API for it. You can copy the file from iCloud to your app's document directory before opening it as a Realm.

**Comment by chittasec** [comment]
I tried below.
Always get error "file doe snot exist". Because the  writeCopyTo takes time and before it is finished , next line executes to move it to cloud .
Since writeCopyTo does not have promise or callback , what is the best way to use it ?


     realm.writeCopyTo(tmpDBPath);
      const sourceUri = {
        path: tmpDBPath,
      };
      const mimeType = null;
      const scope = 'visible';

      RNCloudFs.copyToCloud({
        sourcePath: sourceUri,
        targetPath: "DBbackup"
        mimeType: mimeType,
        scope: scope,
      })

**Comment by kneth** [comment]
@chittasec `Realm.writeCopyTo()` is a synchronous method so the copy is written once the call returns. I wonder if `path: tmpDBPath` is correct - is `tmpDBPath` an absolute path?

**Comment by chittasec** [comment]
Hello Kenneth, 

 I guess something to do with caching . I did the closing . Did Realm.deleteFile (). I even deleted all ".realm" files using react-native- fs in the same program flow .  At this point, I still can access data / insert data . Is the old DB is cached somewhere and I need to clear that before restoring ?

Thanks,
Chitta

**Comment by kneth** [comment]
> I did the closing
> At this point, I still can access data / insert data

Are you able to call `Realm.write()` after closing your Realm?

**Comment by chittasec** [comment]
Yes, I am able to .
I think something like the below thread is happening . 
https://stackoverflow.com/questions/45772154/replace-realm-file-while-app-is-running
How do I open in autorelease mode in React-native ?

**Comment by kneth** [comment]
You need to ensure that you have closed all Realm instances.
