### ISSUE TITLE
[TS] Realm JS breaks when using objects with schemas instead of schemas only

### ISSUE THREAD

**Issue by Dids** [realm/realm-js#3291]
## Goals

I wanted to use custom objects with schemas, passing these to the Realm configuration, like so:
```ts
const FooSchema: Realm.ObjectSchema = {
  name: 'Foo',
  primaryKey: 'Id',
  properties: {
    Id: 'int'
  }
}

class Foo {
  static schema: Realm.ObjectSchema = FooSchema
  ...
}
```

Additionally, I can neither implement `Realm.ObjectType` or extend `Realm.Object`, due to various errors these both produce at startup.

Ideally this would be fixed by allowing us to implement or extends a type, which would create our custom objects with the `Realm.Object` prototype, unless it's possible for this to be fixed internally in Realm.

The documentation should also be updated, if/when this gets fixed.

## Expected Results

Realm should work fine when passing in either schemas or objects with schemas, as per the [documentation](https://realm.io/docs/javascript/latest/).

## Actual Results

The schemas get correctly created in Realm and everything seems fine at first glance.

However, all resulting objects will have the `Object` prototype, instead of `Realm.Object`, which breaks `.entries()`, `.keys()` and `.toJSON()`, as they're never created/assigned and remain undefined.

## Steps to Reproduce

Pass custom objects with schemas to a Realm configuration, then try querying object data and calling for example `resultObject.entries()`, which will be undefined.

## Code Sample

Code sample included above should be enough, as this is very easy/trivial to reproduce.

## Version of Realm and Tooling

- Realm JS SDK Version: v6.1.3
- Node or React Native: v12.16.3
- Client OS & Version: macOS 10.15.7

**Comment by steffenagger** [comment]
Hi @Dids 

> Additionally, I can neither implement Realm.ObjectType or extend Realm.Object, due to various errors these both produce at startup.

Could you elaborate on, or copy/paste these errors here?

I've attached a small test app ([ts-node-test.zip](https://github.com/realm/realm-js/files/5327104/ts-node-test.zip)) with your example (though with added `extends Realm.Object` to `Foo`) - it runs on node `v12.16.3` here.
To test, extract the zip & run `npm i && npm start` (is this solution throwing errors as well? If not, I think the issue might relate to `tsconfig.json`).

**Comment by Dids** [comment]
Thank you, your example works fine, however I still get an error in my own project, which is only triggered when I try to access the object from Realm Cloud. No linting or runtime errors, until an object is actually created.

```ts
TypeError: Class constructors cannot be invoked without 'new'
        at new MyClass (/path/to/models.ts:22:42)
```

I'm not manually creating objects by using `new` either, so it's happening when Realm creates a new instance of it:
```ts
const result = this.realm.objectForPrimaryKey('MyClass', id)
```

Will keep testing if it's something specific to my `tsconfig.json`, or if the issue is somewhere else.

**Comment by Dids** [comment]
Since this is not an issue in literally _anything_ newer than `ECMAScript 5` (which is from 2009), I'll go ahead and close this. Thank you again for helping track this down!

Slightly annoyed how even modern guides for various things (TypeScript included) still mention targeting ES5 for compatibility reasons, even though virtually everything out there supports newer standards.

**Comment by steffenagger** [comment]
Thanks for the helpful updates @Dids!
I'll discuss with the team how/if we can fix this, or add it to the documentation - glad you got up & running.
