### ISSUE TITLE
Realm Constructor returning empty object

### ISSUE THREAD

**Issue by gustavo-dev** [realm/realm-js#3304]
## Goals

Implement Realm in my app

## Expected Results

Get Realm instance

## Actual Results

Constructor Returning empty object

## Steps to Reproduce

Instantiate Realm (`new Realm(config)`

## Code Sample
schemas:
```javascript
export default class Playlist {
    static schema = {
        name: 'Playlist',
        primaryKey: 'id',
        properties: {
            id: {type: 'int', indexed: true},
            title: 'string',
            songs: 'Song[]',
            author: 'string',
            isDownloaded: {type: 'bool', default: false},
        },
    }
}

export default class Song {
    static schema = {
        name: 'Song',
        primaryKey: 'id',
        properties: {
            id: {type: 'int', indexed: true},
            title: 'string',
            url: 'string',
            artwork: 'string',
            artist: 'string',
            stringId: 'string',
            isSlowed: 'bool',
        },
    }
}

```

class 
```javascript
class X {
    constructor() {
        console.log("Creating Realm instance: ")

        this.realm = new Realm({
            schema: [Playlist, Song],
            schemaVersion: SCHEMA_VERSION,
        })

        console.log(this.realm) // Logs: {}
    }
}
```
console: 
![image](https://user-images.githubusercontent.com/42685889/95239339-300b1200-07e1-11eb-9da5-67a4a02a0fce.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.3
- Node or React Native: 4.12.0
- Client OS & Version: Win 10
- Which debugger for React Native: None

**Comment by kneth** [comment]
`new Realm()` returns an object which is managed by C++, and it is expected that looks like an empty object. But `this.realm instanceof Realm` will be true.

If you start `node` and type `const Realm = require("realm");`, you can try to type `realm.` and press TAB. You will then see all the properties and methods :smile:.

**Comment by gustavo-dev** [comment]
Oh, I'm sorry, didn't know about this 🤣. But one more thing, I created this issue mainly because when calling `this.realm.object('Playlist')` nothing is returned, but I think I'll create a new one.
