### ISSUE TITLE
how t o sync restapi with my realm db

### ISSUE THREAD

**Issue by gmchaturvedi1** [realm/realm-js#331]
I am new to realm db .can u please guide how can i sync my db on internet connection with rest api.

Reagrds
G M Chaturvedi

**Comment by alazier** [comment]
Realm allows you to easily create objects from JSON, so as long as your model has the same key names as your JSON objects then all you need to do is call `realm.create(ObjectType, json);`

https://realm.io/docs/react-native/latest/#nested-objects

If you have a primary key you can update existing objects using JSON consisting of the primary key value and just the properties you want to update:

https://realm.io/docs/react-native/latest/#updating-objects

At the moment you need to do your own bookkeeping to keep track of what objects have already been fetched and which need to be retrieved from the server. There are multiple ways you could go about doing this.

**Comment by ajithamp** [comment]
@alazier 
 I want to use var value in bookName like following but i did it throws error any solution for this
let book = Realm.objects('Book');
let var = 'realm';
let book1 = book.filtered('bookName=var');

**Comment by alazier** [comment]
@ajithamp you can use a query parameters for this:

```let book1 = book.filtered('bookName=$0', var);```

**Comment by ajithamp** [comment]
@alazier 
I need one more query for retrieve user input value from database.
Suppose I enter  username and password i want to validate user details from database record.
I using realm react native.
