### ISSUE TITLE
Linting Rule: Warn about Spread Syntax with Realm.Object

### ISSUE THREAD

**Issue by Frans-L** [realm/realm-js#3310]
## Feature Request

If the spread syntax is used with `Realm.Objects`, the result is a just empty object.

e.g.
```javascript

const copied = { ...someRealmObject } // 'copied' will be empty, because spread syntax is not working
```

It should be possible to implement, with Typescript and Eslint, a rule that warns about spreading `Realm.Object`s. 

So, it would be awesome, if there was an ESLint rule that gave an error if spreading an object that is extending `Realm.Object`. This ESLint rule would make realm-js more typesafe :)

This is, of course, is just a nice to have a feature 😄

**Comment by nirinchev** [comment]
Even nicer would be to fix the implementation so that it works with the spread operator 😜

**Comment by kneth** [comment]
@Frans-L Thanks for the suggestion.

**Comment by ws333** [comment]
Check this package https://github.com/Waltari10/eslint-plugin-ban-realm-spread#readme

Shared here https://github.com/realm/realm-js/issues/2844#issuecomment-1112993513
