### ISSUE TITLE
add cache download ios file

### ISSUE THREAD

**Issue by hengkx** [realm/realm-js#3313]
## Goals

I come from China. Every time I install the dependency, I need to download it again without any change in the version. The speed is very slow. I hope I can cache it. Thank you very much.

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
@hengkx I believe it is already possible - see https://github.com/realm/realm-js/issues/2501

**Comment by hengkx** [comment]
> @hengkx I believe it is already possible - see #2501

Thank you for your reply. I didn't understand what that meant.
 I hope it is similar to the function of electron. When my computer downloads it once, if I use this version again, it will go to local cache directly. Because downloading in China is very unstable and slow.

**Comment by kneth** [comment]
>  I didn't understand what that meant.

You need to set up a local mirror/cache of npm.
