### ISSUE TITLE
Missing Realm constructor. Did you run "pod install"? error while running application for macos(react-native-macos)

### ISSUE THREAD

**Issue by panorbit** [realm/realm-js#3317]
## Goals

Trying to run an app that uses realm for macOS using react-native-macos. The application works perfectly on android and iOS. However when I try to run for macOS it thrown the error "Missing Realm constructor". 

Followed the steps for resolution given here - https://realm.io/docs/react-native/latest/#missing-realm-constructor. But it wasn't helpful

##  Stack Trace
![Screenshot 2020-10-07 at 12 58 01](https://user-images.githubusercontent.com/64459610/95485826-e02e7580-09af-11eb-81ff-21aa2d346749.png)

Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting

getContext
    index.bundle?platform=macos&dev=true&minify=false:146885:23
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:146938:26
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:145682:49
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:145497:37
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:110943:34
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:110746:27
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:107097:52
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
<unknown>
    index.bundle?platform=macos&dev=true&minify=false:1344:47
loadModuleImplementation
    index.bundle?platform=macos&dev=true&minify=false:271:13
guardedLoadModule
    index.bundle?platform=macos&dev=true&minify=false:163:46
global code
    index.bundle?platform=macos&dev=true&minify=false:172251:3

## Version of Realm and Tooling

- Realm JS SDK Version:  6.0.3 or 6.1.4 (tried both)
- React Native: 0.62.2
- Client OS & Version: macOS Catalina(10.15.7)
- Which debugger for React Native: None

**Comment by steffenagger** [comment]
We don't officially support react-native-macos yet, but I believe you can find some input/solutions here: https://github.com/realm/realm-js/issues/2907#issuecomment-641045715
