### ISSUE TITLE
Issue syncing Realm App

### ISSUE THREAD

**Issue by srossi3** [realm/realm-js#3318]
## Goals

I am trying to upload data from a RN app to a Realm and retrieve different data from it.

## Expected Results

I expect the app not to crash when I call open realm and to be able to use CRUD operations with the created and synced realm.

## Actual Results

Every time I call the realm the app crashes and closes without throwing any error.

## Steps to Reproduce

I have simply followed the documentation to use realm in a react native app, getting the schema from the SDK section of realm interface.

## Code Sample
```

import React from 'react';
import { Schema } from './Schemas' //the schema is the one exported from Realm
import {

  View,
  Text,
  TouchableOpacity
} from 'react-native';

import Realm from 'realm';

async function start() {

  const appConfig = { id: 'appID', timeout: 10000 } //appID is substituted with the actual ID in the running code
  console.log(appConfig)
  const app = new Realm.App(appConfig);
  console.log('created app')
  const credentials = Realm.Credentials.anonymous();
  console.log(credentials)
  const user = await app.logIn(credentials);
  console.log(user.id)
  try {
    console.log([Schema])
    const realm = Realm.open({
      schema: [Schema],
      sync: {
        user: user,
        partitionValue: 'name',
      },
    })
    console.log(realm)
  }
  catch (e) { console.log(e) }
}

class App extends React.Component {
  async componentDidMount() {
    start();
  }
  render() {
    return (
      <View><TouchableOpacity><Text>temporary</Text></TouchableOpacity></View>
    )
  }
}
export default App 
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm@10.0.0-rc.1
- Node or React Native: React Native 3.0.0-alpha.7
- Client OS & Version: Android 9
- Which debugger for React Native: Chrome but not working correctly so none

**Comment by kneth** [comment]
@srossi3 I can use `console.log()` in the code. By looking in your log, you might be able to tell us where your app crashes.

One quick comment on your code: `Realm.open()` is an async method. This means that `realm` in your code is a promise (`Promise<Realm>` for a TypeScript developer).

**Comment by srossi3** [comment]
> @srossi3 I can use `console.log()` in the code. By looking in your log, you might be able to tell us where your app crashes.
> 
> One quick comment on your code: `Realm.open()` is an async method. This means that `realm` in your code is a promise (`Promise<Realm>` for a TypeScript developer).

Thank you, it crashes after printing the Schema, so before opening the Realm. Should I change the way I handle the call of Realm.open()?

**Comment by kneth** [comment]
> Should I change the way I handle the call of Realm.open()?

Try to do `let realm = await Realm.open(...);`

**Comment by kraenhansen** [comment]
@srossi3 did you manage to get this working?
