### ISSUE TITLE
Support for data migrations

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#333]
Requested by user http://stackoverflow.com/questions/36022863/how-to-handle-realm-react-native-migrations-and-schemaversion-on-ios

**Comment by jwhitley** [comment]
I'll observe that the single global `schemaVersion` may induce the same problem that the original Rails migrations scheme hit: it creates a version control bottleneck in the codebase for all schema-altering changes.  The simplest case is that of two developers working on schema-altering features at the same time.  For Realm, they would both update to `schemaVersion: 5`, which then becomes a textual and semantic conflict for whichever dev merges second.

This was widely considered to be a big pain, so Rails changed that system to use per-migration datetime-stamps instead (e.g. `20160315170935`) and a migrations table that simply lists every migration that's been performed.  The migration process then runs any migration found that isn't in the table.

**Comment by alazier** [comment]
Thanks for the input @jwhitley . We've discussed approaches similar to what you describe in the past, the only downsides being the need for extra tooling and the requirement that all previous schema be bundled with every new app release. For our other platforms the tooling would be complex as it needs be able to extract the schema from native objects and then store it in another format. And bundling files with apps programmatically isn't trivial (at least on iOS) making the whole process error prone. With the JS binding all of this much easier as we are already represent our schema as JSON and the packager should be able to include our old schemas with the app.

That being said I'm not sure we will build this tooling right off the bat, but what we do build will have the hooks to allow us to add these features when we have the time. Even now you could choose to use a timestamp to represent you `schemaVersion` which would address your main concern. And as long as we allow multiple migrations to be performed sequentially, it seems we could eventually accomplish the rest of what you describe without much difficulty.
