### ISSUE TITLE
How to select single field on RealmJS?

### ISSUE THREAD

**Issue by ezranbayantemur** [realm/realm-js#3343]
Hi there.
I have a data structure with `LOG` schema name, like:

    deviceID: 'test',
    deviceName: 'a1:b2:c3...',
    date: 123123123',
    tableData: ["f1", "f2","f3","f4"]
When I try to retrieve data from RealmDB as `realmDB.objects('LOG')` it returns all of the data field as expected.
Like: 

    [deviceID: 'test', deviceName: 'a1:b2:c3...', date: 123123123', tableData: ["f1", "f2","f3","f4"]]
    [deviceID: 'test', deviceName: 'a1:b2:c3...', date: 123123123', tableData: ["f1", "f2","f3","f4"]]
    [deviceID: 'test', deviceName: 'a1:b2:c3...', date: 123123123', tableData: ["f1", "f2","f3","f4"]]...

But I need only `tableData` field and I have 250k amount of data. So if I map all of the return, it can cause so much laggy problem.
So my asking is like:

    [ 
     ["f1", "f2","f3","f4"]
     ["f1", "f2","f3","f4"]
     ["f1", "f2","f3","f4"]...
    ]
kind of.

Is there any way to get specific column on RealmDB JS? 

*(I've tried find method of mongoDB but it didn't work)*

`"realm": "^6.1.2",`

**Comment by ianpward** [comment]
Realm is lazy loaded so we only pull from disk when you actually access the field, for instance, when binding a field to a view. So LOG.tableData should give you want you need

**Comment by ezranbayantemur** [comment]
Thanks for the quick response @ianpward 
I tried `this.realmDatabase.objects('LOG.tableData');` but it says `Error: Object type 'LOG.tableData' not found in schema.`

Also I tried: 
```
const logs = this.realmDatabase.objects('LOG');
console.log(logs.tableData)
```
it return as `undefined`

Is there anything that I misunderstand?

**Comment by kneth** [comment]
`Realm.objects()` returns all objects (lazy-loaded) of a "table". You have only one "table": `LOG`. This explains the first error.

Since `const logs = this.realmDatabase.objects('LOG');` is all your `LOG` objects, you will have to iterate through them as an array in order to access the `tableData` property (or any other property).

**Comment by ezranbayantemur** [comment]
Yes I know but iterating through 250k data and mapping them is very heavy to device.
So there is no way to do it, right?

**Comment by nurmohammed840** [comment]
@ezranbayantemur  mean that iterate  through  array  would be very expensive...

```js
const logs = this.realmDatabase.objects('LOG');
for (const log of logs) {
   log.tableData // is it right way to access single field? wasn't it expensive?  
}
```
Is it right way to `SELECT tableData` ?

**Comment by nirinchev** [comment]
Iterating over 250k records is going to take time, regardless of whether they are being pulled from the database or are in-memory. The fact that Realm is lazy loading everything, means that `realmDatabase.objects('LOG')` is super cheap - definitely cheaper than an equivalent call in SQLite that has to pull 250k items from the database in memory. Then iterating over them is as about as expensive as iterating over an in-memory collection. Finally, reading properties from the objects is slightly more expensive than reading properties from an in-memory data structure. The overall time complexity of

```
const logs = this.realmDatabase.objects('LOG');
for (const log of logs) {
   let foo = log.someProperty;
}
```

should be the same as an equivalent `select someProperty from LOG` call in SQLite.

**Comment by nurmohammed840** [comment]
But Here is a thing React-native doesn't support worker yet... Iterating over an array in a single threaded language block Main thread. If the same Iteration done by other program or thread. then  JS just use callback when result is ready...

Whatever, I have a stupid question. let say 
```js
schema {
   a : 'string', // about 1 mb of data
   b:  'string', // about 1 mb of data
}
```
There are 10 items in `schema`. So its about total 20 MB of  data.
```js
let array_of_object = realm.objects('schema') // where array.length == 10 and each object is about 2 MB
for (const value of array_of_object) {
   let foo = value.a ;   // some other action...
}
```
So how much data I fetch from disk?
 - 10 MB 
 - 20 MB 
 -  Its depend

**Comment by nirinchev** [comment]
You fetch 10 MB because you only access `a`.
