### ISSUE TITLE
realm crash on ios project

### ISSUE THREAD

**Issue by ArianHamdi** [realm/realm-js#3352]
Hello Realm Team

I followed the guide to install Realm into an RN project but I have problem to build ios project.

I tried nvm installation as well.

Please, Help me to solve the problem.

## Goals

Install Realm JS and build in iOS successfully

## Expected Results

react-native run-ios build succeeds 

## Actual Results

running the script npx react-native run-ios, it shows the following error :

The following build commands failed:
	
```
** BUILD FAILED **
PhaseScriptExecution [CP-User]\ Download\ Realm\ Core\ &\ Sync /Users/arian/Library/Developer/Xcode/DerivedData/Game-cfsdcckzxhmrmzduwmlcvbotmdqr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RealmJS.build/Script-133BA2C435A820095DEA7782067AE912.sh
(1 failure)
```

complete log is here : https://file.io/FA9ZQsZbTaMf

## Steps to Reproduce

1. npx react-native init RealmTest
2. npm install realm
3. cd ios && pod install
4. npx react-native start 
5. npx react-native run-ios 

## Version of Realm and Tooling

- Realm JS SDK Version: Realm : 10.0.1 
- Node or React Native: Node : 14.11.0 and RN : 0.63.2
- Client OS & Version: macOS 10.15.7

**Comment by kneth** [comment]
I cannot access the log file you mention. But my best guess is that it is similar to #2910. If you have white spaces in your folder names, try to use a name without white spaces as I think it is the issue.

**Comment by ArianHamdi** [comment]
> I cannot access the log file you mention. But my best guess is that it is similar to #2910. If you have white spaces in your folder names, try to use a name without white spaces as I think it is the issue.

Thank you so much,
that was the issue I had the white space in the parent folder.
good luck
