### ISSUE TITLE
Realm.App.Sync.url return undefined, connected always true, and no ConnectionNotification triggered

### ISSUE THREAD

**Issue by deckyfx** [realm/realm-js#3354]
opened Realm Sync and following 

https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.Sync.Session.html

and use this code

```
const syncSession = Realm.App.Sync.getSyncSession(
        realmApp().currentUser,
        getCurrentPartitionValue(),
      );
      if (syncSession) {
        syncSession.addConnectionNotification((newState, oldState) => {
          console.log(
            logtag,
            `[SyncSession] [ConnectionNotification] from ${oldState} to ${newState}`,
          );
        });
        syncSession.addProgressNotification(
          'download',
          'reportIndefinitely',
          (transferred, transferable) => {
            console.log(
              logtag,
              `[SyncSession] [ProgressNotification] Downloading ${transferred} bytes of ${transferable} bytes`,
            );
          },
        );
        syncSession.addProgressNotification(
          'upload',
          'reportIndefinitely',
          (transferred, transferable) => {
            console.log(
              logtag,
              `[SyncSession] [ProgressNotification] Uploading ${transferred} bytes of ${transferable} bytes`,
            );
          },
        );
        console.log(
          logtag,
          JSON.stringify(
            {
              partition: getCurrentPartitionValue(),
              config: syncSession.config,
              state: syncSession.state,
              user: syncSession.user,
              url: syncSession.url,
              isConnected: syncSession.isConnected(),
            },
            null,
            4,
          ),
        );
      }
```

Realm.App.Sync.url return undefined, connected always true, and no ConnectionNotification triggered

## Goals

do something when Realm Sync Session connection is down or up

## Expected Results

url contains information on which URL the session synced to
connected and state reflect the actual state
ConnectionNotification callback triggered when the connection changed

## Actual Results

url is undefined
connected always true even when I turned off the wifi and data
ConnectionNotification callback not triggered

```
REALM SYNC] {
    "partition": "5f8528b3b1ecb69402296546",
    "config": {
        "user": {}
    },
    "state": "active",
    "user": {},
    "isConnected": true
}
```

## Version of Realm and Tooling
Realm v10.0.0-beta.13

**Comment by deckyfx** [comment]
Resolved, not an Issue

**Comment by caleb-harrelson** [comment]
> Resolved, not an Issue

Resolved how? I'm also not getting notifications on progress and it would be lovely to know how somebody else that ran into the same problem solved it.

**Comment by kneth** [comment]
@caleb-harrelson Please create a new issue with all request information. It will it easier for us to reproduce and fix it.

**Comment by caleb-harrelson** [comment]
For anybody else having this issue the "problem" for me was that my partition was less than the ~16MB chunks the data is downloaded in and it only gives a progress update once per chunk. I was expecting frequent progress updates, especially since 16MB on mobile can take a long time, but it's apparently a limitation of the sync system?

@kneth, if the progress notifications can't be more frequent then I think the fact that only 16MB chunks trigger a notification should be added to the documentation. It makes things like a progress bar impossible to make look good, so I had to abandon my "new user experience" progress bar and just give an infinite spinner until the ~10MB downloads.

**Comment by kneth** [comment]
@caleb-harrelson Thank you for the update. Your observations are consistent with [a known issue](https://github.com/realm/realm-core/issues/4431).

**Comment by caleb-harrelson** [comment]
Thanks, subscribed to that issue. I'd strongly encourage a documentation update in the meantime.
