### ISSUE TITLE
Mac Catalyst Parser file

### ISSUE THREAD

**Issue by marcosrdz** [realm/realm-js#3359]
realm-js 6.1.0 had these files:
ls node_modules/realm/vendor/realm-ios 

* librealm-parser-maccatalyst-dbg.a
* librealm-parser-maccatalyst.a	
* librealm-maccatalyst-dbg.a
* librealm-maccatalyst.a

relm-js 6.1.1 and after only has:

* librealm-sync-maccatlyst.a

There is no librealm-parser-maccatlyst.a

This blocks me from being able to compile the app.

**Comment by marcosrdz** [comment]
Any updates on this? RealmJS catalyst files on 6.1.0 don't work with Xcode 12.2

**Comment by marcosrdz** [comment]
Still no parser file in the latest release. This is a blocker.

**Comment by Overtorment** [comment]
Any news? Can't use Realm  10.2.0 with Catalyst

**Comment by marcosrdz** [comment]
the xcframework used on 10.3.0 or newer have these folders:

ios-arm64_armv7
ios-arm64_i386_x86_64-simulator

However, Realm used to support Mac Catalyst up until 6.0.0.

An example folder of a xcframework with support for Catalyst would include a folder like this:

ios-x86_64-maccatalyst/

6.0.0 no longer works in the new big sur release, making any Catalyst app using this library crash on runtime.

**Comment by takameyer** [comment]
Catalyst support has been added in 10.6.0.
