### ISSUE TITLE
Must first create RPC session with a valid host

### ISSUE THREAD

**Issue by Muzzamil75** [realm/realm-js#3361]
URGENT

Getting this error when debugging from chrome. Its been a while but issue is not resolved till now.

**Comment by kneth** [comment]
@Muzzamil75 Thank you for reporting.

**Comment by kraenhansen** [comment]
I'm actively working on this, but I'm unable to provide a good ETA since all the work needed is not entirely clear to me at this point in time. I appreciate the patience and will update here as I approach a solution.

**Comment by charleycesar** [comment]
Thanks I'm waiting for this solution.

**Comment by kraenhansen** [comment]
I'm closing this as a duplicate of https://github.com/realm/realm-js/issues/3358 - please follow that issue instead of this.
