### ISSUE TITLE
Bundled Realm file doesn't get copied on physical device [iOS]

### ISSUE THREAD

**Issue by ivangr1** [realm/realm-js#3367]
## Goals

I am trying to bundle a realm file with my iOS app and copy it to Documents folder on app start, then open it and write to it

## Expected Results

Realm copied from app bundle to Documents folder and opened successfully on the physical device

## Actual Results

Realm works fine and gets copied on the XCode simulator devices but it fails to copy on the physical device (I see no data when the app loads)

## Code Sample

```
function copyBundledRealm() {
    const fileName = 'mydatabase.realm';

    /* I use RNFS for file access */
    RNFS.exists(RNFS.DocumentDirectoryPath + '/' + fileName).then(
      async (exists) => {
        if (!exists) {
          try {
            if (Platform.OS === 'ios') {

               /* I've tried this: */
              Realm.copyBundledRealmFiles();
              
              /* ...and this... */
              await RNFS.copyFile(
                RNFS.MainBundlePath + '/' + fileName,
                RNFS.DocumentDirectoryPath + '/' + fileName,
              );
            } else {
               ...
            }
            openRealm(fileName);
          } catch (error) {...}
        } else {
          openRealm(fileName);
        }
      },
    );
  }

  function openRealm(fileName) {
    const config = {
      path: fileName,
      schema: [myschema],
    };
    if (Realm.exists(config)) {
      Realm.open(config)
        .then((realm) => {
          setRealm(realm);
        })
        .catch((error) => {...);
        });
    } 
  }
```

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.2
- Node or React Native: 0.63.2

Both `Realm.copyBundledRealmFiles()` and `RNFS.copyFile()` work fine on iOS simulator but I don't get any results on the physical device which would mean that the realm has not been copied and opened, but also I don't get any errors which is also strange.
I am using Mac in cloud to build my app so I don't have any stack trace from the physical device because I can only test my app on the physical device with TestFlight after I have already uploaded it to the AppStore.

I've put my realm file in the main app folder and it was listed on the Build Phases > Copy Bundle Resources
Is this some issue with XCode bundling files differently in Release mode?
Can you help me?
Thank you!

**Comment by kneth** [comment]
@ivangr1 Did you close because you got it to work?

**Comment by ivangr1** [comment]
Yes, I found that the cause of issue was with another library! Sorry!
