### ISSUE TITLE
Realm10 error: 'IN' must be a keypath to a list

### ISSUE THREAD

**Issue by BravenxX** [realm/realm-js#3369]
Fallowing the doc [Link](https://docs.mongodb.com/realm/react-native/query-engine/) I want to use 'in' operator as filter for example:

```
let registers = realm.objects("users");
registers = registers.filtered('name in $0', ['Juan', 'Bryant'])
```

It throws this error: 

`Error: The expression following 'IN' must be a keypath to a list
`

What is happening? IN operator is not aviable yet?

## Version of Realm and Tooling

- Realm JS: 10.0.1
- React Native: 0.63.3

**Comment by ironage** [comment]
We don't have support for using "in" where the right hand side is a user input argument list yet, it is currently only supported for property lists. We would like to add support for this case [soon](https://github.com/realm/realm-core/issues/2978). See also https://github.com/realm/realm-js/issues/2781 for some workarounds.
