### ISSUE TITLE
Error: ObjectId properties must be compared against an ObjectId or Timestamp argument.

### ISSUE THREAD

**Issue by VEmpink** [realm/realm-js#3370]
## Goals

I am new in Realm plus MongoDB, I just want to find more specific data by `ObjectId` with `.filtered()` method

## Expected Results

A `Realm.Results`

## Actual Results

> Error: ObjectId properties must be compared against an ObjectId or Timestamp argument.

## Code Sample

```
const filtered = realm.objects('user').filtered('_id = "5f99ed2032e9c8c0058c8f04"');
console.log(filtered.toJSON());
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.1
- Node or React Native:  12.19.0 & 0.63.2
- Client OS & Version: Linux Mint 20 Cinnamon

**Comment by ironage** [comment]
Hi @VEmpink the query is interpreting the value as a string, try one of these different ways:

1. `const filtered = realm.objects('user').filtered('_id = $0', ObjectId("5f99ed2032e9c8c0058c8f04"));` 
1. `const filtered = realm.objects('user').filtered('_id = oid(5f99ed2032e9c8c0058c8f04)');`

**Comment by VEmpink** [comment]
@ironage 
Thx you :)
