### ISSUE TITLE
Realm Sync does not write data to mongodb server

### ISSUE THREAD

**Issue by promit13** [realm/realm-js#3374]
I am using MongoDB Atlas and MongoDB Realm Sync on my React Native app to read and write data. Atlas cluster is linked to MongoDB Realm Sync. It syncs and reads data properly. But when I write data, it writes on local database only. But not on MongoDB server. I have initialised Sync with both read and write permission set to true. And I am using Email/Password authentication.

## Goals

I want my app to write data on both local and remote MongoDB database via Sync.

## Expected Results

Write data on both local and remote database.

## Actual Results

Writes data only on local database

## Steps to Reproduce

I followed the documentation to integrate mongodb realm sync on react native app. And I generated schema from Schema section on MongoDB Realm dashboard.

## Code Sample

Realm Schema from MongoDB Realm dashboard

```
{
  "title": "session",
  "required": [
    "_id",
    "__v",
    "title",
    "createdAt",
    "user"
  ],
  "properties": {
    "__v": {
      "bsonType": "int"
    },
    "_id": {
      "bsonType": "objectId"
    },
    "createdAt": {
      "bsonType": "date"
    },
    "partitionKey": {
      "bsonType": "string"
    },
    "password": {
      "bsonType": "string"
    },
    "title": {
      "bsonType": "string"
    },
    "updatedAt": {
      "bsonType": "date"
    },
    "user": {
      "bsonType": "objectId"
    }
  }
}
```

Code from my app

// SCHEMA
```
const sessionSchema = {
    name: 'session',
    properties: {
      _id: 'objectId',
      __v: 'int',
      createdAt: 'date',
      title: 'string',
      user: 'objectId',
      updatedAt: 'date?',
      partitionKey: 'string?',
      password: 'string?',
    },
    primaryKey: '_id',
  };
```
Code for write function

```
const createSession = () => {
    const newSessionId = new ObjectId();
    try {
      const realm = realmRef.current;
      realm.write(() => {
        realm.create(
          'session',
          {
             _id: newSessionId,
             __v: 0,
             createdAt: new Date(),
             title: 'New Session',
             user: new ObjectId(user.id),
             updatedAt: new Date(),
             partitionKey: 'test key',
             password: 'test',
           },
        );
      });
    } catch (e) {
      console.log(e);
    }
  };
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-rc.2
- Node : 12.8.3
- React Native: 0.63.2 
- Client OS & Version: ios Simulator 12.0.1
- MongoDB Cluster: Version 4.4.1,   Tier M10,  Encrypted Storage true

**Comment by ianpward** [comment]
@promit13  Are you able to open an Atlas support ticket on this? Or there is a chat widget in the cloud UI which you can request help on this. Generally we like to keep GH issues limited to our local-only database. Thank you
