### ISSUE TITLE
add multiple data

### ISSUE THREAD

**Issue by luojiong** [realm/realm-js#3377]
How to add multiple data to a list at the same time ?
I call 'for' realm.create (key, {Name: AAA}) 'is the result
| ReactNativeJS ▶︎ { '0': {},
                             │ '1': {},
                             │ '2': {},
                             │ '3': {},
                             │ '4': {},
                             │ '5': {},
                             │ '6': {},
                             │ '7': {},
                             │ '8': {},
                             │ '9': {},
                             │ '10': {},
                             │ '11': {},
                             └ '12': {} }

**Comment by steffenagger** [comment]
I'm not sure I understand the question correctly, but if the question is how to initialize a list during creation of a parent, you would pass in an array of the type for the given prop:

```js
const realm = new Realm({ schema: [
  {
    name: "Item",
    properties: {
      name: "string",
      listOfThing: "Thing[]"
    }
  }, 
  {
    name: "Thing",
    properties: {
      name: "string"
    }
  }
]});

realm.create ("Item", {
  name: "AAA",
  listOfThing: [
    { name:"'BBB" },
    { name: "CCC" },
    ...
  ]
});
```


If this does not cover the question, I would kindly ask you to fill out the default issue template:

```
<!---

Questions: If you have questions about HOW TO use Realm, please ask on
StackOverflow: http://stackoverflow.com/questions/ask?tags=realm
We monitor the `realm` tag.

Feature Request: Just fill in the first two sections below.

Bugs: To help you as fast as possible with an issue please describe your issue
and the steps you have taken to reproduce it in as much detail as possible.

-->

## Goals

<!--- What are you trying to achieve? -->

## Expected Results

<!--- What did you expect to happen? -->

## Actual Results

<!--- What happened instead? -->
<!--- e.g. the stack trace of a crash -->

## Steps to Reproduce

<!--- What are steps we can follow to reproduce this issue? -->

## Code Sample

<!---
Please provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Full projects that we can compile and run ourselves are ideal!
-->

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

```

**Comment by luojiong** [comment]
Thank you for your answer. I have solved this problem
