### ISSUE TITLE
How to store Basic Application data in realm?

### ISSUE THREAD

**Issue by nurmohammed840** [realm/realm-js#3381]
Using realm in react-native.

I want to store some key-value data in realm such as:
- User preferences
- Application setting 
- API Endpoint ( http://www.example.com )
- Auth ( Token  )

So I do not need any fancy `Schema` nor any `Collection`.
Can I store such Application data in realm ? 

Currently a solution is `AsyncStorage`. But Problem is that well its Asynchronous! and extra Dependency!
Even why though ? I mean Using Realm Its not enough for any application ?

**Comment by kneth** [comment]
You are required to use a schema when using Realm. 

If you want a schema for simple key/value, you could do:

```
const schema = {
  name: "keyvalue",
  primaryKey: "key",
  properties: {
    key: "string",
    value: "string"
  }
}
```

You can then look up a value using `realm.objectForPrimaryKey("keyvalue", key)["value"]`.

But maybe a schema like the following is a better fit for you:

```
const schema = {
  name: "Settings",
  properties: {
    userPrefs: "UserPref[]",
    appSettings: "AppSetting[]",
    apiEndpoint: "string",
    authToken: "string"
  }
};

const UserPref = {
  name: "UserPref",
  properties: {
     key: "string",
     value: "string"
  }
};

const AppSetting = { ... };
```

**Comment by kraenhansen** [comment]
Since you 👍 'ed Kenneth's suggestion, I will go ahead and close this issue. Feel free to post any additional questions on [the MongoDB forums](https://developer.mongodb.com/community/forums/).
