### ISSUE TITLE
realm-web 1.0 doesn't have "services" method mounted ???

### ISSUE THREAD

**Issue by fanartie** [realm/realm-js#3403]
when I downgrade to version 0.9, it works...

I wonder if "services" method changed since version 1.0 ? Can't find any document about it.

is it a bug or method deprecated ?

Please advice, Thanks !

**Comment by kraenhansen** [comment]
Hi there - sorry for the inconvenience.
Where did you see the `services` property mentioned?

This is the relevant note in the changelog https://github.com/realm/realm-js/blob/v10/packages/realm-web/CHANGELOG.md#breaking-changes-2
