### ISSUE TITLE
realm removes libjsc.so of React-Native

### ISSUE THREAD

**Issue by railsjack** [realm/realm-js#3404]
Once I add `realm` to my react-native project, the `libjsc.so` disappears from `/data/app/com.myapp/lib/x86`.
And the app goes crash.
At the moment, if I copy `libjsc.so`  manually, then the app works normally.

After searching this repository, I found one.
I am not sure if this is a correct point, but I want this helps you fix this problem.
https://github.com/realm/realm-js/blob/281bef26afe6dce697e69d70568d21617c1762a7/react-native/android/build.gradle#L307-313

**Comment by kraenhansen** [comment]
👋 @railsjack Please update the description to follow [the issue template provided by the repository](https://raw.githubusercontent.com/realm/realm-js/v10/.github/ISSUE_TEMPLATE.md). Specifically the version of Realm JS and exact steps to reproduce would help a lot.

> Once I add realm to my react-native project.

Can you share a bit more information on how you're adding Realm JS to your project?

> the `libjsc.so` disappears from `...`

How do you observe this?

**Comment by railsjack** [comment]
## Goals
I need to add and run realm into my React-Native project.

## Expected Results

I expected to run my app like this example.
https://docs.mongodb.com/realm/react-native/install/#import-realm

## Actual Results
My app was crashed.

## Steps to Reproduce

1) Install realm into my React-Native project (and blank React-Native project with Hermes support).
Following this link.
https://docs.mongodb.com/realm/react-native/install/#install-realm-with-npm

2) imported realm as mentioned this link.
https://docs.mongodb.com/realm/react-native/install/#import-realm

3) And then it was crashed when trying to launch the app.

I am going to upload a screencast and a screenshot as it's a little bit difficult to explain in more detail.
The screenshot shows how to reproduce error and how to debug it.
The screencast shows the result of `adb logcat` right after I run the app using realm.



## Code Sample
import Realm from "realm";

## Version of Realm and Tooling

- Realm JS SDK Version: ?
"realm": "^10.0.0-rc.2"

- Node or React Native: ?
React Native
- Client OS & Version: ?
0.62.0
- Which debugger for React Native: 
None



Attachments

![realm-adb-logcat](https://user-images.githubusercontent.com/1916657/99254142-d882ac00-284c-11eb-8bdf-6921875758f0.jpg)
[realm-debug](https://we.tl/t-RidWLzGdMi)

**Comment by kraenhansen** [comment]
You're referring to a release candidate, might I ask you to try this again with the latest version of Realm JS? (v10.0.1)

**Comment by railsjack** [comment]
I used it as well, but I will try again now.

**Comment by railsjack** [comment]
![image](https://user-images.githubusercontent.com/1916657/99279160-e0e9df80-286a-11eb-9b64-8efc369b77c8.png)

**Comment by kraenhansen** [comment]
@railsjack I can see that the directory also has `libhermes.so`. Are you by any chance trying to use Realm JS with [the `enableHermes: true`](https://reactnative.dev/docs/hermes)?

**Comment by railsjack** [comment]
> @railsjack Okay - I re-read your description and unfortunately [Realm JS doesn't support running with the Hermes engine just yet](https://github.com/realm/realm-js/issues/2455).

@kraenhansen  Yes, I know it does not support, and that's why I suggest this problem on removing libjsc.so file in Debug mode.
I think maybe it might work on release, because libjsc.so is not necessary in release apk.
