### ISSUE TITLE
/object-store/src/schema.hpp:25:10: 'realm/util/features.h' file not found

### ISSUE THREAD

**Issue by csdal** [realm/realm-js#3407]
## Goals

successful build for `realm-js/react-native/ReactRealm.xcodeproj`

## Expected Results

build success

## Actual Results

```
/object-store/src/schema.hpp:25:10: 'realm/util/features.h' file not found
``` 

## Steps to Reproduce

```
git clone https://github.com/realm/realm-js.git
cd realm-js
git submodule update --init --recursive
```
- Open react-native/ios/RealmReact.xcodeproj in Xcode
- Select RealmReact under Targets
- Build: ⌘ + B

 

## Version of Realm and Tooling

- Realm JS SDK Version: v10
- Node or React Native: node v14.15.0
- Client OS & Version: Mac
- Which debugger for React Native: ? None

## Tried

Delete `ios/pods` and run `pod install` again.

**Comment by kraenhansen** [comment]
Hi @csdal. First of, I am curious to learn why you're interested in building the library like this and I want to verify that you're aware that this can be consumed as an NPM package:

```
npm install realm
```

That being said, it does look like we're missing some instructions from our README.md.

After cloning the repository, you must also install dependencies from NPM (in both the root and `./react-native` directories) and CocoaPods:

```
npm install
cd react-native && npm install && cd -
cd react-native/ios && pod install && cd -
```

The `RealmReact` project depends on `RealmJS` which will download Realm Core and its headers (including the file that you're currently missing). You can verify that Realm Core has been downloaded by the existence of the `vendor/realm-ios/download-realm.lock` file.
