### ISSUE TITLE
Document Object

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#341]
They are missing from the api docs.

**Comment by appden** [comment]
You mean `{type: 'object', objectType: ...}`? I thought we agreed to not document that since it's confusing, and I'd actually prefer we remove it altogether. It would be like having an `Object<Person>` type in the other bindings in addition to supporting just `Person`.

**Comment by alazier** [comment]
No. I mean `Realm.Object`. But maybe it doesn't make sense if users aren't subclassing this?

**Comment by appden** [comment]
We don't have a `Realm.Object` _yet_, but it would be nice to add one that you could subclass once the need arises, so maybe we should rename this issue. :smile:

**Comment by alazier** [comment]
The point is there are no api docs for property getters/setters and supported types. These are mentioned in the walk through but it seems they should be in the Ali docs for completion.

**Comment by appden** [comment]
I think the [ProperType](https://realm.io/docs/react-native/latest/api/Realm.html#~PropertyType) docs cover this reasonably well (but can certainly be improved), and I'm not sure how we would document it otherwise. It doesn't look like the Swift API docs cover this either.
