### ISSUE TITLE
Property must be of type 'object_id', got {date value} exception on iOS simulator

### ISSUE THREAD

**Issue by andrei-tofan** [realm/realm-js#3412]
## Goals

Filter objects by date using the example below.

## Expected Results

The query to return a list of objects

## Actual Results
The app crashed with the following exception: 
Property must be of type 'object_id', got (Thu Nov 19 2020 16:59:58 GMT+0200 (EET))"

![Screen Shot 2020-11-19 at 5 16 04 PM](https://user-images.githubusercontent.com/23150031/99688724-cc862c80-2a8e-11eb-86e3-9a766ff5d5ed.png)

## Steps to Reproduce

1. Create an app with the code sample
2. Run the app

## Code Sample

```javascript
class Dog extends Realm.Object {}

Dog.schema = {
  name: 'Dog',
  properties: {
    name: 'string',
    dateCreated: 'date',
  },
};

class App extends Component {
  componentDidMount() {
    Realm.open({
      schema: [Dog],
    }).then(realm => {
      realm.write(() => {
        realm.deleteAll();
        [1, 2, 3].forEach(dogId => {
          const dog = {
            name: `Dog #${dogId}`,
            dateCreated: new Date(),
          };
          realm.create('Dog', dog);
        });
      });

      const dog = dogs[0];
      console.log('dog', dog);

      const dogs = realm
        .objects('Dog')
        .filtered(`dateCreated <= $0`, new Date());
    });
  }
}
```

## Version of Realm and Tooling

- Realm JS SDK Version:  10.0.1
- Node or React Native: 0.63.3
- Client OS & Version: iOS 14, on simulator
- Which debugger for React Native: None

**Comment by steffenagger** [comment]
I can't reproduce the error you're seeing.
I added a `render` and flipped the order of initializing `dogs` and logging it - but then the example worked as intended.

<details>
<summary>Click for code example (incl. above mentioned changes)</summary>

```js
import React from 'react';
import {View, Text} from 'react-native';
import Realm from 'realm';

class Dog extends Realm.Object {
  static schema = {
    name: 'Dog',
    properties: {
      name: 'string',
      dateCreated: 'date',
    },
  };
}

export default class App extends React.Component {
  componentDidMount() {
    Realm.open({
      schema: [Dog],
    }).then((realm) => {
      realm.write(() => {
        realm.deleteAll();
        [1, 2, 3].forEach((dogId) => {
          const dog = {
            name: `Dog #${dogId}`,
            dateCreated: new Date(),
          };
          realm.create(Dog, dog);
        });
      });

      const dogs = realm.objects(Dog).filtered('dateCreated <= $0', new Date());

      console.log('dogs', dogs);
    });
  }

  render() {
    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Text>See console</Text>
      </View>
    );
  }
}

```
</details>

Could you try cleaning your build through xcode, and clear the metro bundler cache?

**Not related to the issue:**
I would recommend sticking with class models, when using them, as in `realm.objects(Dog)` instead of `realm.objects('Dog')`, as you then will get instances of the class returned (if you want to extend your models at some point).
And just for the record, the example worked either way.

**Comment by andrei-tofan** [comment]
Hi @steffenagger, thanks for the input.

**Comment by jaltin** [comment]
@steffenagger thank you for trying to reproduce this.

I work with @andrei-tofan and I also can't seem to reproduce his issue.

We will do some more tests, but if nothing new comes up we will then close this issue.

**Comment by steffenagger** [comment]
Thank you @jaltin & @andrei-tofan.

**Comment by andrei-tofan** [comment]
Closing this issue since no one else can reproduce it. Many thanks, @steffenagger!
