### ISSUE TITLE
typings for .sorted

### ISSUE THREAD

**Issue by euZebe** [realm/realm-js#3413]
## Goals

Be able to sort realm elements by several criteria with no typing error.

## Actual Results
A Typescript error:
> Argument of type '(string | boolean)[][]' is not assignable to parameter of type 'string'.

Once this error ignored, everything works fine: elements are sorted as expected.

## Steps to Reproduce

```.filtered(...).sorted([["name", false], ["timestamp", true]])```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.1
- Node or React Native: React Native
- Client OS & Version: iOS 14.2
- Which debugger for React Native: None

**Comment by kneth** [comment]
Thank you for reporting. We need to take a closer look at our TS defs.

Btw, you can also specify sorting in the query. In your case, you can add `SORT(name ASC, timestamp DESC)`.

**Comment by steffenagger** [comment]
Hi @euZebe,
I just went through the different overloads of `sorted`, and non of the bellow sorted-calls yielded a type error (tested in both TS 3 & 4):
```ts
realm.objects(RealmItem).sorted('text');

realm.objects(RealmItem).sorted('text', true);

realm.objects(RealmItem).sorted([
  ['itemNo', true],
  ['text', false],
]);
```

The only way I was able to provoke the error you're seeing (`Argument of type '(string | boolean)[][]' is not assignable to parameter of type 'string'`), is if I altered the order of the tuples (flipped `boolean` & `string`), example:
```ts
realm.objects(RealmItem).sorted([
  [false, 'name'],
  [true, 'timestamp'],
]);
```

Could the TS Server in your editor have stalled while an invalid structure was present?
If not, could you share your typescript-version & `tsconfig.json`?
