### ISSUE TITLE
after installing realm have a Command PhaseScriptExecution failed with a nonzero exit code a error on iOS 

### ISSUE THREAD

**Issue by zanyar3** [realm/realm-js#3418]
## Goals

Install realm into react native application.
 

## Expected Results

Successfully work for Android but when run iOS platform have a error 

## Actual Results

I run in Xcode simulator iPhone 11 

- RealmJS Group
      Uncategorized Group
             Command PhaseScriptExecution failed with a nonzero exit code

If install Pod in iOS folder have a warning `RealmJS has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.`

## Steps to Reproduce

npm install --save realm

## Version of Realm and Tooling

- Realm JS SDK Version:  10.0.1
- Node or React Native:  0.63.2
- Client OS & Version: Catalina 10.15.7

**Comment by kneth** [comment]
My best guess is it is the same as #2910 - do you by any chance have a space in your folder name? If so, try to rename it.

**Comment by zanyar3** [comment]
> My best guess is it is the same as #2910 - do you by any chance have a space in your folder name? If so, try to rename it.

Thanks you save my day 👍
