### ISSUE TITLE
v5:  fix object create peformance on RN iOS

### ISSUE THREAD

**Issue by ferrannp** [realm/realm-js#3422]
Can this PR https://github.com/realm/realm-js/pull/3137/files or this https://github.com/realm/realm-js/pull/3136/files be included in v5? For those who are not ready to update (as v6 is not backward compatible with v5).

To fix this issue precisely: https://github.com/realm/realm-js/issues/2845 which is present in v5.

Thank you!

**Comment by kneth** [comment]
@ferrannp In general I would suggest you to upgrade. Back porting always introduces a risk of breaking something, and we should try to avoid it if possible.

> For those who are not ready to update

What is reason for not being ready for the upgrade?

**Comment by ferrannp** [comment]
Hey @kneth ! We can close the issue if you like (I patched it locally). Basically, I noticed my app works slower in adding, updating and removing elements on v6 than in v5. It looks like listeners are called in different order than v5 and in general, everything is slower (Android). I couldn't investigate further so for now, I stayed in v5.
