### ISSUE TITLE
Relationship created in atlas/realm ui causes null field in realm js

### ISSUE THREAD

**Issue by LawrenceMouarkach** [realm/realm-js#3428]
## Goals

Relationship via atlas, to process in realm js.

## Expected Results

opUnit field populated with results from collection in opunit table for that particular id key.

## Actual Results

opUnit field is null

### **_Schema 1:_** 
{
  "title": "Parcel",
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "_partitionKey": {
      "bsonType": "string"
    },
    "opUnit": {
      "bsonType": "string"
    },
    "tourName": {
      "bsonType": "string"
    }
  },
  "required": [
    "tourName"
  ]
}

**_### Schema 2:_**
{
  "properties": {
    "_id": {
      "bsonType": "string"
    },
    "tourName": {
      "bsonType": "string"
    },
    "createdAt": {
      "bsonType": "date"
    }
  },
  "required": [
    "_id",
    "tourName",
    "createdAt"
  ],
  "title": "OpUnit"
}
### **_Relationship in atlas on Parcel Schema:_**
{
  "opUnit": {
    "ref": "#/relationship/mongodb-atlas/tours_db/opunit",
    "foreign_key": "_id",
    "is_list": false
  }
}

1. create relationship in atlas
2. open Parcel realm

## Code Sample
      
      Realm.open(config).then(projectRealm => {
        const syncParcels = projectRealm.objects('Parcel');
        syncParcels.forEach(element => console.log(element.opUnit));
      });

## Output
![image](https://user-images.githubusercontent.com/26540072/100326029-5408f980-2fc1-11eb-97ef-ba676bab44e4.png)

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

Opening in realm studio:
![image](https://user-images.githubusercontent.com/26540072/100325856-160bd580-2fc1-11eb-9cc5-ba5c890b9134.png)

**Comment by LawrenceMouarkach** [comment]
Further to this i tried opening the realm with a schema declared:
  static schema = [{
    name: 'Parcel',
    properties: {
      _id: 'objectId?',
      address: {
        name: 'Parcel_address',
        properties: {
          addressLine1: 'string?',
          addressLine2: 'string?',
          addressLine3: 'string?',
          addressLine4: 'string?',
          postcode: 'string?'
        }
      },
      createdAt: 'date?',
      customerName: 'string?',
      edd: 'date?',
      ndd: 'date?',
      numberOfAttempts: 'int?',
      opUnit: 'OpUnit',
      parcelId: 'string?',
      clientId: 'string?',
      parcelUpi: 'string?',
      postcode: 'string?',
      receivedOffVan: 'bool?',
      status: 'string?',
      tourDate: 'date?',
      tourId: 'string?',
      tourName: 'string',
    },
    primaryKey: '_id',
  },
    {name: 'OpUnit',
      primaryKey: '_id',
      properties: {
        _id: 'string',
        tourName: 'string',
        createdAt: 'date'
      }
    }
    ];
}

Same problem

**Comment by LawrenceMouarkach** [comment]
const config = {
       schema: Parcel.schema
    };

  Realm.open(config).then(projectRealm => {
    const syncParcels = projectRealm.objects('Parcel');
    syncParcels.forEach(element => console.log(element.opUnit));
  });

**Comment by cesarvr** [comment]
From your screenshoot we can see that your `OpUnit` collection is empty can you share with us how are you populating this particular class ?

Also are you aware if this two collections have any data in the cloud, it would be possible for you to provide a screenshoot just to verify there is actual data ? 

Thanks.

**Comment by LawrenceMouarkach** [comment]
![image](https://user-images.githubusercontent.com/26540072/100348017-31390e00-2fde-11eb-9309-ffdcb954aa20.png)


![image](https://user-images.githubusercontent.com/26540072/100347979-1ebed480-2fde-11eb-9e8a-2372e9cf50b7.png)

**Comment by LawrenceMouarkach** [comment]
@cesarvr from my understanding the relationship based on the opUnit field and the _id field on the opunit collection should pull in the object from the collection keyed with that _id i.e 1235?

**Comment by cesarvr** [comment]
Thanks for reporting this, we are going to take a look into it. 👍

**Comment by LawrenceMouarkach** [comment]
@cesarvr any updates on this issue please?

**Comment by kneth** [comment]
@LawrenceMouarkach We haven't been able to reproduce it (see for example https://github.com/realm/realm-js/pull/3458).

Can you post more details about your app configuration (cloud side)?

**Comment by LawrenceMouarkach** [comment]
@kneth Yeah sure thing! What details should I post?

I've posted the schemas and relationship described above. 
With an example of each.

The only other thing maybe I thought it could be something to do with the _id field being a string? 

But haven't proved that just an idea

Is there any more detail you would like?

**Comment by kneth** [comment]
> The only other thing maybe I thought it could be something to do with the _id field being a string?

String is a support type: https://docs.mongodb.com/realm/sync/partitioning#std-label-partition-limitations-types

I wonder if it can be related to [permissions](https://docs.mongodb.com/realm/sync/permissions). If you - by accident - only allow sync on `Parcel` but not on `OpUnit`.

**Comment by LawrenceMouarkach** [comment]
@kneth thing is this was working fine before I added a relationship in atlas, I could pull in the opUnit objects (when i provided the correct partitionKey) but upon adding the relationship I ended up with a null object.

re permissions does the below look ok I havent changed anything:
![image](https://user-images.githubusercontent.com/26540072/102071497-72138e00-3df8-11eb-889f-99c89c64f852.png)

**Comment by nirinchev** [comment]
Which property is your partition key? From the first snippet you posted, it seemed like it's `_partitionKey`, but that is missing from your `opunit` schema.

**Comment by LawrenceMouarkach** [comment]
Hi @nirinchev  tourName is the partition key (this was a spike to investigate relationships in atlas so we just used tourName in this instance not _partitionKey

**Comment by LawrenceMouarkach** [comment]
In our main app (none spike) we use a "partitionKey" field (minus the _)

**Comment by LawrenceMouarkach** [comment]
evidence attached below:
![image](https://user-images.githubusercontent.com/26540072/102074754-26afae80-3dfd-11eb-9c21-e0c4267d2816.png)

**Comment by nirinchev** [comment]
Haha, no need for evidence, I trust you - I just got confused from the first snippet. In that case, can you confirm that the value for `Tour.tourName` is the same as the value for `OpUnit.tourName`?

**Comment by LawrenceMouarkach** [comment]
@nirinchev in that case no they are not the same, must they be the same for a relationship to work?

If that's the case I may have misunderstood what the point of a relationship was, I thought we would be able to bring together two items based on the **primary/foreign** key agnostic to their partitioning!

Otherwise I would have just created a separate realm partitioned by the value I care about (Which I ended up doing) in order to achieve what I wanted out of a relationship.

To me I don't quite understand the point of a relationship if two entities must be partitioned by the same key?

**Comment by LawrenceMouarkach** [comment]
I shall close this then as there cannot be a relationship between two collections where both objects are not partitioned by the same key
