### ISSUE TITLE
[Realm Web] No method for "resend confirmation for FUNCTION based user confirmation"

### ISSUE THREAD

**Issue by andrefelipe** [realm/realm-js#3430]
## Goals

At Realm Web SDK, there is no method for "Resend confirmation for **Function** based user confirmation" at **Email/Password provider.**

I tried calling "app.emailPasswordAuth.resendConfirmationEmail" but it returns:
`please use confirm via function (status 400)`

Which would be correct. So looked in source code and tried to find the equivalent for function, but there is no such method.

Could you please provide a fix, I have the situation where users who created the account, and forgot to click que confirmation email, are never confirmed, and never able to login.

## Version of Realm and Tooling

- Realm JS SDK Version: Realm Web 1.0
- Node or React Native: No

**Comment by cesarvr** [comment]
We are going to look at it. 

Thanks.

**Comment by andrefelipe** [comment]
Thanks @cesarvr

**Comment by andrefelipe** [comment]
Hello, could you look at it? Would be possible to add to the code?

I am going to make my project public in a couple of weeks, and without this function people who forgot to confirm the email the first time, would be locked out of the app.

Thanks you very much

**Comment by sumedham** [comment]
Hello - the quick way to do this would be to go on your Admin UI -> App Users -> click on "Pending Users" and "Re-Run" function. 

https://docs.mongodb.com/realm/users/create#re-run-the-user-confirmation-workflow

**Comment by andrefelipe** [comment]
Thanks I will use the Admin UI for the time being.

Still we need the SDK's function to resend the confirmation. It is not maintainable to go in the Admin UI every day, or to receive support cases from users for such thing.

We are expecting 500+ new users on the first month after launch. It can become a burden if lots of people miss the confirmation email.

**Comment by sumedham** [comment]
Hey Andre - we actually do have a client endpoint exposed and we are working on getting it added in the meantime. Another programatic way to do this is to use our Admin API (https://docs.mongodb.com/realm/admin/api/v3#email-apis) if you'd like to do this in bulk.

**Comment by andrefelipe** [comment]
Great! Thank you @sumedham

**Comment by andrefelipe** [comment]
Hello, please, do you have a ETA on this?

I know I can use the Realm Dashboard, and the API mentioned. But the key solution here is the user himself trigger the email confirmation, when he tries to login.

I have already many problems, there is about 40 users which didn't confirm when they first received the email, so now they are locked out.

**Comment by kraenhansen** [comment]
Thanks for the ping - I've bumped it up on my backlog 👍  Can't commit to an ETA, but at least it's being actively considered for upcoming work.

**Comment by kraenhansen** [comment]
I believe this is the original issue requesting the feature: https://github.com/realm/realm-js/issues/3032

**Comment by franky-chanyau** [comment]
Hopping on this for an update regarding this implementation i the client sdk. I'm running the mentioned admin api endpoint from a lambda function tied to my app but I don't like the idea of having this as a long term solution

**Comment by andrefelipe** [comment]
I believe this issue is incorrectly marked as **enhancement**. If a new account is created, and for any reason the users didn't click the confirmation link on email within 30 minutes, they are completely locked out my app. This is extremely serious problem. 

I already have **458 pending confirmation users** for my website https://www.typographicposters.com . While the reason is mixed, I believe too many are from that lockdown reason because I already received direct message from many, to help to create their account.

This issue will make 6 months since I first added here. Please give an attention to it. It's very important that the users who try to re-create their account, simply receives the confirmation email again to resume from where they stopped.

Thanks a lot.

**Comment by Dev-Bilaspure** [comment]
Using `await app.emailPasswordAuth.retryCustomConfirmation({ email })` instead of using
`await app.emailPasswordAuth.resendConfirmationEmail` solved `please use confirm via function (status 400)` issue.
