### ISSUE TITLE
Cannot read property 'debugHosts' of undefined

### ISSUE THREAD

**Issue by wulaizi** [realm/realm-js#3433]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

"realm": "^10.0.0-rc.2",
 "react-native": "0.63.2",

1、Cannot read property 'debugHosts' of undefined
2、Invariant Violation: "tsx_craftsman" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by kraenhansen** [comment]
@wulaizi can I ask you to upgrade to the latest version of Realm JS: [v10.0.2](https://github.com/realm/realm-js/releases/tag/v10.0.2) and try again?

**Comment by andrew-whitmore** [comment]
hi,

We are also experiencing this issue using realm 10.0.2. 

We are running:

react-native version 0.63.3
using android version 29 (Simulator)

When the app starts up `createSession` in `rpc.js` is never called therefore when sendRequest is called host is undefined.

The following error is then returned

```
Must first create RPC session with a valid host
```

**Comment by andrew-whitmore** [comment]
Just to follow up - We got past this issue now by removing `node_modules` and clearing the gradle cache and running a fresh `npm install`

**Comment by kneth** [comment]
@andrew-whitmore Yeah, React Native and npm are caching a lot and something you have to manually remove folders when upgrading.
