### ISSUE TITLE
0x8badf00d occurs on application launch using Realm

### ISSUE THREAD

**Issue by mikeslinkman** [realm/realm-js#3443]
## Goals

Provide a working build to iTunes connect so that we can release an update for our application. Locally I'm unable to reproduce the issue myself. 

## Expected Results

App should not crash on launch presumably when trying to open the realm 

## Actual Results

As per the reports of Apple the app crashes on launch indicating a 0x8badf00d issue with the app crashing on launch. When I look in the crash reporting section of Xcode I found a lot of references to Realm just before the crash occurred. Here is a link to the gist containing the crash report [Crash report gist](https://gist.github.com/mikeslinkman/1c554213ca224f03346c49d16d678704). I've shared the complete crash log there but thread 2 is the one where the crash occurs. 

## Steps to Reproduce

I'm not able to reproduce the error myself on any of my devices / simulators. Somehow the reviewer at Apple seems to run into this issue every time. However I've searched already closed issues and found a possible duplicate in the form of (#2349)[https://github.com/realm/realm-js/issues/2349]

## Version of Realm and Tooling

- Realm JS SDK Version: 5.0.5
- Node or React Native: React Native
- Client OS & Version: iOS 14.2
- Which debugger for React Native: None

**Comment by kneth** [comment]
@mikeslinkman 

Did you try to follow the idea about [lowering the protection](https://github.com/realm/realm-js/issues/2349#issuecomment-523993755) and at the same time use encryption?

**Comment by mikeslinkman** [comment]
Hi,

I've seen that issue and haven't tried that yet because the report stated that this was happening on app launch. And as far as I understood the mentioned issue this would occur when the phone of the user was in a locked state. At the moment I've removed the code in the startup screen that uses Realm since this is not critical for the functionality of the app. This seems to help solve the issue since the app can now be published again. Using similar realm functionality in other parts of the app doesn't seem to result in the issue but it remains hard to tell because of me not being able to reproduce the error. I'll be sure to keep this issue updated with my findings on implementing encryption functionality of realm

That being said I'm still going to implement the solution you're mentioning in a future update since I want to rule out the possibility of it occurring.
