### ISSUE TITLE
Archived builds crash on device

### ISSUE THREAD

**Issue by jwhitley** [realm/realm-js#345]
[N.B.: Apologies for the length, but this smells like there's a critical undocumented step, so I'm trying to be fully detailed here. – J]

### Get the sample repo and set it up
1.  `git clone https://github.com/jwhitley/ReactNativeTesting.git/`
2.  `cd ReactNativeTesting`
3.  `git co realm-redbox` (jwhitley/ReactNativeTesting@d252d5b at this writing)
4.  `npm install`

### Launch Xcode and build the project archive
5.  `open ios/ReactNativeTesting.xcodeproj`
6.  In Xcode: Project > Archive
7.  In Xcode: Window > Organizer
8.  With the archive just built selected in the organizer, click "Export..." in the right-hand pane.
9.  In the export UI, choose "Save for Development Deployment" then hit "Next"
10. Choose a valid provisioning team and confirm.
11. Choose "Export one app for all compatible devices" then hit "Next"
12. Hit "Next" on the Summary pane to build the archive, then choose a place to save it.

### Install the archive on device
13. In Xcode, open Window > Devices and select a target device
14.  Drag the newly built `.ipa` file onto the "Installed Apps" pane
15. On the device, launch the app.

## Expected results
This "app", mostly just the base template generated by RN plus `realm-js` integration, loads and runs.

## Actual results
Redbox with `Missing Realm constructor [...]` error message appears.

## Notes

This project has all of these settings from #311 applied:

* **Strip Debug Symbols During Copy: No**
* **Strip Linked Product: No**
* **Dead Code Stripping: No**

The **Archive scheme has been switched to Debug** in this project so that a redbox will appear on the device instead of the app simply crashing and keeping its secrets to itself.  (EDIT: This is merely a convenience; the same error is emitted in the device logs in a normal Archive (Release) build.)

ReactNative's template-generated `AppDelegate.m` in this project has been switched to use the packaged build instead of the development server.

**Comment by esutton** [comment]
I am seeing same issue under **iOS 9.3**

The strange thing is that applying the first two strip option seemed to resolve to provide a work-around that kept me going for at least a week.  I do not know if upgrading to  **iOS 9.3** is a factor or not.

1. Strip Debug Symbols During Copy: No
2. Strip Linked Product: No

**Comment by jwhitley** [comment]
FWIW, I'm seeing this on 9.3 (Xcode 7.3) now, but I first encountered this problem on 9.2.1 (Xcode 7.2 & 7.2.1).

**Comment by appden** [comment]
@jwhitley Thanks so much for the detailed repro steps! @esutton seems to be right that something changed with Xcode 7.3. It looks like the strip settings are not honored when you build with bitcode enabled. So the temporary workaround is to also set `Enabled Bitcode` to `No`.

I am prioritizing getting this to work without all of the special Xcode settings. Thank you again for this report!

**Comment by jwhitley** [comment]
@appden Setting `Enabled Bitcode: No` (finally) did it.  I've got a working archived release build on-device now.  Looking forward to an easier path for all of this, thanks!

**Comment by esutton** [comment]
Thank your @appden !  **Enable Bitcode No** worked for me too.

I was about to resign myself to spending the next two weeks learning sqlite3 on react-native.

Setting these three settings to **No** solved my problem:
- Target > Build Settings
  - Deployment
    - Strip Debug Symbols During Copy: No
    - Strip Linked Product: No
  - Build Options:
      - Enable Bitcode No

The Build Settings > Linking option Dead Code Stripping does NOT need to be set to No.

**Comment by alazier** [comment]
We just released 0.11.0 which uses a static library and should resolve this issue. You should now not have to change any of the strip settings for things to work. Note when upgrading to the newest version that we now recommend using `rnpm`: https://realm.io/docs/react-native/latest/#getting-started

**Comment by appden** [comment]
@jwhitley @esutton Check out the [0.11.0 Release Notes](https://github.com/realm/realm-js/releases/tag/v0.11.0) for how to upgrade your project. Like @alazier said, you can revert your strip and bitcode settings to the defaults after upgrading.
