### ISSUE TITLE
[Realm Web] No "skip" option on MongoDB Collection?

### ISSUE THREAD

**Issue by andrefelipe** [realm/realm-js#3450]
**There is no "skip" option on MongoDB Collection**. Is that correct?

The only way to use skip right now would be on aggregation.

## Code Sample

Directly from realm-web source code:

```js
class MongoDBCollection {

    find(filter = {}, options = {}) {
        return this.functions.find({
            database: this.databaseName,
            collection: this.collectionName,
            query: filter,
            project: options.projection,
            sort: options.sort,
            limit: options.limit,
            // WHERE IS THE "skip" option?
        });
    }
```

## Version of Realm and Tooling

- Realm JS SDK Version: realm-web 1.0
- Node or React Native: no

**Comment by kneth** [comment]
@andrefelipe Thank you for reporting. It looks like we skipped "skip" (sorry for the bad joke).

**Comment by andrefelipe** [comment]
:) Thanks for looking into it

**Comment by dennererthal01** [comment]
Any update on this? Would be great to be able to use skip on "find"  calls rather than only on aggregations.

**Comment by kenkoedu** [comment]
+1 here
Still using aggregation to do the same thing

But I would say thank you to the developers.
I love using the realm service

**Comment by ronsper** [comment]
Any update on this?, we just ran into this with our project.

**Comment by kevinbeal** [comment]
I would also love a skip option <3

**Comment by dennererthal01** [comment]
On our project, we created a backend function with Application Authentication and we're running our "find" calls using that function. Not perfect, but better than skipping with aggregation as it kills performance.

**Comment by papafe** [comment]
As mentioned in my previous message `skip` is not supported in the App Services for now, and there is no current plan to implement it for now, so I am closing this ticket. 

It maybe also mentioning that using `skip` isn't recommended as it's quite expensive and generally `sort` based paging is way cheaper. You can find more info in the [documentation](https://www.mongodb.com/docs/manual/reference/method/cursor.skip/#pagination-example).

**Comment by andrefelipe** [comment]
Sort-based pagination is a good idea. I haven't thought of it.
Thanks.

**Comment by kyjak** [comment]
> aggre

how do you use aggregation to do it? I am stuck on this.

**Comment by irosadie** [comment]
> > aggre
> 
> how do you use aggregation to do it? I am stuck on this.

you can use aggregate function instead for current

```
const pipeline = [
   { $skip: 2},  
   { $limit: 10 },
]
      
      const list = await collection.aggregate(pipeline)
```
