### ISSUE TITLE
Cannot use new Class() Syntax after calling create()

### ISSUE THREAD

**Issue by scousino** [realm/realm-js#3472]
## Goals
Create multiple ES5 classes within a Realm write transaction after create has been called. 

## Expected Results
I expect to be able to execute without error:

```
let myRealm = getRealm();
    myRealm.write(() => {
      const test1 = myRealm.create('TestClass', new TestClass('Testing 1'));
      console.log('Test 1: ', test1.toJSON());
      const test2 = myRealm.create(
        'TestClass',
        new TestClass('Testing2'),
      );
      console.log('Test 2: ', test2.toJSON());
    });
```

## Actual Results
In actuality, the second call to new TestClass returns an empty object that will not allow the setting of any properties on them.

e.g.
``{{ myTestClass.id = 1 // If I console.log myTestClass.id I get null }}``

If I try calling .toJSON on the object I get an error:
![image](https://user-images.githubusercontent.com/8717527/101943253-c6302f80-3bb8-11eb-9932-d43d6fbd9f44.png)

## Steps to Reproduce
Try to run the code I pasted above. Basically, within a write transaction attempt to create multiple TestClass objects after calling realm.create and passing one of those objects as the thing to create. Any subsequent calls to new TestClass will always return {} and not let you set any properties on the object.

## Code Sample
https://github.com/scousino/RealmIssueExample

## Version of Realm and Tooling
* Realm JS SDK Version: 10.1.1
* Node or React Native: React Native
* Client OS & Version: Emulated Pixel C Android Version 11
* Which debugger for React Native: None

**Comment by kneth** [comment]
@scousino 

`Object` is the parent of all objects, and I wonder if you change https://github.com/scousino/RealmIssueExample/blob/main/TestClass.js#L1-L2 to

```
import Realm from "realm";
export class TestClass extends Realm.Object { 
  // ...
};
```
is safer.

**Comment by scousino** [comment]
> 
> 
> @scousino
> 
> `Object` is the parent of all objects, and I wonder if you change https://github.com/scousino/RealmIssueExample/blob/main/TestClass.js#L1-L2 to
> 
> ```
> import Realm from "realm";
> export class TestClass extends Realm.Object { 
>   // ...
> };
> ```
> 
> is safer.

@kneth 

I am using Realm.Object essentially. If you look at my import statement I import the Object class from realm: https://github.com/scousino/RealmIssueExample/blob/13ccb2a0cf6bfe2be6d839e53ddbfc07fb35cf1e/TestClass.js#L1-L2. So, my Object import is the same thing as Realm.Object

**Comment by steffenagger** [comment]
Hey @scousino,

I think the issue here, is that class models are not intended for insertion/creation, or creation outside of realm (due to the hookup directly to the underlying db-data) - but instances of said class models are returned when creating/fetching objects.

So when creating new instances, it should work if use a plain old literal, like so:
```js
realm.write(() => {
  const test1 = myRealm.create(TestClass, {
    id: 'id-1',
    description: 'fist'
  });
});
```
Hint: when utilizing class models you can pass in the class for creation/fetching (perhaps making refactoring easier?).

To utilize a static creation method (as your `newTestClass` for various reasons, ensuring defaults etc.), I let it return a plan literal object, instead of a `TestClass` instance (and probably rename it to something like `newCreationData`).

**Comment by scousino** [comment]
@steffenagger Thanks for the workaround suggestion! However, I think the bug still stands, in prior versions of Realm the class models worked as expected, and there's not any mention in the documentation of the interaction you've described here.

Also, wouldn't the loss of using class models means you also lose any helper/additional methods you have defined in this class?

**Comment by steffenagger** [comment]
> However, I think the bug still stands (...)
We'll have to investigate how to approach this. I've created this ticket to track it: https://github.com/realm/realm-js/issues/3553

> Also, wouldn't the loss of using class models means you also lose any helper/additional methods you have defined in this class?

@scousino: No, in the example bellow (same as before), `test1` will be an instance of `TestClass`, including helper-functions and/or getters for derived data (implemented in `TestClass`).

```js
realm.write(() => {
  const test1 = realm.create(TestClass, {
    id: 'id-1',
    description: 'fist'
  });
});
```
