### ISSUE TITLE
CORS error when logging-in through web-sdk

### ISSUE THREAD

**Issue by DeveloperRic** [realm/realm-js#3473]
## Goals

* log in to my realm app using the Google provider
* then, read/write to and from collections

## Expected Results

* redirect to Google's Oauth2 sign-in page
* redirect back to application (having been logged-in to realm)

## Actual Results

* request blocked by CORS
```
Access to fetch at 'https://stitch.mongodb.com/api/client/v2.0/app/<app_id>/location' from origin 'http://localhost:4200' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://localhost:4200' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
* request:
```
Request URL: https://stitch.mongodb.com/api/client/v2.0/app/<app_id>/location
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: https://localhost:4200
access-control-expose-headers: X-Stitch-Location, X-Baas-Location, Location
cache-control: no-cache, no-store, must-revalidate
content-encoding: gzip
content-length: 126
Content-Security-Policy: upgrade-insecure-requests
content-type: application/json
date: Sat, 12 Dec 2020 16:13:14 GMT
server: envoy
vary: Origin
x-envoy-upstream-service-time: 6
x-frame-options: DENY
:authority: stitch.mongodb.com
:method: GET
:path: /api/client/v2.0/app/<app_id>/location
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7
origin: http://localhost:4200
referer: http://localhost:4200/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```

## Steps to Reproduce & Code Sample

* using an Angular workspace:
```
Angular CLI: 10.0.8
Node: 10.16.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1100.2
@angular-devkit/build-optimizer   0.1100.2
@angular-devkit/build-webpack     0.1100.2
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.7
@angular/cli                      10.0.8
@angular/material                 10.2.7
@ngtools/webpack                  11.0.2
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.44.2
```
* within an injectable service (don't know if this has an effect but thought it was worth mentioning):
```ts
@Injectable({
  providedIn: 'root'
})
export class RealmService implements DatabaseLink {
...
```
* create Google provider credential, then attempt to log in:
```ts
import * as Realm from "realm-web";
...
RealmService.app = new Realm.App({ id: environment.REALM_APP_ID });
const credentials = Realm.Credentials.google(environment.REALM_REDIRECT_URL);
this.user = await RealmService.app.logIn(credentials)
```

## Version of Realm and Tooling

- Realm JS SDK Version: ?
```json
"realm-web": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/realm-web/-/realm-web-1.1.0.tgz",
      "integrity": "sha512-KIXFNdBYh8dQ6QR2CxGE5dHb1UH3GUGLPoXSep7S6gypUbuC1pYOl/FQBACWahh5hoiMOOJ3Ym5lgysVx9oKVg==",
      "requires": {
        "@types/bson": "^4.0.0",
        "abort-controller": "^3.0.0",
        "bson": "4.0.0",
        "detect-browser": "^5.1.1",
        "js-base64": "^2.6.3",
        "node-fetch": "^2.6.0"
      }
    }
```
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
The redirect credentials does work due to a change in Google's API. We suggest that you switch to OpenID (support released in Realm Web v1.1.0).

**Comment by DeveloperRic** [comment]
Hi Kneth thanks for getting back to me. I was able to successfully link realm to google to authenticate users using OpenID, however, the redirect flow seems to be broken. Here's what happened:

* Call logIn()
```ts
const credentials = Realm.Credentials.google(environment.REALM_REDIRECT_URL)
const user = await RealmService.app.logIn(credentials)
```
* A new tab is opened & I am prompted to login (for some reason this only works sometimes, but I suspect this is a [Chrome issue](https://stackoverflow.com/q/10883211)?)
* After logging in a user is created in realm
* I am redirected back to my application (but in the new tab, I now have a stale tab?)
* The URL contains some strange tokens that don't look like auth tokens:
```
/realm-redirect
#_baas_client_app_id=...
&_baas_state=<unusually long string>
&_baas_ua=...
&_stitch_client_app_id=...
&_stitch_state=...
&_stitch_ua=<unusually long string>
```
* Upon redirect, the realm sdk does not hook onto the HTTP to set `Realm.App.currentUser` so I'm left wondering what is left for me to do. Maybe I send the entire URL back to `Realm.Credentials.google()` & call `RealmService.app.logIn()` again?

I'm not sure what is supposed to be happening here. Additionally, the Realm docs list [a completely different auth scheme](https://docs.mongodb.com/realm/web/authenticate#google-oauth) for google than the scheme in the [Realm reference](https://docs.mongodb.com/realm-sdks/js/latest/Realm.Credentials.html#.google)

Please can you let me know what is going on here and also, it looks like your docs are out of date/out of sync so that might be something to look at.

**Comment by DeveloperRic** [comment]
bump. Is this issue still being looked at?

**Comment by kraenhansen** [comment]
> it looks like your docs are out of date/out of sync so that might be something to look at.

I agree: We need to loop back and get this sorted out. The reason (not an excuse) this is currently in a confusing state is that we now support three ways of authenticating via Google and the latest (recommended) way (OAuth OpenID Connect) is not yet properly documented everywhere.

I see you're passing a redirect URL to the google credential function, which means you're not using the OpenID Connect variant of the API. You can use either [Google Sign-in](https://developers.google.com/identity/sign-in/web/sign-in) or [One Tap](https://developers.google.com/identity/one-tap/web/guides/load-one-tap-client-library) to obtain an OpenID Connect ID Token and pass that to the `Credentials.google(..)` function instead of a redirect URL.

We've made a guide that sets this up using the (less known) `google-one-tap` package: https://docs.mongodb.com/realm/web/authenticate#std-label-web-login-google

Please keep us updated and let me know if any of the above is confusing or misleading.

**Comment by kraenhansen** [comment]
@DeveloperRic how are things coming along? I'll close this issue for now, since it looks like you're pursuing an alternative route, making it harder (and less meaningful) to attempt reproducing the original issue. Please feel free to open a now issue if you experience one.

**Comment by maharjanmilan** [comment]
While using openid connect,realm is only storing name of the user. How can we store email as well?
