### ISSUE TITLE
Difference Between Realm JavaScript v10.1.1 vs. Realm JavaScript 6.1.5

### ISSUE THREAD

**Issue by Piero87** [realm/realm-js#3474]
I use Realm for React Native, today I decided to update my version of Realm 6.1.4 to 6.1.5 and after the command `yarn add realm` yarn upgrade to 10.1.1 version, so I check the releases page: https://github.com/realm/realm-js/releases and I can see different version of realm, why?

What I have to install?

**Comment by kneth** [comment]
@Piero87 Thank you for a good and relevant question.

While v6.x supports Realm Cloud, v10.x supports [MongoDB Realm Cloud](https://docs.mongodb.com/realm/). Moreover, v10.x has a number of new data types (`ObjectId`, `Decimal128` and embedded objects). For a local database (no sync), the differences are minimal. We consider v6.1.5 a legacy version, and we will only fix highly critical bugs.

**Comment by Piero87** [comment]
@kneth Thank you very much for the answer, at the moment I use only a local database, so I can switch to the v10.x safely
