### ISSUE TITLE
TypeError: Realm.App is not a constructor

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-js#3475]
## Goals

I am trying to connect to MongoDB Realm following the online Guide but the following line of code returns the error "TypeError: Realm.App is not a constructor"

const app = new Realm.App({ id: appId });

## Expected Results

I don't expect to get this error!

## Actual Results

"TypeError: Realm.App is not a constructor"

## Code Sample

See above

## Version of Realm and Tooling

- Realm JS SDK Version: 6.1.5
- Node or React Native: v12.20.0
- Client OS & Version: macOS11
- Which debugger for React Native: None

**Comment by kneth** [comment]
@duncangroenewald It looks like you are using v6.1.5 which doesn't support `Realm.App`. You will have to upgrade to the v10.x series.

**Comment by duncangroenewald** [comment]
@kneth - thanks, my bad for some reason the 'npm install realm' installed v6.1.5 instead of v10.1.1.  Thanks.
