### ISSUE TITLE
Realm insert queries  is taking 2 to 3 sec with huge data

### ISSUE THREAD

**Issue by PitlaSpandana** [realm/realm-js#3485]
## Goals
We are trying to improve the performance of realm js insertion queries with more than 10k records. 

## Expected Results
The realm insertion  query should take less than a sec.

## Actual Results
realm insertion query is taking 2-3 seconds

## Steps to Reproduce.
we have created a realm object which as 18 properties with couple of backlinking objects
we are trying to  insert 10000 records with 500 per API request(paginated) in a single write transaction
The initial insertions was faster  but as the number of inserted records reach 2000, it started taking 2-3 seconds for 500 insertions each
Due to this the entire time taken to insert  10k records into realm DB is around 60 seconds 

## Version of Realm and Tooling

- Realm JS SDK Version: ?  - 6.1.4
- Node or React Native: ? - 0.61.2
- Client OS & Version: ? - Android - 9
- Which debugger for React Native:  None

**Comment by nirinchev** [comment]
Did you try inserting all 10k records in a single transaction? Also, do you have indexes defined on your models?

**Comment by karthikpala** [comment]
@nirinchev - Yes even though we have paginated API calls, all of the data is inserted in a single write transaction as shown below.

**Comment by kneth** [comment]
v10.5.0 has a couple of performance related fixed.
