### ISSUE TITLE
line 3: npm: command not found for Examples

### ISSUE THREAD

**Issue by leijing7** [realm/realm-js#349]
Just followed the document as the examples. After git clone ..., git submodule... and npm install, I tried to run the code in Xcode but got below problem

/Users/leijing/Library/Developer/Xcode/DerivedData/ReactExample-gmfjpzjdkaqspqclkvxwssziqbow/Build/Intermediates/ReactExample.build/Debug-iphonesimulator/ReactExample.build/Script-02A3C7C11BC4597900B1A7BE.sh: line 3: npm: command not found

 I use nvm I guess this might help.

**Comment by alazier** [comment]
The example should be running nvm before running npm. The command it runs is 
```
[ -s "${HOME}/.nvm/nvm.sh" ] && . "${HOME}/.nvm/nvm.sh"
```
Does running this manually work for you?
