### ISSUE TITLE
Stuck at `Installing RealmJS` when doing `pod install`

### ISSUE THREAD

**Issue by Albert-Gao** [realm/realm-js#3490]
## Goals

Just `pod install` after `npm i && cd ios`

## Expected Results

It works.

## Actual Results

Stuck at when doing `pod install --verbose`
![image](https://user-images.githubusercontent.com/18282328/103492720-a7f4e100-4e91-11eb-8268-e695a1a16347.png)

## More Info

1. Download the URL directly from Chrome just works within 5min
1. Download when doing `pod install --verbose` takes more than 20min

## Steps to Reproduce

1. a new react-native project
1. npm i realm
1. cd ios
2. pod install --verbose

## Version of Realm and Tooling

- Realm JS SDK Version: "realm": "^10.1.2"
- Node or React Native: Node 14 / RN 0.63.4

**Comment by kneth** [comment]
As discussed in #2795, downloading can be difficult in the APAC region. We need to find another way to distribute binaries (see #3492).

**Comment by kneth** [comment]
I close the issue and ask you to follow #3492.
