### ISSUE TITLE
collection.watch() fails on React Native SDK

### ISSUE THREAD

**Issue by thehaiwave** [realm/realm-js#3494]
## Goals
I'm trying to monitor collection changes on a remote MongoDB Atlas database.

## Expected Results
I followed the example on the [official](https://docs.mongodb.com/realm/react-native/mongodb#std-label-react-native-mongodb-watch) Realm docs to use the collection.watch() functionality for the RN SDK. The example works with Node, and it returns any newly inserted objects in the collection, which is what I'm going for. The exact same code, however, does not work in my RN project.

## Actual Results
I get the following error message

```
EROR [TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.]
```

## Steps to Reproduce
The error can be reproduced running the following code with the specified SDK and RN versions at the bottom. I call this function inside the `componentDidMount()` function, which looks like this:

 ```js
 componentDidMount() {
    this.watchMessageCollection().catch((err) => console.log('ERROR', err));
  }
 ```
And watchMessageCollection():

```js
  async watchMessageCollection() {
    const {user} = this.props.session;
    const db = user.mongoClient('mongodb-atlas').db('main');
    const messages_collection = db.collection('chat_messages');
    const generator = messages_collection.watch();

    for await (const change of generator) {
      const {documentKey, fullDocument} = change;
      console.log(`new document: ${documentKey}`, fullDocument);
    }
  }

```
I tried running this function on different project files with the same result, so there's something about the generator itself that's off. The user auth works on my RN project, as do the database and collection connections.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.2
- Node: v15.1.0
- React Native: 0.63.4
- OS: Ubuntu 20.04.1 LTS

**Comment by kneth** [comment]
The watch implementation for React Native is unfortunately not stable. The reason is fetch implementation doesn't implement the entire spec (see https://github.com/facebook/react-native/issues/27741). If possible, using sync might be better.

**Comment by thehaiwave** [comment]
That is indeed unfortunate. Thank you for answering though, I'll start reading through the sync docs. Have a nice day!

**Comment by kraenhansen** [comment]
I'll reopen this issue as a reminder for us to improve this. It might be as easy as applying the [@react-native-community/fetch](https://github.com/react-native-community/fetch) polyfill (via [react-native-polyfill-globals](https://github.com/acostalima/react-native-polyfill-globals#polyfill-selectively-on-demand)).

**Comment by ianpward** [comment]
Whats the estimate with the new polyfills implementation from RN?

**Comment by capt4ce** [comment]
Hi @kneth, Is there any update regarding this?
Our team is planning to use Realm to trigger an operation when document is updated, so I think `sync` don't really serve the purpose for us.

**Comment by kneth** [comment]
After investigating the issue, we realized that it is required to enable the Babel plugin `plugin-proposal-async-generator-functions` in order to support async generators. But even with the plugin enabled, we still see issues with the `fetch` implementation. We continue the quest.

**Comment by kraenhansen** [comment]
This was the source-code for the app we used to debug this:

```javascript
import {useEffect} from 'react';
import Realm from 'realm';

import 'react-native-polyfill-globals/auto';

const app = Realm.App.getApp('realmjstestapp-jjhtf');
async function getUser() {
  await app.currentUser.logOut();
  if (app.currentUser) {
    return app.currentUser;
  } else {
    const credentials = Realm.Credentials.anonymous();
    return app.logIn(credentials);
  }
}

async function start() {
  const user = await getUser();
  console.log(user.id);
  const runs = user
    .mongoClient('mongodb-atlas')
    .db('watch-test-db')
    .collection('runs');
  console.log('Starting to watch!');
  for await (const run of runs.watch({})) {
    console.log('An event came in:', run);
  }
  console.log('Done watching!');
}

const App = () => {
  useEffect(() => {
    start().catch(console.error);
  }, []);
  return null;
};

export default App;
```

**Comment by Arijit1809** [comment]
@kraenhansen still facing this issue despite installing the polyfills and the babel plugin, the generator throws an error saying its not iterable

**Comment by SipNWork** [comment]
Still facing this issue after following all required steps.

**Comment by kneth** [comment]
@SipNWork 

Did you add the two required poly fills?

  1. Polyfills for `fetch`, `ReadableStream` and `TextDecoder`: https://www.npmjs.com/package/react-native-polyfill-globals
  2. Babel plugin enabling async generator syntax: https://npmjs.com/package/@babel/plugin-proposal-async-generator-functions

**Comment by kraenhansen** [comment]
@SipNWork can I get you to create another issue with the exact version of Realm JS you're using and ideally a small reproduction showing off the issue?

**Comment by SipNWork** [comment]
> @SipNWork can I get you to create another issue with the exact version of Realm JS you're using and ideally a small reproduction showing off the issue? If you have time it would also be great to hear if upgrading to Realm JS v12 (soon to be released as `latest`) helps solve the issue for you.

Created a new issue for above
https://github.com/realm/realm-js/issues/5858
