### ISSUE TITLE
new realm vs realm.open

### ISSUE THREAD

**Issue by code-assist** [realm/realm-js#3497]
I want to use realm on my mobile app.

But after study many examples, such as:

https://github.com/ezDeFi/nexty-mobile-RN/blob/21f8dd76017f9a422bda9dabe4f67d9ff246f968/realm/walletSchema.js
https://github.com/Resha1279/react-native-newsfeed/blob/9922908f6dccba24c5100260b3a6483ba6b8feaa/database/data.js
  ...

I have several puzzles.

1) Isn't it low performance do `Realm.open(databaseOptions)` on every CRUD API wrapper? Why not open once and save it as module scope variable for all CRUD API to call ?

2) Also, to get  realm object reference, when should  I  use `new Realm()`, when to use `Realm.open(databaseOptions)` ?

3) Is it thread-safe to do CRUD from multiple threads on React Native? ( Such as use https://www.npmjs.com/package/react-native-bg-thread to fork a new thread for CPU heavy jobs and do CRUD with realm)

4）Can I disable sync with remote server?  To archive it just by simple omit the server url ? I merely want to use realm as traditional DB with simple CRUD API, not care about the sync and data reactive feature.

**Comment by kneth** [comment]
1. Realm instances are cached which means that only the first `Realm.open()` is expensive.
2. `Realm.open()` is useful as it is an async call while `new Realm()` is synchronous. Actually, `Realm.open()` is more flexible, see for example https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.Sync.html#~OpenRealmBehaviorConfiguration.
3. You cannot use Realm objects across threads but you can open Realm instances on different threads and perform CRUD operations.
4. If you don't specify `sync` in your [configuration](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#~Configuration)  when you open your Realm (true for both `Realm.open()`  and `new Realm()`), no sync with a remote server is done.
