### ISSUE TITLE
Attempted to register RCTBridgeModule class RealmReact for the name 'Realm', but name was already registered by class RealmReact

### ISSUE THREAD

**Issue by miknonny** [realm/realm-js#350]
hi everyone, I have been trying to fix this error which happens after i run rnpm link realm on upgrading to Realm 0.11.0 on IOS. Works fine on android.

![simulator screen shot mar 26 2016 3 45 15 pm](https://cloud.githubusercontent.com/assets/3139804/14060623/d339e73e-f36a-11e5-860b-fb74cd4062f4.png)

Thanks.

**Comment by alazier** [comment]
Sounds like you are linking to both the old and new Realm libraries. You probably need to manually remove Realm.xcodeproj from your project before linking using rnpm.

**Comment by alazier** [comment]
The full instructions for updating to the new version were in the release note here https://github.com/realm/realm-js/releases/tag/v0.11.0

Were you able to get things working?

**Comment by miknonny** [comment]
Yes. fixed issue in both IOS and android. thanks so much!
