### ISSUE TITLE
Realm access from incorrect thread when accessing objects (React Native)

### ISSUE THREAD

**Issue by sawndur** [realm/realm-js#3507]
## Goals

Trying to access objects within a realm instance and getting their specific properties

## Expected Results

I was on an older version of realm 2.29.1 (react-native version 0.59.3) and never experienced any issues with accessing data from realm objects. But after upgrading to the latest version of realm (react-native 0.63), I have run into this issue of realm access from incorrect thread. 

I would also like to preface that this is an older codebase that I did not write and have taken over. After reading through the docs, it seems I am not utilizing realm.close() properly? Could that be a reason why this happened? The big issue is the way we get data is used in many places throughout the app and it is all following this format. 

## Actual Results

When trying to access a realm object; ex: realm.objects('files'), it throws the Realm access from incorrect thread. 

## Steps to Reproduce

I believe it would be better to show how the code is set up to retrieve said realm. 

This is the function that retrieves the realm instance. This is used widely throughout the app at different points to get data/delete data/write data.

![image](https://user-images.githubusercontent.com/60828583/104782119-537f1a80-5749-11eb-80a4-a466f7729f1e.png)

An instance of how the realm would be accessed is as such
![image](https://user-images.githubusercontent.com/60828583/104782483-e15b0580-5749-11eb-82c4-14b59642112c.png)

An example of writing
![image](https://user-images.githubusercontent.com/60828583/104782537-f9cb2000-5749-11eb-9846-d731785d68e0.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.3
- Node or React Native: Node 10.2 RN 0.63.4
- Client OS & Version: iOS 13.7
- Which debugger for React Native: None

**Comment by RedBeard0531** [comment]
I can't quite tell because the right edge of the screenshot is cut off, but are you passing a callback to `Realm.open(...)`? It only supports returning a promise and doesn't accept a callback. I suggest transforming your code into something like this:

```js
async getRealm() {
  if (this._realm == null)
    this._realm = await Realm.open(...); 
  return this._realm;
}
```

If that doesn't solve the problem, please post a full copy of the `getRealm()` function.

**Comment by sawndur** [comment]
My bad, I believe I am passing in the realm schema which comprises of the structure for the specific types of objects. 

![image](https://user-images.githubusercontent.com/60828583/104950128-bc52d680-5985-11eb-8367-4147068d2ded.png)

**Comment by sawndur** [comment]
> I can't quite tell because the right edge of the screenshot is cut off, but are you passing a callback to `Realm.open(...)`? It only supports returning a promise and doesn't accept a callback. I suggest transforming your code into something like this:
> 
> ```js
> async getRealm() {
>   if (this._realm == null)
>     this._realm = await Realm.open(...); 
>   return this._realm;
> }
> ```
> 
> If that doesn't solve the problem, please post a full copy of the `getRealm()` function.

So I reformatted my code to use async and await and the realm is opening correctly but the behavior is still the same. When I get the returned realm instance and if I try to access the objects using realm.objects('Projects'), it throws the Realm accessed from incorrect thread. 

![image](https://user-images.githubusercontent.com/60828583/104951463-2cfaf280-5988-11eb-859e-839ad7c40537.png)

The realm object that gets returned
![image](https://user-images.githubusercontent.com/60828583/104951507-41d78600-5988-11eb-9a08-14e57db8759e.png)

**Comment by kneth** [comment]
> Which debugger for React Native: None

Are the screenshots from a debugging session with Safari dev tools?

**Comment by sawndur** [comment]
> > Which debugger for React Native: None
> 
> Are the screenshots from a debugging session with Safari dev tools?

Yes. Would that make a difference? I have been able to access through the safari dev tools before. Using chrome debugger causes issue for me unfortunately

**Comment by kneth** [comment]
Realm objects cannot be accessed from another thread than the one created them. And unfortunately Safari dev tools are running in a different thread. While you can set breakpoints and single step using Safari dev tools, it is better to use `console.log()` in the your code.

> Using chrome debugger causes issue for me unfortunately

In November and December 2020 we worked on our chrome debugger support, so I am a bit curious what issues you encountered.

**Comment by sawndur** [comment]
> Realm objects cannot be accessed from another thread than the one created them. And unfortunately Safari dev tools are running in a different thread. While you can set breakpoints and single step using Safari dev tools, it is better to use `console.log()` in the your code.
> 
> > Using chrome debugger causes issue for me unfortunately
> 
> In November and December 2020 we worked on our chrome debugger support, so I am a bit curious what issues you encountered.

I appreciate your response. The issue we have with chrome debugger is somewhat weird. For one, we need to add an extra import from 'realm' in an area where we use it but this only applies for debugging. Another issue is the chrome debugger makes the app very unresponsive when it comes to touches. It takes around 30 seconds for touch responses to interact. The safari debugger gave us the best results as we were able to access the realm objects returned and test commands such as realm.objects('key') in the console. Would using vscode debugger be an option to view realm objects versus using console.log()?

**Comment by takameyer** [comment]
At the moment it isn't possible to access realm from different threads.  Until that is supported, you won't be able to access realm data from the console.  One alternative could be to use [Realm Studio](https://docs.mongodb.com/realm/studio/) and view the realm contents running in the iOS simulator.
We do want to make a better debugging experience in the future.  Once we are done with our Hermes support, we will be looking into better support using Flipper.  In the meantime, I hope Realm Studio can help.
