### ISSUE TITLE
Use realm 10.1.2 with react-native 0.59, IOS build throw error 'jsc_init.hpp' file not found

### ISSUE THREAD

**Issue by vietkhoa** [realm/realm-js#3509]
Upgrade realm from ^2.28.1 to 10.1.2
Realm 2.28.1 app run IOS ok
Realm 10.1.2 build throw error
Realm 10.1.2 Android run ok
## Goals

Build and launch on a physical and simulator iOS device

## Expected Results

Successful launch and no build error on physical Device

## Actual Results

node_modules/realm/src/rpc.hpp:25:10: fatal error: 
info 'jsc_init.hpp' file not found
#include "jsc_init.hpp"
         ^~~~~~~~~~~~~~

info 1 error generated.

## Steps to Reproduce

Just update realm 10.1.2 in package json and run ios-app

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.2
- Node version: 14.15.1
- React Native: 0.59.10
- Client OS & Version: IOS
- Xcode: 12

**Comment by fronck** [comment]
@vietkhoa The bundling of files in the RN framework has changes somewhat since version 2.x.
If you haven't already, please try hard-resetting the Metro Bundler's cache (`npx react-native start --reset-cache`) and, for good measure, the npm cache (`npm cache clean --force`, then rebuild).

**Comment by justindi15** [comment]
I'm having the same issue. Did you resolve this @vietkhoa ?

**Comment by smatioli** [comment]
I am having the same issue too. I tried the proposed workarounds but it does not work. Also, I tried to move files so it can be found, but after other errors happened. 

Any other suggestions?

**Comment by justindi15** [comment]
@smatioli what version RN are you on?

**Comment by smatioli** [comment]
Hi, I am at 0.63.4

**Comment by justindi15** [comment]
> Hi, I am at 0.63.4

What worked for me was to add `use_native_modules!` to the podfile, unlink your old realmJS, delete old RealmJS pod library in Libraries folder of the Xcode project, and then enable autolinking. Also try enabling use_frameworks.
