### ISSUE TITLE
Synchronization works but data is not visible in mongodb

### ISSUE THREAD

**Issue by euZebe** [realm/realm-js#3519]
## Goals

View synchronized data in mongoDB

## Expected Results

When creating a record in a realm, I would like to be able to see it in mongoDB.

## Actual Results

This feature worked well till today : I was able to request data created from realms in mongoDB (either from cloud.mongodb.com or from Robot 3T).
But right now, even if I can create data **which is correctly synchronized with other devices opening the same realm**, I can't request data in Mongo.

No Sync error can be found in mongo realm logs (which is quite logic since synchronisation works well).

Any suggestion ?

## Steps to Reproduce

Not found yet.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.1
- Node or React Native: React Native
- Client OS & Version: iOS 14.3, Android 10
- Which debugger for React Native: None

_Edit: same issue with Realm JS SDK 10.1.3_

**Comment by ianpward** [comment]
@euZebe Please open a ticket with MongoDB Support - Github issues are generally reserved for the non-sync versions of the Realm SDKs. Thank you
