### ISSUE TITLE
Storing date as milliseconds is not compatible with other bindings

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#355]
Because dates are stored as milliseconds, realm files can not currently be shared across languages. We need to normalize to the new standard format.

**Comment by abhaytalreja** [comment]
Do we have any solution on this? or a workaround?

**Comment by alazier** [comment]
@abhaytalreja There has been ongoing work to come up with a new date format that is consistent across all of Realm's bindings. That work is wrapping up and we hope to release this at the end of this month or in early May. Not sure the exact details yet but we plan to auto-migrate data stored in the old format to the new format.

**Comment by alazier** [comment]
@abhaytalreja this has just been released as `0.13.0-rc` on npm if you would like to give it a try.
