### ISSUE TITLE
Writing a 'modified' realm object with a boolean set to false causes field on object to be omitted. Setting to true works.

### ISSUE THREAD

**Issue by LawrenceMouarkach** [realm/realm-js#3559]
## Goals
NB we **have** an _id field in the schema: 
Please see example data:
{"_id":"7257-1612483200000-LM02-JD0002212345678911","_insertedTS":"2021-02-05T13:57:13.602Z","_modifiedTS":"2021-02-05T13:57:13.602Z","attemptsCount":null,"currentAddress":null,"edd":null,"eventDateTime":"2021-02-05T13:57:13.602Z","expected":false,"heldReason":null,"internallyModifiedDateTimestamp":"2021-02-05T13:57:13.602Z","ndd":null,"opUnit":"7257","originalAddress":null,"parcelInstanceNumber":0,"parcelUpi":"JD0002212345678911","partitionKey":"opUnit=7257&tourDate=2021-02-05&tourName=LM02","receivedBy":"751693","receivedDateTimestamp":"2021-02-05T13:57:13.602Z","tourDate":"2021-02-05T00:00:00.000Z","tourEventCode":null,"tourName":"LM02"}

Write a 'modified' realm object with a boolean set to false.

## Expected Results
boolean on object is set to false

## Actual Results
boolean field is omitted from write to atlas.

## Steps to Reproduce
1. create an object with parameter 'modified' 
1. set boolean on object to false

nb this works for setting a boolean to true

## Code Sample
newRealm.create('Object', {...object, field: false}, 'modified');

## Version of Realm and Tooling
* Realm JS SDK Version: 10.1.4
* Node or React Native: ReactNative
* Client OS & Version: Macos
* Which debugger for React Native: Chrome

**Comment by kneth** [comment]
Using `"modified"` requires a primary key in the schema. 

```js
const Realm = require("realm");

const MyObject = {
    name: "MyObject",
    properties: {
        field1: 'int',
        field2: 'bool'
    }
};

const MyObjectWithPk = {
    name: "MyObjectWithPk",
    primaryKey: "field1",
    properties: {
        field1: 'int',
        field2: 'bool'
    }
};

let realm = new Realm({ schema: [MyObject, MyObjectWithPk] });

realm.write(() => {
    realm.create("MyObject", { field1: 1, field2: false } );
    realm.create("MyObjectWithPk", { field1: 1, field2: false } );
});

console.log(`MyObject      : ${JSON.stringify(realm.objects("MyObject"))}`);
console.log(`MyObjectWithPk: ${JSON.stringify(realm.objects("MyObjectWithPk"))}`);

realm.write(() => {
    realm.create("MyObject", { field1: 1, field2: false }, "modified");
    realm.create("MyObjectWithPk", { field1: 1, field2: false }, "modified");
});

console.log(`MyObject       : ${JSON.stringify(realm.objects("MyObject"))}`);
console.log(`MyObjectWithPk : ${JSON.stringify(realm.objects("MyObjectWithPk"))}`);

realm.close();
```

This will give you the output:

```
MyObject      : [{"field1":1,"field2":false}]
MyObjectWithPk: [{"field1":1,"field2":false}]
MyObject       : [{"field1":1,"field2":false},{"field1":1,"field2":false}]
MyObjectWithPk : [{"field1":1,"field2":false}]
```

When using `"modfied"` with `Realm.create()`, the method is an [upsert](https://en.wikipedia.org/wiki/Merge_(SQL)#upsert) operation - but only if a primary key is defined.

**Comment by LawrenceMouarkach** [comment]
@kneth  we have got a primary key in the schema

**Comment by LawrenceMouarkach** [comment]
@kneth please reopen

**Comment by LawrenceMouarkach** [comment]
@kneth  {"_id":"7257-1612483200000-LM02-JD0002212345678911","_insertedTS":"2021-02-05T13:57:13.602Z","_modifiedTS":"2021-02-05T13:57:13.602Z","attemptsCount":null,"currentAddress":null,"edd":null,"eventDateTime":"2021-02-05T13:57:13.602Z","expected":false,"heldReason":null,"internallyModifiedDateTimestamp":"2021-02-05T13:57:13.602Z","ndd":null,"opUnit":"7257","originalAddress":null,"parcelInstanceNumber":0,"parcelUpi":"JD0002212345678911","partitionKey":"opUnit=7257&tourDate=2021-02-05&tourName=LM02","receivedBy":"751693","receivedDateTimestamp":"2021-02-05T13:57:13.602Z","tourDate":"2021-02-05T00:00:00.000Z","tourEventCode":null,"tourName":"LM02"}

**Comment by kneth** [comment]
Please share a code example.

**Comment by nirinchev** [comment]
If I understand the issue correctly, you create a RealmObject, set `myBool` to `false`, that gets synchronized to the server, but the field gets omitted from the MongoDB document. I'm also assuming that `myBool` is marked as `required` in your JSON Schema? If that's the case, then it is a known issue and the server team are looking into resolving it. The workaround is to manually set the value after the object has been created:

```csharp
realm.write(() => {
    let myObj = realm.create<Foo>(..., "modified");
    myObj.myBool = false;
});
```

**Comment by LawrenceMouarkach** [comment]
@nirinchev this is the workaround I am using, I would obviously prefer it if those changes were propagated could u please send me the link to the issue if there is one open and ill track that and u can close this.

**Comment by nirinchev** [comment]
Unfortunately, the server part of the product is not open source and their Jira tickets are not publicly accessible. We had a similar issue reported on the .NET repo and we're using that as the public counterpart to the Cloud ticket: https://github.com/realm/realm-dotnet/issues/2165.

**Comment by LawrenceMouarkach** [comment]
@nirinchev just out of curiosity why does setting a required bool to true work but not false?

**Comment by nirinchev** [comment]
`false` is the default value for booleans. When creating an object with the `modified` option, the SDK will try to reduce instructions sent to the server by omitting redundant instructions, such as instructions to set properties to their default values (`false`, `0`, `null`, etc.). Since the server doesn't see these instructions, it will not attempt to set the field on the MongoDB document, leaving it as missing.

This is a bug in the server and the fix we're working on is to ensure we backfill all required fields with their default values, even if the client didn't send them.

**Comment by LawrenceMouarkach** [comment]
@nirinchev is it ok if I track the issue on this ticket for now until the server changes happen, just to know when it has been fixed as I'm not monitoring the the dotnet  repos (our impl is react)

**Comment by nirinchev** [comment]
Sure, I'll link this ticket to the server one so that it gets closed automatically when the server changes go in.
