### ISSUE TITLE
currentUser.profile is not persistent after app restart

### ISSUE THREAD

**Issue by yourstruly22** [realm/realm-js#3561]
`##` Goals

When logging in a user I use metadata which is added to their currentUser.profile property which contain their partitionKey values needed to open a realm.
On app.login() the user object contains the profile property which contains all the needed metadata.
After the app is restarted, the user object persists and is still logged in, but the currentUser.profile property is empty.

## Expected Results

app.currentUser should persist when the app is restarted, including the profile property.

## Actual Results

app.currentUser.profile is empty after app restarts.

## Code Sample
```
import Realm from 'realm';
import {getRealmApp} from './getRealmApp';

const app = getRealmApp();
const AuthContext = React.createContext(null);

const AuthProvider = ({children}) => {
  const [user, setUser] = useState(app.currentUser);

const signIn = async ({username, password}) => {
       getCustomJwt({username, password})
      .then((jwt) => {
        const credentials = Realm.Credentials.jwt(jwt);
        // Authenticate the user
        app
          .logIn(credentials)
          .then((loggedInUser) => {
            setUser(loggedInUser);
          })
          .catch((err) => console.error('Failed to log in', err));
      })
      .catch((err) => console.log(err));
  };

  return (
    <AuthContext.Provider
      value={{
        signIn,
        user,
      }}>
      {children}
    </AuthContext.Provider>
  );
};
const useAuth = () => {
  const auth = useContext(AuthContext);
  if (auth == null) {
    throw new Error('useAuth() called outside of a AuthProvider?');
  }
  return auth;
};

export {AuthProvider, useAuth};
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.4
- Node or React Native: React Native
- Client OS & Version: Android 8.0.0
- Which debugger for React Native: Chrome DevTools

**Comment by kneth** [comment]
As `Realm.User.profile` is populated server-side, and it is a read-only property. You can use `Realm.User.customData` but it is also populated server-side. You can use [`Realm.User.apiKeys()`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.User.html#apiKeys) for this.

**Comment by nirinchev** [comment]
The profile data should be persisted between app restarts - I'm fairly certain I've seen code in OS that does that, so either we're not loading it correctly in OS or there's an issue with how JS is proxying it.

**Comment by yourstruly22** [comment]
I just need some way to persist an ID value in the User object that I use to open a realm for the user. I have a multi-tenant app and I partition the realms according to each tenant ID, which I store in the profile data (I use Custom JWT for authenticating), but every time the app restarts the User object loses it's profile data so I can't open a realm with the tenant ID.

**Comment by kneth** [comment]
@yourstruly22 It is fixed by https://github.com/realm/realm-js/pull/3895 and will be included in the next release.

**Comment by yourstruly22** [comment]
@kneth Thank you, I appreciate
