### ISSUE TITLE
User functions are not present if in debugging mode in React Native.

### ISSUE THREAD

**Issue by NilsBacke** [realm/realm-js#3566]
## Goals

Use functions like `user.callFunction()` and `user.mongoClient()` while debugging using Chrome.

## Expected Results

User functions should work properly whether I am in debugging mode or not.

## Actual Results

`user.mongoClient` is not a function.

## Steps to Reproduce

1. Create new React Native App.
2. Create new Realm App as seen in the code sample below.
3. Login using an existing user.

## Code Sample

Creating Realm App:
```
import Realm from "realm";

// Realm App config.
const APP_CONFIG = {
  id: '<my-app-id>'
};

const realmApp = new Realm.App(APP_CONFIG);

export default realmApp;
```

Login:
```
const user = await realmApp.logIn(Realm.Credentials.emailPassword('my-email', 'my-password'));
console.log('mongoClient', typeof user.mongoClient);
```

Not in debugging mode, the console log prints "mongoClient function"
In debugging mode, the console log prints "mongoClient undefined"

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.4
- Node or React Native: React Native 0.63.4
- Client OS & Version: macOS 11.2
- Which debugger for React Native: None/Chrome

**Comment by kneth** [comment]
@NilsBacke Thank you for reporting. We need to investigate why the functionality is missing in the debugger.

**Comment by kraenhansen** [comment]
I can reproduce this - thanks again for the bug report.

**Comment by NilsBacke** [comment]
Thanks guys, happy to put up a PR if you can point me in the right direction. Otherwise let me know if there's anything else I can do to help.

**Comment by madhenry** [comment]
Still an issue with the latest realm 10.2.0 for me - mongoClient is not present when react native debugging is turned on - either on simulator or device.

**Comment by NilsBacke** [comment]
@kneth @kraenhansen when can we expect this to be released?

**Comment by NilsBacke** [comment]
Unfortunately still seeing this issue on v10.3.0

**Comment by tonygomez** [comment]
@kneth @kraenhansen Unfortunately still seeing this issue on v10.3.0.  When can we expect this to be released?

**Comment by kneth** [comment]
It is included in v10.3.0. Since you report the same issue with v10.3.0, I reopen the issue.

**Comment by Xplosive06** [comment]
Still seeing this issue on v10.4.0

**Comment by kraenhansen** [comment]
Sharing our current thoughts on this issue: We're currently focussing on improving the developer experience of debugging an app using Realm JS by [adding support for JSI / the Hermes engine](https://github.com/realm/realm-js/issues/2455). As such, we're trying to limit the time we spent trying to fix issues in the current Remote JS debugger / RPC implementation. We understand that it might be frustrating being unable to debug apps when the Realm JS debugging implementation is broken, which is why we're trying to solve this once and for all by migrating to Hermes and debugging via [Flipper](https://fbflipper.com/).

**Comment by kneth** [comment]
As we have alpha releases (v10.20.0-alpha.1 is currently the latest) with Hermes support, please try them out.
