### ISSUE TITLE
Unable to export a default Realm settings to use in another file

### ISSUE THREAD

**Issue by Ngomana** [realm/realm-js#3567]
## Goals

I want to be able to call functions in my redux-thunk function so that it will handle whether it will push out the data to store or not as I do not want to use react context

## Expected Results

When there's data it should push it to redux store and updates the UI

## Actual Results
When I compile the app I get this error, it doesn't even give me the chance to login or create a new user. 
```
index.ts?77fd:8 Uncaught TypeError: Cannot read property 'id' of null
    at eval (index.ts?77fd:8)
    at Object../src/realm/index.ts (renderer.js:5394)
    at __webpack_require__ (renderer.js:791)
    at fn (renderer.js:102)
    at eval (index.ts?788b:2)
    at Object../src/redux/testReducer/index.ts (renderer.js:5427)
    at __webpack_require__ (renderer.js:791)
    at fn (renderer.js:102)
    at eval (index.ts?76a6:9)
    at Object../src/redux/index.ts (renderer.js:5416)
```

## Steps to Reproduce
1. I created called this file `globalRealm.ts`
2. Create a redux file called `itemsSlice.ts` in order to run realm function in it instead of a react component
3. import `useRealm` inside `itemSlice.ts` in order to do async functions and update the store

## Code Sample
```
import Realm from "realm";
import { getRealmApp } from "../functions/realmConfig";
import { ItemSchema } from "./itemSchema";

const app = getRealmApp();

const user = app.currentUser;
const partitionValue = app.currentUser.id;

const config = {
  schema: [ItemSchema], //other schema will be added in the future
  sync: {
    user,
    partitionValue, //app.currentUser.id,
  },
};

const useRealm = new Realm(config);

export default useRealm;
```

and create a redux thunk function to which will run when a user clicks a button
```
//redux-thunk function
export const getItems = createAsyncThunk("getItems", async (user) => {
  const response = useRealm.objects("Item");
  console.log(response);
});

//redux-reducer
  extraReducers: (builder) => {
    // [getItems.fulfilled]: (state, {payload}: PayloadAction<iTestItem>) => {
    //   state.push(payload)
    // },
    builder.addCase(getItems.fulfilled, (state, { payload }) => {
      console.log(`from redux `);
      console.log(payload);
      payload.forEach((item: any) => {
        return state.push(item);
      });
    });
  },
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0?
- React Native: React native?
- Client OS & Version: macOS?
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
You have `const user = app.currentUser` but I don't see any [`logIn()`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.html#logIn). With no user logged in `app.currentUser` will be `null`.

**Comment by Ngomana** [comment]
The logIn() function is in another file

**Comment by steffenagger** [comment]
But the runtime login functionality will not have been executed at the time you're exporting `useRealm`.
`app.currentUser` will always be `null` at this point.

Also worth noting: When working with a synced realm, you need to use the asynchronous `Realm.open(...)` to initialize the realm.
