### ISSUE TITLE
Promises / event loop stops working until UI is tapped

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#3571]
## Goals
Regular non-sync/offline use.

## Expected Results
Queries working as expected

## Actual Results
Running promises and queries inside a callback function causes the event loop to freeze until the UI is tapped/interacted with.

After trying to reduce the timeout calls to a minimum before/after each Realm query in order to prevent the UI from freezing due to long queries, I'm observing a new strange behaviour when running code inside a callback function.

Basically, any promise/setTimeout call will wait/freeze until the user taps or interacts with the UI. I will try to describe the issue as good as I can below, but it's really difficult to do.

## Steps to Reproduce
The following applies to Android.  On iOS, the behaviour is similar, but happens less frequently, and can be made to happen frequently by wrapping "queries" inside a setTimeout call.

The code uses a global component (that's mounted throughout the life of the app), and that listens to changes to a collection, runs a count query, and updates the UI through a redux/reducer call.  It is implemented as follows ( I will add some comments to show where the code stops running):

```
async componentDidMount(){
    try{
      this.queueListener = await getQueueCollection();
      this.queueListener.addListener(this.handleRealmUpdate);
    }
    catch(err){
      console.error("CRITICAL Queue: Failed to listen to queue collection: ", err.message || err);
    }
  }

handleRealmUpdate = (collection, changes) => {
    console.warn("Code 1");
    this.pollQueue(this.props).then(()=>{}).catch((err) => console.error("Failed to poll queue: ", err.message || err));
    console.warn("Code 2");
}

pollQueue = async (props) => {

    console.warn("Code A");
    let res = await count(user.groupId);
    console.warn("Code B");
    props.updateCounts(res.total, res.errors);
  }
```

The following are helper functions for the querying step:

```
export function asyncQuery(realm, cb){
  console.warn("Inner 0");
  return new Promise((resolve, reject) => {
    try{
      console.warn("Inner 1");
      if(!realm.isInTransaction){
        resolve(cb(realm));
        console.warn("Inner 2");
      }
      else{
        console.warn("Realm (query) was already in a transaction, delaying call one more loop.");
        setTimeout(()=>{
          try{
            resolve(cb(realm));
          }
          catch(err){
            reject(err);
          }
        });
      }
    }
    catch(err){
      reject(err);
    }
  });
}

export function asyncWrite(realm, cb){

  return new Promise((resolve, reject) => {

    try{
      if(!realm.isInTransaction){
        realm.write(() => {
          resolve(cb(realm));
        });
      }
      else{
        //console.warn("Realm (write) was already in a transaction, delaying call one more loop.");
        setTimeout(()=>{
          try{
            realm.write(() => {
              resolve(cb(realm));
            });
          }
          catch(err){
            reject(err);
          }
        });
      }
    }
    catch(err){
      reject(err);
    }
  });
}

export const countQuery = (realm, groupId) => {
  return {
    total: realm.objects('QueueItem').filtered(`groupId=${groupId}`).length,
    errors: realm.objects('QueueItem').filtered(`groupId=${groupId} AND error=true`).length
  }
}

export async function count(groupId){
  return await asyncQuery(global.realm, (realm) => {
    return countQuery(realm, groupId);
  })
}

export async function getQueueCollection(){
  return await asyncQuery(global.realm, (realm) => {
    return realm.objects("QueueItem");
  });
}
```

Lastly, when something happens that writes to the collection and in turn the callback is fired, the following is logged:

```
Code 1
Code A
Inner 0
Inner 1
Inner 2
//  the event loop freezes right here, until either a few seconds have passed, or until the user taps/interacts with the UI
// code resumes afterwards
Code 2
Code B
```

For iOS, this scenario happens much less often. However, if we wrap `asyncQuery` in a `setTimeout` call, the Android version gets "fixed", but iOS breaks 100% of the time.

## Code Sample
See above

## Version of Realm and Tooling

- Realm JS SDK Version: 10.1.4
- Node or React Native: React Native 0.62.2
- Client OS & Version: Android (11 / Pixel 5) / iOS (14.3 iphone 7)
- Which debugger for React Native: None

**Comment by cristianoccazinsp** [comment]
Additionally, a few other things to consider that may or not be related:

- There's a lot of processing before each realm write. This includes photo captures, photo post-processing, UI updates, and many async functions in between. 
- This doesn't seem to happen as often when there are simpler code paths (e.g., no processing or native code between calls).

**Comment by kraenhansen** [comment]
This sounds a bit like the symptoms from https://github.com/realm/realm-js/issues/2655.

**Comment by cristianoccazinsp** [comment]
Yes, at first I thought it was a rendering/setState issue from RN (and I even posted in that issue), but after further digging, it's not really just about `setState`, the code / loop just stops running ANY code.

Probably unrelated, but another issue I have been observing (and also the reason of the initial timeout calls), is that if you run "realm" code in the callback of a `setState` call, it will also freeze the entire UI rendering until realm finishes running (which is odd, since the state should be technically fully rendered on the callback). To circumvent this, anything that runs realm code must be enclosed in a setTimeout call, but it gets tedious, and iOS ends up with frozen event loops as I said above if we wrap everything in timeouts.

**Comment by cristianoccazinsp** [comment]
Upgraded to 10.2.0, and this still happens.

**Comment by kriti18singh** [comment]
@cristianoccazinsp did you find any workaround? I am not using Realm but facing a similar issue where my RN UI freezes until tapped or when RN debug menu comes up.

**Comment by cristianoccazinsp** [comment]
Not really, we just accepted this as a bug for now.
