### ISSUE TITLE
QUESTION: Does this package include the Spatial Functionality of Realm?

### ISSUE THREAD

**Issue by Stophface** [realm/realm-js#3575]
Looking at the [documentation](https://docs.mongodb.com/manual/geospatial-queries/), `mongoDB` is capable of doing that. But is `Realm-JS` for `react-native` too?

**Comment by kneth** [comment]
@Stophface Currently not (see also https://github.com/realm/realm-core/issues/1184).

**Comment by Stophface** [comment]
Thanks.
