### ISSUE TITLE
Installation React Native 0.63.4 

### ISSUE THREAD

**Issue by Muhametzhan-BG** [realm/realm-js#3578]
npm ERR! code 1
npm ERR! path /Users/user/Desktop/RN projects/AwesomePr/node_modules/realm
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build -j 8 ${npm_config_arch:+--target_arch=${npm_config_arch}}
npm ERR! Failed to execute '/opt/homebrew/Cellar/node/15.6.0/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --jobs=8 --module=/Users/user/Desktop/projects/AwesomePr/node_modules/realm/compiled/napi-v4_darwin_arm64/realm.node --module_name=realm --module_path=/Users/user/Desktop/RN projects/AwesomePr/node_modules/realm/compiled/napi-v4_darwin_arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.15.0
npm ERR! node-pre-gyp info using node@15.6.0 | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download

**Comment by Muhametzhan-BG** [comment]
I have Apple M1 
Big Sur 11.0.1
Node version 15.6.0

**Comment by zoobibackups** [comment]
install with the command

`npm i realm --force`

**Comment by Muhametzhan-BG** [comment]
@zoobibackups 
npm WARN using --force Recommended protections disabled.

**Comment by kneth** [comment]
@Muhametzhan-BG 

`npm ERR! node-pre-gyp info using node@15.6.0 | darwin | arm64` - we don't support M1 out of the box yet.

**Comment by Muhametzhan-BG** [comment]
@kneth When you support Apple M1?

**Comment by kneth** [comment]
I can't give a precise estimate, but it is on our radar.
