### ISSUE TITLE
App#getApp missing in Chrome debugging mode

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3579]
## Goals

A unified experience when running with or without chrome debugging mode.

## Expected Results

Calling the `getApp` static method on the `App` class should work when in Chrome debugging mode.

## Actual Results

An error is thrown in the Chrome console:

```
TypeError: _realm.App.getApp is not a function
```

## Steps to Reproduce & Code Sample

Run this in a React Native app running Chrome debugging mode:

```javascript
import { App } from 'realm';
const app = App.getApp('realmjstestapp-jjhtf');
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0
- Node or React Native: React Native in Chrome debugging mode
- Client OS & Version: iOS, N/A
- Which debugger for React Native: Chrome

## Additional context

A workaround for now is to create the app using the constructor:

```
const app = new App('realmjstestapp-jjhtf');
```

As documented in the implementation of `App#_setVersions` we have an outstanding task of making it easier to implement the RPC for a static method on some class (App, User, Credentials, etc.): https://github.com/realm/realm-js/blob/master/lib/browser/app.js#L38-L42

**Comment by tonygomez** [comment]
@kraenhansen still an issue as of 10.4.0.  Any idea when it will be fixed?

**Comment by tonygomez** [comment]
@kraenhansen do you know of any work-arounds?  I tried in safari and chrome.

**Comment by kraenhansen** [comment]
The best known workaround is to debug using Safari as explained here: https://github.com/realm/realm-js/issues/491#issuecomment-404670910

**Comment by bmunkholm** [comment]
Closing this as it will be resolved with the support for Hermes and the Flipper debugger. Please see [here ](https://github.com/realm/realm-js/issues/3940) to try it out and provide feedback. Thanks for your patience!
