### ISSUE TITLE
Question reg - Realm Sync limitation

### ISSUE THREAD

**Issue by saravanakumargn** [realm/realm-js#3585]
Please help me to solve the below usecase.

Example: In my application user have 10 categories in local. After login only 5 categories I should allow to Sync and store on MongoDB collections. Remaining categories I can skip/Delete.

**Comment by kneth** [comment]
It is a difficult use case to support at the moment. All objects in your synced Realm will eventually end in your MongoDB collection. Currently you will have to have two Realm: one synced Realm and one strictly local Realm.

**Comment by saravanakumargn** [comment]
Yes, I understood this. Thank you for your response. 
Can you please guide/Suggest to handle the below use case in my App?

1. Free users can create 5 categories Without login in offline mobile storage
2. After login user (Ex: user1@gmail.com), 5 categories can be sync
3. Now user logout/Using another device and created 5 categories (without login)
4. Now user login again using the existing previous mail id (Ex: user1@gmail.com) and new categories will start sync. already 5 categories are on the server. Now the user will have 10 categories in his account, Which is not allowed.

**Comment by nirinchev** [comment]
It's up to your app to enforce restrictions like this. You can add a server-side trigger that detects when >5 categories are inserted in a partition and mark the user as exceeding their limits. Then you can display a UI in the app prompting the user to delete the categories they don't want or to upgrade to a higher tier. In any case, this is not something within the scope of a general-purpose database SDK. If you need help structuring your app, you can either post a topic on our [community forums](https://community.mongodb.com) or reach out to the [professional services team](https://www.mongodb.com/products/consulting).

**Comment by saravanakumargn** [comment]
Thanks for your help @nirinchev @kneth
