### ISSUE TITLE
App crash after build and install to Android Phone.

### ISSUE THREAD

**Issue by just-innovate** [realm/realm-js#3586]
Feature Request: ./gradlew assembleRelease error

Bugs: App is crashed with message "/data/app/com.justshop.user-n5d4-1lkB6pyD9O4X5yn3Q==/lib/arm64/librealmreact.so result: 0"

## Expected Results

It should work properly after install

## Actual Results

FATAL EXCEPTION: create_react_context
Process: com.justshop.user, PID: 21843
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: Error: Cannot load /data/app/com.justshop.user-n5d4-1lkB6pyD9O4X5yn3Q==/lib/arm64/librealmreact.so result: 0
	at com.facebook.soloader.SoLoader.c(Unknown Source:353)
	at com.facebook.soloader.SoLoader.m(Unknown Source:99)
	at com.facebook.soloader.SoLoader.k(Unknown Source:102)
	at com.facebook.soloader.SoLoader.j(Unknown Source:1)
	at io.realm.react.RealmReactModule.<clinit>(Unknown Source:2)
	at io.realm.react.a.createNativeModules(Unknown Source:0)
	at com.facebook.v0.w.a(Unknown Source:41)
	at com.facebook.v0.f.b(Unknown Source:30)
	at com.facebook.v0.r.Q(Unknown Source:35)
	at com.facebook.v0.r.R(Unknown Source:54)
	at com.facebook.v0.r.q(Unknown Source:36)
	at com.facebook.v0.r.b(Unknown Source:0)
	at com.facebook.v0.r$e.run(Unknown Source:68)
	at java.lang.Thread.run(Thread.java:764)

## Steps to Reproduce

**1 )** ./gradlew assembleRelease

**2)** adb install /Users/macbookpro/Documents/Development/Mobile/RN/JustShop/android/app/build/outputs/apk/release/app-release.apk

## Code Sample

import Realm from 'realm';
import uuid from 'react-native-uuid';

import Moment from 'moment'

import {
    MESSAGE_STATUS_UNREAD,
    MESSAGE_STATUS_READ,
} from './GlobaleStaticVars';

export const generateID = () => {
    return uuid.v1();
};

let currentUser = null;

const UserSchema = {
    name: 'User',
    primaryKey: 'UserID',
    properties: {
        UserID: {type: 'int'},
        FirstName: {type: 'string'},
        image: {type: 'string', optional: true},
        PhoneNumber: {type: 'string'},
        Password: {type: 'string', optional: true},
        firebaseToken: {type: 'string', optional: true},
        status: {type: 'int',optional: true},
        roles: {type: 'string[]'},
        savedAddresses: {type: "UserAddress[]"},
        lastChatSyncDate:{type:'string', optional: true},
        current_page: {type: 'int', optional: true,default:1},
        created_at: {type: 'int', optional: true,default:1},
        last_page: {type: 'int', optional: true,default:1},
    },
};

const UserAddressSchema = {
    name: 'UserAddress',
    primaryKey: 'id',
    properties: {
        id: {type: 'int'},
        landmark: {type: 'string'},
        address: {type: 'string'},
        house: {type: 'string', optional: true},
        latitude: {type: 'string', optional: true},
        longitude: {type: 'string', optional: true},
        tag: {type: 'string', optional: true}
    }
};

const MessageSchema = {
    name: 'Message',
    properties: {
        id: {type: 'int'},
        user_id: {type: 'int'},
        message_title: {type: 'string'},
        message_body: {type: 'string'},
        type: {type: 'string', optional: true, default: 'product'},
        object_id: {type: 'int', optional: true},
        object_avatar: {type: 'string', optional: true, default: ''},
        priority: {type: 'int', optional: true, default: 0},
        status: {type: 'int', optional: true, default: 1},
        read: {type: 'int', optional: true, default: 1},
        last_massage:{type: 'string', optional: true, default: ''},
        last_message_date:{type: 'int', optional: true, default: 1},
        last_massage_type:{type: 'string', optional: true, default: ''},
        message_current_page: {type: 'int', optional: true, default: 1},
        message_last_page: {type: 'int', optional: true, default: 1},

        //items:{type: "MessageItem[]"},
    },
};

const MessageItemSchema = {
    name: 'MessageItem',
    properties: {
        id: {type: 'int'},
        user_message_id: {type: 'int'},
        message: {type: 'string', optional: true, default: ''},
        message_by: {type: 'int'},
        type: {type: 'string'},
        status: {type: 'int', optional: true, default: 1},
        read: {type: 'int', optional: true, default: 0},
        message_status: {type: 'int', optional: true, default: 0},
        created_at: {type: 'int', optional: true, default: 1},
        attachment: {type: "MessageAttachment?"},
    },
};

const MessageAttachmentSchema = {
    name: 'MessageAttachment',
    properties: {
        id: {type: 'int'},
        object_id: {type: 'int'},
        object_type: {type: 'string'},
        filename: {type: 'string'},
        url: {type: 'string'},
        mime_type: {type: 'string'},
    },
};

export const realm = new Realm({
    path: 'RNChat.realm',
    schema: [
        UserSchema,
        UserAddressSchema,
        MessageSchema,
        MessageItemSchema,
        MessageAttachmentSchema
    ],
});

export const getCurrentUser = () => {

    let users = realm.objects('User');
    currentUser = null;
    if (users.length > 0) {
        users.forEach(user => {
            currentUser = user;
        });
    }
    return currentUser;
};

export const addUser = (user,isUpdate) => {
    currentUser = user;

    const {UserID, FirstName, image, PhoneNumber, Password, firebaseToken, status} = user

    realm.write(() => {
        realm.create('User', {UserID, FirstName, image, PhoneNumber, Password, firebaseToken, status},isUpdate);
    });
};

export const updateUserMessagePage = (UserID,current_page,last_page) => {
    currentUser = getCurrentUser(UserID);
    if(currentUser){
        realm.write(() => {
            currentUser.message_current_page = current_page,
            currentUser.message_last_page =last_page
        });
    }

    return currentUser;
}

export const getMessages = (user_id) => {

    console.log("\n\n\n\n", user_id, "\n\n\n\n");

    const messages = realm.objects('Message').filtered(
        ' ( user_id = $0) ',
        user_id || 0
    );

    return messages.sorted('last_message_date', true);
}

export const deleteUser = () =>{
    realm.write(() => {
        let user = realm.objects('User');
        realm.delete(user);
    });
}

export const deleteAllMessage = () =>{
    realm.write(() => {
        let messages = realm.objects('Message');
        realm.delete(messages);
        let messageItems = realm.objects('MessageItem');
        realm.delete(messageItems);
    });
}

export const getMessage = (id, object_type, object_id) => {

    console.log("\n\n\n\n", id, object_type, object_id, "\n\n\n\n");

    const messages = realm.objects('Message').filtered(
        ' ( id = $0) OR ( object_id = $1 && type = $2 ) ',
        id || 0,
        object_id,
        object_type
    );

    let message = null;

    if (messages.length > 0) {
        message = messages[0];
    }

    return message;
}

export const getMessageItems = (message_id) => {
    const message_items = realm.objects('MessageItem').filtered(
        ' ( user_message_id = $0) ',
        message_id || 0
    );

    return message_items;
}

export const saveMessage = (message) => {

    realm.write(() => {
        const {id, user_id, message_title, message_body, type, object_id, object_avatar, priority, status, _read, last_message, last_message_type, current_page,created_at, last_page} = message

        let last_message_date = message.last_message_date

        console.log("message ..... ",last_message_date)

        realm.create('Message', {
            id:id,
            user_id:user_id,
            message_title,
            message_body: (message_body ? message_body : ""),
            type:type,
            object_id:object_id,
            last_message,
            last_message_date,
            last_message_type,
            object_avatar,
            priority:parseInt(priority),
            status,
            read:_read,
            current_page,
            last_page,
            created_at:Moment(created_at).unix(),
        });
    });
}

export const setUnreadMessage = (message_item) =>{
    const currentMessage = getMessage(message_item.user_message_id);

    if(currentMessage){
        console.log("currentMessage ",currentMessage);
        realm.write(() => {

            const message_item_id = message_item.id
            const message_item_type = message_item.type
            const message_item_read = message_item._read
            const message_item_status = message_item.status
            const {user_message_id, message, message_by, created_at, attachment} = message_item;

            currentMessage.last_message=message
            currentMessage.last_message_date =Moment(created_at).unix()
            currentMessage.last_message_type= message_item_type
            currentMessage.read =message_item_read

            let item = realm.create('MessageItem', {
                id:message_item_id,
                user_message_id,
                message,
                message_by: parseInt(message_by),
                type:message_item_type || "product",
                status:message_item_status,
                read:message_item_read,
                created_at:Moment(created_at).unix(),
                attachment
            });

        });
    }

}

export const saveMessages = (messages) => {
    for (let i = 0; i < messages.length; i++) {
        //console.log(messages[i])
        saveMessage(messages[i]);
    }
}

export const saveMessageItems = (message_items,messageFromServer) => {
    if(!message_items) return;
    realm.write(() => {
        if (message_items.length > 0) {

            let _message = getMessage(message_items[0].user_message_id);

            if(!_message && messageFromServer){
                const {
                    id,
                    user_id,
                    message_title,
                    message_body,
                    type,
                    object_id,
                    object_avatar,
                    priority,
                    last_message,
                    last_message_date,
                    last_message_type,
                    status,_read,
                    current_page,
                    last_page,
                    created_at
                } = messageFromServer;

                realm.create('Message', {
                    id:parseInt(id),
                    user_id:parseInt(user_id),
                    message_title,
                    message_body: (message_body ? message_body : ""),
                    type,
                    object_id:parseInt(object_id),
                    last_message,
                    last_message_date:Moment(last_message_date).unix(),
                    last_message_type,
                    object_avatar,
                    priority:parseInt(priority),
                    status,
                    read:_read,
                    current_page,
                    last_page,
                    created_at:Moment(created_at).unix(),
                });
            }

            for (let i = 0; i < message_items.length; i++) {

                let message_item = message_items[i];

                const {id, user_message_id, message, message_by, type, status, _read, created_at, attachment} = message_item;
                let item = realm.create('MessageItem', {
                    id,
                    user_message_id,
                    message,
                    message_by: parseInt(message_by),
                    type,
                    status,
                    read:_read,
                    created_at:Moment(created_at).unix(),
                    attachment
                });
            }
        }
    });
}

export const updateMessageCount = (current_page, last_page) => {
    realm.write(() => {
        realm.create('Message', {current_page, last_page}, true);
    });
}

## Version of Realm and Tooling

- Realm JS SDK Version: ^10.0.0-beta.12
- Node or React Native: 0.61.5
- Client OS & Version: ? None
- Which debugger for React Native: Firebase A/B Labs

**Comment by kneth** [comment]
I suggest that you upgrade from v10.0.0-beta.12 to a recent version.
