### ISSUE TITLE
Add to Docs that sorted takes an optional second argument

### ISSUE THREAD

**Issue by cancan101** [realm/realm-js#359]
Docs should indicate that `sorted` takes an optional second argument indicating sort order.

**Comment by appden** [comment]
The [Realm.Collection.sorted](https://realm.io/docs/react-native/latest/api/Realm.Collection.html#sorted) API docs cover this, but you're right, we should add it to the [sorting section](https://realm.io/docs/react-native/latest/#sorting) of the main doc page.

**Comment by MrHubble** [comment]
The above link is dated. For anyone else looking, here is the relevant info:

![screen shot 2017-05-15 at 9 08 11 pm](https://cloud.githubusercontent.com/assets/2251631/26055098/ba9d6b08-39b2-11e7-8e70-e2f6df484526.png)
