### ISSUE TITLE
Which versions are supported?

### ISSUE THREAD

**Issue by liamjones** [realm/realm-js#3592]
Apologies if this is the wrong place to ask the question but StackOverflow, etc didn't feel correct since it's 3rd-party.

What are the officially supported versions currently? I'm guessing 6.x and 10.x since both had releases recently?

Is there a page somewhere in the docs/website that I'm missing which lists which versions are supported/out of support?

**Comment by kneth** [comment]
Version 6.x is supporting Realm Cloud (our legacy sync solution). With Realm Sync's [General Availability](https://www.mongodb.com/press/mongodb-announces-general-availability-of-device-to-cloud-data-sync-to-accelerate-missioncritical-mobile-development), we will only provide critical bug fixes to this series and Realm Cloud service will be shutdown in the near future.

Version 10.x supports [MongoDB Realm](https://docs.mongodb.com/realm/), and we are actively maintaining and enhancing the 10.x series.

If you don't use sync, version 6.x and version 10.x don't differ, and we recommend that you upgrade. If you are using the legacy Realm Cloud, we urge you to migrate as soon as possible.

**Comment by liamjones** [comment]
Thanks for confirming @kneth!
