### ISSUE TITLE
Unhandled promise rejection TypeError: value.toJSON is not a function

### ISSUE THREAD

**Issue by EricWiener** [realm/realm-js#3600]
## Goals
I am trying to convert a Realm.Object to JSON. This has previously worked (RealmJS 6.0.5), but is now failing. This issue only occurs when an image is part of object (stored as a `CreamAsset` from `IceCream`). The image doesn't have a `toJSON()` attribute, but it seems like RealmJS recursively calls `.toJSON()` on everything in the object.

## Expected Results
I expected no errors.

## Actual Results
```
let existingProduct = realm.objectForPrimaryKey('Product', product.id as string) as Product;
console.log(JSON.stringify(existingProduct));
```

Here is the `Product` schema:
```
export const ProductSchema = {
  name: 'Product',
  primaryKey: 'id',
  properties: {
    id: 'string',
    createdTime: 'int',
    lastEditTime: 'int',
    title: 'string?',
    brand: 'string?',
    tags: 'string[]',
    // I believe this is where the trouble lies
    image0: 'CreamAsset?', // I am also using IceCream Sync v2.0.0
    thumbnail: 'CreamAsset?',
    isDeleted: 'bool',
  },
};

```

Results:
```
ERROR    Unhandled promise rejection [TypeError: value.toJSON is not a function. (In 'value.toJSON(key, cache)', 'value.toJSON' is undefined)]
```

## Steps to Reproduce
Try to convert a Realm.Object to JSON.

## Code Sample
```
let existingProduct = realm.objectForPrimaryKey('Product', product.id as string) as Product;
console.log(JSON.stringify(existingProduct));
```

I can provide the example project privately.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.2.0
- Node or React Native: 0.63.4
- Client OS & Version: iOS 14.4 iPhone 11 Pro Simulator
- Which debugger for React Native: None

**Comment by EricWiener** [comment]
I was able to work-around this issue by adding a `toJSON` function to my `IceCreamSchema`. I originally had:

```
class CreamAssetSchema {
  static schema = {
    name: 'CreamAsset',
    properties: {
      uniqueFileName: 'string',
    },
  };
}
```

and I updated it to be:
```
class CreamAssetSchema {
  static schema = {
    name: 'CreamAsset',
    properties: {
      uniqueFileName: 'string',
    },
  };

  toJSON() {
    return {};
  }
}
```

This seems like it shouldn't be necessary

**Comment by steffenagger** [comment]
@EricWiener could you please test if extending your `CreamAssetSchema` class model from `Realm.Object` would fix this?

Example:
```js
class CreamAssetSchema extends Realm.Object {
  static schema = {
    name: 'CreamAsset',
    properties: {
      uniqueFileName: 'string',
    },
  };
}
```

**Comment by EricWiener** [comment]
Thanks so much for the response @steffenagger! That fixed the issue. 

Also thanks for the sidenote. I appreciate the heads up!

**Comment by Adrielripoll** [comment]
@steffenagger Man, I love you. I tried to solve this issue for 4 hours, reading every issue and documentation related, but nothing worked. 
Your answer saved me. S2
