### ISSUE TITLE
submitAnalytics causing ReferenceError: trying to `import` a file after the Jest environment has been torn down

### ISSUE THREAD

**Issue by justindi15** [realm/realm-js#3608]
While running jest unit tests on both v10.2.0 and v6.1.6 I am getting the error:

`ReferenceError: You are trying to import a file after the Jest environment has been torn down`

I have looked through the version diffs for these releases and what is causing the error and have narrowed it down the the new analytics changes. Specifically, in lib/submit-analytics.js 

<img width="889" alt="Screen Shot 2021-02-22 at 3 10 55 PM" src="https://user-images.githubusercontent.com/36427961/108783767-e66a5c00-7522-11eb-9f6e-4b434d022ed0.png">

Removing the 100ms timeout promise delay solves the issue. I'm wondering what was the reason for adding this?

## Goals

Run jest unit tests with realm. 

## Expected Results

Jest unit tests to run as normally on v10.1.4 and below and v6.1.5 and below.

## Actual Results

<img width="1019" alt="Screen Shot 2021-02-16 at 8 04 40 PM" src="https://user-images.githubusercontent.com/36427961/108784064-5f69b380-7523-11eb-90b3-4235223da85d.png">

## Version of Realm and Tooling

- Realm JS SDK Version: v10.2.0 and v6.1.6
- Node or React Native: React Native
- Client OS & Version: RN 0.62
- Which debugger for React Native: None

**Comment by justindi15** [comment]
Seems like a regression from #3524

**Comment by fronck** [comment]
@justindi15 Thanks for reporting this.  I think you're right about the regression report, and we'll look into the issue.
To answer your question, the 100ms timeout is there to allow for an opt-out by setting the `REALM_DISABLE_ANALYTICS` env variable.

**Comment by kneth** [comment]
@justindi15 A fix has been released in v10.3.0-rc.1.
