### ISSUE TITLE
Aggregate $lookup

### ISSUE THREAD

**Issue by versoworks** [realm/realm-js#3614]
## Goals

Apologies if I've missed it; looking at the docs and based on testing it appears `$lookup` is unsupported with aggregate queries as they timeout.

Without `$lookup` support, it severely limits the usefulness of Realm web with objects containing manual references. Are there any plans to support `$lookup` (with `$mergeObjects` if possible) any time soon ?

**Comment by kraenhansen** [comment]
The client-side Realm JS SDK doesn't impose any restrictions on the stages sent to the server. As such, any limitation on aggregation stages are imposed by the server. Therefore I'll close this issue and suggest that you create a post on our developer community instead: https://developer.mongodb.com/community/forums/

---

That being said, please see [the "Aggregation Pipeline Stage Availability"](https://docs.mongodb.com/realm/mongodb/crud-and-aggregation-apis/#std-label-mongodb-crud-and-aggregation-apis-aggregation) section of our docs for limitations to the aggregation pipeline stages when used via MongoDB Realm.

Reading this `$lookup` should be supported in an aggregation pipeline executed via Realm Web.

Would you be able to share an example of this behaviour, such as a free tier application setup to reproduce it. I believe that would be of great value to help us pinpoint the source of any timeouts you might be experiencing.

**Comment by versoworks** [comment]
@kraenhansen thanks for the detailed response; it's very much appreciated.

With your help. we were able to identify the cause of the timeouts; we had the `$lookup` placed before the `$match` in the pipeline. Moving the `$match` before the `$lookup` resolved the issue.

**Comment by kraenhansen** [comment]
Thanks great! I'm happy that helped.
