### ISSUE TITLE
downloadAllServerChanges is not a function when debugging

### ISSUE THREAD

**Issue by mark-williams** [realm/realm-js#3630]
## Goals
I'm unable to debug an application that makes a call to _downloadAllServerChanges_ on the realm _syncSession_

## Actual Results
When attaching a debugger (react-native debugger) I get the following error reported in the console:

TypeError: syncSession.downloadAllServerChanges is not a function

## Code Sample
```
 if (syncSession) {
      syncSession
        .downloadAllServerChanges(CHECK_SYNC_COMPLETE_TIMEOUT)
        .then(() => setSyncCompleted(true))
        .catch(() => setSyncCompleted(true));
    } 
}
```

## Version of Realm and Tooling

Realm npm package: 10.2.0
react-native: 0.63.3
Android: 10
node: v14.13.1
Debugger for React Native: react native debugger 0.11.5

**Comment by kneth** [comment]
@mark-williams Thank you for the bug report.

I don't think it does matter if you are using React Native Debugger or Chrome Debugger but I have two questions:

* Can you debug on iOS?
* `uploadAllLocalChanges()` work?

**Comment by mark-williams** [comment]
@kneth Thanks for the reply

- We're only targeting Android, so don't build for iOS
- Same error for `uploadAllLocalChanges()`

TypeError: syncSession.uploadAllLocalChanges is not a function

**Comment by kneth** [comment]
@mark-williams Thank you for the update. It sounds like the methods on `Realm.Sync.Session` are not attached correctly in the debugger. We will investigate and find a fix.

**Comment by mark-williams** [comment]
@kneth We get a similar error while trying to call `refreshCustomData` against the `currentUser` prop of the realm:

```await app.currentUser.refreshCustomData();```

**Comment by andrew-whitmore** [comment]
@kneth any progress on this at all?

**Comment by kneth** [comment]
@andrew-whitmore Unfortunately not. We hope to return to it after Easter.

**Comment by mark-williams** [comment]
@kneth - any progress?

**Comment by Meknassih** [comment]
I’m having the same issue, did you manage to find a work around @mark-williams ?

**Comment by kneth** [comment]
We are not planning to fix bugs or add functionality to the Chrome debugger support and we suggest that you migrate to Hermes and start using Flipper as debugger.

**Comment by mark-williams** [comment]
OK, thanks @kneth

**Comment by kneth** [comment]
v11.0.0 removed support for the Chrome debugger and we suggest you to use Hermes and Flipper.
