### ISSUE TITLE
Web: Can't authenticate an anonymous user in incognito mode

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3632]
In [this post on the forum](https://developer.mongodb.com/community/forums/t/realm-annonymous-auth-not-working-on-private-incognito-mode/98373) a user reports an inability to authenticate using the anonymous authentication provider when in incognito mode:

> I am using the realm-web sdk and when the app.logIn(Realm.Credentials.anonymous()) it stores the user id and auth tokens in local storage. In a new private window my application won’t authenticate an anonomous user and there is nothing stored in the local storage.

## Goals & Expected Results
Authenticate anonymously while in Chrome incognito mode.

## Actual Results
To be determined.

## Steps to Reproduce
1. Start a Chrome browser window in incognito mode.
1. Authenticate anonymously.

## Version of Realm and Tooling
* Realm JS SDK Version: Realm Web 1.2.1
* Node or React Native: Web
* Client OS & Version: N/A
* Which debugger for React Native: None

**Comment by kneth** [comment]
@adam91holt Unfortunately not.

**Comment by kraenhansen** [comment]
I just tried to reproduce this, but failed. It seems to have been resolved 🤷 If not, please re-create the issue with more detailed steps on how to reproduce it 👍
