### ISSUE TITLE
Getting _asyncOpen@[native code] when trying to open a realm

### ISSUE THREAD

**Issue by luco** [realm/realm-js#3643]
## Goals
Open the realm.

## Expected Results
Open the realm.

## Actual Results
Getting `_asyncOpen@[native code]` on error.

## Steps to Reproduce

```
const ChatSchema = {
		name: 'chat',
	    properties: {
	      _id: 'objectId',
	      part1: 'objectId',
	      from: 'objectId',
	      to: 'objectId',
	      readAt: 'date',
	      type: 'string',
	      body: 'string',
	      media: {
	      	thumbnail: 'string',
	      	path: 'string',
	      	blurhash: 'string',
	      },
	      available: 'boolean',
	    },
	    primaryKey: '_id',
}


const getRealmApp = () => {
	const appId = 'xxxxxxxx'; // ID hidden
	const appConfig = {
	     id: appId,
	     timeout: 10000,
	};
	return new Realm.App(appConfig);
}

const userLogin = async () => {
	const app = getRealmApp();
	const cred = Realm.Credentials.emailPassword('test@test.com', '123456');
	user = await app.logIn(cred);
	return user;
}

const openRealm = async () => {
	let user = await userLogin();
	try {
	  const config = {
	    schema: [ChatSchema],
	    sync: {
	      user: user,
	      partitionValue: "part1",
	      error: (error) => {
	            console.log(error.name, error.message);
	          },
	    },
	  };
	 let realm = await Realm.open(config);
	} catch (error) {
		console.log(error);
	}
}

```

## Version of Realm and Tooling
* Realm JS SDK Version: 10.2.0
* Node or React Native: React Native
* Client OS & Version: macOS 10.15
* Which debugger for React Native: Default Debugger

**Comment by luco** [comment]
Maybe related to #3555

**Comment by luco** [comment]
Same issue in `10.1.4`

**Comment by takameyer** [comment]
@luco Thanks for posting this issue.
What debugger are you actually using (chrome debugger)?  
Is this happening in iOS or Android?

**Comment by luco** [comment]
@takameyer Hey, thanks for replying. I'm using Chrome Debugger and iOS.

**Comment by takameyer** [comment]
@luco Thanks for getting back.  I am able to reproduce this.  I'll let you know when we have a solution.

**Comment by luco** [comment]
@takameyer Thanks!

**Comment by takameyer** [comment]
@luco sorry for taking so long to get back.  We have been busy on getting Hermes support, which will allow us to use Flipper for debugging.  This is more stable and should create a better debugging experience.

**Comment by takameyer** [comment]
We now have a Hermes release branch, which can be used with Flipper properly debug your application.  
You can start using it now:
```
npm install realm@hermes
```
We are actively working on this, so please share any problems you encounter by opening a new issue.
