### ISSUE TITLE
Can I use realm-js as free forever only for local in react-native ?

### ISSUE THREAD

**Issue by muhammadwafa** [realm/realm-js#3664]
I have a free application, with thousands of users, I want to use free services even local free database.

So I want to know is realm-js free as forever for react-native only as local ?

**Comment by blagoev** [comment]
Realm JS is free and open source with Apache License. 
You can use it to develop free and commercial applications. Also you will get updates with fixes and new features regularly . 
We would love to hear what applications you are developing and are there any challenges and issues you encounter for your apps using Realm.

Cheers

**Comment by kraenhansen** [comment]
I'm closing this again, since there are no immediate actions on our part. Please consider posting on https://community.mongodb.com if you have future questions / comments related to Realm 👍
