### ISSUE TITLE
npm install crashing with sh: cmake-js: command not found

### ISSUE THREAD

**Issue by Tadejo9** [realm/realm-js#3670]
## Goals
Trying to install node modules for project.

## Expected Results
Installed node modules.

## Actual Results
I get the following error.
```
npm ERR! code 127
npm ERR! path /Users/.../node_modules/realm
npm ERR! command failed
npm ERR! command sh -c prebuild-install || cmake-js rebuild
npm ERR! sh: cmake-js: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2021-03-31T09_48_36_996Z-debug.log
```
[Here](https://github.com/realm/realm-js/files/6235644/test.txt) I provide log file referenced above.

## Steps to Reproduce
Add realm to dependencies in package.json and configure it by the docs.

## Version of Realm and Tooling
- Realm JS SDK Version: 10.2.0(used to work couple of days ago) && 10.3.0
- Node or React Native: node 15.12.0, RN: 0.63.2
- Client OS & Version: MacOS 11.2.3, M1 macbook pro
- Which debugger for React Native: None
- XCode version: 12.4

**Comment by Tadejo9** [comment]
Will downgrade and report back.

**Comment by Tadejo9** [comment]
It works on M1 mac also.

**Comment by CodingByJerez** [comment]
I have the same error on: my M1

**Comment by Tadejo9** [comment]
@CodingByJerez It seems you are using node 15.13.0

I suggest you follow this [article](https://tecadmin.net/install-nvm-macos-with-homebrew/) and downgrade to node 14.x as @kneth suggested above.

**Comment by CodingByJerez** [comment]
@Tadejo9 I managed to make it work with the version node 15.13.0
I installed cmake with brew

**Comment by gabrielrufino** [comment]
Same problem using node v14.16.0

**Comment by kneth** [comment]
> I have the same error on: my M1

@CodingByJerez 

We don't produce binary packages for M1 yet.

**Comment by kneth** [comment]
> Same problem using node v14.16.0

@gabrielrufino 

Which CPU architecture and operating system?

**Comment by BravenxX** [comment]
Same error here when installing node dependencies in a React Native (v0.64.0) Project on mac (on Windows the same project works well). Node version: 14.15.0.

My mac is a Macbook pro 2015.

**Comment by kneth** [comment]
@BravenxX 

I am not able to reproduce it using node 14.15.0, React Native 0.64.0 and Realm JavaScript 10.4.0 on my Macbook Pro (2019).

**Comment by flikQ** [comment]
So you guys just aren't going to support those on M1? @kneth or is this on your roadmap for sometime in the next 12-18 months?

**Comment by maihoanglai** [comment]
I followed the tut below to downgrade to node 14 and it worked on Mac M1 too. 
https://medium.com/@georgeenathomas/3-step-process-to-downgrade-node-version-using-homebrew-bc0b0a72ae27

**Comment by kneth** [comment]
> So you guys just aren't going to support those on M1?

M1 is on our radar, and we hope to have progress soon. One challenge is to support both MacOS and iOS with the same XCode project (see also [Xcode 12, building for iOS Simulator, but linking in object file built for iOS, for architecture arm64](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios)). We have been waiting for the (M1) dust to settle :smile:

**Comment by tomas-hartman** [comment]
What's the current status? I still cannot install realm on M1 Pro, even though I tried various node versions (14 and 16) and other above-mentioned tips (install cmake via brew) and different realm versions (10.1.2, 10.2.0 and 10.19.x).

**Comment by kraenhansen** [comment]
@tomas-hartman we're currently experiencing an issue with [an expired certificate](https://github.com/realm/realm-js/actions/workflows/install-test-react-native.yml), which has the same symptoms as this issue. Please try again tomorrow and everything should be fine 🙏

**Comment by angelos3lex** [comment]
I experience this again atm in github actions using ubuntu-latest, and node version 14.

**Comment by dinesh-brilworks** [comment]
Facing the same issue,

[stderr] npm ERR! code 127
[stderr] npm ERR! path /home/expo/workingdir/build/node_modules/realm
[stderr] npm ERR! command failed
[stderr] npm ERR! command sh -c -- prebuild-install --tag-prefix= -r napi || cmake-js build
[stderr] npm ERR! prebuild-install warn install certificate has expired
[stderr] npm ERR! sh: 1: cmake-js: not found

**Comment by husenbyjus** [comment]
Facing the same issue
<img width="975" alt="image" src="https://user-images.githubusercontent.com/92294901/211534698-473c5c2c-6eb6-4fe9-a2d4-e2007c9f1ead.png">
Node version is v16.13.1
mac with intel chip
