### ISSUE TITLE
Realm object constructor must not return another value when debugger running

### ISSUE THREAD

**Issue by aqos156** [realm/realm-js#3673]
## Goals

Debugging working with classes.

## Actual Results

![Snímek obrazovky 2021-04-02 v 15 18 32](https://user-images.githubusercontent.com/11147374/113418915-b4bc9e80-93c6-11eb-8772-cbe0397b4418.png)
## Steps to Reproduce

Try to access a realm object instance when debugging.

This error seems to be still happening in 10.3.0 - we have just migrated our code to be compatible with the version 10.x.x from 3.x.x and are facing this issue. If we do not use a debugger (RN Debugger, Google Chrome debugger) it works as expected.

### Model
```ts
export class User extends Realm.Object {
  static REGISTERED: number = 0;
  static GUEST: number = 1;
  static NOT_ACTIVATED: number = 2;

  static schema = {
    name: "User",
    primaryKey: "id",
    properties: {
      id: "int",
      etc...
    }
}
```

### Accessing an object instance
```js
const users = realm.objects("User");
console.log("Loaded", users[0]);
```
### lib/browser/objects.js (the error is thrown here)
![Snímek obrazovky 2021-04-02 v 15 12 47](https://user-images.githubusercontent.com/11147374/113418500-e5500880-93c5-11eb-8f87-2f5befa96a39.png)

### Console output
![Snímek obrazovky 2021-04-02 v 15 12 06](https://user-images.githubusercontent.com/11147374/113418446-cd788480-93c5-11eb-9fd2-a33f655b75e2.png)

### Error
![Snímek obrazovky 2021-04-02 v 15 18 32](https://user-images.githubusercontent.com/11147374/113418915-b4bc9e80-93c6-11eb-8772-cbe0397b4418.png)

## Version of Realm and Tooling

- Realm JS SDK Version: 10.3.0
- Node or React Native: 0.64.0
- Client OS & Version: Big Sur 11.2.3
- Which debugger for React Native: Tested with Chrom and React Native Debugger
- Affecting Android (tested with 10) and iOS (14.4.2)

**Comment by aqos156** [comment]
I have read that this error has been happening in since version v5 and is described here #3007 and #2790 (I have posted this write-up also in the comments there)

**Comment by kneth** [comment]
#3642 discussed the use of class models. I mentioned the issue since `User` extends `Realm.Object`.

Our Chrome Debugger support is brittle. As an alternative, you can use Safari DevTool and attach it to you running app (actually, the JavaScriptCore instance on the simulator or device).

**Comment by aqos156** [comment]
@kneth Well in comparison to that issue **we are not even using any constructors** inside of our models and the problem is being thrown even in safari dev tools (not tested with directly attaching to JavaScriptCore instance).

If I remove these lines from the mentioned code:
```ts
if (constructor) {
    let result = constructor.call(object);
    if (result != null && result != object) {
        throw new Error('Realm object constructor must not return another value');
    }
}
```

Then it seems to work quite well while debugger is running, but I do not know much about this codebase, so I don't know if it breaks something later on.

### Decorators
Another thing that has been bugging our team is the inability to utilize decorators inside of model properties in v10 (don't know compatibility in other version except in v3 it worked/works):
```ts
@model("User") // Defines model name and initializes schema - WORKS 
class User extends Realm.Object {
  // Defines type in schema - Doesn't work because the property becomes always undefined **without debugger**
  @property("string?") name?: string; 
}
```

> Note: This is not related to the inner workings of the individual decorator, the problem is that even an empty decorator that doesn't do anything behaves the same. The decorators itself work, but the property is always undefined without debugger.

This works **only in debugger** ... These issue combinations seem to be getting comical to be honest 😆  

I know there is an issue #877 already about this, but last activity is 2 years ago and it's only about official decorator support, which I don't need (and I suppose other people as well). The only thing that would be nice would be if the **property decorators worked in production and development builds _without dev tools_**. I have seen some investigation about workarounds for this problem in https://github.com/aklinker1/realm-ts-class-decorators/pull/18#issuecomment-625322305, but it has not been resolved.

Is there anything that can be done about this situation?

**Comment by bmunkholm** [comment]
Closing this as it will be resolved with the support for Hermes and the Flipper debugger. Please see [here ](https://github.com/realm/realm-js/issues/3940) to try it out and provide feedback. Thanks for your patience!
