### ISSUE TITLE
Error using objects.max function: Not implemented

### ISSUE THREAD

**Issue by aj3x** [realm/realm-js#3674]
## Goals

After updating from version `10.2.0` to `10.3.0`, one of our functions stopped working. Created a test function and tried to get max value on Objects using `max` resulting in an error.

## Expected Results

Get the max value from list of objects.

## Actual Results

Got the following error:
![Screenshot_20210405-094908](https://user-images.githubusercontent.com/15078358/113598104-dce01380-95f9-11eb-8995-c334b151c162.jpg)

## Steps to Reproduce

1. Create Realm
2. Get objects
3. Attempt to get max value from objects

## Code Sample

```
Model = {
  name: "Test",
  properties: {
    count: { type: "int" },
  },
};

// Receives list of objects
const objects = realm.objects("TEST");
// attempt to call max on list of objects
return objects.max("count");
// receives Not implemented
```

## Version of Realm and Tooling

- Realm JS SDK Version: 10.3.0
- Node or React Native: React Native 0.64
- Client OS & Version: Android 8.0.0 and iOS 14.4.2
- Which debugger for React Native: None

**Comment by hachther** [comment]
I have the same issue

**Comment by kneth** [comment]
Thank you for the bug report. We believe the bug is only on React Native, but we need to investigate further.

**Comment by davidsonsns** [comment]
Got the same here with `10.3.0`. Downgrading it to `10.2.0` worked perfectly.

**Comment by kneth** [comment]
We have merged a fix for it, and we plan to do a release early next week.
