### ISSUE TITLE
Remove part about rnpm isse #119 from the docs

### ISSUE THREAD

**Issue by Kureev** [realm/realm-js#368]
Hi there! 

Currently on the website you have an outdated info about linking process using `rnpm` :smiley: :

> WARNING: Due to an issue with rnpm (#119), if your project contains the word “Example” or “Test” then you must first explicitly tell rnpm where to find your Xcode project by adding the following to your package.json file:
```json
"rnpm": {
  "ios": {
    "project": "ios/<project-name>.xcodeproj"
  }
}
```

Can we update it?

**Comment by alazier** [comment]
Will do.

**Comment by alazier** [comment]
Docs were updated last week. Thanks again for the fix.
