### ISSUE TITLE
Geospatial Queries

### ISSUE THREAD

**Issue by caleb-harrelson** [realm/realm-js#3684]
## Goals

Sort or filter results by distance from user's current location.

## Expected Results

Be able to calculate a distance from the current lat/long to the lat/long on the record in question, or at least filter by those within X distance from a specified point. See [MongoDB's Geospatial Queries](https://docs.mongodb.com/manual/geospatial-queries/).

**Comment by kneth** [comment]
@caleb-harrelson Thank you for the suggestion. 
The query language is implemented in [Realm Core](https://github.com/realm/realm-core). You suggestion is in the lines of https://github.com/realm/realm-core/issues/1184. I can't give an estimate when we will implement it.
