### ISSUE TITLE
Crash when trying to access data from prepopulated database

### ISSUE THREAD

**Issue by Duell10111** [realm/realm-js#3689]
## Goals

Read data from predefined realm database created with NodeJS script

## Expected Results

Read data from predefined realm database created with NodeJS script

## Actual Results

App crashed when trying to access data with realm.objects
Logcat output:
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12697 (mqt_js), pid 12647 (zenfacesfitness)

## Steps to Reproduce

Run provided code below:

## Code Sample

App.tsx: 
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useData, useInit } from './src/storage';

export default function App() {
  const init = useInit();

  if(!init) {
    return (
      <View style={styles.container}>
        <Text>INIT ....</Text>
      </View>
    )
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <Data />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});


const Data = () => {
  const data = useData()
  return(
    <View>
      <Text></Text>
    </View>
  )
}
```

storage.ts

```
import Realm from 'realm'
import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';
import { useEffect, useState } from 'react';

class FoodSchema extends Realm.Object {
    static schema = {
        name: "FoodEntry",
        properties: {
            uuid: "string",
            name: "string",
            brand: "string?",
            custom: "bool?",
            subfoods : "FoodEntry[]"
        },
        primaryKey: "uuid"
    }
  
  }

const config : Realm.Configuration = {
    path: "db.realm",
    schema: [FoodSchema],
};

export async function transferDB() {
    await FileSystem.deleteAsync(dbfolder, {idempotent: true});
    await FileSystem.makeDirectoryAsync(dbfolder);
    await FileSystem.downloadAsync(
        Asset.fromModule(require('../assets/fooddb.realm')).uri,
        FileSystem.documentDirectory + "db.realm"
    )
}

export function useInit() {
    const [init, setInit] = useState(false)

    useEffect(() => {
        const run = async () => {
            await transferDB()
            setInit(true);
        }
        run();
    }, [])

    return init;
}

export function useData() {
    const [data, setData] = useState("");

    useEffect(() => {
        const realm = new Realm(config)

        const data = realm.objects(FoodSchema);
        data.forEach((v) => console.log(v.toJSON()))

        return () => realm.close()
    }, [])

    return data;
}

```

Prepopulated database if needed : 

https://drive.google.com/file/d/1xo10IMUtki0su9Bm1TfhpSb9esPTQx9V/view?usp=sharing

## Version of Realm and Tooling

- Realm JS SDK Version: 10.3.0
- Node or React Native: 0.63.4 (Ejected Expo SDK 41)
- Client OS & Version: Emulated Pixel 4 Android 11 x86
- Which debugger for React Native: None/Logcat Android Studio

**Comment by kneth** [comment]
I can see that you are copying the file manually. In the API, there is [`Realm.copyBundledRealmFiles`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#.copyBundledRealmFiles).

Moreover, I noticed that you are using Expo. Currently, [Expo doesn't support Realm](https://forums.expo.io/t/realm-support-with-the-new-mongodb-realm/40964).

**Comment by Duell10111** [comment]
> I can see that you are copying the file manually. In the API, there is [`Realm.copyBundledRealmFiles`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#.copyBundledRealmFiles).
> 
> Moreover, I noticed that you are using Expo. Currently, [Expo doesn't support Realm](https://forums.expo.io/t/realm-support-with-the-new-mongodb-realm/40964).

Does that makes any difference between copying it manually and with the api functions, because I checked through the device explorer in Android Studio that the realm file is the same and not corrupted.

Because of your mention of expo is not supported, I am currently using the ejected workflow from expo if this makes a difference.

**Comment by takameyer** [comment]
@Duell10111 Ejected expo should probably not make a difference.  So your goal is:
> Read data from predefined realm database created with NodeJS script
Can you provide more details in how you created the realm database with a NodeJS script?
