### ISSUE TITLE
Typos in docs - req to issue PR with corrections

### ISSUE THREAD

**Issue by plan-do-break-fix** [realm/realm-js#3697]
## Goals

Correct numerous typos in project documentation.

CONTRIBUTING.md explicitly asked typos be submitted as issues. Would you like me to paste in a list of the files and the typos with corrections or go ahead and issue a PR with the corrections?

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by bmunkholm** [comment]
@plan-do-break-fix A PR would be more than welcomed! If you would be so kind to also sign the CLA listed in Contributing then we can easily merge your fixes.
Thanks!
