### ISSUE TITLE
ReactJS `History` with `ObjectId` issue

### ISSUE THREAD

**Issue by versoworks** [realm/realm-js#3700]
Using realm-web v1.2.0. We're seeing an oddity when passing an object that contains a property of type `ObjectId` via the ReactJS `History` component. The object is initially passed as follows;

`history.push({ pathname: '/some-path', state: { object: myObject }});`

`myObject` contains a property of type `ObjectId` and is accessed in the `some-path` component as follows;

`const myObject= history.location.state.object;`

At this point `myObject` is whole; there are no issues. The issue arises when navigating to another path via `history.push` and subsequently returning to `some-path` via the web browser's Back button. At this point, all properties of type `ObjectId` within `myObject` are an empty object `{}`, while all other properties of `myObject` are unchanged.

Is this a known issue with ObjectId? I did search before posting this but didn't find anything related.

**Comment by kraenhansen** [comment]
@versoworks could you share a link to this "ReactJS History component"? The `ObjectId` is reexported from https://www.npmjs.com/package/bson and as such, you might get more progress on this issue by posting an issue there (with a link to this issue for context).

**Comment by versoworks** [comment]
@kraenhansen the History component is more accurately known as the [useHistory Hook](https://reactrouter.com/web/api/Hooks/usehistory).

**Comment by versoworks** [comment]
@kraenhansen here's the official response to this issue;

> BSON ObjectIds are not serializable by the HTML standards in the browser, so cannot be stored and retrieved out of the box. I would recommend converting the ObjectId to a serializable form when putting it in the history state and converting it back when used. A way to do this would be to convert it to it's hex string representation and back: oid.toHexString() and ObjectId.fromHexString().
