### ISSUE TITLE
Is there any way to inject Realm to mobile nodejs environment?

### ISSUE THREAD

**Issue by GHChrisSu** [realm/realm-js#3705]
We currently do a project that running a nodejs mobile version in android and ios, and we found that in mobile can only access by react-native, if we running a nodejs in mobile how to inject Realm to nodejs environment?

## Goals

Make realm object can be access in nodejs mobile environment

## Expected Results

nodejs-mobile can access realm object

## Actual Results

Realm object undefined

## Version of Realm and Tooling

- Realm JS SDK Version: 10.4.0
- Node or React Native: v12.19.0
- Client OS & Version: android, ios
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
We don't support environments like https://android-js.github.io/ at the moment, and it is unclear how to add support for a C++ library like Realm.

**Comment by GHChrisSu** [comment]
I mean using the library like this https://github.com/JaneaSystems/nodejs-mobile
and still have react-native version https://github.com/JaneaSystems/nodejs-mobile-react-native
but what I want is compile realm-js to the realm.node for mobile

**Comment by GHChrisSu** [comment]
Currently jsc have been override nodejs using v8 maybe some way can override v8 to nodejs, I think they are all in same thread, if library load in one place

**Comment by BruceSuperProgramer** [comment]
Have anyone find a solution so far?
