### ISSUE TITLE
Simplify by unifying build commands

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3708]
## Goals
A more approachable developer experience.

## Expected Results
The existing build-android.js and build-ios.sh scripts could be build around a shared CLI, to simplify consumption.

A bare "build" NPM script could provide a discoverable method of building for all supported runtimes.

```
npm run build -- --runtime ios --type Debug --arch x86
```

As an example, the following NPM scripts could expose discoverable shortcuts to build for the various supported runtimes:

```
 npm run build:node
 npm run build:ios
 npm run build:android
 npm run build:node:debug
 npm run build:ios:debug
 npm run build:android:debug
```

Bonus: It would be great to be able to set an environment variable or npm config to skip building Realm JS all together.
This would help simplify the "react native" integration test jobs on GitHub Actions.

## Actual Results
These are the commands needed to build the native module to run the integration tests:

### Building the native module for Node.js in debug mode:
```
npx cmake-js -d
```

### Building the native module (xcframework) for the iOS simulator in debug mode:
```
./scripts/build-ios.sh -c Debug -s
```

### Building the native module (.so) for the Android simulator in debug mode:
```
node scripts/build-android.js --arch=x86 --build-type=Debug
```

## Version of Realm and Tooling
* Realm JS SDK Version: `develop` branch
* Node or React Native: N/A
* Client OS & Version: N/A
* Which debugger for React Native: N/A

**Comment by kneth** [comment]
Should it be possible to specify if you want to build with or without sync (option `--sync` maybe)?
