### ISSUE TITLE
"Missing property value for property XXX" even though XXX is Optional

### ISSUE THREAD

**Issue by cancan101** [realm/realm-js#371]
I am getting the following error when trying to create even though the field is marked optional:
![image](https://cloud.githubusercontent.com/assets/51059/14229377/491d58d8-f900-11e5-9eda-b3baf938c545.png)

here is my schema:
```js
    {
      name: 'Exercise',
      properties: {
        id: Realm.Types.INT,
        target1: {type: Realm.Types.STRING, optional: true},
      }
```
with
```js
realm.create('Exercise', {
        id,
        // target1,
});
```

**Comment by alazier** [comment]
Just merged the fix for this in #369

Until we make the next release you can explicitly pass in `null` or `undefined` for optional properties to work around the issue, or you can build from source to get the fix immediately.

**Comment by appden** [comment]
@cancan101 We just released `0.12.0-rc`, which includes this fix. Please let us know if you notice any issues with it. Thanks!

**Comment by cancan101** [comment]
that seemed to work.

**Comment by appden** [comment]
@cancan101 Great to hear! We should be releasing the final `0.12.0` today or tomorrow at the latest.
