### ISSUE TITLE
Realm insert crashed with react-native-reanimated

### ISSUE THREAD

**Issue by Renjith-paul** [realm/realm-js#3713]
Without react-native-reanimated realm working fine. But after installing react-native-reanimaterv2 realm insert was crashed react native application without any crash log

**Comment by kneth** [comment]
@Renjith-paul Do you use Hermes as JS engine? If so, Realm doesn't support it yet (but we are looking into it).

**Comment by Renjith-paul** [comment]
I used js engine only.but facing crash on realm insertOn May 6, 2021 18:33, Kenneth Geisshirt ***@***.***> wrote:
@Renjith-paul Do you use Hermes as JS engine? If so, Realm doesn't support it yet (but we are looking into it).

**Comment by kneth** [comment]
By reading https://www.reanimated2.com/docs/next/installation, it looks like Realm and Reanimated v2 are incompatible. Try to downgrade to Reanimated v1.

**Comment by kneth** [comment]
I am closing as it seems to be a duplicate (or at least variation) of https://github.com/realm/realm-js/issues/3837

**Comment by zoobibackups** [comment]
> 
I has a massive impact on performance of the app, the app become lagy and lazy with realm and reanimated v1.
