### ISSUE TITLE
Case Insensitive sorting

### ISSUE THREAD

**Issue by cancan101** [realm/realm-js#372]
Is it possible to sort a query in a case insensitive manner (akin to using `[c]` when filtering)?

**Comment by alazier** [comment]
This isn't currently possible

**Comment by cancan101** [comment]
Is this a limitation in the underlying realm libraries?

**Comment by alazier** [comment]
Its not something the core currently supports and given the current roadmap it probably wont come any time soon. It is more likely that we will support custom sorting via a user callback before supporting this as a first class feature.
