### ISSUE TITLE
Reset password doesn't work in realm-web

### ISSUE THREAD

**Issue by jeanbaptistebeau** [realm/realm-js#3723]
## Goals

Reset the password of a user.

## Expected Results

The `resetPassword` function completes without errors and the password is reset.

## Actual Results

Getting the error `invalid token data`.

## Steps to Reproduce

- Replace the appID and the user email in the code below
- Run the script
- Copy paste the token and token ID you received by email in the script below
- Comment the `callResetPasswordFunction` and uncomment the `resetPassword`
- Run the script again

## Code Sample

```
const Realm = require("realm");

const appID = "appID";
const app = new Realm.App({ id: appID, timeout: 10000 });

const tokenId = "someTokenID";
const token = "someToken";

app.emailPasswordAuth.callResetPasswordFunction("someUserEmail", "password", []).then(
	(value) => {
		console.log("SUCCESS");
	},
	(error) => {
		console.log(error);
	}
);

// app.emailPasswordAuth.resetPassword("password", token, tokenId).then(
// 	(value) => {
// 		console.log("SUCCESS");
// 	},
// 	(error) => {
// 		console.log(token);
// 		console.log(tokenId);
// 		console.log(error);
// 	}
// );

```
## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-rc.2
- Node or React Native: Node 14.9.0
- Client OS & Version: MacOS Big Sur 11.3 Beta

Initially tracked here: https://developer.mongodb.com/community/forums/t/consistently-getting-invalid-token-data-when-trying-to-reset-user-password/100020/4

**Comment by jeanbaptistebeau** [comment]
EDIT: Updated to Realm JS SDK Version 10.4.0 and it works. 

It doesn't work when in a webscript script imported using: 
`<script src="https://unpkg.com/realm-web@1.2.0/dist/bundle.iife.js"></script>`

**Comment by jeanbaptistebeau** [comment]
I get `invalid token data` error

**Comment by jeanbaptistebeau** [comment]
Any news about that? Is it a real bug or am I doing something wrong?

**Comment by kushpetal** [comment]
Same issue here. Getting the same error.

**Comment by ryan-byrne** [comment]
For folks still having this issue, the documentation had the **wrong order of arguments**
```js
app.emailPasswordAuth.resetPassword('newPassword', token, tokenId)
```
Should be:
```js
app.emailPasswordAuth.resetPassword(token, tokenId, 'newPassword')
```
Which fixed the issue for me

**Comment by nisajthani18** [comment]
Thank you @ryan-byrne! x 100. This solution worked.

**Comment by fronck** [comment]
@ryan-byrne Thanks for reporting this mismatch.  We'll look into getting it fixed.

**Comment by salmanprk** [comment]
Hi this seems like there is a security hole. The initial "newPassword" value that you enter in **app.emailPasswordAuth.callResetFucntion(email, newPassword)** doesn't matter when you confirm it with **app.emailPasswordAuth.resetPassword(token, tokenId, newPassword)** 

What I really mean is that you can enter any value for password in **app.emailPasswordAuth.resetPassword(token, tokenId, newPassword)** and the realm-web SDK confirms the password change

**Comment by kraenhansen** [comment]
@salmanprk if you truly believe we have a security vulnerability, please consider deleting your comment and instead file a vulnerability report following the instructions on https://www.mongodb.com/security.

**Comment by salmanprk** [comment]
> https://www.mongodb.com/security

Hi @kraenhansen I think looking back it's better that I didn't use the word "security" vulnerability but may be "bug" as of right now because the resetPassword function doesn't work as I had shown above in September 2021 and you can imagine how from the app's (our app on MongoDB Realm) perspective it looks like "security" issue for our users. I will update my wording above but as you can see its critical for us. Let me know if I should post this elsewhere? I also posted this on MongoDB Developer Forum.
