### ISSUE TITLE
Document how to use $0 in filters

### ISSUE THREAD

**Issue by cancan101** [realm/realm-js#373]
How do I filter by a date?

I am trying:

``` js
.filtered(`workoutDate = "${workoutDate}"`)
```

and

``` js
.filtered(`workoutDate = ${workoutDate.getTime()}`)
```

but I get `You must pass in a date argument to compare`

**Comment by cancan101** [comment]
This worked:
```js
.filtered('workoutDate = $0', workoutDate)};
```

**Comment by MihaelIsaev** [comment]
Can someone add an example with `$0` to the [official docs](https://realm.io/docs/javascript/latest/#getting-started)?

**Comment by vinipachecov** [comment]
This really needs to be added to the official docs.

**Comment by bmunkholm** [comment]
It's random that I noticed this comment on a closed issue :-). It's better to create a new issue next time. But I will rephrase the title and reopen. Thanks for reporting this anyway though! :-)

**Comment by cbush** [comment]
An example exists in https://realm.io/docs/javascript/latest/#queries (search for '$0').
