### ISSUE TITLE
Support Visual Studio Code

### ISSUE THREAD

**Issue by zio-zhang** [realm/realm-js#374]
use realm ,when debug in chrome ,show error:

Unbalanced calls start/end for tag 0
Unhandled JS Exception: Module AppRegistry is not a registered callable module.
Missing Realm constructor - please ensure RealmReact framework is included!
Module AppRegistry is not a registered callable module.
Unhandled JS Exception: Missing Realm constructor - please ensure RealmReact framework is included!
Unhandled JS Exception: Module AppRegistry is not a registered callable module.

-------
Realm:0.11.0
React Native version: 0.22.2
OS:mac 10.11.4
simulator: iOS 9.2

**Comment by alazier** [comment]
Do things work when not in chrome debug mode?

If you are seeing this after upgrading from Realm v0.10.0 did you follow the setup instructions in the release notes? 
https://github.com/realm/realm-js/releases/tag/v0.11.0

**Comment by zio-zhang** [comment]
the error is show  in vs-code ,use  debug mode, debug iOS

**Comment by zio-zhang** [comment]
https://github.com/Microsoft/vscode-react-native/issues/198

**Comment by alcat2008** [comment]
Is there any progress?

**Comment by avishayil** [comment]
Hi, I still encounter these issues, on both Android and iOS.
Both problems are going away when disabling "Debug JS Remotely".
Both problems are going away when pre-loading chrome debugger by running `run-android` command and then debugging with vs code.
