### ISSUE TITLE
React-Native crashing in production

### ISSUE THREAD

**Issue by projuljustin** [realm/realm-js#3744]
## Goals

Using realm locally in react-native (not using realm sync)

## Expected Results

CRUD operations locally

## Actual Results

Unexpected crash in production 
`
Crashed: com.facebook.react.JavaScript
0  JavaScriptCore                 0x19ac05bd8 JSC::Structure::add(JSC::VM&, JSC::PropertyName, unsigned int) + 328
1  JavaScriptCore                 0x19ac05b38 JSC::Structure::add(JSC::VM&, JSC::PropertyName, unsigned int) + 168
2  JavaScriptCore                 0x19ac0560c JSC::Structure::addNewPropertyTransition(JSC::VM&, JSC::Structure*, JSC::PropertyName, unsigned int, int&, JSC::PutPropertySlot::Context, JSC::DeferredStructureTransitionWatchpointFire*) + 784
3  JavaScriptCore                 0x19a8c3e24 bool JSC::JSObject::putDirectInternal<(JSC::JSObject::PutMode)0>(JSC::VM&, JSC::PropertyName, JSC::JSValue, unsigned int, JSC::PutPropertySlot&) + 1700
4  JavaScriptCore                 0x19ab1dd24 JSC::JSObject::put(JSC::JSCell*, JSC::JSGlobalObject*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) + 408
5  JavaScriptCore                 0x19a26252c JSObjectSetProperty + 460
6  TestApp                         0x100ef65dc realm::js::Schema<realm::jsc::Types>::object_for_object_schema(OpaqueJSContext const*, realm::ObjectSchema const&) + 55 (jsc_object.hpp:55)
7  TestApp                         0x100f2f228 realm::js::RealmObjectClass<realm::jsc::Types>::get_object_schema(OpaqueJSContext const*, OpaqueJSValue*, realm::js::Arguments<realm::jsc::Types>&, realm::js::ReturnValue<realm::jsc::Types>&) + 36 (jsc_return_value.hpp:36)
8  TestApp                         0x100f2e5a8 OpaqueJSValue const* realm::js::wrap<&(realm::js::RealmObjectClass<realm::jsc::Types>::get_object_schema(OpaqueJSContext const*, OpaqueJSValue*, realm::js::Arguments<realm::jsc::Types>&, realm::js::ReturnValue<realm::jsc::Types>&))>(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 77 (jsc_return_value.hpp:77)
9  JavaScriptCore                 0x19a24fc34 long long JSC::APICallbackFunction::call<JSC::JSCallbackFunction>(JSC::JSGlobalObject*, JSC::CallFrame*) + 420
10 JavaScriptCore                 0x19a1fbee4 llint_entry + 159908
11 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
12 JavaScriptCore                 0x19a1d4b94 vmEntryToJavaScript + 276
13 JavaScriptCore                 0x19a8162ac JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 488
14 JavaScriptCore                 0x19ab23000 JSC::Stringifier::appendStringifiedValue(WTF::StringBuilder&, JSC::JSValue, JSC::Stringifier::Holder const&, JSC::PropertyNameForFunctionCall const&) + 1248
15 JavaScriptCore                 0x19ab2298c JSC::Stringifier::stringify(JSC::JSValue) + 224
16 JavaScriptCore                 0x19ab27350 JSC::JSONProtoFuncStringify(JSC::JSGlobalObject*, JSC::CallFrame*) + 140
17 JavaScriptCore                 0x19a1fbde4 llint_entry + 159652
18 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
19 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
20 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
21 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
22 JavaScriptCore                 0x19a1fa3d8 llint_entry + 152984
23 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
24 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
25 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
26 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
27 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
28 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
29 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
30 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
31 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
32 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
33 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
34 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
35 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
36 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
37 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
38 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
39 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
40 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
41 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
42 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
43 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
44 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
45 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
46 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
47 JavaScriptCore                 0x19a1f91a4 llint_entry + 148324
48 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
49 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
50 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
51 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
52 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
53 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
54 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
55 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
56 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
57 JavaScriptCore                 0x19a1f9258 llint_entry + 148504
58 JavaScriptCore                 0x19a1d4b94 vmEntryToJavaScript + 276
59 JavaScriptCore                 0x19a8162ac JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 488
60 JavaScriptCore                 0x19aac7f1c JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*) + 676
61 JavaScriptCore                 0x19a1fbde4 llint_entry + 159652
62 JavaScriptCore                 0x19a1fa8ec llint_entry + 154284
63 JavaScriptCore                 0x19a1fa8ec llint_entry + 154284
64 JavaScriptCore                 0x19a1fa8ec llint_entry + 154284
65 JavaScriptCore                 0x19a1fa8ec llint_entry + 154284
66 JavaScriptCore                 0x19a1d4b94 vmEntryToJavaScript + 276
67 JavaScriptCore                 0x19a8162ac JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 488
68 JavaScriptCore                 0x19aac7f1c JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*) + 676
69 JavaScriptCore                 0x19a1d4d50 vmEntryToNative + 288
70 JavaScriptCore                 0x19a8162dc JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 536
71 JavaScriptCore                 0x19aa230d0 JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 164
72 JavaScriptCore                 0x19a26471c JSObjectCallAsFunction + 568
73 TestApp                         0x100e7f1ac facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 1253 (JSCRuntime.cpp:1253)
74 TestApp                         0x100e889f8 facebook::jsi::Value facebook::jsi::Function::call<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value>(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value&&) const + 224 (jsi-inl.h:224)
75 TestApp                         0x100e88858 std::__1::__function::__func<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_4, std::__1::allocator<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_4>, void ()>::operator()() + 231 (JSIExecutor.cpp:231)
76 TestApp                         0x100daa880 void std::__1::__invoke_void_return_wrapper<void>::__call<void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()> >(void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 1831 (functional:1831)
77 TestApp                         0x100e861b0 facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&) + 1831 (functional:1831)
78 TestApp                         0x100e7b630 std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()() + 1720 (functional:1720)
79 TestApp                         0x100dc7fc8 facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 121412 (RCTCxxUtils.mm:121412)
80 TestApp                         0x100dd46e0 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 68 (RCTMessageThread.mm:68)
81 TestApp                         0x100dd44a0 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 45 (RCTMessageThread.mm:45)
82 CoreFoundation                 0x190add49c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
83 CoreFoundation                 0x190adc6e4 __CFRunLoopDoBlocks + 408
84 CoreFoundation                 0x190ad6aa0 __CFRunLoopRun + 844
85 CoreFoundation                 0x190ad621c CFRunLoopRunSpecific + 600
86 TestApp                         0x100dbd898 +[RCTCxxBridge runRunLoop] + 266 (RCTCxxBridge.mm:266)
87 Foundation                     0x191ef7a34 __NSThread__start__ + 864
88 libsystem_pthread.dylib        0x1dc60bcb0 _pthread_start + 320
89 libsystem_pthread.dylib        0x1dc614778 thread_start + 8
`

## Steps to Reproduce

Unsure as I can't reproduce this locally, however I have seen it several times in production Crashlytics 

## Version of Realm and Tooling

- Realm JS SDK Version: 10.4.1
- Node or React Native: React-Native

**Device**
Model:iPhone 11 Pro
Orientation: Face Up
RAM free: 738.39 MB
Disk free: 169.66 GB

**Operating System**
Version:14.4.2 (18D70)
Orientation: Portrait
Jailbroken:No

**Crash**
Date:May 16, 2021, 7:44:13 PM
App version:2.8.048 (17996)

**Comment by steffenagger** [comment]
This seems related to https://github.com/realm/realm-js/issues/3112

**Comment by projuljustin** [comment]
Thanks @steffenagger, I'll follow #3112
