### ISSUE TITLE
Unable to resolve module `./mongo-client` from `node_modules\realm\lib\user.js`

### ISSUE THREAD

**Issue by shubhammaurya97** [realm/realm-js#3754]
## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by kraenhansen** [comment]
Hi @shubhammaurya97 👋 Please fill out the template.

**Comment by mklb** [comment]
Had the same issue after upgrading. Just run: `react-native start --reset-cache`
