### ISSUE TITLE
OAuth2 Google login flow broken under Safari 14.1

### ISSUE THREAD

**Issue by markanye** [realm/realm-js#3757]
We've recently deployed an app that authenticates all of its users via realm-js Google login. This was working fine for us on all major browsers, but the login flow seems to be broken on Safari 14.1. (works fine with the previous Safari 14.0.3)

This problem may be related to: https://bugs.webkit.org/show_bug.cgi?id=225344

## Goals

Google login with Safari 14.1.

## Expected Results

1. Realm login call with Google credentials causes app to open secondary tab for Google login.
2. User completes successful login.
3. User redirected to callback and token processed by realm.handleAuthRedirect()
4. Tab closes and login workflow in original tab completes successfully.

## Actual Results

After user completes successful Google login, realm.handleAuthRedirect() is called, but then hangs. Login tab is never closed, and login does not complete in original tab.

## Steps to Reproduce

Attempt realm-web Google login with Safari 14.1.

## Code Sample

none provided

## Version of Realm and Tooling

- Realm JS SDK Version: 1.2.1
- Node or React Native: neither. This is an Angular app
- Client OS & Version: Safari 14.1 on (i believe) any version of Mac OS
- Which debugger for React Native: ?/None

**Comment by kraenhansen** [comment]
Thanks for reporting this. I believe you're right in your assumption that this is related to [Bug 225344](https://bugs.webkit.org/show_bug.cgi?id=225344). We might be able to deploy a workaround using a service worker, but since the issue has been resolved now, I'm tempted to wait for the next release of Safari to verify the fix.

**Comment by markanye** [comment]
@kraenhansen Looks like this update may have hit a few iPads. Nothing yet about desktop Safari ...

**Comment by takameyer** [comment]
@markanye Can you verify that this is still an issue with Safari 14.1.1?  Also it would be good to know if this problem persists in the [Technology Preview](https://developer.apple.com/safari/technology-preview/) of Safari.

**Comment by markanye** [comment]
This is working fine now for the current version of Safari (14.1.2) that I
have on my workstation.

*Mark Nye* • Software Architect & Engineer
http://skylig.ht • 415-562-7588
<http://skylig.ht>

**Comment by takameyer** [comment]
Closing, as this bug has been solved with an update of Safari.
