### ISSUE TITLE
On Android - always returning error for item.toJSON is not a function

### ISSUE THREAD

**Issue by gaurav-vachhani** [realm/realm-js#3760]
We are currently working on the realm react-native app where the things are working fine on iOS devices but on Android devices we are getting a weird message.

## Code Sample
```
  static schema = {
      name: "quotes",
      properties: {
        _id: "objectId",
        _quote: "string?",
        _realm_id: "string?",
        _auther: "string?",
        _date: 'striung?'
      },
      primaryKey: "_id",
  };

userRealm.objects("quotes");
```

## Version of Realm and Tooling

- "realm": "^10.2.0"
- "react-native": "~0.63.4"
- Client OS: macOS

**Comment by kraenhansen** [comment]
Is there a place in your code where you call `toJSON` or perhaps the `JSON.stringify` method?

**Comment by gaurav-vachhani** [comment]
> Is there a place in your code where you call `toJSON` or perhaps the `JSON.stringify` method?

No there's no method written in my code. The issue is throwing from extension.js file of realm lib.

**Comment by takameyer** [comment]
@gaurav-vachhani how are you opening realm? Specifically, how do you define your schema in the configuration?  Are you defining the schema in a class or just using an object?

**Comment by kneth** [comment]
@umarpazir11 It would help us if you answer the same questions as in [this comment](https://github.com/realm/realm-js/issues/3760#issuecomment-889742398)

**Comment by gaurav-vachhani** [comment]
The issue got resolve after changing expo-cli to react-native-cli. Realm doesn't support expo for now.

**Comment by takameyer** [comment]
Once we are finished without Hermes support, you should be able to use Expo.  It is actually possible to use Expo now, but you need to downgrade `react-native-reanimated` to version 1.
I will close this issue as it relates to the JSI engine support, which can be tracked in the PR #3792

**Comment by sejr1996** [comment]
I have the following error
`TypeError: item.toJSON is not a function. (In 'item.toJSON(index.toString(), cache)', 'item.toJSON' is undefined)`

The schemes are as follows:
```
export class MaturationCode {
  public static schema: ObjectSchema = {
    name: 'MaturationCode',
    primaryKey: '_id',
    properties: {
      _id: { type: 'string' },
      code: { type: 'string' },
    },
  };
}


export class Maturation {
  public static schema: ObjectSchema = {
    name: 'Maturation',
    primaryKey: '_id',
    properties: {
      _id: { type: 'string' },
      name: { type: 'string' },
      codes: { type: 'list', objectType: 'MaturationCode', default: [] },
    },
  };
}

```

To read the registers I do the following:
```
public openRealm() {
    return new Realm({
      path: 'larvia.realm',
      schema: ['MaturationCode', 'Maturation'],
      schemaVersion: schemaVersion,
    });
  }

const data = realm.objects('Maturation');
```

The statement realm.objects('Maturation') throws the error.
I'm using:
```
"react-native": "0.66.3",
"realm": "^10.24.0"
```

And I don't use react-native-reanimated.

**Comment by kraenhansen** [comment]
@sejr1996 As a general advice, please consider creating your own issue and feel free to post a link to that on this issue to draw attention to it. This will increase your likelihood of a fast resolution.

**Comment by sejr1996** [comment]
I understand, in case someone has the same problem, the solution was to extend the Realm.Object class.
`export class MaturationCode extends Realm.Object`
`export class Maturation extends Realm.Object`
