### ISSUE TITLE
Could not find source map files.

### ISSUE THREAD

**Issue by HamidShaikh1499** [realm/realm-js#3767]
First of all thank you for this awesome database. That's not a big bug  but it disturbs my Electron application. When i add this

`realm = await Realm.open({
        path: "vehicleRealmDB",
        schema: [vehicleRealm]
    })`

this is important for database location but after running devTools shows warning of COULD NOT FIND SOURCE FILE FOR.. 
there is total 10 map files not found like

**deserializer.js.map
serialze.js.map
event-target-shim.js.map
abort-controller.js.map
float_parser.js.map** 

And I tried to find it in your github realmJs or your official site, And i also update REALM NPM PACKAGE but nothing change shows above warning please add this map files.

Realm and Electron Latest Version

**Comment by kraenhansen** [comment]
Are you using some sort of bundler (like Rollup, Parcel or WebPack)? Would you mind sharing a screenshot and step-by-step instructions on how to reach this state?

**Comment by HamidShaikh1499** [comment]
First Of All Thank you for your reply. i am not using any bundler in this project.
i saw about how to install realm with it's binary files that works in electron environment i followed this site 

[https://medium.com/@sudomax/installing-realm-with-electron-webpack-c113b7976e0b](url) 
[https://stackoverflow.com/questions/51701693/using-realm-from-npm-on-electron-js-app](url).

and also realmJs document i read in your official site.

i installed realmJs, but i followed above site for proper install realm however i run project in devTool console shows 

![image](https://user-images.githubusercontent.com/50068289/120257821-8bc56680-c2ae-11eb-81a8-8768c3fa8c24.png)

as you can see above image it shows not fund **MAP FILES** and insertion, delete, Query | Query Engine | Filtered Also work fine i inserted 80000 document and worked but update not work below code

`realm.write(() => {
                    const updateValue = vehicleDatabase.filtered("vehicleRef == $0",delNum)
                    updateValue.status = status
                })`

**i got updated document but it didn't updated**

package.json
`{
  "name": "smartseizing",
  "productName": "smartseizing",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\"",
    "postinstall": "electron-builder install-app-deps"
  },
  "keywords": [],
  "author": "ADMIN",
  "license": "MIT",
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "smartseizing"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  },
  "dependencies": {
    "docxtemplater": "^3.21.2",
    "electron-squirrel-startup": "^1.0.0",
    "jquery": "^3.6.0",
    "level": "^7.0.0",
    "node-machine-id": "^1.1.12",
    "pizzip": "^3.0.6",
    "realm": "^10.4.1"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.57",
    "@electron-forge/maker-deb": "^6.0.0-beta.57",
    "@electron-forge/maker-rpm": "^6.0.0-beta.57",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.57",
    "@electron-forge/maker-zip": "^6.0.0-beta.57",
    "electron": "13.0.1",
    "electron-builder": "^22.10.5",
    "electron-rebuild": "^2.3.5"
  }
}
`

js filw where i code for database.

`var Realm = require('realm')
var realm
var vehicleDatabase

async function setUp(){
    vehicleRealm = {
        name: "vehicle",
        primaryKey: "_id",
        properties: {
          _id: "string",
          fileName: "string",
          financierPhone: "string",
          financierCompName: "string",
          financierName: "string",
          branchRef: {
            type : "string",
            optional : true
          },
          addressRef: {
            type : "string",
            optional : true
          },
          areaRef: {
            type : "string",
            optional : true
          },
          regionRef: {
            type : "string",
            optional : true
          },
          brmMobileRef: {
            type : "string",
            optional : true
          },
          brmRef: {
            type : "string",
            optional : true
          },
          armMobileRef: {
            type : "string",
            optional : true
          },
          armPrmRef: {
            type : "string",
            optional : true
          },
          bucketRef: {
            type : "string",
            optional : true
          },
          posRef: {
            type : "string",
            optional : true
          },
          emiRef: {
            type : "string",
            optional : true
          },
          customerRef: {
            type : "string",
            optional : true
          },
          agreeNoRef: {
            type : "string",
            optional : true
          },
          makeRef: {
            type : "string",
            optional : true
          },
          engineNoRef: {
            type : "string",
            optional : true
          },
          chassisRef: {
            type : "string",
            optional : true
          },
          vehicleRef: {
            type : "string",
            optional: true
          },
          status: {
            type : "string",
            optional: true
          }
        }
    }

    realm = await Realm.open({
        path: "vehicleRealmDB",
        schema: [vehicleRealm]
    })

    vehicleDatabase = realm.objects('vehicle')
    total_record.innerHTML = vehicleDatabase.length
}
`

And my all code works fine including realm database code also
i hove this information is fine. And thanks...!
