### ISSUE TITLE
Configure Realm function Timeout is not working

### ISSUE THREAD

**Issue by abhishekmongoDB** [realm/realm-js#3768]
### Question: 
* AppConfiguration's timeout is not working.
* Is there any in-build method available in react-native SDK to set the request timeout for the [Realm function](https://docs.mongodb.com/realm/sdk/react-native/examples/call-a-function)?

### Bugs: 
The [AppConfiguration](https://docs.mongodb.com/realm-sdks/js/latest/Realm.App.html#~AppConfiguration) takes an optional timeout parameter which allows you to specify the default timeout (in milliseconds). I have tried setting the timeout value, and it looks like it's not working. 

```
export function getRealmApp() {
  let app;

  if (app === undefined) {
    const appId = '<RealmAppId>'; // Set Realm app ID here.    
    const appConfig = {
      id: appId,
      timeout: 10000,
      app: {
        name: 'default',
        version: '0',
      },
    };
    app = new Realm.App(appConfig);
  }
  console.log('App ==>' + app.id);
  return app;
}
````

## Goals

The function should timeout in the value given in `appConfig.`

## Expected Results

If I set the timeout value to 10 seconds in `app config,` the function should timeout after 10 seconds.

## Actual Results

The function is giving a timeout after 60 seconds even if the value is set to any number. 

## Steps to Reproduce
* In the Realm App, Set timeout to 10 seconds in AppConfig.
* Authenticate the user using any of the authentication methods.
* Call Realm function and add record the time between request and response(Failure case)

## Code Sample
app AppConfiguration
```
export function getRealmApp() {
  let app;

  if (app === undefined) {
    const appId = '<RealmAppId>'; // Set Realm app ID here.    
    const appConfig = {
      id: appId,
      timeout: 10000,
      app: {
        name: 'default',
        version: '0',
      },
    };
    app = new Realm.App(appConfig);
  }
  console.log('App ==>' + app.id);
  return app;
}
```
Function
```

const requestFunctionWithWait = dispatch => async (user) => {
    try {

        console.log('functionA Status ===> ' + JSON.stringify(user));
        const numA = 2;
        const numB = 3;
        console.log('Request Time===> ' + Date());
        const result = await user.functions.functionWithWait(numA, numB);
        console.log('Response Time===> ' + Date());
        Alert.alert(`Using the "functions.sum()" method: the sum of ${numA} + ${numB} = ${result}`)
    } catch (error) {
        console.log('Request Timeout===> ' + Date());
        console.error("Failed functionWithWait with Error", error.message);
    }
}
```

## Version of Realm and Tooling

- Realm JS SDK Version:  10.3.0
- React Native: 0.64.0
- Client OS & Version: iOS SDK v12.4+
- Which debugger for React Native:  None

**Comment by kneth** [comment]
`timeout: 10` will set the timeout to 10 milliseconds. Please try `timeout: 10000` instead.

It is currently only possible to set the timeout in the app configuration.

**Comment by abhishekmongoDB** [comment]
@kneth  I have tried `timeout: 10000` ms as well. It's having same behavior as above

**Comment by kneth** [comment]
The `timeout` parameter doesn't control how long a MongoDB Realm Function can run. It has a fixed upper limit of 90 seconds as [documented](https://docs.mongodb.com/realm/functions/#constraints).
