### ISSUE TITLE
ListView should spread the underlying prop types

### ISSUE THREAD

**Issue by cancan101** [realm/realm-js#377]
```js
  propTypes: {
    ...React.ListView.propTypes,
...
```

**Comment by appden** [comment]
@cancan101 you're right, it would be best to do this, and I will make that change. It should still catch mistakes because it passes all the props down to `React.ListView` inside the `render` method.

**Comment by appden** [comment]
Actually tried this, and it's not worth doing because there are **required** props that the stock `ListView` provides defaults for.

**Comment by cancan101** [comment]
What do you mean?

**Comment by appden** [comment]
For instance, the `renderScrollComponent` prop is required, but a default is provided in `ListView.getDefaultProps()`. It's better us to follow the standard practice of letting the child components do its own prop checking.
