### ISSUE TITLE
'type' must be of type 'String'

### ISSUE THREAD

**Issue by Naoto-Ida** [realm/realm-js#379]
I've `npm install`ed realm,
run `rnpm link realm`,
and imported Realm by
`const Realm = require('realm')`.

Whenever I create a new Realm with schema (exactly as written in the tutorial),
it gives me the error `'type' must be of type 'String'`.

Here is my code:
```
const Realm = require('realm')

export default class SomeComponent extends Component {
    constructor(props) {
        super(props)
        let realm = new Realm({
            schema: [{name: 'Dog', properties: {name: 'string'}}]
        }) 
    }
}
```

Can someone point me in the right direction? Thanks.

**Comment by Naoto-Ida** [comment]
After reading the code in the example project, I specified the schema again as so:

`schema: [{name: 'Dog', properties: {name: 'Realm.Types.STRING}}]`

Is the documentation a little bit old?

**Comment by alazier** [comment]
Both should work - the value of `Realm.Types.STRING` is `"string"`

**Comment by Naoto-Ida** [comment]
It seemed to be the other nested definitions I had in the schema. Closing.
