### ISSUE TITLE
PhaseScriptExecution, missing script files for download-realm in iOS build folder.

### ISSUE THREAD

**Issue by Mudassirraza912** [realm/realm-js#3795]
/Users/username/Library/Developer/Xcode/DerivedData/drb-amuvrvmycyjtiqbyioixomntlgjz/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RealmJS.build/Script-133BA2C435A820095DEA7782067AE912.sh: line 2: /Users/username/Desktop/Remote: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by kneth** [comment]
@Mudassirraza912 We need more context to be able to give a good answer (you deleted the issue template where we ask about the context).

The error message indicates a white space in your path. Unfortunately the download script isn't so robust. However, from v10.3.0, we include the binaries for iOS and Android in the `npm` package and the download script is not used. Please consider to upgrade.
