### ISSUE TITLE
opening lock fifo for writing failed: Too many open files in system

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#3797]
## Goals
Regular use, save operation.

## Actual Results
Save failed with `opening lock fifo for writing failed: Too many open files in system`

## Steps to Reproduce
We have a periodic save step (auto saving every 30 seconds) in the screen that triggered this. The save also can be quite large as it saves a few JSON objects.

Sadly, I don't have any stack traces or additional logs ad the exception was handled in JS code and only the log message was received/logged.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.4.1
- Node or React Native: React Native 0.62.3
- Client OS & Version: iOS 14.6
- Which debugger for React Native: None

**Comment by kneth** [comment]
@cristianoccazinsp Does the save step open a Realm file, writes to it, and close the Realm again? Opening a Realm file should use a cached one but without closing, it could be that you are leaking file descriptors.

For each open Realm file, you will use 3-4 file descriptors. So if you open many different Realm files, you might encounter this issue.

**Comment by cristianoccazinsp** [comment]
No, we only open the realm once at app startup and keep the variable around until the JS environment dies.

On android, we also have a headless task that may open the realm of the global variable is not set, but I believe it is shared between both the headless and regular react components.  Either way, the crash was on iOS which doesn’t have headless execution.

Anything else could be getting all those file descriptors? 

We use bugsnag to do error reporting which I believe opens files too, and the app is used to take hundreds of pictures, but each photo should not leak file descriptors. First time we see this crash also.

**Comment by kneth** [comment]
I believe the number of file descriptors per process/app is low in iOS: https://stackoverflow.com/questions/18666921/maximum-amount-of-open-files-on-ios

You are also using file descriptors for network (socket) communication.
