### ISSUE TITLE
unable to install realm npm package

### ISSUE THREAD

**Issue by shreekanthgaanji** [realm/realm-js#3810]
I am getting the below error when I am running =>npm install realm --save

I have the below software installed
a. Visual studio 2019
b. Installed c++ visual studio build tools
c.  python 2.7.2
d. Windows 10 Enterprise 64bit

Below is the error message 
npm install --save realm
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm ERR! code 1
npm ERR! path C:\oldbackup\ReactNTest\node_modules\realm
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install -r napi || cmake-js rebuild
npm ERR! [
npm ERR! 'C:\\Program Files\\nodejs\\node.exe',
npm ERR! 'C:\\oldbackup\\ReactNTest\\node_modules\\cmake-js\\bin\\cmake-js',
npm ERR! 'rebuild'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- Configuring incomplete, errors occurred!
npm ERR! prebuild-install WARN install unable to get local issuer certificate
npm ERR! info TOOL Using Visual Studio 16 2019 generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN cmake -E remove_directory "C:\oldbackup\ReactNTest\node_modules\realm\build"
npm ERR! info CMD CONFIGURE
npm ERR! info RUN cmake "C:\oldbackup\ReactNTest\node_modules\realm" --no-warn-unused-cli -G"Visual Studio 16 2019" -A"x64" -DCMAKE_JS_VERSION="6.1.0" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="C:\oldbackup\ReactNTest\node_modules\realm\build" -DCMAKE_JS_INC="C:\Users\1016016\.cmake-js\node-x64\v14.15.3\include\node" -DCMAKE_JS_SRC="C:/oldbackup/ReactNTest/node_modules/cmake-js/lib/cpp/win_delay_load_hook.cc" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="14.15.3" -DNODE_ARCH="x64" -DCMAKE_JS_LIB="C:\Users\1016016\.cmake-js\node-x64\v14.15.3\win-x64\node.lib" -DCMAKE_SHARED_LINKER_FLAGS="/DELAYLOAD:NODE.EXE"
npm ERR! CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:129 (message):
npm ERR! Could not find toolchain file:
npm ERR! C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake
npm ERR! Call Stack (most recent call first):
npm ERR! CMakeLists.txt:30 (project)
npm ERR!
npm ERR!
npm ERR! ERR! OMG Process terminated: 1

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\1016016\AppData\Local\npm-cache\_logs\2021-06-18T04_47_06_602Z-debug.log

**Comment by kneth** [comment]
It looks like you haven't the openssl library (and vcpkg) installed. Please take a look at https://github.com/realm/realm-js#additional-steps-for-windows

**Comment by shreekanthgaanji** [comment]
Hi Kneth, Thank you for the response.

I followed all the steps mentioned above but still failing the issue. Below is the log details
npm timing reify:rollback:retireShallow Completed in 408ms
npm timing command:install Completed in 153959ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\1016016\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:375:28)
npm verb stack     at maybeClose (internal/child_process.js:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid realm@10.5.0
npm verb cwd C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\1016016\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "realm@latest" "--force" "--loglevel" "verbose"
npm verb node v14.17.1
npm verb npm  v7.19.0
npm ERR! code 1
npm ERR! path C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\realm
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install -r napi || cmake-js build
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module './tracker.js'
npm ERR! Require stack:
npm ERR! - C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\node_modules\are-we-there-yet\tracker-group.js
npm ERR! - C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\node_modules\are-we-there-yet\index.js
npm ERR! - C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\node_modules\npmlog\log.js
npm ERR! - C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\log.js
npm ERR! - C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\bin.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:92:18)
npm ERR!     at Object.<anonymous> (C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\prebuild-install\node_modules\are-we-there-yet\tracker-group.js:4:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\prebuild-install\\node_modules\\are-we-there-yet\\tracker-group.js',
npm ERR!     'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\prebuild-install\\node_modules\\are-we-there-yet\\index.js',
npm ERR!     'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\prebuild-install\\node_modules\\npmlog\\log.js',
npm ERR!     'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\prebuild-install\\log.js',
npm ERR!     'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\prebuild-install\\bin.js'
npm ERR!   ]
npm ERR! }
npm ERR! internal/modules/cjs/loader.js:329
npm ERR!       throw err;
npm ERR!       ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\ansi\lib\ansi.js'. Please verify that the package.json has a valid "main" entry
npm ERR!     at tryPackage (internal/modules/cjs/loader.js:321:19)
npm ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:92:18)
npm ERR!     at Object.<anonymous> (C:\oldbackup\POS+_Xamarin_Application\mmhf-mobile\node_modules\gauge\progress-bar.js:3:12)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: 'C:\\oldbackup\\POS+_Xamarin_Application\\mmhf-mobile\\node_modules\\ansi\\package.json',
npm ERR!   requestPath: 'ansi'
npm ERR! }
npm verb exit 1
npm timing npm Completed in 154972ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1016016\AppData\Local\npm-cache\_logs\2021-07-08T07_11_34_989Z-debug.log

**Comment by kneth** [comment]
`Error: Cannot find module './tracker.js'` doesn't seem to be related to Realm.
