### ISSUE TITLE
Unable to open realm in debug mode

### ISSUE THREAD

**Issue by TarunBardawa** [realm/realm-js#3817]
## Expected Results

Should run in debug mode

## Actual Results

Error: [json.exception.type_error.302] type must be array, but is number
reactConsoleErrorHandler @ ExceptionsManager.js:179
n @ backend.js:32
registerError @ LogBox.js:148
errorImpl @ LogBox.js:59
console.error @ LogBox.js:33
reportException @ ExceptionsManager.js:104
handleException @ ExceptionsManager.js:171
handleError @ setUpErrorHandling.js:24
reportFatalError @ error-guard.js:49
guardedLoadModule @ require.js:204
metroRequire @ require.js:128
(anonymous) @ index.bundle?platform=ios&dev=true&minify=false:267282
executeApplicationScript @ RNDebuggerWorker.js:2
(anonymous) @ RNDebuggerWorker.js:2

## Code Sample

// Place Your RealmApp ID Here
const app = new Realm.App({ id: "RealmApp_ID_Here", timeout: 10000 });

// can implement inBuilt JWT, Google, Facebook, Apple Authentication Flow.
const credentials = Realm.Credentials.anonymous(); // LoggingIn as Anonymous User. 

getRealm = async (userId) => {
  // loggedIn as anonymous user
  const loggedInUser = await app.logIn(credentials);

  if (loggedInUser) {
    // A user had already logged in - open the Realm synchronously
    return new Realm(getConfig(loggedInUser, userId));
  } else {
    // MongoDB RealmConfiguration
    const configuration = {
      schema: [TournamentSchema, LinkSchema],
      sync: {
        user: loggedInUser,
        partitionValue: userId,
      }
    };

    return Realm.open(configuration); 
  }
}

## Version of Realm and Tooling

- Realm JS SDK Version: ^10.4.2
- Node or React Native: 0.63.4
- Client OS & Version: ?
- Which debugger for React Native: React Native Debugger
![image](https://user-images.githubusercontent.com/22677538/123512105-390b7e80-d6a3-11eb-99b6-1298b06873a3.png)

**Comment by kneth** [comment]
In the code sample I see both `return new Realm(getConfig(loggedInUser, userId));` and `return Realm.open(configuration);`. The two statements have different return types (`Realm` and `Promise<Realm>`). 

Moreover, `const loggedInUser = await app.logIn(credentials);` should give you a logged in user so I don't understand the code sample. I would image that the following code was use:

```
const app = new Realm.App({ id: "RealmApp_ID_Here", timeout: 10000 });
if (!loggedInUser) {
  loggedInUser = await app.logIn(credentials);
}
const configuration = {
  schema: [TournamentSchema, LinkSchema],
  sync: {
    user: loggedInUser,
    partitionValue: userId,
  }
};

return Realm.open(configuration); 
```

**Comment by amplework** [comment]
Same issue for me, when i add this line to the code
`const credentials = Realm.Credentials.anonymous(); // LoggingIn as Anonymous User.`

**Comment by kneth** [comment]
@amplework Can you explain your set up (debugger, not debugger, iOS or Android, etc.)?

**Comment by amplework** [comment]
@kneth i am facing this issue while using debugger, without debugger it is working fine.
i have tried debugging the issue by commenting all the code and one by one uncommenting and found that

const credentials = Realm.Credentials.anonymous();

on this line i get same error which described above

![Screenshot 2021-07-09 at 6 28 11 PM](https://user-images.githubusercontent.com/51485111/125081266-72041400-e0e3-11eb-8306-e4f293a65ed9.png)

**Comment by kneth** [comment]
@amplework Which version of Realm JavaScript? Android or iOS?

**Comment by vizFlux** [comment]
Having the same issue:

```ts
const appId = APP_ID;
const app = new Realm.App({ id: appId });

const credentials = Realm.Credentials.anonymous();

// sample code
async function loginAnonymously() {
  try {
    const user = await app.logIn(credentials);
    console.log('Successfully logged in!', user.id);
    return user;
  } catch (err) {
    console.error('Failed to log in', err.message);
  }
}

async function getRealm() {
  const user = await loginAnonymously();
  console.log(user);
  const config = {
    schema: [MyShcema],
    sync: {
       user: app.currentUser,
       partitionValue: app.currentUser.id,
    },
  };

  return Realm.open(config);
}
```

version: `"realm": "^10.6.0"`
Platform: `iOS`


with this line:
`const credentials = Realm.Credentials.anonymous();`

The app crashes with error as attached:
![IMG_D6D11A163527-1](https://user-images.githubusercontent.com/13939164/126871198-085703f9-9659-429e-a86b-14cf26e6ea43.jpeg)

**Comment by amplework** [comment]
@kneth 
"react-native": 0.63.4,
"realm": "^10.6.0"
using debugger
platform: ios

**Comment by amplework** [comment]
@kneth any update in this?

**Comment by kneth** [comment]
@amplework Just returned from vacation so no updates yet.

I wunder if you change `undefined` to `[]` in https://github.com/realm/realm-js/blob/master/lib/browser/rpc.js#L120 (you can find the file under `node_modules/realm/lib/browser` in your app will help.

**Comment by amplework** [comment]
@kneth finally it worked with above changes. Thanks

**Comment by kneth** [comment]
@amplework Great to hear. If you wish, you are welcome to contribute a PR with the change.

**Comment by takameyer** [comment]
Closing as this issue seems to have been resolved.
