### ISSUE TITLE
[Discussion] Migrate out of Realm

### ISSUE THREAD

**Issue by sintylapse** [realm/realm-js#3819]
Realm doesn't support Hermes, so using Realm in a mobile app is a huge drawback. The related issue is going for 2 years already https://github.com/realm/realm-js/issues/2455, there is no exact answer on when using Hermes will be possible, so people need a backup plan for cases when they can't wait anymore.

Since Realm is a local database, you can't just remove this module from your project, because users will loose their data. You somehow need to be able to use Realm database for migration, without having those parts of Realm which block app from using Hermes.

The best solution I know so far is - use native versions Realm Objective‑C / Realm Java and create a wrapper for calls for migration

If anyone have better thoughts or have experience with that, please share

**Comment by kneth** [comment]
We are currently working on Hermes support (follow https://github.com/realm/realm-js/pull/3792 for progress). I can't give a time estimate as we are hitting a limitation in [Android NDK](https://github.com/android/ndk) related to throwing C++ exceptions in JavaScript callbacks.
