### ISSUE TITLE
No error thrown when getting cached realm with a changed schema

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#382]
We should thrown an exception in this case. Instead we return the cached realm with the schema used for the previous initialization

**Comment by appden** [comment]
If I understand this issue correctly, then I thought we had a test for this? It must easy enough to fix that we should bump up to P1, no?

**Comment by alazier** [comment]
Doesn't need to be bumped - no users have run into this issue. There is no test for this explicitly.

**Comment by alazier** [comment]
Here is the offending code: https://github.com/realm/realm-js/blob/master/src/object-store/src/impl/realm_coordinator.cpp#L91

This doesn't effect the other bindings since schema is inferred rather than passed in by the user.

**Comment by MrHubble** [comment]
> Instead we return the cached realm with the schema used for the previous initialization

Is there anyway to avoid using cached realms? After deleting all of the realm files in my root directory the app is still trying to access `default.realm` which no longer exists.

**Comment by kneth** [comment]
It is possible to listen for schema changes.
