### ISSUE TITLE
Android lib Realm Crashed 

### ISSUE THREAD

**Issue by dipamshujindal1993** [realm/realm-js#3822]
## Crash Logs

Crashed: Thread :  SIGSEGV  0x0000000000000000
#00 pc 0x79b8a22cc8 librealmreact.so 
#01 pc 0x79b8a22cc4 librealmreact.so 
#02 pc 0x79bfeaa8a0  
#03 pc 0x79a0b4f748  
#04 pc 0x79bfeaa8a0  
#05 pc 0x79bfe962c4  
#06 pc 0x79bfde7344  
#07 pc 0x79bfeaa8a0  
#08 pc 0x79a0667e78  
#09 pc 0x79a066945c  
#10 pc 0x79a0751640  
#11 pc 0x79bfeab294  
#12 pc 0x79bfeaa8a0  
#13 pc 0x79bfeaa940  
#14 pc 0x79bfeaa8a0  
#15 pc 0x79a08e0080  
#16 pc 0x79a0acca94  
#17 pc 0x79a08e0080  
#18 pc 0x79a08bf518  
#19 pc 0x79bfeaa8a0  
#20 pc 0x79a08bdb2c  
#21 pc 0x79a0ae7c20  
#22 pc 0x79a0b0476c  
#23 pc 0x79a085c638  
#24 pc 0x79a0ad97e8  
#25 pc 0x79a0ada2bc  
#26 pc 0x79a0ada8fc  
#27 pc 0x79a0669bac  
#28 pc 0x79a0adae2c  
#29 pc 0x79a0605838  
#30 pc 0x79bfe962c4  
#31 pc 0x79bfde7344  
#32 pc 0x79bfde739c  
#33 pc 0x79c542dd04 libjscexecutor.so 
#34 pc 0x79c542db60 libjscexecutor.so 
#35 pc 0x79c5427708 libjscexecutor.so 
#36 pc 0x79c542a83c libjscexecutor.so 
#37 pc 0x79c5529d58 libreactnativejni.so 
#38 pc 0x79c552b350 libreactnativejni.so 
#39 pc 0x79c54f1d48 libreactnativejni.so 
#40 pc 0x79c54e2a70 libreactnativejni.so 
#41 pc 0x79c54e29ec libreactnativejni.so 
#42 pc 0x738eaebc boot-framework.oat 
#43 pc 0x7a331604c4  
#44 pc 0x738ee41c boot-framework.oat 
#45 pc 0x7a4ec1effc libart.so 
#46 pc 0x7a331606b8  
#47 pc 0x7a4e8f4340 libart.so 
#48 pc 0x70cf4e98 boot.oat 
#49 pc 0x7a4e693564 libart.so 
#50 pc 0x7a4e7097e8 libart.so 
#51 pc 0x7a4e5ef5de libart.so 
#52 pc 0x7a4eac5e64 libart.so 
#53 pc 0x7a4eb16154 libart.so 
#54 pc 0x7a4e5ef5de libart.so 
#55 pc 0x7a4e60deff libart.so 
#56 pc 0x7a4e60bf81 libart.so 
#57 pc 0x7d4224f0e8 libc.so 
#58 pc 0x7d4224f0a4 libc.so 
#59 pc 0x7d421eea58 libc.so 
#60 pc 0x7a4eb15c34 libart.so 

## Version of Realm and Tooling

- Realm JS SDK Version: ? 6.1.4
- React Native: ? 0 .63.0
- Client OS & Version: ? Android 11
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
First let me point out that v6.1.x is an old legacy version, and if possible I will suggest that you upgrade. If you need to stay in the v6.1.x series, please consider upgrading to v6.1.7.

Second, we haven't tested v6.1.x with Android 11. Do you see the same crash report on earlier Android versions?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
