### ISSUE TITLE
RJSInitializeInContext EXC_BAD_ACCESS on launch

### ISSUE THREAD

**Issue by mitaxe** [realm/realm-js#3831]
I am trying to use Realm in my RN application, but I get a crash on a splash screen (provided in the 'Actual Results" section).
DB is not even used. I moved initialization to the `initDatabase` method that I am not calling from code. Code snippet is attached at the very end.

## Goals

Realm works on iOS

## Expected Results

Realm works on iOS

## Actual Results

<img width="638" alt="Screenshot 2021-07-06 at 17 09 08" src="https://user-images.githubusercontent.com/17300379/124614425-e25d2c00-de7c-11eb-8ff1-49229975bbc6.png">

## Steps to Reproduce

- yarn install
- cd ios && pod install

## Version of Realm and Tooling

- Realm JS SDK Version: 10.5.0
- Node or React Native: React Native 0.64.1
- Client OS & Version: ? iPhone X, iOS 14.6
- Which debugger for React Native: ? None

```
import Realm from 'realm'
import { Playlist } from './playlist'

class Database {
  realm: Realm
  playlist: Playlist

  public initDatabase() {
    try {
      this.realm = new Realm({
        schema: [Playlist],
        inMemory: true,
        schemaVersion: 1.0,
      })

      console.log('path', this.realm.path)
      this.playlist = new Playlist()
    } catch (err) {
      const { message } = err as Error
      console.error('Failed to open the realm', message)
    }
  }

  //TODO: Specify data type. It will exist in playlist store.
  public addPlaylist(data: any): void {
    this.playlist.addPlaylist(this.realm, data)
  }

  public getPlaylists(): Realm.Results<Realm.Object> {
    return this.playlist.getPlaylists(this.realm)
  }

  // public getPlaylistExercises(playlistId: number) {
  //   return this.playlist.getExercises(playlistId)
  // }

  public closeConnection() {
    this.realm.close()
  }
}

export default new Database()

```

<img width="453" alt="Screenshot 2021-07-06 at 17 16 13" src="https://user-images.githubusercontent.com/17300379/124615370-dfaf0680-de7d-11eb-8a8c-cd7d005b049b.png">

**Comment by mitaxe** [comment]
it happens because we are using Hermes in iOS. I think it should be mentioned somewhere in the readme that realm doesn't support hermes.

**Comment by kneth** [comment]
We are working on Hermes - see https://github.com/realm/realm-js/pull/3792 - but in the meantime it might be a good idea to issue a warning in `README.md`.
