### ISSUE TITLE
dyld: Library not loaded: @rpath/RealmJS.framework/RealmJS

### ISSUE THREAD

**Issue by charlesluo2014** [realm/realm-js#385]
dyld: Library not loaded: @rpath/RealmJS.framework/RealmJS
  Referenced from: /var/containers/Bundle/Application/

  Reason: image not found

**Comment by alazier** [comment]
We have switched over from using a dynamic framework to using a static library. If you re-add realm using the latest instructions it should resolve your issue: https://realm.io/docs/react-native/latest/#installation

**Comment by alazier** [comment]
Any luck following the release notes?
