### ISSUE TITLE
Adding realm with "yarn add realm" causes react native app to crash without error message

### ISSUE THREAD

**Issue by MSrotyr** [realm/realm-js#3858]
## Goals
To use realm in our project
Adding realm with "yarn add realm" causes react native app to crash without error message
[yarn_add_realm.txt](https://github.com/realm/realm-js/files/6830992/yarn_add_realm.txt)
[react_native_start.txt](https://github.com/realm/realm-js/files/6830993/react_native_start.txt)
[react_native_run_android.txt](https://github.com/realm/realm-js/files/6830994/react_native_run_android.txt)

## Expected Results
Expected app to run

## Actual Results
App crashes without error

## Version of Realm and Tooling

- Realm JS SDK Version: Default version
- Node or React Native: React Native
- Client OS & Version: Windows 10
- Which debugger for React Native: ?/None

**Comment by takameyer** [comment]
@MSrotyr Thanks for reporting.  I will try to see if I can reproduce this.  In the meantime, can you tell me what version of `realm` and `react-native` are installed in your app?  Also if you can provide an example of how you are implementing `realm`, that would be most helpful.

**Comment by MSrotyr** [comment]
Realm Version: 10.6.0
react-native: "0.63.4"

Have not implemented realm at all. I've only added it as a dependency.

Node: 16.4.2

npm: 7.18.1

**Comment by oguzhan10** [comment]
my also crashing

"realm": "^10.6.0",
"react-native": "0.63.4",

**Comment by MSrotyr** [comment]
Okay, found out from here https://github.com/realm/realm-js/issues/3713 that realm is incompatible with hermes. So this could explain it.

**Comment by takameyer** [comment]
@MSrotyr thanks for reporting.  Please track #2455 for Hermes support.
