### ISSUE TITLE
Query backlink on two fields with same type

### ISSUE THREAD

**Issue by xuantubka** [realm/realm-js#3865]
## Goals
I have a relationship between Product and its units describe in schema as below:
```js
public static schema: Realm.ObjectSchema = {
    name: Product.schemaName,
    primaryKey: 'sku',
    properties: {
      name: {type: 'string'},
      baseUnit: {type: SoldableUnit.schemaName},
      derivedUnits: {type: 'list', objectType: SoldableUnit.schemaName},
     
    },
  };
public static schema: Realm.ObjectSchema = {
    name: SoldableUnit.schemaName,
    embedded: true,
    properties: {
      unitName: {type: 'string'},
      sellingPrice: {type: 'double'},
      weight: {type: 'float'},
      barcode: {type: 'string', optional: true, indexed:true},
    },
  };
```
The idea is a `product` can have one `baseUnit` and many `derivedUnits`, and both `baseUnit` and `derivedUnit`s are `SoldableUnit` with the same schema. I want to query `product` by `barcode`. Here I have to return the product, providing a barcode which maybe equals to barcode of baseUnit or derived units. After some research, I find out that I can use backlink to return inverse relationship. The problem here is SoldableUnit occurs both in baseUnit and derivedUnits and I dont know how to achieve this goals? And whether the schema design of Product is appropriate?

## Version of Realm and Tooling

- Realm JS SDK Version: ?
- Node or React Native: ?
- Client OS & Version: ?
- Which debugger for React Native: ?/None

**Comment by ironage** [comment]
Hi @xuantubka, if you are doing a query on the Product I think you can follow the forward links like this:
`realm.objects('Product').filtered('baseUnit.barcode == $0 || derivedUnits.barcode == $0', barcode)`
But it is possible that I haven't understood what you are trying to do, and if this isn't what you're looking for, please elaborate on your requirements.
You would only have to do a backlink query if you wanted to filter on the SoldableUnit. For more information about that type of query, you can read the bottom section "Backlink Queries" at this page: https://docs.mongodb.com/realm-legacy/docs/javascript/latest/api/tutorial-query-language.html

**Comment by xuantubka** [comment]
Thanks @ironage  for your quick response. Sorry for not writing elaborately. Here derivedUnits is list, and relationship between product and derivedUnits is one to many. That's why I have to use backlink here.

**Comment by ironage** [comment]
Ok, I understand the relationships from the schema, but I don't understand what kind of query you are trying to write. Is the query that I offered above not what you want? Does that mean that you want to query on the `SoldableUnit` instead?

**Comment by xuantubka** [comment]
No, I just want to retrieve `Product`. But `derivedUnits` is a list. Is it possible to check all list item just by using `derivedUnits.barcode`?

**Comment by ironage** [comment]
`derivedUnits.barcode == $0` will check all items in the list and produce a match if *any* of the items matches the barcode, it is the same as writing `ANY derivedUnits.barcode == $0`. If you really need to check *all* of them like you say, then you can use `derivedUnits.@size > 0 && ALL derivedUnits.barcode == $0`. Does that work for you?

**Comment by xuantubka** [comment]
Wow, it's really an amazing what you're doing. Thanks for your clarifying. It works already.
