### ISSUE TITLE
Guidelines for updating Realm version

### ISSUE THREAD

**Issue by teebolt** [realm/realm-js#387]
After looking through all of the documentation, I wasn't able to find a way to update Realm versions. Currently using Realm.js for React Native v0.10 but noticed v0.11 is available.

Would be good to have some clarity on how to upgrade and any gotchas that could be encountered.

**Comment by alazier** [comment]
Instructions were in the release notes - we should probably add a note in the docs until more people have upgraded. The release notes are here https://github.com/realm/realm-js/releases/tag/v0.11.0
