### ISSUE TITLE
React native restore a backup

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [realm/realm-js#3873]
I have download a  copy of my realm database `database.realm` . I have copied that file to downloads and then I have to delete the app. after some days I reinstalled that app I want to restore the backup file.  `database.realm`  any solution for this,

**Comment by fronck** [comment]
@aftabaminzoobiapps For clarification:  are you the developer of this app, or a user of the app?

**Comment by AftabUfaq** [comment]
> @aftabaminzoobiapps For clarification: are you the developer of this app or a user of the app?

I am the developer of the app. but I want when a user clicks the backup button so my realm database would be backed up. similarity if a user has the .realm file. and he wants to restore the previous data. for example, a user used the app. then he delete that app and after some time he reinstalls that app. now he wants to restore his previous data. as we can do this whatsapp

**Comment by fronck** [comment]
Okay, thanks for clarifying.
I assume you're working with React Native.  If so, have a look at the [`copyBundledRealmFiles`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#.copyBundledRealmFiles) functionality.  It an implementation of functionality like what you seem to be after.

Be aware that restoring a backed up realm may incur some cost in the form of network traffic if modifications have happened on the server side between backup and restore.
