### ISSUE TITLE
Alert Gradle Deprecated after installation Realm 

### ISSUE THREAD

**Issue by bnobre** [realm/realm-js#3879]
## Goals

After installing Realm, I wish that when I run the command "react-native run-android" it does not display the following warning: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings."

## Expected Results

I would like this alert to disappear "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.", which only appears after installing Realm.

## Actual Results

Always after installing Realm, when executing the command "react-native run-android" the alert is displayed.

## Steps to Reproduce

1 - Create a new react native project: react-native init testApp
2 - Install Realm: yarn add realm
3 - Run the app: react-native run-android

## Version of Realm and Tooling

- Realm JS SDK Version: 10.6.1
- Node: 15.10.0 x64
- React Native: 0.64.2
- Client OS & Version: Windows 10 Home Single Language x64
- Which debugger for React Native: None

**Comment by takameyer** [comment]
@bnobre Thanks for reporting.  We will look into it as soon as we can.

**Comment by takameyer** [comment]
It's possible the problem lies in how analytics.gradle is defined.  Perhaps adhering to the class structure in the documentation would make the issue go away.  I attempted this, but `@Inject` was not defined.
https://docs.gradle.org/6.7/userguide/more_about_tasks.html#sec:passing_arguments_to_a_task_constructor
