### ISSUE TITLE
Safari Debugging: Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#3880]
When using Safari to debug a React Native application using Realm, the debugger is unable to read any properties of a realm object.  The debugger is showing an error which has been thrown from Object Store, indicating that the object is being accessed from the incorrect thread. 

![image](https://user-images.githubusercontent.com/164606/127977732-ba927d7d-b9cf-4a2f-8832-b90e2db3f237.png)

## Goals

The Safari debugging experience should be helpful in determining what values are set in a Realm object.  It would be worthwhile to investigate if there is a way this can be achieved.

## Expected Results

It is reasonable to expect that setting a breakpoint in javascript and viewing a Realm object should show it's contents.

## Actual Results

The properties of a Realm object are throwing an exception "Error: Realm accessed from incorrect thread."

## Possible Solution

Frozen objects are able to be read from other threads.  An implementation of frozen objects underneath the application layer may make this problem go away.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.6.2
- Node or React Native: React Native
- Client OS & Version: MacOS 11.4
- Which debugger for React Native: Safari

**Comment by kneth** [comment]
We recommend switching to [Hermes](https://github.com/realm/realm-js/issues/3940) and use [Flipper](https://fbflipper.com/) as debugger.
