### ISSUE TITLE
Delete an object in realm cause react native app crash

### ISSUE THREAD

**Issue by helloworld123456** [realm/realm-js#389]
DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8082/get_property'.
    at Error (native)
    at sendRequest (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81928:9)
    at Object.getProperty (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81848:1504)
    at Object.ORD_NO (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81746:961)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:80873:27
    at Object.changeOrderState (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:80874:19)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:73377:3977
    at task$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:73377:1670)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:10263:30)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:10539:12)

**Comment by alazier** [comment]
Looks like you are running in chrome debug mode. Do you get the same crash when running in regular mode? Are you deleting the object from within a write transaction?

**Comment by helloworld123456** [comment]
@alazier 
:-), thank your reply, I found the crash occurred when I access a deleted object's properties, code something like this:

realm.write(()=>{
    realm.create('PREFS',{KEY:'key1',VALUE:'value1'})
})

let result = realm.objects('PREFS').find(row=>{
    return row.KEY=='key1'
})

realm.write(()=>{
    realm.delete(result)
})

console.log(result.KEY)  //whenever run in debug or normal mode, this line always make app crash.

If I keep a reference to a realm object, how do I know it is deleted before access its property?

**Comment by helloworld123456** [comment]
@alazier 
I end up added a _DELETE property to all my schemas, when an object need to be deleted, set _DELETE to true, and before user exit app, find all objects marked _DELETE with true and delete these objects all together.

Then define a _objects(type) as follow to replace original objects() function:
realm._objects = function (type) {
    return realm.objects(type).filtered('_DELETE=false')
}

Could you tell me what's the drawbacks of this approch?

**Comment by alazier** [comment]
That approach is fine as a workaround. If you have a very large dataset the query could potentially slow things down but in most cases it should be fine. 

This is really a problem with Realm though that there is no way to check if an object has been deleted. This is something that is supported on other bindings and we need to support for RN as well. I created a new item #391 to track the issue.

**Comment by helloworld123456** [comment]
@alazier 
Tanks for your feedback. Have a nice day.

**Comment by L3V147H4N** [comment]
I get the same error when (for example) deleting an Object and then returning to a view (go back) that was rendering the collection... I use the .isValid() in the render method but error is thrown anyway
