### ISSUE TITLE
iOS production crash - realm::DB::get_number_of_versions()

### ISSUE THREAD

**Issue by infaprakash** [realm/realm-js#3902]
Steps for others to Reproduce
Not sure how to reproduce. This is happening in production app and is detected in Crashlytics logs.

From Crashlytics:
realm::DB::get_number_of_versions()
Crashed: com.facebook.react.JavaScript
0  app_name                            0x101151344 realm::DB::get_number_of_versions() + 632572
1  app_name                           0x100c46d00 check_can_create_write_transaction(realm::Realm const*) + 494 (shared_realm.cpp:494)
2  app_name                            0x100c46a30 realm::Realm::begin_transaction() + 599 (shared_realm.cpp:599)
3  app_name                            0x100c006a0 realm::js::RealmClass<realm::jsc::Types>::write(OpaqueJSContext const*, OpaqueJSValue*, realm::js::Arguments<realm::jsc::Types>&, realm::js::ReturnValue<realm::jsc::Types>&) + 28 (jsc_function.hpp:28)
4  app_name                            0x100bfa950 OpaqueJSValue const* realm::js::wrap<&(realm::js::RealmClass<realm::jsc::Types>::write(OpaqueJSContext const*, OpaqueJSValue*, realm::js::Arguments<realm::jsc::Types>&, realm::js::ReturnValue<realm::jsc::Types>&))>(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) + 77 (jsc_return_value.hpp:77)
5  JavaScriptCore                 0x199991d3c long long JSC::APICallbackFunction::call<JSC::JSCallbackFunction>(JSC::JSGlobalObject*, JSC::CallFrame*) + 412

react native version - 0.63.3
realm version - 10.1.0
xcode version  - 12.3
pod version - 1.10.1

based on crashlytics -
majority of the crashes seen in iOS 14 (97% of the total crashes)
98% of this crash occurs in the background

complete crash log attached - 
[get_number_of_versions() complete crash log.txt](https://github.com/realm/realm-js/files/6973257/get_number_of_versions.complete.crash.log.txt)

**Comment by fronck** [comment]
@infaprakash Thanks for reporting this.  We will look into it.  

Do you know how often this crash occurs compared to the number of running apps?
Would you be able to upgrade to the latest version of Realm-JS?
If you find any way to reproduce it in a development environment, please let us know.

**Comment by infaprakash** [comment]
Hi @fronck ,
The crash count for the past week has been 197 cashes affecting 192 iOS users out of 178k users
And yes, our current plan is to upgrade realm to 10.6.1
Unfortunately, we haven't had this crash reported in development environment, only seen in production

**Comment by takameyer** [comment]
@infaprakash Have you been able to reproduce this in a development environment?  As soon as you can and share the steps, we can investigate.  Unfortunately this is too vague for us to move forward without knowing how to cause the issue.

**Comment by elizabethpradeep** [comment]
Hi @takameyer , we have a similar issue in production, crash count is currently at 84 crashes per week, can you please provide an update on this? current realm version used in our application is 10.7.0

**Comment by nirinchev** [comment]
Closing this as it's >2 years old and we haven't got any repro steps.
