### ISSUE TITLE
Install realm ,and  Android archive filed:OutOfMemoryError

### ISSUE THREAD

**Issue by jeffy7** [realm/realm-js#3909]
## Goals
Archive success

## Actual Results
when I remove  ,I can archive success ,add realm   iOS can archive success ,android failed 

`> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)`
## Version of Realm and Tooling

- Realm JS SDK Version: ?"realm": "^10.6.1"
- Node or React Native: ?React Native
- Client OS & Version: ?Android 
- Which debugger for React Native: ?/None

**Comment by kneth** [comment]
It is Gradle which produces the error message. To understand the issue, can you tell us:

* The Gradle version
* Your operating system
* The amount of memory

**Comment by hamzaabujarad** [comment]
in android/gradle.properties put 
`org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m`
 and increment your memory as much as your project need
