### ISSUE TITLE
Cannot close schemas?

### ISSUE THREAD

**Issue by lincdh** [realm/realm-js#3911]
## Goals

To open different schema after closing current schema

## Expected Results

Close the current schema and open new schema

## Actual Results

![image](https://user-images.githubusercontent.com/21136244/129673223-9cabf65f-bae1-411c-9c78-9eddac1d5ff9.png)
![image](https://user-images.githubusercontent.com/21136244/129679029-e29836e9-83d7-4b90-94c1-8fb62e9a0b85.png)

## Steps to Reproduce
```

componentDidMount() {
  const realm = await Realm.open({
      schema: [firstSchema],
    });
  
  let allData = realm.objects(firstSchema.name);
  
  realm.close();
}

componentDidUpdate() {
  const realm2 = await Realm.open({
      schema: [secondSchema],
    });
  
  allData = realm2.objects(secondSchema.name);
  
  realm2.close();
}

```

## Version of Realm and Tooling

Realm JS SDK Version: 10.6.1
React Native: 0.64.2
Node: 14.16.1
Client OS & Version: Windows 10 10.0.19042
Which debugger for React Native: ?/None

**Comment by kneth** [comment]
The schema is bound to the Realm file, but you can open multiple Realm files, each having a different schema. The `path` configuration option specifies the file name - if omitted, `default.realm` is used.

In you change, I suggest that you change the second Realm to:

```js
const realm2 = await Realm.open({
  path: "second.realm",
  schema: [secondSchema]
});
```
