### ISSUE TITLE
my ReactNative app is getting crashed due to realm.delete!!!

### ISSUE THREAD

**Issue by abhilashiic** [realm/realm-js#3936]
### How frequently does the bug occur?

All the time

### Description

```
realm.write(() => {
        let stock_rcd = realm.objects("stock").filtered("id = '" + id + "'");
        realm.delete(stock_rcd)
});
```

### Stacktrace & log output

```shell
app crashed
```

### Can you reproduce the bug?

Yes, always

### Version

10.2.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

NA

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
@abhilashiic what happens when you surround the callback function body with a try catch?

```
realm.write(() => {
    try {
        let stock_rcd = realm.objects("stock").filtered("id = '" + id + "'");
        realm.delete(stock_rcd);
    } catch (err) {
        console.errror(err);
    }
});
```

**Comment by abhilashiic** [comment]
### Got a clue. The issue appears when I add a listener for deletion.
```
realm.objects('stock').addListener((stocks, changes) => {
    changes.deletions.map(idx => {
        let obj = stocks[idx]
        if (obj.type === "damage") {
            realm.write(() => {
                const product = realm.objects("product").filtered('id = $0', obj.product_id)[0]
                product.stock = (product.stock + parseInt(obj.quantity))
            });
        }
    })
}); 
```

**Comment by abhilashiic** [comment]
@kraenhansen Tried Try & Catch expression. But no error was logged. Same, app chashed. 
Thanks for the suggestion.

**Comment by kraenhansen** [comment]
> The issue appears when I add a listener for deletion.

Interesting ... what happens when you surround your listener block with a `try-catch`?

```javascript
realm.objects('stock').addListener((stocks, changes) => {
    try {
        changes.deletions.map(idx => {
            let obj = stocks[idx]
            if (obj.type === "damage") {
                realm.write(() => {
                    const product = realm.objects("product").filtered('id = $0', obj.product_id)[0]
                    product.stock = (product.stock + parseInt(obj.quantity))
                });
            }
        })
    } catch (err) {
        console.error(err);
    }
}); 
```

**Comment by abhilash-aiolos** [comment]
> That code looks just wrong to me. You're mapping the deletions to the current collection, which doesn't seem like it will ever work. E.g. if you had one element in your `stocks` table and it got deleted. You'd get a notification where `changes.deletions` would be `[0]`. At this point the collection has been updated, meaning that it has zero elements, so `stocks[0]` would be undefined, then `obj.type` would throw an error as you're trying to access a property on an undefined object.
> 
> At this point, Realm does not offer the ability to access deleted objects, so you'll probably have to rework the design of your code to get it to do what you need.

Thanks!!
