### ISSUE TITLE
Using Realm in Navigator scenes in some circumstances can crash the app

### ISSUE THREAD

**Issue by dantman** [realm/realm-js#394]
The combination of Realm + Navigator + Re-rendering scenes that use Realm objects + deletion can cause Realm to crash the app.

I've written up a sample app for this scenario:
https://github.com/dantman/realm-bug-test-1/tree/master/lib

"Next" creates a Realm object and navigates to a scene that uses the Realm object and also periodically re-renders (like a scene that includes a timer/countdown, etc... would); The "Delete" button then navigates back to the top and deletes the object. Most of the time this should result in the app crashing.

* This seems to be because Navigator keeps the scene around for awhile to do its animation and during that time the deleted Realm object is accessed by the not yet unmounted scene.
* This won't necessarily only happen when you're using timers. It's possible a re-render of the component could be triggered during navigation for various other reasons. These are just harder to demonstrate; potentially causing infuriatingly hard to debug "The app just crashed" reports in production.
* I actually simplified this a bit. In practice I'm working on an app where an "Activity" referencing a Realm object is started; when 'done' they go to a scene to write a note about the activity; then when the note is created the app navigates back to the top and deletes the activity. So in practice the scene in the stack that accesses the Realm object and the scene that deletes it may be different; so the reference to the object cannot be removed prior to deletion.

**Comment by alazier** [comment]
Thanks for the detailed bug report and example project. I was able to easily reproduce the issue. In the near term the way we will address this is to add an api to allow you to check if an object has been deleted. There was an existing issue/request for this and I have added this functionality in a pr #395 which should make it into the next release.

With this new api in cases you are accessing objects which may later be deleted you will need to check if the object is deleted before each access. In your example app I had to change the crashing code in `Second.js` to:
```js
<Text style={styles.title}>
    Object: {realm.isValid(this.obj) ? this.obj.id : 'invalid'}
</Text>
```

If you can think of other/better ways we can address this type of issue please let us know.

**Comment by dantman** [comment]
Checking for validity all the time is going to make code a lot messier and make the pop process messy. Not every situation will be able to provide an alternative for when there is no object. And instead of scenes displaying their previous content as they fade out, they'll either be blank or display weird placeholders.

IMHO this is an inherent fault to Realm's default behaviour of live-updating objects, but this issue could probably be worked around by allowing shallow and deep snapshots of an object to be created.

Then the `this.obj` could be a snapshot that won't suddenly become non-existent in the middle of a scene's existence.

**Comment by alazier** [comment]
Deep snapshots/immutability is something we definitely want to do but there are performance considerations which give me low confidence that it is something we can provide in the shorter term. Until then it will be necessary to perform this check for objects that could be deleted, or to copy/clone the data to prevent any live updating from occurring.
