### ISSUE TITLE
android build error.

### ISSUE THREAD

**Issue by liuqing520it** [realm/realm-js#3946]
### How frequently does the bug occur?

All the time

### Description

android build error 

### Stacktrace & log output

```shell
* Exception is:
org.gradle.internal.execution.WorkValidationException: Some problems were found with the configuration of task ':realm:send' (type 'SendAnalyticsTask').
  - Type 'SendAnalyticsTask' property 'applicationId' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
```

### Can you reproduce the bug?

Yes, always

### Version

10.7.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

max os 11.5.2

### Build environment

Which debugger for React Native: ..
"react": "17.0.2",
"react-native": "0.65.1",

com.android.tools.build:gradle:7.0.1

**Comment by takameyer** [comment]
@liuqing520it thanks for reporting.  This seems to be an issue with newer versions of Gradle.  We will try and take care of it as soon as we can.  More information can be seen in #3879

**Comment by takameyer** [comment]
@liuqing520it In the meantime, is it possible for you to use Gradle 6.9?

**Comment by liuqing520it** [comment]
> @liuqing520it In the meantime, is it possible for you to use Gradle 6.9?

![image](https://user-images.githubusercontent.com/16216435/133205219-ca704753-d38d-4128-803a-23b465625174.png)

**Comment by takameyer** [comment]
@liuqing520it We haven't fixed the problem with Gradle 7 yet.  A workaround would be to downgrade to Gradle 6.9.

**Comment by alejandrorangel** [comment]
Hi @takameyer I'm havving the same issue right now do you guys have a ETA for the fix?

**Comment by takameyer** [comment]
@alejandrorangel It's a priority and hopefully will be fixed soon.  I can't provide a concrete ETA.

**Comment by takameyer** [comment]
The fix will come in the next release.

**Comment by takameyer** [comment]
@roxlu @Strapazzon @liuqing520it realm 10.9.0 is now Gradle 7 compatible

**Comment by Strapazzon** [comment]
> @roxlu @Strapazzon @liuqing520it realm 10.9.0 is now Gradle 7 compatible

Thank you. Great Job!

**Comment by Sachin926** [comment]
Hi @takameyer I'm still facing the same issue in realm 6.0.2 and I do not want to upgrade to the latest, is it possible that if I create a PR for the same now then it would be merged in the next patch release of version 6?

**Comment by takameyer** [comment]
@Sachin926 you are welcome to fork and create a fix yourself.  I will discuss with my team after the holidays whether we are continuing to make patches for v6.  At the moment we are fully committed to the latest version of Realm.  What is keeping you from updating?

**Comment by Sachin926** [comment]
Thanks, @takameyer for the quick response, the possible breaking changes are what's keeping me from upgrading, although I have planned to do so in the near future as soon as I have some bandwidth.

**Comment by ianpward** [comment]
We do not plan to backport anything to v6 - sorry about that but its quite old.

**Comment by Sachin926** [comment]
Hi @ianpward thanks for the reply, I can create a PR for the same because as far as the version history goes for realm-js, there is a bump from v6 to v10 so if possible is there any room for a patch at v6?

**Comment by takameyer** [comment]
@Sachin926 By now, version 6 is so outdated that it would take a lot of effort on our part to release a patch.  Our entire release process has migrated since then, and we aren't willing to back port those changes into this older code base.  If you really can't upgrade then I recommend using something like [patch-package](https://www.npmjs.com/package/patch-package) to get by.  In any case, I highly recommend upgrading to v11.

**Comment by ThalKod** [comment]
@Sachin926 Were you able to find a fix whitout upgradingg your realm version ?

**Comment by Sachin926** [comment]
@ThalKod Yes you need to make these two variables public in analytics.gradle in the realm android dir

```
String applicationId = 'UNKNOWN'
String version = 'UNKNOWN'
```
you can either make script for the same or use [patch-package](https://www.npmjs.com/package/patch-package)
