### ISSUE TITLE
realm.create(name, ...params) name is string error?

### ISSUE THREAD

**Issue by labike** [realm/realm-js#3948]
### How frequently does the bug occur?

All the time

### Description

<img width="668" alt="截屏2021-09-08 上午10 11 27" src="https://user-images.githubusercontent.com/15871933/132453554-a97eacba-bd46-4cf6-b26e-2c03f9d1605f.png">

the error tips: `new (...arg: any[]) => Object` params type can't string

### Can you reproduce the bug?

Not yet

### Version

10.7.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macos big sur 11.0.1

### Build environment

"react": "17.0.1",
"react-native": "0.64.1",

**Comment by takameyer** [comment]
Hello @labike, thanks for submitting this issue.  Can you provide the `Program` schema and give me some details into what is in the `data` object being passed to `realm.create`?

**Comment by labike** [comment]
@takameyer
```
import Realm from 'realm';

export interface IProgram {
  id: string;
  title: string;
  thumbnailUrl: string;
  currentTime: number;
  duration: number;
  rate: number;
}

class Program {
  static schema = {
    name: 'Program',
    primaryKey: 'id',
    properties: {
      id: 'string',
      title: 'string',
      thumbnailUrl: 'string',
      currentTime: {
        type: 'double',
        default: 0,
      },
      duration: {
        type: 'double',
        default: 0,
      },
      rate: {
        type: 'double',
        default: 0,
      },
    },
  };
}

const realm = new Realm({
  schema: [Program],
  schemaVersion: 1,
  migration: (oldRealm, newRealm) => {
    if (oldRealm.schemaVersion < 1) {
      const oldObjects = oldRealm.objects<IProgram>('Program');
      const newObjects = newRealm.objects<IProgram>('Program');
      for (let i = 0; i < oldObjects.length; i++) {
        newObjects[i].rate =
          Math.floor(
            ((oldObjects[i].currentTime * 100) / oldObjects[i].duration) * 100,
          ) / 100;
      }
    }
  },
});

export function saveProgram(data: Partial<IProgram>) {
  try {
    realm.write(() => {
      realm.create('Program', data, true);
    });
  } catch (error) {
    return error;
  }
}
```

**Comment by takameyer** [comment]
@labike The third argument to `realm.create` is not a boolean, but an enum of Realm.UpdateMode.  If you set this argument to one of the enum values, the error will go away.

**Comment by labike** [comment]
@takameyer thanks!!!
