### ISSUE TITLE
Memory Leak problem in React Native

### ISSUE THREAD

**Issue by saeho** [realm/realm-js#397]
Hi, we want to use Realm in our React Native project. But there's a memory leak issue in Realm.

Using the latest version 0.11.1,eEvery time the app refreshes, the memory usage goes up by ~40 MB and it does not go back down. By refreshing multiple times, the memory usage can go up as high as 300 MB before the app closes itself.

Also letting the app idle will cause the app to slowly climb in memory usage without ever going down.

**Comment by appden** [comment]
Thanks so much for reporting this @saeho. I figured out that we were leaking JS executors on iOS when refreshing. I have a PR open that will fix this, and it will be in the next release.

**Comment by aljs** [comment]
>  I have a PR open that will fix this, and it will be in the next release.
Any news when the next release will be available?

**Comment by alazier** [comment]
Early this week.

**Comment by appden** [comment]
@aljs We just released `0.12.0-rc`. Would you mind updating to that and letting us know that this issue was resolved for you?

**Comment by tolbrino** [comment]
I've hit the same issue before and with this release the memory stays stable across reloads for me.

**Comment by appden** [comment]
@tolbrino That's great to hear, thanks so much for confirming that!
