### ISSUE TITLE
Remove our ListView component

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3977]
It's been a 2½ years since the `ListView` component got deprecated and moved to the `deprecated-react-native-listview` package.

As [the README on the repository states](https://github.com/facebookarchive/react-native-deprecated-modules/blob/master/README.md):

> You shouldn't use any of these modules in your applications - there is a good replacement for each one.

There's no need for us to keep this around. We should instead invest in the upcoming releases of our efforts to integrate better with React.

I suggest removing these files:
- [react-native/index.js](https://github.com/realm/realm-js/blob/master/react-native/index.js)
- [react-native/listview.js](https://github.com/realm/realm-js/blob/master/react-native/listview.js)
- [react-native/package.json](https://github.com/realm/realm-js/blob/master/react-native/package.json)

**Comment by Acetyld** [comment]
I agree!

**Comment by misterlib** [comment]
I rean into an issue today on 10.10.0 where my application would not build due to version 0.0.6 of deprecated-react-native-listview. I updated that in the package-lock to 0.0.7 so that it would build, but either that needs to get updated or removed.

**Comment by kneth** [comment]
@misterlib Thank you for reporting. We consider removing it a breaking change, so we will start by upgrading deprecated-react-native-listview.

For people interested in our progress on providing React Native integration, I will recommend you to have a look at https://github.com/realm/realm-js/tree/master/packages/realm-react

**Comment by misterlib** [comment]
@kneth thank you! I'm simutaneously excited and infuriated 🤣. I am finishing up a six month rewrite on 5 RN apps to move them from cloud to mongodb (3 -> 10). SOOOO much boiler plate. Maybe next year. I'll move to React Realm, but so glad to know that it's there!

**Comment by kneth** [comment]
@misterlib We have many plans for React Realm - including sync stuff :smile:

**Comment by kraenhansen** [comment]
Removing the breaking label, since this component was never a part of our publicly documented API.

**Comment by kneth** [comment]
@misterlib We have decided to remove the code which requires `deprecated-react-native-listview` - much simpler solution :-)
