### ISSUE TITLE
Crash on android 64 bit devices 

### ISSUE THREAD

**Issue by melihmucuk** [realm/realm-js#398]
Check this [issue](https://github.com/facebook/react-native/issues/7087)

**Comment by appden** [comment]
Thanks for reporting this @melihmucuk. Can you please confirm that you're running the latest version (`0.11.1`)?

**Comment by melihmucuk** [comment]
Hi, I was on 0.10.0, then upgrade to 0.11.1 and issue  solved. Thanks !

**Comment by appden** [comment]
Thanks for the update @melihmucuk, that's really good to hear!
