### ISSUE TITLE
Graphql throwing invalid session

### ISSUE THREAD

**Issue by abhishekmatta999** [realm/realm-js#3983]
### How frequently does the bug occur?

Sometimes

### Description

I’m using realm-graphql in my electron app. Now I’m facing an error while I’m passing authentication token in the header of graphql request.
This is the error:

`Error: Network error: invalid session: failed to find refresh token
at new ApolloError.`

Here's my code:

`async function getValidAccessToken () {
     const app = await getRealmApp()
    // Guarantee that there's a logged in user with a valid access token
    if (!app.currentUser) {
    // If no user is logged in, log in an anonymous user. The logged in user will have a valid
    // access token.
    const token = 'xyz....'
    if (token) {
      const credentials = Realm.Credentials.jwt(token);
      await app.logIn(credentials);
    } 
  } else {
    // An already logged in user's access token might be stale. To guarantee that the token is
    // valid, we refresh the user's custom data which also refreshes their access token.
    await app.currentUser.refreshCustomData()
  }
  return app.currentUser.accessToken
}
`

### Can you reproduce the bug?

Yes, sometimes

### Version

10.4.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Macos big sur Version: 11.5.2

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
Realm GraphQL only works with [legacy Realm Cloud](https://docs.mongodb.com/realm-legacy/docs/) (pre v10). You will have to migrate to MongoDB Realm Cloud which supports [GraphQL](https://docs.mongodb.com/realm/graphql/).

**Comment by abhishekmatta999** [comment]
I'm already using the one.
As mentioned in the docs:
`GraphQL requires MongoDB version 4.0 or greater.`

**Comment by abhishekmatta999** [comment]
> Realm GraphQL only works with [legacy Realm Cloud](https://docs.mongodb.com/realm-legacy/docs/) (pre v10). You will have to migrate to MongoDB Realm Cloud which supports [GraphQL](https://docs.mongodb.com/realm/graphql/).

And It was working till now with anonymous login. But as I mentioned above now I'm using custom JWT it starts showing me this error message

**Comment by kneth** [comment]
Please take a look and https://docs.mongodb.com/realm/graphql/ and https://docs.mongodb.com/realm/mongodb/link-a-data-source/
