### ISSUE TITLE
Realm throws in Electron forge installation due to react native package

### ISSUE THREAD

**Issue by florianbepunkt** [realm/realm-js#3988]
### How frequently does the bug occur?

All the time

### Description

Using electron forge and realm, I get this error as soon as I use / import realm. The error is in react-native, but I don't understand why  react-native is even installed, as I'm working on an electron app. 

```
ERROR in ../../node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
File was processed with these loaders:
 * ../../node_modules/@vercel/webpack-asset-relocator-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
| 
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
 @ ../../node_modules/realm/lib/utils.js 146:29-52
 @ ../../node_modules/realm/lib/index.js 19:14-32
 @ ./src/db-test.ts 43:30-46
 @ ./src/layout/base-structure.tsx 27:16-37
 @ ./src/layout/index.ts 4:23-50
 @ ./src/app.tsx 22:15-34
 @ ./src/renderer.ts 31:0-16
```

Output of `npm ls react-native`

```
└─┬ @datev-konverter/client@1.0.0 -> ./packages/client
  └─┬ realm@10.8.0
    ├─┬ deprecated-react-native-listview@0.0.6
    │ └── react-native@0.65.1 deduped
    └─┬ react-native@0.65.1
      └─┬ @react-native-community/cli@6.0.1
        └── react-native@0.65.1 deduped
```

### Can you reproduce the bug?

Yes, always

### Version

10.8.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac OSX 11.6 M1/Arm arc

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@florianbepunkt Can you use the work-around as described above?

**Comment by florianbepunkt** [comment]
@kneth Sorry, we decided against realm and for an indexdb infrastructure. Apologies for not closing this.
