### ISSUE TITLE
Predicate expressions must compare a keypath and another keypath or a constant value

### ISSUE THREAD

**Issue by avishayil** [realm/realm-js#399]
![Error](http://i.imgur.com/ujyHZln.png)
Relevant code on lines 66-67:
````javascript
Object.keys(missingTags).forEach((key, index) => {
	let filteredTag = AppStore.getState().tags.filtered('slug = ' + key);
````
Any ideas?

**Comment by appden** [comment]
In order for the `key` to be treated as a string, it would be need to be enclosed in quotes, but in this case, I would recommend you use the placeholder syntax instead like this: `filtered('slug = $0', key)`.

**Comment by appden** [comment]
@avishayil I'm closing this, but if you have any trouble, please let us know. Thanks!
