### ISSUE TITLE
React Native Realm not releasing memory after deleteAll

### ISSUE THREAD

**Issue by msaqlain** [realm/realm-js#3992]
### How frequently does the bug occur?

All the time

### Description

I have a react app mobile application with offline storage supported by realm. On login i sync with server using APIs and on logout I call `deleteAll` to delete all data in database.

After sync my app size grows from **100 MB** to **140 MB**

On logout after calling `deleteAll` data gets removed but appsize remains intact i.e **140 MB**.

Expectation: After data removal App must resize to 100 MB.

`realm.deleteAll()`

### Can you reproduce the bug?

Yes, always

### Version

5.0.3

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

OS 11 Android

### Build environment

Which debugger for React Native: ..

**Comment by Acetyld** [comment]
Also got this question, how to delete realm on logout?

**Comment by takameyer** [comment]
@msaqlain Thanks for reporting.  Deletion does not automatically deallocate memory.  You can force this however with [`compact()`](https://docs.mongodb.com/realm-sdks/js/latest/Realm.html#compact).  Let us know if that works for you

**Comment by bmunkholm** [comment]
@Acetyld that's an unrelated question. Please use our Forum to ask "how to" questions as we only use Github for bugs and feature requests.
