### ISSUE TITLE
Lazy loading/limit on react native

### ISSUE THREAD

**Issue by Acetyld** [realm/realm-js#3994]
### How frequently does the bug occur?

All the time

### Description

Hello!

I read realmjs is lazy loaded so using Object.(... for example in a flatlist i causing it to be lazy loaded.
But i had a few questions

1. Is it actually laze loaded into flat list? 
2. When i use a function to get all tasks sorted by date and put it inside a react.useState, is it still lazy loaded? 
3. Is there a limit option in react native? I couldt find anything in dogs, because otherwise i would implement a onEndReached function to load on demand.

### Stacktrace & log output

```shell
N/A
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

N/A

### Version

Newest

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

N/A

### Build environment

Which debugger for React Native: ..
N/A

**Comment by takameyer** [comment]
Hi @Acetyld , questions about Realm should generally be posted in our [forum](https://www.mongodb.com/community/forums/c/realm/realm-sdks/58).  That being said, I will attempt to answer your questions and close this non-issue.

1. By default a flat list will load the first 10 elements of the given collection.  Changing the settings of the flatlist will cause more of the realm data to be loaded.
2. If you use a custom function to sort through realm data, this will load all the data.  I recommend using the `filtered` and `sorted` functions to keep your data lazy loaded.  More info on that can be found in our [reference documentaiton](https://docs.mongodb.com/realm-sdks/js/latest/Realm.Collection.html)
3. There is no limit function, since everything is lazy loaded.

**Comment by Acetyld** [comment]
> Hi @Acetyld , questions about Realm should generally be posted in our [forum](https://www.mongodb.com/community/forums/c/realm/realm-sdks/58). That being said, I will attempt to answer your questions and close this non-issue.
> 
>     1. By default a flat list will load the first 10 elements of the given collection.  Changing the settings of the flatlist will cause more of the realm data to be loaded.
> 
>     2. If you use a custom function to sort through realm data, this will load all the data.  I recommend using the `filtered` and `sorted` functions to keep your data lazy loaded.  More info on that can be found in our [reference documentaiton](https://docs.mongodb.com/realm-sdks/js/latest/Realm.Collection.html)
> 
>     3. There is no limit function, since everything is lazy loaded.

Alright thanks!
And what about: 
```
const sortedTasks = realmRef?.objects('Task').sorted('@id');
```
 setTasks([...sortedTasks]);
 
 And then using **tasks** inside a flat list. Will this cause all to be rendered?
And i read in other SDK's that there is a limit function.

**Comment by Acetyld** [comment]
Sadly this doenst work.

This causing the problem of rendering it all and increasing memory. What am i doing wrong @bmunkholm ?

```
const Item = React.memo(({id})=>{
    console.log('Rerendering:',id)
    return (
        <View style={{ flex: 1, flexDirection: "column" }}>
            <Text> {id}</Text>
        </View>
    )
},
    (prevProps,nextProps)=>{
        return prevProps.id === nextProps.id
    }
);
const renderItem = ({item})=>{
    const {id} = item;
    return <Item id={id}/>
}
export function RealmTest() {
  const realmRef = useRealm();
    const tasks = realmRef.objects('Task');

return (
<View>
     <FlatList
                            data={tasks.sorted('@id')}
                            renderItem={renderItem}
                            keyExtractor={(item) => item.id}
                        />
</View>
)};

```

![afbeelding](https://user-images.githubusercontent.com/55088242/136061413-5ec5ca1c-8efc-4c43-b3ca-8686c14017b7.png)
