### ISSUE TITLE
react-native app crashed getting object schema in array index

### ISSUE THREAD

**Issue by gmchaturvedi1** [realm/realm-js#400]
Dear All,

I am very new to realm.First i just save my access token and then i retrieve with the following : 

let auth=realm.objects('auth');
let authToken=auth[0];
const token= authToken.token
causing app crash .

when i correct the folloing line  
let authToken=auth;

it is running. 

Can u suggest how to workaround it as array index is causing problem of app crash.

Kindly help me out on this.

Reagards
G M Chaturvedi

import {realm} from './realm/index.js';

export const token=authToken.token;

//development
//export const url='http://10.0.3.2:9191/api';
//Live case
export const url='http://api.go4skill.com/api';

**Comment by gmchaturvedi1** [comment]
kindly help me out on this as i am stuck with this.

**Comment by alazier** [comment]
Can you share the exception or crash log you are seeing? You would probably get a crash/exception if `auth.length == 0` so you might want to check for this before accessing `auth[0]`

**Comment by gmchaturvedi1** [comment]
How to collect crash report can u suggest me as i am new to this

**Comment by alazier** [comment]
If you run from XCode any crash information should be printed out in the console area on the bottom right.

**Comment by gmchaturvedi1** [comment]
i am running on windows and developing android app

**Comment by gmchaturvedi1** [comment]
i am saving my auth token first then ijust want to send token on each api call. So what i am doing in one file like this  : 
auth =realm.objects('auth');
export const token=auth[0].token

second line is creating issue .

thanks & Regards
G M Chaturvedi

**Comment by alazier** [comment]
Sounds like `auth.length` is 0, so accessing that index is causing the problem. Can you verify that `auth.length > 0`?

**Comment by gmchaturvedi1** [comment]
its coming true.But it is an array and index must start from 0.

Kindly suggest what to do.

**Comment by alazier** [comment]
I missed the message where you said you are on android/windows. We haven't yet tried running on windows so maybe we have some issue there. To see android crash information run `adb logcat` from the command line. `adb` is found in the android sdk. Does this print out any other information?

**Comment by alazier** [comment]
Also, are you running in chrome debug mode? If so that could also be causing issues on windows.

**Comment by gmchaturvedi1** [comment]
yes i am running chrome debug mode.So shall i use realm now or wait

**Comment by alazier** [comment]
I would guess that turning off chrome debug mode may fix the issue in which case the issue is in that layer. Unfortunately I don't have a windows machine setup to test this at the moment, so if there is an issue I'm not sure when we will be able to resolve it.

**Comment by gmchaturvedi1** [comment]
ok thanks for your support
