### ISSUE TITLE
Out Of Memory crashes since upgrading to v. 10.8.0

### ISSUE THREAD

**Issue by martinpoulsen** [realm/realm-js#4016]
### How frequently does the bug occur?
Sometimes

### Description
We are seeing a lot of "Out Of Memory" crashes in production on both iOS and Android since we upgraded realm from 10.2.0 to 10.8.0.

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
I have reproduced in this template app + realm 10.8.0:

https://github.com/martinpoulsen/realm-memory-issue

The app will populate "RoutePoint" entities to a "Trip" entity periodically initiated on app launch:

Schema:

```
const tripSchema = {
  name: 'Trip',
  primaryKey: 'id',
  properties: {
    id: 'string',
    updatedAt: {type: 'date', optional: true, default: new Date()},
    route: {
      type: 'list',
      objectType: 'RoutePoint',
    },
  },
};

const routePointSchema = {
  name: 'RoutePoint',
  primaryKey: 'id',
  properties: {
    id: 'string',
    lat: 'double',
    lon: 'double',
    time: {type: 'date', optional: true},
    alt: {type: 'int', optional: true},
    accuracy: {type: 'int', optional: true},
    speed: {type: 'int', optional: true},
    course: {type: 'int', optional: true},
    battery: {type: 'double', optional: true},
    invalid: {type: 'int', optional: true},
    deletedAt: {type: 'date', optional: true},
  },
};

const schema = [tripSchema, routePointSchema];
const schemaVersion = 1;
const migration = (oldRealm, newRealm) => {};

export const createRealmInstance = () => {
  const config = {
    schema,
    schemaVersion,
    path: 'realmfile',
    migration,
  };
  return new Realm(config);
};

```

Adding route points:

    const trip = realm.objects('Trip').filtered(`id == "${tripId}"`)[0];
    console.log('retrieved trip', trip.id, JSON.stringify(trip.route));
    
    const newRoute = Array.from(trip.route);
    const routePointId = getRoutePointUUID(i++);
    newRoute.push({
      ...routePointStub,
      id: routePointId,
      time: new Date(),
    });
    
    realm.write(() => {
      realm.create(
        'Trip',
        {
          id: trip.id,
          updatedAt: new Date(),
          route: newRoute,
        },
        true,
      );
    });After ~10 minutes (adding ~1300 route points), Android Studio memory profiling shows that the app uses ~800 MB of memory in the native layer and it only keeps growing from there.

![realm-memory-problem-10](https://user-images.githubusercontent.com/2430314/136787220-6f2aa878-28a8-4c70-a9c6-734b4288a6c1.png)UNITO-UNDERSCORE!8!UNITO-UNDERSCORE!0!

If the realm version in the sample app is downgraded to 10.2.0 and the app is deleted/reinstalled, then after 10 minutes the app only takes up less than 100 MB of memory in the native layer and this amount seems relatively stable.

![realm-memory-problem-10](https://user-images.githubusercontent.com/2430314/136787244-eec0fd48-6c6a-4f96-97c4-1ea769f6c6c9.png)UNITO-UNDERSCORE!2!UNITO-UNDERSCORE!0!

I have noticed that if I don't log `JSON.stringify(trip.route)` then the problem significantly decreases and if I don't log `trip.id` then the problem almost goes away. However, in our production app we don't log or stringify the trip or route, but we must be triggering the problem some other way.

We can't downgrade the realm version in our production app due to the internal realm file format version so a quick fix or ideas for a workaround would be much appreciated!

### Version
10.8.0

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
iOS 14, Android 11, etc.

### Build environment
Which debugger for React Native: ..

**Comment by cristianoccazinsp** [comment]
I'm using 10.8.0 as well, but haven't seen OOM issues. What is the specific use case that will trigger this so I can review our code to make sure we are not missing this until the patch is merged?

**Comment by martinpoulsen** [comment]
@kneth @fronck Awesome, thanks 🎉
