### ISSUE TITLE
Hermes enabled crashing React Native android app

### ISSUE THREAD

**Issue by GabrielBrotas** [realm/realm-js#4028]
### Description
When I try to run my app with hermes enabled the app keeps crashing and never open !!

The app just work when I disable the hermes !

Please fixx !!

It is a painfull trade off

### Can you reproduce a bug?
Yes, always

### Reproduction Steps
1 - Enable hermes
2 - Install app

never open

### Version
10.8.0

### What SDK flavour are you using?
MongoDB Realm (i.e. Sync, auth, functions)

### Platform OS and version(s)
Android

**Comment by kraenhansen** [comment]
Please try our pre-release with support for Hermes on Android and open an issue with a stack trace if the issue persists: https://github.com/realm/realm-js/releases/tag/v10.20.0-alpha.1
