### ISSUE TITLE
Default values of new columns not set for old entities after migration

### ISSUE THREAD

**Issue by artyom-ivanov** [realm/realm-js#4075]
### How frequently does the bug occur?

All the time

### Description

I have migration to new schema:
```js
const SCHEMA = [
  {
    name: 'SomeEntity',
    primaryKey: 'id',
    properties: {
      id: 'string', // old field
      // new fields after this line
      testField1: { type: 'bool', default: 'true' },
      testField2: { type: 'bool', default: 'false' },
      testField3: { type: 'string', default: 'im default' },
      testField4: { type: 'int', default: 42 },
      testField5: { type: 'int[]', default: [42, 911] },
      testField6: { type: 'string[]', default: ['tiler', 'durden'] },
      testField7: { type: 'bool[]', default: [false, true, true, false] },
      testField8: { type: 'date', default: new Date('2007-09-10 11:12:13') },
    }
  }
];
```
And no default values were set for existing entities in the database. They look like this:
```js
{
  "id": "someId",
  "testField1": false,
  "testField2": false,
  "testField3": "",
  "testField4": 0,
  "testField5": [],
  "testField6": [],
  "testField7": [],
  "testField8": "1970-01-01T00:00:00.000Z"
}
```

### My temporary fix
I am explicitly setting the values of existed entities in the migration:
```js
function migration(_: Realm, newRealm: Realm) {
  let enitites = newRealm.objects<SCHEMA['someEntity']>('SomeEntity');
  enitites.forEach((entity) => {
    entity.testField1 = true;
    entity.testField2 = false;
    entity.testField3 = "im default";
    // ... and other fields
  });
}
```

I think this is a bug? Shouldn't default values be set for all previous entities?

### Can you reproduce the bug?

Yes, always

### Version

10.9.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

React Native 0.66.2

**Comment by kneth** [comment]
@artyom-ivanov It is correct that adding new properties to a schema will not populate the values with default values. The reason is that we don't track changes to default values (will not trigger a migration), and you are responsible to set properties using a migration function.
