### ISSUE TITLE
Invalid session ID

### ISSUE THREAD

**Issue by IlyaSuhodolskiy** [realm/realm-js#408]
When debug in chrome starts
<img width="601" alt="screenshot 2016-04-30 00 08 30" src="https://cloud.githubusercontent.com/assets/8992530/14929745/bd772656-0e67-11e6-923e-d4a71b6e6d8e.png">

**Comment by alazier** [comment]
Are you able to reproduce this issue? If so can you provide the steps to do so?

**Comment by alazier** [comment]
Were you able to figure this out?

**Comment by amanthegreatone** [comment]
getting the same error for android but not for ios.

**Comment by dcarrot2** [comment]
@amanthegreatone Getting the same error as well. Looking to consistently reproduce. Were you able to solve this?

**Comment by sachinwak** [comment]
I am getting same issue below is my code
"react-native": "0.47.1",
"realm": "^1.11.1",
platform: android

```
let realm = new Realm({ schema: [RecipesSchema] });
let allRecipes = realm.objects('Recipes');
```

**Comment by LeonidVeremchuk** [comment]
Very ugly workaround:

**Comment by danijel1108** [comment]
This error always appear for me in android emulator.
Please re-open this issue.

**Comment by bmunkholm** [comment]
@danijel1108 This issue is old. Please recreate with full reprocase of how to reproduce this.

**Comment by danijel1108** [comment]
When I enable remote debug option then I'm getting always "Invalid Session ID".
I tried with  @LeonidVeremchuk 's solution but it doesn't helpful for me.
Please let me know how to fix it.
Thank you so much for your reply.

**Comment by bmunkholm** [comment]
Sorry I wasn't clear. Please create a new github issue will full instructions on how to replicate your issue. Thanks!

**Comment by colaskirschoff** [comment]
@danijel1108 if you installed another lib that depends on a different version of realm that could be the reason why you still have this issue !
