### ISSUE TITLE
EXC_BAD_ACCESS during writes from React Native

### ISSUE THREAD

**Issue by lachlanjc** [realm/realm-js#409]
I’m developing a React Native app with Realm v0.11.1 for iOS 9.3, and every time I use `realm.write` the app freezes and Xcode gives me an error on [`node_modules/realm/src/js_util.hpp`](https://github.com/realm/realm-js/blob/0.11.x/src/js_util.hpp#L113), line 113:

```
Thread 1: EXC_BAD_ACCESS (code=1, address=0xbbadbeef)
```

Code I’m writing to Realm with:

```js
const NoteSchema = {
  name: 'Note',
  primaryKey: 'id',
  properties: {
    id:      { type: 'string', indexed: true },
    content: { type: 'string', indexed: true },
    createdAt:  'date',
    modifiedAt: 'date'
  }
}

let realm = new Realm({ schema: [NoteSchema] })
const data = { id: this.state.id, content: text }
realm.write(() => {
  realm.create('Note', data, true)
})
```

I would expect this to go through smoothly, as my code is so similar to that in the documentation. I’ve found issues in the Cocoa version about fixing EXC_BAD_ACCESS errors, but in React Native these issues are still present. If I’m being an idiot, however, please let me know 😜 — thanks!

**Comment by aljs** [comment]
Your data does not contain 'createdAt' and 'modifiedAt' properties. Try this:
`const data = { id: this.state.id, content: text, createdAt: new Date(), modifiedAt: new Date() }`
Also, you should check that **this.state.id** is not undefined.

**Comment by lachlanjc** [comment]
Thanks @aljs, I got this sorted out! :v:

**Comment by appden** [comment]
@lachlanjc Thanks for reporting this. You should have been getting an exception that says `Missing property value for property createdAt`, and **not** a crash. I tried reproducing this crash but was instead getting the exception. I was hoping that you would be willing to send us an example of your code that was causing this crash to occur. Thanks!
