### ISSUE TITLE
React Native pagination

### ISSUE THREAD

**Issue by rajb19** [realm/realm-js#4116]
### How frequently does the bug occur?

All the time

### Description

How to set LIMIT & OFFSET for pagination in react native with realm database?

### Can you reproduce the bug?

Yes, always

### Version

  "realm": "^10.10.1"

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

MAC

### Build environment

Which debugger for React Native: ..

**Comment by tomduncalf** [comment]
Objects in the Realm database are lazy-loaded, so you don't need `limit`/`offset` operators in the same way you might with other databases. Instead, you can just directly access the results when you need them, with no extra overhead – the items will only be loaded into memory when you actually access them. For example, you could call `.silce(startIndex, endIndex)` on the array returned from a `realm.objects` call to simulate traditional pagination.

You can read more about this in the documentation: https://docs.mongodb.com/realm/sdk/react-native/fundamentals/live-queries/#collections
