### ISSUE TITLE
Cannot logout - got TypeError: user.logOut is not a function

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#4118]
Have a similar issue here. 
Cannot logout - got TypeError: user.logOut is not a function
If I disable hermes & use the latest version of realm, everything works well.

_Originally posted by @threefeetcat in https://github.com/realm/realm-js/discussions/3978#discussioncomment-1535470_

**Comment by Meknassih** [comment]
react-native: 0.66.4
realm: 10.20.0-alpha.2

I’m having the same issue : `TypeError: undefined is not a function` when using `user.logOut()`.
Same thing happens with `user.refreshCutomUserData()`.

I also noticed that `user.id` is always correct but `user.customData` is always `undefined` even though it is enabled in the Authentication settings of the Realm UI.

**Comment by Meknassih** [comment]
Hello @fronck, unfortunately I cannot, I scraped everything and rewrote the logic without Realm. Turned out it wasn’t compatible with React Native + Hermes Javascript Engine at the time.
