### ISSUE TITLE
Mobile SDK is missing `Realm.Credentials.apiKey()` method

### ISSUE THREAD

**Issue by tomduncalf** [realm/realm-js#4127]
`Realm.Credentials.serverApiKey` and `Realm.Credentials.userApiKey` perform identical functions, so were marked as deprecated in https://github.com/realm/realm-js/commit/f54955a5ef7dff2d6bfb45483ecf351a68180cac#diff-52e30e256b42ae9eb24479069c555370865a9f9be570eabe2b097a1d01d867afR147 and superseded by a single `Realm.Credentials.apiKey` method.

This method was added to the web SDK: https://github.com/realm/realm-js/blob/master/packages/realm-web/src/Credentials.ts#L91 but was missed from the mobile SDK. This means that users see a deprecation warning for the old methods, but if they change their code to use `apiKey`, it will not work.

We need to add the `apiKey` method in https://github.com/realm/realm-js/blob/master/src/js_app_credentials.hpp#L51 and in the TS definitions. It should have the same implementation as `server/userApiKey`.

**Comment by vadimluminous** [comment]
Seconded on this I get the same issue. Warning recommends to use "Realm.Credentials.apiKey" but apiKey is not found

**Comment by kamontat** [comment]
`apiKey()` is missing in Node.JS SDK as well.
package: `realm@v10.19.2`

**Comment by linxiano** [comment]
Still seems to be missing in Node.JS SDK package: "realm": "10.19.5"
