### ISSUE TITLE
Multiple Audience Support for JWT Auth Not Working

### ISSUE THREAD

**Issue by jasontlouro** [realm/realm-js#4133]
### How frequently does the bug occur?

All the time

### Description

When setting two audiences in Realm's UI (using a comma with no spaces as the delimiter), attempting to authenticate with either audience fails. The error message is "[audience] not found in 'aud' claim" where [audience] is the other audience specified in the Realm configuration.

For example, I set two acceptable audiences, one to be used by our desktop application's authentication and one to be used by our web app authentication. As soon as the configuration was saved, the web app's authentication broke, with the error message "[desktop audience] not found in 'aud' claim" while the desktop app authentication broke with "[web audience] not found in 'aud' claim". 

Realm seems to be expecting all audiences when my understanding is that it should just be checking for one of them. I am not particularly experienced with JWT however so perhaps I'm missing something obvious here.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Set two audiences in a Realm app's custom JWT authentication. We are using a JWK URI.
2. Attempt to authenticate with either of the two audiences.

### Version

Realm Web v1.4.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Observed on both Windows 10 and macOS Big Sur

### Build environment

Observed on Realm Web 1.4.0.

**Comment by kneth** [comment]
@jasontlouro Thank you for reporting. We'll work with the cloud team to narrow down where the issue is. In the meantime, can you explain how you encode the audience in the JWT?

**Comment by jasontlouro** [comment]
@kneth Sure:

Our use case for custom JWT auth is to support Log in with Google. I know you guys have a Google Auth signin method, but due to a breaking issue that existed with that authentication method and Realm Web around the time of the launch of our product back in October/November 2020, we were forced to use custom JWT instead.

To authenticate, we use Google's javascript(specifically [gapi.auth2.authorize](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams_callback)). This runs with the Google Client ID that we created for our web app, which is also the `aud` that Realm is configured to expect. The authorize function gives us an `id_token` upon successful authentication by the user, which we use to initialize a Realm credentials object: `Realm.Credentials.jwt(id_token)`. 

This all works as expected when Realm's Custom JWT is configured such that the expected audience is exactly equal to the Google Client ID mentioned above.

The issue is when we add a second audience to Realm's configuration. The use case here is that our Desktop application needs a different kind of Google Client ID. So, we update the Realm configuration so that the audience contains the Client ID for web, followed by a single comma with no spaces, followed by the Client ID for desktop. This immediately breaks authentication on web, which continues to use the process described above. The error message that comes from Realm is the one I described in this issue: "[Desktop Client ID] not found in 'aud' claim".

**Comment by jasontlouro** [comment]
Here is the Realm Custom JWT configuration that works correctly with our web app:

![RealmConfig](https://user-images.githubusercontent.com/33489988/145207594-3823e5f7-7076-492d-93be-a17a58796283.png)

And the configuration that breaks with the error mentioned above:

![RealmBreakingConfig](https://user-images.githubusercontent.com/33489988/145207636-88136a6e-430b-48bd-91a2-748d0eda7d36.png)

The only change is adding the additional permitted audience with a comma separating them.

**Comment by kneth** [comment]
When you have configured multiple audiences, you need to send the all for each token. From the [specification](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3):

> In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value

**Comment by jasontlouro** [comment]
@kneth That was not my interpretation of the spec. See immediately below the quote from your post above:

> Each principal intended to process the JWT MUST identify itself with a value in the audience claim.  If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected.

Note that it says the processor of the claim must identify itself with **a value**, not **all values**, in the "aud" claim. My interpretation here was that Realm should just be checking that there is a match between the aud claim I provide upon authentication and the audiences I set up in the Realm config.

If your interpretation is correct, I believe what I'm trying to do is impossible, as I'd have to get valid Client IDs from both the web auth flow and the desktop auth flow just to sign in on web. It seems unlikely that this is the case. I should be able to get the Client ID from a successfully login using the web audience and have my Realm configuration accept that audience.

Please advise and thank you for your help so far!

**Comment by kneth** [comment]
As I am not a JWT expert, I will suggest that you ask at https://www.mongodb.com/community/forums/c/realm/9 to get a more educated advise.

**Comment by jasontlouro** [comment]
> As I am not a JWT expert, I will suggest that you ask at https://www.mongodb.com/community/forums/c/realm/9 to get a more educated advise.

Why is the community forum the place to go for this? I'm fairly certain this is a misinterpretation of the spec on Realm's end. Is it possible for whoever worked on the recent addition of multiple-audience support (who I assume is your resident "JWT expert") can take a look? If I'm correct, this is a bug, so a Github issue seems the right place for it.

**Comment by kneth** [comment]
@jasontlouro Sorry, I was a bit quick there. I will talk with the MongoDB Realm cloud team to see how we can support your use case better.

**Comment by jasontlouro** [comment]
> @jasontlouro Sorry, I was a bit quick there. I will talk with the MongoDB Realm cloud team to see how we can support your use case better.

No worries, thanks!

**Comment by jasontlouro** [comment]
Hey @kneth - This is still not working. We are totally unable to get multi-aud support, which means we can't simultaneously support Google Sign-in on our web app and our mobile app. Please advise.

**Comment by kneth** [comment]
@jasontlouro The work has been schedule but I can't give you an exact date for when we have multiple audience support.

**Comment by jasontlouro** [comment]
> @jasontlouro The work has been schedule but I can't give you an exact date for when we have multiple audience support.

Thank you for the update @kneth. We are hoping to launch our mobile app in June and we use Realm + Atlas as our backend solution. We were able to come up with a workaround for the launch of our desktop app back in December when I first reported this issue (by using the web app's aud claim for desktop too) but that solution will not work for mobile. We need a separate aud claim for the app.

I understand that you can't yet provide an exact date, but can you give us anything more than that it's been scheduled? We've been a Realm customer since October 2020 and would be extremely appreciative if this could be resolved in time for our launch.

**Comment by kneth** [comment]
> launch our mobile app in June 

My understanding is that the updates to the MongoDB Realm backend will be ready for you.

**Comment by jasontlouro** [comment]
Hey @kneth, tested this a couple days ago and still no dice. Any updates on when/whether this issue will be resolved? It is the only blocker on our mobile app release.

**Comment by jasontlouro** [comment]
@kneth I imagine the best solution is to follow the spec and instead of checking whether the `aud` array of the claim exactly matches the `aud` array configured in the Realm settings, checking if there is a match between any item in the two arrays. The spec states this clearly. This bug has been live since December, and the fix is remarkably straightforward. We're trying to launch a mobile app with the use of Realm, and this is a complete blocker on our app's launch. It's been 6 months since I first reported this.

There's nothing to investigate here. The spec is clear. Please try to squeeze it in for us as soon as possible.

**Comment by jasontlouro** [comment]
Thanks @kneth, I appreciate it!

**Comment by jasontlouro** [comment]
There looks to be a new option in JWT auth to choose between any/all for multiple audiences. This appears to be working as expected. Thank you for getting this sorted out for us in time for our mobile app launch.

**Comment by kneth** [comment]
@jasontlouro I am happy at we - finally - got the feature out to you.
