### ISSUE TITLE
How to store Array of multipe types with realm in react native

### ISSUE THREAD

**Issue by dridi93** [realm/realm-js#4134]
HI,

When using realm, if i need to store filed with value like [783, "Name of"],

This is my code, when i use mixed i got null,

```
export const Schema = {
  name: 'Schema',
  primaryKey: 'id',
  properties: {
    id: 'int',
    name: {type: 'string', indexed: true},
    field: 'string[]', // mixed[] not work too
  }
}
```

Any help please !!!

**Comment by kneth** [comment]
@dridi93 How do you store the list `[783, "Name of"]`? You can try to create the object first and then set `field` after. Maybe you can get some inspiration from [one of our tests](https://github.com/realm/realm-js/blob/master/tests/js/mixed-tests.js#L175-L200).

**Comment by dridi93** [comment]
@kneth

Can i override the object constructor like the example above, to auto set field values ?

`constructor (values) { 
this.id = values[0];
this.name = values[1];
 }`

Thanks,
