### ISSUE TITLE
Add option to exclude realm from iCloud backup

### ISSUE THREAD

**Issue by c-goettert** [realm/realm-js#4139]
### Problem
Some apps might want to exclude realm from the iCloud backup. Currently there is no configuration option to achieve this behavior. I am aware that there are manual ways to solve this, e.g. manipulating the resource keys of files created by realm. However, I can understand developers who would rather not make such adjustments, as they may not be able to fully understand the effects. E.g., Apple writes in the documentation about the corresponding [NSURLIsExcludedFromBackupKey](https://developer.apple.com/documentation/foundation/nsurlisexcludedfrombackupkey) parameter:

> Set this property each time you save a file because some common file operations cause this property to reset to false.

It also feels to me that this option should be configurable via Realm itself, since Realm is a database with its own synchronisation capabilities. React Native Async storage for example offers a [configuration option](https://react-native-async-storage.github.io/async-storage/docs/advanced/backup/) for this purpose. Also, I've seen that for some files there is already an exclusion rule defined (see [PR](https://github.com/realm/realm-cocoa/pull/5270/commits/ce8be5ed6aec5b0c73cd62ff55f9a62d0c97373d)). Maybe you can tie in here? 

### Solution
Provide a configuration parameter to exclude realm file from iCloud backup.

### How important is this improvement for you?
I'd like to see it, but have a workaround

**Comment by kneth** [comment]
@c-goettert Thank you for the suggestion. I see three possibilities:

1. Always exclude Realm files from iCloud backup
2. Only synced Realms from backup
3. Add a configuration option and let the app developer to decide

I can't give a timeline for when we add it, but if you were to pick, which one of the three above would you prefer?

**Comment by c-goettert** [comment]
Hi @kneth, thanks for the fast reply!
I would prefer a configuration option (3), as it's the most flexible one.

**Comment by marcosrdz** [comment]
Any updates on this?

**Comment by kraenhansen** [comment]
Did a quick search on this. It seems we'd need to (optionally, based on the configuration) call into Swift code every time we save a Realm .db file: https://github.com/react-native-async-storage/async-storage/blob/67bb6f543db43678b2ee142503c8c12ac7a10989/packages/default-storage/ios/RNCAsyncStorage.mm#L37-L57

Since we memory-map the file, I'm not 100% certain what "save" means in our case, it might be required on every flush, which would likely be detrimental to runtime performance 🤔

**Comment by danibonilha** [comment]
Hi @kraenhansen,  any updates on this ? Is there an easy workaround for now ? If I could get some pointers on how it works I could try and patch it for me project or open a PR

**Comment by kraenhansen** [comment]
A fix for this was released in v12.14.0, enabled by setting `excludeFromIcloudBackup: true` in the config when opening the Realm file - see the changelog for more details on this feature.

Thanks a lot @danibonilha for your PR and time crafting the testing guide!
