### ISSUE TITLE
Expo Template for Realm

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#4142]
Expo now supports third party libraries through the expo dev client.  Let's create an Expo template for Realm!

- make a copy of the ts-template into a new expo template
- install expo modules (https://docs.expo.dev/bare/installing-expo-modules/)
- install dev-client (https://docs.expo.dev/development/installation/)
- add expo specific scripts to package.json (npm run android/ios/start ...etc)
- target the beta version of SDK 44 (without react-native-reanimated)
- test in both android and ios
- if necessary, downgrade to RN 0.64

**Comment by polymath74** [comment]
Is this now the accepted procedure? If so, please update the docs (with a warning about "not yet supported / fully functional"?) - https://docs.mongodb.com/realm/sdk/react-native/install/ still refers to a "not possible" vote page that is more than a year old.
