### ISSUE TITLE
Cannot run reset password function using Node SDK

### ISSUE THREAD

**Issue by ivanBereznev** [realm/realm-js#4143]
### How frequently does the bug occur?

All the time

### Description

I use NodeJS Realm SDK.

I expect my password reset function to be called when I do the following:
```
await app.emailPasswordAuth.callResetPasswordFunction('user@example.com', 'myNewPassword')
```
or at least when I use new API as this is described [here](https://github.com/realm/realm-js/issues/3943):
```
await app.emailPasswordAuth.callResetPasswordFunction({ email: 'user@example.com', password: 'myNewPassword' })
```
But both approaches result in the same error.
 

### Stacktrace & log output

```shell
Error: Error: resetDetails must be of type 'object', got (user@example.com)
at /myProject/node_modules/realm/lib/email-password-auth-methods.js:76:35
at /myProject/node_modules/realm/lib/utils.js:52:7
at new Promise (<anonymous>)
	at promisify (/myProject/node_modules/realm/lib/utils.js:51:12)
	at EmailPasswordAuth.callResetPasswordFunction (/myProject/node_modules/realm/lib/email-password-auth-methods.js:76:12)
	at _callee$ (/myProject/utils/resetPassword.js:11:31)
	at tryCatch (/myProject/node_modules/regenerator-runtime/runtime.js:63:40)
	at Generator.invoke [as _invoke] (/myProject/node_modules/regenerator-runtime/runtime.js:294:22)
	at Generator.next (/myProject/node_modules/regenerator-runtime/runtime.js:119:21)
	at asyncGeneratorStep (/myProject/utils/resetPassword.js:11:103)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Enable email/password auth for Realm Application
2. Configure it to run custom password reset function
3. Register a user
4. Try to run password reset function for registered user:
```
const app = new Realm.App({id: id})
await app.emailPasswordAuth.callResetPasswordFunction({ email: 'user@example.com', password: 'newUserPassword' })
```

### Version

10.10.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Debian GNU/Linux 9.13 (stretch)

**Comment by takameyer** [comment]
Thanks for reporting this issue.  We will look into it as soon as we can.  I assume this is happening in a Node environment (not React Native)?

**Comment by ivanBereznev** [comment]
@takameyer yes, this happens in Node environment.

**Comment by takameyer** [comment]
@ivanBereznev we have found the issue and it will be fixed in the next release.  Here is the PR:
https://github.com/realm/realm-js/pull/4148
