### ISSUE TITLE
Realm partially persists invalid objects

### ISSUE THREAD

**Issue by marcoancona** [realm/realm-js#4146]
### How frequently does the bug occur?

All the time

### Description

If a schema validation is caught while performing a write operation, the object in the db will be partially updated, even if invalid. Please see the example below.

I would expect each `realm.create` operation to be atomic, therefore such that it cannot only partially succeed. Is this the expected behavior?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

The following snipped can be run as `node realm.js`, assuming `realm.js` is:

```js
const Realm = require('realm');
const uuidV4 = require('uuid').v4;

console.log(process.versions);

const TaskSchema = {
  name: 'Task',
  properties: {
    _id: 'string',
    stamp: 'string',
    name: 'string',
  },
  primaryKey: '_id',
};

const sleep = async (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function run() {
  const realm = await Realm.open({
    schema: [TaskSchema],
    deleteRealmIfMigrationNeeded: true,
    path: './real-test.realm',
  });

  // Write a valid object
  const uuid = uuidV4();
  const originalStamp = `${new Date().valueOf()}`;
  realm.write(() => {
    realm.create(
      'Task',
      {
        _id: uuid,
        name: 'Test event',
        stamp: originalStamp,
      },
      Realm.UpdateMode.Modified
    );
  });

  // Wait a moment
  await sleep(125);

  // Try to write an update with an invalid format (name should be a string)
  const newStamp = `${new Date().valueOf()}`
  realm.write(() => {
    // add a try-catch
    // the goal is to ignore invalid objects while performing a "bulk save" operation
    try {
      realm.create(
        'Task',
        // Invalid update because of "name"
        { _id: uuid, stamp: newStamp, name: {} },
        Realm.UpdateMode.Modified
      );
    } catch (e) {
      // Log the error but continue
      console.log(e);
    }
  });

  // Get the object in the database and compare
  const newTask = realm.objects('Task').filtered(`_id == "${uuid}"`).toJSON()[0];

  console.log(`Original stamp: `, originalStamp). // 1639433231974
  console.log(`Update stamp: `, newStamp) // 1639433232101
  console.log(`Expected value in the database: `, originalStamp) // 1639433231974
  console.log(`Actual value in the database: `, newTask.stamp) // 1639433232101
}

run();
```

### Version

10.7.0"

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS 12.0.1

### Build environment

Plain nodeJS environment:
```
{
  node: '15.14.0',
  v8: '8.6.395.17-node.28',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k+quic',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by marcoancona** [comment]
Hi @kneth,
after some experiments I realized it as well. On the other hand, the reason why the try-catch was around `create` in the first place is to support fast bulk-save operations. 

Say that we need to store an array of objects, ignoring invalid ones. The way I thought I could do that is 

```js
realm.write(() => {
    myObjectList.forEach((obj) => {
        try {
           realm.create('Task', obj, Realm.UpdateMode.Modified);
        }
        catch (e) {
           console.log('Ignoring error')
        }
    })    
  });
```  

but this could leave inconsistent data in the db. If I create a write transaction for each object, this would be significantly slower with a large list, wouldn't it?

**Comment by kneth** [comment]
@marcoancona 

In an [ACID](https://en.wikipedia.org/wiki/ACID) compliant database (as Realm), the write transaction must be atomic (A in ACID). Atomicity is "all or none" that is, either all operations succeed or none succeed. By catching an exception inside a transaction, you will break this invariant.

> ignoring invalid ones ... leave inconsistent data in the db

You should check if an object is invalid instead of using [exceptions as flow control](https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why). 

> If I create a write transaction for each object, this would be significantly slower with a large list, wouldn't it?

Potentially yes.

**Comment by marcoancona** [comment]
Thanks for clarifying @kneth. Still, it is not clear to me what is the recommended way to "check if an object is valid". As far as I understood, Realm does not expose a validation API, does it? Nor the Realm schema can be processed by out-the-shelf JSON schema validators. At the same time, we don't want to have multiple schemas for the same object, creating multiple sources of truth for the validity of an object.

If I understood correctly Realm atomicity, something like the code below should work. This is efficient _assuming invalid objects are rare_ but clearly this also seems just an ugly workaround that relies heavily on exceptions as flow control.

```js
    const safeTransaction = (objs) => {
      realm.beginTransaction();
      for (let i = 0; i < objs.length; i++) {
        try {
          realm.create(collectionName, objs[i], Realm.UpdateMode.Modified);
        } catch (err) {
          // Remove the invalid object from the array
          objs.splice(i, 1);
          // Cancel transaction to discard every "create" operation done so far
          realm.cancelTransaction();
          // Try again
          return safeTransaction(objs);
        }
      }
      realm.commitTransaction();
    };
```
