### ISSUE TITLE
Port over ignoredProperties or allow non-schema properties

### ISSUE THREAD

**Issue by Lida** [realm/realm-js#415]
If I try to assign a non-schema property to a RealmObject, I currently get an exception in `Object::set_property_value` in file object_accessor.hpp.

This only happens on Release builds and was unexpected. If RealmJS want all properties to be listed in schema, then there should be an ignoredProperties field in schemas. Otherwise, it should not throw a InvalidPropertyException.

**Comment by alazier** [comment]
I've made a pr to address this. Instead of having to specify ignored properties, we will allow you to set and get properties not in your schema like any other js properties.
