### ISSUE TITLE
Unreachable Code - Android

### ISSUE THREAD

**Issue by WenLonG12345** [realm/realm-js#4169]
### How frequently does the bug occur?

All the time

### Description

I faced this issue when creating schema with 'mixed' data-type.
Here is my code for schema

```
  const MessageSchema = {
    name: 'Message',
    primaryKey: 'id',
    properties: {
      assignee_id: 'string',
      client_id: 'string',
      content: 'mixed',  <-- cannot use 'mixed'
      created_at: 'string',
      from_id: 'string',
      from_type: 'string',
      id: 'string',
      msg_cat: 'string',
      msg_type: 'string',
      reference_id: 'string',
      room_id: 'string',
      sequence: 'int',
      updated_at: 'string',
    }
  };
```

I tried to change 'mixed' into 'string' and all working fine. 
I suspect maybe 'mixed' is the one causing the crash error.
Any solution? 

The error stack is coming from Logcat in Android Studio. React Native will straight crash and exit the app.

### Stacktrace & log output

```shell
E/REALM: /Users/kneth/Projects/realm-js/src/jsc/rpc.cpp:360: [realm-core-11.7.0] Unreachable code
    <backtrace not supported on this platform>!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
```

### Can you reproduce the bug?

Yes, always

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 10

### Build environment

Which debugger for React Native: ..
React Native Debugger

**Comment by kneth** [comment]
@WenLonG12345 The data type Mixed isn't supported by our Chrome debugger implementation. If you switch to Hermes, you can use Flipper as debugger. For more information, please take a look at https://github.com/realm/realm-js/issues/3940
