### ISSUE TITLE
ld: library not found for -lrealm-js-ios

### ISSUE THREAD

**Issue by skyforeverRivian** [realm/realm-js#4171]
### How frequently does the bug occur?

All the time

### Description

our team is trying to plugin realm as main db, however, we tried many times, it always return the below errors. 

solution 1:
clean & deintegrate everything in pod then reinstall everything

solution 2:
excludes arm64

our pod file:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == "Debug" || config.name == "Release-e2e"
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      else
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end
  end
end

target 'Internal' do

  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'BarcodeDetectorMLKit'
]

  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
end
```

realmjs:
10.11.0

node version:
v14.15.4

yarn version:
v1.22.10

pod version:
1.10.1

react native:
0.65.1

### Stacktrace & log output

```shell
: warning: directory not found for option '-L"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator" "" "/Users/myname/Library/Developer/Xcode/DerivedData/Internal-finbwplvgoowpcfagqvegkbibheg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/realm-js-ios"'
ld: library not found for -lrealm-js-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)


```Showing All Messages
Directory not found for option '-L"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator" "" "/Users/myname/Library/Developer/Xcode/DerivedData/Internal-finbwplvgoowpcfagqvegkbibheg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/realm-js-ios"'```
```
log from terminal:
```
The following build commands failed:
	Ld /Users/myname/Library/Developer/Xcode/DerivedData/Internal-finbwplvgoowpcfagqvegkbibheg/Build/Products/Debug-iphonesimulator/Rivian\ HUB.app/Rivian\ HUB normal (in target 'Internal' from project 'Internal')
```

### Can you reproduce the bug?

Yes, always

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

xcode 13.2; react native 0.65.1

### Build environment

Which debugger for React Native: ..

**Comment by tomduncalf** [comment]
Hi,

I've created a test Realm project using our template, but with your Podfile and versions of Realm and React Native and was able to build it without issues on Xcode 13.2.

Would you be able to see if you are able to build my project? Clone https://github.com/tomduncalf/issue4171 then `npm install`, `npx pod-install`, `npm run ios`.

If this builds OK, then are you able to think of any other differences in the way your project is set up which might be causing this?

Thanks,
Tom

**Comment by skyforeverRivian** [comment]
@tomduncalf thank you for replying. I believe you testing template can work properly; however, we are using yarn, can you try with that?

**Comment by tomduncalf** [comment]
Hey @skyforeverRivian, I just tried with `yarn` 1.22.15 and 3.1.1, deleting my `node_modules` in between, and it worked fine with both. Are you not able to build my sample project using `yarn`?

**Comment by skyforeverRivian** [comment]
@tomduncalf let me try, will get back to you very soon

**Comment by skyforeverRivian** [comment]
@tomduncalf yeah, it works with yarn based on your project; still don't know why it keeps giving us that error based on our project? do you have any suggestion?

**Comment by tomduncalf** [comment]
My template is using an identical Podfile to yours so I don't think that's the issue: https://github.com/tomduncalf/issue4171/blob/main/ios/Podfile

Let me do some research and I'll get back to you!

**Comment by skyforeverRivian** [comment]
@tomduncalf thanks a lot; hopefully, you can have something for us; otherwise, we don't know what next thing we can do.

**Comment by skyforeverRivian** [comment]
@tomduncalf meanwhile, here is our package file:

```
{
  "name": "com.company.ios.internal",
  "version": "1.1.0",
  "private": true,
  "scripts": {
    "setup": "find ./node_modules/@company/ -name \"node_modules*\" -exec rm -rf '{}' +",
    "start": "APP_ENV=development npx react-native start",
    "start:stage": "APP_ENV=stage npx react-native start",
    "start:prod": "APP_ENV=prod npx react-native start",
    "start:e2e": "APP_ENV=e2e npx react-native start",
    "android": "APP_ENV=development react-native run-android --no-packager --appId com.company.internal",
    "iPad": "APP_ENV=development cd ios && pod install && cd .. && react-native run-ios --simulator='iPad Pro (12.9-inch)'",
    "ios": "APP_ENV=development cd ios && pod install && cd .. && react-native run-ios --simulator=\"iPad Air (4th generation)\"",
    "ios:device": "APP_ENV=development cd ios && pod install && cd .. && react-native run-ios",
    "android-release": "APP_ENV=prod react-native run-android --variant=release",
    "ios-release": "APP_ENV=prod cd ios && pod install && cd .. && react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios' && npx react-native run-ios --configuration Release",
    "test": "jest",
    "test:watch": "jest --verbose --watch ./src",
    "lint": "eslint ./src",
    "lint:technician": "eslint ./src/screens/technician && eslint ./src/screens/concierge",
    "format": "prettier-eslint --write '**/.*.{yml,json,js}' '**/*.{md,yml,json,js,css,scss}'",
    "generate-gql-types": "npx apollo codegen:generate --endpoint=$NEXT_PUBLIC_company_GQL_ENDPOINT --target=typescript --includes=src/api/apollo/queries/index.ts --tagName=gql --no-addTypename  --globalTypesFile=src/api/apollo/queries/delete-me.ts --outputFlat src/api/apollo/queries/types && rm src/api/apollo/queries/delete-me.ts",
    "local-install": "rm -rf node_modules && yarn install",
    "copy-services": "nodemon --watch ../../dc-fe-mobile-services/src --exec \"cp -R ../../dc-fe-mobile-services/src/* ./node_modules/@company/dc-fe-mobile-services/src && cp -R ../../dc-fe-mobile-services/src/* ../shared/mobile-services/src\"",
    "test:cov": "jest --verbose --coverage ./src",
    "cov:open": "open coverage/lcov-report/index.html",
    "type-check": "node scripts/add-ts-no-check.js && yarn tsc"
  },
  "repository": {
    "type": "git",
    "url": "https://gitlab.com/company/dc/dc-fe-app-mobile-internal.git"
  },
  "dependencies": {
    "@apollo/client": "^3.3.12",
    "@datadog/mobile-react-native": "^1.0.0-rc3",
    "@datadog/mobile-react-navigation": "^1.0.0-rc3",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/netinfo": "^5.9.7",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-native-cookies/cookies": "^6.0.8",
    "@react-native-firebase/analytics": "^12.8.0",
    "@react-native-firebase/app": "^12.8.0",
    "@react-native-firebase/crashlytics": "^12.8.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-native-segmented-control/segmented-control": "^2.3.0",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.9.3",
    "@react-navigation/material-top-tabs": "^5.3.19",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "@reduxjs/toolkit": "^1.5.0",
    "@company/dc-fe-mobile-components": "git+https://internal:84DUJ-13sUMqDtZ8yrzG@gitlab.com/company/dc/shared/dc-fe-mobile-components",
    "@company/dc-fe-mobile-services": "git+https://internal:ksEgZLo69425kxnAeVKX@gitlab.com/company/dc/shared/dc-fe-mobile-services",
    "add": "^2.0.6",
    "axios": "^0.21.1",
    "base-64": "^1.0.0",
    "buffer": "^6.0.3",
    "core-js": "^3.6.5",
    "core-js-bundle": "3.8.2",
    "cross-fetch": "^3.1.4",
    "css-select": "^3.1.0",
    "css-tree": "^1.0.0-alpha.39",
    "deepmerge": "^4.2.2",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "graphql": "^15.3.0",
    "immer": "^8.0.1",
    "lodash": "^4.17.20",
    "moment-timezone": "^0.5.28",
    "nodemon": "^2.0.7",
    "react": "17.0.2",
    "react-combine-reducers": "^1.1.1",
    "react-dom": "^16.13.1",
    "react-is": "^16.13.1",
    "react-native": "0.65.1",
    "react-native-actionsheet": "^2.4.2",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-camera": "^4.2.1",
    "react-native-camera-hooks": "^0.5.2",
    "react-native-confetti-cannon": "^1.5.1",
    "react-native-device-info": "^8.0.2",
    "react-native-dotenv": "^2.5.3",
    "react-native-fs": "^2.17.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-geolocation-service": "5.1.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-image-picker": "^3.2.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-mail": "^6.1.0",
    "react-native-maps": "0.27.1",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-mime-types": "^2.3.0",
    "react-native-open-maps": "^0.3.5",
    "react-native-pager-view": "^5.4.7",
    "react-native-paper": "^4.2.0",
    "react-native-pdf": "^6.3.0",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.13.1",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-shimmer-placeholder": "^2.0.7",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^7.1.0",
    "react-native-video": "^5.1.1",
    "react-native-webview": "^11.2.5",
    "react-redux": "^7.2.2",
    "react-use-websocket": "^2.9.1",
    "reactotron-react-native": "^5.0.0",
    "realm": "^10.11.0",
    "redux-logger": "^3.0.6",
    "rn-fetch-blob": "^0.12.0",
    "styled-components": "^5.2.0",
    "ts-invariant": "^0.4.4",
    "tsc": "^2.0.3",
    "tslib": "^2.0.2",
    "typescript": "^4.0.2",
    "warning": "^4.0.3",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-actions": "^5.3",
    "@storybook/addon-knobs": "^5.3",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.23",
    "@storybook/react-native": "^5.3.23",
    "@storybook/react-native-server": "^5.3.23",
    "@testing-library/react-native": "^7.2.0",
    "@types/": "react-native-cookies/cookies",
    "@types/flat": "^5.0.1",
    "@types/jest": "^26.0.10",
    "@types/lodash": "^4.14.168",
    "@types/moment-timezone": "^0.5.30",
    "@types/node": "^14.6.0",
    "@types/react": "^16.9.46",
    "@types/react-combine-reducers": "^1.0.0",
    "@types/react-dom": "^16.9.8",
    "@types/react-native": "^0.63.9",
    "@types/react-native-maps": "^0.24.1",
    "@types/react-native-vector-icons": "^6.4.6",
    "@types/react-redux": "^7.1.16",
    "@types/react-test-renderer": "^16.9.3",
    "@types/redux-logger": "^3.0.8",
    "@types/styled-components": "^5.1.7",
    "@types/styled-components-react-native": "^5.1.1",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^3.10.0",
    "@typescript-eslint/parser": "^3.10.0",
    "apollo-server-express": "^3.4.0",
    "babel-jest": "^26.2.2",
    "babel-loader": "^8.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "detox": "^17.14.5",
    "eslint": "^7.7.0",
    "eslint-config-prettier": "^8.3.0",
    "express": "^4.17.1",
    "husky": "^5.0.9",
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "metro-react-native-babel-preset": "^0.61.0",
    "mock-apollo-client": "^1.2.0",
    "prettier-eslint-cli": "^5.0.0",
    "react-native-codegen": "^0.0.8",
    "react-native-storybook-loader": "^2.0.2",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "16.13.1",
    "redux-mock-store": "^1.5.4",
    "typescript-styled-plugin": "^0.18.1"
  },
  "jest": {
    "preset": "react-native",
    "moduleNameMapper": {
      "^.+\\.(css|less|scss)$": "identity-obj-proxy"
    },
    "transformIgnorePatterns": []
  },
  "resolutions": {
    "styled-components": "^5"
  }
}
```
not quite sure if it helps

**Comment by tomduncalf** [comment]
Could you open your project's `.xcworkspace` in Xcode and check if you have "RealmJS" in Pods > Development Pods?

![image](https://user-images.githubusercontent.com/5458070/147342486-ac5eb92b-959e-4992-888a-0022296d4401.png)

and if you select "Pods" in the left hand menu, do you see "RealmJS" in the list of targets (left hand list in the center pane)?

![image](https://user-images.githubusercontent.com/5458070/147342645-d40495c7-d139-4734-b641-b1459351c381.png)

Could you also try doing a search in your Xcode workspace for "realmjs" and screenshot the results? Mine looks like:

![image](https://user-images.githubusercontent.com/5458070/147342764-5f01aba0-e9bf-48d7-bdd5-f1f6f17a3f4e.png)
![image](https://user-images.githubusercontent.com/5458070/147342778-146bb0e9-f2ce-4b3b-a894-2f77ff2d4541.png)

I am thinking that something is going wrong either during the pod installation process, or in your project setup.

If you'd rather share your repo privately with me, I'd be happy to take a look, but I understand that that might not be possible.

**Comment by skyforeverRivian** [comment]
@tomduncalf Hi, first of all, I thank you for your quick response in this holiday season, appreciate it
<img width="1527" alt="Screen Shot 2021-12-24 at 10 22 47 AM" src="https://user-images.githubusercontent.com/82187941/147368702-181a27c1-34c4-4307-adb5-607c7f9dbb5b.png">
<img width="1300" alt="Screen Shot 2021-12-24 at 10 24 03 AM" src="https://user-images.githubusercontent.com/82187941/147368705-05acc199-a2c6-44e3-92aa-6f0213b6d1fa.png">
.
please see attached above, I believe I have everything like what you do in my local; yeah, probably, I cannot share the project to you; however, I can show you how it looks like in front of you through share screen if we can zoom or something, what do you think?

**Comment by skyforeverRivian** [comment]
@tomduncalf I think it could be something to do with realm podspec, cause I tried https://github.com/realm/realm-js/issues/3675, even realm ```jsc_init.h``` cannot be found correctly; do you guys have any kind of backlist which would have some conflict with realm?

**Comment by skyforeverRivian** [comment]
@tomduncalf I think I find out the root cause; However, I am not quite sure if it is realm or cocoapod; the problem is resolved when ```${PODS_XCFRAMEWORKS_BUILD_DIR}/RealmJS``` manually added under library search paths from xcode. 
<img width="1050" alt="Screen Shot 2021-12-26 at 10 29 19 PM" src="https://user-images.githubusercontent.com/82187941/147442122-91a66dda-bf8f-417a-8fea-7e73704c24f2.png">
However, it suppose to be auto added through pod install, right? could you enlighten us more about it when you have any chance, thank you.

**Comment by takameyer** [comment]
@skyforeverRivian One thing that catches my eye in the Podfile is `useFrameworks!`.  Can you try it without that part?  It's possible that is causing some sort of conflict.

**Comment by takameyer** [comment]
@skyforeverRivian In any case, Realm should work without having to mess with the xcode build configuration.  I would suggest trying to keep these parts of your project as close to the React Native template as possible.  My gut feeling is that something in your Podfile is causing a conflict.  Try using the [original template podfile](https://github.com/facebook/react-native/blob/0.65-stable/template/ios/Podfile), making modifications based on your project context (ie, project name, etc).

**Comment by skyforeverRivian** [comment]
@takameyer I think @tomduncalf put our podfile in that sample project already(https://github.com/tomduncalf/issue4171/blob/main/ios/Podfile), I don't think it is because of ```useFrameworks!```. probably, we can not do like what you suggested, because we have several sub-packages under main one; however, I did try the solution like what you suggestion last week, it gave us the same error.

**Comment by takameyer** [comment]
@skyforeverRivian Ah ok, shame that didn't work.  Are you by chance building with an M1?

**Comment by skyforeverRivian** [comment]
@takameyer sorry, unfortunately, all of our engineers plus our build machines are using intel-based mac

**Comment by takameyer** [comment]
@skyforeverRivian Ok, then just to rule this out, can you run these commands in your project directory and try again?
```
rm -rf ios/Pods
rm ios/Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData
npx pod-install
```

**Comment by skyforeverRivian** [comment]
@takameyer I did, every single time; actually, my clean is more than that

**Comment by takameyer** [comment]
@skyforeverRivian Strange.  Then I have some followup questions:
* Does https://github.com/tomduncalf/issue4171 build on your machine?
* Can you send us your `package.json`?
* Have you made any significant changes to your `project.pbxproj`, compared to the original provided by the React Native template?

**Comment by skyforeverRivian** [comment]
@takameyer 
- yeah, that sample project works in our local
- sorry, probably, i cannot share that package.json file to you guys; however, I did copy our package.json file to that sample project and clean and reinstall, it can build everything successfully
- not too much, but some bridging stuff

**Comment by tomduncalf** [comment]
> I think I find out the root cause; However, I am not quite sure if it is realm or cocoapod; the problem is resolved when ${PODS_XCFRAMEWORKS_BUILD_DIR}/RealmJS manually added under library search paths from xcode.

> However, it suppose to be auto added or be parts of `${inherited}` through pod install, right? could you enlighten us more detail about it when you have any chance, thank you.

This is a good observation, thanks – I'm not sure what might be going wrong for this not to be added to your project, but I will investigate and see if I can find out more. 

Is adding the search path manually a suitable workaround for the moment?

**Comment by tomduncalf** [comment]
I believe this line: https://github.com/realm/realm-js/blob/master/RealmJS.podspec#L66 in our podspec should result in the library search path being added.

As an experiment, what happens if you strip your `package.json` down to the bare minimum (basically React Native + Realm, something like https://github.com/realm/realm-js/blob/master/templates/react-native-template-realm-ts/template/package.json) and then do a full clean and `npm install`, `pod install`? 

Obviously your project will not work any more, but does `"${PODS_XCFRAMEWORKS_BUILD_DIR}/RealmJS"` appear in your `xcworkspace`'s library search paths? I'm wondering if there could be some unintended interaction with another dependency, which results in our library search path entry being removed/overwritten.

**Comment by skyforeverRivian** [comment]
@tomduncalf I am not quite sure which dependency in our project does removed / overwritten; somehow, the solution I find out is our current best work around

**Comment by tomduncalf** [comment]
Hey @skyforeverRivian, cool, I think the only way to proceed from here would be to try using a "clean" `package.json` and see if the problem still occurs as I suggested. If you're happy to use your workaround instead then I will close this issue.

**Comment by skyforeverRivian** [comment]
@tomduncalf we are still looking for the fix / solution from you guys because we find out the same issue with most of build machines (using fastlane). somehow, my work around cannot resolve that problem.

**Comment by tomduncalf** [comment]
That would be expected with Fastlane, as it will be rerunning `pod install` which will overwrite the manually set library search paths. It is possible to programatically modify an Xcode project with e.g. https://github.com/CocoaPods/Xcodeproj so it would be possible create a to run script after `pod install` which corrects your library search paths, but we shouldn't need to do this.

Could you try what I suggested above please?

> As an experiment, what happens if you strip your package.json down to the bare minimum (basically React Native + Realm, something like https://github.com/realm/realm-js/blob/master/templates/react-native-template-realm-ts/template/package.json) and then do a full clean and npm install, pod install?

>Obviously your project will not work any more, but does "${PODS_XCFRAMEWORKS_BUILD_DIR}/RealmJS" appear in your xcworkspace's library search paths? I'm wondering if there could be some unintended interaction with another dependency, which results in our library search path entry being removed/overwritten.

You can probably just take the package.json directly from https://github.com/realm/realm-js/blob/master/templates/react-native-template-realm-ts/template/package.json directly and drop it in your project, then do a clean/`npm install`/`pod install`, then check if `"${PODS_XCFRAMEWORKS_BUILD_DIR}/RealmJS"` appears correctly in the library search paths or not. This will help us work out if it's something else in your `package.json` at fault.

Let me know the results.

**Comment by skyforeverRivian** [comment]
@tomduncalf sure, thank you, let me bring these info to our build team, and see if it helps, will get back to you when I have something.

**Comment by tomduncalf** [comment]
No worries, I'm sure we can get to the bottom of this!

**Comment by skyforeverRivian** [comment]
@tomduncalf meanwhile, we find out the root cause on our build machines, they all are because of cocoapod version; it was 1.10.1; after upgraded to 1.11.0, everything gets to work nicely and correctly.

**Comment by tomduncalf** [comment]
Ah excellent, I'm glad you were able to resolve this issue!
