### ISSUE TITLE
Facing "invalid character issue in string constant" intermittently.

### ISSUE THREAD

**Issue by akhileshagrhari** [realm/realm-js#4172]
### How frequently does the bug occur?

Sometimes

### Description

code written ->
let query = ``pickupMasterCode = '${pickupMasterCode}' AND cityId ='${cityId}' AND hubId='${hubId}'``
query += `` AND pickupLocationCode = "${pickupLocationCode}"``
query += `` AND (jobTransactionId = "${jobTransactionId}" OR jobTransactionId = 0 )``

scheema->

`Pickup.schema = {`
`    name: TABLE_PICKUP,`
`    primaryKey: 'id',`
`    properties: {`
`        id: 'int',`
`        pickupMasterCode: 'string',`
`        referenceNumber: 'string',`
`        companyId: 'int',`
`        cityId: 'int',`
`        hubId: 'int',`
`        userId: 'int',`
`        pickupLocationCode: 'string',`
`        jobTransactionId :{ type: 'int', default: 0 }`
`    }`
`}`

Note- There are other column as well, but writing here only few to avoid lengthy description.

exception -> 

pickupMasterCode = 'shipment_pickup' AND cityId ='7296' AND hubId='97620' AND pickupLocationCode = "NEW_OLYMPIC VILLAGE-2021-12-14_monoh" AND (jobTransactionId = "4293348611" OR jobTransactionId = 0 ):1:119(119): Invalid characters in string constant.

On hitting the same query I'm not getting this error. But still facing this issue production application.

Realm -> 3.6.0
React-native -> 0.63.4

### Stacktrace & log output

```shell
pickupMasterCode = 'shipment_pickup' AND cityId ='7296' AND hubId='97620' AND pickupLocationCode = "NEW_OLYMPIC VILLAGE-2021-12-14_monoh" AND (jobTransactionId = "4293348611" OR jobTransactionId = 0 ):1:119(119): Invalid characters in string constant.
```

### Can you reproduce the bug?

Yes, sometimes

### Version

3.6.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Not known. Will try to get this info if necessary.

### Build environment

Which debugger for React Native: ..

**Comment by tomduncalf** [comment]
Hi,

Is there any more information in the stack trace? Could you provide a bit more context around the code snippet you provided (e.g. show how you are using the `query` you define)? If you'd like to share your code with me (in private if preferred) that would be fine too.

How often can you reproduce this? What is different between the times you can and cannot reproduce it?

I cannot find the string "Invalid characters in string constant" anywhere in the Realm JS code base, so I'm a bit confused as to where this is coming from, so more context would be very helpful.

Thanks,
Tom

**Comment by tomduncalf** [comment]
Hi,

Could you try upgrading to the latest Realm to see if this fixes the issue? I just noticed that the version you are using is over 2 years old.

Thanks,
Tom
