### ISSUE TITLE
Uncaught Error: Can´t use debugger if __DEV__ isn´t true.

### ISSUE THREAD

**Issue by mangkoran** [realm/realm-js#4174]
### How frequently does the bug occur?

All the time

### Description

My app uses `expo-dev-client` as build environment (following https://github.com/realm/realm-js/tree/0b9ddcaa0885b5e392355cfc0dabc181c2326793/templates/expo-template-js).

Whenever I tried to run the app in browser (`› Press w │ open web`), I got `Uncaught Error: Can´t use debugger if __DEV__ isn´t true.`. No error when running the app in Android emulator.

### Stacktrace & log output

```shell
index.js:51 Uncaught Error: Can´t use debugger if __DEV__ isn´t true.
    at getRealmConstructor (index.js:51)
    at Object.<anonymous> (index.js:59)
    at Object../node_modules/realm/lib/index.js (index.js:66)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../App.js (immutable.js:19)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../index.js (index.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.1 (Register.js:66)
    at __webpack_require__ (bootstrap:789)
    at bootstrap:856
    at bootstrap:856
getRealmConstructor @ index.js:51
(anonymous) @ index.js:59
./node_modules/realm/lib/index.js @ index.js:66
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
./App.js @ immutable.js:19
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
./index.js @ index.js:1
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ Register.js:66
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
VM469:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

I will give the source code of my app privately.

1. Prepare the source code
2. Install dependencies using `npm ci` (make sure `npm` is `>=7`)
3. 
### Version

`realm@10.11.0`

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows 11 Pro 22000.376

### Build environment

Which debugger for React Native: not sure, command line(?)

**Comment by tomduncalf** [comment]
Hi,

If I understand correctly, you are trying to run your React Native app which uses RealmJS in a browser? This isn't possible unfortunately, as RealmJS depends on native C++ code for the database core, which can't run in a web browser.

If you want to access Realm data from a web browser, you'll need to use the Web SDK (which does not work offline, so can only access data which is synced to MongoDB Atlas). It has an API which matches the native API as much as possible, so hopefully should not be too difficult to implement: https://docs.mongodb.com/realm/web/.

Thanks,
Tom

**Comment by mangkoran** [comment]
Actually, I only use Realm online (I don't utilize local/offline Realm database). I'll try the Web SDK.

**Comment by tomduncalf** [comment]
I've just tested this out and unfortunately it doesn't seem possible to use Realm Web in React Native out of the box, I get an error `Can't find variable: TextDecoder`. 

I believe you'd need to use RealmJS on the native side, and Realm Web on the web site – perhaps there's some way to do this with conditional imports/requires if you want to share one code base? The way you access data in Realm Web is different too as you need to use GraphQL or the MongoDB API (https://docs.mongodb.com/realm/web/graphql-apollo-react/, https://docs.mongodb.com/realm/web/mongodb/).

I will speak to the team to see if anyone has any other suggestions for using RealmJS with a web target, it's not something we officially support. I'll let you know if we think of anything!

**Comment by mangkoran** [comment]
How if I reopen this issue and then rename the title so it will better reflect my question above?

**Comment by tomduncalf** [comment]
I'll create new issues to track two things and reference this in them:
1. A better error message for this scenario
2. Investigate the possibility of having Realm Web work in React Native

In future we'd love to support WebAssembly so we could run Realm in the browser, but we don't have a timeline for this.

**Comment by tomduncalf** [comment]
@mangkoran I created the two issues linked above to track this. I'm afraid I can't offer any timeline on us resolving them but we will update you if we make any progress here.

**Comment by mangkoran** [comment]
Subscribed to those 2 issues. Hope these will enable more possibilities to implement Realm in various React Native app scenario.
