### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by aldobel** [realm/realm-js#4176]
Hello everyone, as per the subject, my project with this fantastic db is fine on iOS, but on android it crashes after a data entry operation. I use react native 0.64.3 with react 17.0.1. Seeing on Android Studio, it gives me this error: 
```
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4480 (mqt_js), pid 4421 
```
If I need to attach anything else to help, let me know. Thank you all

In addition: I created my project with expo, then expelled it.
Thanks again everyone !!!

**Comment by aldobel** [comment]
Update: I created a project with 
```
npx react-native init myProject
```
and, adding only the Realm library and 2 buttons, the app doesn't crash. Can you help me? otherwise I rewrite the whole app in this new project (I hope for your help). Thank you all

**Comment by takameyer** [comment]
If you are using Expo, make sure to use v44 (recently released). The previous version contains react-native-reanimated v2, which is not compatible with Realm on Android.

**Comment by aldobel** [comment]
Perfect ... react-native-reanimated and expo 43.0.0 was also installed
I have removed react-native-reanimated and upgraded to expo 44.0.0, and now it's fine. Thanks so much

**Comment by kneth** [comment]
> Is Realm still incompatible with react-native-reanimated ?

You can use Realm JS and react-native-reanimated in the same app. The [compatibility matrix](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md) helps you to pick the Realm JS version with your React Native version. I believe react-native-reanimated is compatible with a broader range of React Native versions.

**Comment by h-assefi** [comment]
I downgraded my realm version to 11.3.0. but my app still crashes.
Also, there was no react-native-reanimated compatibility note in compatibility matrix
could you tell me if I should do something else

**Comment by h-assefi** [comment]
any other suggestion ?
@takameyer @kneth

**Comment by kneth** [comment]
@h-assefi Please create a new issue with all information (including your dependencies).
