### ISSUE TITLE
Fix the type of PropertyType

### ISSUE THREAD

**Issue by kaancembertas** [realm/realm-js#4181]
Hi!  
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/realm/types/index.d.ts b/node_modules/realm/types/index.d.ts
index b6b205e..3ed2a6e 100644
--- a/node_modules/realm/types/index.d.ts
+++ b/node_modules/realm/types/index.d.ts
@@ -36,7 +36,7 @@ declare namespace Realm {
      * PropertyType
      * @see { @link https://realm.io/docs/javascript/latest/api/Realm.html#~PropertyType }
      */
-    type PropertyType = string | 'bool' | 'int' | 'float' | 'double' | 'decimal128' | 'objectId' | 'string' | 'data' | 'date' | 'list' | 'linkingObjects';
+    type PropertyType = 'bool' | 'int' | 'float' | 'double' | 'decimal128' | 'objectId' | 'string' | 'data' | 'date' | 'list' | 'linkingObjects';
 
     /**
      * ObjectSchemaProperty
```

**Comment by fronck** [comment]
Hi @kaancembertas .
Thanks for the patch.  Have you reported an issue that you ran into that this patch fixed?

**Comment by takameyer** [comment]
@kaancembertas I also noticed this today.  This would definitely help TypeScript developers when they are defining their schemas, since it restricts `type` to only valid strings.  I'll get this added to our "breaking changes" log and will hopefully have it included in our next major release.

**Comment by takameyer** [comment]
@kaancembertas Unfortunately, in practice, this change does not allow the possibility to set a property to a linked object:
```
const schema: Realm.ObjectSchema = {
  name: "Task",
  properties: {
    owner: "User" // This would show an error
  }
}
```
I do however, understand how great it would be for typescript to be able to derive the realm datatypes when adding properties to a schema (and also yell when it's wrong).  We are working on developing a way to use Realm without defining a schema, where the data types are derived either from a class or some sort of generator function.  

That being said, I am going to close this issue.  Keep an eye out on future versions, where we are going to take a deeper look into how models in Realm could be easier to define.
