### ISSUE TITLE
Opening multiple realms with @realm/react

### ISSUE THREAD

**Issue by lkoehl** [realm/realm-js#4182]
### How frequently does the bug occur?

All the time

### Description

My db includes user related data with a user related `partitionValue`, and public data with a different `partitionValue`.
As I found out the recommended way of dealing with this is to open two separate Realms each with a corresponding config.
Recently I am experimenting with the @realm/react hooks and I am not able to transfer my code.

My idea was to create two different contexts and access them accordingly.
Accessing the two contexts brings up a promise rejection because the same realm gets opened twice with different schemas.

### Stacktrace & log output

```shell
Possible Unhandled Promise Rejection (id: 11):
Error: Realm at path '/my/path' already opened on current thread with different schema.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```
const PublicRealmContext = createRealmContext({
  schema: [TaskPublic],
});

const PrivateRealmContext = createRealmContext({
  schema: [TaskPrivat],
});

export {PublicRealmContext, PrivateRealmContext};
``` 

And providing the context in my App.js.
```
import {PublicRealmContext, PrivateRealmContext} from './src/models';

const {RealmProvider: PublicRealmProvider} = PublicRealmContext;
const {RealmProvider: PrivateRealmProvider} = PrivateRealmContext;

const App = () => {
  return (
    <PublicRealmProvider sync={{user, partitionValue: 'PUBLIC'}}>
      <PrivateRealmProvider sync={{user, partitionValue: user.id}}>
        <MyApp />
      </PrivateRealmProvider>
    </PublicRealmProvider>
  );
};
```

Accessing the two realms brings up a promise rejection because the same realm gets opened twice with different schemas.

### Version

10.11.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@lkoehl Have you tried providing an explicit path to either `createRealmContext` or the `RealmProvider`?

```typescript
const PrivateRealmContext = createRealmContext({
  schema: [TaskPrivat],
  path: "privateRealm"
});

// --or--

const App () => {
  return(
    <PrivateRealmProvider sync={{user, partitionValue: user.id}} path="privateRealm">
         <MyApp />
     </PrivateRealmProvider>
  )
}
```

**Comment by lkoehl** [comment]
> By default, the name of a realm is `default`. When using multiple realms an explicit name (path) is required so that we can determine which realm file belongs to which realm.
That does make sense, and it worked. Thanks for the quick help @takameyer!
