### ISSUE TITLE
Error: Missing Realm constructor when first installing app (sometimes)

### ISSUE THREAD

**Issue by EricWiener** [realm/realm-js#4186]
### How frequently does the bug occur?

Sometimes

### Description

When first installing the app (either on a physical device or on a reset simulator), I will sometimes get the error:
```
Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
```

However, this clearly isn't an issue with the pod not being installed since the error doesn't appear after reloading the app. The error only appears sometimes and seems to be related to #1128 and #2181

Also please note that I am using RealmSwift 10.20.0 in my app as well. The app used to work well without these crashes on 10.2.0

### Stacktrace & log output
Got the error:
```
Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
```

and then this caused React Native to error out. Nothing else useful.

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps
Unfortunately can't provide repo. I initially shared the repository, but later realized you wouldn't be able to install the node modules since many are from private repos.  

### Version

10.10.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPhone 13 Pro iOS 15.2

**Comment by kraenhansen** [comment]
@EricWiener are you able to reproduce this with a newly initialised React Native template? If not, could you perhaps share what other dependencies your package has and the commands you're running to build and run the app?

**Comment by DtheRock** [comment]
Hi, 

I am facing the same issue with the latest upgrade that I did on Realm. The issue is happening on ios only, and not all the time. It might happen on a new installation, but if the user closes the app and open it again it's working, or when the connection status of the device changes, online-offline. 

Below is my packaje.json and my podfile

{
  "name": "GEP",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@apollo/client": "^3.3.19",
    "@bugsnag/react-native": "^7.11.0",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "appcenter": "4.2.0",
    "appcenter-analytics": "4.2.0",
    "appcenter-crashes": "4.2.0",
    "axios": "^0.21.1",
    "formik": "^2.2.9",
    "graphql": "^15.5.0",
    "https": "^1.0.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "node-fetch": "^2.6.1",
    "ramda": "^0.27.1",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-calendars": "^1.1275.0",
    "react-native-code-push": "^7.0.4",
    "react-native-date-picker": "^3.2.10",
    "react-native-dropdown-picker": "^5.1.21",
    "react-native-encrypted-storage": "^4.0.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-crop-picker": "^0.33.4",
    "react-native-image-picker": "^3.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-modal-datetime-picker": "^10.0.0",
    "react-native-pdf": "6.3.0",
    "react-native-permissions": "^3.2.0",
    "react-native-preference": "2.0.2",
    "react-native-realm": "^0.1.2",
    "react-native-reanimated": "2.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-native-svg": "^12.1.1",
    "realm": "^10.20.0-beta.0",
    "rn-fetch-blob": "^0.12.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/runtime": "^7.12.13",
    "@bugsnag/source-maps": "^2.3.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.31.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

==========PODFILE============

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Facilt' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'FaciltTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'Facilt-tvOS' do
  # Pods for Facilt-tvOS

  target 'Facilt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

**Comment by kneth** [comment]
@DtheRock 

> latest upgrade that I did on Realm

From which version do you upgrade?

**Comment by DtheRock** [comment]
> @DtheRock
> 
> > latest upgrade that I did on Realm
> 
> From which version do you upgrade?

10.2.0

**Comment by kneth** [comment]
Since 10.2.0 doesn't support Hermes, and 10.20.0-beta.0 does (and you have enabled Hermes), you might have to clear any build folders first and rebuild the app from scratch.

**Comment by DtheRock** [comment]
That's correct, I upgraded to the latest version for the Hermes engine. However, I am building through the appcenter, thus the new buildings are cleared from old files, but the issue still remains.

**Comment by kneth** [comment]
@DtheRock Can you provide the log?

**Comment by DtheRock** [comment]
> @DtheRock Can you provide the log?

Sure, but not here, can you please give me an email address?

**Comment by kneth** [comment]
@DtheRock Please use realm-help@mongodb.com.

**Comment by WenLonG12345** [comment]
Hi, I am recently enables hermes in my project and update realm to `10.20.0-beta`. However, when I build my app in Android, this `Missing Realm Constructor` error showed. Any idea why?

**Comment by N3TC4T** [comment]
I'm getting same crash reports.

`hermes_enabled: false`

<details>
  <summary>Crash log</summary>

```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
0  CoreFoundation                 0x91c9c __exceptionPreprocess
1  libobjc.A.dylib                0x14758 objc_exception_throw
2  MYAPP                           0xf3810 RCTFormatError + 166 (RCTAssert.m:166)
3  MYAPP                           0x171c40 -[RCTExceptionsManager reportFatal:stack:exceptionId:suppressRedBox:] + 78 (RCTExceptionsManager.mm:78)
4  MYAPP                           0x17259c -[RCTExceptionsManager reportException:] + 148 (RCTExceptionsManager.mm:148)
5  CoreFoundation                 0x208d0 __invoking___
6  CoreFoundation                 0x3c5a8 -[NSInvocation invoke]
7  CoreFoundation                 0x7080c -[NSInvocation invokeWithTarget:]
8  MYAPP                           0x126328 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
9  MYAPP                           0x12892c facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 183 (RCTNativeModule.mm:183)
10 MYAPP                           0x12855c invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 419 (Optional.h:419)
11 libdispatch.dylib              0x63194 _dispatch_call_block_and_release
12 libdispatch.dylib              0x64198 _dispatch_client_callout
13 libdispatch.dylib              0xa0d4 _dispatch_lane_serial_drain$VARIANT$mp
14 libdispatch.dylib              0xab84 _dispatch_lane_invoke$VARIANT$mp
15 libdispatch.dylib              0x14750 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0x4e84 _pthread_wqthread
17 libsystem_pthread.dylib        0x49f0 start_wqthread
```

</details>

**Comment by takameyer** [comment]
@N3TC4T This can be caused by a number of varying factors.  Can you open a new issue and provide more details? (package.json and podfile)
