### ISSUE TITLE
Hermes + Realm v10.20.0-alpha.2 it's not working on ios

### ISSUE THREAD

**Issue by RalissonMattias** [realm/realm-js#4194]
### Description

When I try to use hermes + realm in alpha version, the application crashes on splash screen generating the following error:
<img width="848" alt="Screen Shot 2022-01-06 at 09 55 43" src="https://user-images.githubusercontent.com/92331757/148411926-7f1afc18-98f4-454f-b0aa-a2797ca07aa0.png">

- React Native: 0.66.4
- Hermes Engine: 0.10.0
- Realm: 10.20.0-alpha.2

### Can you reproduce a bug?

Yes, always

### Reproduction Steps

1.  Enable hermes
2.  Install realm v10.20.0-alpha.2
3. Running on Xcode v13.0

### Version

10.20.0-alpha.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Iphone 12 Pro Max - IOS 15.0

**Comment by YaoHuiJi** [comment]
did you clean the build folder before running?

**Comment by RalissonMattias** [comment]
> did you clean the build folder before running?

Yes I cleaned the folder

**Comment by RalissonMattias** [comment]
The issue has been resolved in the new beta version. Thank you guys

**Comment by kraenhansen** [comment]
@RalissonMattias I hoped that would be the case. Thanks a lot for upgrading and verifying this!
