### ISSUE TITLE
Cannot insert Array of Object

### ISSUE THREAD

**Issue by WenLonG12345** [realm/realm-js#4205]
### How frequently does the bug occur?

All the time

### Description

I have an array of objects to be insert into realmDB, I tried to console.log() it out. It is like this
```
"participants": [[Object], [Object]]

// example json
[{"avatar": "https://static.chativo.io/images/avatar/001.png", "id": "5f56de52987fdb1a15615a52", "kind": "agent", "name": "1wltest4", "presence": "offline", "seen_at": "2022-01-10T10:18:49.432Z", "seen_count": 369, "visible": true}, {"avatar": "/api/v2/file/c4d8bhvt6p4e6328o8dg/IMG_20210620_115523.jpg", "id": "5f56de52987fdb1a15615a55", "kind": "agent", "name": "wltest7", "presence": "offline", "seen_at": "2022-01-10T03:51:05.005Z", "seen_count": 351, "visible": true}]
```

Here is my code
```
const RoomSchema = {
  name: 'Room',
  primaryKey: 'id',
  properties: {
    participants: 'Person[]'
  },
};

const PersonSchema = {
  name: 'Person',
  properties: {
    id: 'string?',
    kind: 'string?',
    name: 'string?',
    seen_count: 'int?',
    avatar: 'string?',
    presence: 'string?',
    visible: 'bool?'
  }
};
```

However, when I try to insert, it keeps throw me error. 
```
TypeError: undefined is not an object (evaluating 'realm.write')
```

Please help if I done anything wrong. 

### Stacktrace & log output

```shell
TypeError: undefined is not an object (evaluating 'realm.write')
```

### Can you reproduce the bug?

Yes, always

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 10

### Build environment

Which debugger for React Native: ..
Flipper

**Comment by fronck** [comment]
@WenLonG12345 I can't reproduce this problem on my end.  Can you provide the code that is failing for you?

FWIW, the following code works for me:
```JavaScript
    const RoomSchema = {
      name: "Room",
      primaryKey: "id",
      properties: {
        id: "string",
        participants: "Person[]",
      },
    };

    const PersonSchema = {
      name: "Person",
      properties: {
        id: "string?",
        kind: "string?",
        name: "string?",
        seen_count: "int?",
        avatar: "string?",
        presence: "string?",
        visible: "bool?",
      },
    };

    const persons = [
      {
        avatar: "https://static.chativo.io/images/avatar/001.png",
        id: "5f56de52987fdb1a15615a52",
        kind: "agent",
        name: "1wltest4",
        presence: "offline",
        seen_at: "2022-01-10T10:18:49.432Z",
        seen_count: 369,
        visible: true,
      },
      {
        avatar: "/api/v2/file/c4d8bhvt6p4e6328o8dg/IMG_20210620_115523.jpg",
        id: "5f56de52987fdb1a15615a55",
        kind: "agent",
        name: "wltest7",
        presence: "offline",
        seen_at: "2022-01-10T03:51:05.005Z",
        seen_count: 351,
        visible: true,
      },
    ];

    const realm = new Realm({ schema: [RoomSchema, PersonSchema] });
    realm.write(() => {
      let roomPeople = realm.create("Room", { id: "theroom", participants: persons });
    });

    let readRoom = realm.objects("Room")[0];
    console.log(JSON.stringify(readRoom.participants));
````

Output:
```JSON
[{"id":"5f56de52987fdb1a15615a52","kind":"agent","name":"1wltest4","seen_count":369,"avatar":"https://static.chativo.io/images/avatar/001.png","presence":"offline","visible":true},{"id":"5f56de52987fdb1a15615a55","kind":"agent","name":"wltest7","seen_count":351,"avatar":"/api/v2/file/c4d8bhvt6p4e6328o8dg/IMG_20210620_115523.jpg","presence":"offline","visible":true}]
```

**Comment by WenLonG12345** [comment]
Oh sorry it is my mistake. The undefined is actually coming from `realm` instance. I was wondering how can I make `realm` as a singleton instance that can be called globally? 

Because if I constantly make new instance (`new Realm()`), the compiler complain that there is existing realm instance.

**Comment by takameyer** [comment]
@WenLonG12345 I recommend trying our hooks library https://www.npmjs.com/package/@realm/react 
This will give you a provider which you can use to retrieve the open `realm` from `context`.

**Comment by WenLonG12345** [comment]
@takameyer is there any documentation about the CRUD operation on this realm hooks library?

**Comment by takameyer** [comment]
@WenLonG12345 we are working on updating the official documentation.  But I can give you a quick overview:
```tsx
const SomeComponent = () => {
  const realm = useRealm();
  const collection = useQuery('Object');  //this is using realm.objects() 
  
  const createSomething = useCallback(() => {
    realm.write(() => {
       realm.create('Object', {foo: 'bar'})
    })
  },[realm])
  
  const updateSomething = useCallback(() => {
    realm.write(() => {
      collection[0].foo = 'buz'
    })
  },[realm, collection])
  
  const deleteSomething = useCallback(() => {
    realm.write(() => {
      realm.delete(collection[0])
    })
  },[realm, collection])
  
  return (
    <>
      {
        collection.map((item) => {
          return item.foo
        })
      }
    </>
  )
}
```

**Comment by WenLonG12345** [comment]
Thanks for the overview. But want to ask it this official realm supported hooks library? and will be maintained by mongoDB team?

**Comment by takameyer** [comment]
@WenLonG12345 Yes, it is an officially supported library.  The source code is in the `realm-js` library under `packages/realm-react`

**Comment by WenLonG12345** [comment]
Ok thanks!
I forget to ask how about the listener? is it included in this hooks library as well?

**Comment by takameyer** [comment]
@WenLonG12345 You can add a listener directly on the result of `useQuery`.  I would advise wrapping that in a `useEffect`, in order to remove listeners on teardown.
```tsx
const collection = useQuery('Object')

useEffect(() => {
  const listenerCallback = () => { /** do stuff **/ }
  collection.addListener(listenerCallback)
  return () => collection.removeListener(listenerCallback)
},[collection])
```

**Comment by WenLonG12345** [comment]
Great! Looking forward to see all the documentation!

**Comment by WenLonG12345** [comment]
I got question regarding to

**Comment by fronck** [comment]
@anastely The "Migration is required" error indicates that the schema in the database you're trying to work with doesn't match the schema you're currently using.
As long as you're working with a test dataset, try deleting all the files associated with the Realm, or specifying a `path` component in the config when opening a new Realm (e.g., `Realm({path: "new_file.realm", schema: [GroupsSchema, ProductSchema]})`.

**Comment by takameyer** [comment]
@WenLonG12345 If you really need to access the realm outside of a component, then you can create a new instance with the same configuration.  
```
const realm = await Realm.open(sharedConfig);
```

**Comment by WenLonG12345** [comment]
> @WenLonG12345 If you really need to access the realm outside of a component, then you can create a new instance with the same configuration.
> 
> ```
> const realm = await Realm.open(sharedConfig);
> ```

wont the realm created duplicate instance?

**Comment by takameyer** [comment]
@WenLonG12345 No, it behaves like a singleton.  But be careful about `realm.close()` as this will close all instances.

**Comment by WenLonG12345** [comment]
If I am using the `useRealm()` hooks,  there is no needed for `realm.close()`? while if I am accessing realm outside of a component, `realm.close()` is needed? I am confused on this

**Comment by takameyer** [comment]
@WenLonG12345 if you are using `useRealm` and the `RealmProvider` you will not need to call `realm.close` in any case.  That happens automatically.

**Comment by takameyer** [comment]
Closing this issue as the original problem has been addressed.  Please open new issue if you have experience any other problems.
