### ISSUE TITLE
download-realm script is using removed variable

### ISSUE THREAD

**Issue by zmefz** [realm/realm-js#4206]
### How frequently does the bug occur?

All the time

### Description

`./scripts/download-realm` script is using `REALM_SYNC_VERSION` variable from `./dependencies.list` which was removed at [Upgrade to Realm Core v10.5.6 ](https://github.com/realm/realm-js/commit/708f1f239debea47e32cd8a4d8a217793dc752f2). This issue leads to an error during the script execution

### Stacktrace & log output

```shell
$ node node_modules/realm/scripts/download-realm.js ios --sync
Resolved requirements: {
  SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-undefined.tar.gz',
  SYNC_ARCHIVE_ROOT: 'core'
}
Resolved options: { platform: 'ios', sync: true }
No lockfile found at the target /Users/yauheni.saihak/Projects/platform-mobile-app/node_modules/realm/vendor/realm-ios, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-undefined.tar.gz
Error: Error downloading https://static.realm.io/downloads/sync/realm-sync-cocoa-undefined.tar.gz - received status 404 Not Found
    at /Users/yauheni.saihak/Projects/platform-mobile-app/node_modules/realm/scripts/download-realm.js:100:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Execute `scripts/download-realm.js ios --sync`

### Version

^10.5.6

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

mac

### Build environment

not related to the issue

### Cocoapods version

not related to the issue

**Comment by kneth** [comment]
In version [10.3.0-rc.1](https://github.com/realm/realm-js/blob/master/CHANGELOG.md#1030-rc1-release-notes-2021-3-19) we changed how we build Realm JS, but we forgot to remove `scripts/download-realm.js` (thank you for reporting).

The script has been never been intended to be called manually. If you which to build Realm JS from source, `npm install --build-from-source realm` is one option. You can also clone the repository.

The change in our build system was a consequence of open sourcing our [sync client](https://github.com/realm/realm-core/tree/master/src/realm/sync).
