### ISSUE TITLE
Invalid json with app.emailPasswordAuth.sendResetPasswordEmail({email})

### ISSUE THREAD

**Issue by mednche** [realm/realm-js#4216]
### How frequently does the bug occur?

All the time

### Description

Running ...

```
const email = "joe.jasper@example.com"
await app.emailPasswordAuth.sendResetPasswordEmail({ email });
```

...  as per the Realm Web SDK [docs](https://docs.mongodb.com/realm/web/manage-email-password-users/#reset-a-user-s-password) but getting `Error: Request failed (POST https://eu-west-1.aws.stitch.mongodb.com/api/client/v2.0/app/{myAppID}/auth/providers/local-userpass/reset/call): invalid json (status 400)`.

The same thing happens if I try `app.emailPasswordAuth.callResetPasswordFunction({ email, password }, args);` instead.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```

import * as Realm from "realm-web";

export default function Account() {

    const app = new Realm.App(myAppId)
    
    async function resetPassword() {
    
        const email = "joe.jasper@example.com"
        await app.emailPasswordAuth.sendResetPasswordEmail({ email });  
            
    }

    return (
        <>
            <button type="submit"
                onClick={ () => resetPassword()}>
                Send reset password email
            </button>
         
        </>
    )
}
```

### Version

realm-web@1.3.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS localhost

### Build environment

Node.js v15.2.1

**Comment by mednche** [comment]
It looks like my issues was due to an outdated version of realm-web (`realm-web@1.3.0`). I've upgraded to `realm-web@1.5.1` and it now works. Closing this!

**Comment by alinpha** [comment]
I was using the latest from _https://unpkg.com/realm-web/dist/bundle.iife.js_ and it gave me the same error. 
After I specified a version _https://unpkg.com/realm-web@1.7.1/dist/bundle.iife.js_ it went through successfully.
