### ISSUE TITLE
realm.object() return empty object

### ISSUE THREAD

**Issue by yasfdany** [realm/realm-js#4232]
### Description
I use `Realm 10.11.0`, I create a function for saving bookmark to realm database, but every time I get all data using realm.objects() it only return empty object {}

### Expected Results
It should return the list of objects stored in the realm database.

### Actual Results
only return list of empty object [{} , {}]

package.json
```
"realm": "^10.11.0"
"react": "17.0.2"
"react-native": "0.66.4"
```

realmClient.tsx
```
const realmClient = new Realm({
    path: "database",
    schema: [
        MovieBookmarkSchema,
    ],
    schemaVersion: 1
})

export default realmClient
```

MovieBookmarkSchema.tsx
```
let _MovieBookmarkSchema

_MovieBookmarkSchema = {
    name: "MovieBookmarks",
    properties: {
        adult: "bool?",
        backdrop_path: "string?",
        genre_ids: "int?[]",
        id: "int?",
        original_language: "string?",
        original_title: "string?",
        overview: "string?",
        popularity: "int?",
        poster_path: "string?",
        release_date: "string?",
        title: "string?",
        video: "bool?",
        vote_average: "int?",
        vote_count: "int?",
    },
    primaryKey: "id",
}

export const MovieBookmarkSchema = _MovieBookmarkSchema
```

Function call
```
const bookmarks = realmClient.objects("MovieBookmarks");
console.log(bookmarks[0])
```

I tried accessing the property directly but it only return undefined
`console.log(bookmarks[0].id)`

I already tried the solution from [https://stackoverflow.com/questions/61116210/realm-objects-return-empty-objects-on-react-native](this question) the virtual object kinda thing, but it just lead me to another error

I tried the encode decode object method
```
const bookmarks = realmClient.objects("MovieBookmarks");
console.log(JSON.parse(JSON.stringify(bookmarks)))
```

and this error happen
`TypeError: item.toJSON is not a function. (In 'item.toJSON(index.toString(), cache)', 'item.toJSON' is undefined)`

**Comment by KhangNguyen136** [comment]
I had the same problem on Android, but IOS works fine.

**Comment by yasfdany** [comment]
@KhangNguyen136 yes mee too, I encounter the problem in Android

**Comment by kneth** [comment]
@KhangNguyen136 @yasfdany Thank you for reporting.

Can I ask you to see what `realm.objects("MovieBookmarks").length` is?

Do you see the error message `TypeError: item.toJSON is not a function.` only on Android when you do `console.log(JSON.parse(JSON.stringify(bookmarks)))`?

**Comment by yasfdany** [comment]
@kneth Thank you for replying

When I run `realm.objects("MovieBookmarks").length` it returns the length of the data, in my case, it's `2`

I'm only testing it on Android, so I'm not sure it happens on iOS too

**Comment by takameyer** [comment]
@yasfdany are you using `react-native-reanimated` v2?  This symptom lines up with conflicts our current latest version has with said module.

**Comment by yasfdany** [comment]
@takameyer yes, I already try to lower the version of react-native-reanimated to v1.x.x but the problem still persist

**Comment by yasfdany** [comment]
@takameyer  I encounter this problem after install and enable realm version of hermes

![image](https://user-images.githubusercontent.com/31397565/150260705-23ad45bf-2e9d-4c47-827f-7e394d9dcff6.png)

**Comment by yasfdany** [comment]
@takameyer Remove reanimated package work for me

**Comment by takameyer** [comment]
@yasfdany I just made a project using `realm@hermes` and `react-native-reanimated@2.3.1` without any problems.  Also tested that it works with and without enabling `hermes`.
If you would like to use `react-native-reanimated`, just follow the [installation guide](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation) and make sure to do a clean build in android and reinstall pods in ios.  Also, it might be necessary to clear your bundler cache using `npx react-native start --reset-cache`

**Comment by yasfdany** [comment]
@takameyer okay I will stick to removing the reanimated library solution for now, cuz I don't really need it in the future.

So, yeah thank you so much, I will close this issue

**Comment by manarfalah** [comment]
@takameyer 
after installing  realm@hermes problem was solved in android, but now my build in iOS is failing in realmjs: 
may be you can help with this ? 
# #![image](https://user-images.githubusercontent.com/6088761/150328212-466cb079-6f74-4557-9aec-6d2d5d657485.png)

**Comment by takameyer** [comment]
@manarfalah did you reinstall your pods?  `npx pod-install`

**Comment by manarfalah** [comment]
@takameyer Yes I did, tried also to remove pods and podfile.lock and install again nothing is fixing it.

**Comment by takameyer** [comment]
@manarfalah What version of React Native are you using?  This only works with 0.66.0 and later.

**Comment by manarfalah** [comment]
@takameyer Using react native 66.4

**Comment by takameyer** [comment]
@manarfalah ok, then perhaps clearing your derived data and doing a clean build can help:
`rm -rf ~/Library/Developer/Xcode/DerivedData`

**Comment by manarfalah** [comment]
@takameyer I tried also removing DerivedData and it keeps failing, this is another view of the error when clicking on in Xcode: 

![Screen Shot 2022-01-20 at 13 39 35](https://user-images.githubusercontent.com/6088761/150331964-a6d76aea-0275-4ae2-833b-a588eaa6c809.png)

**Comment by takameyer** [comment]
@manarfalah we will have to take a look into it then.  Can you please open a new issue and provide as many relevant details as possible? ( such as Error message, Podfile, package.json. ). Thanks 😃

**Comment by manarfalah** [comment]
@takameyer  Ok just for your information, I installed realm beta version and I forgot about it, moving it back to 10.11.0 version fixed the issue ! thanks a lot for trying to help :)

**Comment by manarfalah** [comment]
@takameyer actually running npm install realm@hermes did the upgrade of realm version to ^10.20.0-beta.0, and that what is causing the fail on iOS, getting it back to 10.11.0 caused the issue described above to come back, which is realm.object() return empty object. any suggestion :( ?

**Comment by takameyer** [comment]
@manarfalah I need more information.  10.11.0 issue is caused by having `react-native-reanimated` installed.  The `hermes` version should fix that, but it seems for some reason it's not compiling correctly in Xcode.  In order to look into that, I need to see the `Podfile` and the `package.json`.  Preferably in a new issue.

**Comment by manarfalah** [comment]
@takameyer new issue was opened  #4239, you can see all information there, thanks !
