### ISSUE TITLE
Cannot run the typescript example with Hermes enabled

### ISSUE THREAD

**Issue by lamhtf** [realm/realm-js#4233]
### Description

After getting this from git
npx react-native init TsExample --template @realm/react-native-template-ts

I tried to enable the hermes and do pod install

but I am not able to run the app in iOS simulator with Hermes enabled (as I was trying to use Flipper for Realm.Object debug instead of Chrome)

I have tried to run in 2 diff mac including 1 with intel CPU 2017 and 1 with M1 Pro 2021 but still have the same error and cannot start in the Simulator.

iOS: 15
MacOS: 12.1
XCode: 13.2.1
Error: RealmReact :: EXC_BAD_ACCESS
 
<img width="755" alt="Screenshot 2022-01-19 at 9 45 36 AM" src="https://user-images.githubusercontent.com/70745239/150067381-e9116162-3aae-4aa5-9383-d6ccbb206c6c.png">

 

### Can you reproduce a bug?

Yes, always

### Version

10.11.0

### Platform OS and version(s)

iOS 15

**Comment by takameyer** [comment]
@lamhtf our latest release doesn't have Hermes support yet.  We do have a beta release that you can use and are grateful for any feedback or issues you find with it.  
`npm install realm@10.20.0-beta.0`
