### ISSUE TITLE
Issue on publish with @google-cloud/pubsub library 

### ISSUE THREAD

**Issue by tonythomas01** [realm/realm-js#4245]
### How frequently does the bug occur?

All the time

### Description

I have a function that publishes a JSON to gcloud pub-sub. I could install the dependency “@google-cloud/pubsub” without any issues. However, on the actual publish command, GCP returns me an error message which tells me that the data was not POSTed correctly from realm. 

```
 "Error: 3 INVALID_ARGUMENT: Invalid resource name given (name=\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information."
``` 

The code works just as fine when run locally, though.  Code that was used is posted below. 

### Stacktrace & log output

```shell
async function publishMessage(pubsubPayload, GCPCredentials) {
    const {PubSub} = require('@google-cloud/pubsub');
    const config = {
        "projectId": "my-gcp-project-id",
        "credentials": GCPCredentials
    };
    const pubSubClient = new PubSub(config);
    const topicName = "projects/my-gcp-project/topics/my-topic-name";
    
    try {
        const dataBuffer = Buffer.from(JSON.stringify(pubsubPayload));
        const messageId = await pubSubClient.topic(topicName).publish(dataBuffer);
        console.log(`Message ${messageId} published.`);
    } catch (error) {
        console.error(`Received error while publishing: ${error.message}`);
        console.log(error);
    }
}


exports = function(arg){
  const pubsubPayload = {
      "event": "profile_updated"
  };
  const GCPCredentials =  context.values.get('gcp-auth-credentials');
  publishMessage(pubsubPayload, GCPCredentials);
  return true;
};
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Run the code above on Realm Functions 

### Version

unknown

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

unknown

### Build environment

Which debugger for React Native: ..

**Comment by tonythomas01** [comment]
Posted also here: https://www.mongodb.com/community/forums/t/publish-to-gcloud-pubsub-fails-with-a-decoding-fail-error-works-locally/143458

**Comment by kneth** [comment]
This is the repository for Realm Web and Realm JavaScript while you are asking a question about [Realm Functions](https://docs.mongodb.com/realm/functions/). I will locate an engineer who can answer your forum question, and I will close this issue.
