### ISSUE TITLE
Move realm data file from document directory to library directory

### ISSUE THREAD

**Issue by lincdh** [realm/realm-js#4246]
### Problem

On iOS when an app enables document browsers which make the iOS default file manager `Files` to show a folder of the app so users can access the app document directory sandboxed data.

Realm also generates it's data files in that directory so they are visible on Files app and cause confusions that users may delete them which breaks the database and app.

![image](https://user-images.githubusercontent.com/21136244/150732758-912f1ab2-4b26-4999-a520-6ab210959c83.png)

### Solution

Move realm data files to library directory.

### How important is this improvement for you?

Dealbreaker

**Comment by kneth** [comment]
You can change the default path by setting the static property `Realm.defaultPath`. However, it has been to a path which is permitted by iOS.

**Comment by lincdh** [comment]
@kneth Great! Is that supported for react native yet?

**Comment by kneth** [comment]
@lincdh It should be. But it will set the default path + file name. You can also specify the path + file name using the `path` configuration option.

**Comment by lincdh** [comment]
It works when I specify the whole path when only a string like `main.realm` is specified, Realm chooses the Document.

Does it mean Realm checks if the path is not valid then default path will come into play?

**Comment by kneth** [comment]
If the path doesn't begin with either `.` or `/`, `Realm.defaultPath` will be prepended to `path` from the configuration. If `path` is not specified, `default.realm` is used.
