### ISSUE TITLE
Support for arrayFilters updates in the realm-web package

### ISSUE THREAD

**Issue by joellord** [realm/realm-js#4247]
### Problem

As it current is, arrayFilters are not supported by the realm-web npm package. When passing an arrayFilters property in the third argument (`options`) as is expected when using the MongoDB Node.js driver, the following error message shows up.
```
No array filter found for identifier 'element' in path 'submissions.$[element].status'
```
The message hinted that the `arrayFilters` was not sent to the server. Looking at the POST request confirms that only the `upsert` option is passed to the serverless function on Realm. If the `arrayFilters` option is forced to the Realm function `updateOne`, the update works as expected. 

### Solution

PR to follow

**Comment by kneth** [comment]
@joellord I suggest that we keep the conversation in the PR and not here.
