### ISSUE TITLE
Titanium Appcelerator Support

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-js#429]
Added for people to vote and comment on adding support for [Titanium Appcelerator](http://www.appcelerator.com/) after reading the [request on Hacker News](https://news.ycombinator.com/item?id=11671072).

**Comment by developer82** [comment]
Seems like a great idea!

**Comment by juanagu** [comment]
Great idea! 👍

**Comment by mattlanham** [comment]
+1

**Comment by mattlanham** [comment]
+1

**Comment by playmobilman** [comment]
That would be awesome! 👍

**Comment by nuno** [comment]
+1

**Comment by Topener** [comment]
Titanium support would be awesome! +1

**Comment by mcvendrell** [comment]
+1

**Comment by darknos** [comment]
+1

**Comment by nirmaljpatel** [comment]
+1

**Comment by caioiglesias** [comment]
+1. 

PS. Github doesn't support reactions on mobile, sorry.

**Comment by tujoworker** [comment]
+1

**Comment by chmiiller** [comment]
+1

**Comment by nitrag** [comment]
+1

**Comment by HazemKhaled** [comment]
+1

**Comment by AppWerft** [comment]
Awesome idea! But best is a native Solution, not JS

**Comment by AppWerft** [comment]
+1

**Comment by olivierFr** [comment]
Yes, there are many developers of Titanium are waiting realm.io! Including me.

**Comment by minhnc** [comment]
+1
That would be awesome!

**Comment by botmaster** [comment]
+1

**Comment by prashantsaini1** [comment]
Curious to see this in Titanium and wondering why Titanium is not named to get support but Cordova/PhoneGap does 😆

**Comment by nazrdogan** [comment]
+1

**Comment by AppWerft** [comment]
Currently only a Web and and RN implementation is available. It is impossible to build a Tiatnium module via native SDKs because  i.e. in java the app will modified on byte level after after building (gradle plugin). Background: if in java code I write `new Horse()` it cannot work, because there is no a class definition  for `Horse`. This will done in Bytecode. 

Only the maker of real.io can build an SDK, he knows the internas and the protocol.

**Comment by serkansekman** [comment]
+1

**Comment by egemenmede** [comment]
+1

**Comment by smdulgeroglu** [comment]
+!

**Comment by onursinirtas** [comment]
+1

**Comment by roddogy63** [comment]
+1

**Comment by raybelisle** [comment]
+1

**Comment by SquirrelMobile** [comment]
+1

**Comment by jvandijk** [comment]
+1

**Comment by rolfdalhaug** [comment]
+1

**Comment by Topener** [comment]
@bmunkholm The project lives on though, it's handed over to the community.

https://tidev.io
https://github.com/tidev
