### ISSUE TITLE
Hermes branch running JSC on iOS throws `Properties can only be defined on Objects` from `realm/lib/extensions.js`

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#4297]
Trying to upgrade to `10.20.0-beta.1` but it won't even let me start the app on iOS (`10.20.0-alpha.2` worked fine). Note that I'm not using Hermes on iOS (`:hermes_enabled => false`) but I am using it on Android.

I'm getting `Properties can only be defined on Objects` from `realm/lib/extensions.js` on line 364:
```
Object.defineProperties(
      realmConstructor.App.Sync.Subscriptions,
      getOwnPropertyDescriptors(subscriptionsMethods.static),
    );
```

_Originally posted by @cristianoccazinsp in https://github.com/realm/realm-js/issues/3940#issuecomment-1027264594_

**Comment by kneth** [comment]
Partially fixed by #4298

**Comment by juhasuni** [comment]
This bug affects `10.13.0` also, however I only discovered the issue when starting the app using "My Mac" as the target. iOS simulator seems to run fine.

**Comment by kraenhansen** [comment]
We havn't been able to reproduce this yet.

**Comment by cristianoccazinsp** [comment]
Odd, I consistently get the error by just upgrading to beta1 from alpha2 and doing no code changes.

**Comment by takameyer** [comment]
I'll add my obligatory xcode cleanup commands here:
```
rm -rf ios/Pods
rm ios/Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData
npx pod-install
```

**Comment by cristianoccazinsp** [comment]
I did not clear everything, no, just the regular XCode clean.

**Comment by cristianoccazinsp** [comment]
Looks like after doing a cleanup and installing beta2, the issue went away.

**Comment by kraenhansen** [comment]
@cristianoccazinsp thats great news!
Thanks for trying it out and submitting your findings - this is a great help for us!
