### ISSUE TITLE
Subsequent 'change' events not firing.

### ISSUE THREAD

**Issue by joshuapinter** [realm/realm-js#430]
Hi guys, 

I'm using Realm's `ListView` and an event listener to monitor for changes to the data and updating my ListView. 

Oddly, it works fine on the first change to the data (e.g. adding a record or deleting a record) but on subsequent changes the event doesn't seem to fire. 

Here's my setup: 

```js
constructor(props) {
  super(props);

  var dataSource = new ListView.DataSource(
    { rowHasChanged: (r1, r2) => r1 !== r2 } );

  this.state = {
    dataSource: dataSource.cloneWithRows(this.getRecords())
  };

  Realm.addListener('change', () => {
    console.log("Realm Changed!");

    this.setState({
      dataSource: dataSource.cloneWithRows(this.getRecords())
    })
  });
}
```

When I first add (or delete) a record, I see `Realm Changed!` in my console. However, if I add (or delete) a subsequent record, I don't see this console message. 

Any idea why this could be? 

Thanks!

Josh

**Comment by appden** [comment]
@joshuapinter It would be really helpful for me to see a lot more of the code or a reduction that reproduces this if you preferred, you can privately email it to me if you wish.

I have a couple quick comments on what you sent, but I don't think either will resolve your issue:
- The `addListener()` method is on a Realm instance, but it looks like you're calling it on the constructor in the code you provided
- It's better to clone the current `dataSource` so it can find which rows changed from one being displayed, which means doing this instead: `this.state.dataSource.cloneWithRows(...)`

**Comment by joshuapinter** [comment]
@appden Thanks for the reply!

Yeah, it's tricky to get the full picture without more details. 

To answer you two quick comments: 

1) `Realm` is actually a separate file where I require Realm, define the schemes and instantiate the Realm. It then exports the instantiated Realm into the `Realm` variable. So we should be good there. 

2) That makes sense. So would that mean my code would look like this? 

```js
this.setState({
  dataSource: this.state.dataSource.cloneWithRows(this.getRecords())
})
```

**Comment by joshuapinter** [comment]
An additional discovery on the event listener.

My app Routes are laid out like this:

Relationships
-> Relationship
----> Edit Relationship

If I restart the app and edit a Relationship, I get the Realm change event. But if I go back to Relationships and try and edit another Relationship, I no longer get the Realm change event.

However, if I keep editing the same Relationship, without going back to the Relationships scene, I keep getting the Realm change event.

My initial thought is that it has something to do with mounting and unmounting or something. 

I get from the Relationship scene to the Relationships scene by using `popToTop()` on the navigator, since Relationships is the initial route.

Let me know if that helps at all. 

Thanks.

**Comment by appden** [comment]
@joshuapinter 
1. That make total sense
2. Yep, your could should look like that, but it doesn't explain to me why you're not seeing the console log, so I think there's an issue we might need to resolve here.

Regarding your latest comment, I'll give it some thought, but I'm not sure if that helps me narrow it down. You definitely should be using `removeListener` in your React component when it is unmounted because otherwise the `change` listener will try to call `setState` on an unmounted component. Likewise, you probably want `addListener` be called when the component is mounted. That still doesn't explain why you're not seeing the console log though...

**Comment by joshuapinter** [comment]
@appden Right. Thanks. Yeah, I actually had the `removeListener` on the `componentWillUnmount` but removed it to test if that was causing issues. Had no effect.

Let me know what you think. Thanks again. Really appreciate it.

**Comment by appden** [comment]
@joshuapinter I'm not sure I can help narrow this down without seeing more code. Are you sure there are no exceptions being thrown?

**Comment by joshuapinter** [comment]
@appden Definitely no exceptions popping up. And I've even added console logs for all the different lifecycle events for the Relationships component and it doesn't get unmounted or anything. 

I ended up getting around this by using `resetTo` on the `navigator` instead of `popToTop`, but that forces a new instantiation of the Relationships component.

No worries, though, I'll leave this here for now and come back to it when I have more time to debug it. 

Many thanks for your help, really appreciate it. 👍

**Comment by joshuapinter** [comment]
Hey @appden, what should I be doing to try and debug this?

**Comment by appden** [comment]
@joshuapinter if you're sure `removeListener` (or `removeAllListeners`) isn't being called, then the next thing I would wonder about is if the JS context is being reloaded. If so, that listener would implicitly be removed. I didn't think that that React Native Navigator did that, but it's worth double checking. If the JS context is definitely not being removed, then I would confirm this bug also exists in Chrome debugging mode. If so, then it's much easier to use the JS debugger there. I'd be more than happy to help figure this out if I had access to something that demonstrates this issue.

**Comment by ekryski** [comment]
Yes I've also noticed that `removeListener` seems to not work or that events seem to be dispatched at weird times. @joshuapinter and I know each other so we'll work to get a slimmed down example that demonstrates the problem(s).

**Comment by appden** [comment]
Thanks so much @ekryski @joshuapinter!

**Comment by appden** [comment]
@ekryski Just checking in to see if you guys came up with an example that demonstrates these issues? Thanks!

**Comment by joshuapinter** [comment]
@appden Not yet. It's high up on the list, though, it's been nagging at me. :)

**Comment by bmunkholm** [comment]
.

**Comment by alazier** [comment]
Is this still an issue?

**Comment by joshuapinter** [comment]
@alazier As far as I know, yes. We haven't tested against master or anything, though. And haven't gotten around to stubbing a public project to show the issue.

Have you made any changes that may have resolved this?

**Comment by alazier** [comment]
We were never able to reproduce the issue as you described so I'm not really sure. Reading through this again I'm wondering if somehow your code is creating multiple Realm instances through the lifecycle of your app which causes the notification to stop firing after the second instance is created. Have you tried logging in the code which creates your Realm instance to see if this is the case?

**Comment by joshuapinter** [comment]
That definitely could be it. 

Do you have a Best Practices when it comes to creating the Realm instance but including it in future Scenes of a React Native app?

**Comment by appden** [comment]
@joshuapinter I recommend exporting your Realm instance from a module, like we do in the example app (see [here](https://github.com/realm/realm-js/blob/master/examples/ReactExample/components/realm.js)).

There are other decent options, especially if you're dealing with multiple Realms, like passing it down through the context of your React components.

**Comment by joshuapinter** [comment]
@appden I see you're using `export default new Realm(...)` in your `realm.js` file and then using `import realm from './realm'` to import it into your other Components. 

I'm using 
```js
let realm = new Realm(...)

module.exports = realm;
```

And then using `var Realm   = require('./Realm')` in other Components. 

Would this method be incorrectly creating multiple Realm instances? 

I'll try your method and see if I get the same issue in the meantime....

**Comment by joshuapinter** [comment]
Okay, I feel like a bit of a dum dum. On a nested page I was using `Realm.removeAllListeners();` instead of removing just the listener for that page.

I'm having trouble using `removeListener` effectively but I'll create a new issue for that. 

Thanks for all your help. I'm closing this off now.
