### ISSUE TITLE
Android App crash instantly after add Realm + React Navigation Drawer (screens/gesture handler/hermes)

### ISSUE THREAD

**Issue by gabrielporcher** [realm/realm-js#4301]
### How frequently does the bug occur?

All the time

### Description

Hello,

I'm working on a fresh react native project (CLI). So I started adding and configuring React navigation (Stack and Drawer). Also i added React-native gesture handler, react native screens and hermes (because both are dependencies to react navigation). Until here, everything was fine.

After this, I added MongoDB Realm (npm install realm) but then my app started to fail. The app install with build successful, but when I try to open app in emulator it just close instantly, without any errors. The only messaged displayed is this:

![error](https://user-images.githubusercontent.com/44413897/152177325-1bab9d7a-d767-4ff1-be7e-32581c39cf7e.png)

I spent a whole day researching and trying to fix it, but i just couldnt do anything.

So I created a new project and started in reverse way. First, installed and configured Realm, and everything was fine. Then, I added react-navigation stack and still ok. But when I added react native navigation Drawer and configured its dependencies (gesture handler and react native screens, also I had to enable hermes because its a screens must have) the app started to crashes exactly the same as the previous app.

I tried to fix it in so many ways but nothing seems to work. I'm starting to get desperate, because it's been 2 days since I can't do anything in my app :C

In addition, I just cant create a log because my app doesnt even start.

### Stacktrace & log output

```shell
I cant make a log because my app even start.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Add Realm
- Add react navigation/drawer
- Add react-native-gesture-handler
- Add and configure react-native-screens
- enable hermes

### Version

30

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by gabrielporcher** [comment]
I forgot to mention that i had to add react-native-reanimated too for the react-navigation/drawer.
Then I just saw #4176 and looks like Realm isnt compatible with reanimation V2. I'll try to change it to V1 and see what happens next

**Comment by takameyer** [comment]
@gabrielporcher alternatively, you can try our Hermes release branch, which is compatible with reanimated v2:
```
npm install realm@hermes
```
Let us know if that helps!

**Comment by gabrielporcher** [comment]
Hi @takameyer,

Last night I was debuggin the my app dependencies and doing some researches to found the root of the problem, and i found your commentary #3837 .

I tried your Hermes release branch and looks like its working perfectly with reanimated v2.

Thank you!

**Comment by takameyer** [comment]
@gabrielporcher Happy its working for you :)

**Comment by gabrielporcher** [comment]
Hey @takameyer sorry to bother you again, but I'm having a very strange error when I try to save/read data from Realm.

![Screenshot_1643997715](https://user-images.githubusercontent.com/44413897/152579826-4ccc492d-544a-4965-b7d0-ba678a883dc4.png)

Heres my Schema and repository files:

Schema:

```
import Realm from "realm";

const User = {
    name: "User",
    primaryKey: "id",
    properties: {
        id: "string",
        type: "string",
        token: "string",
        refreshToken: "string"
    },
};

const realm = await Realm.open({
    path: "myrealm",
    schema: [User],
});


export default realm;
```
User repository:

```
import realm from './RealmSchema';

const User = {
    saveUser(user) {
        try {
          realm.write(() => {
            realm.create('User', user)
          });
        } catch (error) {
          console.log(error)
        }
      },
};

export default User;
```
I'm sorry if its any import/export error or missing ; or something, but I just cant resolve this problem, so I dont know if its possible to be something wrong with the version that you shared with me

**Comment by gabrielporcher** [comment]
Well, I think that some kind of syntax error, I change my schema and its working now.
Schema now:

```
import Realm from "realm";

const User = {
    name: "User",
    primaryKey: "id",
    properties: {
        id: "string",
        type: "string",
        token: "string",
        refreshToken: "string"
    },
}

export default new Realm({
    schema: [User],
})
```

Now I'm able to save my user, but when I try to read them, i have the very same error than #4119 .

Again, I'm sorry if I'm doing something wrong, I went from Realm 6.1 to 10 in this newer project.

**Comment by ansh** [comment]
@takameyer is [Realm JavaScript v11.0.0-rc.1](https://github.com/realm/realm-js/releases/tag/v11.0.0-rc.1) this version compatible with RN 0.66 and below 0.69? Because, v11.0.0-rc.0 is compatible with those.
