### ISSUE TITLE
IOS app crashed with EXC_BAD_ACCESS in some devices.

### ISSUE THREAD

**Issue by krupalikevadiya** [realm/realm-js#4319]
### How frequently does the bug occur?

Sometimes

### Description

IOS app crashed in some ios devices when terminated app by swiping from device and got below error.
Error : https://prnt.sc/26qhrl9

To resolve this i updated library to latest available version with 10.12.0 and with this version i didn't found crash when i terminated app but when i again open app i got below error.
Error : @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
 node_modules
 
 Can you please suggest me any way to resolve it.

### Can you reproduce the bug?

Yes, sometimes

### Version

10.12.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS with version 15.2.1

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
@krupalikevadiya your screenshot only provide the first frame of the stacktrace, can you expand your left sidebar to reveal all the frames in the stack at the point of crashing? We can see that it happens in `JSC::symbolTableGet` but we can't see what code (of ours) is calling into it.

**Comment by krupalikevadiya** [comment]
Hey @kraenhansen did you mean this https://prnt.sc/26qi1la ?

**Comment by kraenhansen** [comment]
Yep. That helps a lot, can you expand it even further so we we can see the entire symbol name (the one that starts with `realm::js::MixedLink<realm...`)

**Comment by kraenhansen** [comment]
Re-reading your issue description, I realise that you're actually reporting another bug than the one you first saw, sorry about that.

**Comment by krupalikevadiya** [comment]
@kraenhansen wait let me share you exact code when my app crashed in ios.

**Comment by tomduncalf** [comment]
@krupalikevadiya Please can you clarify the exact issues you are seeing? It sounds like two are being reported:

1. With v10.12.0, your app crashes when terminating it
2. With v10.12.0-beta.1, your app will not start with the error: `Error : @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories: node_modules`

Is this correct?

If so, we should focus on debugging the second issue, as v10.12.0 has been superseded by v10.12.0-beta.1.

I would suggest you first try clearing out your `node_modules` and other temporary files which can cause issues with React Native, and restart the packager.

First close any running React Native bundler, then run the following commands from the root of your React Native project:

```
rm -rf node_modules
npm cache clean -f
watchman watch-del-all
rm -rf $TMPDIR/metro*
rm -rf $TMPDIR/react-native*
npm install
rm -rf ios/Pods
rm ios/Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData
npx pod-install
```

Then restart the metro bundler with:

```
npx react-native start --reset-cache
```

And try again.

**Comment by krupalikevadiya** [comment]
@tomduncalf thanks for quick reply.
I tried to resolve my error with version v10.12.0-beta.1 but my app is not even start with this so i removed that version form my app.
Next i tried with version v10.12.0 and with this i didn't get crash of EXC_BAD_ACCESS when terminated but when i again open my app after terminating it is not started and it gives blank white screen.

**Comment by tomduncalf** [comment]
@krupalikevadiya Sorry, I had mixed up my version numbers and thought you were talking about 10.20.0-beta.1. Please ignore my previous message, v10.12.0-beta.1 is no longer relevant as we have released v10.12.0 :) 

Have you tried the above steps to reset your React Native packager and node_modules etc?

**Comment by krupalikevadiya** [comment]
Let me try your suggested way @tomduncalf

**Comment by takameyer** [comment]
Hi @krupalikevadiya, it's been a while since we have heard from you 🙂 .  Did you have any luck with your issue?

**Comment by krupalikevadiya** [comment]
Hey @takameyer issue has been resolved in latest updated version.
