### ISSUE TITLE
Change Realm.App#delete to Realm.App#deleteUserApiKey

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#4322]
Realm.App#delete is a method that removes a user API key from a Realm app.  The method name `delete` is very ambiguous and does not denote its intention.  I believe changing it to the more explicit name `deleteUserApiKey` will remove any ambiguity.

**Comment by kraenhansen** [comment]
This method is not on the `Realm.App` though. It's exposed via the [ApiKeyAuth](https://github.com/realm/realm-js/blob/master/types/auth-providers.d.ts#L269-L274), which is available through a `User#apiKeys`.

Calling it looks like this:

```typescript
app.currentUser.apiKeys.delete(id);
```
