### ISSUE TITLE
Expo Metro iOS: Missing Realm constructor

### ISSUE THREAD

**Issue by mickey-stringer** [realm/realm-js#4332]
### How frequently does the bug occur?

All the time

### Description

I was expecting to be able to run the expo template project on iPhone.

I cloned the [expo-template-js](https://github.com/realm/realm-js/tree/master/templates/expo-template-js), entered the repo, and ran `expo start`. After scanning the QR with my iphone, the iOS bundling completes, but `Error: Missing Realm constructor` is thrown as soon as the app starts running.

I also tried `expo start --dev-client`, as specified in the readme, but when I scan the QR, the iPhone banner says "No usable data found"

### Stacktrace & log output

```shell
iOS Bundling complete 5609ms
iOS Running app on iPhone 11

Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-dev-launcher\build\DevLauncherErrorManager.js:44:19 in errorHandler
at node_modules\expo-dev-launcher\build\DevLauncherErrorManager.js:49:24 in <anonymous>
at node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules\metro-runtime\src\polyfills\require.js:204:6 in guardedLoadModule
at http://192.168.1.240:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:137641:3 in global code
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Clone https://github.com/realm/realm-js/tree/master/templates/expo-template-js
2. Run `expo start`
3. Scan QR with iPhone and run app

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14.8.1 and 15.3.1

### Build environment

Which debugger for React Native: ..
Expo SDK 44.0.0
Expo dev-client 0.8.4
Expo CLI 5.1.1

### Cocoapods version

N/A

**Comment by mickey-stringer** [comment]
Ah, ok that is definitely helpful - I am using Expo Go. 
Thanks for the info, @takameyer

**Comment by Kochiyama** [comment]
> 

I think this information should be on documentation, I've spent a day trying, until I found this issue. Anyway thank you so much!

**Comment by VityaSchel** [comment]
> @mickey-stringer Are you using the Expo Go app? This is not compatible with Realm or the dev-client. In order to use the dev-client, you have to first build it and install it on your phone. The easiest way to do that on device is connect it with usb and build locally: `expo run:ios -d` After doing that, you will have a dev-client on your phone running your app and you should be able to scan future QR codes provided by `expo start`.
> 
> Just for added explanation, the dev-client is like a custom Expo Go App that you build yourself. This allows for adding any third party libraries, such as Realm, to the dev-client. It acts as a foundation to run your React Native JS code on top of it.
> 
> Hope this helps, let us know if you make any progress or run into any other issues.

Wow how am I supposed to develop my app if every change I made requires me to wait 30 minutes for app to build? 😂

**Comment by kneth** [comment]
@VityaSchel You might wish to read https://github.com/reactwg/react-native-new-architecture/discussions/4#discussioncomment-2382960

**Comment by gshawnr** [comment]
Just to clarify with a follow up - if one is developing on a linux machine (and therefore unable to build locally) the only option if using Realm is to use Expo to build the app in the cloud correct?  I can find no other way to do it if I want to test on an ios device. As mentioned above, I have no issue with other apps, only ones where I am using Realm.

**Comment by takameyer** [comment]
> Wow how am I supposed to develop my app if every change I made requires me to wait 30 minutes for app to build? 😂

@VityaSchel You will only need to rebuild the entire app when you add any new native dependencies.  Once you build with the dev client, the application will attempt to connect to your active bundler and will receive any changes to JavaScript remotely.

> the only option if using Realm is to use Expo to build the app in the cloud correct?

@gshawnr Expo is a good option if you don't have Xcode on your machine.  Once you build with the dev client and have the app installed on an iOS device, you will be able to not only test your code, but make changes to the JavaScript and see the changes directly on the device.

> As mentioned above, I have no issue with other apps, only ones where I am using Realm.

What issues are you having?  I see nothing mentioned above.

**Comment by gshawnr** [comment]
@takameyer 
I have the same issue as the OP.  I do not thave Xcode on my machine, so I have used Expo Go to test a few apps on my iphone as well as using an android emulator.  However, when I try to use Expo Go with an app using Realm, I have the same issues as the OP.  I understood your comment from Feb 10th, 2022 that I will not be able to test my Realm app on my iphone since I do not have Xcode (ability to build locally) - I unless I was to use Expo cloud to build the app for me.
