### ISSUE TITLE
React Native UI task queue is not being flushed when async updates come from C++

### ISSUE THREAD

**Issue by tomduncalf** [realm/realm-js#4344]
This seems to be the cause of bugs such as https://github.com/realm/realm-js/issues/2371 and https://github.com/realm/realm-js/issues/2655, and is also affecting our ability to run flexible sync React Native integration tests, as the simulator screen requires "tapping" before the sync Promise resolves.

See https://github.com/realm/realm-js/pull/4389 for description of the issue and fix

**Comment by cristianoccazinsp** [comment]
After upgrading to `10.20.0-beta.5` from beta3, I'm seeing this more often, although not 100% sure it's related.

When running realm queries/writes in an async callback, no timeouts execute until there's some kind of interaction with the UI.
