### ISSUE TITLE
iOS - Can't find variable: globalThis

### ISSUE THREAD

**Issue by cristianoccazinsp** [realm/realm-js#4350]
### Description

Using `10.20.0-alpha.2` (but without actually using Hermes on iOS), reported the above crash for a user right on app startup.

### Stacktrace & log output

```shell
ReferenceError
Can't find variable: globalThis

    node_modules/realm-network-transport/dist/bundle.react-native.es.js:91:43 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    node_modules/realm/lib/extensions.js:60:45 exports
    node_modules/realm/lib/react-native.js:45:24 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    src/db/index.js:8 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    src/App.js:31 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    node_modules/metro-runtime/src/polyfills/require.js:200:45 guardedLoadModule
    index.js:86:29 
    node_modules/regenerator-runtime/runtime.js:63:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:294:30 
    node_modules/regenerator-runtime/runtime.js:63:44 tryCatch
    node_modules/regenerator-runtime/runtime.js:155:28 invoke
    node_modules/regenerator-runtime/runtime.js:165:19 
    node_modules/promise/setimmediate/core.js:37:14 tryCallOne
    node_modules/promise/setimmediate/core.js:123:25 
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:248:17 
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:112:6 _callTimer
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:166:15 _callReactNativeMicrotasksPass
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:418:11 callReactNativeMicrotasks
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:393:11 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:11 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:370:8 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 value
    [native code] value
    [native code] value
```
```


### Can you reproduce a bug?

Not yet

### Reproduction Steps

Regular offline (non sync) usage.

### Version

10.20.0-alpha.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

_No response_

### Platform OS and version(s)

iOS 12.1.1 (iPad Mini 3)

**Comment by kraenhansen** [comment]
Impressive 🙂  I think this is only possible if we load before the runtime globals gets set?

**Comment by cristianoccazinsp** [comment]
I'm amazed as well. I've only seen one user with this issue with an old device, so perhaps a slow start and a race condition?

The user still managed to trigger the issue 4 times, and then probably gave up.

<img width="423" alt="Screen Shot 2022-02-16 at 12 10 36" src="https://user-images.githubusercontent.com/48869228/154294281-c05dc498-e677-4e67-8f66-5df59096f444.png">


The issue also happens right when importing realm:
`import Realm from 'realm';`

Could it be related to `inlineRequires: true` ?

**Comment by fronck** [comment]
@cristianoccazinsp Thanks for reporting -- we'll look into it.  Please let us know if you dig out more information.

**Comment by laxminarayan192** [comment]
do we have solution for this issue?

**Comment by takameyer** [comment]
@laxminarayan192 What version of `jsc-android` were you using before?

**Comment by takameyer** [comment]
@laxminarayan192 you are running an iPad with iOS 12.1.  `globalThis` was added to JSC in iOS 12.2.  Can you update your device?

**Comment by takameyer** [comment]
It appears `globalThis` support was added in iOS version 12.2 (https://github.com/WebKit/WebKit/commit/2b424f0e6003f952845748f82afd9a21dce5538f).  So that would explain why users running on old devices would run into this issue.

**Comment by cristianoccazinsp** [comment]
I'm getting the issue only on iOS. But you are right, these are all old devices. 

<img width="311" alt="Screen Shot 2022-03-02 at 09 33 28" src="https://user-images.githubusercontent.com/48869228/156362394-c9ba733f-acaa-40f8-b5cc-bfba41760a18.png">

**Comment by laxminarayan192** [comment]
> @laxminarayan192 What version of `jsc-android` were you using before? I am a bit confused that updating JSC on android would fix your issue on iOS.

I was using `jsc-android: "241213.1.0"`,

**Comment by takameyer** [comment]
@cristianoccazinsp I created a PR that might solve the issue.  Unfortunately, I do not have a good way to test this.

**Comment by takameyer** [comment]
Although, the ipad mini mentioned above does have the ability to upgrade to 12.5, which would also fix the issue

**Comment by cristianoccazinsp** [comment]
It's not easy to tell users to upgrade their ancient devices :D

**Comment by takameyer** [comment]
@cristianoccazinsp That is true 😆  A fix is on the way.

**Comment by cristianoccazinsp** [comment]
@takameyer @kraenhansen  I seem to be seeing the same crash logs with Realm `10.20.0-beta.4`. Wasn't this resolved? Maybe not released yet?

```
ReferenceError
Can't find variable: globalThis

    node_modules/realm/lib/react-native/index.js:42:25 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    src/db/index.js:8 
```

```
model
iPad Air 2 (iPad5,3)

modelNumber
J81AP

osName
iOS

osVersion
11.2.6
runtimeVersions
{
  "clangVersion": "13.1.6 (clang-1316.0.21.2)",
  "osBuild": "15D100",
  "reactNative": "0.67.4",
  "reactNativeJsEngine": "jsc"
}
```

**Comment by takameyer** [comment]
@cristianoccazinsp I believe this was released with `10.20.0-beta.5`

**Comment by cristianoccazinsp** [comment]
@takameyer we have released a new version using `10.20.0-beta.5`, yet the error still shows.

```
ReferenceError Can't find variable: globalThis 
    node_modules/realm/lib/react-native/index.js:45:32 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    node_modules/realm/lib/index.native.js:20 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    src/db/index.js:8 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    src/App.js:30 
    node_modules/metro-runtime/src/polyfills/require.js:340:6 loadModuleImplementation
    node_modules/metro-runtime/src/polyfills/require.js:200:45 guardedLoadModule
    index.js:128:29 
```

Device: iPhone SE, iOS 12.0

**Comment by tomduncalf** [comment]
I was able to reproduce this on iOS 11, so will investigate further tomorrow.

**Comment by cristianoccazinsp** [comment]
Thanks for the quick review!

**Comment by cristianoccazinsp** [comment]
Not sure if just a coincidence, but beta.5 seems to be having this issue more frequently than beta.4.  After the release, the error is being reported much more frequently.

<img width="853" alt="Screen Shot 2022-06-14 at 09 16 22" src="https://user-images.githubusercontent.com/48869228/173575082-91f8c7fe-5eb7-42cd-8d7a-faeb4150cdac.png">

<img width="1127" alt="Screen Shot 2022-06-14 at 09 16 52" src="https://user-images.githubusercontent.com/48869228/173575091-f1dcb9b6-55ca-49f4-b39c-1957a41bc81e.png">

**Comment by tomduncalf** [comment]
Hey @cristianoccazinsp, I think that's a coincidence, from what I can see this would just not work on iOS 11 (which I tested on) and from the sounds of things 12. I've got a fix in review, so hopefully we can get that into the next Hermes branch release (which is currently blocked on some test issues but we are working to resolve those this week)

**Comment by fronck** [comment]
@cristianoccazinsp We've closed this issue for now.  If the fix merged in the `hermes` branch doesn't work for you, feel free to re-open.

**Comment by cristianoccazinsp** [comment]
@fronck what beta version can this fix be found at?
