### ISSUE TITLE
JS SDK documentation styling broken in Firefox

### ISSUE THREAD

**Issue by liamjones** [realm/realm-js#4359]
### How frequently does the bug occur?

All the time

### Description

![Screenshot 2022-02-18 at 08 55 41](https://user-images.githubusercontent.com/521341/154650292-70e9986a-d533-4da3-ac4b-349803fe94c8.png)

Looks like the issue is the:

```
The stylesheet https://docs.mongodb.com/realm-sdks/js/latest/styles/normalize.css was not loaded because its MIME type, “text/plain”, is not “text/css”.
```

Statements in the console

### Can you reproduce the bug?

Yes, always

### Version

https://docs.mongodb.com/realm-sdks/js/latest/

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 11.6.3 / Firefox Developer Edition 98.0b5

**Comment by tomduncalf** [comment]
Thanks for raising this Liam, I can see it on Chrome too actually. It looks like something went wrong with deploying the documentation, we will investigate!

**Comment by fronck** [comment]
Can confirm on the Firefox side.  We will look into what went wrong.
Thanks for reporting, @liamjones .

**Comment by tomduncalf** [comment]
Hey @liamjones, this should be fixed now. Sorry for the inconvenience. `s3cmd`, which we use to upload the docs to S3, apparently does not set the correct MIME type for CSS by default!
