### ISSUE TITLE
[WEB]: Unable to link anonymous user with new email and password credentials

### ISSUE THREAD

**Issue by 3210jr** [realm/realm-js#4371]
### How frequently does the bug occur?

All the time

### Description

For an anon user that is already logged in, I was expecting the code:
`
const emailPasswordUserCredentials = Realm.Credentials.emailPassword(
  email,
  password
);
await app.currentUser.linkCredentials(emailPasswordUserCredentials);
`
to work and turn the anon user into a use with the above credentials.

What actually happens is that I get a 401 error in the console
```
POST https://eu-central-1.aws.realm.mongodb.com/api/client/v2.0/app/db-name/auth/providers/local-userpass/login?link=true 401
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Simply running the code above to turn an anon authenticated user into a user with email and password results in the error. Havent been able to *not* reproduce it :) 

### Version

realm-web@1.7.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

web

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Greetings @3210jr ... We have [an integration test verifying that this works](https://github.com/realm/realm-js/blob/master/packages/realm-web-integration-tests/src/user.test.ts#L169-L193) as expected, which basically executes:

```typescript
// Ensure you have an anonymously authenticated current user
const credentials = Credentials.anonymous();
const user = await app.logIn(credentials);
// Register a new email / password user
await app.emailPasswordAuth.registerUser({ email, password });
// Link the current user with the email credentials
const emailCredentials = Credentials.emailPassword(email, password);
await user.linkCredentials(emailCredentials);
```

I suspect you're not registering an email / password user before linking. Please reopen the issue if that's not the case.

**Comment by bradoyler** [comment]
@kraenhansen does this integration test run with "Email confirmation" turned on? 
Because in that case, I get a 401 retry loop when calling `use.linkCredentials(emailCredentials)`
(using latest realm-web@2.0.0)
