### ISSUE TITLE
[Atlas] The "Automatically confirm users" option is not working

### ISSUE THREAD

**Issue by 3210jr** [realm/realm-js#4372]
### How frequently does the bug occur?

All the time

### Description

What I expect: when the option "Automatically confirm users" option is selected in the dashboard, new sign ups should not be put in the "pending" section of the users.

What is happening: Even after selecting that option, users are not automatically confirmed 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Select the option "Automatically confirm users" on the dashboard and try to register a new email and password user

### Version

realm-web@1.7.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

web

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
Hello @3210jr, I was unfortunately not able to reproduce this issue.  And in any case, I'm not in the position to help solve it.  For problems with Atlas, please use the [support channel](https://support.mongodb.com) at MongoDB.  Someone should be able to help you there.

**Comment by takameyer** [comment]
@3210jr I just received word that this is a known issue and "works as designed".  Apparently the user will be marked as `pending` until their first login.  In any case, I would still use the support channel if this is a blocking issue for you.
