### ISSUE TITLE
ReferenceError: Can't find variable: globalThis 

### ISSUE THREAD

**Issue by laxminarayan192** [realm/realm-js#4379]
### How frequently does the bug occur?

All the time

### Description

I had well working project in react native 0.64.1, i have upgraded to react native0.67.2 started getting this error.
if i use `const Realm = require("realm") `i get following error.  
node_modules/realm-network-transport/dist/bundle.react-native.es.js
<img width="398" alt="Screenshot 2022-02-28 at 7 17 30 PM" src="https://user-images.githubusercontent.com/7250679/155994546-95c4a710-7364-4126-9c78-2ff514ecba50.png">

if `import Realm from "realm"` i get following error
Error: Requiring module "node_modules/realm/lib/index.js", which threw an exception: ReferenceError: Can't find variable: globalThis
<img width="395" alt="Screenshot 2022-02-28 at 7 14 42 PM" src="https://user-images.githubusercontent.com/7250679/155994481-3b41591b-8285-49e2-8772-7ac00f485779.png">

### Can you reproduce the bug?

Yes, always

### Version

realm:10.4.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

android

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@laxminarayan192 Thanks for creating an issue.  I'll see if I can reproduce this and get back to you soon.

**Comment by laxminarayan192** [comment]
"jsc-android": "^250230.2.1" solved issue

**Comment by tatiana-lonestone** [comment]
> "jsc-android": "^250230.2.1" solved issue

This work for me !
