### ISSUE TITLE
Expo + realm: Missing Realm Constructor 

### ISSUE THREAD

**Issue by AppneticSoftware** [realm/realm-js#4405]
### How frequently does the bug occur?

All the time

### Description

Hi all, 

I currently have a problem with my Expo + realm Project. **When executing `expo run:ios` everything works perfectly fine.**
As soon as **building for simulator/Appstore** with `eas build -p ios --profile preview` the **App crashes** and tells me "Unhandled JS Exception: Error: Missing Realm constructor". Did everything like mentioned in this article: https://docs.expo.dev/build-reference/simulators/

-> See the logs - I also did the pod install stuff. Guess the problem occurs due to the packages I installed? 
package.json **without** template: 
dependencies": {
    "@gorhom/bottom-sheet": "^4.1.5",
    "@gorhom/portal": "^1.0.12",
    "expo": "^44.0.0",
    "expo-device": "~4.1.0",
    "expo-linear-gradient": "~11.0.3",
    "expo-modules-core": "^0.6.5",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "^0.11.6",
    "moment": "^2.29.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-get-random-values": "^1.7.2",
    "react-native-reanimated": "~2.3.1",
    "react-native-web": "0.17.1",
    "realm": "^10.13.0"
  },

I also tried to move my code into a project created with the official template from takeameyer : https://www.npmjs.com/package/@realm/expo-template-js
With using the template another problem occurs: The App is stuck within the launching screen and never open the main app. I also build a version of the template app without changing anything and it was working. That is why I guess it comes down to some incompatibility with other packages? 

package.json **with** template:
  "@realm/react": "^0.1.0",
    "expo": "^44.0.6",
    "expo-dev-client": "~0.8.4",
    "expo-splash-screen": "~0.14.2",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.6",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-get-random-values": "~1.7.2",
    "realm": "^10.13.0",
    "@gorhom/bottom-sheet": "^4.1.5",
    "@gorhom/portal": "^1.0.12",
    "expo-device": "~4.1.0",
    "expo-linear-gradient": "~11.0.3",
    "expo-modules-core": "^0.6.5",
    "moment": "^2.29.1",
    "react-dom": "17.0.1",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-web": "0.17.1"`

### Stacktrace & log output

```shell
Crash Log without using the template: 
Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
CoreSimulator 783.5 - Device: iPhone 12 Pro Max (7B810D3C-6DC4-406D-96C2-F970DAA9417D) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 12 Pro Max
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting', reason: 'Unhandled JS Exception: Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubl...,
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Guess it is hard to reproduce since it only occurs within my code. In case you need repo access let me know. 

How I am calling realm: 

import Realm from "realm";
(also tried: import from @realm/react)

 useEffect(() => {
    Realm.open({
      path: ASN,
      schema: [AccountSchema, EntrySchema],
    }).then((realm) => {
      setRealm(realm);
      getAllAccounts(realm).then((accountsFromDB) => {
        accountsFromDB.addListener(Accountslistener);
      });
      getActiveAccount(realm).then((activeAccount) => {
        setActiveAccount(activeAccount);
      });
    });
    return () => {
      if (realm != null) {
        realm.removeAllListeners();
        realm.close().then(() => {
          setRealm(null);
          setActiveAccount(null);
        });
      }
    };
  }, []);

(P.S. Sorry for the dirty code)

### Version

10.13.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15.2

### Build environment

Which debugger for React Native: ..

**Comment by AppneticSoftware** [comment]
@tomduncalf Thanks a lot - I will keep on trying as well. Hope to get some good news from your side! Thanks again - really appreciate your service.

**Comment by AppneticSoftware** [comment]
I found the problem and the corresponding solution. 

Problem: Gorhom Bottom Sheet **v4**
Solution: Use Gorhom Bottom Sheet **v2** 

-> _Guess the real problem is react-native-reanimated_ - read in a few posts that realm and reanimated to not like each other. 

However: after changing the code from GBSv4 to GBSv2 everything works perfectly. 

Hope this posts will save other people a lot of time. Took me ages to find the right solution.

**Comment by tomduncalf** [comment]
I'm glad you were able to solve the issue @AppneticSoftware, thanks for sharing your resolution.

If `gorhom/react-native-bottom-sheet@4` is depending on Reanimated v2, you will need to use the Hermes beta branch of Realm (`realm@hermes`).
