### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

### ISSUE THREAD

**Issue by amplework** [realm/realm-js#4408]
### How frequently does the bug occur?

Sometimes

### Description
I have 23 crashes in production precisely like this from 12 different users.

![image](https://user-images.githubusercontent.com/51485111/158124991-e4d31dbe-7aca-4277-a64b-bf7effcef1b9.png)

### Can you reproduce the bug?

Not yet

### Version

10.10.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.11.2

**Comment by fronck** [comment]
@amplework Thanks for reporting this issue.
Would you be able to share the schema you're working with when this crash happens?

**Comment by amplework** [comment]
@fronck **i have added my schema below:**

export const CURRENT = 'Current';
export const WORKOUTLIST = 'WorkoutList';
export const USER_WORKOUT_INFO = 'UserWorkoutInfo';
export const PROGRAM = 'Program'

export const CurrentSchema = {
  name: CURRENT,
  primaryKey: 'id',
  properties:{
    id: 'string?',// DeviceInfo.getUniqueId(),
    memberships: 'Membership?',
    program: 'Program?',
    workout: 'Workout?',
    team: 'Team?', 
    workoutList: 'WorkoutList[]',
    programs: 'Program[]',
    userWorkoutInfo: 'UserWorkoutInfo?'
  }
};


export const WorkoutListSchema = {
  name: WORKOUTLIST,
  embedded: true,
  properties: {
    name: 'string?',
    published: 'bool?',
    _id: 'string?',
  }
};

export const UserWorkoutInfoSchema = {
  name: USER_WORKOUT_INFO,
  embedded: true,
  properties: {
    created: 'date?',
    currentDay: 'int?',
    supplementDay: 'int?',
    updated: 'date?',
    _currentProgram: 'string?',
    _currentTeam: 'string?',
    _currentWorkout: 'string?',
    _id: 'string?',
    _lastWorkout: 'string?',
    _secondLastWorkout: 'string?',
    _supplementProgram: 'string?',
    _supplementTeam: 'string?',
    _supplementWorkout: 'string?',
    _user: 'string?',
    isPendingSync: 'bool?'
  }
};

**Comment by fronck** [comment]
@amplework Thanks for that.
Do you have any idea what the users are doing at the time of the crash (e.g., inserting/deleting Workouts or Programs, initializing the DB)?

Also, does your screenshot above include the entire stacktrace?  It seems like it may have gotten cut off at the bottom.

**Comment by amplework** [comment]
@fronck user is initialized Workouts or Programs in DB.

**I have added full screenshot of crashes below:**

![image](https://user-images.githubusercontent.com/51485111/159205911-df444401-8936-4072-9d82-7822fcc6b97b.png)
![image](https://user-images.githubusercontent.com/51485111/159205939-ea1d52fc-50e1-46ae-b278-60ff4b9853fd.png)
![image](https://user-images.githubusercontent.com/51485111/159205966-97a21cfa-f254-4de3-b6c4-50f568f92f6a.png)
![image](https://user-images.githubusercontent.com/51485111/159206024-a5597f01-9d7c-499d-8f09-141e58f826c8.png)

**Comment by kneth** [comment]
We have been reworking the interaction with JavaScriptCore by using the new JSI api. Please upgrade to v11.0.0-rc.1. If you still experience the issue after upgrading, please either reopen the issue or create a new issue.
