### ISSUE TITLE
[React-Native] Unable to resolve module "submit-analytics"

### ISSUE THREAD

**Issue by IronTony** [realm/realm-js#4419]
### How frequently does the bug occur?

All the time

### Description

After Android compilation, I can see in the terminal this error:

`Error: Unable to resolve module ./submit-analytics from /Repository/App/node_modules/realm/lib/index.js:`

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/3645225/158453668-f30b8151-3922-4b4f-8c75-7cfd198bc35e.png">

### Can you reproduce the bug?

Yes, always

### Version

10.20.0-beta.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 10

**Comment by kneth** [comment]
@IronTony Thank you for reporting. We need to rebase the `hermes` branch on `master` where it has been fixed.

**Comment by IronTony** [comment]
Ok thank you for the reply. So probably new version always on the `hermes` branch or brand new release?

**Comment by kneth** [comment]
After a regular release, we rebase the `hermes` branch and release a new Hermes beta (delay will be a couple of days).

**Comment by IronTony** [comment]
Thank you so much
