### ISSUE TITLE
Realm.Results.filter(callback) method

### ISSUE THREAD

**Issue by helloworld123456** [realm/realm-js#442]
:-)
Hi, I recently meet a requirement that display a list which data source may come from db or json from network api call.

In my RN components I want reuse the filtering logic for both Realm.Results and Array, but the filter gramma is different:

In realm:
realmResults.filtered('propertyOne = $0', valueOne)

In javascript: 
jsArray.filter(obj=>obj.propertyOne==valueOne)

I also consider translate realm Results to javascript Array but it is much code to write.

Is there a Realm.Results.filter(callback) just like in javascript Array object? I look for the realmjs api and not find one.

I updated the latest version of realm, and access the deleted object not crash the app instead of throwing an exception,  It is much intuitive, thanks  for realm team's great work!

**Comment by appden** [comment]
There is currently not a way to filter with a callback. We will be looking into doing that once all the plumbing is in place (this issue relates to #437).

Given that `filtered('propertyOne = $0', valueOne)` is **much** faster for this use case, I would strongly recommend doing that over converting the results to an Array. However, if you really want to convert to an Array, the easiest way to do that is by calling `slice()` on the results.

**Comment by helloworld123456** [comment]
@appden 
Thanks for your suggestion, I will consider separate the filtering logic for Realm.Results and javascript  Array. I also find the slice() method is useful to convert Results to Array.

**Comment by ward-dotdev** [comment]
Trying to do the same thing here. Any changes or updates on this?

**Comment by JosefButzke** [comment]
Hi guy, my solution was return a function with instance inside Schema:

```
//Schema
export default class UserSchema {
  static schema = {
    name: 'Users',
    primaryKey: 'id',
    properties: {
      id: {type: 'int', indexed: true},
      name: 'string',
      cr: 'int',
      data_nascimento: 'int',
      ghe: 'string',
      path: 'string',
      epis: 'Epis[]',
    },
  };

  get values() {
    return {
      id: this.id,
      name: this.name,
      cr: this.cr,
      data_nascimento: this.data_nascimento,
      ghe: this.ghe,
      path: this.path,
      epis: this.epis.map(e => e.values),
    };
  }
}

//call
const realm = await getRealm();
const response = realm.objects('Users').sorted('name');
console.tron.log(response.map(user => user.values));
```
