### ISSUE TITLE
React Native Realm: Accessing object of type "X" which has been deleted

### ISSUE THREAD

**Issue by johnmurphy01** [realm/realm-js#443]
What is the best practice for determining whether or not a Realm record has been deleted in React Native? I am fetching a list of objects from Realm and I will get this error pretty consistently. Other objects will also throw this error but not as frequently. As far as I am aware, I am not attempting to access a deleted record. The stacktrace doesn't give enough information in order for me to pinpoint where I would be attempting to access a deleted record. It gives me the method name but not the line in which the error threw.

**Comment by appden** [comment]
This exception is thrown if trying to either get or set a property on a deleted object. The stack trace _should_ include where that happened, so I'd really appreciate if you included an example of such a trace so I could see if there's an issue there. As of `0.12.0` you can explicitly check if an object is valid by calling its `isValid()` method (documented [here](https://realm.io/docs/react-native/latest/api/Realm.Object.html#isValid) in case you're interested).

**Comment by johnmurphy01** [comment]
Thanks! I just discovered isValid and it has seemed to alleviate some of the issues I am experiencing. The stacktrace was helpful after I was able to view the entire source file that is generated.

**Comment by appden** [comment]
Awesome, thanks for following up!

**Comment by esutton** [comment]
I extended my object with Realm.Object.  However, isValid() always returns true?

This continues to be quite challenging to figure out solutions to prevent app crashes due to invalid Real objects.
