### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

### ISSUE THREAD

**Issue by amplework** [realm/realm-js#4438]
### Discussed in https://github.com/realm/realm-js/discussions/4437

<div type='discussions-op-text'>

<sup>Originally posted by **amplework** March 22, 2022</sup>
@stennie @timanglade @BrandonSmith @ashwinphatak @breezeight i facing this issue for multiple users. many users are affected.

![image](https://user-images.githubusercontent.com/51485111/159452889-10e1cae8-86c5-40c2-9e38-ac4b562d093e.png)
</div>

**Comment by N3TC4T** [comment]
This is duplicated, Please check https://github.com/realm/realm-js/issues/3913#issuecomment-975537832

**Comment by tomduncalf** [comment]
Thanks for that @N3TC4T!

@amplework this does appear to be the same as the other issue. I've raised this issue internally so hopefully we can investigate it in more detail soon.
