### ISSUE TITLE
Problem when using Realm React 0.2.0 inside a section list  undefined is not an object (evaluating 'object._objectId')

### ISSUE THREAD

**Issue by Acetyld** [realm/realm-js#4441]
### How frequently does the bug occur?

All the time

### Description

Problem when using Realm React 0.2.0 inside a section list  causing error  undefined is not an object (evaluating 'object._objectId')

### Stacktrace & log output

```shell
ERROR  TypeError: undefined is not an object (evaluating 'object._objectId')

This error is located at:
    in VirtualizedList (at VirtualizedSectionList.js:190)
    in VirtualizedSectionList (at SectionList.js:247)
    in SectionList (at AssignedToModal.js:208)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at AssignedToModal.js:201)
    in RCTView (at View.js:32)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```
  const usersData = useMemo(() => {
    let memoOptions = users;
    if (filter) {
      memoOptions = memoOptions.filtered(`fullName CONTAINS[c] '${filter}'`);
    }
    return memoOptions;
  }, [filter, users]);

  const teamsData = useMemo(() => {
    let memoOptions = teams;
    if (filter) {
      memoOptions = memoOptions.filtered(`name CONTAINS[c] '${filter}'`);
    }
    return memoOptions;
  }, [filter, teams]);

  const departmentsData = useMemo(() => {
    let memoOptions = departments;
    if (filter) {
      memoOptions = memoOptions.filtered(`name CONTAINS[c] '${filter}'`);
    }
    return memoOptions;
  }, [filter, departments]);

  const options = useMemo(() => {
    return [
      {
        title: 'Afdelingen',
        type: DepartmentsSchema.schema.name,
        fieldText: 'name',
        data: departmentsData,
      },
      {
        title: 'Teams',
        type: TeamsSchema.schema.name,
        fieldText: 'name',
        data: teamsData,
      },
      {
        title: 'Gebruikers',
        type: UsersSchema.schema.name,
        fieldText: 'fullName',
        data: usersData,
      },
    ];
  }, [departmentsData, teamsData, usersData]);`
```

Options is being used inside the sectionlist

### Version

0.2.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

15.2

### Build environment

Which debugger for React Native: ..

**Comment by Acetyld** [comment]
I personally think its because my primary key is not a number? and you use Number(key)?

**Comment by tomduncalf** [comment]
Hi @Acetyld, could you share your schema please? Or alternatively if you can create a full reproduction in a Git repo (either pushing your existing code or creating a minimal reproduction) that would be helpful.

[`Number(key)`](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/cachedCollection.ts#L96) in `CachedCollection` is referring to [which key of the object we are trying to access](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/cachedCollection.ts#L71) so we can detect array access in the Proxy, so is unrelated to this – e.g. if you access `cachedCollection.test`, `key` would be `test`; if you access `cachedCollection[12]`, `key` would be 12.

Every Realm object has an internal `_objectId()` so I don't think this is the issue either.

If you can share more details or a reproduction, I can try to diagnose what is happening.

**Comment by tomduncalf** [comment]
Actually @Acetyld, my colleague tells me they have a fix for your issue which will be in the Realm React 0.2.1 release, thanks!

**Comment by Acetyld** [comment]
Thanks! @tomduncalf we love to see this!

**Comment by tomduncalf** [comment]
The new release is out: `@realm/react@0.2.1`. Could you please try it out and let me know if it solves your issue?

**Comment by Acetyld** [comment]
Hello @tomduncalf,
The update didint help, see screenshot:
![Schermafbeelding 2022-03-24 om 18 31 33](https://user-images.githubusercontent.com/55088242/159976093-481ba274-75f9-4068-a386-24525e72a01e.png)

**Comment by Acetyld** [comment]
Nevermind! @tomduncalf clearing cache en deleting app cache fixed the issue!

**Comment by tomduncalf** [comment]
Great, glad to hear you got it working. Clearing cache is always a good idea with React Native, haha :)
