### ISSUE TITLE
app crashes after build

### ISSUE THREAD

**Issue by oguzhan10** [realm/realm-js#4444]
### How frequently does the bug occur?

All the time

### Description

After I installed realm in my react-native app, app crashes without error. 

"react-native": "^0.67.4",
"realm": "^10.14.0",
gradle version 7.2
node version :15.2.0
 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

npm install realm after that npx react-native android-run

### Version

^10.14.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

android

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@oguzhan10 If you downgrade to 10.13.0, does it work?

**Comment by oguzhan10** [comment]
trying now @kneth

**Comment by kneth** [comment]
Are you using JavaScriptCore or Hermes as JS engine? If you are using Hermes, you need to use v10.20.0-beta.2.

**Comment by oguzhan10** [comment]
How can I check it ? @kneth

**Comment by kneth** [comment]
The issue is `react-native-reanimated`. If you want to use that library, you will have to use Hermes as engine - and use Realm JS v10.20.0-beta.2 or later. See also https://github.com/realm/realm-js/issues/3940

**Comment by oguzhan10** [comment]
Project is finally working but I am getting a weird error. 
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: 
undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by tomduncalf** [comment]
Hey @oguzhan10, that usually indicates an error somewhere in your React Native code, for example I've had it in the past when I've mixed up default and named exports. I don't think it's likely to be a Realm thing. Unfortunately it's not always obvious where the error is from from the stack trace so fixing it can require some trial and error...

I would suggest trying to strip your app down to just the bare minimum (e.g. just rendering "Hello world" from your App component and see if that works), then add in your other components/code one by one until you find what is triggering the problem.
