### ISSUE TITLE
v10.20.0-beta.3: Unable to resolve module ./submit-analytics

### ISSUE THREAD

**Issue by saravanakumargn** [realm/realm-js#4448]
### How frequently does the bug occur?

All the time

### Description

I can't find `submit-analytics` module in v10.20.0-beta.3.

### Stacktrace & log output

```shell
./submit-analytics could not be found within the project or in these directories:
  node_modules/realm/node_modules
  node_modules
  ../../../../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  18 |
  19 | const utils = require("./utils");
> 20 | const analytics = require("./submit-analytics");
```

### Can you reproduce the bug?

Yes, always

### Version

v10.20.0-beta.3

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Thanks for reporting this. I'll look into this first thing on Monday.

**Comment by kraenhansen** [comment]
I'd love to know what version of React Native you're using and if you're using any custom metro configuration?

**Comment by IronTony** [comment]
Hi @kraenhansen,
I am facing the same issue using the latest version, installed using `yarn add realm@hermes`.
I installed it after your patch inside the package.json and I am using RN 0.67.4

**Comment by IronTony** [comment]
@kraenhansen  I am trying to, but if I install `realm@hermes` on a brand new `create-react-native-app` it compiles on ios and android.
If I use my app, I have this problem on iOS and Android
<img width="886" alt="image" src="https://user-images.githubusercontent.com/3645225/160480085-9cc27d89-e3fd-453d-ab19-cc7d0b52a1d1.png">

I removed `node_modules`, `yarn.lock`, `Pods` and `Podfile.lock`, but always the same problem

**Comment by kraenhansen** [comment]
I'd love to see em the contents of your Metro config. Would it be possible for you to share your app with all your components deleted? You can share this confidentiality by sending an email to realm-help@mongodb.com

**Comment by saravanakumargn** [comment]
> It seems your Metro bundler is picking up the wrong export target. We're specifying a "metro" field in the package.json which Metro should be picking up to ensure this doesn't happen. I'd love to know what version of React Native you're using and if you're using any custom metro configuration?

@[kraenhansen](https://github.com/kraenhansen) You are right. I am using `nx` workspace monorepo for React Native. By default `nx` has some custom metro config. After removed `resolverMainFields` config it started working. Please find metro config below and my environment. 

Thanks for your great support.

```
const { withNxMetro } = require('@nrwl/react-native');
const { getDefaultConfig } = require('metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return withNxMetro(
    {
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        }),
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
      },
      resolver: {
        assetExts: assetExts.filter((ext) => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg'],
        // resolverMainFields: ['sbmodern', 'browser', 'main'], // Working find after disable this config
        // blacklistRE: exclusionList([/\.\/dist\/.*/]),
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      debug: false,
      // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
      extensions: [],
    }
  );
})();
```

package.json
```
"realm": "^10.20.0-beta.3",
"react-native": "^0.67.4",
```

apps/mobile-app/android/app/build.gradle
```
project.ext.react = [
    entryFile: "apps/mobile-app/src/main.tsx",
    enableHermes: true,  // clean and rebuild if changing
]
```

**Comment by kraenhansen** [comment]
@saravanakumargn Great news! Instead of removing it, you should be able to simply add "react-native" as a main field (before "browser" and "node").

@IronTony feel free to open another issue if this doesn't solve your problem and I'll be happy to help debug it further.
