### ISSUE TITLE
field name cannot start with 'not',  such as 'notic'.

### ISSUE THREAD

**Issue by OrangeBao** [realm/realm-js#445]
there are two query string:

1. filtered( '$0==notic',notic)
2. filtered( 'notic==$0',notic)

first is correct, second is error. 
I think that  second string is equal with ' not  ic==$0'.

can you understand?

**Comment by appden** [comment]
@OrangeBao thanks so much for reporting this. We'll get this fixed very soon.

**Comment by appden** [comment]
@OrangeBao We're in the process of releasing `0.13.0`, which includes a fix for this. It should be out within an hour or so.

**Comment by OrangeBao** [comment]
@appden thanks so much
