### ISSUE TITLE
[iOS] Expo EAS Xcode version incompatible with 10.20.0.beta3

### ISSUE THREAD

**Issue by thespacemanatee** [realm/realm-js#4462]
### How frequently does the bug occur?
All the time

### Description
With the latest version, I am unable to build my project on Expo EAS build service.

The Expo team says that it is [difficult for them to upgrade](https://forums.expo.dev/t/eas-latest-image-xcode-version-out-of-date/62705) Xcode on their VMs. Would it be possible to make this library compatible with an older version of Xcode?

Thank you!

### Stacktrace & log output
```shell
❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1316.0.21.2.0_0' Reader: '1300.0.29.30_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.30)' for architecture arm64
```

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
Build project on Expo EAS servers with `realm@10.20.0.beta3`.

### Version
10.20.0.beta3

### What SDK flavour are you using?
MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
iOS

### Cocoapods version
1.11.3

**Comment by kraenhansen** [comment]
I'm on a fully upgraded system and unable to verify this, but we should support being built on Xcode 10 and above (just as React Native does). As such I'll close this issue. Please re-open with information on specific versions of Xcode that the build is failing for and ideally exact steps to reproduce this.

I have a colleague with a bitcode related issues after upgrading to macOS Monterey which also required an update to Xcode. It might be that the Expo builders have upgraded OS but miss the Xcode upgrade required.

**Comment by thespacemanatee** [comment]
Based on my conversation with the Expo team [here](https://forums.expo.dev/t/eas-latest-image-xcode-version-out-of-date/62705) I would assume that they are using Xcode 13.2.1. I would also like to point out that earlier builds that I was using up to `10.20.0.beta2` works, so something must have changed in the latest release.

**Comment by kraenhansen** [comment]
Have you tried reverting your upgrade to verify that the `10.20.0.beta2` version still works on their build nodes? I mean, it might have been a change to their infrastructure which happened between your upgrades.

**Comment by kraenhansen** [comment]
Okay - thanks for verifying that!

I believe the XCFramework shipped with `10.20.0-beta.3` was build using Xcode 13.3 (13E113), which does include a [major version upgrade of LLVM](https://en.wikipedia.org/wiki/Xcode#13.x_series).

Depending on what build tools exists on the Expo builder nodes, it might be possible to build the XCFramework from within the `realm` package:

```
cd node_modules/realm
./scripts/build-ios.sh
```

**Comment by thespacemanatee** [comment]
Thanks for the explanation and also the quick replies! I will try it out and worse case we'll just have to disable bitcode until Expo updates their Xcode version which is fine since we are still in the development phase 🙂

**Comment by kraenhansen** [comment]
I just tried this locally and realised a patch is needed to our cmake configuration to enable building from our NPM artifact: https://github.com/realm/realm-js/pull/4466/commits/9ad22a72babde56aa42bf9e5280e8dd032dd9a46
I'll work towards getting this merged and released, but in the meantime you should be able to apply that patch and build from the NPM package.

**Comment by kraenhansen** [comment]
I just had a chat with my colleague on the Realm Swift team and we'll work towards building the XCFramework we release with an older version of Xcode as those binaries will be consumable by newer versions of Xcode perfectly fine. This should make it possible to consume from any Xcode version reasonably used by developers or other services such as Expo EAS. Thanks a lot for bringing this to our attention!

**Comment by thespacemanatee** [comment]
@kraenhansen My pleasure and happy to contribute in a tiny way to such an awesome project!

**Comment by kraenhansen** [comment]
@thespacemanatee I'm pleased to announce that we just released [v10.20.0-beta.4](https://github.com/realm/realm-js/releases/tag/v10.20.0-beta.4) which was built using Xcode 12.4 - hopefully solving your original issue 🤞 

Thanks again for reporting this!

**Comment by thespacemanatee** [comment]
@kraenhansen Just did a build on EAS and can verify that it works great, thanks again for resolving it so quickly 😊

**Comment by kraenhansen** [comment]
@thespacemanatee this is great news!
