### ISSUE TITLE
Realm file has bad size (4322) Path:Exception backtrace:

### ISSUE THREAD

**Issue by TangChanged** [realm/realm-js#4469]
### How frequently does the bug occur?

All the time

### Description

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/12230238/161376048-1568ae24-c9d4-41a0-91f5-16b75041c746.png">

I uploaded the local Realm file to the server, downloaded it, and the file couldn't be opened.Android can't open it, ios can

### Can you reproduce the bug?

Yes, always

### Version

3.3.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

android 10

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@TangChanged If you are using Realm JavaScript v3.3.0, you will need to upgrade to at least v10.0.0 (but latest is recommended). The pre-v10.0.0 sync is no longer supported. Please see https://docs.realm.io/realm-legacy-migration-guide/?_ga=2.74106320.330975681.1649056103-182012221.1608307054

**Comment by TangChanged** [comment]
@kneth Thank you very much for your reply.I simply uploaded a local Realm file to my own service and did not use Realm's synchronization. I'm not sure we're talking about the same thing?

**Comment by kneth** [comment]
@TangChanged Oh, I get it. Copying an open Realm file might lead to corruption as Realm is using [memory mapped](https://en.wikipedia.org/wiki/Memory-mapped_I/O). You will have to ensure that the Realm is closed before copying.

**Comment by TangChanged** [comment]
@kneth Yeah, we had a suspect on the canvass. However, I sent a realm file to my colleague using wechat, which also couldn't be opened, so I ignored this point. So, after the upgrade, will this problem still exist?

**Comment by mklb** [comment]
> @TangChanged Oh, I get it. Copying an open Realm file might lead to corruption as Realm is using [memory mapped](https://en.wikipedia.org/wiki/Memory-mapped_I/O). You will have to ensure that the Realm is closed before copying.

Very interesting. I did not know that.
Would uploading a copy of a current open realm via ```writeCopyTo``` prevent this kind of corruption? I have multiple users effected by corrupt realm files - I think - because of uploading open realm DBs.

**Comment by kneth** [comment]
Unfortunately, in many cases `writeCopyTo` will either replicate a corruption or crash in the call

**Comment by mklb** [comment]
Thanks @kneth for the quick reply. 

Does it mean that there is no way of safely uploading/saving a realm while the application interacts with a realm? In most cases the realm is active as long as the application is running 👀 

Therefor it would be very nice if ```writeCopyTo``` would copy everything correctly.

**Comment by mklb** [comment]
Does ```realm.close()``` close the realm immediately ? I call an upload function right after that call. Maybe closing takes to long and that is the problem?

**Comment by kneth** [comment]
`realm.close()` closes the Realm immediately from the viewpoint of the app, and you cannot call any instance method on the instance after that.

Since Realm is memory mapped, storing Realm files on replicated file systems (Google Drive, iCloud, Dropbox, etc.) might lead to corruptions. It is safer to use [device sync](https://www.mongodb.com/docs/atlas/app-services/sync/).

I am not sure what you mean by "upload function".
