### ISSUE TITLE
React-native 0.25 compatible?

### ISSUE THREAD

**Issue by cablegunmaster** [realm/realm-js#447]
Is this up to date to the react-native 0.25 version? Can this be checked? 
Also wondering how to implement this in the redux way.
As it states on the website its up to date to 0.12, is this just a number or untested in higher versions?

Looking forward to your answer :).

If posted in the wrong repository please let me know where the correct one is, thanks.

**Comment by alazier** [comment]
We are up to date and have been testing with version `0.25.1` of react-native. `0.12.0` is the version for the `realm` module, and we just released `0.13.0` yesterday.
