### ISSUE TITLE
Email/Password Authentication Randomly Does Not Work After Application Crash

### ISSUE THREAD

**Issue by jasontulloch** [realm/realm-js#4474]
### How frequently does the bug occur?

Sometimes

### Description

I have run into this issue a few times while developing my react native application.

I currently have a functioning react native application with email/password authentication. But during development my app may return an error due to some small development typo, issue, etc. When I try to log back in, there is not an issue, I re-authenticate the user if they were logged.

Randomly, following my application crashing or returning an error and trying to log back in, my email/password suddenly does not work. If I open Realm on MongoDB, my current user and their email exists, which gives me the impression the password somehow changed or was lost. Since I have built a ‘Forgot My Password’ button that works, I go in to reset my password without issue. But again, I still can not log in. At this point, I have a user on Realm but can no longer authenticate them with email/password.

If I check my logs, I see the error ‘username/password invalid’ even though it’s the same username and password I had been using for over a month.

Most recently, the issue returned the following error: "code: -1, message: Network request failed". While other development errors have caused the bug, mostly recently it was of a typo in react navigation (third-party library). 

I have tried to change the user's password, restart my local server, remove the application from my simulator, and even restart my computer.

### Stacktrace & log output

```shell
{"code": -1, "message": "Network request failed"}
```

### Can you reproduce the bug?

Not yet

### Reproduction Steps

Uncertain how to reproduce this issue, it may be related to the network connection being lost?

Most recently, the issue was because my "Screen Name" had a typo.

```
using React Navigation

const onPressLeaveScreen = async () => {
   navigation.navigate('Screen Name')
}
```

### Version

8.1.4

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS 15.0, iPhone 13

### Build environment

Which debugger for React Native: ..

**Comment by narentechie** [comment]
I'm facing the same issue. it's happening in production. please provide solution to fix this issue.

**Comment by kneth** [comment]
I can imagine that "Network request failed" indicates that the request has timed out. Could you increase the value `timeout` in the app's configuration?

**Comment by jasontulloch** [comment]
Thanks for the response, sure I can try that. Are the following changes what you were referring to?

new Realm.app({id: MONGO_ID, timeout: 1000*60 })

Just to confirm, could this lead to any performance issues?

If this does resolve the issue, is there any way to access the accounts that I can no longer log into though? Thanks for the help!

**Comment by jasontulloch** [comment]
Update: changing the timeout does not resolve this issue as another account has been permanently locked out again.

**Comment by tomduncalf** [comment]
@jasontulloch so the account appears to be permanently locked out, even if you uninstall and reinstall the app and log in again?

**Comment by jasontulloch** [comment]
@tomduncalf  that is correct. I have tried the following:

- Complete reboot of my computer
- Deleting the app from the simulator
- Deleting the app from the simulator and clicking "Erase All Content and Settings"
- Changing the password
- Signing up new account with the same email (error message received that the user already exists which is also validated on realm)

One interesting thing I discovered last night was that when a new user was permanently locked out the rebooted application logged an old user in that had been permanently locked out. I logged out as this user and tried to log back in, hoping they somehow had access again, but that did not work either. It made me think that when the application crashes a user may not be logged out properly and the users state is persisted elsewhere. Not sure, but maybe that information helps.

Thanks for the help!

**Comment by tomduncalf** [comment]
Thanks @jasontulloch, we will have to do some investigation into this – if you have any further hints or code for being able to repro this it would be really helpful

**Comment by jasontulloch** [comment]
@tomduncalf I will keep reviewing the issue and can share anything that is helpful on your end. This may be related...

I booted up my simulator this morning with "npx react-native start" and on IOS with "npx react-native run-ios". Upon build, I immediately received the "Network request failed" error I see when a user is permanently locked out. In my async function that normally works without any issues, I did the following:

```
useEffect(() => {
   async function callFunction() {
      try {
         console.log(user.id) --- somehow this returns the realmId of a user that was permanently locked out
         console.log(user) --- returns an empty object
         const result = await user.functions.myfunction(params) --- this is where the error occurs
         console.log(result) --- nothing returned here as the function stopped on the previous line
      } catch (error) {
         console.error(error)
      }
   }
   callFunction()
}, [param1, param2])
```

@narentechie you mentioned you were having the same issue in production? Does the issue only occur if your application crashes or are users just getting randomly locked out? Is this only the case for Email/Password Auth or have you seen issues with other authentication methods as well?

Let me know what else you need from my end.

**Comment by tomduncalf** [comment]
Thanks, I'll see if I can repro it in any way and we'll also have a look in to this as a team.

**Comment by jasontulloch** [comment]
Sounds good, I think the only thing I would stress is that when my app crashes users that were locked out are suddenly logged in again. Their state is persisting somewhere but if you log out and then try to sign in as them again, you cannot. 

I'm imagining that the application crashes (network error driven, maybe other issues as well) and that the current user is not logged out successfully. Because of this you cannot log out (if somehow logged in as them) or log in as them.

Thanks!

**Comment by tomduncalf** [comment]
Thanks for clarifying - it sounds like a really odd bug and I'm surprised we've not had it reported before if it was a general issue, so perhaps something in your app is triggering it somehow. 

Are you able to share your app source code? If it's private but you'd be happy for us to take a look, you can email it to realm-help@mongodb.com – no worries if that is not possible, but it might help us track down the bug quicker.

**Comment by kneth** [comment]
@jasontulloch Could you provide the app id and/or some server-side log (in an email)? Then we have a chance to investigate a bit more.

**Comment by jasontulloch** [comment]
@kneth sure, I can provide the app id. Is this still the best email?

realm-help@mongodb.com

**Comment by kneth** [comment]
@jasontulloch Yes, please use that address.

**Comment by kneth** [comment]
@jasontulloch I ask you to create a proper support case at https://support.mongodb.com/ to have our experience Technical Service Engineers to investigate your issues.
