### ISSUE TITLE
Re-opening Re-Authenticate Last-User during App restart while OFFLINE 

### ISSUE THREAD

**Issue by reanzi** [realm/realm-js#4495]
### How frequently does the bug occur?

All the time

### Description

Restarting an application offline should Re-Authenticate the last-logged-in user.

But the application keep requesting internet connection to re-authenticate the last-user who was active before app restart.
though after that re-authentication, all activities proceed without connection just fine and syncing works fine when connected.

Tried:

```
const realmFileBehavior = {
  type: "downloadBeforeOpen", // even 'openImmediately' did not work
  timeOut: 1000,
  timeOutBehavior: "openLocalRealm", // open the local realm if the download has not completed within 1000ms
};

const config = {
  schema: [Car], 
  sync: {
    user: app.currentUser, 
    partitionValue: "myPartition",
    existingRealmFileBehavior: realmFileBehavior, // <-- specify behaviour here
    newRealmFileBehavior: realmFileBehavior, // <-- and here
  },
};
```

 as suggested by @tomduncalf  in #4485  issue (which was closed though the issue is not solved so I'd to re-open)

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Just create an application with authentication enabled (I've used email and password), enable sync.

// While you're online
Login into the application
see everything is working (You see the application is working as normal)
Kill the application and restart it, it should re-authenticate the user just fine
Turn off internet connection

** // While OFFLINE  - Make sure the whole computer is not connected to network not just emulator **
restart the application
The app launches but never complete to main screens, stuck with empty white screen

### Version

realm: 10.13.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

windows 10, android Emulator

**Comment by takameyer** [comment]
@reanzi I have reopened https://github.com/realm/realm-js/issues/4485 so lets continue the conversation there

**Comment by reanzi** [comment]
@takameyer thanks buddy 👍
