### ISSUE TITLE
useObject doesn't react to the object being inserted

### ISSUE THREAD

**Issue by mfbx9da4** [realm/realm-js#4514]
### How frequently does the bug occur?

All the time

### Description

As a user, if I do the following `const foo = useObject('foo', fooId)` and foo is initially not in the database, I would expect the hook to re-render if the object with `fooId` is later inserted into realm. This is how most state libraries work in react. In practice, the way `useObject` works is that it will not re-render. The way to solve this is to do the following in the useObject hook:

Try to get the object by primary key. If it exists setup a listener. Otherwise listen to its collection. In the collection listener callback, if the object has been inserted, setup the listener.

### Can you reproduce the bug?

Yes, always

### Version

main

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios

**Comment by takameyer** [comment]
@mfbx9da4 Yes, this is indeed a problem.  We will look into it and get back to you when we have a fix.

**Comment by mordechaim** [comment]
@takameyer 
Until this is fixed, is there a react-friendly workaround?

**Comment by takameyer** [comment]
@mordechaim That is similar to the workaround I would've suggested.

**Comment by channeladam** [comment]
Argh, just ran into this issue :(

**Comment by takameyer** [comment]
The PR #5208 will fix this issue.  Now, when the object does not exist, there will be a listener established on the collection that will re-render when an object with the given primary key comes into existence.

**Comment by Fuzzyma** [comment]
@takameyer I still have this issue!
When deleting and recreating an object, the deletion is handled properly and the object becomes null. However after reinsertion it stays null.
The temporary fix of @mordechaim worked for me
