### ISSUE TITLE
[React-Native]: Require FS (bindings problem)

### ISSUE THREAD

**Issue by IronTony** [realm/realm-js#4517]
### How frequently does the bug occur?

All the time

### Description

Hello,

after the fix for the `submit-analytics` ([here](https://github.com/realm/realm-js/issues/4459) is the issue and the thread), I have another problem during app launching.
As you can see in the screenshot below, I installed `realm@hermes` branch (`10.20.0-beta.5`), but unfortunately I have this problem now (both on iOS and Android, RN version 0.67.4):
![164289568-9aef39c4-2550-4358-80ff-a26bfac4a13f](https://user-images.githubusercontent.com/3645225/164678368-ccfb637e-d94f-4ab5-a270-9bf1a4573542.png)

Any hint? Thank you as usual

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

After the successful compilation with Xcode/Android Studio/Terminal, during the server start compilation

### Version

10.20.0-beta.5

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Both iOS and Android

**Comment by kraenhansen** [comment]
@IronTony can you share your Metro configuration?

**Comment by IronTony** [comment]
Here it is:

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require('metro-config');
const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs'],
  },
};
```

**Comment by kraenhansen** [comment]
What happens if you add `".native.js"` to the `extensions` array of the Babel "module-resolver"?

**Comment by IronTony** [comment]
I have added like this:
```
extensions: [
          '.ios.js',
          '.android.js',
          '.ios.jsx',
          '.android.jsx',
          '.js',
          '.jsx',
          '.json',
          '.ts',
          '.tsx',
          '.native.js',
        ],
```
but the result is same error 😢

**Comment by kraenhansen** [comment]
Are you running the `react-native` CLI with `--reset-cache`?

**Comment by IronTony** [comment]
Yes always. To be sure I have delete `node_modules, `yarn.lock`, and pods and reinstalled from scratch

**Comment by kraenhansen** [comment]
Okay - I just reproduced this locally and found a fix:

```js
  // ...
  resolver: {
    ...defaultResolver,
    sourceExts: [...defaultResolver.sourceExts, 'cjs'],
    resolverMainFields: ['react-native', ...defaultResolver.resolverMainFields],
  },
```

I have no idea why the `getDefaultConfig.getDefaultValues()` doesn't include `"react-native"` in the `resolverMainFields`. I'll try to do a bit more digging on why that is.

**Comment by kraenhansen** [comment]
What's happening here is that the Metro default of this property is `["browser", "main"]` but when invoked via the React Native CLI it gets overwritten with `["react-native", "browser", "main"]`: https://github.com/react-native-community/cli/blob/master/packages/cli-plugin-metro/src/tools/loadMetroConfig.ts#L85

I think that's pretty unfortunate and I'd love to get that updated.

**Comment by IronTony** [comment]
> Okay - I just reproduced this locally and found a fix.
> 
> Add a `resolverMainFields` to your Metro "resolver" configuration:
> 
> ```js
>   resolver: {
>     ...defaultResolver,
>     sourceExts: [...defaultResolver.sourceExts, 'cjs'],
>     resolverMainFields: ['react-native', ...defaultResolver.resolverMainFields],
>   },
> ```
> 
> I have no idea why the `getDefaultConfig.getDefaultValues()` doesn't include `"react-native"` in the `resolverMainFields`. I'll try to do a bit more digging on why that is.

And YES!
Now it works...finally!! 🥳🥳🥳

Thank you so much for the patient and for the help. Super appreciated

**Comment by kraenhansen** [comment]
Likewise - I'm really happy you're trying this out.
It's super important for us to get these rough edges rounded and we can't do this without the help of our community.
So thank you too!

**Comment by kraenhansen** [comment]
I created https://github.com/facebook/metro/pull/808 in an attempt to rectify this.

**Comment by kraenhansen** [comment]
As mentioned in [this comment](https://github.com/facebook/metro/issues/807#issuecomment-1106403161), you probably want to enable the React Native CLI to set their defaults by leaving out the spread of `defaultResolver`:

```js
resolver: {
  sourceExts: [...defaultResolver.sourceExts, 'cjs'],
},
```

**Comment by IronTony** [comment]
Nice, thank you again.
I will try later.
