### ISSUE TITLE
`await Realm.open` does not seem to work with Node.js and sync enabled

### ISSUE THREAD

**Issue by tomduncalf** [realm/realm-js#4554]
Running the following code in Node results in `libc++abi: terminating with uncaught exception of type Napi::Error: domain.enter is not a function`

```
const Realm = require("realm");

const taskSchema = {
  name: "Task",
  primaryKey: "_id",
  properties: {
    _id: "objectId",
    description: "string",
    isComplete: { type: "bool", default: false },
    createdAt: "date",
    userId: "string",
  },
};

const app = new Realm.App({ id: "pbs-test-pwvrg" });

const user = await app.logIn(Realm.Credentials.anonymous());

const realm = await Realm.open({
  schema: [taskSchema],
  sync: {
    user,
    partitionValue: "myPartition",
  },
});
```

I found that if I change [this line](https://github.com/realm/realm-js/blob/master/src/js_realm.hpp#L1084) to: `Function<T>::callback(protected_ctx, protected_callback, protected_this, 2, callback_arguments);` (i.e. add `protected_this`), the error goes away. But I assume this is a symptom of something else being wrong…

That code was last changed in [this PR by Mathias to prep for Hermes from June 2021](https://github.com/realm/realm-js/commit/5b0eabf940d843b76835b6e889817f4052c0b5c3#diff-0e7960bf82824a008ff89d2ffc7ac5f11c7e223a82cf6bf6c3a4c27a5df0bcc8R753).

I also see the issue on `v11`.

**Comment by kneth** [comment]
Your proposed solution makes sense as it sets `this` to a proper value instead of an empty object (`{}`).

**Comment by kneth** [comment]
With v12 out we are rewritten this part of the code base, and I believe that it has fixed the issue.
