### ISSUE TITLE
Can't filter results using IN operator

### ISSUE THREAD

**Issue by marcfrankel** [realm/realm-js#4596]
### How frequently does the bug occur?
All the time

### Description
Following the documentation, I'm trying to filter a query by a list of string primary ids I have. However, when using the IN operator as part of the query I can never seem to get it to work. Apologies if this is not actually a bug, but perhaps an example of the IN operator is due in the documentation if I'm just doing this wrong.  I give an example below

### Stacktrace & log output
```shell
[Unhandled promise rejection: Error: Exception in HostFunction: Unsupported comparison between type 'string' and type 'link']
```

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
The error above is produced when I attempt to use the IN operator on any field (indexed, non-indexed, string, not string, primary key, etc).

`
const test = ['foo'];
realm.objects('QueuedItem').filtered('mediaCategory IN $0', test)
`

### Version
10.20.0-beta.5

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
iOS 15.5

### Build environment
Expo

**Comment by marcfrankel** [comment]
Here's the only related issue I could find on google: https://www.mongodb.com/community/forums/t/error-unsupported-comparison-between-type-string-and-type-link/158010

**Comment by kraenhansen** [comment]
Unfortunately, the `IN` operators right hand operand needs to be a list on a Realm object which is already in the database.
That is, unfortunately you cannot supply an array as the value to replace the placeholder.

As an alternative you can use the `OR` operator to achieve the same:

```typescript
const realm = new Realm({ schema: [{ name: "Person", properties: { name: "string" } }] });
realm.write(() => {
  realm.create("Person", { name: "Alice" });
  realm.create("Person", { name: "Bob" });
  realm.create("Person", { name: "Charlie" });
});
const names = ["Alice", "Bob"];
const query = names.map((_, i) => "name = $" + i).join(" OR ");
const persons = realm.objects("Person").filtered(query, ...names);
```

Please see [this issue](https://github.com/realm/realm-js/issues/2781) for more information and upvote that if you want this feature too 👍  (closing this as a duplicate).
