### ISSUE TITLE
can not use realm inside hook

### ISSUE THREAD

**Issue by fukemy** [realm/realm-js#4604]
### How frequently does the bug occur?
All the time

### Description
I have the class **_RealmContext.js_**

```
import { Room } from "../database/RealmSchemas";
import { Realm, createRealmContext } from '@realm/react'

const config = {
    schema: [Room],
};

export default createRealmContext(config);
  
```

In App.js, i have defined:

import { RealmProvider } from './context/RealmContext';

<RealmProvider>
....
</RealmProvider>

### Stacktrace & log output
```shell
ERROR  Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at App.js:236.
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in VedaxLink(RootComponent) (at renderApplication.js:60)
```

### Can you reproduce the bug?
Not yet

### Version
im using lasted cli

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
IOS

### Build environment
Which debugger for React Native: ..
Check                               Value   Recommendation/Notes
npm ping                            ok
npm -v                              not ok  Use npm v8.11.0
node -v                             ok      current: v17.9.0, recommended: v17.9.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
which git                           ok      /usr/bin/git
Perms check on cached files         ok
Perms check on local node_modules   ok
Perms check on global node_modules  ok
Perms check on local bin folder     ok
Perms check on global bin folder    ok
Verify cache contents               ok      verified 11051 tarballs

### Cocoapods version
1.1.13

**Comment by kraenhansen** [comment]
You have a few options available:

## Default import in your App.js

```jsx
import RealmContext from './context/RealmContext';

function App() {
  return <RealmContext.RealmProvider>{/* Rest of the app goes here .. */}</RealmContext.RealmProvider>
}
```

## Default import in your App.js followed by destructuring assignment

This is a bit more DRY.

```jsx
import RealmContext from './context/RealmContext';
const { RealmProvider } = RealmContext;

function App() {
  return <RealmProvider>{/* Rest of the app goes here .. */}</RealmProvider>
}
```

## Use named export from your RealmContext.js

This has the downside that you must enumerate all the hooks you want to expose.

```jsx
import { Room } from "../database/RealmSchemas";
import { Realm, createRealmContext } from '@realm/react'

const config = {
    schema: [Room],
};

const { RealmProvider, useQuery } = createRealmContext(config);
export { RealmProvider, useQuery };
```

---

Please see our documentation for more examples than what I provide above: https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/

As this isn't really a Realm related issue, but more related to export / import of the Realm context, I'll go ahead and close this. Feel free to reply here or [post on the MongoDB developer forum](https://www.mongodb.com/community/forums/) if you want to follow up.

**Comment by prantaDutta** [comment]
@kraenhansen , can you give us an example, how can we access the realm objects outside of a react component, because there are some cases where we might have to access realm data outside of a react component, let's say a typescript function

**Comment by kraenhansen** [comment]
@prantaDutta I'm on vacation these days, followed by paternity leave.

You could probably get some help with this over at the community forum: https://www.mongodb.com/community/forums/tag/react-js

**Comment by prantaDutta** [comment]
For anyone who might step on this, look here, this helped
https://www.mongodb.com/community/forums/t/mobile-bytes-9-realm-react-for-react-native/155370/15
