### ISSUE TITLE
[EAS Build] /bin/sh: cmake-js: command not found

### ISSUE THREAD

**Issue by thespacemanatee** [realm/realm-js#4618]
### How frequently does the bug occur?

All the time

### Description

Hello!

I'm not sure who to turn to so I am trying my luck here. Overnight, our builds on EAS start to fail consistently due to a dependency on `cmake-js` leading to `/bin/sh: cmake-js: command not found` after `yarn install`. Since I have been using the same image on EAS, it is not an issue with EAS. The project builds fine on our local machines.

### Stacktrace & log output

```shell
Running "yarn install" in the root dir of your repository 
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[stderr] 
warning " > @gorhom/paper-onboarding@1.2.0" has incorrect peer dependency "react-native-gesture-handler@^1.10.3".
[stderr] 
warning " > @gorhom/paper-onboarding@1.2.0" has incorrect peer dependency "react-native-reanimated@^1.13.3".
[stderr] 
warning "@realm/react > react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[stderr] 
warning " > redux-persist@6.0.0" has unmet peer dependency "redux@>4.0.0".
[4/4] Building fresh packages...
[stderr] 
error /Users/expo/workingdir/build/node_modules/realm: Command failed.
[stderr] 
Exit code: 127
[stderr] 
Command: prebuild-install -r napi || cmake-js build
[stderr] 
Arguments: 
[stderr] 
Directory: /Users/expo/workingdir/build/node_modules/realm
[stderr] 
Output:
[stderr] 
prebuild-install WARN install write EPROTO 4576347648:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 40
[stderr] 
prebuild-install WARN install 
[stderr] 
/bin/sh: cmake-js: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn exited with non-zero code: 127
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Create a clean project and add `realm` dependency
2. Upload to EAS build servers

### Version

10.20.0.beta5

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android, iOS

### Build environment

iOS:

```
macOS Monterey 12.4
Xcode 13.4 (13F17a)
Node.js 16.13.2
Yarn 1.22.17
pnpm 7.0.0
npm 8.1.2
fastlane 2.205.2
CocoaPods 1.11.3
Ruby 2.7
```

Android:

```
Docker image: ubuntu:focal-20210921
NDK 21.4.7075529
Node.js 16.13.2
Yarn 1.22.17
npm 8.1.2
Java 11
```

### Cocoapods version

1.11.3

**Comment by thespacemanatee** [comment]
Can be reproduced if I use `npm install` instead of `yarn` locally.

**Comment by sunnylqm** [comment]
same issue on github action

**Comment by kraenhansen** [comment]
We're currently experiencing [an expired SSL certificate](https://github.com/realm/realm-js/issues/4619) and working hard to resolve it.

We're very sorry for the inconveniences this is causing.

**Comment by nirinchev** [comment]
Hey folks, the expired certificate problem has been resolved - can you try again and verify that it's all working on your end?

**Comment by nathalia-rus** [comment]
> Hey folks, the expired certificate problem has been resolved - can you try again and verify that it's all working on your end?

hey, I just tried again and now it works. Thanks so much for resolving this !

**Comment by thespacemanatee** [comment]
@nirinchev Happy to report that this is has been resolved, thank you so much!

**Comment by atropos0902** [comment]
> We're currently experiencing [an expired SSL certificate](https://github.com/realm/realm-js/issues/4619) and working hard to resolve it.
> 
> We're very sorry for the inconveniences this is causing.

Still having the issue...
```
Exit code: 127
Command: prebuild-install --tag-prefix= -r napi || cmake-js build
Arguments: 
Directory: /Volumes/Code/envas/node_modules/realm
Output:
prebuild-install warn install premature close
/bin/sh: cmake-js: command not found

```

**Comment by takameyer** [comment]
@atropos0902 Are you using `eas` build as well?  In any case, please open a new issue and provide as many details as you can about your build system.  It would appear the `realm` binary is now being downloaded for your dev environment, so `npm` is trying to compile it for you (which requires `cmake-js`).

**Comment by GotiMehta** [comment]
Still I too had the same error. I installed cmake-js using npm `npm i -g cmake-js` and then tried to install Realm but below was the error.

> Output:
> prebuild-install warn install self signed certificate in certificate chain
> [
>   '/usr/local/Cellar/node/18.6.0/bin/node',
>   '/usr/local/bin/cmake-js',
>   'build'
> ]
> info TOOL Using Unix Makefiles generator.
> ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.

I have a Mac with Intel processor. I also tried creating a new project.

Anyone have a any lead please?
