### ISSUE TITLE
[Needs help] Flexible sync not working on expo 45

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [realm/realm-js#4625]
### How frequently does the bug occur?
All the time

### Description
The app doesn't open a connection with sync set to true on Android. Although tested on an iPhone simulator and it's working fine.

![Peek 2022-06-07 15-14](https://user-images.githubusercontent.com/14947957/172393708-1fa31345-1cd8-45d3-8187-6fc56a0e9e77.gif)

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
Clone this repo and run it on ubuntu os

https://github.com/mohamedGamalAbuGalala/expo-45-realm-with-flexible-sync

### Version
check the repo for more info

### What SDK flavour are you using?
Atlas Device Sync

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
Ubuntu 20.04.4 LTS

### Build environment
Which debugger for React Native: check the repo for more info

**Comment by takameyer** [comment]
@mohamedGamalAbuGalala Thanks for reporting and providing a reproduction code.  We will investigate and get back to you as soon as we can find out what's going wrong here.

**Comment by takameyer** [comment]
@mohamedGamalAbuGalala There appears to be a conflict with expo 45 and our android library (similar to an issue we have had with `react-native-reanimated` v2).  We are preparing a v11 release which uses a different method of binding realm to android.  This should resolve this issue.  I'll post when we have an update.

**Comment by takameyer** [comment]
We will now be tracking this issue here https://github.com/realm/realm-js/issues/4639
