### ISSUE TITLE
How to stop a transaction?

### ISSUE THREAD

**Issue by rclai** [realm/realm-js#463]
My app has some parallel tasks running which require that a transaction be stopped if need be. I'd like to check at the very end of the write transaction for a flag indicating whether to trash the transaction.

How would I go about this? Do I just throw an error?

**Comment by appden** [comment]
@rclai That's exactly right, if an exception is thrown from inside the transaction, then it will be cancelled, but be warned that the exception will be propagated to the call site of `realm.write()`, so you'll need to catch it there.

**Comment by appden** [comment]
I'm going to close this for now, but please let us know if you run into any issues.

**Comment by rclai** [comment]
Thanks.
