### ISSUE TITLE
UserProvider.js throwing app.addListener is not a function error

### ISSUE THREAD

**Issue by lukewalz** [realm/realm-js#4638]
### How frequently does the bug occur?

All the time

### Description

I am seeing an error when setting up realm/react [with the user provider ](https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#using-the-user-provider). My app is stuck on the splash screen and I get an error in my console that looks like this. This error comes straight from the UserProvider.js file in the react/realm package. Is this intended?
 

### Stacktrace & log output

```shell
ExceptionsManager.js:149 TypeError: app.addListener is not a function

This error is located at:
    in UserProvider (at App.tsx:67)
    in AppProvider (at App.tsx:66)
    in App (at sdk.js:98)
    in ReactNativeProfiler (at sdk.js:97)
    in RCTView (at View.js:32)
    in View (at touchevents.js:23)
    in __Sentry.TouchEventBoundary (at sdk.js:96)
    in RootApp (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in thedriverclient(RootComponent) (at renderApplication.js:60)
```

### Can you reproduce the bug?

Yes, always

### Version

@realm/react": "^0.3.1"

### What SDK flavour are you using?

Atlas Device Sync

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

ios

### Build environment

React Native Debugger

### Cocoapods version

1.11.3

**Comment by takameyer** [comment]
@lukewalz Thanks for reporting.  We have just released this, but the Hermes branch of Realm doesn't have these changes yet.  This should work with latest `realm` release.  Which version of `realm` are you using?

**Comment by lukewalz** [comment]
> @lukewalz Thanks for reporting. We have just released adding listeners to `app` and `user` on `master`, but the Hermes branch of Realm doesn't have these changes yet. This should work with latest `realm` release. Which version of `realm` are you using?

10.9.1

**Comment by takameyer** [comment]
@lukewalz `@realm/react 0.3.1` requires `realm 10.17.0` or higher.  That should remove the issue.  You will have to update your pods with `pod install` and rebuild in order for the changes to take effect.

**Comment by lukewalz** [comment]
> @lukewalz `@realm/react 0.3.1` requires `realm 10.17.0` or higher. That should remove the issue. You will have to update your pods with `pod install` and rebuild in order for the changes to take effect.

I mistyped. ^10.19.1 is my current realm version

**Comment by tomduncalf** [comment]
Hi @lukewalz, are you able to share a reproduction for your issue please? I created a new app with our Realm React template (`npx react-native init ProjectName --template @realm/react-native-template-ts`) and ensured I had `realm@10.19.1` and `@realm/react@0.3.1` installed, enabled sync, and I have no issues running it.

**Comment by lukewalz** [comment]
For what its worth, the template had the same issue for me when I selected the sync version. I didn't set up the schemas or anything for that in the realm dashboard though so that could explain it. 

I also am using partition instead of flexible if that matters


Sure. Here is some code. Let me know if you need anything else

schemas 
```
import Realm from 'realm';

export const rideSchema = {
  name: 'ride',
  properties: {
    _id: 'objectId?',
    date_completed: 'date?',
    date_created: 'date?',
    date_requested: 'date?',
    duration: 'double?',
    locations: 'string[]',
    notes: 'string?',
    passengers: 'int?',
    service: 'string?',
    status: 'int?',
    tip: 'double?',
  },
  primaryKey: '_id',
};

export const userSchema = {
  name: 'user',
  properties: {
    _id: 'objectId',
    account_type: 'int?',
    address: 'string?',
    auth_id: 'string',
    city: 'string?',
    creation_date: 'date?',
    email: 'string?',
    first_name: 'string?',
    hours: 'int?',
    last_name: 'string?',
    notification_keys: 'string[]',
    phone: 'string?',
    plan: 'int?',
    profile_image: 'string?',
    rides: 'ride[]',
    state: 'string?',
    zip: 'string?',
  },
  primaryKey: '_id',
};
```
App.tsx => 

```
const config = {
  schema: [userSchema, rideSchema],
};

export const {RealmProvider, useObject, useQuery, useRealm} =
  createRealmContext(config);

const syncConfig = {
  partitionValue: null as any,
};

    <AppProvider id=[redacted]>
      <UserProvider fallback={Login}>
        <RealmProvider sync={syncConfig} fallback={() => <ActivityIndicator />}>
        </RealmProvider>
      </UserProvider>
    </AppProvider>
```

package.json
```
  "dependencies": {
    "@react-native-firebase/app": "^14.9.1",
    "@react-native-firebase/messaging": "^14.9.1",
    "@react-native-firebase/storage": "^14.9.4",
    "@react-native-picker/picker": "github:react-native-picker/picker",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@realm/react": "^0.3.1",
    "@sentry/react-native": "^3.4.2",
    "@types/realm": "^1.13.0",
    "formik": "^2.2.9",
    "moment": "^2.29.3",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-bootsplash": "^4.1.4",
    "react-native-date-picker": "^4.2.1",
    "react-native-gesture-handler": "^2.4.0",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-image-picker": "^4.8.3",
    "react-native-paper": "^4.12.0",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.13.1",
    "react-native-sms": "^1.11.0",
    "react-native-vector-icons": "^9.1.0",
    "realm": "^10.19.1",
    "use-sync-external-store": "^1.1.0",
    "yup": "^0.32.11"
  },
```

**Comment by tomduncalf** [comment]
Hey @lukewalz,

I took your schema and created a simple test app based on the React Native Typescript template. This seems to have no issues syncing.

Could you try it out please and see if it works for you? https://github.com/tomduncalf/Issue4638AddListenerUndefined (`npm install`, `npx pod-install`, `npm run ios`) – you can use my app ID for now, I'll delete the app once this is resolved.

If it works for you then we'll need to work out where your app is differing – you can see the changes I made to the RN template here: https://github.com/tomduncalf/Issue4638AddListenerUndefined/commit/c31aa0ce03ff8ec8382c989d8570191bbf1a50cc

**Comment by lukewalz** [comment]
hey @tomduncalf,
I very much appreciate the quick responses and help.
If I clone that branch that you posted, The app works without issue. However, when I clone the template and make the changes you outlined in https://github.com/tomduncalf/Issue4638AddListenerUndefined/commit/c31aa0ce03ff8ec8382c989d8570191bbf1a50cc , I get the same app.addListener error. I can't find differences but something must be going wrong with my template. I have created a [repo](https://github.com/lukewalz/Issue4638AddListenerUndefinedAttempt) for your reference. I will keep digging to see differences.

**Comment by tomduncalf** [comment]
Hey @lukewalz... so you see the issue with your repo that you linked there? I just cloned it and I don't see any issues. Is there anything specific I need to do to repro this? Are you running on the iOS simulator?

**Comment by lukewalz** [comment]
Yes I am running on the iphone 13 simulator

**Comment by tomduncalf** [comment]
OK @lukewalz, please feel free to reopen the issue if you need more assistance!

**Comment by lukewalz** [comment]
After weeks of trying different react-native, realm, and react-realm versions, this issue still persists. Even the template project (adjusted for my case) throws the same error. Do I possibly have the wrong tier of atlas? I am out of ideas. I have a repo that I hope will help you reproduce the error.

https://github.com/lukewalz/AwesomeProject

<img width="426" alt="Screen Shot 2022-07-07 at 1 56 42 AM" src="https://user-images.githubusercontent.com/25109068/177711022-d129ba09-0095-4068-b8c4-433848ac3a41.png">
.

**Comment by takameyer** [comment]
@lukewalz `app.addListener` was added to Realm in version `10.17.0`.  It seems to be that you somehow have an outdated version of `realm`.  Can you confirm the `realm` version in `node_modules/realm/package.json` is greater that `10.17.0`?  And also to rule out the obvious: 
```
cd ios
rm -rf Pods
rm Podfile.lock
rm -rf ~/Library/Developer/Xcode/DerivedData
pod install
```

**Comment by takameyer** [comment]
@lukewalz I ran your project just fine.  Here are the commands (with comments) that i typed:

```bash
git clone https://github.com/lukewalz/AwesomeProject.git
cd AwesomeProject
ruby -v # made sure my ruby version matched what was in the Gemfile
vi Gemfile #updated the gemfile to my current version (2.7.5)
bundle install #this installs cocoapods
yarn 
npx pod-install
npx react-native run-ios
```

**Comment by david011111000101** [comment]
I'm experiencing the same issue. The application runs but this error appears if you enable Chrome debugger in the app. 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/77883752/178094001-6a00a0c5-167d-4e71-b6c8-4ebb5324b71b.png">

**Comment by takameyer** [comment]
@david011111000101 we are not compatible with the Chrome debugger, so I would expect this error to pop up when it's turned on.  Please refer to our [`README`](https://github.com/realm/realm-js/blob/master/README.md#known-issues) for debugging alternatives.
