### ISSUE TITLE
There is a issue if use both realm-java and realm-js

### ISSUE THREAD

**Issue by wusuopu** [realm/realm-js#464]
In my android app, I use both realm-java and realm-js. After I created a object in reaml-java, then I query it in react-native with realm-js, but I get null.

This is my code:

```java
// create a Baby object
Realm realm = Realm.getDefaultInstance();

Baby baby = new Baby();
baby.name = "Baby Name";

realm.beginTransaction();
realm.copyToRealm(baby);
realm.commitTransaction();
```

```javascript
// then query in react-native
let baby = realm.objects('Baby').filtered('name = "Baby Name"')[0];
// but the result of baby is undefined
```

It won't get the result until I reload react-native JS. But I debug in chrome with stetho_realm, I can see the object has been created.

I don't know whether it's a bug, or maybe there is a error in my code.
But that's OK in my ios app with using both realm-swift and realm-js.

My environment are:

Mac OS 10.11
Android 5.1
node 5.3
realm-js 0.11.1
java version "1.8.0_66"
io.realm:realm-gradle-plugin:0.88.2

**Comment by appden** [comment]
@wusuopu Thanks so much for taking the time to report this issue. I'm working on fixing this bug right now, and it should work in the next release.

As a workaround for right now, I suggest sending a message to the JS when changes have been made, and in the JS, you should close (`realm.close()`) the Realm and re-open it (`realm = new Realm(config)`). That should allow it to access the latest data.

**Comment by wusuopu** [comment]
@appden Your advice is working for me. But I have find another way to avoid this issue.
When changes have been made in realm-java, I also execute a write operation in realm-js. In this way, I can allow it to access the latest data.

**Comment by chrisdukey** [comment]
I'm still getting this issue. I created a new React Native project and installed realm via npm (it installed version 1.12.0 of the realm npm module). On the Android side of things I'm using version 3.7.2 via the realm gradle plugin. I can add an object on the Android side of things but I only see an updated object count in RN if I use @wusuopu's method of executing an empty write. The problem with that is that the count is alway one behind the actual count. I see this appears to be fixed so am wondering is there something I'm missing in order for my change listener to see changes made via Java?

**Comment by gouravd** [comment]
Happens to me as well. I am on Realm-java 4.2.0 and Realm-JS 2.0.7

**Comment by afranchuk** [comment]
I was hoping after upgrading to the latest on both sides the issue would be fixed (similar to @gouravd). After reading over the changes in #469, it's not immediately apparent how those changes address the problem. The two classes don't seem to be used anywhere (maybe the `WeakRealmNotifier` through its base class somehow, but I can't see how `ExternalCommitHelper` is used by any other code).

**Comment by gouravd** [comment]
This issue is still persistent in latest Build 4.3.1

**Comment by afranchuk** [comment]
FWIW, I found the following workaround to be effective:
1. Add a java-side event that's fired into the javascript side when the realm changes (via `io.realm.Realm.addChangeListener` or `io.realm.DynamicRealm.addChangeListener`).
2. Debounce change events on the javascript side and do an empty `write()` on the realm for it to update.

**Comment by danleechina** [comment]
Hi, I want to ask a similar question here. How can I use both RealmSwift and RealmJS in an iOS app? When I try to integrate both RealmSwift and RealmJS, I run into duplicate symbol. How can I solve this?

**Comment by afranchuk** [comment]
@danleechina while that is similar, I would recommend you make a new issue. That sounds like an entirely different problem.

**Comment by githubdoramon** [comment]
For everyone still facing the issue, the key thing to make it work is the empty write. The Realm.close() and reopen didn't worked for me.
I am sending the event through a broadcast (from native to react) after I write stuff on the Android side, and doing the empty write on react native
