### ISSUE TITLE
react-native app crashing on variant release after adding realm .work fine in debug mode

### ISSUE THREAD

**Issue by midlajk** [realm/realm-js#4671]
**Description** My applucation works fine on build mode live testing but once we try to release it it keeps crashing with a single error message. Project works fine if unlink realm package in both buold and release mode . hence issue is with realm linking .i wish to know how to solve this

` E AndroidRuntime: Process: com.gocollect, PID: 25349 06-22 21:22:41.273 25349 29886 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: io.realm.react.util.SSLHelper result: 0 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.g(Unknown Source:341) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.t(Unknown Source:124) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.s(Unknown Source:2) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.q(Unknown Source:42) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.p(Unknown Source:1) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at io.realm.react.RealmReactModule.(Unknown Source:2) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at io.realm.react.a.c(Unknown Source:0) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.u.a(Unknown Source:41) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.e.b(Unknown Source:30) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.p.V(Unknown Source:35) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.p.W(Unknown Source:54) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.p.t(Unknown Source:36) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.p.d(Unknown Source:0) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.react.p$f.run(Unknown Source:69) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at java.lang.Thread.run(Thread.java:920) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: io.realm.react.util.SSLHelper 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at java.lang.Runtime.nativeLoad(Native Method) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at java.lang.Runtime.nativeLoad(Runtime.java:1121) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at java.lang.Runtime.load0(Runtime.java:927) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at java.lang.System.load(System.java:1620) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader$a.a(Unknown Source:201) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.d.h(Unknown Source:176) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.d.a(Unknown Source:2) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.b.a(Unknown Source:2) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: at com.facebook.soloader.SoLoader.g(Unknown Source:67) 06-22 21:22:41.273 25349 29886 E AndroidRuntime: ... 14 more 06-22 21:22:41.292 5096 5096 E DMASA[D]: [DropBoxReceiverManager]enqueueFCwork: ProcessErrorStateInfo is null 06-22 21:22:41.324 7583 5485 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 06-22 21:22:41.325 2362 2431 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 06-22 21:22:41.325 2362 7092 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 06-22 21:22:41.326 5176 5455 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 06-22 21:22:41.416 621 621 E BpTransactionCompletedListener: Failed to transact (-32) 06-22 21:22:41.417 530 536 E statsd : Predicate -7037417284711607308 dropping data for dimension key (10)0x2010101->10658[I] (10)0x30000->launch[S] 06-22 21:22:41.418 530 536 E statsd : Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10658[I] (10)0x30000->launch[S] 06-22 21:22:41.462 3156 3156 E pageboostd: Received HALT command code 2 06-22 21:22:43.568 2362 2446 E CscParser: update(): xml file exist 06-22 21:22:44.125 5816 15614 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:585 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 06-22 21:22:44.243 29930 29930 E com.gocollect: Not starting debugger since process cannot load the jdwp agent. 06-22 21:22:44.250 29930 29930 E USNET : USNET: appName: com.gocollect 06-22 21:22:44.608 2362 2446 E CscParser: update(): xml file exist

`these are the error logs obtained after running logcat command .
my realm dependency version i s    "realm": "^10.19.1"

npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2 
react-native: 0.68.0 => 0.68.0 
react-native-macos: Not Found

i have tried many ways herms is not enabled. i have linked the project

**Comment by fronck** [comment]
@midlajk Thanks for the report.  Can you share how you fixed it?
