### ISSUE TITLE
Unable to install realm in new directory - command failed

### ISSUE THREAD

**Issue by brianinator** [realm/realm-js#4677]
### How frequently does the bug occur?

All the time

### Description

I have a colleague who is unable to install via `npm install realm` in new directory. It throws an error with code 127 and outputs about the command failing at the `prebuild` step. I have another colleague who had no issue installing. I myself had no issue. We tried different node versions (14, 16) and tried to install with new react-native project.

### Stacktrace & log output

```shell
npm install realm
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /Users/k/node_modules/realm
npm ERR! command failed
npm ERR! command sh -c prebuild-install -r napi || cmake-js build
npm ERR! prebuild-install warn install unable to get local issuer certificate
npm ERR! sh: cmake-js: command not found
```

### Can you reproduce the bug?

Yes, always

### Version

10.19.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac OS Big Sur 11.6

### Build environment

System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 475.41 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/k/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 32.0.0, 32.1.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
    Python: 3.9.13 - /usr/local/opt/python/libexec/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Comment by 0anw0** [comment]
I downgraded my Node version to 14.16.0 And It worked with me!
