### ISSUE TITLE
Realm works only in debug mode

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-js#4692]
### How frequently does the bug occur?

All the time

### Description

when I open my app with debug mode, realm is woking correctly. but when I closed the debug mode not working correctly.(some schemas item I can write realm db, other I can't write). I tried to write console db object when debug mode online I can see db objects. when debug mode is offline I can't see db objects(I see empty object). I attached my realm open thunk.
<img width="948" alt="Screen Shot 2022-06-30 at 17 51 25" src="https://user-images.githubusercontent.com/44754934/176735368-7b6d290e-1e0c-49b9-90a6-351c936f0799.png">
### Stacktrace & log output

```shell
Empty db object.



```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1-)start app without debug mode

### Version

10.19.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS & Android

### Build environment

 "react-native": "0.68.2",

**Comment by MuratAkbaba006** [comment]
I found source of problem, problem is caused by uuid package. in my code I was using uuid for realm schemas primary key.
this usage throw error (Error: crypto.getRandomValues() not supported). I installed react-native-get-random-values package and I imported this package in index.js. problem is solved 💯  

uuid issues realeted this problem: [Link](https://github.com/uuidjs/uuid/issues/416)

**Comment by fronck** [comment]
@MuratAkbaba006 Thanks for reporting this AND for posting the solution :)
