### ISSUE TITLE
Realm Sync Error

### ISSUE THREAD

**Issue by inderpal31** [realm/realm-js#4694]
### How frequently does the bug occur?

Sometimes

### Description

![Screenshot 2022-06-30 at 5 42 22 PM](https://user-images.githubusercontent.com/108508371/176830999-83aa0e92-310a-4207-8ba1-4ab2d4e4c7dd.png)

### Can you reproduce the bug?

Not yet

### Version

"^10.10.1"

### What SDK flavour are you using?

Atlas Device Sync

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MAC

### Build environment

Which debugger for React Native: ..

**Comment by fronck** [comment]
We believe it should be fixed in the next release (which in imminent) by #4684

**Comment by inderpal31** [comment]
thanks for you reply but my is not not working and solution

**Comment by fronck** [comment]
We haven't released the fix yet.  Are you building from source?

**Comment by inderpal31** [comment]
no using package manager and also this issue (on server) is coming from yesterday previously it was working fine.

**Comment by fronck** [comment]
Strange.  Did you update the Realm version in your dependencies in the last few days, or has the error spontaneously started appearing on a version you've been using for a long time?

**Comment by inderpal31** [comment]
yes this is case and also I've reverted the code then it's remain the case

**Comment by inderpal31** [comment]
when will the next release will launch ?

**Comment by kneth** [comment]
@inderpal31 We did a release yesterday.

**Comment by kneth** [comment]
I am closing the issue. If you still observe the issue after upgrading to the latest release, please create a new issue.
