### ISSUE TITLE
iOS Crash in new version com.facebook.react.JavaScript (15): EXC_BAD_ACCESS (code=1, react native)

### ISSUE THREAD

**Issue by Archimondee** [realm/realm-js#4726]
### How frequently does the bug occur?

All the time

### Description

I getting issue in iOS with realm version "realm": "^11.0.0-rc.1", i debug in xcode and getting this error in xcode. And i using "@realm/react": "^0.3.1". So if you getting this error too just downgrade to 11.0.0-rc.0 it will solve temporary until realm team fixed this issue. 

com.facebook.react.JavaScript (15): EXC_BAD_ACCESS (code=1, react native)

### Can you reproduce the bug?

Not yet

### Version

11.0.0-rc.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS

### Build environment

Which debugger for React Native: ..
"react-native": "0.68.2",
"realm": "^11.0.0-rc.1",
"@realm/react": "^0.3.1",

### Cocoapods version

1.11.3

**Comment by takameyer** [comment]
@Archimondee At the moment `v11` is bound to specific React Native releases.
Version `11.0.0-rc.0` works with `react-native@0.68.*` and `11.0.0-rc.1` works with `react-native@0.69.*`

**Comment by takameyer** [comment]
Closing this as there are known workarounds for this.  It is also documented in the [release logs](https://github.com/realm/realm-js/releases)
