### ISSUE TITLE
React native can't get Realm Module on the android when activate new architecture

### ISSUE THREAD

**Issue by phanmduong** [realm/realm-js#4733]
### Description
I enable new architecture on the android and ios with react native 0.69.1. On ios, It's working. But on android, It's can't connect with realm native module.

### Stacktrace & log output
```shell
Missing Realm constructor. Did you run "pod install".
```

### Can you reproduce a bug?
Yes, always

### Reproduction Steps
1. in file android/gradle.properties set newArchEnabled=true
1. in file android/app/build.gradle set enableHermes: true
1. After that, I new Realm connection
`const realm = await Realm.open({
path: "testdatabase",
schema: [UserSchema],
schemaVersion: 1
})`
1. yarn android
I receive the error below.
![Screen Shot 2022-07-20 at 19 24 20](https://user-images.githubusercontent.com/18007936/179981067-5504dfdc-a5b0-480a-9556-662467496bd5.png)

### Version
^11.0.0-rc.1

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
Android Simulator '10.1_WXGA_Tablet_API_31(AVD) - 12'

**Comment by phanmduong** [comment]
If i set newArchEnabled=false in file android/gradle.properties. it's working on android.

**Comment by takameyer** [comment]
@phanmduong thanks for reporting this.  The new architecture is quite experimental, so at the moment we cannot guarantee everything will work when it is activated.  We will, however, be working to ensure we are fully compatible with it before it is activated by default.  

In any case, we will be investigating this issue.

**Comment by phanmduong** [comment]
@takameyer thanks guy, I will wait for you to fix this problem

**Comment by RalissonMattias** [comment]
Same problem here in RN 0.69.4

**Comment by joaotmachado** [comment]
> @phanmduong thanks for reporting this. The new architecture is quite experimental, so at the moment we cannot guarantee everything will work when it is activated. We will, however, be working to ensure we are fully compatible with it before it is activated by default.
> 
> In any case, we will be investigating this issue.

The point is that the Realm doesn't work at all with the new version of the react native (react native 0.69 or 0.70rc) when hermes is enable. Not to mention here the new architecture that become a legend.

Try to create a new project from the scratch (react native 0.69 or 0.70rc) and then install realm. It doesn't work in any circumstances. 

I believe that should be a priority for the Realm team, otherwise developers and companies who adopted React Native as solution will not be able anymore to use Realm in their projects. Depending on the project the migration from Realm to Watermelon is hard task. But I think we're running out of options here.

**Comment by takameyer** [comment]
@joaotmachado Please create a new issue with details on what is not working and how you configured your project.  This is definitely a priority for us.

**Comment by joaotmachado** [comment]
> @joaotmachado Please create a new issue with details on what is not working and how you configured your project. This is definitely a priority for us.

here it goes @takameyer thank you in advance: https://github.com/realm/realm-js/issues/4866

**Comment by joaotmachado** [comment]
@takameyer i updated the issue https://github.com/realm/realm-js/issues/4866 because React Native 0.70 is officially released and as expected Realm doesn`t work at all with [11.0.0-rc.1](https://www.npmjs.com/package/realm/v/11.0.0-rc.1).

**Comment by kneth** [comment]
@joaotmachado Please try to upgrade to RJS v10.2.0.

**Comment by takameyer** [comment]
This should be fixed for the latest Realm at v11 and `react-native` at v70
