### ISSUE TITLE
realm create() inside for-each make slow

### ISSUE THREAD

**Issue by fukemy** [realm/realm-js#4745]
### How frequently does the bug occur?

All the time

### Description

i have list of message, when using foreach, i write into realm. It make app slower

```
export class RoomMessage extends Realm.Object {
    key: 'string'
    roomId: 'string'
    value: 'string'

    static schema = {
        name: 'RoomMessage',
        primaryKey: 'roomId',
        properties: {
            key: 'string',
            roomId: 'string',
            value: 'string'
        }
    }
}
```

here is logic code:
```
messages.forEach(message => {
        if(realm){
            try{
                realm.write(() => {
                    const roomConfigDb = { 
                        'roomId': room.RoomId,
                        'key': message.Id,
                        'value': message }
                    realm.create('RoomMessage', message, true)
                })
            }catch (error) {
                console.log('write message to db failed', error)
            }
        }
....
```

### Stacktrace & log output

```shell
no log
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. create a huge list
2. foreach list
3. insert into realm inside foreach

### Version

im using lasted cli

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS simulator 15.5

### Build environment

Which debugger for React Native: ..
Check                               Value   Recommendation/Notes
npm ping                            ok
npm -v                              not ok  Use npm v8.15.1
node -v                             not ok  Use node v18.7.0 (current: v18.3.0)
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
which git                           ok      /usr/bin/git
Perms check on cached files         ok
Perms check on local node_modules   ok
Perms check on global node_modules  ok
Perms check on local bin folder     ok
Perms check on global bin folder    ok
Verify cache contents               ok      verified 13418 tarballs

### Cocoapods version

1.1.13

**Comment by tomduncalf** [comment]
Can you switch the order round so that you have your `forEach` inside the `realm.write`? `realm.write` creates and commits a new transaction, so is going to be slower if you do that every time.

So you'd have:

```
realm.write(() => {
  messages.forEach((message) => {
    realm.create(...);
  });
});
```

**Comment by fukemy** [comment]
Work as expected, thanks
