### ISSUE TITLE
Realm.List subscript accessor (`[]`) has incorrect return type

### ISSUE THREAD

**Issue by myou11** [realm/realm-js#4750]
### How frequently does the bug occur?

All the time

### Description

The return type for subscript access on a Realm.List seems to be incorrect. In the [index.d.ts from the realm package](https://github.com/realm/realm-js/blob/master/types/index.d.ts#L463), the definition of the subscript access is:
```
interface List<T> extends Collection<T> {
    [n: number]: T;
    .....
```
I think the return type should be `T | undefined` since specifying an `n` that is out of bounds does produce an `undefined` result.

### Can you reproduce the bug?

Yes, always

### Version

10.20.0-beta.5

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 15

### Build environment

Which debugger for React Native: ..
Hermes

### Cocoapods version

1.11.2

**Comment by kneth** [comment]
@myou11 Thank you for reporting. As both `Realm.List` and `Realm.Results` mimics `Array`, `undefined` is returned if you are out of bound. The TypeScript definition needs to be fixed.

**Comment by kneth** [comment]
After studying it a bit more careful, I think the type is correct. From the [discussion](https://github.com/microsoft/TypeScript/issues/13778), it is on purpose that `ReadonlyArray` doesn't have `T | undefined` as return type for `[]`.

**Comment by myou11** [comment]
Thanks for looking into this @kneth! I appreciate the linking to that Typescript discussion. After reading it, I understand why they have the return type as just `T` rather than `T | undefined`.
I do see that they have a tsconfig option `noUncheckedIndexedAccess` that provides the `| undefined` in the index signatures. Is there a way to get something like this for `Realm.List` and `Realm.Results`?

**Comment by kneth** [comment]
> Is there a way to get something like this for `Realm.List` and `Realm.Results`?

Just to be clear, you only want it for `Realm.List` and `Realm.Results`? I mean, `noUncheckedIndexedAccess` affects all arrays.

The rationale behind our current types is to promote that you guard against out-of-range situations. It means, accessing an element should never return `undefined`.

**Comment by myou11** [comment]
After re-visiting this, the types provided are good! For my use case before, I was already having checks to guard against out-of-range situations. I realize enabling the `noUncheckedIndexedAccess` would be a bit too strict for all our other uses similar to what is discussed in the discussion you linked.

You can disregard this issue. Thanks for the discussion!
