### ISSUE TITLE
Migration is required due to the following errors

### ISSUE THREAD

**Issue by sejr1996** [realm/realm-js#4752]
### How frequently does the bug occur?

All the time

### Description

I have a schema to which I have added a property, how should migrations be created?

```
Migration is required due to the following errors:
- Property 'ModuleSchema.phaseType' has been added.
```

The scheme is as follows:
```
import { ObjectSchema } from 'realm';

export class ModuleSchema {
  public _id: string;
  public name: string;
  public code: string;
  public phaseType: string;

  constructor(id: string, name: string, code: string, phaseType: string) {
    this._id = id;
    this.name = name;
    this.code = code;
    this.phaseType = phaseType;
  }

  public static schema: ObjectSchema = {
    name: 'ModuleSchema',
    primaryKey: '_id',
    properties: {
      _id: 'string',
      name: 'string',
      code: 'string',
      phaseType: 'string',
    },
  };
}

```

I define migration as follows, in development it works, but not in production:
```
export const schemas = [ContainerSchema.schema, ModuleSchema.schema];
export const schemaVersion = 4;

const realm = new Realm({
    path: 'custompath.realm',
    schema: schemas,
    schemaVersion: schemaVersion,
    migration: (oldRealm, newRealm) => {
      if (newRealm.schemaVersion > oldRealm.schemaVersion) {
      }
    },
  });
```

### Can you reproduce the bug?

Yes, always

### Version

"realm": "^10.19.5",

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS and Android

### Build environment

Which debugger for React Native: "react-native": "0.66.3"

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
If you don't need to populate the property for any existing objects, you can let Realm do the schema migration by removing `schemaVersion` and `migration` from your configuration.

For manual schema migrations, it is important that the schema version is increased.

See also [the documentation](https://www.mongodb.com/docs/realm/sdk/node/fundamentals/schema-versions-and-migrations/). For an example on how you can create objects during a manual migration, you can take a look at [one of our tests](https://github.com/realm/realm-js/blob/master/tests/js/migration-tests.js#L136-L186).

**Comment by sejr1996** [comment]
After many hours I managed to make it work, for that I had to call a function to perform the migration from the index.js file.
Call the function before loading the App.ts component:

import { AppRegistry } from 'react-native';

```
import App from './App';
import { name as appName } from './app.json';
import { runMigration } from './src/database/migrations';

runMigration();
AppRegistry.registerComponent(appName, () => App);
```
Funcion para ejecutar la migracion:
```
export const runMigration = () => {
  const realm = new Realm({
    schema: schemas,
    schemaVersion: schemaVersion,
    migration: (oldRealm, newRealm) => {},
  });

  realm.close();
};
```

**Comment by kneth** [comment]
@sejr1996 Happy to hear 🎉 

It makes sense since you should only run the migration once - and only when the app is launched.

I close the issue and I hope that future users will find your investigation useful.
