### ISSUE TITLE
Realm.List is saved as an object instead of array on MongoDB and causes MongoEncodingError (schema mismatch)

### ISSUE THREAD

**Issue by thespacemanatee** [realm/realm-js#4760]
### How frequently does the bug occur?

All the time

### Description

When I try to update a Realm object that has an array as one of its properties, that property will be overridden with an indexed object, unless that is the property that is being updated itself, like so:

### Expected

<img width="381" alt="Screenshot 2022-08-07 at 11 19 16 PM" src="https://user-images.githubusercontent.com/6837599/183298131-110f99c2-9be2-40f6-b433-6557b6e688fc.png">

### Issue

<img width="381" alt="Screenshot 2022-08-07 at 11 18 27 PM" src="https://user-images.githubusercontent.com/6837599/183298090-09efb159-3432-486b-a10e-d1263bf2be75.png">

### Stacktrace & log output

```shell
NA
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

```ts
if (fields?.green?.others) {
  fields.green.others = [...fields.green.others] // <-- workaround that prevents the below code
                                                 // from overriding the array property into an object
}
onChange?.({
  ...fields, // <-- existing Realm.Object
  [zone]: {
    ...zoneDetails,
    ...(field && { [fieldSection]: field }), // <-- changed field
  },
})
```

### Version

11.0.0-rc.1

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android, iOS

### Build environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.13.1 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Canary 9 Electric Eel 2022.1.1 Canary 9
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.2 => 46.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.69.3 => 0.69.3 
    Expo Workflow: bare
```

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
@thespacemanatee You might wish to consider to use [device sync](https://www.mongodb.com/docs/realm/introduction/#sync-data-with-mongodb-atlas) in the long run as it is a simpler solution for sync'ing data between your app and Atlas.

We try to emulate JavaScript objects as good as possible but they are backed by the database. For `Realm.List` and `Realm.Results`, we try to be as close to JavaScript's `Array` but as you can see, the illusion isn't perfect. You can try to use `toJSON()` instead of `[... ]`.

**Comment by thespacemanatee** [comment]
@kneth  We are currently using device sync, but for this specific use case, we needed to have a function to do the update instead because we wanted to do post-processing at the backend, and this function should be callable by a web application as well. Thanks for shedding some light on why this is happening and feel free to close this issue!

**Comment by kneth** [comment]
@thespacemanatee Thank you for providing some context. I understand that sharing logic with a web application can put some constraints on you. 

I will close the issue, but don't hesitate to create issues if you have further questions.
