### ISSUE TITLE
React Native Realm SDK: useApp and useUser hook does not re-render component on user login or logout

### ISSUE THREAD

**Issue by akashatnix** [realm/realm-js#4767]
### How frequently does the bug occur?

All the time

### Description

**React Native Realm SDK:**

I have a component that has following code in it:
(NOTE: This component is wrapped under `<AppProvider id="..."></AppProvider>`)

```
const realmApp = useApp();
const user = useUser();

const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);

useEffect(() => {
  console.log("user: ", user)
}, [user])

useEffect(() => {
  console.log("current user: ", realmApp.currentUser)
}, [realmApp])

const login = async (email, password) => {
  const credentials = Realm.Credentials.emailPassword(email, password)
  await realmApp.logIn(credentials);
  // setIsUserLoggedIn(true);
}
```

and I have a `<Button>` that triggers the `login(...)` method.

The login is successful but component does not get re-rendered. None of the `useEffect` hooks gets triggered.
If i uncomment `setIsUserLoggedIn(true);` then it will re-render component and both the `useEffect` hooks gets triggered.

`useApp()` or `userUser()` are not rendering the component. I had to implement state management to force component to re-render on login/logout.

### Can you reproduce the bug?

Yes, always

### Version

"realm": "^10.19.5"

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Samsung Android S21+ 5G (SM-G986W - 12)

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@akashatnix I see an `AppProvider`, but have you implemented the `UserProvider`?  This is necessary to trigger a re-render on your app on login.  Here is the documentation:
https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#using-the-user-provider

**Comment by takameyer** [comment]
The solution above should fix this issue.  If anyone has this issue with the proposed solution, please reopen this issue and provide more details so we can get to the bottom of it.
