### ISSUE TITLE
Pushing objects to list with same primary key doesn't update object in list, instead it creates a new object with the same id in ther list

### ISSUE THREAD

**Issue by EngineerDiab** [realm/realm-js#478]
Pushing objects to list with same primary key doesn't update object in list, instead it creates a new object with the same id in the list. 

Object with primary key updates properly but new objects are being pushed into the list with same id instead of updating those in the list

**Comment by appden** [comment]
Lists can hold duplicate objects just like arrays (and unlike sets), so that's the behavior I'm guessing that you're seeing. Realm won't let you create two objects with the same primary key. You can check if the object is already in the list with a query like: `list.filtered('id = $0', id)`

**Comment by alazier** [comment]
@EngineerDiab was this your issue? If not can you post some sample code to illustrate your issue?

**Comment by alazier** [comment]
If you are still having issues feel free to reopen

**Comment by club9822** [comment]
`NewsSchema = {
  name: "News",
  // primaryKey: "id",
  properties: {
    id: "double",
    author: {type:"string?",default:null},
    category: "string?",
    organizationName: "string?",
    tags: { type: "string?[]", },
    title: "string?",
    text: "string?",
    publishDate: "string?",
    status: "string?",
    introImage: "string?",
    viewCount: "string?",
    created: "string?",
    modified: "string?", 
  }
}`


`realm.write(function() {
                      res.data.forEach(function (news ) {
                        realm.create("News", {
                          id: news.id,
                          author: news.author,
                          category: news.category,
                          organizationName: news.organizationName,
                          tags: news.tags,
                          title: news.title,
                          text: news.text,
                          publishDate: news.publishDate,
                          status: news.status,
                          introImage: news.introImage,
                          viewCount: news.viewCount,
                          created: news.created
                        },true);
                      });
                    });`


duplicate item if exist instead of update
"react": "16.8.3",
 "react-native": "0.59.10",
"realm": "^2.29.1",
