### ISSUE TITLE
isRunningOnEmulator() in RealmReactModule.java not sufficient enough

### ISSUE THREAD

**Issue by fkranenburg** [realm/realm-js#4784]
### How frequently does the bug occur?

All the time

### Description

Whenever we try to put our React Native application in debug mode (on Macbook) the applicatie won't respond. After intensive research we found out that the check `isRunningOnEmulator` is not correct anymore. This issue relates to #2441

We fixed it to added the following code.

```
    private static boolean isRunningOnEmulator() {
        return (Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic"))
            || Build.FINGERPRINT.startsWith("generic")
            || Build.FINGERPRINT.startsWith("unknown")
            || Build.HARDWARE.contains("goldfish")
            || Build.HARDWARE.contains("ranchu")
            || Build.MODEL.contains("google_sdk")
            || Build.MODEL.contains("Emulator")
            || Build.MODEL.contains("Android SDK built for x86")
            || Build.MANUFACTURER.contains("Genymotion")
            || Build.PRODUCT.contains("sdk_google")
            || Build.PRODUCT.contains("google_sdk")
            || Build.PRODUCT.contains("sdk")
            || Build.PRODUCT.contains("sdk_x86")
            || Build.PRODUCT.contains("sdk_gphone64_arm64")
            || Build.PRODUCT.contains("vbox86p")
            || Build.PRODUCT.contains("emulator")
            || Build.PRODUCT.contains("simulator");
    }
```

Could you please update this for a future release?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Just enable 'debug' mode on the emulator

### Version

latest

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Mac

### Build environment

Which debugger for React Native: ..

**Comment by fronck** [comment]
@fkranenburg Thanks for reporting this, and thanks for the patch code.
Have you tested this code on real (non-simulator devices)?  And would you be able to share the contents of the `Build` variable on your emunators?

**Comment by fkranenburg** [comment]
@fronck no, I did not test this code on real devices. I actually found this list on stackoverflow here: https://stackoverflow.com/a/55355049.

And I think this check is very common because it is also used wider, for example in the `react-native-device-info` package:

https://github.com/react-native-device-info/react-native-device-info/blob/7358986d0836cf5a272abc48a4d0edd24478d13a/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L224

**Comment by fronck** [comment]
Okay, thanks for the references.  I'll make sure we update the checks.
Of course, you're more than welcome to create a PR if you're interested, and I'll make sure it gets reviewed.

**Comment by fkranenburg** [comment]
Thanks @fronck, I created a PR.

**Comment by fronck** [comment]
@fkranenburg Thanks a lot for contributing.  It's very much appreciated.
