### ISSUE TITLE
Assert from accessing preloaded realm file: group.cpp:286: [realm-core-0.100.2] Assertion failed: top_size == 9 [5790035, 9]

### ISSUE THREAD

**Issue by nerdcrack** [realm/realm-js#482]
See attached for the error log.
Realm React Native: 0.13.2
Realm Browser: 0.102.1 (73)
On devices running iOS 9.3.2

The error isn't spurious and is seen persistently during development.  It seems to be related to pre-packaged Realm database that is then copied from Bundle to Documents folder, and later accessed. 

It happens in two different setups. Setup 1 is where the pre-packaged realm file was first generated from Realm Browser importing from CSV files on a laptop, and then added to the app bundle. Setup 2 is where the pre-packaged realm file was generated from the app importing from CSV files at runtime on the device, and then downloaded back to the laptop for inclusion to the app bundle (i.e., bypassing the use of Realm Browser).

[realmjs_exception.txt](https://github.com/realm/realm-js/files/309762/realmjs_exception.txt)

**Comment by bmunkholm** [comment]
@nerdcrack It's super important for us to get this reproduced and fixed! So if you are able to reproduce it somewhat reliably we are really appreciate your help to reproduce this. The details you provide is unfortunately not sufficient. The basic info I get is that the Browser is not causing this. But creating a file and opening it is. That's being doing a million times a day by others so your setup/data or the way you store or retrieve it is highly interesting for us. You can send data and code in full confidentiality to help@realm.io.

**Comment by appden** [comment]
@nerdcrack We released `0.14.0-rc` and believe it may be fixed in that release. Will you please update to it and let us know whether or not that's the case. Thanks a lot!

**Comment by nerdcrack** [comment]
Sure thing!

**Comment by appden** [comment]
@nerdcrack Checking in to see if you've been able to update and confirm this is fixed. Thanks!

**Comment by nerdcrack** [comment]
@appden Sorry I don't think I could get to it until later this week. Will let know no later than next Monday. Thanks!

**Comment by nerdcrack** [comment]
@appden Got a link error when building my app (Xcode 7.3.1, iOS 9.3.2, iPhone 6) with Realm v0.14.0 
ld: targeted OS version does not support use of thread local variables in __ZN5realm4util13get_thread_idEv for architecture arm64

Reverted to v0.13.2 and everything worked fine again. Any idea? Thanks!

**Comment by appden** [comment]
@nerdcrack Thank you for reporting that issue. This is caused by React Native projects targeting a minimum of iOS 7 by default. I have a fix that I will hopefully release as `0.14.1` today, but I would really appreciate if you could switch your project (temporarily) to target iOS 8 so I can know if the main issue of this thread was fixed. If you're still seeing the `Assertion failed: top_size == 9`, then I would like to see if we can get a fix for that into `0.14.1` as well. Thanks again!

**Comment by appden** [comment]
@nerdcrack We just released `0.14.1-rc`. Would you mind updating to that and seeing if your issue is resolved? Thanks!

**Comment by nerdcrack** [comment]
@appden The release worked (re: deployment target iOS 8.0), without the issue seen again. Thanks for the great work!

**Comment by appden** [comment]
Awesome, thanks for the update @nerdcrack!

**Comment by appden** [comment]
We just released the official `0.14.1`. Thanks again!

**Comment by nerdcrack** [comment]
That's great, and keep up the good work!
