### ISSUE TITLE
App is Crashing at launch After installing Realm into React Native Project(Only Android)

### ISSUE THREAD

**Issue by jaskarjhon** [realm/realm-js#4832]
### How frequently does the bug occur?

All the time

### Description

We didn't use Hermes Engine. We are using JSC
Please see the stacktrace for error

### Stacktrace & log output

```shell
E SoLoader: couldn't find DSO to load: libturbomodulejsijni.so
08-26 11:32:46.255  7373  7851 E SoLoader: 	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.*****/lib-main flags = 1]
08-26 11:32:46.255  7373  7851 E SoLoader: 	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.*****-WR6iHZylXxpW6vmckz5csw==/lib/arm flags = 0]
08-26 11:32:46.255  7373  7851 E SoLoader: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
08-26 11:32:46.255  7373  7851 E SoLoader: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
08-26 11:32:46.255  7373  7851 E SoLoader: 	Native lib dir: /data/app/com.*****-WR6iHZylXxpW6vmckz5csw==/lib/arm
08-26 11:32:46.255  7373  7851 E SoLoader:  result: 0
08-26 11:32:46.260  7373  7851 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
08-26 11:32:46.260  7373  7851 E AndroidRuntime: Process: com.*****, PID: 7373
08-26 11:32:46.260  7373  7851 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libturbomodulejsijni.so
```

### Can you reproduce the bug?

Yes, always

### Version

10.20.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@jaskarjhon Thanks for reporting this.  We will take a look and see if we can also reproduce this.  In the meantime, can you perhaps provide the contents of your `package.json` so we can verify that there aren't any incompatibilities with your dependencies?

**Comment by takameyer** [comment]
@jaskarjhon Do you also have the new architecture activated?  It seems odd that there are `turbomodulejsi` errors there if you are using JSC.  Another option is to use our release candidate for v11, which has a JSI implementation and supports Hermes.  This could probably remove the crash you are having:
```
npm install realm@11.0.0-rc.1
```
I assume you are using RN v0.69.x?

**Comment by jaskarjhon** [comment]
@takameyer FYI, I am using react native 0.63.x version.......two months back, i used realm 10.11.0 version, it worked in both iOS & android.....When i ran the same code now, it is crashing in android and it is working fine in iOS......So I upgraded to the new version of realm 10.20.0....There also facing the same crash when app launch

**Comment by takameyer** [comment]
Ah.  You may need to upgrade React Native then.  I think [this PR](https://github.com/realm/realm-js/pull/4725/files) is causing the issue, as it is importing methods from `turbomodules`.  I'm going to try to find what the minimum React Native version this would work on.  Sorry for the inconvenience!

**Comment by jaskarjhon** [comment]
@takameyer having small doubt,
Actually, this PR has been merged(july 15) in the latest release.....When i tried to use version 10.11.0, there also facing this same turbomodules error

**Comment by takameyer** [comment]
@jaskarjhon so it also doesn't work with 10.11.0?  You done a full clean build of your project?  
`cd android && ./gradlew clean`

**Comment by jaskarjhon** [comment]
Yes. For 10.11.0 also, itis crashing @ launch
I have done all the cleaning procedures for build

**Comment by takameyer** [comment]
What was exactly was updated to cause this crash?

**Comment by jaskarjhon** [comment]
@takameyer Nothing from react native project......i just run the same code which worked two months back, got the Crash now......from system side, installed ndk and ndk side by side.....now, i have uninstalled that too....Still facing crash

**Comment by takameyer** [comment]
@jaskarjhon Sounds like you may have an issue with your Android development environment.  Can you try running one of our realm templates to make sure it's possible to run a simple realm project?

Instructions here:
https://www.npmjs.com/package/@realm/react-native-template-js

**Comment by takameyer** [comment]
@jaskarjhon I was able to reproduce this with RN 63.4.  With the same code on RN 69.4 there was no crash.  I am unsure what exact version of Realm of React Native caused this crash, but I can be sure that upgrading React Native will remove this issue.

**Comment by takameyer** [comment]
As I do not see a way that we could fix our current release to be compatible with RN 63.4, I am going to close this ticket.  We will soon make an update to our `package.json` to reflect the minimum required version of React Native.

**Comment by takameyer** [comment]
Our current minimum version of React Native is `0.64.0`.

**Comment by jaskarjhon** [comment]
Thanks @takameyer 
I am facing some weird behaviour while using Realm.....
Please let me know, if you could help me out here

First Scenario ::
1. I have created new react native app using react-native init command with 0.63.4 version.
2. Then, I edited package.json and added "realm": "^10.11.0" in dependencies
3. After that, I deleted node modules and package.lock file.
4. Atlast, I run "npm install && react-native run-android"
5. For this scenario, **App is crashing**

Second Scenario ::
1. I have created new react native app using react-native init command with 0.63.4 version.2. 
2. After that, I deleted node modules and package.lock file.
3. Then, I run "npm install && npm install realm@10.11.0"
4. For this scenario, **App is not crashing**

**Comment by takameyer** [comment]
@jaskarjhon is it possible your gradle file has been changed?  Refer to the [tagged templates](https://github.com/facebook/react-native/tree/v0.63.4/template) to compare any configuration files in your `android` directory.

**Comment by jaskarjhon** [comment]
@takameyer The only thing I changed from template is react version from 16.13.1 -> 17.0.0......... With 16.13.1, I am facing some react related crashes.....I changed the react version to make it work......

**Comment by takameyer** [comment]
Maybe there is still something being cached.  Can you try:
```
rm -rf node_modules
npm cache clean -f
watchman watch-del-all
rm -rf $TMPDIR/metro*
rm -rf $TMPDIR/react-native*
npm install
```

**Comment by takameyer** [comment]
Can you also verify that the realm version in `node_modules/realm/packages.json` is correct?

**Comment by jaskarjhon** [comment]
<img width="1394" alt="Screenshot 2022-08-29 at 1 15 33 PM" src="https://user-images.githubusercontent.com/95403595/187150867-258be962-80a3-40ff-8300-bfebe058c76f.png">


There is a difference in file

**Comment by jaskarjhon** [comment]
@takameyer

**Comment by jaskarjhon** [comment]
<img width="1367" alt="Screenshot 2022-08-29 at 1 15 33 PM" src="https://user-images.githubusercontent.com/95403595/187151131-225b2f7d-8810-43d6-97ba-0a206694b0fc.png">

There is a difference in file @takameyer

**Comment by takameyer** [comment]
That's the issue then.  It is installing version 10.20.0.  Make sure you remove the `^` from your `package.json`.

**Comment by takameyer** [comment]
This also explains why it stopped working suddenly.  https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

**Comment by jaskarjhon** [comment]
Thanks for the help man @takameyer .Its working now......
