### ISSUE TITLE
Realm.App.Sync is undefined

### ISSUE THREAD

**Issue by rf1804** [realm/realm-js#4837]
### How frequently does the bug occur?

All the time

### Description

Realm.App.Sync is not accessible and throws undefined every time

### Stacktrace & log output

```shell
`Realm.App.Sync.initiateClientReset(app, path);`

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'initiateClientReset')

`Realm.App.Sync.setLogLevel(user, 'debug');`

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'setLogLevel')

`console.log(Realm.App.Sync, 'Realm.App.Sync');`

> undefined 'Realm.App.Sync'
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

`Realm.App.Sync.initiateClientReset(app, path);`

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'initiateClientReset')

`Realm.App.Sync.setLogLevel(user, 'debug');`

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'setLogLevel')

`console.log(Realm.App.Sync, 'Realm.App.Sync');`

> undefined 'Realm.App.Sync'

### Version

10.20.0

### What SDK flavour are you using?

Atlas Device Sync

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

IOS 15.

### Build environment

Which debugger for React Native: ..

### Cocoapods version

10.20.0

**Comment by kneth** [comment]
@rf1804 Are you using TypeScript? If you do, can you share your TS configuration?

The error message `Possible Unhandled Promise Rejection` is a bit odd - do you know where it comes from?

If it is possible for you, can you create a small project which can reproduce it?

**Comment by rf1804** [comment]
Hi @kneth We are facing this issue in Tracker Project as well as main project, here i'm sharing the Tracker project which has the same issue on this particular line:-
[https://github.com/easyeat-ai/RealmReactTutorial/blob/2058fc1006cf317140977f5680051433d5bd8a23/providers/TasksProvider.js#L62](https://github.com/easyeat-ai/RealmReactTutorial/blob/2058fc1006cf317140977f5680051433d5bd8a23/providers/TasksProvider.js#L62)

`Realm.App.Sync.setLogLevel(user, 'debug');`

> Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read properties of undefined (reading 'setLogLevel')

[https://github.com/easyeat-ai/RealmReactTutorial](https://github.com/easyeat-ai/RealmReactTutorial)

**Comment by kneth** [comment]
@rf1804 Oh, I see it now. The first argument in `setLogLevel()` (and `setLogger()`) is not a user (`Realm.User`) but an app (`Realm.App`).

Moreover, setting the log level and the logger must be done *before* opening the Realm. You can add it at https://github.com/easyeat-ai/RealmReactTutorial/blob/2058fc1006cf317140977f5680051433d5bd8a23/realmApp.js#L6:

```js
Realm.App.Sync.setLogLevel(app, 'debug');
Realm.App.Sync.setLogger(app, (level, message) => console.log(`[${level}] ${message}`));
```

**Comment by rf1804** [comment]
@kneth Still same issue
Even this is a issue console.log(Realm.App.Sync, 'Realm.App.Sync'); -> undefined

Code has been updated as you suggested

<img width="1436" alt="Screenshot 2022-08-30 at 11 40 12 PM" src="https://user-images.githubusercontent.com/35443934/187511896-830b9223-0c5b-47da-b874-c845eee6164d.png">
