### ISSUE TITLE
Attempting to create (and update if exists) with primary generates error.

### ISSUE THREAD

**Issue by saeho** [realm/realm-js#485]
According to the doc, I should be able to "realm.create(name, {...}, true)" which should create if document doesn't exist, and update if it exists.

But doing this creates an error.

**Comment by appden** [comment]
Would you mind pasting in the error that you're getting? Also, it would be helpful to see the schema and full call to `realm.create()`. Thanks!

**Comment by saeho** [comment]
Schema:
```
Conversation.schema = {
  name: 'Conversation',
  primaryKey: 'id',
  properties: {
    id: 'string',
    users: 'string',
    status: 'string',
    type: 'string'
  }
};
```

Realm write:
```
Realm.write(() => {
  Realm.create('Conversation', {
    id: conversation._id,
    users: conversation.users.join(','),
    status: conversation.status,
    type: conversation.type
  }, true);
});
```

Realm error:
```
Error: Attempting to create an object of type 'Conversation' with an exising primary key value.(…)
```

Note. The error message was copied "as is". The typos are in the actual error message.

**Comment by alazier** [comment]
Just fixed that typo. Not sure how you are getting this error though. Doesn't seem possible to get this message unless `false` is passed as the third argument to create.

**Comment by saeho** [comment]
My primaryKey "id" is a string. In the example its an "int". Do you think this could cause this issue?

**Comment by saeho** [comment]
I just did console.log(Realm.create) and this is what I got:

```
function create(name,obj){
return (0,_index.getRealm)().create(name,obj);}
```

This tells me that the Realm.create() function does not accept a 3rd parameter. This explains everything about this problem I'm facing.

The version I'm using is 0.13.2 which is the latest.

**Comment by appden** [comment]
@saeho We have no `getRealm` in our codebase. It appears that you're using some kind of wrapper around `Realm` that is exposing its own `create()` method. Can you confirm?

**Comment by saeho** [comment]
Ah. Thank you. This was a separate unrelated issue.
