### ISSUE TITLE
 Reactnative: Access to invalidated Results objects/already opened on current thread with different schema

### ISSUE THREAD

**Issue by krishanMohanVemra** [realm/realm-js#4860]
### How frequently does the bug occur?

All the time

### Description

I have tried with One schema at a time approach. when I try to close the DB facing issue **:Access to invalidated Results objects**

async fetchData(options) {
    const { schema, filter, sort, schemaName } = options;
        Realm.open({
          schema: [schema],
        }).then(realm => {
          let responseData = realm.objects(schema);
          if (filter) {
            responseData = responseData.filtered(filter);
          }
          if (sort) {
            responseData = responseData.sorted(sort);
          }
          resolve(responseData);
          realm.close()
        })
        }
        
        
        
And when try without close DB and switch 1 schema to another schema facing issue :**already opened on current thread with different schema.'**

### Can you reproduce the bug?

Yes, always

### Version

"realm": "10.19.5"

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

android 29

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@krishanMohanVemra 

Try to remove `realm.close()`. We are caching Realm instances, so `Realm#open()` will return the same instance. With `Realm#close()` you will close all instances, and your query results will be invalidated.

**Comment by krishanMohanVemra** [comment]
@kneth  Do you have any sample code to follow to same approach because When I tried to shift one schema to another schema that time :I am facing  below error:
**already opened on current thread with different schema**

const getRealm = (schemaName) => {
  return Realm.open({
    schema: [schemaName],
  });
}

Usage: 
async fetchData(options) {
    const { schema, filter, sort,} = options;
    const realmRef = await getRealm(schema);
     let responseData = realmRef.objects(schema);
}


When I tried to open all schema's together that's work fine for me.
but my requirement is  to open one schema at a time so when I tied to switch btw the schema, facing error :
**already opened on current thread with different schema**

**Comment by kneth** [comment]
@krishanMohanVemra 

If you need to update your schema, you have to close all Realms (and probably relaunch the app). You must also increament the schema version. For the fine details, please take a look at https://www.mongodb.com/docs/realm/sdk/react-native/examples/modify-an-object-schema/.

On the other hand, if you need two different Realm (different schemas), you have to specify the file name (it defaults to `default.realm`) by using the `path` option in your configuration.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
