### ISSUE TITLE
Realm 11.0.0-rc.1 doesn't work with React Native 0.70

### ISSUE THREAD

**Issue by joaotmachado** [realm/realm-js#4866]
### How frequently does the bug occur?

All the time

### Description

When try to create a new react native project 0.70 with hermes enabled or disable  + realm  11.0.0-rc.1 the app crashes after the opening process.

### Stacktrace & log output

```shell
        2022-09-05 13:13:47.375 8633-8633/com.nome E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.nome/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Zd4M_cuYSz0cPdjEGTNQAA==/com.nome-w281IwntRzzNNg4jTfhLPg==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~Zd4M_cuYSz0cPdjEGTNQAA==/com.nome-w281IwntRzzNNg4jTfhLPg==/lib/arm64
     result: 0
2022-09-05 13:13:57.355 8633-8695/com.nome A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8695 (mqt_js), pid 8633 (com.nome)
2022-09-05 13:14:16.696 8755-8755/com.nome E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.nome/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Zd4M_cuYSz0cPdjEGTNQAA==/com.nome-w281IwntRzzNNg4jTfhLPg==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~Zd4M_cuYSz0cPdjEGTNQAA==/com.nome-w281IwntRzzNNg4jTfhLPg==/lib/arm64
     result: 0
2022-09-05 13:14:18.444 8755-8811/com.nome A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8811 (mqt_js), pid 8755 (com.nome)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Create a RN project: npx react-native init project.
- Install Realm: yarn add 11.0.0-rc.1.
- Insert `import Realm from "realm"` on the app.js file.
- Run yarn android.

### Version

11.0.0-rc.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS Monterey 12.5.1

### Cocoapods version

1.11.3

**Comment by RalissonMattias** [comment]
It also happens here on windows

**Comment by kneth** [comment]
We are aware that RN 0.70 is breaking our recent v11 release candidates. We are working on releasing a new one with support of RN 0.70.

**Comment by joaotmachado** [comment]
@kneth i just tested the new version: [11.0.0-rc.2](https://www.npmjs.com/package/realm/v/11.0.0-rc.2).

- It works with Hermes enabled.
- The App crashes when the New Architecture is enabled.

**Comment by takameyer** [comment]
This is now resolved for the latest Realm at v11 and `react-native` at v70

**Comment by goingtorean** [comment]
still got this problem when use react native 0.70.6 and realm 11.3.1. Any helps?

**Comment by takameyer** [comment]
@goingtorean Please open a separate issue with more details and we can look into it.
