### ISSUE TITLE
How init realm and use in all files?

### ISSUE THREAD

**Issue by antoxi4** [realm/realm-js#487]
I Just try create file with shemes and import to another. But keep error what shema is missing in realm.
```javascript
let store = {
  name: 'stores',
  properties: {
    userId: {type: 'string'},
    stores: {type: 'string'},
    filters: {type: 'string'},
    sorting: {type: 'string'}
  }
}

let user = {
  name: 'users',
  properties: {
    users: {type: 'string'}
  }
}

var realm = new Realm({
      schema: [store, user]
    });

export default class DBConnector {
  constructor() {
  }

  getItem(param) {
    realm.objects('users');
  }
}
```

This case doesnt work. Any Ideas?

**Comment by appden** [comment]
Would you mind pasting in the error message that you're getting? The code looks good. The `getItem()` method doesn't really do anything yet, but it doesn't look like you should be getting an error.

**Comment by antoxi4** [comment]
Thanks for fast answer))And sorry))Yesterday i getting error)But now i cant replay it))
