### ISSUE TITLE
BadChangeset Error

### ISSUE THREAD

**Issue by inderpal31** [realm/realm-js#4886]
### How frequently does the bug occur?

Sometimes

### Description

ending session with error: UPDATE instruction had incorrect partition value for key "_partition_key" { expectedPartition: catalog_id=61d5d22e34308c0e70bcad21, foundPartition: catalog_id=undefined (ProtocolErrorCode=212)

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps

When DB is full and gives 512MB error

### Version

10.19.4

### What SDK flavour are you using?

Atlas Device Sync

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

MAC

### Build environment

Which debugger for Vue JS: ..

**Comment by kneth** [comment]
@inderpal31 

The error message is `UPDATE instruction had incorrect partition value for key "_partition_key" { expectedPartition: catalog_id=61d5d22e34308c0e70bcad21, foundPartition: catalog_id=undefined`. Can you verify that you are using the correct value for the partition key and not `undefined`?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
