### ISSUE TITLE
[@realm/react] Broken useQuery types in combination with realm v11.0.0-rc.1

### ISSUE THREAD

**Issue by haikov** [realm/realm-js#4905]
### How frequently does the bug occur?

All the time

### Description

The easiest way to reproduce the issue is to use [expo realm template](https://github.com/expo/examples/tree/master/with-realm) and upgrade realm packages to the latest versions:

```
"@realm/react": "^0.3.2",
"realm": "^11.0.0-rc.1",
```

After doing that `useQuery` hook types [used on this line](https://github.com/expo/examples/blob/master/with-realm/App.tsx#L14) break with the following error:

```
Argument of type 'typeof Task' is not assignable to parameter of type 'string | ((new () => Task) & ObjectClass<any>)'.
  Type 'typeof Task' is not assignable to type '(new () => Task) & ObjectClass<any>'.
    Type 'typeof Task' is not assignable to type 'new () => Task'.
      Types of construct signatures are incompatible.
        Type 'new (realm: Realm, values: Unmanaged<unknown>) => Task' is not assignable to type 'new () => Task'.
```

For reference, previous `useQuery` type was:

```typescript
<Task>(type: string | ((new () => Task) & Realm.ObjectClass)) => Realm.Results<Task & Realm.Object>
```

After reading [changelog for v11.0.0](https://github.com/realm/realm-js/releases/tag/v11.0.0-rc.0) it feels like the change to Class-based models might have caused the typing change in `useQuery` as well (which is not intended?).

### Can you reproduce the bug?

Yes, always

### Version

@realm/react: 0.3.2; realm: 11.0.0-rc.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

React Native (Expo)

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@haikov Thanks for reporting this.  The fix is now released in `0.4.0-rc.0`.  You can install this using the `next` tag:
```
npm install @realm/react@next
```

**Comment by haikov** [comment]
Thank you! I can confirm that it works with `0.4.0-rc.0` version of `@realm/react`, _please feel free to close the issue when it's best, now or after the 0.4.0 release_.

**Comment by takameyer** [comment]
We will be keeping `0.4.0-rc.0` as a release candidate until `v11` is officially released.  `0.4.0` will have a hard dependency on `realm >= 11.0.0`.

Thanks for testing this out!
