### ISSUE TITLE
Realm 11.0.0-rc.2 makes the app extremely slow on iOS

### ISSUE THREAD

**Issue by joaotmachado** [realm/realm-js#4923]
### How frequently does the bug occur?

All the time

### Description

The App with React Native 0.70 + Realm 11.0.0-rc.2  + Hermes true + New Architecture False = extremely slow experience on the App.

ps: android is working fine.
ps 2: both android and iOS still crashes the App at the opening when New Architecture True.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

- Upgrade realm to Realm 11.0.0-rc.2.
- Enable Hermes.
- Build the App and test it.

### Version

Realm 11.0.0-rc.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS Monterey 12.5.1

### Build environment

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 103.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/Desktop/app/app/node_modules/.bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/userbr/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 24.0.8215888
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
@joaotmachado  We are aware of a [performance regression](https://github.com/realm/realm-js/issues/3940#issuecomment-1238168460). To understand the regression better, please answer the following questions:

* Do you compare v11.0.0-rc.2 against v11.0.0-rc.1 or v10.21.1?
* Is it slow when you create new objects or when you access objects?

> ps 2: both android and iOS still crashes the App at the opening when New Architecture True.

We are currently testing the new architecture in https://github.com/realm/realm-js/pull/4924. If you can see a missing test scenario, please comment on the pull request so we can broaden our tests.

**Comment by joaotmachado** [comment]
> @joaotmachado We are aware of a [performance regression](https://github.com/realm/realm-js/issues/3940#issuecomment-1238168460). To understand the regression better, please answer the following questions:
> 
> * Do you compare v11.0.0-rc.2 against v11.0.0-rc.1 or v10.21.1?
> * Is it slow when you create new objects or when you access objects?
> 
> > ps 2: both android and iOS still crashes the App at the opening when New Architecture True.
> 
> We are currently testing the new architecture in #4924. If you can see a missing test scenario, please comment on the pull request so we can broaden our tests.

@kneth the React Native new release 0.70.1 apparently solved it.

**Comment by kneth** [comment]
@joaotmachado Thank for the update. I will close the issue with this good news.

**Comment by joaotmachado** [comment]
@kneth Have there been any changes to the RC in the last few days? Projects with Realm 11.0.0-rc.2 +  Hermes true are slow again. Both Android and iOS.
