### ISSUE TITLE
Bi-directional relationships

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#493]

**Comment by jasonmerino** [comment]
Hey @alazier, I'm curious on what the status on this is. I'm working on an app that was written in Obj-C and used core data's bi-directional relationship modeling and now am porting it to React Native and it would be lovely if I didn't have to do the JavaScript equivalent of what is described in this issue https://github.com/realm/realm-cocoa/issues/677 to get that to work.

Really enjoying realm BTW. 👍

Thanks!

**Comment by kristiandupont** [comment]
While this is an important feature, there are a number of issues that are higher priority right now, so sadly this probably won't be available in the near future.

**Comment by jasonmerino** [comment]
@kristiandupont thanks for the update. :)

**Comment by kneth** [comment]
The inverse relationships (`linkingObjects`) solve it.
