### ISSUE TITLE
App crash after path changed

### ISSUE THREAD

**Issue by HuuNguyen312** [realm/realm-js#4941]
### How frequently does the bug occur?

All the time

### Description

I have a switch account feature.
After User switch account, I update dbPath by uid

``` js
import React from 'react'
import { RealmProvider } from '@/core/data/database/Database'
import { useAppSelector } from '@/core/data/redux/hook'
import { uidSelector } from '@/features/auth/data/redux/AuthSelector'

const RealmWrapper: React.FC = ({ children }) => {
  const uid = useAppSelector(uidSelector) || 'Default'
  // const dbPath = useMemo(() => `${uid}.realm`, [myId])
  const dbPath = `${uid}.realm`
  return (
    <RealmProvider path={dbPath} realmRef={realmRef}>
      {children}
    </RealmProvider>
  )
}

export default RealmWrapper
```

``` js
"dependencies": {
  "react": "18.1.0",
  "react-native": "0.70.1",
  "realm": "^v11.0.0-rc.2",
  "@realm/react": "^0.3.2",
}
```
But I am facing a crash after switch account or logout
<img width="410" alt="image" src="https://user-images.githubusercontent.com/9895294/191677205-d0e24fbe-b4d0-45d0-8f94-711831c0704b.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/9895294/191697054-f6d7568e-3aae-41ad-adff-bea6f8b2a077.png">

Is there a problem with my code or is there another solution?
Thanks

### Stacktrace & log output

```shell
{ [Error: Exception in HostFunction: Access to invalidated Results objects]
  componentStack: '\n    in MoreScreen (created by SceneView)\n    in StaticContainer\n    in EnsureSingleNavigator (created by SceneView)\n    in SceneView (created by BottomTabView)\n    in RCTView (created by View)\n    in View (created by Screen)\n    in RCTView (created by View)\n    in View (created by Background)\n    in Background (created by Screen)\n    in Screen (created by BottomTabView)\n    in RNSScreen (created by AnimatedComponent)\n    in AnimatedComponent\n    in AnimatedComponentWrapper (created by InnerScreen)\n    in Suspender (created by Freeze)\n    in Suspense (created by Freeze)\n    in Freeze (created by DelayedFreeze)\n    in DelayedFreeze (created by InnerScreen)\n    in InnerScreen (created by Screen)\n    in Screen (created by MaybeScreen)\n    in MaybeScreen (created by BottomTabView)\n    in RNSScreenContainer (created by ScreenContainer)\n    in ScreenContainer (created by MaybeScreenContainer)\n    in MaybeScreenContainer (created by BottomTabView)\n    in RCTView (created by View)\n    in View (created by SafeAreaInsetsContext)\n    in SafeAreaProviderCompat (created by BottomTabView)\n    in BottomTabView (created by BottomTabNavigator)\n    in Unknown (created by BottomTabNavigator)\n    in BottomTabNavigator (created by MainScreen)\n    in MainScreen (created by SceneView)\n    in StaticContainer\n    in EnsureSingleNavigator (created by SceneView)\n    in SceneView (created by SceneView)\n    in RCTView (created by View)\n    in View (created by DebugContainer)\n    in DebugContainer (created by MaybeNestedStack)\n    in MaybeNestedStack (created by SceneView)\n    in RNSScreen (created by AnimatedComponent)\n    in AnimatedComponent\n    in AnimatedComponentWrapper (created by InnerScreen)\n    in Suspender (created by Freeze)\n    in Suspense (created by Freeze)\n    in Freeze (created by DelayedFreeze)\n    in DelayedFreeze (created by InnerScreen)\n    in InnerScreen (created by Screen)\n    in Screen (created by SceneView)\n    in SceneView (created by NativeStackViewInner)\n    in Suspender (created by Freeze)\n    in Suspense (created by Freeze)\n    in Freeze (created by DelayedFreeze)\n    in DelayedFreeze (created by ScreenStack)\n    in RNSScreenStack (created by ScreenStack)\n    in ScreenStack (created by NativeStackViewInner)\n    in NativeStackViewInner (created by NativeStackView)\n    in RCTView (created by View)\n    in View (created by SafeAreaInsetsContext)\n    in SafeAreaProviderCompat (created by NativeStackView)\n    in NativeStackView (created by NativeStackNavigator)\n    in Unknown (created by NativeStackNavigator)\n    in NativeStackNavigator (created by AppNavigator)\n    in EnsureSingleNavigator\n    in BaseNavigationContainer\n    in ThemeProvider\n    in NavigationContainerInner (created by AppNavigator)\n    in AppNavigator (created by App)\n    in Unknown (created by RealmWrapper)\n    in RealmWrapper\n    in RNGestureHandlerRootView (created by GestureHandlerRootView)\n    in GestureHandlerRootView (created by App)\n    in I18nextProvider (created by App)\n    in Provider (created by App)\n    in ThemeProvider (created by App)\n    in Suspense (created by App)\n    in RNCSafeAreaProvider (created by SafeAreaProvider)\n    in SafeAreaProvider (created by App)\n    in App\n    in RCTView (created by View)\n    in View (created by AppContainer)\n    in RCTView (created by View)\n    in View (created by AppContainer)\n    in AppContainer\n    in Nobu(RootComponent)',
  isComponentError: true }
```

### Can you reproduce the bug?

Yes, always

### Version

v11.0.0-rc.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

Which debugger for React Native: ..

**Comment by HuuNguyen312** [comment]
``` js
  const result = useQuery(Task)

  useEffect(() => {
    console.log('####Result', result?.length)
  }, [result])
```

It seems that app crashes when I use `useQuery`

**Comment by kneth** [comment]
Please try to upgrade to `@realm/react` v0.4.0-rc.0 (see https://github.com/realm/realm-js/pull/4907) - it fixes a number of compatibility issues with Realm JS v11.0.0-rc.X. 

```sh
npm install @realm/react@next
```

**Comment by HuuNguyen312** [comment]
I tried "@realm/react": "^0.4.0-rc.0",
The crash still happens

<img width="410" alt="image" src="https://user-images.githubusercontent.com/9895294/191701716-8216914a-ab93-4f30-8a49-c7b18bbf5d1a.png">

**Comment by kneth** [comment]
What happens if you wrap it in a memo to prevent it from being GCed:

```js
const result = useQuery(Task);
const tasks = useMemo(() => result.sorted("createdAt"), [result]);
useEffect(() => {
    console.log('####Result', tasks?.length)
  }, [tasks]);
```

**Comment by HuuNguyen312** [comment]
Thanks for your response. The crash still happens :(

**Comment by kneth** [comment]
The error message `Access to invalidated Results objects` indicates that the underlaying Realm might be closed. When you switch from one Realm to the next, do you close the Realm? Can you avoid closing it?

**Comment by HuuNguyen312** [comment]
I'm using @realm/react, not manual realm management.

``` js

     // RealmProvider:
    useEffect(() => {
      ...
      return () => {
        if (realm) {
          realm.close();
          setRealm(null);
        }
      };
    }, [configVersion, realm, setRealm]);
```
It seems that realm only close when RealmProvider is unmounted.
Please share with me how to close realm by RealmProvider
Call realmRef.close or something else

**Comment by kneth** [comment]
@HuuNguyen312 I will suggest that you don't call `realm.close()`. The reason is that we cache Realm instances, and `realm.close()` will close **all** instances.

As we cache, only the first call to `Realm.open()` is expensive.

**Comment by HuuNguyen312** [comment]
@kneth I'm sorry, I misunderstood your idea. I don't close the Realm when I switch from one Realm to the next.
All child components inside RealmProvider is re-render after changing the realm path
But this crash still occurs.

I tried to change the realm path in your example. It's working fine.
But console.log('####Result' was called twice
- First time: data of old path
- Secondary time: data of new path

Can the crash occurs at the first time?
<img width="405" alt="image" src="https://user-images.githubusercontent.com/9895294/192424596-38a1aeee-531b-4101-b441-77072fb6a4f8.png">

This issue only occurs in my project.
My error screen ABC is a tab in the BottomTabNavigator(@react-navigation/bottom-tabs)

**Comment by kneth** [comment]
@HuuNguyen312 What happens if you manually remove https://github.com/realm/realm-js/blob/master/packages/realm-react/src/RealmProvider.tsx#L129?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
