### ISSUE TITLE
Infinite loop calling my repo (using realm) with useFocusEffect

### ISSUE THREAD

**Issue by pipocadr** [realm/realm-js#4952]
### How frequently does the bug occur?

All the time

### Description

Hi,

I bring realm/react to my project and I would like to fetch my data inside an useFocusEffect.

I create a simple class repository to separete the realm code from page code.

![image](https://user-images.githubusercontent.com/1215749/192347101-dc906c6c-e22b-4cf8-8b76-4689b74e01f1.png)

![image](https://user-images.githubusercontent.com/1215749/192347250-2395a253-320f-4140-bf76-ee638ff8e528.png)

So, the problem is with the code below:

![image](https://user-images.githubusercontent.com/1215749/192348278-18ccf223-a5a1-48b3-b5c7-559bc0352b54.png)

The page is getting in loop because the reference from carRepository is changing every time.

If a put the whole code from the carRepository inside the useFocusEffect works fine (The difference is the **const realm = useRealm()** is put outside the function).

I don't know what's the best approach to dealing with this case

### Can you reproduce the bug?

Yes, always

### Version

^0.3.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Any version

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@pipocadr Instead of `getById()` you can use [`useObject()`](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/useObject.tsx#L34-L46)

**Comment by pipocadr** [comment]
Hi @kneth,

Thanks for your help.

I put on top of my page this hook instead of calling my class repo!

![image](https://user-images.githubusercontent.com/1215749/192358733-a6fb39f6-1e86-4de9-9729-5b3b319bb820.png)

and

![image](https://user-images.githubusercontent.com/1215749/192359106-91dc3c3f-fc82-4070-9697-cac3233dd3c9.png)

Still getting in loop

**Comment by pipocadr** [comment]
Hi @kneth,

I was able to make work putting another useCallback on my method carRepository.getById and adding the realm object on dependency list.

Thanks for your help.
