### ISSUE TITLE
Memory leak in realm.write() inside a loop

### ISSUE THREAD

**Issue by anderpaz** [realm/realm-js#4953]
### How frequently does the bug occur?

All the time

### Description

I'm writing data every 20ms to a schema with this structure:

![image](https://user-images.githubusercontent.com/72525631/192535808-e6e98df3-9822-4d78-b4bd-a1bb02f874e6.png)

My function that is called in this loop is described below:

![image](https://user-images.githubusercontent.com/72525631/192536326-b38aeb93-f13f-4085-827e-48599116dbff.png)

The problem occurs that as I record, the memory increases until it reaches a limit that the cell phone freezes, I already got up to see if the consumption was in another part of the application, but as soon as I comment the add function the problem no longer occurs.

Detail that consumption that starts to grow is identified by the Profiler as Others

starting recording
![image](https://user-images.githubusercontent.com/72525631/192536878-8220c6f7-331a-4ecb-b25c-70a8bf4ee2bc.png)

1800 records
![image](https://user-images.githubusercontent.com/72525631/192537674-b2d97925-9ee9-49d5-a522-e5b4aad56de6.png)

7600 records
![image](https://user-images.githubusercontent.com/72525631/192538286-7933568d-ad70-4b2a-a139-55278b2864f2.png)

Loop finished and ram consumption remains the same.
![image](https://user-images.githubusercontent.com/72525631/192538394-fbb3d8ef-a068-4504-9d24-3eb2af3bf14c.png)

I did a search to see if I could find a solution and I ended up not finding it, I saw some cases with a similar problem but I didn't find a solution. Before I opened the bank with new Realm and the problem is the same.
Could anyone help?

Platform : Android
targetSdkVersion = 31

"react": "18.1.0",
"react-native": "0.70.1",
"realm": "^11.0.0-rc.2",
"react-native-reanimated": "^2.9.1",

project.ext.react = [
    enableHermes: true,
]

### Can you reproduce the bug?

Yes, always

### Version

11.0.0-rc.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by anderpaz** [comment]
No one had this memory leak issue?

**Comment by kneth** [comment]
As you create objects, the Realm file will grow. Realm is memory-mapping the Realm file, and it is expected that the virtual memory usage will increase. 

Do you have any other Realm instances (same configuration) open in your app? If so, consider to move the `Realm.open()` out of your loop and share the instance through out the app.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.

**Comment by PEZO19** [comment]
@kneth Any ideas on how to calculate/mitigate the footprint? To me, the sales point of Realm is low memory footprint, but I ran into the same issue. +~6K objects => +~60MB (based on the screenshot) => ~ 10kb / object (with 6-7 properties?) seems absurdly high. I have issues of the same scale. If that is normal, then I think I can not use Realm for a heavy, data/database oriented app. :(

**Comment by kneth** [comment]
@PEZO19 In version 11.3.0-rc.0 introduced online compaction of Realm files, and the issue should be smaller. If you continue to observe after upgrading to our latest release, please create a new issue.
