### ISSUE TITLE
Specific `removeListener` not working.

### ISSUE THREAD

**Issue by joshuapinter** [realm/realm-js#496]
With the following `addListener` and `removeListener`, the listener remains active (i.e. doesn't get removed):

```js
Realm.addListener('change', this.realmChanged.bind(this));

Realm.removeListener('change', this.realmChanged.bind(this));

// A change to Realm will still trigger a call to realmChanged().
```

Am I using this correctly?

Thanks!

Josh

**Comment by joshuapinter** [comment]
Okay, I figured the `.bind(this)` was causing issues so I was able to get the following to work just fine: 

```js
this.realmChanged = this.realmChanged.bind(this);

Realm.addListener('change', this.realmChanged);

Realm.removeListener('change', this.realmChanged);
```

I'm not a JS expert so was an obvious solution?

Also, it would be useful to put an example of `removeListener` in your non-API docs so others don't accidentally fall into a similar trap.

Thanks!

**Comment by appden** [comment]
Great suggestion @joshuapinter. We'll do that! We're going to be redoing the docs for that very soon because we are expanding on where you can listen for events.
