### ISSUE TITLE
model in schema is not being recognized

### ISSUE THREAD

**Issue by texas697** [realm/realm-js#497]
> "react-native": "^0.26.2",
"realm": "^0.13.2"

I have followed the example with implementing realm in my react-native project. I am getting a error saying my object "User" is not being found in the schema

> Possible Unhandled Promise Rejection (id: 0):
Object type 'User' not found in schema.
Error: Object type 'User' not found in schema.
    at sendRequest (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:108020:7)
    at sendRequest (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:108035:8)
    at Object.callMethod (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:107916:1370)
    at Realm.<anonymous> (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:107825:771)
    at Object.setUser (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:110439:16)
    at Login._success (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:105614:19)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:105655:6
    at tryCallOne (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:9617:8)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:9703:9
    at JSTimersExecution.callbacks.(anonymous function) (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:7605:13)

User Model
```
import Realm from 'realm';

class Claim extends Realm.Object { }
Claim.schema = {
    name: 'Claim',
    properties: {
        marketId: 'int'
    }
};

class User extends Realm.Object { }
User.schema = {
    name: 'User',
    properties: {
        token: 'string',
        userId: 'int',
        name: 'string',
        email: 'string',
        loginExpireDate: 'date',
        claims: { type: 'list', objectType: 'Claim', optional: true }
    }
};

export default new Realm({ schema: [Claim, User] });
```

Service were I am trying to set the User Object
```
'use strict';

import _ from 'lodash/core';
import jwtDecode from 'jwt-decode';
import q from 'q';
import Realm from './../realm/user';

const UserService = (() => {

    return {
        setUser: (response) => {

            let user = [];
            let deferred = q.defer();

            let decoded = jwtDecode(response.access_token);

            let model = {
                token: response.access_token,
                userId: decoded.nameid,
                name: 'string',
                email: decoded.unique_name,
                loginExpireDate: new Date().getTime() + (30 * 24 * 60 * 60 * 1000)
            }
            Realm.write(() => {
                user = Realm.create('User', model);
            });

            deferred.resolve(user);
            return deferred.promise;
        }
    }
})();
module.exports = { UserService };
```

**Comment by alazier** [comment]
Instad of passing in the string 'User' can you instead try passing in the `User` class?

```user = Realm.create('User', model);```

**Comment by texas697** [comment]
coming up as a undefined variable

**Comment by alazier** [comment]
I guess that makes sense since the classes aren't exported from your User Model file. When using the string do you get the same error when turning off chrome debug mode?

**Comment by texas697** [comment]
yes, it is the same. what is strange is this setup worked on a previous project. I have tripled checked to make sure I didnt do anything different. i am using same versions of all resources. and the database is being set. I tested it by changing the model and I got a error saying I needed to do a migration.

**Comment by appden** [comment]
@texas697 Would you mind sharing your code so we can more effectively diagnose this issue? You can send it to `help@realm.io` if you want to keep it private.

**Comment by alazier** [comment]
When you change the model you should need to do a migration, unless you delete the old Realm files. I suspect that deleting the old Realm files will resolve the issue you are seeing (you can find them with `console.log(realm.path)`). What confuses me is why you are not getting the migration required message.  As @appden working sample code would also be helpful here.

**Comment by texas697** [comment]
Sure let me remove some un-needed code. I mentioned the migration error just to let you know I was troubleshooting what i could. I have deleted and reinstalled many times hoping it would work. I will send email shortly

**Comment by texas697** [comment]
ok i need to do some more trouble shooting. I just tested the stripped down version I am going to send you and it worked as it should. so I will do piece by piece and see whats going wrong. ill get back tonight to let you know. thanks!

**Comment by texas697** [comment]
ok I cannot figure out why it is not working. It worked when I had one model setup but not when I am using multiple? I am sending project with some hard coded temp/token, etc..  Should not have any problem installing npm packages. appreciate the help.

**Comment by texas697** [comment]
solution is:

I had a /realm folder with multiple files.
user.js
claim.js
etc....

```
import Realm from 'realm';

export default class User extends Realm.Object { }
User.schema = {
    name: 'User',
    properties: {
        token: 'string',
        userId: 'string',
        name: 'string',
        email: 'string',
        loginDate: 'string'
    }
};
export default new Realm({ schema: [User] });
```

each file was exporting a new instance of Realm

> export default new Realm({ schema: [User] });

That was the issue...

So I instead exported the class: 

```
import Realm from 'realm';

export default class User extends Realm.Object { }
User.schema = {
    name: 'User',
    properties: {
        token: 'string',
        userId: 'string',
        name: 'string',
        email: 'string',
        loginDate: 'string'
    }
};
```

And then I created a /realm
index.js

```
import Realm from 'realm';

import Claim from './claim';
import User from './user';

export default new Realm({ schema: [Claim, User] });
```

And now the only import statement I use throughout the project is

> import realm from './../realm/index';

that solved the problem

**Comment by appden** [comment]
Thanks so much for taking the time to explain the solution here so we can refer back to it in the future for others who run into this.

**Comment by stlemon** [comment]
@texas697 I met the same issuer, and I used your solution .But it doesn't work. So, does it has another solution ?
