### ISSUE TITLE
Update OpenSSL version in node dependencies

### ISSUE THREAD

**Issue by devWaleed** [realm/realm-js#4984]
### How frequently does the bug occur?

All the time

### Description

I have an app that uses Realm js as a database. I recently submitted my app to Playstore for release and it rejected my app with the following error:

<img width="980" alt="Screen Shot 2022-10-05 at 7 59 35 PM" src="https://user-images.githubusercontent.com/4759525/194100696-0f9cbe27-3284-42cd-bbcf-221ae7077676.png">

After doing some search through VS Code, I get that OpenSSL 1.1.1g is listed as dependency of this package. Also on Google's guide to fix this error also mentions Realm JS SDK having this open ssl version here: https://support.google.com/faqs/answer/12576638

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Build the app
2. Submit to the Play store
3. Gets rejected with the error as shown above

### Version

10.13.0 (latest version uses the same dependencies i checked)

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android and iOS

### Build environment

Which debugger for React Native: ..

**Comment by beisert1** [comment]
we are encountering the same issue, started happening this week. We are on older realm version v6 but still same error just on older version of openssl 1.1.1b

**Comment by oseach1** [comment]
I have a same issue in version 10.20.0-beta.2.

I read all comments.
But I can't understand this issue solution.

Solution is update version? Or react-native core is update so  I don't update realm version?

**Comment by devWaleed** [comment]
@kneth Yes, I saw that the realm core has updated the dependency list. But since it was listed in the realm dependency list as well. I thought an update is required.  

So if I simply update my realm to the latest version 10.21.1 it should resolve the issue?

**Comment by kneth** [comment]
@oseach1 

> I have a same issue in version 10.20.0-beta.2.

You need to update to v10.20.0-beta.4 or v11.0.0-rc.X (X = 0,1,2)

**Comment by kneth** [comment]
@devWaleed 

> So if I simply update my realm to the latest version 10.21.1 it should resolve the issue?

Yes!

**Comment by Ping5841** [comment]
> 
I still had the same issue in version v10.20.0-beta.5

**Comment by kneth** [comment]
@Ping5841 v10.20.0-beta.5 should be using OpenSSL 1.1.1n. But in general I will suggest that you upgrade to v11.0.0.

**Comment by paritosh-yadav** [comment]
Hi @kneth ,
I check for all the above mentioned version, but all of them contains `OPENSSL_VERSION=1.1.1g`
Kindly help.

**Comment by devWaleed** [comment]
This is how I solved it:

I updated the realm version to the latest, then I changed the OPENSSL_VERSION in node_modules since the latest version also has the dependencies.list file with the old version., compiled my app and submitted it to Play store. It was accepted and approved for public distribution.

I think updating it to the latest version will solve the issue. You can check this by compiling the app with the new version and submitting it for review. If there is a problem, they will show you the error within the 24 hours period.

**Comment by trapridge** [comment]
> we are encountering the same issue, started happening this week. We are on older realm version v6 but still same error just on older version of openssl 1.1.1b

Were you able to solve this on v6 somehow?

**Comment by kneth** [comment]
> Were you able to solve this on v6 somehow?

We don't plan to update version 6.

**Comment by AnassHmida** [comment]
> 

Hey , did you change the OPENSSL_VERSION to 3.0 ?

**Comment by AnassHmida** [comment]
> This is how I solved it:
> 
> I updated the realm version to the latest, then I changed the OPENSSL_VERSION in node_modules since the latest version also has the dependencies.list file with the old version., compiled my app and submitted it to Play store. It was accepted and approved for public distribution.
> 
> I think updating it to the latest version will solve the issue. You can check this by compiling the app with the new version and submitting it for review. If there is a problem, they will show you the error within the 24 hours period.

Hey , did you change the OPENSSL_VERSION to 3.0 ?

**Comment by victorroatt** [comment]
I'm still getting the error on v10.20.0-beta.X. Can anybody help me?

**Comment by kneth** [comment]
@victorroatt 

> I'm still getting the error on v10.20.0-beta.X. Can anybody help me?

Please upgrade to v11.2.0 (v10.20.0-beta.X ended with the release of v11.0.0).

**Comment by kneth** [comment]
We are not planning to backport fixes to our old beta versions. Moreover, I believe v10.20.0-beta.5 is using OpenSSL 1.1.1n.

**Comment by gfirmacionpear** [comment]
Has anyone found a fix for this? Is updating realm to v11 the only solution?

**Comment by bishalkc** [comment]
> Has anyone found a fix for this? Is updating realm to v11 the only solution?

I see same dependencies on v11 too

I see url-parse and openssl being reported in v10.24.0

**Comment by kneth** [comment]
We are currently (https://github.com/realm/realm-js/pull/5252) working on upgrading Realm Core which will give you OpenSSL 3.
