### ISSUE TITLE
Aggregation functions return `undefined` when they should return `null`

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#4994]
### How frequently does the bug occur?

Seen once

### Description

Our types declare that the `min`, `max` and `sum` can return `null`:

```typescript
min(property?: string): number | Date | null;
max(property?: string): number | Date | null;
sum(property?: string): number | null;
avg(property?: string): number;
```

But the implementation shows that `min`, `max` and `avg` actually return `undefined` when there are no objects in the collection:

```typescript
const realm = new Realm({
  schema: [{
    name: "Item",
    properties: { value: "int" }
  }],
});
realm.objects("Item").min("value"); // returns `undefined`
realm.objects("Item").max("value"); // returns `undefined`
realm.objects("Item").avg("value"); // returns `undefined`
realm.objects("Item").sum("value"); // returns `0`
```

We are actually testing, to ensure this behaviour ☝️
https://github.com/realm/realm-js/blob/master/tests/js/list-tests.js#L1389-L1392

### Can you reproduce the bug?

Yes, always

### Version

10.21.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Tested on Node.js

**Comment by kneth** [comment]
[The return value from aggregation function](https://github.com/realm/realm-js/blob/master/src/js_util.hpp#L150) is using `std::optional<Mixed>`, and with zero objects it has no value. The return value is then set to `undefined` (https://github.com/realm/realm-js/blob/master/src/node/node_return_value.hpp#L119).

**Comment by kraenhansen** [comment]
@kneth right. I think the easiest would be to update the types.
