### ISSUE TITLE
Copy of realm object

### ISSUE THREAD

**Issue by atomfried** [realm/realm-js#5021]
### Problem

It has been years and this has been discussed on various occasions but there still is no straightforward way to create a (managed or unmanaged) copy of a realm object. Copying all properties to a new object breaks for embedded objects. The commonly suggested workaround of encoding to and decoding from JSON breaks for linkedObjects due to circularity. We have to write individual copy code for each schema.

### Solution

Make it so you can copy stuff:
* reinsert an object under a new primary key
* create unmanaged copies (i believe swift exposed this via copyFromRealm) 
 
Isn't this a most basic feature of a database? 
Incidentally, what is the maintenance situation of realm?

Take care
M

### How important is this improvement for you?

It makes me consider migrating to a different database...

**Comment by atomfried** [comment]
Correction: There seems to be one generic way to create unmanaged copies using the (undocumented?) JsonSerializationReplacer:
`const pojo = JSON.parse(JSON.stringify(liveObject, Realm.JsonSerializationReplacer))`
However serializing (in some cases) all sorts of linked objects just to duplicate an entry still feels wrong...?

**Comment by kneth** [comment]
@atomfried With v11.0.0 we have released https://github.com/realm/realm-js/pull/4997 which will deal with circular object graphs.

**Comment by atomfried** [comment]
Hello kneth,
I am aware of Realm.Object.toJSON. As far as I understand it serves the same purpose as JsonSerializationReplacer -- both functions seem undocumented and neither solve the problem (see edition of my second post).

**Comment by kneth** [comment]
We consider plain JavaScript objects as our unmanaged objects.

As mentioned, v11.0.0 has some changes to `toJSON()`. In particular we have removed `Realm.JsonSerializationReplacer`.

You mention conflicts with primary keys, and one what is to use `Realm#create` in update mode instead of insert mode. In the example below, the second call to `Realm#create` is a [upsert](https://en.wikipedia.org/wiki/Merge_(SQL)#upsert) operation.

```js
const Realm = require("realm");

const Parent = {
  name: "Parent",
  primaryKey: "id",
  properties: {
    id: "int",
    child: "Child"
  },
};

const Child = {
  name: "Child",
  primaryKey: "key",
  properties: {
    key: "int",
    value: "string",
  },
};

let realm = new Realm({ schema: [Parent, Child] });
realm.write(() => {
  realm.create("Parent", {
    id: 1,
    child: {
      key: 7,
      value: "seven" 
    }
  });
});

let pojo = realm.objectForPrimaryKey("Parent", 1).toJSON();
pojo.id = 2;
realm.write(() => {
  realm.create("Parent", pojo, true);
});

console.log(realm.objects("Child").toJSON());
console.log(realm.objects("Parent").toJSON());
realm.close();
```

The output is (only one `Child` object):

```
[ { key: 7, value: 'seven' } ]
[
  { id: 1, child: { key: 7, value: 'seven' } },
  { id: 2, child: { key: 7, value: 'seven' } }
]
```

**Comment by atomfried** [comment]
First of all thank you for your answer. I adopted your code sample to illustrate the issue. If the parent contains the children as linking objects then children cannot be created from POJOs, as the parent needs to be passed as live object:
```

const Realm = require("realm");

const Parent = {
  name: "Parent",
  primaryKey: "id",
  properties: {
    id: "int",
    children: {
      type: 'linkingObjects',
      objectType: 'Child',
      property: 'parent'
    }
  },
};

const Child = {
  name: "Child",
  primaryKey: "key",
  properties: {
    key: 'int',
    value: 'string',
    parent: 'Parent'
  },
};

const realm = new Realm({ schema: [Parent, Child]});
const parent = realm.write(() => realm.create('Parent', { id: 0}));
const child = realm.write(() => realm.create('Child', {key: 7, value: 'seven', parent: parent}));

// this will break in realm 11.0.0 (realm will try to reinsert the parent resulting in pk conflict):
realm.write(() => realm.create('Child', {...child.toJSON(), key: 8})); 

// to create a child we need a live parent:
realm.write(() => realm.create('Child', {...child.toJSON(), parent: parent, key: 8})); 
```
Arguably a corner case but it cost me a lot of time to understand what's going on. Some documentation on toJSON would be helpful. Is the resulting object a true POJO? In that case `child.toJSON()` would always contain the parents collection of linking children (except for `child` itself) which seems very inefficient...?

**Comment by atomfried** [comment]
Thank you for clarifying. I see now that using toJSON + **upsert** is indeed a generic method of duplicating realm objects.
However I am still worried about performance when my Child collection grows large as `child.toJSON().parent.children` (referring to the above example) seems to be fully populated (except for `child`). In fact in some use cases the parent object holds itself a lot of data, so currently I'm still duplicate child objects field by field in order to avoid fetching the parent.
Is there a better way of doing this that I am not aware of?
Otherwise it would make sense to make population of referenced objects optional in toJSON or to have some "duplicate with new ID" method...?

**Comment by kneth** [comment]
@atomfried Sorry for the late reply.

>  avoid fetching 

Realm is lazy-loading and is using memory-mapping so fetching is controlled by the database - and should be a little as possible.

My question is: why do you need to duplicate your objects? Could you use a [to-many relationship](https://www.mongodb.com/docs/realm/sdk/node/fundamentals/relationships-and-embedded-objects/#std-label-node-to-many-relationship) to avoid it?

> Otherwise it would make sense to make population of referenced objects optional in toJSON or to have some "duplicate with new ID" method...?

A low-level method for this is definitely doable, and it might help your use case. I leave the issue open to track this idea to a feature.

**Comment by atomfried** [comment]
> @atomfried Sorry for the late reply.

Not at all, thanks for replying :)

> Realm is lazy-loading and is using memory-mapping so fetching is controlled by the database - and should be a little as possible.

However the object returned by toJSON is not lazy-loading, correct? (That's what I was getting at when I asked whether the resulting object is a POJO).

> 
> My question is: why do you need to duplicate your objects? 

So I have a bunch of items (`child` objects) which the user can modify through a react native app. This requires creating a temporary copy of the item (a draft) that is being edited until the user requests, if they please, to save the changes. The user may also choose the save the draft to a new item and to keep the original unchanged. Very basic. However the objects are subject to child-parent relationships as discussed above.

> Could you use a [to-many relationship](https://www.mongodb.com/docs/realm/sdk/node/fundamentals/relationships-and-embedded-objects/#std-label-node-to-many-relationship) to avoid it?

I do not use embedded objects because I also need to query items across parents and each item needs to know it's parent.

Since my data model is subject to occasional changes I am looking for a convenient way to copy the items rather than copying them "manually". But from my understand toJSON is no good here because it _will_ fetch the parent object which notably slows down our app.

**Comment by kneth** [comment]
It might not solve all use cases, but v12 does support the spread operator.
