### ISSUE TITLE
iOS bug report 

### ISSUE THREAD

**Issue by rodrigobertolottizinsp** [realm/realm-js#5039]
### How frequently does the bug occur?

Sometimes

### Description

SIGABRT please_report_this_issue_in_github_realm_realm_core 

We started experimenting this bug a couple of weeks ago. It has happened to three users so far, all with them using iOS 15 and 16. 

### Stacktrace & log output

```shell
3
please_report_this_issue_in_github_realm_realm_core

4	
realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)

5	
realm::util::terminate_with_info(char const*, char const*, long, char const*, std::initializer_list<realm::util::Printable>&&)

6	
void realm::util::terminate_with_info<unsigned long&, unsigned long>(char const*, int, char const*, char const*, unsigned long&, unsigned long&&)

7	
realm::StringIndex::StringIndex(unsigned long, realm::ArrayParent*, unsigned long, realm::ClusterColumn const&, realm::Allocator&)

8	
realm::Table::refresh_index_accessors()

9	
realm::Group::create_table_accessor(unsigned long)

10	
realm::Group::do_get_table(unsigned long)

11	
realm::Transaction::check_consistency()

12	
realm::DB::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, realm::DBOptions)

13	
realm::DB::open(realm::Replication&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::DBOptions)

14	
realm::DB::create(std::__1::unique_ptr<realm::Replication, std::__1::default_delete<realm::Replication> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::DBOptions)

15	
realm::_impl::RealmCoordinator::open_db()

16	
realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&)

17	
realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, realm::util::Optional<realm::VersionID>)

18	
realm::Realm::get_shared_realm(realm::RealmConfig)

19	
realm::js::RealmClass<realm::js::realmjsi::Types>::create_shared_realm(realm::js::JsiEnv, realm::RealmConfig, bool, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiVal>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiVal> > > > > > >&&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, realm::js::Protected<realm::js::JsiFunc>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, realm::js::Protected<realm::js::JsiFunc> > > >&&)

20	
realm::js::RealmClass<realm::js::realmjsi::Types>::constructor(realm::js::JsiEnv, realm::js::JsiObj, realm::js::Arguments<realm::js::realmjsi::Types>&)

21	
realm::js::realmjsi::ObjectWrap<realm::js::RealmClass<realm::js::realmjsi::Types> >::create_constructor(realm::js::JsiEnv)::{lambda(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)#1}::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const

22	
function.h:505:16
std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const

23	
JSCRuntime.cpp:1158:13
facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::HostFunctionMetadata::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**)

95	
JSCRuntime.cpp:1260:14
facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)

96	
jsi-inl.h:228:18
facebook::react::JSIExecutor::invokeCallback(double, folly::dynamic const&)

97	
function.h:505:16
std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()()

98	
function.h:505:16
facebook::react::tryAndReturnError(std::__1::function<void ()> const&)

99	
RCTMessageThread.mm:69:20
facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)

100	
function.h:505:16
___ZN8facebook5react16RCTMessageThread8runAsyncENSt3__18functionIFvvEEE_block_invoke

105	
RCTCxxBridge.mm:384:12
+[RCTCxxBridge runRunLoop]
```

### Can you reproduce the bug?

Not yet

### Version

11.0.0-rc.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iPad Mini (5 Gen) (iPad11,2), iPad Air (5th generation) (iPad13,17)

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.11.2

**Comment by kneth** [comment]
@rodrigobertolottizinsp Thank you for reporting. From the stack trace it looks like it occurs when you open a Realm. Do you have any error messages?

Last week we released version 11.0.0, and upgrading might be a good idea. 

Please state your React Native version, other third party libraries (reanimated, etc.) and JS engine (hermes or JSC).

**Comment by rodrigobertolottizinsp** [comment]
Hi, thanks for the reply.
I'll send you the dependencies of out project. 

We are using the old react native architecture so we have Hermes disabled for iOS. 

"dependencies": {
    "@bugsnag/react-native": "7.17.3",
    "@miblanchard/react-native-slider": "2.1.0",
    "@react-native-async-storage/async-storage": "1.17.8",
    "@react-native-clipboard/clipboard": "1.10.0",
    "@react-native-community/datetimepicker": "6.3.1",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-community/push-notification-ios": "1.10.1",
    "@react-native-community/slider": "4.2.4",
    "@react-navigation/compat": "5.3.20",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "5.14.9",
    "async-mutex": "0.3.2",
    "color": "4.2.3",
    "eventemitter3": "4.0.7",
    "jsc-android": "250230.2.1",
    "moment": "2.29.4",
    "moment-timezone": "0.5.34",
    "native-base": "github:cristianoccazinsp/NativeBase#b62417221f11442c51e0522342ff0c8cf6d69d80",
    "natural-orderby": "2.0.3",
    "prop-types": "15.8.1",
    "query-string": "7.1.1",
    "react": "17.0.2",
    "react-native": "0.67.4",
    "react-native-background-fetch": "4.1.2",
    "react-native-background-upload": "github:cristianoccazinsp/react-native-background-upload#c569c7e95dd7dcb9a9fa72cd8967fcd73f55153a",
    "react-native-base64": "0.2.1",
    "react-native-blob-util": "0.16.2",
    "react-native-camera": "github:cristianoccazinsp/react-native-camera#0354b4cc59286f7b3a83de08c99309adb11bf074",
    "react-native-compass-heading": "github:cristianoccazinsp/react-native-compass-heading#cbb96952a644de9af1947db545d45927fd9a18a6",
    "react-native-config-reader": "4.1.1",
    "react-native-device-info": "10.0.2",
    "react-native-easy-grid": "0.2.2",
    "react-native-foreground-service": "github:cristianoccazinsp/react-native-foreground-service#d16912d3e197ed1cc478494369aa2230fc5919b6",
    "react-native-geolocation-service": "github:Agontuk/react-native-geolocation-service#ed2bc7da417e73059de1a4b23bccae60023d58d5",
    "react-native-gesture-handler": "2.5.0",
    "react-native-gles-checker": "github:cristianoccazinsp/react-native-gles-checker#638dc55926dcd30abcd2481afdc199b2e67fb0a3",
    "react-native-image-pan-zoom": "2.1.12",
    "react-native-image-picker": "4.8.5",
    "react-native-image-resizer": "1.4.5",
    "react-native-in-app-review": "4.1.1",
    "react-native-keep-awake": "4.0.0",
    "react-native-loading-spinner-overlay": "2.0.0",
    "react-native-localize": "2.2.2",
    "react-native-mime-types": "2.3.0",
    "react-native-mlkit-ocr": "0.2.5",
    "react-native-panorama-view": "github:cristianoccazinsp/react-native-panorama-view#fbf46afc1299e5bcf0f667f24fb2eeff0714872f",
    "react-native-pell-rich-editor": "github:cristianoccazinsp/react-native-rich-editor#02088917af69085a6c698e6c63acd26a773b6820",
    "react-native-push-notification": "8.1.1",
    "react-native-reanimated": "2.9.1",
    "react-native-render-html": "github:cristianoccazinsp/react-native-render-html#4b769dc140c5dff4557575b846c55f315b009b1b",
    "react-native-restart": "0.0.24",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "3.15.0",
    "react-native-share": "7.8.0",
    "react-native-sketch-draw": "github:cristianoccazinsp/react-native-sketch-draw#41aa49e1c161ec48ee3a7e0ae110fe32afacbe4b",
    "react-native-thermal-sdk": "github:BeeCorp/react-native-thermal-sdk#82c0a52fde5010bedcc794174bf4d9c6b282a747",
    "react-native-uuid-generator": "github:cristianoccazinsp/react-native-uuid-generator#b987630715007edb0762c55e99ee3e3843da1336",
    "react-native-video": "5.2.0",
    "react-native-view-shot": "github:cristianoccazinsp/react-native-view-shot#be682e77a7c7d798bcda11272c227858d891191d",
    "react-native-webview": "11.23.0",
    "react-native-zar-measure": "github:cristianoccazinsp/react-native-zar-measure#9819e6de30329ce1449bbb42f6433a386db52544",
    "react-redux": "8.0.2",
    "react-string-replace": "1.1.0",
    "realm": "11.0.0-rc.0",
    "redux": "4.2.0",
    "redux-logger": "3.0.6",
    "redux-thunk": "2.4.1",
    "underscore": "1.13.4"
  },
  "overrides": {
    "react-native": {
      "hermes-engine": "~0.11.0"
    }
  },
  "devDependencies": {
    "@bugsnag/source-maps": "2.3.1",
    "@react-native-community/eslint-config": "3.0.1",
    "babel-jest": "27.4.6",
    "eslint": "7.32.0",
    "jest": "27.2.1",
    "metro-react-native-babel-preset": "0.67.0",
    "react-test-renderer": "17.0.2"
  }

Do you think its worth it updating to the new version? 

Thank you very much for your help.

**Comment by kneth** [comment]
There might be a mismatch in versions for `realm`, `react-native` and `react-native-reanimated`. For example, `react-native-reanimated` v2.9.1 has a [different version of `react-native`](https://github.com/software-mansion/react-native-reanimated/blob/2.9.1/package.json#L126).

**Comment by kneth** [comment]
Please check the [compatibility matrix](https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md)

**Comment by rodrigobertolottizinsp** [comment]
Thanks! We already upgraded react native and realm, we are testing, hope everything goes well. I will close the issue for now and if it keeps happening with the correct versions we can open it again.
