### ISSUE TITLE
delete(obj) and deleteAll() seem to soft delete

### ISSUE THREAD

**Issue by KevinMartin** [realm/realm-js#504]
When trying to delete the entire realm or specific objects in the realm, the `.realm*` files stay the same size.

```js
realmDelete.write(() => {
    realm.delete(obj);
});
```

and 

```js
realmDeleteAll.write(() => {
    realm.deleteAll();
});
```

On the application side, the objects seem to delete. Just not on the file system it seems. Am I missing something?

**Comment by appden** [comment]
Typically, Realm files do not shrink after deleting objects, but instead will allow for that space in the file to be used by new objects. We could expose a method that would "compact" this empty space, but it would have performance penalties when used. I filed #507 to track exposing that method.
