### ISSUE TITLE
Defining Reflect.construct.sham will let other 3rd library exception

### ISSUE THREAD

**Issue by allen-hsu** [realm/realm-js#5055]
### How frequently does the bug occur?
All the time

### Description
When I use the ethers.js ( web3 library, Used to communicate with Ethereum), I will get this issue 

`missing new`, because ethers.js do some construct check to ensure class type is right, but when I use realm and ethers.js togeter, beceause realm to change this. 

```
if (typeof Reflect !== "undefined" && Reflect.construct) {
    Reflect.construct.sham = 1;
}
```

it will let construct mechanism become different , and will let new.target be undefined in constructor.

```
export class Wordlist {
    constructor(locale) {
        logger.checkAbstract(new.target, Wordlist);
        defineReadOnly(this, "locale", locale);
    }
}

checkAbstract(target, kind) {
        if (target === kind) {
            this.throwError("cannot instantiate abstract class " + JSON.stringify(kind.name) + " directly; use a sub-class", Logger.errors.UNSUPPORTED_OPERATION, { name: target.name, operation: "new" });
        }
        else if (target === Object || target == null) {
            this.throwError("missing new", Logger.errors.MISSING_NEW, { name: kind.name });
        }
    }
```

why realm do that, and very dangerous, this problem has been bothering me for two days

### Can you reproduce the bug?
Yes, always

### Reproduction Steps
import realm and ethers.js in the same time

### Version
10.23.0

### What SDK flavour are you using?
Local Database only

### Are you using encryption?
No, not using encryption

### Platform OS and version(s)
React Native

### Build environment
React Native

**Comment by kneth** [comment]
@allen-hsu With version 11.0.0 we started to [support class based models](https://github.com/realm/realm-js/pull/4537). Prior to that we did do some - as you put it - dangerous manipulations to the prototype chain. 

I will suggest that you upgrade to 11.0.0 or 11.1.0.

**Comment by allen-hsu** [comment]
hi @kneth, but this PR https://github.com/realm/realm-js/pull/4537.
didn't remove those 

```
if (typeof Reflect !== "undefined" && Reflect.construct) {
    Reflect.construct.sham = 1;
}
```

**Comment by kneth** [comment]
It might have been fixed on v12, but if it hasn't please create a new issue for it.
