### ISSUE TITLE
@realm/react still uses _objectId() which is deprecated in 11.0.0

### ISSUE THREAD

**Issue by thecoorum** [realm/realm-js#5056]
### How frequently does the bug occur?

All the time

### Description

After upgrading realm-js to version 11.0.0 I noticed that realm/react 0.4.0 still uses _objectId() under the hood which is deprecated in the realm and causes error on using useQuery

### Can you reproduce the bug?

Yes, always

### Version

11.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 16.0

### Build environment

Which debugger for React Native: Simulator iPhone 14 Pro iOS 16.0

**Comment by kneth** [comment]
`@realm/react` v0.4.0 doesn't use `_objectId()` but `_objectKey()`. The change is: https://github.com/realm/realm-js/pull/4821/files#diff-f0c9376eb96b76a54c91ca0746212846dc369c498d06bf97cd4fdda5f3209301

> error on using useQuery

Which errors do you see?

**Comment by thecoorum** [comment]
I saw an error like `object._objectId() is undefined` and I tried to do patch-package and it installed the latest version which caused an error to be gone. So I think this was my issue. But thanks for quick response
