### ISSUE TITLE
`undefined is not a function` when using useObject

### ISSUE THREAD

**Issue by RenaudAubert** [realm/realm-js#5058]
### How frequently does the bug occur?

All the time

### Description

Hi !
I have a react-native project using `"realm": "^11.1.0"`, `"@realm/react": "^0.4.0"` and `"react-native": "0.70.4"`.

I'm using `useObject` to retrieve an object and it's working fine until I try to access a property being an array of string.

Here's what my code looks like

```jsx
const ProjectComponent = () => {
    const { params: { projectId} } = useRoute();
    // Here project is { name: string, stringArray1: string[], stringArray2: string[], contracts: Contract[] }
    const project = useObject(Project, new Realm.BSON.ObjectId(projectId));
    const myString = project?.stringArray1?.[0] // The error happens here => undefined is not a function
```

Getting any `project` value works fine even  getting elements inside `contracts` which is an array of contract objects but when trying to get elements inside `stringArray1` or `stringArray2` I get this error.

I looked at the stack trace and the problem seems to come from this [line](https://github.com/realm/realm-js/blob/master/packages/realm-react/src/cachedCollection.ts#L115).
In my case `object` is a string and `object._objectKey` is not defined.

It works when I shallow copy the array because it is not using the proxy anymore.

Please let me know if I'm using realm or react-realm incorrectly or if you need more informations.

### Stacktrace & log output

![Capture d’écran 2022-11-02 134332](https://user-images.githubusercontent.com/15106918/199494762-7e404712-2e67-4263-9276-162f8a517358.png)

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

To reproduce create a model with a property being an array of strings

```js
export class Project extends Realm.Object {
    _id;
    name;
    stringArray1;
    stringArray2;

    static schema = {
        name: "Project",
        properties: {
            _id: "objectId",
            name: "string",
            stringArray1: "string[]",
            stringArray2: { type: "string[]", default: [] },
        },
        primaryKey: "_id",
    };
}
```

And inside a react component, retrieve an element of the array of string from this object

```js
const project = useObject(Project, _id);
const myString = project?.stringArray1?.[0]
```

### Version

11.1.0 and 11.0.0

### What SDK flavour are you using?

Atlas Device Sync

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

I'm using Windows 10 version 21H2 to emulate (emulator version 31.2.10) a Pixel 4 phone running on Android 12

**Comment by kneth** [comment]
@RenaudAubert 

Another user reported the same thing but an update [solved the issue](https://github.com/realm/realm-js/issues/5056#issuecomment-1300459960). Can it be an issue with a build cache?

**Comment by takameyer** [comment]
@RenaudAubert I can see the issue in our current implementation.  We are checking of the property of an object is an instance of `Realm.List`.  Seemed there was a false assumption that a `Realm.List` was a collection of `Realm.Object`.  Therefore the code is trying to cache a list of primitives and assumes they are `Realm.Object`s.  

We will look into this right away and update you here when a fix is available.  Thanks for reporting this!

**Comment by RenaudAubert** [comment]
@takameyer Thank you 🙏 
Let me know if you need more information regarding this issue

**Comment by takameyer** [comment]
@RenaudAubert This should be fixed now.  Please use `@realm/react@0.4.1`

**Comment by RenaudAubert** [comment]
I confirm I no longer have an error thrown when accessing a value from an array of primitives.  Thank you very much
