### ISSUE TITLE
Expose compact() method on Realm instances

### ISSUE THREAD

**Issue by appden** [realm/realm-js#507]
We can call it something else in JS, but essentially it would just call `SharedRealm::compact()`. This would alleviate concerns for app developers over ever-growing Realm file sizes.

This issue was brought up in #504.

**Comment by lakhman** [comment]
If I create a bunch of objects, then delete, them, then create them again, it takes twice as much space - it doesn't just reuse the existing space of the old data, I have a realm file which grows up to 2mb when logging users in and out (and saving data).

Code is simply:

```
realm.delete(realm.objects('ObjectName'));
```

This does a "soft delete" where it removes it from the database (can be viewed in realm browser), but the file size remains (it's never reused).

Is this a bug? or am I doing something wrong?

**Comment by lakhman** [comment]
I figured out the unexpected growth of file size, it was related to:

https://github.com/realm/realm-browser-osx/issues/71

Using the Realm Browser in OSX (while developing), causes the file size to grow and not reuse the existing space. Once you close the Realm Browser Instance, the file size works as expected.

+1 for a `compact` method, would be nice to reclaim users disk space as required.

**Comment by rdev5** [comment]
I have a 5.6 MB SQLite file I'm currently working to export to Realm via upserts:

````
# RealmBase.js
const Realm = require('realm');
const uuid4 = require('uuid/v4');

Realm.prototype.getUpsertId = function(data) {
  return data.id ? data.id : uuid4();
}

Realm.prototype.upsert = function(model, data) {
  data.id = this.getUpsertId(data);

  this.create(model, data, true);
};

module.exports = Realm;
````

However, after only importing a subset of records (less than 50% perhaps), the corresponding *.realm file has grown to over 8 GB and continues to grow even when existing records are upserted, yielding 0 changes across the entire set.

Could really use a way to programmatically compact from Node.js. Thanks!

**Comment by Mellemel** [comment]
I really need this method since I have a csv file that after importing blows up my realm file from 87mb to 500mb. The compact method in the Realm browser reduces my realm file to 137mb.

Where should I look/start after forking this repo to be able to expose this method to the js side?

**Comment by kneth** [comment]
@Mellemel I am currently working on it.

**Comment by kneth** [comment]
@Mellemel See #1209
