### ISSUE TITLE
Align visuals studio code configuration with new package structure

### ISSUE THREAD

**Issue by JacobOscarGunnarsson** [realm/realm-js#5087]
Discussed this error with @kneth in person

The `launch.json` is no longer completely valid, as many of the paths and required prerequisite commands have changed.

The task here would be to go over the launch commands an determine if everything is valid, correct, and useful (perhaps some parts are no longer valid).

**Comment by kraenhansen** [comment]
I believe we addressed this with https://github.com/realm/realm-js/pull/5561
