### ISSUE TITLE
reset password keep giving token has expires

### ISSUE THREAD

**Issue by u007** [realm/realm-js#5089]
hi,

my reset password is mailed to my email, so I tried to call this to set a new password, but I keep getting:
```
{"error":"userpass token is expired or invalid","error_code":"UserpassTokenInvalid","link":"https://realm.mongodb.com/groups/5c7f7250c56c988c0a935770/apps/614033bed78843bf22a174bf/logs?co_id=636b48f1b8c40f4ed36f5d90"}
```
using code (vue):
```
await app.emailPasswordAuth.resetPassword({
      password: pass.value,
      token: route.query.token as string,
      tokenId: route.query.tokenId as string,
    })
```
```
{"password":"Abc123.....","token":"461d91b025411f8771bd461f4278efe6d90c2c5b0a10ab7fb93d7fa5f48a68107211a374d2a2479e2736937d913ed3f1d68a166bd14116d3582f8b8fb0f22b88","tokenId":"636b4f4296f67bb1cede35b0"}
```

**Comment by kneth** [comment]
Please tell us if you are using Realm Web or Realm JavaScript (and the version).

**Comment by u007** [comment]
realm web sdk om browser

**Comment by kneth** [comment]
The token is expired after 30 minutes (see https://www.mongodb.com/docs/realm/web/manage-email-password-users/#complete-a-password-reset). Can the problem be that you don't "meet the deadline"?

**Comment by u007** [comment]
no it expires immediately

**Comment by kneth** [comment]
@u007 Can you try to run it again and ping me when you have done so. I will then ask the cloud folks to investigate (your old session has been removed).

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
