### ISSUE TITLE
Realm for react-native gives IOS version warning

### ISSUE THREAD

**Issue by uc-bkr** [realm/realm-js#509]
After installing the latest version of Realm using npm, when I tried to run my react-native app
The build failed with the following error:

d: targeted OS version does not support use of thread local variables in __ZN5realm4util13get_thread_idEv for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

After changing the deployment target from 7 to 8.1
I found this error 

ld: targeted OS version does not support use of thread local variables in __ZN5realm4util13get_thread_idEv for architecture x86_64

**Comment by appden** [comment]
@uc-bkr It should work after you changed you deployment target to 8.1, so maybe you could try cleaning your build products (**Product → Clean**) and trying again? Once we release `0.14.1` (tracked in #506), it should work again with the default iOS 7 target.

**Comment by appden** [comment]
@uc-bkr We just released `0.14.1-rc`. Would you mind updating to that and seeing if your issue is resolved? Thanks!
