### ISSUE TITLE
Task :realm:send FAILED

### ISSUE THREAD

**Issue by bankiprudhvi** [realm/realm-js#5094]
### How frequently does the bug occur?

All the time

### Description

warn Package realm contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed,"dependency.platforms.ios.sharedLibraries" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

"react": "16.13.1",
    "react-native": "^0.69.0", above
  classpath("com.android.tools.build:gradle:7.0.1") above 

### Can you reproduce the bug?

Yes, always

### Version

31

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

"react": "16.13.1",
    "react-native": "^0.69.0", above
  classpath("com.android.tools.build:gradle:7.0.1") above 

 RNNKotlinVersion = "1.5.20"
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }

**Comment by kneth** [comment]
@bankiprudhvi Which version of Realm JavaScript do you use?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
