### ISSUE TITLE
Missing Realm constructor on Android

### ISSUE THREAD

**Issue by lukewalz** [realm/realm-js#5099]
### How frequently does the bug occur?

All the time

### Description

Whenever I try to debug my app on android, I get the following error: Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting and get stuck on splash screen. I am not using the new architecture or hermes. The same code works fine on ios.

Version

### Stacktrace & log output

```shell
ERROR  Error: Missing Realm constructor. Did you run "pod install"? Please see https://realm.io/docs/react-native/latest/#missing-realm-constructor for troubleshooting
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

npm run android

### Version

v11.0.0-rc.1

### What SDK flavour are you using?

Atlas App Services (auth, functions, etc.)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 

### Build environment

Flipper

 npm info
System:
OS: macOS 12.6
CPU: (8) arm64 Apple M1 Pro
Memory: 137.75 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
Yarn: Not Found
npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK:
API Levels: 31, 32, 33
Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
System Images: android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
Android NDK: Not Found
IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335
Xcode: 13.3/13E113 - /usr/bin/xcodebuild
Languages:
Java: 11.0.13 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.0.0 => 18.0.0
react-native: 0.69.1 => 0.69.1
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

**Comment by kneth** [comment]
@lukewalz Thank you for reporting. First I will recommend that you upgrade to v11.0.0 or v11.1.0 but it will require that you upgrade React Native to v0.70.

Second, when building your app for Android, did you see any warnings or error messages?

**Comment by tayloraleach** [comment]
I just encountered this issue as well. Brand new react native project running on Linux (ubuntu) trying to run on my physical android device

"react": "18.1.0",
"react-native": "0.70.5",
"realm": "^11.0.0-rc.2"

**Comment by kneth** [comment]
@tayloraleach Please upgrade to v11.0.0 or later.

**Comment by tayloraleach** [comment]
> @tayloraleach Please upgrade to v11.0.0 or later.

I have tried 11.0.0, 11.1.0, and 10.21.1. Seeing the same error message.

**Comment by lukewalz** [comment]
As an update on this for me, I upgraded as instructed and used the
https://react-native-community.github.io/upgrade-helper/ and my issue was
resolved. I am not using new arch or Hermes. Thanks for the help!

**Comment by kneth** [comment]
@lukewalz Good to hear that you are able to find the constructor 😄
