### ISSUE TITLE
[Android] Using realm-java and realm-js: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture.

### ISSUE THREAD

**Issue by jabm111** [realm/realm-js#511]
Hi!

I'm trying to use realm-js and realm-java in the same app but I'm getting this error when trying to access the default realm from JS and Java:

`Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture.`

I think it might have to do with the realm versions not matching? Is there a way I can be sure to use the same Realm version (is it the realm-core version that has to be the same?)?

Versions:
react-native: 0.24.0
realm: 0.14.0
io.realm:realm-gradle-plugin:1.0.1

Any help would be greatly appreciated! Let me know if I can provide any other information.

Thanks,

James

**Comment by alazier** [comment]
Those two binding versions definitely use different core versions which could be the root of your issue. Trying to confirm that is the case. Unfortunately there aren't recent versions of the js and java bindings that use the same core version, but you could try to build a custom version of the js binding to get the core versions matched up.

**Comment by jabm111** [comment]
Ok, I'll give that a try. Thanks for the info!

**Comment by jabm111** [comment]
Ok, so matching the realm-core versions of the js and java bindings did fix the problem I was having! In the end I've decided not to use both bindings at the same time though.

Thanks!

**Comment by alazier** [comment]
Glad you got things working!
