### ISSUE TITLE
The application freezes when requesting length

### ISSUE THREAD

**Issue by valery-lavrik** [realm/realm-js#5146]
### How frequently does the bug occur?

All the time

### Description

The react-native application freezes when I execute the code:
`
this.Base.objects('Objects').length;
`
Because I have about 120,000 records written to the Objects table.   
I can't even see the exact number of them.  What should I do?

### Version

"realm": "^11.2.0",

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

    "react": "18.1.0",
    "react-native": "0.70.5",
    "realm": "^11.2.0",

**Comment by kneth** [comment]
Can you confirm that you have no queries involved (not calling `.filtered()`)? Is it possible for you to share a small project which can reproduce the behaviour?

Moreover, can you tell us which JS engine you can using (Hermes or JSC)?

**Comment by valery-lavrik** [comment]
I use Hermes.
I deleted all the code except the line
`this.Base.objects('Objects').length;`
Apart from her, there is nothing else that could work at all.

Unfortunately, I can't share the project, but you can try to assemble a simple table yourself: **id (string, index), props (string)**     And put 100,000 records in it.   You'll see for yourself

**Comment by kneth** [comment]
I am not able to reproduce it. I have used our [app template](https://github.com/realm/realm-js/tree/master/templates/react-native-template-realm-js), enabled Hermes in `ios/Podfile` and changed `app/AppNonSync.js` to 

```js
import React, {useMemo} from 'react';

import {Task} from './models/Task';
import {TaskRealmContext} from './models';
import {TaskManager} from './components/TaskManager';

const {useQuery} = TaskRealmContext;

export const AppNonSync = () => {
  console.log("FISK 1");
  const result = useQuery(Task);
  console.log(`FISK 2 ${Date.now()}`);
  const length = result.length;
  console.log(`FISK 3 ${Date.now()}`, length);

  const tasks = useMemo(() => result.sorted('createdAt'), [result]);

  return <TaskManager tasks={tasks} />;
};
```

**Comment by takameyer** [comment]
Closing this as, as there has been no response.  Please submit a reproducible case if you want to reopen this issue.
