### ISSUE TITLE
Cannot install realm 6.x on M1 apple chip, react native project

### ISSUE THREAD

**Issue by Vi-debug** [realm/realm-js#5149]
### How frequently does the bug occur?

All the time

### Description

when I run command 
`npm install realm@6.1.7`
Error appear as below. It stated that it try to download on a link that doesn't exist (404):
```
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.15.0
npm ERR! node-pre-gyp info using node@16.18.1 | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/Documents/project/mlng/node_modules/realm/compiled/napi-v4_darwin_arm64/realm.node" (not found)
npm ERR! node-pre-gyp http GET https://static.realm.io/node-pre-gyp/napi-v4/realm-v6.1.7/realm-v6.1.7-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/napi-v4/realm-v6.1.7/realm-v6.1.7-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/napi-v4/realm-v6.1.7/realm-v6.1.7-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for realm@6.1.7 and node@16.18.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://static.realm.io/node-pre-gyp/napi-v4/realm-v6.1.7/realm-v6.1.7-darwin-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.1 | darwin | arm64
npm ERR! gyp info ok
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

run command `npm i @realm@6.1.7` in a react native project

### Version

6.1.7

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Mac OS Monterey 12.6

### Build environment

```
"react": "16.9.0",
"react-native": "0.61.1",
"realm": "6.1.7",
```

**Comment by nirinchev** [comment]
Realm 6.x doesn't support M1. Any reason why you can't upgrade to the latest version?

**Comment by Frans-L** [comment]
Realm 6.x works when using Node 14 or 12 with Rosetta. 

```bash
# verify node version < 15
node --version
# verify arch to be "x64"
arch -x86_64 node -p "process.arch"

# ensure clean state and install packages
rm -r node_modules
arch -x86_64 npm install 

# should work now
arch -x86_64 npm run ios
```

Note: Node 14 usually runs automatically using x86, so the Rosetta command `arch -x86_64` is not needed with many setups.

**Comment by kneth** [comment]
@Frans-L Thank you for taking the time to provide a solution/workaround.

**Comment by Namnp1521** [comment]
it's not work for me, i got this error when run `arch -x86_64 node -p "process.arch"`:
`arch: posix_spawnp: node: Bad CPU type in executable`
btw, when i run `arch -x86_64 npm install`, still fail 
![Screenshot 2022-12-05 at 10 15 34](https://user-images.githubusercontent.com/45452919/205541804-065d868d-edce-4211-b000-d4e1f9397877.png)

**Comment by Namnp1521** [comment]
it work with node 14.16.0 thanks
