### ISSUE TITLE
Is Realm 10.24.0 really a pre-release?

### ISSUE THREAD

**Issue by liamjones** [realm/realm-js#5152]
### How frequently does the bug occur?

All the time

### Description

Sorry for posting this as a bug, I realise it's not the right place but I asked in the forums over two weeks ago and haven't had a reply ([forum thread](https://www.mongodb.com/community/forums/t/realm-10-24-0-is-a-prerelease/199206)). I thought it might get more notice here.

[Release 10.24.0](https://github.com/realm/realm-js/releases/tag/v10.24.0) is marked as a pre-release. Is this a mistake? I don't want to upgrade Realm in our app unless it's a full release.

### Can you reproduce the bug?

Yes, always

### Version

10.24.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

N/A

**Comment by kneth** [comment]
@liamjones 

Good catch. It is a side-effect of our automated release flow (hosted by Github Actions). v11.3.0 is our latest release and v10.24.0 is consider the "legacy". Every release not targeting "latest" will end up as a pre-release on Github. I have manually removed "pre-release" from v10.24.0.

After v11.0.0 we have had a couple of v10.x releases as we believe some of the fixes are important to backport. v10.24.0 is a full release but we encourage you to upgrade to v11.x when possible.

In the future I suggest you use `npm dist-tags realm` to get a better picture of our releases.

**Comment by liamjones** [comment]
> In the future I suggest you use `npm dist-tags realm` to get a better picture of our releases.

Ah, I wasn't aware of this command, thanks!
