### ISSUE TITLE
Installing realm for node (Electron) desktop app also downloads react-native folder (272mb size) - can react-native be excluded?

### ISSUE THREAD

**Issue by GitMurf** [realm/realm-js#5153]
### How frequently does the bug occur?

All the time

### Description

I am using Realm for a Nodejs app (Electron). I do not need react-native but when I install realm with `npm install realm` it also downloads the `react-native` folder ([here](https://github.com/realm/realm-js/tree/master/react-native)) which takes up 272mb on disk for Realm. If I was able to exclude this it would reduce the package size tremendously for my app which makes a huge difference for my app for my users.

Is this intentional? Is it required? Is there any way to use Realm just for a Node/Electron app that does not require react-native as we are just building a desktop app that will not be used on ios / android.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Install realm for Electron (or just plain Node app) project with `npm install realm`. You will have the react-native folder downloaded automatically even if you do not need react-native.

![image](https://user-images.githubusercontent.com/64155612/205239327-755a7cb7-e8bb-4861-afbd-dfc66fabede0.png)

### Version

11.3.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Windows 11

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
> Is this intentional? 

Currently, yes it is intentionally.

> Is it required?

We are currently working on building the SDK in a very different way. I invite you to follow the branch [bindgen](https://github.com/realm/realm-js/tree/bindgen) where the work is being done. As part of this long-running project we are exploring how we can release a number of specialized packages instead of putting everything together in a single package.

**Comment by GitMurf** [comment]
@kneth thank you for the quick response. I look forward to the new SDKs! For the time being, would it cause any issues if I am not using react-native to delete the react-native folder before I build my app for users (to reduce package size)? Or will there be something realm uses in that folder that will be required regardless of whether we use react native or not?

**Comment by kneth** [comment]
@GitMurf I can't see any reason why you cannot delete it.

**Comment by kneth** [comment]
I will leave the issue open and close it once we have split out packages.

**Comment by GitMurf** [comment]
> I will leave the issue open and close it once we have split out packages.

Thanks! Sounds good. Curious if you have any ETA on the split out packages? We talking in the next few months? or more like sometime in the next year? Just high level estimate... I won't hold you to anything ;-)

**Comment by kneth** [comment]
In general we are not so happy to give out ETA but it will not happen in the next few months but hopefully sometime next year

**Comment by mtsdnz** [comment]
If you're using electron-builder, you can remove the react-native folder from the build by adding the following entry to the `build.files` of your **package.json**:
``` JSON
"!**/node_modules/realm/react-native"
```
Full example:
``` JSON
"build": {
    "productName": "....",
    "appId": "....",
    "files": [
      "!**/node_modules/realm/react-native"
    ],
}
```

I was able to remove 41mb from my build size by just adding this line.

@kneth I think it would be good to add this information on the [Electron quick start page](https://www.mongodb.com/docs/realm/sdk/node/integrations/electron/)

**Comment by kneth** [comment]
@mtsdnz Thanks for the suggestion. I agree that we should add it to our Electron guide.

**Comment by takameyer** [comment]
@GitMurf @mtsdnz in v12, which will soon be released, `react-native` is excluded and is now an optional dependency.  You can try this out right now `npm install realm@next`.
Going to close this now, but don't hesitate to open a new issue if you find something broken in our latest release candidate!

**Comment by GitMurf** [comment]
Thanks for the update!! I'll give it a try this week. Since you mentioned v12, anything new exciting things coming in v12 that I should consider moving to sooner rather than later? Or mostly just bug / optimization stuff? Thanks!
