### ISSUE TITLE
Error: RealmObject cannot be called as a function

### ISSUE THREAD

**Issue by Vivaan7** [realm/realm-js#5162]
### How frequently does the bug occur?

All the time

### Description

I am getting this error only on android side when i am going to add data. IOS side it is working properly !

this is my versions 

  "realm": "^10.6.1",
  "react": "17.0.2",
  "react-native": "0.65.0",

### Stacktrace & log output

```shell
// Add a single WOListData using parameters
let addWOListData = (
  _totalTimeSpent,
  _totalPlannedMechanicTime,
  _mechanicName,
  _appointmentId,
  _workOrderNumber,
  _ifsWorkOrderStatusId,
  _workOrderColor,
  _licensePlateNumber,
  _model,
  _brandName,
  _logo,
  _customerName,
  _mobileNo,
  _description,
  _plannedTime,
  _bookedDate,
  _updatedDate,
  _workOrderStatus,
  _dealer,
  _appointmentGuid
) => {
  realm.write(() => {
    const WOList = realm.create("WOList", {
      totalTimeSpent: _totalTimeSpent,
      totalPlannedMechanicTime: _totalPlannedMechanicTime,
      mechanicName: _mechanicName,
      appointmentId: _appointmentId,
      workOrderNumber: _workOrderNumber,
      ifsWorkOrderStatusId: _ifsWorkOrderStatusId,
      workOrderColor: _workOrderColor,
      licensePlateNumber: _licensePlateNumber,
      model: _model,
      brandName: _brandName,
      logo: _logo,
      customerName: _customerName,
      mobileNo: _mobileNo,
      description: _description,
      plannedTime: _plannedTime,
      bookedDate: _bookedDate,
      updatedDate: _updatedDate,
      workOrderStatus: _workOrderStatus,
      dealer: _dealer,
      appointmentGuid: _appointmentGuid,
    });

    printLog("Wooho WOListData ADDED", WOList);
  });
};
```

### Can you reproduce the bug?

Not yet

### Version

10.6.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12 (31 API)

### Build environment

Which debugger for React Native: ..

**Comment by Vivaan7** [comment]
@takameyer  please help ASAP ... 
we are in rush

**Comment by takameyer** [comment]
@Vivaan7 Please post the error you are getting.  Also this is the preferred syntax:
```
  const WOList = realm.write(() => {
    return realm.create("WOList", { ...
```

**Comment by Vivaan7** [comment]
@takameyer  i am getting error on given function from the beginning that "RealmObject cannot be called as a function"

**Comment by Vivaan7** [comment]
i am following this structure https://github.com/mbvissers/RealmExampleApp/blob/master/RealmExample/Database.js

even this is working in other 2 projects

**Comment by kneth** [comment]
Realm JS v10.6.1 doesn't support class-based models (`class UserSchema extends Realm.Object`) - at least not reliable. By that I mean that it might have worked for some JS engines but you shouldn't trust it to work.

For version 11.0.0 we decided to fix the class-based models, and if you wish to use it, please upgrade to v11.0.0 or later.

Another issue is that `Realm#write` is a synchronous method, and I think that the behaviour of `realm.write(async () => { ... });` is  not well-defined. I recommend that you remove `async`.

**Comment by Vivaan7** [comment]
Actually i have not used other schema i will use it i am getting issue in WOList schema so no async in that @kneth  let me check with latest version 11.0.0

**Comment by Vivaan7** [comment]
@kneth   i am getting this error in version 11.0.0 

Error: Exception in HostObject::get(propName:Realm): java.lang.LinkageError: This version of Realm JS needs at least React Native version 0.66.0. 


application is not building successfully even

**Comment by kneth** [comment]
You probably have to upgrade React Native too.

**Comment by Vivaan7** [comment]
@kneth  aah shit this won't be easy but yaah any other ways ?

**Comment by kneth** [comment]
Don't do `class UserSchema extends Realm.Object` for now and upgrade when you have some more air :-)

**Comment by Vivaan7** [comment]
@kneth  i used 10.1.2, 10.6.1 both cases i am getting same error  ===> Error: RealmObject cannot be called as a function

and pointing me to this function


// Add a single WOListData using parameters
let addWOListData = (
_totalTimeSpent,
_totalPlannedMechanicTime,
_mechanicName,
_appointmentId,
_workOrderNumber,
_ifsWorkOrderStatusId,
_workOrderColor,
_licensePlateNumber,
_model,
_brandName,
_logo,
_customerName,
_mobileNo,
_description,
_plannedTime,
_bookedDate,
_updatedDate,
_workOrderStatus,
_dealer,
_appointmentGuid
) => {
realm.write(() => {
const WOList = realm.create("WOList", {
totalTimeSpent: _totalTimeSpent,
totalPlannedMechanicTime: _totalPlannedMechanicTime,
mechanicName: _mechanicName,
appointmentId: _appointmentId,
workOrderNumber: _workOrderNumber,
ifsWorkOrderStatusId: _ifsWorkOrderStatusId,
workOrderColor: _workOrderColor,
licensePlateNumber: _licensePlateNumber,
model: _model,
brandName: _brandName,
logo: _logo,
customerName: _customerName,
mobileNo: _mobileNo,
description: _description,
plannedTime: _plannedTime,
bookedDate: _bookedDate,
updatedDate: _updatedDate,
workOrderStatus: _workOrderStatus,
dealer: _dealer,
appointmentGuid: _appointmentGuid,
});

printLog("Wooho WOListData ADDED", WOList);
});
};

// Add a single WOListData using parameters
// let addWOListData = (
// _totalTimeSpent,
// _totalPlannedMechanicTime,
// _mechanicName
// ) => {
// realm.write(() => {
// let _id = 0;
// if (getWOListData().length > 0) _id = realm.objects("WOList").max("id") + 1;

// const WOList = realm.create("WOList", {
// id: _id,
// totalTimeSpent: _totalTimeSpent,
// totalPlannedMechanicTime: _totalPlannedMechanicTime,
// mechanicName: _mechanicName,
// });

// printLog("Wooho WOListData ADDED", WOList);
// });
// };

**Comment by takameyer** [comment]
@Vivaan7 When opening the realm can you try:
```
let realm = new Realm({ schema: [WOListSchema.schema, UserSchema.schema]}
```
There really isn't a point defining a `class` for this if you aren't using TypeScript.  Just use the `schema` objects.  Maybe this would help.

Also make sure you Android environment is setup correctly.  Perhaps try a clean build:
```
cd android
./gradlew clean
```

**Comment by Vivaan7** [comment]
@takameyer  i already told you its not about class i guess still i am facing same issue @kneth  guys can you provide me promising solution.

**Comment by kneth** [comment]
The issue is that class-based models are not working prior to version 11. We fixed it in v11.0.0-rc.2, and it was [confirmed](https://github.com/realm/realm-js/issues/3876#issuecomment-1250014480) to work on Android.

As [outlined above](https://github.com/realm/realm-js/issues/5162#issuecomment-1340972756) you shouldn't use classes in your Realm configuration prior to version 11.0.0-rc.2.

**Comment by Vivaan7** [comment]
@kneth  i am not using it dear i removed but facing same issue !

**Comment by kneth** [comment]
Please post your recent code snippet as it is a bit difficult to track the changes.

**Comment by kneth** [comment]
I don't see any issues with the code snippet. Could you try to remove all build folders, clear all caches and remove the app from your device?

**Comment by Vivaan7** [comment]
@kneth i tried but it's not working I am getting crash whenever I tried to insert the data...

**Comment by takameyer** [comment]
@Vivaan7 Can you share the contents of your `package.json`. In older versions of `realm` we had some incompatibilities with certain packages, such as `react-native-reanimated` v2.

**Comment by Vivaan7** [comment]
@takameyer  

{
  "name": "AutoFacets",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "simulator_ios": "react-native run-ios --device Gateway’siPad",
    "start": "react-native start",
    "port change": "rnp patch -o 8081 -n 9000",
    "test": "jest",
    "jestCodeCoverage": "npx jest --coverage",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-clipboard/clipboard": "^1.9.0",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/netinfo": "^6.0.2",
    "@react-native-community/slider": "^4.1.9",
    "@react-native-cookies/cookies": "^6.0.11",
    "@react-native-firebase/app": "^12.9.2",
    "@react-native-firebase/crashlytics": "^12.9.2",
    "@react-native-firebase/messaging": "^12.9.2",
    "@react-navigation/drawer": "^5.12.9",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/native-stack": "^6.2.2",
    "@react-navigation/stack": "^5.14.9",
    "axios": "^0.23.0",
    "buffer": "^6.0.3",
    "date-fns": "^2.25.0",
    "html-entities": "^2.3.2",
    "i": "^0.3.7",
    "i18n-js": "^3.8.0",
    "lodash.memoize": "^4.1.2",
    "moment": "^2.29.1",
    "native-base": "^2.15.2",
    "npm": "^8.1.1",
    "react": "17.0.2",
    "react-native": "0.65.0",
    "react-native-audio-recorder-player": "^3.5.1",
    "react-native-calendar-strip": "^2.2.5",
    "react-native-camera": "^4.2.1",
    "react-native-crypto-js": "^1.0.0",
    "react-native-element-dropdown": "^1.8.13",
    "react-native-elements": "^3.4.2",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-get-random-values": "^1.8.0",
    "react-native-html-to-text": "0.0.5",
    "react-native-image-crop-picker": "^0.36.4",
    "react-native-image-marker": "^0.6.3",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-manager": "^6.5.4-3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-dropdown": "git+https://github.com/noway/react-native-material-dropdown.git",
    "react-native-media-controls": "^2.3.0",
    "react-native-modal-datetime-picker": "^12.0.0",
    "react-native-paper": "^4.9.2",
    "react-native-pell-rich-editor": "^1.8.5",
    "react-native-permissions": "^3.1.0",
    "react-native-qrcode-scanner": "^1.5.4",
    "react-native-reanimated": "^2.9.1",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-signature-capture": "^0.4.12",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-slider": "^0.11.0",
    "react-native-sound": "^0.11.1",
    "react-native-svg": "^12.1.1",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-svg-uri": "^1.2.3",
    "react-native-text-ticker": "^1.14.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^11.14.0",
    "react-redux": "^7.2.5",
    "realm": "^11.0.0",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",
    "sonarqube-scanner": "^2.8.1",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/plugin-transform-modules-commonjs": "^7.19.6",
    "@babel/preset-env": "^7.20.2",
    "@babel/runtime": "7.15.4",
    "@react-native-community/eslint-config": "2.0.0",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-native": "^9.1.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.66.2",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native",
    "verbose": true,
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "setupFiles": [
      "./jestSetupFile.js"
    ],
    "transform": {
      "^.+\\.(js|jsx)$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?@?react-native|@react-native-responsive-screen|@react-native-image-crop-picker|@react-native-video/(.*))"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ]
  }
}






I am tired solution this realm issue due to that facing other issues now this is unbelievable..

**Comment by Vivaan7** [comment]
@takameyer  i can't upgrade or downgrade because my app is depend on other SDK so suggest me better option and plz plz plz help me ASAP

**Comment by takameyer** [comment]
@Vivaan7 I'm sorry, but the only option is to upgrade `realm` or downgrade `react-native-reanimated`.  We worked hard on v11 to be compatible with all native libraries and hermes.  I wish I could offer another solution, but those are unfortunately the only options.
My recommendation is to upgrade React Native.  Then you can make use of the most updated versions of all those libraries.  I find this tool to be helpful: https://react-native-community.github.io/upgrade-helper/

**Comment by Vivaan7** [comment]
@takameyer  okay l can try from my side !

**Comment by Vivaan7** [comment]
@takameyer  @kneth  i am getting this crash now 

 A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6e754600000004 in tid 2850 (mqt_js), pid 2778
 
 
 
 using 
 
 realm "10.6.1"

**Comment by takameyer** [comment]
After upgrading React Native to version `0.70.0`, upgrade realm to `11.3.1`

**Comment by Vivaan7** [comment]
@takameyer  i can't mate due to that there are lots of things which will be stopped working and i don't have time figure it out one by one. our project is already live

**Comment by takameyer** [comment]
@Vivaan7 There is absolutely no way that any v10 version of Realm will be compatible with `react-native-reanimated` v2.  

So there are two choices:
* upgrade Realm and React Native
* downgrade `react-native-reanimated` to v1

Unfortunately, that's all the help we can offer.
