### ISSUE TITLE
Incompatible architecture error when running on Macbook with ElectronJS

### ISSUE THREAD

**Issue by nicoladaniello** [realm/realm-js#5168]
### How frequently does the bug occur?

All the time

### Description

I'm making a desktop app using electron and I'm trying to open a Realm in the main process which run Node.

The app works ok until I import Realm, at which point I get the error.

All I do is trying to start a Realm after the app is ready:

```
app.on("ready", () => {
  realmConnect().catch((err) => {
    console.error("Failed to start server:", err);
  });

  createWindow();
});

async function realmConnect() {
  realm = await Realm.open(configs);
}
```

### Stacktrace & log output

```shell
App threw an error during load
Error: dlopen(/Users/nicoladaniello/htdocs/books-v3/.webpack/main/native_modules/build/Release/realm.node, 0x0001): tried: '/Users/nicoladaniello/htdocs/books-v3/.webpack/main/native_modules/build/Release/realm.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nicoladaniello/htdocs/books-v3/.webpack/main/native_modules/build/Release/realm.node' (no such file), '/Users/nicoladaniello/htdocs/books-v3/.webpack/main/native_modules/build/Release/realm.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ./node_modules/realm/lib/index.js (/Users/nicoladaniello/htdocs/books-v3/.webpack/main/index.js:27543:26)
    at __webpack_require__ (/Users/nicoladaniello/htdocs/books-v3/.webpack/main/index.js:32645:42)
```

### Can you reproduce the bug?

Yes, always

### Version

11.3.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS Ventura 13.0

**Comment by kneth** [comment]
From the error message it looks like you have downloaded Realm for the wrong architecture. Are you using M1 but have installed node.js for Intel? Please try the following commands:

* `uname -a`
* `node -e 'console.log(process.arch)'`

To help us debug, please try to use 11.3.0 instead and see if it works or you get the same error message?

**Comment by nicoladaniello** [comment]
@kneth Thanks for your reply.

My version of node was correct but apparently I had an issue with nvm, which I realised after it failed to install other versions of node.

Installing the latest version of nvm and using node v16 (v19 stalled while installing realm for some reason) solved the issue.

**Comment by kneth** [comment]
@nicoladaniello I am happy to hear. I'll close the issue.
