### ISSUE TITLE
React Native - Changed Schema - App Update Isn't Possible

### ISSUE THREAD

**Issue by avishayil** [realm/realm-js#518]
Hi all,

As you probably know, when changing schema a user must clear data / cache on Android or uninstall the app, and on iPhone uninstall the app.

The question is, how am I suppose to maintain updates to the app, enforcing users to reinstall the app every time I change the schema?

This is very important to the workflow and would eventually cause huge loss of users.

Thanks.

**Comment by alazier** [comment]
You shouldn't need to delete or clear the data when changing the schema as Realm supports migrations. This is described in the documentation here: https://realm.io/docs/react-native/latest/#migrations

At a minimum you just need to specify a schema version when changing the schema. If you just do this any new properties will be added, and old ones removed, and any old data will be persevered. You also have the option to provide a migration block which is only run when the schema is updated.

**Comment by alazier** [comment]
Were you  able to get everything working?

**Comment by avishayil** [comment]
Yeah, thanks!
