### ISSUE TITLE
Dictionary not updating on data change with @realm/react

### ISSUE THREAD

**Issue by mohammadhunan-dev** [realm/realm-js#5182]
### How frequently does the bug occur?

Seen once

### Description

Hi,

I'm having issues with the Realm.Dictionary type where I'm trying to render data about the dictionary to the UI. However, when the data changes, the component doesn't rerender.

Consider the following scenario that would have the UI update if the task's name or priority changed:
```
const TaskItem = ({_id}: {_id: number}) => {
  const myTask = useObject(Task, _id);
  return (
    <View>
      {myTask ? (
        <Text>
          {myTask.name} is a task with the priority of: {myTask.priority}
        </Text>
      ) : null}
    </View>
  );
};
```

Alternatively, consider this scenario where if the home.address changed, the UI wouldn't re-render:
```
const HomeList = () => {
  const realm = useRealm();
  // query for all HomeOwner objects
  const homeOwners = realm.objects(HomeOwner);

  return (
    <View>
      <Text>All homes:</Text>
      {homeOwners.map(homeOwner => (
        <View>
          <Text>{homeOwner.home.address}</Text>
        </View>
      ))}
    </View>
  );
};
```

### Can you reproduce the bug?

Yes, always

### Version

@realm/react: ^0.4.1;  realm: ^11.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.6.1 (Monterey)

### Build environment

Which debugger for React Native: ..
Running this in a test environment with jest and react native testing library, you can see that environment here:  https://github.com/mongodb/docs-realm/tree/master/examples/react-native

**Comment by kneth** [comment]
@mongomoe Thank you for reporting. I wonder if is it related to #5185, and we need to investigate it further.
