### ISSUE TITLE
How to add a nested List of objects in Realm [Error: JS value must be of type: object]

### ISSUE THREAD

**Issue by KalebPortillo** [realm/realm-js#519]
I'm trying to create Realm database that has a json array of objects with a nested array of objects.

When I try to add using the code below I always get the error: JS value must be of type: object.

Schemas:

```
import Realm from 'realm';

class Exercise extends Realm.Object {
}
Exercise.schema = {
    name: 'Exercise',
    primaryKey: 'id',
    properties: {
        id: 'int',
        name: 'string',
        category: 'string',
        bodyPart: 'string',
        levels: {type: 'list', objectType: 'Level'}
    }
};

class Level extends Realm.Object {
}
Level.schema = {
    name: 'Level',
    properties: {
        level: 'int',
        equipments: 'string'
    }
};
```

export default new Realm({schema: [Exercise, Level, Multiplier]});
and the method where I'm trying to create the database:

```
 realm.write(() => {
        let exercise = realm.create('Exercise', {
            id: 209,
            name: 'Dumbbell Overhead Press',
            category: 'Military Press',
            bodyPart: 'Shoulder'
        }, true);

        exercise.levels.push({
            level: 3,
            equipments: 'DB'
        });

    });
```
I tried every way possible, putting the array direct in the Exercise creation, etc, I had no success..

Cheers

**Comment by alazier** [comment]
Thanks for providing the code. I just pasted it into a new project and it seems to work without issue. Are you making any other realm calls in your app? Are you sure the data you are trying to insert is of the same form as the example you provided?

**Comment by KalebPortillo** [comment]
Hey @alazier
Thanks for your help.
I think the issue was not with realm it self, but something else... But I choose to work without realm for now.
Cheers

**Comment by ismdcf** [comment]
@alazier Do we have to write recursive code if we have nested lists in the  object we are going to save. if so can you tell an easier (rather than using for loops )

**Comment by chandankrishnan** [comment]
how can I write nested object in realm ?
like that 
`{
data:{
"first_name":"evil",
"last_name":"rejex",
"created_by":"123"
}
created_at:"12:12:2019T12:12:12"
}`
