### ISSUE TITLE
Memory not being freed with Swift

### ISSUE THREAD

**Issue by mungbeans2** [realm/realm-js#5217]
[This is supposed to be in the Realm-Swift forum. It got posted here by mistake]

### How frequently does the bug occur?

All the time

### Description

There is no Realm close method when using Swift, and the documentation states:

There is no need to manually close a realm in Swift or Objective-C. When a realm goes out of scope and is removed from memory due to ARC, the realm is closed.
(https://www.mongodb.com/docs/realm/sdk/swift/realm-files/configure-and-open-a-realm/)

But I am finding memory is never released in my app when it's finished using Realm. Here's a code snippet I created which reproduces and condenses the issue:

autoreleasepool {
    NSLog("App memory usage is 19MB at this point")
    iDontReleaseMemory()
    NSLog("Now its 34Mb")
}
NSLog("Its still 34MB")

func iDontReleaseMemory() {
    autoreleasepool {
        do {
            let theConfig = Realm.Configuration()
            let realm = try Realm(configuration: theConfig) // Memory jumps here, and is never freed
        } catch let error as NSError {
      }
   }
}

The memory usage jumps from 19MB to 34MB when the line  let realm = try Realm(configuration: theConfig) is executed. It stays at 34MB forever afterwards.

The usage of Realm is confined within a function and only local variables are used within the function, for good measure its in an autorelease pool, as is its invocation.
If the Realm doesn't go out of scope when the iDontReleaseMemory() exits, and if memory doesn't get freed via the autoreleasepool, then when exactly does it go out of scope and release its memory and how can that be forced if the code above isn't doing so?

### Can you reproduce the bug?

Yes, always

### Version

10.32.2

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Any version of iOS

### Build environment

Which debugger for React Native: ..

### Cocoapods version

10.32.2

**Comment by bmunkholm** [comment]
@mungbeans2 Would you mind creating this in the realm-swift repo instead please? Thanks!
