### ISSUE TITLE
Document boolean comparisons

### ISSUE THREAD

**Issue by edmofro** [realm/realm-js#522]
From https://realm.io/docs/react-native/latest/#queries: 

"At the moment only a subset of the NSPredicate syntax is supported in the query language. Basic comparison operators ==, !=, >, >=, <, and <= are supported for numeric properties. ==, BEGINSWITH, ENDSWITH, and CONTAINS are supported for string properties. String comparisons can be made case insensitive by appending [c] to the operator: ==[c], BEGINSWITH[c] etc. Filtering by properties on linked or child objects can by done by specifying a keypath in the query eg car.color == 'blue'."

Please add something to mention booleans are compared using == etc., for example
- let purebredDogs = dogs.filtered('isPurebred == true');
  to avoid people (like me) trying, for example
- let purebredDogs = dogs.filtered('isPurebred');
- let purebredDogs = dogs.filtered('isPurebred == "true");

P.S. Realm has been working great for me :-)

**Comment by alazier** [comment]
We really need to add full documentation for our query language. It is still being developed so it may be a while until that happens. In the meantime we will try to beef up the existing documentation.

**Comment by Damnum** [comment]
The queries documentation doesn't seem to have changed though.. or is it somewhere else?

**Comment by kristiandupont** [comment]
You are right. I did write some documentation about the queries, but this particular bit is not included.

**Comment by kneth** [comment]
The reference document has been updated.
