### ISSUE TITLE
Realm template err

### ISSUE THREAD

**Issue by wesvh** [realm/realm-js#5227]
### How frequently does the bug occur?
Always

### Description
Actually i have a issue, when i try prebuild on expo this tempalte 
https://www.npmjs.com/package/@realm/expo-template-js/v/0.4.2

Expo returns on the process this : 
`Running "yarn install" in the root dir of your repository 
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[stderr] warning "@realm/react > react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[stderr] warning "expo-splash-screen > @expo/prebuild-config@5.0.7" has unmet peer dependency "expo-modules-autolinking@>=0.8.1".
[4/4] Building fresh packages...
[stderr] error /home/expo/workingdir/build/node_modules/realm: Command failed.
[stderr] Exit code: 127
[stderr] Command: prebuild-install --tag-prefix= ~~r napi || cmake~~js build
[stderr] Arguments: 
[stderr] Directory: /home/expo/workingdir/build/node_modules/realm
[stderr] Output:
[stderr] prebuild-install warn install certificate has expired
[stderr] /bin/sh: 1: cmake-js: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn exited with non-zero code: 127`

The package json is :

`Using package.json:
{
  "name": "myawesomerealmapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@realm/react": "^0.4.1",
    "expo": "~47.0.3",
    "expo-dev-client": "~2.0.0",
    "expo-splash-screen": "~0.17.4",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-get-random-values": "~1.8.0",
    "realm": "^11.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}`

### Can you reproduce the bug?
Always

### Version
47

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
ANDROID 

### Build environment
Which debugger for React Native: ..

**Comment by GitMurf** [comment]
@wesvh see this issue I opened. Do you think this is related? https://github.com/realm/realm-js/issues/5228

**Comment by takameyer** [comment]
We are working on it.  You can track it here #5228
