### ISSUE TITLE
npm install command failed - prebuild-install warn install certificate has expired - 'cmake-js' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GitMurf** [realm/realm-js#5228]
### How frequently does the bug occur?

Always

### Description

I am having trouble installing Realm on Windows 11 with `npm install realm`. I have never had this problem and typically install Realm every few weeks. It looks like a certificate issue?

![image](https://user-images.githubusercontent.com/64155612/211233330-13b8637a-ca3e-40a0-86d7-1e33d902591e.png)

I have seen other reports of this in the past here:

https://github.com/realm/realm-js/issues/4618
https://github.com/realm/realm-js/issues/4619
https://github.com/realm/realm-js/issues/4677
https://github.com/realm/realm-js/issues/4828
https://github.com/realm/realm-js/issues/5227

Specifically I saw this response from Realm team in the past: https://github.com/realm/realm-js/issues/4619#issuecomment-1146604129

![image](https://user-images.githubusercontent.com/64155612/211233278-a888eed3-22c5-42c8-ab64-a9f75e83663b.png)

### Can you reproduce the bug?

Always

### Version

Current and 10.22

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11

### Build environment

Which debugger for React Native: ..

**Comment by GitMurf** [comment]
I definitely think it is a problem with Realm not updating/renewing the cert (or it going down for some reason).

![image](https://user-images.githubusercontent.com/64155612/211238222-b9e80c78-4c79-4f5c-984e-86f33d96fffc.png)

![image](https://user-images.githubusercontent.com/64155612/211238237-acd648ee-c560-487c-8ef7-363e916c0adb.png)

Based on troubleshooting suggestions in this comment: https://github.com/realm/realm-js/issues/4619#issuecomment-1375014960

**Comment by sharan-SKY** [comment]
have similar issue. hopefully a SRE can solve this soon :)

**Comment by GitMurf** [comment]
> have similar issue. hopefully a SRE can solve this soon :)

Yes and it appears others are posting on an old issue here (https://github.com/realm/realm-js/issues/4619) too. As I stated here (https://github.com/realm/realm-js/issues/4619#issuecomment-1375073170) I really hope the Realm team takes a proactive approach this time to automate this process of certificate renewal to make sure this doesn't happen again as it appears this has happened several times over the last couple years :(

**Comment by GitMurf** [comment]
For the time being (and if it happens again in the future), does anyone know if there is a workaround for an expired certificate? I just need to do some testing `tonight` and need a quick realm install via `npm`.

I have tried all the recommendations from past GH Issues with no success such as: `REALM_DISABLE_ANALYTICS=1`, `npm config set strict-ssl false`, `npm install -g --unsafe-perm binding`, `npm config set registry http://registry.npmjs.org/`, etc.

**Comment by wsan3** [comment]
Can someone provide an estimate of how long it'll take for this issue to be resolved? Thanks

**Comment by Vijayakumarktm** [comment]
I'm facing the same issue in Appcenter Today.

**Comment by zabutok** [comment]
if you have stuck maybe for somebody will useful until we are waiting fixes you can use `NODE_TLS_REJECT_UNAUTHORIZED=0 yarn install`

**Comment by alpfactory-alex** [comment]
Same here our whole CI is stuck this is the second time again.

VERY annoying considering we're paying for realm and have those outtakes.

**Comment by NobodyButMe-Haiya** [comment]
> if you have stuck maybe for somebody will useful until we are waiting fixes you can use `NODE_TLS_REJECT_UNAUTHORIZED=0 yarn install`

we try npm install okay but upon  run in ios it complain the same thing  - react native .

**Comment by alpfactory-alex** [comment]
using NODE_TLS_REJECT_UNAUTHORIZED=0 npm ci worked for us for now thanks for the hint @zabutok !

**Comment by bmunkholm** [comment]
Very sorry about this - it shouldn't happen of course. We are looking into this.

**Comment by phuongwd** [comment]
```
Installing RealmJS (10.1.4)
[!] /bin/bash -c 
set -e
./scripts/xcode-download-realm.sh ./scripts

Resolved requirements: {
  SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-10.1.6.tar.gz',
  SYNC_ARCHIVE_ROOT: 'core'
}
Resolved options: { platform: 'ios', sync: true }
No lockfile found at the target ****/node_modules/realm/vendor/realm-ios, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz
FetchError: request to https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz failed, reason: certificate has expired
    at ClientRequest.<anonymous> (****/node_modules/realm/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED'
}
```

**Comment by mickeylam** [comment]
> [4/4] Building fresh packages...
error /builds/.../node_modules/realm: Command failed.
Exit code: 127
Command: prebuild-install --tag-prefix= -r napi || cmake-js build
Arguments: 
Directory: /builds/.../node_modules/realm
Output:
prebuild-install warn install certificate has expired
/bin/sh: 1: cmake-js: not found

Having the same issue during yarn stage in docker image https://github.com/react-native-community/docker-android

docker: reactnativecommunity/react-native-android:5.4
yarn: v1.22.17

**Comment by zabutok** [comment]
@phuongwd  we have latest version of realm what builds from sources please try `GIT_SSL_NO_VERIFY=true pod install`

**Comment by phuongwd** [comment]
@zabutok thanks for response.

> @phuongwd we have latest version of realm what builds from sources please try `GIT_SSL_NO_VERIFY=true pod install`

Its not working. same error message

```
Installing RealmJS (10.1.4)
[!] /bin/bash -c 
set -e
./scripts/xcode-download-realm.sh ./scripts

Resolved requirements: {
  SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-10.1.6.tar.gz',
  SYNC_ARCHIVE_ROOT: 'core'
}
Resolved options: { platform: 'ios', sync: true }
No lockfile found at the target ****/node_modules/realm/vendor/realm-ios, proceeding.
Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz
FetchError: request to https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/ ****/node_modules/realm/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'CERT_HAS_EXPIRED',
  code: 'CERT_HAS_EXPIRED'
}

phuong@Hello ios % GIT_SSL_NO_VERIFY=true  pod install
```

**Comment by zabutok** [comment]
> @zabutok thanks for response.
> 
> > @phuongwd we have latest version of realm what builds from sources please try `GIT_SSL_NO_VERIFY=true pod install`
> 
> Its not working. same error message.
> 
> ```
> Installing RealmJS (10.1.4)
> [!] /bin/bash -c 
> set -e
> ./scripts/xcode-download-realm.sh ./scripts
> 
> Resolved requirements: {
>   SYNC_SERVER_FOLDER: 'sync',
>   SYNC_ARCHIVE: 'realm-sync-cocoa-10.1.6.tar.gz',
>   SYNC_ARCHIVE_ROOT: 'core'
> }
> Resolved options: { platform: 'ios', sync: true }
> No lockfile found at the target ****/node_modules/realm/vendor/realm-ios, proceeding.
> Download url: https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz
> FetchError: request to https://static.realm.io/downloads/sync/realm-sync-cocoa-10.1.6.tar.gz failed, reason: certificate has expired
>     at ClientRequest.<anonymous> (/ ****/node_modules/realm/node_modules/node-fetch/lib/index.js:1491:11)
>     at ClientRequest.emit (node:events:527:28)
>     at TLSSocket.socketErrorListener (node:_http_client:454:9)
>     at TLSSocket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'CERT_HAS_EXPIRED',
>   code: 'CERT_HAS_EXPIRED'
> }
> 
> phuong@Hello ios % GIT_SSL_NO_VERIFY=true  pod install
> ```

oh yes now i see it is just another node script which should download archive `https://github.com/realm/realm-js/blob/v10.1.4/scripts/xcode-download-realm.sh#L32 `  then you can try something like `export NODE_TLS_REJECT_UNAUTHORIZED=0` but don't forget return it back when issue will be fixed, I hope everything works out for you

**Comment by frankfuu** [comment]
Using realm 10.24.0, react-native 0.69.7 and nodejs v16.14.1 and receiving the same error.

**Comment by Waltari10** [comment]
Same error here

**Comment by malikmani** [comment]
I am also facing the same issue.

**Comment by MrFuentastic** [comment]
@takameyer @bmunkholm Any ETA for certificate being renewed?

**Comment by muhammadshaheer-er** [comment]
Facing same issue "prebuild-install WARN install certificate has expired" Blocked,

**Comment by takameyer** [comment]
@MrFuentastic It's being addressed with high priority and should be fixed soon.  Will update here when it's completed.  Sincerely apologize for the inconvenience.

**Comment by MrFuentastic** [comment]
No worries, auto renewals haven't worked on our dokku server for whatever reason so I've had this happen a few times. :/

**Comment by Kishore0297** [comment]
Facing the  same issue here in appcenter.

**Comment by geragray** [comment]
Downloading of binaries from static.realm.io has been fixed. Please accept our apologies for the inconvenience.

**Comment by GitMurf** [comment]
For the future, if this happens again, below is a one liner solution for Windows users using PowerShell to get around the certificate error as a TEMPORARY workaround as it is not good practice to ignore `NODE_TLS_REJECT_UNAUTHORIZED`. Based off suggestions above here (https://github.com/realm/realm-js/issues/5228#issuecomment-1375191886) and here (https://github.com/realm/realm-js/issues/5228#issuecomment-1375222840).

I know it is verbose (I am not the greatest at PS) but also posting here for documentation purposes for myself for the future :) This errors on the side of caution printing out whether you currently have a value set for `NODE_TLS_REJECT_UNAUTHORIZED` and then resets it to that original value after the Realm install or sets it back to `$null` if it wasn't set in the first place.

Note that this is using `npm ci` which requires a `package-lock.json` file to be present. Hope this helps others in the future!

```powershell
$envVarName = "NODE_TLS_REJECT_UNAUTHORIZED"; $envVarNewValue = "0"; if((Get-Item "env:$envVarName" -ErrorAction Ignore)){$envVarOrigValue = (Get-Item "env:$envVarName").Value}else{$envVarOrigValue = $null}; Write-Host "$envVarName originally set to: $envVarOrigValue"; Set-Item "env:$envVarName" $envVarNewValue; Write-Host "$envVarName has been CHANGED to: " (Get-Item "env:$envVarName").Value; npm ci; Set-Item "env:$envVarName" $envVarOrigValue; Write-Host "$envVarName has been SET BACK to original value: " (Get-Item "env:$envVarName" -ErrorAction Ignore).Value;
```
