### ISSUE TITLE
Encryption error when opening Realm

### ISSUE THREAD

**Issue by anderpaz** [realm/realm-js#5237]
### How frequently does the bug occur?

Sometimes

### Description

I have several devices running without any problems, but one device is giving me this error when opening the database at all times

   ```
const KEY = '7pwYH@pg-Exw1Z0+VOV3J!OV3*JNxBw@ZW0V1OVa!3JNN-WrMql@SEkIz8+KB2GH;
   const encryptionKey = new Uint8Array(KEY.split('').map((val) => val.charCodeAt(0)));
   ew Realm({
        path: 'app.db',
        encryptionKey,
        inMemory: false,
        schemaVersion: 3,
        schema: [schemas.schemaReduxPersist, schemas.schemaPosition, schemas.schemaChat],
        shouldCompact: (totalBytes, usedBytes) => {
          const oneHundredMB = 1 * 1024 * 1024 * 1024; // 1 Gb
          return totalBytes > oneHundredMB && usedBytes / totalBytes < 0.5;
        },
      })
```

### Stacktrace & log output

```shell
"stack":"Error: Exception in HostFunction: Unable to open a realm at path '/data/data/com.spacecom.mpmobile/files/app.db': Realm file decryption failed Path:Exception backtrace:\n<backtrace not supported on this platform>.\n    at Realm (native)\n    at apply (native)\n    at Realm (JavaScript:8:41)\n    at connect (address at index.android.bundle:1:1067456)\n    at use (address at index.android.bundle:1:1067697)\n    at size (address at index.android.bundle:1:1715039)\n    at ?anon_0_ (address ..."}
```

### Can you reproduce the bug?

No

### Version

30

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@anderpaz Thanks for reporting this.  I'll look this over with the team and get back to you.

**Comment by Waltari10** [comment]
Hey, sorry, but which npm Realm package version does number "30" correlate with? Bit confused about the versioning here.

**Comment by kneth** [comment]
@anderpaz Please tell us the Realm version you are using ("30" doesn't correspond to any Realm version).

**Comment by anderpaz** [comment]
Sorry for the delay, the version I'm using.

@realm/common@0.1.4
@realm/network-transport@0.7.2
realm@11.3.1
