### ISSUE TITLE
Offline Support Similar to Couch/Pouch?

### ISSUE THREAD

**Issue by geirman** [realm/realm-js#524]
I'm specifically interested in offline support similar to Couch/Pouch for React Native. I would like to write objects to a local version that will sync to the online version when connectivity is available. My use case involves data and blob (or base64 encrypted) media objects (JPG). 

I was hoping Realm supported this out of the box and found this quote on your [Introducing Realm Post](https://realm.io/news/introducing-realm/)...

> ## 4. Get “offline mode” for free
> 
> Adding local persistence for offline access is often seen as an extra and time-consuming step, and is widely requested by users. In contrast, we’ve found that if you just replace your custom app objects with Realm objects, you often get offline mode for free. It won’t solve things like offline writes without a bit more work, of course, but it’s a painless way to let people see their data and interact with it while offline without incurring any extra work.

What do you mean when you say "without a bit more work" exactly?

**Comment by alazier** [comment]
At the moment there is no builtin synchronization with the server - you currently need to build your own using REST or other apis. In the case that you are doing writes offline you may also need to do some sort of conflict resolution depending on you application and data model. Realm is hard at work building end to end sync solution that does all of this for you automatically but this is not yet done, and there is not currently an estimate for when it will be available.

**Comment by geirman** [comment]
Thank you for the response. Totally understand and look forward to seeing how Realm evolves. Happy to hear a sync solution is in the works.

**Comment by abhaytalreja** [comment]
@geirman - I have a similar situation. I am using Meteor as a server and reactively syncs with phone when it's available. Once, i am done with my app, i will probably do a blog/video on how to..

But, i agree, offline support will be awesome!

**Comment by geirman** [comment]
@abhaytalreja thx for the head's up. I'm a huge fan of meteor, but haven't created anything practical with it yet. Are you building your mobile app in react native? I've been meaning to explore RN+Meteor.

**Comment by abhaytalreja** [comment]
@geirman - Me too, love Meteor! my app is pretty much read for online/iOS - I just wanted to get my head around Android. It works! even the synchronization! and everything is so real time. I am actually building a game! as against to just an app! It was difficult, but i think i am closer to getting done.

**Comment by ReDetection** [comment]
As far as I can tell, this is working now

**Comment by kneth** [comment]
[Realm Sync](https://docs.mongodb.com/realm/sync) provides this functionality.
