### ISSUE TITLE
Server error when MongoDB Atlas rules on documents of collection contains %%user

### ISSUE THREAD

**Issue by kulxtreme** [realm/realm-js#5240]
### How frequently does the bug occur?

Always

### Description

If there is added rule using %%user, the call to MongoDB Atlas finishes with server error. So there is a problem either with implementation of %%user in MongoDB Atlas, that is much more probable, or this SDK in web browser is not sending some kind of data about user. The bug can be caused when %%user is undefined in MongoDB Atlas. One example of the rule for  searching in collection when the call fails:
```
{"%%user.id": "rfretgyuji7js"}
```
MongoDB Atlas has awful tech support so there is low probability they will investigate and fix this issue.

### Can you reproduce the bug?

Always

### Version

latest

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Mozilla Firefox

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@kulxtreme Thanks for reporting this.  I'll bring this up with the cloud team.

**Comment by takameyer** [comment]
@kulxtreme Just to follow up, is this a rule configuration you have set in Device Sync?  Any extra context and settings you could share would be helpful.

**Comment by takameyer** [comment]
In looking at the syntax you are using to define a rule, it would appear you are misusing `%%user.id`.  One can set rules with the following syntax:
```
{
  "rules": {
    "Tasks": [
      {
        "name": "manager",
        "applyWhen": { 
          "%%user.custom_data.isManager": true
        },
        "read": { 
          "manager": "%%user.id"
        },
        "write": { 
          "manager": "%%user.id"
        }
      }
    ]
  },
  "defaultRoles": [
    {
      "name": "users",
      "applyWhen": {},
      "read": true,
      "write": false
    }
  ]
}
```
In the case above, the Task model has a `manager` field, and would set `read` and `write` to true, for all data where the `manager` is equal to the current `%%user.id`. 
For more information, please consult our [documentation](https://www.mongodb.com/docs/atlas/app-services/mongodb/define-roles-and-permissions/).
If you have more questions about defining rules, please reach out to our [forums](https://www.mongodb.com/community/forums), where we have more folks with more knowledge about that than I that are able to help you out.

I'm closing this issue for now, as this is not an issue with `realm-js`, but a question about Atlas App Services.  Cheers.

**Comment by kulxtreme** [comment]
The rule is set on MongoDB Atlas under section 'Rules'.

**Comment by takameyer** [comment]
```
{"%%user.id": "rfretgyuji7js"}
```
Is this the complete rule configuration you are trying to set?  If so, it is not a valid.  `%%user` is not a valid right hand value, unless it is wrapped in a clause such as `applyWhen`.
