### ISSUE TITLE
Linking objects with id

### ISSUE THREAD

**Issue by dridi-spectrum** [realm/realm-js#5245]
### Problem

I have two realm objects:

```
    const PersonSchema = {
      name: 'Person', properties: {name: 'string', cars: 'Car[]'},
    };

    const CarSchema = {
      name: 'Car',
      properties: {model: 'string', owner: {type: 'linkingObjects', objectType: 'Person', property: 'cars'}},
    };
```

I need to create a car and reference the owner directly without passing by the Person object and pushing the new created Car...

Now: 

```
    realm.write(() => {
        const owner = realm.objectForPrimaryKey('Person', ownerID);
        owner.cars.push({
          model: 'Model name'
        });
    });
```

### Solution

I need to linking the owner to car instead of owner.cars.push(car)

```
    realm.write(() => {
        const car = realm.create('Car', {
          model: 'Model name',
          owner: ownerID
        });
    });
```

Any help PLZ !

### How important is this improvement for you?

Dealbreaker

**Comment by gaoxiaosong1113** [comment]
I have a problem

I have two realm objects:

```
export const BookSchema = {
  name:'Book',
  primaryKey: 'id',
  properties: {
    id: 'string',
    name: 'string',
    tags: 'Tags[]',
  },
};

export const TagSchema = {
  name:'Tags',
  primaryKey: 'id',
  properties: {
    id: 'string',
    label: 'string',
  },
};
```

Page1 Manage tag information 

A tag is added to page2. 
```
//  create
{
     id: 'Tags-1676464592406',
     label: 'cartoon'
}
```

Page 2 Information of management book


```
//  create
{   
     id: 'Books-1676464592406',
     label: 'web',
     tags: [
          id: 'Tags-1676464592406',
          label: 'cartoon'
     ]
}
```

When adding a tag to tags in page1, you will be prompted

```
 Attempting to create an object of type 'Tags' with an existing primary key value ''Tags-1676464592406''.
```
What method should I use to solve the problem

**Comment by kneth** [comment]
@dridi-spectrum `linkingObjects` is a computing property, and you cannot assign directly to it. You can consider modelling in a different way:

```js
const PersonSchema = {
  name: 'Person', 
  properties: {
    name: 'string',
  },
};

const CarSchema = {
  name: 'Car',
  properties: {
    model: 'string', 
    owner: 'Person[]'
  },
};
```
It is a different model where each car has 0, 1, or many owners. You can add a `linkingObjects` property to `Person` to be able to easily get the cars.

Your update can now be:

```js
realm.write(() => {
  const owner = realm.objectForPrimaryKey('Person', ownerID);
  realm.create("Car", {
    model: 'Model name',
     owner: [owner]
   });
});
```

**Comment by kneth** [comment]
@gaoxiaosong1113 

I guess you get the error message when calling `Realm.create()`. You might add a third argument to let `create()` to behave like an upsert operation: https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#create

**Comment by gaoxiaosong1113** [comment]
@kneth 

thank

`instance.create(tabName, obj, 'all')`
