### ISSUE TITLE
Document limitations and performance issues with Chrome Debug

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#525]

**Comment by vikeri** [comment]
Was just about to dismiss Realm since it took ~1000 times longer to read 10 000 records when the debugger was connected compared to when it wasn't connected.
Debug in Chrome: ~76 000 ms
No debugging: ~70 ms

**Comment by vikeri** [comment]
What is the reason for this being closed, documentation added or limitation fixed?

**Comment by kristiandupont** [comment]
[https://realm.io/docs/javascript/latest/#chrome-debugging-is-slow](Documentation), sadly. Follow the issue here: #491
