### ISSUE TITLE
How to do step debugging with Realm for react-native app ?

### ISSUE THREAD

**Issue by poonamdhomane** [realm/realm-js#5257]
### How frequently does the bug occur?

-- select --

### Description

As Realm does not support chrome debugging, and flipper not showing up the file viewer. How to do step debugging with Realm for react-native app ?

### Can you reproduce the bug?

Always

### Version

"realm": "^11.3.1",

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15.5

### Build environment

Which debugger for React Native: Visual Studio Code Debugger

### Cocoapods version

1.11.3

**Comment by takameyer** [comment]
@poonamdhomane Activate Hermes and open up the Flipper debugger.  Add this line to some part of your code
```
debuggger;
```
This will be a breakpoint.  From there you can step through the code.

**Comment by poonamdhomane** [comment]
@takameyer  thanks.
It's working,  files got displayed in flipper's hermes file viewer after adding **debugger**
