### ISSUE TITLE
Operation not permitted IOS

### ISSUE THREAD

**Issue by MisterAlex95** [realm/realm-js#526]
Hello, 
I have a problem with realm on IOS (not on Android...).
When I launch my application there is a red screen with this error: 

**Unable to open realm at path '/var/mobile/Documents/name.realm.management': make_dir() failed: Operation not permitted.**

Someone have a clue to solve it ? 

"react": "^15.2.0",
"react-native": "^0.28.0",
"realm": "^0.14.1"

Thanks.

**Comment by alazier** [comment]
Were you able to figure this out? Looks like the path that the realm is being written to isn't valid. Are you passing in a custom path? If so could you share the code you are using to initialize your Realm?

**Comment by MisterAlex95** [comment]
I don't change the path... :/

**Comment by MisterAlex95** [comment]
We just change the name of the file with this : 
path: 'voicemail.realm'

**Comment by alazier** [comment]
I have tried using a custom path but haven't yet run into this issue. Are you seeing this on the simulator, device, or both?

**Comment by alazier** [comment]
I'm assuming you are only seeing this on device based on the path you are seeing. In a sample project I just created where I initialize the realm as ```new Realm({path: 'custom.realm', schema: []});```, I am getting this path: `/var/mobile/Containers/Data/Application/1F9C66B2-0F8B-4728-B5AC-EAEEC05BAB69/Documents/custom.realm`

The problem you are having is that the Documents directory you are getting doesn't seem to be correct but I'm not sure why.

**Comment by MisterAlex95** [comment]
Only on device ! 

`const realm = new Realm({path: 'voicemail.realm',
  schema: [VoicemailSchema],
  schemaVersion: 2,
  migration: function(oldRealm, newRealm) {
    const voicemails = newRealm.objects('Voicemails');
    for (let i = 0; i < voicemails.length; ++i) {
      voicemails[i].thumbnailPath = '';
      voicemails[i].editing = false;
    }
  },
});`

The path is : **/var/mobile/Documents/voicemail.realm.management**

**Comment by alazier** [comment]
Not sure where that path comes from we are using `NSSearchPathForDirectoriesInDomains` to determine the path to use. Searching online it looks like the path you are seeing is sometimes used  on jailbroken devices - unfortunately I don't have jailbroken device to try to confirm this. If this is the case it sounds like you might need to possibly create the`/var/mobile/Documents` directory and/or make sure it has the proper permissions. Alternative you can specify the full path to a realm in another writable dir (starting with a `/`) which would bypass this issue completely.

**Comment by MisterAlex95** [comment]
Ok I'll try it ! 
Thanks !

**Comment by MisterAlex95** [comment]
I tried to set the path manually with RNFS:

```
const RNFS = require('react-native-fs');
const pathPrefix = RNFS.DocumentDirectoryPath;

const realm = new Realm({path: pathPrefix + '/voicemail.realm',
  schema: [VoicemailSchema],
```

**Comment by alazier** [comment]
The problem is the documents directory you are getting back is not writable. Either you need to change the permissions of this directory, or you need to use a different directory where you have write access.

**Comment by alazier** [comment]
Hopefully you were able to resolve this.

**Comment by jap99** [comment]
Hey folks, ever figure this one out? 

I'm having the same issue at the moment - the path i'm using is /var/mobile/Containers/Data/Application/576C4546-FE63-4F93-A643-17F2DEF1F981/sample_tblview.pdf

**Comment by nileshkikani** [comment]
I hope this will help for this issue : https://github.com/realm/realm-cocoa/issues/4809
