### ISSUE TITLE
Or operator with filtered in react native not working

### ISSUE THREAD

**Issue by poonamdhomane** [realm/realm-js#5261]
### How frequently does the bug occur?

-- select --

### Description

I am trying to add condition for 
if title = "test1" or title ="test2"   then show the records to user from a collection
like below 

realm.objects('table').filtered('title == $0 OR title == $1', 'test1', 'test2')

but its not working 

what is the exact way of using OR operator (IN operator ) in realm in react native ?
spend lot of time by trying different ways but not wroked

### Can you reproduce the bug?

Always

### Version

"realm": "^11.3.1",

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15.5

### Build environment

Which debugger for React Native: ..
flipper

### Cocoapods version

1.11.3

**Comment by Frans-L** [comment]
> but its not working

Are you receiving an error message or is the received result incorrect or something else?

**Comment by kneth** [comment]
The operator is [supported](https://www.mongodb.com/docs/realm/realm-query-language/#logical-operators). Moreover, I haven't been able to reproduce it (see https://github.com/realm/realm-js/pull/5282).
