### ISSUE TITLE
Merge realm-core #5993 PR

### ISSUE THREAD

**Issue by rodrigobertolottizinsp** [realm/realm-js#5281]
### Problem

Hi everyone. 
Im having this https://github.com/realm/realm-core/issues/6207 issue with realm-core, that was supposed to be fixed in here https://github.com/realm/realm-core/pull/5993 . 
I took a look at the releases page of this library and I couldn't find any references to that PR being included in any release, do you know if it is already merged on some release? 
If its not, do you plan to do it in any future version?

Thank you!

### How important is this improvement for you?

Dealbreaker

**Comment by bmunkholm** [comment]
Hi @rodrigobertolottizinsp 
That was released in 11.2.0. You can see that in the [CHANGELOG.md](https://github.com/realm/realm-js/blob/master/CHANGELOG.md#1120-2022-11-12)
