### ISSUE TITLE
Android doesn't work on RN 0.71.0 with new architecture enabled

### ISSUE THREAD

**Issue by RalissonMattias** [realm/realm-js#5284]
### How frequently does the bug occur?

Always

### Description

I'm trying to run the realm with the latest version of React Native with the new architecture enabled, but I get an error when running `yarn android`. When the new architecture is turned off it works normally

### Stacktrace & log output

```shell
ERROR  Error: Missing Realm constructor. Did you run "pod install"? Please see https://docs.mongodb.com/realm/sdk/react-native/install/ for troubleshooting, js engine: hermes
 LOG  Running "test071" with {"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}
 ERROR  Invariant Violation: "test071" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Run: npx react-native init projectName
2. Enable new architecture
3. Run: yarn android
4. Follow these steps: [Quick Start](https://www.mongodb.com/docs/realm/sdk/react-native/quick-start/)

### Version

11.3.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 12

### Build environment

```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 4.00 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/Documents/test071/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ralissonmattias/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
@RalissonMattias Thank you for reporting.

Currently we don't support the new architecture (TurboModules in particular). 

Does it work when you disable new architecture?

**Comment by RalissonMattias** [comment]
> @RalissonMattias Thank you for reporting.
> 
> Currently we don't support the new architecture (TurboModules in particular).
> 
> Does it work when you disable new architecture?

Yes, it works with the new architecture turned off. Do you have any PR so I can follow the development? I believe this will be a big step for my apps. Thank you very much

**Comment by joaotmachado** [comment]
@kneth any news about a PR for this issue?

**Comment by kneth** [comment]
@joaotmachado Not big updates to share. We have posted https://github.com/reactwg/react-native-new-architecture/discussions/95 to shared with the greater React Native community (and library maintainers in particular) which directions we wish to explore.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
