### ISSUE TITLE
Realm version 11.3.0 showing old realm core version in stack trace

### ISSUE THREAD

**Issue by rodrigobertolottizinsp** [realm/realm-js#5289]
### How frequently does the bug occur?

Sometimes

### Description

We are currently using realm javascript library version 11.3.0 and we got this https://github.com/realm/realm-core/issues/6207 error twice yesterday. 
If you look at the stack trace it says 

please_report_this_issue_in_github_realm_realm_core_v_12_9_0

but according to release notes version 11.3.0 of realm-js should use realm-core version 13.1.0 

It's quite important to have the correct realm-core version because v12.12 includes some major bug fixes happening in iOS  

Any ideas why this could be happening?

Thank you very much

### Can you reproduce the bug?

No

### Version

11.3.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@rodrigobertolottizinsp This is indeed strange. 

Please verify the version (`node_modules/realm/dependencies.list` or `node_modules/realm/package.json`). You might also have to clear all build folders and caches when you upgrade. 

Finally, did you run `pod install` after upgrading?

**Comment by rodrigobertolottizinsp** [comment]
Thank you for your response. 
The dependencies.list file indicates REALM_CORE_VERSION=13.1.0
Do you know if there's the possibility that this errors has happened on the past with the old realm version and they were fired now?

**Comment by rodrigobertolottizinsp** [comment]
I checked at the realm-core code for the release commit corresponding to v13.1.0 and it doesn't seem to be any references to version 12.9 as that log says, so probably the pods or cache were outdated for some reason.
There is any way to check the actual realm-core version from realm-js code besides the dependencies.list file?

**Comment by kneth** [comment]
> There is any way to check the actual realm-core version from realm-js code besides the dependencies.list file?

Unfortunately not (I have asked the [Realm Core](https://github.com/realm/realm-core) team) but it might be something we can add.
