### ISSUE TITLE
Missing this file "libRealmNode.dylib". Anyone help me?

### ISSUE THREAD

**Issue by thaivinhloc** [realm/realm-js#530]

**Comment by alazier** [comment]
Can you give a bit more information? What environment/platform are you trying to build for?

**Comment by alazier** [comment]
What is trying to load this file? If you are using `rnpm`, it should be adding `libRealmReact.a` to your xcodeproj, not the filename you have listed. Can you post the exact error message you are seeing and explain when in the build process it is being displayed?
