### ISSUE TITLE
App always crashes after release

### ISSUE THREAD

**Issue by agunbuhori** [realm/realm-js#5307]
### How frequently does the bug occur?

Always

### Description

I tried to use realm in debug mode, it's working fine. But when I release the app with ./gradlew assembleRelease and install the app on my phone, the app always crashes without showing any messages. 

I haven't found any clear documentation. 

### Can you reproduce the bug?

No

### Version

11.3.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

31

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@agunbuhori Which React Native version do you use?

Please check the [compatibility matrix](https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md). Furthermore, please notice that we have deprecated version 11.3.2.

**Comment by shaikhhafizf** [comment]
I am facing the same issue with realm@11.3.1 and react-native@0.70.5.

app work fine in debug but when create release it crashes and one of the errors on the **`crash is Failed to create NativeModule "Realm"`**

Can help me in solving problem

**Comment by FN-FAL113** [comment]
same issue on the latest react native and realm version, SIGABRT signal from logcat and librealm.so are mentioned from the debug messages
I have react reanimated 2 not sure if it would cause such issues but mine crashes on the first realm.write() and realm.create()

**Comment by kneth** [comment]
@shaikhhafizf @FN-FAL113 We need more information to help. It includes dependencies, which JS engine you are using and whether you have enable the new architecture or not.

**Comment by FN-FAL113** [comment]
> @shaikhhafizf @FN-FAL113 We need more information to help. It includes dependencies, which JS engine you are using and whether you have enable the new architecture or not.

I'm using hermes and new architecture is disabled, I'd do a separate issue report on this but my time is really scarce
![image](https://user-images.githubusercontent.com/88238718/217553118-7611e4e5-9129-46ae-a383-8c2dbf03ab59.png)

**Comment by kneth** [comment]
As https://github.com/realm/realm-js/issues/5393 has been closed, and @shaikhhafizf never replied, I am closing the issue
