### ISSUE TITLE
Issue with expo

### ISSUE THREAD

**Issue by 60red** [realm/realm-js#5321]
### How frequently does the bug occur?

-- select --

### Description

Hi,

  I've used expo with realm for a month, but since yesterday, i've got the following error on app launching with npx expo run:android.

  I have "realm": "^11.3.1" in my package.json. I suspect gradle updates or explo-cli update.

  Please help, i'm completely blocked....

   ERROR  Error: Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError: io.realm.react.RealmReactModule
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Stacktrace & log output

```shell
ERROR  Error: Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError: io.realm.react.RealmReactModule
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

### Can you reproduce the bug?

-- select --

### Version

21

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@60red we released a now deprecated version of `realm` 11.3.2.  Can you ensure this is not installed?  One way would be to remove `^` from your package.json.

**Comment by 60red** [comment]
It's done "realm": "11.3.1"
In node_mobules/realm/package.json i have "version": "11.3.1",
I've deleted node_modules directory and android
Did a npx expo prebuild then npx expo run:android

But still same error 

ERROR  Error: Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError: io.realm.react.RealmReactModule
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

What is strange is i have backup copies of my project, when i run npx expo run:android, i have the same errors.

**Comment by 60red** [comment]
Would it be possible it has been cause by a gradle or expo cli update ?

I'ts really blocking for our project

**Comment by 60red** [comment]
I'm working with  "react-native": "0.70.5",

**Comment by takameyer** [comment]
@60red dumb question, but I often see this error when I have a bundler running for another project in another directory.  You aren't happening to have this issue as well or?

**Comment by 60red** [comment]
Well, i've started my computer again to be sure nothing was running... And it works... Thanks !

**Comment by 60red** [comment]
Do you think realm 11.4.0 would work ?

**Comment by takameyer** [comment]
@60red It will not.  It has a hard dependency on RN 0.71.0.  But when Expo has a new release it will be compatible.  We are currently working on a method to break this hard dependency on future releases.

Happy to hear you got it working!
