### ISSUE TITLE
GHA: Break up iOS build into platform types and run in parallel

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#5331]
Currently the iOS build step takes the longest out of all of the builds.  This is because it must build for 3 platforms.  We could speed things up by splitting up the build task by platform and combining these into the `realm-js-ios.xcframework`.  This may require tweaking of the `scripts/build-ios.sh`.

**Comment by kraenhansen** [comment]
This issue could probably be merged with #4939 (one way or the other).
