### ISSUE TITLE
Sync Error: realm::util::websocket::Error: - code: 10: Bad WebSocket response 4xx client errors

### ISSUE THREAD

**Issue by grantespanetstoa** [realm/realm-js#5341]
### Description

Upon building my iOS app (while authenticated) on expo-client, getting an error at sync:

```
        schema={MainRealmSchema}
	path='Main.realm'
	fallback={fallback}
	sync={{
		flexible: true,
		onError: (_session, error: any) => {
			console.log("ERROR: ", error)
		}
	}}
```

> LOG ERROR: {“category”: “realm::util::websocket::Error”, “code”: 10, “isFatal”: true, “message”: “Bad WebSocket response 4xx client errors”, “name”: “Error”, “userInfo”: {}}

I don’t see any docs describing this error/code, what is code 10?

For additional context, I have a `User` schema with a property which has 3 nested arrays of objects

ex: `user_draft_groups_categories_presets`

I can reproduce the issue when my User has the data below:

My `groups` array has about 6 elements

My `categories` array has about 25 elements in each group array

My `presets` array has about 1-2 elements in each category array

Each `preset` array has an objectId and string.

The preset’s strings usually contain text of about 400 characters (sometimes more or less).

Interestingly, if I change all of the presets’ strings to a hardcoded “A”, restart/build the app, then it seems to work without error. However, if I change the data back to user input, then I get the error above.

Is this a particular limitation issue? Thanks.

### Stacktrace & log output

```shell
LOG ERROR: {“category”: “realm::util::websocket::Error”, “code”: 10, “isFatal”: true, “message”: “Bad WebSocket response 4xx client errors”, “name”: “Error”, “userInfo”: {}}
```

### Can you reproduce the bug?

Always

### Version

"@realm/react": "^0.4.1",

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.2

### Build environment

"@realm/react": "^0.4.1",
"expo": "~47.0.12",

### Cocoapods version

Podfile.lock: - RealmJS (11.3.0):

**Comment by kneth** [comment]
@grantespanetstoa Thank you for reporting.

It could be interesting to see the log leading to this error (using `Realm.App.Sync.setLogger()` and `Realm.App.Sync.setLogLevel()`).

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
