### ISSUE TITLE
'yarn add realm' command throws error

### ISSUE THREAD

**Issue by dimitris4** [realm/realm-js#5363]
### How frequently does the bug occur?

Always

### Description

"react": "18.2.0",
 "react-native": "0.71.1",

I'm trying to install realm in a RN project with yarn v. 1.22.18.

### Stacktrace & log output

```shell
warning realm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

[2/4] 🚚  Fetching packages...

error An unexpected error occurred: "https://registry.yarnpkg.com/realm/-/realm-11.4.0.tgz: incorrect data check".

info If you think this is a bug, please open a bug report with the information provided in ...

info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Can you reproduce the bug?

Always

### Version

11.4.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Mac monterey 12.6

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.11.3

**Comment by kneth** [comment]
@dimitris4 Are you using node 19? If so, your issue might be the same as https://github.com/realm/realm-js/issues/5136, and you can try to download to node 18.

**Comment by kneth** [comment]
Thanks for the update
