### ISSUE TITLE
Doing non-realm things inside write transaction causes error in release build

### ISSUE THREAD

**Issue by cpsubrian** [realm/realm-js#538]
This could totally be a misunderstanding of how the write transactions work, but I was running into an error that only occurred in my release build. My code originally looked something like this:

```js
function saveTheThing (thing, cb) {
  realm.write(() => {
    let obj = realm.create('Thing', thing, true)
    cb(null, obj)
  })
}
```

This produced an error **only in release builds**. I don't know what the error was because no message was outputted to the console (I can't get an error messages to show up in release builds, only stack traces, but that's another issue).

When I changed the code (on a whim) to this, it worked:

```js
function saveTheThing (thing, cb) {
  let obj
  realm.write(() => {
    obj = realm.create('Thing', thing, true)
  })
  cb(null, obj)
}
```

My natural inclination was towards the first pattern, because I assume that since the write transaction happens inside a callback, I shouldn't assume its synchronous. Will write transactions always be synchronous in relation to the code around it? If so, how do you avoid code slowdowns due to IO between the js thread and wherever realm is storing stuff?

**Comment by alazier** [comment]
Seems odd that things wouldn't be working only in release mode. My guess would be that the callback could be throwing and exception which would then cancel the write transaction leading to different behavior. Is it possible that this is what is happening? You could wrap your callback in a try/catch block to be safe which would avoid this situation altogether.

At the moment write transactions are always synchronous. If you are doing longer running operations you can split them up into multiple write transactions, and/or us await async to prevent the ui from blocking.

**Comment by cpsubrian** [comment]
The change above is literally all I did to get it working in release, so as far as I can tell the callback is not triggering any exceptions (or else they still be an issue?).

Thanks for the detail about how write transactions fire.
