### ISSUE TITLE
Realm not working with react native@0.70.6 in my mac mini

### ISSUE THREAD

**Issue by vaghasiya-mayur** [realm/realm-js#5383]
### How frequently does the bug occur?

Always

### Description

I created an empty react-native project and then installed Realm. After installing my react-native app, I received a white screen and was unable to connect to Metro.

I've been working on it for a few days now; how can I resolve this problem? .

**This issue occur in only for ios**

node :- v18.14.0, 
macos version :- 13.1 (Ventura)

Here is my package.js file
```
{
    "name": "AwesomeProject",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint ."
    },
    "dependencies": {
        "@realm/react": "^0.4.3",
        "react": "18.1.0",
        "react-native": "0.70.6", //aslo tried with 0.70.3
        "realm": "^11.3.1" // also tried with 11.4.0, 11.2.0, 11.0.0, 10.24.0, 6.1.8
    },
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "@babel/runtime": "^7.12.5",
        "@react-native-community/eslint-config": "^2.0.0",
        "babel-jest": "^26.6.3",
        "eslint": "^7.32.0",
        "jest": "^26.6.3",
        "metro-react-native-babel-preset": "0.72.3",
        "react-test-renderer": "18.1.0"
    },
    "jest": {
        "preset": "react-native"
    }
}
```

![image](https://user-images.githubusercontent.com/53115279/217166254-dfc5cf94-2025-4de0-b07d-83b44698cb19.png)

### Can you reproduce the bug?

Always

### Reproduction Steps

When create new react-native project and install realm library 

### Version

21

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

mac os 13.1 (Ventura)

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@vaghasiya-mayur By using `^11.3.1` you will install version 11.4.0 (currently the latest version) which is not compatible with RN 0.70.x.  Try to use `11.3.1` instead - or upgrade to RN 0.71.x.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please comment and reopen the issue if needed.
