### ISSUE TITLE
Downloading dependency: core 1.1.2

### ISSUE THREAD

**Issue by yangjiayu** [realm/realm-js#539]
when i create a new project. I follow: 
```
react-native init realmTest
npm install --save realm
rnpm link realm
```

there is an error.
`
Downloading dependency: core 1.1.2
Downloading core failed. Please try again once you have an Internet connection.
`
my network is ok, and my rnpm is 1.9.0 version.
I am running in ios.

**Comment by fealebenpae** [comment]
Hi @yangjiayu, the file that realm needs to download appears to have been flushed from the CDN we host it on - we're looking into it. Sorry for the trouble.

**Comment by fealebenpae** [comment]
Can you please try again?

**Comment by timzaak** [comment]
I have tried ,but it failed to download core 1.1.2.    and if I download the core 1.1.2 by chrome, it successed.

**Comment by yangjiayu** [comment]
it works.but there is another problem.
`
ld: library not found for -lRealmNode
`
and when i run in RealmNode target. it show:
![image](https://cloud.githubusercontent.com/assets/13096687/17124627/16f43182-531f-11e6-942a-7a235066d727.png).
Also,there is my linked frameworks.
![image](https://cloud.githubusercontent.com/assets/13096687/17124667/67ac7436-531f-11e6-8b20-a153a16827ee.png)

**Comment by fealebenpae** [comment]
@yangjiayu: can you please let me know how to reproduce this on a clean project step by step?

**Comment by charlesluo2014** [comment]
@yangjiayu you can download the file by wget or other download tools,and then 'cd' into the directory of realm,which is install into the node_modules, use text editor or vi to edit the download shell,'vi node_modules/realm/scripts/download-core.sh',and echo the file path $CORE_TAR,when you get the output ,and then cp the file you download from to it.

**Comment by xiaoleiooo** [comment]
Downloading dependency: core 1.1.2
Downloading core failed. Please try again once you have an Internet connection.
Command /bin/sh failed with exit code
