### ISSUE TITLE
expo-template-js installs incompatible version of realm

### ISSUE THREAD

**Issue by fkjohn** [realm/realm-js#5392]
### How frequently does the bug occur?

Always

### Description

When creating a reproducible repo for my bug report, I started by cloning expo-template-js. 
However, expo-template-js will install the latest version of Realm (v11.4.0) which is not compatible with the react native version (0.70.5) of the latest Expo SDK. Therefore the app will crash on startup and it is necessary to manually downgrade realm to the last compatible version.

### Can you reproduce the bug?

Always

### Reproduction Steps

Follow the steps stated in the documentation (https://www.mongodb.com/docs/realm/sdk/react-native/bootstrap-with-expo/)

### Version

11.4.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
Expo isn't supporting RN 0.71 yet (we are still waiting for https://github.com/expo/expo/pull/20799 to be released) but I will imagine that Expo 48 will support RN 0.71. We try to be current with RN.

I will recommend that you check the [compatibility matrix](https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md)

**Comment by fkjohn** [comment]
I understand that realm is tied to specific RN versions, but I can imagine that it is a quite frustrating experience if a person new to realm exactly follows the Tutorial available on https://www.mongodb.com/docs/realm/sdk/react-native/bootstrap-with-expo/ and in the end has an App which is unable to start. Furthermore, the error messages do not make it obvious that it is necessary to adjust the realm version. 

The current template requires exactly Expo 47, so even when Expo 48 is released it will not work without adjustment. I managed to get the template working, so maybe this ticket should rather be seen as an improvement idea.

**Comment by kneth** [comment]
@fkjohn We are aware of how annoying it is. For every RN release, we also have to go through the same pain of testing and releasing to keep current with React Native.

Many libraries are in the same situation as we are, and we are planning to tackle it sooner and later. We are studying the [out-of-npm artifacts](https://github.com/react-native-community/discussions-and-proposals/blob/master/proposals/0508-out-of-npm-artifacts.md) proposal to align better with how the React Native is envisioning it.

**Comment by bsluther** [comment]
I ran into this problem trying to use Realm for the first time and it took me quite a while to figure out that I needed to adjust my versions (as mentioned, the errors you get don't really indicate the source of the problem). Maybe it would be helpful to add a note to the template readme and the Realm docs advising newcomers to check the compatibility matrix and adjust versions accordingly?

**Comment by takameyer** [comment]
@fkjohn just tried this out, and `realm@11.5.0` was installed.  The version in the `package.json` is `^11.3.1`, which will end up installing the latest minor version.  

On the next release of the templates, we will need to change the `package.json` so that `realm` doesn't automatically upgrade to the latest minor version and is pinned to the latest compatible version.  

If anyone is hitting this issue, just remove the `^` for `realm` in the `package.json` and reinstall your node modules. 

I've [created an issue](https://github.com/realm/realm-js/issues/5458) to ensure this is completed on the next release.
