### ISSUE TITLE
SAME ISSUE WITH THIS FOR LINKED LIST

### ISSUE THREAD

**Issue by structlooper** [realm/realm-js#5395]
### Problem

I have tried the same.
const dataList = db.objects(State.schema.name); for 
I wanna filter this with districts link list to be null or empty

### How important is this improvement for you?

-- select --

### Feature would mainly be used with

-- select --

**Comment by kneth** [comment]
You can use [`SUBQUERY`](https://www.mongodb.com/docs/realm/realm-query-language/#subqueries) to do this.

**Comment by structlooper** [comment]
YEAH, Thanx it worked.
