### ISSUE TITLE
Cannot open Xcode after linking the Realm.

### ISSUE THREAD

**Issue by ShujunBian** [realm/realm-js#541]
My Xcode crashes after linking the Realm. So I created a new project to test whether Realm works with it but I got the same issue.

Here is what I did.

1 .`react-native init RealmTest`
2. `npm install --save realm`
3. `rnpm link realm`

Then I saw this:

```
rnpm-link info Linking realm android dependency
rnpm-link info Android module realm has been successfully linked
rnpm-link info Linking realm ios dependency
rnpm-link WARN ERRGROUP Group 'Frameworks' does not exist in your XCode project. We have created it automatically for you.
rnpm-link info iOS module realm has been successfully linked
```
Then after that, I cannot open the Xcode. It would crash all the time. Here is the screen capture.
<img width="1001" alt="screen shot 2016-07-27 at 1 30 12 pm" src="https://cloud.githubusercontent.com/assets/2719763/17185279/71642e9e-53fe-11e6-94cf-b2793b41b997.png">

Here is how my package.json looks like:
```
{
  "name": "RealmTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.2.1",
    "react-native": "^0.30.0",
    "realm": "^0.14.1"
  }
}
```

**Comment by joelwass** [comment]
what version of xcode?

**Comment by ShujunBian** [comment]
Version 7.3.1 (7D1014)

2016-08-01 13:49 GMT-04:00 Joel Wasserman <notifications@github.com>:

**Comment by alazier** [comment]
@ShujunBian what version of rnpm? Also did you try reinstalling XCode and did it resolve anything?

**Comment by ShujunBian** [comment]
rnpm version is 1.9.0. No, I haven't reinstalled XCode. I will do it right now and tell you the result about that.

**Comment by ShujunBian** [comment]
I have reinstalled the Xcode but it doesn't fix the issue.

**Comment by bdash** [comment]
The crash report says there's a code signing error when running Xcode, where part of an executable file or shared library it has loaded into memory was changed unexpectedly. This isn't something that Realm JS could have caused, but it's possible something else that you did around the same time  you started using Realm JS triggered the problem. Sometimes these errors are transient, and will go away after restarting your machine. Have you tried rebooting?

**Comment by ShujunBian** [comment]
@bdash Restarting really fixes my problem. Thanks so much!
