### ISSUE TITLE
Node Backend Not Building on Ubuntu 16.04

### ISSUE THREAD

**Issue by JamesChristie** [realm/realm-js#542]
I'm working in a codebase that's utilizing Node.js version `4.4.3`, and has a `prepublish` task set up to build the node backend for Realm that is then used in our test environment. The React Native application can build happily, but the node backend compilation fails.

The `prepublish` task we're running is: `cd ./node_modules/realm && ./scripts/download-core.sh node && ./src/node/build-node.sh`

The downloaded core binary appears to be a jolly Linux build, and everything seems sane there. I had assumed that the `isnan()` failure was caused by the somewhat common namespacing issue of not invoking `std::isnan()` instead of just `isnan()`, but changing that produces a reference error in the compiled .so file. I assume this is because it's intended to be from the utf-8 validation, the header of which all appear present including the `isnan.h` file.

I am currently totally stumped by this, so an indication of this being my own fault entirely or an actual issue would be lovely. Below is a link to a sanitized log of me running `npm install` when Realm is the only package not yet installed (names have been changed to protect the innocent and whatnot): https://gist.github.com/JamesChristie/ef7727260cbfdaca8c80ba06a21a7716

This failure can also be duplicated in a perfectly clean test project with the most minimal dependency set I could manage. Node is installed via NVM, the `build-essential` package is present, and all Node headers should be available.

**Goals**: I would like to build the node backend for Realm on Ubuntu 16.04,

**Expected Results**: Given the `prepublish` step above, I would like to utilize a built Node backend with bindings for Realm.

**Actual Results**: A compilation error or a reference error depending on how `isnan()` is resolved or not.

**Steps to Reproduce**: Add `realm` as a package in a Node project, and run the `prepublish` script above on an Ubuntu 16.04 system.

**Code Sample**: https://docs.google.com/uc?id=0Bw1KklqtXFT7Y0FnZ3k3bGxPRTg&export=download This is a super simple, minimal project that can produce the same error reported above.

**Version of Realm/etc**: Realm (0.14.1), Android Studio (2.1), Ubuntu 16.04 will all provided, supported updates installed

**Comment by bigfish24** [comment]
@JamesChristie thanks for reaching out and I apologize for the delay (we had some vacations on our end). Right now we are not officially supporting `realm-js` with Node, though, we intend to soon. Instead if you could email me at af@realm.io, I would love to learn more about your project and how we can support it going forward.

**Comment by JamesChristie** [comment]
@bigfish24 Previously, there was a pull to enabled the Node backend in Realm that got the test suite for the project running under Linux. It was my understanding that this was essentially supported after that, even if it might be a bit shaky. The core libs already download a Linux version when on a Linux OS. Am I misunderstanding the purpose of that commit?

Relevant link: https://github.com/realm/realm-js/pull/489
