### ISSUE TITLE
Realm Database size does not decrease after compacting

### ISSUE THREAD

**Issue by feiyuntao** [realm/realm-js#5422]
### How frequently does the bug occur?

Always

### Description

I have a Realm database in my React Native app and after adding a lot of data, the size of the database grew to 4.42GB. I then opened the database using a schema that includes only one table, but the size did not decrease, even after I compacted it and increase the schema version 

I expected that compacting the database would reduce its size, but this has not been the case. The size of the database remains large, which is causing performance issues in my app.

I would appreciate it if the Realm team could look into this issue and provide a solution to help reduce the size of my database. Thank you.

### Can you reproduce the bug?

Always

### Version

realm 10.20.0, react-native 0.66.4

### What services are you using?

-- select --

### Are you using encryption?

-- select --

### Platform OS and version(s)

Ios 16.2

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@feiyuntao 

You mention that you have compacted the database, but did you ensure that all Realm instances were closed? Moreover, you can take advantage of the `shouldCompactOnLaunch` configuration option to ensure that the database is compacted when the app is starting.

In version 11.3.0 we introduce automatic compaction. It doesn't compact as well as the manual compact method but it should help you avoiding a too rapid growth.

**Comment by kneth** [comment]
> all Realm instances were closed

`Realm.open()` and `new Realm()` will cache the underlying Realm so you can have multiple instances for the same configuration if you have called `Realm.open()` or `new Realm()` multiple times.

> I did use shouldCompactOnLaunch, but seems It does not work

If you want to compact unconditionally, you should use  something like `shouldCompactOnLaunch: () => true`? Out of curiousity, can you share how you configure `shouldCompactOnLaunch`?

**Comment by feiyuntao** [comment]
Hi Kenneth,

Thank you for your reply.   The following code is how I opened realm.

The point is when I checked totalBytes and usedBytes, they are the same big
size.  Even if I have only one table defined in the schema.   When I opened
the Realm Studio, I can still see all data in other tables that are not
included in current config.schema.

export const dbOpen = async (config: Realm.Configuration): Promise<Realm> =>
{
if (!config.deleteRealmIfMigrationNeeded && !config.migration) {
config.migration = () => {
// do nothing
};
}
if (!config.shouldCompactOnLaunch) {
config.shouldCompactOnLaunch = (totalBytes: number, usedBytes: number) => {
return totalBytes > 2 * usedBytes;
};
}
if (!config.schemaVersion) {
// currentVerison = -1 if realm db does not exist
const currentVersion = Realm.schemaVersion(config.path!);
config.schemaVersion = Math.max(currentVersion, 1);
}
let db: Realm;
try {
db = await Realm.open(config);
} catch (error: any) {
if (
error.message?.toLowerCase()?.includes('primary key') &&
error.message?.toLowerCase()?.includes('duplicate')
) {
config.migration = handleDuplicatePrimaryKeyMigration;
return dbOpen(config);
} else if (
error.message?.toLowerCase()?.includes('migration is required')
) {
config.schemaVersion += 1;
return dbOpen(config);
}
throw error;
}
console.debug(
`${config.path} with version ${config.schemaVersion} is opened`,
);
return db;
};

**Comment by kneth** [comment]
@feiyuntao 

If `shouldCompactOnLaunch` returns false, compact is not performed. It could be interesting to try two things:

1. Log `totalBytes` and `usedBytes` to see if the predicate is false
2. Use `shouldCompactOnLaunch = (totalBytes: number, usedBytes: number) => true` to force is unconditionally to compact

**Comment by feiyuntao** [comment]
Hi Kenneth,

I have tried to always return true, and it still doesn't work.   Also, when
I tried to log totalBytes and usedBytes, and they are almost the same.
And it couldn't be true, because I only passed one table in config.schema
for Realm to open.



Thanks

**Comment by kneth** [comment]
@feiyuntao If `totalBytes` and `usedBytes` are roughly equal, it is an indication that there is not free space for compaction to reclaim. 

>  includes only one table

If you only need one particular table, you should remove all objects from the other tables as part of your migration between different schema versions. And likely compact after the migration to ensure that all free space (deleted objects) is reclaimed.

**Comment by feiyuntao** [comment]
So does it mean if I didn't delete those tables, their space would be taken
all the time ?  Since I change the schema to only one table, I assume all
other tables' structure and data would be removed automatically?

**Comment by kneth** [comment]
> So does it mean if I didn't delete those tables, their space would be taken all the time 

Yes, it is by design. It is possible to open a Realm without a schema - or an incomplete schema. In particular opening without a schema can be very useful in some cases (Realm Studio is an example - the application is using Realm JavaScript). 

You could copy the table (`KeepTable`) to a new Realm file:

```js
const Realm = require("realm");

let oldRealm = new Realm({ path: "old-file.realm" }); // you don't have to specify the schema
let newRealm = new Realm({ path: "new-file.realm", schema: [KeepTable] });

let objs = oldRealm = realm.objects(KeepTable.name);
newRealm.write(() => objs.forEach(s => newRealm.create(KeepTable.name, s)));

newRealm.close();
oldRealm.close();
```

**Comment by feiyuntao** [comment]
Thank you so much for your reply, I understand now.   So if I really want
to drop some tables, I can only achieve that by copying to another
database file ?

**Comment by kneth** [comment]
@feiyuntao You can use [`deleteModel`](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#deleteModel) and compact it next time you open the Realm file.

**Comment by feiyuntao** [comment]
Cool, thanks!
