### ISSUE TITLE
V8 Support? 

### ISSUE THREAD

**Issue by allen-hsu** [realm/realm-js#5424]
### Problem

Hi , I see few years old, Some people have proposed about V8 support.
I know realm already support Hermes now, On a specific type of app, the overall performance of v8 is far better than that of hermes, whether it is startup speed or rendering, especially the Crypto app
do you have any plan to support v8 ?

### Solution

support v8

### Alternatives

support v8

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by kneth** [comment]
@allen-hsu 

We have support for V8 but it is to support node.js. You are asking about support of https://github.com/Kudo/react-native-v8, right? If that's the case, the quick answer is, no we don't have immediate plans to support it. 

We are in the middle of a major rewrite of the SDK (see https://github.com/realm/realm-js/discussions/5416 for more), and once it lands, the theory is that it will be easier (but not trivial) to add support for new engines. It could be interesting if our community would like to pick up V8 support.

I will leave the issue open, and ask everybody to express their interest by upvoting it. We are also interested in understanding the upsides of V8 is for React Native apps, so please leave a comment.
