### ISSUE TITLE
RealmProvider `fallback` property should include progress notifications

### ISSUE THREAD

**Issue by takameyer** [realm/realm-js#5459]
### Problem

Currently, there is no clear way to include display progress notifications when opening a synced Realm.

We already have complaints about this (see issue #5144).

### Solution

The best solution would be for the `fallback` component rendered by the `RealmProvider` to include properties for the progress notification and re-render when this changes.  This would allow more context into the `fallback` in order to determine that progress is being made in opening the `realm`.

```tsx
const RealmFallback = ({transferred, transferable}) => {...}
```

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Atlas Device Sync

**Comment by BubbleTrouble14** [comment]
Hi there. Any news on this topic ?
