### ISSUE TITLE
Realm for react-native stops onload.

### ISSUE THREAD

**Issue by aneuroo** [realm/realm-js#5474]
### How frequently does the bug occur?

Always

### Description

My App closes on load but if I remove (import Realm from "realm";) it works as normal here is my package.json 

{
  "name": "PrewornMarket",
  "version": "0.0.1",
  "private": false,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-regular-svg-icons": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-google-signin/google-signin": "^8.2.1",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@realm/common": "^0.1.4",
    "@realm/react": "^0.4.3",
    "bad-words": "^3.0.4",
    "cors": "^2.8.5",
    "events": "^3.3.0",
    "express": "^4.18.2",
    "firebase": "^9.13.0",
    "mongodb": "^5.0.1",
    "mongoose": "^6.9.2",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-fbsdk": "^3.0.0",
    "react-native-fontawesome": "^7.0.0",
    "react-native-get-random-values": "^1.8.0",
    "react-native-image-picker": "^4.10.1",
    "react-native-keychain": "^8.1.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^11.25.0",
    "realm": "^11.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

### Stacktrace & log output

```shell
Log doesn't load.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Just build that app with  import Realm from "realm" anywhere on the project 

### Version

11.5.0

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Android 

### Build environment

Which debugger for React Native:

### Cocoapods version

Just Android

**Comment by takameyer** [comment]
@aneuroo At the moment `realm` is very version dependent to `react-native`.  See our [compatibility matrix](https://github.com/realm/realm-js/blob/master/COMPATIBILITY.md).  
To solve you issue, pin realm to `11.3.1`

**Comment by aneuroo** [comment]
Ill let you know tomorrow and edit this comment to thanks if this works.
