### ISSUE TITLE
Cannot compare `realm.syncSession?.connectionState === Realm.ConnectionState[enumValue]`

### ISSUE THREAD

**Issue by mongodben** [realm/realm-js#5480]
### How frequently does the bug occur?
Always

### Description
when checking the value of Realm.syncSession.connectionState enum using an equality operator, such as:

```ts
// throws error :( 
realm.syncSession?.connectionState === Realm.ConnectionState.Connected
```

this code throws the following error:

```txt
    TypeError: Cannot read properties of undefined (reading 'Connected')
```

However, if I use the value of the enum (which i found by looking at the source code), things work as expected. For example:

```ts
// runs fine :)
realm.syncSession?.connectionState === 'connected'
```

I believe this might be related to some funky TS enum behavior, as talked about here https://stackoverflow.com/questions/50365598/typescript-runtime-error-cannot-read-property-of-undefined-enum (perhaps it's [this issue](https://github.com/microsoft/TypeScript/issues/3200)?)

- - -
Additionally, in the [API reference for this method](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.App.Sync.Session.html#connectionstate), it describes the enum as accessible from `Realm.App.Sync.ConnectionState`, however in the SDK the enum is accessed through `Realm.ConnectionState`.

Also, the reference docs describe `connectionState` as a method, but in the SDK it is a property.

Also the [docs for discussing `realm.syncSession?.connectionState`](https://www.mongodb.com/docs/realm/sdk/node/examples/sync-changes-between-devices/#check-the-network-connection) are pretty wrong (but I guess that's my problem to fix )

### Can you reproduce the bug?
Always

### Version
realm@11.4.0 with @realm/react@0.4.1

### What services are you using?
Atlas Device Sync

### Are you using encryption?
No

### Platform OS and version(s)
macOS 12.6.3

### Build environment
Which debugger for React Native:

using React Native Testing Library, which i believe runs in a Node.js process.

**Comment by kraenhansen** [comment]
In the current latest version of the SDK, this enum is exported on `Realm.App.Sync.ConnectionState` as per https://github.com/realm/realm-js/blob/master/lib/extensions.js#L506-L510

**Comment by mongodben** [comment]
thank you for the speedy feedback @kraenhansen!

**Comment by mongodben** [comment]
hi kraen, i've upgraded realm to 11.5.0, and the same issue persists. no change in behavior.

**Comment by kraenhansen** [comment]
> the same issue persists

Are you still using `Realm.ConnectionState.Connected` or did you update to use `Realm.App.Sync.ConnectionState.Connected`?

**Comment by krollins-mdb** [comment]
@kraenhansen, I'm seeing the same behavior with the `Realm.OpenRealmBehaviorType` enums.

Using this behavior config object:
``` ts
const realmAccessBehavior: Realm.OpenRealmBehaviorConfiguration = {
  type: Realm.OpenRealmBehaviorType.OpenImmediately,
};
```

Results in a TypeError:
```
TypeError: Cannot read properties of undefined (reading 'OpenImmediately')
```

But providing the value of the enum compiles just fine:
``` js
const realmAccessBehavior: Realm.OpenRealmBehaviorConfiguration = {
  type: 'openImmediately',
};
```

**Comment by kraenhansen** [comment]
Thanks for highlighting this 👍 It seems we never provided an implementation for that, which is ... very unfortunate. I'll make a quick PR for that.
