### ISSUE TITLE
react-native 0.31-rc

### ISSUE THREAD

**Issue by charlesluo2014** [realm/realm-js#551]
Use of undeclared identifier 'class_getInstanceVariable'

**Comment by alazier** [comment]
It looks like we have a few small issues with this rc, but they are easy to work around. If you do the following you should be ok until we get a proper fix out:
- Clean the build in XCode
- Add ```#import "RCTJavaScriptExecutor.h"``` and ```#import <objc/runtime.h>
``` in `RealmReact.mm`

**Comment by FearMediocrity** [comment]
This did the trick for me on RN 0.31.0

**Comment by alazier** [comment]
@mschipperheyn I'm working on a pr for this right now. What versions of realm and react-native are you using?

**Comment by mschipperheyn** [comment]
I'm using 0.14.1 and RN0.31. I'm trying 0.14.2-rc as we speak

**Comment by mschipperheyn** [comment]
If you need any testing of tmp versions, let me know

**Comment by alazier** [comment]
We released 0.14.2 a few days ago. I think/hope that along with the header additions should fix the issue you are seeing.

**Comment by mschipperheyn** [comment]
0.14.2-rc with the addition of the above mentioned includes for ReactRealm.mm

	Aug  7 12:30:00 Marcs-MBP Ology[37252]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTJavaScriptContext ctx]: unrecognized selector sent to instance 0x7ffba5b06cb0'
		*** First throw call stack:
		(
			0   CoreFoundation                      0x0000000107f21e65 __exceptionPreprocess + 165
			1   libobjc.A.dylib                     0x0000000107122deb objc_exception_throw + 48
			2   CoreFoundation                      0x0000000107f2a48d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
			3   CoreFoundation                      0x0000000107e7790a ___forwarding___ + 970
			4   CoreFoundation                      0x0000000107e774b8 _CF_forwarding_prep_0 + 120
			5   Ology                               0x000000010610f478 RealmReactGetJSGlobalContextForExecutor + 1112
			6   Ology                               0x0000000106111e50 __24-[RealmReact setBridge:]_block_invoke + 496
			7   Ology                               0x0000000105ffa19d -[RCTJSCExecutor executeBlockOnJavaScriptQueue:] + 301
			8   Foundation                          0x0000000106d0b067 __NSThreadPerformPerform + 283
			9   CoreFoundation                      0x0000000107e4da31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
			10  CoreFoundation                      0x0000000107e4395c __CFRunLoopDoSources0 + 556
			11  CoreFoundation                      0x0000000107e42e13 __CFRunLoopRun + 867
			12  CoreFoundation                      0x0000000107e42828 CFRunLoopRunSpecific + 488
			13  Ology                               0x0000000105ff11e8 +[RCTJSCExecutor runRunLoopThread] + 472
			14  Foundation                          0x0000000106dacdfb __NSThread__start__ + 1198
			15  libsystem_pthread.dylib             0x000000010b1b499d _pthread_body + 131
			16  libsystem_pthread.dylib             0x000000010b1b491a _pthread_body + 0
			17  libsystem_pthread.dylib             0x000000010b1b2351 thread_start + 13
		)
	Aug  7 12:30:00 Marcs-MBP SpringBoard[19495]: BSXPCMessage received error for message: Connection invalid
	Aug  7 12:30:00 Marcs-MBP SpringBoard[19495]: HW kbd: Failed to set (null) as keyboard focus
	Aug  7 12:30:00 Marcs-MBP com.apple.CoreSimulator.SimDevice.147CEF63-B3B3-4997-9C63-C32BE768B3EE.launchd_sim[19478] (UIKitApplication:org.reactjs.native.example.Ology[0x7bbe][37252]): Service exited due to signal: Abort trap: 6

**Comment by alazier** [comment]
I'm able to reproduce this pretty easily. Will let you know when we have a fix ready.

**Comment by mschipperheyn** [comment]
Ok, let's see with a full clean plus Simulator reset....and.....hmm, ReactRealm.mm reverted. Ok, try again, and.....

sorry, no joy.

	Aug  7 12:35:48 Marcs-MacBook-Pro Ology[40065]: -[RCTJavaScriptContext ctx]: unrecognized selector sent to instance 0x7fd3e3c08380
	Aug  7 12:35:48 Marcs-MacBook-Pro Ology[40065]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTJavaScriptContext ctx]: unrecognized selector sent to instance 0x7fd3e3c08380'
		*** First throw call stack:
		(
			0   CoreFoundation                      0x000000010ed80e65 __exceptionPreprocess + 165
			1   libobjc.A.dylib                     0x000000010df81deb objc_exception_throw + 48
			2   CoreFoundation                      0x000000010ed8948d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
			3   CoreFoundation                      0x000000010ecd690a ___forwarding___ + 970
			4   CoreFoundation                      0x000000010ecd64b8 _CF_forwarding_prep_0 + 120
			5   Ology                               0x000000010cf6e478 RealmReactGetJSGlobalContextForExecutor + 1112
			6   Ology                               0x000000010cf70e50 __24-[RealmReact setBridge:]_block_invoke + 496
			7   Ology                               0x000000010ce5919d -[RCTJSCExecutor executeBlockOnJavaScriptQueue:] + 301
			8   Foundation                          0x000000010db6a067 __NSThreadPerformPerform + 283
			9   CoreFoundation                      0x000000010ecaca31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
			10  CoreFoundation                      0x000000010eca295c __CFRunLoopDoSources0 + 556
			11  CoreFoundation                      0x000000010eca1e13 __CFRunLoopRun + 867
			12  CoreFoundation                      0x000000010eca1828 CFRunLoopRunSpecific + 488
			13  Ology                               0x000000010ce501e8 +[RCTJSCExecutor runRunLoopThread] + 472
			14  Foundation                          0x000000010dc0bdfb __NSThread__start__ + 1198
			15  libsystem_pthread.dylib             0x000000011201399d _pthread_body + 131
			16  libsystem_pthread.dylib             0x000000011201391a _pthread_body + 0
			17  libsystem_pthread.dylib             0x0000000112011351 thread_start + 13
		)
	Aug  7 12:35:48 Marcs-MacBook-Pro SpringBoard[37580]: HW kbd: Failed to set (null) as keyboard focus
	Aug  7 12:35:48 Marcs-MacBook-Pro SpringBoard[37580]: BSXPCMessage received error for message: Connection invalid
	Aug  7 12:35:48 Marcs-MacBook-Pro assertiond[37584]: assertion failed: 15E56a 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1
	Aug  7 12:35:48 Marcs-MacBook-Pro com.apple.CoreSimulator.SimDevice.147CEF63-B3B3-4997-9C63-C32BE768B3EE.launchd_sim[37563] (UIKitApplication:org.reactjs.native.example.Ology[0x9191][40065]): Service exited due to signal: Abort trap: 6

**Comment by mschipperheyn** [comment]
Ok, great. Looking forward to it!

**Comment by rclai** [comment]
Me too, I'm having the same issue. What is the latest RN version that still works for Realm right now?

**Comment by alazier** [comment]
I didn't see these issues with V0.30.0

**Comment by charlesluo2014** [comment]
@alazier 
I use V0.31.0,it sims that the bridge method arguments dismatch

2016-08-08 23:06:26.069 TestRealm[19062:1069950] -[RCTJavaScriptContext ctx]: unrecognized selector sent to instance 0x7ff79090eeb0
2016-08-08 23:06:26.082 TestRealm[19062:1069950] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTJavaScriptContext ctx]: unrecognized selector sent to instance 0x7ff79090eeb0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109e1ed85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109013deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109e27d3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000109d6dcfa ___forwarding___ + 970
	4   CoreFoundation                      0x0000000109d6d8a8 _CF_forwarding_prep_0 + 120
	5   TestRealm                           0x000000010805d32c RealmReactGetJSGlobalContextForExecutor + 1100
	6   TestRealm                           0x000000010805fbf4 __24-[RealmReact setBridge:]_block_invoke + 484
	7   TestRealm                           0x0000000107f8880d -[RCTJSCExecutor executeBlockOnJavaScriptQueue:] + 301
	8   Foundation                          0x0000000108bf97a7 __NSThreadPerformPerform + 283
	9   CoreFoundation                      0x0000000109d44301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x0000000109d3a22c __CFRunLoopDoSources0 + 556
	11  CoreFoundation                      0x0000000109d396e3 __CFRunLoopRun + 867
	12  CoreFoundation                      0x0000000109d390f8 CFRunLoopRunSpecific + 488
	13  TestRealm                           0x0000000107f7fae8 +[RCTJSCExecutor runRunLoopThread] + 472
	14  Foundation                          0x0000000108c9c12b __NSThread__start__ + 1198
	15  libsystem_pthread.dylib             0x000000010d60999d _pthread_body + 131
	16  libsystem_pthread.dylib             0x000000010d60991a _pthread_body + 0
	17  libsystem_pthread.dylib             0x000000010d607351 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by alazier** [comment]
I just pushed an new version for realm `0.14.3-rc` which resolves this issue in my tests. Please let me know how it goes!

**Comment by alazier** [comment]
@mschipperheyn `0.14.3-rc` should hopefully fix this issue. Let me know if/when you get a chance to try it out.

**Comment by rclai** [comment]
Okay RN 0.31.0 works with Realm 0.14.3. Thanks.

**Comment by alazier** [comment]
Glad we got this resolved.

**Comment by mschipperheyn** [comment]
Works. thx.
