### ISSUE TITLE
Notifications/Synchronization between react-native and android bindings

### ISSUE THREAD

**Issue by ai277014717** [realm/realm-js#553]
Android project insert A Object every minutes.
react-native run realm.addListener() but when android insert A, the listener not work.
if I want to get the A Object currnet count,I must run realm.write().
It's is very worse.
What should I do

**Comment by alazier** [comment]
Can you provide a code snippet which reproduces this issue?

**Comment by alazier** [comment]
Were you able to figure this out? If not can you give more detailed steps to reproduce? Thanks.

**Comment by ai277014717** [comment]
There is a full project.
https://github.com/ai277014717/react-native-baidumap/tree/bugs/FLS
android code save one location in a time
react-native code show the android saved locations
only add 
this.realm.write(() => {

            });
the react-native code could show right data

**Comment by alazier** [comment]
Were you able to figure this out? If I am understanding correctly, you are using both the realm android binding and the react native binding at the same time? If that is the case then this is a known issue but the android team is working on a fix.

**Comment by ai277014717** [comment]
Now I update the project.
https://github.com/ai277014717/react-native-baidumap/tree/bugs/FLS
![2016-09-27 10 17 52](https://cloud.githubusercontent.com/assets/7580754/18858045/af849722-849b-11e6-8226-b8746f1de791.png)
see this picture if I don't click item3 the number of LLLocation will not update.
I have already update android realm to 1.2.0.
If you want run this project.
you may be run 
#npm install
#npm install react-native-button
#npm install react-native-tabbar
#npm start
and use android studio open the android project run in simulation.
please open gps and wifi to make app work

**Comment by alazier** [comment]
From looking at your code it seems you are trying to use both the react-native and android bindings concurrently. While this may work notifications between the two bindings does not currently work. It isn't clear when we will have a fix for this.
