### ISSUE TITLE
Expo Web support

### ISSUE THREAD

**Issue by riebel** [realm/realm-js#5532]
### Problem
I know the web context of Expo is not officially supported, but since Hermes is now supported and the default engine in Expo SDK 48 also switched to Hermes, maybe it is now somehow possible?

I get it running on Expo48 Android dev client, but when i try to bundle for web, I get:

```
The package at "node_modules\bindings\bindings.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.
```

Maybe there is a workaround or fix for this or is it just plain impossible at the moment?

### How important is this improvement for you?
Dealbreaker

### Feature would mainly be used with
Atlas Device Sync

**Comment by kneth** [comment]
@riebel Thank you for reporting. It is not something we have tried out. You might be able to find a work-around by tweaking your Babel configuration: https://github.com/goatandsheep/react-native-dotenv/issues/78

**Comment by riebel** [comment]
I tried to modify my `babel.config.js` with no success:

```
module.exports = function (api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo', 'module:metro-react-native-babel-preset'],
    plugins: [
      '@babel/plugin-proposal-export-namespace-from',
      'react-native-reanimated/plugin',
      require.resolve('expo-router/babel')
    ]
  }
}
```

**Comment by kneth** [comment]
It is not on our current roadmap to support Expo Web but in general web is an interesting platform. I am curious to learn more about your use case? Do you want to share an app between mobile and web? Are you interested in developing your mobile app as a PWA?

**Comment by riebel** [comment]
Yes, I share the whole codebase with android, iOs and web and the same app runs flawlessly on all three platforms. I plan to switch from firebase to a self-hosted solution, but I think it is impractical for my project to use different APIs for web and for mobile. It would require a lot of duplicated code and/or a weird wrapper API.

**Comment by federicogomezlara** [comment]
@riebel Did you find any work around?

**Comment by riebel** [comment]
@federicogomezlara sadly not.

**Comment by aronkramer** [comment]
I'm having the same issue.

**Comment by farynaio** [comment]
same

**Comment by Arthurmtro** [comment]
+1

**Comment by bishoyroufael** [comment]
Any updates regarding this?

**Comment by kraenhansen** [comment]
@bishoyroufael I did manage make some advancements on this:  https://github.com/realm/realm-js/pull/6821 but that PR is nowhere near ready to merge.

With the [deprecation announcement](https://github.com/realm/realm-js/blob/main/DEPRECATION.md) this is left as work for the community to do and we haven't (yet) seen a huge interest in members of the community contributing large features. So ... likely not going to happen 😞 I'll close it as such and we can re-open if that change 👍
