### ISSUE TITLE
`npm install realm` broken? keeps hanging up at `reify:realm: timing...` (see screenshot)

### ISSUE THREAD

**Issue by GitMurf** [realm/realm-js#5547]
### How frequently does the bug occur?

Always

### Description

I am having trouble doing an npm install of current version as well as tried plenty of older versions as well. They all hang up at the screenshot below:

![image](https://user-images.githubusercontent.com/64155612/223328592-017c6bb0-9cb6-429e-855d-d2d37ff4d3c5.png)

### Can you reproduce the bug?

Always

### Reproduction Steps

`npm install realm`

### Version

Latest and 10.22

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11

### Build environment

Which debugger for React Native: ..

**Comment by GitMurf** [comment]
I don't know if this is it or not but when I kill the install it gives the following and appears it may be erroring out at `node scripts/submit-analytics.js`?

![image](https://user-images.githubusercontent.com/64155612/223329823-35773e3b-d4bb-46da-98c8-78a254870879.png)

**Comment by kneth** [comment]
@GitMurf I am not sure if we will get any useful information but can you try to run `npm install -d verbose realm`?

Which version of node do you use? We have an unresolved [issue with node 19](https://github.com/realm/realm-js/issues/5136).

**Comment by GitMurf** [comment]
> @GitMurf I am not sure if we will get any useful information but can you try to run `npm install -d verbose realm`?
> 
> Which version of node do you use? We have an unresolved [issue with node 19](https://github.com/realm/realm-js/issues/5136).

I am indeed using the "Current Version" v19.7 of node along with current version of NPM v9.6. Are there any solutions at this point other than downgrading to v18.xx?

**Comment by GitMurf** [comment]
> @GitMurf I am not sure if we will get any useful information but can you try to run `npm install -d verbose realm`?

Here is the end of the verbose results. Again the only thing I can get out of it is that something seems to be hanging with the "submit-analytics.js" step?

![image](https://user-images.githubusercontent.com/64155612/223494332-4ebf0b28-d2ff-4cbe-b794-094dc28371fb.png)

**Comment by kneth** [comment]
I have a fix in https://github.com/realm/realm-js/pull/5554

**Comment by pachewise** [comment]
@kneth thanks for fixing this issue. Do y'all have a release planned soon for this, or will we have to build from source / use node@18 to be able to install realm?

**Comment by kneth** [comment]
The plan is to get a release out this week

**Comment by kneth** [comment]
Released in v11.5.2

**Comment by 2sem** [comment]
I can't install 11.0.0-rc.1
my project is using react-native 0.69, so I should use 11.0.0-rc.1

<img width="608" alt="스크린샷 2023-03-24 오후 8 03 41" src="https://user-images.githubusercontent.com/16129260/227528620-96649c78-a16b-46e5-9d93-6dfbbe165046.png">

hang on reify:realm: info run realm@11.0.0-rc.1 postinstall node_modules/realm node scripts/submit-analytics.j


```
npm http fetch GET 200 https://registry.npmjs.org/realm/-/realm-11.0.0-rc.1.tgz 26700ms (cache miss)
npm info run realm@11.0.0-rc.1 install node_modules/realm prebuild-install --tag-prefix= -r napi || cmake-js build
npm info run realm@11.0.0-rc.1 install { code: 0, signal: null }
npm info run realm@11.0.0-rc.1 postinstall node_modules/realm node scripts/submit-analytics.js
(##################) ⠼ reify:realm: info run realm@11.0.0-rc.1 postinstall node_modules/realm node scripts/submit-analytics.j
```

**Comment by kneth** [comment]
If you are using node 19, please upgrade to Realm JS v11.5.2 or downgrade to node 18.
