### ISSUE TITLE
rnpm link realm fails on windows

### ISSUE THREAD

**Issue by hhashmi** [realm/realm-js#555]
I'm a newbie and trying react-native realm on windows 10
rnpm link realm fails on windows. 
I have searched for it and came to know it is because iOS setup not found on windows.

It there any other way to get it done?

just tried it again and following is the ouput

> rnpm-link info Android module realm is already linked
> rnpm-link info iOS module realm is already linked
> rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
> Please file an issue here: https://github.com/rnpm/rnpm/issues

**Comment by hhashmi** [comment]
I tried following in my MainActivity.java

> import io.realm.react.RealmReactPackage; // ADD THIS
> ...
>   @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>           new RealmReactPackage() // AND THIS
>       );
>     }

on execution getting following error

**Comment by fealebenpae** [comment]
Hey @hhashmi, sorry for taking so long to respond, but we've been flooded with a bunch of stuff.

I'm not a Windows user myself, so I tried to set up a VM and install React Native but I failed spectacularly.

Do you still experience this with latest React Native and rnpm? I'll try to set up a Windows environment again, but I might not get the chance to do it this week.

**Comment by hhashmi** [comment]
rnpm on windows.. yes it is still failing.

What I did to get going, I configured it manually on windows and it is working fine.
The initial problem rnpm, still no luck

**Comment by abeikverdi** [comment]
Same error! Cant fix it either...

**Comment by j-Kode** [comment]
Hey guys I am on a windows environment and I am trying to get Realm to work. I am also getting this error and nothing seems to be working. Was anyone able to solve this issue?

**Comment by fealebenpae** [comment]
With the latest `react-native-cli@1.0.0` you need to run `react-native link realm` instead of `rnpm`. We will update the docs to reflect this.

**Comment by 2rajpx** [comment]
I run `react-native link realm` but I get same error!
Heeeelp!!!

**Comment by andrewvmail** [comment]
+1

**Comment by daninaga** [comment]
i'm having the same problem, can anyone explain how to manual link?

**Comment by kristiandupont** [comment]
Tracking this in #633
