### ISSUE TITLE
Build error for React Native 0.32

### ISSUE THREAD

**Issue by maxdjohnson** [realm/realm-js#560]
Realm-js 0.14.1 has build errors with React Native 0.32 due to changes in `RCTBridge.h` and the `RCTJavaScriptContext` class.

I was able to hackily fix it by adding missing imports (`RCTJavaScriptExecutor.h` and `objc/runtime.h`) and I had to change `[rctJSContext ctx]` to `[rctJSContext context].JSGlobalContextRef`

I would make a PR but my interim solution won't work for other RN versions :(

**Comment by alazier** [comment]
We recently released v0.14.3 which should resolve this issue.

**Comment by alazier** [comment]
If you are still having issues with the latest version please let us know!

**Comment by maxdjohnson** [comment]
Whoops didn't see the new release in /releases - works for me thanks!
