### ISSUE TITLE
Anyway to use createRealmContext and old fashion operation at once in react native?

### ISSUE THREAD

**Issue by somasekharkakarla** [realm/realm-js#5624]
Hi,

i want to know whether realm-react's RealmContext can return realm like

const realm = await Realm.open({
path: "realm-files/myrealm",
schema: [TaskSchema],
});

like const realm.

So that i can use in class. i want to use the realm in dataManager, where i do business logic there and save in regular fashion like
realm.write(() => {
task1 = realm.create("Task", {
_id: 1,
name: "go grocery shopping",
status: "Open",
});

doing all logic in function component making file bigger.

so that i can use useQuery for fetching and listening the data , useRealm for small changes  as hooks in function component.

**Comment by takameyer** [comment]
@somasekharkakarla You could use the `realmRef` attribute of the `RealmProvider` to get a reference of the current `realm`.  With that, you could store the reference as a member in a class in order to perform operations.
Reference: https://github.com/realm/realm-js/tree/main/packages/realm-react#realmprovider

**Comment by takameyer** [comment]
Actually I have a better idea than using the `realmRef`. There is nothing wrong with sharing the `RealmConfiguration` that you passed into `createRealmContext` with your `RealmManager` and opening a `new Realm()` there.  Then you could add the config as an argument to the constructor and do `new RealmManager(config)`, which would also open and set the `private realm`.

Just keep in mind, that as soon as the `RealmProvider` is unmounted, it will call `realm.close()` which will close the realm encapsulated by the `RealmManager`.   I doubt this will be a problem though.

**Comment by somasekharkakarla** [comment]
yeah, i actually done that. i am getting Exception in HostFunction: Cannot access realm that has been closed.

**Comment by takameyer** [comment]
Can you perhaps make an example repo to reproduce this?  At what point in your code are you getting this error?  Is it possible you are trying to access the realm before you have opened it in `RealmManager`?

**Comment by somasekharkakarla** [comment]
Hi @takameyer, Thank you very much for help. i don't what happened it is working fine now.  I am not accessing the before i open realmManager. After invalidating caches, restart the system and a fresh install. All are working as expected.

**Comment by somasekharkakarla** [comment]
hi @takameyer ,
i have one more doubt. useQuery can listen even changes for a string. for example.

Here is my data

[
  {
    "name": "test 1",
    "prop": {
      "uid": "asasdfa",
      "name": "test_prop"
    }
  },
  {
    "name": "test 2",
    "prop": {
      "uid": "asasdfa",
      "name": "test_prop",
      "des":"asdfasdfa"
    }
  }
]

prop here may add more. so creating schema for those keys is not possible. i don't know is there any other way. i want to store it has string. i will get that string parse it, use it and convert to string and save it back to db. i want to know whether useQuery can listen to that change in string. If there is any other way please let me know.

**Comment by takameyer** [comment]
It is not currently possible to dynamically create properties on your schema.  The [dictionary](https://www.mongodb.com/docs/realm/sdk/react-native/realm-database/schemas/dictionaries/) might be more suited for this.

**Comment by somasekharkakarla** [comment]
Ho okay,

here is  an asset object
```
{
    name: 'Asset',
    primaryKey: 'uid',
    properties: {
      uid: "string?",
      name: "string?",
      description: "string?",
      properties:"{}?",
      lool:"Location?",

    }
  }
```
  
  and here is an location object
```
{
    name: 'Location',
    embedded: true,
    properties:{
      type: "string?",
      coordinates: "double?<>",
    }
  }
```


Normally by using useRealm() i able to update or add values to the asset object by calling

```
realm.write(()=>{
              item.name = "test change"
          })
```

How to update an value of lool (embedded object). if i create inside write function 

```
realm.write(()=>{
             let location = realm.create('Location',{type:'adfdad'}, Realm.UpdateMode.Modified)
              item.lool = location
          })
```

Error: Exception in HostFunction: Embedded objects cannot be created directly., js engine: hermes

can you please give me an example who to update using useRealm()?

**Comment by somasekharkakarla** [comment]
Hi @takameyer, i figured it out 
   realm.write( () => {
              item.lool ={"type":"clicked"}
          }) 


Thank you very much for your support and fast reply's. This really helpful and your youtube videos too. One request from my side is from now use both simple and complex objects in your videos.

And one last doubt why dictionary is not accepting depths? like

{
item1:"asdfd",
item2:"wertwer",
item3:{subItem1:"asdfasdf", subItem2:"73456"}
}

**Comment by takameyer** [comment]
@somasekharkakarla Happy you figured it out and that you found the videos helpful! Hopefully more to come!

We don't have support for it yet, but the core team has it on their roadmap to support nested mixed dictionaries, which would allow storing arbitrary JSON in a property.  I wish we had it now, be we have to be patient.  It will be a great addition to the JS SDK!

I'm closing this issue now.  Good luck with your project and feel free to open a new issue if you find something that doesn't work.
