### ISSUE TITLE
Failed to create directory at '/var/task/mongodb-realm/': Read-only file system

### ISSUE THREAD

**Issue by thucnguyenpfs** [realm/realm-js#5631]
### How frequently does the bug occur?

Sometimes

### Description

Hello, Im a newbie. Im writing some function in Atlas App services and only want to use it on my microservice app (just get data without modify) built on NodeJS and deploy on AWS.

Here is my code
```
let creditAvailables, cogintoToken;
  try {
    const appLogged = await app.logIn(
      Realm.Credentials.apiKey(process.env.REALM_API_KEY)
    );

    const creditAvailablePromise = await appLogged.functions.getCreditAvailableByBrand({
        brandShopCode: partnerCode,
      });
   } catch (err) {
    console.error('Failed to log in', err);
  }
```
I have realm version 11.5.2
Everything works well on local but I got randomly error in production with ```"errorMessage": "Failed to create directory at '/var/task/mongodb-realm/': Read-only file system"```

Do you have any idea? Am I missing some config?

### Stacktrace & log output

```shell
"errorType": "RealmError",
    "errorMessage": "Failed to create directory at '/var/task/mongodb-realm/': Read-only file system",
    "code": "PermissionDenied",
    "name": "RealmError",
    "stack": [
        "RealmError: Failed to create directory at '/var/task/mongodb-realm/': Read-only file system",
        "    at /var/task/src/handler.js:1:1555",
        "    at Generator.next (<anonymous>)",
        "    at /var/task/src/handler.js:1:1234",
        "    at new Promise (<anonymous>)",
        "    at o (/var/task/src/handler.js:1:979)",
        "    at Runtime.t.creditLoyalty [as handler] (/var/task/src/handler.js:1:1464)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
```

### Can you reproduce the bug?

Sometimes

### Version

11.5.2

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Nodejs

### Build environment

AWS

**Comment by kneth** [comment]
In version 11.6.0 we added `Realm.App.Configuration.baseFilePath` so you can specify where `mongodb-realm` is created. I am curious to learn if it can solve your issue.

**Comment by thucnguyenpfs** [comment]
I'm sorry for my late reply. I changed my code with your advice and waited a while to make sure everything was ok.

`new Realm.App({ id: process.env.REALM_APP_ID, baseFilePath: '/tmp'})`

Finally it works like a charm.
