### ISSUE TITLE
Simple misspelling, `cannoy` instead of `cannot`

### ISSUE THREAD

**Issue by joshwhatk** [realm/realm-js#564]
I ran into it in React Native.

Not sure where it would be in the code to submit a pull request, but here is an image of it occurring:

![cannoy be nullable](https://d.pr/i/Unb6+)

**Comment by fealebenpae** [comment]
Hey @joshwhatk, thanks for reporting this. The typo is in https://github.com/realm/realm-js/blob/v0.14.3/src/object-store/src/object_store.cpp#L575, but the code's already been rewritten in master so the typo is no longer there.
