### ISSUE TITLE
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.

### ISSUE THREAD

**Issue by aliza-khu** [realm/realm-js#5646]
### How frequently does the bug occur?

Always

### Description

I am expecting that after the upgrade react-native version to 0.71.4, the release build should succeed without any failure. But actually, the build is getting failed with the below error:

**package="io.realm.react" found in source AndroidManifest.xml: /home/circleci/react-native/node_modules/realm/react-native/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.**

### Stacktrace & log output

```shell
package="io.realm.react" found in source AndroidManifest.xml: /home/circleci/react-native/node_modules/realm/react-native/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Try to create the release build APK with react-native 0.71.4.

### Version

11.4.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android OS - API Level 33

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@aliza-khu Thank you for reporting. As you can reproduce it, can you provide a small app as an example?

**Comment by aliza-khu** [comment]
@kneth, Actually when I deep debug I found that the release build failure happening was not due to the issue I mentioned. It was a different one but yes I am still seeing the above issue's content on the release build logs. I believe this is due to react native version 0.71.4 changes in which the AndroidManifest will no more mention the package name instead of that in the file android/app/build.gradle need to mention the namespace which should be the same as applicationID. By doing so the warning will get disappears from the release build log. Currently, I am ignoring it because I am not able to change the library's internal code. But I suggest you make this be resolved to avoid a further large incident.

Thank You 🙂

**Comment by takameyer** [comment]
@aliza-khu I was able to see this as well and created a fix.  Thanks for creating the issue!
