### ISSUE TITLE
Always crashed after installing the realm package

### ISSUE THREAD

**Issue by devethan** [realm/realm-js#5685]
### How frequently does the bug occur?

Always

### Description

I have installed Realm according to the official document. After installing the Realm package it always crashes.

Below is the result of `react-native info`

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 48.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/c4/qvbz4hhn47ng986xsygvvxqh0000gn/T/yarn--1680511747973-0.33486784275012593/node
    Yarn: 1.22.19 - /var/folders/c4/qvbz4hhn47ng986xsygvvxqh0000gn/T/yarn--1680511747973-0.33486784275012593/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Stacktrace & log output

```shell
There's no stacktrace OR log.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

```bash
yarn add realm @realm/react

npx pod-install ios

yarn start --reset-cash

yarn ios
```

### Version

- realm: 11.7.0
- @realm/react: 0.4.3

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 13.2.1 / iOS 16.1

### Build environment

Which debugger for React Native: ..

### Cocoapods version

1.12.0

**Comment by takameyer** [comment]
The current release of `realm` is only compatible with React Native `0.71.x`.  You will have to either upgrade React Native, or downgrade `realm`.  Our [compatibility matrix](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md) show's what is compatible with what version.

**Comment by devethan** [comment]
@takameyer Thanks! I solved with [this compatible matrix](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md)
