### ISSUE TITLE
Cannot read property 'Upload' of undefined

### ISSUE THREAD

**Issue by devsales** [realm/realm-js#5687]
### How frequently does the bug occur?

Always

### Description

For some reason I cannot use the enums `Realm.ProgressDirection.Upload` and `Realm.ProgressMode.ReportIndefinitely` with TypeScript. I get the error as shown on the screenshot below. The same goes for `OpenRealmBehaviorType.DownloadBeforeOpen` and `OpenRealmTimeOutBehavior.OpenLocalRealm`.

Do I need to install some @type NPM dependency?

<img width="338" alt="image" src="https://user-images.githubusercontent.com/47062834/229556625-1fff5a19-b9cf-473c-bf27-442df3912ba7.png">

### Can you reproduce the bug?

Always

### Version

"realm": "^11.3.1", "@realm/react": "^0.4.1"

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@devsales Thanks for reporting.  We already have a fix for this released in version `11.5.2` by [this PR](https://github.com/realm/realm-js/pull/5493).  Please upgrade to the latest version of `realm` to fix the issue..
