### ISSUE TITLE
realm.node is not a valid Win32 application

### ISSUE THREAD

**Issue by rossicler-hostalky** [realm/realm-js#5713]
### How frequently does the bug occur?

Always

### Description

Hi, I'm using realm v11.7.0 with electron. Creating builds work without any issues, but after installing on windows and running the application, I'm getting this error `...\realm.node is not a valid Win32 application`. This error only happens for Windows, for Mac it works fine.

I'm using [electron-react-boilerplate](https://electron-react-boilerplate.js.org/) configuration.

### Stacktrace & log output

```shell
Uncaught Exception:
Error:
\\?\C:\Users\MyUser\AppData\Local\Programs\electron-react-boilerplace\res...\realm.node is not a valid Win32 application.
\\?\C:\Users\MyUser\AppData\Local\Programs\electron-react-boilerplace\res...\realm.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at c._load (node:electron/js2c/asar_bundle:5:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
   ...
```

### Can you reproduce the bug?

Always

### Reproduction Steps

For reproducing the issue I created a very minimal sample project with [electron-react-boilerplate](https://electron-react-boilerplate.js.org/), added realm and added realm tutorial example code.
```
git clone https://github.com/rossicler-hostalky/realm-win-error && cd realm-win-error

yarn
```

if you want to test in development
```
yarn start
```

to create the windows build
`yarn package --win` or `yarn package --win --x64`

In case you want to run development after creating a build, you need to run this
```
ts-node ./.erb/scripts/clean.js
yarn
```

### Version

11.7.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS Monterey 12.6

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@rossicler-hostalky Thanks for submitting this issue.  Did this just start happening on `11.7.0` or is this a new project you are working on?  I would like to know if there was an older version that this was functioning on, so we can determine if this broke, or if this has been an unnoticed issue for some time.

**Comment by rossicler-hostalky** [comment]
It's a new project, but I also tried downgrading the realm version to some other versions like `v11.5.1` and `v10.24.0`. All of them gave me the same problem.

**Comment by takameyer** [comment]
@rossicler-hostalky Ok, good to know. We will have to investigate then.

**Comment by rossicler-hostalky** [comment]
Sure, I'll wait for updates, thanks

**Comment by blagoev** [comment]
@rossicler-hostalky Are you using a Windows x86 32 bit installation in a virtual machine. We can not reproduce this problem on Win x64?

**Comment by rossicler-hostalky** [comment]
It's a windows 64 bit installation. Running the command you send returns `AMD64`.

**Comment by rossicler-hostalky** [comment]
Quick update, I've been searching about this error "... is not a valid Win32 application" and it looks like one of the reasons is that for packaging for windows, I need a windows vm or machine. Was that the case for your test? I've been packaging using a Mac and sending the .exe to my windows machine.
