### ISSUE TITLE
Realm instance closed during background (custom) sync causing "Cannot access realm that has been closed" error on realm.write()

### ISSUE THREAD

**Issue by Acetyld** [realm/realm-js#5731]
### How frequently does the bug occur?

Always

### Description

We have a sync function that syncs our server with Realm, which can take a while. If the user sends the app to the background during this process, the sync continues for a few seconds before the app is suspended. During this time, the Realm instance is closed (i think?),_ causing the realm.write() call to fail and resulting in the "Cannot access realm that has been closed" error.
So i think the realm instance is closed when app goes to background and thats why we get this error.
Sentry is getting spammed by it.

In sentry we see it always happens after event:
```
app.lifecycle
{
state: background
}
```

### Stacktrace & log output

```shell
app.lifecycle
{
state: background
}

After that: 

Error: Exception in HostFunction: Cannot access realm that has been closed.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

**Step 1.** 
Start the sync passing the realm
Imagine this takes like 5 minutes.
```js
const { useRealm } = RealmContext;
const realm = useRealm();

//Fake for each loop to reproduce bug.
for (let i = 0; i < 100; i++) {
  updateSyncRealm({realm, schema: TasksSchema, data: {}, extraData: {}});
}


export const updateSyncRealm = ({ realm, schema, data, extraData }) => {
  realm.write(() => {
    for (const item of data) {
      realm.create(
        schema.schema.name,
        schema.add({ ...item, ...extraData }, realm),
        'modified',
      );
    }
  });
};
```

**Step 2**

Make the app go in background.
After this the realm.write will be triggered.

**Step 3**

Expect the following error to happen:
Cannot access realm that has been closed.

### Version

   "realm": "^11.7.0",    "@realm/react": "^0.4.3",

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

    "react-native": "0.71.4",

### Build environment

Which debugger for React Native: ..
Flipper

**Comment by Acetyld** [comment]
Yhea for us it is not happing in "real background" it happens directly when the app is only like 3/4 seconds in background, and it also happens on android.

Maybe its something due to realm.write being called rappidly bcs of sync, maybe i should add a realm if (!realm.isClosed()) {
but this seems cumbersome

**Comment by kneth** [comment]
@Acetyld Sorry for the late reply. Is it possible for you to create a small app which can reproduce this?
