### ISSUE TITLE
Android error: XMLHttpRequest cannot load ... in rpc.js

### ISSUE THREAD

**Issue by jamealg** [realm/realm-js#574]
I'm seeing these errors in the debugger when I'm running on my Nexus 6P (Android):

![index.android.bundle:87959XMLHttpRequest cannot load http://2600:1015:8026:1a94:43b5:539e:3fe3:1af2%13:8082/create_session. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.](http://jameals.com/temp/Screen Shot 2016-08-21 at 1.15.12 PM.png)

So far it doesn't seem to be causing any functional issues with Realm but it's still troubling. I'm on OSX using React Native 0.31.0 and Realm 0.14.3. I don't get the same issues running iOS simulator.

I recently upgraded from React Native 0.29.2 so I wonder if that has something to do with it.

**Comment by alazier** [comment]
There are currently issues when running in chrome debug mode when running on device. We hope to fix this in a future release but do not currently have a timeline. If you turn off chrome debug mode you should no longer see these errors when running on device.

**Comment by jamealg** [comment]
Good to know. It seems to be functioning normally though. Are there any
specific problems to be aware of when running in chrome debug mode?

**Comment by alazier** [comment]
We have had some reports of connectivity issues and performance has also caused problems for some users. Functionally everything else should work identically if you are able to make rpc requests which it sounds like it is the case for you.

**Comment by alazier** [comment]
I assume everything is working for you now? If not please reopen this or a new issue.

**Comment by jamealg** [comment]
Yes thanks for following up. Console errors aside I haven't noticed any problems with functionality.
