### ISSUE TITLE
realm@11.2.0 install: `prebuild-install --tag-prefix= -r napi || cmake-js build`

### ISSUE THREAD

**Issue by nitheeshnd** [realm/realm-js#5747]
Getting below error while installing realm on my mac laptop
node version: v14.16.0
npm version:6.14.11

MacBook Pro
mac Os: 13.3.1 (22E261)

**Comment by kneth** [comment]
@nitheeshnd I am not able to reproduce it

<img width="1510" alt="Screenshot 2023-04-19 at 17 21 37" src="https://user-images.githubusercontent.com/1225363/233123139-07628591-767f-4f41-a7e4-0a56997ffafc.png">

There is a warning, which indicates it is recommended to upgrade `rpm` (see also https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md).

**Comment by nitheeshnd** [comment]
@kneth , getting same error, Please check attached screenshot and let me know if any changes required.

node version:  v16.19.0
npm version: v8.19.3
<img width="1004" alt="Screenshot 2023-04-20 at 10 23 21 AM" src="https://user-images.githubusercontent.com/46712632/233261693-9a9e8a25-8783-48e8-ae97-cc9788a3a32d.png">

**Comment by kneth** [comment]
It looks like the issue is between your end and npmjs.org. Please upgrade `npm` or run `npm config set registry https://registry.npmjs.org/`
