### ISSUE TITLE
Realm date data type problem

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-js#5788]
### How frequently does the bug occur?

Always

### Description

Hello, I have a problem releated with date data type. when I open a debugger(ex: chrome-debugger) in my react-native app everthing is fine but when I closed the debugger, realm query not working correctly. For example my realm query result like this(uptadet_at a property and type is date).
```
{
    name: 'Bill'
    updated_at: 2023-05-02T11:35:01.000Z
}
```
I want to reach this result object keys 
when debugger is open 
console.log(Object.keys(result)) --> output: ['name','updated_at']

when debugger is closed
console.log(Object.keys(result)) --> output: []

thank you for helps

### Can you reproduce the bug?

Always

### Version

v11.8.10

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

mac 13.2.1(Ventura)

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
`Object.keys()` and the spread operator don't work reliable in version 11. We have fixed it in version 12 (currently in alpha). As a workaround, you could use `result.toJSON()`.

**Comment by MuratAkbaba006** [comment]
this fixed the problem but led to another problem in my logic. I made a workaround for now. waiting for realm@12 then. thanks for the response
