### ISSUE TITLE
"tar -xzf" cannot decompress tar.bz2 nor tar.xz

### ISSUE THREAD

**Issue by loevaljh** [realm/realm-js#579]
Hi Team,
I love your project!

There is a bug here

If the core file downloaded is *.tar.bz2 (in the older version) or *.tar.xz (in the current version), 
`CORE_DOWNLOAD_FILE="realm-core-$REALM_CORE_VERSION.tar.xz"`
https://github.com/realm/realm-js/blob/master/scripts/download-core.sh#L25

This line will fail:
`tar -xzf "$CORE_TAR"`
https://github.com/realm/realm-js/blob/master/scripts/download-core.sh#L56

Please fix the tar command (why don't you just use tar.gz for all?)

**Comment by bdash** [comment]
Which platform are you on? Can you please share the output of `tar --version` to help us understand why you're having difficulty decompressing the tarball?

> why don't you just use tar.gz for all?

xz and bzip2 have significantly better compression than gzip, and support for both has been widely available for a number of years now.

**Comment by loevaljh** [comment]
~$tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
~$
~$
~$touch helloworld.txt
~$
~$tar -c --xz -f helloworld.tar.xz helloworld.txt
~$
~$tar -xzf helloworld.tar.xz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~$
~$tar -cjf helloworld.tar.bz2 helloworld.txt
~$
~$tar -xzf helloworld.tar.bz2

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~$

**Comment by bdash** [comment]
What OS version are you on?

**Comment by loevaljh** [comment]
OS X EI Capitan
Version 10.11.6

**Comment by bdash** [comment]
Ah, you have GNU tar on your PATH ahead of the system version.

I think the solution here is to simply drop the `z` argument to `tar`, since all modern versions will auto detect compression. BSD tar appears to also auto detect the presence of compression even when `z` is specified (you can decompress a plain `.tar` file with `tar xzf foo.tar`), but GNU tar treats `z` as meaning the input must be gzip.

**Comment by loevaljh** [comment]
Thanks for the fix!

**Comment by alazier** [comment]
Is this still an issue for you @loevaljh ? If not we can close this.

**Comment by bdash** [comment]
While I suspect @loevaljh has worked around this, we should still fix download-core.sh as I noted above.

**Comment by loevaljh** [comment]
Please close it.
