### ISSUE TITLE
Error compiling a project in TypeScript

### ISSUE THREAD

**Issue by whiteua** [realm/realm-js#5799]
### How frequently does the bug occur?

Always

### Description

When trying to compile a project in TypeScript, the compiler gives an error: 
` Cannot find module '../generated/ts/realm.node'`.
Windows 11, node v18.14.2 

When compiling on Ubuntu 22.04, node v18.14.2 Typescript - everything works fine.

I checked in node_modules. Indeed, the file ` ../generated/ts/realm.node` is indeed missing. 

### Stacktrace & log output

```shell
Error: Cannot find module '../generated/ts/realm.node'
Require stack:
- C:\White\Dev\ts-test-realm\node_modules\realm\dist\bundle.node.mjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\White\Dev\ts-test-realm\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at file:///C:/White/Dev/ts-test-realm/node_modules/realm/generated/ts/native.mjs:22:22
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\White\\Dev\\ts-test-realm\\node_modules\\realm\\dist\\bundle.node.mjs'
  ]
}
```

### Can you reproduce the bug?

Always

### Reproduction Steps

```
import { Realm } from 'realm';

const TaskSchema = {
    name: "Task",
    properties: {
      _id: "int",
      name: "string",
      status: "string?",
      owner_id: "string?",
    },
    primaryKey: "_id",
  };
  

const realm = await Realm.open({
      schema: [TaskSchema],
      inMemory: true,
});

```

### Version

realm@12.0.0-alpha.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Windows 11

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
What architecture are you installing on? 64 bit intel or arm64?

Can you share the output of running this command in your `node_modules/realm` directory?

```
npx prebuild-install --runtime napi
```

**Comment by kantorcodes** [comment]
FYI I am getting this too inside of Docker within NextJS

#16 77.20 Error: Cannot find module '../generated/ts/realm.node'
#16 77.20 Require stack:
#16 77.20 - /app/node_modules/realm/dist/bundle.node.js
#16 77.20 - /app/node_modules/realm/index.node.js

**Comment by brianmuks** [comment]
> FYI I am getting this too inside of Docker within NextJS
> 
> #16 77.20 Error: Cannot find module '../generated/ts/realm.node' #16 77.20 Require stack: #16 77.20 - /app/node_modules/realm/dist/bundle.node.js #16 77.20 - /app/node_modules/realm/index.node.js

Same here

**Comment by uceumice** [comment]
@kraenhansen referencing the request for testing out the command, I (also running Win11) get the following...

`prebuild-install warn install No prebuilt binaries found (target=6 runtime=napi arch=x64 libc= platform=win32)`

**Comment by kneth** [comment]
@uceumice Please create a new issue and remember to fill in all requested details.
