### ISSUE TITLE
Filtering by linking objects crashing an app

### ISSUE THREAD

**Issue by thecoorum** [realm/realm-js#5803]
### How frequently does the bug occur?

Always

### Description

I was trying to filter the model `Category` with the following query `type == "expense" AND @links.Transaction.userId == "644826202ad0cf54f1385eff" AND @links.Transaction.wallet.currency.id == uuid(5cdc1046-49c8-4e06-bba9-555e633a824e)`. If I replace the `@links.<Model>.<Property>` with simple dot notation Realm seems to be just ignoring them. Am I doing something wrong?

Here are the models for the reference

```
static schema = {
  name: 'Currency',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    ...
  }
}

static schema = {
  name: 'Wallet',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    ...
    currency: 'Currency',
    ...
  }
}

static schema = {
  name: 'Transaction',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    ...
    wallet: 'Wallet',
    ...
  }

static schema = {
  name: 'Category',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    ...
    type: 'string',
    ...
    transactions: {
      type: 'linkingObjects',
      objectType: 'Transaction',
      property: 'category'
    },
    ...
  }
}
```

### Stacktrace & log output

```shell
[Gist](https://gist.github.com/thecoorum/d75c212bf4f777c2b6c1f6f954e69894)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Init Expo application with the following model structure
2. Try to filter based on example given above
3. See the crash

### Version

11.8.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.2

### Build environment

Which debugger for React Native: Flipper

**Comment by kneth** [comment]
It looks like you are getting a crash with your query. I have tried to rewrite it a bit and it might be off as I don't know exact what your intension is.

```js
const Realm = require("realm");

const Currency = {
  name: 'Currency',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
  }
};

const Wallet = {
  name: 'Wallet',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    currency: 'Currency',
  }
};

const Transaction = {
  name: 'Transaction',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    userId: 'string',
    wallet: 'Wallet',
    category: 'Category',
  }
};

const Category = {
  name: 'Category',
  primaryKey: 'id',
  properties: {
    id: 'uuid',
    type: 'string',
    transactions: {
      type: 'linkingObjects',
      objectType: 'Transaction',
      property: 'category'
    },
  }
};

let realm = new Realm({ schema: [Currency, Wallet, Transaction, Category] });
let categories = realm.objects("Category").filtered('type == "expense" AND ANY transactions.userId == "644826202ad0cf54f1385eff" AND transactions.wallet.currency.id == uuid(5cdc1046-49c8-4e06-bba9-555e633a824e)');
realm.close();
```

**Comment by thecoorum** [comment]
So, if I understood correctly links are working only if linkingObjects are not defined in the schema, right?

**Comment by kneth** [comment]
`linkingObjects` is a computed property, and you don't set it explicitly (Realm is recomputing the list/array when needed).
