### ISSUE TITLE
Realm link issue with React native

### ISSUE THREAD

**Issue by j-Kode** [realm/realm-js#581]
Hey everyone, I needed help. I'm trying to get realm working on my windows environment with android. I keep getting this error, 

rnpm-link info Android module realm is already linked
rnpm-link info iOS module realm is already linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

I did alot of googling  about editing files and even after I have edited mainactivity.java I still get the following error.

Missing Realm constructor - please ensure RealmReact framework is included!

Please any help would be appreciated, I have been stuck on this for a while. Thanks everyone.

**Comment by alazier** [comment]
What versions of react-native and realm are you using? I believe with the latest react-native versions you need to instead edit `MainApplication.java`.

**Comment by fealebenpae** [comment]
With the latest `react-native-cli@1.0.0` you need to run `react-native link realm` instead of `rnpm`. We will update the docs to reflect this.

**Comment by alazier** [comment]
Did running `react-native` link fix your issue?

**Comment by j-Kode** [comment]
I sorry for not replying in a while. Yes it solved my issue. Thank you.
