### ISSUE TITLE
Realm sync with atlas issue

### ISSUE THREAD

**Issue by seif1000** [realm/realm-js#5810]
### How frequently does the bug occur?

Always

### Description

I am using Realm Sync with MongoDB Atlas in a React Native app. The use case I am working on is that I want to create a Realm object, and once I have created this object, I need to update it constantly using time intervals. Once I get the newly created object _id, I use it to update this current object instantly. The error I am getting is: 'Exception in HostFunction: Accessing object of type Post which has been invalidated or deleted 
and when I log the newly created _id from the react native app and compare it to the one in MongoDB they are different:
`

 // this is the object creation function
  const created_post = handleAddPost();
     

      watchId.current = Geolocation.watchPosition(
        async position => {
          realm.write(() => {
            let updated_post = realm.create(
              'Post',
              {
                _id: new Realm.BSON.ObjectId(created_post._id),
                body: 'My trip',
                coords: [
                  ...created_post?.coords,
                  {
                    lat: position.coords.latitude.toString(),
                    long: position.coords.longitude.toString(),
                  },
                ],
              },
              'modified',
            );
          });
`

 Also, sometimes I get an error that I think is related to the above issue. When I create a new object from the React Native app, it is saved successfully in the MongoDB database. But when I make some manual changes from MongoDB, I get this error: {'category': 'realm::sync::ClientError', 'code': 112, 'is fatal': True, 'message': 'Bad changeset (DOWNLOAD): Failed to apply received changeset: Update: No such object: Post in class 'ObjectId{6460f24bd60bc9ad4c93d080}' (instruction table: Post, version: 165, last_integrated_remote_version: 268, origin_file_ident: 10, timestamp: 264004727013)'}.

### Stacktrace & log output

```shell
Error: Exception in HostFunction: Accessing object of type Post which has been invalidated or deleted

{"category": "realm::sync::ClientError", "code": 112, "isFatal": true, "message": "Bad changeset (DOWNLOAD): Failed to apply received changeset: Update: No such object: Post in class 'ObjectId{6460f24bd60bc9ad4c93d080}' (instruction table: Post, version: 165, last_integrated_remote_version: 268, origin_file_ident: 10, timestamp: 264004727013)
```

### Can you reproduce the bug?

Always

### Version

11.3.1

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Android 13

### Build environment

Which debugger for React Native: ..

react-nnative :"0.70.1"
realm: "^11.3.1"
"@realm/react": "^0.4.3",

**Comment by seif1000** [comment]
Do you mean @realm/babel-plugin, No I am not
This is my model implementation 
`
import {Realm} from '@realm/react';


export class Coord extends Realm.Object<Coord> {
  lat!: string;
  long!: string;
 
  static schema = {
    name: "Coord",
    embedded: true, // default: false
    properties: {
      lat: "string",
      long: "string",
  
    },
  };
}

export class Post extends Realm.Object<Post> {
  _id: Realm.BSON.ObjectId = new Realm.BSON.ObjectId();
  body!: string;
  createdAt!: Date;
  owner!:string;
  images?: Realm.List<string>;
  coords!:Realm.List<Coord>;
  isMap!:boolean;
  isComplete!:boolean



  static schema = {
    name: 'Post',
    properties: {
      _id: 'objectId',
      body: 'string',
      createdAt:{
        type:"date",
        default:new Date(),

      },
      owner: 'string',
      images:{
        type:"list",
        objectType:"string"
      },
      coords: {
        type: 'list',
        objectType: 'Coord',
      
      },
      isMap:{
        type:"bool",
        default:false,

      },
      isComplete:{
        type:"bool",
        default:false,

      }
   
    },
    primaryKey: '_id',
  };
}
`

**Comment by kneth** [comment]
> Do you mean @realm/babel-plugin, No I am not

Yes, that's what I meant :+1:

You are calling `new Realm.BSON.ObjectId()` twice - once in the schema and once in the code.  Either remove the one in the class entirely or move it to the `schema` (as `_id: { type: 'objectId', default: () => new Realm.BSON.ObjectId() }`).

**Comment by seif1000** [comment]
Thank you @kneth  this was the issue
