### ISSUE TITLE
Figure out what to do about "Lists - supports snaphots" test.

### ISSUE THREAD

**Issue by RedBeard0531** [realm/realm-js#5817]
Realm core changed the behavior of snapshotted `Results` of collections in v13.11.0 (https://github.com/realm/realm-core/issues/6635), in a way that broke this test: https://github.com/realm/realm-js/blob/412d5a62c2807608b54c0c72a5d98874e26a5192/integration-tests/tests/src/tests/list.ts#L1134-L1172

As part of upgrading `main` to realm-core@v13.11.0 we are temporarily disabling that test, but we should revisit this prior to the final release of realm-js v12.
* If core decides to revert to the old behavior we should simply re-enable the test without modifying it
* If core decides to keep the new behavior we should re-enable the test and modify it to reflect the new reality. This should probably result in a changelog note as well in this case.

**Comment by kneth** [comment]
It seems to have been fixed in core, and we will have to wait for a new core release
