### ISSUE TITLE
React Native with Realm - Removing from iCloud Backup

### ISSUE THREAD

**Issue by abhaytalreja** [realm/realm-js#582]
Creating a github issue for [Stackoverflow question](http://stackoverflow.com/questions/38478582/react-native-with-realm-removing-from-icloud-backup).

My question is, how can we prevent this from happening. I am using `Realm.copyBundledRealmFiles();` for pre-loading data. Please see https://github.com/realm/realm-js/issues/392 for more details on the approach.

If i change my realm path like below, will it work? Will the realm files be avoided from the iCloud backup? 

```
let realmPath = Platform.OS == 'android' ? 'default.realm' : RNFS.DocumentDirectoryPath +'/tmp/default.realm';
```

P.S. I am using react native document directory for getting the documents directory path in react native.

Any help will be great, especially when i am at the last step of getting the app completed :)

**Comment by alazier** [comment]
I think if you move the realm file to the Caches directory you will avoid this issue. See https://developer.apple.com/icloud/documentation/data-storage/index.html

**Comment by abhaytalreja** [comment]
@alazier yes, i tried doing it.. by adding it to the path... however, i am using `Realm. copyBundledRealmFiles();` so it may not work as the path is hardcoded for this method....

**Comment by alazier** [comment]
Yeah. Right after calling `copyBundledRealmFiles()` you could try to move the files from the Documents directory to the Caches Directory? Not sure if this will work but might be worth a try.

**Comment by alazier** [comment]
Were you able to get this working?

**Comment by alazier** [comment]
Hope you were able to get this working. If there are api changes we can make to make this easier feel free to open another issue.
