### ISSUE TITLE
BSON: For React Native please polyfill crypto.getRandomValues when using the new Realm.BSON.UUID() to generate a unique ID

### ISSUE THREAD

**Issue by adhamhassan99** [realm/realm-js#5841]
### How frequently does the bug occur?

Always

### Description

I integrated Realm in a React Native app using version 0.71.7 , created a schema and followed the basic setup and all works perfectly fine. When I added the uuid field and used the new `Realm.BSON.UUID()` to generate an id, It does actually generate an Id and I confirmed it by printing the value however I receive a warning as illustrated in the image below:
![image](https://github.com/realm/realm-js/assets/49523561/ab318d4b-be17-4b1b-ab21-b15c64a618bd)
 upon clicking it it expands to show: 
![image](https://github.com/realm/realm-js/assets/49523561/7e531803-eb43-4eac-8540-087b6d45197b)

### Stacktrace & log output

```shell
WARN  BSON: For React Native please polyfill crypto.getRandomValues, e.g. using: https://www.npmjs.com/package/react-native-get-random-values.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. create a react native project 
2. setup real by following basic real setup docs for react native
3. add a schema that has a uuid field for ex:
 ```
export class CarSchema extends Realm.Object<CarSchema> {
  name!: string;

  brand!: string;

  makeYear?: number;

  price!: number;

  _id!: Realm.BSON.UUID;

  static schema = {
    name: 'CarSchema',
    properties: {
      _id: 'uuid',
      name: 'string',
      brand: 'string',
      makeYear: 'int?',
      price: 'float',
    },
  };
}
```
6. in your app.tsx add  the following before the return statement
```
 const addObject = () =>
    realm.write(() =>
      realm.create(CarSchema, {
        _id: new Realm.BSON.UUID(),
        name: 'X6',
        brand: 'BMW',
        price: 300000,
        makeYear: 2023,
      }),
    );
```
and the following in your return statement:
`<Button label="add car" onPress={addObject} />`

after clicking the button you will get the same warning

### Version

latest

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android API 30

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
> I don't see an open issue for this

... but I'm sure they would appreciate the feedback from someone opening an issue.
Perhaps something changed in the 5 years since https://github.com/facebook/react-native/issues/5049 got closed.

**Comment by adhamhassan99** [comment]
> > I don't see an open issue for this
> 
> ... but I'm sure they would appreciate the feedback from someone opening an issue. Perhaps something changed in the 5 years since [facebook/react-native#5049](https://github.com/facebook/react-native/issues/5049) got closed and locked.

looks like ill have to settle for now on manually installing it while opening a ticket there if suitable. Thanks for the support

**Comment by beardwin** [comment]
> > I'm interested to know if you've tried to apply the polyfill mentioned in the warning?
> > https://www.npmjs.com/package/react-native-get-random-values
> > If not, what are your concerns (if any) about applying it?
> 
> I know installing the mentioned package will suppress the warning however it surely is not a final solution for this issue as it needs to be addressed from its core. also referring back to this comment [#3714 (comment)](https://github.com/realm/realm-js/issues/3714#issuecomment-834328297)
> 
> @kraenhansen

I installed it. Did a rebuild. Still seeing the warning. It won't disappear. Life is hard.

**Comment by kraenhansen** [comment]
@beardwin are you importing the polyfill before you import realm or bson?

**Comment by mujehoxe** [comment]
> @beardwin are you importing the polyfill before you import realm or bson?

thing is we want it to become dependency, we shouldn't import it in our code it should be used by realm

**Comment by kraenhansen** [comment]
> What should we do?

@bloggerklik follow [the link](https://www.npmjs.com/package/react-native-get-random-values) and apply the polyfill if you want a secure UUID implementation 👍
