### ISSUE TITLE
After building the Android apk, it crashes upon launch.

### ISSUE THREAD

**Issue by niceKingsley** [realm/realm-js#5847]
### How frequently does the bug occur?
Always

### Description
After building the apk and installing it on the phone, it crashes on launch on the device. However, when I debug on a real device or a virtual machine, nothing ill happens. I'm not sure how to proceed.

### Can you reproduce the bug?
Always

### Version
realm: 11.9.0  @realm/react: 0.4.3 node: 18.13.0 react-native: 0.71.6

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
window11 

### Build environment
Which debugger for React Native: ..

**Comment by niceKingsley** [comment]
Hi@kraenhansen
This is the error message I got when I start up

![c7105f743346dbbe949dc19542942c3](https://github.com/realm/realm-js/assets/127419413/9a0063a5-d104-4688-bbca-57b9dc59080c)

**Comment by kraenhansen** [comment]
Interesting. It looks like the native library (librealm.so) isn't able to be located. Are you performing any build steps that might be stripping native binaries? Also, is this happening on all architectures or have you only experienced this on a single architecture (which?).

**Comment by niceKingsley** [comment]
@kraenhansen 
Tried all architectures, to no avail. A single architectures doesn't help either.

**Comment by takameyer** [comment]
@niceKingsley I have tested on [our template](https://github.com/realm/realm-js/tree/main/templates/react-native-template) and the apk generated seems to be working fine.  I used the command `npx react-native run-android --mode=release` to test this.  How are you generating your apk?   Have you made some significant changes to any of the gradle files in `android`?
