### ISSUE TITLE
How to create instance of a realm object instead of creating a object in realm

### ISSUE THREAD

**Issue by chandranikitha94** [realm/realm-js#585]

**Comment by alazier** [comment]
Since JS isn't type safe you can just create a regular JS object and set/get properties and interact with it much as you would interact with a Realm object. You can then pass this object to `realm.create` to create a new object in a Realm with the same properties.

**Comment by alazier** [comment]
Does this answer your question?

**Comment by chandranikitha94** [comment]
Yes
