### ISSUE TITLE
Realm 12 throwing "Error: Cannot determine which app is associated with user (id  = <correct user id>)"

### ISSUE THREAD

**Issue by ccapndave** [realm/realm-js#5856]
### How frequently does the bug occur?

Always

### Description

I am unable to login to Realm with a username/password.

### Stacktrace & log output

```shell
Error: Cannot determine which app is associated with user (id  = <correct user id>)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Here is what I did:

1. Create a Realm app with username/password login enabled.
2. Manually create a user in the Mongo web UI.  I then use Realm in Typescript to login like so:
3. Use the following React code to login

```
function Login() {
  const app = useApp();

  React.useEffect(() => {
    const creds = Realm.Credentials.emailPassword("username", "password");
    app.logIn(creds).then(console.log);
  }, []);

  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <ActivityIndicator size="large" />
    </View>
  );
}

function AppWrapper() {
  return (
    <AppProvider id="my-app-id">
      <UserProvider fallback={Login}>
        <TheRestOfMyApp />
      </UserProvider>
    </AppProvider>
  );
}
```

This results in `UserProvider` throwing the following error.

```
Error: Cannot determine which app is associated with user (id  = <correct user id>)
```

The same code works correctly in Realm 11.

### Version

12.0.0-alpha.2

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.4.1 (a)

### Build environment

Building on MacOS Ventura with XCode 14.2.  

### Cocoapods version

1.12.1

**Comment by takameyer** [comment]
@ccapndave I noticed this as well and have already merged [a solution](https://github.com/realm/realm-js/pull/5790).  It should go away on the next release.  For now you can use something like [patch-package](https://www.npmjs.com/package/patch-package) to apply the merged fix.
