### ISSUE TITLE
Collection.watch() not returning generated response

### ISSUE THREAD

**Issue by SipNWork** [realm/realm-js#5858]
### How frequently does the bug occur?

Always

### Description

Collection.watch invoked to get realtime updates from specific collection, but not getting triggered even when logs showing Ok on app services. 

React-native configurations 

 "react": "18.2.0",
 "react-native": "0.71.8", 
"@realm/react": "^0.4.3",
"realm": "11.9.0",

### Can you reproduce the bug?

Always

### Version

0.4.3

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

MAC os

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@SipNWork Have you set up any polyfills, such as `react-native-polyfill-globals`?  These are necessary in order to use `watch`.  You can find more info in [our documentation](https://www.mongodb.com/docs/realm/sdk/react-native/app-services/query-mongodb/#real-time-change-notifications)

**Comment by SipNWork** [comment]
> our documentation

Yes, Added all three in my app.js file.

**Comment by SipNWork** [comment]
> @SipNWork There is [an issue](https://github.com/react-native-community/fetch/issues/13) with fetch on Android that may be causing this. Are you seeing this problem on iOS as well?

Yes, I am facing this on IOS.

**Comment by takameyer** [comment]
@SipNWork We have this covered in our integration tests and it is passing.  Can you possibly create a sample repo to reproduce this issue?  Then we can help further to diagnose the problem.

**Comment by SipNWork** [comment]
`const reply = await new DefaultNetworkTransport().fetch(request)`

File - mongo-client.js , line no - 216
relative path - node_modules/realm/lib/mongo-client.js

Fetch never resolves any response. I checked the logs in mongodb console and request was successful.

Configurations
    "react": "18.2.0",
    "react-native": "0.71.8",
    "realm": "11.9.0",

**Comment by SipNWork** [comment]
> @SipNWork We have this covered in our integration tests and it is passing. Can you possibly create a sample repo to reproduce this issue? Then we can help further to diagnose the problem.

Would be helpful if you could connect with me on Gmeet or Zoom to resolve this issue. Our release is blocked due to this issue.
