### ISSUE TITLE
realm mapTo error

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-js#5863]
### How frequently does the bug occur?

Always

### Description

Hi, I have a realm schema like this 
export const Person = {
  name: 'new',
  properties: {
    new_school: {
      type: 'string',
      mapTo: 'school',
    },
    new_surname: {
      type: 'string',
      optional: true,
      mapTo: 'surname',
    }
  primaryKey: 'school',
};

when I added records everythings is fine. I can see columns name as "school" and "surname" in realm Studio but when I try to read realm schema records like this ( db.objects(new).toJSON() ).  I see column names as new_school and new_surname. 
does the mapTo feature only work when adding records? is that a bug?

### Can you reproduce the bug?

Always

### Reproduction Steps

add records a realm schema with mapTo property.
read this record.

### Version

11.8.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

mac monterey 12.5.1

### Build environment

just metro I dont use a debugger.

**Comment by takameyer** [comment]
According to [our docs](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#~ObjectSchema)

> This can e.g. be used to have different naming convention in Javascript than what is being used in the Realm file. Reading and writing properties must be done using the public name. Queries can be done using both the public and the underlying property name.

So it is working as designed.  I do agree that this isn't particularly idiomatic.

**Comment by MuratAkbaba006** [comment]
Thanks for the response 🥇
