### ISSUE TITLE
Issue when we use realmContext and Realm.config at same time

### ISSUE THREAD

**Issue by somasekharkakarla** [realm/realm-js#5871]
### How frequently does the bug occur?

Always

### Description

Hi @kneth and @takameyer  ,

Here is a problem i have found with realm.

@realm/react is hook i am using in view components to for CURD operations. 
I am using Realm.config in RealmMangerClass for listening the changes in old fashion and changed data was updated to server. I am writing the response from server to realm. These are all happing in RealmManager

In this way. i am initialising same config at two place. createRealmContext at App.js and Realm.open in RealmManager class

In random case both (RealmContext and Realm.open) > write to db.
This is causing two errors:
1. realm already in write transaction
2. [Error: Exception in HostFunction: Accessing object of type Tasks which has been invalidated or deleted]

Is there any way i can get reference of realm from createRealmContext. where i can use it in RealmManager class instead of initialising again in Class 

I want to use hook on UI and listen to listener and  do CURD operations in old fashion at same time.

### Can you reproduce the bug?

Always

### Version

11.3.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android 13

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@somasekharkakarla The workflow you described is supported.  As long as you use the same configuration passed to `createRealmContext` and `new Realm()`, the result will be a shared instance of the same Realm.  Even if you were to get the same realm from `createRealmContext` and have it in your RealmManager, the result would likely be the same.

Let's address the errors you are having:

> realm already in write transaction

There is a member variable on the realm instance called [isInTransaction](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.html#isInTransaction).  I would recommend using this in the areas that have been crashing to help ensure you do not come into conflict with realm transactions.

> [Error: Exception in HostFunction: Accessing object of type Tasks which has been invalidated or deleted]

This can happen if you are holding onto a realm object that isn't managed by the hooks (`useObject`, `useQuery`).  The hooks will automatically re-render and nullify any invalid objects.  If you are doing some logic with RealmManager to look at a held instance of some object, then I would recommend checking the member variable [isValid](https://www.mongodb.com/docs/realm-sdks/js/latest/Realm.List.html#isValid) on the object.

Let me know if this helps!

**Comment by somasekharkakarla** [comment]
Hi @takameyer,

Thank for the response. isInTransaction is really helpful. Tell me something,
I am using a hook taskObj = useObject('Task', uid)
i delete it from backend from a async call. But i am still in same component. Then i am getting 
[Error: Exception in HostFunction: Accessing object of type Tasks which has been invalidated or deleted]
i used isVaild() it says undefined and crash
is there anyway we can know the obj is deleted.

**Comment by somasekharkakarla** [comment]
Hi @takameyer ,
i'm pleasing you looking into this feature request https://github.com/realm/realm-js/issues/5864. I think it will give more power to developers

**Comment by somasekharkakarla** [comment]
Hi @takameyer . i will reverify it again.

**Comment by somasekharkakarla** [comment]
Hi @takameyer ,

i reverified. crash is happening at useObject only.

try {
    taskObj = useObject('Tasks', task?.uid);
      taskObj.addListener((task:any, changes:any) =>{
          if(changes.deleted){
              navigation.goBack();
          }
      })
  } catch (e) {
      console.error(" taskObj.addListener Error", e)

**Comment by somasekharkakarla** [comment]
Hi @takameyer , sure. i create separate repo for that share you soon.

**Comment by kneth** [comment]
@somasekharkakarla Sounds good. We will leave the issue open and you can post a link to the repo once you are ready.
