### ISSUE TITLE
Building from source results in error related to the logger

### ISSUE THREAD

**Issue by krollins-mdb** [realm/realm-js#5874]
### How frequently does the bug occur?

Always

### Description

I expected to be able to use `npm link` or `npm pack` to use the latest features that have been added but not included in a release.

Building from source and using Realm.js in the docs test suite using `npm link` and by creating a `.tgz` file with `npm pack`.

In both cases, running my tests results in the following error:
`TypeError: _native_Helpers_make_logger is not a function`.

Running tests in my local `realm-js` repo is all green. This seems to be an issue with bindgen and bundling.

### Stacktrace & log output

```shell
FAIL   TypeScript  __tests__/quickstart.test.ts
  ● Test suite failed to run

    TypeError: _native_Helpers_make_logger is not a function

      1628 |   }
      1629 |   static makeLogger(log) {
    > 1630 |     return _native_Helpers_make_logger(log);
           |            ^
      1631 |   }
      1632 |   static simulateSyncError(session, code, message, type, is_fatal) {
      1633 |     return _native_Helpers_simulate_sync_error(session, code, message, type, is_fatal);

      at Function.makeLogger (../../../../realm-js/packages/realm/dist/bundle.node.js:1630:12)
      at Function.setLogger (../../../../realm-js/packages/realm/dist/bundle.node.js:9587:32)
      at Object.<anonymous> (../../../../realm-js/packages/realm/dist/bundle.node.js:10413:7)
      at Object.<anonymous> (jestSetup.ts:2:1)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Download/clone the `realm-js` repo.
2. In your local `realm-js` repo, in `packages/realm`, run the following commands:
  - `npm install`
  - `npm run build`
  - `npm link`
3. Download/clone the [`docs-realm` repo](https://github.com/mongodb/docs-realm/tree/realmjs-v12/examples/node/v12).
4. In the `realmjs-v12` branch, navigate to `examples/node/v12`.
5. Run `npm install`, then `npm link realm`.
6. Run tests with `npm run test:ts`.

### Version

Build from source

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS Ventura 13.4

### Build environment

Using Node.js v18.16.0.

**Comment by krollins-mdb** [comment]
After pairing with @takameyer and @kraenhansen, we determined that `npm run build:node` was not overwriting my locally-generated `realm.node` file. This resulted in an older version of realm being used.

After deleting the `realm.node` file and re-building, I can run tests successfully.

Still not sure why the compiler didn't throw any errors or overwrite the locally-generated `realm.node` file.

**Comment by kraenhansen** [comment]
@krollins-mdb still seeing this or should we close it and reopen if it appears again?
