### ISSUE TITLE
Migrate `integration-test/environment/react-native` to use `react-native-test-app`

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#5879]
To cut down complexity and time spent on upgrading the app on new releases of React Native and in light of the RFC on React Native Frameworks (proposing to deprecate the template app as we know it), we should consider migrating our test app to [react-native-test-app](https://github.com/microsoft/react-native-test-app/wiki/Migrate-an-Existing-Test-App). The MS team has been hard at work improving the DX.

See https://youtu.be/DAEnPV78rQc?t=860 with a demo of how to upgrade RN.

**Comment by tido64** [comment]
@kraenhansen, why would you need to migrate to Yarn to support this? Did you hit any issues with RNTA in your current setup?

Also, please feel free to reach out on Discord if you have questions.

**Comment by kelset** [comment]
small nit, we also had a live demo of upgrading a RNTA app on stage at RNEU'23 ;) you can check it out here ➡️ https://youtu.be/PYMMxfttOug?si=zDi3wGK-TDzvjrpO&t=462

**Comment by kraenhansen** [comment]
> why would you need to migrate to Yarn to support this?

@tido64 I don't think we do 👍
