### ISSUE TITLE
How can I force-recreate my DB everytime I change properties?

### ISSUE THREAD

**Issue by hybrisCole** [realm/realm-js#589]
Hello, 

So I have this model:

```
export default {
  name       : 'ExerciseSession',
  primaryKey : '_id',
  properties : {
    _id       : 'string',
    type      : 'string',
    enabled   : 'bool',
    exercises : {type : 'list', objectType : 'Exercise'},
  },
};
```

but then I change my mind and have it as

```
export default {
  name       : 'ExerciseSession',
  properties : {
    _id       : 'string',
    type      : 'number',
    inactive   : 'bool',
    exercises : {type : 'list', objectType : 'Exercise'},
  },
};
```

changed prop name and types, I stop my RN project and run again, but it will throw an error saying that types are not matching, unless I do `xcrun simctl erase all` I will keep receiving this same thing, which is correct heh, but, is there a way to say it to realm that everytime I run my project, to flush everything from scratch?

something like 

```
export default new Realm({
  schema : [Exercise, ExerciseSession],
   overwrite : true,
});
```

Maybe I got some misconceptions about this.

Regards,

**Comment by alazier** [comment]
There is no way to do this by passing in a configuration parameter, although this is something we can consider adding.

For now there is an undocumented method `Realm.clearTestState();` which deletes all realm files in the application's documents directory. This is used by the test harness but could change at sometime in the future.

**Comment by hybrisCole** [comment]
awesome, that's good enough for me, thanks!
