### ISSUE TITLE
Testing DB in multiple test suites results in exception

### ISSUE THREAD

**Issue by sharq1** [realm/realm-js#590]
Each test suite with db-related tests executed separately runs fine. But when I run them all the first one runs fine and every another throws this exception:
```
TypeError: Cannot redefine property: join
        at Function.defineProperties (native)

      at Object.<anonymous> (node_modules/realm/lib/index.js:41:8)
```

My `package.json`
```
  "jest": {
    "preset": "jest-react-native",
    "moduleNameMapper": {
      "\\./datepicker$": "<rootDir>/node_modules/tcomb-form-native/lib/templates/bootstrap/datepicker.ios.js"
    },
    "preprocessorIgnorePatterns": [
      "node_modules/(?!react-native|tcomb-form-native|apsl-react-native-button)"
    ],
    "testRegex": "(/__tests__/.*|\\.(test))\\.js$",
    "collectCoverage": true,
    "verbose": true
  },
...
    "jest": "15.1.1",
    "jest-cli": "15.1.1",
    "jest-react-native": "15.0.0",
    "realm": "git+https://git@github.com/realm/realm-js.git",
```

As a workaround I might alias `npm test` script to run files with db tests separately, but as I described in #521 Jest hangs after finishing any db tests :(

**Comment by fealebenpae** [comment]
Are you refreshing the modules cache between every suite? Jest used to do that implicitly before version 15.

**Comment by sharq1** [comment]
Already tried that - doesn't help.

**Comment by fealebenpae** [comment]
I would expect it to not work if you were resetting the modules cache. It looks like the Realm module is being re-evaluated in every test suite and that's a problem, because it's stateful due to the c++ code it loads.

**Comment by alazier** [comment]
I ran into this yesterday and have a fix in the works but need to make sure it doesn't break anything else.

**Comment by alexsotocx** [comment]
[Out Of Context]
Where can I get a guide how to test with jest and realm-js?

**Comment by sharq1** [comment]
Thanks guys!

**Comment by johannesschirrmeister** [comment]
@alazier I hope this is an acceptable place to leave this feedback, but I imagine this is a pretty huge issue for people and I wonder why the fix hasn't been released yet as a new minor version. 

In my understanding, this means one can't really run tests with the default react native setup when there is a fix for two months already. I feel bad to complain, but I feel like this would cause a lot of react native developers to give up on Realm before they really get started with it.
