### ISSUE TITLE
[Expo] Realm Errors are not propagated to console

### ISSUE THREAD

**Issue by haikov** [realm/realm-js#5903]
### How frequently does the bug occur?

Always

### Description

Hey!

I'm building an app with Expo and Realm, and one of the biggest issues I'm facing with realm is inability to understand what's going wrong in case of issues with schema, query (or anything else related to Realm), since Realm always throws the same error in console which gives no details. The error looks like that:

```
 ERROR  Error: Exception in HostFunction: <unknown>

This error is located at:
    in Unknown (created by App)
    in Provider (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (created by RootApp)
    in ReactNativeProfiler (created by RootApp)
    in RCTView (created by View)
    in View (created by __Sentry.TouchEventBoundary)
    in __Sentry.TouchEventBoundary (created by RootApp)
    in RootApp (created by withDevTools(RootApp))
    in withDevTools(RootApp)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

Is this something known or maybe I'm missing some configuration step to make the output cleaner? Or is there some better way to look up the detailed stack trace?

### Can you reproduce the bug?

Always

### Version

11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16

### Build environment

Expo SDK 48

**Comment by kraenhansen** [comment]
I tried but failed to reproduce this. I do see "Exception in HostFunction:", but I get a proper message.
Can you help reproduce this by sharing a minimal repository exhibiting this behaviour?

**Comment by haikov** [comment]
Tried reproducing it with an example repo, no luck, works as expected there. So it must be something with my project setup. I'm trying to dig into that a bit more and will report back as soon as I get anything. But one more thing which I see when Realm emits an error is this weird log:

```
Error: ENOENT: no such file or directory, open '/Users/path/to/project/folder/JavaScript'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/path/to/project/folder/node_modules/metro/src/Server.js:1004:18)
    at Server._symbolicate (/Users/path/to/project/folder/node_modules/metro/src/Server.js:1073:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._processRequest (/Users/path/to/project/folder/node_modules/metro/src/Server.js:437:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/path/to/project/folder/JavaScript'
}
```

Maybe it rings some bell for you?

**Comment by haikov** [comment]
After installing the same packages from my app to the sample Expo+Realm app I've found that installing `@shopify/react-native-skia` causes the issue. You can reproduce it by simply adding `@shopify/react-native-skia` package to `@realm/expo-template` and then making Relm to crash (for example by removing required property when saving something).

Any ideas if this is something on Realm or RN Skia side?

**Comment by haikov** [comment]
Couldn't run a project successfully with that realm version due to `Unable to resolve "bson" from "node_modules/realm/dist/bundle.react-native.mjs"`

**Comment by kneth** [comment]
@haikov I believe the `Unable to resolve "bson"` issue has been solved in one of our v12 release candidates.

**Comment by elle-j** [comment]
@haikov, to add to what @kneth was saying, for your issue with bson, see [#5791](https://github.com/realm/realm-js/issues/5791) which mentions a temporary solution. When [#5943](https://github.com/realm/realm-js/pull/5943) has been merged and released, we believe the issue will be solved.

**Comment by takameyer** [comment]
I have tested the latest release candidate with Expo 48 and `@shopify/react-native-skia` installed on both iOS and Android.  Everything seems to be working fine.
@haikov have you had a chance to test this again?

**Comment by haikov** [comment]
I can also confirm it is now working fine for those versions. Thank you for looking into that! 🙌
