### ISSUE TITLE
Throw a meaningful error when imported from the Expo Go App

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#5905]
When `realm` is imported from the Expo Go app, our native module isn't linked and the following error will be thrown:

<img width="470" alt="Screenshot 2023-06-19 at 09 51 30" src="https://github.com/realm/realm-js/assets/1243959/a620aea8-27ca-4c45-85ad-5b57d4462a31">

```
Cannot read property 'Helpers_get_table' of undefined.
```

The SDK should instead  and throw an error with more information and steps to resolve the issue when loaded into the Expo Go app.

1. Assert the result of loading the native module.
2. Detect that we're running in the Expo Go app or throw a more generic error.
3. Ask uses to follow https://www.mongodb.com/docs/realm/sdk/react-native/bootstrap-with-expo/ and ultimately run `npx expo run:ios` or `npx expo run:android` (etc.)

**Comment by kraenhansen** [comment]
@johnludena this happens when you load `realm` into an app running in the Expo Go App. Because this app only loads the JS code for imported packages, "our native module isn't linked". This is because the `pod install` command hasn't been ran and the XCode / Android project knows nothing about the native part of the `realm` package.

You need to produce a "development build" of your Expo app.
Please see https://docs.expo.dev/develop/development-builds/introduction/ for more information on what that is and how to do just that 👍

**Comment by johnludena** [comment]
@kraenhansen THANK. YOU!

HYOOGE help, been at this for days!!!

Understanding a bit better the difference between the "normal" Expo build and the "development" build that can support pretty much any dependency did the trick for me (please correct if my understanding is wrong here, still very much a newbie in the mobile world).

For anybody that might find this helpful: All it took for me in the end was basically run an `npm run ios` command that would create an `ios` folder, install the Cocoa dependencies, and finally open in the Simulator without issues from the new `ios` folder code (somebody please correct me if I'm wrong in my understanding here, still very new to mobile development). I did that from a clean project from running `npx create-expo-app my-app` command. 

Thanks again! 🙏🏻

PS: Github effing rocks. 🤘
