### ISSUE TITLE
Default value of empty array not applied to Atlas documents during object creation

### ISSUE THREAD

**Issue by onetrace-abdullah** [realm/realm-js#5907]
### How frequently does the bug occur?

Always

### Description

When using Realm with Flexible Syncing and creating objects based on a given schema, the default value of an empty array is not being applied to the property during object creation. This issue results in the property being omitted in the documents in Atlas.

If the default is set to an array with values in it, both the property and value are present in Atlas.

For example, in the following schema I've set the default value for `number_array` to be an empty array, but Atlas never receives the empty array:

<table>
<tr>
<td> Code </td> <td> Atlas </td>
</tr>
<tr>
<td>
    
```typescript
export const TestSchema = {
  name: 'Test',
  properties: {
    _id: { type: 'objectId' },
    number_array: { type: 'int[]', default: [] }, // <---
  },
  primaryKey: '_id',
}


realm.write(() => {
  realm.create(TestSchema.name, {
    _id: new Realm.BSON.ObjectID(),
  })
})
```

</td>
<td> 
<img src="https://github.com/realm/realm-js/assets/117074905/50d96d80-52cf-4037-a3c3-9893aad51037" />
 </td>
</tr>

</table>

But when the schema definition is updated to default `number_array` to be `[1, 2, 3]` it does have the correct value:

<table>
<tr>
<td> Code </td> <td> Atlas </td>
</tr>
<tr>
<td>
    
```typescript
export const TestSchema = {
    // ...
    number_array: { type: 'int[]', default: [1, 2 ,3] },
   // ...
}
```

</td>
<td> <img src="https://github.com/realm/realm-js/assets/117074905/83ed8d13-1362-43ba-863b-4569a3d09d8a" /> </td>
</tr>

</table>

The issue also happens when I' not using default values and explicitly set the empty array when creating a new object:

```typescript
realm.write(() => {
  realm.create<Test>(TestSchema.name, {
    _id: new Realm.BSON.ObjectID(),
    number_array: [], // <---
  })
})
```

### Can you reproduce the bug?

Always

### Reproduction Steps

I've created a gist with the code I've used to test the app [here](https://gist.github.com/onetrace-abdullah/1d509f5c797d913400a6019e5f810ef5)

1. Create an Atlas app service
2. Enable anonymous authentication
3. Create a schema called "Test" defined as follows:
```
{
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "number_array": {
      "bsonType": "array",
      "items": {
        "bsonType": "int"
      }
    }
  },
  "required": [
    "_id"
  ]
}
```
4. Enable Flexible Device Sycning
5. Create a Realm app:
```
// 1. Create App
// 2. Login as Anonymous user
// 3. Configure syncing

export type Test = {
  _id: Realm.BSON.ObjectId
  number_array: Realm.List<number>
}

export const TestSchema: Schema<Test> = {
  name: 'Test',
  properties: {
    _id: { type: 'objectId' },
    number_array: { type: 'int[]', default: [] },
  },
  primaryKey: '_id',
}

const create = () => {
  realm.write(() => {
    realm.create<Test>(TestSchema.name, {
      _id: new Realm.BSON.ObjectID(),
    })
  })
}
```

### Version

11.4.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

MacOS 13.4

### Cocoapods version

1.12.1

**Comment by kraenhansen** [comment]
I reproduced the issue and from my investigations, this happens even when you explicitly pass the empty array through the 2nd argument to `realm.create`. I tried making the items required in the server-side schema, but that results in a protocol error when initialising sync:

```
{"category": "realm::sync::ProtocolError", "code": 225, "isFatal": true, "message": "Invalid schema change (UPLOAD): failed to add app schema for ns='mongodb.test-db.Test' for new top-level schema \"Test\": sync-incompatible app schema for the same collection already exists. This app schema is incompatible with error: \"array property \\\"items\\\" must be optional to be sync-compatible\". To continue, delete the app schema in Atlas App Services, or update it to match the app schema defined on the device Logs: ...", "name": "Error", "userInfo": {}}
```

I've raised this with the server team through an internal channel and I'll report back as I learn more.

**Comment by kraenhansen** [comment]
The answer I got is that our core database doesn't distinguish between an empty list and the list missing entirely, therefor sync assumes the latter when the changeset is uploaded to the server. I personally feel this is very unfortunate, I can see reasons you'd want an empty list in the resulting document. I'll keep this issue open for further reference, but I don't expect this to be solved anytime soon as it'll require pretty deep changes to our core database library and sync protocol.

**Comment by onetrace-abdullah** [comment]
@kraenhansen are there any other suggestions perhaps on how we can overcome this without using triggers?

**Comment by kraenhansen** [comment]
@onetrace-abdullah I haven't verified this myself, but one of my colleagues suggested creating the object with an item and removing it right after. That should touch the array enough that the instructions are sent to the server via the sync protocol. Not at all an ideal solution, but it might be "good enough" for now?

**Comment by onetrace-abdullah** [comment]
That's a good suggestion if it works! However in our use case we have a schema with multiple arrays each having complex objects in them so it's not a viable solution unfortunately

**Comment by nirinchev** [comment]
Closing this as it's a server-side bug.
