### ISSUE TITLE
Provided schema version 5 is less than last set version 3

### ISSUE THREAD

**Issue by avishayil** [realm/realm-js#591]
Happened on test device, on Android.
Ideas?

**Comment by alazier** [comment]
Can you give any more information? Sounds like you tried to perform a migration? If this is a test device you could simply delete the app to get around the issue.

**Comment by avishayil** [comment]
I didn't try to perform a migration. First time app ran was fine, second
time I received this error. Never happened before. It was a test device, on
a release build before deployment. Now deployment is delayed because I'm
afraid it would return in production.

**Comment by alazier** [comment]
Sorry to hear about the delay. How are you setting the `schemaVersion` parameter passed into `new Realm`? If you are doing this programmatically you would see this error if passing in a value lower than a previous value.

**Comment by avishayil** [comment]
How exactly version 5 can be lower than 3

**Comment by alazier** [comment]
I think the error message is incorrect - it has the old version and new versions swapped in the message.

**Comment by alazier** [comment]
Were you able to figure everything out and get your product released?

**Comment by alazier** [comment]
Is there anything else we can do here other than fix the error message? If not I will close this.

**Comment by avishayil** [comment]
You can close this, thanks!

**Comment by MrHubble** [comment]
@avishayil do you mind sharing how you were able to solve the problem?

**Comment by crisari666** [comment]
Is great close issues without resolve

**Comment by bmunkholm** [comment]
@crisari666 If you have a problem, please create a new issue. Thanks!
