### ISSUE TITLE
Specify namespace in Gradle build files

### ISSUE THREAD

**Issue by kneth** [realm/realm-js#5925]
https://github.com/react-native-community/discussions-and-proposals/issues/671 outlines an upcoming change (to land in RN 0.73) to the Gradle build files.

**Comment by takameyer** [comment]
@kneth I have a [PR](https://github.com/realm/realm-js/pull/5861) for this, but for some reason in v11 the tests weren't passing with this change.  Quite sure this is already in v12 though.  If we don't need it for v11 then we could probably close this

**Comment by kneth** [comment]
@takameyer Let's close it for v11.
