### ISSUE TITLE
UpdateMode doesn't get passed recursively when creating child objects in realm v12

### ISSUE THREAD

**Issue by chvllad** [realm/realm-js#5933]
### How frequently does the bug occur?

Always

### Description

Realm v12.0.0-alpha.2 always use `UpdateMode.Never` for children objects ignoring mode arg in create function:

https://github.com/realm/realm-js/blob/d357fafbd53f8a57b3a00a34b2db7d98b38b09a4/packages/realm/src/TypeHelpers.ts#L231-L238

### Can you reproduce the bug?

Always

### Reproduction Steps

Code:
```js
import Realm, { UpdateMode } from "realm";

const ASchema = {
  name: "A",
  primaryKey: "id",
  properties: {
    id: "int",
  },
};

const BSchema = {
  name: "B",
  properties: {
    a: "A[]",
  },
};

const realm = new Realm({
  schema: [ASchema, BSchema],
  schemaVersion: 0,
  inMemory: true,
  path: "temp_db",
});

realm.write(() => {
  realm.create("A", {
    id: 1,
  });
  realm.create("B", {
    a: [{ id: 1 }],
  }, UpdateMode.All);
});
```

### Expected
Successful creation

### Actual
`Error: Attempting to create an object of type 'A' with an existing primary key value '1'., js engine: hermes`

### Version

12.0.0-alpha.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

React-native; Android, IOS

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Thanks for reporting this! I'll put it top of the backlog.
