### ISSUE TITLE
Missing Realm Constructor

### ISSUE THREAD

**Issue by codehob** [realm/realm-js#595]
"firebase": "^3.2.1",
    "fs": "0.0.2",
    "react": "~15.2.0",
    "react-native": "0.28.0",
    "react-native-navbar": "^1.5.0",
    "react-native-simple-router": "0.11.1",
    "react-realm": "0.4.1",
    "realm": "^0.14.3"

Getting missing realm constructor error with red screen on react-native ios

**Comment by alazier** [comment]
Did you run `react-native link realm` after `npm install`?

**Comment by Dallas187** [comment]
@codehob are you using the Visual Studio Code IDE?

**Comment by Crash--** [comment]
I got the same error using Visual Studio Code. If I run the app manually with react-native run-ios I have no problem.

**Comment by Dallas187** [comment]
I'm also using VS Code, this seems to be affecting a lot of people - might wanna subscribe to this one... [#198](https://github.com/Microsoft/vscode-react-native/issues/198)

**Comment by alazier** [comment]
@Dallas187 @Crash-- We are tracking the VSCode issue here #583 

@codehob hope you were able to figure this out - I suspect the issue was with the switch from rnpm, so running `react-native link realm` should hopefully fix your issue. If it doesn't feel free to open another issue.
