### ISSUE TITLE
React Native New Arch without hermes, android can't find Realm constructor.

### ISSUE THREAD

**Issue by allen-hsu** [realm/realm-js#5969]
### How frequently does the bug occur?

Always

### Description

As title.

My React Native Version is 0.72, and I try to enable new Arch flag, but I want to disable hermes enginge.
Bug Realm will report `Missing Realm constructor` issue

### Can you reproduce the bug?

Always

### Version

11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 

### Build environment

Which debugger for React Native: ..

**Comment by allen-hsu** [comment]
even I enable hermes, still get this issue

**Comment by takameyer** [comment]
Hi @allen-hsu.  We are currently working hard on `realm@12.0.0` which will work fine with the new architecture, with our without Hermes (I just tested this today).  If you want to try it out, you can `npm install realm@next --force`.  It is mostly stable at this point, with a few little things we need to iron out.  That being said, don't hesitate to open an issue for anything bugs you find or features you are interested in us developing!

Closing as we will not be implementing this in v11
