### ISSUE TITLE
Realm still crashes with Reanimated

### ISSUE THREAD

**Issue by zubair999** [realm/realm-js#5982]
### How frequently does the bug occur?

Always

### Description

I am building an app which uses react navigation drawer which in turn uses reanimated but app crashes as soon as I install realm with reanimated. When I uninstall realm app work normally.

### Can you reproduce the bug?

-- select --

### Version

12.0.0-alpha.2

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

android

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@zubair999 Thank you for reporting. We have recently released v12.0.0-rc.1, and I ask you if you can try to upgrade and report back?

Moreover, it will be useful for us to know the versions of reanimated and React Native in order to help.

**Comment by Abdelalim-dev** [comment]
@kneth I have faced the same issue with the following versions:
React Native: **0.70.12** 
Reanimated: **3.3.0**

PS: I had to install **RealmJS 11.3.1** because that's the latest version compatible with **RN 70**.
Upgrading to **v12.0.0-rc.1** means that I have to upgrade React Native as well.

**Comment by kneth** [comment]
Please check the [compatibility matrix](https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md)
