### ISSUE TITLE
Is there a way to run Realm-Cocoa and Realm-JS same time

### ISSUE THREAD

**Issue by jniemin** [realm/realm-js#599]
I couldn't find a way to run both react native (realm-js) and iOS version of the realm at the same time. Is this even possible currently? Use case for me is, that I like to store most of my data realms created in realm-js but I have one data set that is really big (over 40megs of json) and handling of that sized data is really slow and eats lots of memory on JavaScriptCore. So I would like to download and store to realm that on native side and then offer a custom native module to do simple queries to realm. This realm would be physically different file than the realms created on React Native Realm.

**Comment by alazier** [comment]
This should work as long as both bindings use the same data schema. The default Realm path should be the same for both bindings. Some features like notifications may not work across bindings but writing to and querying the same Realm should work.

**Comment by jniemin** [comment]
I got finally working. I think it needs to use same realm-core version to actually work. Also I had problems if I used CocoaPods or statically linked version. Now using realm-js from master and realm-cocoa 1.1.0 (dynamically linked) which both uses core 1.5.0.

**Comment by alazier** [comment]
Glad you were able to get this working!
