### ISSUE TITLE
Array containing empty objects being returned when querying list of subscriptions

### ISSUE THREAD

**Issue by njmulsqb** [realm/realm-js#5996]
### How frequently does the bug occur?

Always

### Description

Hi,
I am using realm 11.8.0 and @realm/react 0.4.3 in react native expo app, when I try to console.log list of subscriptions using 
```
  const allSubscriptions = realm.subscriptions;
console.log(allSubscriptions

// returns {"0": {}, "1": {}, "2": {}, "3": {}}
```

I cant see any further details of the subscriptions, even if I add any more subscriptions it will also show up as empty object in this array

### Can you reproduce the bug?

Always

### Reproduction Steps

Just list the subscriptions

### Version

11.8.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

React Native Expo 48.0.0

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@njmulsqb In v11 the subscriptions are c++ objects and it appears the enumeration wasn't implemented (which would just output an empty object in console).  This should be enumerated and visible in v12.  If you want to try it out, you can use the latest release candidate (`npm install realm@next`)

**Comment by njmulsqb** [comment]
I am using it on Node 18.0.0, with npm version 9.6.6, I tried updating the realm using `npm update realm` but it didnt update the package.json file. Could this be an issue?

**Comment by kneth** [comment]
@njmulsqb You can try to remove `package-lock.json` and do `npm install realm@12.0.0-rc.3`.

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
