### ISSUE TITLE
Question about scalability

### ISSUE THREAD

**Issue by anton-aleksandrov** [realm/realm-js#600]
If i've understood it correctly, recursive retrieval of each one single property is the only way to retrieve plain object from realm: https://github.com/realm/realm-js/issues/323

I've just tried this and it appears to be very slow. About 4.5 seconds (!) to retrieve 5 objects with 40 numeric props each. Is it really that's slow or i'm doing something wrong?

If this is my fault and there is a way to retrieve data faster than 300ms, then another question: how do i import ~9000 objects (1000 letters each) in the database? I haven't found import guidance in docs, and it looks like i can't access database outside the app's code. And app (iPhone 6+ simulator) is not able to handle 6.5mb `.json`  file.

Thank you!

**Comment by alazier** [comment]
Are you running in chrome debug mode? That would slow things down considerably (orders of magnitude). We have plans to speed things up in that department but have not had the time to make it happen yet.

**Comment by alazier** [comment]
Hope that running in debug mode was the root of your issue. If not feel free to re-open.
