### ISSUE TITLE
How to use `writeCopyTo` with react query `RealmProvider`

### ISSUE THREAD

**Issue by saravanakumargn** [realm/realm-js#6000]
### How frequently does the bug occur?

Always

### Description

How to use `writeCopyTo` with react query `RealmProvider`? when I use react query hot i can open Realm and copy from local to sync?

```
 <AppProvider id={'app-qa-sbapv'}>
        <UserProvider fallback={<AppWelcome />}>
          <RealmProvider schema={schemas}
            sync={{
              flexible                  : true,
              existingRealmFileBehavior : {
                type    : OpenRealmBehaviorType.DownloadBeforeOpen,
                timeOut : 1000,
                timeOutBehavior :
                  // In v11 the enums are not set up correctly, so we need to use the string values
                  OpenRealmTimeOutBehavior?.OpenLocalRealm ?? 'openLocalRealm',
              },
              onError: (_session, error) => {
                console.log('onError: ',error);
              },
            }}
            >
            <App />
</AppProvider>
```

### Can you reproduce the bug?

Always

### Version

@realm/react 0.5.1, "realm": "^11.10.1",

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

"realm": "^11.10.1",

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
Hi @saravanakumargn and thanks for reporting. The `RealmProvider` can't do this.  What I would recommend is to initiate this yourself before the `RealmProvider` is rendered.  

Here would be an example of [copying a bundled Realm](https://www.mongodb.com/docs/realm/sdk/node/realm-files/bundle/#create-a-realm-file-for-bundling):
```tsx
// Import a shared configuration that will also be used in your `RealmProvider`
import Realm from "realm";
import {localConfig, syncConfig} from "./myRealmConfig";

export function RealmMigrator(props){
  const user = useUser();
  useEffect( () => {
    // load some sort of logic to determine if you need to do this
    if(!migratedToSync){
	  const originalRealm = await Realm.open(localConfig); 
	  // The `RealmProvider` derives `user` from the `UserProvider`, so we need
      // to add it ourselves here.
	  originalRealm.writeCopyTo({...syncConfig, user});
    }
  }, [user]);
  
  return props.children;
};
```

Then the wrapper would be:
```tsx
import {localConfig, syncConfig} from "./myRealmConfig";
import {RealmMigrator} from "./RealmMigrator";

function App(){
  return(
   <AppProvider id={'app-qa-sbapv'}>
        <UserProvider fallback={<AppWelcome />}>
          <RealmMigrator>
	        <RealmProvider {...syncConfig}>
	          <App />
	        </RealmProvider>
          </RealmMigrator>
        </UserProvider>
	</AppProvider>
	);
};

```

Let us know if this helps!

**Comment by takameyer** [comment]
@saravanakumargn Have you enabled flexible sync in your Atlas dashboard?  Should look something like this:
![image](https://github.com/realm/realm-js/assets/164606/3b59656d-adf7-4c45-94c1-df4eeb090b30)

**Comment by saravanakumargn** [comment]
Yes, I did that already and the schema also synced. Pls, check the screenshot `Latest Sync Event 10 sec ago`. But I am getting this error on writeCopyTo. without this local sync, I am able to save the data and view the collections in the atlas.


![Screenshot 2023-07-19 at 2 59 11 PM](https://github.com/realm/realm-js/assets/1115851/d389a9be-be47-4279-89aa-95a2a7357ed8)

**Comment by takameyer** [comment]
@saravanakumargn I apologize, but I believe my example is incorrect:
```
// Import a shared configuration that will also be used in your `RealmProvider`
import Realm from "realm";
import {localConfig, syncConfig} from "./myRealmConfig";

export function RealmMigrator(props){
  const user = useUser();
  useEffect( () => {
    // load some sort of logic to determine if you need to do this
    if(!migratedToSync){
	  const syncedRealm = await Realm.open({...syncConfig, user}); 
	  // The `RealmProvider` derives `user` from the `UserProvider`, so we need
      // to add it ourselves here.
	  syncedRealm.writeCopyTo(localConfig);
    }
  }, [user]);
  
  return props.children;
};
```

The `writeCopyTo` writes the passed in Realm into the open Realm.

**Comment by saravanakumargn** [comment]
@takameyer Thanks for looking at this.
I think no issue with your previous code. This should work as per https://www.mongodb.com/docs/realm/sdk/react-native/sync-data/partition-based-sync/#copy-data-and-open-a-new-realm

The use case is anytime I can convert local to sync and sync to local vice-versa. So, the first time when I open the app it's non sync(local). after some time(if premium users i need to copy local to sync and continue the app)

**Comment by saravanakumargn** [comment]
Thanks for your help & support in this issue @takameyer. Let me check how to do this.

**Comment by saravanakumargn** [comment]
As this is expected I am closing this ticket.

**Comment by saravanakumargn** [comment]
@takameyer are you talking about this issue? https://github.com/realm/realm-core/issues/5798
Do you have any about this feature roadmap?

**Comment by takameyer** [comment]
@saravanakumargn That issue was referring to making the error a bit more helpful.  The project is on our roadmap for the year, but there's nothing publicly posted at the moment.  Sorry I can't provide any further information.

**Comment by devsales** [comment]
Nevermind, I figured it out :) I just had to skip the exporting of the data to Atlas and instead after switching to the sync realm, open the local Realm and save the local data to the sync realm... and of course close the local Realm afterwards.

```JavaScript
  <AppProvider>
    <UserProvider>
      <RealmProvider sync={flexSyncConfig}>
        <App />
      </RealmProvider>
    </UserProvider>
  </AppProvider>
```
And in `<App />` I have a `useEffect` hook that does something like this:
```JavaScript
if (shouldMigrate) {
  const localRealm = await Realm.open(localRealmConfig);
  const arr = localRealm.objects("SomeType");

  realm.write(() => {
    arr.forEach(obj => {
      realm.create("SomeType", obj)
    })
  })
}
```
As @takameyer mentioned earlier, It's important to call `realm.write()` after the sync RealmProvider has been initialised with the subscriptions. I hope that helps someone...
