### ISSUE TITLE
Fetch never resolved the response

### ISSUE THREAD

**Issue by SipNWork** [realm/realm-js#6001]
### How frequently does the bug occur?

Always

### Description

`const reply = await new DefaultNetworkTransport().fetch(request)`

File - mongo-client.js , line no - 216
relative path - node_modules/realm/lib/mongo-client.js

Fetch never resolves any response. I checked the logs in mongodb console and request was successful.

Configurations
"react": "18.2.0",
"react-native": "0.71.8",
"realm": "11.9.0",

### Can you reproduce the bug?

Always

### Version

11.9.0

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

MAC os

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@SipNWork What specifically in your application code invokes this issue?  
Can you try the latest release candidate for `realm@12.0.0`.  Can you try this and see if the error still persists?
`npm install realm@next`

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
