### ISSUE TITLE
Device Sync with roles that depend on user custom data is not triggered immediately

### ISSUE THREAD

**Issue by aureosouza** [realm/realm-js#6002]
### How frequently does the bug occur?
Always

### Description
We have a Role for a collection Place that depends on user custom data, so something similar to:

```json
{
  "roles": [
    {
      "name": "cityAccessRule",
      "apply_when": {},
      "document_filters": {
        "write": {
          "city": {
            "$in": "%%user.custom_data.cities"
          }
        },
        "read": {
          "city": {
            "$in": "%%user.custom_data.cities"
          }
        }
      },
      "read": true,
      "write": true,
      "insert": true,
      "delete": true,
      "search": true
    }
  ]
}
```

We are updating the custom user data collection in a React Native app and calling refresh as [doc](https://www.mongodb.com/docs/realm/sdk/react-native/manage-users/custom-user-data/#std-label-react-native-access-custom-user-data):

```javascript
      realm.write(() => {
        customUserData.cities = cities;
      });
      await user.refreshCustomData()
```

As soon as the user custom data is updated, we would expect to sync down the documents in the collection Place that passes successfully the role. But this is not the case, user needs to to kill the app and open again to trigger a new sync and see the expected Place documents.

All data seems correct on the server side (Dedicated M10) for the CustomUserData collection and UserSettings in AppSettings has correct configs for userId and Creation Function is working correctly. As well the connection between userId (CustomUserData collection) and the user.Id (User collection from Atlas) seems correct, as it is fetching correctly the expected documents, but only after the user restarts the app.

We performed some tests and issue seems to be connected with the user custom data update across the Mongo Atlas environment. Because if we use a static value for the Role comparison the sync is immediate as soon as the condition passes. But if it depends on a value from custom user data, then the sync it's not immediate.

### Can you reproduce the bug?
Always

### Version
11.9.0

### What services are you using?
Atlas Device Sync

### Platform OS and version(s)
iOS 16.4

**Comment by takameyer** [comment]
I did notice this:
```tsx
      realm.write(() => {
        customUserData.cities = cities;
      });
```
You won't be able to update the custom user data in this fashion.  If you want to update this from the application you will have to use the mongo db client:
https://www.mongodb.com/docs/realm/sdk/react-native/manage-users/custom-user-data/#write-custom-user-data

**Comment by aureosouza** [comment]
Thanks for the response @takameyer, I am able to write to customUserData in that way, I see the data in server. The issue is that the sync is not restarting. And I believe it should, if custom user data is used as a sync role in App Rules. We were able as a workaround to restart the sync using `pause` then `start` on the sync session as below. But I still believe this is not an optimal solution, and sync should be triggered automatically: 

```
realm.write(() => {
        customUserData.cities = cities;
      });

await user.refreshCustomData();
realm.syncSession.pause();
realm.syncSession.resume();
```

**Comment by takameyer** [comment]
@aureosouza Can you provide a few more details into what `customUserData` is in your example?

**Comment by aureosouza** [comment]
@takameyer sure, so this is the schema of our CustomUserData collection:

```json
{
  "title": "CustomUserData",
  "type": "object",
  "required": [
    "_id",
    "userId"
  ],
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "cities": {
      "bsonType": "array",
      "items": {
        "bsonType": "string"
      }
    },
    "userId": {
      "bsonType": "string"
    }
  }
}
```

On Atlas -> Users -> UserSettings -> Custom User Data we have the following:

![user_settings](https://github.com/realm/realm-js/assets/71460422/d7a597f4-7947-4a18-996d-d287afaabc58)

onUserCreation Function:

```js
exports = async function onUserCreation(user) {
  const customUserDataCollection = context.services
    .get("mongodb-atlas")
    .db("MY_DATABASE_NAME")
    .collection("CustomUserData");
  try {
    await customUserDataCollection.insertOne({
      // Save the user's account ID to your configured user_id_field
      userId: user.id,
      cities: [],
    });
  } catch (e) {
    console.error(`Failed to create custom user data document for user:${user.id}`);
    throw e
  }
}
```

More info:

- CustomUserData collection is correctly updated when we change `cities` param of a document.
- The relationship between Atlas User id and the userId in the CustomUserData collection seems correct, as the response of `await user.refreshCustomData();` has value correctly updated.

If we kill and restart app (or pause and start sync session), everything is working correctly. The issue here is that Device Sync does not trigger a new sync automatically and we believe it should if the custom user data changed and is a sync condition on a role under App Service -> Rules.

**Comment by takameyer** [comment]
@aureosouza I have just discussed this with the device sync team.  The Sync permissions are only evaluated at the beginning of a sync session, so the method you are currently doing to reset the session is the recommended path.
The other way to get around this would be to use the flexible sync subscription query to filter the data (for example, by user city).  This could be applied dynamically and would be correctly re-render.  Would that be a possible solution?

**Comment by aureosouza** [comment]
@takameyer  Yes the `pause` are `start` are working as workaround for this case, but maybe the auto sync should be priortized, when custom user data, that is used in roles, are updated. But there is another scenario in which the pause + start does not help, only killing and restarting app that we noticed now. I'll try to provide replication steps:

1) Login anonymously
```js
const credentials = Realm.Credentials.anonymous();
await app.logIn(credentials);
```
2) Register a new user, will be send confirmation email:
```js
await app.emailPasswordAuth.registerUser(
  {
    email,
    password,
  },
);
```

3) Confirm user with email and login with new user
```js
await app.emailPasswordAuth.confirmUser({
  token,
  tokenId,
});
const credentials = Realm.Credentials.emailPassword(
  email,
  password,
);
await app.logIn(credentials);
```
4) The CustomUserData subscriptions does not work, currentCustomUserData is `undefined`, restarting app fixes sync.
```js
const customUserQuery = useQuery(CustomUserData);
const user = useUser();

useEffect(() => {
  realm.subscriptions.update(mutableSubs => {
    mutableSubs.add(realm.objects(CustomUserData));
  });
}, [realm]);

const currentCustomUserData: CustomUserData = useMemo(() => {
  if (user?.id) {
    const currentUser = customUserQuery.filtered(`userId == '${user.id}'`);
    return currentUser?.[0];
  }
}, [customUserQuery, user.id])

console.log('currentCustomUserData', currentCustomUserData?.cities) // Is undefined, restarting app necessary
```

We noticed that user.id is correctly update with new user id, but the customUserQuery does not return the document. We confirmed on backend side and the value for this userId is on server, so issue only with sync. Do you have any workaround to restart the collection subscription? We tried remove + add:

```js
realm.subscriptions.update(mutableSubs => {
  mutableSubs.remove(realm.objects(CustomUserData));
  mutableSubs.add(realm.objects(CustomUserData));
});
```

But we get unhandled promise rejection:

```json
{
  "errorCode": "OperationAborted",
  "message": "Sync session became inactive",
}
```

**Comment by aureosouza** [comment]
@takameyer Tried upgrading to latest version `v12.0.0-rc.3` and the scenario is a bit worse, because now restarting the app simply freezes and returns: `Error: Server permissions for this file ident have changed since the last time it was used`

So reproduction steps are:


1) Login anonymously
```js
const credentials = Realm.Credentials.anonymous();
await app.logIn(credentials);
```
2) Register a new user, will be send confirmation email:
```js
await app.emailPasswordAuth.registerUser(
  {
    email,
    password,
  },
);
```

3) Confirm user with email and login with new user
```js
await app.emailPasswordAuth.confirmUser({
  token,
  tokenId,
});
const credentials = Realm.Credentials.emailPassword(
  email,
  password,
);
await app.logIn(credentials);
```
4) Try a simple upsert:

```js
realm.write(() => {
  realm.create('MyCollection', userObject, UpdateMode.Modified);
}); // Getting error: Cannot access realm that has been closed.
```

Tried as well:

```js
const collection =  user
    .mongoClient('mongodb-atlas')
    .db(DATABASE_NAME)
    .collection('MyCollection');
await collection.updateOne(
  { userId: user.id },
  { $set: documentObj },
  { upsert: true },
); // Getting error: updateOne service_name: mongodb-atlas -> 400 ERROR: insert not permitted
```

Reminder that all of these scenarios appear when we add the Rule to MyCollection below in MongoAtlas. If we change to read/write all everything works. So this seems to be an issue with the sync session refresh on new user login with rules.

```json
{
  "roles": [
    {
      "name": "userAccessRule",
      "apply_when": {},
      "document_filters": {
        "write": {
          "userId": "%%user.custom_data.userId"
        },
        "read": {
          "userId": "%%user.custom_data.userId"
        },
      },
      "read": true,
      "write": true,
      "insert": true,
      "delete": true,
      "search": true
    }
  ]
}
```

**Comment by qaws5503** [comment]
It seems that I encounter this issue with web SDK as well(I'm using Next.js). When I call `refreshCustomData()` the custom data will refresh, I can't fetch any data through app service since my role is associate with the custom data property. I can't find any sync session pause method in web SDK, the only solution is to hard reload the page. Then the data can be fetch now.
Any solution?

**Comment by aureosouza** [comment]
Can be closed as `pause` and `resume` functions are no longer necessary on version 12.6.0, was solved under this issue https://github.com/realm/realm-js/issues/6277
