### ISSUE TITLE
Error: Exception in HostFunction: Cannot set the logger factory after creating the sync client

### ISSUE THREAD

**Issue by mednche** [realm/realm-js#6005]
### How frequently does the bug occur?

Always

### Description

I cannot seem to be able to use `Realm.App.Sync.setLogLevel()` or `Realm.App.Sync.setLogger()` in my react native app.

If I place `Realm.App.Sync.setLogger()` BEFORE `const app = new Realm.App(appConfig);` I get:
"Error: Exception in HostFunction: app must be of type 'object', got (undefined)". This makes sense to me, as `app` has not be defined yet.

If I place it straight AFTER `const app = new Realm.App(appConfig);`, I get:
"Error: Exception in HostFunction: Cannot set the logger factory after creating the sync client". Why am I getting this?

### Can you reproduce the bug?

Always

### Reproduction Steps

```
const appConfig = {
    id: appId,
    timeout: 10000,
    app: {
      name: "default",
      version: "0",
    },
  };

Realm.App.Sync.setLogLevel(app, "debug"); // "all", "debug", "error", "info", "trace"
Realm.App.Sync.setLogger(app, (level, message) => console.log(`[${level}] ${message}`));

const app = new Realm.App(appConfig);

// I've also tried to place it here instead
// Realm.App.Sync.setLogLevel(app, "debug"); // "all", "debug", "error", "info", "trace"
// Realm.App.Sync.setLogger(app, (level, message) => console.log(`[${level}] ${message}`));
```

### Version

realm@11.9.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

NA

### Build environment

Which debugger for React Native: ..

**Comment by mednche** [comment]
> The second example of setting the logger is the correct way. What version of Realm are you using?

I'm using realm@11.9.0. When I use the second example of setting the logger, I get "Error: Exception in HostFunction: Cannot set the logger factory after creating the sync client". Any idea what tends to cause this error?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
