### ISSUE TITLE
Close or Kill a realm sync process for a synced realm

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-js#6006]
### How frequently does the bug occur?

Always

### Description

Realm process does not exit when I am closing realm only in case of synced realm. My main issue is I am using Synced Realm with Electron and when I close the electron application, it keeps running in background (doesn't get killed, the synced realm process keeps running)

I tried opening a non synced realm and the process was exiting gracefully.

Is there a way to kill the realm sync process?

### Can you reproduce the bug?

Always

### Version

11.10.1

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Node 18.x.x

**Comment by takameyer** [comment]
@gauravbordoloi Thanks for submitting this issue.  Are you closing the realm when the app is closed?

**Comment by gauravbordoloi** [comment]
@takameyer yes i am closing the instances. 
In fact the exact code works fine with non synced realm whereas the synced realm is only creating this issue

**Comment by gauravbordoloi** [comment]
@takameyer Maybe this is fixed in 12.0.0-rc01 as mentioned in release docs.
Can you please confirm?

![image](https://github.com/realm/realm-js/assets/23193185/6a54f3b9-06ee-446d-aed0-25799806b5aa)

**Comment by takameyer** [comment]
@gauravbordoloi It's possible, but I can't confirm 100% of this solves the issue or not. You can try using the current Release Candidate with `npm install realm@next`.  At the moment, it is very stable, so any feedback would be great.

**Comment by gauravbordoloi** [comment]
Hi @takameyer 
I tried using the current release candidate but I am facing the below issue. Do you have a quick fix for this?

```
Error: Cannot find module '../generated/ts/realm.node'
Require stack:
- A:\homedrop-pos\node_modules\realm\dist\bundle.node.js
- A:\homedrop-pos\node_modules\realm\index.node.js
- A:\homedrop-pos\out\main\index.js
- A:\homedrop-pos\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117469)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (A:\homedrop-pos\node_modules\realm\dist\bundle.node.js:110:22)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
```

**Comment by takameyer** [comment]
@gauravbordoloi Haven't experienced this issue yet.  It could be Windows related, but at the moment those tests are passing. Does `node_modules\realm\generated\ts\realm.node` exist on your system?  Perhaps there is some path resolution not happening correctly.

**Comment by takameyer** [comment]
If you were to modify `node_modules\realm\dist\bundle.node.js` line 110 to:
```
const nativeModule = nodeRequire("..\generated\ts\realm.node");
``` 
it might work.  We might need to sanitise this through `path` module here.

**Comment by gauravbordoloi** [comment]
Hi @takameyer 
When I am installing `11.10.1` it is generating realm.node
But when I am installing `12.0.0-rc2` it's not installing as present in screenshot

![image](https://github.com/realm/realm-js/assets/23193185/3171dffa-d5b3-43ea-ac28-d55fc499eb31)

**Comment by gauravbordoloi** [comment]
Thanks @takameyer . 
Any hack for now to run the current candidate? This problem is creating headache for me. Either I completely move my realm's code to a child process and kill the process or I will use the current candidate with a hackish solution if available.

**Comment by takameyer** [comment]
Appears something went wrong in our automation:
![image](https://github.com/realm/realm-js/assets/164606/39060258-a2da-466f-aa99-1d523e85b9a8)

I'll see if I can get the correct binary

**Comment by gauravbordoloi** [comment]
Thanks. @takameyer

**Comment by takameyer** [comment]
@gauravbordoloi Looking into the logs, it appears both win32 and win64 were outputting to the same path.  It's possible the contents of this tgz will work if you put it in the `node_modules\realm\` folder.  
[realm-v12.0.0-rc.2-napi-v6-win32-%PREBUILD_ARCH%.tar.gz](https://github.com/realm/realm-js/files/12183419/realm-v12.0.0-rc.2-napi-v6-win32-.PREBUILD_ARCH.tar.gz)

I'll keep looking into what the original issue is as this is a blocker for our next release.

**Comment by gauravbordoloi** [comment]
Thanks @takameyer , putting the file worked.
Will verify my real problem with this build and post here.

**Comment by takameyer** [comment]
Just an update, I was able to figure out our issues with publishing windows binaries.  I know that wasn't your original issue, but I still want to thank you for trying this out and making this known.

**Comment by takameyer** [comment]
New binaries are now uploaded, so it should work now without manually adding the binary to `node_modules`.  I have verified this in a windows VM.

**Comment by gauravbordoloi** [comment]
Thanks a lot @takameyer 
Also my core problem is resolved in the `12` version :)

By the way the new release candidate is logging every minute internal details including ssh keys for sync probably, etc.
Is this meant for the RC candidate or there is a way to disable the logging. If I run the production electron app with `--trace-warnings` these logs become visible, so need to disable this before releasing to prod.
I have attached a screenshot.

Thanks a lot again for the help.

![image](https://github.com/realm/realm-js/assets/23193185/26581e48-d9ea-4f3b-8906-214dee9a513e)

**Comment by takameyer** [comment]
@gauravbordoloi This version introduces more granular logging and we implemented a default logger that should only be logging warnings and errors.  Somehow, in your case, it doesn't seem to be functioning as anticipated. You can, however, use the following methods to modify the logger and its threshold:
```
Realm.setLogger((logLevel, message) => console.log(`${logLevel}:${message}`));
Realm.setLogLevel("debug");
```

**Comment by gauravbordoloi** [comment]
Hi @takameyer 
✔️ The realm binary is working fine.
❌ The log configuration is not working at all. I tried setting `off`, `error`, etc but logs are always being shown

**Comment by takameyer** [comment]
@gauravbordoloi Strange, I have tried this in a Windows environment using `node` and I haven't seen any output until I set the proper `logLevel`.  Is it possible you are calling `setLogLevel` somewhere else in your code?

**Comment by gauravbordoloi** [comment]
@takameyer 
Sorry, mistake from my end. I left out the deprecated log code `Realm.App.Sync.setLogLevel(app, "debug")` somewhere in my app.
Removed and everything is working perfect now.

 You can close this ticket. Thanks again :)

**Comment by takameyer** [comment]
@gauravbordoloi Happy we got that all worked out!  Thanks again for your patience with the new release candidate.  That issue saved many others from a giant headache 🚀
