### ISSUE TITLE
How to know realm.deleteAll() cleared all data from realm.

### ISSUE THREAD

**Issue by somasekharkakarla** [realm/realm-js#6007]
### How frequently does the bug occur?

Yes

### Description

How much time does realm.deleteAll() will take to clear data?
How to know realm.deleteAll() has finished?
Will realm.deleteAll() closes realm as soon as it finished? because i getting an error as accessing invalid object. if so how to reopen at the same time?

### Can you reproduce the bug?

-- select --

### Version

11.3.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 13

### Build environment

Which debugger for React Native: ..

**Comment by somasekharkakarla** [comment]
Why don't we have realm.resetAllModels() and realm.resetModels(["Model1", "Model2"]). So that it only clears data in models?

**Comment by takameyer** [comment]
Hi @somasekharkakarla.  

> Why don't we have realm.resetAllModels() and realm.resetModels(["Model1", "Model2"]). So that it only clears data in models?

We don't have those specific methods, but it is possible to just delete an entire collection by querying it and passing it to `realm.delete()`.

https://www.mongodb.com/docs/realm/sdk/react-native/crud/delete/#delete-multiple-objects

**Comment by kneth** [comment]
I am closing the issue due to no new activity. Please create a new issue if you have new observations to share.
