### ISSUE TITLE
App is Crashing at launch After installing Realm into React Native Project(Only IOS)

### ISSUE THREAD

**Issue by sisoalbert** [realm/realm-js#6008]
### How frequently does the bug occur?

Always

### Description

After installing realmjs the app crashes / quit unexpectedly when opening. There following error is shown

### Stacktrace & log output

```shell
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x754665766974617e -> 0x000065766974617e (possible pointer authentication failure)
Exception Codes: 0x0000000000000001, 0x754665766974617e
VM Region Info: 0x65766974617e is not in any region.  Bytes after previous region: 6005596643711  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [5039]

Triggered by Thread:  13
```

### Can you reproduce the bug?

yes

### Reproduction Steps

on a clean app w/:
`"react-native": "0.70.6",`
build ios - successful/
add 
` "realm": "^11.2.0"`
build ios -  launches the app and it crashes immediately 

### Version

11.2.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

IOS 16.1

### Build environment

Which debugger for React Native: ..

    "@realm/react": "^0.4.1",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "realm": "^11.2.0"

### Cocoapods version

 1.11.3

**Comment by takameyer** [comment]
@sisoalbert Are you doing anything specific with `realm` or have you just installed it into your application?  Are you able to produce an example of this that we can try out?

**Comment by sisoalbert** [comment]
I am using device sync, it works on android but as soon I do the ios build, it successfully launches the app and it crashes immediately with the EXC_BAD_ACCESS (SIGSEGV) exception.

It happens even when I try build on a separate M1 laptop.

**Comment by takameyer** [comment]
@sisoalbert Does it persist if you upgrade `react-native` and `realm`?

**Comment by sisoalbert** [comment]
It works with the latest versions (I tested on a new app)
```
    "@realm/react": "^0.5.1",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "realm": "^11.10.1"
```

I try downgrading the version on realm on my 0.7 rn version app

**Comment by kneth** [comment]
@sisoalbert Any updates to share?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
