### ISSUE TITLE
Realm library is missing when signing archive for enterprise distribution

### ISSUE THREAD

**Issue by kljajo** [realm/realm-js#601]
There seems to be an issue when exporting archive for Enterprise distribution.
I am using Realm and RealmSwift 1.1.0 with Xcode8.

Here is the stack trace:
Termination Description: DYLD, Library not loaded: @rpath/Realm.framework/Realm | Referenced from: /var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/xxxx | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm' | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm' | /private/var/containers/Bundle/Application/DF539C48-5B15-4E10-8498-E2F8FE13A1B9/xxxx.app/Frameworks/Realm.framework/Realm: code signing blocked mmap() of '/private/var/containers/Bundle/Application/DF539C48-5
Triggered by Thread:  0

**Comment by fealebenpae** [comment]
Hey @kljajo, this sounds like a question for the folks at https://github.com/realm/realm-cocoa.
