### ISSUE TITLE
react-native - useQuery().filtered() returns new object every render

### ISSUE THREAD

**Issue by aclelland-netfore** [realm/realm-js#6014]
### How frequently does the bug occur?

Always

### Description

setting up a new App and just started learning how to use Realm and noticed this issue with useQuery and filtered() where filtered() will return a new object every render. I've managed to get around this by manually memorizing based on useQuery but I'm pretty sure this is a bug.

### Can you reproduce the bug?

Always

### Reproduction Steps

```
const useItems = (parentId: number) => {
  const {useQuery} = useRealmContext(); // useQuery doesn't work globally at the moment, the Provider also seems broken.

  const items = useQuery(Item); // this is fine, doesn't change
  useEffect(() => {
    // only when parentId changes  as expected
  }, [items])

  const filteredItems = items.filtered("parentId = $0", parentId); // this is a new object
  useEffect(() => {
    // every render
  }, [filteredItems])

  return filteredItems 
}
```

### Version

0.5.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

React-Native, Expo, Android

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@aclelland-netfore We actually just released a way around this.  You can apply filters and sorts in a callback:
```
  const tasks = useQuery(
    Task,
    collection =>
      showDone
        ? collection.sorted('createdAt')
        : collection.filtered('isComplete == false').sorted('createdAt'),
    [showDone],
  );
```
This will be memoized and only return new objects when they have changed.
