### ISSUE TITLE
Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Hisham546** [realm/realm-js#6026]
### How frequently does the bug occur?

Always

### Description

Hi,
I'm getting this error after installing.i tryed clean installing node modules but this thing still shows before app opens.

### Stacktrace & log output

```shell
Error: Exception in HostObject::get(propName:Realm): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealm.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~x_E5su1IaYd9B_sH1hA34w==/com.app-hrzTdpx7NMncezc9OiGzUQ==/lib/x86/librealm.so"... result: 0
```

### Can you reproduce the bug?

Sometimes

### Version

11.10.1

### What services are you using?

-- select --

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@Hisham546 Can you verify the contents of `node_modules/realm/react-native/android/src/main/jniLibs`?
There should be an `x86/librealm.so` in there.

**Comment by takameyer** [comment]
@Hisham546 That needs to be there, so verify that you are installing the `realm` package and that it exists in `node_modules`

**Comment by Hisham546** [comment]
@takameyer  It fixed,i think the issue was with React-Native version 0.69.3.i updated to 0.71.4 and everything working fine now . x86/librealm.so is there.
