### ISSUE TITLE
Realm.Results.removeAllListeners() not working

### ISSUE THREAD

**Issue by rossicler-hostalky** [realm/realm-js#6028]
### How frequently does the bug occur?

Always

### Expected result:
Remove all listeners from a collection when calling `results.removeAllListeners()` method.

### What actually happens:
When calling `results.removeAllListeners()` previously registered listeners are not removed.

### Can you reproduce the bug?

Always

### Reproduction Steps

Example code:
```
export const getItems = async (shouldAddListeners: boolean) => {
  ...
  const items = realm.objects(ItemSchema);
  await realm.subscriptions.update((mutableSubs) => {
    mutableSubs.add(items, { name: "items" });
  })
  
  if (shouldAddListeners) {
    items.removeAllListeners(); // supposed to clean all listeners registered on previous
    items.addListener(itemListener);
  }
  ...
}
```

After calling this function for the second time, it duplicates the same listener.

### Version

11.7.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

macOS Monterey 12.6

### Build environment

Electron ^23.0.0

**Comment by takameyer** [comment]
@rossicler-hostalky Thanks for posting this issue.  We will investigate and get back to you.

**Comment by mednche** [comment]
I have the same issue (realm-js 11.9.0).

```
function myFunction() {
    const records = siteRealm.objects("record")

    // FIRST REMOVE LISTENER!
    records.removeAllListeners()

    // Add new listener
    records.addListener(async (collection, changes) => {
        // My code
    }
}
```

Every time I call `myFunction()`, it creates a new instance of the listener but does not remove any existing ones.

This creates many issues in my app. Any idea what is causing it?

**Comment by rossicler-hostalky** [comment]
Hi @takameyer, is there any other way to remove listeners previously created? Maybe it should have the option to return a unsub function when adding a new listener, kind of similar to web js listeners.

My problem with this is that in the app I'm working we don't keep the "live" objects from realm, all results is always parsed to JSON objects, so changing that to keep the same instance of live objects between method calls will probably require some time to test and a lot of refactoring to work properly.

**Comment by takameyer** [comment]
@rossicler-hostalky Happy you were able to find a workaround.  Feel free to open a feature request.  Aligning our event listeners on web js listeners sounds like an interesting enhancement.
