### ISSUE TITLE
npm WARN engine xmlbuilder

### ISSUE THREAD

**Issue by 2rajpx** [realm/realm-js#604]
How can I fix this error???

`C:\Users\2raj\Documents\React Native Projects\Leitner>npm install --save realm

npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.4.7","npm":"2.15.8"})

npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.`

**Comment by 2rajpx** [comment]
I can't run my project after `react-native link realm`
![image](https://cloud.githubusercontent.com/assets/19687157/18809684/64bd6e20-828f-11e6-8bed-c3f5560fe7da.png)

**Comment by alazier** [comment]
It isn't currently possible to develop Realm react-native projects on windows. This is being tracked in #555
