### ISSUE TITLE
Is it possible to create a has-and-belong-to-many type relationship?

### ISSUE THREAD

**Issue by chaodoze** [realm/realm-js#606]
e.g. I have a class PokemonType, whose, say, "dragon" instance is weak against "ice" and other "dragon"s

so, a class would be something like
```
class PokemonType extends Realm.Object {
  static schema = {
    ...
    weakAgainst: {type:'list', objectType:'PokemonType'}
  }
}

````
Is it possible to have weakAgainst be populated by existing PokemonType instances? #323 seems to implies that is not possible?
If not, how else should I model this?

**Comment by alazier** [comment]
You can definitely do this. You just need to add them to your `List` manually. `List.push`, `List.unshift`, and `List.splice` should all add existing objects to a list, resulting in multiple references to the same object instance. https://realm.io/docs/react-native/0.14.0/api/Realm.List.html#push

**Comment by Bogidon** [comment]
New link: https://realm.io/docs/javascript/latest/api/Realm.List.html#push
