### ISSUE TITLE
Improve documentation regarding indexing.

### ISSUE THREAD

**Issue by Acetyld** [realm/realm-js#6068]
### How frequently does the bug occur?

Always

### Description

So we are rebuilding our app to expo + lots of new stuff, and we are also revisiting our indexes.
By default on all our entities we do a .filtered with active == 1 and __isDeleted == false, we also do a sort by default on most stuff.

So i am trying to figure out if it is worth to keep a index for the filter by id/boolean/name and also if i should have a index if by default i sort on .name
[Index explanation from realmjs page](https://www.mongodb.com/docs/realm/sdk/react-native/model-data/define-a-realm-object-model/#index-a-property)

### Can you reproduce the bug?

Always

### Version

11.10.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

expo 49

### Build environment

Which debugger for React Native: Flipper

**Comment by NextThread** [comment]
is it open?

can I work on this?

**Comment by kneth** [comment]
In this case our internal documentation team will handle it
