### ISSUE TITLE
Didn't find class "io.realm.internal.network.NetworkStateReceiver"

### ISSUE THREAD

**Issue by pgwzzz** [realm/realm-js#607]
Hi.

I've just integrated my react native mobile app with realm.

The problem is that the app is forcely closed by some problem of realm.

I attached the detail of exception.

Should I change the realm version, or is there another way to solve this?

Thank you so much.

[realm-crash.pdf](https://github.com/realm/realm-js/files/515527/realm-crash.pdf)

**Comment by bdash** [comment]
`io.realm.internal.network.NetworkStateReceiver` seems like a type from Realm's Java SDK, rather than from the React Native JavaScript SDK.

**Comment by kristiandupont** [comment]
@pgwzzz are you sure you are using Realm React Native?

**Comment by kristiandupont** [comment]
Closing due to lack of information
