### ISSUE TITLE
Windows 32 bit support?

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-js#6080]
### How frequently does the bug occur?

Always

### Description

I am building an electron app for 32 bit windows in a 64 bit windows machine.
When I run the app on the 32 bit windows, it is showing `realm.node is not a valid Win32 application`

Versions - 
Realm - 12.0.0-rc.3
Electron - 25.3.1
Electron Builder - 24.6.2

Do realm supports windows 32 bit? Or do we have to download different `realm.node` binary for 32 bit support? Any docs would be helpful.

### Can you reproduce the bug?

Always

### Version

12.0.0-rc.3

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Windows 10 32 bit

**Comment by kneth** [comment]
@gauravbordoloi Thank you for asking. Realm supports 32 bit Windows but my guess is that npm gets confused and downloads the 64 bit binary as your host machine is a 64 bit machine.

You can try to specify the architecture for npm before running `npm install`. According to [using native node modules](https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules#using-npm) you should probably do

```sh
export npm_config_arch=x86
export npm_config_target_arch=x86
```

**Comment by gauravbordoloi** [comment]
Hi @kneth 
I tried specifying the architecture in `.npmrc` file with below
`npm_config_arch=x86`
`npm_config_target_arch=x86`

But I guess it's still downloading the 64 bit version as the error persists.

How do I confirm that the downloaded binary is of 32 bit/64 bit?

**Comment by gauravbordoloi** [comment]
Ok I got it working. Thanks.
