### ISSUE TITLE
Method callfunction stopped work in realm 12.0.0

### ISSUE THREAD

**Issue by bnobre** [realm/realm-js#6095]
### How frequently does the bug occur?

Always

### Description

Hi,

I needed to update my RN(0.64.2) and realm(10.9.1) to the RN(0.72.4) and realm(12.0.0). After that, Realm's callfunction method  stopped working (https://www.mongodb.com/docs/realm-sdks/js/10.0.0-beta.8/Realm.User.html#callFunction).

When trying to run I always get the error: **[error] App: call_function: XXXXXXX service_name: <none> -> 500 ERROR: (BadValue) cannot compare to undefined**

### Can you reproduce the bug?

Always

### Reproduction Steps

Upgrade to realm version 12.0.0

### Version

12.0.0

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

OS: Windows 10 10.0.18362 CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

### Build environment

Which debugger for React Native: 0.72.4

**Comment by kneth** [comment]
@bnobre Thank you for reporting. Can you provide a short code snippet on how you use `callFunction`?

**Comment by bnobre** [comment]
Hi @kneth,
```
const app = new Realm.App({ id: "XXXX" })
const credentials = Realm.Credentials.emailPassword(user.name.toLowerCase(), user.password)
const result = await app.logIn(credentials)
const data = await app.currentUser.callFunction("nameFunction", ["2023-08-24", "2023-08-24"])
```

**Comment by kneth** [comment]
In v12 we removed the array for argument. You can use `const data = await app.currentUser.callFunction("nameFunction", "2023-08-24", "2023-08-24")` instead
