### ISSUE TITLE
geospatial queries are unsupported on the server

### ISSUE THREAD

**Issue by samsonayalew** [realm/realm-js#6098]
### Problem

I was trying to subscribe realm sync with geolocation and i got a warning
**Error: Invalid query: unsupported query for table "UserLocation": geospatial queries are unsupported on the server**

```
      const location: GeoPoint = [9.3290, 32.0909];
      const radius = kmToRadians(5) //5 km
    
      // Circle with a radius of 5kms centered
      const circleShape: GeoCircle = {
        center: location,
        distance: radius,
      }
      let filtered = realm.objects(UserLocation).filtered("location geoWithin $0", circleShape)
    
      realm.subscriptions.update(subs => {
        // Create subscription for filtered results.
        subs .add(filtered)
      });
```

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Atlas Device Sync

**Comment by kneth** [comment]
@samsonayalew Currently geospatial queries are not support with Flexible Sync. We are planning to implement it but I can't give you an exact timeline.

**Comment by samsonayalew** [comment]
Is there a way around it?
Does it work on partition sync?

**Comment by samsonayalew** [comment]
Is there a way around it?
Does it work on partition sync?

**Comment by nirinchev** [comment]
What do you mean? With partition sync you don't subscribe to specific queries - you just get all documents that match your partition.

**Comment by samsonayalew** [comment]
Can i specify geolocation on partition sync?

**Comment by nirinchev** [comment]
You can't specify any queries with partition sync.
