### ISSUE TITLE
Filtering by Date without Time

### ISSUE THREAD

**Issue by CrystalRanita** [realm/realm-js#610]
How to filter with specific date (ex. specific_date  is Oct 09 2016 without time) in DB?
const result = realm.objects(type).filtered('DATE == $0', specific_date  );

[Schema Type Define]: DATE = 'date'

[DB contains DATE data]:
Tue Oct 11 2016 09:37:28 GMT+0800 (SGT)
Mon Oct 10 2016 09:37:28 GMT+0800 (SGT)
Sun Oct 09 2016 09:37:28 GMT+0800 (SGT)
Sat Oct 08 2016 09:37:28 GMT+0800 (SGT)

**Comment by alazier** [comment]
You would want to compare against a range, matching dates at 12am of the day you want and 12am of the next day:
```const result = realm.objects(type).filtered('DATE >= $0 && DATE < $1', specific_day, next_day );```

**Comment by CrystalRanita** [comment]
Thanks :) 
Is realm possible to get strings such as "Mon" from date type?

**Comment by stonecold123** [comment]
@alazier 
Are there any changes regarding the filter in 1.11.1?
I can only query either `DATE >= $0` or 'DATE < $1` , but I can't query both
````
const result = realm.objects(type).filtered('DATE >= $0 && DATE < $1', specific_day, next_day);
````

**Comment by saravanakumargn** [comment]
```
import { startOfDay, endOfDay } from 'date-fns';

const filterItems = taskLists.filtered('dueDate >= $0 && dueDate <= $1', startOfDay(new Date()), endOfDay(new Date()));
```
