### ISSUE TITLE
Realm 12.0.0 migration : had to downgrade typescript to 4.8.4 (from 5)

### ISSUE THREAD

**Issue by olivier5741** [realm/realm-js#6106]
### How frequently does the bug occur?

Always

### Description

I migrated from Realm 11 to 12 and had to downgrade Typescript from 5 to 4.8.4 because of OrderedCollection implementation of Omit<ReadonlyArray<T>, "entries"> is incomplete (from what I understand). 

I'm not using babel, don't know if it supposed to make a difference. This are the only depencies I have.

[I'm not really a node expert :)]

```
  "dependencies": {
    "realm": "^12.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.5.7",
    "typescript": "^4.8.4"
  }
```

```
{
  // https://www.typescriptlang.org/tsconfig#compilerOptions
  "compilerOptions": {
    "esModuleInterop": true,
    "lib": ["es2020"],
    "module": "es2022",
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "strict": true,
    "sourceMap": true,
    "target": "es2022",
    "types": ["node"],
    "outDir": "dist"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

### Stacktrace & log output

```shell
node_modules/realm/dist/bundle.d.ts:424:24 - error TS2420: Class 'OrderedCollection<T, EntryType>' incorrectly implements interface 'Omit<readonly T[], "entries">'.
  Property '[SymbolConstructor.unscopables]' is missing in type 'OrderedCollection<T, EntryType>' but required in type 'Omit<readonly T[], "entries">'.

424 declare abstract class OrderedCollection<T = unknown, EntryType extends [unknown, unknown] = [number, T]> extends Collection<number, T, EntryType, T, CollectionChangeCallback<T, EntryType>> implements Omit<ReadonlyArray<T>, "entries"> {
                           ~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:107:14
    107     readonly [Symbol.unscopables]: {
                     ~~~~~~~~~~~~~~~~~~~~
    '[SymbolConstructor.unscopables]' is declared here.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

I can share code privately if it helps but I would say that upgrading typescript would show the issue.

### Version

12.0.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

mac 0S

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@olivier5741 Thank you - it's a good catch. It is definitely not on purpose that we don't support TypeScript 5.x. We should investigate if all supported JavaScript engines support [unscpobales](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables) as it looks as a requirement. Hermes is a new engine, and it is still catching up.

**Comment by olivier5741** [comment]
Thank you, I just upgraded my dependencies and it's working :)

```
 @types/node  ^20.5.7  →  ^20.10.4
 realm        ^12.0.0  →   ^12.3.1
 ts-node      ^10.9.1  →   ^10.9.2
 typescript    ^4.8.4  →    ^5.3.3
```
