### ISSUE TITLE
Property '***' of type 'array' cannot be nullable.

### ISSUE THREAD

**Issue by bao-multiIT** [realm/realm-js#6112]
### How frequently does the bug occur?

Always

### Description

Hello, I'm not sure if this is a bug or not, but I just followed the Realm guide and it crashes the app.

In the React Native Realm guide, I followed the code in the section [Declare an Optional Property](https://www.mongodb.com/docs/realm/sdk/react-native/model-data/define-a-realm-object-model/#declare-an-optional-property)

But an error appears and crashes the app:
```
Error: Exception in HostFunction: Schema validation failed due to the following errors:
- Property 'Dog.owners' of type 'array' cannot be nullable.
```

If a list cannot be nullable, then why does the example in the React Native Realm guide do so?

### Stacktrace & log output

```shell
Error: Exception in HostFunction: Schema validation failed due to the following errors:
- Property 'Dog.owners' of type 'array' cannot be nullable.
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Make any 'list' property have `optional: true` in your schema and the error will appear

### Version

11.10.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 12

### Build environment

Built on Windows 10, React Native 0.72.4

**Comment by kneth** [comment]
@bao-multiIT Lists are always optional, and specifying `optional` is not possible. In version 12.0.0 we introduced a better check. The documentation needs to be updated.

**Comment by krollins-mdb** [comment]
Terribly sorry, @bao-multiIT. There are a few spots in the docs that still contain examples that aren't tested - and you found one of them.

I appreciate you bringing it to our attention. I have [a PR](https://github.com/mongodb/docs-realm/pull/2985) up for the docs repo that addresses the problem and ensures this won't happen again it's being tested.

**Comment by bao-multiIT** [comment]
Thanks for addressing this guys. I'll close the issue since the fix PR has been merged.
