### ISSUE TITLE
useQuery fails to update

### ISSUE THREAD

**Issue by myt-satish** [realm/realm-js#6113]
### How frequently does the bug occur?

Always

### Description

how do you recommend using useQuery with filtered/filter/sorted and so on?

```
const [search, setSearch] = useState("")
const allItems = useQuery(Object, (collection) -> collection.filtered("search == $0", search))
```
`allItems` fails to update when setSearch('asd') is called.

### Can you reproduce the bug?

Always

### Version

latest

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

React native android/ios both

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@myt-satish `useQuery` takes a dependency array similar to `useEffect` in order to know when to update the given query.  Here is how to fix your example:
```
const [search, setSearch] = useState("")
const allItems = useQuery(Object, (collection) -> collection.filtered("search == $0", search),[search])
```
