### ISSUE TITLE
React Native Android crashes immediately when put in debug mode

### ISSUE THREAD

**Issue by dwpuush** [realm/realm-js#6133]
### How frequently does the bug occur?
Always

### Description
When enabling debug mode on a freshly created React Native project with only realm and @realm/react installed, the app crashes.

### Stacktrace & log output
```shell
09-14 19:14:27.534  5422  5422 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_object == null
09-14 19:14:27.534  5422  5422 F DEBUG   :     in call to GetObjectClass
09-14 19:14:27.534  5422  5422 F DEBUG   :     from com.facebook.react.turbomodule.core.CallInvokerHolderImpl com.facebook.react.bridge.CatalystInstanceImpl.getJSCallInvokerHolder()'
```

### Can you reproduce the bug?
Always

### Reproduction Steps
react-native init testProject
yarn add realm @realm/react
yarn start --reset-cache
react-native run-android

press "d" to open menu
click on "debug"

### Version
12.1.0

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Android

### Build environment
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@realm/react": "^0.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "realm": "12.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

node v16.20.2
Android Studio 2022.3.1 Patch 1
AVD Android 12.0

**Comment by kneth** [comment]
@dwpuush I wonder if the following ProGuard configuration will help:

```
-keep class com.facebook.react.turbomodule.** { *; }
```

**Comment by dwpuush** [comment]
@kneth Thanks for the advice, but adding that doesn't seem to help.  It's my understanding that during a debug build proguard is not enabled anyhow.  I checked to be sure and enableProguardInReleaseBuilds is set to false in my app/build.gradle

As mentioned earlier, I've made no changes to any files in the project after initializing the project.  I've tested this on both a linux machine and on a mac with the same results.

**Comment by kneth** [comment]
@dwpuush Your issue is similar to https://github.com/software-mansion/react-native-reanimated/issues/2710 and the renanimated folks haven't found a solution.

Does it happen on both JavaScriptCore and Hermes?

**Comment by dwpuush** [comment]
This happens with both JSC and Hermes.  I had not noticed before the known issue in the readme stating that the old debug in chrome feature did not work and that I should be using Flipper.  I've been successful using that and just not turning on debug mode in the app.  Closing issue.
