### ISSUE TITLE
onFirstOpen not work

### ISSUE THREAD

**Issue by eliot-ye** [realm/realm-js#6143]
### How frequently does the bug occur?

Always

### Description

onFirstOpen not work on v12.1.0

### Can you reproduce the bug?

Always

### Version

12.1.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

android, ios

### Build environment

Which debugger for React Native: ..
"react-native": "0.72.4",
"realm": "^12.1.0",

### Cocoapods version

1.12.1

**Comment by elle-j** [comment]
Hi @eliot-ye, could you provide some more specifics of what is not working? Do you mind sharing some code?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
