### ISSUE TITLE
Invalid top array

### ISSUE THREAD

**Issue by AdnanJafar** [realm/realm-js#6156]
### How frequently does the bug occur?

Sometimes

### Description

Hello,
I use Realm Studio on a regular basis to create .json files from the realm file. However, this time, I cannot open the file and it throws an error of invalid top array.... I tried to upgrade and used realm realm studio versions but this problem could not be fixed. I would appreciate it if anyone could suggest any fix or create a .json file if I share that file privately.  Many Thanks!

### Can you reproduce the bug?

Sometimes

### Version

Realm Studio Version 14.0.4

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Microsoft Window 11

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@AdnanJafar Thank you for reporting.

`Invalid top array` can have different causes, so I have a couple of follow-up questions:

* When you open the file in Studio, is the file also opened by another process?
* Is the Realm file encrypted?
* Which SDK and which version were the file created with?
