### ISSUE TITLE
Non of my types for realm  with typescript pick up when i upgrade to version 12 of realm

### ISSUE THREAD

**Issue by shanoysinc** [realm/realm-js#6160]
### How frequently does the bug occur?
Always

### Description
before on version 11 typescript was working fine but since upgrading to version 12 typescript just doesnt work with realm it picks of typescript for everything else in the file just not realm

### Can you reproduce the bug?
Always

### Version
12.1.0

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
expo  v49.0.11  react native 0.72.5

### Build environment
Which debugger for React Native: ..

**Comment by kneth** [comment]
@shanoysinc Since you reproduce always, we will appreciate a production case or a least some code snippets to help us understand the issue.
