### ISSUE TITLE
RangeError: number is not integral, js engine: hermes

### ISSUE THREAD

**Issue by angelos3lex** [realm/realm-js#6190]
### How frequently does the bug occur?

Sometimes

### Description

There is a crash when I'm doing a creation in the db. Seems like it doesn't happen everytime, maybe around 80%, or maybe has something to do with specific data, i haven't yet concluded where the error begins.
_This is happening now as I updated realm and react native, didn't use hermes before._

The creation is happening inside a transaction as i have called `beginTransaction` and then i call:
```
this._realm.beginTransaction();
this._realm.create(schema, obj, Realm.UpdateMode.All)
this._realm.commitTransaction();
```

I get the following error:
`RangeError: number is not integral, js engine: hermes`

This is happening on android (I haven't yet tested iOS)
with: Realm 12.2.0, hermes and RN 0.72.5

### Stacktrace & log output

```shell
numToInt 
  bundle.react-native.js:649:18
anonymous
  bundle.react-native.js:4334:42
anonymous
  bundle.react-native.js:3749:40
set
  bundle.react-native.js:4127:24
create
  bundle.react-native.js:4717:41
create
  bundle.react-native.js:9653:45
```

### Can you reproduce the bug?

Sometimes

### Reproduction Steps

Will update further while i follow more the crash, as the schema is huge and cant provide as is for now.
Any ideas/hints for now on how to proceed debugging?

### Version

12.2.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android (tested on 13 & 10, happens on both)

**Comment by angelos3lex** [comment]
I verify that on previous realm the double was automatically transformed by realm to int and saved successfully to the database. I'm closing this issue as we can fix this on our end, no reason to ask to keep same automatic transformation.

**Comment by mklb** [comment]
I can confirm this. I use ```Math.trunc()```  now

**Comment by joseluishaddad** [comment]
I am having the same issue with realm 12.5.1 on iOS
