### ISSUE TITLE
Error: Could not find the Realm binary with Expo49

### ISSUE THREAD

**Issue by maichongju** [realm/realm-js#6193]
### How frequently does the bug occur?

Always

### Description

When building a brand new app with Realm and Expo. App crashed after compile, with the error message `Error: Could not find the Realm binary. Please consult our troubleshooting guide: https://www.mongodb.com/docs/realm-sdks/js/latest/#md:troubleshooting-missing-binary, js engine: hermes`

I am using Expo Go to run the app.

### Stacktrace & log output

The complete dependencies (`package.json`)

```
{
  "name": "myawesomerealmapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@realm/react": "^0.6.1",
    "expo": "^49.0.8",
    "expo-dev-client": "~2.4.8",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-get-random-values": "~1.9.0",
    "realm": "^12.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.5",
    "@babel/plugin-proposal-decorators": "^7.22.5",
    "@realm/babel-plugin": "^0.1.1",
    "@types/react": "~18.2.13",
    "typescript": "^5.1.3"
  },
  "license": "Apache-2.0",
  "private": true
}

```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. run `expo init MyAwesomeRealmApp --template @realm/expo-template`
2. `npx expo start --android`

Error appear after app compiled 

### Version

"realm": "^12.2.1",, "@realm/react": "^0.6.0",

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Win11 23H2

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@maichongju You cannot use Expo Go to run dev-client applications.  You must compile your own dev client.  The Realm Binary is not included as part of Expo Go.
