### ISSUE TITLE
Mismatch type when passing `user`  from `useUser` as parameter  

### ISSUE THREAD

**Issue by maichongju** [realm/realm-js#6196]
### How frequently does the bug occur?

Always

### Description

As the [documentation](https://www.mongodb.com/docs/realm/sdk/react-native/manage-users/authenticate-users/) suggested, we can pass the `user` to a function. 

```typescript

// Gets a valid user access token to authenticate requests
async function getValidAccessToken(user: Realm.User) {
// An already logged in user's access token might be stale. To
// guarantee that the token is valid, refresh it if necessary.
await user.refreshCustomData();
 
return user.accessToken;
}

```

However, when passing the `user` from `useUser()`. following error display. 

```
Argument of type
User<DefaultFunctionsFactory, Record<string, unknown>, DefaultUserProfileData>
is not assignable to parameter of type
UserType<UserFunctionsType, UserCustomDataType, UserProfileDataType>
Types have separate declarations of a private property  cachedProfile 
```

### Can you reproduce the bug?

Always

### Reproduction Steps

`file1.ts`
```typescript
import Realm from 'realm';

export function foo(user: Realm.User){
  // Do something
}

```

`file2.ts`
```typescript
import {foo} from file1;

const user = useUser();
foo(user);
```

### Version

"realm": "^12.2.1",, "@realm/react": "^0.6.0",

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Win11 23H2

### Build environment

Which debugger for React Native: ..

**Comment by takameyer** [comment]
@maichongju Thanks for reporting!  It seems using `rollup` for generated type declarations was causing some trouble.  I opened a PR which uses good old `tsc` to do this and the results have seemed to improve.  Most importantly, it fixes the issue you have.  Once this has been reviewed and merged we will cut a release.

**Comment by CarlosVilasAlvarez** [comment]
@takameyer Okay, it seems that this happens when I use the following import

`import { User } from 'realm'`

but it works when I use the following type

```
import Realm from 'realm
 
const user: Realm.User = ...
```

**Comment by kraenhansen** [comment]
I'll be taking over this issue and try to reproduce it 👍
