### ISSUE TITLE
Nullability for property has been changed from true to false

### ISSUE THREAD

**Issue by edo1493** [realm/realm-js#620]
Hi guys, 
I am trying to create a Realm schema in Objective-C and then run a React Native app on top of it to try to read it. My objective-c schema is the following:

```
@interface PersonTest : RLMObject
@property NSString *firstName;
@property NSString *lastName;
@end
```

This is my React Native one: 

```
class PersonTest extends Realm.Object {}
PersonTest.schema = {
  name: 'PersonTest',
  properties: {
    firstName:  'string',
    lastName:   'string',
  }
};
```

I was told, in theory, I should be able to grab the data from RN cause they both write on the same file. The properties are string in both the schemas, so I am not sure if this is an issue or there is something wrong in the objective-c definition. 

I am getting: 
"Migration is required due to the following errors:
Nullability for the property "firstName" has been changed from true to false
Nullability for the property "lastName" has been changed from true to false"

**Comment by alazier** [comment]
Sorry for the late response. `NSString` properties are optional by default, so to create the same schema in RN, you would need to use:
```js
PersonTest.schema = {
  name: 'PersonTest',
  properties: {
    firstName: {type: 'string', optional: true},
    lastName: {type: 'string', optional: true}
  }
};
```

Hope that solves your issue!

**Comment by edo1493** [comment]
Yes, it works. I can read realm from RN.
