### ISSUE TITLE
Your app is relying on a Realm global, which will be removed in realm-js v13, please update your code to ensure you import Realm

### ISSUE THREAD

**Issue by hpelitebook745G2** [realm/realm-js#6209]
### How frequently does the bug occur?
Always

### Description
I wanted to implement a Singleton class for Realm to ensure reusability throughout the application. Creating a separate instance for each component doesn't seem practical.

### Stacktrace & log output
```shell
WARN  Your app is relying on a Realm global, which will be removed in realm-js v13, please update your code to ensure you import Realm:

 import Realm from "realm"; // For ES Modules
 const Realm = require("realm"); // For CommonJS

 To determine where, put this in the top of your index file:
 import Realm from "realm";
 Realm.flags.THROW_ON_GLOBAL_REALM = true
```

### Can you reproduce the bug?
Always

### Reproduction Steps
1. Create a file that holds Realm instance

```
const realm = new Realm({ schema: [TestSchema] })

export default realm
```

1. Import this from your component
1. Get the warning

Versions:

```
"@realm/react": "^0.6.1",
"realm": "^12.2.1",
"realm-flipper-plugin-device": "^1.1.0",
```

### Version
12.2.1

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
iOS 17 and Android 11.0

### Build environment
Which debugger for React Native: Flipper Version 0.228.0 (50.0.0)

### Cocoapods version
1.13.0

**Comment by kraenhansen** [comment]
Please try setting the `THROW_ON_GLOBAL_REALM` as outlined [here](https://github.com/realm/realm-js/pull/5660), to figure out where you're using `Realm` without an import:

```typescript
import { flags } from "realm";
flags.THROW_ON_GLOBAL_REALM = true;
```

If that doesn't work, please create a new issue or alternatively post in our community forums: https://www.mongodb.com/community/forums/

**Comment by buster95** [comment]
this is because you are using Realm without import check your Schemas and every part you use `Realm.`

for example you can define a schema in this way
```typescript
export class PersonSchema extends Realm.Object<Person> {
  name!: string
  age?: number

  static schema: Realm.ObjectSchema = {
    name: 'Person',
    properties: {
      name: 'string',
      age: 'int?',
    },
  }
}
```

but the right way is this
```typescript
import Realm from 'realm' // <-- check yours imports

export class PersonSchema extends Realm.Object<Person> {
  name!: string
  age?: number

  static schema: Realm.ObjectSchema = {
    name: 'Person',
    properties: {
      name: 'string',
      age: 'int?',
    },
  }
}
```

**Comment by congduong97** [comment]
<img width="555" alt="Screenshot 2023-12-01 at 12 10 08" src="https://github.com/realm/realm-js/assets/39731881/ddeaea75-2cea-483e-bba7-f87efde10c24">
Thanks @buster95 , it worked. my problem when create new item use Realm.BSON for id without import Realm
