### ISSUE TITLE
Print result

### ISSUE THREAD

**Issue by ajithamp** [realm/realm-js#621]
render() {
    let realm = new Realm({
      schema: [{ name: 'Dog', properties: { name: 'string' } }]
    });
    realm.write(() => {
      realm.create('Dog', { name: 'Ajith' });
    });
    let name = realm.objects('Dog').name;
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!{'\n\n'}
        </Text>
        <Text style={styles.welcome}>
          Count of Dogs in Realm:{name}
        </Text>
      </View>
    );
  }

how can i print the name value, when i use above code it shows empty space in {name} Area

**Comment by alazier** [comment]
The problem is that the objects method returns a `Results` object, not an individual `Dog` object. Try changing your code to get the first object in the `Results` list:
```
let dog = realm.objects('Dog')[0];
let name = dog.name;
```
