### ISSUE TITLE
Query with parameterized expression only considers last element in array 

### ISSUE THREAD

**Issue by yakusho** [realm/realm-js#6222]
### How frequently does the bug occur?

Always

### Description

I'm trying to use parameterized expressions in React Native, and I noticed that whenever I pass an array, it only considers the last element in the array.

The docs for the Realm Query Language shows this example:
```js
const ids = [
  new BSON.ObjectId("631a072f75120729dc9223d9"),
  new BSON.ObjectId("631a0737c98f89f5b81cd24d"),
  new BSON.ObjectId("631a073c833a34ade21db2b2"),
];
const parameterizedQuery = realm.objects("Item").filtered("id IN $0", ids);
```

My use case is slightly different and would be better expressed like this:
```js
const targetTypes = ["House", "Flat"];
const parameterizedQuery = useQuery(Target, res => res.filtered("targetType IN $0", targetTypes));
```

However, it's only ever returning records where targetType is "Flat" in that example, if you put "House" as the last element, it starts showing only those with targetType "House", if I use a random value that has 0 results ("Test" for example), it crashes the app but I'm unable to verify if that happens because of the query or just my application

### Can you reproduce the bug?

Always

### Version

11.10.2

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.4

### Build environment

```json
"@realm/react": "^0.6.0",
"realm": "^11.10.2",
"react-native": "0.72.6",
```

### Cocoapods version

~> 1.12

**Comment by kneth** [comment]
In v12.0.0-rc.0 we fixed a [bug ](https://github.com/realm/realm-core/pull/6545) related to `IN`. The changelog entry is `Fixed an error where performing a query like "{1, 2, 3, ...} IN list" where the array is longer than 8 and all elements are smaller than some values in list, the program would crash.`. I don't know if it applies to your case.

You are using `@realm/react`, and does you only observe it with `useQuery()` or do you see a similar behavior when querying directly?

We have [tests](https://github.com/realm/realm-js/blob/main/integration-tests/tests/src/tests/queries.ts#L1798-L1828) covering the `IN` operator. In order for us to reproduce it, we would like to know how your case differs from our tests.

**Comment by yakusho** [comment]
> In v12.0.0-rc.0 we fixed a [bug ](https://github.com/realm/realm-core/pull/6545) related to `IN`. The changelog entry is `Fixed an error where performing a query like "{1, 2, 3, ...} IN list" where the array is longer than 8 and all elements are smaller than some values in list, the program would crash.`. I don't know if it applies to your case.
> 
> You are using `@realm/react`, and does you only observe it with `useQuery()` or do you see a similar behavior when querying directly?
> 
> We have [tests](https://github.com/realm/realm-js/blob/main/integration-tests/tests/src/tests/queries.ts#L1798-L1828) covering the `IN` operator. In order for us to reproduce it, we would like to know how your case differs from our tests.

I'll have to verify if upgrading to v12 will fix the bug where it crashes.

As for the useQuery, I could reproduce it both with useQuery or querying directly using ``objects(type).filtered``

I created a project to reproduce the problem I'm having [here](https://github.com/yakusho/realm-param-expression), I tested it using an array of ObjectIds and in that case, the ``IN`` operator does work, but if it's a string, then it doesn't work anymore, which is weird considering that I believe this test should probably fail in that scenario:
```js
const many = persons.filtered("name in $0", ["Alice", "Dennis", "Bob"]);
expect(many.length).equal(2);
```

**Comment by nirinchev** [comment]
This is fixed in Realm 12.
