### ISSUE TITLE
Race condition when checking for / creating JS context

### ISSUE THREAD

**Issue by benwixen** [realm/realm-js#624]
I am using Realm in a React Native application, running it from XCode on an iPhone 6, and randomly, I would guess around 20% of the time, the application crashes on startup. I get the following error from `RCTJSCExecutor.mm`:

```
RCTAssert(self->_context == nil, @"Didn't expect to set up twice");
```

This is in turn originating from `RealmReact.mm`:

```
rctJSContext = [[RCTJavaScriptContext alloc] initWithJSContext:[JSContext new] onThread:[NSThread currentThread]];
```

It seems like there is a race condition between RN and React around here in the same file:

```
id rctJSContext = object_getIvar(executor, contextIvar);
if (!rctJSContext && create) {
```

Please let me know if there is anything I can do to provide more information / get closer to a solution.

My environment is:
OS X 10.11.16
XCode 8.0
iPhone 6
iOS 8.4
react-native 0.34.1
realm 0.14.3

**Comment by kneth** [comment]
@benwixen Do you still experience these random crashes? I mean, we have fixed many bugs and added much functionality since you created this issue.

**Comment by benwixen** [comment]
I'm not currently working on a project using this library, but I'll close the issue, and if it's still broken, I guess someone will report it.
