### ISSUE TITLE
What is best practice to migration?

### ISSUE THREAD

**Issue by devethan** [realm/realm-js#6241]
### Problem
Hi, I'd like to know what is YOUR the best practice to write codes for migration statement.

I've manageed to that like below codes,

```typescript
export const CURRENT_REALM_SCHEMA_VERSION = 6;

export function onMigration( oldRealm: Realm, newRealm: Realm ) {
   if( oldRealm.schemaVersion < CURRENT_REALM_SCHEMA_VERSION ) {
      switch( oldRealm.schemaVersion ) {
         case 0:
            // do
         case 1:
            // do
         case 2:
            // do
         ...
         case 5:
            // do
            break;
         default:
            throw new Error('Cannot match schemaVersion for this migration')
      }
   }
}
```

If the user install the version which has schemaVersion 2 and then update to the version has schemaVersion 6, the migration statement will executed from case 2 to 5. 

### How important is this improvement for you?
  * select --

### Feature would mainly be used with
  * select --

**Comment by kneth** [comment]
In most cases, schema migration can happen automatically. At least if you have simple schema changes, and you don't need to change any objects.

In your case, I would change the code to

```js
export const CURRENT_REALM_SCHEMA_VERSION = 6;

export function onMigration( oldRealm: Realm, newRealm: Realm ) {
  const oldSchemaVersion = oldRealm.schemaVersion;
  const migration = [
    () => { /* do */ },
    () => { /* do */ },
  ];
  for (let ver = oldSchemaVersion; ver < CURRENT_REALM_SCHEMA_VERSION; ver++) {
    migration[ver]();
  }
};
  
```

Documentation on how to [change an object model](https://www.mongodb.com/docs/realm/sdk/node/model-data/modify-an-object-schema/) might be useful.

**Comment by ansarizafar** [comment]
@kneth Could you please explain/list schema changes that require migration and what are the schema changes that trigger automatic migration?

**Comment by nirinchev** [comment]
The topic of migrations is covered in our [docs](https://www.mongodb.com/docs/realm/sdk/node/model-data/modify-an-object-schema/). If you have questions or suggestions for additional content there, you can use the "Rate this page" widget and explain your request.
