### ISSUE TITLE
Realm.User.identities is returning undefined providerType

### ISSUE THREAD

**Issue by joelowry96** [realm/realm-js#6248]
### How frequently does the bug occur?

Always

### Description

When trying to access the providerType of a UserIdentity in Realm.User.identities, providerType is undefined.

https://github.com/realm/realm-js/blob/a3589c63a1d18740b4ffd7b18ca82b92a8ea33b5/packages/realm/src/app-services/User.ts#L191-L196C4

I think this could be fixed with:
realm-js/packages/realm/src/app-services/User.ts @193
```diff
- const { id, provider_type: providerType } = identity as Record<string, string>;
+ const { id, providerType } = identity as Record<string, string>;
```

because Realm.User.providerType (now deprecated) just accesses identity.providerType (not identity.provider_type)
https://github.com/realm/realm-js/blob/a3589c63a1d18740b4ffd7b18ca82b92a8ea33b5/packages/realm/src/app-services/User.ts#L141-L151C4

### Can you reproduce the bug?

Always

### Version

12.3.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 16

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@joelowry96 Thank you for reporting. If you have a fix, please create a pull request.
