### ISSUE TITLE
Could not find the Realm binary

### ISSUE THREAD

**Issue by suntan-superman** [realm/realm-js#6255]
I am trying to test Realm with React Native (JavaScript) on a Windows machine and keep getting the message "Could not find the Realm binary". I have tried all of the suggested solutions to no avail.

**Comment by kneth** [comment]
@suntan-superman Can you give more details about your set up?

**Comment by suntan-superman** [comment]
Setup:
Windows 10 Pro machine
Android Studio emulator
Package.json:
{
  "name": "realmtailwindcssapp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    ***@***.***/webpack-config": "^0.12.52",
    ***@***.***/react": "^0.6.2",
    "expo": "^44.0.6",
    "expo-dev-client": "^2.4.12",
    "expo-splash-screen": "^0.10.3",
    "expo-status-bar": "^1.7.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "^0.72.7",
    "react-native-get-random-values": "^1.9.0",
    "react-native-web": "~0.19.6",
    "realm": "^12.3.0",
    "twrnc": "^3.6.4"
  },
  "devDependencies": {
    ***@***.***/core": "^7.20.0",
    "sharp-cli": "^4.1.1",
    "tailwindcss": "^3.3.2"
  },
  "private": true
}

Would love to test on iPhone but it seems that is not possible at this time.
________________________________

**Comment by takameyer** [comment]
@suntan-superman Are you activating the dev-client when starting the bundler?  

```
expo start --dev-client
```

**Comment by suntan-superman** [comment]
Yes I am.
________________________________

**Comment by ahmad1508** [comment]
Hey did you find a solution for this problem ? 
i have the same problem using the following command to create my app `npx create-expo-app@latest MyRealmApp --template @realm/expo-template` and without adding any code i get this error when i start the server

**Comment by kneth** [comment]
@ahmad1508 @suntan-superman It is unclear if you are using Expo Go or not. But Expo Go doesn't support Realm - see https://github.com/realm/realm-js/issues/6193#issuecomment-1757270090
