### ISSUE TITLE
when to use debug ui to debug react native app POST http://172.16.152.15:8082/create_session net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by zhanghaj00** [realm/realm-js#627]
when to use debug ui to debug react native app POST http://172.16.152.15:8082/create_session net::ERR_CONNECTION_TIMED_OUT ,,and I dont know why this while a outside link appeared  to stop the app debug. and a notice `import io.realm.react.RealmReactPackage;` this will auto insert into MainActivity.java  . this is weired....

**Comment by nhachicha** [comment]
Hi @zhanghaj00  do you still have this issue with the latest version we published?

`create_session` allow debugging with Chrome, if you see a `net::ERR_CONNECTION_TIMED_OUT` that could indicate that the IP address set by the Gradle script is wrong (or the packager is not running)

AFAICT `RealmReactPackage` is no longer used in the module
