### ISSUE TITLE
Nullable embedded schema behaves differently on Realm 12 and 11

### ISSUE THREAD

**Issue by andreyukD** [realm/realm-js#6280]
### How frequently does the bug occur?

Always

### Description

Realm 11.9.0 and 12.3.1 (I suppose it since 12.0.0) have different behavior when setting the embedded object field to null. 
While 11.9.0 allows us to do it, 12.3.1 doesn't set null to an object field. Will it be fixed, or are these new validation constraints?

### Can you reproduce the bug?

Always

### Reproduction Steps

I've created an example to show the difference between Realm 12.3.1 and 11.9.0.

https://github.com/andreyukD/reproduce-realmjs-issue (branch v12-3-1)

Starting point was `npx create-expo-app MyAwesomeRealmApp --template @realm/expo-template`

I've added a new field `items` in `Task` schema

commit with 12.3.1 - https://github.com/andreyukD/reproduce-realmjs-issue/commit/82700701cccf2f794e912fb99a7a8466d4092767
commit with 11.9.0 - https://github.com/andreyukD/reproduce-realmjs-issue/commit/b1ce35065b97c24b32dc9c6f7c55dc46b25ddef6

https://github.com/realm/realm-js/assets/33383393/45beff07-7b8c-42d1-b662-9adef282d636

https://github.com/realm/realm-js/assets/33383393/5a337bc3-9be8-4374-a3c2-680a6c42fc8d

### Version

12.3.1 / 11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 14.0

### Build environment

Which debugger for React Native: ..

**Comment by andreyukD** [comment]
Hi Realm team, any news on this issue? Thanks!

**Comment by kneth** [comment]
@andreyukD 

First, sorry for the late reply. Second, thank you for the bug request. Unfortunately we have had a chance to investigate it yet, but I will bring it up with the next early next week.

**Comment by andreyukD** [comment]
Can confirm that bug was fixed in Realm v12.5.0
https://github.com/andreyukD/reproduce-realmjs-issue/commit/93e37e56386e740a505ff53c132ef1dea9aa73c9

**Comment by elle-j** [comment]
Great, thanks @andreyukD 👍
