### ISSUE TITLE
Downloading core failed.

### ISSUE THREAD

**Issue by xiaoleiooo** [realm/realm-js#629]
when I create a new project, use those：
react-native init MyApp
npm install --save realm
react-native link realm
there‘s no problem，but when i run it on ios:react-native run-ios
give me a  tips :"Downloading dependency: core 1.1.2"   for a long long time .
at last :Downloading core failed. Please try again once you have an Internet connection.
Command /bin/sh failed with exit code 1

I have try several times。

**Comment by na4zagin3** [comment]
I also hit the same problem.
I guess the reason is <https://github.com/realm/realm-js/blob/master/scripts/download-core.sh#L56>.

Even though it downloads file "realm-core-$REALM_CORE_VERSION.tar.xz", it try to extract by tar with option `-czf`, although it should be `-cjf`.

**Comment by alazier** [comment]
Were you ever able to get this working?
