### ISSUE TITLE
mmap() failed: Out of memory size error on Android

### ISSUE THREAD

**Issue by jrichardlai** [realm/realm-js#630]
Hello, 

I'm seeing a memory error in react-native 0.34.1 and realm 0.14.3.
I didn't had this issue before, so not sure if its because of RN or Realm,
I'm seeing the error in our bug report on Bugsnags, when calling `realm.write`:
`mmap() failed: Out of memory size: 11534336 offset: 0`
Interestingly after this first crash there could be subsequent one indicating: 
`The Realm is already in a write transaction`.
Have you guys heard of anything like this? Any ideas of how to debug this ( what to log, what to ask) ?

Thank you for the help!

**Comment by nhachicha** [comment]
Hi @jrichardlai 
> The Realm is already in a write transaction
this happen at the [Object Store level](https://github.com/realm/realm-object-store/blob/e807c4505d4185ec1923622f53a5c762d8f5def7/src/shared_realm.cpp#L458)  
This indicate that you're trying to start a write transaction while another one is on going.

This also might be related to your OutOfMemory, if you maintain a long running write transaction...

are you trying to access the Realm file from Android as well?

it could be helpful to share the project or APK privately help@realm.io

**Comment by Udbhav12** [comment]
@nhachicha - I am facing the same problem when I try to perform a long running write transaction (inserting around 600k records). 

I am testing on Samsung Galaxy On7 Pro 

I am using react-native 0.57.5 and realm 2.20.0

I am opening Realm synchronously that is creating a realm instance by invoking the constructor and passing a configuration object to it. I don't know whether this is recommended approach or not. I am not using Realm Object Server

> This indicate that you're trying to start a write transaction while another one is on going.
  What is the recommended way to avoid this problem ? Should I use isInTransaction( )  before performing write operation ?
