### ISSUE TITLE
Chrome Debugging not woring with realm

### ISSUE THREAD

**Issue by vinaykumar0339** [realm/realm-js#6302]
### How frequently does the bug occur?
Always

### Description
I have upgraded my React native version from 0.67.4 to 0.71.14. but here I am facing an issue with the async await code where some places working and some places are not in staging builds, But it working fine in debug modes.[
](https://github.com/facebook/react-native/issues/41737) but no response.

so I thought to disable Hermes in my project.
but realm having an issue with if I enabled Chrome debugging realm throwing errors like below screenshot
![simulator](https://github.com/realm/realm-js/assets/66993050/5c85815e-067b-4187-8a12-cb946e7006ce)UNITO-UNDERSCORE!screenshot!UNITO-UNDERSCORE!88F32B1B-5B49-4FE0-BED2-D9093619E73F!

can anyone help on this quickly?

"realm": "12.2.1",
 "react-native": "0.71.14",

node version: 16.18.0

### Can you reproduce the bug?
Always

### Reproduction Steps
while upgrading to 0.71.14 from 0.67.4. build failing with realm so upgraded from 10.9.1 to 12.2.1.
disable hermes enable chrome debugging.

### Version
12.2.1

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
all versions

### Build environment
Which debugger for React Native: ..
Chrome Debugger

### Cocoapods version
1.12.0

**Comment by vinaykumar0339** [comment]
@takameyer thank you for your quick reply. 

Do you have any idea about this Hermes staging builds issues https://github.com/facebook/react-native/issues/41737
It would be more helpful to us if you have any idea on this 😊

**Comment by vinaykumar0339** [comment]
@takameyer I did not enable the Chrome debugger. Opened Safari to debug without Hermes. 
for the source map of the code I modified the Appdelegate.mm file below

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
 {
   #if DEBUG
     NSURL *nsUrl = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios"];
     return [NSURL URLWithString:[[nsUrl absoluteString] stringByAppendingString:@"&inlineSourceMap=true"]];
   #else
     return [CodePush bundleURL];
   #endif
 }

but still same error coming.
Error: could not find the realm binary. as above image.

**Comment by kneth** [comment]
@vinaykumar0339 Can you provide a repro case for us?

**Comment by vinaykumar0339** [comment]
@kneth thanks for your reply it shows an error when we select **Automatically Show Web inspector for JSContext**
if you open the debugger after app loads its working fine only.

**Comment by kneth** [comment]
@vinaykumar0339 Do you observe the same behavior with our [template app](https://github.com/realm/realm-js/tree/main/templates/react-native-template)?
