### ISSUE TITLE
Device-Sync clientRest mode typescript error

### ISSUE THREAD

**Issue by maichongju** [realm/realm-js#6316]
### How frequently does the bug occur?

Always

### Description

When setting the clientRest mode on react native with typescript. Typescript will report that the `value` is not assignable to type ClientResetMode.

The code still works, but it is a bug that should be fixed with the typing issue. 

### Can you reproduce the bug?

Always

### Reproduction Steps

Add the following code in the app.

```typescript
<RealmProvider
  schema={[FriendRequest]}
  sync={{
    flexible: true,
    clientReset:{
      mode: 'manual', // <-- Here the type error show up
      onManual: (session, path) => {
        // handle manual client reset here
      },
    },
    onError: (session, error) => {
      logger.error(`Realm sync error: ${error}`);
    }
  }}

>
  // Rest of the code
</RealmProvider>
```

### Version

"realm": "^12.3.1",, "@realm/react": "^0.6.2",

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Win11 23H2

**Comment by maichongju** [comment]
Yes. I believe I got misled by the documentation from [here](https://www.mongodb.com/docs/realm/sdk/react-native/sync-data/handle-sync-errors/#manual-mode) and [here](https://www.mongodb.com/docs/realm/sdk/react-native/sync-data/client-reset-data-recovery/#configure-realm-to-use-manual-client-reset). As you can see it is telling us to use the string `"manual"` for the mode. But now I look at other code blocks, they did use the `ClientRestMode`. 

Is there any chance you know how to report this kind of documentation inconsistency?

**Comment by elle-j** [comment]
Thanks for bringing it to our attention anyway! I'll let our Docs team know 👍 

Atlas Device SDK (Realm) docs repo is here: https://github.com/mongodb/docs-realm
