### ISSUE TITLE
does realm support react-native 0.73?

### ISSUE THREAD

**Issue by karam1ashqar** [realm/realm-js#6339]
### Problem

I tried to update to react-native 0.73 and got some errors related to node-fs in realm, so i'm wondering if the package is supporting RN 0.73

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by kneth** [comment]
@karam1ashqar

I am closing the issue, and please create a new "bug report" and fill out all fields. Without more information, we cannot help.
