### ISSUE TITLE
posix_fallocate() failed: Operation not supported on transport endpoint

### ISSUE THREAD

**Issue by N3TC4T** [realm/realm-js#6349]
### How frequently does the bug occur?

Always

### Description

Using realm inside [Samsung secure folder](https://www.samsung.com/uk/support/mobile-devices/what-is-the-secure-folder-and-how-do-i-use-it/) will cause the app to crash with the message:
 ```
posix_fallocate() failed: Operation not supported on transport endpoint: Operation not supported on transport endpoint (95)
```

This happened after upgrading `realm` from `v11.10.2` to `v12.2.0`, I believe [multiple processes support](https://github.com/realm/realm-core/issues/1845) for realm encryption added in `v12` is the cause of this issue.

I see a duplicated issue in https://github.com/realm/realm-dotnet/issues/3482 as well.

### What services are you using?

Local Database only - using encryption

### Platform OS and version(s)

Android - Galaxy S9 MOD. SM-G9600

**Comment by kneth** [comment]
@N3TC4T A fix is released in v12.6.0.
