### ISSUE TITLE
Manual link Realm for windows

### ISSUE THREAD

**Issue by daninaga** [realm/realm-js#635]
hi there, i would like to know how i can manually link realm to my react-native project since i'm using windows and the link script seems to not work.

i created a thread to ask for how to do this because in the official documentation there is only the `react-native link realm` mode and no further explanation on how to do it manually in cases of problem.

**Comment by alazier** [comment]
Were you able to get things working on windows? I do not have a windows machine nor have I had the time to try to get things working or support people working on windows, but if you have been able to get things working this might be useful for other developers.

**Comment by daninaga** [comment]
hey there, the only way that i found around this was to use a pre-built project with all the dependencies and links already done.
then i just swaped the code inside the original project with my code.
