### ISSUE TITLE
Expo: Android builds failed when @realm/react installed

### ISSUE THREAD

**Issue by dancurtis144** [realm/realm-js#6383]
### How frequently does the bug occur?
Always

### Description
When creating a local build using EAS from Expo, the Android build fails with the following error message.

`[RUN_GRADLEW] FAILURE:
[RUN_GRADLEW] Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-modules-core$android-annotation:compileKotlin'.
[RUN_GRADLEW] > 'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
[RUN_GRADLEW]   Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED
[RUN_GRADLEW] in 23s
[RUN_GRADLEW] 17 actionable tasks: 17 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1`

This does not occur on any builds before the package was installed and also does not occur if just realm is installed. iOS builds will run successfully.

Installed versions
React: 18.2.0
React Native: 0.72.6
Expo: 49.0.13
Realm: 12.5.1
@realm/react: 0.6.2

### Can you reproduce the bug?
Always

### Reproduction Steps
Install realm into an Expo project
Install @realm/react into an Expo project
Run a local build

### Version
12.5.1

### What services are you using?
Local Database only

### Are you using encryption?
No

### Platform OS and version(s)
Android all versions

### Build environment
Which debugger for React Native: ..

**Comment by kneth** [comment]
Please provide a sample project which can reproduce the issue
