### ISSUE TITLE
Support DISTINCT queries on dictionary

### ISSUE THREAD

**Issue by gauravbordoloi** [realm/realm-js#6387]
### How frequently does the bug occur?

Always

### Description

I have a model with the below property

```
class ProductModel extends Realm.Object {
    static schema = {
        name: "ProductModel",
        properties: {
            _id: "uuid",
            name: { type: "string", indexed: true },
            attributes: {
                type: "dictionary",
                objectType: "string",
                default: {},
            },
        },
        primaryKey: "_id",
    };
}
```

How can I find all the distinct values of `attributes`?
I am trying to use the below code but it's not working
```
realm.objects(ProductModel).filtered("status == $0 DISTINCT(attributes.@keys)", "PUBLISH")
```

However, I am able to get distinct values of a particular key easily by the below code
```
//attr = "Random String"
realm.objects(ProductModel).filtered(`status == $0 DISTINCT(attributes['${attr}'])`, "PUBLISH")
```

### Can you reproduce the bug?

Always

### Version

12.5.1

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Windows 11

**Comment by ironage** [comment]
Hi @gauravbordoloi we don't currently support sorting or distinct on a collection. What do you expect the behaviour of distinct to be, given dictionaries with the following sets of keys: `{a, b, c}, {a, b}, {c}`? When talking about comparing collections, we usually need to specify the match behaviour: ANY/ALL/NONE. So then we might be looking for syntax like `DISTINCT(ALL attributes)`? Is that the feature you are looking for?

**Comment by gauravbordoloi** [comment]
Hi @ironage , I have multiple data like these,
```
[
    {
        "name": "Levis Shirt",
        "attributes": {
            "color": "White",
            "size": "XL"
        }
    },
    {
        "name": "Nike Shirt",
        "attributes": {
            "color": "Red",
            "size": "L"
        }
    },
    {
        "name": "Adidas Shirt",
        "attributes": {
            "color": "Black",
            "size": "XXL"
        }
    }
]
```

What I want to do is 
1. fetch all the attribute keys without duplicates - Result (color, size)
2. fetch all the attribute values for a particular key without duplicates- Result (color=White,Red,Black)

2nd point, I am able to get the data using the query
//attr = "color"
`realm.objects(ProductModel).filtered(`status == $0 DISTINCT(attributes['${attr}'])`, "PUBLISH")`

but for the 1st point, nothing is working. I tried the below code but it doesn't work
`realm.objects(ProductModel).filtered(`status == $0 DISTINCT(attributes@.key`, "PUBLISH")`

**Comment by ironage** [comment]
@gauravbordoloi we don't currently support the query you are trying to do. Fundamentally, our query system produces matching objects, not a collection of matching properties. I think what you want is an advanced use of [projections](https://github.com/realm/realm-core/issues/1037).
A solution for you today would be to also insert your keys into an independent class that tracks unique keys. So every time you insert into the `attribute` dictionary, you could also call
```realm.create("AllKeys", {_id: "myKey"}, UpdateMode.Modified); // UpdateMode.Modified makes this an upsert```
Insertion/lookup is fast because a primary key is indexed. Then to get all keys, you iterate over all objects of this class
```realm.objects("AllKeys");```
Would this work for you?

**Comment by gauravbordoloi** [comment]
Hi @ironage 
Understood and yeah the other table will work for me. Thank you. You can close the issuw.
