### ISSUE TITLE
sync example

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#640]
@alazier assuming this meant for Node or did you mean React Native (or both?)

**Comment by alazier** [comment]
This was for node. But we should also have one for react native, maybe the todo app?

**Comment by bigfish24** [comment]
yeah a simple version of RealmTasks would be great. @dhmspector thoughts on helping?

**Comment by kristiandupont** [comment]
So that will be a web version of tasks that communicates with the server over web sockets?

**Comment by alazier** [comment]
Not sure we have decided what we want to do for node yet. Global notifier for realm tasks could be on option. Webapp would be another. I created a separate ticket for the realm-tasks for rn.

**Comment by bigfish24** [comment]
for node, I was assuming we could use https://github.com/realm/realm-sync-demos/tree/master/textscanner since it is a straight forward example of the global notifier

**Comment by kristiandupont** [comment]
This is being tracked in #643
