### ISSUE TITLE
All dependency versions should be taken from dependencies.list

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#644]
Right they also exist in download-core.sh @sorenvind

**Comment by alazier** [comment]
@radu-tutueanu - we should be using the versions in this file in `download-core.sh`. Also, `download-core.sh` now seems to be broken for react-native - we need to unzip/untar files into separate directories for node and react-native as they require different distributions. Now that node is using the `sync` directory rather than `node-sync`, react native is trying to link to the node binaries which obviously doesn't work.

**Comment by radu-tutueanu** [comment]
Pushed a fix for dependencies.list
I see that you fixed the script for react-native.

Will push fixes for:
1) Only download core when not downloading sync
2) Support running the node tests on linux
