### ISSUE TITLE
Please make compatible to use latest version with old react native versions.

### ISSUE THREAD

**Issue by somasekharkakarla** [realm/realm-js#6460]
### Problem
Our project currently using react native version v0.70.5 and We have some issues with other libraries which we are resolving and soon we will upgrade the react native to latest version. We want to use latest realm in our project. But document shows we can only use React Native >= v0.71.4. Can we use latest realm with react native 0.70.5

### Solution
Support at least last 5 version.

### How important is this improvement for you?
Would be a major improvement

### Feature would mainly be used with
Local Database only

**Comment by somasekharkakarla** [comment]
Hi @takameyer, any update on this?

**Comment by takameyer** [comment]
@somasekharkakarla unfortunately the latest Realm has a hard dependency on features released in v0.71 of React Native.  You will not be able to use the latest Realm with anything earlier than that.
