### ISSUE TITLE
"Realm at path already opened with different sync user" upon reopening with identical configuration

### ISSUE THREAD

**Issue by craigdrayton** [realm/realm-js#6461]
### How frequently does the bug occur?
Always

### Description
I have a React Native app with Realm and Device Sync configured as per [the starter docs](https://www.mongodb.com/docs/realm/sdk/react-native/quick-start/#configure-and-access-a-synced-realm).

I am trying to use [Expo TaskManager](https://docs.expo.dev/versions/latest/sdk/task-manager/) to run a background task where location data is written to Realm.

The background task runs in global context, outside of React, so I cannot access use hooks to access the Realm context.

So I attempt to connect to the Realm with `Realm.open()`, using identical configuration and the `app.currentUser` (anonymous auth) but I get this error:

`TaskManager: Task "LOCATION_TRACK" failed: [Error: Realm at path '/data/data/[redacted]/files/mongodb-realm/[redacted]/[redacted ID]/flx_sync_default.realm' already opened with different sync user.]`

I understood from this comment that I should be able to open the Realm twice successfully without error:
https://github.com/realm/realm-js/issues/6273#issuecomment-1869013164

### Stacktrace & log output
```shell
TaskManager: Task "LOCATION_TRACK" failed: [Error: Realm at path '/data/data/[redacted]/files/mongodb-realm/[redacted]/[redacted ID]/flx_sync_default.realm' already opened with different sync user.]
```

### Can you reproduce the bug?
Always

### Reproduction Steps
Create an expo app with Realm and Device Sync configured as per [the starter docs](https://www.mongodb.com/docs/realm/sdk/react-native/quick-start/#configure-and-access-a-synced-realm).

Realm works correctly inside React using hooks.

Attempt to open the Realm outside the React context, using the same config, and get the error.

```
const app = new Realm.App({ id: ATLAS_APP_ID });

    const realm = await Realm.open({
      schema: [LocationLog],
      sync: {
        flexible: true,
        user: app.currentUser,
      },
    });
```

### Version
^12.6.0

### What services are you using?
Atlas Device Sync

### Are you using encryption?
No

### Platform OS and version(s)
Windows

**Comment by kneth** [comment]
@craigdrayton From reading the documentation of Expo TaskManager it is unclear if a task is a thread or a process. The error message you see indicates that it is a process, since Realm currently doesn't support multi-process access for synced Realm (work in process but it will take some time before it is released).

You might consider using the same trick as our Electron users apply: One process handles device sync, and other processes open the Realm with the sync configuration set to true (yes, literally `sync: true,`).

**Comment by craigdrayton** [comment]
Thanks for your reply @kneth, really appreciate the help.

When I try the following in the background task:
```
const realm = await new Realm.open({
    schema: [LocationLog],
    sync: true,
  });
```
I get: `Expected 'sync' on realm configuration to be an object, got a boolean`.

If I pass the following config to RealmProvider in React Native:
```
  const realmConfig = {
    schema: [LocationLog],
    sync: true,
    closeOnUnmount: false,
  };
```
I get: `Expected 'partitionValue' on realm sync configuration to be an integer, string, ObjectId, UUID, or null, got undefined.`

**Comment by craigdrayton** [comment]
Downgrading to Realm `11.10.2` and @realm/react `0.5.2` resolves the validation errors (perhaps the `sync: true` workaround broke with version 12).

I haven't been able to get the `sync: true` workaround to work copying the pattern from [the Electron example](https://github.com/mongodb-university/realm-electron-advanced-quickstart/blob/main/renderer.js). But it looks like I have a different workaround working: using a different realm path for the background tasks from the foreground realm.

**Comment by kneth** [comment]
> perhaps the sync: true workaround broke with version 12

Yes, for v12, you can use `openSyncedRealmLocally` (set it to true - and no `sync` configuration).

**Comment by nirinchev** [comment]
Closing this as stale. Feel free to reopen if you have more questions/Kenneth's suggestion didn't work.
