### ISSUE TITLE
Error compiling a project and run JEST test

### ISSUE THREAD

**Issue by Wawa-AlexSurabka** [realm/realm-js#6473]
### How frequently does the bug occur?

Always

### Description

When trying to compile a project and run unit tests, the compiler gives an error:
Cannot find module '../generated/ts/realm.node' from 'node_modules/realm/dist/bundle.node.js'
Using Codefresh with Alpine 3.9 node v18.17.1

When compiling on Windows 11, node v18.17.1 Typescript - everything works fine (Build succesful, unit test works)

This may be related to https://github.com/realm/realm-js/issues/5799

`npx prebuild-install --runtime napi`
`No prebuilt binaries found (target=6 runtime=napi arch=arm64 libc=musl platform=linux)`

### Stacktrace & log output

```shell
● Test suite failed to run

    Cannot find module '../generated/ts/realm.node' from 'node_modules/realm/dist/bundle.node.js'

    Require stack:
      node_modules/realm/dist/bundle.node.js
      node_modules/realm/index.node.js
      electron/realm-dal/realm-connection-manager.ts
```

### Can you reproduce the bug?

Always

### Reproduction Steps

- Create docker container with alpine@latest
- Install node
- Create empty package.json
- npm install realm@12.6.0
- Check that we don't see the "generated" folder in node_modules/realm

### Version

12.6.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Alpine 3.9

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
We don't support Alpine, but we know it is popular for containerized applications (see also #6150). Alpine is using Mucl and not glibc, and we need to produce binaries for this target.
