### ISSUE TITLE
Update docs/error message with instructions for fixing the missing constructor issue

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#648]
Users continue to hit #375 

We should update the error message with steps to try to address the issue as outlined here: https://github.com/realm/realm-js/issues/375#issuecomment-259596699

**Comment by brunobraga95** [comment]
any updates on this matter? I am trying to get it to work on Android, I have tried pretty much every solution I found online. No Success

**Comment by kristiandupont** [comment]
@brunobraga95 Are you building on an OSX machine?
