### ISSUE TITLE
Realm not working with nextjs App router

### ISSUE THREAD

**Issue by berjouji** [realm/realm-js#6489]
### How frequently does the bug occur?

Always

### Description

Hello, I'm trying to use Realm with nextjs(14) app router, it keeps giving the same error as mentioned in the stacktrace.
Tried downgrading to nextjs 13 and still have the same issue.

Any suggestions please?
PS: the same setup works fine with page router, the error happens with app router only

### Stacktrace & log output

```shell
Import trace for requested module:
./node_modules/realm/generated/ts/realm.node
./node_modules/realm/dist/bundle.node.js
./node_modules/realm/index.node.js
./src/server/auth.ts
./src/app/page.tsx
 ⨯ ./node_modules/realm/generated/ts/realm.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

=>npx create-next-app@latest
=> choose app router as config
=> on the main page.tsx code
`
import Realm from "realm"

async function getData() {
  const realm = await Realm.open()
  return []
}

export default async function Home() {
  const data= await getData()
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      
    </main>
  );
}
`

### Version

12.6.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

MacOS 14

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Hmm - it seems the process is trying to import and parse the native .node binary as source-code.
Please update your issue description to include the minimal steps required to reproduce this ourselves.

**Comment by berjouji** [comment]
I added a snippet on the reproduction steps.
Basically, any time you import Realm and use it, the error occurs. Regardless of if it's Synced or Local, Front or backened. 
It always gives the same error(again only in app router mode)

**Comment by kraenhansen** [comment]
I succeeded at reproducing this.

Next.js's default Webpack configuration doesn't have a loader specified for the native `realm.node` binary, but this can be easily configured by installing the `node-loader` dependency and adding this to your `next.config.mjs` file:

```js
const nextConfig = {
  webpack: (config, options) => {
    config.module.rules.push({
      test: /\.node$/,
      loader: "node-loader",
      options: {
        name: "[path][name].[ext]",
      },
    });
    return config;
  }
};
```

This does however not solve the problem in itself, as it fails to locate the binary on the file system:

```
Error: node-loader:
Error: dlopen(/Users/kraen.hansen/Projects/my-realm-next-app/.next/server/vendor-chunks//_next/node_modules/realm/generated/ts/realm.node, 0x0001): tried: '/Users/kraen.hansen/Projects/my-realm-next-app/.next/server/vendor-chunks//_next/node_modules/realm/generated/ts/realm.node' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/kraen.hansen/Projects/my-realm-next-app/.next/server/vendor-chunks//_next/node_modules/realm/generated/ts/realm.node' (no such file), '/Users/kraen.hansen/Projects/my-realm-next-app/.next/server/vendor-chunks//_next/node_modules/realm/generated/ts/realm.node' (no such file)
```

I do see the file at `.next/server/node_modules/realm/generated/ts/realm.node` so I suspect some more Webpack configuration might be able to eventually resolve this, but I suspect you'll have more success asking around for a solution with the Next.js community. This doesn't seem to be specific to our library, but instead should be a universal issue to all projects trying to use dependencies with native .node binaries.

Even if you do get the Realm native module to load, you should be away of [the limitations of the edge runtime](https://nextjs.org/docs/app/api-reference/edge#unsupported-apis), most notably, that it doesn't support "Native Node.js APIs", which most likely will include loading the Realm native binary 😞

At the moment we do not actively test compatibility with Next.js and we make no guarantees that we're actually compatible.
Please feel free to report back in this issue and share your progress to help others trying to use Realm with Next.js, but for now I'll close the issue as we don't have explicit plans to support Next.js at the moment. I'll reopen if that changes.

**Comment by kraenhansen** [comment]
I spent a bit more time playing around this and I succeeded at making [the "browser" preview of our SDK](https://www.mongodb.com/docs/realm/web/sync/#install---set-up-manually) used from a client-side component (thanks to my team-mate @elle-j). Full disclosure, it's possible but not pretty 😞

> [!NOTE]  
> The following steps are messy and definitely not the developer experience we would want if we adopt Next.js as a supported target in the future:

### Install the browser preview version of the SDK

```
npm install realm@12.0.0-browser.2
```

Please read the current limitations of this browser preview of the SDK: https://www.mongodb.com/docs/realm/web/sync/#limitations-of-device-sync-on-web

### Modify the `next.config.mjs` to allow top-level awaits

```
const nextConfig = {
  webpack: (config) => {
    config.experiments.topLevelAwait = true;
    return config;
  }
};
```

### Patch `node_modules/realm/dist/realm-js-wasm.mjs`

The default babel config used by Next injects code which breaks the realm-js-wasm.mjs file, with the following error:

> Module parse failed: Identifier 'Module' has already been declared (5:12)

With a bit more investigation, we could probably find a babel configuration that doesn't do this or we could probably tune emscripten to generate code which is more compatible, but for now the workaround I'm using is modifying the file by removing the following code:

```js
var Module=typeof Module!="undefined"?Module:{};
```

### Create a `realm.tsx` file

```tsx
"use client";

import { useState } from "react";

type Realm = import("realm").Realm;
type Person = { name: string };

async function getRealm(): Promise<Realm> {
  const { Realm } = await import("realm");

  const realm = new Realm({
    schema: [ { name: "Person", properties: { name: "string", age: "int" } } ]
  });
  
  if (realm.isEmpty) {
    realm.write(() => {
      realm.create("Person", { name: "Alice", age: 32 });
    });
  }

  return realm;
}

export function usePersons(): Person[] {
  const [realm, setRealm] = useState<Realm | null>(null);
  getRealm().then(setRealm);
  return realm ? realm.objects<Person>("Person").map(person => person) : [];
}
```

### Create a `Greeting.tsx` file exporting a client-side component

```tsx
"use client";

import { usePersons } from "./realm";

export function Greeting() {
  const persons = usePersons();
  return <p>Hello {persons.map(p => p.name).join(", ")}!</p>
}
```

### Use this `Greeting` component on the `page.tsx`

```tsx
import styles from "./page.module.css";
import { Greeting } from "./Greeting";

export default function Home() {
  return (
    <main className={styles.main}>
      <div className={styles.description}>
        <Greeting />
      </div>
    </main>
  );
}
```

**Comment by berjouji** [comment]
Hello @kraenhansen, 
Thank you for the suggestions, I really appreciate it.
I think doing it this way adds more complexity than necessary. We'll just switch to using the page router instead for the time being as it doesn't cause the same problem.
I'll continue investigating the issue with app router and will come back if I find anything interesting.
