### ISSUE TITLE
Data loss after migrating to flexible sync affecting first write per realm.

### ISSUE THREAD

**Issue by DanW82** [realm/realm-js#6491]
### How frequently does the bug occur?

Always

### Description

The first write to a new realm appears to have worked but disappears a couple of seconds later. If a read is done from the realm first it works.

We have a count on the screen showing the number of items in the realm we are working on. When we add the first item the count goes to 1 but then reduces to 0 a couple of seconds later.

Steps to reproduce.
- Start in partition based sync
- Migrate to flexible sync
- Get new realm with new Realm(config). See below for config
- realm.write(….)
- At this point the item initially appears in the LOCAL realm
- A couple of seconds later it disappears from the local realm
- It never appears in the backend atlas database.

Android 11
SDK Node JS 12.6
Type: Partition based sync migrated to flexible sync

Config used to open the realm
```
{
    "schema" : "removed to save space",
    "path": "/data/data/com.XXXXX/files/mongodb-realm/XXXXX/XXXXXX/temporary/opUnit%3D7523%26tourDate%3D2024-02-15%26tourName%3DMA30.realm",
    "sync":
    {
        "user" : "removed to save space",
        "partitionValue": "opUnit=7523&tourDate=2024-02-15&tourName=MA30",
        "existingRealmFileBehavior": { "type": "openImmediately" },
        "newRealmFileBehavior":{ "type": "downloadBeforeOpen" },
        "clientReset":{ "mode": "manual" }
    }
}
```

Workaround - do any operation to read and the issue doesn't seem to occur:
  ```
const realm = new Realm(config);
  const length = realm.objects(objectType);
  console.log(`Realm length: ${length} partitionKey: ${partitionKey}`);
  return realm;
```

### Can you reproduce the bug?

Always

### Version

12.6.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

Android 11

### Build environment

Which debugger for React Native: ..

**Comment by nirinchev** [comment]
This is probably something you'd like to [file a support ticket](https://support.mongodb.com) for. The team will need to review the server-side and the client-side logs to understand what's happening. My gut feeling is that there's a compensating write being sent by the server because it deems the first write invalid, but we'll need to see the logs to validate that assumption.
