### ISSUE TITLE
Jest tests fail with Node version 16

### ISSUE THREAD

**Issue by mattlewer** [realm/realm-js#6509]
### How frequently does the bug occur?

Always

### Description

According to this page:
https://github.com/realm/realm-js/blob/HEAD/COMPATIBILITY.md

Node 16 is compatible with Realm 12.6.0. 

But unfortunately when running Jest tests, the tests fail. This has been resolved by upgrading Node in our pipeline to 18, where the tests then pass.

Errors received with node 16:
```
TypeError: Cannot read properties of undefined (reading 'bind')

    > 1 | import Realm from 'realm';
```

```
    TypeError: Cannot read properties of undefined (reading 'bind')

      1 | import 'react-native-get-random-values';
    > 2 | import {createRealmContext} from '@realm/react';
 ```

### Can you reproduce the bug?

Always

### Reproduction Steps

react-native: "0.72.6"
realm: "12.6.0"
@realm/react: "0.6.2"
node: 16

### Version

12.6.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android/iOS

**Comment by kneth** [comment]
Unfortunately we haven't updating the compatibility matrix for a while. In general, we only support either current and active version of node (as I write this comment, that's version 20, 21 and 22). We suggest that you upgrade, and if the issue persists, please create a new issue.
