### ISSUE TITLE
Upgrading to v12 causes duplicate to be created instead of updated when updating nested object

### ISSUE THREAD

**Issue by mattlewer** [realm/realm-js#6517]
### How frequently does the bug occur?

Always

### Description

Similar issues:
https://github.com/realm/realm-js/issues/6322
https://github.com/realm/realm-js/issues/6239

We have been using Realm v11.10.1 without issues, since upgrading to v12.6.0, we are encountering errors updating nested objects.

We receive an updated version of an object from our server in JSON format.
We want to update the Realm object in the devices local database so that the changes are reflected.

The object we have looks like this, with each name being its own Realm table:
```
Session: {
    User: {
        Organisations: []
    }
}
```

We update the object in Realm like so:
```
  const update = (updates: () => void) => {
    realm.write(() => {
      updates();
    });
  };
```

and call this function as such:
```
update(() => {
    session.user = updatedUser;
});
```

We receive this error:
`Attempting to create an object of type 'User' with an existing primary key value '341'`

In an attempt to fix this, we have adapted the update function to be the following, this also works on v11.10.1 without issue:
```
const update = (original: T, changes: Partial<T>) => {
    realm.write(() => {
      realm.create(
        'session',
        merge({}, original, changes),
        Realm.UpdateMode.Modified,
      );
    });
};
```
  
Which is then called as such:
```
update(session, {
          user: updatedUser,
});
```

This also fails, however giving an error a layer deeper:
`Error: Attempting to create an object of type 'Organisation' with an existing primary key value '454'`

### Can you reproduce the bug?

Always

### Reproduction Steps

Have an object stored in Realm
Attempt to update this objects nested fields, using an interfaced JSON object, containing the primary key
Receive error

### Version

12.6.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android & iOS

### Build environment

Which debugger for React Native: ..

**Comment by kneth** [comment]
@mattlewer Thank you for reporting. Is it possible for you to share the schema?

**Comment by mattlewer** [comment]
> @mattlewer Thank you for reporting. Is it possible for you to share the schema?

Hopefully this helps


**Config**
``` export const config: Realm.Configuration = {
  schema: [
    OrganisationRealm,
    Session,
    User,
  ],
  schemaVersion: 4,
};
export default createRealmContext(config);
```

 **Session**
``` import 'react-native-get-random-values';
import {Realm} from '@realm/react';
import User from './User';
import idGenerator from '../../services/idGenerator';

export default class Session extends Realm.Object {
  client_id!: string;
  user!: User;

  static create(user: User): Object {
    return {
      user: user,
    };
  }

  static schema = {
    name: 'Session',
    primaryKey: 'client_id',
    properties: {
      client_id: {type: 'string', default: () => idGenerator.generate()},
      user: 'User',
    },
  };
}
```

**User**
```
import 'react-native-get-random-values';
import {Realm} from '@realm/react';
import idGenerator from '../../services/idGenerator';
import {Organisation} from './Organisation';

export default class User extends Realm.Object {
  client_id!: string;
  id!: number;
  inviting_organisations?: Organisation[];

  static schema = {
    name: 'User',
    primaryKey: 'id',
    properties: {
      client_id: {type: 'string', default: () => idGenerator.generate()},
      id: 'int',
      inviting_organisations: 'Organisation[]',
    },
  };
}
```

**Organisation**
```
import 'react-native-get-random-values';
import {Realm} from '@realm/react';
import idGenerator from '../../services/idGenerator';

export interface Organisation extends Syncable {
  client_id: string;
  id: number;
  name: string;
  created_at: Date;
  updated_at: Date;
}

export class OrganisationRealm extends Realm.Object implements Organisation {
  client_id!: string;
  id!: number;
  name!: string;
  created_at!: Date;
  updated_at!: Date;
  resource!: string;

  static schema = {
    name: 'Organisation',
    primaryKey: 'id',
    properties: {
      client_id: {type: 'string', default: () => idGenerator.generate()},
      id: 'int',
      name: 'string',
      created_at: {type: 'date', default: () => new Date()},
      updated_at: {type: 'date', default: () => new Date()},
      resource: {type: 'string', default: SyncResource.Organisations},
    },
  };
}
```

**Syncable**
```
export interface Syncable {
  id?: number;
  client_id?: string;
  created_at: Date;
  updated_at: Date;
  is_synced?: boolean;
  resource?: string;
}
```

**SyncResource** 
 ``` 
 export enum SyncResource {
  Organisations = 'organisations',
}
```

**Comment by kneth** [comment]
It sounds like the same as https://github.com/realm/realm-js/issues/6129 and we released a fix for it in v12.2.0.

**Comment by mattlewer** [comment]
Has this potentially regressed since as I'm using v12.6.0? Will downgrade to v12.2.0 to see if it makes a difference and get back to you

**Comment by kneth** [comment]
> downgrade to v12.2.0 to see if it makes a difference

Thanks!

**Comment by mattlewer** [comment]
Same error unfortunately:
`Error: Attempting to create an object of type 'Organisation' with an existing primary key value '454'.`

**Comment by nirinchev** [comment]
So the first error is expected:

```js
realm.write(() => {
	session.user = updatedUser;
});
```

where `updatedUser` is an unmanaged object will attempt to first add it to realm and then set `session.user` to it. In the case where the user already exists, you're supposed to get an error.

The second code snippet points to a legitimate bug though, however I've been unable to reproduce it. I've attached my attempt to repro this - if you can modify it in a way that triggers the duplicate PK error, let us know and we'll continue investigating.

[Archive.zip](https://github.com/realm/realm-js/files/14672382/Archive.zip)

**Comment by mattlewer** [comment]
Thank you for getting back to me, I will have a look ASAP.

Given the above situation, what would be the correct way to update this nested object? I would assume that because it comes down with the same primary key as the object currently stored in the DB, it would successfully match these up and update it?

Also as this worked fine in v11, is there something specific that has caused this breaking change? If I downgrade again, everything works as intended.

**Comment by mattlewer** [comment]
Yep, both worked fine with v11, will try and reproduce with a test when I have a moment and get back to you

**Comment by kneth** [comment]
@mattlewer 

> will try and reproduce with a test when I have a moment and get back to you

Any chance you have a moment to create a reproduction case for us?
