### ISSUE TITLE
Device Sync stoped working: could not decode next message: failed to get reader: WebSocket closed: failed to acquire lock: context deadline exceeded

### ISSUE THREAD

**Issue by ampopdev** [realm/realm-js#6519]
### How frequently does the bug occur?

Once

### Description

Scenario is no READ or WRITE operations permitted and user is stuck. We should expect at least a client reset in this case to unblock user. Getting constant error on server logs: 

> could not decode next message: failed to get reader: WebSocket closed: failed to acquire lock: context deadline exceeded

### Stacktrace & log output

```shell
Error:


could not decode next message: failed to get reader: WebSocket closed: failed to acquire lock: context deadline exceeded

Logs:

[
  "Connection was active for: 1m4s"
]
Function Call Location:

DE-FF

Remote IP Address:

151.47.237.19

SDK:

JS v12.6.0

Framework:

react-native v0.71.8

Platform:

iOS v16.3
```

### Can you reproduce the bug?

Sometimes

### Version

12.6.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

iOS v16.3

### Build environment

Which debugger for React Native: ..

**Comment by nirinchev** [comment]
This is a server-side issue and not a bug with the JS SDK. Please open a case in https://support.mongodb.com.
