### ISSUE TITLE
Random SIGSEGV error and crash on production

### ISSUE THREAD

**Issue by puneetmyt** [realm/realm-js#6600]
### How frequently does the bug occur?

Sometimes

### Description

Platform: Android
Devices: Pixel Pro 8, Galaxy Tab S7 FE (SM-T733)
Environment: Production

We are facing random crashes for a couple of users in the production build of our React Native app. I have gone through similar issues reported by users; many of them are due to incompatibility between Reanimated and Realm. However, we do not use Reanimated. I'm attaching the Bugsnag stack trace. Please let me know if you require other details. Thanks

### Stacktrace & log output

```shell
SIGSEGV: Segmentation violation (invalid memory reference)

0  librealm.so +0x47435c      0x6a6a9a235c
1  librealm.so +0x467244      0x6a6a995248
2  librealm.so +0x496220      0x6a6a9c4224
3  librealm.so +0x495f34      0x6a6a9c3f38
4  librealm.so +0x422904      0x6a6a950908
5  librealm.so +0x41c10c      0x6a6a94a110
6  librealm.so +0x41c054      0x6a6a94a058
7  librealm.so +0x41bfcc      0x6a6a949fd0
8  librealm.so +0x41ade4      0x6a6a948de8
9  libjscexecutor.so +0x2d794 0x738eeb1798
10 libjsc.so +0x2575ac        0x738f2ae5b0
11 libjsc.so +0x33cf30        0x738f393f34
12 libjsc.so +0x250db4        0x738f2a7db8
```

### Can you reproduce the bug?

No

### Reproduction Steps

We are unable to reproduce the crash. It's been reported by couple of our users having  Pixel Pro 8, Galaxy Tab S7 FE (SM-T733) device.

### Version

"realm": "^11.10.2"

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android  14 

### Build environment

Which debugger for React Native: ..

### Cocoapods version

NA

**Comment by kraenhansen** [comment]
Without a clear reproduction we won't be investigating crashes on v11 and as such, I'll close this issue.

As we rewrote all native code in the v12 and I'd expect this issue to have been fixed there, is there anything holding you back from upgrading to the v12 of our library?
