### ISSUE TITLE
MIT?

### ISSUE THREAD

**Issue by resistdesign** [realm/realm-js#663]
Why not an MIT license?

**Comment by bmunkholm** [comment]
Why would you prefer that @resistdesign?

**Comment by resistdesign** [comment]
Isn't it a lot less restrictive?

**Comment by teotwaki** [comment]
Disclaimer: don't take legal advice from someone on the internet. I am not a lawyer.

Not really. Even though Apache introduces a few restrictions over trademark usage (that protects Realm), I don't feel like it can be considered as "a lot more restrictive". What restrictions were you thinking of? An example of a much more restrictive licence would be the GPL, or, even more so, the Affero GPL.

In addition, Apache includes an explicit patent licence. This protects you. MIT does not offer that protection.

A couple of resources on the subject:

- https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license
- http://www.oreilly.com/openbook/osfreesoft/book/ch02.pdf
- https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

If you have any specific reasons for us to change the licence, we would be happy to look into it.

**Comment by resistdesign** [comment]
Here is the aspect I'm concerned with from the MIT License:

```
deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so
```

Is all of this possible with your current license?

**Comment by teotwaki** [comment]
> Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.

https://www.apache.org/licenses/LICENSE-2.0

**Comment by resistdesign** [comment]
Can it be included in something else that is sold and/or redistributed by those who receive it?
