### ISSUE TITLE
What problem does persisting object as it is withosolve?

### ISSUE THREAD

**Issue by imvetri** [realm/realm-js#665]
I'm preparing for a presentation on realm as well as a demo. But before that wanted to understand problem it solves in the first place.

 I couldn't find relevant realm stackoverflow channel to post this question. Pls let me know if there is any, i shall continue the diacussion there.

**Comment by kristiandupont** [comment]
Hi @imvetri, are you talking about Realm from a React Native perspective or from a Node perspective?

**Comment by imvetri** [comment]
I am talking from Node perspective. 
Reference article -[Object database](https://realm.io/news/first-object-database-realm-node-js-server)

**Comment by kristiandupont** [comment]
Ok. So is your question why you would want to persist objects in Node?

**Comment by imvetri** [comment]
No. right now application persist objects by serializing it to a string and eventually into a file.

in case of RealmJs, the developer need not worry about serializing it, instead ReamJS takes care of it.

This is my understanding and it is a very good approach. 

I wanted to confirm is there anything else RealmJS could do apart from this?

**Comment by kristiandupont** [comment]
That's basically what Realm does, correct. In addition to that, you can run queries on your data. And with the SDK's that support sync (which doesn't yet apply to the Node one), you can automatically synchronize data between devices and servers.  Stay tuned for updates on that.
