### ISSUE TITLE
logInWithFacebook is not working with iOS Limited Login

### ISSUE THREAD

**Issue by mydesweb** [realm/realm-js#6710]
### How frequently does the bug occur?

Always

### Description

I obtain the token as described here [Login Manager with Limited Login + Authentication Token](https://github.com/thebergamo/react-native-fbsdk-next?tab=readme-ov-file#login-manager-with-limited-login--authentication-token) then call `logInWithFacebook(authenticationToken)`

I receive this error

[Realm.App - error] App: log_in_with_credentials failed: 401 message: unauthorized

### Can you reproduce the bug?

Always

### Version

12.9.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

latest

### Build environment

Which debugger for React Native: ..

**Comment by nirinchev** [comment]
Please file a support ticket at http://support.mongodb.com as the social login authentication is not something the Realm JS SDK has control over - we just send the token to the server.
