### ISSUE TITLE
Issue building for ARM/Linux

### ISSUE THREAD

**Issue by sonofjavascript** [realm/realm-js#6719]
### How frequently does the bug occur?

Always

### Description

I am following these steps https://github.com/realm/realm-js/blob/main/contrib/building.md#building-for-nodejs.

While running `npm run bundle --workspace realm` throws an error due to bundle script does not exist in realm package.

Could you help on this please?

### Stacktrace & log output

```shell
npm ERR! Lifecycle script `bundle` failed with error: 
npm ERR! Error: Missing script: "bundle"

To see a list of scripts, run:
  npm run 
npm ERR!   in workspace: realm@12.9.0 
npm ERR!   at location: /realm-js/packages/realm
```

### Can you reproduce the bug?

Always

### Reproduction Steps

```
export REALM_USE_SYSTEM_OPENSSL=1
git clone https://github.com/realm/realm-js
cd realm-js
git submodule update —-init —-recursive
npm install --ignore-scripts
npm run build:node --workspace realm
npm run bundle --workspace realm
```

### Version

12.9.0

### What services are you using?

-- select --

### Are you using encryption?

Yes

### Platform OS and version(s)

debian

**Comment by kraenhansen** [comment]
We've renamed this to "build:ts" since we're not longer bundling the SDK:

```
npm run build:ts --workspace realm
```

Thanks for reaching out! I'll update the docs.

**Comment by sonofjavascript** [comment]
@kraenhansen we've managed to build within a specific architecture and build steps seems to complete successfully (`realm.node` is created).

Nest documentation step is: run `npm install realm-js-path`. We run it and a symlink is setup. After it, we start the application and seems the some dependencies are missing. 

```
Error: Cannot find module '@realm/fetch'
```

Which step are we missing? Could you help on that please?

**Comment by kraenhansen** [comment]
> Which step are we missing? Could you help on that please?

I suggest you do an `npm pack` in `packages/realm` and use that in your app, in which case the `@realm/fetch` dependency will be downloaded from NPM :+1:
