### ISSUE TITLE
mongodb realm sync App: log_in_with_credentials failed: 404 message: App not available in requested region: Client App ID=application-0-llfhjoe, App Location=US-VA ProviderRegion=aws-us-east-1, Server Location=IN-MB ProviderRegion=aws-ap-south-1

### ISSUE THREAD

**Issue by VikasPathaniaa** [realm/realm-js#6749]
### How frequently does the bug occur?

Always

### Description

i am integrating mongo db realm sync in my react js web application. my realm-web is working fine but it is not giving us realm.open function so i used react/realm it is giving us App: log_in_with_credentials failed: 404 message: App not available in requested region: Client App ID=application-0-llfhjoe, App Location=US-VA ProviderRegion=aws-us-east-1, Server Location=IN-MB ProviderRegion=aws-ap-south-1

### Can you reproduce the bug?

Always

### Version

react/realm 0.6.1

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

window

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Are you aware of the Realm JS Sync for Web preview that we've published? https://www.mongodb.com/docs/atlas/device-sdks/web/sync/
