### ISSUE TITLE
libary instalation issue

### ISSUE THREAD

**Issue by saifalitai** [realm/realm-js#6750]
### How frequently does the bug occur?

Always

### Description

Description
library is unable to install continue. showing install process 

package.json
"react-native": "0.66.5",
    "realm": "11.0.0-rc.0",
    "@realm/react": "0.3.0",
![Screenshot 2024-06-24 at 11 34 44 AM](https://github.com/realm/realm-js/assets/40918031/d52c71fa-ea83-4344-8b39-5e346406a325)

### Stacktrace & log output

```shell
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.14.2" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-config-airbnb@18.0.1" has incorrect peer dependency "eslint@^5.16.0 || ^6.1.0".
warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has incorrect peer dependency "eslint-plugin-import@^2.22.1".
warning " > eslint-plugin-import@2.20.0" has incorrect peer dependency "eslint@2.x - 6.x".
warning " > eslint-plugin-react@7.18.3" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > eslint-plugin-sonarjs@0.5.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > pixels-catcher@0.7.0" has unmet peer dependency "prop-types@>=15.7.2".
warning " > ts-jest@25.5.1" has incorrect peer dependency "jest@>=25 <26".
warning " > ts-jest@25.5.1" has incorrect peer dependency "typescript@>=3.4 <4.0".
[4/4] 🔨  Building fresh packages...
[-/2] ⠈ waiting...
[2/2] ⠈ realm
```

### Can you reproduce the bug?

Always

### Reproduction Steps

add package.json above mention library version and install node modules 

### Version

11.0.0-rc.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android and ios

### Build environment

Which debugger for React Native: ..

### Cocoapods version

cocoapods-1.15.2

**Comment by kraenhansen** [comment]
Can you share some details on the bandwidth of your network connection?

**Comment by saifalitai** [comment]
Internet speed below screenshot and latest version installed successfully but my react native not supported.
according to this document I have installed library 
see the document link : https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md

<img width="399" alt="Screenshot 2024-06-24 at 12 43 13 PM" src="https://github.com/realm/realm-js/assets/40918031/8a16abc9-3ac7-4e93-af83-cd0a78e35b27">

**Comment by kraenhansen** [comment]
Am I correct in my understanding that you're using React Native < 0.69.0?

If that's the case, we unfortunately cannot justify supporting a release candidate version of our library compatible with a React Native version that has dropped out of support long time ago. Good news is that since https://github.com/realm/realm-js/releases/tag/v12.11.0 our prebuild binaries no longer have a tight coupling to the JSI ABI. We haven't tested the v12.11.0 release with React Native 0.69.0, but there's a chance that it actually might "just work" ™️. If you're feeling adventurous, please consider taking it for a spin in your app - if it builds, you should be good 👍
