### ISSUE TITLE
after libary install facing below issue

### ISSUE THREAD

**Issue by saifalitai** [realm/realm-js#6752]
after libary install facing below issue 
    "@realm/react": "^0.8.0",
    "realm": "^12.11.0",
    "react-native": "0.66.5",

FAILURE: Build failed with an exception.

* Where:
Build file 'react-native/src/node_modules/realm/binding/android/build.gradle'

* What went wrong:
Could not compile build file '/Users/saif/Documents/Builder/dhpapp-285028-react-native/src/node_modules/realm/binding/android/build.gradle'.
> startup failed:
  General error during class generation: null. _BuildScript_
  
  groovy.lang.GroovyRuntimeException: null. _BuildScript_
  
  	at java.base/java.lang.Thread.run(Thread.java:829)
  Caused by: org.codehaus.groovy.syntax.SyntaxException: Operator ("===" at 34:30:  "===" ) not supported @ line 34, column 30.
  	at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.eval(BinaryExpressionHelper.java:301)
  	... 258 more
  
  1 error

_Originally posted by @saifalitai in https://github.com/realm/realm-js/issues/6750#issuecomment-2186678656_

**Comment by kraenhansen** [comment]
This error seems related to an outdated version of Groovy (`===` was introduced in 3.0.0 according to https://docs.groovy-lang.org/latest/html/documentation/core-operators.html), caused by an outdated Gradle / Groovy version related to the RN version.

You can try patching https://github.com/realm/realm-js/blob/1b24533db033d1cae13f2da62c3cb081cddb44e6/packages/realm/binding/android/build.gradle#L34 to use a double equal `==` instead of `===`. If it works we'd be happy to accept at PR for that.

```
 return File.separatorChar == '/' as char ? filePath : filePath.replace(File.separatorChar, '/' as char) 
```

**Comment by saifalitai** [comment]
after the above fix apply facing below issue 
> Task :realm:generateJsonModelDebug FAILED

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app > project :realm
         
         * Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugAssets'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.facebook.react:react-android:.
Required by:
    project :app > project :realm

**Comment by kneth** [comment]
Please provide a minimal project which can reproduce the issue.
