### ISSUE TITLE
Two different processes use the same local Realm

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#677]
When using Sync, if we have 2 processes that use the same user and and realm they connect to, they would use the same local realm. 

@alazier

**Comment by alazier** [comment]
Not sure we can do anything about this at the binding level. Seems like we might need a lockfile used when creating sync-sessions and having the second client fail, or just open the realm without a sync session piggybacking on the first. Thoghts @teotwaki ?

**Comment by radu-tutueanu** [comment]
I think we can work around this in the cases where the user does not specify the path. We do not have to reuse the same realm when the process restarts.

So I was thinking we can include a hash with a random element in the path.

**Comment by alazier** [comment]
We do need to reuse the same path - otherwise every time you restart an app you need to re-download the entire realm.

**Comment by radu-tutueanu** [comment]
I was wondering if that might be acceptable, but in mobile apps that is definitely an issue.

**Comment by radu-tutueanu** [comment]
Extra piece of info: since the path is relative, this issue is valid only for processes launched in the same folder.

**Comment by teotwaki** [comment]
I believe there is a flag in the Realm file that indicates whether it's already being synced. Might be worthwhile to throw if that's the case? The problem would come from the fact that a crashed process wouldn't unset that flag in the Realm file, and thus lock the user out of re-using that Realm file (unless we had an override API).

**Comment by alazier** [comment]
Is there a way in core to prevent multiple processes from opening the same realm? That might suffice.

**Comment by teotwaki** [comment]
Yes, typically you'd use `Group` instead of `SharedGroup`. Not really a viable option for sync.

**Comment by kristiandupont** [comment]
Is this a problem that we are seeing or a hypothetical one?

**Comment by radu-tutueanu** [comment]
In theory we should not get into that situation in the ROS...so right now it is a hypothetical one.
If a user runs 2 processes from the same folder opening the same synced realms, things might go wrong.

**Comment by kristiandupont** [comment]
With the work being done to prevent two sync agents attaching to the same realm, will this issue be resolved @radu-tutueanu?

**Comment by teotwaki** [comment]
@kristiandupont Yeah, although `sync` will throw an exception, so this will have to be handled by OS.

**Comment by kristiandupont** [comment]
So with that, and realm/realm-object-store#237, this is covered?

**Comment by radu-tutueanu** [comment]
Yes, that is correct. I could even argue that we should close the issue, as it is tracked in realm-object-store.
