### ISSUE TITLE
Error: Realm at path *** already opened with a different schema mode in React Native

### ISSUE THREAD

**Issue by bezenson** [realm/realm-js#6773]
### How frequently does the bug occur?

Always

### Description

Hello! I'm developing React Native app with realm. 

I'm initializing app with RealmProvider:

```
 <RealmProvider schema={[RealmList, RealmTask]}>
```

At some point I've decided to change schema:

```typescript
export class RealmTask extends Realm.Object<RealmTask> {
  _id: BSON.ObjectId = new BSON.ObjectId();
  completed: boolean = false;
  createdAt: Date = new Date();
  // date: Date | null = null;  <<<< BEFORE
  date?: Date; // <<<< AFTER
  listId!: BSON.ObjectId;
  order: number = 0;
  reminderEnabled: boolean = false;
  title: string = '';
  updatedAt: Date = new Date();

  static primaryKey = '_id';
}
```

And after that I've got error:

> Error: Realm at path '/Users/[user]/Library/Developer/CoreSimulator/Devices/F93F6540-1289-4F0A-9FFC-FAEAE781EDEA/data/Containers/Data/Application/5A6B5E22-3848-4D24-AF59-B7F2B0528A74/Documents/default.realm' already opened with a different schema mode.

I am developing on iOS simulator. 

1. I've tried to delete app
2. Tried to add `deleteRealmIfMigrationNeeded`
3. Deleted this file manually
4. Launched another clean simulator

Nothing helped. Only if I roll back schema changes.

How can I fix that? Really got stuck with it.

### Can you reproduce the bug?

Always

### Version

12.11.1

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17.5 Simulator

### Cocoapods version

1.15.2

**Comment by kneth** [comment]
@bezenson Is it possible that you open the Realm without schema or the old schema somewhere else in your app? The error message could hint that.

**Comment by bezenson** [comment]
Oh, that's true. I was calling `open()` in another place. Removing this fixed the issue. Thank you for pointing me out and sorry for bothering :)

**Comment by kneth** [comment]
@bezenson Good to hear that you found the second place
