### ISSUE TITLE
Realm does not build on iOS with `use_frameworks! :linkage => :static` as of version 12.12.0

### ISSUE THREAD

**Issue by gvanderclay** [realm/realm-js#6808]
### How frequently does the bug occur?

Always

### Description

Our React Native app fails to build when `use_frameworks! :linkage => :static` is set in the Podfile. This issue started occurring after upgrading to Realm JS v12.12.0. Given that this configuration was working in previous versions, we expected it to continue working after a minor version upgrade.

I believe the issue was introduced by #6791.

This issue is critical for our project as we rely on react-native-firebase, which requires the use_frameworks! :linkage => :static configuration.

### Stacktrace & log output

```shell
❌  (/Users/gvanderclay/workspace/my-app/node_modules/realm/binding/apple/RealmReactModule.mm:24:9)

  22 | #import <React/RCTInvalidating.h>
  23 | #import <ReactCommon/CallInvoker.h>
> 24 | #import <React-featureflags/react/featureflags/ReactNativeFeatureFlags.h>
     |         ^ 'React-featureflags/react/featureflags/ReactNativeFeatureFlags.h' file not found
  25 | #import <jsi/jsi.h>
  26 |
  27 | #import <arpa/inet.h>
```

### Can you reproduce the bug?

Always

### Reproduction Steps

I have created a minimal reproducible example to demonstrate the issue. The repository is available [here](https://github.com/gvanderclay/realm-useframeworks-build-error), and it includes detailed instructions on how to reproduce the build failure.

Note: The example uses Expo with expo-build-properties to set use_frameworks!, but the issue persists regardless of this context.

### Version

12.12.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS only

### Cocoapods version

1.15.2

**Comment by kraenhansen** [comment]
Thanks for reaching out and for the detailed reproduction!

> I believe the issue was introduced by https://github.com/realm/realm-js/pull/6791.

Git blame suggests it's more likely that this is caused by changes introduced in https://github.com/realm/realm-js/pull/6737. We actually ended up not relying on those feature flags anyway - what happens if you simply delete that import?

**Comment by sunrise1002** [comment]
I have the same issue with 
"realm": "^12.3.1"
"@realm/react": "^0.6.2"

**Comment by TirumalReddy** [comment]
I have the same issue with
"realm": "^12.6.2"

**Comment by gvanderclay** [comment]
> Thanks for reaching out and for the detailed reproduction!
> 
> > I believe the issue was introduced by #6791.
> 
> Git blame suggests it's more likely that this is caused by changes introduced in #6737. We actually ended up not relying on those feature flags anyway - what happens if you simply delete that import?

Thanks for the quick response!

I did test with that import deleted and the app successfully built and compiled.

**Comment by AlienDev66** [comment]
> I have the same issue with "realm": "^12.9.0", im going to try now with v12.11.1

I tried, but the error persists. I'm still trying to resolve it.

**Comment by kraenhansen** [comment]
A fix was released with [v12.12.1](https://github.com/realm/realm-js/releases/tag/v12.12.1) - please take it for a spin a report back if the issue persists.

**Comment by rkz98** [comment]
For me, the issue persists on `v12.12.1` (`v12.11.1` is working). `react-native 0.71.5`

**Comment by gvanderclay** [comment]
@kraenhansen Just validated that this fixed it for me! Thanks for the quick turnaround!
