### ISSUE TITLE
Fix chrome support for fine grained

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#685]

**Comment by dccarmo** [comment]
Is this the issue that throws an error on `addListener` to a `Collection` when debugging on Chrome?

**Comment by alazier** [comment]
@dccarmo this is the issue. The error should no longer be thrown using `0.15.1-rc` but the rc doesn't doesn't yet resolve all of the issues. Still working on it.

**Comment by kneth** [comment]
As we have rewritten large portion of the Chrome debugger support - multiple times - this issue is considered obsolete.
