### ISSUE TITLE
Property updating not working inside forEach loop

### ISSUE THREAD

**Issue by rpereira** [realm/realm-js#690]
Hi @alazier,

Let's suppose we have a list of notifications and eventually we need to mark unseen notifications as seen.

Here's our model:
```js
class Notification {}
Notification.schema = {
  name: 'Notification',
  primaryKey: 'id',
  properties: {
    message: 'string',
    id: 'int',
    seen: { type: 'bool', default: false }
  }
};
```

Received notifications are shown correctly.
```js
function receiveNotification(payload) {     // payload: { message, id }
  realm.create('Notification', payload);
}
```

When trying to mark all unseen notifications as seen, an `undefined is not an object (evaluating e.id)` exception is thrown.

```js
function markAllNotificationsAsSeen() {
  const unseen = realm.objects('Notification').filtered('seen = $0', false);
  realm.write(() => unseen.forEach(e => e.seen = !e.seen));
}
```

Updating with primary key throws the same exception.
```js
realm.write(() => 
  unseen.forEach(e => realm.create('Notification', { id: e.id, seen: true }, true))
);
```

On the other hand, updating the `message` property works as expected.

```js
realm.write(() => unseen.forEach(e => e.message = 'Some message...'));
```

I've read the docs carefully and everything seems to be ok.

Can you spot anything that I'm doing wrong? 
Thanks for your time.

**Comment by kristiandupont** [comment]
Hi @rpereira, from a quick glance your code looks solid. I will try and see if I can replicate the problem.

**Comment by rpereira** [comment]
Thanks for your time @kristiandupont.

**Comment by rpereira** [comment]
Hi @kristiandupont. Are there any news on this regard? Thanks.

**Comment by kristiandupont** [comment]
Hi @rpereira, sorry I got caught up but I finally had a chance to look at this.
We should improve the error messages here but basically what happens is that as you are changing the `seen` property on your objects, you are also modifying the `unseen` result -- as soon as you set it to true, it is removed from the collection. `forEach` gets confused by this and in the end will try to give you an object that is out of range.
An easy workaround would be to copy the result, if it's not too big to be a performance implication:
```javascript
 const unseen = realm.objects('Notification').filtered('seen = $0', false).slice();
```

**Comment by alazier** [comment]
Or maybe you could try calling `snapshot` before doing the enumeration? This would prevent the Results from being updated without needed to make a copy https://realm.io/docs/react-native/0.15.0/api/Realm.Results.html#snapshot

**Comment by rpereira** [comment]
Thanks @kishikawakatsumi. My workaround solution was the same. However, I'm looking for something more performant. @alazier, can you please elaborate how to use the `snapshot`?

Thanks for your time guys.

**Comment by kristiandupont** [comment]
Hi @rpereira sorry for the delay. Did you resolve this?

**Comment by rpereira** [comment]
No @kishikawakatsumi. My last comment reflects the current status. Thanks.

**Comment by kristiandupont** [comment]
So #798 is about solving this, but for now you can simply replace `slice` with `snapshot` in the example I gave and you should be iterating over a collection that won't change even when you add or remove items.

**Comment by rpereira** [comment]
Thanks, @kristiandupont.
