### ISSUE TITLE
> Task :realm:configureCMakeDebug[arm64-v8a] FAILED, React Native 0.76

### ISSUE THREAD

**Issue by nigelrudolf** [realm/realm-js#6908]
### How frequently does the bug occur?

always

### Description

> Task :realm:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at CMakeLists.txt:14 (add_library):
C/C++:   Target "realm-js-android-binding" links to target
C/C++:   "ReactAndroid::reactnativejni" but the target was not found.  Perhaps 
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Error at CMakeLists.txt:14 (add_library):
C/C++:   Target "realm-js-android-binding" links to target
C/C++:   "ReactAndroid::turbomodulejsijni" but the target was not found.  Perhaps a
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.

### Stacktrace & log output

```shell
https://files.slack.com/files-pri/T4ZL804RH-F07TE3DRYRY/realm-error
```

### Can you reproduce the bug?

Always

### Reproduction Steps

npm run android

### Version

12.13.1

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

0.76.0

### Build environment

Which debugger for React Native: ..
React Native DevTools

**Comment by felipegmg** [comment]
same issue here!

**Comment by coder-xiaomo** [comment]
Same issue here, after upgrading from react-native 0.75.4 to 0.76

using realm@12.13.1

```bash
> Task :realm:configureCMakeDebug[arm64-v8a]
C/C++: CMake Error at CMakeLists.txt:14 (add_library):
C/C++:   Target "realm-js-android-binding" links to target
C/C++:   "ReactAndroid::reactnativejni" but the target was not found.  Perhaps a
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Error at CMakeLists.txt:14 (add_library):
C/C++:   Target "realm-js-android-binding" links to target
C/C++:   "ReactAndroid::turbomodulejsijni" but the target was not found.  Perhaps a
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.

> Task :realm:configureCMakeDebug[arm64-v8a] FAILED
```

**Comment by Jean-Diniz** [comment]
The same occurs for v20.0.0

**Comment by bhojaniasgar** [comment]
Also Facing this same Issue 

<img width="1275" alt="Screenshot 2024-10-26 at 1 56 37 PM" src="https://github.com/user-attachments/assets/53cfc0a6-3e31-49e1-821a-6635a36c96ac">

**Comment by DiarraDah** [comment]
I also have the same error on Android but not on iOS with react-native: 0.76.0 and realm 20.0.0.

Any solution ?

**Comment by kraenhansen** [comment]
@DiarraDah it's in the oven: https://github.com/realm/realm-js/pull/6912 🍞⏲️

**Comment by DevRedaKhalaf** [comment]
> @DiarraDah it's in the oven: #6912 🍞⏲️

I'm still facing the same issue after the merge of your pull request, any advice?

**Comment by kraenhansen** [comment]
@DevRedaKhalaf 🙈 it needs to be released as well.
Currently, battling a GitHub Actions outage: https://www.githubstatus.com/incidents/9yk1fbk0qjjc

**Comment by DevRedaKhalaf** [comment]
> @DevRedaKhalaf 🙈 it needs to be released as well. Currently, battling a GitHub Actions outage: https://www.githubstatus.com/incidents/9yk1fbk0qjjc

OMG! 
anyway, i appreciate your help and fast reply.

**Comment by kraenhansen** [comment]
This should be fixed with [Realm JS v12.13.2](https://github.com/realm/realm-js/releases/tag/v12.13.2). Please take it for a spin and let me know if it works for you 👍

I appreciate y'alls patience on the turnaround of this one.

**Comment by driq** [comment]
Thanks @kraenhansen!

Any chance of this landing in Realm 20.x?

**Comment by kraenhansen** [comment]
> Any chance of this landing in Realm 20.x?

Sure - that's the idea 👍 As that will be the first release commits from v12 ported onto v20, I just have to figure out if I'd be merging `main` into `community` or do individual cherry-picks 🤔

**Comment by mgagna** [comment]
> > Any chance of this landing in Realm 20.x?
> 
> Sure - that's the idea 👍 As that will be the first release commits from v12 ported onto v20, I just have to figure out if I'd be merging `main` into `community` or do individual cherry-picks 🤔

Do you know if there is an ETA for the Realm 20.x update?
Should we downgrade to Realm 12.13.x?

**Comment by kraenhansen** [comment]
@mgagna thanks for the nudge 🙂 It's cooking now: https://github.com/realm/realm-js/pull/6940
