### ISSUE TITLE
"npm install --save realm" reminder me :  node-pre-gyp ERR! 

### ISSUE THREAD

**Issue by zhouxin1233** [realm/realm-js#692]
@alazier  node-pre-gyp ERR! Tried to download(404): https://static.realm.io/node-pre-gyp/realm-v0.15.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@0.15.0 and node@6.9.1 (node-v48 ABI) (falling back to source compile with node-gyp)

**Comment by kenma9123** [comment]
I have the same problem which forced me to revert to `0.14.1`

**Comment by kristiandupont** [comment]
This is already tracked in #674 -- we are looking into it.
