### ISSUE TITLE
Missing binary on Android with RN 0.76 & Expo SDK 52

### ISSUE THREAD

**Issue by nzapponi** [realm/realm-js#6933]
### How frequently does the bug occur?

Always

### Description

Since upgrading to Expo SDK 52 & RN 0.76, any Android build fails with "Could not find binary" error.

All troubleshooting steps were taken, none helped.

### Can you reproduce the bug?

Always

### Reproduction Steps

- Create an Expo project with SDK 52 (new arch not enabled)
- Add Realm
- Run

### Version

12.14.0

### What services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android 14

### Build environment

Tried both RN DevTools and Expo Dev Client

**Comment by nzapponi** [comment]
Added repro sample project. This is a clean expo project with just realm added.
To reproduce:
- Clone project
- Install deps
- Run expo run:android


https://github.com/nzapponi/realm-bug-repro

**Comment by nzapponi** [comment]
I did some quick checking and after running `expo prebuild`, no realm files are found in the `android` folder. It looks like they're not being bundled at all

**Comment by alexphl** [comment]
This is happening because Expo SDK 52 has removed `@react-native-community/cli`.

Although it's a breaking change, it is only briefly mentioned in their [blog post](https://expo.dev/changelog/2024/11-12-sdk-52):
> Reduced size of Expo CLI by removing the dependency on RNC CLI. Expo projects use expo-modules-autolinking to discover both Expo Modules and modules built with the React Native module API (such as Turbo Modules). You can opt in to @react-native-community/cli autolinking by setting the environment variable EXPO_USE_COMMUNITY_AUTOLINKING=1 and running pod install again.

**The fix is to add `@react-native-community/cli` to your package.json and set the `EXPO_USE_COMMUNITY_AUTOLINKING=1` env variable.**

**Comment by kbinder** [comment]
@alexphl Thank you this solved my issue.

**Comment by nzapponi** [comment]
Thanks so much!

**Comment by susannah-mccloskey** [comment]
I'm still experiencing this issue even after I added `@react-native-community/cli` to my `package.json`, set the `EXPO_USE_COMMUNITY_AUTOLINKING=1`, and ran the prebuild. Any other suggestions of what to do next?

**Comment by s-turcheniuk** [comment]
Thanks for the suggestion, but Is there a plan to make realm-js to work with expo-modules-autolinking?

**Comment by kraenhansen** [comment]
Since the notice of deprecation, we don't plan to add any new features to the SDK: https://www.mongodb.com/docs/atlas/device-sdks/deprecation/

**Comment by JulianHillworth** [comment]
I am having the same issue.  I tried the below but no luck, to the point of about 30 rebuilds and play around.  Trying pretty much everything.  Is there a step that is not mentioned that I may be missing?  Any help much appreciated.

> This is happening because Expo SDK 52 has removed `@react-native-community/cli` autolinking.
> 
> Although it's a breaking change, it is only briefly mentioned in their [blog post](https://expo.dev/changelog/2024/11-12-sdk-52):
> 
> > Reduced size of Expo CLI by removing the dependency on RNC CLI. Expo projects use expo-modules-autolinking to discover both Expo Modules and modules built with the React Native module API (such as Turbo Modules). You can opt in to @react-native-community/cli autolinking by setting the environment variable EXPO_USE_COMMUNITY_AUTOLINKING=1 and running pod install again.

**Comment by CodeWithBlaze** [comment]
hey guys, i have a bare react native app which is using realm. it is working fine in developement but when i release it for android
using gradlew assembleRelease and install it in the device, then i get this error "could not find realm binary".  I am using react native 0.76.1. it will be great if someone could help me or provide me some guidance. Thank you

**Comment by ArindamRayMukherjee** [comment]
> the notice of deprecation

@kraenhansen They have deprecated the Atlas SDK but the on-device DB will continue to exist AFAIK

https://www.mongodb.com/docs/atlas/device-sdks/deprecation/#std-label-device-sdks-deprecation

**Comment by ArindamRayMukherjee** [comment]
What worked for my bare react-native(0.76.5) app that only wishes to use `expo-image`(2.0.3) from `expo`(52.0.0) and wishes to link separately to `realm`(12.14.0) was the follows

in `package.json`
```
EXPO_USE_COMMUNITY_AUTOLINKING=1 react-native run-android
```
in `ios/Podfile` the following `if conditional` (this may or may not come with the instrumentation done by the tools prescribed by the expo docs for integrating with bare react-native, in my case it did arrive)
```
//other code

target 'ProjectName' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

//other code
```
and in `android/settings.gradle`  the following conditional similar to iOS (this may or may not come with the instrumentation done by the tools prescribed by the expo docs for integrating with bare react-native, *in my case it DID NOT arrive as opposed to the Podfile change*)

```
extensions.configure(com.facebook.react.ReactSettingsExtension) { ex ->
  if (System.getenv('EXPO_USE_COMMUNITY_AUTOLINKING') == '1') {
    ex.autolinkLibrariesFromCommand()
  } else {
    def command = [
            'node',
            '--no-warnings',
            '--eval',
            'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
            'react-native-config',
            '--json',
            '--platform',
            'android'
    ].toList()
    ex.autolinkLibrariesFromCommand(command)
  }
}
```

**Comment by kfchan-git** [comment]
still can't find the realm in `android` folder, works when i run it in debug mode

**Comment by AdamGerthel** [comment]
> still can't find the realm in `android` folder, works when i run it in debug mode; already added `@react-native-community/cli` into the package.json but still not working

Are you using Expo? If so, see https://github.com/realm/realm-js/issues/6933#issuecomment-2539821276

**Comment by kfchan-git** [comment]
> > still can't find the realm in `android` folder, works when i run it in debug mode; already added `@react-native-community/cli` into the package.json but still not working
> 
> Are you using Expo? If so, see [#6933 (comment)](https://github.com/realm/realm-js/issues/6933#issuecomment-2539821276)

yes, but i dont have the eas.json file since i'm using android studio to build

**Comment by AdamGerthel** [comment]
> > > still can't find the realm in `android` folder, works when i run it in debug mode; already added `@react-native-community/cli` into the package.json but still not working
> > 
> > 
> > Are you using Expo? If so, see [#6933 (comment)](https://github.com/realm/realm-js/issues/6933#issuecomment-2539821276)
> 
> yes, but i dont have the eas.json file since i'm using android studio to build; or is there any other way to link it?

I see... Hmm, if you're using Expo, I don't think you should be using Android Studio to build. You're at least not making it easy for yourself. You'll need a way to set `EXPO_USE_COMMUNITY_AUTOLINKING=1`.

You know, you don't need to use the cloud service EAS. You can use the `--local` flag to [run eas locally](https://docs.expo.dev/build-reference/local-builds/).

**Comment by harit2305** [comment]
Hello Guys, 

I am using react native bare workflow with
realm => 12.13.2
react-native => 0.76.2

It's crashing in the release build but its working fine in debug build 
Any solutions for this without expo?

**Comment by kraenhansen** [comment]
> It's crashing in the release build

Please create a new issue with the stack from the crash and any information needed to reproduce this 🙏
