### ISSUE TITLE
Help me guys with the following error

### ISSUE THREAD

**Issue by abdurehmanali611** [realm/realm-js#6952]
### How frequently does the bug occur?

Always

### Description

The path is correct but i don't know why i got it

### Stacktrace & log output

```shell
λ Bundling failed 4963ms node_modules\expo-router\node\render.js (1580 modules)
Web Bundling failed 4998ms node_modules\expo-router\entry.js (1191 modules)

Metro error: Unable to resolve module ../../../prebuilds/node/realm.node from C:\Users\Abdu\Documents\Mobile Apps\vehicle_management\node_modules\realm\dist\platform\node\binding.js:

None of these files exist:
  * node_modules\realm\prebuilds\node\realm.node(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
  * node_modules\realm\prebuilds\node\realm.node
  20 | const binding_1 = require("../binding");
  21 | // eslint-disable-next-line @typescript-eslint/no-var-requires
> 22 | const nativeModule = require("../../../prebuilds/node/realm.node");
     |                               ^
  23 | (0, binding_1.injectNativeModule)(nativeModule, { Int64: binding_1.NativeBigInt, WeakRef });
  24 | //# sourceMappingURL=binding.js.map


Call Stack
  <unknown> (node_modules/realm/dist/platform/node/binding.js)
Web Bundled 48ms node_modules\expo-router\_error.js (1 module)
```

### Can you reproduce the bug?

-- select --

### Version

expo 52

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android and web

### Build environment

Which debugger for React Native: ..

**Comment by kraenhansen** [comment]
Your metro resolver config is messed up, causing Metro start reading the binding intended for Node.js.
Can you share your `metro.config.js`?

**Comment by abdurehmanali611** [comment]
no i use expo 52 default template which doesn't contain metro.config.js file

**Comment by kraenhansen** [comment]
Ahh, I see it now. It seems you're trying to bundle you app for the web?
Realm JS doesn't support browsers.

**Comment by abdurehmanali611** [comment]
ok i should use development build instead of expo to run it
