### ISSUE TITLE
Crash of other process detected, session restart required

### ISSUE THREAD

**Issue by haiyangjiajian** [realm/realm-js#697]
Realm crashes with the following exception message:

Crash of other process detected, session restart required
when attempting to begin a write transaction. Stack trace:

proxiedMethod
    createPrototypeProxy.js:44
eventHandler
    PublisherMethods.js:44
emit
    index.js:116
trigger
    PublisherMethods.js:63
crawlerAuthCompleted
    AuthStore.js:76
eventHandler
    PublisherMethods.js:44
emit
    index.js:116
trigger
    PublisherMethods.js:63
<unknown>
    PublisherMethods.js:74
<unknown>
    JSTimers.js:78
callTimer
    JSTimersExecution.js:99
callTimers
    JSTimersExecution.js:140
__callFunction
    MessageQueue.js:234
<unknown>
    MessageQueue.js:105
guard
    MessageQueue.js:45
callFunctionReturnFlushedQueue
    MessageQueue.js:104

**Comment by haiyangjiajian** [comment]
@kristiandupont

**Comment by kristiandupont** [comment]
@haiyangjiajian With "realm crashes", do you mean that the object server crashes? Or do you have an app (in React Native?) that crashes?

**Comment by bmunkholm** [comment]
and which version?

**Comment by haiyangjiajian** [comment]
@kishikawakatsumi   the app(in React Native) crashes . @bmunkholm version 0.14.3 . thanks

**Comment by haiyangjiajian** [comment]
any update?

**Comment by kneth** [comment]
@haiyangjiajian Have you tried to upgrade to a recent version? I mean, we have been through 1.x and are currently at 2.0.12.
