### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by ryutamaki** [realm/realm-js#698]
Hi, I'm using typescript much.
Would you consider provide official typescript definition files?

typescript is the language commonly used and we can now include definition file like npm dependencies.
cf) https://github.com/moment/moment/blob/develop/package.json#L27

**Comment by kristiandupont** [comment]
Hi @ryutamaki, that should be fairly easy to add I suppose. I'll look into that some day when I have some spare time. Unfortunately things are a bit hectic at the moment..

**Comment by ryutamaki** [comment]
Appreciate for that, Kristian!

**Comment by Pencl** [comment]
I believe this one can be closed.

There are type-definitions available provided by the DefinitelyTyped project:
[https://www.npmjs.com/package/@types/realm](https://www.npmjs.com/package/@types/realm)

**Comment by mrackwitz** [comment]
This should be now indeed fully resolved with the merge of #1076. 🎉
