### ISSUE TITLE
Can't find variable: Symbol----android

### ISSUE THREAD

**Issue by LiuC520** [realm/realm-js#699]
Can't find variable: Symbol
<unknown>
    constants.js:30
<unknown>
    constants.js:29

android build successfull,but got the wrong position: realm/lib/browser/index.js,line 22, ----> realm/lib/browser/constants.js,line 29 and 30,

].forEach(function(name) {
keys[name] = Symbol();

what can i do ?

**Comment by kristiandupont** [comment]
Hi @LiuC520, we're already tracking this issue in #683. Sorry that we don't have a fix yet.
