### ISSUE TITLE
Avoid calling process.exit in sigint/exception handling

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#700]
See https://github.com/realm/realm-js/pull/675#issuecomment-263275285 -- it shouldn't be reverted but we should figure out how to let users attach custom handlers. Perhaps through the use of `eventEmitter.once`.

**Comment by sorenvind** [comment]
Just a small remark: It's important that realm-js either does everything internally or provides a handler that downstream users can call in their handlers. I.e. the user should not be required to pass a handler that realm-js then calls.
