### ISSUE TITLE
Realm doesn't store anything on first run

### ISSUE THREAD

**Issue by dccarmo** [realm/realm-js#704]
I'm currently working on a React Native project using Realm to persist data. I've run into this strange behaviour where on the first run of the app, Realm doesn't persist anything. 

Here's the flow:

1) Run the app for the first time

2) Login (and theoretically persist data with no error)

3) Try to access data (error)

4) Reload app

5) Back to Login view, but this time when I do log in, it saves data and everything works perfectly

I'm not even sure which part of my code to post here, 'cause I'm not doing much, just storing simple data. And since it works after the first attempt, it seems that it's correct. But if you have any suggestions I'm happy to share.

**Comment by nhachicha** [comment]
Hi @dccarmo 
does this happen on Android or iOS or both?
is it possible to share the project so we can try to reproduce? help@realm.io
Cheers

**Comment by dccarmo** [comment]
Found the issue, it was something on my code. Sorry about that.
