### ISSUE TITLE
Realm returns empty data field

### ISSUE THREAD

**Issue by wochinge** [realm/realm-js#705]
Hi there,

**Goals**
I try am trying to save an image to realm and then read it.

**Expected results**
The database query should return the ArrayBuffer which represents the data of the image.

**Actual results**
Saving the ArrayBuffer seems to work as `realm.create` returns a valid object. When trying to read the image from the database, it only returns the id field, but the image data is empty.

**Steps to reproduce**
Save an ArrayBuffer and then read it.

**Code**

```javascript
import Realm from 'realm';
import { encode, decode } from 'base64-arraybuffer';

const PlantSchema = {
  name: 'Plant',
  properties: {
    id:     'int',
    image:  'data'
  }
};

let realm = new Realm({schema: [PlantSchema]});

class Plant {

  getPlantImage(id) {
    const plants = realm.objects('Plant').filtered(`id == ${id}`);
    console.log(plants[0].image); // { '0': { id: 12, image: {} } }
    ...
  }

  save(id, imageData) {
    const decoded = decode(imageData); //base64 to ArrayBuffer
    realm.write(() => {
      let plant = realm.create('Plant', {
        id: id,
        image: decoded
      });
      console.log('saved: ' + plant.image); // prints saved: [object ArrayBuffer]
    });
  }
}
```

**Versions**
* Realm: 0.15.0
* react-native: 0.38.0
* react: 15.4.1
* Xcode: 8.1
* iPhone 6 Simulator
* OSX: 10.12.1

Thanks a lot
Tobias

**Comment by wochinge** [comment]
I worked around by storing the image with the local file system and just saving the URI with realm.

**Comment by spencexyz** [comment]
I'm also having the same issue.

**Comment by noisytempo** [comment]
The issue is still there in realm 2.2.6.

**Comment by alax** [comment]
So do data fields just not work in Realm JS at all? The issue is still present on 2.3, and it looks like this bug has been open for over a year.

**Comment by kneth** [comment]
The test [testRealmCreateOrUpdate](https://github.com/realm/realm-js/blob/master/tests/js/realm-tests.js#L383) indicates that binary data is support and it works.
