### ISSUE TITLE
Even if specifying a path, folders are created in the CWD

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#706]
Even if you specify a path for a synced realm, a folder for the realm is still create  {{ ./realm-object-server/$hash}}
e.g. {{ ./realm-object-server/505e07b4-97c7-4638-b386-11882ce5b2ad}}

**Comment by alazier** [comment]
I think this might be an object store issue. @austinzheng ?

**Comment by mrackwitz** [comment]
This is tracked by https://github.com/realm/realm-object-server/issues/669.

**Comment by austinzheng** [comment]
Has this bug been fixed, @alazier? If there's any outstanding work you need from me let me know.

**Comment by gritzko** [comment]
related: #894
