### ISSUE TITLE
Cannot evaluate module realm : Configuration with name 'default' not found. - Android Studio

### ISSUE THREAD

**Issue by lakhman** [realm/realm-js#714]
I got the following error in **Android Studio** when using realm in a RN project.

![screen shot 2016-12-02 at 19 00 07](https://cloud.githubusercontent.com/assets/1582690/20847180/db6bd4e2-b8c4-11e6-8681-9465aa72369e.png)

```text
Caused by: org.gradle.internal.exceptions.LocationAwareException: A problem occurred configuring project ':app'.
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module realm : Configuration with name 'default' not found.
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
Caused by: org.gradle.internal.exceptions.LocationAwareException: A problem occurred configuring project ':app'.
2016-12-02 18:35:04,460 [  28653]   INFO - ls.idea.gradle.GradleSyncState - Sync with Gradle for project 'ProjectName' failed: Configuration with name 'default' not found.
```

> org.gradle.api.UnknownProjectException: Cannot evaluate module realm : Configuration with name 'default' not found.

The full log from the IDE can be found here (I truncated above): http://pastebin.com/71ufJf6Q

I've installed and updated my `ANDROID_NDK` path to: `/Users/username/Library/Android/sdk/ndk-bundle`(and restarted).

I can comment out realm temporarily to use Android Studio (so that gradle builds successfully), but with realm included it fails and makes android studio difficult to use (no code insight, auto completion etc).

`build.gradle`
```
//    compile project(':realm') // Uncomment this while using Android Studio so gradle can build
```

My `node_modules/realm/android` is **empty**, is this correct?

```
project(':realm').projectDir = new File(rootProject.projectDir, '../node_modules/realm/android')
```

Any ideas?

**Android Studio 2.2**
**Realm JS:** git@github.com:realm/realm-js.git#f44f31e721d2d616d7a482bd034a382b77008ed9
(I tried the latest to see if it would help).
**OSX:** El Capitan 10.11.6

**Comment by nhachicha** [comment]
Hi @lakhman 
`node_modules/realm/android` shouldn't be empty.

There seems to be different problem here...

Can you please first make sure the installation is correct, we updated recently the [install guide](https://realm.io/docs/react-native/latest/#installation)

Try building first from the command line using `<Project-Name>/react-native run-android`
if this works, then try starting Android studio from the command line as described [here](https://github.com/realm/realm-js/issues/687#issuecomment-264257814), so it can pick the NDK location correctly

**Comment by lakhman** [comment]
Thanks, I found the issue in that ticket #687.

https://github.com/realm/realm-js/issues/687

For now I changed the `npm` path in `node_modules/realm/android/build.gradle` around line 71 from:

```
# Line 71 : node_modules/realm/android/build.gradle
version = "npm --silent run get-version".execute(null, projectDir).text.trim()
```

to:
```
# Line 71 : node_modules/realm/android/build.gradle
version = "/usr/local/bin/npm --silent run get-version".execute(null, projectDir).text.trim()
```

Android studio now works as expected, not a permanent solution, but works for now.

Thanks!
