### ISSUE TITLE
Exposing begin_transaction & close_transaction

### ISSUE THREAD

**Issue by marcus433** [realm/realm-js#715]
By having explicit control over opening and closing transactions it can be possible to run asynchronous code inside a transaction. 

e.g. currently the below code would close the transaction before the coroutine completes as it isn't synchronous.
```
realm.write(() => {
  Promise.coroutine(() => {
    var somedata = yield x();
    realm.create('objname', somedata);
  })();
})
```

However, with explicit control of begin / close we could still have synchronous transactions while allowing for asynchronous functions to run.
```
Promise.coroutine(() => {
  realm.begin_transaction();
  var somedata = yield x();
  realm.create('objname', somedata);
  realm.close_transaction();
})();
```

Of course the above could also be solved by fetching the data outside of the transaction and placing the write inside the coroutine. However, situations can exist where the yielded function also depends on the transaction being ran. E.g. `function x()` may run `realm.create` itself rather than return data.

Side note: Wonderful job Realm Team!

**Comment by kristiandupont** [comment]
This is an interesting idea. Thank you for the feedback and kind words!

**Comment by kneth** [comment]
I have merged #1216 which implements manual transactions.

**Comment by Udbhav12** [comment]
How to use begin transaction and close transaction? Where can I find it's documentation?

I am using realm 2.26.1

**Comment by kneth** [comment]
@Udbhav12 

You can use [`beginTransaction`](https://realm.io/docs/javascript/latest/api/Realm.html#beginTransaction), [`cancelTransaction`](https://realm.io/docs/javascript/latest/api/Realm.html#cancelTransaction), and [`commitTransaction`](https://realm.io/docs/javascript/latest/api/Realm.html#commitTransaction).
