### ISSUE TITLE
gyp error: No such file or directory: ...\src\node\gyp\realm.sln.gyp.up7p0k

### ISSUE THREAD

**Issue by Arman92** [realm/realm-js#716]
I've been trying to install realm on my react-native project, but I'm getting this strange error:

OSError: [Errno 2] No such file or directory: 'D:\\reactProject\\node_modules\\realm\\build\\src\\node\\gyp\\realm.sln.gyp.up7p0k.tmp'

Node version: v6.9.1
NPM version: 3.10.8

react-native module version: 0.39.0
react module version: 15.4.1

And I must mention I'm using Windows 10 build version 14393.447

here is the full log report of the error:
`gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\Arman.DESKTOP-04F6PPB\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Arman.DESKTOP-04F6PPB\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Arman.DESKTOP-04F6PPB\\.node-gyp\\6.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Arman.DESKTOP-04F6PPB\\.node-gyp\\6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Arman.DESKTOP-04F6PPB\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2009, in Genera
teOutput
    version=msvs_version)
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 241, in Write
    f = writer(self.path)
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 399, in WriteOnDiff
    return Writer()
  File "C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 346, in __init__
    dir=os.path.split(filename)[0])
  File "C:\Python27\lib\tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:\Python27\lib\tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: 'D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\build\\src\\node\\gyp\\realm.sln.gyp.up7p0k
.tmp'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:
305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Arman.DESKTOP-04F6PPB\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\compiled\\node-v48
_win32_x64\\realm.node" "--module_name=realm" "--module_path=D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\compiled\\node-v48_win32_x64"
 "--python=python" "--msvs_version=2015"
gyp ERR! cwd D:\GeoLocation\react\FleetMonitoring\node_modules\realm
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\GeoLocation\react\FleetMonitoring\node_modules\
realm\compiled\node-v48_win32_x64\realm.node --module_name=realm --module_path=D:\GeoLocation\react\FleetMonitoring\node_modules\realm\compiled\node-v48
_win32_x64 --python=python --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\GeoLocation\react\FleetMonitoring\node_modules\realm\node_modules\node-pre-gyp\lib\util\comp
ile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "D:\\GeoLocation\\react\\FleetMonitoring\\node_modules\\realm\\node_modules\\node-
pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\GeoLocation\react\FleetMonitoring\node_modules\realm
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\GeoLocation\react\FleetMonitoring\node_modules\realm\compiled\node-v48_win32_x
64\realm.node --module_name=realm --module_path=D:\GeoLocation\react\FleetMonitoring\node_modules\realm\compiled\node-v48_win32_x64 --python=python --ms
vs_version=2015' (1)
npm verb lifecycle realm@0.15.0~install: unsafe-perm in lifecycle true
npm verb lifecycle realm@0.15.0~install: PATH: C:\Users\Arman.DESKTOP-04F6PPB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\GeoLocation\react`

**Comment by kristiandupont** [comment]
There are problems using Realm RN on Windows (tracked in #674). We are working on a solution and hopefully this will fix your problem as well.

**Comment by Arman92** [comment]
Ok thank you, however I switched to a better OS ;-)
