### ISSUE TITLE
Set the root dir used for the object server including the metadata dir

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#720]
According to https://github.com/realm/realm-object-store/issues/263#issuecomment-263949456
We need support for setting the root dir used by OS
We currently have a workaround for the ROS to have the server running without being able to set the path.

@alazier

**Comment by sellmeadog** [comment]
I apologize if this is not the correct place to start this discussion, but I found myself here after researching how to change the location of the `realm-object-server` directory in Node.

I am struggling to understand what was actually changed in this PR to support specifying a custom sync directory and if it is still valid. I am trying to synchronize a Realm Cloud instance using Azure Functions and the presence of `realm-object-server` within the site root is problematic as whenever the directory is written to, it triggers a restart of the Azure Functions runtime.

My directory structure looks like this:

```
\site\realm
  \my.realm.management
  my.realm
  my.realm.lock
  my.realm.note
\site\wwwroot
  \function1
  \functionN
  \realm-object-server  
```
I need the ability to locate `realm-object-server` under `\site\realm` as this will prevent the Azure Function runtime from seeing changes to the file system triggering a runtime restart.

The only directory/path I seem to have any control over is the Realm file path. I have tried setting `Realm.defaultPath` and the `path` option in the Realm configuration to `...\realm\my.realm` which resulted in the directory structure outlined above, i.e., no effect on the location of `realm-object-server`. 

Please advise.
