### ISSUE TITLE
Inserting strings with Emoji to Realm

### ISSUE THREAD

**Issue by geldarhb** [realm/realm-js#726]
Hey all,

We've tried to insert a string with an Emoji into Realm (in React Native) but the DB didn't play well and rejected the insert.

Does anyone know if there's an issue with Emoji in Realm, or am I missing smtng here... ?

Thanks,
Guy

**Comment by kristiandupont** [comment]
Hi @geldarhb, there might well be an issue, I don't think we've tried inserting strings with emojis. What do you mean it rejects the insert? Does it throw an exception or is the property simply not updated?
