### ISSUE TITLE
Realm Result has no addListener method

### ISSUE THREAD

**Issue by dwsc** [realm/realm-js#729]
I'm using Realm 0.15.0 in React Native.

I'm trying to add a listener to a realm result per the documentation [1].  When trying the following:

> realm.objects('Project').addListener((projects) => {...}
I receive:
> _realm2.default.objects(...).addListener is not a function

Using the debugger, I can see that a "Results" object is returned with a "Collection" prototype.
Looking at the Results object methods available in the debugger, I do not see "addListener".  It almost looks like the result object matches that of version 0.14.0, but I've verified that I'm using 0.15.0.

output of "head realm/packages.json"
> {
  "name": "realm",
  "description": "Realm is a mobile database: an alternative to SQLite and key-value stores",
  "version": "0.15.0",
  "license": "Apache-2.0",
  "homepage": "https://realm.io",
  "keywords": [
    "database",
    "db",
    "react",

I've also unlinked and relinked the realm module to ensure it's using the current version.

[1] https://realm.io/docs/react-native/latest/#notifications

Is there a reason that the addListener method would not be available?

**Comment by alazier** [comment]
This method is broken in chrome debugging but should work otherwise. There is a partial fix in version `0.15.1-rc` which adds the method in chrome debug mode although it still does not yet work in call cases. We should hopefully have a full fix for this soon.

**Comment by mdekrey** [comment]
This appears to have escalated in later versions of Realm: If I attempt to use Collection Notifications on Android with chrome debugging on as of 2.21.1, my application crashes with what looks like a `android.os.DeadObjectException`.

**Comment by kneth** [comment]
See [`Realm.Results.addListener()](https://realm.io/docs/javascript/latest/api/Realm.Results.html#addListener)
