### ISSUE TITLE
Ambiguous error - Error: 'Property' must be of type: string

### ISSUE THREAD

**Issue by sambwest** [realm/realm-js#730]
Hi,

I have an issue with the error messages. I am getting the following error:

Error: 'Property' must be of type: string

I obviously have a problem with my data but I have no clue _which_ property is being provided the wrong data. Is there anyway the message could be updated to indicate where the problem lies? Or, if I'm just being dumb, point me to where I can see what property is having issues. 

Thanks,

Sam

**Comment by sambwest** [comment]
After allot of trial and error this error seems to be if the primary key property is missing on a newly created object. So, I guess it'd be good if the error message said that.

**Comment by lakhman** [comment]
These types of errors are a pain to debug, we really need better error reporting for this, this ends up taking so much time to track down (removing items one at a time) - a simple message like "Property 'date' must be of type: date" would be so useful and save so much time, even trying to track down the error with the debugger is difficult due to how the objects are structured.

**Comment by alazier** [comment]
This is definitely something we want/need to improve. Thanks for the feedback.

**Comment by rdougan** [comment]
@kristiandupont I've noticed this same error on 1.0.0. It happened when a property of mine was **not** optional and I was trying to create it with a `null` value.

    properties: {
      ...
      email: { type: 'string' },
    }

    realm.create('FeedItem', {
      ...
      email: null,
    });

**Comment by kristiandupont** [comment]
@rdougan yes, this is covered by #787. Sorry for the inconvenience, I hope we will get it fixed soon.

**Comment by yuvaraj119** [comment]
@rdougan How did you fix the null issue. Same issue I am getting.

**Comment by maxto024** [comment]
the same issue hey @yuvaraj119   did you get a solution

**Comment by yutianhaijiao** [comment]
> the same issue hey @yuvaraj119 did you get a solution
#1803 is solved

**Comment by yuvaraj119** [comment]
> 
> 
> the same issue hey @yuvaraj119 did you get a solution

Yes I fixed by removing null values in API response and then I insert an empty string
