### ISSUE TITLE
Array must contain values for all object properties realm

### ISSUE THREAD

**Issue by laclance** [realm/realm-js#731]
I am using realm with react-native and if I have 1 to many relationship but an object is not related to anything i get "Array must contain values for all object properties realm". Is there any way to make a relationship optional?

**Comment by alazier** [comment]
Use an object to specify an object with keys for each property. You can omit object or other optional properties on creation to set them to null

**Comment by laclance** [comment]
Sorry Im not following, what object do you speak of? Say for example this is my db: 

TodoList.schema = {
  name: 'TodoList',
  properties: {
    todos: {type: 'list', objectType: 'Todo'},
  }
};

Todo.schema = {
  name: 'Todo',
  properties: {
    content: {type: 'string'},
    todoList: {type: 'TodoList')
  }
};

Do you mean i must change todos to {type: 'list', objectType: 'object'}

**Comment by alazier** [comment]
No that schema is fine. I think the problem you are having is when calling `realm.create`. I suspect you are doing something like `realm.create('TodoList', [])` which would give you the error you are seeing. If this is what you are doing you should change it to `realm.create('TodoList', {})`

**Comment by alazier** [comment]
Or to be more explicit
```
realm.create('TodoList', { todos: [] });
```

**Comment by laclance** [comment]
yes exactly. is there no way to handle an empty array?

**Comment by laclance** [comment]
like when there are no todos but the TodoList still exists

**Comment by alazier** [comment]
```realm.create('TodoList', { todos: [] });```

**Comment by laclance** [comment]
but then i get that error

**Comment by alazier** [comment]
Can you post the code which produces the error?

**Comment by laclance** [comment]
const items = [{
  "contributors": [],
  "category": [{
    "title": "Trigonometry",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "parentCategory": null,
    "context": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:57:18.835Z"),
    "updatedAt": newDate("2016-11-01T16:57:29.101Z")
  }],
  "baseContent": [{
    "content": "Arc Ratio",
    "type": "term",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T17:01:00.237Z"),
    "updatedAt": newDate("2016-11-30T11:11:50.359Z")
  }, {
    "content": "The inverse of a trigonometric ratio.  Uses the sides to calculate the angle. Arcsin(1/2) = sin^-1 (1/2) = 90 degrees.",
    "type": "description",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 1,
    "id": 4,
    "createdAt": newDate("2016-11-16T14:14:29.700Z"),
    "updatedAt": newDate("2016-11-30T11:11:25.500Z")
  }],
  "masteryActivity": [],
  "context": [{
    "title": "Mathematics",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:56:58.295Z"),
    "updatedAt": newDate("2016-11-01T16:57:12.808Z")
  }],
  "createdBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "updatedBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "term": "Arc ratio",
  "type": "term",
  "lang": "en_US",
  "template": "default",
  "id": 1,
  "createdAt": newDate("2016-11-01T16:57:42.357Z"),
  "updatedAt": newDate("2016-11-01T16:58:00.705Z")
}, {
  "contributors": [],
  "category": [{
    "title": "Trigonometry",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "parentCategory": null,
    "context": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:57:18.835Z"),
    "updatedAt": newDate("2016-11-01T16:57:29.101Z")
  }],
  "baseContent": [{
    "content": "Any angle with a magnitude between 0 and 90 degrees.",
    "type": "description",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 2,
    "id": 2,
    "createdAt": newDate("2016-11-16T14:11:43.948Z"),
    "updatedAt": newDate("2016-11-30T11:11:42.807Z")
  }, {
    "content": "Acute Angle",
    "type": "term",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 2,
    "id": 7,
    "createdAt": newDate("2016-11-16T14:17:27.961Z"),
    "updatedAt": newDate("2016-11-30T11:10:31.171Z")
  }],
  "masteryActivity": [],
  "context": [{
    "title": "Mathematics",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:56:58.295Z"),
    "updatedAt": newDate("2016-11-01T16:57:12.808Z")
  }],
  "createdBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "updatedBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "term": "Acute Angle",
  "type": "term",
  "lang": "en_ZA",
  "template": "default",
  "id": 2,
  "createdAt": newDate("2016-11-16T14:07:27.280Z"),
  "updatedAt": newDate("2016-11-16T14:07:47.758Z")
}, {
  "contributors": [],
  "category": [{
    "title": "Trigonometry",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "parentCategory": null,
    "context": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:57:18.835Z"),
    "updatedAt": newDate("2016-11-01T16:57:29.101Z")
  }],
  "baseContent": [{
    "content": "Next to.  Adjacent angles are next to each other.  An adjacent side, is the side next to a given angle.",
    "type": "description",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 3,
    "id": 3,
    "createdAt": newDate("2016-11-16T14:13:18.587Z"),
    "updatedAt": newDate("2016-11-30T11:11:34.164Z")
  }, {
    "content": "Adjacent",
    "type": "term",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 3,
    "id": 6,
    "createdAt": newDate("2016-11-16T14:16:45.430Z"),
    "updatedAt": newDate("2016-11-30T11:10:39.740Z")
  }],
  "masteryActivity": [],
  "context": [{
    "title": "Mathematics",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:56:58.295Z"),
    "updatedAt": newDate("2016-11-01T16:57:12.808Z")
  }],
  "createdBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "updatedBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "term": "Adjacent",
  "type": "term",
  "lang": "en_ZA",
  "template": "default",
  "id": 3,
  "createdAt": newDate("2016-11-16T14:07:51.862Z"),
  "updatedAt": newDate("2016-11-16T14:08:12.831Z")
}, {
  "contributors": [],
  "category": [{
    "title": "Trigonometry",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "parentCategory": null,
    "context": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:57:18.835Z"),
    "updatedAt": newDate("2016-11-01T16:57:29.101Z")
  }],
  "baseContent": [{
    "content": "Amplitude",
    "type": "term",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 4,
    "id": 5,
    "createdAt": newDate("2016-11-16T14:16:28.235Z"),
    "updatedAt": newDate("2016-11-30T11:10:50.927Z")
  }, {
    "content": "The average range of a trigonometric function",
    "type": "description",
    "lang": "en_ZA",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "baseTerm": 4,
    "id": 8,
    "createdAt": newDate("2016-11-16T14:17:38.344Z"),
    "updatedAt": newDate("2016-11-30T11:10:21.089Z")
  }],
  "masteryActivity": [],
  "context": [{
    "title": "Mathematics",
    "lang": "en_US",
    "template": "default",
    "createdBy": 1,
    "updatedBy": 1,
    "id": 1,
    "createdAt": newDate("2016-11-01T16:56:58.295Z"),
    "updatedAt": newDate("2016-11-01T16:57:12.808Z")
  }],
  "createdBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "updatedBy": {
    "username": "Glenncito",
    "email": "glennmarcstein@gmail.com",
    "lang": "en_US",
    "template": "default",
    "id_ref": "1",
    "provider": "local",
    "id": 1,
    "createdAt": newDate("2016-11-01T15:30:29.195Z"),
    "updatedAt": newDate("2016-11-01T15:30:29.217Z")
  },
  "term": "Amplitude",
  "type": "term",
  "lang": "en_ZA",
  "template": "default",
  "id": 4,
  "createdAt": newDate("2016-11-16T14:08:18.115Z"),
  "updatedAt": newDate("2016-11-16T14:08:34.810Z")
}];

  realm.write(() => {
    realm.create('BaseTerm', items);
  }
[models.zip](https://github.com/realm/realm-js/files/643638/models.zip)

**Comment by laclance** [comment]
Ah, my apologies, items has to be an object. realm.create('BaseTerm', {items}); works. Thank you for your time.

**Comment by laclance** [comment]
It does not save the values though. Do I have to iterate the array and add objects 1 at a time?

**Comment by alazier** [comment]
Yes exactly. Something like ```items.forEach((item) => realm.create('BaseTerm', item))``` should work.

**Comment by laclance** [comment]
Cool. Thank you.
