### ISSUE TITLE
Realm Mobile Platform compatible with React Native ?

### ISSUE THREAD

**Issue by ax88** [realm/realm-js#733]
Hello,
I saw there is a "The Realm Mobile Platform" section on the documentation of Realm database for Objective-C, Java, Swift and Xamarin, but none for react native.
Is it compatible with the realm mobile platform?
If no is it planned to be compatible with react native ?

**Comment by kristiandupont** [comment]
Hi @ax88, no, it's not compatible at this point. We are working hard on making it though, so stay tuned!
