### ISSUE TITLE
PR jobs do not clean up the workspace

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-js#734]
After a build is done, the jobs do not clean up the files, so that each PR run takes 1GB on the slaves.

**Comment by alazier** [comment]
What exactly do we want to clean up? @larkost any suggestions on how to cleanup only the successful jobs?

**Comment by radu-tutueanu** [comment]
We could delete the binaries - both downloaded and created by the build - at the end of the job. If the job fails,  the step that clears the binaries will not have been run.

**Comment by larkost** [comment]
I will take this one, it should be easy to do and I am already working on that JenkinsFile so have it open already.

@alazier: I am pretty sure that @radu-tutueanu is talking about deleting the workspace. In the rare case that it would be useful, this will mean that we will not have access to the contents of the folder after a build for troubleshooting purposes. But in most cases that should be addressed by better logging and deliberate saving of files, and the latter is more of a long-term strategy discussion (so out-of-scope here).

**Comment by larkost** [comment]
As part of #712 (112cda2e) we put in a few lines that will delete the directory on the way out for all successful builds. That should take care of this problem, while leaving broken builds around for a while.

However, I should note that other builds in the same PR, that happen to run on that same client machine will empty out that directory as the first thing that they do, so even broken builds do not stay around forever. Plus, eventually we are going to need better systems to clean out these directories so they don't just build up on actual hosts (we already drop docker builders often enough to probably not see this very often).

I think that saves this problem for this issue most of the time, so I am closing this issue.
