### ISSUE TITLE
Not compatible with javascript template literals filtered(`name = ${name}`)

### ISSUE THREAD

**Issue by maotora** [realm/realm-js#741]
Hi,

I was passing my query conditions using Javascript es6 template literals and noticed an error 

    'number = "111122"':1:0: Invalid predicate.

and the condition was

``` js
const condition = ` number = "${number}"`
```

also tried

``` js
const condition = `number = ${number}`
```

The condition would later go to a `realm.objects.filtered(condition)` to make a query which it then brings that error i showed.

It doesn't bring any error when i use normal string concatenation however.

``` js
    const condition = 'number = "' + number + '"';
```

In my modal i had 

``` js
VehicleSchema = {
    name: 'vehicleInfo',
    properties: {
        name: 'string',
        number: 'int',
        password: 'string',
        type: 'string',
        picture: { type: 'data', optional: true }
    }
};
```

Is this a known issue?

Thank you!

**Comment by reformer** [comment]
I'm facing same issue Invalid predicate. 
My filter criteria is
`filterCriteria = Ids.map((value) => 'Id = ' + "'"+value+"'").join(' OR ')` 
output of above code is "Id = 'MD00078'"
My calling stuff `databaseHelper.retriveValueInTable(databaseHelper.getRealmObject(), "MedRecords", filterCriteria, null);`

My Method fetching data from database
```
exports.retriveValueInTable = function(realm, tableName, filter, sortField) {
  // console.log("exports.retriveValueInTable");

  if(filter === null && sortField === null){
    return realm.objects(tableName);
  }

  if(sortField){
    return realm.objects(tableName).filtered(filter).sorted(sortField);
  } else {
    console.log("Filter "+filter);
    return realm.objects(tableName).filtered("'"+filter+"'");
  }
};
```

My Schema 
name: 'MedRecords',
  properties:{
       "Id"             : "string",
       "TimeId"                 : "string",
       "RecordDate"             : "date",
       "UnitTaken"              : "int",
     } 

 Everything is perfect but fail. Don't understand where is problem,
This is official doc code fetching data,
```
let dogs = realm.objects('Dog');
let tanDogs = dogs.filtered('color = "tan" AND name BEGINSWITH "B"');
```

I also pass same filter string that wanted realm filtered.

**Comment by alazier** [comment]
@kristiandupont what is the actual issue here? Or have we not figured it out yet?

**Comment by kristiandupont** [comment]
Hi @maotora, are you seeing this on iOS, Android or in the chrome debugger? I am unable to reproduce the problem using your code, so there must be something else going on.

**Comment by reformer** [comment]
@maotora  I think the issue is datatype. Realm "number" column has int datatype and you passing number in string datatype. That's why it shows you invalid predicate. Your query string is like "number = 11111" not like "number = "11111" ".

**Comment by maotora** [comment]
Thank you guys,

and am really sorry for the delay as i have been working with something else and not sure how to get instant github notifications.

I commited the project to buyer but i'm pretty sure @reformer 's solution should work.
I have an issue with doing `int` instead of `Number` on types (in realm and mongoose).

@kristiandupont i'm using Android with just the command line.

I will fire up my project to see if @reformer 's solution works then make a comment on this issue.

Thank you all. :)

**Comment by maotora** [comment]
I just checked the docs the datatype is `int` and not `Number` @reformer .

considering this example on realm docs.

``` js
// Define your models and their properties
class Car {}
Car.schema = {
  name: 'Car',
  properties: {
    make:  'string',
    model: 'string',
    miles: 'int',
  }
};
```

**Comment by reformer** [comment]
@maotora  Yes my friend glad to  you found where was the issue lies. I also many times stuck in Realm issues. But it got resolved after seen documentation carefully. Of course Realm has to be mature much more like other databases.
