### ISSUE TITLE
Reloading a React Native app when using Remote JS Debugging causes leaks

### ISSUE THREAD

**Issue by bdash** [realm/realm-js#745]
While looking into #552 I noticed that hitting Cmd-R in the ReactExample app while remote debugging is enabled results in a large part of the native object graph leaking (JavaScript context, open Realms, and any live Realm objects).

To reproduce:

1. Build ReactExample for iOS simulator.
1. Run it under Instruments' Allocations instrument.
1. Enable Remote JS Debugging (Cmd-D, Debug JS Remotely).
1. Press Cmd-R a few times to reload the view.
1. In Instruments, select the Allocations instrument and:
  * Filter the Allocation Summary view by `RealmDelegate` to find the number of Realms that are live.
  * Filter the Allocation Summary view by `CFRunLoopTimer` to get an idea of the number of JavaScript contexts that are live.
1. Press Cmd-R a few more times in the simulator to reload the view some more.
1. Re-check the allocation counts observed in step 5 to see the memory growth.

The underlying cause is a reference cycle between native objects and objects managed by the JavaScript GC. This prevents the JavaScript context from being freed when the page is reloaded, which means no GC is ever performed to collect the JS wrappers and free the native objects they wrap. In particular, `RealmDelegate` holds a strong reference to the `JSGlobalContextRef`, so as long as there is a live `Realm` instance the JavaScript context cannot be destroyed. `ResultsClass<T>::add_listener` introduces a similar problem due to the lambda it passes to `Results::add_notification_callback` holding a strong reference to the `JSGlobalContextRef`, meaning that unless `remove_listener` / `remove_all_listeners` is called the JavaScript context cannot be destroyed.

It seems unsafe for native code to ever hold a strong reference to a `JSGlobalContextRef` for an unbounded duration. Ideally we'd hold weak references to the global context in the places we currently hold strong references, but since JavaScriptCore's C API doesn't support weak references it's not immediately apparent to me how to do this.

**Comment by zachkirsch** [comment]
Did this ever get patched?

**Comment by kristiandupont** [comment]
Not yet, no.

**Comment by mbret** [comment]
Might be related to https://github.com/realm/realm-js/issues/2057. What you described is exactly what happen to us. It basically makes realm unusable
