### ISSUE TITLE
Auto increment id?

### ISSUE THREAD

**Issue by jamesaspence** [realm/realm-js#746]
Hello,

I'm liking Realm so far! I was wondering if auto incremented primary keys or ids would be supported something / is supported already. I didn't see anything in the docs about it.

**Comment by kristiandupont** [comment]
Hi James, 

sorry, we do not support it currently. You can see a discussion of the same request for Java here: https://github.com/realm/realm-java/issues/469

**Comment by rajscet** [comment]
var ID = realm.objects('Student_Info').length + 1;

**Comment by ghorbani-m** [comment]
@rajscet 
`var ID = realm.objects('Student_Info').length + 1;`
this code generates duplicate ID if some date removed from the table.

**Comment by bmunkholm** [comment]
Lookup max value instead and add 1.

**Comment by ghorbani-m** [comment]
another solution is to use guid instead int,
each time to create a new record generate new guid.

**Comment by mimoune** [comment]
hi, I resolve this issue with this steps :

1. get the last Item in table :
`_LastItem(){
        queryAllInventory().then((allInventory) => {
            if(allInventory.length==0){
                this.setState({ lastItemId:1 })
            }else{
                let lastItem= allInventory[allInventory.length-1]
                this.setState({ lastItemId: lastItem.id })
            }
            
        }).catch((error) => {
            this.setState({ error })
        })
    }`

1. and i add 1 to last item :
`let insertInventoryObject = {
            **id: this.state.lastItemId+1,**
            raison: this.state.chosenRaison,
            date: this.state.chosenDate,
            statut: 'Ouvert'
        }`

**Comment by Chris533** [comment]
```
    Realm.open({ path: db, schema: [Qa] })
      .then(realm => {
        const results = realm.objects('Qa').sorted('id');
        const id = results[results.length - 1].id + 1;
        realm.write(() => {
          realm.create('Qa', {...data, id});
        });
        return null;
      })
      .catch(error => {
        console.log(error);
      });
```

**Comment by Chris533** [comment]
> @rajscet
> `var ID = realm.objects('Student_Info').length + 1;`
> this code generates duplicate ID if some date removed from the table.

List ID 1, 2, 3
When delete ID 2
New Id = 3
Realm Creating failed.

**Comment by poleseArthur** [comment]
> var ID = realm.objects('Student_Info').length + 1;

THANK YOU, YOU ARE A GOD

**Comment by luccas-bandeira** [comment]
I'm new to realm, I did as mentioned above but it doubled every time I enter the method

`response.data.forEach(data => {

        const lastlojaID = realm.objects('lojas').sorted('id');
        const id = lastlojaID.length > 0 ? lastlojaID[lastlojaID.length - 1].id + 1 : 1;

        realm.write(() => {
          var idRedeLojas = ""
          const bancoLoja = data.loja.grupo.banco;

          if (data.loja.grupo.id_rede_lojas)
            idRedeLojas = data.loja.grupo.id_rede_lojas

          const novas_lojas = realm.create('lojas', {
            id: id,
            id_loja: data.loja.id_loja,
            nome_loja: data.loja.loja,
            id_grupo: data.loja.grupo.id_grupo,
            codigo_linx: data.loja.codigo_linx,
            codigo_tab_preco: data.loja.parametro.codigo_tab_preco,
            id_rede_loja: idRedeLojas,
            banco: bancoLoja.trim()
          }, 'modified');
        });
        //deleteAllLojas()
      });
`

how do i not duplicate when passing in foreach? I check in the bank if it already has before entering the loop?
