### ISSUE TITLE
Sync for React Native

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#751]

**Comment by SrihariThalla** [comment]
@kristiandupont Do you have any ETA?

**Comment by kristiandupont** [comment]
@SrihariThalla not at this point, sorry. But it's what I am working on :-)

**Comment by SrihariThalla** [comment]
Thanks for the heads up @kristiandupont I'll be waiting for it ;)

**Comment by kristiandupont** [comment]
Splitting this up into sub tasks and closing.
