### ISSUE TITLE
Build on Xcode it failed at RealmJs.build

### ISSUE THREAD

**Issue by chuhongliang** [realm/realm-js#754]
the error details 

/bin/sh -c /Users/fzt/Library/Developer/Xcode/DerivedData/test-dzesprjyobkfwghgrsswhfzjslgg/Build/Intermediates/RealmJS.build/Debug-iphonesimulator/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh

Downloading dependency: core 2.1.4
Using cached core from TMPDIR
core/librealm-ios.a: Lzma library error: Corrupted input data
tar: Error exit delayed from previous errors.
Command /bin/sh failed with exit code 1

**Comment by kristiandupont** [comment]
Hi @chuhongliang, could you provide a bit more info? It sounds like you downloaded a corrupted file, did you try running this multiple times?
