### ISSUE TITLE
Run packager directly

### ISSUE THREAD

**Issue by larkost** [realm/realm-js#759]
In the `start_packager` method in `test.sh` we are starting up `node` implicitly using `node_modules/react-native/packager/packager.sh`. That (two line) script in turn is the one to start `node`. Because of that indirection we had to eventually end the packager by using `pkill node`, which is a bit of using a cannon to kill a fly.  Rather if we started `node` in the same way as that script (by calling `cli.js`) we could then kill that process individually in a cleaner manner.

**Comment by kneth** [comment]
We have changed `test.sh` so many time that I don't believe it is still relevant.
