### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#76]

**Comment by dorongutman** [comment]
needed indeed :hourglass:

**Comment by alazier** [comment]
With the public launch yesterday you can now install Realm using npm without having to clone the source repo. Instructions are here https://realm.io/docs/react-native/latest/#installation

With npm support is there still a reason you would want to install using cocoapods?

**Comment by dorongutman** [comment]
@alazier yes - as with many other packages (react native included - https://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods) using cocoapods after installing via npm reduces the need for the integration inside xcode - all the dragging of xcodeproj files, defining of Link with Binary configuration, etc..
