### ISSUE TITLE
undefined is not an object (evaluating '_NativeModules$Realm.debugHosts') react-native android

### ISSUE THREAD

**Issue by vishadpatel22** [realm/realm-js#762]
undefined is not an object (evaluating '_NativeModules$Realm.debugHosts')

**Comment by imjared** [comment]
OP didn't really provide much info in terms of a submission but I can follow up here and say I'm seeing similar behavior in the iOS simulator.

I'm using
`"react-native": "^0.38.1"`
`"realm": "^0.15.0"`

My sim is an iPhone 6 running iOS 9.1.

Upon loading the sim, here's the output I get:
<img src="https://cloud.githubusercontent.com/assets/525011/21476782/d548dca2-cb09-11e6-8f54-9349a66a6316.png" width="50%" />

**Comment by MiyazakiKaito** [comment]
I'm also having this issue.

**Comment by kristiandupont** [comment]
Are you getting this while using chrome debugging? I think it might be solved by #742 which will be in the next release that will be out this week.

**Comment by imjared** [comment]
Can verify that this doesn't seem to be an issue if DevTools aren't enabled.

**Comment by vishadpatel22** [comment]
create new project and install realm.

**Comment by kristiandupont** [comment]
Are you still experiencing this problem?

**Comment by charlespeters** [comment]
@kristiandupont i'm experiencing this on iOS

**Comment by camslaz** [comment]
@kristiandupont I'm also getting this error.

`"react-native": "0.40.0",`
`"realm": "^0.15.0",`

**Comment by istx25** [comment]
Please provide a project that reproduces this issue and/or any additional information that you can provide that'd put us in the right direction to resolve it.

**Comment by istx25** [comment]
And please file a new issue (referencing this one) once you do.
