### ISSUE TITLE
Ability to observe individual objects

### ISSUE THREAD

**Issue by vaibhawc** [realm/realm-js#763]
I am big fan of both realm and react native and realm has made me love writing apps even more.
If only there was a thing like a listener on individual object, it would have been great. 
Also, should I expect anything like this in near future?
I have seen this discussion on some other thread too, but in a nested object, it doesn't send out notifications on modifying an object of a list child. 
There could both good and bad parts to it. AFAIK, android has it, do we plan to have for JS too?

Thanks for this great library.

**Comment by kristiandupont** [comment]
Yes, this feature exists in some of the other SDK's and will be added React Native as well but we can't give a timeline at this point. 
Thank you for the kind words!
