### ISSUE TITLE
Release mode build throwing error

### ISSUE THREAD

**Issue by jhorman** [realm/realm-js#764]
An app I have been building with Realm, which works great in unit tests, and in Debug mode, seems to throw an exception in Release mode.

```
Dec 28 22:56:50 Jasons-iMac lola[84452] <Error>: Object type 'e' not found in schema.
Dec 28 22:56:50 Jasons-iMac lola[84452] <Critical>: Unhandled JS Exception: Object type 'e' not found in schema.
Dec 28 22:56:50 Jasons-iMac lola[84452] <Error>: *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Object type 'e' not found in schema.', reason: 'Unhandled JS Exception: Object type 'e' not found in schema., stack:
	value@453:2094
	value@453:2970
	<unknown>@487:1370
	value@487:2530
	<unknown>@487:840
	callTimer@55:626
	callTimers@55:1010
	value@53:2623
	<unknown>@53:858
	d@53:127
	value@53:830
```

I have found various references to `Object type not found in schema` online, but

1. I don't have a data type called "e". Is this the result of RN minifying the code?
2. I made sure I don't have any code attempting to create > 1 Realm db. __That said, actually__. I did just manually set a `path` on my DB, and now it isn't happening. Is there another Realm db getting created somehow, inside of Realm itself, with a data type "e"?

**Comment by nhachicha** [comment]
Hi @jhorman 
RN uses `UglifyJS` to obfuscate the code for the `release` target. You might be hitting the same issue  we had for some unit tests, when used in `release` mode. https://github.com/realm/realm-js/pull/755

Maybe you can override the configuration of your locally installed `UglifyJS` (I believe under `node_modules/react-native/packager/react-packager/src/JSTransformer/worker/minify.js`) to disable obfuscation https://github.com/mishoo/UglifyJS2/

you can then run the packager in release mode to generate & inspect the JS bundle file

```
node node_modules/react-native/local-cli/cli.js bundle --platform android --dev false --entry-file index.android.js --bundle-output rel_out.js --assets-dest rel
```

**Comment by jhorman** [comment]
If I turn off mangle, in the minify.js file, our app starts working again, but that can't be the solution right?

**Comment by jhorman** [comment]
It turned out btw that setting the realm `path` didn't help. I had confused myself.

**Comment by kristiandupont** [comment]
@jhorman we made a new release yesterday. Could you try updating and see if it helps?

**Comment by nhachicha** [comment]
@jhorman the goal of turning off the mangle is to check in your code which object/function was causing the issue in release mode. 

Example:
let's say we have a Realm schema defined like this 

```javascript
function PersonObject() {}
PersonObject.schema = {
    name: 'PersonObject',
    properties: {
        name:    'string',
        age:     'double',
        married: {type: 'bool', default: false}, 
    }
};
```
if you use the function name as a key in a Map, the name will be changed to `a` for example 
which might be a problem for you, if you've set up the value elsewhere using the string `"PersonObject"`

**Comment by jhorman** [comment]
Yes, you were right. I did have a few places doing `type.constructor.name` to get the type name back. I switched to `type.schema.name` and things started working again. Might be worth a note in your docs. (maybe there already is one somewhere).

**Comment by netrevisanto** [comment]
Whaaaaat! Thanksssss!
