### ISSUE TITLE
Realm is not defined (React-native + Debug JS Remotely)

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [realm/realm-js#766]
Hi!
When I turn on the Debug JS Remotely feature on my Android emulator, I get this error

![err](https://cloud.githubusercontent.com/assets/12840136/21550837/2557e0bc-cde4-11e6-8487-6c4dd44814cd.png)

When the Debug JS Remotely is Off, I get no errors

Android: API 17
React-native: 0.39.2
Realm: 0.15.2

**Comment by kristiandupont** [comment]
Thank you for the report. Did this error start after updating realm, or was this a new project?

**Comment by raymondctc** [comment]
I encounter the same problem. It seems that starting from 0.39.2, the `navigator.product` object in `getContext()` is always returning `ReactNative` no matter whether it is doing remote debug. It's returning something like `Gecko` in version 0.38.1

Therefore, my temporary solution is that replacing the line in the switch statement:
`realmConstructor = Realm` with `realmConstructor = require('./browser').default; `

**Comment by kristiandupont** [comment]
Argh, just as I updated the constructor detection. Thanks for the info, I will fix this!

**Comment by csotiriou** [comment]
+ 1. Same thing happens on iOS, after updating to RN 0.39

**Comment by csotiriou** [comment]
It's worth noting that when I downgraded my RN version to 0.38 it worked when debugging in Chrome. However, when debugging with Visual Studio Code, the same thing happens, even with React Native 0.38.

**Comment by hangwoo** [comment]
unlink and uninstall realm 0.15.2. then install 0.15.0 realm and react native link so disappear this bug

**Comment by joyerf** [comment]
import Realm from 'realm';
