### ISSUE TITLE
Deactivate mixpanel

### ISSUE THREAD

**Issue by AzSiAz** [realm/realm-js#769]
Hello, 

I just tried to run my nodejs project without internet and it crashed right away since realm can't make a request to api.mixpanel.com.

Is there a way to handle the error so it doesn't crash ? or remove analytic if there is no internet connection ?

```js
events.js:160
throw er; // Unhandled 'error' event
^
Error: getaddrinfo ENOTFOUND api.mixpanel.com api.mixpanel.com:443
at errnoException (dns.js:28:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by fealebenpae** [comment]
Hey @AzSiAz,

To disable analytics you can export the `REALM_DISABLE_ANALYTICS` environment variable in your shell.

**Comment by AzSiAz** [comment]
Oh perfect, I will be using this until next release with #770, thank you :)
