### ISSUE TITLE
Support for React Native v0.40.0

### ISSUE THREAD

**Issue by antoxi4** [realm/realm-js#782]
When you can fix import ReactBridge?)

**Comment by kristiandupont** [comment]
Turns out that RN 0.40.0 has major breaking changes that we need to address: https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by antoxi4** [comment]
@kristiandupont  This is what i mean)

**Comment by csotiriou** [comment]
I can confirm that React Native 0.40 does not work with Ream.

It crashes with this message when trying to import Realm for the first time. 

<img width="377" alt="screen shot 2017-01-07 at 11 53 16" src="https://cloud.githubusercontent.com/assets/1228484/21740888/f02a4338-d4cf-11e6-9d2f-7696046042cf.png">

**Comment by fealebenpae** [comment]
Hey @antoxi4,

I tried to reproduce this using the latest version of Realm on npmjs.com, using the following:
```shell
react-native init ReactExample && cd ReactExample
npm install --save realm
react-native link realm
react-native run-ios
```

<details>
  <summary>Here's how my package.json looks like</summary>

  ```json
  {
    "name": "ReactExample",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "start": "node node_modules/react-native/local-cli/cli.js start",
      "test": "jest"
    },
    "dependencies": {
      "react": "~15.4.0-rc.4",
      "react-native": "0.40.0",
      "realm": "^0.15.2"
    },
    "devDependencies": {
      "babel-jest": "18.0.0",
      "babel-preset-react-native": "1.9.1",
      "jest": "18.1.0",
      "react-test-renderer": "~15.4.0-rc.4"
    },
    "jest": {
      "preset": "react-native"
    }
  }
  ```
</details>
<br />
Please let me know what's the error message that you get and how I can reproduce it for easier debugging.

**Comment by mschipperheyn** [comment]
I recommend adding some release notes clearly stating this upgrade moment as it will be breaking depending on the RN version in use.

**Comment by fealebenpae** [comment]
Hey @mschipperheyn,

We didn't make any changes to Realm for React Native 0.40 (breaking or otherwise), but merely upgraded our test and example apps to the latest React Native to verify everything works.

As far as I can tell, the same Realm package should work on 0.40 and earlier.

**Comment by antoxi4** [comment]
@fealebenpae Thanks. I'll try to install again)
