### ISSUE TITLE
Cannot sync with Node.js

### ISSUE THREAD

**Issue by mytototo** [realm/realm-js#786]
Hi all,

This is my first project with Realm so this is probably a dumb question.
Even following the docs I can't make the sync works between a Node.js app and a Realm platform.

Here is the code:

```js
const Realm = require('realm');

const CarSchema = {
  name: 'Car',
  properties: {
    make: 'string',
    model: 'string',
    miles: {
      type: 'int',
      default: 0
    },
  }
};

const PersonSchema = {
  name: 'Person',
  properties: {
    name: 'string',
    birthday: 'date',
    cars: {
      type: 'list',
      objectType: 'Car'
    },
    picture:  {
      type: 'data',
      optional: true
    }
  }
};

let realm = new Realm({
  schema: [CarSchema, PersonSchema],
  sync: {
    url: 'realm://localhost:9080'
  }
});
```

Issues : 
- `Realm.Sync` does not exist so I can not associate a user to the sync.
- Probably because of this, nothing happens on the platform.

What am I doing wrong?

Thanks for your help.

**Comment by kristiandupont** [comment]
Hi @mytototo, which operating system are you developing on? We released a version yesterday that includes a fix for sync on MacOs, perhaps upgrading will help you?

**Comment by mytototo** [comment]
@kristiandupont The connection with `Realm.Sync` looks like to work fine. No code error at this level. I have one question though. Why the connection close just right after I start it?

The error is:

```
Connection[1]: Connection closed due to error reported by server: Illegal Realm path (BIND) (204)
```

Here is the code:

```js
const Realm = require('realm');

let realm = new Realm({
  schema: [CarSchema, PersonSchema],
  sync: {
    user: Realm.Sync.User.adminUser('token'),
    url: 'realm://localhost:9080/'
  }
});
```

I read from the docs sometimes the path looks like `realm://localhost:9080/~/whatEver` but I don't know why. This path needs to be relative to a specific user id, a Realm path or something else?

**Comment by kristiandupont** [comment]
Hi @mytototo, yes, the url needs to include the path of a realm. The tilde character allows you to have specific realms for each user.

**Comment by mytototo** [comment]
Ok I see. Thanks for the explanation.
