### ISSUE TITLE
More descriptive error message when creating objects

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#787]
If setting a property to the wrong type when creating an object, you still get the vague error message `'Property' must be of type: string` etc.

**Comment by wilomgfx** [comment]
I do agree we need more descriptive errors, if you look at my issue #883, the error does not really point out the real problem.

**Comment by MrHubble** [comment]
Any update on this? I'm getting `property must be of type: number` for an `int` column. This occurs if I try to pass the whole object to update, ie:

````js
realm.create('MyModel', {myObject}, true);
````

It doesn't occur if I individually map the fields, ie:

````js
realm.create('MyModel', {id: myObject.id, myIntColumn: myObject.myIntColumn}, true);
````

I've double checked that my column is a number with `Number.isInteger(myIntColumn)`

Are there any suggested steps for debugging this further?

**Comment by MrHubble** [comment]
I continue to see this problem with multiple models. The error messages goes away if I individually map the fields (as per above example )but that seems to make the `create` action take longer.

**Comment by esutton** [comment]
+1

This has **wasted so much time**...

So ***many*** times
