### ISSUE TITLE
Enumerating on collections via forEach should be implicitly safe to mutations

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-js#798]
When you are in a write transaction and enumerate on a collection, this should implicitly take place on a snapshot, so that it is safe to making mutations while enumerating. Otherwise objects would be removed when they aren't matching the query anymore. e.g.
```js
let dogs = realm.objects("Dog").filtered("age < 5");
dogs.forEach((dog) => {
  dog.age = 6;
});
```
Given this query would contain two instances, this would fail in the second call of the enumeration block, because the first instance wouldn't match the query anymore.

/c @alazier @kristiandupont

**Comment by kneth** [comment]
With 2.0.0 we introduce a different semantics for iterators.

**Comment by Udbhav12** [comment]
@kneth - I am facing the same problem. I am currently using realm 2.14.2. Currently I am using snapshot() to resolve my problem. Is there any better way of solving this?

Please guide

**Comment by kneth** [comment]
`snapshot()` was introduce to solve this problem. You can also use the property [`isValid`](https://realm.io/docs/javascript/latest/api/Realm.Object.html#isValid) on an object to see if it is safe to access it.

**Comment by kneth** [comment]
`snapshot()` doesn't copy any data but you are keeping a particular version of the database (Realm is [MVCC](https://en.wikipedia.org/wiki/Multiversion_concurrency_control)) so it will have an impact on memory and the size of the Realm file.
