### ISSUE TITLE
Storing JSON

### ISSUE THREAD

**Issue by bleonard** [realm/realm-js#8]
React uses [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html) and we can just write an object (json) to disk.

I'm thinking I want to do that in Realm. That is, any given table would have a "document" column and I'd put a bunch of JSON in there. The other columns would only be things I wanted to filter or sort by.

Is that crazy? Here are some of the benefits
- I can actually have a null value :-)
- I can do simple nesting - which is a easier and more reliable than making object graphs in the db
- less migrations
- more or less can cache what comes from the server

The downsides are probably something like the downsides to NoSQL in general
- there are still "migrations" - it's just internal versioning stuff

If it is a not-crazy idea, would I just store a String of the json or is there some more native way to do it?
Is there a string size limit? I see something about 16 MB in the docs for a property.

**Comment by ismdcf** [comment]
So what about the second problem 

> Is there a string size limit? I see something about 16 MB in the docs for a property.

will the string size create an issue.

**Comment by alazier** [comment]
@ismdcf if you want to store larger blocks of data you will need to break it up into smaller pieces or store it outside of Realm.

**Comment by brunobraga95** [comment]
@alazier Is there a new solution for this? I also want to store a JSON value that will constantly change and contain arrays and such. Is using string still the best method?

**Comment by alazier** [comment]
@brunobraga95 no new solution as of yet.

**Comment by brunobraga95** [comment]
@alazier does that mean everytime I need to do a write/query I will have to retrieve and save the whole data?

**Comment by cmbasnett** [comment]
Has nothing been done for this? Why was this closed? The solution posted by @alazier doesn't appear to work anymore.

I have nested JSON objects coming from an API; some of those fields are simple JSON. I have no need to *search* the JSON fields, I merely want to read and write it naturally without needing to serialize/deserialize manually.

**Comment by Dhirajbhujbal** [comment]
I have JSON comming from API it contains the fields whose data type is String and Object.
How to store this nested JSON in realm DB column

**Comment by AmalMenachery** [comment]
@Karthikpala This doesn't seem closed, could please expain the fix
