### ISSUE TITLE
Support aggregates on collections

### ISSUE THREAD

**Issue by astigsen** [realm/realm-js#807]
`.sum()`, `.min()`, `.max()`, `.avg()` should be supported on any collection.

**Comment by luisalima** [comment]
👍

**Comment by ncpope** [comment]
This is very important to many use cases, is there any progress on this?

**Comment by ashwinphatak** [comment]
Merged https://github.com/realm/realm-js/commit/199210eb68a24950467099080789473fb740431b into master
