### ISSUE TITLE
Issue installing/recognising realm-0.15.5-rmp-beta.1.tgz

### ISSUE THREAD

**Issue by ajonno** [realm/realm-js#812]
This is for a React Native project. I think I'm just not importing this .tgz correctly. Here's what I've done:

1. react-native init realmrn
2. downloaded and placed the file "realm-0.15.5-rmp-beta.1.tgz" into root dir of the react native app
![image](https://cloud.githubusercontent.com/assets/3005269/22233021/34fc764c-e241-11e6-9a72-4f219cf1303b.png)

3. npm install --save ./realm-0.15.5-rmp-beta.1.tgz
    This runs for some time/log messages look ok/doesnt throw any errors and completes 

    package.json then has this entry in its dependencies:
```
    ......
   "realm": "file:realm-0.15.5-rmp-beta.1.tgz"
```
4. react-native link realm
    No issues.

In index.ios.js:

```....
     import Realm from 'realm';
     ....
     render() {
       
       var realm;
       Realm.Sync.User.login('http://xx.yy.xx.yy:9080/', 'test@one.com', 'thepwd', (error, user) => {
            realm = new Realm({
         ..... etc..     
        })
     }
```

Then it throws error:
![image](https://cloud.githubusercontent.com/assets/3005269/22232939/a56cd684-e240-11e6-9bc9-d3318acded1d.png)

**Comment by kristiandupont** [comment]
It looks like you are doing everything right. Could you try accessing simply the `Realm` class to see if you successfully imported anything or if it is in fact lacking the `Sync` bits?

**Comment by ajonno** [comment]
thanks Kristian. i did try that should have included for you. there dont seem to be any sync objects. if i inspect the Realm instance -- var realm = new Realm() ;-- it looks like the screenshot here. I also took a look inside the node_modules folder,  /realm/package.json looks like it IS the correct beta version. Maybe I'll send you the RN project (minus the node modules) and you can take a look? 

![image](https://cloud.githubusercontent.com/assets/3005269/22271343/2a717374-e2e8-11e6-8200-6d2ad60fbb90.png)

**Comment by kristiandupont** [comment]
Please be aware that Chrome debugging doesn't work with sync yet, it's one of the issues I am currently working on (#791). So for the moment, you will have to rely on a more manual approach of writing info in, say, a text label etc.

**Comment by ajonno** [comment]
ok no worries. ill do that now and let you know. also emailed you a link to the test project i'm using.

**Comment by ajonno** [comment]
just tested - if i new up a Realm class like so:
```
   let realm = new Realm({
        schema: [{name: 'Dog', properties: {name: 'string'}}]
   });
```

works fine, i can write to it, read from it etc.  

is this what you wanted me to check?

**Comment by kristiandupont** [comment]
Yes. So apparently, you have a version of realm without sync. I don't understand how that could happen. I will take a look at the project you sent me and try to see if I can spot a problem with it.

**Comment by ajonno** [comment]
thanks Kristian, appreciate your help.

**Comment by ajonno** [comment]
hey Kristian - just checking in to see if you had a chance to look at this today ?

**Comment by kristiandupont** [comment]
Hi @ajonno, so it seems to work on my machine. Your code contained a masked out ip address -- are you running the object server on a different machine? Try tunning it locally. Also, does the server output say anything when you try to connect?

**Comment by ajonno** [comment]
thanks for doing that Kristian. i'm trying to connect to an AWS instance. Realm browser works fine so i know the backend is functioning/up. ill try running against a local Mac instance as you've said and see how it goes.  in terms of server output when trying to connect - i didn't look closely there so shall also do that today. ill let you know how it all goes once done.

**Comment by kristiandupont** [comment]
@ajonno, if you have further issues, please create new ones in Github. I'm closing this one.
