### ISSUE TITLE
Add option to delete realms if a migration is needed

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-js#814]
Like in [Swift](https://realm.io/docs/swift/2.3.0/api/Classes/Realm/Configuration.html#/s:vVC10RealmSwift5Realm13Configuration28deleteRealmIfMigrationNeededSb).

**Comment by kneth** [comment]
Duplicate of #502

**Comment by ashwinphatak** [comment]
Merged https://github.com/realm/realm-js/commit/670f7507f2becaa9080a7bcec54de0f0e314982f into master
