### ISSUE TITLE
Getting `Unknown execution context` on Android.

### ISSUE THREAD

**Issue by sharq1** [realm/realm-js#817]
I discovered that `navigator.product` equals `ReactNative`, but `typeof Realm` is `undefined`, thus following error.

Tried different emulators and different API's (23 and 25).

At the same time it works in the same app on iOS.

```
Unknown execution context
getContext
    index.js:62
<unknown>
    index.js:67
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    db.js:1
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    syncDbActions.js:32
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    sync.js:120
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    sync.js:7
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    configureStore.js:44
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    Buddle.js:142
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.android.js:3
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:116
_require
    require.js:107
global code
    require-0.js:1
```

**Comment by kristiandupont** [comment]
Hi @sharq1 did you remember to run `react-native link realm` on your project?

**Comment by sharq1** [comment]
@kristiandupont I did not, indeed.
Thank you very much and sorry for taking your time.

**Comment by kristiandupont** [comment]
Well, you still pointed out to me that you were getting the wrong error message so I need to fix that, thanks!

**Comment by glendmaatita** [comment]
hi @kristiandupont, i am facing this problem eventhough i have linked realm to my RN app. seems like the issue is similar with @sharq1 's

**Comment by barron9** [comment]
linked but same here

**Comment by chrise86** [comment]
Getting the same on iOS when running on device. https://github.com/realm/realm-js/issues/850 might be related

**Comment by ankittyagi** [comment]
Faced same issue ... find out that another react native app is running in another terminal.
Closes that and run again 
```
react-native run-ios

```

**Comment by barron9** [comment]
yes thanks
