### ISSUE TITLE
ObjectSchema error

### ISSUE THREAD

**Issue by amanthegreatone** [realm/realm-js#819]
Hi,

I am trying to initialize a new realm and getting this ObjectSchema error.

this is my realm.js

```
import Realm from 'realm';

import Country from './schemas/Country';

const VERSION_TEST = 0
const SCHEMA_VERSION = VERSION_TEST

const realm = new Realm({
  schema: [
    //VERSION_TEST
    Country,
  ],
  schemaVersion: SCHEMA_VERSION,
  migration: function(oldRealm, newRealm) {
    console.log("old realm version:", oldRealm.schemaVersion, "new realm version:", newRealm.schemaVersion);
  },
});

export default realm;
```

here is my Country.js file with schema definition

```
export const Country = {
  name: 'Country',
  primaryKey: 'id',
  properties:{
    id: 'int',
    name: 'string',
    code: 'string',
    timezone: 'string',
    currency: 'string',
    calling_code: 'string',
  }
};
```

This is the error i get 
![screen shot 2017-01-28 at 8 11 47 pm](https://cloud.githubusercontent.com/assets/24354452/22397375/19d35662-e596-11e6-817d-71c35ee4666d.png)

Is something wrong with the export import const Schema as when I declare the Country schema in realm.js file instead of importing it the error is not there.

RN 0.40
iPhone 6 simulator / Android 4.1 simulator
realm@0.15.4

**Comment by fealebenpae** [comment]
You need to either `import { Country } from './schemas/Country'`, or `export default = { ... }`.

**Comment by amanthegreatone** [comment]
aaah. noob mistake! thanks :)
