### ISSUE TITLE
Not work case insensitive

### ISSUE THREAD

**Issue by antoxi4** [realm/realm-js#820]
I try filter items with this query

`items.filtered('actualName CONTAINS[c] $0', 'паркова');`

and items result is zero. but if i change query string for
`items.filtered('actualName CONTAINS[c] $0', 'Паркова');`
 then result is right.

RN 0.38
IOS, ANDROID.
Realm 0.15.4

**Comment by istx25** [comment]
Hi @antoxi4. Thanks for reaching out. We're working through a bit of backlog and will be in touch with a solution or follow-up questions soon. Cheers! :)

**Comment by kristiandupont** [comment]
Hi @antoxi4 sorry, sorting and case insensitive string matches in queries are only supported for character sets in ‘Latin Basic’, ‘Latin Supplement’, ‘Latin Extended A’, ‘Latin Extended B’ (UTF-8 range 0-591).

**Comment by alexstoyanov** [comment]
@kristiandupont Are you going to support Cyrillic in the future? This is very important for applications which use this character set.

**Comment by dimlksin2** [comment]
Is there a solution to this problem? How can I get around this?

**Comment by dimlksin2** [comment]
why closed the task without a correct answer, the task is relevant and important not only for me!

**Comment by bmunkholm** [comment]
@dimlksin2 You are welcome to create another issue with a request to support it. But just to set expectations, it's not trivial to do as it requires us to include a big ICU library.
