### ISSUE TITLE
Not work not equal

### ISSUE THREAD

**Issue by antoxi4** [realm/realm-js#821]
This query not work 

`items.filtered('storeTypes.id != $0', 'intrist-west_Y000000003');`

result is all entries in table.

RN 0.38
Realm 0.15.4
IOS, Android

**Comment by istx25** [comment]
Hi @antoxi4. Thanks for reaching out. We'll be in touch with a solution or follow-up questions soon. :-)

**Comment by kristiandupont** [comment]
Hi @antoxi4, do you have a realm file that I can try to use to reproduce this?
