### ISSUE TITLE
Realm requires gradle 2.2?

### ISSUE THREAD

**Issue by hisham** [realm/realm-js#822]
I'm getting this error when building android app with realm. So there is no support for gradle version 2.14.1 currently? 

`Error:Gradle version 2.2 is required. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in <path>gradle-wrapper.properties to gradle-2.2-all.zip.
`

**Comment by istx25** [comment]
Hi @hisham. Thanks for reaching out. We're working through a bit of backlog but someone will follow-up with you with more information soon. Cheers!

**Comment by kristiandupont** [comment]
@hisham yes, I'm afraid Gradle 2.2 or higher is required.

**Comment by hisham** [comment]
@kristiandupont - Gradle 2.14 _is_ higher than 2.2. But your build refuses to compile because you need the lower Gradle 2.2 version. You have this as a dependency in your android/build.gradle: 'com.android.tools.build:gradle:1.3.1'. It should be changed to 2.2.3 so that it works with the latest gradle. 

Can you reopen this issue as it's not resolved?

**Comment by kristiandupont** [comment]
Ah, my apologies, you are right.

**Comment by blagoev** [comment]
@hisham I can't reproduce this with the latest version of realm and RN. Also tried with realm 1.0.1. Builds is ok. Can you confirm it is still failing on your side? Or it is fixed?

The latest version of RN is using 2.14.1 when you create a new project.
