### ISSUE TITLE
isValid for js objects

### ISSUE THREAD

**Issue by gritzko** [realm/realm-js#829]
In js, we have no way of knowing whether the inner Realm object is still alive.
That may generate plenty of intermittent bugs if:

1. a developer does not check for object liveness in other ways (list membership, etc)
2. a developer can't check for object liveness at all (e.g. a handle is given to React or other framework)

Solution: add `isValid()`, like in the .NET version.

**Comment by gritzko** [comment]
Pardon, it has isValid since last April.

**Comment by juanfer0002** [comment]
Hi.

If for some reason you can't find the method **isValid()** in an object that comes from realm, either by using **Realm.objectForPrimaryKey** or **Realm.objects**., then try this.

When you create your model, it must look like this (extends Realm.Object)

```
import Realm from 'realm';

// Define your models and their properties
class App extends Realm.Object { }
App.schema = {
    name: 'App',
    properties: {
        version: 'string'
    }
};
```

Then you can add your class to Realm schema as Documentation specifies:

`Realm.open({schema: [App]})`

or instantiate it:

```
const realm = new Realm({
    schema: [App]
});
```
Just do that with all your objects, then you can use Realm.Object functions: https://realm.io/docs/javascript/latest/api/Realm.Object.html

I hope it helps someone, it took me a while.
