### ISSUE TITLE
realm.write return changed data

### ISSUE THREAD

**Issue by atom2ueki** [realm/realm-js#835]
is there any plan make realm.write return the data write into realm database, so that easy to handle data return without query again from realm? #

**Comment by csotiriou** [comment]
I have found that you can already do that, albeit with a less-than-graceful way.

Pseudocode:

```
let newUsers = []
realm.write(() => {
   let user = realm.create('User', <<new object properties>>)
   newUsers.push(user)
})

//the new users array contains all created objects.
//since realm.write() is synchronous, you can safely return the array here.
```

**Comment by atom2ueki** [comment]
@csotiriou thanks
