### ISSUE TITLE
Auto-edit of MainApplication.java

### ISSUE THREAD

**Issue by gritzko** [realm/realm-js#837]
Some overly smart build script edits the Android boilerplate, apparently.
It does so repeatedly (mistakenly), adding double lines.
Which results in a mystical error message.
This time, I observed this when building a fresh checkout of RealmTasks.

```diff
diff --git a/RealmTasks React/android/app/src/main/java/io/realm/react/example/MainApplication.java b/RealmTasks React/android/app/src/main/java/io/realm/react/example/MainApplication.java
index fd45f4f..e959bc4 100644
--- a/RealmTasks React/android/app/src/main/java/io/realm/react/example/MainApplication.java    
+++ b/RealmTasks React/android/app/src/main/java/io/realm/react/example/MainApplication.java    
@@ -4,6 +4,7 @@ import android.app.Application;
 import android.util.Log;
 
 import com.facebook.react.ReactApplication;
+import io.realm.react.RealmReactPackage;
 import com.facebook.react.ReactInstanceManager;
 import com.facebook.react.ReactNativeHost;
 import com.facebook.react.ReactPackage;
@@ -27,6 +28,7 @@ public class MainApplication extends Application implements ReactApplication {
     protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(
           new MainReactPackage(),
+            new RealmReactPackage(),
           new RealmReactPackage()
       );
     }
```

Grep did not find the offender (`grep -ri RealmReactPackage *`)
attn @fealebenpae

**Comment by fealebenpae** [comment]
That seems to be the `react-native link` CLI tool at work - it doesn't pick up that the package has already been added because of the indentation, I think. We should remove all mentions of Realm from `MainApplication.java`, run `react-native link realm` and commit the changes.

**Comment by gritzko** [comment]
> On Feb 2, 2017, at 2:08 PM, Yavor Georgiev <notifications@github.com> wrote:
> 
> commit the changes

Done
