### ISSUE TITLE
Remote-Local Sync

### ISSUE THREAD

**Issue by akusany2** [realm/realm-js#845]
Hi, how can I sync data between realm-mobile-database and realm-object-server? I've read the whole docs but could not find how to connect or sync those 2 realm files. 
Is it done behind the scene?
Do I have to call a function for that?

I've raised a question regarding this same issue on stackoverflow too. [Link] (code sample are there)(https://stackoverflow.com/questions/42052337/realm-sync-remote-to-local)

**Goals**
Automatic or manual syncing between local and remote realms.

**Actual results**
Both realm-mobile and object-server have different objects stored in them, they are not syncing.

react-native: 0.41.1
realm: 1.0.1

**Comment by kristiandupont** [comment]
Hi @akusany2, I've commented on your SO post, so I will close this.
