### ISSUE TITLE
Function result as default value

### ISSUE THREAD

**Issue by fever324** [realm/realm-js#846]
Hi I was trying to set the default value of id to a function that generates an Id, and it is not working for me.

Could you take a look at it and let me know if anything is wrong?
Thank you!

Here is my schema
```
import ObjectId from 'bson-objectid'

class User {
// Add functions here
}
const UserSchema = {
  name: 'User',
  primaryKey: 'id',
  properties: {
    id: {type: 'string', default: ObjectId().id },
    email: 'string',
    password: 'string',
    firstName: { type: 'string', optional: true },
    lastName: { type: 'string', optional: true },
    avatar: { type: 'string', optional: true },
    createdAt: { type: 'date', default: new Date() },
    updatedAt: { type: 'date', default: new Date() },
  },
};

User.schema = UserSchema;
export default User;
```

**Comment by istx25** [comment]
Hey @fever324, thanks for reaching out. I'll ping one of the engineers to look into this for you.

**Comment by istx25** [comment]
I'm not a JavaScript developer but is it possible that the spelling mistake: `ObejctId` could be related to your problem? I looked up [`bson-objectid`](https://github.com/williamkapke/bson-objectid) and its [usage docs](
https://github.com/williamkapke/bson-objectid#usage) point to it being `ObjectId` not `ObejctId`. If not, no worries but I thought I'd chime in.

**Comment by fever324** [comment]
Hi, thanks for getting back to me. 

Sorry about the `ObejctId`, it's a typo on my side.
I have also verified that `typeof(ObjectId().id)` is a `string`

**Comment by istx25** [comment]
Sorry - so the problem has been resolved? Or was it unrelated? Thanks.

**Comment by fever324** [comment]
It's not resolved. ☹️

**Comment by istx25** [comment]
Okay, thanks for clarifying that for me (I'm in the process of learning JavaScript). One of the JavaScript engineers will be in touch soon to help you further debug the issue.

**Comment by fever324** [comment]
I'm not sure if providing functions as default value is supported in realm-js according to this pull request #414.

**Comment by kristiandupont** [comment]
Hi @fever324 sorry, we do not support functions as default values. For now, it's probably easiest to wrap `realm.Create` in another function if you want something like it.
