### ISSUE TITLE
Unknown execution context on iOS Simulator with Remote JS Debugging

### ISSUE THREAD

**Issue by aparedes** [realm/realm-js#850]
1. Goals
Debug code with Remote JS Debugging.

2. Expected results
Debug code with Remote JS Debugging.

3. Actual results
Red error screen with title 'Unknown execution context'
![uec](https://cloud.githubusercontent.com/assets/480605/22728147/a8c1c11c-eddc-11e6-8bf8-0a651a2afdfa.png)

4. Steps to reproduce
* Create new project `react-native init TestRealm`
* Install Realm `npm install --save realm` or `yarn add realm`
* Link Realm `react-native link realm`
* In index.ios.js insert `import Realm from 'realm`
* Run code `react-native run-ios`
* Enable Remote JS Debugging

5. Code sample that highlights the issue 
    **https://github.com/aparedes/TestRealm** 

6. Version of Realm 1.0.2 / Xcode 8.2.1 / OSX 10.11.6

**Comment by kristiandupont** [comment]
Hi @aparedes did you run `react-native link realm`? This should be noted in the error message, I need to fix that..

**Comment by aparedes** [comment]
Yes, I did run `react-native link realm`. 

I only get this error with the Remote JS Debugging activated, otherwise it works and I can write and read to/from the Realm database.

**Comment by kristiandupont** [comment]
I see, in that case something else is wrong. Thank you for reporting.

**Comment by anonymoushitec** [comment]
I got this issue, too. Does it fix yet?

**Comment by jankjr** [comment]
I tried to reproduce this problem, but its to be running fine on my computer, tried both iPhone SE and iPhone 6 simulators.

Looking at the `getContext` here [here](https://github.com/realm/realm-js/blob/master/lib/index.js#L57-L60), it seems to only work when useragent is set to contain Chrome. What debugger are you using?

Realm 1.0.2, Xcode 8.2.1, OSX 10.12.3

**Comment by aparedes** [comment]
I'm using Realm 1.0.2 / Xcode 8.2.1 / OSX 10.11.6 / React-Native 0.41.2 / Chrome 56

I can't reproduce it anymore, could be something with Xcode, that needed a restart or something.

**Comment by lnlfps** [comment]
I got this issue, too. if close the "Remote JS Debugging', it's works well.

**Comment by lnlfps** [comment]
```javascript
    if (typeof Realm !== 'undefined') {
        if (typeof navigator !== 'undefined' &&
            navigator.product === 'ReactNative') { // eslint-disable-line no-undef
            return 'reactnative';
        }

        return 'jscore';
    }
```

when Remote JS Debugging is off, the fragment return 'reactnative'.  if remote js debugging is on, return undefined, so ```throw Error("Unknown execution context");```

**Comment by aparedes** [comment]
I had the same, but tried again a few days later and it worked. I didn't change a thing.

**Comment by aparedes** [comment]
Do you have the debugger with device toolbar on?<img width="26" alt="screen shot 2017-02-17 at 14 58 48" src="https://cloud.githubusercontent.com/assets/480605/23067941/bf6d7b58-f521-11e6-9668-384d7350de7f.png">

It seems that is the one causing the problems. Or at least for me.

**Comment by agahEbrahimi** [comment]
I have the same problem
I didn't under what you mean by Remote JS debugging

**Comment by aparedes** [comment]
I mean in Chrome Dev Tools

**Comment by aparedes** [comment]
When you are in the phone or simulator, you enable the debugging and it opens chrome. In chrome, if you press the device toolbar on it shows the web view in a "mobile" view. That seemed to be causing some issues for me. When it was disabled, it was acting normal

**Comment by agersoncgps** [comment]
I am having the same issue. It only happens when I am debugging with Nuclide debugger. Works fine with dubugging off and when dubugging routed through Chrome.

**Comment by sumesh1993** [comment]
running `react-native run-ios` again, worked for me.

**Comment by chrise86** [comment]
Also getting this error when trying to run on (iOS) device. Haven't changed anything, but after working on a different project and trying to run this one again it just started failing :(

**Comment by oliviachang29** [comment]
I have the same problem with debugging off. Nothing works.
Tried the following:

- restart server
- run react-native run-ios again
- restart comp (mac osx)
- installing on fresh new react native project

**Comment by kristiandupont** [comment]
@oliviachang29 I am sorry to hear that. If you are able to provide us with a repro-case in some form we can try taking a look at it.

**Comment by oliviachang29** [comment]
Got it working after starting on a fresh new project. Not sure what specifically got it to work.

**Comment by sp-suresh** [comment]
I am not running in debug mode. Still, I am getting the same
![222](https://user-images.githubusercontent.com/20751381/27435025-57499534-5778-11e7-8e2c-6858de33117f.png)
![111](https://user-images.githubusercontent.com/20751381/27435026-574a5456-5778-11e7-8641-257e87ab7f38.png)

**Comment by camslabosz** [comment]
Why is this closed? It's still a problem.

**Comment by SaurabhKshirsagar** [comment]
I am facing same problem
