### ISSUE TITLE
Uniqueness based on two fields

### ISSUE THREAD

**Issue by fever324** [realm/realm-js#861]
Is there any way to create an constraint that ensures the two fields combined together is unique in a table? 

For example I would like to keep `id` as my primary key and want to make sure the combination of email and name is unique in the table.
```
const TestSchema = {
  name: 'Test',
  primaryKey: 'id',
  properties: {
    id: 'string',
    name: 'string',
    email: 'email',
  },
}
```

**Comment by kristiandupont** [comment]
Sorry, you will have to enforce that manually at this point. We are considering offering combined primary keys but it's still on the drawing board.
