### ISSUE TITLE
Create and Update NOT working on reload

### ISSUE THREAD

**Issue by lodev09** [realm/realm-js#870]
I'm currently following this doc:
https://realm.io/docs/javascript/latest/#creating-and-updating-objects-with-primary-keys

Basically, if I insert a data with primary key it should update the specified properties and "ignore" other properties -- it's not doing this at all. Although it doesn't insert a new row when the primary key is existing but it's setting those unspecified properties to NULL (or the default)  instead of retaining current values.

For example, I'm trying cache photos fetched remotely:
![auto_update_issue](https://cloud.githubusercontent.com/assets/6686328/23034954/8c486dd2-f4b8-11e6-8e19-60e870feb910.gif)

It shouldn't set the `cached` field to `false` when they are already `true` as it will fetch again instead of reusing the path.

** schema **
```js
class Photo {
	static schema = {
		name: 'Photo',
		primaryKey: 'id',
		properties: {
			id: 'int',
			filename: 'string',
			cached: { type: 'bool', optional: true, default: false },
			/* ... */
		}
	}

	source() {
		return { /* RN source */ };
	}

	async init() {
		if (this.cached) return this.source();

		const info = fileInfo({
			folder: Photo.folder,
			filename: this.filename
		});

		/* fetch the image and realm write cached = true
	}
}
```

** realm setup **
```js
const schemas = [ Photo /* ... */ ];

const realm = new Realm({
	schema: schemas,
	schemaVersion: SCHEMA_VERSION
});

schemas.forEach((ObjectType) {
	// insert new object
	ObjectType.insert = (data) => {
		return realm.create(schemaName, data, true); // the true arg should update existing rows
	};
}
```

Am I missing something here? Are persisting data supposed to be overwritten when you reload?

Any help is much appreciated!

**Comment by lodev09** [comment]
I think I see where my problem is.. Sorry to bother you guys :)

**Comment by istx25** [comment]
No need to apologize, @lodev09! Happy to hear you resolved the issue. We're here if you need help with anything else. :)

**Comment by abser** [comment]
@lodev09 ,
I am new in realm and having same issue when reloading the app. How you fix it?

**Comment by lodev09** [comment]
@abser it was not a realm issue but an issue with my code using redux. there was a bug that keeps redux updating and resetting the keys. I forgot the details but again, it was not an issue with realm :)
