### ISSUE TITLE
react-native unlink fails

### ISSUE THREAD

**Issue by fungilation** [realm/realm-js#872]
I want to unlink before upgrading and then re-link. But this fails:
```
$ react-native unlink realm
rnpm-install info Unlinking realm android dependency 
rnpm-install info Android module realm has been successfully unlinked 
rnpm-install info Unlinking realm ios dependency 
rnpm-install ERR! It seems something went wrong while unlinking. Error: Cannot read property 'children' of null 

Cannot read property 'children' of null
```

Later when I run react-native link, it says:
```
rnpm-install info Linking realm android dependency 
rnpm-install info Android module realm has been successfully linked 
rnpm-install info iOS module realm is already linked 
```

**Comment by fungilation** [comment]
Resolved with deleting an orphaned library in Xcode. It's somehow broken and left as a Xcode library with no text label. Deleting it then react-native link again works.

**Comment by istx25** [comment]
Hi @fungilation. Thanks for reaching out. Glad to hear you resolved the issue. Please let us know if you need help with anything else! :)
