### ISSUE TITLE
Unknown named module: './submit-analytics' when debugging with vs code

### ISSUE THREAD

**Issue by sparameshwar** [realm/realm-js#873]
Not sure whether this is a VS code issue or a realm issue. When I debug my app using VS code, I get the following error. I see that all the other modules under node_modules/realm/lib are loaded properly but not submit-analytics.js. Let me know if you need more details.

```
Unknown named module: './submit-analytics'
_require
    require.js:93:12
nodeRequire
    index.js:23:11
<unknown>
    index.js:70:8
loadModuleImplementation
    require.js:171:4
guardedLoadModule
    require.js:123:11
_require
    require.js:107:6
<unknown>
    db.js:1
loadModuleImplementation
    require.js:171:4
guardedLoadModule
    require.js:123:11
_require
    require.js:107:6
```

**Comment by avishayil** [comment]
+1

**Comment by istx25** [comment]
Hi @sparameshwar (and @avishayil). Thanks for reporting this. Someone will review what you've shared and follow-up with you soon with more information and/or questions. Cheers!

**Comment by yblunan** [comment]
I found the error in  realm/lib/index.js
function getContext
The function retend "nodejs"  but not "reactnative"

**Comment by mongris** [comment]
It's a new issue after VS Code 1.9.1 updated.
I were pull a request to fix VS Code crash issue in VS Code 1.9, but it's not working 1.9.1 now.
More information here: https://github.com/realm/realm-js/pull/855

I think realm-js should implement data request asynchronous.

**Comment by gritzko** [comment]
Technically, you can safely delete submit-analytics, except it is the key symptom in our case :)

Regarding platform detection heuristics, there is a branch for that:  https://github.com/realm/realm-js/commit/f6347cf59fd71f90723f38f63152418ab642f348
I'll be happy if you'll find some regressions there.

VSCode 1.9.1 fast fix by mongers: https://github.com/realm/realm-js/pull/855#issuecomment-282658385

Synchronous requests are kind of problematic, because Realm access model is exclusively synchronous (it is a very fast embedded mmap'ed database). That causes some difficulties when the js environment runs separately from the native env (#491).

**Comment by sparameshwar** [comment]
Deleting submit-analytics didnt work. I now get an error: "Unknown named module: './submit-analytics'". Reopening the issue. It will be good to have a build that fixes the issue.

**Comment by sparameshwar** [comment]
I cant seem to reopen the issue. @gritzko - can you help reopen it?

**Comment by gritzko** [comment]
@sparameshwar did you use the VS Code fast fix? https://github.com/realm/realm-js/pull/855#issuecomment-282658385

**Comment by sparameshwar** [comment]
Yes, I did but it didnt help.


________________________________

**Comment by gritzko** [comment]
@sparameshwar Then, you may try using an older VS Code release while waiting for a new release that fixes the regression https://github.com/Microsoft/vscode-react-native/issues/406#issuecomment-282670868.

**Comment by ajonno** [comment]
i just tried debugging today on VSCode 1.11.1 and it crashed with this error too. bummer. any eta on a fix ?

**Comment by mongris** [comment]
@gritzko there is missing https://github.com/realm/realm-js/commit/f6347cf59fd71f90723f38f63152418ab642f348 to fix `getContext` issue in the latest release. Can you confirm it will be release in the next release please?

**Comment by nechmads** [comment]
Anyone knows how to fix this?
I'm running react native with realm 1.3.1 and VSCode 1.12.2 and still get this error when trying to debug using VSCode and React Native Tools:
"Unknown named module: './submit-analytics'
Module AppRegistry is not a registered callable module (calling runApplication)"

Any help will be super appreciated.

**Comment by Arcanfel** [comment]
Same error. Debugging is impossible atm.

**Comment by Arman92** [comment]
I'm having this issue too, deleted the `nodeRequire('./submit-analytics')('Run');` in `/.vscode/.react/index.android.bundle`

But it was there again after another debugging attempt.
Should we consider this a vscode bug?

**Comment by puelocesar** [comment]
Hotfix by @blagoev https://github.com/realm/realm-js/commit/3764d4bf55ee604b2fdd3f02eb6a3e25dd0b07fd

**Comment by blagoev** [comment]
I will be creating a PR for merging this then. Cheers everyone!

**Comment by blagoev** [comment]
https://github.com/realm/realm-js/pull/1062
