### ISSUE TITLE
Realm is not defined 

### ISSUE THREAD

**Issue by amirhaghajani** [realm/realm-js#874]
Realm dont work on debugging

**Comment by istx25** [comment]
Hi @amirhaghajani. Thanks for reaching out. Would you be able to provide more information about the problem you're experiencing and code samples and/or information about your dev setup so we have more information to go on while trying to help? Cheers!

**Comment by amirhaghajani** [comment]
Hi. thank you for your attention.
When I turn on the Debug JS Remotely feature on my Android emulator, I get this error.
I used Realm 1.0.0
<img src="http://proxy.ge.tt/thumbnail/7p5f9vi2/0/user-wsnj0piiKpEEYHWu87s5f9ppOrwOjLK29B9Ca-/0x675.png?ofn=error.png&referrer=user-wsnj0piiKpEEYHWu87s5f9ppOrwOjLK29B9Ca-" alt="err" style="max-width:100%;">

**Comment by amirhaghajani** [comment]
When I turn on the Debug JS Remotely feature on my Android emulator, I get
this error.
I used Realm 1.0.0

**Comment by istx25** [comment]
Rather than a screenshot of your code, would you be able to provide the code itself @amirhaghajani?

**Comment by amirhaghajani** [comment]
I've simplified my code and remove all things to show that it is not depends on my code.

<pre>
<code>
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
    Button
} from 'react-native';

export default class smart01_dbTest extends Component {
    
    realm : undefined;
    
    constructor(props){
        super(props);
        
        const realm = this.realm = new Realm({
            schema : [
                {
                    name : 'User',
                    properties : {
                        firstName : 'string',
                        lastName : 'string',
                        email : 'string'
                    }
                }
            ]
        });
    }
    
    
    
    
  render() {
    return (
      <View>
        <Text>Test</Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('smart01_dbTest', () => smart01_dbTest);

</code>
</pre>

**Comment by kristiandupont** [comment]
@amirhaghajani sorry for the late reply, I've been on vacation. It looks like you need to add an import statement for Realm:
```
import Realm from 'realm';
```

**Comment by amirhaghajani** [comment]
It works like a charm, thanks for your help
