### ISSUE TITLE
Xcode stuck building RealmJS 

### ISSUE THREAD

**Issue by barbatus** [realm/realm-js#880]
Brand new React Native app created wirh `react-native init` and added Realm NPM can't build hanging on the step 'Building ReamlJS'.
Steps to reproduce:
- `react-native create app`
- `cd app & yarn add realm --save`
- `react-native link`
- `open ios/app.xcodeproj` and Build

react-native-cli@2.0.1
Xcode@8.2.1

**Comment by fealebenpae** [comment]
Hey @barbatus, could you please post the Build log from the Xcode Report navigator?

**Comment by barbatus** [comment]
@fealebenpae thanks, I checked there (not very familiar withe xcode).
It's stuck on downloading https://static.realm.io/downloads/core/realm-core-2.3.0.tar.xz.
This link seems pretty slow.

**Comment by fealebenpae** [comment]
Our downloads go through a Cloudflare CDN, and they seem to be having issues in some locations at the moment: https://www.cloudflarestatus.com. Unfortunately you might be affected. Hopefully this will be resolved soon. My suggestion is to try to wait it out - once the archive is downloaded it'll be cached locally.

**Comment by barbatus** [comment]
@fealebenpae thanks!
