### ISSUE TITLE
Realm Endpoint Connection Error

### ISSUE THREAD

**Issue by danielmhanover** [realm/realm-js#886]
My Realm Object Server was working up until this morning. Now, attempting to connect to it yields this error:

Connection[1]: Resolving 'localhost:9080'
Connection[1]: Connecting to endpoint '127.0.0.1:9080' (1/1)
ERROR: Connection[1]: Failed to connect to endpoint '127.0.0.1:9080': Connection refused
ERROR: Connection[1]: Failed to connect to 'localhost:9080': All endpoints failed

I have not chnaged any of my network settings. Any ideas?

**Comment by istx25** [comment]
What version of the ROS are you using and how are you deploying it? On macOS or on a server? Please share as much information as you can. Thanks!

**Comment by danielmhanover** [comment]
This issue was resolved. Apparently ROS can't handle DigitalOcean floating IPs

**Comment by istx25** [comment]
Okay, sounds good. If you'd like ROS to work with Digital Ocean floating IPs, I recommend filing a feature request on https://github.com/realm/realm-mobile-platform/issues/new.
