### ISSUE TITLE
Error when installing RealmJS with Node.js on Windows

### ISSUE THREAD

**Issue by kr05** [realm/realm-js#888]
I'm trying to install Realm javascript with "npm install --save realm" command, but I get the following error:

```
ERROR: Realm is not yet supported for Node on Windows
npm WARN cf-tester No description
npm WARN cf-tester No repository field.
npm WARN cf-tester No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "realm" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! realm@1.0.2 install: `node scripts/install.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the realm@1.0.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the realm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs realm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls realm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kevin Rivera\cf-tester\npm-debug.log
```

I noticed this problem was already fixed in #689 , which is why this has me quite confused. 

npm version: 3.10.10
node version: 6.10.0

**Comment by fealebenpae** [comment]
Hey @kr05,

Is this a React Native project? Currently realm-js on Windows can only be installed in a React Native project, provided the `react-native` module is installed first.

**Comment by kr05** [comment]
It isn't. The only thing I'm using is Node.js

In that case, would the only solution be using linux?

**Comment by fealebenpae** [comment]
Linux or macOS. We're working on adding support for Windows, though, so that should be available in the near future.

**Comment by mehdi-cit** [comment]
Hello @fealebenpae 
>>We're working on adding support for Windows, though, so that should be available in the near future.

How "near"? Not asking for an exact release date but would you say days, weeks or months?
Thanks

**Comment by kristiandupont** [comment]
It's in the "weeks" category. :-)

**Comment by mehdi-cit** [comment]
Thank you @kristiandupont 
For what's worth, I do believe that having realm-database ready for node.js/electron in all platforms (windows included) will bring a lot of attention to realm as a whole.
There's a very strong need for a light weight embedded database that can seamlessly work with node.js/electron and realm could be just that!

**Comment by kristiandupont** [comment]
I hope you are right! 😄 Note though that we are not officially supporting Electron just yet, so that is also a bit into the future.

**Comment by kr05** [comment]
I happily started running Realm from a machine running Ubuntu 16.04, when I noticed that RMP only works with Android/iOS. :( 

Any suggestion/workarounds to getting it to work from a web app context?

**Comment by kristiandupont** [comment]
@kr05 at the moment there isn't a lot you can do if you don't want to go with the [professional edition](https://realm.io/pricing/) -- but we are looking into different ways of alleviating this situation so stay tuned

**Comment by kr05** [comment]
What would the professional edition allow me to do? I combed through the email and the scanner app, but I'm still clueless as to how I would run Realm from a website.

**Comment by kristiandupont** [comment]
The node sdk in the professional edition includes sync. But maybe I am misunderstanding what you mean with "running realm from a website". You can use it in Node.js for your backend, in React Native for iOS and Android clients and soon via Electron for desktop apps. But not in a web based frontend at this moment.

**Comment by mehdi-cit** [comment]
Should we assume that realm database works for windows (including with electron under windows) since this issue has been closed? 
https://realm.io/news/realm-javascript-node-js-windows/?utm_source=news-list&utm_medium=email&utm_content=rmp-content
I did read yesterday on real's website that the realm-database should work now anywhere javascript can work (including windows) but I wonder why isn't that replicate it in here.. have I miss-understood something?

**Comment by fealebenpae** [comment]
The Realm Mobile Database now works on Node.js on Windows, too. Electron on any platform is a separate target for us, but we've seen reports that it's possible to run Realm on Electron if you use `electron-rebuild`, but it's not something we support officially. You can see https://github.com/realm/realm-js/issues/765 for details.
