### ISSUE TITLE
Callback gets called on addListener

### ISSUE THREAD

**Issue by Cody-G-G** [realm/realm-js#889]
When adding a listener for an object, the callback is called. This is very undesirable since my callbacks all trigger re-renders, and so since I register the listeners in the componentWillMount() method, the app freezes for a couple seconds when navigating to a screen for the first time, because of all the re-renders triggered when registering the listeners (I'm using realm-js with React Native).

Is this considered normal behavior? I am using realm 1.0.2. You can find below an example of a function that gets called in my componentWillMount() method, which triggers the callback right away:

```
    initBGLReadingListener(callback) {
        realm.objects('BGLReading').addListener((objects, changes) => {
            callback()
        });
    }
```

**Comment by istx25** [comment]
Hi @Cody-G-G. Happy to hear you could resolve the issue. If you have any other questions or need help with anything else, let us know!
