### ISSUE TITLE
Add argument checks for methods in user-methods.js

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#890]
As is nothing happens which is confusing. We should probably throw an error for an invalid number of arguments. I saw this behavior in node.

**Comment by alazier** [comment]
Hmm - it could be that we are throwing an error but it isn't showing up in the console for node.

**Comment by gritzko** [comment]
Either this https://nodejs.org/api/process.html#process_event_uncaughtexception or somebody eats it.

**Comment by alazier** [comment]
Looks like we don't do any argument checking for the user-methods implemented in js: https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L135
