### ISSUE TITLE
Value not convertible to a number

### ISSUE THREAD

**Issue by JohnDerConsulter** [realm/realm-js#897]
Hello community :) I implemented lots of good working functionality with firebase -> realm. Now i tried to edit a structure and I am running through the wildest error messages.

**What is right for sure:**

**Firebase** sends the data
Data is **converted** (e.g. Firebase has "brands" as array -> is converted to a string for Realm Schema)
The error appears when firebase **updates**
Not every firebase content has all fields (e.g. Like you can see out of Realm Schema some fields are **optional:** true)

**Fields where i maybe expect an issue:**

Maybe its not possible to say that the ReferentList is optional (or i implemented it wrong): See Realm Schema const ReferentsList

**What i tried:**

Debug before realm.create (Realm set) Result: Every data came in the right format
Checked all input values if they are int, string, ...
Hopefully someone can help me here because i got completely stuck with this issue and its necesarry to continue for my project. I want to know:

The solution why or what to do
A posibility to debug realm in a better way **Thank you in advance for your time and help :)**
**Error message:** Value not convertible to a number

I described the whole datastructure in this ticket in Stackoverflow:
http://stackoverflow.com/questions/42631219/realm-value-not-convertible-to-a-number

**Comment by fealebenpae** [comment]
Hey @JohnDerConsulter,

The terseness of the error messages when creating an object is a known issue we're tracking in https://github.com/realm/realm-js/issues/787 and hoping to resolve in the near future.

What I would do with regards to debugging is to remove properties from the Realm schema one by one until the error goes away to figure out which property is causing this. The code in StackOverflow looks fine to me, though, so at least there isn't an obvious problem I can detect :/

**Comment by gritzko** [comment]
solved, see SO http://stackoverflow.com/questions/42631219/realm-value-not-convertible-to-a-number

**Comment by JohnDerConsulter** [comment]
The error got thrown through a wrong created date object. Solution was a try / catch block to see each child of created objects. Thx for help
