### ISSUE TITLE
Keep getting error message

### ISSUE THREAD

**Issue by intelcoder** [realm/realm-js#899]
I am keep getting this errors. I have used lastest version of the realm and order version (0.14.0, 0.14.3)

```
package io.realm.react does not exist
import io.realm.react.RealmReactPackage;
error: cannot find symbol
new RealmReactPackage()
                ^
symbol: class RealmReactPackage
```

## versions 
```
OS: window 10
node: 6.9.2
npm: 3.10.9
"react": "~15.4.0",
"react-native": "^0.42.0",

```

I tried some suggestion from below link but none of this solve the problem.
[#799](https://github.com/realm/realm-js/issues/799), [#674](https://github.com/realm/realm-js/issues/674)

**Comment by gritzko** [comment]
Is this an error from Realm Java?
What are you trying to do, precisely?

**Comment by intelcoder** [comment]
I am trying to use realm for the react-native project and it throws error when it builds using command  **react-native run-android**

**Comment by intelcoder** [comment]
I am not sure which method fixed problem but it got fixed after I run react-native upgrade -> link again -> react-native run-android
