### ISSUE TITLE
README.md broken links

### ISSUE THREAD

**Issue by eduardomoroni** [realm/realm-js#904]
Hey guys, we have some broken links on [README.md](https://github.com/realm/realm-js/blob/master/README.md)

We same some on the site as well.

**Comment by ianpward** [comment]
Thanks @eduardomoroni what links are you referring to so we can track them down and fix them?

@pixelchef

**Comment by eduardomoroni** [comment]
https://realm.io/docs/react-native/latest/#models
https://realm.io/docs/react-native/latest/#queries
