### ISSUE TITLE
realm is aleady open in another context on this thread

### ISSUE THREAD

**Issue by stlemon** [realm/realm-js#906]
![default](https://cloud.githubusercontent.com/assets/21324615/23819997/f677672e-0649-11e7-8f74-550697756850.png)
version 
"realm": "^0.15.0",
"react-native": "^0.36.0"

Can you help me ? Thank you very much ! 
And if you can say Chinese ,I'll be very happy!

**Comment by kristiandupont** [comment]
Hi @stlemon, can you share some code that produces this error?

**Comment by stlemon** [comment]
I will share my code when I met this error later.

**Comment by blagoev** [comment]
I will close this issue until it is more clear it is reproducible for you. In  the mean time you can try the latest version of realm and react-native and check if your solution is triggering similar errors.

cheers
