### ISSUE TITLE
testErrorHandling() is failing on linux when testing the node sdk

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#907]
```
Failures:
1) SessionTests testErrorHandling
  Message:
    Failed: Cannot read property 'url' of undefined
  Stack:
    TypeError: Cannot read property 'url' of undefined
        at /tmp/build/node-server-sdk/public/tests/js/session-tests.js:95:77

116 specs, 1 failure
```

This is blocking ROS development.

**Comment by radu-tutueanu** [comment]
This has the same cause as #876

**Comment by fealebenpae** [comment]
@radu-tutueanu I don't think it's the same as #876 - this one's on Node.js for another test case on another property.

@alazier I don't get this when running tests locally and it doesn't seem to show up in CI. Do you get it on latest master, or is it intermittent?

**Comment by fealebenpae** [comment]
Exploring this is going to take more time as we don't have the means to test sync on Linux out of the box.
