### ISSUE TITLE
feature: Integration with React Native FlatList / SectionList

### ISSUE THREAD

**Issue by aksharpatel47** [realm/realm-js#911]
React native recently introduced the FlatList, SectionList and VirtualizedList as better alternatives to the ListView ([blogpost](https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html)).  It would be ideal to have a realm component that leverages these for better performance.

**Comment by kristiandupont** [comment]
Yes, that is a nice idea and definitely worth looking into!

**Comment by philohelp** [comment]
Actually I use FlatList with realm and it seems to work ok. Am I missing something ?

**Comment by MrHubble** [comment]
@philohelp I tried FlatList with Realm and found the performance nowhere near as good as with the Realm ListView component. I added a [shouldItemUpdate](https://facebook.github.io/react-native/docs/virtualizedlist.html#shoulditemupdate) method but still experienced poor performance.

I am basing this on using the iOS simulator. The results were blatantly worse with the FlatList for me.  Has your experience been different to this?

**Comment by Talor-A** [comment]
Is the flatlist loading all realm results into memory rather than lazy loading them?

**Comment by rpereira** [comment]
@Talor-A I believe you should use `VirtualizedList` instead because it provides more flexibility and by doing so you avoid doing `Array.from()`, which is an expensive operation if your collection has a lot of data.

**Comment by Talor-A** [comment]
@rpereira sorry for the late response but can you give a example on how to do this? `Array.from()` gets very slow after a few hundred results.

**Comment by hellomaya** [comment]
Currently by using Realm data list in FlatList will bring `VirtualizedList` warning to say the list is big, if I scroll the list fast in iOS simulator. Probably because the realm object is nested, to compare it in VirtualizedList bring negative result, by using the pure object with same data from the realm data as a list, it won't have this warning.

**Comment by Talor-A** [comment]
I got this working with a few thousand items with VirtualizedList, the performance is amazing in production builds but seriously lags when running `react-native start`. just a warning for anyone trying this.

**Comment by hellomaya** [comment]
I tried VirtualizedList, and it showed amazing memory usage down by comparing with ListView/Realm, And this warning I saw with FlatList:

> VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.

Actually wasn't serious, just happened in debug mode, in release mode the performance was good.

Here is some rough memory usage data from my test in Android device, focus on the difference between each operation, and the initial memory usage of my test app was large though, it had a 300 rows from a 3000 rows Realm table, I scroll to bottom & top for several times and record the memory usage for each:

```
- ListView/Realm
  - start: 71M
  - scroll to bottom: 123M
  - scroll to top: 133M
  - scroll to bottom: 135M
  - scroll to top: 136M
- VirtualizedList
  - start: 70M
  - scroll to bottom: 108M
  - scroll to top: 115M
  - scroll to bottom: 105M
  - scroll to top: 107M
  - scroll to bottom: 116M
  - scroll to top: 111M
  - scroll to bottom: 107M
```
Usage of VirtualizedList:

```jsx

                <VirtualizedList

                    data={ClientStore.listData}
                    renderItem={this.renderRow.bind(this)}
                    keyExtractor={(item) => item.id}
                    windowSize={11}
                >

                </VirtualizedList>
```

Test in:

- react native ^0.44.0
- realm ^1.3.1
- Nexus 5, Android 5.0.1

**Comment by fxfactorial** [comment]
I really don't see a reason for even calling `Array.from`

**Comment by brancooo1** [comment]
Can someone please give a simple idea how to update FlatList when Realm data changed?

I found only this one example, in which I found updating quite complicated:
https://github.com/realm/realm-js/tree/master/examples/ReactExample

And this stackoverflow post regarding updating when Realm changed:
https://stackoverflow.com/a/35923260

Then we have also Realm docs:
https://realm.io/docs/javascript/latest/#notifications

Let's say we did somewhere in code changed some Item within list in realm. Now we want to show that change in FlatList. I tried different solutions from mentioned stackoverflow solution and don't get updated FlatList childrens. 

Please if someone can give some sample code, would be appreciated.
I find it not good that there is no easy self explaining solution provided, even in documentation...

**Comment by fxfactorial** [comment]
@brancooo1 

```
class F extends React.Component {

  constructor(p) {
    super(p);
    this.data_source = realm.objects('FooBar');
    this.data_source.addListener(this.on_change);
  }

  componentWillUnmount() {
    this.data_source.removeListener(this.on_change);
  }

  on_change = (name, changes) => {
    this.forceUpdate();
  }

  render() {
    return (
      <FlatList
        data={this.data_source}
        />
    )
  }
}
```

**Comment by Unforgiven-wanda** [comment]
@fxfactorial  Is this still the recommended usage method?
I've seen in another SO question put the realm objects inside the state and updating the state when they change? What are the drawbacks to that in your opinion?
Basically, performance-wise, what is the best method to use?

**Comment by fxfactorial** [comment]
@Unforgiven-wanda I don't work for realm, nor do I know. I recommend you profile and figure out the best use case for yourself.

**Comment by Chris-Petty** [comment]
Force update on the component returning the would try re-render the whole FlatList no?

Wouldn't it be better to give the FlatList `extraData` prop and having rows update if extraData for that row changed?

**Comment by wilbyang** [comment]
@Talor-A you mentioned that 「 I got this working with a few thousand items with VirtualizedList, the performance is amazing in production builds 」, would you please share some snippets or example on how you make this?

**Comment by jaltin** [comment]
@Talor-A, I second @wilbyang's comment. Would be great if you could share an example of how you did this with VirtualizedList. Thx!

**Comment by Talor-A** [comment]
@jaltin @wilbyang had to dig this up because the project had been cancelled so I haven't been using realm, but here's a basic example (using SectionList not FlatList, but it should be the same concept)

```JSX

export default class SearchBenchmark extends Component {
  constructor (props) {
    super(props)
    this.getSections = this.getSections.bind(this)
  }
  componentWillMount () {
    this.items = realm.objects('Item').sorted('updatedAt')
    this.containers = realm
      .objects('Container')
      .sorted('updatedAt')
  }

  renderRow = ({ item, index }) => (
    <SearchResult item={item} key={index} size={48} />
  )
  filter (list, text) {
    if (text) list = list.filtered('title CONTAINS[c] $0', text)
    return list
  }
  getSections () {
    const { text } = this.props
    const sections = []
    const conts = this.filter(this.containers, text)
    const rooms = this.filter(this.rooms, text)

    if (this.props.showContainers) {
      if (conts.length) {
        sections.push({
          data: conts,
          key: 'Containers',
          renderItem: this.renderRow
        })
      }
    }
    if (this.props.showItems && items.length) {
      sections.push({
        data: items,
        key: 'Items',
        renderItem: this.renderRow
      })
    }
    return sections
  }
  render () {


    return (
      <View style={{ flex: 1 }}>

        <SectionList
          renderEmptySectionHeaders={false}
          keyExtractor={(item, index) => item.id}
          sections={this.getSections()}
          renderSectionHeader={({ section }) => (
            <Text bold style={{ paddingLeft: 8 }}>{section.key}</Text>
          )}
        />

      </View>
    )
  }
}
```

**Comment by zek** [comment]
Any progress on this? My FlatList never updates when data changes :/

**Comment by douglasjunior** [comment]
> Any progress on this? My FlatList never updates when data changes :/
Our solution is to handle data change events and then call `this.forceUpdate()` in the class `Component`.

**Comment by club9822** [comment]
> Any progress on this? My FlatList never updates when data changes :/
retry extraData as prop to flatlist or virtual....

**Comment by club9822** [comment]
Use extraData  flatlist prop

**Comment by club9822** [comment]
> Any progress on this? My FlatList never updates when data changes :/

add listener to your  realm js schema  and define extraData={this.state} flatlist  .
you can add listener to insert, update or delete  .check official docs

**Comment by whalemare** [comment]
List updated only on inserts. When I change item, list updates only when I wrap RealmResults into `Array.from(realmCollection)`

**Comment by kneth** [comment]
The `@realm/react` is a package utilizing React hooks. Please take a look at it.
