### ISSUE TITLE
libGCDWebServers.a not found 

### ISSUE THREAD

**Issue by zhuyifan2013** [realm/realm-js#914]
I drag the RealmReac.xcodeproj into my project and add libRealmReact.a as linked binary ,but when I build my project I got this error message.  What should I do?? 

`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/rockvr/Library/Developer/Xcode/DerivedData/Test2D-gargqltptrilykhcxvplvutfnpkh/Build/Products/Debug-iphonesimulator/libGCDWebServers.a (No such file or directory)`

**Comment by fealebenpae** [comment]
Hey @zhuyifan2013,

Why do you need to manually edit your Xcode project to add Realm? All you need to do is to run `react-native link realm` in your project after you install the realm npm package, provided the project has been created with `react-native init`.

If you cannot use the React Native CLI, then it's up to you to edit your Xcode scheme so that the RealmReact target has a dependency on the RealmJS target and the RealmJS target has a dependency on the GCDWebServer target, but that's not something we support or have documented.

**Comment by zhuyifan2013** [comment]
Hi @fealebenpae  ,
Thanks for your reply.
I'd like to introduce my scene: 
I have two native projects (one for my personal test for some special reason) used one react-native codes (js files and node_modules ,etc.). So I could not use `react-native link realm` to link realm.
What I do now is drag the `RealmReac.xcodeproj` from node_modules/realm/react-native into my project, I found it has already a dependency on the RealmJS target . But there is still has the error descried above. I want to know more about `libGCDWebServers.a` 
<img width="421" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3753079/23955864/1ca85c5c-09d6-11e7-9227-a5061e1c71c7.png">

**Comment by fealebenpae** [comment]
RealmReact.xcodeproj should include `vendor/GCDWebServer/GCDWebServer.xcodeproj` as a subproject. If you're building from the repository, you have likely not initialized git submodules.

**Comment by zhuyifan2013** [comment]
@fealebenpae  You are right !! you saved my day . Thanks very much. 
But I have a question about this : 
Why there is no error by React Native CLI , the node_modules/realm/vendor folder has no `GCDWebServer.xcodeproj` but it works well , is there some story behind `react-native link realm` ???

**Comment by fealebenpae** [comment]
If you're using the npm package it already has the GCDWebServer code in it.

**Comment by zhuyifan2013** [comment]
Thanks, I should closed this issue first. 
But I am sorry I am still curious about What is the different of  `1. react-native link realm` and `2. drag the `node_modules/realm/react-native/RealmReac.xcodeproj` into my project` ? (regardless of git clone realm-js project scene)  . Why the first has no error ? What else the `react-native link` do about `GCDWebServer ` ?
