### ISSUE TITLE
Descriptive error message trying to access Sync on Linux

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#923]
As Sync is not available in the free edition on node on linux, we should produce an error rather than just a missing sync object.

**Comment by rodrigopivi** [comment]
I use the free edition of Realm, previous to this change, my circleci build on a linux box worked fine, now it fails with `Realm.Sync is not available. Note that the developer edition of the Node.JS SDK for Realm does not include sync on Linux.`

**Comment by kristiandupont** [comment]
All the change does is throw this error when trying to access the `Sync` namespace as it's not available on Linux. Is your code doing something with `Sync` that was perhaps silently failing before?

**Comment by rodrigopivi** [comment]
Yes, that error gets thrown but is not handled, tbh i´m not doing any syncing i just have some unit tests for a react native application, that do some write and read operations. Before this change all runs well. Maybe this Sync method is being called somewhere else in the realmjs codebase by default? should i open a new issue for this?

**Comment by kristiandupont** [comment]
Do you have a stacktrace or something? If we do call sync, that's a problem but I don't know where it would be.

**Comment by rodrigopivi** [comment]
```
    Realm.Sync is not available. Note that the developer edition of the Node.JS SDK for Realm does not include sync on Linux.
      
      at Function.get (node_modules/realm/lib/extensions.js:72:23)
      at Object.<anonymous>.module.exports (node_modules/realm/lib/extensions.js:44:25)
      at Object.<anonymous> (node_modules/realm/lib/index.js:95:24)
```

**Comment by kristiandupont** [comment]
Hm, that means that the extensions are invoked twice, odd! Are you `require`ing (or `import`ing) Realm twice in the same file?

**Comment by rodrigopivi** [comment]
the problem is that at `node_modules/realm/lib/extensions.js:44:25` we access the getter method that throws the error

**Comment by smaris** [comment]
Tests run fine with jest on my local mac but on linux they won't run because of this error. I'm not using sync at all, so how can I avoid this error?

**Comment by vikkio88** [comment]
any news about this error? do you need any help?
I am having the same error with react-native and using jest
```
 FAIL  __tests__/reducers/app.test.js
  ● Test suite failed to run

    Realm.Sync is not available. Note that the developer edition of the Node.JS SDK for Realm does not include sync on Linux.
      
      at Function.get (node_modules/realm/lib/extensions.js:72:7)
      at Object.<anonymous>.module.exports (node_modules/realm/lib/extensions.js:44:20)
      at Object.<anonymous> (node_modules/realm/lib/index.js:95:24)
      at Object.<anonymous> (src/realm/index.js:1:216)
```

**Comment by blagoev** [comment]
Hi can you share a simple project reproducing this. I can't seem to get it to fail with the setup you describe.
