### ISSUE TITLE
Electron Support

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#928]
In order to properly support Electron, we need a couple of things
 - [ ] pre-gyp binaries
 - [x] Test harness (#752)
 - [ ] Customizable folder for internal realms (#818)

**Comment by mbalex99** [comment]
If you need a boilerplate check this out:

https://github.com/mbalex99/realm-electron

Just `npm install` then start the electron app. No global dependencies are needed.

**Comment by Unforgiven-wanda** [comment]
Is there any progress concerning this?

**Comment by raghuureddy** [comment]
It would be awesome if realmjs can be supported & packaged with electron app. Waiting for it. Thank you..

**Comment by mbalex99** [comment]
Hey guys! You can use Realm-js with electron! Feel free to embed it in the renderer process! Note this feature is working nicely as far as I am aware.

1. Please go ahead and play with it! List us any issues you may have.
2. This feature is experimental and in development at the moment. 
3. Realm-js local database seems to work across platforms. However, Realm-JS sync features only work MacOSX and Linux as of right now.

**Comment by adeperio** [comment]
+1 for this feature! We are releasing an offline first desktop app in April so hanging out for this!

**Comment by george-norris-salesforce** [comment]
+1

**Comment by anthonydito** [comment]
Agreed. This would be a great feature!

**Comment by mbalex99** [comment]
Hey all 

@bigfish24 published a blog post about this. [https://blog.realm.io/native-performance-electron-realm/](https://blog.realm.io/native-performance-electron-realm/)

Key take away on support:
> While Electron works great for our use in Realm Studio, we haven’t yet tested it out in other use cases and are therefore not fully ready to offer the same level of support as for our other supported products. We hope the community is interested in stepping in and help test and support this area going forward

Go and try and please make pull requests!

If you're interested here are some bare bone examples of using React + Realm + Electron:
https://github.com/realm/electron-react-samples

**Comment by risabhkumar-cc** [comment]
@mbalex99 Did you face this issue: 
`ERROR in ./node_modules/realm/lib/browser/index.js Module not found: Error: Can't resolve 'react-native' in '/Volumes/Others/Project/realm-exporter/node_modules/realm/lib/browser'.`

Please provide input @ #1060

**Comment by kneth** [comment]
As mentioned earlier, we do not support Electron. [Realm Studio](https://github.com/realm/realm-studio) is an Electron app, and you are welcome to see how we are using Realm JS and Electron together.
