### ISSUE TITLE
TypeError: utf8 is not a function

### ISSUE THREAD

**Issue by red3** [realm/realm-js#947]
I used Realm Node.js and encounted the following error:

```
/Users/herui/Develop/gitt/PlayAppStore/Server/node_modules/realm/lib/submit-analytics.js:92
    request(`https://api.mixpanel.com/track/?data=${Buffer.from(JSON.stringify(payload), 'utf8').toString('base64')}&ip=1`,
                                                           ^

TypeError: utf8 is not a function
```
Currently, I using the node v5.6.0 
And I also found the following issue: nodejs/node#772 
follow his guide, I tried  v4.5.0, and it works.

**Comment by kristiandupont** [comment]
This bug should be fixed. Are you running the latest version of Realm?

**Comment by red3** [comment]
Sorry for not good at node, and can you tell me how to ensure which version of Realm currently installed on my mac?
And after install the latest version of node v7.7.4, it works too.

**Comment by red3** [comment]
I got it, I am using v1.1.1 version.

**Comment by red3** [comment]
From now, using v1.1.1 works well, this issue should be closed.
Thanks, @kristiandupont
