### ISSUE TITLE
Help: set property values out a transaction

### ISSUE THREAD

**Issue by red3** [realm/realm-js#951]
I am trying to do follows:

```
var records = realm.objects('AppRecord')
if (records.length > 0) {
  var r = records[0];
  r.icon = 'host/xxx.png';
  console.log(r);
}
```
However, I got this error: Error: Can only set property values within a transaction.

I know this is for auto-updating feature, but I still wonder is there a way to modify a property out a transaction, cause in my business, I need to add a host string to the `icon` property and then return to restfull API service.

**Comment by red3** [comment]
Currently, I am using this:
```
  JSON.parse(JSON.stringify(r));

```
but I am worrying about its efficiency.

**Comment by blagoev** [comment]
Can you use Object.assign()
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
