### ISSUE TITLE
IOS: Unable to open a realm at path 'blah blah': make_dir() failed: Operation not permitted.

### ISSUE THREAD

**Issue by Eric0625** [realm/realm-js#955]
Hello

When I tested my app on a real iPhone, it says: Unable to open a realm at path '/var/containers/Bundle/Application/E14E2F71-E34F-466E-B56A-836A4E76BCC5/SimpleFit.app/DefaultData.realm.management': make_dir() failed: Operation not permitted.

But when I tested on the simulator, nothing wrong happened. Any clue?

The file is included in Build Phases.
![2017-04-01 2 39 54](https://cloud.githubusercontent.com/assets/18132007/24576167/409c7d44-16e9-11e7-84ee-fe7e99457bf3.png)

here is the code:
```
let dataFile = Bundle.main.url(forResource: "DefaultData", withExtension: "realm")
let config = Realm.Configuration(
            fileURL: dataFile,
            readOnly: false
        )        
let r = try! Realm(configuration: config) //that's where the error happened
```

environment: Xcode 8.2.1 (8C1002), simulator: iPhone 6s-iOS 10.2(14C89), real iPhone: iPhone 6-iOS 10.2, realm version: 2.4.4

**Comment by psmortal** [comment]
any helpful info?

**Comment by kupriknikita** [comment]
how u fix it?
