### ISSUE TITLE
Opening management realm throws

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-js#963]
I'd like to open the management realm from a Node.js script on the server like it's described in the JS docs here: https://realm.io/docs/swift/latest/#access-control

The expected result would be: the script will not crash
The result is: the script crashes

The code to reproduce:
```js
var Realm = require('realm');
const token = require('fs').readFileSync('admin_token.base64').toString()

var admin = Realm.Sync.User.adminUser(token);
admin.openManagementRealm();
```

The crash output:

```
node crash.js
Error: Unexpected user auth url:
    at User.openManagementRealm (.../realm-object-server-1.4.1/node_modules/realm/public/lib/user-methods.js:213:23)
    at Object.<anonymous> (.../realm-object-server-1.4.1/crash.js:5:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
```

**Comment by alazier** [comment]
My guess would be you can't open a management realm for the token admin user. I would try creating an admin user through the dashboard and try to use that instead.

**Comment by icanzilb** [comment]
ok, now it's more clear to me that getting an admin user object on the server side by using the token doesn't return a "real" user object, so I can't access the management realm. we had a discussion with some of the guys on the JS team and it looks like an issue that needs to be addressed one way or another so that either what you get back when using the token is a real user or when using the token you get a different object than a user object. @kristiandupont do you want to leave this issue open and track this further here before opening a new feature issue when we know how we want to solve the problem?

**Comment by alazier** [comment]
We should just make both types of users behave identically. Don't see any reason why things should behave in any other way.
