### ISSUE TITLE
Realm path: create directory

### ISSUE THREAD

**Issue by acroix** [realm/realm-js#965]
```javascript
const realm = new Realm({
      path: `myFolder/${customParameter}`,
      schema: [MySchema],
});
```

realm path does not find my directory because it doesn't exist. 
The fact is I want to create it if it does not exist.
Any advices ? Thanks

**Comment by kristiandupont** [comment]
Are you using node or react native?

**Comment by acroix** [comment]
react native

**Comment by kristiandupont** [comment]
Ok. I don't have any experience with it but it looks like [this library](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#mkdirpathstringpromise) might help you

**Comment by acroix** [comment]
Yes I just saw it after some researches, thanks ;)
