### ISSUE TITLE
Download Realm API

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#973]

**Comment by kristiandupont** [comment]
Cocoa implementation: https://github.com/realm/realm-cocoa/pull/4859

**Comment by blagoev** [comment]
A solution to this could be one of the following APIs
```Javascript
Realm.openAsync(config, callback)
Realm.open(config, callback)
```

or one of the above methods where the callback is passed as part of the config 
```Javascript
Realm.openAsync({
sync: {
    user: user,
    url: 'realm://object-server-url:9080/~/my-realm',
    downloadCompleted : (error) => { .....   }

}});

```

**Comment by kristiandupont** [comment]
The first solution seems the most aligned with the cocoa API. I think we should generally promisify all of our API's but that could be in a separate PR, it would feel wrong to do it in this one instance for now.

**Comment by blagoev** [comment]
Are we trying to be aligned with cocoa API elsewhere?
If true then "openAsync" name is better. (Although cocoa uses openAsyncWithConfig)
If not I feel "open" is better aligned with our JS api like write, create etc
