### ISSUE TITLE
Node.js write very slow

### ISSUE THREAD

**Issue by tony-cj** [realm/realm-js#978]
I have a big dataset to add to realm. The schema like this:
```
const PoiSchema = {
  name: 'Poi',
  schemaVersion: 1,
  properties: {
    name:  { type: 'string', indexed: true },
    admin_code: { type: 'string', indexed: true },
    address_info: 'string',
    latitude: 'string',
    longitude: 'string',
  }
};
```
### Process steps
-  1 bill records want to add realm database.
-  Every time I created about 50000 object for a `realm.write` action
-  The process is more and more slowly.

@blagoev @fealebenpae

**Comment by bigfish24** [comment]
Can you try it without the indexed config on `name` and `admin_code`? curious how that affects performance...

**Comment by tony-cj** [comment]
@bigfish24  If I remove the index, it will affect my local search right?
With twenty million record, if no index , I can imagine that.

**Comment by bigfish24** [comment]
Yeah just curious what it does to the initial write.

**Comment by tony-cj** [comment]
The data process is still going on. I can do a small testing after that, If you want to the report.

**Comment by istx25** [comment]
Hi @tony-cj. Yes please - a test project would be helpful. Thanks!
