### ISSUE TITLE
Crash in ios simulator

### ISSUE THREAD

**Issue by solitaire12** [realm/realm-js#979]
Using realm.js in my react-native project, it often crash without any notice in my ios simulator after add the realm module to my project.It happens frequently in several minutes.

**Comment by kristiandupont** [comment]
Hi @solitaire12 could you give us a bit more information? Does your app do anything or is it simply caused by the mere presence of the realm module? Do you have a stack trace?

**Comment by solitaire12** [comment]
it only happens in react-native debug mode

`May  4 14:50:56 MacBook-Pro cashpad[18385] <Error>: [] nw_connection_get_connected_socket_block_invoke 772 Connection has no connected handler
May  4 14:50:57 MacBook-Pro SpringBoard[1687] <Error>: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
May  4 14:50:57 MacBook-Pro com.apple.CoreSimulator.SimDevice.B3A4DDE5-2612-4A58-9235-5491374DF1BA.launchd_sim[1670] (UIKitApplication:com.***.cashpad[0xa55d][1692][18385]) <Notice>: Service exited due to Trace/BPT trap: 5
May  4 14:50:57 MacBook-Pro backboardd[1688] <Error>: [Common] Unable to get short BSD proc info for 18385: No such process
May  4 14:50:57 MacBook-Pro backboardd[1688] <Error>: [Common] Unable to get proc info for 18385: Undefined error: 0
May  4 14:50:58 MacBook-Pro assertiond[1692] <Warning>: Deleted job with label: UIKitApplication:com.***.cashpad[0xa55d][1692]
 `

**Comment by solitaire12** [comment]
fixed after updated to version 1.3.0

**Comment by cwagner22** [comment]
I have the same issue and am using realm 1.3.1.

**Comment by agersoncgps** [comment]
I am also noticing this behavior in 1.3.1. The app just quits out of the simulator with no errors or exceptions.

**Comment by cwagner22** [comment]
@agersoncgps If you find a solution please let me know, this has been driving me crazy for over one month and I'm thinking about switching to another db lib. I'm not even 100% sure this is caused by realm since there is no error log but this must be the cause.

**Comment by zachkirsch** [comment]
I am having the exact same issue (sporadic crashes with no warning and no stack trace). It began since I incorporated realm into my project.

realm 1.8.3

```
Jul 19 19:33:57 zkirsch09-mac com.apple.CoreSimulator.SimDevice.8367D761-D79E-4FCC-B37C-C267BF56A9E0.launchd_sim[12929] (UIKitApplication:com.palantir.gotham.mobile.dev[0xca0][12951][22018]): Service exited due to Trace/BPT trap: 5
Jul 19 19:33:57 zkirsch09-mac backboardd[12947]: [Common] Unable to get short BSD proc info for 22018: No such process
Jul 19 19:33:57 zkirsch09-mac backboardd[12947]: [Common] Unable to get proc info for 22018: Undefined error: 0
Jul 19 19:33:58 zkirsch09-mac assertiond[12951]: Deleted job with label: UIKitApplication:com.palantir.gotham.mobile.dev[0xca0][12951]
```

**Comment by jseverinson** [comment]
I'm also getting this issue with sporadic crashes that I can't seem to link to anything really. Sometimes they happen quickly after each other even when idle, sometimes app is running idle for hours before crashing. Like @zachkirsch I think this started to occur upon installing Realm.

The systemlog is the same every time, here are three different occurences:

```
Aug 26 13:06:48 Johns-MacBook-Pro-2 SpringBoard[54167]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Aug 26 13:06:48 Johns-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.E30DF418-3F3B-481B-9744-5F754C2553C1.launchd_sim[54150] (UIKitApplication:se.webbtrepunktnoll.minbrf[0xe5a8][54172][58448]): Service exited due to Trace/BPT trap: 5
Aug 26 13:06:48 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get short BSD proc info for 58448: No such process
Aug 26 13:06:48 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get proc info for 58448: Undefined error: 0
```

```
Aug 26 13:53:30 Johns-MacBook-Pro-2 SpringBoard[54167]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Aug 26 13:53:30 --- last message repeated 1 time ---
Aug 26 13:53:30 Johns-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.E30DF418-3F3B-481B-9744-5F754C2553C1.launchd_sim[54150] (UIKitApplication:se.webbtrepunktnoll.minbrf[0xf28c][54172][58705]): Service exited due to Trace/BPT trap: 5
Aug 26 13:53:30 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get short BSD proc info for 58705: No such process
Aug 26 13:53:30 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get proc info for 58705: Undefined error: 0
```

```
Aug 26 18:17:08 Johns-MacBook-Pro-2 SpringBoard[54167]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Aug 26 18:17:08 Johns-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.E30DF418-3F3B-481B-9744-5F754C2553C1.launchd_sim[54150] (UIKitApplication:se.webbtrepunktnoll.minbrf[0x79d5][54172][58772]): Service exited due to Trace/BPT trap: 5
Aug 26 18:17:08 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get short BSD proc info for 58772: No such process
Aug 26 18:17:08 Johns-MacBook-Pro-2 backboardd[54168]: [Common] Unable to get proc info for 58772: Undefined error: 0
```

**Comment by kristiandupont** [comment]
This is obviously very problematic. It's a bit hard to think of a debugging strategy with this little information so please give us anything you have that might help boil this down.

**Comment by cwagner22** [comment]
I've tried to get additional logs using sentry but couldn't get anything. Since the crashes are impossible to reproduce on purpose (but happen usually every less than 5-10 mins for me, only in debug mode), I don't see how we could help... Maybe a custom debug version of realm? I've paused developing my app because I lost too much time and motivation caused by that.

**Comment by cwagner22** [comment]
It might be related to the fact that having Remote Debugging enabled makes the app very slow.

**Comment by mtx62** [comment]
I'm facing the same error also, but I just want to know if this error will happen in the production?

**Comment by skizzo** [comment]
Has anybody been able to solve this?

**Comment by bmunkholm** [comment]
Most info here is really old. Please create new reproducible issues.

**Comment by cesargdm** [comment]
Dec 18 15:14:12 ---------- com.apple.CoreSimulator.SimDevice.-----------[13098] (UIKitApplication:org.reactjs.native.example.--------[0xdca7][13120][20479]) <Notice>: Service exited due to SIGTRAP | sent by exc handler[20479]

**Comment by maddie-lam** [comment]
@cesargdm getting same issue @agersoncgps can you please help here.
this log comes when i try to access public website such as faccebook from simulator in chromium browser and then google.com just then browser get suddenly closed and give this above error
