### ISSUE TITLE
node-webkit build error

### ISSUE THREAD

**Issue by hibari9** [realm/realm-js#987]
win_delay_load_hook.cc
C:\Users\zl\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(34): error C2664: 'HMODULE GetModuleHandleW(LPCWSTR)': cannot convert argument 1 from 'const char [9
]' to 'LPCWSTR' [C:\Users\zl\Desktop\nwjs-64\app\node_modules\realm\build\object-store.vcxproj]
  C:\Users\zl\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(34): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or f
  unction-style cast
C:\Users\zl\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(35): error C2664: 'HMODULE GetModuleHandleW(LPCWSTR)': cannot convert argument 1 from 'const char [7
]' to 'LPCWSTR' [C:\Users\zl\Desktop\nwjs-64\app\node_modules\realm\build\object-store.vcxproj]
  C:\Users\zl\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(35): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or f
  unction-style cast
gyp ERR! build error

**Comment by istx25** [comment]
Hi @hibari9. Thanks for reaching out. I wanted to let you know that we've received your issue but I would like to request that you edit your issue and use the template from [here](https://github.com/realm/realm-js/issues/new) as that template is designed to provide us with the information we need to help you as best as we can.

What you've provided is not enough information for us to be helpful. Cheers.

**Comment by abobab** [comment]
A fix for the error above is to update the link found in the documentation to the latest version for the replacement:
https://github.com/nwjs/nw.js/blob/nw22/tools/win_delay_load_hook.cc

No error shows up during installation, but then when trying Realm into the main html file:
`<script>const Realm = require('realm');</script>`

The following error appears:
```
Uncaught TypeError: Realm is not a constructor
    at index.html:31
```

**Comment by kristiandupont** [comment]
Sorry, we are not supporting nwjs. We might look into it at some point, but not in the immediate future.

**Comment by itwy** [comment]
@ghost did you find a solution for this? Thanks.
