### ISSUE TITLE
Unsupported Realm file format version for a preload realm

### ISSUE THREAD

**Issue by batical** [realm/realm-js#988]
Hello,

I am discovering RN and trying to convert one of my Swift app in RN more for learning purpose
I am testing on simulator right now

I am creating a preload realm with a Mac OS App I did long time ago in objective C
Using - Realm (2.6.1):
   
For information, on my swift app it is working 
- Realm (2.6.1):
- RealmSwift (2.6.1):

On my react-native app,  
- "realm": "^1.2.0", (I think it is the last version)

I copy the file in appDelegate into the Documents folder. (I remove encryption for test here, and I can open it with the last realm-browser app
The file is present in the simulator  container (Documents folder)

In my RN code, I am accessing like this
```
new Realm({
    path : "Test.realm",
    readOnly : true,
    schemaVersion: 1,
    schema : [ ...]})

```

I read that since 2.0 the file format changes. So I am wondering if the new file format is used for the realm-js 1.2 version. 

Should I downgrade my Objc version to generate a realm-js compatible format ? if yes, could you tell me which version ?

Thanks

EDIT : I downgrade my Mac App to 1.1.0 (last version before 2.0) and I got the same issue
EDIT 2 : It seems to work with 1.1.0 preload version If I remove the read-only. (seems to work because my crappy beginner JS code it not working after :p)

**Comment by istx25** [comment]
Hi @batical. Thanks for reaching out. We're happy to help! Though by reading your edit 2 message, do you still require support for this problem? If so, I'll happily get someone to look into this and if not, that's totally fine too. Let us know! Cheers. :)

**Comment by batical** [comment]
Sorry , maybe I should have close it.
I got it running, not the way as expected (same realm file for my swift / and RN app) and without the read only, but I am able to play with it, that's fine :)

thanks
