### ISSUE TITLE
Electron with realm. <Encryption not enabled>  problem

### ISSUE THREAD

**Issue by lenter85TW** [realm/realm-js#995]
hi~
i made an app with Electron, react, realm.
my OS is windows 10(x64) 

and now i meet a problem when i try to use 'encryptionKey ' option.

-------------------------------
var realm = new Realm({schema: [CarSchema, PersonSchema], encryptionKey: new Int8Array(64)});
--------------------------------

as you can see, i followed Docs.

and my electron app say "Error: Encryption not enabled at Object.<anonymous>" 

i try to find the reason for 2 days...but still i can't understand.

i use latest electron(ver.1.6.2) and realm(ver.1.2.0)

and i used 'electron-rebuild' to use realm db in Electron.

so, when i check node_modules

node_modules
    |--relam
    ------|-- compiled
    ------------|-- electron-v1.6_win32_x64_       <--- this is newly added after i use electron-rebuild.
    ------------|-- node-v48_win32_x64

if i don't use encryptionKey option, my app is working well with no problems to use relam DB.

please give me an answer how to fix it.

**Comment by kristiandupont** [comment]
Sadly, we don't yet support encryption on Windows.
