### ISSUE TITLE
Jest Tests on Linux machine failing becasue of Realm.Sync

### ISSUE THREAD

**Issue by vikkio88** [realm/realm-js#996]
Hi I am having issues with Realm on my Linux machine when I try to run jest unit tests.
All the tests fail with 
```
● Test suite failed to run

    Realm.Sync is not available. Note that the developer edition of the Node.JS SDK for Realm does not include sync on Linux.
      
      at Function.get (node_modules/realm/lib/extensions.js:72:7)
      at Object.<anonymous>.module.exports (node_modules/realm/lib/extensions.js:44:20)
      at Object.<anonymous> (node_modules/realm/lib/index.js:95:24)
      at Object.<anonymous> (src/realm/index.js:1:585)
```
I saw that the "problem" was introduced on the PR https://github.com/realm/realm-js/pull/925 referenced on the issue https://github.com/realm/realm-js/issues/923 
The problem is that I am not using Sync at all. Should not this being thrown just in case of actual usage?
Thanks a lot

## Goals
Being able to run my unit-tests for a react-native project using realmjs on a machine running Linux
## Expected results
The CI process to match what we have on the dev machine (all the tests passed)
## Actual results
all the tests fail with this error
```
● Test suite failed to run

    Realm.Sync is not available. Note that the developer edition of the Node.JS SDK for Realm does not include sync on Linux.
      
      at Function.get (node_modules/realm/lib/extensions.js:72:7)
      at Object.<anonymous>.module.exports (node_modules/realm/lib/extensions.js:44:20)
      at Object.<anonymous> (node_modules/realm/lib/index.js:95:24)
      at Object.<anonymous> (src/realm/index.js:1:585)
```
## Steps to reproduce
1. Get a Linux machine
2. Make a react-native project including react and jest
3. Use realm somewhere in your code base
4. Run a test

## Code sample that highlights the issue (full Xcode / Android Studio projects that we can compile ourselves are ideal)
No test code is using realm, just one single file
```
const realm = new Realm({path: 'app.realm', schema: [Some, Schema, Around, App]});
```
## Version of Realm/Linux
from packages.json
```
"react": "16.0.0-alpha.6",
"react-native": "0.43.4",
"realm": "^1.2.0"
```

**Comment by vikkio88** [comment]
At the moment I am making the build work with a dirty workaround.
We use Makefiles and I am basically replacing, after npm install, the extensions.js file with a version that is missing the else which does the ```throw Error```
so it works like this
```
fudge_realm:
	mv realmfixer.js node_modules/realm/lib/extensions.js
```

and the file realmfixer.js is the same as **node_modules/realm/lib/extensions.js** apart from those lines missing https://github.com/realm/realm-js/blob/master/lib/extensions.js#L69&L75

**Comment by smaris** [comment]
Will there be an option to disable sync (when you don't use it) in future release for the developer package?

**Comment by blagoev** [comment]
We have a PR that resolves this error when Sync is not used. https://github.com/realm/realm-js/pull/960
Still on node v4 the pr is not working. We will be looking more into this. 

Cheers

**Comment by blagoev** [comment]
Hi can you share a simple project reproducing this. I can't seem to get it to fail with the setup you describe.

**Comment by vikkio88** [comment]
oh thank you very much for this change, I completely forgot that I had opened this issue.
Is there a new version released of the npm package yet?

**Comment by blagoev** [comment]
there will be very soon
