### ISSUE TITLE
Compatible Realm Browser version?

### ISSUE THREAD

**Issue by tybro0103** [realm/realm-js#997]
Question: Is there a version of Realm Browser for macOS that is compatible with realm-js v1.2.0? The latest one will open the .realm file, but forces an upgrade first so I can't continue using it afterwards. All the older versions I've tried ask for an encryption key.

**Comment by blagoev** [comment]
Hi a newer version will be released soon that has this fixed. Also note that the realms should be local only. Opening synced realms is not supported.

**Comment by blagoev** [comment]
will leave this open. Close it when you had a chance to test it on your side with the newer version

**Comment by tybro0103** [comment]
@blagoev Would that be a new version of Realm Browser or a new version of realm-js that will fix? Can you update this thread when it happens?

**Comment by blagoev** [comment]
I was referring to Realm Browser. Will ping you here when it is released so you can try it out.
cheers

**Comment by blagoev** [comment]
Hey @tybro0103 you can try the latest version of Realm Browser 2.1.8

**Comment by blagoev** [comment]
Realm Browser 2.1.9 has been released you can try with that also. I assume all is working ok now. closing this issue
