### ISSUE TITLE
Unsupported Realm file format version when opening existing realm file

### ISSUE THREAD

**Issue by Damnum** [realm/realm-js#999]
I'm trying to open an existing, unencrypted realm file that I created using Realm Java Version 3.1.3.

For opening the file, I'm using the Realm React Native Version 1.2.0.

The error message is:

Error: Unable to open a realm at path '~/Library/Developer/CoreSimulator/Devices/AC535B60-6F76-446F-9B03-03BDB25E280F/data/Containers/Data/Application/A3878062-48E3-47E2-BFE0-85AB0C2F7996/Documents/data.realm': Unsupported Realm file format version.

I can open the same file with the Realm browser without problems.

Is that a compatibility issue?

**Comment by Damnum** [comment]
It was indeed a compatibility issue. I downgraded to Realm Java Version 3.0.0 and it works now.

**Comment by joshuapinter** [comment]
Another option is to upgrade your `realm` version in React Native, which is now up to 2.24.0 and will likely be using the same "version" of `.realm` file format as the Java Realm.
